- keyboard/planck/keymap_sean.c
Hey Jack,
This a pull request for my latest mapping as per your email.
Loving the planck!
Sean
> Latest custom map with lower + raise

- keyboard/planck/extended_keymaps/extended_keymap_joe.c
rearranged mouse button layout
> added mouse scroll keymapping

- keyboard/planck/keymaps/keymap_joe.c
now in standart TLK style cluster
VIM style still available in upper layer
> rearranged dedicated cursor keys

- keyboard/planck/keymaps/keymap_joe.c
> Modified numpad/tenkey layout

- keyboard/jd45/Makefile
- keyboard/jd45/backlight.c
- keyboard/jd45/config.h
- keyboard/jd45/jd45.c
- keyboard/jd45/jd45.h
- keyboard/jd45/keymaps/keymap_default.c
- keyboard/jd45/keymaps/keymap_justin.c
Hi Jack,
This is to add the support for the keyboard JD45.
Please help to review and consider merging it to your branch.
Thanks,
Justin
> added support for JD45

- keyboard/ergodox_ez/keymaps/keymap_workman_osx_mdw.c
This layout adds workman with a deadkey set to the bottom right key on the right side. I am still playing with placement of the cmd, ctrl, and option keys since this is specifically for a mac. Even though its going to change, probably worth merging due to its use of macros to switch layouts, something I haven't seen anyone else do in any layout. in fact none of the things I tried for the first few days would work but this seems to do the trick.
> first attempt at a working workman layout for the ergodoxez

- keyboard/ergodox_ez/README.md
Edited filename to remove plural case in example so that prefix is
correctly parsed in step 6.
> Small change to filename spelling in README

- keyboard/planck/keymaps/keymap_gabriel.c
Hi Jack,
I fixed the faulty fn layer and improved the location of a few special characters. Overall the layout is now even closer to the standard Mac layout.
Thanks,
Gabriel
> Fix for faulty fn layer

- keyboard/ergodox_ez/README.md
Replaces #64 
In lieu of merging, just reopened with the new wording.
> Fix homebrew references

- keyboard/planck/keymaps/mollat.c
Hi Jack,
here, as I announced some time ago, my quite complex keymap for 'german vi editor using programmers'... ;)
I hope I did the 'pull' request right (never did this before...)
Regards, Andreas
> add mollat keymap

- keyboard/atreus/Makefile
- keyboard/atreus/README.md
- keyboard/atreus/atreus.c
- keyboard/atreus/atreus.h
- keyboard/atreus/config.h
- keyboard/atreus/keymaps/keymap_default.c
Add support for the Teensy2 hand-wired Atreus with the default layout.
/cc @technomancy
> Add Teensy2 Atreus support

- keyboard/atreus/README.md
Note requested in https://github.com/jackhumbert/qmk_firmware/pull/115
@technomancy do you think this is enough?
I could rename the directory to `atreus_teensy` or similar, so it's clear without looking at the readme.
> Clarify Atreus support

- quantum/keymap_common.c
> Use boolean AND instead of bitwise (possible typo)

- .gitignore
Ignore Eclipse configuration files to make sure they will never get committed.
> Add Eclipse settings files to .gitignore

- quantum/template/template.h
Credit for finding the issue goes to /u/n0bs on Reddit. https://www.reddit.com/r/olkb/comments/48vdwr/making_quark_hex_file/d0ne9it
> Fix building new projects

- BUILD_GUIDE.md
> Added Windows and Linux instructions to BUILD_GUIDE.md

- keyboard/planck/common_keymaps/keymap_mitch.c
Here is my current layout, Russ wanted to see it.
> First keyboard layout

- keyboard/planck/CYGWIN_GUIDE.md
More corrections and additional missing dependencies. I hope someone else is finding this useful.
> Cygwin Based Users Guide v0.6 -fixes to dfu-programmer build

- keyboard/Bantam44/Bantam44.c
- keyboard/Bantam44/Bantam44.h
- keyboard/Bantam44/Makefile
- keyboard/Bantam44/README.md
- keyboard/Bantam44/config.h
- keyboard/Bantam44/keymaps/default.c
Project folders has everything configured for Teensy and includes default keymap.
> Added project folder for Bantam-44

- keyboard/Bantam44/Bantam44.c
- keyboard/Bantam44/Bantam44.h
Updating to fix broken files after pull #190
> Edited Bantam44 to work with jackhumbert/qmk_firmware pull #190

- 1-setup-path-win.bat
Drastically rewrote the path script to handle Explorer's stubborn grasp of EnvVars. Tested on Win7.
> Fixed Setup Script

- 2-setup-environment-win.bat
Added check for the MinGW directory. Fixed a bug with script exiting out of a CMD window. Fixed a bug with script dropping user into MinGW directory. Fixed a bug with RD not deleting temp. Fixed a bug with PNPUtil.exe not being present in the path.
> Added Error Checking to 2nd Setup Script

- keyboard/planck/keymaps/bone2planck.c
My Attempt at adapting the Bone2 layout with Neo2 navigation cluster & number block to the Planck.
Very much a WIP, will most likely start tweaking further once my Planck kit has dropped
> Bone2 Layout adptation for Planck

- quantum/led.c
remove conflict with user defined led_set
> __attribute__ ((weak)) added to led_set

- keyboard/atomic/keymaps/pvc/keymap.c
- keyboard/hhkb/rn42/rn42_task.c
- keyboard/planck/keymaps/default/keymap.c
- keyboard/preonic/keymaps/default/keymap.c
- quantum/audio/audio.c
- quantum/keymap_common.c
- quantum/rgblight.c
- quantum/rgblight.h
- tmk_core/common/avr/eeconfig.c
- tmk_core/common/backlight.c
- tmk_core/common/bootmagic.c
- tmk_core/common/eeconfig.h
- tmk_core/protocol/lufa/LUFA-git/Bootloaders/CDC/BootloaderCDC.c
- tmk_core/protocol/lufa/LUFA-git/Bootloaders/DFU/BootloaderDFU.c
I made a similar pull request to @tmk, but I'm afraid that the changes will take too long to trickle all they way down here.
> Update functions used to write to EEPROM

- quantum/tools/README.md
Seems that this is a typo. When I used the hex file it worked so presuming that means it's right ;)
> Referencing the hex file

- quantum/matrix.c
- tmk_core/common/keyboard.c
I failed to see that the scopes of these variables could be limited.
> Clean up #343's code

- keyboard/ergodox_ez/readme.md
- tmk_core/rules.mk
These make flashing easier :-)
> Update to Makefile an ergodox readme

- .gitignore
- 1-setup-path-win.bat
- BUILD_GUIDE.md
- util/ELEVATE_LICENSE.md
- util/add-paths.bat
Finally pushing this fix in a mergable form. 
/u/IBNobody might be interested.
> Stop explorer.exe from being started with admin privilieges

- doc/HAND_WIRE.md
- Fix a broken link
- Fix an incoherent sentence (my fault)
> Fix hand wiring guide

- tmk_core/protocol/lufa/descriptor.c
related #312
from https://github.com/jackhumbert/qmk_firmware/issues/312#issuecomment-223822020 👏
> fix HID_RI_LOGICAL_MAXIMUM value

- keyboards/kc60/keymaps/stanleylai/Makefile
- keyboards/kc60/keymaps/wigguno/Makefile
- keyboards/kc60/keymaps/wigguno/keymap.c
- keyboards/kc60/keymaps/wigguno/readme.md
- keyboards/kc60/keymaps/ws2812/Makefile
As title says. 
I've also changed the other keymaps' makefiles to reference the master qmk makefile instead of the keyboard makefile as it wasn't compiling.
> Adding my keymap to KC60

- quantum/matrix.c
- tmk_core/common/avr/suspend.c
- tmk_core/common/bootmagic.c
- tmk_core/common/keyboard.c
- tmk_core/common/matrix.h
See the end of #343 for the full discussion.
> reverts #343 for the most part

- keyboards/infinity_ergodox/MEMO.txt
- keyboards/infinity_ergodox/Makefile
- keyboards/infinity_ergodox/bootloader_defs.h
- keyboards/infinity_ergodox/chconf.h
- keyboards/infinity_ergodox/config.h
- keyboards/infinity_ergodox/halconf.h
- keyboards/infinity_ergodox/infinity_ergodox.c
- keyboards/infinity_ergodox/infinity_ergodox.h
- keyboards/infinity_ergodox/keymaps/default/keymap.c
- keyboards/infinity_ergodox/led.c
- keyboards/infinity_ergodox/matrix.c
- keyboards/infinity_ergodox/mcuconf.h
- tmk_core/avr.mk
- tmk_core/chibios.mk
- tmk_core/rules.mk
This is a working version of one side of the Infinity Ergodox. I just flashed the firmware and tried it :)
The next step is to add the serial protocol, so that both hands can be used. 
Currently it's located in it's own keyboard folder, but at some point, I we might want to try to merge it with the Ergodox EZ, as a subproject.
> Add infinity ergodox

- keyboards/alps64/readme.md
- keyboards/clueboard/readme.md
- keyboards/cluepad/readme.md
- keyboards/ergodox_ez/keymaps/romanzolotarev-norman-plover-osx-hjkl/readme.md
- keyboards/jd45/readme.md
- keyboards/phantom/readme.md
- keyboards/satan/Makefile
- keyboards/satan/keymaps/sethbc/Makefile
- keyboards/satan/readme.md
- readme.md
I'm dropping a couple of incremental improvements i've made into this pull request. Thus far:
1. Doc cleanups
2. satan default DIP switch change
3. personal satan keymap changes
May add several more as I run through.  If there's anything truly substantive i'll branch and make a new PR.
> Misc. fixes from sethbc

- quantum/keymap_extras/keymap_bepo.h
Hi, I found some errors in the bepo mapping file while doing my keymap, so here's the fix for them if you're interested.
> Fix some errors in bepo mapping

- readme.md
> Added music recording/playing doc

- readme.md
Added (simple) Tap Dance example implementation steps.
> Added Tap Dance Example

- keyboards/ergodox_ez/keymaps/colemak_osx_pc_no/keymap.c
this fixes a build error (take a look at the travis log, it's starting to look like a hot mess).
> update NO_AMP to NO_AMPR

- keyboards/planck/keymaps/bone2planck/keymap.c
fixed broken build from travis
> Fix bone2planck build

- keyboards/planck/keymaps/callum/Makefile
- keyboards/planck/keymaps/callum/keymap.c
- keyboards/planck/keymaps/callum/readme.md
The more the merrier right? :)
Includes a `readme.md` explaining my design decisions. Might be useful for other people designing their own layouts.
> Pull request to include my keymap if you want it!

- keyboards/preonic/keymaps/0xdec/Makefile
- keyboards/preonic/keymaps/0xdec/README.md
- keyboards/preonic/keymaps/0xdec/config.h
- keyboards/preonic/keymaps/0xdec/keymap.c
An ergonomically optimized Colemak keymap for the grid-layout Preonic
> 0xdec Preonic keymap

- quantum/audio/song_list.h
The ringtone from the _In Like Flint_ (1967) movie.
> Add IN_LIKE_FLINT song

- doc/basic_how_keyboards_work.md
This comes from the discussion on #520
> feature: add basic doc about how a keyboard works on USB

- quantum/rgblight.c
Mostly just fixing tabs and whitespace, plus a small refactor to sethsv()
> Clean up formatting & tiny refactor in rgblight.c

- quantum/keymap_extras/keymap_cyrillic.h
These Cyrillic characters should cover many/all languages that use this orthography.
> Add keymap_cyrillic.h, lots of cyrillic characters

- quantum/keymap_extras/keymap_russian.h
- quantum/keymap_extras/keymap_unicode_cyrillic.h
And also renamed CY_RUBLE and CY_NUMERO in to CY_RUBL and CY_NMRO, the names are shorter and better.
> Added file for software implementation of Russian, gave keymap_cyrillic.h a better name.

- keyboards/preonic/keymaps/kinesis/Makefile
- keyboards/preonic/keymaps/kinesis/config.h
- keyboards/preonic/keymaps/kinesis/keymap.c
- keyboards/preonic/keymaps/kinesis/readme.md
This is a keymap similar to the Kinesis Advantage for the Atomic and the Preonic
> Adds keymap based on Kinesis advantage

- quantum/dynamic_macro.h
- readme.md
These are my macros I mentioned on Reddit some time ago [link](https://www.reddit.com/r/olkb/comments/4siwmz/got_my_planck_up_and_running_now_what/d59pg6x). They have been through a major refactoring, cleanup and bugfixing since. I'm not sure if I did put the header in the right directory, so please move it if appropriate.
Should I also add my keymap as an example of the dynamic macro usage?
> Implement the dynamic macros that are recorded in runtime

- keyboards/planck/keymaps/circuit/keymap.c
> planck/circuit: Update after the latest tap-dance change

- keyboards/tv44/keymaps/default/keymap.c
Updating with proper Dvorak layout.
> Fixing Dvorak

- keyboards/kitten_paw/Makefile
- keyboards/kitten_paw/config.h
- keyboards/kitten_paw/keymaps/default/keymap.c
- keyboards/kitten_paw/kitten_paw.c
- keyboards/kitten_paw/kitten_paw.h
- keyboards/kitten_paw/led.c
- keyboards/kitten_paw/matrix.c
- keyboards/kitten_paw/readme.md
- keyboards/readme.md
This adds support for the 2016 revision of the [Kitten Paw](http://bathroomepiphanies.com/controllers/)  replacement controller by [Bathroom Epiphanies](https://github.com/BathroomEpiphanies).
> Added support for the Kitten Paw controller

- quantum/process_keycode/process_unicode.c
- quantum/process_keycode/process_unicode.h
See https://github.com/jackhumbert/qmk_firmware/issues/672
> Add method to set Unicode input key for ISO 14755

- keyboards/ergodox/readme.md
I spent some time struggling with updating my Ez keymap to work with the Infinity, and I hoped my notes could help someone else, even though I haven't quite gotten it finished.  This took me a couple of hours to figure all of it out.
> Adding nicer Infinity build instructions.

- keyboards/tv44/keymaps/jeebak/Makefile
- keyboards/tv44/keymaps/jeebak/config.h
- keyboards/tv44/keymaps/jeebak/keymap.c
- keyboards/tv44/keymaps/jeebak/readme.md
This one, I don't have yet, but I did join the MiniVan Drop... so planning ahead :). The keymap matrix in `config.h` was based off of the 2 example keymaps for this keyboard. I did a bunch of `diff -r` and `vim -d`-ing with my JD45 port, and it builds w/ no errors, so it should be OK. What could possibly go wrong?!
> Port jeebak's Planck/JD45 keymap to TV44

- keyboards/readme.md
I hope the added descriptions are ok.
I also changed the dashes to be consistent.
> Update list of community keyboards

- .travis.yml
After the Unit Test changes, there were errors about the GH_TOKEN, on the master branch too.
This attempts to fix that, but I have no idea if it will work or not.
> Fix the .travis.yml so that GH_TOKEN works properly

- keyboards/planck/keymaps/jhenahan/Makefile
- keyboards/planck/keymaps/jhenahan/config.h
- keyboards/planck/keymaps/jhenahan/keymap.c
- keyboards/planck/keymaps/jhenahan/readme.md
NKRO by default, Workman Dead base layout, KWM interaction (likely adaptable to other window managers without much fuss), Plover with a toggle switch. The README should explain the rest.
> jhenahan Planck layout

- keyboards/planck/keymaps/sgoodwin/Makefile
- keyboards/planck/keymaps/sgoodwin/keymap.c
- keyboards/planck/keymaps/sgoodwin/readme.md
Does nifty things like shift/enter and hyper and removes stuff I never use.
> Add my keymap.

- tmk_core/readme.md
32byte report = 1byte modifiers + 31byte keys
31byte * 8bit * 1key/bit = 248keys
> fix number of NKRO keys

- keyboards/kc60/config.h
I've tried some value with my KC60 and 5 levels seems to be the good value.
> Updated backlight levels for KC60

- quantum/process_keycode/process_tap_dance.c
- quantum/process_keycode/process_tap_dance.h
- readme.md
i will soon push my own keymap where i am using that.
> [tap dance] restore each_tap functionality

- keyboards/atreus/keymaps/jeremy/keymap.c
- keyboards/atreus/keymaps/jeremy/readme.md
This is my personal layout that I've been using/tuning for about 1 week now. I am new to QMK and the Atreus/ErgoDox keyboards so this is a work in progress, but changes have slowed way down. I think it is interesting in that it breaks the mold with Symbols, Cursor and Function layers.
> Added Jeremy’s Atreus Layout

- keyboards/planck/keymaps/callum/keymap.c
Sorry for the second PR this week Jack! Just discovered the modifier functions that can be stuck straight in the keymap definitions. Great stuff!
Thanks for being awesome 👍
> Made some simplifications leveraging the LALT(), LGUI(), and S() functions.

- keyboards/cluecard/keymaps/default/readme.md
- keyboards/cluecard/keymaps/rgb_effects/Makefile
- keyboards/cluecard/keymaps/rgb_effects/config.h
- keyboards/cluecard/keymaps/rgb_effects/keymap.c
- keyboards/cluecard/keymaps/rgb_effects/readme.md
- quantum/rgblight.c
- quantum/rgblight.h
Also made the RGB intervals tunable, by defining them as weak symbols.
> Add a Cluecard keymap for testing the RGB effects

- keyboards/planck/keymaps/vifon/Makefile
- keyboards/planck/keymaps/vifon/config.h
- keyboards/planck/keymaps/vifon/keymap.c
I'm adding my personal keymap since it should be a good reference for the dynamic macros setup.
> New Planck keymap: vifon

- quantum/keymap.h
- readme.md
Quite simple, not much changes.
This is my first pull request, please let me know if i should do this differently
> Altgr quick combination and updated readme

- keyboards/ergodox/keymaps/pvinis/Changelog.md
- keyboards/ergodox/keymaps/pvinis/Makefile
- keyboards/ergodox/keymaps/pvinis/Readme.md
- keyboards/ergodox/keymaps/pvinis/keymap.c
> pvinis keymap

- keyboards/pegasushoof/Makefile
- keyboards/pegasushoof/README.md
- keyboards/pegasushoof/config.h
- keyboards/pegasushoof/keymaps/blowrak/Makefile
- keyboards/pegasushoof/keymaps/blowrak/keymap.c
- keyboards/pegasushoof/keymaps/default/Makefile
- keyboards/pegasushoof/keymaps/default/keymap.c
- keyboards/pegasushoof/matrix.c
- keyboards/pegasushoof/pegasushoof.c
- keyboards/pegasushoof/pegasushoof.h
- keyboards/pegasushoof/rules.mk
Been using this for the past 6 months and it works really well, a pair of extra eyes would be nice though.
> Support the Pegasus Hoof controller.

- quantum/process_keycode/process_unicode.c
- quantum/process_keycode/process_unicode.h
Fix https://github.com/jackhumbert/qmk_firmware/issues/837 by using WinCompose (https://github.com/samhocevar/wincompose)
> Unicode WinCompose input method

- keyboards/planck/keymaps/callum/keymap.c
Workaround for some issues I was having with chaining S, LALT etc. Will create an issue with more details later.
> tiny keymap change

- Makefile
This will fix the situation where the commandline gets too long when there are many keyboards and keymaps.
Fixes #828
> Run each sumbmake in a separate shell

- quantum/keymap_extras/keymap_br_abnt2.h
This adds the scan codes for people using the Brazilian ABNT2 keyboard layout
See also: #147
> Add brazilian ABNT2 keymap

- keyboards/satan/keymaps/sethbc/keymap.c
Cleaned up the keymap to make a little more mac/thumb friendly.
> update sethbc keymap

- keyboards/ergodox/keymaps/sethbc/Makefile
- keyboards/ergodox/keymaps/sethbc/keymap.c
- keyboards/ergodox/keymaps/sethbc/readme.md
> update sethbc ergodox keymap

- tmk_core/protocol/lufa/lufa.c
(this is part of a series relating to #912; it is stacked on top of #915, so there are apparently duplicate commits here due to the lack of stacked diff review support on GH)
There are now 3 potential locations to send HID reports:
1. USB
2. The bluefruit easy key
3. Adafruit BLE
Generally speaking, if USB is connected then we should prefer to
send the reports there; it is generally the best channel for this.
The bluefruit module has no feedback about bluetooth connectivity
so the code must speculatively send reports over both USB and bluetooth.
The BLE module has connectivity feedback.  In general we want to
prefer to send HID reports over USB while connected there, even
if BLE is connected.  Except that it is convenient to force them
over BLE while testing the implementation.
This …
> Connect the adafruit ble code to the lufa main loop

- keyboards/converter/Makefile
- keyboards/converter/converter.c
- keyboards/converter/converter.h
- keyboards/converter/ibm_terminal/Makefile
- keyboards/converter/ibm_terminal/README
- keyboards/converter/ibm_terminal/config.h
- keyboards/converter/ibm_terminal/ibm_terminal.c
- keyboards/converter/ibm_terminal/ibm_terminal.h
- keyboards/converter/ibm_terminal/keymaps/default/Makefile
- keyboards/converter/ibm_terminal/keymaps/default/config.h
- keyboards/converter/ibm_terminal/keymaps/default/keymap.c
- keyboards/converter/ibm_terminal/keymaps/priyadi/Makefile
- keyboards/converter/ibm_terminal/keymaps/priyadi/config.h
- keyboards/converter/ibm_terminal/keymaps/priyadi/keymap.c
- keyboards/converter/ibm_terminal/led.c
- keyboards/converter/ibm_terminal/matrix.c
- keyboards/converter/ibm_terminal/rules.mk
> IBM Terminal M-122 converter support

- Makefile
Remove an extra parenthesis and clean up the SKIP_GIT code
> Fix makefile on cygwin

- keyboards/planck/keymaps/jeremy-dev/keymap.c
- keyboards/planck/keymaps/jeremy-dev/readme.md
This is a keymap setup for the Planck specifically for developers. I believe it offers some unique attributes that others may like, steal for their own or maybe use this one directly.
> Added Jeremy’s developers keymap for the Planck

- keyboards/ergodox/keymaps/deadcyclo/keymap.c
- keyboards/ergodox/keymaps/deadcyclo/readme.md
I know I promised to pull request this way back when the first ergodox ez were sent out and I got mine, but it completely slipped my mind. So here it is, updated to the new project structure.
> Added the deadcyclo layout

- keyboards/ergodox/keymaps/bryan/keymap.c
> Added Bryan's keymap

- keyboards/planck/keymaps/callum/keymap.c
- keyboards/planck/keymaps/callum/readme.md
Removed some experiments that I wasn't using. Updated readme.
> simplified my keymap

- keyboards/preonic/keymaps/smt/Makefile
- keyboards/preonic/keymaps/smt/keymap.c
- keyboards/preonic/keymaps/smt/readme.md
> Add smt's keymap for Preonic

- keyboards/ergodox/keymaps/ordinary/keymap.c
- keyboards/ergodox/keymaps/robot_test_layout/keymap.c
- quantum/config_common.h
- quantum/light_ws2812.c
- quantum/matrix.c
- quantum/template/config.h
- tmk_core/common/keyboard.c
- tmk_core/common/matrix.h
- tmk_core/common/report.h
These changes mostly reduce build warnings and clean up minor things.
> Minor cleanup

- quantum/quantum.c
You should be able to define your `BACKLIGHT_PIN` as any pin now, along with `BACKLIGHT_ON_STATE` to either 0 (low) or 1 (high) depending on your hardware set-up. This should address #1061.
> Open backlight functionality to all ports

- keyboards/ergodox/keymaps/dvorak_emacs_software/keymap.c
- keyboards/ergodox/keymaps/dvorak_emacs_software/readme.md
Same layout as dvorak_emacs -- but using software layout instead of firmware layout
> Add dvorak_emacs_software layout for ergodox

- keyboards/planck/keymaps/callum/keymap.c
- keyboards/planck/keymaps/callum/readme.md
> keymap update

- keyboards/planck/keymaps/callum/keymap.c
- keyboards/planck/keymaps/callum/readme.md
filled out unused keys with more hotkeys
> moar hotkeys

- keyboards/ergodox/keymaps/german-lukas/README.md
- keyboards/ergodox/keymaps/german-lukas/keymap.c
- quantum/quantum_keycodes.h
I added my keymap called german-lukas for the ergodox-ez.
Also I added a key for pressing the left control and the left alt key at once because Linux makes a difference between pressing AltGr and pressing control + alt.
> keymap german lukas

- keyboards/clueboard/keymaps/colemak/keymap.c
My Colemak layout. Function layer includes some movement keys around the home row.
> Colemak layout for Clueboard

- .gitignore
- keyboards/tada68/keymaps/default/keymap.c
- keyboards/tada68/keymaps/default/readme.md
- keyboards/tada68/readme.md
- Add the default function layer mappings for the tada68.
- Provide flashing instructions in the tada68 readme.
> Update readme and default layout for TADA68

- doc/keymap.md
- tmk_core/common/action_tapping.c
> Add TAPPING_FORCE_HOLD to regulate behaviour

- keyboards/planck/keymaps/callum/keymap.c
> changed hotkey cluster to acommodate awkward software

- keyboards/planck/keymaps/callum/keymap.c
another minor change... sorry!
> changed hotkey cluster to accomodate awkward software... again

- keyboards/handwired/kbod/Makefile
- keyboards/handwired/kbod/config.h
- keyboards/handwired/kbod/kbod.c
- keyboards/handwired/kbod/kbod.h
- keyboards/handwired/kbod/keymaps/default/Makefile
- keyboards/handwired/kbod/keymaps/default/config.h
- keyboards/handwired/kbod/keymaps/default/keymap.c
- keyboards/handwired/kbod/keymaps/default/readme.md
- keyboards/handwired/kbod/readme.md
- keyboards/handwired/kbod/rules.mk
Hello, I ported my [60% keyboard](https://github.com/fudanchii/keyboard_of_disapproval) to qmk, and I just love how easy the effort was. Now I'm wondering if it's okay to include this back to upstream.
Thanks for the wonderful project!
> Handwired 60% keyboard with 8x8 matrix

- keyboards/miuni32/Makefile
- keyboards/miuni32/config.h
- keyboards/miuni32/keymaps/default/Makefile
- keyboards/miuni32/keymaps/default/config.h
- keyboards/miuni32/keymaps/default/keymap.c
- keyboards/miuni32/keymaps/default/readme.md
- keyboards/miuni32/miuni32.c
- keyboards/miuni32/miuni32.h
- keyboards/miuni32/readme.md
- keyboards/miuni32/rules.mk
Miuni32 is an ortholinear 30% keyboard. Please visit www.bigtuna.io for more info.
> Add Bigtuna.io Miuni32 

- keyboards/amjpad/amjpad.h
- keyboards/amjpad/keymaps/max/keymap.c
For use with grid layout pads.
> Adding Maximized Keymap

- keyboards/planck/keymaps/lae3/Makefile
- keyboards/planck/keymaps/lae3/config.h
- keyboards/planck/keymaps/lae3/keymap.c
- keyboards/planck/keymaps/lae3/readme.md
Keymap based around mode switching for adding extra functionality. Layout is based around my personal programming preferences and easily playing most games even if they need arrow keys or numpad.
> Added lae3 keymap

- keyboards/xd60/readme.md
i guess that fixes the image link - currently its broken
> lowercase .jpg

- tmk_core/common/action.c
See https://github.com/qmk/qmk_firmware/issues/950
> Call led_set for layer action events to update LEDs on layer changes

- keyboards/satan/keymaps/colemak/Makefile
- keyboards/satan/keymaps/colemak/keymap.c
- keyboards/satan/keymaps/colemak/readme.md
My Colemak layout for the satan. Function layer includes some navigation and media keys.
> Colemak layout for GH60 Satan

- keyboards/ergodox/keymaps/dvorak_programmer_swe/keymap.c
- keyboards/ergodox/keymaps/dvorak_programmer_swe/readme.md
There wasn't a dvorak layout with the special swedish characters åäö so I created one.
It has also a developer layout for common keywords that can speed up your coding.
> Created a dvorak keymap for Swedish developers using Visual Studio

- keyboards/ergodox/config.h
- keyboards/ergodox/ez/config.h
Also tweaks mousekey time to max
> Adds prevent stuck modifiers to EZ default

- .gitignore
- docs/Build-Environment-Setup.md
- util/activate_wsl.sh
- util/drivers.txt
- util/wsl_install.sh
Also update the Windows 10 instructions.
> Add script for setting up Windows Subsystem for Linux

- tmk_core/common/action.c
@Dbroqua will this still work for your trackpoint? @ezuk this should fix #1339.
> Re-enable mouse buttons from #1327

- tmk_core/protocol/lufa/adafruit_ble.cpp
- tmk_core/protocol/lufa/adafruit_ble.h
- tmk_core/protocol/lufa/lufa.c
Merged from relevant parts of https://github.com/wez/qmk_firmware/commit/73b7a1447041f3dde4caf07aaf608696974f9f9a issue: https://github.com/qmk/qmk_firmware/issues/912#issuecomment-299674183
> Adafruit Feather BLE / BLE Friend mouse buttons support

- keyboards/planck/keymaps/dshields/Makefile
- keyboards/planck/keymaps/dshields/config.h
only affects planck/dshields keymap
> Tweak reported power consumption to work with iOS

- docs/Keycodes.md
- docs/keycode.txt
Yes, with all three Ls
At least it doesn't have a random K anymore lol
> SCKLCK is now SCROLLLOCK

- .gitmodules
The submodules now point to the QMK Github.
Also update uGfx to version 2.7, with some custom fixes.
Fixes #1312, by removing duplicate const declarations
The other fixes are for the upcoming emulator support.
> Update uGFX and Chibios submodules + fixes

- keyboards/clueboard/keymaps/magicmonty/Makefile
- keyboards/clueboard/keymaps/magicmonty/config.h
- keyboards/clueboard/keymaps/magicmonty/keymap.c
- keyboards/clueboard/keymaps/magicmonty/readme.md
Cleanup of Keymap
+ Changed CapsLock to Esc when tapped, Fn when held
+ Changed Tab to Tab when tapped, Hyper when held
+ Changed Shift keys to Space caded shift parentheses
+ Updated README
> Added HyperTab and Ctrl/Fn as well as Space cadet parens

- keyboards/planck/keymaps/dshields/config.h
- keyboards/planck/keymaps/dshields/keymap.c
* tweaks to tap dance keys
* tidy up code
* save a few bytes
> Minor updates to planck/keymaps/dshields

- keyboards/kmac/keymaps/default/Makefile
- keyboards/kmac/keymaps/default/keymap.c
- keyboards/kmac/keymaps/default/readme.md
- keyboards/kmac/keymaps/winkeyless/Makefile
- keyboards/kmac/keymaps/winkeyless/keymap.c
- keyboards/kmac/keymaps/winkeyless/readme.md
- keyboards/kmac/kmac.c
- keyboards/kmac/matrix.c
- keyboards/kmac/rules.mk
Mostly formatting fixes but there are also a few documentation corrections and some default configuration tweaks.
> KMAC fixes

- keyboards/s65_x/keymaps/default/keymap.c
- keyboards/s65_x/keymaps/iso/keymap.c
Add LED control to the BL layer for toggling backlight and changing brightness
Map Function layer home and end to < and > as was intended.
> S65-X Fixes Part 3

- keyboards/planck/keymaps/chance/Makefile
- keyboards/planck/keymaps/chance/config.h
- keyboards/planck/keymaps/chance/keymap.c
Added personal keymap with underglow, right shift, numpad, and bright hidden behind raise/lower.
> Adding a planck keymap

- keyboards/planck/keymaps/brandon/Makefile
- keyboards/planck/keymaps/brandon/config.h
- keyboards/planck/keymaps/brandon/keymap.c
layers including qwerty, colemak, navigation, and gui layers.
I also was playing around with dancing tap keys.
> This is a complete redo of my keymap. It includes several

- keyboards/ergodox/ez/ez.c
- keyboards/gh60/gh60.c
- keyboards/pegasushoof/pegasushoof.c
- keyboards/xd60/xd60.c
> Fix undefined reference errors with avr-gcc 7.1

- keyboards/sixkeyboard/config.h
- keyboards/sixkeyboard/keymaps/default/keymap.c
- keyboards/sixkeyboard/matrix.c
Did this a while ago - kept forgetting to get this merged.
> Adds debouncing to sixkeyboard

- drivers/avr/ssd1306.c
- drivers/avr/ssd1306.h
- keyboards/hadron/keymaps/default/config.h
- keyboards/hadron/keymaps/default/keymap.c
- keyboards/hadron/keymaps/side_numpad/config.h
- keyboards/hadron/keymaps/side_numpad/keymap.c
- keyboards/lets_split/keymaps/OLED_sample/config.h
- keyboards/lets_split/keymaps/OLED_sample/keymap.c
removed task_user from SSD1306.c all together, was not rendering anything with it in both keymap and SSD1305.c
> fix implementation issues from SSD1306 clean up, added rotation

- docs/modding_your_keyboard.md
- keyboards/kc60/keymaps/workman-dead/keymap.c
- keyboards/planck/keymaps/default/config.h
- keyboards/planck/keymaps/default/keymap.c
- keyboards/preonic/keymaps/default/config.h
- keyboards/preonic/keymaps/default/keymap.c
- quantum/audio/audio.c
- quantum/audio/audio.h
- quantum/audio/musical_notes.h
- quantum/audio/song_list.h
- quantum/config_common.h
- quantum/process_keycode/process_audio.c
- quantum/process_keycode/process_music.c
- quantum/process_keycode/process_music.h
- quantum/quantum.c
- quantum/quantum.h
- quantum/quantum_keycodes.h
A couple different audio features will be embedded through-out QMK, and the songs can be over-ridden/disabled in the `config.h` file, rather than `keymap.c`.
This will also remove some of the extra `_user` functions that weren't being used (and are mostly unneeded).
Planck and Preonic keymaps are being slimmed down a bit for when they get copied 2000 times :) (remaining hopeful)
> Updates to the audio/song implementation

- keyboards/kc60/keymaps/mechmerlin/keymap.c
- keyboards/kc60/keymaps/mechmerlin/readme.md
New keymaps that are inspired by the KBP V60 and WKL FaceW layouts. Also adds function layer for pseudo HHKB layout.
> KC60 new keymaps 

- keyboards/xd60/keymaps/BASE/keymap.c
- keyboards/xd60/keymaps/BASE/readme.md
- keyboards/xd60/keymaps/base/keymap.c
- keyboards/xd60/keymaps/base/readme.md
I feel like this version of the firmware could help those with a different layout than is currently here
> Adding another layout

- keyboards/satan/keymaps/poker/keymap.c
Just pushing back a minor comment fix in a file I was reading.
> Fixed a layout comment to match layout array

- book.json
- docs/documentation_best_practices.md
- docs/faq.md
- docs/glossary.md
We somehow missed this with the merge of #1449.
> Updates some remaining doc stuff

- keyboards/gonnerd/keymaps/tkl/Makefile
- keyboards/gonnerd/keymaps/tkl/keymap.c
Added a simple 87 key layout for the GON Nerd TKL.
> Add TKL keymap for GON NerdTKL

- keyboards/ergodox/ez/keymaps/drashna-custom/Makefile
- keyboards/ergodox/ez/keymaps/drashna-custom/config.h
- keyboards/ergodox/ez/keymaps/drashna-custom/keymap.c
- keyboards/ergodox/ez/keymaps/drashna/Makefile
- keyboards/ergodox/ez/keymaps/drashna/config.h
- keyboards/ergodox/ez/keymaps/drashna/keymap.c
- keyboards/ergodox/ez/keymaps/drashna/readme.md
Adds keymap that uses underglow as layer indicator rather than the top LEDs.
> RGB Underglow layer indicator keymap

- keyboards/ergodox/config.h
- keyboards/ergodox/ergodone/Makefile
- keyboards/ergodox/ergodone/config.h
- keyboards/ergodox/ergodone/ergodone.c
- keyboards/ergodox/ergodone/ergodone.h
- keyboards/ergodox/ergodone/expander.c
- keyboards/ergodox/ergodone/expander.h
- keyboards/ergodox/ergodone/i2cmaster.h
- keyboards/ergodox/ergodone/matrix.c
- keyboards/ergodox/ergodone/readme.md
- keyboards/ergodox/ergodone/rules.mk
- keyboards/ergodox/ergodone/twimaster.c
- keyboards/ergodox/ergodox.h
- keyboards/ergodox/keymaps/replicaJunction/config.h
- keyboards/ergodox/keymaps/win10_writers-block/config.h
- keyboards/ergodox/readme.md
This adds support for the ErgoDone keyboard by K.T.E.C as a subproject (so all existing keymaps should be compatible). See README.md for instructions on how to flash the firmware.
> Add support for the ErgoDone

- keyboards/nyquist/readme.md
Addresses this issue: https://github.com/qmk/qmk_firmware/issues/1588
> Update Nyquist readme file to new format

- keyboards/amj60/readme.md
- keyboards/amjpad/readme.md
- keyboards/hhkb/readme.md
List issue apparent after the clobber.
> Fixing readme clobber linebreak issues

- keyboards/lets_split/keymaps/dale/Makefile
- keyboards/lets_split/keymaps/dale/config.h
- keyboards/lets_split/keymaps/dale/defaultkeymap.c
- keyboards/lets_split/keymaps/dale/keymap.c
- keyboards/planck/keymaps/dale/Makefile
- keyboards/planck/keymaps/dale/config.h
- keyboards/planck/keymaps/dale/keymap.c
- keyboards/planck/keymaps/dale/readme.md
- keyboards/preonic/keymaps/dale/Makefile
- keyboards/preonic/keymaps/dale/config.h
- keyboards/preonic/keymaps/dale/keymap.c
- keyboards/preonic/keymaps/dale/readme.md
This only contains my keymaps for the Preonic, Planck and Let's Split.
I haven't seen many people ditch the arrows for punctuation and I've tried to use a consistent layout across all three keyboards.
Thought it might be worth sharing!
Thanks,
Dale 
/u/deaconblue42
> My keymaps only

- keyboards/satan/keymaps/mark1/keymap.c
- keyboards/satan/keymaps/mark1/readme.md
- keyboards/satan/satan.h
A Mac layout for touch typists who enjoy having a Fn key on both the left-hand and right-hand side.
> New Mac layout for Satan GH60

- keyboards/hhkb/keymaps/jp_mac/Makefile
- keyboards/hhkb/keymaps/jp_mac/keymap.c
Swapping command and alt, restoring fn+left for delete, subbing in grave for hhkb key.
> Creating Mac Version of JIS Keymap

- keyboards/9key/9key.c
- keyboards/9key/9key.h
- keyboards/9key/Makefile
- keyboards/9key/config.h
- keyboards/9key/keymaps/default/Makefile
- keyboards/9key/keymaps/default/keymap.c
- keyboards/9key/readme.md
- keyboards/9key/rules.mk
Actual product is currently not available as Bishop's store is still offline. This PCB was given away at the recent Charleston meetup held earlier this month.
> Add support for 9key keyboard/minipad by Bishop Keyboards

- keyboards/jd40/keymaps/vanagon/README.md
...and this is why you don't commit after 11:00 PM.
> (vanagon) - fix link brackets.

- keyboards/9key/config.h
- keyboards/9key/keymaps/default/keymap.c
- keyboards/9key/readme.md
- keyboards/readme.md
- Add 9key to keyboard list
- Update Bishop Keyboards url to new site
- Improve default layout to cover numpad
- Add example macro setup
> 9key updates

- keyboards/deltasplit75/keymaps/itsaferbie/config.h
- keyboards/deltasplit75/keymaps/itsaferbie/keymap.c
- keyboards/deltasplit75/matrix.c
- keyboards/deltasplit75/readme.md
- keyboards/deltasplit75/split_util.c
- Updated my config and keymap files.
- Port updated debouncing algorithm for Let's Split added in [#1519](https://github.com/qmk/qmk_firmware/pull/1519)
- Updated readme to be in the new format in issue: [#1588](https://github.com/qmk/qmk_firmware/issues/1588)
> DeltaSplit75 Updates

- keyboards/ergodone/ergodone.c
- keyboards/ergodone/ergodone.h
I wrote code to make ergodone's led work.
I tested on my keyboard.
> make ergodone's led work well

- Makefile
I'm always having to look up what the right command to do this is. A make target would be easier to remember and handy.
> add a `git-submodule` make target.

- keyboards/frosty_flake/frosty_flake.h
- keyboards/frosty_flake/keymaps/tkl/Makefile
- keyboards/frosty_flake/keymaps/tkl/config.h
- keyboards/frosty_flake/keymaps/tkl/keymap.c
- keyboards/frosty_flake/keymaps/tkl/readme.md
- keyboards/frosty_flake/readme.md
Provide simpler/explicit support for TKL keymaps for the Frosty Flake
Includes a simple example keymap and update to the Frosty Flake README.md
> Add TKL keymap for Frosty_Flake

- keyboards/tv44/keymaps/belak/config.h
- keyboards/tv44/keymaps/belak/keymap.c
- keyboards/tv44/keymaps/belak/readme.md
I made these tweaks a while ago but never ended up submitting them to avoid too much churn. I've been using these for a while now, so I'm a bit more confident I'll stick with them.
> Update tv44-belak keymap

- keyboards/planck/keymaps/sean/Makefile
- keyboards/planck/keymaps/sean/config.h
- keyboards/planck/keymaps/sean/keymap.c
- keyboards/planck/keymaps/sean/mymappings.h
- keyboards/planck/keymaps/sean/readme.md
- keyboards/planck/old_keymap_files/common_keymaps/keymap_sean.c
Hey there,
Could you please consider merging my keymap?  This is what I've got for my rev3, and am planning to use when I build my new keyboard (tomorrow).
Thanks!
Sean
> My new keymap

- keyboards/ergodone/readme.md
I have already open a issue #1703 for the same
> updated read.md file to fix the ergodone build command

- keyboards/ergodone/readme.md
Added clearer instruction with image to enter flash mode to flash a hex file or ergodone
> Further updated read.md

- util/wsl_install.sh
There are small changes, press enter instead of any key and bash command prompt instead of batch.
> Wording changes for the WSL install script

- keyboards/atreus/config.h
- keyboards/atreus/readme.md
- keyboards/atreus/rules.mk
Remove an outdated comment and show the correct upload command.
> Improve readme for Atreus.

- docs/keycodes.md
- docs/keycodes_basic.md
Platform compatibility descriptions added for mute, volume up/down
issue: #1642
fixes issues identified by @barrar with pull req #1750
> updated keycodes media descriptions

- keyboards/gherkin/README.md
- keyboards/gherkin/config.h
- keyboards/gherkin/keymaps/itsaferbie/config.h
- keyboards/gherkin/keymaps/itsaferbie/keymap.c
- keyboards/gherkin/keymaps/itsaferbie/rules.mk
I updated the readme to display properly and updated config to show more information.
As well as added my own keymap.
> Add my Gherkin keymap, and update readme and config.

- keyboards/obelus/config.h
- keyboards/obelus/keymaps/default/Makefile
- keyboards/obelus/keymaps/default/config.h
- keyboards/obelus/keymaps/default/keymap.c
- keyboards/obelus/keymaps/default/readme.md
- keyboards/obelus/obelus.c
- keyboards/obelus/obelus.h
- keyboards/obelus/readme.md
- keyboards/obelus/rules.mk
> Added Obelus

- keyboards/ergodox_ez/keymaps/matrixman/keymap.c
- keyboards/ergodox_ez/keymaps/matrixman/readme.md
- keyboards/planck/keymaps/matrixman/Makefile
- keyboards/planck/keymaps/matrixman/keymap.c
- keyboards/planck/keymaps/matrixman/readme.md
Hello, I've been using these layouts and I thought I might add them here so that I can refer others to them.
> Adding my layout to Ergodox_ez and Planck

- quantum/dynamic_macro.h
> Fix dynamic macros on ChibiOS keyboards

- keyboards/planck/keymaps/tehwalris/config.h
- keyboards/planck/keymaps/tehwalris/keymap.c
- keyboards/planck/keymaps/tehwalris/rules.mk
This is my personal layout. I'd like to get it merged so that I can refer people to it.
> Add new planck layout

- layouts/community/ergodox/qwerty_code_friendly/keymap.c
- layouts/community/ergodox/qwerty_code_friendly/readme.md
Hi, not sure new layout's are welcome, submitting a PR since I *think* having a layout for developers coming from QWERTY might be useful for others.
I've moved some opinionated decisions behind an ifdef that can be set using `EXTRAFLAGS`.
> Ergodox layout: code friendly qwerty

- docs/tap_dance.md
Change-Id: I64aa6f95a30ab05f0ed3f499e54b9e125d379fad
> 'makefile' changed to 'rules.mk' in tap dance doc

- docs/feature_bootmagic.md
I fixed a minor typo in `docs/feature_bootmagic.md` :)
> Fixed a minor typo in feature_bootmagic.md.

- keyboards/ergodox_ez/keymaps/default/keymap.c
- keyboards/ergodox_ez/keymaps/default_osx/keymap.c
> [cleanup] consistent 2 space indentation for ergodox default map

- keyboards/amj40/keymaps/fabian/keymap.c
- keyboards/lets_split/keymaps/fabian/keymap.c
- keyboards/planck/keymaps/fabian/Makefile
- keyboards/planck/keymaps/fabian/config.h
- keyboards/planck/keymaps/fabian/keymap.c
- keyboards/xd75/keymaps/fabian/keymap.c
My custom layout "fabian" for amj40, let's split, planck and xd75.
> Consistent fabian layouts for amj40, let's split, planck and xd75

- keyboards/gh60/keymaps/bluezio/keymap.c
- keyboards/gh60/keymaps/bluezio/rules.mk
I decided on creating a layout with split backspace (like in HHKB), ANSI-like Enter key, and split left shift. I've also decided to use a SpaceFn-like layout.
I am rather happy with my layout so far - perhaps it might be worth including?
Looking forward to further comments,
Antonio
> Contribute GH60 layout

- keyboards/gherkin/keymaps/itsaferbie/keymap.c
Added layer for Experience Design.
> Updated my Gherkin Keymap

- tmk_core/common/action.c
added waits as described here https://github.com/tmk/tmk_keyboard/issues/390
fixes #1792
> #1792 added in waits from tmk for locking switches

- docs/feature_ps2_mouse.md
- tmk_core/protocol/ps2_mouse.c
Invert mouse and scroll axes using:
#define PS2_MOUSE_INVERT_X
#define PS2_MOUSE_INVERT_Y
#define PS2_MOUSE_INVERT_H
#define PS2_MOUSE_INVERT_V
> Add option to reverse PS2 mouse axes and scrolling

- keyboards/atreus/keymaps/xk/config.h
- keyboards/atreus/keymaps/xk/keymap.c
- keyboards/atreus/keymaps/xk/rules.mk
mmkay I just deleted by old github clone and it worked
> newkb-atreus-xk

- keyboards/tada68/readme.md
Some updates to the tada68 instructions to help people avoid the pitfalls I fell in tonight.
> Tada68 instructions, updated and clarified to avoid bricking keyboards

- util/activate_msys2.sh
I must apologize.
The following pull request is incorrect.
[Fix missing teensy path #1790](https://github.com/qmk/qmk_firmware/pull/1790)
> Fix missing teensy path

- keyboards/tomato/config.h
- keyboards/tomato/keymaps/default/keymap.c
- keyboards/tomato/readme.md
- keyboards/tomato/rules.mk
- keyboards/tomato/tomato.c
- keyboards/tomato/tomato.h
more info about this board can be found [here](http://www.40percent.club/2017/07/tomato-in-gherkin.html) and [here](https://github.com/di0ib/Misc/tree/master/tomato)
> Add the Tomato keyboard

- tmk_core/avr.mk
> Fix avrdude message to not mention any specific device model.

- keyboards/ergodox_ez/keymaps/heartrobotninja/config.h
- keyboards/ergodox_ez/keymaps/heartrobotninja/keymap.c
- keyboards/ergodox_ez/keymaps/heartrobotninja/rules.mk
- keyboards/lets_split/keymaps/heartrobotninja/config.h
- keyboards/lets_split/keymaps/heartrobotninja/keymap.c
- keyboards/lets_split/keymaps/heartrobotninja/rules.mk
Commit of my own keyboard layouts. Layouts are documented in the keymap.c files themselves.
> heartrobotninja ergodox_ez and lets_split layouts

- docs/tap_dance.md
* Quad function tap dance works as intended when typing fast
* Example 4 in doc has been updated
> Update to Tap-Dance Docs for Fast Typists

- keyboards/planck/keymaps/paget/config.h
- keyboards/planck/keymaps/paget/keymap.c
- keyboards/planck/keymaps/paget/rules.mk
Custom layout which I created for my planck
> My layout to suit my needs

- keyboards/planck/keymaps/gunp/config.h
- keyboards/planck/keymaps/gunp/keymap.c
- keyboards/planck/keymaps/gunp/readme.md
- keyboards/planck/keymaps/gunp/rules.mk
- keyboards/planck/keymaps/gunp/upload-and-make.sh
Add a layout of planck named GunP, ready for pull request review.
> Add a layout of planck named GunP, ready for pull request review.

- keyboards/ergodox_ez/keymaps/heartrobotninja/keymap.c
Moving LOCK and adding RUN. Fixing equal key to actually use equal keycode.
> Updates to heartrobotninja ergodox_ez keymap.

- layouts/community/ergodox/qwerty_code_friendly/keymap.c
- layouts/community/ergodox/qwerty_code_friendly/readme.md
> Code friendly qwerty

- quantum/process_keycode/process_key_lock.c
> Fix for issue #1751

- keyboards/ergodox_infinity/keymaps/nordic_ergo/keymap.c
- keyboards/ergodox_infinity/keymaps/nordic_ergo/readme.md
- keyboards/ergodox_infinity/readme.md
- Basic Nordic layout for Infinity
- Fixed typo in Ergodox Infinity readme.md
> Ergodox Infinity Nordic layout

- keyboards/chimera_ortho/chimera_ortho.c
- keyboards/chimera_ortho/chimera_ortho.h
- keyboards/chimera_ortho/config.h
- keyboards/chimera_ortho/keymaps/default/keymap.c
- keyboards/chimera_ortho/matrix.c
- keyboards/chimera_ortho/rules.mk
I designed a split wireless 40% keyboard, this is the firmware code
> Chimera Ortho

- keyboards/chimera_ortho/chimera_ortho.c
- keyboards/chimera_ortho/chimera_ortho.h
- keyboards/chimera_ortho/config.h
- keyboards/chimera_ortho/keymaps/default/keymap.c
- keyboards/chimera_ortho/matrix.c
- keyboards/chimera_ortho/readme.md
- keyboards/chimera_ortho/rules.mk
New pull request to add readme for Chimera Ortho
> Chimera Ortho Readme

- common_features.mk
- tmk_core/protocol/iwrap/iwrap.c
- tmk_core/protocol/pjrc.mk
extract of changes that allowed me to use the pointing device feature
> Fix pointing device feature

- keyboards/satan/keymaps/dkrieger/config.h
- keyboards/satan/keymaps/dkrieger/keymap.c
- keyboards/satan/keymaps/dkrieger/readme.md
- keyboards/satan/keymaps/dkrieger/rules.mk
… and without LED functionality
> Add satan keymap: HHKB-alike based on dbroqua's, with mouse functionality

- keyboards/dz60/dz60.c
Rebased to bring in fixes from Gitter troubleshooting session.
> DZ60 LED function update

- keyboards/xd60/keymaps/petesmom/README.md
- keyboards/xd60/keymaps/petesmom/keymap.c
Mac layout based on yuuki with some other changes, for Pete's 40th birthday keyboard
> Pete's 40th XD64 Layout

- layouts/community/ergodox/qwerty_code_friendly/keymap.c
- layouts/community/ergodox/qwerty_code_friendly/readme.md
> qwerty_code_friendly: configurable left thumb

- docs/keymap.md
Also removed references to what appear to be outdated tmk variable names.
> Fixed some grammar and typos on the docs

- docs/faq_debug.md
> Document the Teensy hardware reset problem

- keyboards/whitefox/whitefox.h
This keymap has been tested on my Truefox layout Whitefox.
> Add Keymap for Whitefox Truefox layout

- docs/feature_macros.md
Following some feedback on the MK Discord, I expanded the documentation of macros a bit. Mainly by expanding the example, giving it some more context and explaining the code in prose.
> Macro docs improvement

- keyboards/ergodox_ez/keymaps/drashna/config.h
- keyboards/ergodox_ez/keymaps/drashna/keymap.c
- keyboards/handwired/woodpad/keymaps/drashna/config.h
- keyboards/handwired/woodpad/keymaps/drashna/keymap.c
- keyboards/handwired/woodpad/keymaps/drashna/rules.mk
- keyboards/orthodox/keymaps/drashna/keymap.c
- keyboards/viterbi/keymaps/drashna/config.h
- keyboards/viterbi/keymaps/drashna/keymap.c
- keyboards/viterbi/keymaps/drashna/rules.mk
- users/drashna/drashna.c
- users/drashna/drashna.h
- Finish moving code to userspace (tap dances)
- Add alternate keycodes to use when tap dance is disabled
- Add forced NKRO (to assist with macro output speed)
- Added toggle for RGB layer indication (so one could "go back" to normal functionality)
- Cleaned up macros
- Added audio/faux click code
> Update to drashna keymaps

- keyboards/fc980c/README.md
sorry for forgetting it in the first PR.
> I forgot to add a README.md for the FC980C

- keyboards/tkc1800/README.md
- keyboards/tkc1800/config.h
- keyboards/tkc1800/keymaps/default/config.h
- keyboards/tkc1800/keymaps/default/keymap.c
- keyboards/tkc1800/rules.mk
- keyboards/tkc1800/tkc1800.c
- keyboards/tkc1800/tkc1800.h
Tested functional on rev 0.1 prototype PCB.
> Initial support for TKC1800 PCB

- docs/feature_userspace.md
- users/drashna/template.c
16 byte optimization of macro ;)
Thanks seebs!
> Optimization of Make macro and doc

- keyboards/pearl/keymaps/default/keymap.c
Pearl should be done now other than the backlighting 🎉
> Modified default keymap to match ps2avrgb default

- keyboards/do60/config.h
- keyboards/do60/do60.c
- keyboards/do60/do60.h
- keyboards/do60/keymaps/default/keymap.c
- keyboards/do60/keymaps/default/readme.md
- keyboards/do60/keymaps/test/keymap.c
- keyboards/do60/keymaps/test/readme.md
- keyboards/do60/readme.md
- keyboards/do60/rules.mk
Add DO60 support.
Add keymaps.
Second request see if deleting issue is able to solve.
> Add DO60 support - try2

- keyboards/clueboard/66/keymaps/magicmonty/Makefile
- keyboards/clueboard/66/keymaps/magicmonty/keymap.c
- keyboards/clueboard/66/keymaps/magicmonty/readme.md
- keyboards/clueboard/66/keymaps/magicmonty/rules.mk
Also removed superfluous Makefile and fixed a value in rules.mk
> Updated color for base layer to better match my key caps (Dasher)

- keyboards/nyquist/keymaps/333fred/config.h
- layouts/community/ergodox/333fred/config.h
- users/333fred/333fred_config.h
Leaving these locked all the time with my new VIM mode layers.
> Turn on prevent stuck modifiers for my keymaps.

- keyboards/planck/keymaps/dr_notsokind/Readme.md
- keyboards/planck/keymaps/dr_notsokind/config.h
- keyboards/planck/keymaps/dr_notsokind/keymap.c
- keyboards/planck/keymaps/dr_notsokind/rules.mk
Hi there, just sharing my personal layout!
Cheers
> New Planck Layout

- keyboards/lightsaver/config.h
- keyboards/lightsaver/indicator_leds.c
- keyboards/lightsaver/indicator_leds.h
- keyboards/lightsaver/keymaps/default/keymap.c
- keyboards/lightsaver/keymaps/default/readme.md
- keyboards/lightsaver/lightsaver.c
- keyboards/lightsaver/lightsaver.h
- keyboards/lightsaver/matrix.c
- keyboards/lightsaver/readme.md
- keyboards/lightsaver/rules.mk
Add Duck Lightsaver V3 custom keyboard.
> Add Lightsaver V3 keyboard

- keyboards/lightsaver/keymaps/default/readme.md
- keyboards/lightsaver/keymaps/rasmus/config.h
- keyboards/lightsaver/keymaps/rasmus/keymap.c
- keyboards/lightsaver/keymaps/rasmus/readme.md
- keyboards/lightsaver/keymaps/rasmus/rules.mk
Added my own keymap and changed default keymap readme.
> Add rasmus keymap and fix default keymap readme for Duck Lightsaver

- .gitmodules
- keyboards/fc660c/README.md
- keyboards/fc660c/actuation_point.c
- keyboards/fc660c/actuation_point.h
- keyboards/fc660c/config.h
- keyboards/fc660c/fc660c.c
- keyboards/fc660c/i2c.c
- keyboards/fc660c/i2c.h
- keyboards/fc660c/lib_i2c
- keyboards/fc660c/matrix.c
- keyboards/fc660c/rules.mk
- keyboards/fc980c/README.md
- keyboards/fc980c/actuation_point.c
- keyboards/fc980c/actuation_point.h
- keyboards/fc980c/config.h
- keyboards/fc980c/fc980c.c
- keyboards/fc980c/i2c.c
- keyboards/fc980c/i2c.h
- keyboards/fc980c/keymaps/actuation-point-example/README.md
- keyboards/fc980c/keymaps/actuation-point-example/config.h
- keyboards/fc980c/keymaps/actuation-point-example/keymap.c
- keyboards/fc980c/lib_i2c
- keyboards/fc980c/matrix.c
- keyboards/fc980c/rules.mk
if you are unhappy with how the lib is set up tell me. right now it's a git submodule linking my fork. to include it in the makefiles, I'm using a symlink because I don't know what the "proper" way to include it would be.
> actuation point adjustment for fc980c and fc660c

- keyboards/dz60/keymaps/iso_7u_space/keymap.c
added a keymap for an iso layout with 7u spacebar
> added iso support

- keyboards/ergodox_ez/keymaps/drashna/README.md
- keyboards/ergodox_ez/keymaps/drashna/keymap.c
- keyboards/handwired/woodpad/keymaps/drashna/README.md
- keyboards/orthodox/keymaps/drashna/README.md
- keyboards/viterbi/keymaps/drashna/keymap.c
- users/drashna/_sensitive.h
- users/drashna/drashna.c
- users/drashna/drashna.h
- users/drashna/readme.md
- users/drashna/sensitive.h
* Change "overwatch" layer to more generic "gamepad"
* Remove "sensitive" file stuff
* Add @colinta's fantastic "secrets.h" method to include customizable strings
> Update Drashna keymaps

- keyboards/tv44/keymaps/budi/config.h
- keyboards/tv44/keymaps/budi/keymap.c
- keyboards/tv44/keymaps/budi/readme.md
dvorak base, with ~~qwerty layer and~~ gaming support for minivan southpaw arrow layout
> [budi] tv44 arrow dvorak

- keyboards/dz60/keymaps/iso_6u_space/keymap.c
fixed the problems with deleting the mechmini.md referencing pull request #2150
> reforked master and added changes to 7u and 6u iso layouts

- keyboards/dz60/keymaps/tailcall/keymap.c
Hello.
I've recently bought TINA keyboard and decided to implement my keymap that I use on Pok3r before with some modifications.
> Add my keymap for dz60

- layouts/community/ergodox/zweihander-osx/keymap.c
- layouts/community/ergodox/zweihander-osx/readme.markdown
- add right command keys
- add F16 on ;' for Siri
- remove command-Q (too easy to hit)
> Zweihander: remove app keys, etc.

- keyboards/dz60/keymaps/iso_7u_space/keymap.c
Merge conflict text left in source code, was breaking dz60 build.
> fix breaking build: remove merge conflict text

- quantum/audio/song_list.h
It's the sound that's made when opening a treasure chest.
> Adding a Zelda Treasure sound.

- keyboards/meira/keymaps/takmiya/config.h
- keyboards/meira/keymaps/takmiya/keymap.c
- keyboards/meira/keymaps/takmiya/readme.md
> Add meira/takmiya keymap

- keyboards/gherkin/keymaps/wanleg/config.h
- keyboards/gherkin/keymaps/wanleg/keymap.c
- keyboards/gherkin/keymaps/wanleg/readme.md
- keyboards/gherkin/keymaps/wanleg/rules.mk
> wanleg's gherkin layout

- docs/getting_started_build_tools.md
> macOS also requires avrdude

- docs/feature_rgblight.md
- quantum/rgblight.c
Limit the val of HSV to limit the maximum brightness simply. 
So we can add 100+ RGB leds to our keyboard.
> Add RGBLIGHT_LIMIT_VAL

- keyboards/chimera_ortho/keymaps/gordon/keymap.c
- keyboards/ergodox_infinity/keymaps/gordon/keymap.c
- users/gordon/gordon.c
- users/gordon/gordon.h
- users/gordon/readme.md
- users/gordon/rules.mk
* gordon.c defines many aliases for KC codes.
* gordon.c defines many advanced tap dance functions.
* This is a squashed commit of about 6 months of work on chimera and
ergodox infinity changes.
> Add Daniel Gordon's Ergodox Infinity and Chimera

- keyboards/tada68/keymaps/trashcat/keymap.c
- keyboards/tada68/keymaps/trashcat/readme.md
- keyboards/tada68/keymaps/trashcat/rules.mk
Just adding my Tada68 layout because there really aren't many options for it.
> Adding my Tada68 Keymap.

- keyboards/dz60/keymaps/60_plus_arrows/keymap.c
dz60 layout with right hand arrow keys, plus function layer for rgb controls
> add dz60 map with arrow keys

- keyboards/iris/matrix.c
Backlight state on the slave half of the keyboard was not being written when using I2C, only Serial.
This PR uses the first byte of the i2c_slave_buffer, and writes the information there before switching to a read operation for the slave's matrix.
> Iris send backlight info over i2c

- keyboards/clueboard/66/keymaps/manofinterests/keymap.c
- keyboards/clueboard/66/keymaps/manofinterests/readme.md
this is a tutorial layout for the QMK Tutorial stream
> Tutorial QMK Pull Request for Top Clack

- util/new_project.sh
See https://stackoverflow.com/questions/19456518/invalid-command-code-despite-escaping-periods-using-sed
> update sed to work on mac

- keyboards/readme.md
Adding jj40 to Community-supported list.
> Adding jj40 to keyboard list

- keyboards/readme.md
- keyboards/ymdk_np21/README.md
- keyboards/ymdk_np21/backlight.c
- keyboards/ymdk_np21/backlight_custom.h
- keyboards/ymdk_np21/breathing_custom.h
- keyboards/ymdk_np21/config.h
- keyboards/ymdk_np21/i2c.c
- keyboards/ymdk_np21/i2c.h
- keyboards/ymdk_np21/keymaps/default/keymap.c
- keyboards/ymdk_np21/matrix.c
- keyboards/ymdk_np21/rules.mk
- keyboards/ymdk_np21/usbconfig.h
- keyboards/ymdk_np21/ymdk_np21.c
- keyboards/ymdk_np21/ymdk_np21.h
Adding basic support for YMDK NP21 - edit of jj40 directory to suport the num-pad.
> Support for YMDK NP21

- tmk_core/rules.mk
> Use perl directly instead of grep -P

- keyboards/iris/keymaps/hag/config.h
- keyboards/iris/keymaps/hag/keymap.c
- keyboards/iris/keymaps/hag/rules.mk
Created iris "hag" keymap, a custom heavily modified swedish dvorak keymap with multiple layouts and heavy use of layers. 
Rules.mk and config.h are copied from default keymap folder, keymap.c is modified for my useage. 
Hopefully it is correct done, I'm new to git. :)
> Added "hag" keymap to Iris

- util/win_shared_install.sh
Found the updated URL for it.
http://www.microchip.com/developmenttools/productdetails.aspx?partno=flip
> Re-add Flip Installer

- tmk_core/protocol/chibios/main.c
- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/chibios/usb_main.h
The relevant changes are already pushed to the ChibiOS and ChibiOS contrib repositories.
The contrib repository needed some minor additions, and I will add pull request to upstream for it. Right now they are in our own branch.
NOTE: I was not able to re-open the other pull request for some reason
> Update chibios to version 17.6.3

- keyboards/diverge3/config.h
- keyboards/diverge3/diverge3.c
- keyboards/diverge3/diverge3.h
- keyboards/diverge3/keymaps/default/config.h
- keyboards/diverge3/keymaps/default/keymap.c
- keyboards/diverge3/keymaps/default/readme.md
- keyboards/diverge3/keymaps/default/rules.mk
- keyboards/diverge3/readme.md
- keyboards/diverge3/rules.mk
Diverge 3 support. Tested on my own device, also a readme to go back to stock firmware.
I'm not the maker of this keyboard. Just wanted QMK support
> Diverge 3 initial commit

- keyboards/ergodox_infinity/keymaps/halfkeyboard/config.h
- keyboards/ergodox_infinity/keymaps/halfkeyboard/keymap.c
- keyboards/ergodox_infinity/keymaps/halfkeyboard/rules.mk
- keyboards/ergodox_infinity/keymaps/halfkeyboard/visualizer.c
- keyboards/ergodox_infinity/keymaps/halfkeyboard/visualizer.h
also visualizer KITT scanner, attempt to add music mode(still a lot of work to go) and mouse mode added back as a keymap.
> ergodox steno support(gemini)

- keyboards/lets_split/keymaps/default/keymap.c
- Fixed alignment whitespace in QWERTY keymap
- Fixed errors in Lower and Raise keymap comments
> Let's Split: Minor keymap fixes

- keyboards/nyquist/keymaps/pitty/keymap.c
Added underglow layer feedback to my keymap.
> Update my nyquist keymap.c

- docs/getting_started_build_tools.md
Noticed the typo while trying to build my keymap using docker.
> ergobox -> ergodox

- keyboards/gherkin/keymaps/wanleg/config.h
- keyboards/gherkin/keymaps/wanleg/keymap.c
- keyboards/gherkin/keymaps/wanleg/readme.md
* added flashing instructions for Linux & Windows
* minor keymap changes
> flashing instructions, keymap changes

- docs/feature_bootmagic.md
- covers most of tmk_core/common/bootmagic.h
- ignores debugging options because I don't know how to use them
Contributes docs to #2389 
@skullydazed
> Document bootmagic hot keys

- keyboards/tada68/keymaps/wamsm_tada/config.h
- keyboards/tada68/keymaps/wamsm_tada/keymap.c
- keyboards/tada68/keymaps/wamsm_tada/readme.md
- keyboards/tada68/keymaps/wamsm_tada/rules.mk
Adding my personal 'tada68' layout. Hopefully others will use it or take ideas from it.
> Add additional 'tada68' layout.

- keyboards/jj40/keymaps/ajp10304/config.h
- keyboards/jj40/keymaps/ajp10304/jj40.h
- keyboards/jj40/keymaps/ajp10304/keymap.c
- keyboards/jj40/keymaps/ajp10304/readme.md
- keyboards/jj40/keymaps/ajp10304/rules.mk
- keyboards/jj40/keymaps/default/keymap.c
Added JJ40 AJP10304 layout
Updated AJP10304 Planck layout readme.md formatting
> JJ40 AJP10304 layout

- keyboards/ergodox_infinity/keymaps/trulyergonomic/README.md
- keyboards/ergodox_infinity/keymaps/trulyergonomic/keymap.c
A layout for the Infinity ErgoDox keyboard that imitates the layout of the Truly Ergonomic keyboard (also known as the TECK).
> ErgoDox layout similar to Truly Ergonomic

- docs/eclipse.md
- docs/feature_audio.md
- docs/feature_mouse_keys.md
- docs/keycodes.md
Just fixed that one typo, working on revising the documentation
> Fixed typo of 'confid.h' to 'config.h'

- keyboards/planck/keymaps/navi/config.h
- keyboards/planck/keymaps/navi/keymap.c
- keyboards/planck/keymaps/navi/readme.md
- keyboards/planck/keymaps/navi/rules.mk
Has a nifty numberpad layer & some other shortcuts that I find useful and hope others will find useful as well!
Mostly focused on qwerty and colemak
> Adding my Planck Keymap

- docs/_summary.md
- docs/faq_keymap.md
- docs/feature_bootmagic.md
- docs/feature_command.md
- docs/hardware_keyboard_guidelines.md
Addresses many of the points in #2389.
> More thoroughly document Bootmagic and Command

- docs/hardware_keyboard_guidelines.md
Add mention of some possible invalid keyboard names. I assume these are all invalid, but I'm basing that off of reading the makefile, of which my understanding is poor.
https://github.com/qmk/qmk_firmware/issues/2447
> Mention invalid names in the readme.

- keyboards/kbd66/keymaps/maartenwut/keymap.c
I ported the kbd66 myself initially and copied it over to the existing port, but forgot that he used KEYMAP() instead of KEYMAP_ANSI(). Fixed that and cleaned unused stuff up, as well as adding the caps lock led.
> Fixed keymap, added capslock led for maartenwut's kbd66 keymap

- keyboards/helix/rev2/keymaps/default/config.h
- keyboards/helix/rev2/keymaps/default/rules.mk
Add USB_MAX_POWER_CONSUMPTION and auto-setup RGBLIGHT_LIMIT_VAL
> Usb max power

- util/macos_install.sh
With this change, the script worked for me.
> Fixed exit status check for brew

- keyboards/jj40/keymaps/ajp10304/keymap.c
- keyboards/jj40/keymaps/ajp10304/readme.md
- keyboards/planck/keymaps/ajp10304/keymap.c
- keyboards/planck/keymaps/ajp10304/readme.md
Added Layer extensions for Mac OS
> Planck ajp10304

- quantum/keymap_extras/keymap_italian.h
Italian keys definition, streamlines the development of keymaps based on the Italian layout
> Add italian keymap

- keyboards/helix/rev2/keymaps/led_test/config.h
- keyboards/helix/rev2/keymaps/led_test/keymap.c
- keyboards/helix/rev2/keymaps/led_test/rgblight.c
- keyboards/helix/rev2/keymaps/led_test/rgblight.h
- keyboards/helix/rev2/keymaps/led_test/rules.mk
A new keymap for Helix keyboard.
It's for LED test.
This keymap always LED on and LED color changing Red, Blue, Green.
User can check LED.
> Helix keyboard led test as a keymap

- keyboards/amj40/keymaps/myee/build.sh
- keyboards/amj40/keymaps/myee/config.h
- keyboards/amj40/keymaps/myee/keymap.c
- keyboards/amj40/keymaps/myee/readme.md
- keyboards/amj40/keymaps/myee/rules.mk
- keyboards/amj40/keymaps/myee/updatemerge.sh
Hi, I'd like to contribute my keymap for the AMJ40 to QMK.
> Added my keymap

- keyboards/xd75/keymaps/adi/config.h
- keyboards/xd75/keymaps/adi/keymap.c
- keyboards/xd75/keymaps/adi/readme.md
- keyboards/xd75/keymaps/adi/rules.mk
Hi there!
I would like to contribute my own personal keymap for the XD75re. I hope it can benefit someone somehow :)
> New keymap for XD75re ("adi")

- docs/keycodes.md
- docs/keycodes_basic.md
- quantum/quantum.h
- quantum/quantum_keycodes.h
- tmk_core/common/keycode.h
> Add CMD and WIN aliases for KC_GUI, GUI(kc), GUI_T(kc), etc.

- keyboards/unloved_bastard/config.h
- keyboards/unloved_bastard/keymaps/default/config.h
- keyboards/unloved_bastard/keymaps/default/keymap.c
- keyboards/unloved_bastard/keymaps/default/readme.md
- keyboards/unloved_bastard/matrix.c
- keyboards/unloved_bastard/readme.md
- keyboards/unloved_bastard/rules.mk
- keyboards/unloved_bastard/unloved_bastard.c
- keyboards/unloved_bastard/unloved_bastard.h
My first contribution, probably something wrong somewhere, but everything seems to work on my ISO version. Would be nice if someone with an ANSI version could test or give me some feedback if I forgot about something that would not be noticeable on my ISO version.
> Initial support for The Unloved Bastard

- util/macos_install.sh
> Fix logic in macos install

- keyboards/contra/info.json
My first attempt to support two different layouts on a board! Good thing the contra has two layouts that are super simple.
> add info.json to support both layouts on the Contra

- docs/hardware_keyboard_guidelines.md
I think I got all of them, so I removed the "FIXME".
> Added bootloader options

- docs/feature_advanced_keycodes.md
- docs/keycodes.md
- quantum/keymap_common.c
- quantum/quantum_keycodes.h
Plus cleaning up some semi-related documentation.
> Add macro for momentarily switching to a layer while some mods are active

- keyboards/iris/keymaps/transmogrified/config.h
- keyboards/iris/keymaps/transmogrified/keymap.c
- keyboards/iris/keymaps/transmogrified/rules.mk
> Add new keymap for iris transmogrified

- docs/feature_rgblight.md
I got caught out with this as most color pickers use a percentage NOT 0-255 for this number
> Add HSV value specification

- quantum/process_keycode/process_auto_shift.c
I noticed that tilde wasn't responding to the auto-shift.
> add grave to auto-shift.

- layouts/default/60_ansi/default_60_ansi/keymap.c
- layouts/default/60_ansi_split_bs_rshift/default_60_ansi_split_bs_rshift/keymap.c
Someone might try to use these keymaps, so they shouldn't be non-functional.
> layouts/default: fill in 60_ansi keymaps

- keyboards/contra/keymaps/ryanm101/config.h
- keyboards/contra/keymaps/ryanm101/keymap.c
- keyboards/contra/keymaps/ryanm101/readme.md
- keyboards/contra/keymaps/ryanm101/rules.mk
> Just a multilayered Layout using tapdance

- keyboards/preonic/keymaps/0xdec/keymap.c
- keyboards/preonic/keymaps/CMD-Preonic/keymap.c
- keyboards/preonic/keymaps/blake-newman/keymap.c
- keyboards/preonic/keymaps/bucktooth/keymap.c
- keyboards/preonic/keymaps/choromanski/keymap.c
- keyboards/preonic/keymaps/default/keymap.c
- keyboards/preonic/keymaps/dlaroe/keymap.c
- keyboards/preonic/keymaps/dudeofawesome/keymap.c
- keyboards/preonic/keymaps/ekis_isa/keymap.c
- keyboards/preonic/keymaps/jacwib/keymap.c
- keyboards/preonic/keymaps/kinesis/keymap.c
- keyboards/preonic/keymaps/nikchi/keymap.c
- keyboards/preonic/keymaps/smt/keymap.c
- keyboards/preonic/keymaps/that_canadian/keymap.c
- keyboards/preonic/keymaps/xyverz/keymap.c
- keyboards/preonic/keymaps/zach/keymap.c
Used grid unless it was clear that MIT was used
> Convert all Preonic keymaps to layout format

- keyboards/xd60/keymaps/birkir/keymap.c
- keyboards/xd60/keymaps/birkir/readme.md
Added my custom keymap for xd60
> Added birkir's xd60 keymap

- quantum/template/keymaps/default/keymap.c
- quantum/template/template.h
Changed the templates used by the new_project script so all new layouts made from using this script will actually use LAYOUT.
> Change KEYMAP to LAYOUT

- keyboards/rama/m6_a/keymaps/naut/config.h
- keyboards/rama/m6_a/keymaps/naut/keymap.c
- keyboards/rama/m6_a/keymaps/naut/readme.md
> M6-A Personal keymap added

- keyboards/levinson/keymaps/treadwell/config.h
- keyboards/levinson/keymaps/treadwell/keymap.c
- keyboards/levinson/keymaps/treadwell/rules.mk
Just added personal keymap for levinson
> Added personal keymap

- keyboards/iris/keymaps/davidrambo/config.h
- keyboards/iris/keymaps/davidrambo/keymap.c
- keyboards/iris/keymaps/davidrambo/readme.md
- keyboards/iris/keymaps/davidrambo/rules.mk
- keyboards/iris/keymaps/dnrambo/config.h
- keyboards/iris/keymaps/dnrambo/keymap.c
- keyboards/iris/keymaps/dnrambo/readme.md
- keyboards/iris/keymaps/dnrambo/rules.mk
- keyboards/planck/keymaps/davidrambo/config.h
- keyboards/planck/keymaps/davidrambo/keymap.c
- keyboards/planck/keymaps/davidrambo/rules.mk
- keyboards/planck/keymaps/rambo/config.h
- keyboards/planck/keymaps/rambo/keymap.c
- keyboards/planck/keymaps/rambo/rules.mk
- keyboards/satan/keymaps/bri/keymap.c
- keyboards/satan/keymaps/bri/readme.md
- keyboards/xd75/keymaps/davidrambo/config.h
- keyboards/xd75/keymaps/davidrambo/keymap.c
- keyboards/xd75/keymaps/davidrambo/readme.md
- keyboards/xd75/keymaps/davidrambo/rules.mk
- keyboards/xd75/keymaps/rambo/config.h
- keyboards/xd75/keymaps/rambo/keymap.c
- keyboards/xd75/keymaps/rambo/readme.md
- keyboards/xd75/keymaps/rambo/rules.mk
This is a pull request for my several custom keymaps. (I apologize for having the four keymaps being lumped together. I'm not proficient enough with git to go back and commit them separately.)
The Satan keymap has a different name because it is my wife's. I hope it is okay to diverge from my user name. Otherwise I can of course change it.
Thank you : )
> keymaps for Iris, Planck, Satan, and XD75

- keyboards/ergodox_infinity/keymaps/input_club/README.md
- keyboards/ergodox_infinity/keymaps/input_club/keymap.c
This keymap uses the same layout as the default Input Club layout from their configurator. It does not perform the same layer notifications in the LCD, but should match other than that.
Please let me know if I need to change the name due to trademark/company name.
> Adds default IC keymap

- keyboards/kinesis/config.h
- keyboards/kinesis/readme.md
- keyboards/kinesis/stapelberg/readme.md
- keyboards/kinesis/stapelberg/stapelberg.h
Updated info and fixed minor errors regarding make command and Teensy pin assignments.
>  Updated info and fixed minor errors 

- keyboards/dz60/keymaps/eric/keymap.c
- keyboards/hhkb/keymaps/eric/keymap.c
> Added dz60/eric and hhkb/eric

- keyboards/scrabblepad/config.h
Matrix updated alongside changes to ongoing design, new WS2812 capable pin specified.
> ScrabblePad updates

- keyboards/ut47/keymaps/rgb/config.h
- keyboards/ut47/keymaps/rgb/keymap.c
- keyboards/ut47/keymaps/rgb/readme.md
- keyboards/ut47/keymaps/rgb/rules.mk
- keyboards/ut47/matrix.c
Modified matrix.c to not initialize serial port if not needed.
> Add RGB keymap to UT47

- quantum/process_keycode/process_clicky.c
> Fix Clicky Down keycode

- keyboards/redox/config.h
- keyboards/redox/i2c.c
- keyboards/redox/i2c.h
- keyboards/redox/keymaps/default/config.h
- keyboards/redox/keymaps/default/keymap.c
- keyboards/redox/keymaps/default/readme.md
- keyboards/redox/keymaps/default/rules.mk
- keyboards/redox/matrix.c
- keyboards/redox/readme.md
- keyboards/redox/redox.c
- keyboards/redox/redox.h
- keyboards/redox/rev1/config.h
- keyboards/redox/rev1/rev1.c
- keyboards/redox/rev1/rev1.h
- keyboards/redox/rev1/rules.mk
- keyboards/redox/rules.mk
- keyboards/redox/serial.c
- keyboards/redox/serial.h
- keyboards/redox/split_util.c
- keyboards/redox/split_util.h
Hi,
I added the files for supporting the Redox keyboard. Already tested on the hardware I have on hand and everything seems to be working.
The keyboard is available on [Falbatech's site](https://falba.tech/product-category/keyboard-parts/redox-parts/), more info available [here](https://github.com/mattdibi/redox-keyboard).
I hope I did everything correctly. :smile:
> Redox keyboard code

- keyboards/v60_type_r/v60_type_r.c
- keyboards/v60_type_r/v60_type_r.h
Even though the changes are unlikely to break anything, it would be nice if anyone with a POLESTAR could make sure. (Mine's a plain-no-RGB model)
> Clean up v60_type_r keyboard

- keyboards/xd75/keymaps/tdl-jturner/config.h
- keyboards/xd75/keymaps/tdl-jturner/keymap.c
- keyboards/xd75/keymaps/tdl-jturner/readme.md
- keyboards/xd75/keymaps/tdl-jturner/rules.mk
/u/tdl-jturner - XD75 Layout
===
Keyboard Layout Editor: [Link](http://www.keyboard-layout-editor.com/#/gists/b2b23097ef70fd9170e266e4cbc06c02)
Notes:
* Based on Qwerty
* Tweaks for DBA & Programming including tap dance braces on lower right, custom shift codes, and F5 access on Nav layer
* Layers are all based on layer control on the left and the right is a 10 key pattern
* Layers include Functions, Media, Numpad, Navigation, Mouse, System, and Lighting
> Added new layout to XD75. See Readme for details

- docs/feature_tap_dance.md
* Added more comments
* Documentation for 'quad function' tap dance now suggests to use the
user's directory, and explains how to do so.
> Update to tap dance docs

- keyboards/frosty_flake/keymaps/nikchi/keymap.c
Removed need to enumerate all emojis in code for tap dances
> infinite emoji

- layouts/community/60_ansi/mechmerlin-ansi/readme.md
- layouts/community/60_ansi/readme.md
Readme was looking a little sparse. This is a no code change commit.
> Edit readmes for userspace layouts for 60_ansi

- keyboards/jd40/jd40.h
- keyboards/jd40/keymaps/default/keymap.c
ThatCynicalBastard reported that jd40 was not compiling for him.
Turns out that the LAYOUT macro was of the kc variant. 
Made a new LAYOUT without all the KC_##
> LAYOUT_kc problems with JD40

- tmk_core/common/avr/bootloader.c
> Fix compile issues for atmega328p

- keyboards/orthodox/keymaps/rfvizarra/config.h
- keyboards/orthodox/keymaps/rfvizarra/keymap.c
- keyboards/orthodox/keymaps/rfvizarra/readme.md
* Added a personal layout for the orthodox keyboard
> A personal layout for the orthodox keyboard

- keyboards/iris/matrix.c
- keyboards/levinson/matrix.c
- layouts/community/ortho_4x12/bakingpy/keymap.c
Backlight enabled flag was not being used while sending backlight level info
> Fix led enabled slave

- docs/README.md
- docs/contributing.md
Fixed a few hyperlinks in docs/README.md and docs/contributing.md.
> Fix readme and contributing hyperlinks

- keyboards/bigswitch/bigswitch.c
- keyboards/bigswitch/config.h
Wait for 1 second before turning on RGB to get debug messages on
console.
- configure HSV color, on a brand new pro micro the default values are
0, 0, 0
> Wait for QMK to initialize before configuring RGB

- keyboards/chibios_test/readme.md
- keyboards/chibios_test/stm32_f072_onekey/readme.md
- keyboards/chibios_test/stm32_f103_onekey/readme.md
- keyboards/chibios_test/teensy_lc_onekey/readme.md
This is primarily done to get rid of more QMK API errors
This is a no logic change commit, only has addition of sparse/basic readmes.
> Add some ChibiOS Test Readmes

- docs/feature_leader_key.md
- `register_code`/`unregister_code` are not the recommended way to do macro.
- Provide some details I wish I had found when first used the leader
functionality.
> Refresh & improve leader documentation page

- keyboards/deltasplit75/matrix.c
- keyboards/ergo42/matrix.c
- keyboards/fourier/matrix.c
- keyboards/handwired/dactyl_manuform/matrix.c
- keyboards/iris/matrix.c
- keyboards/lets_split/matrix.c
- keyboards/levinson/matrix.c
- keyboards/nyquist/keymaps/hexwire/keymap.c
- keyboards/nyquist/matrix.c
- keyboards/nyquist/rules.mk
- keyboards/redox/matrix.c
- keyboards/vitamins_included/matrix.c
- keyboards/viterbi/matrix.c
- keyboards/zen/matrix.c
- Switch default Nyquist revision to Rev. 2
- Port over LED slave changes from Iris/Levinson
- Fix issue with D2 pin being set for various split boards in debounce algorithm
> Fix nyquist

- keyboards/bigseries/bigseries.h
- keyboards/bigseries/info.json
- keyboards/bigseries/keymaps/8ball/keymap.c
- keyboards/bigseries/keymaps/default/keymap.c
- keyboards/bigseries/keymaps/leddance/keymap.c
- `bigseries.h`: `KEYMAP` is now `LAYOUT`
- All keymaps updated to use new `LAYOUT` macro
- Add `info.json`
> Refactor and Configurator updates for Woodkeys/NovelKeys Big Series

- keyboards/ergodox_ez/keymaps/bpruitt-goddard/config.h
- keyboards/ergodox_ez/keymaps/bpruitt-goddard/keymap.c
- keyboards/ergodox_ez/keymaps/bpruitt-goddard/readme.md
- keyboards/ergodox_ez/keymaps/bpruitt-goddard/rules.mk
Ergodox EZ layout with Included KLE image and link to provide others with a quick idea of what features the layout provides.
> Add bpruitt-goddard Ergodox Layout

- keyboards/bigswitch/bigswitch.c
- avoid writing to the eeprom when possible
> Switch to noeeprom variants of rgb fns

- keyboards/ergodox_infinity/keymaps/gordon/config.h
- keyboards/ergodox_infinity/keymaps/gordon/keymap.c
- keyboards/ergodox_infinity/keymaps/gordon/rules.mk
- users/gordon/gordon.c
- users/gordon/gordon.h
- users/gordon/rules.mk
* Moved tap dance enums to gordon.h
* Moved tap dance aliases to gordon.h
* Moved TD to user space
* Added config file with preventing mods sticking
* Added a few keys to keymaps
Lots of things left to do, like using the new raise/lower feature, more LED customizaton, and updates to chimera layout.
> Updates to gordon keymaps

- keyboards/christmas_tree/christmas_tree.h
- keyboards/christmas_tree/info.json
- keyboards/christmas_tree/keymaps/default/keymap.c
- `christmas_tree.h`
- `KEYMAP` renamed to `LAYOUT`
- `keymaps/default/keymap.c`
- Keymap updated and refactored to use `LAYOUT` macro
- `#include "christmas_tree.h"` updated to `#include QMK_KEYBOARD_H`
- Update `info.json`
> Refactor and Configurator update for Christmas Tree

- keyboards/kbd8x/rules.mk
> Enable KBD8x Underglow RGB

- docs/hardware_keyboard_guidelines.md
> Remove bootloader key in info.json documentation

- keyboards/playkbtw/ca66/keymaps/kelorean/keymap.c
on layer0
fixed swapped KC_PGUP and KC_UP
on layer 1 and 2
added KC_GRV
on layer 3
moved RGB functions around a bit
and tidied everything up a bit
> Fixed mistake to kelorean keymap for ca66

- docs/feature_rgblight.md
- docs/keycodes.md
- quantum/quantum.c
- quantum/quantum_keycodes.h
- quantum/rgblight.c
- quantum/rgblight.h
* add rgblight mode 35 (R,G,B cyclic mode) into quantum/rgblight.[ch], etc
* Update docs
> Add rgblight mode 35 (R,G,B test mode)

- keyboards/zen/keymaps/jwlawrence/config.h
- keyboards/zen/keymaps/jwlawrence/keymap.c
- keyboards/zen/keymaps/jwlawrence/rules.mk
> Added new keymap for zen keyboard

- keyboards/tkc1800/keymaps/yanfali/config.h
- keyboards/tkc1800/keymaps/yanfali/keymap.c
- disable i2c to avoid hid spam
- set capslock -> lctl_t(kc_esc)
- OSX mode - reverse GUI and ALT
> Add TKC keymap

- keyboards/fortitude60/info.json
- keyboards/fortitude60/rev1/rev1.h
Refactor:
- removed `LAYOUT_ortho_5x12`
- right number of keys, but wrong layout
Configurator:
- added `info.json`
> Fortitude60: Refactor and Configurator support

- keyboards/felix/info.json
Needed a small change in this file to solve a Configurator API warning.
> Felix info.json fix

- keyboards/tomato/rules.mk
> this allows programming the device throught the reset keycode.

- keyboards/chimera_ortho/keymaps/dcompact/README.md
- keyboards/chimera_ortho/keymaps/dcompact/keymap.c
- keyboards/planck/keymaps/dcompact/README.md
- keyboards/planck/keymaps/dcompact/keymap.c
- keyboards/planck/keymaps/dcompact/rules.mk
This PR is intended as the first update to my keymaps.
It adds Stenography support for the Planck version of the layout.
It also makes fixes and updates to the PR.
That's bout it! 😸
> DCompact Update 1

- keyboards/meme/rules.mk
This was resulting in incorrect flashing of the meme keyboard.
> Change ucontroller from 32u4 to 32u2

- keyboards/tada68/keymaps/pascamel/keymap.c
- keyboards/tada68/keymaps/pascamel/readme.md
- keyboards/tada68/keymaps/pascamel/rules.mk
I created this new layout which is a mix of different existing layouts - I could not find one that would match my needs so I juste created it!
> Another alternative layout for TADA68

- keyboards/ergodox_ez/keymaps/kou/keymap.c
- keyboards/ergodox_ez/keymaps/kou/readme.md
I created my custom keymap of Ergodox.
Please add me your project, thank you!
> feat: add a keymap of kou

- keyboards/tada68/keymaps/unix/config.h
- keyboards/tada68/keymaps/unix/keymap.c
- keyboards/tada68/keymaps/unix/readme.md
- keyboards/tada68/keymaps/unix/rules.mk
Added my custom layout for the tada68. Should be more *nix friendly
> added tada68:unix layout

- keyboards/niu_mini/keymaps/default/keymap.c
Added comments to graphically show the default keymap for the Niu Mini for each of the layers.
> Added comments to Niu Mini default keymap

- keyboards/planck/keymaps/default/keymap.c
This triggered col 0 for the Light.
> Fix the fn/backlight key for the Light

- keyboards/jj40/README.md
It took me several hours to get jj40 flashed and working and I think the hint about HIDBootFlash helps.
> Added a description how to flash in Windows

- keyboards/contra/keymaps/maxr1998/config.h
- keyboards/contra/keymaps/maxr1998/keymap.c
- keyboards/contra/keymaps/maxr1998/readme.md
- keyboards/contra/keymaps/maxr1998/rules.mk
Contra/Planck keymap that's highly adjusted to personal preferences with focus on ISO-DE compatibility. Supports LED underglow, has a numpad layer and arrow keys.
> Maxr1998's contra keymap

- keyboards/helix/info.json
- keyboards/helix/rev1/info.json
- keyboards/helix/rev2/config.h
- keyboards/helix/rev2/info.json
Fixed an issue that qmk configrator can not build.
> Helix fix configrator problem

- keyboards/lets_split/sockets/config.h
Users ran in to an RGB issue. I had the wrong pin set in the config.
> Fixed pin for RGB

- keyboards/the_ruler/info.json
- keyboards/the_ruler/keymaps/default/keymap.c
- keyboards/the_ruler/the_ruler.h
Not too much to do here other than change `KEYMAP` to `LAYOUT` and add an appropriate `info.json`
> The Ruler QMK Configurator Support

- keyboards/tanuki/info.json
> Tanuki Configurator support

- keyboards/ergodone/readme.md
Updated some broken hyperlinks in the ErgoDone readme file
> Fix hyperlinks in ErgoDone readme.md

- docs/config_options.md
- docs/feature_advanced_keycodes.md
Also improve documentation for related settings.
I am not a native English speaker, please tell me about any language mistake.
> Add documentation for TAPPING_FORCE_HOLD (#2957)

- keyboards/tada68/keymaps/bazooka/config.h
- keyboards/tada68/keymaps/bazooka/keymap.c
- keyboards/tada68/keymaps/bazooka/readme.md
- keyboards/tada68/keymaps/bazooka/rules.mk
- keyboards/tanuki/info.json
Adding my personal Tada68 layout onto the base fork. 
I'm new to this, I tried following the current guidelines, but if anything needs to be changed, feel free to change it as needed. I'm open to any suggestions or edits to my code, considering that I used a funky unsigned integer to get things working the way I wanted it to.
> Adding FireBazooka's Tada68 Keymap

- keyboards/al1/al1.c
- keyboards/al1/matrix.c
This is me testing in production....sigh
> Al1 Configurator compile fix redux

- keyboards/iris/readme.md
- Updating `readme.md` in `keyboards/iris/readme.md` to match website links
> Docs update in iris readme

- keyboards/noxary/268/268.c
- keyboards/noxary/268/keymaps/default/keymap.c
- keyboards/noxary/268/keymaps/sixtyeight/keymap.c
> Fix header references

- users/mtdjr/mtdjr.c
Corrected issue causing compile failure referenced in commit 89e8563be53ee2da0e1009a2657f34e62f3b05c9
> Correct conditional in mtdjr userspace

- docs/contributing.md
- docs/custom_quantum_functions.md
- docs/getting_started_getting_help.md
Separated out this commit from https://github.com/qmk/qmk_firmware/pull/3365.
> Replace gitter links with Discord.

- layouts/community/ortho_4x12/bakingpy/keymap.c
- layouts/community/ortho_4x12/bakingpy/rules.mk
- quantum/audio/song_list.h
Fixes issues #3345, #3346, #3347, #3348, #3349, #3350
> Add macro to play All Star chorus and print lyrics

- keyboards/helix/rev1/rev1.h
Attempting to fix an error in the Configurator API error log.
> Helix rev1 refactor: deleted extra commas

- layouts/community/ortho_4x12/bakingpy/config.h
- layouts/community/ortho_4x12/bakingpy/keymap.c
- quantum/audio/song_list.h
Speed was too intense when I finally got to test it on my board
> Slow down speed of All Star song by factor of 4

- keyboards/jc65/readme.md
- keyboards/jc65/v32a/readme.md
- keyboards/jc65/v32u4/readme.md
This is a no code change commit. 
Changes
1. Add appropriate whitespaces so things don't appear all in one line
2. Add reset info for ps2avrgb variant
3. Add flashing instructions for windows
4. Add disclaimer about QMK + ps2avrgb issues
5. Wordsmith
> Update JC65 Readme

- docs/newbs.md
- docs/newbs_learn_more_resources.md
add resources for git
add git tut from codecademy which is free and takes about 2 hours to complete, giving new members better understanding of what git is and how to navigate and use it
add git game, because games confuse people to think they are having fun while they are actually learning git
> add resources for git

- keyboards/planck/keymaps/callum/keymap.c
> Keymap updates

- drivers/avr/i2c_slave.c
- drivers/avr/i2c_slave.h
- Add I2C slave library for general use.
> Add I2C slave library

- shell.nix
add avrdude do dependency list to allow flashing via make
> allow building with nix on darwin

- docs/getting_started_github.md
> Adjust prompt to be more recognizable

- quantum/template/avr/config.h
- quantum/template/base/keymaps/default/config.h
- quantum/template/ps2avrgb/config.h
Making sure this is consistent with #3404, as mentioned by @drashna in
that PR.
> Update template config.h with `#pragma once`

- keyboards/satan/keymaps/lepa/keymap.c
- keyboards/satan/keymaps/lepa/readme.md
- keyboards/satan/keymaps/lepa/rules.mk
Hello,
I added a satan keymap. Do I need to do something else?
Thanks
> Satan keymap

- quantum/keymap_extras/keymap_hungarian.h
Hi,
I created a Hungarian keymap. It covers most of the characters, however, there are 3 rarely used symbols which I could not name properly. For the sake of completeness, I left them in the keymap file, in commented lines.
> Hungarian keymap added

- keyboards/ergo42/keymaps/default-underglow/config.h
- keyboards/ergo42/keymaps/default-underglow/keymap.c
- keyboards/ergo42/keymaps/default-underglow/rules.mk
Underglow support for Ergo42 default keymap
> Transport underglow implementation to default map

- keyboards/iris/keymaps/xyverz/keymap.c
I was missing the KC_BSLS from my Dvorak layer, so I needed to add it back in.
> Fixed Dvorak layer

- keyboards/handwired/nicekey/config.h
- keyboards/handwired/nicekey/keymaps/default/keymap.c
- keyboards/handwired/nicekey/nicekey.c
- keyboards/handwired/nicekey/nicekey.h
- keyboards/handwired/nicekey/readme.md
- keyboards/handwired/nicekey/rules.mk
A one button "keyboard" that prints random compliments when it is pressed. A little summer project that I made together with my younger sister for a https://mindlevel.net challenge.
> Base for the nicekey keyboard

- keyboards/iris/keymaps/jennetters/config.h
- keyboards/iris/keymaps/jennetters/keymap.c
- keyboards/iris/keymaps/jennetters/readme.md
- keyboards/iris/keymaps/jennetters/rules.mk
Re-write for improved readability.
> jennetters iris keymap

- keyboards/ckeys/obelus/keymaps/default/keymap.c
- keyboards/ckeys/obelus/obelus.h
As the title says, but also used this opportunity to fix up a few formatting and readme items.
> Update KEYMAP to LAYOUT for ckeys obelus

- docs/feature_advanced_keycodes.md
I couldn't understand this sentence at first owing to the confusion
between right meaning "correct," and right meaning "right-handed."
> Clarify "right" -> "right-handed"

- keyboards/lets_split/sockets/config.h
- keyboards/vitamins_included/config.h
- keyboards/vitamins_included/rev1/config.h
- keyboards/vitamins_included/rules.mk
Implemented fixes as disgussed here: https://github.com/qmk/qmk_firmware/issues/3448
> Feedback fixes

- docs/feature_dynamic_macros.md
I'm reading through the docs, trying to clarify and clean where I can.
I noticed that this page only refers to the instance of implementing
dynamic macros on a planck, and I thought it would be worthwhile to
abstract it and add some context.
> Update docs: Dynamic Macros

- docs/feature_grave_esc.md
Not much to say here, this page is pretty simple.
> Format Grave Escape documentation

- keyboards/helix/rev2/keymaps/five_rows_jis/keymap.c
* display of LED mode
* refactoring
* modified a keymap
* use extra jp header
> refactoring and modifief to helix five rows jis

- docs/feature_rgblight.md
In addition to rewriting this page quite a lot, I added the list of animation modes. The Hardware Modification section could use some more fleshing out, almost all of the information that was there is kind of redundant.
> Improve RGB lighting documentation

- docs/feature_rgb_matrix.md
- docs/hardware_drivers.md
- Minor formating in rgb matrix page
- Added a short discription for is31fl3731 in drivers page
> RGB Driver Documentation Update

- keyboards/catch22/keymaps/default/keymap.c
> Update keymap to be numpad

- keyboards/ergodone/keymaps/eozaki/keymap.c
- keyboards/ergodone/keymaps/eozaki/readme.md
A new ergodone layout, mostly changing L0 layout from default.
> Custom L0 layout for ergodone

- keyboards/al1/keymaps/default/keymap.c
- keyboards/al1/keymaps/splitbs/keymap.c
- Switch FN1 to MO(1) and other such changes
- Add a RESET key
> Update AL1 default keycaps to new QMK standards

- keyboards/iris/keymaps/broswen/config.h
- keyboards/iris/keymaps/broswen/keymap.c
- keyboards/iris/keymaps/broswen/rules.mk
> Adding broswen keymap for iris split keyboard.

- keyboards/atreus/readme.md
- readme.md
As requested in https://github.com/qmk/qmk.fm/pull/12#issuecomment-413251048
> Add Atreus as an official board.

- message.mk
- tmk_core/rules.mk
change compile end message like this.
```
* Your file is too big! 28798/28672 (126 over)
```
and
```
* File size is fine - 23886/28672 (4786 free)
```
> change messege at 'check-size' target

- keyboards/1up60hse/info.json
- keyboards/1up60hse/readme.md
My bad....I'm sorry. I forgot to check that info.json had the correct name which is `LAYOUT_60_ansi`
> forgot to rename the layout correctly

- keyboards/ut47/info.json
- keyboards/ut47/readme.md
- added `info.json`
- markdown formatting on `readme.md`
> UT47 Configurator support and readme cleanup

- keyboards/bface/keymaps/kpeatt/keymap.c
- keyboards/bface/keymaps/kpeatt/readme.md
Glad to see the PR for this keyboard got shipped! This is the keymap I use on mine.
> [keymap] Added personal keymap for bface

- keyboards/tada68/readme.md
Remove confusing mention of a "Windows" computer.
> Keyboard: Fix tada68 Linux readme

- keyboards/blockey/blockey.h
- keyboards/blockey/info.json
- keyboards/blockey/keymaps/default/keymap.c
- keyboards/blockey/keymaps/eucalyn/keymap.c
- keyboards/blockey/readme.md
Edited for readability.
Deleted TMK-syntax macro block. Edited for readability.
Edited image link (link previously referenced a single-image album).
Added `info.json`.
> Blockey refactor

- layouts/community/ortho_4x12/wanleg/keymap.c
- users/wanleg/rules.mk
to resolve issue [#3680](https://github.com/qmk/qmk_firmware/issues/3680)
> fix conditionals in userspace rules.mk

- layouts/community/60_ansi/mechmerlin-ansi/keymap.c
Let it be known that MechMerlin says, "QMK IS DA BEST"
Until I can figure out what other layouts I want this in, it will stay in LAYOUT_60_ansi.
> Hold for MO and Tap for TG

- keyboards/tv44/keymaps/budi/keymap.c
- keyboards/tv44/keymaps/budi/readme.md
Updates July 2018:
- I guess I don't play games that much anymore
- SUGDW modifiers
- Somehow LALT(LSFT(KC_RET)) does not register correctly on my mac
> update to budi's tv44

- keyboards/alpha/keymaps/default/keymap.c
- keyboards/alpha/readme.md
- keyboards/lets_split/keymaps/pyrol/config.h
- keyboards/lets_split/keymaps/pyrol/keymap.c
- keyboards/lets_split/keymaps/pyrol/rules.mk
> PyroL Let's Split keymap + Alpha keymap modifications

- keyboards/1up60rgb/keymaps/raffle/keymap.c
- keyboards/1up60rgb/keymaps/raffle/readme.md
> initial migration of raffle 1up60rgb

- docs/_sidebar.md
- docs/_summary.md
- docs/feature_backlight.md
- docs/ref_functions.md
And start documenting functions for different features
> Add page with useful functions for QMK 

- keyboards/dz60/keymaps/xtonhasvim/keymap.c
- keyboards/niu_mini/keymaps/xtonhasvim/config.h
- keyboards/niu_mini/keymaps/xtonhasvim/keymap.c
- keyboards/niu_mini/keymaps/xtonhasvim/rules.mk
- users/xtonhasvim/fancylighting.c
- users/xtonhasvim/fancylighting.h
- users/xtonhasvim/rules.mk
- users/xtonhasvim/xtonhasvim.c
- users/xtonhasvim/xtonhasvim.h
Sync'ing up some changes to my layouts that I already have checked in here. Of note is a useless but fun feature where lower+enter sends a rainbow wave across the underglow. I also removed the separate _EDIT layer since that was sort of confusing.
> xtonhasvim updates

- keyboards/massdrop/alt67/readme.md
- keyboards/massdrop/ctrl/readme.md
Massdrop keyboards readme update for flashing instructions
> Massdrop keyboards readme update

- keyboards/massdrop/alt67/readme.md
- keyboards/massdrop/ctrl/readme.md
Updating CTRL and ALT readme for make command example to reflect directory change
> Update CTRL and ALT keyboard readme

- docs/becoming_a_qmk_collaborator.md
Just some tiny things here, and I added a heading ;)
> Tweak the wording in "Becoming a QMK Collaborator"

- keyboards/massdrop/alt67/info.json
- keyboards/massdrop/ctrl/info.json
> CTRL and ALT keyboard json fix

- layouts/community/60_ansi/mechmerlin-ansi/keymap.c
- layouts/community/60_ansi/mechmerlin-ansi/readme.md
- layouts/community/60_ansi/mechmerlin-ansi/rules.mk
- layouts/community/60_ansi_split_bs_rshift/mechmerlin-split/keymap.c
- layouts/community/60_ansi_split_bs_rshift/mechmerlin-split/rules.mk
- layouts/community/66_ansi/mechmerlin/keymap.c
- layouts/community/66_ansi/mechmerlin/rules.mk
- layouts/community/75_ansi/mechmerlin-75_ansi/keymap.c
- layouts/community/75_ansi/mechmerlin-75_ansi/rules.mk
- users/mechmerlin/mechmerlin.c
- users/mechmerlin/mechmerlin.h
- users/mechmerlin/readme.md
- users/mechmerlin/rules.mk
Move some of the more common things I'm doing in the layouts/community directory and putting it in my own userspace.
> Merlin Learns to QMK

- keyboards/ergo42/keymaps/yshrsmz/config.h
- keyboards/ergo42/keymaps/yshrsmz/keymap.c
- keyboards/ergo42/keymaps/yshrsmz/rules.mk
- keyboards/helix/rev2/keymaps/yshrsmz/config.h
- keyboards/helix/rev2/keymaps/yshrsmz/keymap.c
- keyboards/helix/rev2/keymaps/yshrsmz/readme.md
- keyboards/helix/rev2/keymaps/yshrsmz/rules.mk
- keyboards/lets_split/keymaps/yshrsmz/config.h
- keyboards/lets_split/keymaps/yshrsmz/keymap.c
- keyboards/lets_split/keymaps/yshrsmz/rules.mk
- keyboards/nyquist/keymaps/yshrsmz/config.h
- keyboards/nyquist/keymaps/yshrsmz/keymap.c
- keyboards/nyquist/keymaps/yshrsmz/rules.mk
added my keymaps for erg42, helix, lets_split and nyquist.
> add yshrsmz keymaps

- layouts/community/ortho_4x12/symbolic/README.md
- layouts/community/ortho_4x12/symbolic/config.h
- layouts/community/ortho_4x12/symbolic/keymap.c
- layouts/community/ortho_4x12/symbolic/rules.mk
> share my ortho_4x12 layout symbolic

- keyboards/levinson/keymaps/xtonhasvim/config.h
- keyboards/levinson/keymaps/xtonhasvim/keymap.c
- keyboards/levinson/keymaps/xtonhasvim/readme.md
- keyboards/levinson/keymaps/xtonhasvim/rules.mk
Okay, this is the last keyboard... until the next one.
> xtonhasvim Levinson

- keyboards/jj40/keymaps/like_jis/config.h
- keyboards/jj40/keymaps/like_jis/keymap.c
- keyboards/jj40/keymaps/like_jis/rules.mk
I added a keymap like a JIS keyboard for JJ40.
Thank you always.
> Added a keymap like a JIS keyboard for JJ40.

- util/linux_install.sh
Changed `grep` command in installation script to match Fedora in `/etc/os_release`
> Fix installation for Linux Fedora

- keyboards/massdrop/alt/keymaps/default/keymap.c
- keyboards/massdrop/alt/keymaps/mac/keymap.c
- tmk_core/protocol/arm_atsam/i2c_master.c
Added additional End key on layer 1 to match key cap
> ALT keymap update and LED driver brightness mismatch fix

- keyboards/crkbd/config.h
- keyboards/crkbd/keymaps/default/config.h
- keyboards/crkbd/keymaps/like_jis/config.h
>  Crkbd: move I2C and Serial defines to keyboard's config.h

- keyboards/macropad/config.h
- keyboards/macropad/info.json
- keyboards/macropad/keymaps/default/config.h
- keyboards/macropad/keymaps/default/keymap.c
- keyboards/macropad/keymaps/default/readme.md
- keyboards/macropad/macropad.c
- keyboards/macropad/macropad.h
- keyboards/macropad/readme.md
- keyboards/macropad/rules.mk
As requested by Jukem on the QMK Discord.
> New Keyboard: Treasure Macropad

- keyboards/planck/keymaps/jetpacktuxedo/config.h
- keyboards/planck/keymaps/jetpacktuxedo/keymap.c
controlled by dip 3 with pitch modulated by the knob
> add clicky support to my keymap

- keyboards/model01/config.h
- keyboards/model01/keymaps/default/keymap.c
- keyboards/model01/leds.c
- keyboards/model01/leds.h
- keyboards/model01/rules.mk
- quantum/rgb_matrix.c
This brings model01 up to feature complete, I think.
> keyboardio model01: rgbmatrix support

- keyboards/jc65/v32a/config.h
- keyboards/jc65/v32a/rules.mk
> Optimize size of JC65/v32a keyboard

- keyboards/hadron/config.h
- keyboards/hadron/keymaps/default/rules.mk
- keyboards/hadron/rules.mk
- keyboards/hadron/ver0/config.h
- keyboards/hadron/ver2/config.h
- keyboards/hadron/ver2/rules.mk
> Optimize size of Hadron keyboard

- keyboards/vitamins_included/config.h
- keyboards/vitamins_included/keymaps/default/config.h
- keyboards/vitamins_included/keymaps/default/keymap.c
- keyboards/vitamins_included/keymaps/default/rules.mk
- keyboards/vitamins_included/rules.mk
> Optimize size of Vitamins_Included keyboard

- keyboards/pearl/config.h
> Optimize size of Pearl keyboard

- keyboards/converter/usb_usb/ble/config.h
- keyboards/converter/usb_usb/ble/rules.mk
> Optimize size of USB_USB BLE Converter

- keyboards/rama/m60_a/config.h
- keyboards/zeal60/zeal60.c
- keyboards/zeal60/zeal60_api.h
No core changes here, just adding some extra magic.
> RAMA M60-A minor changes

- docs/feature_userspace.md
Because leaving review comments on a PR that's already been merged doesn't make any sense.
> Spell-check update for Userspace documentation

- keyboards/planck/keymaps/jetpacktuxedo/keymap.c
Also worked around my busted dipswitch 2...
Thanks for the help on this @drashna
> Clicky frequency modulation

- tmk_core/chibios.mk
Added st-link_cli SWD flashing.
But I don't add st-link_cli to install script, because it needs registlation to download.
> add st-link_cli flashing

- lib/arm_atsam/packs/atmel/SAMD51_DFP/1.0.70/gcc/gcc/samd51j18a_flash.ld
- tmk_core/common/arm_atsam/bootloader.c
- tmk_core/protocol/arm_atsam/md_bootloader.h
- tmk_core/protocol/arm_atsam/startup.c
Adds support for CTRL keyboards to enter bootloader via bootloader_jump()
> CTRL keyboard bootloader_jump support

- keyboards/tada68/keymaps/shalzz/config.h
- keyboards/tada68/keymaps/shalzz/keymap.c
- keyboards/tada68/keymaps/shalzz/readme.md
- keyboards/tada68/keymaps/shalzz/rules.mk
Made some improvements (atleast for me) to the already great unix layout for tada68.
> tada68: add shalzz's layout

- docs/feature_unicode.md
- quantum/process_keycode/process_unicode_common.c
- quantum/process_keycode/process_unicode_common.h
Co-authored-by: kdb424 <kdb424@gmail.com>
Co-authored-by: Konstantin <vomindoraan@gmail.com>
> Add send_unicode_hex_string function

- docs/custom_quantum_functions.md
A small improvement in readability.
> Add C hint to inline code

- keyboards/mint60/keymaps/default/keymap.c
- keyboards/mint60/keymaps/eucalyn/keymap.c
> Keyboard: Mint60: Set SAFE_RANGE

- docs/_sidebar.md
- docs/_summary.md
- docs/arm_debugging.md
- Added a detailed (but saddly long) debugging guide.
- Modified sidebar and summary to include the links.
> ARM SWD guide

- keyboards/helix/config.h
- keyboards/helix/rev2/keymaps/five_rows/config.h
- keyboards/helix/rev2/keymaps/five_rows/keymap.c
- keyboards/helix/rev2/keymaps/five_rows/rules.mk
- keyboards/helix/rev2/keymaps/led_test/config.h
- keyboards/helix/rev2/keymaps/led_test/rules.mk
Removed unnecessary mode by setting rgblight.c modes.
> Helix five_rows keymap reduced size

- keyboards/planck/keymaps/jcorrado/keymap.c
- keyboards/planck/keymaps/jcorrado/readme.md
Integrated feedback from @noroadsleft on my prior PR #4081
> Added Planck keymap: jcorrado

- docs/feature_unicode.md
* Adds a much needed description of how the UCIS mode works
* Adds mention of the "set unicode input mode" function and how it works
* Formatting for clarity
* Add US Intl layout information
> Update and clarify Unicode documentation

- docs/feature_rgblight.md
- quantum/rgblight.h
Add a temporary comment. The content is a contrast table of old magic number and new symbol.
> Add a temporary comment to quantum/rgblight.h to aid migration.

- docs/custom_quantum_functions.md
> 誤字修正(Typo correction)

- keyboards/planck/keymaps/skug/config.h
- keyboards/planck/keymaps/skug/keymap.c
- keyboards/planck/keymaps/skug/readme.md
- keyboards/planck/keymaps/skug/rules.mk
Now with an image of the layout and an actual readme
> Reworked layout

- keyboards/converter/sun_usb/type5/keymaps/sigma/keymap.c
- keyboards/converter/sun_usb/type5/keymaps/sigma/readme.md
- keyboards/converter/sun_usb/type5/keymaps/sigma/rules.mk
- users/sigma/config.h
- users/sigma/rules.mk
- users/sigma/sigma.c
- users/sigma/sigma.h
Also add users/sigma, which contains useful code for keymaps.
> add sun_usb keymap for sigma

- docs/how_keyboards_work.md
- docs/keycodes_basic.md
- docs/reference_glossary.md
I noticed that the link to the HID specification was broken so I fixed it, also at the same time fixed some of the wording/grammar/typos to make it more correct english. I am not a native English but fluent enough (imho).
> Fix documentation

- docs/ref_functions.md
Mainly, this addes some examples for the tri layer functions, so it's clear how to use them.
> Some cleanup of the Useful Functions docs

- keyboards/whitefox/keymaps/konstantin/config.h
- keyboards/whitefox/keymaps/konstantin/keymap.c
Added virtual desktop controls and changed a few keys around.
> Update whitefox/konstantin keymap

- layouts/community/ergodox/qwerty_code_friendly/keymap.c
- layouts/community/ergodox/qwerty_code_friendly/readme.md
Missed some edits to the readme.
> qwerty_code_friendly: update readme, comments

- keyboards/iris/keymaps/vyolle_steno/rules.mk
Title says it all.  Noroadsleft practically wrote a small book on how to use git properly, which I appreciate greatly.
> Renabled EXTRAKEYS.

- docs/hardware_avr.md
> Update hardware config warnings to be more accurate

- docs/feature_advanced_keycodes.md
- docs/keycodes_us_ansi_shifted.md
And some formatting and grammar corrections.
Closes #1037
> Add caveats for shifted characters

- util/macos_install.sh
> adds 'dfu-util' to macos_install.sh

- keyboards/xd87/config.h
- keyboards/xd87/keymaps/default/config.h
- keyboards/xd87/keymaps/default/keymap.c
- keyboards/xd87/keymaps/default/readme.md
- keyboards/xd87/readme.md
- keyboards/xd87/rules.mk
- keyboards/xd87/xd87.c
- keyboards/xd87/xd87.h
- layouts/default/tkl_iso/default_tkl_iso/keymap.c
* Add row/col pin configuration for XD87 PCB
* Add default ISO layout
> Keyboard: initial support for XD87

- keyboards/1upkeyboards/sweet16/keymaps/ridingintraffic/config.h
- keyboards/1upkeyboards/sweet16/keymaps/ridingintraffic/keymap.c
- keyboards/1upkeyboards/sweet16/keymaps/ridingintraffic/readme.md
- keyboards/1upkeyboards/sweet16/keymaps/ridingintraffic/rules.mk
This keymap for 1upkeyboards/sweet16 has many features:
3 layers
Momentary layer switching
16 pixel neopixel
Unicode Enabled
Tap dance enabled
The rgb also updates depending on what layer you are on, and then flips back when done.
> keymap for 1upkeyboards/sweet16 multilayers rgb lighting and tapdance

- util/new_keymap.sh
Discovered this while showing leonardvdj on discord how to create his own keymap.
> Bug: Users had to be in the /util directory to run the script

- users/spacebarracecar/readme.md
Trying to explain my abomination of code
> Adding a readme to my userspace

- tmk_core/protocol/chibios/usb_main.c
> Fix mouse_send() on chibiOS so it won't lock up the firmware

- keyboards/planck/keymaps/jasperla/config.h
- keyboards/planck/keymaps/jasperla/keymap.c
- keyboards/planck/keymaps/jasperla/readme.md
- keyboards/planck/keymaps/jasperla/rules.mk
Here's my layout for the Planck, as developed for my rev5 board.
> add my planck rev 5 layout

- keyboards/iris/keymaps/transmogrified/Readme.md
- keyboards/iris/keymaps/transmogrified/config.h
- keyboards/iris/keymaps/transmogrified/keymap.c
Custom breathing function (so both sides of the board breath) when layer lock is enabled.
Changed light feature on regular layer toggle to simply increase brightness.
Added ctrlaltdel with tap dance
Added right hand ctrl alt with tap dance
Cleaned up code, added comments etc.
> update keymap transmogrified 

- keyboards/helix/serial.c
I'm sorry. I forgot to commit the last comment addition.
> helix serial.c: add some comment

- docs/feature_bootmagic.md
> Fix typo in feature_bootmagic.md

- quantum/split_common/split_util.c
@mechmerlin or @jackhumbert ..... right away please....
> Add pointer(?) to disable_JTAG to prevent compiler errors

- keyboards/miniaxe/config.h
- keyboards/miniaxe/info.json
- keyboards/miniaxe/keymaps/default/keymap.c
- keyboards/miniaxe/keymaps/underglow/keymap.c
- keyboards/miniaxe/keymaps/underglow/rules.mk
- keyboards/miniaxe/matrix.c
- keyboards/miniaxe/miniaxe.c
- keyboards/miniaxe/miniaxe.h
- keyboards/miniaxe/readme.md
- keyboards/miniaxe/rules.mk
Add a new keyboard MiniAxe.
I'm planing to sell this keyboard kit at the end of this month.
> Keyboard: Add a new keyboard MiniAxe.

- keyboards/niu_mini/keymaps/abhixec/keymap.c
- keyboards/niu_mini/keymaps/abhixec/readme.md
- keyboards/niu_mini/keymaps/abhixec/rules.mk
> Niu keymap WIP

- docs/flashing.md
Also fixed some typos in the numbering.
Feel free to give suggestions on the changes I added, I'm not entirely sure if it's up to documentation standards.
> Instructions on how to flash via STM32 bootloader

- util/linux_install.sh
Sabayon is a gentoo based distro with a different package manager. Does
not need any use flags or masking for the required packages.
Edit: Tested the install script successfully on my local system.
> Add distro support for sabayon

- keyboards/crkbd/rev1/serial_config.h
- keyboards/crkbd/rev1/split_scomm.c
- keyboards/crkbd/rev1/split_scomm.h
- keyboards/crkbd/rev1/split_util.h
- keyboards/crkbd/serial.c
- keyboards/crkbd/serial.h
Update files by copying from the helix
- `keyboards/crkbd/serial.h`
- `keyboards/crkbd/serial.c`
- `keyboards/crkbd/rev1/split_scomm.h`
- `keyboards/crkbd/rev1/split_scomm.c`
- `keyboards/crkbd/rev1/split_util.h`
Update `serial_config.h` for the patched `serial.c`.
> Update the serial.c of crkbd based on the helix-serial.c

- common_features.mk
- tmk_core/common.mk
- tmk_core/common/print.h
> Fix Terminal feature on ChibiOS

- docs/newbs_getting_started.md
> Improve wording, punctuation and capitalization in newbs_getting_started guide

- keyboards/redox/keymaps/finex/config.h
- keyboards/redox/keymaps/finex/keymap.c
- keyboards/redox/keymaps/finex/readme.md
- keyboards/redox/keymaps/finex/rules.mk
Hi, I've created a custom keymap with Colemak Mod DH-MK, MacOS layers and some minor macros. The keymap is suited for International layout with dead keys. Colemak Mod DH-MK looks like a good compromise when you have to type in both Italian and English languages.
> Finex Redox keymap

- keyboards/levinson/readme.md
This PR is to resolve issue #4444
> Update Levinson readme to support elite-c

- quantum/process_keycode/process_ucis.c
Revert code change that broke UCIS
> Fix UCIS code

- keyboards/idobo/keymaps/xaceofspaidsx/config.h
- keyboards/idobo/keymaps/xaceofspaidsx/keymap.c
- keyboards/idobo/keymaps/xaceofspaidsx/readme.md
- keyboards/idobo/keymaps/xaceofspaidsx/rules.mk
First time adding a keymap to the git repo, so I'm hoping i did things right. 
The keymap is based off xd75 with my changes, with leds enabled via the rules.mk file.
> Adding my new keymap for the Idobo

- util/linux_install.sh
https://www.archlinux.org/packages/core/x86_64/diffutils/
> Fix diffutils Arch Linux package name

- docs/newbs_testing_debugging.md
- tmk_core/common/print.h
see https://github.com/qmk/qmk_firmware/issues/4071
> Fixed docs/newbs_testing_debugging.md and tmk_core/common/print.h

- keyboards/ergodox_ez/keymaps/default/keymap.c
Remove unused code
Clean up process_record_user function based off [doc example](https://docs.qmk.fm/#/feature_macros?id=the-new-way-send_string-amp-process_record_user).
> Ergodox ez cleanup

- keyboards/fortitude60/keymaps/default/keymap.c
> [fortitude60] match default keymap comment to the implementation.

- quantum/audio/song_list.h
> Added Rick Roll

- docs/keycode.txt
- docs/keycodes.md
- docs/keycodes_basic.md
- quantum/keymap_common.c
- tmk_core/common/keycode.h
- tmk_core/common/report.h
Hi there guys!
I was just wondering if you were willing to accept this contribution.
I'm using it on my fork and even if I found out the numeric values on a MS webpage they work also on linux (I don't know about Mac OS though)
> Brightness up/down

- docs/zh-cn/README.md
This is mostly a test of the structure of the docs to see how to structure things :)
> Test out i18n of the docs

- keyboards/planck/keymaps/default/keymap.c
> Planck: Align Keycode Columns

- keyboards/converter/ibm_5291/info.json
> Invalid JSON

- keyboards/ergodox_ez/keymaps/hacker_dvorak/.gitignore
- keyboards/ergodox_ez/keymaps/hacker_dvorak/config.h
- keyboards/ergodox_ez/keymaps/hacker_dvorak/default.png.md
- keyboards/ergodox_ez/keymaps/hacker_dvorak/default_highres.png.md
- keyboards/ergodox_ez/keymaps/hacker_dvorak/gulpfile.js
- keyboards/ergodox_ez/keymaps/hacker_dvorak/keymap.c
- keyboards/ergodox_ez/keymaps/hacker_dvorak/package.json
- keyboards/ergodox_ez/keymaps/hacker_dvorak/readme.md
- keyboards/ergodox_ez/keymaps/hacker_dvorak/rules.mk
- quantum/keymap_extras/keymap_plover_dvorak.h
Work in Progress.
Programmer Dvorak based layout for the Ergodox EZ, with:
* Dvorak, Plover, Gaming, Mouse, Arrows, Numpad layers (duplicated for when OS keyboard layout is US or DV).
* Function/Shine layer.
* Shortcut layers.
* Bootmagic Magic layer.
> [WIP]: Hacker Dvorak

- keyboards/crkbd/keymaps/like_jis/config.h
- keyboards/crkbd/keymaps/like_jis/keymap.c
- keyboards/crkbd/keymaps/like_jis/oled_helper.c
- keyboards/crkbd/keymaps/like_jis/oled_helper.h
- keyboards/crkbd/keymaps/like_jis/rules.mk
Modified keymap
Modified like-jis keymap for crkbd.
- [x ] Keymap/Layout/Userspace (addition or update)
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
- [x ] I have added tests to cover my changes.
> Modified like-jis keymap for crkbd

- keyboards/puck/info.json
- keyboards/puck/puck.h
- keyboards/puck/readme.md
Adds Configurator layout rendering to the Puck, and updates layout macro and readme to use current QMK conventions for both.
Reformat layout macro to resemble physical keyboard layout.
Markdown formatting corrections.
> Puck Refactor, Configurator support and readme cleanup

- keyboards/rama/m10_b/config.h
- keyboards/rama/m10_b/keymaps/default/keymap.c
- keyboards/rama/m10_b/keymaps/knops/config.h
- keyboards/rama/m10_b/m10_b.c
- keyboards/rama/m10_b/rules.mk
- keyboards/rama/u80_a/config.h
- keyboards/rama/u80_a/rules.mk
- keyboards/wilba_tech/wt60_a/config.h
- keyboards/wilba_tech/wt65_a/config.h
- keyboards/wilba_tech/wt80_a/config.h
- keyboards/wilba_tech/wt_main.c
Added Dynamic Keymaps to M10-B (VIA Configurator support)
Also minor refactoring of `wt_main.c` so it can be used as-is in basic keyboard implementations likesuchas M10-B (i.e. conditionally compiles in the mono LED driver feature).
*
> Added Dynamic Keymaps to M10-B

- docs/feature_advanced_keycodes.md
Mostly, this just changes the headers for the features, so the entire section can be easily linked
> Enhance documentation for Tap-Hold functions

- docs/keycodes.md
Reorder and add OSL
Closes #4618
> Docs: Remove duplicate layer block in keycodes.md

- docs/newbs.md
And fix a typo or two.
Specifically, ad a like to Thomas Baart's blog, covering the QMK Basics.  It's a great read, and may be very helpful for new users, in understanding how different aspects of the firmware work. 
Additionally, I found a typo or two.
> Add additional resource links

- keyboards/bigswitch/keymaps/333fred/keymap.c
> Fix keymap build to send over remote desktop correctly.

- keyboards/cospad/info.json
- keyboards/cospad/readme.md
- added LAYOUT_gamepad_6x4 data
- renders as 4 rows by 6 columns visually
- fixed LAYOUT_numpad_6x4 data
- JSON objects were in the wrong order
- markdown formatting fixes
- made Hardware Availability address a hyperlink
- updated Docs links
> Cospad Configurator and readme update

- keyboards/planck/keymaps/mattly/config.h
- keyboards/planck/keymaps/mattly/keymap.c
- keyboards/planck/keymaps/mattly/readme.md
- keyboards/planck/keymaps/mattly/rules.mk
> My personal planck keymap

- drivers/arm/i2c_master.c
Removed minor comment in i2c library for stm32
Also removed the use of internal pullup. The internal pullup is too weak for fast speeds
* Fixed issue where internal pullup was used.
> Minor STM32 i2c driver cleanup

- keyboards/dichotomy/keymaps/alairock/keymap.c
Just a couple placement updates to my layout on the dichotomy keyboard. 
*
> update the alairock keymap for dichotomy

- keyboards/atom47/rev3/config.h
Enables RGB Animations in Atom47 rev3
> Enable RGB animations in Atom47

- docs/config_options.md
- docs/feature_leader_key.md
- quantum/process_keycode/process_leader.c
Add caveat to `LEADER_TIMEOUT` settings, to make it more clear about what to do when missing sequences.
* #2514
> Docs:  Add additional clarification to Leader Key documention

- keyboards/helix/pico/keymaps/mtei/config.h
- keyboards/helix/pico/keymaps/mtei/keymap.c
- keyboards/helix/pico/keymaps/mtei/rules.mk
Add mtei's keymap for Helix/pico
> Add Helix/pico keymap 'mtei'

- docs/feature_unicode.md
The original code example was unable to compile.
Error message:
``` 
error: expected ',' or ';' before ':' token
}:
```
*
> Feature Unicode example code fixed.

- keyboards/miuni32/config.h
- keyboards/miuni32/readme.md
Updating the number of RGB lights to 17 (from 7) to match the final version of Miuni32 (rev.1 and rev.2).
*
> [Miuni32] Update the # of LEDs to match the final version of PCB

- keyboards/kbd6x/keymaps/othi/config.h
- keyboards/kbd6x/keymaps/othi/keymap.c
- keyboards/kbd6x/keymaps/othi/readme.md
- keyboards/kbd6x/keymaps/othi/rules.mk
initial commit for Othi's HHKB layout keymap, covering multiple modifiers hold and vim-like support and german characters. If there's any suggestion i can be reached via mnpqraven on github or Othi#6661 on discord
I accidentally squashed README.md, i'll update it again later
> First PR for KBD6x HHKB layout keymap

- keyboards/planck/keymaps/ishtob/keymap.c
- users/ishtob/ishtob.h
> fix ishtob userspace compile error with planck grid

- .travis.yml
- util/travis_compiled_push.sh
Improve Travis Diagnostics
Help add some diagnostics on the git hash used during a build. Tracking down why the git hashes don't match for the pushed keyboard hex files from a valid tree they were built from.
*
> Improve diagnostics for build hashes

- docs/config_options.md
- quantum/split_common/serial.c
- quantum/split_common/split_util.c
Adds and updates documentation for various split keyboard options.
*
> Update split keyboard docs

- keyboards/planck/keymaps/mattly/keymap.c
more changes to my planck layout
> mattly: more tweaks

- keyboards/namecard2x4/keymaps/brainfuck/config.h
- keyboards/namecard2x4/keymaps/brainfuck/keymap.c
- keyboards/namecard2x4/keymaps/brainfuck/readme.md
I define keymap for brainfuck(<>+-.,[]) on namecard2x4.
> define brainfuck keymap

- keyboards/hadron/ver3/config.h
- keyboards/hadron/ver3/keymaps/ishtob/keymap.c
- keyboards/hadron/ver3/mcuconf.h
adding settings for using ERM motors (cellphone-type vibration motors) instead of standard LRA drivers for haptic feedback
*
> Adding default settings for ERM motors for Hadron v3 haptic feedback

- keyboards/preonic/rev3/info.json
File was saved with an invalid JSON structure.
I wonder what poor soul screwed that up... :innocent:
> Preonic rev. 3: fix info.json file

- keyboards/mehkee96/readme.md
Update mehkee96 readme with ps2avr flashing instructions. 
*
> Update mehkee96 readme with ps2avr flashing instructions

- keyboards/massdrop/alt/matrix.c
- keyboards/massdrop/ctrl/matrix.c
- tmk_core/common/arm_atsam/timer.c
- tmk_core/common/wait.h
- tmk_core/protocol/arm_atsam/arm_atsam_protocol.h
- tmk_core/protocol/arm_atsam/clks.c
- tmk_core/protocol/arm_atsam/clks.h
- tmk_core/protocol/arm_atsam/i2c_master.c
- tmk_core/protocol/arm_atsam/led_matrix.c
- tmk_core/protocol/arm_atsam/main_arm_atsam.c
- tmk_core/protocol/arm_atsam/usb/udi_cdc.c
- tmk_core/protocol/arm_atsam/usb/usb2422.c
This update is to get the arm_atsam branch timer and wait functions aligned with common QMK functions. It also includes a much simpler, rewritten method to microsecond delays to tighten timings. This update affects Massdrop's CTRL and ALT keyboards, and they have both been thoroughly tested.
Microsecond (us) delays are now handled by a busy wait loop according to MCU frequency. This replaces the system counter method which had an overhead of around 12us. The new method has an overhead less than 0.5us.
`TC5` device and supporting routines removed as it was the old us delay counter.
`wait_ms()` is now properly a macro to `CLK_delay_ms()`.
`wait_us()` is now properly a macro to `CLK_delay_us()`.
Removed `CLK_get_us()` as it has no use.
All calls to `CLK_get_ms()` have been replaced by …
> Update to arm_atsam wait and timer routines

- keyboards/alps64/keymaps/mechmerlin/keymap.c
- keyboards/alps64/keymaps/mechmerlin/readme.md
- keyboards/alps64/readme.md
Update the Alps64 readme, and add my own Alps64 Keymap using the Infinity LAYOUT.
> Alps64 Keymap + Readme Updates

- keyboards/minidox/keymaps/tw1t611/keymap.c
- keyboards/minidox/keymaps/tw1t611/readme.md
- keyboards/minidox/keymaps/tw1t611/rules.mk
> Add tw1t611/ german keyboard layout for minidox.

- quantum/audio/musical_notes.h
Changes rest term to avoid bug as per @drashna 
closes https://github.com/qmk/qmk_firmware/issues/4450
> Changed rest term

- keyboards/clueboard/66/keymaps/muzfuz/keymap.c
- keyboards/clueboard/66/keymaps/muzfuz/readme.md
- keyboards/clueboard/66/keymaps/muzfuz/rules.mk
- keyboards/dz60/keymaps/muzfuz/README.md
- keyboards/dz60/keymaps/muzfuz/keymap.c
- keyboards/planck/keymaps/muzfuz/config.h
- keyboards/planck/keymaps/muzfuz/keymap.c
- keyboards/planck/keymaps/muzfuz/readme.md
- keyboards/planck/keymaps/muzfuz/rules.mk
Adds keymaps for Planck, DZ60 and Clueboard66
👍
> Adds keymaps for muzfuz DZ60, Planck, Clueboard66

- common_features.mk
I feel it is a little simpler to make this change.
If someone disagrees with this change, I will close this PR.
There is no change in the code generated by this change.
> Change handling of CUSTOM_MATRIX in common_features.mk slightly.

- docs/feature_advanced_keycodes.md
Changed docs as per https://github.com/qmk/qmk_firmware/issues/3185
closes #3185
> Pointed LM Docs at expected keycodes

- tmk_core/common/action_layer.c
Fills in some FIXMEs with function documentation.
> Add some function comments in action_layer.c

- keyboards/ergodox_ez/keymaps/bdk/config.h
- keyboards/ergodox_ez/keymaps/bdk/keymap.c
- keyboards/ergodox_ez/keymaps/bdk/readme.md
- keyboards/ergodox_ez/keymaps/bdk/rules.mk
* 
I believe my code follows the code style, but please correct me if I'm wrong.
> Adding bdk keymap for ergobox_ez

- tmk_core/common/action_layer.c
Finish adding documentation in `action_layer.c`.
Additionally, reformatting the file to follow QMK Firmware's coding convention. 
No code changes were made.
> Finish adding documentation in action_layer.c

- keyboards/xd75/keymaps/skewwhiffy/keymap.c
Simple add of cursor keys to the skewwhiffy xd75 keymap.
> Add cursor keys to top layer

- keyboards/hhkb/keymaps/schaeferdev/README.md
- keyboards/hhkb/keymaps/schaeferdev/config.h
- keyboards/hhkb/keymaps/schaeferdev/keymap.c
- keyboards/hhkb/keymaps/schaeferdev/rules.mk
Added new HHKB layout which implements movement layer (VIM style + Mouse) while staying close to homerow. Contains some comfort-changes, particularly for Germans.
I am not entirely sure how I can put the correct Label on this PR, would be great if somebody could explain, or do it for me, thanks!
> schaeferdev layout for hhkb implementing movement layer (VIM style + Mouse)

- keyboards/do60/keymaps/crd/keymap.c
just sharing my simple do60 keymap
> Add crd's do60

- quantum/template/avr/config.h
- quantum/template/avr/template.c
- quantum/template/avr/template.h
- quantum/template/base/keymaps/default/config.h
- quantum/template/base/keymaps/default/keymap.c
- quantum/template/ps2avrgb/rules.mk
- quantum/template/ps2avrgb/template.c
- quantum/template/ps2avrgb/template.h
Update copyright date in our templates to 2019. 
*
> Stop living in the past! It's 2019!!

- docs/isp_flashing_guide.md
> Fix a typo in link to the Pro Micro ISP firmware

- quantum/keymap_common.c
Fix problem that MAGIC_SWAP_ALT_GUI will not be effective when OSM(mod) is used.
> Fix OSM(mod) problem

- tmk_core/common/action_util.c
This bug cause one shot mod not some time not work for ergodox infinity.
> Fix oneshot_time wrong type

- keyboards/dz60/keymaps/mechmerlin/keymap.c
Minor update to my dz60 keymap: Use `KC_GESC` on the base layer.
> Minor updates to my dz60 keymap

- docs/newbs.md
- docs/newbs_building_firmware_configurator.md
- docs/newbs_getting_started.md
I'm contributing the MechMerlin QMK Configurator docs from https://github.com/mechmerlin/qmk_setup/blob/master/qmk_configurator.md. I've edited it as necessary to point to the correct documentation links. 
This guide is pinned in several discord channels and has been mentioned many times in conversation or reddit links. It has provided much needed help for everyone using the QMK Configurator. 
Unfortunately,  the guide is invisible for people new to the hobby or those who just don't browse discord or the forums. I've encountered many users who go straight to the QMK Docs (good for them) to make their first keymap. QMK Configurator however is not very well mentioned in the docs. 
I will be deprecating my document once this is fixed. The document will contain links into QMK. 
*
> Contribute the MechMerlin QMK Configurator docs

- Makefile
Cherry picked from #4947.
When a keyboard has a DEFAULT_FOLDER, the make all:default invocation adds an additional duplicate make target. This wastes a few cpu cycles (about 45 seconds) preforming an unnecessary incremental build.
Before (note the extra rev5 compilation)
```
Making planck/rev5 with keymap default                                                                 [OK]
Making planck/light with keymap default                                                                [OK]
Making planck/rev1 with keymap default                                                                 [OK]
Making planck/rev2 with keymap default                                                                 [OK]
Making planck/rev3 with keymap default …
```
> Remove duplicate make invocations

- keyboards/alice/config.h
Fixes the last column pin and the number of LEDs on the TGR Alice matrix
> Fixed TGR Alice pinout and number of LEDs

- tmk_core/common/action_layer.c
- tmk_core/common/action_layer.h
Layer numbers can never be negative. Nuff said :)
* None.
> Change return type of layer_switch_get_layer() to uint8_t

- keyboards/ergodash/readme.md
Keyboard Documentation improvement for ErgoDash
- [X ] Keyboard (addition or update)
- [X ] Documentation
* 
- [ X] I have read the **CONTRIBUTING** document. (https://docs.qmk.fm/#/contributing)
> ergodash Keyboard readme documentation

- keyboards/honeycomb/config.h
- keyboards/honeycomb/honeycomb.c
- keyboards/honeycomb/honeycomb.h
- keyboards/honeycomb/keymaps/default/keymap.c
- keyboards/honeycomb/matrix.c
- keyboards/honeycomb/readme.md
- keyboards/honeycomb/rules.mk
This is the QMK firmware for the [Keyhive Honeycomb macropad](https://keyhive.xyz/shop/honeycomb-macropad). There are a few comments that were left in by the original author to help users create their own macros.
> Add Honeycomb macropad

- docs/faq_build.md
Add section about missing serial devices on Linux. This section mentions some kernel drivers which may be required in order for the device to be detected.
> faq_build.md: Add section about serial devices on Linux

- docs/feature_bootmagic.md
Document that using bootmagic lite resets the eeprom every time.
Update docs for behavior which differs from bootmagic.
Updates docs.
*
> Bootmagic Lite Caveat

- docs/_summary.md
- docs/hardware_keyboard_guidelines.md
- docs/reference_info_json.md
> Update the keyboard guidelines

- keyboards/hhkb/keymaps/bakingpy/keymap.c
- keyboards/hhkb/keymaps/bakingpy/rules.mk
Add bakingpy layout for HHKB JP
*
> Add HHKB JP keymap for bakingpy

- keyboards/bdn9/config.h
- keyboards/bdn9/keymaps/default/keymap.c
Update default keymap, change RGB LEDs to 4 for Rev. 1.1
*
> Update default keymap, change RGB LEDs to 4 for Rev. 1.1

- docs/feature_combo.md
> added missing ; on example

- keyboards/kbdfans/kbd75/keymaps/digital/keymap.c
- keyboards/kbdfans/kbd75/keymaps/digital/readme.md
> Add digital layout for KBD75

- keyboards/eco/keymaps/fsck/config.h
- keyboards/eco/keymaps/fsck/keymap.c
- keyboards/eco/keymaps/fsck/readme.md
- keyboards/eco/keymaps/fsck/rules.mk
- keyboards/eco/rev2/config.h
- keyboards/planck/keymaps/fsck/config.h
- keyboards/planck/keymaps/fsck/keymap.c
- keyboards/planck/keymaps/fsck/readme.md
- keyboards/planck/keymaps/fsck/rules.mk
- keyboards/preonic/keymaps/fsck/config.h
- keyboards/preonic/keymaps/fsck/keymap.c
- keyboards/preonic/keymaps/fsck/readme.md
- keyboards/preonic/keymaps/fsck/rules.mk
* Add fsck keymaps for the eco, planck and preonic keyboards
> Add fsck keymaps for eco, planck and preonic

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other_issues.md
- .github/PULL_REQUEST_TEMPLATE.md
Just some tiny improvements to the issue templates.
* None.
> Tweak issue templates (capitalisation mostly)

- docs/feature_encoders.md
> Improve Encoder documentation

- util/travis_compiled_push.sh
- util/travis_push.sh
Cherry picked from #4947.
Before, each PR contains the following block at the end of the logs:
```
0.04s$ bash util/travis_docs.sh
iv undefined
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
chmod: cannot access ‘id_rsa_qmk_firmware’: No such file or directory
chmod: cannot access ‘id_rsa_qmk.fm’: No such file or directory
Agent pid 10110
id_rsa_qmk_firmware: No such file or directory
The command "bash util/travis_docs.sh" exited with 0
```
While fixing the above, i also reduced the duplication of ssh keys handling within travis_compiled_push.sh
> Remove duplication of ssh keys and fix usage on PR builds

- docs/feature_grave_esc.md
- document caveats on OSX and expected behavior with KC_GESC and GUI
- clarify documentation slightly
- give examples of expected output in actual use
Update GESC documentation with better examples and expected behavior on OSX.
* N/A
> Update KC_GESC documentation

- keyboards/playkbtw/pk60/keymaps/rfvizarra/keymap.c
- keyboards/playkbtw/pk60/keymaps/rfvizarra/readme.md
A personal (minila) layout for the Playkeyboard PK60 PCB
*
> rfvizarra's custom PK60 layout

- .clang-format
- docs/contributing.md
Here's a .clang-format file I've been using which follows the defined code style (such as it is) as closely as I can manage.
* #4867
> Add .clang-format file for #4867

- keyboards/tmo50/keymaps/olivia/keymap.c
> Add Olivia's TMO50 layout

- keyboards/helix/rev2/keymaps/default/keymap.c
- keyboards/helix/rev2/keymaps/led_test/led_test_init.c
Change to use keyboard_post_init_user() hook (#3113)
> Update Helix 'led_test' keymap

- keyboards/doro67/regular/regular.c
Thanks to oldcat for reporting this but apparently the caps lock led wasn't working. Had to actually enable it in matrix_init and swap the logic around when toggling. 
*
> Get doro67 caps lock led working

- keyboards/kinesis/keymaps/tw1t611/config.h
- keyboards/kinesis/keymaps/tw1t611/keymap.c
- keyboards/kinesis/keymaps/tw1t611/readme.md
- keyboards/kinesis/keymaps/tw1t611/rules.mk
> Add kinesis layout.

- docs/hand_wire.md
The main reason for this PR was to replace the outdated KEYMAP function with the newer LAYOUT function. The setup script referred to in the docs is already updated, so the name confused me. 
While I was at it, I added links to the two best visual step by step guides on hand wiring. Let me know if that's discouraged and I will make changes accordingly. I have no affiliations with the users who wrote the guides. 
*
> Updated hand wiring docs

- keyboards/melody96/readme.md
The Melody96 is the same as what's in the NYM96 currently on sale at Massdrop. This change merely updates the readme to mention that fact.
> NYM96 mention in YMDK Melody96

- keyboards/ergo42/keymaps/koba/keymap.c
- keyboards/ergo42/keymaps/koba/readme.md
- keyboards/ergo42/keymaps/koba/readme_ja.md
Update personal keymap for Ergo42.
N/A
> Keymap: Update Koba's keymap for Ergo42.

- quantum/process_keycode/process_steno.c
Fix missing break; in switch statement.
* Fixes #4578, Fixes #4506
> Fix Tx Bolt ghosting second character on key press

- keyboards/hs60/v2/keymaps/stanrc85/config.h
- keyboards/hs60/v2/keymaps/stanrc85/keymap.c
- keyboards/hs60/v2/keymaps/stanrc85/readme.md
- keyboards/hs60/v2/keymaps/stanrc85/rules.mk
Adding my keymap to HS60v2 since it is incompatible with community keymaps currently.
*
> Initial upload of stanrc85 HS60 v2 keymap and config

- keyboards/kbdfans/kbd4x/kbd4x.h
- keyboards/kbdfans/kbd4x/rules.mk
- keyboards/kbdfans/kbd66/config.h
- keyboards/kbdfans/kbd66/kbd66.h
- keyboards/kbdfans/kbd66/rules.mk
- keyboards/kbdfans/kbd67/hotswap/config.h
- keyboards/kbdfans/kbd67/rev1/rev1.h
- keyboards/kbdfans/kbd6x/kbd6x.h
- keyboards/kbdfans/kbd75/kbd75.h
Minor cleanups to KBDFans keyboards that include changes such as 
- Switch to using `#pragma once`
- Turn on bootmagic lite for boards that could benefit with it on. 
- Turn on RGB animations for boards that have RGB capability
- Readme updates
> KBDFans Minor Fixes

- keyboards/1upkeyboards/1up60hse/1up60hse.h
- keyboards/1upkeyboards/1up60hse/rules.mk
- keyboards/1upkeyboards/1up60hte/keymaps/default/keymap.c
- keyboards/1upkeyboards/1up60hte/rules.mk
- keyboards/1upkeyboards/1up60rgb/1up60rgb.h
- keyboards/1upkeyboards/1up60rgb/config.h
- keyboards/1upkeyboards/1up60rgb/readme.md
- keyboards/1upkeyboards/1up60rgb/rules.mk
- keyboards/1upkeyboards/readme.md
- keyboards/1upkeyboards/super16/keymaps/default/config.h
- keyboards/1upkeyboards/super16/rules.mk
- keyboards/1upkeyboards/sweet16/config.h
- keyboards/1upkeyboards/sweet16/readme.md
- keyboards/1upkeyboards/sweet16/rules.mk
- keyboards/1upkeyboards/sweet16/sweet16.h
Mainly just sprucing up the 1upkeyboards keyboards to adhere to QMK's modern standards
Some changes are
- Usage of `#pragma once`
- `=` in favor of `?=` in `rules.mk`
- Minor readme tweaks
*
> Some minor refactoring of stuff I've done in 1upkeyboards directory

- layouts/community/ortho_4x4/jotix/keymap.c
> LAYOUT_ortho_4x4

- keyboards/dozen0/config.h
- keyboards/dozen0/dozen0.c
- keyboards/dozen0/dozen0.h
- keyboards/dozen0/info.json
- keyboards/dozen0/keymaps/default/config.h
- keyboards/dozen0/keymaps/default/keymap.c
- keyboards/dozen0/keymaps/default/readme.md
- keyboards/dozen0/keymaps/f12/config.h
- keyboards/dozen0/keymaps/f12/keymap.c
- keyboards/dozen0/readme.md
- keyboards/dozen0/rules.mk
I added a new keyboard(macropad) "Dozen0".
*
> Add new keyboard Dozen0

- keyboards/keebio/quefrency/keymaps/unausgeschlafen/config.h
- keyboards/keebio/quefrency/keymaps/unausgeschlafen/keymap.c
- keyboards/keebio/quefrency/keymaps/unausgeschlafen/readme.md
- keyboards/keebio/quefrency/keymaps/unausgeschlafen/rules.mk
> unausgeschlafen quefrency keymap

- keyboards/hs60/v2/readme.md
Add flash and reset instructions to the `README` of HS60 v2. It's important to erase the EEPROM, because of recent changes.
More information can be found here: https://github.com/qmk/qmk_firmware/pull/5193#issuecomment-466842609
*
> HS60 v2: Instructions how to reset and flash

- keyboards/ergodash/rev2/keymaps/default/keymap.c
I changed the keymap to make it easy to check the operation of the keyboard.
- [ x ] Keymap/layout/userspace (addition or update)
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ x ] I have added tests to cover my changes.
- [ x ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
> Update default keymap

- keyboards/converter/usb_usb/custom_matrix.cpp
Inadvertent extra line in previous commit.
> matrix_init_user shouldn't call itself

- docs/_summary.md
- docs/features.md
When the LED Matrix code was merged in, docs were written, but ... we missed adding links to the sidebar and to the features page.
This adds them.
*
> Add LED Matrix to Features list for easy reference

- keyboards/hs60/v2/rules.mk
This should have gone into previous PR but I am dumb
*
> Fixed default to dissable VIA

- docs/hand_wire.md
I'm a web designer and know there are several "decent" code editors out there, but I would figure not everyone into keyboards is, so I found Sublime text a bit of a hard sell for someone who just need to manipulate some text files. VS Code or Atom would b a much better suit for them instead of dropping $80 on a "decent" text editor.
*
> Add more "decent" text editors

- keyboards/planck/keymaps/vxid/config.h
- keyboards/planck/keymaps/vxid/keymap.c
- keyboards/planck/keymaps/vxid/readme.md
> Add vxid planck layout

- keyboards/handwired/jotanck/config.h
- keyboards/handwired/jotanck/readme.md
> re-arrange the pinout for backlight support

- keyboards/dztech/dz60rgb/keymaps/mekanist/config.h
- keyboards/dztech/dz60rgb/keymaps/mekanist/keymap.c
- keyboards/dztech/dz60rgb/keymaps/mekanist/readme.md
Checking in @nshanpetrosyan (mekanist) keymap so he can retain all his functionality and easily edit it on his own. Special thanks to @MatthewRobo for helping create the layer rgb lightings. 
I've included a helpful `readme.md` as well.
> Mekanist DZ60rgb Keymap

- docs/feature_userspace.md
This includes a much more feature rich version of the code, as well as updating for changes that have occurred in QMK Firmware
> [Docs] Update the KC_MAKE example in Userspace docs

- docs/getting_started_build_tools.md
See https://www.archlinux.org/packages/extra/x86_64/dfu-programmer/
getting_started_build_tools: dfu-{util,programmer} now available from arch repo
n/a
> getting_started_build_tools: dfu-{util,programmer} now available from arch repo

- keyboards/keebio/iris/keymaps/vyolle/keymap.c
Literally just the title.
- [ X] Enhancement/optimization
*
> Swapped Gui keys and Shift Keys. I think it's more ergonomic in this configuration.

- keyboards/dztech/dz60rgb/config.h
- keyboards/dztech/dz60rgb/keymaps/ansi/config.h
- keyboards/dztech/dz60rgb/keymaps/default/config.h
- keyboards/dztech/dz60rgb/keymaps/hhkb/config.h
- keyboards/dztech/dz60rgb/keymaps/hhkb_iso/config.h
- keyboards/dztech/dz60rgb/keymaps/iso/config.h
- keyboards/dztech/dz60rgb/keymaps/mekanist/config.h
> fix dz60rgb config.qmk.fm non-combile 

- keyboards/crkbd/keymaps/jarred/config.h
- keyboards/crkbd/keymaps/jarred/keymap.c
- keyboards/crkbd/keymaps/jarred/readme.md
- keyboards/crkbd/keymaps/jarred/rules.mk
Adding my crkbd keymap, this keyboard is awesome :)
*
> Add crkbd keymap

- keyboards/handwired/mechboards_micropad/config.h
- keyboards/handwired/mechboards_micropad/info.json
- keyboards/handwired/mechboards_micropad/keymaps/default/keymap.c
- keyboards/handwired/mechboards_micropad/keymaps/default/readme.md
- keyboards/handwired/mechboards_micropad/mechboards_micropad.c
- keyboards/handwired/mechboards_micropad/mechboards_micropad.h
- keyboards/handwired/mechboards_micropad/readme.md
- keyboards/handwired/mechboards_micropad/rules.mk
Micropad added, this is going to be a freebie/in limited quantities so its in handwired.
*
> Mechboards Micropad

- quantum/audio/musical_notes.h
- quantum/audio/song_list.h
I added 3 new songs to song_list.h
1) Megalovania - A boss fight theme from the game Undertale
2) Kataware Doki - An insert song from the anime Kimi no na wa
3) La Campanella - Liszt
I also added the breve (double whole note) and dotted breve note types to musical_notes.h. I included these because the default tempo is quite high, so I thought a note with higher duration would be useful for some songs, and although M__NOTE could be used instead, this provides a simpler shorthand notation. 
Tested using a Preonic V2, and confirmed that the changes compile on several other keyboards as well.
*
>  Added 3 new songs to song_list.h and added new note type to musical_notes.h

- layouts/community/ergodox/dvorak_programmer_swe/keymap.c
- layouts/community/ergodox/dvorak_programmer_swe/readme.md
* 2019-03-08
* Switched position on Alt and Alt-shift
* Added tilde character to symbol layer
* Added Print Screen to keymap 3
* Added ' (NO_APOS) to keymap 3
* Added how to install help in this readme
*
> Small improvements to this layout

- keyboards/dztech/dz40rgb/config.h
- keyboards/dztech/dz60rgb/config.h
- keyboards/dztech/dz60rgb/keymaps/default/keymap.c
> Fix speed issues with RGB Matrix in the DZ60RGB 

- keyboards/handwired/mechboards_micropad/readme.md
> Minor readme fix

- keyboards/atreus62/keymaps/jarred/config.h
- keyboards/atreus62/keymaps/jarred/keymap.c
- keyboards/ergotravel/keymaps/jarred/config.h
- keyboards/ergotravel/keymaps/jarred/keymap.c
- keyboards/org60/keymaps/jarred/keymap.c
- users/jarred/jarred.h
Add my atreus, ergotravel and org60 keymaps
*
> Add atreus, ergotravel and org60 keymaps

- layouts/community/ergodox/dvorak_programmer_swe/keymap.c
- layouts/community/ergodox/dvorak_programmer_swe/readme.md
acute accent and pipe character also
* 
> Some more improvements to keymap, currency symbols..

- keyboards/hotdox/left.c
> Fix i2c calls for HotDox keyboard

- keyboards/1upkeyboards/1up60rgb/keymaps/mdyevimnav/keymap.c
> Added 1up60rgb keymap: mdyevimnav

- docs/how_keyboards_work.md
> Fix ascii art

- keyboards/handwired/splittest/config.h
- keyboards/handwired/splittest/keymaps/default/config.h
- keyboards/handwired/splittest/keymaps/default/keymap.c
- keyboards/handwired/splittest/readme.md
- keyboards/handwired/splittest/rules.mk
- keyboards/handwired/splittest/splittest.c
- keyboards/handwired/splittest/splittest.h
Add handwired board for split RGB testing
*
> Add handwired split tester

- quantum/audio/song_list.h
Added 4 new songs to song_list.h
1. Liebesleid - Kriesler/Rachmaninoff
2. Michishirube - Ending song from Violet Evergarden
3. Melodies of Life - Main song from Final Fantasy IX
4. Eyes on Me - Main song from Final Fantasy VIII
Tested using a Preonic V2
*
> Added 4 new songs to song_list.h

- keyboards/handwired/prime_exl/keymaps/default/keymap.c
- keyboards/handwired/prime_exl/keymaps/via/keymap.c
- keyboards/primekb/prime_e/keymaps/default/keymap.c
- keyboards/primekb/prime_e/keymaps/via/keymap.c
function of indicator lights was inverted. these changes correct that.
correction LED indicator light functions
*
> correct indicator light states.

- docs/newbs_getting_started.md
Specifically, so that it grabs the submodules, since ARM keyboards are becoming more common, and we are seeing more issues about chibiOS not being downloaded (in the error log, rather than by question)
* Discord
> [Docs] Recursively clone qmk_firmware repo

- tmk_core/avr.mk
> correct typo in eeprom split target for dfu

- keyboards/dk60/dk60.c
> Fix dk60 compiler issue on newer compiler versions

- keyboards/hs60/v2/keymaps/stanrc85/keymap.c
- keyboards/hs60/v2/keymaps/stanrc85/readme.md
- layouts/community/60_ansi/stanrc85-ansi/keymap.c
- layouts/community/60_ansi/stanrc85-ansi/readme.md
- users/stanrc85/stanrc85.c
- users/stanrc85/stanrc85.h
Small update to move my tap dance code from two keymaps into my userspace for easier management. Also readme file updates to match updated keymaps. 
*
> [Keymap] Keymap and readme updates

- docs/flashing.md
As of https://github.com/arduino/Arduino/commit/d6b40d02183399f7e3faedcb9b734f25cf1c06f4 (a long time ago!) this link is broken.
*
> Fix link to Caterina bootloader hex files

- keyboards/kbdfans/kbd67/rev1/keymaps/koba/config.h
- keyboards/kbdfans/kbd67/rev1/keymaps/koba/keymap.c
- keyboards/kbdfans/kbd67/rev1/keymaps/koba/readme.md
> Keymap: Add Koba's keymap for KBD67.

- keyboards/hs60/v2/keymaps/stanrc85/keymap.c
- layouts/community/60_ansi/stanrc85-ansi/keymap.c
- users/stanrc85/stanrc85.c
- users/stanrc85/stanrc85.h
New tap dance code for copy/paste/CTL added
*
> [Keymap] New tap dance code added to userspace and keymaps

- keyboards/mxss/rgblight.h
This PR is cherry-pick from 90b9a1aa7d8a in PR #5020.
@MxBlu copied quantum/rgblight.c to keyboards/mxss/rgblight.c on July 8, 2018. At that time, I think it would be better to copy quantum/rgblight.h at the same time.
Because if someone makes a change to `quantum/rgblight.[ch]` that is incompatible with the past, it may cause problems with the compilation of keyboards/mxss.
(Like when I changed the prototype of the `rgblight_effect_XXX()` functions of rgblight.c in PR #5020.)
I hope that @MxBlu approves this change.
> add keyboards/mxss/rgblight.h from e661f1559:quantum/rgblight.h

- keyboards/keebio/iris/keymaps/default/config.h
- keyboards/keebio/iris/keymaps/default/keymap.c
Update default keymap for Iris to move around some keys and add grave to base layer.
*
> Update iris default

- keyboards/c39/c39.c
- keyboards/c39/c39.h
- keyboards/c39/config.h
- keyboards/c39/info.json
- keyboards/c39/keymaps/default/config.h
- keyboards/c39/keymaps/default/keymap.c
- keyboards/c39/keymaps/default/readme.md
- keyboards/c39/readme.md
- keyboards/c39/rules.mk
> Add Collide39 keyboard

- keyboards/kbdfans/kbd67/readme.md
- keyboards/kbdfans/kbd67/rev1/readme.md
Document the fact that the KBD65 PCB is supported by this part of the firmware. It was not obvious that this was the case.
None
> Update KBD67 readme so that it mentions the KBD65 PCB

- Dockerfile
- docs/getting_started_build_tools.md
- util/docker_build.sh
Tried to follow instructions to build firmware for Whitefox kb and build failed as it cant find ChibiOS lib.
> Update build instructions and docker file to download submodules

- keyboards/jj50/keymaps/abstractkb/keymap.c
- keyboards/jj50/keymaps/abstractkb/readme.md
- keyboards/keebio/bfo9000/keymaps/abstractkb/config.h
- keyboards/keebio/bfo9000/keymaps/abstractkb/keymap.c
- keyboards/keebio/bfo9000/keymaps/abstractkb/readme.md
- keyboards/keebio/bfo9000/keymaps/abstractkb/rules.mk
Added my personal keymaps for the BFO9000 and JJ50.  This is my first PR.
* N/A
> Updated my personal keymaps for the bfo9000 and jj50

- keyboards/hs60/v2/keymaps/stanrc85/config.h
Following update to zeal60 RGB update I have set more RGB options in my config.h
*
> [Keymap] Additional RGB options set

- keyboards/cannonkeys/instant60/instant60.h
- keyboards/cannonkeys/instant60/keymaps/tsangan/keymap.c
- keyboards/cannonkeys/stm32f072/keyboard.c
Add Tsangan keymaps and all keymaps for the Instant60
*
> Instant60 Tsangan

- docs/feature_rgblight.md
Added the following diagram to illustrate the relationship between RGBLIGHT_LED_MAP macro and `rgblight_set_clipping_range()`.
> update feature_rgblight.md: add some figures

- keyboards/keebio/bdn9/bdn9.h
- keyboards/keebio/bdn9/config.h
Now that #5091 (DIRECT_PINS support) is merged, migrate BDN9 to use it. Fixes inability to use BDN9 with Proton-C.
> Use DIRECT_PINS for BDN9

- keyboards/rama/koyu/config.h
Seems like `config.h` was missing a few `#defines` required for compilation.  Thanks to @Wilba6582 for pointing me in the right direction.
> Koyu Compilation Fixes

- keyboards/handwired/prime_exl/keymaps/default/keymap.c
- keyboards/handwired/prime_exl/keymaps/via/keymap.c
- keyboards/primekb/prime_e/keymaps/default/keymap.c
- keyboards/primekb/prime_e/keymaps/via/keymap.c
> Flesh out keymaps and some tweaks to indicators

- .travis.yml
Currently a make all:default takes about 20 minutes, applying https://docs.travis-ci.com/user/speeding-up-the-build/ and some logic i have used in previous projects.
Values for j can vary from:
- num_of_cores
- num_of_cores + 1
- num_of_cores * 2
https://docs.travis-ci.com/user/reference/overview/ documents the environment as 2 cores
> Speed up Travis CI builds

- docs/feature_macros.md
Alt↯Tab macro has be requested before. This example will help with anyone else who wants to have a single key way to alt tab
*
> Adding Alt↯Tab macro; Redo of pr #5593 with suggested changes

- keyboards/ok60/keymaps/default/keymap.c
Replace Left with Right alt and Ctrl on right side of OK60
*
> Use Right Alt/Ctrl on right side of OK60

- keyboards/ergodox_ez/config.h
Sets the default debounce to 5ms
n/a
> Change Ergodox EZ default debounce

- keyboards/planck/keymaps/oeywil/readme.md
> [keymap] Update readme.md

- keyboards/comet46/keymaps/satt/action_pseudo_lut.c
- keyboards/hhkb/keymaps/shela/action_pseudo_lut.c
Fix compilation error of keymaps.
> [Keymap] Fix compilation error of feature #4301

- keyboards/xd75/keymaps/markus/config.h
- keyboards/xd75/keymaps/markus/keymap.c
- keyboards/xd75/keymaps/markus/readme.md
- keyboards/xd75/keymaps/markus/rules.mk
* Use newly merged mouse keys functionality
* Remap certain Unicode characters
* Update code style
* Update `readme.md`
> Update XD75 keymap by markus

- docs/feature_mouse_keys.md
Two minor changes to mouse keys docs:
* A mouse can move the pointer into an infinite number of directions. Not just 8.
* The linked keymap showed nothing more than a layer containing a few key codes for mouse keys. I doubt this benefits users who are configuring a feature like mouse keys. In addition, mapping keys is already better covered under *Keymap Overview.*
> Update mouse keys docs

- keyboards/rama/koyu/readme.md
```json
{
"message": "Error: rama/koyu/qmk_firmware/keyboards/rama/koyu/readme.md: Invalid file encoding!",
}
``` 
Fixed up encoding ( had to subs a few characters). Flagging @Wilba6582 as the maintainer.
* http://compile.qmk.fm/v1/keyboards/error_log error
> Fix koyu readme encoding

- docs/feature_rgb_matrix.md
RGB Matrix docs update with more details on how to setup the rgb_led struct based on questions asked by mechmerlin.
*
> RGB Matrix docs update from mechmerlin discussion

- keyboards/sol/keymaps/default/rules.mk
Small fix for Sol default rules.mk file.
Small fix for Sol default rules.mk file to have it use the correct feature define. Missed this in the oled driver pr.
*
> Updated rules.mk for Sol to use the correct feature flag

- keyboards/atreus/readme.md
- keyboards/atreus/rules.mk
Removed superfluous upload code from keyboards/atreus/rules.mk, and general tidying.
Updated keyboards/atreus/readme.md to clarify make instructions for the keyboard variants.
*
> Atreus rules.mk and readme

- keyboards/dztech/dz60rgb/rules.mk
> DZ60RGB: update rule.mk

- keyboards/keebio/quefrency/keymaps/bcat/keymap.c
- keyboards/keebio/quefrency/keymaps/bcat/readme.md
Fix minor documentation errors in #5717.
None
> Fix typo and function layer image for my Quefrency keymap

- keyboards/cannonkeys/satisfaction75/config.h
- keyboards/cannonkeys/satisfaction75/i2c_master.c
- keyboards/cannonkeys/satisfaction75/keymaps/jae/keymap.c
Fix i2c_master.c in Satisfaction75 firmware, and update the VIA keymap for the rev1 PCB
* Read title :P
- [X ] My code follows the code style of this project.
- [X ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
> Satisfaction75 i2c fix and VIA layout

- keyboards/butterstick/butterstick.c
- keyboards/butterstick/butterstick.h
- keyboards/butterstick/config.h
- keyboards/butterstick/keymaps/default/keymap.c
- keyboards/butterstick/readme.md
- keyboards/butterstick/rules.mk
- keyboards/butterstick/sten.c
- keyboards/butterstick/sten.h
- keyboards/georgi/keymaps/default/rules.mk
Adds support for the Butter Stick from g Heavy Industries
Did you know it takes 21.2 pounds of whole milk to make one pound of butter?
> 🐮🥛 Butterstick Support 🥛🐮

- keyboards/doro67/multi/keymaps/default/readme.md
- keyboards/doro67/multi/keymaps/default_iso/readme.md
- keyboards/doro67/multi/keymaps/default_multi/readme.md
- keyboards/doro67/multi/readme.md
- keyboards/doro67/regular/keymaps/default/readme.md
- keyboards/doro67/regular/readme.md
- keyboards/doro67/rgb/keymaps/default/readme.md
- keyboards/doro67/rgb/readme.md
> readme clarification

- docs/_summary.md
Didn't add OLED Driver to the _summary.md, now it's added
*
> Added OLED Driver to the summary

- keyboards/preonic/keymaps/mikethetiger/config.h
- keyboards/preonic/keymaps/mikethetiger/keymap.c
- keyboards/preonic/keymaps/mikethetiger/readme.md
- keyboards/preonic/keymaps/mikethetiger/rules.mk
> Made adjustment to my Preonic keymap

- readme.md
> Use HTTPS for qmk.fm link

- docs/zh-cn/newbs_best_practices.md
- docs/zh-cn/newbs_building_firmware.md
- docs/zh-cn/newbs_flashing.md
- docs/zh-cn/newbs_getting_started.md
- docs/zh-cn/newbs_learn_more_resources.md
- docs/zh-cn/newbs_testing_debugging.md
translate
newbs_getting_started.md
newbs_building_firmware.md
newbs_flashing.md
newbs_testing_debugging.md
newbs_best_practices.md
newbs_learn_more_resources.md
into Mandarin Chinese
I correct my way to pull. I think I am right this time.
*
> translate the first unit(newbs) into  Mandarin Chinese

- docs/zh-cn/getting_started_introduction.md
Traslate
getting_started_introduction.md (20190503)
into Mandarin Chinese
感谢各位（可能只有寥寥数人）朋友对汉化的支持！
Translate docs into Mandarin Chinese
*
> translate docs into Mandarin Chinese

- Makefile
- message.mk
- util/freebsd_install.sh
- util/linux_install.sh
- util/macos_install.sh
- util/msys2_install.sh
As described in #5776 this adds python to all the OS install scripts.
We need to test on the following platforms:
*
> Make python a required build dependency

- keyboards/keebio/bdn9/keymaps/default/keymap.c
Add layout description to keymap.c
Just adds a table to the keymap.c for understandability
> Add layout description to keymap.c

- keyboards/signum/3_0/elitec/keymaps/default/keymap.c
- keyboards/signum/3_0/elitec/keymaps/default/layout.py
* Signum 3.0, fix, move and change keys
> Signum 3.0, fix, move and change keys

- keyboards/signum/3_0/elitec/keymaps/default/generate_km.py
- keyboards/signum/3_0/elitec/keymaps/default/keymap.c
* Generate a keymap in asciidoc format to quickly generate a printable version
> Signum3.0 Generate printable keymap

- keyboards/satan/keymaps/no_caps_lock/keymap.c
- keyboards/satan/keymaps/no_caps_lock/readme.md
Add no_caps_lock layout for Satan GH60
> Add no_caps_lock layout for Satan GH60

- keyboards/westfoxtrot/cyclops/cyclops.h
Fixes the physical matrix.
The physical matrix was wrong, this PR fixes it.
*
> Cyclops fixed matrix

- keyboards/minidox/keymaps/norman/config.h
- keyboards/minidox/keymaps/norman/keymap.c
- keyboards/minidox/keymaps/norman/readme.md
- quantum/keymap_extras/keymap_norman.h
- quantum/keymap_extras/sendstring_norman.h
* Add Norman layout under the Minidox keyboard
* Add keymap_extra def for Norman layout
* Re-org'ed the modifiers as explained in the Readme
* Corrected colour legend for KLE that the Readme links to
*
> Norman layout for the minidox keyboard

- docs/feature_rgblight.md
It's a struggle to find good documentation on how to reduce the memory footprint of RGB currently. This provides a simple example of how to do so with our current mechanisms.
Show using a code diff how to selectively enable 2 animations, reducing memory pressure on the flash space on constrained MCUs like AVR. Also re-orders the effect list.
*
> RGB Animation documentation on reducing memory footprint

- keyboards/dz60/keymaps/billiams/keymap.c
- keyboards/dz60/keymaps/billiams/readme.md
added vim arrow keybindings to layer 1 HJKL and updated readme. Also fixed typo in readme regarding mute function.
*
> Add vim arrow keybindings to layer 1, update readme.

- Vagrantfile
Now that #5469 has merged, there is no need for the `yes` bodge, also #5845 has been raised for the unavailable `/vagrant` mount point
* #5845
> Update Vagrant unattended install and fix mount point for Debian

- keyboards/kbdfans/kbd67/hotswap/readme.md
- keyboards/kbdfans/kbd67/readme.md
- keyboards/kbdfans/kbd67/rev1/readme.md
> clarify readme for the growing number of kbd67 revisions

- keyboards/staryu/backlight_staryu.h
- keyboards/staryu/config.h
- keyboards/staryu/staryu.c
- keyboards/staryu/staryu.h
Just a little tidy up to reduce unnecessary code by using DIRECT_PINS and BACKLIGHT_PINS.
Added benefit is that Staryu can now support multiple backlight levels.
> Convert Staryu to use DIRECT_PINS and BACKLIGHT_PINS

- keyboards/yosino58/readme.md
- keyboards/yosino58/rev1/config.h
```json
{
"message": "Warning: yosino58 does not have a readme.md.",
"severity": "warning"
}, {
"message": "Warning: qmk_firmware/keyboards/yosino58/rev1/config.h: Could not determine file encoding, some characters were replaced.",
"severity": "warning"
}, {
"message": "Warning: yosino58/rev1 does not have a readme.md.",
"severity": "warning"
}
``` 
Fixed up file encoding and add readme. Flagging @sakurachari for feedback as they added the board.
> Fix yosino58 api errors

- keyboards/keycapsss/o4l_5x12/config.h
- keyboards/keycapsss/o4l_5x12/keymaps/2x2u/config.h
- keyboards/keycapsss/o4l_5x12/keymaps/2x2u/keymap.c
- keyboards/keycapsss/o4l_5x12/keymaps/default/config.h
- keyboards/keycapsss/o4l_5x12/keymaps/default/keymap.c
- keyboards/keycapsss/o4l_5x12/o4l_5x12.c
- keyboards/keycapsss/o4l_5x12/o4l_5x12.h
- keyboards/keycapsss/o4l_5x12/readme.md
- keyboards/keycapsss/o4l_5x12/rules.mk
Add the O4L 5x12 keyboard and default keymaps.
Hardware will be sold on [keycapsss.com](https://keycapsss.com)
- [X ] Keyboard (addition or update)
- [X ] Keymap/layout/userspace (addition or update)
> [Keyboard] Add Keycapsss O4L 5x12 keyboard

- keyboards/doro67/multi/multi.c
Added capslock LED support to the Doro67 Multi PCB.
* Fixes #5838
> Added capslock LED support to the Doro67 Multi PCB.

- keyboards/signum/3_0/elitec/keymaps/default/keymap.c
- keyboards/signum/3_0/elitec/keymaps/default/layout.py
> Signum 3.0 Swap positions

- keyboards/georgi/config.h
- keyboards/georgi/keymaps/colemak-dh/keymap.c
- keyboards/georgi/keymaps/colemak-dh/readme.md
- keyboards/georgi/keymaps/colemak-dh/rules.mk
- keyboards/georgi/keymaps/default/keymap.c
- keyboards/georgi/sten.c
- keyboards/georgi/sten.h
Added some features to improve mid-stroke keypresses. Suggested and tested by @claymager
> Georgi improvements

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix_animations/colorband_sat_anim.h
- quantum/rgb_matrix_animations/colorband_val_anim.h
- quantum/rgb_matrix_animations/rgb_matrix_effects.inc
Single color band, scrolls left to right, fades saturation or value depending on effect.
Videos:
https://photos.app.goo.gl/qdsXmnMEPBWYTj3w5
https://photos.app.goo.gl/v7bnMcGVDd3XNcN67
❗️ #5919 contains this work, merge this first, or just merge that pr and close this one.
*
> Single Color Band scrolling left to right rgb matrix effects

- layouts/community/ortho_4x12/jotix/keymap.c
> jotix ortho_4x12_layout tweakings

- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c
- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/readme.md
- keyboards/keebio/bdn9/keymaps/bcat/keymap.c
- keyboards/keebio/bdn9/keymaps/bcat/readme.md
- keyboards/keebio/quefrency/keymaps/bcat/keymap.c
- keyboards/keebio/quefrency/keymaps/bcat/readme.md
- keyboards/keebio/quefrency/keymaps/bcat/rules.mk
I'm updating my Quefrency and KBD67 keymaps so that the function layer has a little more in common with the stock HHKB function layer, since I want to start experimenting with that layout.
I'm also setting the bootloader properly for my Quefrency and adding a simple keymap for a BDN9 macropad.
None
> Update my Quefrency/KBD67 keymaps, adding BDN9 macropad keymap as well

- layouts/community/ortho_4x12/jotix/keymap.c
> vim style cursor keys

- keyboards/converter/palm_usb/readme.md
Added table formatting to the readme.md for the palm_usb keyboard. This is only to help determine the connections that need to be made by preserving the whitespace.
* 
> Fix formatting on keyboard to micro connection table

- docs/keycodes.md
`MT()` was missing from keycodes.md. Just a basic description since the Advanced Keycodes page goes into more detail.
*
> Document MT keycode in keycodes.md

- util/linux_install.sh
I recently packaged cross-compilers for arm-none-eabi and avr targets on Solus and now i made addition to linux_install.sh script that will handle installation of tools on Solus distro.
*
> Add Solus support to linux_install.sh script

- keyboards/ergo42/keymaps/shinze/config.h
- keyboards/ergo42/keymaps/shinze/keymap.c
Added support for french layout Bépo http://bepo.fr/
> Added french Bépo support on Ergo42 keeb

- util/travis_compiled_push.sh
The addition to the build script should find any files that have the exact same name, except for capitalization. And remove the oldest one.
Such duplicated files will cause issues on windows, and are usually the result of a name change, and as such deprecated.
* fixes qmk/qmk.fm#43
> Clean up duped filenames om qmk.fm. Solves https://github.com/qmk/qmk.fm/issues/43

- layouts/community/ortho_4x12/jotix/config.h
- layouts/community/ortho_4x12/jotix/keymap.c
> jotix's ortho4x12 layout 

- quantum/config_common.h
Teensy 3.x and LC (when not using custom matrix) have some pin definitions missing, which produces build errors and less than ideal workarounds. Found by @St0RM53 on Discord.
Not sure if these need to be wrapped with a teensy only `#ifdef`?
> Add additional pin defs for Teensy 3.x and LC

- keyboards/business_card/alpha/alpha.c
- keyboards/business_card/alpha/alpha.h
- keyboards/business_card/alpha/config.h
- keyboards/business_card/alpha/keymaps/default/config.h
- keyboards/business_card/alpha/keymaps/default/keymap.c
- keyboards/business_card/alpha/keymaps/default/readme.md
- keyboards/business_card/alpha/rules.mk
- keyboards/business_card/beta/beta.c
- keyboards/business_card/beta/beta.h
- keyboards/business_card/beta/config.h
- keyboards/business_card/beta/keymaps/default/config.h
- keyboards/business_card/beta/keymaps/default/keymap.c
- keyboards/business_card/beta/keymaps/default/readme.md
- keyboards/business_card/beta/rules.mk
- keyboards/business_card/business_card.c
- keyboards/business_card/business_card.h
- keyboards/business_card/readme.md
- keyboards/business_card/rules.mk
> define new keyboard "BusinessCard"

- keyboards/canoe/keymaps/boy_314/keymap.c
- keyboards/canoe/keymaps/boy_314/readme.md
- keyboards/xd75/keymaps/boy_314/keymap.c
Created my layout for the canoe custom mechanical keyboard. Updated Caps Lock on XD75 to Mod Tap Left Control/Caps Lock.
*
> Create Boy_314's Canoe layout, small update on xd75 layout

- keyboards/keebio/iris/keymaps/default/keymap.c
- keyboards/keebio/iris/keymaps/via/keymap.c
- keyboards/keebio/iris/rev1/config.h
- keyboards/keebio/iris/rev1_led/config.h
- keyboards/keebio/iris/rev2/config.h
- keyboards/keebio/iris/rev3/config.h
- Swap left Control and Shift in default keymaps
- Use new DEBOUNCE setting for VIA compatibility
*
> Update iris default keymap

- keyboards/keebio/levinson/levinson.h
- keyboards/keebio/levinson/rev3/config.h
- keyboards/keebio/levinson/rev3/rev3.c
- keyboards/keebio/levinson/rev3/rev3.h
- keyboards/keebio/levinson/rev3/rules.mk
> Add Levinson Rev 3

- keyboards/coseyfannitutti/mulletpad/info.json
- correct layout macro name
- correct JSON object ordering
> Fix Configurator support for Mulletpad

- quantum/audio/song_list.h
This removes any song that has a license/copyright on them.
Additionally, it adds the license information for any song that remains.
> Remove all Copyrighted Sounds and Songs

- keyboards/candybar/rules.mk
Disabled console and command to get compiled size under flash space limitations.
> Candybar: updated rules.mk

- keyboards/clueboard/66_hotswap/gen1/config.h
- keyboards/hadron/ver3/config.h
- keyboards/planck/ez/config.h
- keyboards/planck/rev6/config.h
- keyboards/preonic/rev3/config.h
> Fix debounce conflicts in a few boards

- keyboards/jj40/keymaps/cockpit/keymap.c
- keyboards/jj40/keymaps/cockpit/readme.md
Added backlight controls and updated keymap docs
*
> Update jj40:cockpit keymap

- layouts/community/ortho_4x12/jotix/keymap.c
- layouts/community/ortho_4x12/jotix/readme.md
> jotix ortho_4x12 layout change

- keyboards/handwired/jotanck/readme.md
- layouts/community/ortho_4x12/jotix/keymap.c
> Jotix minor layout changes - readme.md fix

- keyboards/planck/keymaps/default/keymap.c
- keyboards/planck/keymaps/mgalisa/config.h
- keyboards/planck/keymaps/mgalisa/keymap.c
- keyboards/planck/keymaps/mgalisa/readme.md
- keyboards/planck/keymaps/mgalisa/rules.mk
Starting a new keymap for the Planck. Tweaked the Raise layer and added an emoji layer to more easily be annoying on Slack.
*
> New keymap

- keyboards/hecomi/keymaps/kakunpc/config.h
- keyboards/hecomi/keymaps/kakunpc/keymap.c
- keyboards/hecomi/keymaps/kakunpc/readme.md
> add keymap hecomi alpha

- layouts/community/ortho_4x12/jotix/keymap.c
- layouts/community/ortho_4x12/jotix/readme.md
> jotix ortho_4x12_layout rethink

- keyboards/planck/keymaps/rjhilgefort/config.h
- keyboards/planck/keymaps/rjhilgefort/keymap.c
- keyboards/planck/keymaps/rjhilgefort/rules.mk
Fix firmware errors in my layout noticed when flashing my Rev6 Planck.
none
> Fix firmware errors when flashing Rev6 Planck

- keyboards/keebio/quefrency/keymaps/bcat/keymap.c
- keyboards/keebio/quefrency/keymaps/bcat/readme.md
- users/bcat/config.h
* Fix typos in my userspace config
* Remove Quefrency mouse keys layer I don't use
None
> Minor userspace and Quefrency keymap fixes

- keyboards/nk65/readme.md
> Added NK65 Picture in Readme as promissed

- keyboards/aeboards/ext65/config.h
- keyboards/aeboards/ext65/ext65.c
- keyboards/aeboards/ext65/ext65.h
- keyboards/aeboards/ext65/keymaps/default/keymap.c
- keyboards/aeboards/ext65/keymaps/default/readme.md
- keyboards/aeboards/ext65/keymaps/via/keymap.c
- keyboards/aeboards/ext65/keymaps/via/readme.md
- keyboards/aeboards/ext65/keymaps/via/rules.mk
- keyboards/aeboards/ext65/readme.md
- keyboards/aeboards/ext65/rules.mk
New keyboard Ext65 and fix up Aegis config.h.
*
> Aeboards Ext65 - New keyboard & Aegis Update

- keyboards/crkbd/keymaps/thumb_ctrl/config.h
- keyboards/crkbd/keymaps/thumb_ctrl/keymap.c
- keyboards/crkbd/keymaps/thumb_ctrl/rules.mk
Add tap to modifier key.
Place the move key on the lower layer.
*
> New keymap for crkbd

- keyboards/planck/ez/ez.c
Prevents compiler issuer, if RGB Matrix is disabled.
> [Keyboard] Fixup RGB Matrix functionality on Planck EZ

- quantum/audio/song_list.h
Seems like this one was missed ;)
> Remove one more copyrighted song

- keyboards/pdxkbc/config.h
- keyboards/pdxkbc/info.json
- keyboards/pdxkbc/keymaps/default/config.h
- keyboards/pdxkbc/keymaps/default/keymap.c
- keyboards/pdxkbc/keymaps/default/readme.md
- keyboards/pdxkbc/pdxkbc.c
- keyboards/pdxkbc/pdxkbc.h
- keyboards/pdxkbc/readme.md
- keyboards/pdxkbc/rules.mk
> Add PDXKBC badge keyboard

- keyboards/dz60/keymaps/weeheavy_2.25_lshift/README.md
- keyboards/dz60/keymaps/weeheavy_2.25_lshift/keymap.c
I made a new layout as I could not find one with the following specs:
- ANSI
- 2.25u left shift
- Arrow cluster
*
> DZ60 w/ 2.25u left shift and arrow cluster

- docs/feature_advanced_keycodes.md
> [docs] fix typo

- keyboards/meishi2/config.h
- keyboards/meishi2/keymaps/default/config.h
- keyboards/meishi2/keymaps/default/keymap.c
- keyboards/meishi2/keymaps/default/readme.md
- keyboards/meishi2/meishi2.c
- keyboards/meishi2/meishi2.h
- keyboards/meishi2/readme.md
- keyboards/meishi2/rules.mk
> Add meishi2 keyboard

- keyboards/thevankeyboards/minivan/keymaps/budi/keymap.c
> Replaced xxxxxxx by XXXXXXX to fix build breakage (Minivan/budi)

- keyboards/thevankeyboards/minivan/readme.md
> Update catalog link in the TheVanKeyboards/Minivan Readme.

- keyboards/gingham/keymaps/iso/keymap.c
There were some copypasta BL keycodes
*
> Fixed ISO keymap

- keyboards/gonnerd/keymaps/gam3cat/keymap.c
- keyboards/gonnerd/keymaps/gam3cat/rules.mk
- keyboards/hineybush/h87a/keymaps/gam3cat/keymap.c
- keyboards/jc65/v32u4/keymaps/gam3cat/keymap.c
- keyboards/jc65/v32u4/keymaps/gam3cat/rules.mk
- keyboards/m10a/keymaps/gam3cat/keymap.c
- keyboards/m10a/keymaps/gam3cat/rules.mk
Moved DYNAMIC_MACRO_RANGE to end of keycode enumeration.
Moved DYNAMIC_MACRO_RANGE to end of keycode enumeration.
https://github.com/qmk/qmk_firmware/pull/6241
*
> Fixing keymap DYNAMIC_MACRO_RANGE keycode enumeration (Fix #6241)

- .editorconfig
Because when fixing makefile stuff, this was driving me UP A WALL
> Add makefile rules to .editorconfig

- docs/feature_oled_driver.md
Updated OLED Docs with notes about screen timeout.
* #5982
> Updated OLED Docs with notes about screen timeout.

- keyboards/crkbd/keymaps/vxid/README.md
- keyboards/crkbd/keymaps/vxid/config.h
- keyboards/crkbd/keymaps/vxid/keymap.c
- keyboards/crkbd/keymaps/vxid/rules.mk
Add a new layout for the crkbd keyboard.
*
> Add crkbd/vxid keymap

- quantum/template/avr/config.h
- quantum/template/avr/template.c
- quantum/template/base/keymaps/default/config.h
- quantum/template/base/keymaps/default/keymap.c
- quantum/template/base/template.h
- quantum/template/ps2avrgb/config.h
- quantum/template/ps2avrgb/rules.mk
- quantum/template/ps2avrgb/template.c
- quantum/template/ps2avrgb/usbconfig.h
- util/new_keyboard.sh
> Add copyright year placeholders to new keyboard script

- quantum/debounce/eager_pk.c
- quantum/debounce/eager_pr.c
Fixes issue with stuck keys on the Per Key and Per Row debouncing algorithms. 
* Fixes #6032
> Fix debouncing issue for eager algorithms

- docs/ChangeLog/20190830/PR6198.md
- quantum/keymap_extras/keymap_br_abnt2.h
- quantum/keymap_extras/keymap_swedish.h
Update and fix some of the keymap_extra files, to be more complete and useful, based on user feedback. 
* Fixes #6187
> Language Keymap extras backport from ZSA fork

- util/travis_compiled_push.sh
Format newly added files, not only modified files. Pointed out by @noroadsleft 
*
> Add new files to the list of files that are formatted.

- docs/feature_unicode.md
The section headers being the rules.mk options is kinda unclear. It should be more explicit as to what you need to do to get Unicode working.
*
> Clarify the rules.mk setup for Unicode

- message.mk
- tmk_core/rules.mk
A rough percentage calculation of the firmware file size, because I find the bytes a little too hard to wrap my head around 😄
*
> Display firmware size percentage

- keyboards/runner3680/3x6/config.h
- keyboards/runner3680/3x7/config.h
- keyboards/runner3680/3x8/config.h
- keyboards/runner3680/4x6/config.h
- keyboards/runner3680/4x7/config.h
- keyboards/runner3680/4x8/config.h
- keyboards/runner3680/5x6/config.h
- keyboards/runner3680/5x7/config.h
- keyboards/runner3680/5x8/config.h
- keyboards/runner3680/rules.mk
* Fix the number of keys
1. The number of matrix rows and cols
2. The number of RGBLED
* Add RGBLIGHT_LIMIT_VAL
> [Keyboard] [runner3680] Fix the number of keys

- util/travis_compiled_push.sh
This ensures that only version numbers will be incremented, not tags.
*
> Switch version incrementing to the command put together by @noroadsleft.

- docs/newbs_flashing.md
Highlight the note about sudo so it's more prominent, especially because this is a newbs guide.  Also added "dfu-programmer: no device present" into the doc text so that anyone searching for that particular error can hopefully find the page.
> Documentation: Newbs Flashing: Hightlight that sudo may be needed

- keyboards/keyhive/maypad/keymaps/default/keymap.c
- keyboards/keyhive/maypad/maypad.h
Updating layout to fix problems after #6287, now compiled and tested. Also noticed there was some typos in the previous `maypad.h`.
* Resolves: #6278
> Fixed maypad layout

- tmk_core/protocol/vusb/usbdrv/usbportability.h
> Fix vusb compiling after clang-format

- keyboards/dz60/keymaps/billiams/keymap.c
- keyboards/dz60/keymaps/billiams/readme.md
Switched keymaps for backspace and backslash keys.
*
> switch backspace and backslash, updated readme

- docs/faq_debug.md
This has bugged me for a while:
> Fix indented subheading on faq_debug.md

- keyboards/winkeyless/bface/keymaps/p3lim/README.md
- keyboards/winkeyless/bface/keymaps/p3lim/keymap.c
Ended up using QMK for my bface, had to add a custom layout mapping, so I'm just opening a PR with my layout in case anyone else would find it useful.
> [Keyboard] [bface] My custom layout

- tmk_core/rules.mk
This makes the Travis CI checks a bit more readable, actually. 
Also, I blame jack for this.
> Skip unsupported firmware check message in silent mode

- quantum/keymap_extras/sendstring_french.h
> Add sendstring LUTs for French keymap

- keyboards/crkbd/keymaps/default/rules.mk
- keyboards/crkbd/rules.mk
For Tessachka and Configurator support!
* Tessachka mentioned it on twitch stream
> Enable Mousekeys on Corne Keyboard by default

- quantum/rgb_matrix.c
- quantum/rgb_matrix.h
- tmk_core/common/eeconfig.c
- tmk_core/common/eeconfig.h
- users/xulkal/process_records.c
Added rgb matrix speed into eeprom storage system
*
> Adding rgb matrix speed into eeprom storage.

- keyboards/business_card/rules.mk
- keyboards/ivy/rules.mk
I missed these two, or didn't catch them before they were merged 😄
*
> Remove more commented out MCUs

- keyboards/planck/keymaps/dsanchezseco/config.h
- keyboards/planck/keymaps/dsanchezseco/keymap.c
> cleanup and start sound

- keyboards/primekb/prime_e/keymaps/jetpacktuxedo/keymap.c
> Add prime_e keymap

- keyboards/handwired/6macro/6macro.c
- keyboards/handwired/6macro/6macro.h
- keyboards/handwired/6macro/config.h
- keyboards/handwired/6macro/info.json
- keyboards/handwired/6macro/keymaps/default/config.h
- keyboards/handwired/6macro/keymaps/default/keymap.c
- keyboards/handwired/6macro/keymaps/default/readme.md
- keyboards/handwired/6macro/keymaps/osu/config.h
- keyboards/handwired/6macro/keymaps/osu/keymap.c
- keyboards/handwired/6macro/keymaps/osu/readme.md
- keyboards/handwired/6macro/readme.md
- keyboards/handwired/6macro/rules.mk
Add new keyboard 6macro. This is a very low volume project and as so it's in the "handwired" section.
Open source hardware here: https://github.com/joaofbmaia/6macro
Also added "default" and "osu" keymaps for the keyboard.
*
> Add 6macro keyboard

- keyboards/singa/readme.md
I seem to like copying the Singa as a BMC template a lot, and keep noticing a few things not quite up to date with the readme. 
*
> Singa readme fix

- docs/faq_build.md
Like the title says.  This should make it more clear about what is doing on and what should be done, and to which boards.
> [Docs] Clarify Zadig usage in FAQ Docs

- keyboards/handwired/numbrero/readme.md
Example given was wrong. No logic changes here.
> Fix Numbrero Handwired make example in readme

- keyboards/handwired/jotanck/keymaps/default/keymap.c
- keyboards/handwired/jotanck/readme.md
> leds in default keymap

- keyboards/fc660c/keymaps/siroleo/README.md
- keyboards/fc660c/keymaps/siroleo/keymap.c
Add colemak to existing fc660c keymap
* Add colemak layer to keymap
* moves RESET to a familiar location
*
> Add Colemak to existing fc660c keymap

- keyboards/gray_studio/space65/space65.c
Added code to fix the caps lock LED.
* Caps lock LED
> Update space65.c to fix caps lock LED

- keyboards/converter/usb_usb/custom_matrix.cpp
usb_usb: Fix startup block 
https://github.com/tmk/tmk_keyboard/commit/c2ce617a363f3b9d43aa81f98e70d58f928931f4#diff-deed77fb597e3a0019ce59fc1d09e260
usb_usb: Order of init prevents uneeded bus reset
https://github.com/tmk/tmk_keyboard/commit/7c228967a405b04d58bb06e619de8d1d7bb3c15b#diff-deed77fb597e3a0019ce59fc1d09e260
> Backport two fixes from TMK: usb-usb converter

- keyboards/unikorn/readme.md
Worked with user Fireworm to get the docs more clear. People were getting confused on how to properly reset the board. 
*
> Update Unikorn 60 Readme 

- keyboards/projectkb/alice/info.json
File was referencing an incorrect layout macro name.
> QMK Configurator fix for ProjectKB Alice info.json

- keyboards/angel64/config.h
- keyboards/angel64/keymaps/default/keymap.c
- keyboards/angel64/rules.mk
- Set angel64 to enable RGBLIGHT
*
> Set RGBLIGHT ENABLE for angel64

- keyboards/planck/keymaps/skank/keymap.c
- keyboards/planck/keymaps/skank/readme.md
- keyboards/planck/keymaps/skank/rules.mk
Personal keymap for the planck with muzak
* Has Colemak on a layer
* Enables mouse layer, but does not activate it yet
* Has Muzak and Sounds (Wheeee)
*
> Personal keymap for the planck with muzak
