lib/python/qmk/commands.py
Fixes https://github.com/qmk/qmk_configurator/issues/873
* https://github.com/qmk/qmk_configurator/issues/873
=> Fix QMK_BUILDDATE

keyboards/keebio/bdn9/keymaps/via/keymap.c
Add 3rd encoder to VIA keymap
*
=> Add 3rd encoder to VIA keymap

docs/faq_debug.md, docs/faq_general.md, docs/faq_misc.md
This PR fixes a typo in `docs/faq_general.md` and fixes a few grammar issues in `docs/faq_debug.md`. This branch was started mostly because of `faq_general.md` but I thought I'd go over the other FAQs for good measure (but since rewording is more debatable compared to just typos, I'm 100% okay with dropping the grammar changes if you want).
- No code changes -- docs change only
- No code changes -- docs change only
=> Fix typos and reword some sentences in FAQs

keyboards/rart/rart45/config.h, keyboards/rart/rart4x4/config.h
fixed number of LED RGB on RART4x4 and pin Matrix on RART45
*
=> Fix number RGB RART4x4 dan matrix pin RART45

docs/feature_ps2_mouse.md
Corrected macro in Scroll Button example so it compiles.
=> fix(feature_ps2_mouse): fix Scroll Button example

keyboards/zinc/rev1/config.h, keyboards/zinc/reva/config.h
Change Vender ID and Product ID.
*
=> Change VID/PID for Zinc

docs/newbs_getting_started.md
Document the qmk setup home option.
* Closes #9075
=> [Docs] add qmk setup home parameter

keyboards/afternoonlabs/gust/config.h, keyboards/afternoonlabs/gust/gust.c, keyboards/afternoonlabs/gust/gust.h, keyboards/afternoonlabs/gust/keymaps/default/keymap.c, keyboards/afternoonlabs/gust/keymaps/default/readme.md, keyboards/afternoonlabs/gust/rev1/config.h, keyboards/afternoonlabs/gust/rev1/info.json, keyboards/afternoonlabs/gust/rev1/readme.md, keyboards/afternoonlabs/gust/rev1/rev1.c, keyboards/afternoonlabs/gust/rev1/rev1.h, keyboards/afternoonlabs/gust/rev1/rules.mk
Adding the new Gust macro board rev1. A Simple 3x2 macro board that comes as a part of the Breeze Board.
*
=> Adding Gust Macro Board

quantum/quantum.c
Improved `tap_random_base64()` - now uses `send_char()` so will respect sendstring LUT overrides.
Also simplified `send_nibble()` to simply call `hex_to_keycode()` which again can be overridden for other language layouts as necessary.
These functions are rarely used so will probably be compiled out most of the time, but may as well optimise this anyway.
*
=> quantum.c send char cleanups

docs/ja/internals_defines.md, docs/ja/internals_midi_device.md, docs/ja/internals_midi_device_setup_process.md, docs/ja/internals_midi_util.md, docs/ja/internals_send_functions.md, docs/ja/internals_sysex_tools.md
Add Japanese translation of
- docs/internals_defines.md
- docs/internals_midi_device.md
- docs/internals_midi_device_setup_process.md
- docs/internals_midi_util.md
- docs/internals_send_functions.md
- docs/internals_sysex_tools.md
*
=> [Docs] Japanese translation of internals_*.md

keyboards/boardsource/the_mark/config.h
Added 2 lines to config.h to limit rgb brightness. With white selected and max brightness fuse would go off. 
*
=>  added limit to RGB brightness

lib/python/qmk/cli/flash.py, lib/python/qmk/commands.py
Fix the `qmk flash /path/to/json` process.
* https://github.com/qmk/qmk_firmware/issues/11711
=> CLI: Fix json flashing

keyboards/inett_studio/sqx/hotswap/hotswap.c, keyboards/inett_studio/sqx/universal/universal.c
* Add Caps Lock indicators support
* Fix 'a' flag error for RGB Light Mode
=> Update iNETT Studio Square.X RGB Light

keyboards/v60_type_r/config.h, keyboards/v60_type_r/keymaps/via/keymap.c, keyboards/v60_type_r/keymaps/via/rules.mk, keyboards/v60_type_r/rules.mk
I've added VIA compatibility to the v60 Type R as well as created a unique PRODUCT_ID for the v60 Type R in accordance with VIA's requirements.
* Updated PRODUCT_ID to a value that is globally unique in the source related to PRODUCT_IDs in accordance with VIA [documentation](https://caniusevia.com/docs/configuring_qmk#change-vendor_id-product_id)
* Updated the PRODUCT to include the manufacturer in accordance with VIA [documentation](https://caniusevia.com/docs/configuring_qmk#change-product)
* Added a via keymap using the default keymap.c and updated this keymaps rules to enable VIA
* Enabled bootmagic lite as recommended by VIA [documentation](https://caniusevia.com/docs/configuring_qmk#changes-to-keyboard-directorys-rulesmk)
*
=> [Keyboard] Add VIA support to v60 Type R

keyboards/kikoslab/kl90/keymaps/default/rules.mk
=> Fix build errors on kikoslab/kl90 default keymap

.github/workflows/format.yaml
Given the issues trying to get actions to commit to master, and those changes potentially not having been reviewed, tagged, tested etc, this change aims to raise a PR for the formatting changes. Per the actions docs, it should keep pushing changes to the same open PR, if we do not get a chance to review it in time.
Maybe in the future myself/someone else can dig in deeper into why the push was failing, however I think eyes on the changes has value in its own right.
https://github.com/zvecr/qmk_firmware/pull/18 for an example of what it will create.
=> [CI] Auto Formatting - Swap from direct commit to PR

tmk_core/protocol/serial_uart.c
=> Manual formatting fix for serial_uart.c

keyboards/lucid/kbd8x_hs/config.h
Fixed pin assignment on Lucid KBD8X HS PCB's for upcoming GB
* Fixed pin assignment on Lucid KBD8X HS PCB
=> Fixed pin assignment on KBD8X Hotswap by Lucid

keyboards/mechlovin/delphine/keymaps/via/rules.mk, keyboards/nightly_boards/n40_o/keymaps/via/config.h, keyboards/xelus/valor/rev1/rules.mk
Add/change the firmware so that they compile under the size limit.
Specifically for VIA firmware compile size
As shown in 
https://github.com/Xelus22/QMK-VIA-Hex/runs/1811476376?check_suite_focus=true
* Fix mechlovin/delphine/rgb_led
* Fix nightly_boards/n40_o
* Fix xelus/valor/rev1
=> [Keyboard] VIA fix firmware sizes

keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c, keyboards/boardsource/the_mark/keymaps/stanrc85/rules.mk, users/stanrc85/config.h, users/stanrc85/rules.mk
Add my keymap and enable VIA for Mark65 keyboard
*
=> Add my keymap for Mark65

keyboards/keebio/nyquist/keymaps/georgepetri/config.h, keyboards/keebio/nyquist/keymaps/georgepetri/keymap.c
#7754 caused a rgb's not to work on the right side, I had to do a `#undef RGBLED_SPLIT` to fix it.
=> Update keymap for keebio/nyquist

docs/isp_flashing_guide.md
1. Added USBasp as ISP option + hardware link
2. Added wiring for USBasp and changed the order of the documentation accordingly.
I placed _USBasp_ under _SparkFun Pocket AVR_ because both of these ISPs don't have additional `!> Notes` under the wiring instructions. This keeps the documentaion clean and readable.
*
=> Added wiring for USBasp in the ISP Flashing Guide

docs/i2c_driver.md, docs/spi_driver.md
(And the SPI docs a bit)
I've rewritten `i2c_driver.md` in the style of the SPI driver docs, particularly to add the AVR pinouts, and make the API documentation nicer.
*
=> Rework I2C driver docs

keyboards/alpine65/config.h, keyboards/ck60i/config.h, keyboards/evolv/config.h, keyboards/technika/config.h
=> Fix RGBLIGHT_LIMIT_VAL typo

keyboards/ymdk/ymd67/config.h
=> Fix  VENDOR_ID for ymd67

keyboards/planck/keymaps/dear_vehicle_owner/config.h, keyboards/planck/keymaps/dear_vehicle_owner/keymap.c, keyboards/planck/keymaps/dear_vehicle_owner/readme.md, keyboards/planck/keymaps/dear_vehicle_owner/rules.mk, keyboards/planck/keymaps/default/keymap.c
We've been trying to reach you concerning your vehicle's extended warranty. You should've received a notice in the mail about your car's extended warranty eligibility. Since we've not gotten a response, we're giving you a final courtesy call before we close out your file. Press 2 to be removed and placed on our do-not-call list. To speak to someone about possibly extending or reinstating your vehicle's warranty, press 1 to speak with a warranty specialist.
n/a
=> added dear_vehicle_owner meme keymap to planck keyboard

keyboards/planck/keymaps/stuartfong1/config.h, keyboards/planck/keymaps/stuartfong1/keymap.c, keyboards/planck/keymaps/stuartfong1/readme.md, keyboards/planck/keymaps/stuartfong1/rules.mk
Added my personal layout for the Planck keyboard.
*
=> Add stuartfong1 Planck Layout

.github/workflows/format.yaml
Should create 2 streams of PRs for master/develop
=> [CI] Format develop

keyboards/dztech/dz60rgb_wkl/keymaps/hhkb/keymap.c, keyboards/dztech/dz60rgb_wkl/keymaps/hhkb/rules.mk
=> [Keymap] Adding HHKB Keymap for dz60rgb_wkl:v2

keyboards/hhkb/ansi/keymaps/shela/keymap.c
Fixed my keymap broken by #11127
*
=> fix build error

keyboards/kbdfans/kbd67/hotswap/keymaps/madhatter/config.h, keyboards/kbdfans/kbd67/hotswap/keymaps/madhatter/keymap.c
* Add a personal keymap for kbd67 hotswap
* Cleaning up personal keymap for space65 v1
*
=> Personal keymap for kbd67 and some cleanup

keyboards/donutcables/budget96/config.h, keyboards/donutcables/budget96/keymaps/default/keymap.c, keyboards/donutcables/budget96/keymaps/via/config.h, keyboards/donutcables/budget96/keymaps/via/keymap.c, keyboards/donutcables/budget96/keymaps/via/rules.mk
Add VIA keymap to the budget 96
*
=> Budget96 VIA

keyboards/program_yoink/ortho/ortho.h
A quick update to ortho.h to fix matrix.
*
=> Program Yoink ortho.h update

keyboards/dozen0/config.h, keyboards/dozen0/keymaps/via/keymap.c, keyboards/dozen0/keymaps/via/rules.mk
=> Add via support to Dozen0

keyboards/leafcutterlabs/bigknob/keymaps/default/keymap.c
Fixes minor typo in comment string.
=> Leafcutterlabs/bigknob: Fix minor typo

keyboards/handwired/consolekeyboard/config.h, keyboards/handwired/consolekeyboard/consolekeyboard.c, keyboards/handwired/consolekeyboard/consolekeyboard.h, keyboards/handwired/consolekeyboard/info.json, keyboards/handwired/consolekeyboard/keymaps/default/keymap.c, keyboards/handwired/consolekeyboard/keymaps/via/keymap.c, keyboards/handwired/consolekeyboard/keymaps/via/rules.mk, keyboards/handwired/consolekeyboard/readme.md, keyboards/handwired/consolekeyboard/rules.mk
Added Console Keyboard (again)
*
=> Added ConsoleKeyboard

keyboards/montsinger/rebound/rev4/config.h
- [ x] Bugfix
- [ x] Keyboard (addition or update)
*
=> Rebound: change vendor and product ID for VIA

keyboards/kbdfans/kbd75/readme.md, keyboards/winkeyless/bmini/readme.md, keyboards/ymd75/readme.md
KBDFans' naming scheme for keyboard / pcb revisions is notoriously confusing.
This attempts to direct folks to the correct firmware for their actual pcb.
=> Reduce confusion for kbdfans/kbd75 rounds / revisions

keyboards/gray_studio/cod67/config.h, keyboards/gray_studio/cod67/keymaps/via/keymap.c, keyboards/gray_studio/cod67/keymaps/via/rules.mk
VIA support for the Graystudio COD67, tested on my personal board.
N/A
=> Graystudio COD67 VIA support

lib/python/qmk/c_parse.py
As reported by spidey3 this makes the layout processing more robust in the face of trailing commas.
=> Make LAYOUT parsing more robust

data/schemas/keyboard.jsonschema, lib/python/qmk/c_parse.py, lib/python/qmk/cli/chibios/confmigrate.py, lib/python/qmk/cli/generate/layouts.py, lib/python/qmk/cli/info.py, lib/python/qmk/cli/kle2json.py, lib/python/qmk/info.py, lib/python/qmk/keymap.py, lib/python/qmk/os_helpers/linux/__init__.py, lib/python/qmk/tests/test_cli_commands.py
This fixes two issues on develop- 
* Encoding errors on windows
* layouts were not correctly merging into info.json.
=> Fix develop

keyboards/linworks/whale75/rules.mk
=> Fix build for linworks/whale75.

keyboards/melgeek/mj63/rev2/rules.mk, keyboards/melgeek/mj64/rev3/rules.mk, keyboards/melgeek/mj65/rev3/rules.mk
Fix up build failures for melgeek boards after Feb27 develop merge.
=> Fix up build failures for melgeek boards after Feb27 develop merge.

tmk_core/protocol/vusb/main.c
Fix build for attiny85-based boards.
=> Fix build for attiny85-based boards.

docs/feature_unicode.md
I have used this approach myself with great success, and it seems to be the only good solution that doesn't involve IBus.
This is equivalent to how a traditional keyboard would input special symbols and it works in practically all software.
Added a paragraph to Linux Unicode input section describing how to input Unicode characters indirectly. Included some helpful links for people who want to learn how to make a custom layout in Linux.
If it seems appropriate, I could also add an example of how these would be invoked from QMK.
*
=> Add suggestion for indirect unicode input on Linux

keyboards/handwired/onekey/keymaps/quine/keymap.c, keyboards/handwired/onekey/keymaps/quine/rules.mk
This onekey keymap is a quine -- when the sole key is pressed, it outputs its own source code in its entirety.
This is truly an abomination, but in the spirit of Hacktoberfest I wanted to do something more conceptually unusual.
For starters, there is some pretty flagrant abuse going on here.  Right off the bat we have to eschew the preferred `#include QMK_KEYBOARD_H`, as the macro replacement will alter the results of performing a `send_string` on it, as well as breaking quotation once `"board.h"` is substituted.  Next up is the fact that I've used angle brackets in the `#include` statement, which I didn't not expect to work at all, but in my testing has not brought up any errors.  Beyond that there are probably some no-nos with respect to indentation, variable placement, and line breaks. …
=> handwired/onekey keymap: quine

keyboards/keyboardio/atreus/keymaps/dshields/keymap.c, users/dshields/dshields.c, users/dshields/dshields.h
=> [Keymap] Initial commit for keyboardio/atreus/dshields keymap.

lib/python/qmk/cli/c2json.py, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/cli/generate/layouts.py, lib/python/qmk/cli/generate/rgb_breathe_table.py, lib/python/qmk/cli/generate/rules_mk.py, lib/python/qmk/cli/json2c.py
Was hitting the following error when adding #12061, figured it was worth aligning 
```
<class 'OSError'>
☒ [Errno 18] Invalid cross-device link: '/tmp/asdf.h' -> 'asdf.h.bak'
```
*
=> Fix generated file output while target exists

keyboards/dichotomy/keymaps/alairock/keymap.c
Add page up and down next to arrows,
Add command and shift to layer, which helps with ergonomics while on this layer. F keys overwritten are not common and will soon be move to a new layer entirely. 
* Better layout for dichotomy/alairock
=> Update dichotomy/alairock layout

build_keyboard.mk, lib/python/qmk/cli/generate/rules_mk.py
Solves an issue in build_keyboard.mk around line 101 when the path to qmk_firmware contains a space.
```
$ pwd
/Users/fauxpark/git/space in/qmk_firmware
$ make gh60/satan:default
Making gh60/satan with keymap default
build_keyboard.mk:101: /Users/fauxpark/Git/space: No such file or directory
build_keyboard.mk:101: in/qmk_firmware/.build/obj_gh60_satan/src/rules.mk: No such file or directory
make[1]: *** No rule to make target `in/qmk_firmware/.build/obj_gh60_satan/src/rules.mk'.  Stop.
make: *** [gh60/satan:default] Error 1
```
*
=> `qmk generate-rules-mk`: add `--escape` switch for makefile logic

quantum/quantum_keycodes.h
Forgot to do this in #12129...
*
=> Remove ifdefs for UC and X/XP too

keyboards/soup10/config.h, keyboards/soup10/info.json, keyboards/soup10/keymaps/default/keymap.c, keyboards/soup10/keymaps/default/readme.md, keyboards/soup10/keymaps/via/keymap.c, keyboards/soup10/keymaps/via/rules.mk, keyboards/soup10/readme.md, keyboards/soup10/rules.mk, keyboards/soup10/soup10.c, keyboards/soup10/soup10.h
=> [Keyboard] add Soup10 support

requirements.txt
Some people are running into problems with older versions of jsonschema.
=> Enforce minimum versions for jsonschema and MILC

.github/workflows/api.yml, .github/workflows/develop_api.yml
Turns out we can't use github pages for our API data. This uploads it to our digitalocean spaces instead.
=> Upload api data to spaces

lib/python/qmk/info.py
This correctly detects support for community layouts in all situations, cleaning up the `qmk generate-api` log significantly.
=> Improve detection of community layout support

keyboards/planck/rev6/rev6.c, keyboards/preonic/rev3/rev3.c
Added index to physical location comments into Planck `rev6.c` and Preonic `rev3.c` to provide an easy guide for RGB matrix users to directly [light up specific LED positions](https://beta.docs.qmk.fm/using-qmk/hardware-features/lighting/feature_rgb_matrix#direct-operation-id-direct-operation) on the PCB with the index in function: `rgb_matrix_set_color(i, 0xff, 0xff, 0x00)`
=> Document LED physical location index for Planck and Preonic

docs/feature_rgb_matrix.md
Added undocumented DISABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
rearranged disable effect define documentations to reflect actual order
*
=> Update RGB matrix effects documentation

keyboards/m10a/config.h, keyboards/m10a/info.json, keyboards/m10a/keymaps/default/keymap.c, keyboards/m10a/keymaps/via/config.h, keyboards/m10a/keymaps/via/keymap.c, keyboards/m10a/m10a.c, keyboards/m10a/m10a.h, keyboards/m10a/readme.md, keyboards/m10a/rules.mk
Refactors the M10-A codebase to be more up-to-date with QMK standards.
cc: @Wilba6582, who's become something of a de-facto maintainer for this keyboard. PR edits the VIA keymap, but there shouldn't be any logic changes.
=> M10-A refactor

keyboards/hub16/readme.md, keyboards/hub16/rules.mk, keyboards/hub20/readme.md, keyboards/hub20/rules.mk
Add bootmagic support for hub16 and hub20, and updated the documentation accordingly. Also added reset instructions using the onboard reset switch.
*
=> Add bootmagic support for hub16 and hub20

lib/python/qmk/cli/doctor.py
Since WSL has yet to gain USB support, these checks will always fail. Let's skip them for now.
Also I didn't like that the "Detected {OS}" line coloured the `.` at the end... 😄
*
=> `qmk doctor`: Don't run udev checks under WSL

common_features.mk
No need for the else as the invalid driver error message halts execution. Now aligned with RGB Matrix except for the CIE1931 curve (coming later).
*
=> LED Matrix: Additional common_features.mk tweaks

keyboards/keebio/quefrency/readme.md
Fix incorrect flashing instructions
=> Update readme.md on quefrency

keyboards/sirius/uni660/rev1/rules.mk, keyboards/sirius/uni660/rev2/rules.mk
=> Fix Uni660 linker errors

keyboards/handwired/datahand/info.json
=> Add info.json for handwired/datahand

quantum/send_string_keycodes.h
The extra mouse keycodes, combined with the subsequent via fixes, need to be reflected in the sendstring implementation.
=> Align SEND_STRING mouse keycodes with recent changes

docs/feature_tap_dance.md
Define the state enums/typedefs more rigidly, and remove some magic numbers.
*
=> More Tap Dance docs improvements

quantum/api/api_sysex.h, quantum/config_common.h, tmk_core/protocol/midi/qmk_midi.c
I don't think this needs to be in there. If it's supposed to be overriden, can wrap it in an ifndef.
*
=> Move `API_SYSEX_MAX_SIZE` out of `config_common.h`

docs/cli_commands.md
=> Fix a small typo in cli_commands.md

keyboards/kb_elmo/twelvekey/config.h, keyboards/kb_elmo/twelvekey/info.json, keyboards/kb_elmo/twelvekey/keymaps/default/keymap.c, keyboards/kb_elmo/twelvekey/keymaps/via/keymap.c, keyboards/kb_elmo/twelvekey/keymaps/via/rules.mk, keyboards/kb_elmo/twelvekey/readme.md, keyboards/kb_elmo/twelvekey/rules.mk, keyboards/kb_elmo/twelvekey/twelvekey.c, keyboards/kb_elmo/twelvekey/twelvekey.h
Add support for the twelvekey macropad
=> added twelvekey

keyboards/boardsource/the_mark/config.h, keyboards/boardsource/the_mark/the_mark.c
Add suspend wake functions for The Mark:65's RGB Matrix
=> Add suspend wake functions for The Mark:65's RGB Matrix

.gitignore, keyboards/massdrop/alt/keymaps/hlmtre/keymap.c
Simply add a new keymap for myself. Very basic, unmaps caps and sets a few media keycodes to reasonable things, MO(1) + I becomes Insert.
*
=> add massdrop/alt/hlmtre keymap, add .exe to gitignore

keyboards/anavi/macropad2/keymaps/git/keymap.c
This keymap for ANAVI Macro Pad 2 contains popular git commands
typed out and executed with a single key:
- left key: git commit -s
- right key: git push
Add new keymap for ANAVI Macro Pad 2 contains popular git commands typed out and executed with a single key:
- left key: git commit -s
- right key: git push
*
=> [Keymap] ANAVI Macro Pad 2 add git keymap

keyboards/xd60/readme.md
I found (an earlier revision of) my keyboard's schematic on EasyEDA and I think others would find it useful.
* ~~n/a~~
=> keyboards/xd60/readme.md: link to schematic on EasyEDA

docs/newbs_getting_started.md
I had problems with qmk_firmware on my WSL instance
Moving the firmware from the windows filesystem to WSL fixed it completely.
I'm leaving this here so other people don't have the same issue.
#12368
=> [docs] Add IO Warning to WSL section of Getting Started

lib/python/qmk/json_schema.py
This was missed in a recent PR.
=> Add utf-8 encoding to an open() call

quantum/led_matrix.c, quantum/led_matrix.h, tmk_core/common/keyboard.c
Introducing the helper/noeeprom/"" functions and lib8tion. Removed some commented out code that won't make it to the final version. `BL_TOGG` still does not function correctly yet, I hoped adding the task call to keyboard.c would fix it but I guess it's something in the existing code that I have yet to update.
*
=> LED Matrix: Config functions

lib/python/qmk/cli/cformat.py
As it says on the tin -- allows for clang-format up until v20. Should give us a few weeks of respite.
=> Allow for clang-format up to v20.

keyboards/bm68rgb/config.h
=> change BM68 RGB USB Device descriptor device name

lib/python/qmk/cli/doctor.py
```
INFO Detected Windows 10 (10.0.19041).
```
```
Ψ Detected macOS 11.2.3.
```
Linux info could be obtained through the [`distro`](https://pypi.org/project/distro/) package, which would also come in handy for the install scripts when they are migrated to the CLI.
*
=> `qmk doctor`: Display macOS and Windows versions, and add WSL warning for /mnt

lib/python/qmk/cli/doctor.py
=> `qmk doctor`: Fix WSL /mnt check

keyboards/wilba_tech/rama_works_kara/config.h, keyboards/wilba_tech/rama_works_kara/info.json, keyboards/wilba_tech/rama_works_kara/keymaps/default/keymap.c, keyboards/wilba_tech/rama_works_kara/keymaps/via/keymap.c, keyboards/wilba_tech/rama_works_kara/keymaps/via/rules.mk, keyboards/wilba_tech/rama_works_kara/rama_works_kara.c, keyboards/wilba_tech/rama_works_kara/rama_works_kara.h, keyboards/wilba_tech/rama_works_kara/readme.md, keyboards/wilba_tech/rama_works_kara/rules.mk
=> Added RAMA WORKS KARA

docs/breaking_changes.md
=> Fix Breaking Change date

docs/newbs_getting_started.md
Clarify that the link to the github/forking instructions is a link to how to fork this project. Previous wording implied that the link was to a how-to-use github in general page.
* 
=> Update github instruction link in newbs_getting_started.md

docs/getting_started_make_guide.md
Update documentation to reflect what the actual target flags are
=> Documentation update

keyboards/anavi/macropad2/keymaps/google-meet/keymap.c, keyboards/anavi/macropad2/keymaps/google-meet/rules.mk
This keymap for ANAVI Macro Pad 2 contains a couple of shortcuts
for Google Meet:
- left key: turn on/off the microphone (mute button)
- right key: turn on/off the camera
Add a new keymap for ANAVI macro Pad 2 to provide quick shortcuts to control the microphone and the camera during video meetings using Google Meet.
*
=> [Keymap] ANAVI Macro Pad 2 add Google Meet keymap

keyboards/gray_studio/think65/solder/readme.md
Clarify readme to indicate it is for both V1 and V2 soldered PCBs. 
*
=> Update Think 6.5 V2 README

keyboards/keebio/quefrency/keymaps/bfiedler/config.h, keyboards/keebio/quefrency/keymaps/bfiedler/keymap.c, keyboards/keebio/quefrency/keymaps/bfiedler/rules.mk
Add the layout I'm using for my quefrency rev2.
=> Add my quefrency layout

keyboards/handwired/frankie_macropad/config.h, keyboards/handwired/frankie_macropad/frankie_macropad.c, keyboards/handwired/frankie_macropad/frankie_macropad.h, keyboards/handwired/frankie_macropad/info.json, keyboards/handwired/frankie_macropad/keymaps/default/keymap.c, keyboards/handwired/frankie_macropad/keymaps/default/readme.md, keyboards/handwired/frankie_macropad/readme.md, keyboards/handwired/frankie_macropad/rules.mk
Hello! I've designed and built a simple macropad. You can find the PCB layouts [here](https://github.com/eric-wood/macro-pad).
*
=> Add handwired/frankie_macropad

keyboards/kbdfans/kbdpad_mk2/keymaps/iracing_replay/keymap.c, keyboards/kbdfans/kbdpad_mk2/keymaps/iracing_replay/readme.md, keyboards/kbdfans/kbdpad_mk2/keymaps/iracing_replay/rules.mk
Adds a keymap for an iRacing replay keymap.
*
=> Iracing replay keymap

keyboards/xelus/pachi/mini_32u4/config.h, keyboards/xelus/pachi/mini_32u4/mini_32u4.c, keyboards/xelus/pachi/mini_32u4/mini_32u4.h, keyboards/xelus/pachi/mini_32u4/rules.mk, keyboards/xelus/pachi/readme.md
Add Pachi  Mini 32u4 edition
* Add Pachi  Mini 32u4 edition
=> [Keyboard] Pachi Mini 32u4

keyboards/mechlovin/infinity87/rev1/rev1.h, keyboards/mechlovin/infinity87/rev1/rules.mk, keyboards/mechlovin/infinity87/rules.mk
There was an error compiling rogue 87 and rouge 87 on config.qmk.fm even though I compiled with no errors on the computer.
I think I don't call keyboard.h in infinity87/rev1
Error when compile rogue87 on config.qmk.fm:
*
=> Refactor IF87_rev1

keyboards/kbdfans/bella/rgb/config.h, keyboards/kbdfans/bella/rgb_iso/config.h
Reset the debounce for the KBDfans Bella hotswap PCBs back to the default 5ms.  
For some reason it was set to 3ms which according to some people in the kbdfans Discord causes chattering.
*
=> fix bella debounce

keyboards/mechlovin/adelais/rgb_led/readme.md, keyboards/mechlovin/adelais/standard_led/config.h, keyboards/mechlovin/adelais/standard_led/halconf.h, keyboards/mechlovin/adelais/standard_led/mcuconf.h, keyboards/mechlovin/adelais/standard_led/readme.md, keyboards/mechlovin/adelais/standard_led/rev4/config.h, keyboards/mechlovin/adelais/standard_led/rev4/readme.md, keyboards/mechlovin/adelais/standard_led/rev4/rules.mk, keyboards/mechlovin/adelais/standard_led/rules.mk
=> add adelais rev4

docs/pr_checklist.md
Adds some additional requirements/points for PRs, as well as info about review process.
=> Add additional info to PR Checklist

quantum/led_matrix.c, quantum/split_common/transport.c
=> LED Matrix: Split

keyboards/keebio/bdn9/keymaps/test/keymap.c
=> not accessible and not needed anyway for a test keymap

keyboards/hub16/keymaps/peepeetee/config.h, keyboards/hub16/keymaps/peepeetee/keymap.c, keyboards/hub16/keymaps/peepeetee/rules.mk
=> peepeetee's *very janky* hub16 keymap

tmk_core/common/keyboard.c, tmk_core/protocol/chibios/main.c
This follows what chibios does.
*
=> eeprom driver: call eeprom_driver_init on avr targets too

.gitignore
When using **VSCode with QMK** as IDE, if you create a **.code-workspace** file in root folder **qmk_firmware** (i.e. **qmk_firmware.code-workspace** or any other file name), this user specific file shows as modified.
Add **.code-workspace** extension files to **.gitignore**.
*
=> [Config] Add VSCode workspace files to .gitignore

keyboards/planck/keymaps/via/rules.mk
Remove console as VIA takes up the endpoint.
* Fix planck light compile issues
=> [BUG FIX] planck light via endpoints

.gitignore
.python-version is used for tools like pyenv to set the python version in the current directory.
With the advent of the QMK CLI being required, QMK should also support tooling to make those python dependencies easier to manage.
This add .python-version to .gitignore so it doesn't get checked in inadvertently.
*
=> Add python-version to gitignore

keyboards/gmmk/pro/readme.md
=> Add flashing instructions to GMMK Pro readme

keyboards/ymdk/wings/config.h
- [x ] Core
Adding caps led support
* 
- [x ] I have added tests to cover my changes.
=> YMDK Wings: Update config.h

quantum/process_keycode/process_leader.h
Bad merge on #6580. `develop` wasn't building.
=> Fix bad PR merge for #6580

util/drivers.txt
=> Align drivers.txt with toolbox

lib/python/qmk/cli/generate/keyboard_h.py
=> Fix unused import in recent generation code

docs/feature_encoders.md
Added explanation of how multiple encoders can share pins and the limitations of this configuration
=> Add docs on multiple encoders sharing pins

keyboards/arisu/keymaps/stanrc85/keymap.c, keyboards/arisu/keymaps/stanrc85/rules.mk
Adding my keymap to Arisu keyboard keymaps
*
=> [Keymap] My Arisu layout setup

docs/newbs_getting_started.md
The easiest way to install QMK CLI and all the necessary
dependencies on FreeBSD is to use the packages
from the official FreeBSD Ports Collection.
This is possible since QMK CLI has been added to the Ports Collection:
https://www.freshports.org/sysutils/py-qmk/
=> Update FreeBSD install method

lib/python/qmk/cli/info.py
Complementing qmk/qmk_distro_msys#22, this allows box characters if the system allows. This can also be true if you use msys within windows terminal, so a bit of duck typing gives some flexibility.
=> Align qmk info ascii logic with milc logging

lib/python/qmk/cli/multibuild.py
=> Fix the makefile snippet so flake8 and yapf don't fight

lib/python/qmk/info.py
Common misconception is that `LAYOUTS` is for listing every layout macro, lets fix that...
=> Catch 'LAYOUTS = all' in lint

.github/workflows/format.yaml, lib/python/qmk/cli/cformat.py, lib/python/qmk/cli/generate/api.py, lib/python/qmk/cli/pyformat.py, lib/python/qmk/cli/pytest.py, lib/python/qmk/tests/test_cli_commands.py
Modify tests to add a read-only mode and start testing `qmk generate_api`.
=> Improve our CI tests

bin/qmk, lib/python/qmk/cli/__init__.py
=> Move the module checking and updating to lib/python

keyboards/bm68rgb/keymaps/peepeetee/config.h, keyboards/bm68rgb/keymaps/peepeetee/keymap.c, keyboards/bm68rgb/keymaps/peepeetee/keymap.h, keyboards/bm68rgb/keymaps/peepeetee/readme.md, keyboards/hub16/rules.mk
=> peepeetee's custom keymap for bm68rgb

keyboards/monarch/config.h, keyboards/monarch/halconf.h, keyboards/monarch/mcuconf.h
Sleep LED changes in core break the `monarch` board. This fixes things in the same way others were fixed.
Would be great if @ramonimbao could confirm this is all good.
=> Fixup `monarch` build errors on `develop` branch.

tmk_core/rules.mk
Seems to be macOS specific - something to do with zsh?
```
Creating binary load file for flashing: .build/planck_rev6_default.bin                              [OK]
sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [.build/planck_rev6_default.bin] Error 2
make: *** [planck/rev6:default] Error 1
```
* Fixes #12862
=> Fix syntax error when compiling for ARM

keyboards/anavi/macropad2/readme.md
Add more details about ANAVI Macro Pad 2 to readme.md.
Add details about ANAVI Macro Pad 2 to `readme.md`.
*
=> [Keyboard] ANAVI Macro Pad 2 update readme.md

docs/feature_led_matrix.md, docs/feature_rgb_matrix.md
Bringing the LED Matrix docs up to par with RGB Matrix. Both need a bit of a makeover though.
*
=> LED Matrix: Documentation

keyboards/crbn/keymaps/via/keymap.c, keyboards/crbn/keymaps/via/rules.mk
Added via keymap for the Polarity Works CRBN Featherlight keyboard, tested and working on my own sample
=> Added via keymap for crbn keyboard

keyboards/ploopyco/trackball_mini/trackball_mini.c, keyboards/ploopyco/trackball_nano/trackball_nano.c, keyboards/ploopyco/trackball_nano/trackball_nano.h
Moves all of the sensor code out of the user functions for the nano and micro, so that the user functions can be properly configured.
=> [Keyboard] Fix Mini and Nano trackball code up

keyboards/neopad/config.h, keyboards/neopad/readme.md, keyboards/neopad/rev1/config.h, keyboards/neopad/rev1/info.json, keyboards/neopad/rev1/keymaps/default/keymap.c, keyboards/neopad/rev1/readme.md, keyboards/neopad/rev1/rev1.c, keyboards/neopad/rev1/rev1.h, keyboards/neopad/rev1/rules.mk, keyboards/neopad/rules.mk
Added a new macropad compatible with QMK Firmware.
I have developed a new macropad. This PR contains the default keymap of this keyboard.
*
=> Add Neopad macropad

keyboards/illusion/rosa/config.h
The originally chosen vendorId overlapped with that of one other board. Changed it slightly so Rosa can be appropriately added to VIA ahead of the private buy.
*  Fixed overlapping vendorId
=> [Keyboard] Update Rosa vendorId to something unique for VIA

tmk_core/common/keyboard.c, tmk_core/common/keyboard.h, tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/chibios/main.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/main.c
=> Fixup housekeeping from being invoked twice per loop.

lib/python/qmk/cli/cformat.py, lib/python/qmk/cli/clean.py, lib/python/qmk/cli/compile.py, lib/python/qmk/cli/doctor.py, lib/python/qmk/cli/flash.py, lib/python/qmk/cli/generate/docs.py, lib/python/qmk/cli/multibuild.py, lib/python/qmk/cli/new/keyboard.py, lib/python/qmk/cli/pyformat.py, lib/python/qmk/cli/pytest.py, lib/python/qmk/commands.py, lib/python/qmk/keymap.py, lib/python/qmk/os_helpers/__init__.py, lib/python/qmk/os_helpers/linux/__init__.py, lib/python/qmk/submodules.py, lib/python/qmk/tests/test_cli_commands.py, util/install/debian.sh, util/install/fedora.sh, util/install/freebsd.sh, util/install/msys2.sh, util/install/void.sh, util/qmk_install.sh
This switches most of our subprocess usage to MILC's `cli.run()`. There are still a couple places that use subprocess.run which I didn't want to change just now.
I added `stdin=DEVNULL` to most commands because this fixes a bug on windows where input is no longer accepted after a subprocess is run.
=> Align our subprocess usage with current best practices.

lib/python/qmk/cli/generate/layouts.py
=> Ensure qmk generate-layouts does not conflict with existing keymap aliases

keyboards/nk87/config.h
=> Updated NK87 GPIO

keyboards/afternoonlabs/summer_breeze/rev1/rev1.h
Fixes a typo that was missed in the `LAYOUT` macro for the `afternoonlabs/summer_breeze`
=> Fix typo in summer breeze hardware layout

lib/python/qmk/cli/generate/api.py, lib/python/qmk/keyboard.py
[Found by @noroadsleft](https://github.com/qmk/qmk_configurator/pull/927#issuecomment-846725111) , we are not populating keyboards.qmk.fm with readme's for all the keyboards. This will search up in the tree for a readme when one specific to the revision doesn't exist.
=> Search for the readme.me in higher directories as well

docs/feature_rgb_matrix.md
=> Document RGB_MATRIX_FRAMEBUFFER_EFFECTS

docs/feature_led_matrix.md
=> Document LED_MATRIX_FRAMEBUFFER_EFFECTS

keyboards/crkbd/rev1/rev1.h
=> Remove redundant CRKBD header files

quantum/backlight/backlight.c
Bugfix for #12560 - evidently I didn't test the final state of this PR...
*
=> `backlight.c`: include `eeprom.h`

lib/python/qmk/decorators.py
=> CLI: Fix automagic

keyboards/planck/keymaps/lja83/config.h, keyboards/planck/keymaps/lja83/keymap.c, keyboards/planck/keymaps/lja83/readme.md, keyboards/planck/keymaps/lja83/rules.mk
Created a new layout for planck
Added a nav layer with mouse controls and arrow keys on hjkl as well as esc/ctrl and return/shift mod taps
*
=> Planck keymap

keyboards/thevankeyboards/jetvan/config.h, keyboards/thevankeyboards/jetvan/jetvan.c, keyboards/thevankeyboards/jetvan/jetvan.h, keyboards/thevankeyboards/jetvan/keymaps/default/keymap.c, keyboards/thevankeyboards/jetvan/keymaps/via/keymap.c, keyboards/thevankeyboards/jetvan/keymaps/via/rules.mk, keyboards/thevankeyboards/jetvan/readme.md, keyboards/thevankeyboards/jetvan/rules.mk
Initial support for JetVan keyboard including VIA.
*
=> JETVAN: Add initial support

keyboards/program_yoink/config.h, keyboards/program_yoink/staggered/keymaps/via/config.h, keyboards/program_yoink/staggered/keymaps/via/keymap.c, keyboards/program_yoink/staggered/keymaps/via/readme.md, keyboards/program_yoink/staggered/keymaps/via/rules.mk
=> Add program yoink via keymap

docs/ja/feature_rawhid.md
update Japanese translation of docs/feature_rawhid.md.
*
=> [Docs] update Japanese translation of feature_rawhid.md

docs/ja/hardware_avr.md
update Japanese translation of docs/hardware_avr.md.
*
=> [Docs] update Japanese translation of hardware_avr.md

docs/ja/one_shot_keys.md
update Japanese translation of docs/one_shot_keys.md.
*
=> [Docs] update Japanese translation of one_shot_keys.md

docs/ja/ref_functions.md
update Japanese translation of docs/ref_functions.md.
*
=> [Docs] update Japanese translation of ref_functions.md

docs/ja/newbs_building_firmware_configurator.md
=> [Docs] Update Japanese newbs_building_firmware_configurator.md

requirements-dev.txt, requirements.txt
=> Move hid and pyusb to requirements.txt

requirements.txt
This should align with the changes required within #13046, and allow it to error out slightly gracefully.
Could also be 1.4.0, per clueboard/milc/pull/28 which introduced the change?
=> Bump minimum compatible milc

keyboards/program_yoink/staggered/keymaps/via/keymap.c
Fix `program_yoink/staggered` 
https://github.com/Xelus22/QMK-VIA-Hex/runs/2779291781?check_suite_focus=true#step:13:906
Build fails
* Fix `program_yoink/staggered`
=> [Bug] Fix VIA Keymap Encoder

docs/ja/newbs.md
=> [Docs] Update Japanese newbs.md document

.vscode/settings.json
This lets vs code format on save using QMK's rules.
=> VS code: specify yapf as the formatting provider

docs/ja/newbs_learn_more_resources.md
=> [Docs] Update Japanese newbs_learn_more_resources.md

keyboards/ploopyco/trackball_nano/keymaps/default/readme.md
The keymap readme for the Ploopy nano incorrectly asserts that it ships with VIA support.
*
=> Fix ploopy readme

keyboards/tender/macrowo_pad/config.h, keyboards/tender/macrowo_pad/info.json, keyboards/tender/macrowo_pad/keymaps/default/keymap.c, keyboards/tender/macrowo_pad/keymaps/default/rules.mk, keyboards/tender/macrowo_pad/keymaps/via/keymap.c, keyboards/tender/macrowo_pad/keymaps/via/rules.mk, keyboards/tender/macrowo_pad/macrowo_pad.c, keyboards/tender/macrowo_pad/macrowo_pad.h, keyboards/tender/macrowo_pad/readme.md, keyboards/tender/macrowo_pad/rules.mk
- x ] Keymap/layout/userspace (addition or update)
*
=> add tender/macrowo_pad

keyboards/anavi/macropad2/keymaps/skype/keymap.c, keyboards/anavi/macropad2/keymaps/skype/rules.mk
This keymap for ANAVI Macro Pad 2 contains a couple of Skype
shortcuts for MS Windows and GNU/Linux distributions:
- Ctrl+M: Mute/unmute microphone
- Ctrl+Shift+K: Start/stop camera
The keymap contains the following shortcuts for Skype on MS Windows and GNU/Linux distributions:
- Ctrl+M: Mute/unmute microphone
- Ctrl+Shift+K: Start/stop camera
NOTE: Mac users should change the shortcut to toggle the mic to Command+Shift+M, for example `KC_LGUI(LSFT(KC_M))`.
*
=> [Keymap] ANAVI Macro Pad 2 add Skype keymap

docs/feature_rgb_matrix.md
Prior to this, the some of the common config looks like a detail of the APA102 driver
*
=> Top level heading for common config (RGB Matrix)

docs/feature_led_matrix.md
Prior to this, the some of the common config looks like a detail of the APA102 driver
*
=> Top level heading for common config (LED Matrix)

util/install/debian.sh
=> Debian requires package libusb-dev to build bootloaderHID

docs/feature_audio.md
=> Document user song list file

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
Synced up docs and doc comments. Fixed incorrect type for `oled_rotation`
*
=> OLED driver tweaks

docs/breaking_changes.md
=> Update `develop` merge sequence to reflect no-ff, no-squash.

docs/ja/feature_haptic_feedback.md
update Japanese translation of docs/feature_haptic_feedback.md.
*
=> [Docs] update Japanese translation of feature_haptic_feedback.md

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
This change adds the ability to invert displays to the standard OLED driver by sending the appropriate i2c command to a SSD1306 or SH1106 OLED.
Please tell me if my returns are sensible, and whether or not I should condense the if statements more.
* #13171
=> Add oled_invert

keyboards/keebio/iris/keymaps/mnil/config.h, keyboards/keebio/iris/keymaps/mnil/keymap.c, keyboards/keebio/iris/keymaps/mnil/readme.md, keyboards/keebio/iris/keymaps/mnil/rules.mk, keyboards/planck/keymaps/mnil/config.h, keyboards/planck/keymaps/mnil/keymap.c, keyboards/planck/keymaps/mnil/readme.md, users/mnil/config.h, users/mnil/mnil.c, users/mnil/mnil.h, users/mnil/readme.md, users/mnil/rules.mk
This commit add my keymaps for my Keebio Iris and Planck.
Nothing.
=> Add my keymaps for the Keebio Iris and Planck

keyboards/xelus/trinityxttkl/config.h, keyboards/xelus/trinityxttkl/trinityxttkl.c, keyboards/xelus/trinityxttkl/trinityxttkl.h
Trinity XT TKL fix license and add forgotten indicators
* Trinity XT TKL fix license and add forgotten indicators
=> [Keyboard Update] Trinity XT TKL fix license and add forgotten indicators

common_features.mk
Unused so should be okay for the short term
*
=> Temporary disable of CRC for split

keyboards/ymdk/wings/config.h, keyboards/ymdk/wings/rules.mk
Backlighting was not enabled by default, and was turned on. Also took the opportunity to move rgblight_animations into the rest of the rgb settings for cleanup. 
*
=> YMDK Wings: enable Backlight

data/mappings/keyboard_aliases.json
Title says it 
* Experienced by at least one user.
=> Fix issue with crkbd json mapping

quantum/led_matrix.c, quantum/rgb_matrix.c
Update flag wasn't being cleared.
=> rgb+led matrix write throttling

docs/feature_advanced_keycodes.md
Missed documenting GUI+shift/alt in this page for PR #13107.
=> Additional documentation for GUI mod combo

docs/pr_checklist.md
=> docs/pr_checklist: fix capitalization of Vial

keyboards/makrosu/keymaps/default/keymap.c, keyboards/makrosu/keymaps/via/keymap.c
Fix Makrosu keymap formatting and compilation errors.
* Fix Makrosu keymap formatting and compilation errors.
=> [Bug] Makrosu VIA compile fix encoder and formatting

keyboards/sowbug/ansi_tkl/keymaps/sowbug/keymap.c
Moves current default layout to a custom-named one; create new default layout that is more of a standard TKL.
=> Switch default layout to standard TKL; add custom

keyboards/reviung34/keymaps/default_rgb/config.h, keyboards/reviung34/keymaps/default_rgb/keymap.c, keyboards/reviung34/keymaps/default_rgb/readme.md, keyboards/reviung34/keymaps/default_rgb/rules.mk, keyboards/reviung34/keymaps/default_rgb2u/config.h, keyboards/reviung34/keymaps/default_rgb2u/keymap.c, keyboards/reviung34/keymaps/default_rgb2u/readme.md, keyboards/reviung34/keymaps/default_rgb2u/rules.mk
Add Keymap reviung34rgb for reviung34
- [*] Keymap/layout/userspace (addition or update)
* 
- [*] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [*] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [*] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [*] I have added tests to cover my changes.
- [*] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> [Keymap]Add Keymap reviung34rgb

keyboards/handwired/dactyl/keymaps/default/rules.mk, keyboards/handwired/dactyl/keymaps/dvorak/rules.mk
enable mousekeys in the handwired/dactyl keyboard
the default keymap for the dactyl contains a mouse layer, but the feature is disabled, so a first time builder has a confusing experience.  this change makes things Just Work.
* I haven't opened an issue for this, but I'm happy to if you'd like.
=> enable dactyl mousekeys, since default keymap uses them

docs/ja/cli_configuration.md, docs/ja/newbs_getting_started.md
=> [Docs] Update Japanese newbs_getting_started.md

docs/ja/feature_advanced_keycodes.md
Update Japanese document
* 
cf. #10192
=> Update advanced_keycodes.md of Japanese document

keyboards/ploopyco/mouse/mouse.c, keyboards/ploopyco/mouse/readme.md, keyboards/ploopyco/trackball/readme.md, keyboards/ploopyco/trackball/trackball.c, keyboards/ploopyco/trackball_mini/readme.md, keyboards/ploopyco/trackball_mini/trackball_mini.c, keyboards/ploopyco/trackball_mini/trackball_mini.h, keyboards/ploopyco/trackball_nano/config.h
Drag scroll was never documented... It is now.
Also found some bugs in the code that needed fixing, and some cleanup.
=> [Keyboard] Bugfixes and Readme additions for PloopyCo devices

keyboards/xelus/pachi/rgb/keymaps/via/config.h
Enable RGB Matrix VIA side for Pachi RGB
* Enable RGB Matrix VIA side for Pachi RGB
=> [Keyboard] Enable RGB Matrix VIA side for Pachi RGB

.vscode/settings.json
Disable automatic formatting for json files.
=> [VSCode] Do not automatically format json

tmk_core/common/chibios/chibios_config.h, tmk_core/common/usb_util.c
=> Allow configuration of USB_VBUS_PIN on chibios

lib/python/qmk/cli/doctor.py
Now that MILC grabs this correctly we can show it in the doctor output.
*
=> Doctor: print CLI version

keyboards/ramonimbao/squishytkl/keymaps/default/keymap.c, keyboards/ramonimbao/squishytkl/keymaps/iso/keymap.c, keyboards/ramonimbao/squishytkl/keymaps/jis/keymap.c, keyboards/ramonimbao/squishytkl/keymaps/via/keymap.c
Fix ramonimbao/squishytkl keymap encoders
* Fix ramonimbao/squishytkl keymap encoders
=> [Bug] VIA Hex fix `bool` encoder

docs/ja/api_docs.md, docs/ja/api_overview.md, docs/ja/coding_conventions_c.md, docs/ja/contributing.md, docs/ja/documentation_templates.md, docs/ja/faq_keymap.md, docs/ja/feature_stenography.md, docs/ja/how_a_matrix_works.md, docs/ja/reference_configurator_support.md, docs/ja/reference_glossary.md, docs/ja/understanding_qmk.md
* Check again that the following files are up to date.
* docs/how_a_matrix_works.md 
* docs/api_overview.md 
* docs/contributing.md 
* docs/coding_conventions_c.md 
* docs/reference_configurator_support.md 
* docs/reference_glossary.md 
* docs/api_docs.md 
* docs/feature_stenography.md 
* docs/documentation_templates.md 
* docs/faq_keymap.md 
* docs/understanding_qmk.md
=> [Update] Change Original TAGs of Japanese translations

common_features.mk
RGB Matrix requires `rgblight.h` for `RGBLIGHT_MODE_xxx`... it is now no longer implicitly visible after #13312.
@mtei would it be possible to refactor this somehow?
*
=> Add rgblight to RGB Matrix VPATH

keyboards/sanctified/dystopia/dystopia.h
Fix sanctified/dystopia compile issue with missing comma
* Fix sanctified/dystopia compile issue with missing comma
=> [Bug] fix Dystopia.h comma

keyboards/ramonimbao/chevron/info.json
QMK Configurator isn't using the data in this file, and I think this may be why...
cc @ramonimbao (keyboard maintainer)
=> Chevron by ramonimbao: add maintainer value to info.json

message.mk, tmk_core/avr.mk
Just to be a little more user-friendly for newbs.
*
=> Add "Ctrl+C to cancel" to "waiting for bootloader" messages

layouts/community/65_ansi_blocker/stanrc85/keymap.c, layouts/community/65_ansi_blocker/stanrc85/rules.mk
Add my preferred keymap to 65_ansi_blocker community layout to use with a few boards I have.
*
=> Add my community layout

keyboards/boardsource/beiwagon/beiwagon.c, keyboards/boardsource/beiwagon/beiwagon.h, keyboards/boardsource/beiwagon/config.h, keyboards/boardsource/beiwagon/info.json, keyboards/boardsource/beiwagon/keymaps/default/keymap.c, keyboards/boardsource/beiwagon/keymaps/default/readme.md, keyboards/boardsource/beiwagon/keymaps/via/keymap.c, keyboards/boardsource/beiwagon/keymaps/via/readme.md, keyboards/boardsource/beiwagon/keymaps/via/rules.mk, keyboards/boardsource/beiwagon/readme.md, keyboards/boardsource/beiwagon/rules.mk, keyboards/boardsource/technik_o/config.h, keyboards/boardsource/technik_o/info.json, keyboards/boardsource/technik_o/keymaps/default/keymap.c, keyboards/boardsource/technik_o/keymaps/default/readme.md, keyboards/boardsource/technik_o/keymaps/via/keymap.c, keyboards/boardsource/technik_o/keymaps/via/readme.md, keyboards/boardsource/technik_o/keymaps/via/rules.mk, keyboards/boardsource/technik_o/readme.md, keyboards/boardsource/technik_o/rules.mk, keyboards/boardsource/technik_o/technik_o.c, keyboards/boardsource/technik_o/technik_o.h
Added ortho version of technik keyboard the technik-o and the macro pad to go with it the beiwagon to the Boardsource folder.
*
=> added the ortho boards from the technik gb

keyboards/yampad/info.json
[title]
cc @mattdibi (keyboard maintainer)
=> Yampad: add info.json

docs/keycodes.md
Added the list of MIDI keycodes already present in` feature_midi.md` to the full list of keycodes in` keycodes.md`
see issue: https://github.com/qmk/qmk_firmware/issues/9868
*  https://github.com/qmk/qmk_firmware/issues/9868
=> added list of MIDI keycodes

keyboards/nullbitsco/nibble/keymaps/oled_status/keymap.c
=> Fix encoder_update_user signature for nullbitsco/nibble olead

util/chibios_conf_updater.sh, util/generate_internal_docs.sh, util/install/arch.sh, util/install/debian.sh, util/install/fedora.sh, util/install/freebsd.sh, util/install/gentoo.sh, util/install/linux_shared.sh, util/install/macos.sh, util/install/msys2.sh, util/install/slackware.sh, util/install/solus.sh, util/install/void.sh, util/new_keyboard.sh, util/qmk_install.sh, util/rules_cleaner.sh, util/travis_build.sh, util/travis_compiled_push.sh, util/travis_test.sh
Changing path to bash from /bin/bash to more versatile /usr/bin/env bash
Makes it more robust, especially on systems without bash under /bin/bash
*
=> /bin/bash to /usr/bin/env bash

docs/ja/internals_gpio_control.md
Update Japanese translation of docs/internals_gpio_control.md.
* Add 'Atomic Operation' section
=> [Docs] update Japanese translation of internals_gpio_control.md

docs/ja/feature_ps2_mouse.md
Changed following the change in the definition of `PS2_MOUSE_SCROLL_BTN_MASK` in the original document.
```c
#define PS2_MOUSE_SCROLL_BTN_MASK (1<<PS2_MOUSE_BTN_MIDDLE) /* Default */
```
=> [Docs] Updated Japanese translation of feature_ps2_mouse.md.

.github/workflows/api.yml, .github/workflows/develop_api.yml
Allow the API data generation to be triggered manually, not just during keyboard pushes.
=> Enable manual trigger for api data

keyboards/crkbd/keymaps/via/config.h
=> Fix VIA compilation issues for RGB Matrix

keyboards/kyria/keymaps/plattfot/README.md, keyboards/kyria/keymaps/plattfot/config.h, keyboards/kyria/keymaps/plattfot/keymap.c
- Major change in the keymap to work with EurKey. Which relaxes some
constraints it had before when it had to take in consideration two
layouts.
With this the parenthesis can be moved to a better location instead
of being in the top right corner.
This also allows `esc`, `del` and `rctrl` to be moved to the base layer.
Only downside is that `ctrl+lalt` needed to be removed and instead
`AltGr` takes it's place. Add `rctrl` on right thumb cluster to
compensate for this which need some reorganization on the thumb
cluster.
- Split the symbol and function keys layer into two layers, one for
each hand. Make it easier to press symbols and function keys.
- Add some symbols specific for the EurKey layout.
- Change from running `C-<tab>` `S-C-<tab>` to `page up`/`down` for the right
rotary. As …
=> [keymap] plattfot - Keymap updates for Kyria

keyboards/crkbd/keymaps/via/config.h
=> [Keymap] Fix Corne Via Layout properly

keyboards/capsunlocked/cu7/config.h, keyboards/capsunlocked/cu7/cu7.c, keyboards/capsunlocked/cu7/cu7.h, keyboards/capsunlocked/cu7/info.json, keyboards/capsunlocked/cu7/keymaps/default/keymap.c, keyboards/capsunlocked/cu7/keymaps/default/readme.md, keyboards/capsunlocked/cu7/readme.md, keyboards/capsunlocked/cu7/rules.mk
Support for the CapsUnlocked CU7, a 3x2 key macropad with clickable rotary encoder.
Basic support for the CU7, a 32u4-powered 6-key macropad with rotary encoder and RGB underglow. Tested on the production PCB.
N/A
=> CapsUnlocked CU7

keyboards/massdrop/alt/matrix.c, keyboards/massdrop/alt/rules.mk, keyboards/massdrop/ctrl/matrix.c, keyboards/massdrop/ctrl/rules.mk
=> Refactor Drop boards to custom matrix lite

keyboards/mechlovin/infinity87/rev1/rogue87/info.json, keyboards/mechlovin/infinity87/rev1/rouge87/info.json
I we encounter an error when compiling on QMK.config (please see attached picture). 
We suspect that the issue may stem from the layout property (it was "LAYOUT" instead of "LAYOUT_all")
*
=> correct data for info.json

keyboards/crkbd/keymaps/kidbrazil/keymap.c, keyboards/dztech/dz60rgb/keymaps/piv3rt/keymap.c
I believe this should (at least partially) allow for #13371 to be reverted.
@kidBrazil @piv3rt
*
=> Fix some RGB Matrix-enabled keymaps referring to RGBLight mode

keyboards/atreus/keymaps/erlandsona/keymap.c, keyboards/atreus/keymaps/khitsule/keymap.c, keyboards/bpiphany/kitten_paw/keymaps/ickerwx/keymap.c, keyboards/clueboard/66/keymaps/magicmonty/keymap.c, keyboards/clueboard/66/keymaps/tetris/keymap.c, keyboards/gh60/revc/keymaps/dbroqua_7U/keymap.c, keyboards/infinity60/keymaps/jpetermans/keymap.c, keyboards/whitefox/keymaps/kim-kim/keymap.c, keyboards/whitefox/keymaps/matt3o/keymap.c, layouts/community/ergodox/coderkun_neo2/keymap.c, layouts/community/ergodox/colemak_osx_pc_no/keymap.c, layouts/community/ergodox/deadcyclo/keymap.c, layouts/community/ergodox/guni/keymap.c, layouts/community/ergodox/norwegian_programmer_osx_pc/keymap.c, layouts/community/ergodox/norwegian_programmer_osx_pc_colemak/keymap.c, layouts/community/ergodox/osx_whiskey_tango_foxtrot_capslock/keymap.c, layouts/community/ergodox/workman_osx_mdw/keymap.c
These were some of the easier ones, and the LF boards will need their own PR.
*
=> Migrate more `fn_actions` stuff

docs/ja/newbs_getting_started.md
Update Japanese document.
Delete notes that are no longer needed in #13460.
=> [Docs] Remove unwanted notes

docs/driver_installation_zadig.md
Added a section on uninstallation of drivers, and the View->Devices by container option.
* Fixes qmk/qmk_toolbox#191
=> Improve driver installation docs

keyboards/aeboards/constellation/rev2/config.h
=> [Bug] Constellation Rev2

keyboards/winkeyless/bface/keymaps/p3lim/README.md, keyboards/winkeyless/bface/keymaps/p3lim/keymap.c, keyboards/winkeyless/bface/keymaps/p3lim/rules.mk
=> Update bface p3lim keymap

keyboards/projectcain/vault45/config.h, keyboards/projectcain/vault45/info.json, keyboards/projectcain/vault45/keymaps/default/config.h, keyboards/projectcain/vault45/keymaps/default/keymap.c, keyboards/projectcain/vault45/keymaps/default/readme.md, keyboards/projectcain/vault45/keymaps/default/rules.mk, keyboards/projectcain/vault45/readme.md, keyboards/projectcain/vault45/rules.mk, keyboards/projectcain/vault45/vault45.c, keyboards/projectcain/vault45/vault45.h
- [ x] Keyboard (addition or update)
* 
=> adding my keyboard and keymap

docs/feature_led_indicators.md
Currently, this feature isn't supported on splits, spent about an hour troubleshooting my board and firmware before asking, and turns out it's not in place. Note added to save others from this in the future.
*
=> Added note about no split support

keyboards/cannonkeys/vicious40/rules.mk
When we went through the review process, I didn't catch that one of the commits turned sleep LED on.
This breaks the build as the keyboard isn't setup to support sleep LED.
*
=> Fix vicious40 rules

keyboards/rart/rartland/keymaps/default/keymap.c, keyboards/rart/rartland/keymaps/via/keymap.c
Fixed number layer on keymap
*
=> fixed number layer on keymap

keyboards/aeboards/constellation/rev2/config.h
@Xelus22
```
☒ aeboards/constellation/rev2: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 15 != 14
```
(oddly this value seems to be correct in master, no idea why it hasn't synced)
*
=> Fix MATRIX_COLS for aeboards/constellation/rev2

keyboards/peranekofactory/tone/rev1/config.h, keyboards/peranekofactory/tone/rev2/config.h
@peraneko
```
☒ peranekofactory/tone/rev1: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 8 != 10
☒ peranekofactory/tone/rev2: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 8 != 10
```
*
=> Fix MATRIX_COLS for peranekofactory/tone

keyboards/xd004/keymaps/narze/keymap.c, keyboards/xd004/keymaps/narze/readme.md
* Add narze keymap of keyboard xd004
=> [Keymap] narze/xd004

keyboards/clawsome/hatchback/hatchback.h, keyboards/reviung5/config.h
because docker/travis APIs being ... crippled by cryptomining
=> Fix clawsome/hatchback and reviung5 compile issues

keyboards/dztech/dz60rgb/readme.md, keyboards/dztech/dz60rgb/v2_1/config.h, keyboards/dztech/dz60rgb/v2_1/rules.mk
Adds new keyboard version: dztech/dz60rgb/v2_1
*
=> [Keyboard] adds new keyboard version: dztech/dz60rgb/v2_1

keyboards/fc660c/matrix.c, keyboards/fc980c/matrix.c, keyboards/hhkb/ansi/matrix.c, keyboards/hhkb/jp/matrix.c
Add avr/timer_avr.h as an include to the matrix.c files. This is a quick fix and I guess they all could do with reworking properly.
I've added the include above "hhkb_avr.h" as it's required in that header.
=> [develop] Fix builds broken by #12240

keyboards/handwired/promethium/config.h
=> [Keyboard] Fix matrix issues with Promethium

keyboards/massdrop/alt/alt.c, keyboards/massdrop/ctrl/ctrl.c
=> [Keyboard] Fix matrix delay on Drop boards

keyboards/sekigon/grs_70ec/matrix.c
=> [Keyboard] Fix split matrix for sekigon grs 70ec

keyboards/pearlboards/pandora/keymaps/via/keymap.c
=> [Keyboard] Fix type on pandora via keymap

quantum/split_common/split_util.c, tmk_core/common/usb_util.c, tmk_core/common/usb_util.h, tmk_core/protocol/chibios/usb_util.c, tmk_core/protocol/lufa/usb_util.c, tmk_core/protocol/vusb/usb_util.c
`usb_disable` already exists within the arm_atsam vendor code.
Longer term, I see the usb_util code being wrapped into a better abstraction (maybe forming part of the existing `host` functionality) and/or the introduction of another HAL.
Short term, this avoids some build failures on drop boards.
*
=> Avoid LTO conficts on arm_atsam

keyboards/xd002/keymaps/multilayer_rgb/keymap.c, keyboards/xd002/keymaps/multilayer_rgb/rgblite.h, keyboards/xd002/keymaps/rgb_lite/keymap.c, keyboards/xd002/keymaps/rgb_lite/rgblite.h
Broken during recent refactoring, mainly due to trying to imitate rgblight too much.
=> Fix up xd002 rgb keymaps

docs/feature_dip_switch.md
=> [develop][docs] Fix typo in dip switch example

quantum/audio/voices.h, quantum/keymap_common.c, quantum/quantum.h, quantum/rgblight.c, quantum/rgblight.h, tmk_core/common/arm_atsam/platform.h, tmk_core/common/avr/platform.h, tmk_core/common/chibios/platform.h, tmk_core/common/print.h, tmk_core/common/timer.h
=> Refactor some platform dependent logic

keyboards/meira/featherble/config.h, keyboards/meira/matrix.c, keyboards/meira/promicro/config.h
It's hardcoded to only scan 4 columns, so implemented a new define.
=> [develop] Fix meira compliation

drivers/haptic/solenoid.c
needs it for `writePin` functions. 
* tzarc ci
=> [Bug] Include gpio.h in solenoid driver for GPIO Control functions

keyboards/splitkb/kyria/readme.md
Update readme to reflect new path.
=> Update Kyria path in readme

docs/feature_tap_dance.md
Added a `default` case in `switch(ql_tap_state.state)` at line 493 and 494.
Without the `default` case, compiling firmware with Example 6 code will encounter 2 errors:
`enumeration value 'TD_NONE' not handled in switch`
`enumeration value 'TD_UNKNOWN' not handled in switch`
I'm on the latest dev brach, after adding the `default` case, compile passed without error and firmware tested on GMMK Pro, which works fine. It really a minor thing and not sure if it only happends to me since I only have one QMK supported board for now.
Solution was provided by fauxpark(not sure if his/her Github username are the same) on discord and credit goes to him/her.
=> Add `default` case in Example 6.

keyboards/handwired/dactyl_manuform/dactyl_manuform.h
=> Fix typo in Dactyl Manuform

tmk_core/common/test/platform.h
=> Fix unit tests after recent refactor

keyboards/jones/v03/config.h, keyboards/jones/v03_1/config.h
Change "jones" Vendor ID to match my other keyboard, "unison".  
0xFEED (QMK's default) to 0xB9DD
The reason is below.
- Consistency (same ID for all my keyboard)
- To make VIA enabled firmware
"unison"
https://github.com/qmk/qmk_firmware/blob/master/keyboards/unison/v04/config.h
*
=> Change "jones" Vendor ID to match my other keyboard, "unison".

keyboards/ymdk/ymd40/v2/keymaps/via/keymap.c, keyboards/ymdk/ymd40/v2/keymaps/via/readme.md, keyboards/ymdk/ymd40/v2/keymaps/via/rules.mk
=> Added YMD40v2 VIA

docs/hand_wire.md
While described in the image it should still be stated verbatim for those not following suggested images exactly.
=> Added information on soldering diodes in parallel

keyboards/nack/info.json, keyboards/nack/nack.h
[title]
Describes the layout better at a glance, because *[reasons]*...
cc @farfalleflickan (keyboard maintainer)
*
=> Nack: rename layout macro to LAYOUT_ortho_4x13

keyboards/xbows/ranger/info.json, keyboards/xbows/ranger/keymaps/default/keymap.c, keyboards/xbows/ranger/keymaps/via/keymap.c, keyboards/xbows/ranger/ranger.h
[title]
cc @XBowsTech (keyboard maintainer)
=> X-Bows Ranger: rename LAYOUT to LAYOUT_tkl_ansi

keyboards/handwired/onekey/keymaps/console/keymap.c
I was using the wrong function. `printf()` on AVR crashes :(
*
=> Fix onekey console keymap

keyboards/bioi/g60/rules.mk, keyboards/bioi/morgan65/rules.mk
Fix up paths for bioi boards - parallel compilation failures due to file collisions.
=> bioi CI build fix

keyboards/matrix/m20add/rules.mk
Follow up to #13821, since I missed the SRC include. 
This time, I verified it compiles all the way.
=> [Keyboard] Fix SRC include for matrix/m20add issi driver

docs/feature_bootmagic.md
Fix documentation grammar. An extra word that should not be there is removed.
* 
- [NA] I have added tests to cover my changes.
=> Remove extra word

keyboards/boardsource/holiday/spooky/info.json
- change LAYOUT to LAYOUT_ortho_2x3
https://github.com/qmk/qmk_firmware/blob/2b097d670a9fa458b8d059f824a0cbbd5b6c6659/keyboards/boardsource/holiday/spooky/spooky.h#L29 vs. https://github.com/qmk/qmk_firmware/blob/2b097d670a9fa458b8d059f824a0cbbd5b6c6659/keyboards/boardsource/holiday/spooky/info.json#L8
cc @daysgobye (keyboard maintainer)
=> boardsource/holiday/spooky: update info.json layout macro reference

quantum/template/avr/readme.md, quantum/template/ps2avrgb/readme.md
=> Add bootloader section to keyboard template

keyboards/knops/mini/keymaps/default-gsm-newbs/keymap.c, keyboards/knops/mini/keymaps/default/keymap.c, keyboards/knops/mini/keymaps/knops/keymap.c, keyboards/knops/mini/keymaps/mverteuil/keymap.c, keyboards/wilba_tech/rama_works_m6_a/keymaps/knops/keymap.c
Noticed the knops/mini default keymap was broken in the webhook and then looking at #12116 there were some others.
=> [develop] Fix knops keymaps

keyboards/ckeys/handwire_101/config.h, keyboards/ckeys/handwire_101/handwire_101.c, keyboards/ckeys/handwire_101/handwire_101.h, keyboards/ckeys/handwire_101/info.json, keyboards/ckeys/handwire_101/keymaps/default/config.h, keyboards/ckeys/handwire_101/keymaps/default/keymap.c, keyboards/ckeys/handwire_101/rules.mk
Tidies up the codebase, and fixes an issue with the QMK Configurator implementation.
cc @brandenbyers (keyboard maintainer)
=> cKeys Handwire 101 Refactor

keyboards/keebio/kbo5000/keymaps/via/rules.mk, keyboards/keebio/sinc/keymaps/via/rules.mk
=> [Keyboard] Remove console from keebio via keyboards

util/update_chibios_mirror.sh
=> Update ChibiOS-Contrib, mirroring script.

keyboards/gmmk/pro/readme.md
Many GMMK Pro users have [reported stripped screws](https://www.reddit.com/r/glorious/search/?q=screw&restrict_sr=1), so I've added specs to find replacement screws to the readme.
(Dusty) picture with the McMaster screw mentioned: 
Picture with some dirt cheap M2x5mm screws from Aliexpress:
*
=> Add replacement screw specifications to GMMK Pro readme

keyboards/gmmk/pro/iso/readme.md
Automerge of #13903 only moved the readme changes to the ANSI variant, this PR copies those changes to the ISO readme as well.
*
=> Copy GMMK Pro screw specs to ISO readme

keyboards/owl8/config.h, keyboards/owl8/keymaps/default/keymap.c, keyboards/owl8/keymaps/default/readme.md, keyboards/owl8/keymaps/via/keymap.c, keyboards/owl8/keymaps/via/readme.md, keyboards/owl8/keymaps/via/rules.mk, keyboards/owl8/owl8.c, keyboards/owl8/owl8.h, keyboards/owl8/readme.md, keyboards/owl8/rules.mk
=> Add owl8 keyboard

keyboards/handwired/xealousbrown/config.h, keyboards/handwired/xealousbrown/matrix.c, keyboards/handwired/xealousbrown/readme.md, keyboards/handwired/xealousbrown/rules.mk, keyboards/handwired/xealousbrown/xealousbrown.c
I noticed sometimes i'd get ghost inputs because my delay after unselecting pins was too short.
I did some testing and got 15us as the answer. Then i realised there's a new api for this, so updated the keyboard code.
Use new matrix_output_select_delay api
*  Other Keys on same column would trigger sometimes when pushing a key.
=> Use new matrix_output_select_delay api

keyboards/melgeek/mojo68/rev1/config.h
=> Modify key drive pins for mojo68.

keyboards/keebio/nyquist/keymaps/peott-fr/keymap.c
Adding my Nyquist keymap.
* 
- [x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the apropriate changes.
=> Adding my Nyquist keymap

keyboards/hp69/config.h, keyboards/hp69/keymaps/via/keymap.c
Added CapsLED and ScrollLock LEDs
- [*] New feature
* 
- [*] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [*] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [*] I have updated the documentation accordingly.
- [*] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
=> Added CapsLED and ScrollLock LEDs

lib/python/qmk/json_schema.py
As reported on discord: https://discord.com/channels/440868230475677696/869749041074937936/873002805273710683
=> Make json imports more robust

keyboards/aozora/hotswap/config.h, lib/python/qmk/info.py
An error in a keyboard exposed a missing return code that caused `qmk generate-api` to upload incomplete data after a failure.
=> Fix generate api

keyboards/niu_mini/keymaps/edvard/keymap.c, keyboards/niu_mini/keymaps/edvard/readme.md
This PR adds a new keymap for the niu_mini
Created the keymap and readme files
I can compile the keymap.c with my qmk installation
First PR:), sorry for any possible inconveniences
*
=> New keymap for the niu_mini

keyboards/ferris/0_2/bling/bling.c
Changes the include as the issi drivers have moved.
=> [develop] Fix compliation for ferris 0.2 bling

keyboards/ristretto/rules.mk
Changed `BOOTLOADER=caterina` to `BOOTLOADER=atmel-dfu`
Should be atmel-dfu instead of caterina as the mcu is integrated instead of on a pro-micro/elite-c
*
=> Ristretto - Update bootloader

keyboards/crkbd/keymaps/vayashiko/config.h, keyboards/crkbd/keymaps/vayashiko/keymap.c, keyboards/crkbd/keymaps/vayashiko/rules.mk
Add new keymap named "vayashiko."
This keymap is made for those who type Japanese.
This keymap contains KC_MHEN and KC_HENK to switch between Japanese and English, which makes typing very fast for you.
*
=> adding my keymap "vayashiko"

docs/feature_wpm.md
Wrap last example in backticks to format as code in markdown.
* N/A
=> Fix example code formatting in feature_wpm.md

keyboards/hp69/keymaps/via/keymap.c
- [*] Bugfix
* 
- [*] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [*] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
=> Hp69 - Update led logic

docs/ChangeLog/20210529.md
This was confusing to me when I updated, so I want to make it more clear for those that come after.
*
=> Update breaking changes file with clearer explanation of encoder updates

lib/python/qmk/cli/__init__.py
This is needed so people can install to the virtualenv the [new Linux packages](https://github.com/qmk/qmk_fpm) use.
=> Use sudo to install modules if needed

keyboards/ungodly/launch_pad/config.h
Fix merge issue with config file for Ungodly Launch Pad.
=> [Keyboard] Fixup Ungodly Launch Pad config

keyboards/gmmk/pro/ansi/keymaps/andrebrait/keymap.c
Remove the dependency on `lib8tion`. I was using `sin8` in order to get either a 1 or a 0, which can be accomplished with just some bitwise operations, so I just changed it. This makes things a lot simpler. I also renamed some defines inside the keymap file to make it slightly easier to parse when reading.
=> [Keymap] Improve andrebrait keymap

keyboards/boardsource/microdox/rules.mk
=> Add split_3x5_3 community layout support to boardsource/microdox

docs/reference_keymap_extras.md
Clarifying some parts, made the table a little more precise, added the macOS Swedish/Swedish Pro headers to the list.
*
=> Rework keymap_extras docs

keyboards/ocean/stealth/config.h, keyboards/ocean/stealth/info.json, keyboards/ocean/stealth/keymaps/default/keymap.c, keyboards/ocean/stealth/keymaps/via/keymap.c, keyboards/ocean/stealth/keymaps/via/rules.mk, keyboards/ocean/stealth/readme.md, keyboards/ocean/stealth/rules.mk, keyboards/ocean/stealth/stealth.c, keyboards/ocean/stealth/stealth.h
add Stealth macropad and via support
*
=> add Stealth macropad

keyboards/bastardkb/skeletyl/skeletyl.c, keyboards/bastardkb/skeletyl/skeletyl.h
The Skeletyl is a keyboard from Bastard Keyboard by @bstiq, with per-key RGB as an option: https://bastardkb.com/skeletyl/.
This change adjusts the LED configuration of the Skeletyl and fixes the LED-to-key mapping.  It also updates the LED's physical position reference to better reflect the physical layout of the LEDs on the original keyboard case/PCB (*eg.* vertically aligns the outermost thumb key with the innermost column of each half).
The LEDs index were determined empirically using, among other things, a naive RGB matrix animation (`RGB_MATRIX_CUSTOM_CYCLE_LED_INDEX`) that iterates in a linear fashion with a step of `1` from `0` to `DRIVER_LED_TOTAL - 1` and calls `rgb_matrix_set_color(index, r, g, b)` to surface and observe the LED physical layout/wiring.  (Note that this …
=> bastardkb/skeletyl: fix LED configuration

docs/ja/feature_tap_dance.md
Update Japanese translation of docs/ja/feature_tap_dance.md
*
=> update feature_tap_dance.md translation

tmk_core/protocol/arm_atsam/main_arm_atsam.c
Fixup atsam builds. Works on a CTRL.
=> Fixup atsam builds.

keyboards/montex/rules.mk
* Bootmagic full is dangerous to use on a keypad.
* Keypads don't support things like spacebar.
This could result in a bricked device.
This device is a keypad, as a result there aren't going to be good bootmagic defaults when using full.
We need to ensure users can reset their devices via the matrix otherwise they could end up with bricked devices.
*
=> Use Bootmagic Lite

keyboards/pistachio_mp/config.h, keyboards/pistachio_mp/keymaps/via/keymap.c, keyboards/pistachio_mp/keymaps/via/readme.md, keyboards/pistachio_mp/keymaps/via/rules.mk, keyboards/pistachio_pro/keymaps/default/readme.md, keyboards/pistachio_pro/keymaps/rate/readme.md, keyboards/pistachio_pro/keymaps/via/readme.md
=> Added VIA keymap for pistachio_mp

keyboards/dztech/dz60rgb_wkl/readme.md, keyboards/dztech/dz60rgb_wkl/v2_1/config.h, keyboards/dztech/dz60rgb_wkl/v2_1/rules.mk
New keyboard version: DZ60RGB-WKL v2_1
*
=> [Keyboard] adds new keyboard version: dztech/dz60rgb_wkl/v2_1

keyboards/dumbpad/config.h, keyboards/dumbpad/dumbpad.c, keyboards/dumbpad/dumbpad.h, keyboards/dumbpad/info.json, keyboards/dumbpad/keymaps/default/keymap.c, keyboards/dumbpad/keymaps/via/keymap.c, keyboards/dumbpad/keymaps/via/rules.mk, keyboards/dumbpad/rules.mk
=> Dumbpad VIA support added

build_keyboard.mk, data/schemas/keymap.jsonschema
=> Fix issues with recent keymap.json changes

quantum/dip_switch.c
My take of the tidy up suggestion within #13074.
This keeps the implementation style consistent what what exists right now in the code base.
*
=> Align DIP_SWITCH_PINS_RIGHT implementation with encoders

quantum/led_matrix/led_matrix.c
#14084 wasn't quite correct.
```
ergodox_infinity:default
terrazzo:default
whitefox:default
```
*
=> Fix LED Matrix suspend code

drivers/eeprom/eeprom_spi.c
This file doesn't compile, otherwise.
=> Fix up compilation issues.

util/install/macos.sh
This will remove the old way of forcefully upgrading peoples systems
without proper notice and consent.
If there are any packages or dependencies that needs upgrading it will
prompt the user and he/she/they/ze can consent to the upgrade or
continue without at own risk.
* Fixes #12794
=> Only upgrade formulae ~~Remove brew upgrade and prompts the user~~

keyboards/ocean/wang_v2/keymaps/default/keymap.c, keyboards/ocean/wang_v2/keymaps/via/keymap.c
update default and via keymap for ocean/wang_v2
*
=> update default and via keymap for ocean/wang_v2

platforms/avr/flash.mk
Seriously, it was the comments....
* https://discord.com/channels/440868230475677696/869749041074937936/879491837960810497
=> Fix bootloadHID comments breaking :flash

quantum/action_tapping.c, quantum/keymap.h, quantum/keymap_common.h
#14083 introduce bloat of about 2k. This is due to the include of `keymap.h`, which is only used for `keymap_key_to_keycode`.
=> Short term bodge for firmware size bloat

docs/ChangeLog/20210828.md
Clarifies the terminology to avoid confusion.
=> Bootmagic lite docs clarity.

util/update_chibios_mirror.sh
Fixes issue for mismatching remotes.
=> ChibiOS Update Script Updates

keyboards/primekb/prime_e/keymaps/peott-fr/keymap.c
=> My Prime E keymap.

keyboards/keebio/iris/iris.h, keyboards/keebio/iris/rev5/config.h, keyboards/keebio/iris/rev5/rev5.c, keyboards/keebio/iris/rev5/rev5.h, keyboards/keebio/iris/rev5/rules.mk
Add Iris Rev. 5, pinouts and everything are the same as Rev. 4, only difference is that TRRS was switched out for USB-C
*
=> Add Iris Rev. 5

docs/feature_key_overrides.md
This is a fix for the links in the documentation of the feature key overrides.
*
=> Documentation: Fix links in key overrides

keyboards/splitkb/kyria/keymaps/cwebster2/config.h, keyboards/splitkb/kyria/keymaps/cwebster2/keymap.c, keyboards/splitkb/kyria/keymaps/cwebster2/rules.mk, users/cwebster2/keycodes.c, users/cwebster2/my_miryoku.h
General updates to my keymaps and user files that have been waiting for the latest develop merge.
*
=> Personal keymap and user updates

docs/faq_keymap.md
Updated path to keycode.h (file moved in #13673).
keycode.h file was moved in #13673. Documentation link was not updated accordingly.
- [`x] Documentation
=> Update path to keycode.h

keyboards/hineybush/h87a/keymaps/peott-fr/keymap.c
=> Adding my H87 keymap.

keyboards/keebio/nyquist/keymaps/peott-fr/keymap.c
Removing some random text that got accidentally pasted in there... 
*
=> Fine-tuning Nyquist keymap.

keyboards/cu75/cu75.c, keyboards/cu75/cu75.h, keyboards/ergotaco/ergotaco.h, keyboards/georgi/georgi.h, keyboards/gergo/gergo.h, keyboards/handwired/dactyl/dactyl.h, keyboards/handwired/frenchdev/frenchdev.h, keyboards/hotdox/hotdox.h, keyboards/ktec/ergodone/ergodone.h, keyboards/lfkeyboards/lfk65_hs/lfk65_hs.h, keyboards/lfkeyboards/lfk87/lfk87.c, keyboards/lfkeyboards/lfk87/lfk87.h, keyboards/lfkeyboards/mini1800/mini1800.c, keyboards/lfkeyboards/mini1800/mini1800.h, keyboards/lfkeyboards/smk65/revb/revb.c, keyboards/lfkeyboards/smk65/revb/revb.h, keyboards/sx60/sx60.h
- Remove conditional `kb.h` includes
- Convert `cbi()`/`sbi()` macros to QMK GPIO macros
- Remove unused `CPU_PRESCALE(n)` macros (looks like copypasta)
*
=> Remove more cruft in keyboard files

keyboards/naiping/nphhkb/info.json, keyboards/naiping/nphhkb/keymaps/default/keymap.c, keyboards/naiping/nphhkb/keymaps/via/keymap.c, keyboards/naiping/nphhkb/nphhkb.h, keyboards/naiping/nphhkb/readme.md, keyboards/naiping/nphhkb/rules.mk
[title].
Also some minor touch-ups to the readme and `info.json`.
cc @weirdo-f (keyboard maintainer)
=> Naiping NPhhkb: 60_tsangan_hhkb Community Layout support 

keyboards/boardsource/technik_o/rules.mk, keyboards/boardsource/technik_s/rules.mk
Enable extra keys to support media keys that are placed on default keymaps.
Mentioned on Boardsource discord.
=> Enable extra keys for Technik ortho and stagger

docs/reference_glossary.md
The Space Cadet markdown link got broken in https://github.com/qmk/qmk_firmware/pull/5277
=> Fix Space Cadet md link

docs/feature_oled_driver.md, drivers/oled/oled_driver.h, drivers/oled/ssd1306_sh1106.c
This pr exposes the `oled_scrolling` state through a new function `is_oled_scrolling`. 
In the future it might be interesting to not only expose if the display is scrolling but also in which direction, thoughts?
=> Add `is_oled_scrolling`

tmk_core/common/chibios/eeprom_stm32_defs.h
Looks like I broke a few things in #14275....
=> Fix eeprom for Durgod boards

keyboards/3w6/rev1/matrix.c, keyboards/3w6/rev2/matrix.c
Part of the long term goal of unifying the i2c_master api. Little value in keeping the more verbose code over the read/write reg abstraction.
cc @weteor as maintainer
=> 3w6 - Refactor use of AVR only I2C functions

keyboards/lazydesigners/the40/keymaps/via/keymap.c
Update VIA support for lazydesigners/the40
Update more layouts supported in VIA for lazydesigners/the40
*
=> Update VIA support for lazydesigners/the40

keyboards/3w6/rev1/matrix.c, keyboards/3w6/rev2/matrix.c, keyboards/handwired/dactyl/dactyl.h, keyboards/sx60/sx60.h
=> Fixes for recent i2c migrations

keyboards/work_louder/work_board/keymaps/default/keymap.c, keyboards/work_louder/work_board/keymaps/via/keymap.c
Just a couple of layout tweaks.
=> [Keyboard] Minor tweaks to Work Board layout

docs/feature_led_matrix.md, docs/feature_rgb_matrix.md
Due to the way that `*_matrix_legacy_enables.h` content works, the old behaviour is still in effect. All animations are always enabled, setting any of `ENABLE_` defines within the docs does not do anything. Given the keyboards need to be refactored, it seems safe enough to keep the old logic in the docs for now.
=> Align rgb/led matrix docs with current behaviour

docs/ja/compatible_microcontrollers.md
update Japanese translation of docs/compatible_microcontrollers.md.
just changed/added some links. i.e. no translation is added.
*
=> [Docs] update Japanese translation of compatible_microcontrollers.md

common_features.mk
...
* 
- [] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> RN42 Bluetooth typo fix

quantum/backlight/backlight_chibios.c
Says SPI, in backlight... 99.99% sure that's just a typo. 
*  Tzarc CI
=> fix typo in backlight code from #14439

docs/feature_oled_driver.md
Changed line 21 from saying "three steps" to "two steps" as there are only two steps
*
=> Fixed incorrect amount of steps for oled usage

docs/feature_led_indicators.md, docs/feature_split_keyboard.md
The new heading will also be useful for the discord bot (I'll PR that later) and the led indicators being out of date was a good excuse for adding it.
This also consolidates the repeated warning to under the new heading.
Maybe not sold on the heading name?
=> [Docs] add sync options heading, update led indicators

tmk_core/protocol/usb_descriptor.c
=> [Bug] fix logical minimum in Programmable Button rdesc

keyboards/gmmk/pro/ansi/keymaps/mattgauf/ansi.c, keyboards/gmmk/pro/ansi/keymaps/mattgauf/config.h, keyboards/gmmk/pro/ansi/keymaps/mattgauf/helpers.c, keyboards/gmmk/pro/ansi/keymaps/mattgauf/keymap.c, keyboards/gmmk/pro/ansi/keymaps/mattgauf/keymap.h, keyboards/gmmk/pro/ansi/keymaps/mattgauf/keymap_helpers.h, keyboards/gmmk/pro/ansi/keymaps/mattgauf/readme.md, keyboards/gmmk/pro/ansi/keymaps/mattgauf/rules.mk
Add my personal GMMK Pro keymap 
Made some quality of life changes in userspace:
1. Changed the RGB matrix flag for the caps lock LED to be 0x01. (ansi.c, via rules.mk)
2. Defined custom RAW_USAGE codes for PAGE and ID.
3. Adjusted configuration of dynamic macro size
4. Disabled several RGB Matrix effects
5. Defined helper functions for RGB lighting control in helpers.c
6. Defined QoL constants for LED locations based on default keymap
7. Keycode, and encoder changes are listed in the keymap readme.md.
* None
=> [Keymap] Adding personal keymap

keyboards/xbows/knight/rules.mk, keyboards/xbows/knight_plus/rules.mk, keyboards/xbows/numpad/rules.mk
=> Update rules.mk for xbows keyboard 

keyboards/dtisaac/dosa40rgb/rules.mk
=> [Keyboard] Fix BT rules for dosa40rgb

keyboards/yushakobo/quick17/keymaps/default/keymap.c, keyboards/yushakobo/quick17/keymaps/via/keymap.c
=> [Keyboard] Fix Compiler issues for quick17

keyboards/rgbkb/mun/keymaps/xulkal2/rules.mk, keyboards/rgbkb/mun/rules.mk
Comment out the custom matrix scan code  (for now) as that is preventing the keyboard functionality.
*
=> Quick fixes for the Mun to unblock customers

keyboards/boston/rules.mk
* Enabled Mousekeys in rules.mk (there was no particular reason this was left off originally)
=> Enabled Mousekeys in rules.mk

keyboards/rgbkb/mun/keymaps/peott-fr/config.h, keyboards/rgbkb/mun/keymaps/peott-fr/keymap.c
=> Adding my Mun keymap.

docs/feature_led_matrix.md, docs/feature_rgb_matrix.md
=> [Docs] fix wrong director; add link

docs/feature_encoders.md, docs/ja/feature_encoders.md
As title. I know there's an explanation right below but this code just gets copy and pasted. This has resulted in a few queries on discord why the encoder doesn't function correctly (as it's also running the keyboard encoder function).
*
=> [Docs] Modify encoder_update_user example to return false

keyboards/smallkeyboard/config.h, keyboards/smallkeyboard/info.json, keyboards/smallkeyboard/keymaps/default/keymap.c, keyboards/smallkeyboard/keymaps/via/keymap.c, keyboards/smallkeyboard/keymaps/via/rules.mk, keyboards/smallkeyboard/readme.md, keyboards/smallkeyboard/rules.mk, keyboards/smallkeyboard/smallkeyboard.c, keyboards/smallkeyboard/smallkeyboard.h
=> [keyboard] NEW smallkeyboard support ，Thanks

docs/custom_quantum_functions.md, docs/ja/custom_quantum_functions.md, docs/zh-cn/custom_quantum_functions.md
I couldn't think of a good example to place here. I've also modified the examples in other languages by just removing the line, I didn't want to insert an english comment. Maybe someone will have a better suggestion for an example to use.
Edited as searching for `rgb matrix suspend` in docs will show this as a top result, which is now handled else where.
=> [Docs] update suspend_*_user examples

docs/ja/feature_advanced_keycodes.md
update Japanese translation of docs/feature_advanced_keycodes.md.
*
=> [Docs] update Japanese translation of feature_advanced_keycodes.md

docs/ja/feature_backlight.md
update Japanese translation of docs/feature_backlight.md.
*
=> [Docs] update Japanese translation of feature_backlight.md

keyboards/meira/featherble/featherble.c, keyboards/meira/featherble/featherble.h, keyboards/meira/info.json, keyboards/meira/keymaps/default/keymap.c, keyboards/meira/meira.c, keyboards/meira/meira.h, keyboards/meira/promicro/promicro.c, keyboards/meira/promicro/promicro.h, keyboards/meira/readme.md, keyboards/meira/rules.mk
[title]
cc @colemarkham (keyboard maintainer)
=> Meira Refactor

keyboards/planck/keymaps/default/config.h, keyboards/planck/keymaps/default/keymap.c, keyboards/preonic/keymaps/default/config.h, keyboards/preonic/keymaps/default/keymap.c
Mostly add/update the license headers on the default keymaps
* Copypasta
=> [Keyboard] Fix default keymaps for OLKB boards

docs/understanding_qmk.md
Change faq.md to faq_general.md
*
=> Broken FAQ hyperlink

keyboards/mechlovin/adelais/adelais.h
=> [Keyboard] Fix typo in mechloving adelais header files

keyboards/aozora/hotswap/info.json, keyboards/aozora/hotswap/readme.md
Correct some issues with the `info.json` file, now that I've verified the layout data is correct.
cc @Phooood (keyboard maintainer) - Changed your `maintainer` value because some QMK tooling that's in the pipeline is going to use this field, and needs it to be a valid and accurate GitHub username.
=> Aozora Hotswap info.json clean-up

keyboards/clawsome/bookerboard/info.json, keyboards/clawsome/coupe/info.json, keyboards/clawsome/doodle/info.json, keyboards/clawsome/fightpad/info.json, keyboards/clawsome/gamebuddy/v1_0/info.json, keyboards/clawsome/gamebuddy/v1_m/info.json, keyboards/clawsome/hatchback/info.json, keyboards/clawsome/numeros/info.json, keyboards/clawsome/roadster/info.json, keyboards/clawsome/sedan/info.json, keyboards/clawsome/sidekick/info.json, keyboards/clawsome/suv/info.json
Correct some issues with the `info.json` files, now that I've verified the layout data is correct.
cc @AlisGraveNil (keyboard maintainer) - Changed your `maintainer` values because some QMK tooling that's in the pipeline is going to use this field, and needs the values to be valid and accurate GitHub usernames.
=> tidy up Clawsome Boards info.json files

keyboards/ferris/sweep/config.h
Fix alignment spacing in `config.h`
=> Fix Sweep KB pin spacing alignment

keyboards/dztech/dz60rgb_ansi/readme.md, keyboards/dztech/dz60rgb_ansi/v2_1/config.h, keyboards/dztech/dz60rgb_ansi/v2_1/rules.mk
Adds a v2_1 like the other boards, I did need to add `#define LAYER_STATE_8BIT` to keep it under size with my avr-gcc version (10.2.0). Hopefully there's not too many other lufa-ms updated boards.
=> [Keyboard] Add dz60rgb_ansi v2_1

message.mk, tmk_core/rules.mk
And tweaked it to use `MCU_ORIG` to reflect what's in the rules.mk, as `MCU` gets overwritten for ARM boards.
*
=> Move "firmware size check skipped" note to message.mk

keyboards/mechlovin/adelais/standard_led/arm/rev4/rev4.h
Fix for a bad merge conflict resolution on `qmk:develop`. https://github.com/qmk/qmk_firmware/pull/14622#issuecomment-929554241
cc @mechlovin (keyboard maintainer)
=> Fix for mechlovin/adelais/standard_led/arm/rev4

keyboards/keychron/q1/rev_0100/keymaps/gtg465x/README.md, keyboards/keychron/q1/rev_0100/keymaps/gtg465x/config.h, keyboards/keychron/q1/rev_0100/keymaps/gtg465x/keymap.c, keyboards/keychron/q1/rev_0100/keymaps/gtg465x/rules.mk
=> Keychron Q1 user keymap

docs/feature_haptic_feedback.md
=> Fix documentation for NO_HAPTIC_MOD and NO_HAPTIC_FN features.

keyboards/converter/modelm101/config.h
The Model M membrane lacks diodes and has potential ghosting issues, so we should enable `MATRIX_HAS_GHOST`.
=> [Keyboard] Add anti-ghosting support to Model M Converter

Makefile, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/generate/rules_mk.py, lib/python/qmk/cli/list/layouts.py
This was intended to work but wasn't actually working.
=> Allow community layouts to be specified in info.json

keyboards/handwired/dc/mc/001/001.c, keyboards/handwired/dc/mc/001/001.h, keyboards/handwired/dc/mc/001/config.h, keyboards/handwired/dc/mc/001/info.json, keyboards/handwired/dc/mc/001/keymaps/default/keymap.c, keyboards/handwired/dc/mc/001/keymaps/default/readme.md, keyboards/handwired/dc/mc/001/readme.md, keyboards/handwired/dc/mc/001/rules.mk
Added my media controller "keyboard", DC MC 001.
Added [my prototype media controller](https://imgur.com/a/PM9lQ). Maybe one day it'll go into production and I'll move it out of `handwired`. Who knows.
=> Added DC MC 001

docs/pr_checklist.md
Due to some misinterpretation of the PR checklist, some clarification on licensing.
=> Add clarification for licensing.

docs/feature_rgb_matrix.md, drivers/led/issi/is31fl3733.c
[datasheet](https://www.mouser.jp/datasheet/2/198/IS31FL3733B_DS-1863637.pdf) - Page 18
* Fixes #14044
=> Enable configuration of PWM frequency for IS31FL3733B

docs/feature_rgb_matrix.md, quantum/rgb_matrix/animations/pixel_rain_anim.h, quantum/rgb_matrix/animations/rgb_matrix_effects.inc
Pixel Rain effect that randomly light keys, with random hues.
=> Add Pixel Rain RGB Matrix effect

drivers/led/issi/is31fl3733.c
=> [Bug] Fix unterminated ifdef in ISSI 3733 driver

keyboards/pistachio_pro/keymaps/via/rules.mk
Compiles too large on develop. 
* Tzarc CI
=> [Keyboard] Fix size issues on pistachio pro via keymap

docs/feature_oled_driver.md
Clarify the location and format for OLED configuration options
New user on Discord mistaking them as `rules.mk` directives.
=> Clarify placement of OLED configuration options

quantum/led_matrix/led_matrix.h
=> Fixup LED matrix.

tmk_core/protocol/chibios/chibios.c
=> Fixup #15029

docs/cli_commands.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/cd.py
Go to your qmk_firmware dir with ease.
*
=> CLI: Add 'cd' subcommand

lib/python/qmk/info.py
As it says on the tin. Fixes CLI failures.
=> Fixup actions.

keyboards/mechlovin/infinity87/rev2/config.h, keyboards/mechlovin/infinity87/rev2/info.json, keyboards/mechlovin/infinity87/rev2/matrix.c, keyboards/mechlovin/infinity87/rev2/readme.md, keyboards/mechlovin/infinity87/rev2/rev2.c, keyboards/mechlovin/infinity87/rev2/rules.mk
MCU changed from Atmega32A to Atmega32u4
This design originally used Atmega32A as a budget-conscious choice due to the microcontroller shortage experienced recently. However, it lacks certain features that are necessary for our current TKL lineup, so we decided to switch to Atmega32u4 with minimal changes regarding the matrix pins and LED pins. Thank you for your support!
*
=> [MCU change] Update Infinity87 rev. 2

docs/isp_flashing_guide.md
An attempt at making this guide a little more comprehensive and straightforward.
We first go through some background on what ISP flashing is and what it's for. Then, the hardware and software required. Next, a listing of the most common bootloader .hex files with their fuse settings and USB VID/PID pairs. Finally, putting it all together to actually flash a board, and set the fuses.
*
=> Rework ISP flashing guide

docs/feature_rgb_matrix.md
Add a documented example on how to "disable" RGB matrix colors and retain the use of `rgb_matrix_indicators_user`
Frequently asked solution in the QMK discord
=> Add example for turning off RGB colors and retaining indicator function

keyboards/cradio/readme.md
Add instructions on using QMK Toolbox to set `EE_HANDS`.
Direct questions on about handedness
=> Add toolbox handedness instructions for Cradio

keyboards/ferris/sweep/readme.md
Improve readme structure and bootloader documentation.
=> Improve Sweep keyboard readme documentation

keyboards/xiudi/xd60/keymaps/ansi_split_bs_rshift_space/keymap.c, keyboards/xiudi/xd60/keymaps/ansi_split_bs_rshift_space/readme.md, keyboards/xiudi/xd60/xd60.h
Added xd60 keymap for split spacebar.
*
=> add keymap for xd60

keyboards/evyd13/gud70/keymaps/via/keymap.c, keyboards/evyd13/gud70/keymaps/via/rules.mk
Adds a VIA keymap to Gud70.
* 
=> Add VIA to Gud70

keyboards/teleport/numpad/config.h, keyboards/teleport/numpad/info.json, keyboards/teleport/numpad/keymaps/default/keymap.c, keyboards/teleport/numpad/keymaps/via/keymap.c, keyboards/teleport/numpad/keymaps/via/rules.mk, keyboards/teleport/numpad/numpad.c, keyboards/teleport/numpad/numpad.h, keyboards/teleport/numpad/readme.md, keyboards/teleport/numpad/rules.mk
Adds support for The Teleport  Macropad PCB
* Adds support for The Teleport  Macropad PCB
=> Teleport numpad

keyboards/teleport/numpad/keymaps/default/keymap.c, keyboards/teleport/numpad/keymaps/via/keymap.c
=> [Keyboard] Fix compilation issues for teleport numpad

keyboards/lime/keymaps/default/keymap.c, keyboards/lime/keymaps/default/rules.mk
Fixes oled function, and enables LTO.
* Tzarc CI
=> [Keyboard] Fix compilation issues for Lime

keyboards/sawnsprojects/krush/krush60/solder/solder.h, keyboards/sawnsprojects/krush/krush65/solder/keymaps/via/rules.mk
* Fix errors in layout macro (casing issues yay)
* Fix size issues for VIA keymap
* Tzarc CI
=> [Keyboard] Fix compilation issues for Krush boards

keyboards/gboards/gergoplex/keymaps/georgepetri/config.h, keyboards/gboards/gergoplex/keymaps/georgepetri/gergoplex.def, keyboards/gboards/gergoplex/keymaps/georgepetri/keymap.c, keyboards/gboards/gergoplex/keymaps/georgepetri/rules.mk
=> Update Gergoplex keymap

keyboards/matrix/abelx/config.h, keyboards/matrix/abelx/matrix.c
```console
$ qmk info -l -kb matrix/abelx
☒ Invalid API data: matrix/abelx: matrix_pins.cols.0: 'DEF_PIN(TCA6424_PORT2' is not valid under any of the given schemas
```
Easier than fixing the parsing of the DEF_PIN macro, and updating the schema.
=> Avoid MATRIX_*_PINS due to schema validation errors

keyboards/matrix/abelx/chconf.h, keyboards/matrix/abelx/halconf.h
=> matrix/abelx - Fix "obsolete or unknown configuration file"

docs/mod_tap.md
The original code logic will result with the tap key registered on key up. This change simplifies the `if` statement to avoid that condition.
=> Correct logic of tap hold sample code

docs/_langs.md
=> Fix hebrew emoji in langs.md

quantum/pointing_device.c
Add missing+needed include, whoops. 
* Tzarc CI
=> Add needed include to pointing_device.c

.github/workflows/format_push.yaml
Will update to include the `-a` for python within #15156.
=> Auto-create PRs for merged formatting issues

.github/workflows/format.yaml, .github/workflows/format_push.yaml, lib/python/qmk/cli/format/python.py, lib/python/qmk/tests/test_cli_commands.py
Broken out from 11910.
More alignment of functionality between existing formatting commands.
=> Add diff logic to python format subcommand

lib/python/qmk/cli/list/keymaps.py, lib/python/qmk/cli/list/layouts.py
If the CLI cannot infer the keyboard name (these commands have `@automagic_keyboard`) or it is not passed with `-kb`, show an error message.
* Fixes #15203
=> [CLI] `list-keymaps`/`list-layouts`: Check keyboard passed in

keyboards/mokey/xox70/keymaps/via/keymap.c
LAYOUT_all doesn't exist... use LAYOUT instead.
=> [Keyboard] Fix xox70 via layout

.github/workflows/format.yaml
Update the format job output to better highlight errors, fixes extra `::` in message
=> Tidy CI format error message

keyboards/viktus/sp_mini/keymaps/via/rules.mk
=> [Keyboard] Enable LTO on viktus/sp_mini via keymap

docs/feature_combo.md
`layer_combo` was never defined in the code example. What the author meant is the `sd_combo`.
*
=> [DOCS] layer_combo → sd_combo

lib/python/qmk/cli/format/python.py
Incorrectly formatting .json files, not 100% sure how the behaviour was introduced.
=> qmk format-python - filter for Python files

.github/workflows/format.yaml
```
Run cat ~/files_added.txt ~/files_modified.txt > ~/files_changed.txt
Ψ Successfully formatted the C code.
☒ No Python files in filelist: /__w/qmk_firmware/qmk_firmware/tests/auto_shift/config.h, /__w/qmk_firmware/qmk_firmware/tests/auto_shift/test.mk,
...
/__w/qmk_firmware/qmk_firmware/tests/test_common/test_fixture.hpp
Error: Process completed with exit code 1.
```
=> [CI] Ignore exit codes for formatters

keyboards/xbows/nature/config.h
40 bytes over => 932 bytes free.
=> More headroom.

keyboards/ploopyco/trackball_mini/readme.md, keyboards/ploopyco/trackball_nano/readme.md
Noticed this when looking over the other ploopy PR. 
*
=> [Develop] Fix ploopy readme typos

docs/breaking_changes.md
Minor fix of the date of the last merge in the documentation.
*
=> Fix last merge date

users/stanrc85/config.h
Enabling the RGB matrix animations I have in my userspace/keymap 
*
=> [Userspace] Enable RGB Matrix animations being used in keymap

keyboards/lyra/lyra.c, keyboards/plut0nium/0x3e/keymaps/default/keymap.c, keyboards/plut0nium/0x3e/rules.mk, keyboards/pteron36/keymaps/via/keymap.c, keyboards/pteron36/pteron36.c, keyboards/pteron36/rules.mk
Seems to have slipped through.
=> Fix keyboard level use of OLED_DRIVER_ENABLE

keyboards/macro3/config.h, keyboards/macro3/keymaps/default/keymap.c, keyboards/macro3/macro3.c, keyboards/macro3/macro3.h, keyboards/macro3/post_config.h, keyboards/macro3/readme.md
* Use simpler SPDX license
* Allow user `config.h` to overwrite bootmagic and encoder resolution
* More media centric encoder and keymap defaults
* Update readme content
=> Minor Macro3 code changes

keyboards/ferris/sweep/readme.md, keyboards/ferris/sweep/sweep.c
* Add `config.h` override instructions to correct a PCB variant with swapped pins.
* Add swap hands feature.
* Update handedness information
=> Sweep swap hand feature and pin documentation

keyboards/boardsource/technik_o/rules.mk, keyboards/boardsource/technik_s/rules.mk
=> Add mousekey support for Technik variants

keyboards/dtisaac/dosa40rgb/keymaps/default/keymap.c
Add define GPIO B5 (pre_init = LOW) into Dosa40RGB
*
=> Add define GPIO into Dosa40RGB

docs/feature_swap_hands.md
Add documentation for `SH_TT` feature and `TAPPING_TOGGLE`
=> Document swap-hands tap-toggle feature

keyboards/a_dux/a_dux.c, keyboards/a_dux/readme.md
* Add swap hands support
* Update handedness information
=> Add swap hands support and readme updates for Architeuthis Dux

keyboards/ploopyco/mouse/readme.md
Minor typo and broken link fix
Minor typo and broken link fix
* Minor typo and broken link
=> [Keyboard] Fix typos in readme for PloopyCo Mouse

keyboards/ploopyco/mouse/mouse.c, keyboards/ploopyco/mouse/mouse.h, keyboards/ploopyco/mouse/rules.mk, keyboards/ploopyco/trackball/rules.mk, keyboards/ploopyco/trackball/trackball.c, keyboards/ploopyco/trackball/trackball.h, keyboards/ploopyco/trackball_mini/rules.mk, keyboards/ploopyco/trackball_mini/trackball_mini.c, keyboards/ploopyco/trackball_mini/trackball_mini.h
Converts the scroll wheel behavior to use encoder callbacks, which adds additional control over the behavior.
=> [Keyboard] Ploopy improvements

keyboards/xelus/kangaroo/keymaps/default/config.h, keyboards/xelus/kangaroo/keymaps/via/config.h
Increase pollrate to 1kHz
* Increase pollrate to 1kHz
=> [Keyboard] Kangaroo improvements

keyboards/ploopyco/trackball/trackball.h
Forgot to remove prototype, when overhauling.
* Tzarc CI
=> [Keyboard] Fix compilation issues for Ploopy Trackball classic

docs/keycodes.md, docs/keycodes_magic.md, quantum/process_keycode/process_magic.c, quantum/quantum_keycodes.h
Slightly nicer to only have to use a single key to swap/unswap. Known position within keymap, rather than `a or b depending on what mode you currently have`
=> Implement MAGIC_TOGGLE_CONTROL_CAPSLOCK

quantum/quantum.h
=> Add missing define for unicode common

tmk_core/protocol/vusb/vusb.c
=> Remove Deprecated USB Polling comment from vusb.c

keyboards/ploopyco/trackball_mini/readme.md
Minor typo and broken link fix
* Minor typo and broken link
=> [Keyboard] Fix minor typo in Ploopy Trackball Mini Docs 

keyboards/ploopyco/trackball/readme.md
Minor typo fix
Minor typo fix
* Minor typo
=> [Keyboard] Fix minor typo in Ploopy Trackball Docs 

docs/cli_commands.md, lib/python/qmk/cli/pytest.py
Allows the following, 
```python
qmk pytest -t qmk.tests.test_cli_commands
qmk pytest -t qmk.tests.test_cli_commands.test_c2json
qmk pytest -t qmk.tests.test_qmk_path
```
=> Add test filter to 'qmk pytest'

docs/_langs.md
As titled. I might create a Traditional Chinese translation in the far far future, here's preparing for it. 
*
=> Change "Chinese" to "Simplified Chinese" in langs.md

keyboards/xelus/pachi/rgb/rev1/config.h, keyboards/xelus/pachi/rgb/rev2/config.h
Add 1 to the Product ID for Rev2 due to the different "duplexed" matrix state to add a second version to VIA.
* Product ID change Pachi RGB Rev2
=> [Keyboard] Pachi RGB update

keyboards/spacey/config.h, keyboards/spacey/keymaps/via/keymap.c, keyboards/spacey/keymaps/via/rules.mk
adding via support for spacey
*
=> adding via support for spacey

docs/feature_bluetooth.md
Updated the text from nRF5182 to nRF51822 to avoid confusion about which part is needed. Especially when there are no results for "nRF5182"
=> Updated typo on feature_bluetooth.md

keyboards/handwired/jot50/keymaps/default/keymap.c
=> [Keyboard] Fix compilation issues with jot50

keyboards/boardsource/technik_o/technik_o.c
=> Add swap hands support for Technik_O

keyboards/ferris/sweep/readme.md
As titled.
New user confusion on discord
=> Add Elite-C DFU bootloader commands for Sweep

keyboards/40percentclub/ut47/ut47.c
=> Fix build failure for UT47

keyboards/jorne/jorne.h
quick followup to https://github.com/qmk/qmk_firmware/pull/15461, removes extra layout from jorne.h
=> removed extra layout from jorne.h

keyboards/macro3/config.h
Remove default to save firmware space because PCB has no support.
=> Remove locking support for Macro3

keyboards/cradio/config.h
Remove default to save firmware space because PCB has no support.
=> Remove locking support from Cradio

keyboards/nasu/nasu.h, keyboards/nasu/rules.mk
Small addition to Nasu PCB to support full backspace layout/keymaps as well. 
@yiancar Let me know if this is alright with you, thanks.
*
=> Add LAYOUT_alice support for Nasu

keyboards/crkbd/keymaps/soundmonster/keymap.c
Fixed compilation caused by missing boolean on return
*
=> [CRKBD/SOUNDMONSTER] Fixed compilation (forgot return)

keyboards/crazy_keyboard_68/config.h
Corrected Caps Lock LED pin from B2 to B0 (finally had a chance to test it physically, was hard to source the led itself)
*  The caps lock led now lights up as expected when caps lock is activated
=> Fixed caps lock led pin for crazy_keyboard_68

keyboards/pearlboards/pandora/pandora.c, keyboards/pearlboards/zeus/zeus.c, keyboards/pearlboards/zeuspad/zeuspad.c
Fix compilation issues, and callbacks
* Tzarc CI
=> [Keyboard] Fix compilation issues for Pearlboards

keyboards/keychron/q1/rev_0102/keymaps/kubahorak/README.md, keyboards/keychron/q1/rev_0102/keymaps/kubahorak/config.h, keyboards/keychron/q1/rev_0102/keymaps/kubahorak/keymap.c, keyboards/keychron/q1/rev_0102/keymaps/kubahorak/keymap_user.h, keyboards/keychron/q1/rev_0102/keymaps/kubahorak/rgb_matrix_user.c, keyboards/keychron/q1/rev_0102/keymaps/kubahorak/rgb_matrix_user.h, keyboards/keychron/q1/rev_0102/keymaps/kubahorak/rules.mk
* Custom keymap for the Keychron Q1 with the ISO layout (rev_0100) inspired by #14666.
=> [Keymap] Add keymap for the Keychron Q1 ISO layout

docs/feature_combo.md
=> Link Macro example for COMBO_ACTION documentation

docs/feature_rgb_matrix.md
Add another RGB matrix indicator code example that will light up configured keys on each layer.
=> RGB Matrix layer key indicator

keyboards/pistachio_pro/keymaps/via/keymap.c
The same action as #14599 will be taken for pistachio_pro.
*
=> Enable encoder settings VIA.

keyboards/evyd13/atom47/rev2/config.h, keyboards/evyd13/atom47/rev2/rules.mk, keyboards/evyd13/atom47/rev3/config.h, keyboards/evyd13/atom47/rev3/rules.mk, keyboards/evyd13/atom47/rev4/config.h
Specifies the pin on states for earlier revisions (caused inverted led behaviour) and enable backlight in rules.mk which is not working at the moment due to it not being enabled.
*
=> Atom47 led fix

platforms/avr/drivers/serial.c
More fixes related to #15282 and #15589.
=> More AVR GPIO compilation fixes.

keyboards/centromere/matrix.c, keyboards/centromere/rules.mk, keyboards/chimera_ergo/matrix.c, keyboards/chimera_ergo/rules.mk, keyboards/chimera_ls/matrix.c, keyboards/chimera_ls/rules.mk, keyboards/chimera_ortho/matrix.c, keyboards/chimera_ortho/rules.mk, keyboards/chimera_ortho_plus/matrix.c, keyboards/chimera_ortho_plus/rules.mk, keyboards/comet46/matrix.c, keyboards/comet46/rules.mk, keyboards/mitosis/matrix.c, keyboards/mitosis/rules.mk, keyboards/redox_w/matrix.c, keyboards/redox_w/rules.mk, keyboards/sirius/uni660/rev1/matrix.c, keyboards/sirius/uni660/rev1/rules.mk, keyboards/sirius/uni660/rev2/matrix.c, keyboards/sirius/uni660/rev2/rules.mk
Based on the Telophase cleanup I did a while back (#13225). Followup to #15479. Dichotomy and Honeycomb are still to do, as their implementations have pointing device stuff that is also sent over the serial link.
*
=> Convert some more boards to Matrix Lite

docs/feature_encoders.md
=> Add layer condition example to encoder callback function

quantum/matrix_common.c, quantum/split_common/split_util.h
Fix issue with print on ARM, as well as re-add mem functions for matrix syncing. 
* Tzarc CI.
=> [Core] Fix bug and code regression for Split Common

quantum/matrix_common.c
=> [Bug] Include missing string.h include in split

keyboards/sendyyeah/pix/keymaps/default/keymap.c, keyboards/sendyyeah/pix/keymaps/via/keymap.c
=> [Keyboard] Fix sendyyeah/pix oled task function type

docs/feature_rgb_matrix.md
Clarify the location and intended usage of `rgb_matrix_user.inc` and `rgb_matrix_kb.inc` files. The original description was misinterpreted as needing both.
=> Clarify placement and usage of RGB matrix effect inc files

drivers/sensors/analog_joystick.c
Switch to pin_t so can be used with ARM, this came up when someone in discord was trying to use the feature with a blackpill.
*
=> Fix analog joystick to mouse compilation.

docs/feature_macros.md
Add a footnote to indicate that `enum` of custom keycodes must be declared before code that uses them.
=> [Docs] Note the order of enumerated custom keycodes

lib/python/qmk/cli/format/c.py
Seems a case was missed, and CI raised #15726. The issue, expecting to modify a list while enumerating... 
*
=> Refix "No C files in filelist: None"

keyboards/boardsource/beiwagon/config.h, keyboards/boardsource/technik_o/config.h, keyboards/boardsource/technik_s/config.h
Remove default locking support code on Boardsource's choc LP boards to save some firmware space.
=> [Keyboard] Remove locking support for Boardsource LP boards

docs/feature_pointing_device.md
=> [Docs] Add drag scrolling example to Pointing device docs page

keyboards/mechbrewery/mb65s/info.json, keyboards/mechbrewery/mb65s/keymaps/default/keymap.c, keyboards/mechbrewery/mb65s/keymaps/iso/keymap.c, keyboards/mechbrewery/mb65s/keymaps/split_bs/keymap.c, keyboards/mechbrewery/mb65s/mb65s.h
- Update keymap for MechBrewery MB-65S
- Change name of layout "LAYOUT_65_ansi_blocker_split_bs" to layout "LAYOUT_all", follows request from OEM.
None
=> Update keymap for MechBrewery MB65S

keyboards/crkbd/keymaps/soundmonster/config.h, keyboards/crkbd/keymaps/soundmonster/keymap.c, keyboards/crkbd/keymaps/soundmonster/rules.mk
Upgrade personal keymap to use split common and fix long-standing issue with OLED display.
* n/a
=> Migrate crkbd/soundmonster to split common, fix OLED and RGB matrix

platforms/chibios/eeprom_teensy.c
This reverts commit 7f8faa429e0c0662cec34a7d60e33ca58333d6d7.
related to https://github.com/qmk/qmk_firmware/issues/15521
Multiple people have reported issues with the Teensy 3.6 after our EEPROM changes made it in the most recent breakpoint, see https://github.com/qmk/qmk_firmware/issues/15521
For now, we should revert the changes.
This PR is against the develop branch — can you cherry-pick the revert into master afterwards, or what’s the process? :)
* https://github.com/qmk/qmk_firmware/issues/15521
=> Revert "core: make the full 4096 bytes of EEPROM work on Teensy 3.6 (#12947)

docs/feature_rgblight.md
Questions on using `RGB_*` keycodes with code comes up often on Discord. This change adds a note to recommend using direct RGB light functions if users need to control RGB feature with code.
=> [Docs] Recommend the use of RGB light functions for code

docs/feature_rgb_matrix.md
Questions on using `RGB_*` keycodes with code comes up often on Discord. This change adds a note to recommend using direct RGB matrix functions if users need to control RGB feature with code.
=> [Docs] Recommend the use of RGB matrix functions for code

keyboards/handwired/dygma/raise/rules.mk
Needs a default folder specified. 
* Tzarc CI
=> [Keyboard] Fix compilation issues for Dygma Raise

keyboards/orthocode/config.h, keyboards/orthocode/keymaps/default/keymap.c, keyboards/orthocode/keymaps/via/keymap.c, keyboards/orthocode/keymaps/via/rules.mk, keyboards/orthocode/orthocode.c, keyboards/orthocode/orthocode.h, keyboards/orthocode/rules.mk
Adding the via keymap and rules.mk to enable via support for Orthocode
*
=> Added via support for orthocode

keyboards/wuque/mammoth20x/config.h, keyboards/wuque/mammoth20x/keymaps/via/keymap.c, keyboards/wuque/mammoth75x/config.h
Fixed the ENCODER_RESOLUTION and wrong encode keyvalue problem in Mammoth20x and Mammoth75x
https://github.com/qmk/qmk_firmware/pull/14014
https://github.com/qmk/qmk_firmware/pull/14925
=> Fixed bugs Wuque Mammoth Keyboard Series

keyboards/atreus/keymaps/dvorak_42_key/keymap.c, keyboards/ergodox_ez/keymaps/dvorak_42_key/keymap.c
Layout change for Ergodox EZ and Atreus "Dvorak 42 key" layouts.
*
=> [Keyboard][Keymap] dvorak 42 key layouts (Ergodox EZ / Atreus) updates

docs/newbs_flashing.md
Add a link to the build environment section
- [x ] Documentation
* 
=> newbs_flashing.md: add link to build environment section

keyboards/massdrop/ctrl/keymaps/R167/keymap.c, keyboards/massdrop/ctrl/keymaps/R167/readme.md
As per [getting started guide](https://docs.qmk.fm/#/newbs_building_firmware), add my keymap under `massdrop/ctrl`
Add `massdrop/ctrl:R167` keymap
* n/a
=> [keymap] Add massdrop/ctrl R167 keymap

docs/squeezing_avr.md
=> fix typo and remove trailing whitespace

docs/feature_split_keyboard.md
* Add title for all 3 bootloader targets
* Document QMK toolbox support
=> [Docs] Improve Handedness by EEPROM documentation

keyboards/mechlovin/hex4b/readme.md, keyboards/mechlovin/hex4b/rev1/config.h, keyboards/mechlovin/hex4b/rev1/readme.md, keyboards/mechlovin/hex4b/rev1/rules.mk, keyboards/mechlovin/hex4b/rev2/chconf.h, keyboards/mechlovin/hex4b/rev2/config.h, keyboards/mechlovin/hex4b/rev2/halconf.h, keyboards/mechlovin/hex4b/rev2/mcuconf.h, keyboards/mechlovin/hex4b/rev2/readme.md, keyboards/mechlovin/hex4b/rev2/rules.mk
Add Hex 4B rev.2 PCB, APM32F103.
Thank you.
*
=> Add Hex4B rev.2 PCB

docs/newbs_building_firmware.md, docs/newbs_getting_started.md
The [newbs build environment guide](https://docs.qmk.fm/#/newbs_getting_started?id=_5-configure-your-build-environment-optional) will create occasional confusion because `qmk compile` will fail before an actual keymap is setup. This change moves that guide into the next section, _after_ a keymap is properly created.
=> [Docs] Move QMK newbs build environment guide to next section

keyboards/mlego/m48/keymaps/default/keymap.c, keyboards/mlego/m48/keymaps/via/keymap.c, keyboards/mlego/m48/m48.h
=> move enum_layers in keymaps, in sync with the other mlego/m*

keyboards/mokey/xox70hot/keymaps/via/keymap.c
=> [Keyboard] Fix xox70hot via layout

util/qmk_install.sh
The Toolbox can now read files from the WSL UNC path (`\\wsl$\<instance>`). Also avoids the silly escaping here (which I think doesn't work anyway).
*
=> Remove network drive mapping comment for WSL

docs/keycodes.md
=> Make note of upper limit for `UC()`

keyboards/gray_studio/space65/keymaps/conor/config.h, keyboards/gray_studio/space65/keymaps/conor/keymap.c, keyboards/gray_studio/space65/keymaps/conor/rules.mk
Added the "conor" keymap which enables rgb layers support to display the current layer on the side LEDs and caps on the badge LEDs
=> added keymap conor with rgb layers

data/mappings/keyboard_aliases.json
=> Update keyboard_aliases.json for KPrepublic, cleaning up after #15047

keyboards/ymdk/yd60mq/rules.mk
=> Yet another bad `DEFAULT_FOLDER` fix.

docs/compatible_microcontrollers.md
If there are any other notable boards missing, feel free to suggest.
*
=> Add example implementations for compatible MCUs list

keyboards/readme.md
A futile endeavour if I've ever seen one.
*
=> Remove community-supported keyboards list from readme

docs/feature_rgblight.md
=> docs: fix typo in rgblight docs

keyboards/wolf/ts60/keymaps/default/keymap.c, keyboards/wolf/ts60/keymaps/via/keymap.c
Small correction to the keymap for the TS60
- [ x I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> Update keymap on the TS60

docs/feature_led_matrix.md
=> docs: fix typo in led matrix docs

docs/newbs_learn_more_resources.md
It is also a good IDE with git integration
=> Add Atom editor suggestion

quantum/color.h
Changed to orange declaration to match the [documentation](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_rgblight.md) value, which I confirmed appears more orange,
- [x ] Bugfix
* 
=> fixed typo in orange HSV colors decalartion

keyboards/rocketboard_16/keycode_lookup.h
Forgot to test this board...
#15993 
*
=> `rocketboard_16`: Fix mismatched LUT sizes

keyboards/converter/usb_usb/custom_matrix.cpp, keyboards/sirius/unigo66/custom_matrix.cpp, quantum/keyboard.c, quantum/keyboard.h, quantum/led.c, quantum/led.h, quantum/quantum.c, quantum/quantum.h
* Almost all host LED code now in one location
* Remove `keyboard_set_leds` as it was mostly irrelevant to the new location
* Minor tidy up
=> Align location of some host led logic

docs/pr_checklist.md
Adds a bit more clarity in the sense that we don't want new board definitions embedded in a new keyboard PR.
=> PR Checklist: new board definitions

quantum/process_keycode/process_joystick.c
I got myself a cheap joystick module and ran into this when playing around with it, which @broekema previously reported.
* Fixes #15573
=> Fix joystick button off-by-one error

keyboards/creatkeebs/thera/thera.h
Issues with layout macro. 
* Tzarc CI
=> [Keyboard] Fix compilation issues for creatkeebs thera

docs/feature_oled_driver.md
* Add section on `glcdfont.c` file location
* Clarify the timeout description
* #15952
=> [Docs] OLED documentation edits

keyboards/nasu/config.h, keyboards/nasu/nasu.c
This PCB did not use open drain as I usually do.
Sorry for that.
Switched back to normal buffered I/O
*
=> Fix Nasu Indicators

keyboards/sandwich/keeb68/config.h, keyboards/sandwich/keeb68/keeb68.c, keyboards/sandwich/keeb68/keeb68.h, keyboards/sandwich/keeb68/keymaps/default/keymap.c, keyboards/sandwich/keeb68/keymaps/grv_esc/keymap.c, keyboards/sandwich/keeb68/keymaps/grv_esc/readme.md, keyboards/sandwich/keeb68/readme.md, keyboards/sandwich/keeb68/rules.mk
Added sandwich\keeb68 to origin's keyboards folder
Added my sandwich\keeb68 keyboard to master's keyboards folder
My keyboard gets added.
=> Added sandwich\keeb68 to keyboards

docs/zh-cn/other_eclipse.md, docs/zh-cn/other_vscode.md
IDE configuration parts: Eclipse and VSCode
following after PR #14924
* tracking issue: #15443
=> [Docs] zh-cn document translate: IDE configuration

keyboards/planck/planck.c, keyboards/preonic/preonic.c
At least they will then do something....?
*
=> Planck/Preonic - Enable default encoder behaviour on configurator

docs/zh-cn/hand_wire.md
* hand wire
following after PR #14924
* tracking issue: #15443
=> [Docs] zh-cn documentation translate: hand-wire

keyboards/cablecardesigns/cypher/rev6/keymaps/via/keymap.c
```
Compiling: keyboards/cablecardesigns/cypher/rev6/keymaps/via/keymap.c                              keyboards/cablecardesigns/cypher/rev6/keymaps/via/keymap.c: In function ‘layer_state_set_user’:
keyboards/cablecardesigns/cypher/rev6/keymaps/via/keymap.c:37:56: error: ‘_F1’ undeclared (first use in this function)                                                                            
rgblight_set_layer_state(2, layer_state_cmp(state, _F1));
```
*
=> Fix Cypher rev6 VIA keymap

keyboards/ferris/keymaps/via/keymap.c, keyboards/ferris/keymaps/via/rules.mk
*  Added VIA Keymap for Ferris Sweep. This is basically just a conversion of the madhatter keymapping. No code changes were made except those minimally required to enable VIA.
=> added via keymap for ferris sweep

keyboards/charue/sunsetter/keymaps/peott-fr/keymap.c
=> Adding Sunsetter keymap.

keyboards/gmmk/pro/ansi/keymaps/gigahawk/config.h, keyboards/gmmk/pro/ansi/keymaps/gigahawk/keymap.c
Add Gigahawk's keymap for GMMK Pro
*
=> [Keymap]: Create Gigahawk GMMK Pro keymap

keyboards/25keys/aleth42/rules.mk, keyboards/maple_computing/ivy/rules.mk
Yet another round of broken `DEFAULT_FOLDER` moves.
=> Fix up default folder locations. Again.

keyboards/mikeneko65/rev3/config.h, keyboards/mikeneko65/rev3/keymaps/default/keymap.c, keyboards/mikeneko65/rev3/keymaps/via/keymap.c, keyboards/mikeneko65/rev3/rev3.c, keyboards/mikeneko65/rev3/rev3.h, keyboards/mikeneko65/rev4/config.h, keyboards/mikeneko65/rev4/keymaps/default/keymap.c, keyboards/mikeneko65/rev4/keymaps/via/keymap.c, keyboards/mikeneko65/rev4/rev4.c, keyboards/mikeneko65/rev4/rev4.h
Fix a bug in pin assignment.
Add original copyright notice.
Assign the tilde key to layer 1.
Remove extra whitespaces at the end of lines.
*
=> Fixed a bug in pin assignment and some updates on mikeneko65

keyboards/cradio/config.h, keyboards/cradio/readme.md
* Use master left as default handedness
* Readme file typo correction
=> Simplify handedness

keyboards/ferris/sweep/readme.md
Remove the extra word in readme.
=> Typo correction

keyboards/crkbd/readme.md
Correcting typo and wording in Crkbd ReadMe around the RGB Matrix
functionality.
Corrected a small typo and updated the wording describing the RGB Matrix feature in the Crkbd ReadMe.
If you want anything changed then let me know, and thank you for the wonderful keyboard that this software lets me customise to my liking!
*
=> ReadMe corrections

.gitignore
Removed old irrelevant `.gitignore` entry, added other macOS junk files.
=> Remove old .gitignore entry. Add more macOS junk exclusions.

keyboards/gmmk/pro/ansi/keymaps/andrebrait/keymap.c, keyboards/gmmk/pro/ansi/keymaps/andrebrait/readme.md, keyboards/gmmk/pro/ansi/keymaps/andrebrait/rules.mk
Just added a layer dedicated to macOS, remapped a few keys.
*
=> Add MacOS layer

platforms/chibios/eeprom_teensy.h
=> Fixup builds so that teensy EEPROM knows which MCU it's targeting.

keyboards/handwired/aball/config.h
Add in define for inverting pointing device X axis as part of switch to standard ADSN/Pointing device libs as the sensor is 'upside-down' in the aball design.
=> Fix axis inversion using new libraries

docs/custom_quantum_functions.md
Docs were lacking, wasn't obvious that a rules.mk entry was required for deferred execution.
=> Point out that deferred execution needs to be enabled in rules.mk

docs/feature_macros.md
This PR is generated while making zh-cn translating: #16201
* not applicable
=> [Docs] feature_macro.md: minor formatting fix

keyboards/marksard/rhymestone/keymaps/default/config.h
=> Fix OLED font path in default Rhymestone keymap

tmk_core/protocol.mk, tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/chibios/usb_main.c
This adds support for HID Programmable Buttons for ChibiOS devices.
* #15596
=> ChibiOS: add support for HID Programmable Buttons

keyboards/gmmk/pro/ansi/keymaps/lalitmaganti/config.h, keyboards/gmmk/pro/ansi/keymaps/lalitmaganti/keymap.c, keyboards/gmmk/pro/ansi/keymaps/lalitmaganti/rules.mk
Add LalitMaganti GMMK Pro Keymap
*
=> [Keymap]: add LalitMaganti GMMK Pro Keymap

.gitignore
=> Add version.h to gitignore

keyboards/ez_maker/directpins/teensy_32/info.json, keyboards/ez_maker/directpins/teensy_lc/info.json, keyboards/handwired/twadlee/tp69/rules.mk, keyboards/keychron/q2/rev_0110/rules.mk, keyboards/keychron/q2/rev_0111/rules.mk, keyboards/keychron/q2/rev_0112/rules.mk, keyboards/keychron/q2/rev_0113/rules.mk
These are the CI failures that can be easily fixed. The others all use various custom bootloaders and may need some extra work - API complains that `custom` is not one of the valid values from jsonschema.
*
=> Add missing `BOOTLOADER` for a handful of boards

data/schemas/keyboard.jsonschema
=> Add `custom` to list of valid bootloader types in info.json

docs/feature_mouse_keys.md
There is a misused wording under "Combined Mode", it was copy-pasted from upper "Constant Mode".
related PR:(Translating) #16227
* not applicable
=> [Docs] feature: mouse keys, fix misused wording

docs/feature_rgb_matrix.md, docs/feature_rgblight.md
* Add line breaks between warning notes.
* Add note on layer state data sync
* Anchor link corrections
* Join floating sentence
Fix format bug introduced by #15744 and #15745
=> [Docs] RGB documentation formatting corrections

docs/api_docs.md, docs/cli_commands.md, docs/feature_tap_dance.md, docs/hardware_avr.md, docs/ja/cli_commands.md, docs/keycodes_us_ansi_shifted.md, docs/mod_tap.md, docs/other_eclipse.md, docs/other_vscode.md, docs/zh-cn/cli_commands.md, keyboards/moonlander/matrix.c, keyboards/moonlander/readme.md
While familiarizing myself with QMK, I found a duplicated word in the documentation and decided to fix that type of error. I also found what appears to be an older copy-paste error, where the wrong half was mentioned in the output of the moonlander code.
* None
=> [Docs] Address some typos (also in moonlander matrix.c)

data/schemas/keyboard.jsonschema, keyboards/xiudi/xd002/rules.mk
Could have gone either way, but given its used on a single board :shrug:
=> Remove half implemented micronucleus bootloader support

keyboards/ducky/one2mini/1861st/1861st.c, keyboards/ducky/one2mini/1861st/rules.mk, keyboards/ergodox_stm32/ergodox_stm32.c, keyboards/ergodox_stm32/rules.mk, keyboards/jm60/jm60.c, keyboards/jm60/rules.mk, keyboards/matrix/abelx/abelx.c, keyboards/matrix/abelx/rules.mk, keyboards/matrix/m12og/rev1/rev1.c, keyboards/matrix/m12og/rev1/rules.mk, keyboards/matrix/m20add/m20add.c, keyboards/matrix/m20add/rules.mk, keyboards/matrix/noah/noah.c, keyboards/matrix/noah/rules.mk, keyboards/wolfmarkclub/wm1/rules.mk, keyboards/wolfmarkclub/wm1/wm1.c, keyboards/xiaomi/mk02/rules.mk
Fixes CI errors about missing bootloader.
=> Fixup bootloaders.

keyboards/eternal_keypad/config.h, keyboards/eternal_keypad/keymaps/kyek/config.h, keyboards/eternal_keypad/keymaps/kyek/keymap.c, keyboards/eternal_keypad/keymaps/kyek/readme.md
I assigned pid `0xDB00` to my device, I checked and no other device should be using it currently.
Also added my own keymap.
* none
=> [eternal_keypad] Update product_id and add keymap

docs/pr_checklist.md
This PR comes from translating works.
related: #16262
* not applicable
=> [Docs] pr checklist: update doc hyperlinks to relative ones and use IDs

keyboards/1upkeyboards/super16v2/config.h, keyboards/1upkeyboards/super16v2/info.json, keyboards/1upkeyboards/super16v2/keymaps/default/keymap.c, keyboards/1upkeyboards/super16v2/keymaps/default/readme.md, keyboards/1upkeyboards/super16v2/keymaps/via/keymap.c, keyboards/1upkeyboards/super16v2/keymaps/via/readme.md, keyboards/1upkeyboards/super16v2/keymaps/via/rules.mk, keyboards/1upkeyboards/super16v2/readme.md, keyboards/1upkeyboards/super16v2/rules.mk, keyboards/1upkeyboards/super16v2/super16v2.c, keyboards/1upkeyboards/super16v2/super16v2.h
Add a new 1upkeyboards keyboard the super16v2
=> New Keyboard: 1upkeyboards super16v2

keyboards/idobao/id80/v3/config.h, keyboards/idobao/id80/v3/rules.mk
`RGB_DI_PIN` is redefined
`RGBLED_NUM` is redefined... looks to be unnecessarily defined anyway.
=> Fix idobao/id80/v3 compilation errors

keyboards/crkbd/keymaps/ardakilic/config.h, keyboards/crkbd/keymaps/ardakilic/keymap.c
Hello, 
This is further update to #13745 , somehow my commit did not get merged.
https://github.com/qmk/qmk_firmware/pull/13745#discussion_r802603490
*
=> Further update to #13745 on Crkbd keymap

users/zigotica/rows.h
=> zigotica keymap tweaks

docs/feature_led_indicators.md
Improve the pre-amble section of LED indicators documentation
=> Improve description of LED state data sync option

build_full_test.mk
This was bothering me slightly 😄
*
=> Fix slashes in build_full_test.mk

keyboards/handwired/promethium/promethium.h
```
Compiling: .build/obj_handwired_promethium_handwired_promethium_layout_mine/src/keymap.c           .build/obj_handwired_promethium_handwired_promethium_layout_mine/src/keymap.c:10:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'keymaps'
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
^~~~~~~
```
*
=> handwired/promethium: fix missing include

data/mappings/keyboard_aliases.json
Updates the json mapping for moved keyboards, as to not break existing configurator jsons.
=> Update keyboard mapping for all moved boards this cycle

platforms/chibios/drivers/uart.c
Cherry picked fix from 15724
* Fixes #15675
=> Fix compilation of ChibiOS UART driver

keyboards/handwired/aball/keymaps/default/keymap.c, keyboards/ploopyco/trackball_nano/keymaps/default/keymap.c, keyboards/ploopyco/trackball_nano/keymaps/maddie/keymap.c
#16350
```
handwired/aball:default
[...]
ploopyco/trackball_nano/rev1_001:default
```
Since it's a 3D array...
*
=> Add extra braces for trackball keymaps

keyboards/aya/config.h
Updates USB VID and PID as per https://pid.codes/1209/2925/.
=> Update USB VID and PID for Aya

data/templates/keyboard/info.json, docs/porting_your_keyboard_to_qmk.md
Looks like i missed #14580 when rebasing the new-keyboard command. Seems wise to avoid a deprecated field.
*
=> Align new-keyboard with recent schema updates

keyboards/evancookaudio/sleepingdinosaur/config.h, keyboards/evancookaudio/sleepingdinosaur/info.json, keyboards/evancookaudio/sleepingdinosaur/keymaps/default/keymap.c, keyboards/evancookaudio/sleepingdinosaur/readme.md, keyboards/evancookaudio/sleepingdinosaur/rules.mk, keyboards/evancookaudio/sleepingdinosaur/sleepingdinosaur.c, keyboards/evancookaudio/sleepingdinosaur/sleepingdinosaur.h
added 28 key macropad that is closest to the style of an ortho 5x6 macropad.
* 
i have compiled locally, successfully. i have also linted, locally, successfully.
=> [keyboard] added evancookaudio sleepingdinosaur

keyboards/dc01/left/config.h, keyboards/dc01/left/matrix.c
Small fix on dc01 with i2c detection using timeout:)
*
=> DC01 i2c timout fix

.github/workflows/format.yaml, .github/workflows/format_push.yaml
Workflow is silently spitting out....
```console
Run qmk format-c -a
Ψ Successfully formatted the C code.
<class 'FileNotFoundError'>
☒ [Errno 2] No such file or directory: 'yapf'
```
Aligned to how cli tests run (which as a test case also run a live format of the codebase using `qmk format-python`)
https://github.com/qmk/qmk_firmware/blob/e0342fec18e4b6b14a820d7a5d62954853c91756/.github/workflows/cli.yml#L25
=> [CI] Install extra CLI dependencies that are missing

keyboards/handwired/frankie_macropad/rules.mk
These don't really make sense for a macropad-sized board anyway.
*
=> handwired/frankie_macropad: disable some features to reduce size

.github/workflows/format.yaml, .github/workflows/format_push.yaml
Lets try that again... #16425
*
=> Install extra CLI dependencies that are missing

keyboards/handwired/lemonpad/config.h, keyboards/handwired/lemonpad/info.json, keyboards/handwired/lemonpad/keymaps/default/keymap.c, keyboards/handwired/lemonpad/keymaps/default/readme.md, keyboards/handwired/lemonpad/keymaps/via/config.h, keyboards/handwired/lemonpad/keymaps/via/keymap.c, keyboards/handwired/lemonpad/keymaps/via/readme.md, keyboards/handwired/lemonpad/keymaps/via/rules.mk, keyboards/handwired/lemonpad/lemonpad.c, keyboards/handwired/lemonpad/lemonpad.h, keyboards/handwired/lemonpad/readme.md, keyboards/handwired/lemonpad/rules.mk
QMK + Via support for a handwired Lemon-themed keypad, designed by Adafruit. Modified for a pro micro.
https://learn.adafruit.com/qtpy-lemon-mechanical-keypad-macropad
*
=> [Handwired] Support for Adafruit lemon keypad

docs/feature_rgb_matrix.md, docs/feature_rgblight.md
Adds a tip about changing from the ws2812 bitbang driver when using arm controllers.
=> Link WS2812 driver page from rgblight and rgb matrix feature page.

docs/feature_rgb_matrix.md
Minor correction the RGB matrix doc anchor link
=> Anchor link correction

lib/python/qmk/info.py
The culprit of the recent spamming of ` MANUFACTURER in config.h is overwriting manufacturer in info.json`
*
=> Revert CLI default for manufacturer

keyboards/gizmo_engineering/gk6/info.json
Currently producing:
```
☒ gizmo_engineering/gk6: Invalid matrix config.
```
Causes <https://github.com/qmk/qmk_firmware/blob/master/lib/python/qmk/info.py#L406> to fail to find `config.h` files. If absent, it is calculated at build time.
*
=> Remove invalid keyboard_folder from gk6

keyboards/helix/rev2/local_features.mk, keyboards/helix/rev2/override_helix_options.mk
```diff
--- a/keyboards/helix/rev2/local_features.mk
+++ b/keyboards/helix/rev2/local_features.mk
@@ -6,7 +6,7 @@
#
KEYBOARD_LOCAL_FEATURES_MK :=
--include $(strip $(HELIX_TOP_DIR)/pico/override_helix_options.mk) ## File dedicated to maintenance
+-include $(strip $(HELIX_TOP_DIR)/rev2/override_helix_options.mk) ## File dedicated to maintenance
```
=> Fix mistakes in the include path in `helix/rev2/local_features.mk`.

tmk_core/protocol/arm_atsam/i2c_master.c, tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/arm_atsam/md_rgb_matrix.c
#15953 changed the behaviour of a few core API. With the `arm_atsam` code implementing its own main logic, this has introduced #16489.
This PR fixes the use of ISSI driver config before init,
* `matrix_init` called twice - the first time way too early compared to other platforms
* `issidrv` used before structure configured
Given how the RIOT port has progressed, I didnt see it worth investing a ton of time on the fix.
* Fixes #16489
=> Fix Drop ALT/CTRL startup issues

docs/squeezing_avr.md
Fixed typo in squeezing_avr docs.
*
=> Typo in squeezing_avr.md

drivers/sensors/analog_joystick.c, platforms/avr/drivers/analog.c, platforms/avr/drivers/analog.h, platforms/chibios/drivers/analog.c, platforms/chibios/drivers/analog.h
Most things do not need to include the entirety of quantum.h and everything it pulls in.
* Fixes #16416
=> analog.[ch]: remove unnecessary includes

.github/ISSUE_TEMPLATE/bug_report.md
Since #16155 `qmk doctor` now provides all of this information (and more). It should be useful to have users simply paste the output instead of having to run a handful of commands.
*
=> Bug report template: require `qmk doctor` output

keyboards/neson_design/n6/config.h, keyboards/neson_design/n6/keymaps/via/keymap.c, keyboards/neson_design/n6/n6.c
=> Update the N6 keyboard

keyboards/keebio/fourier/keymaps/via/keymap.c, keyboards/keebio/fourier/keymaps/via/rules.mk
Add VIA Keymap for Fourier Keyboard
Copied the default firmware for the Fourier and added VIA support
*
=> created fourier via keymap

keyboards/handwired/wakizashi40/info.json, keyboards/handwired/wakizashi40/readme.md
Updated pin mapping for pro micro and teensy2.0 rather than teensy2pp. Changed location of models due to deteriorating Thingiverse condition.
*
=> Updated pin mapping and readme.

keyboards/atlantis/ak81_ve/ak81_ve.c, keyboards/atlantis/ak81_ve/ak81_ve.h, keyboards/atlantis/ak81_ve/config.h
Atlantis ak81_ve encoder behaviour enhancement & fixes.
LED matrix flag fixes & cleanup.
*
=> Atlantis ak81_ve encoder behaviour enhancement & fixes

keyboards/salicylic_acid3/naked48/keymaps/via_rgb_matrix/config.h, keyboards/salicylic_acid3/naked48/rev1/config.h
Change the maximum LED brightness of Naked48
*
=> Change maximum LED brightness

docs/reference_info_json.md
=> Fix in-page links in reference_info_json.md

keyboards/kb58/config.h, keyboards/kb58/info.json, keyboards/kb58/kb58.c, keyboards/kb58/kb58.h, keyboards/kb58/keymaps/default/keymap.c, keyboards/kb58/readme.md, keyboards/kb58/rules.mk
=> add new keyboard "KB58"

keyboards/macro3/config.h, keyboards/macro3/keymaps/default/keymap.c, keyboards/macro3/macro3.c, keyboards/macro3/readme.md
* Use tap code delay for volume control
* Add maintainer information
=> [Keyboard] Update encoder code

keyboards/keebio/bigswitchseat/bigswitchseat.c, keyboards/keebio/bigswitchseat/bigswitchseat.h, keyboards/keebio/bigswitchseat/config.h, keyboards/keebio/bigswitchseat/info.json, keyboards/keebio/bigswitchseat/keymaps/default/keymap.c, keyboards/keebio/bigswitchseat/keymaps/default/rules.mk, keyboards/keebio/bigswitchseat/keymaps/via/keymap.c, keyboards/keebio/bigswitchseat/keymaps/via/rules.mk, keyboards/keebio/bigswitchseat/readme.md, keyboards/keebio/bigswitchseat/rules.mk
Add Big Switch Seat keyboard
*
=> Add Big Switch Seat

keyboards/horrortroll/handwired_k552/rules.mk, keyboards/tkc/portico68v2/config.h, quantum/action.c
Fixes up builds on `develop` branch.
=> Fixup builds.

keyboards/gboards/gergoplex/keymaps/tgrosinger/combos.def, keyboards/gboards/gergoplex/keymaps/tgrosinger/gergoplex.def, keyboards/gboards/gergoplex/keymaps/tgrosinger/keymap.c, keyboards/gboards/gergoplex/keymaps/tgrosinger/readme.md, keyboards/gboards/gergoplex/keymaps/tgrosinger/rules.mk
Adding a new keymap to the gboards/gergoplex keyboard.
=> Add Gergoplex keymap for tgrosinger

keyboards/acheron/elongate/delta/info.json
Fixes:
cc @Gondolindrim (keyboard maintainer)
=> Acheron Elongate Delta: add info.json

platforms/pin_defs.h
Something odd off the back of #16611.
Hopefully this should ensure a consistent include order.
=> Workaround for pin_def errors on KINETIS based builds

keyboards/p3d/glitch/glitch.c
=> Missing endif in p3d/glitch

keyboards/40percentclub/nein/info.json, keyboards/40percentclub/nori/info.json, keyboards/40percentclub/ut47/info.json
#16481 had a couple minor error. This fixes them.
=> Fix 40percentclub USB descriptors

quantum/mousekey.c
#16543 forgot to include `string.h` as it's required for `memcpy` oops
=> Mousekeys fix

keyboards/bolsa/damapad/damapad.h
cc @matthewdias 
* <https://yanfali.github.io/qmk_error_page/> errors
=> bolsa/damapad - Fix missing layout macro

keyboards/keebio/iris/rev3/rev3.c, keyboards/keebio/iris/rev4/rev4.c, keyboards/keebio/iris/rev5/rev5.c, keyboards/keebio/iris/rev6/rev6.c
Handles the case where users set `ENCODER_ENABLE = no`.
*
=> keebio/iris: Add ifdefs to encoder callbacks

docs/feature_bootmagic.md
=> Sentence correction

keyboards/evancookaudio/sleepingdinosaur/config.h, keyboards/evancookaudio/sleepingdinosaur/keymaps/via/keymap.c
VIA keymap was missing some commas and whatnot.
=> Fix evancookaudio/sleepingdinosaur

.github/workflows/develop_update.yml, .github/workflows/feature_branch_update.yml
Making a single generic workflow was proving to be a total pain. This will do for the short term.
*
=> Add merge workflow for XAP branch

keyboards/matthewdias/m3n3van/keymaps/default/keymap.json, keyboards/matthewdias/minim/keymaps/default/keymap.json
qmk_error_page getting confused by this.
*
=> Fix m3n3van and minim keyboard names in keymap JSON

builddefs/build_keyboard.mk, builddefs/message.mk
=> Print out generated files during build

lib/python/qmk/cli/doctor/check.py, lib/python/qmk/cli/doctor/main.py, lib/python/qmk/cli/generate/version_h.py, lib/python/qmk/cli/new/keyboard.py, lib/python/qmk/commands.py, lib/python/qmk/git.py
`commands.py` becoming a bit of a dumping ground, so this PR aims to:
* Break out some common git functionality
* Slight alignment of function names/order
* Removed unused check_git_repo
* Remove git_get_version "return this on error" argument
=> Relocate CLI git interactions

users/stanrc85/config.h, users/stanrc85/rules.mk, users/stanrc85/stanrc85.c
Small userspace updates:
* Define "Indicator Pins" for mechlovin PCB to match code used in other files
* Add rgb_timeout and indicator code on my Mechlovin PCBs
* Use correct indicator pin values for Mechlovin PCB
*
=> [Userspace] Update some code and keyboard rules

keyboards/dyz/dyz40/info.json, keyboards/dyz/dyz_tkl/info.json, keyboards/dyz/selka40/info.json, keyboards/dyz/synthesis60/info.json, keyboards/handwired/3dortho14u/rev1/info.json, keyboards/handwired/3dortho14u/rev2/info.json, keyboards/handwired/baredev/rev1/info.json, keyboards/handwired/hillside/0_1/info.json, keyboards/handwired/pytest/info.json, keyboards/handwired/wakizashi40/info.json, keyboards/karlb/kbic65/info.json, keyboards/splitography/info.json
=> `device_ver` -> `device_version` for some more boards

docs/ref_functions.md
Fixes a small typo in `docs/ref_functions.md`.
=> Fix typo in docs/ref_functions.md

keyboards/matrix/noah/readme.md
Change "keybaord" to keyboard
*
=> Fix a small typo in matrix/noah's readme.md

keyboards/linworks/dolice/config.h
This PR fixes an issue with a duplicate product ID for the Linworks Dolice
Linworks Fave84H and Dolice share Vendor + Product ID - this PR increments the Dolice product ID by +1 to fix this issue.
* Changes product ID of Linworks Dolice to a unique one
- [ x I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> Change linworks Dolice product ID to non-duplicate value

keyboards/handwired/m40/5x5_macropad/5x5_macropad.c, keyboards/handwired/m40/5x5_macropad/5x5_macropad.h, keyboards/handwired/m40/5x5_macropad/config.h, keyboards/handwired/m40/5x5_macropad/info.json, keyboards/handwired/m40/5x5_macropad/keymaps/default/keymap.c, keyboards/handwired/m40/5x5_macropad/keymaps/default/readme.md, keyboards/handwired/m40/5x5_macropad/readme.md, keyboards/handwired/m40/5x5_macropad/rules.mk
=> Adding the custom handwired 5x5 macropad.

data/schemas/definitions.jsonschema, data/schemas/keyboard.jsonschema
Mostly to enforce <https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=naming-your-keyboardproject> on PRs.
Longer term, the exceptions will be removed and offending keyboards updated.
=> Lint keyboard/project name

keyboards/converter/usb_usb/usb_usb.h
Positioning of enter/nuhs and numpad keys also needs adjustment (in develop) to conform to `LAYOUT_fullsize_*`
*
=> usb-usb converter: fix layout macros

.github/workflows/auto_approve.yml
Should help to make sure lint runs on keyboard PRs
*
=> Automatically approve workflow runs from first time contributors

data/mappings/defaults.json, data/schemas/keyboard.jsonschema, lib/python/qmk/info.py
Cherry picked whats ready to go from https://github.com/qmk/qmk_firmware/pull/16598.
This PR aims to...
* Provide context for later conversion logic to key against
* Reduce boilerplate
* Later enhance new-keyboard?
Name is still up for grabs as "development_board" still feels a little wordy. (Currently chosen as it seems to be common enough when browsing various documention/stores). Alternative names?
* "preset"
* "carrier_board"
* "dev_board"
* "controller"
* "module" - maybe too close to RIOT terminology
=> Add frameworking for development board presets

drivers/ps2/ps2_mouse.h
change to MOUSE
change mosue to mouse
typo in set_defaults
=> fix typo in ps2 set_defaults

.github/workflows/auto_approve.yml
<https://discord.com/channels/440868230475677696/440868230475677698/960272842191159356>
*
=> Run auto approve only on qmk/qmk_firmware

keyboards/keebio/iris/iris.h, keyboards/keebio/iris/rev6a/config.h, keyboards/keebio/iris/rev6a/rev6a.c, keyboards/keebio/iris/rev6a/rev6a.h, keyboards/keebio/iris/rev6a/rules.mk
Add Iris Rev 6.1, which is still the same hardware, but has lightning support for VIA added to the firmware. People with Rev. 6 firmware can upgrade to Rev. 6.1 firmware, as a different PID is used.
*
=> Add Iris Rev 6.1

data/mappings/defaults.json, data/schemas/keyboard.jsonschema
=> Add bluepill/blackpill development board presets

keyboards/eyeohdesigns/theboulevard/theboulevard.h
- [X ] Keyboard (addition or update)
- [X ] Keymap/layout/userspace (addition or update)
* 
- [X ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ X] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ X] I have added tests to cover my changes.
- [ X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> Header file fixes for all layout macros

keyboards/helix/rev2/keymaps/fraanrosi/rules.mk
Reduce the size of the keymap helix:fraanrosi
@fraanrosi
=> Reduce the size of the keymap helix:fraanrosi

keyboards/gmmk/pro/ansi/keymaps/default/keymap.c, keyboards/gmmk/pro/ansi/keymaps/via/keymap.c, keyboards/gmmk/pro/iso/keymaps/default/keymap.c, keyboards/gmmk/pro/iso/keymaps/via/keymap.c
Returning true causes a lot of questions from new users, I guess it doesn't need these user functions but they do serve as an example.
Ideally I think modifying all existing keymaps to the correct behaviour would be helpful but that's for another PR to develop.
=> GMMK Pro return false in encoder user.

keyboards/s_ol/0xc_pad/0xc_pad.c, keyboards/s_ol/0xc_pad/0xc_pad.h, keyboards/s_ol/0xc_pad/config.h, keyboards/s_ol/0xc_pad/info.json, keyboards/s_ol/0xc_pad/keymaps/default/config.h, keyboards/s_ol/0xc_pad/keymaps/default/keymap.c, keyboards/s_ol/0xc_pad/keymaps/default/readme.md, keyboards/s_ol/0xc_pad/keymaps/default/rgb_matrix_user.inc, keyboards/s_ol/0xc_pad/keymaps/default/rules.mk, keyboards/s_ol/0xc_pad/readme.md, keyboards/s_ol/0xc_pad/rules.mk, keyboards/s_ol/info.json
This PR adds a new keyboard (`0xc_pad`) and manufacturer folder (`s_ol`).
After an "Interest Check" last year, the first set of PCBs, Cases and Keycaps are currently in production.
* Previous stale PR #11622
=> [Keyboard] Add s-ol/0xC.pad

keyboards/crkbd/keymaps/gotham/README.md, keyboards/crkbd/keymaps/gotham/config.h, keyboards/crkbd/keymaps/gotham/keymap.c, keyboards/crkbd/keymaps/gotham/oled.c
fixed OLED turn off issue for `crkbd:gotham`
*
=> fixed oled turn-off issue for crkbd:gotham

keyboards/4pplet/waffling80/keymaps/default/keymap.c, keyboards/4pplet/waffling80/keymaps/via/keymap.c
=> Fix waffling80 - Missing comma

keyboards/mechlovin/kay65/keymaps/default/keymap.c
=> Fix kay65 - Missing keycode

.gitignore
VIA and VIAL json files should not be included in PRs to the QMK repo.  This should help prevent them from being included in PRs.
=> Ignore VIA(L) json files

keyboards/rmkeebs/rm_numpad/info.json
```
$ qmk lint -kb rmkeebs/rm_numpad
☒ rmkeebs/rm_numpad: "LAYOUT_default" has no "matrix" definition in either "info.json" or "<keyboard>.h"!
☒ rmkeebs/rm_numpad: "LAYOUT_split_plus" has no "matrix" definition in either "info.json" or "<keyboard>.h"!
☒ rmkeebs/rm_numpad: "LAYOUT_ortho" has no "matrix" definition in either "info.json" or "<keyboard>.h"!
☒ Lint check failed for: rmkeebs/rm_numpad
```
=> Resolve layout macro inconsistencies for rmkeebs/rm_numpad

keyboards/kbdfans/phaseone/config.h, keyboards/kbdfans/phaseone/keymaps/default/keymap.c, keyboards/kbdfans/phaseone/keymaps/via/keymap.c, keyboards/kbdfans/phaseone/keymaps/via/rules.mk, keyboards/kbdfans/phaseone/phaseone.c, keyboards/kbdfans/phaseone/phaseone.h, keyboards/kbdfans/phaseone/readme.md, keyboards/kbdfans/phaseone/rules.mk
=> add phase one keyboard

quantum/rgblight/rgblight.h
=> Fix #16859.

keyboards/handwired/onekey/keymaps/hardware_id/keymap.c, platforms/arm_atsam/hardware_id.c, platforms/avr/hardware_id.c, platforms/chibios/hardware_id.c, platforms/common.mk, platforms/hardware_id.h, platforms/test/hardware_id.c
To allow XAP to identify devices slightly better, this exposes an API for chipid/serial number/etc.
Currently stubbed out to return 0 for a few scenarios, only stm32 and avr are currently covered. If someone can be bothered, more chips can be added with inspiration from something like <https://github.com/ricaun/ArduinoUniqueID>.
=> Expose API for hardware unique ID

platforms/avr/hardware_id.c
=> Fixup AVR builds.

.github/workflows/develop_api.yml
Fixes up API generation when develop has more python dependencies compared to the base container.
=> Preinstall python dependencies before executing `qmk`.

keyboards/crimsonkeyboards/resume1800/config.h, keyboards/crimsonkeyboards/resume1800/keymaps/via/config.h, keyboards/crimsonkeyboards/resume1800/readme.md
As per title. Causes an error when compiling
```
Compiling: quantum/dynamic_keymap.c                                                                quantum/dynamic_keymap.c:88:1: error: static assertion failed: "Dynamic keymaps are configured to use more EEPROM than is available."
_Static_assert((DYNAMIC_KEYMAP_EEPROM_MAX_ADDR) - (DYNAMIC_KEYMAP_MACRO_EEPROM_ADDR) >= 100, "Dynamic keymaps are configured to use more EEPROM than is available.");                                                                  
^~~~~~~~~~~~~~                                                                                                                                                                                                                         
[ERRORS]
```
=> Fix resume1800 - Dynamic layer count undefined

keyboards/gmmk/pro/ansi/keymaps/andrewcharnley/config.h, keyboards/gmmk/pro/ansi/keymaps/andrewcharnley/keymap.c, keyboards/gmmk/pro/ansi/keymaps/andrewcharnley/readme.md
Personal GMMK ANSI keymap without gimmicks - designed for development. Specifics documented in readme.md
=> chore: Add personal GMMK Pro keymap

keyboards/keyhive/uno/rules.mk
=> Fix build of `keyhive/uno`.

keyboards/jels/jels60/config.h
* Fixed row 1 not registering keys (wrong pin was assigned from prototypes and not updated)
=> Fixed error in config

keyboards/kin80/keymaps/default/keymap.c
@DmNosachev would you mind confirming this is the desired behaviour please?
*
=> Fix kin80 default keymap

keyboards/a_dux/keymaps/default/keymap.c
=> [Keymap] Fix missing KC_QUOT

keyboards/gboards/gergoplex/gergoplex.h, keyboards/gboards/gergoplex/rules.mk
=> gergoplex: small cleanup

docs/reference_keymap_extras.md, quantum/keymap_extras/keymap_ukrainian.h
=> Add Ukrainian keymap header

lib/python/qmk/cli/format/c.py
As per the title. We have some files already.
=> Also format *.hpp files.

keyboards/xelus/rs60/rev2/config.h
Fix RS60 Rev2 I2C hardware from 3 -> 1
*  Fix RS60 Rev2 I2C
=> [Bug] Fix RS60 Rev2 I2C

builddefs/bootloader.mk
Extracted from #14420
The Teensy Loader (GUI and CLI) expects input files in .hex format, even for ARM Teensys.
*
=> Ensure .hex file output for ARM Teensys

keyboards/converter/usb_usb/usb_usb.h
=> converter/usb_usb: remove surplus commas

util/install/msys2.sh
`pillow` cannot be installed through pip on MSYS2 because it must be compiled from source - there is no wheel for `mingw_x86_64` - however this fails because of missing image library headers.
Instead, I think it might be a good idea to first install as many Python packages through the system package manager as possible, at the very least for MSYS2. This way they also stand a better chance of being updated more regularly.
*
=> MSYS2 install: add some Python dependencies through Pacman

keyboards/fjlabs/tf65rgbv2/tf65rgbv2.h
Two buttons of the layout of the tf65rgbV2 were swapped.
* Fixed layout of the tf65rgbV2
=> fixed tf65rgbv2 keyboard layout

keyboards/4pplet/yakiimo/keymaps/default/keymap.c
Default keymap missing a comma, causing compilation errors.
=> Fixup 4pplet/yakiimo

drivers/sensors/cirque_pinnacle_spi.c
Updated the Cirque Pinnacle SPI driver to interact with their registers for requesting data register reads as described in their Application Note (GT-AN-090620) and as shown in their example code:
https://github.com/cirque-corp/Cirque_Pinnacle_1CA027/blob/master/Circular_Trackpad/Dual_Pad_Sample_Code/SPI_FlatCurved/SPI_FlatCurved.ino
* None
=> Updated Cirque Pinnacle SPI driver to read data correctly.

keyboards/cannonkeys/balance/config.h
Adding Caps lock and Num lock indicators to the Balance PCB
*
=> Add caps and num indicators to Balance keyboard

builddefs/common_rules.mk
=> Warn about LTO with arm_atsam, not ChibiOS.

keyboards/kbdfans/tiger80/tiger80.h
=> fix tiger80 matrix error

keyboards/machkeyboards/mach3/mach3.c
LED index correction for `g_led_config`.
* #17105
=> LED index correction

keyboards/xelus/pachi/rgb/rev1/config.h, keyboards/xelus/pachi/rgb/rev2/config.h
Fix Pachi RGB i2c pin definitions
* Fix Pachi RGB Rev1 i2c
* Fix Pachi RGB Rev2 i2c
=> [Bug] Fix old i2c pin definitions

docs/pr_checklist.md
Update link to mcu_selection.mk from https://github.com/qmk/qmk_firmware/blob/master/quantum/mcu_selection.mk to https://github.com/qmk/qmk_firmware/blob/master/builddefs/mcu_selection.mk
*
=> Fix bad link in  PR checklist

docs/faq_keymap.md
Initially just adding a section on VIA foiling keymap updates, turned into a light cleanup of the page. I thought the real/weak mods entry needed a bit of clarification too.
*
=> Keymap FAQ updates

docs/newbs_getting_started.md
=> Recommend pillow as part of manual MSYS install

platforms/avr/platform.mk
=> Workaround for recent -Werror=array-bounds AVR issues

docs/feature_stenography.md
The left half keys follow a pattern of left-to-right top then bottom in each column. The right half keys were close to this, but had two characters flipped. I rearranged it so it is consistent between the sides for ease of writing keymaps while referencing this table.
* None
=> Update Steno Keycode Table

keyboards/ryanskidmore/rskeys100/config.h
LED count correction.
* #17105
=> [Keyboard] rskeys100 LED index correction

docs/feature_led_matrix.md
The LED Matrix docs states that a user needs to disable an effect while showing a table with defines to enable them, this PR fixes it.
*
=> Align LED Matrix docs with RGB matrix docs

keyboards/dailycraft/sandbox/rev1/info.json, keyboards/dailycraft/sandbox/rev2/info.json
[title]
cc @yfuku (keyboard maintainer)
=> Dailycraft Sandbox Configurator Data

keyboards/massdrop/alt/keymaps/charlesrocket/keymap.c
Custom keymap for the Massdrop ALT keyboard
=> Add massdrop/alt:charlesrocket keymap

docs/ChangeLog/20220528.md, docs/breaking_changes.md, docs/feature_encoders.md
Breaking changes docs for the 2022q2 merge.
=> Breaking changes for 2022q2.

keyboards/checkerboards/quark_lp/keymaps/via/rules.mk
=> Fix quark_lp via firmware size

.github/workflows/unit_test.yml
=> Use correct container for unit test workflow

keyboards/handwired/dactyl_manuform/3x5_3/keymaps/default/keymap.c, keyboards/handwired/dactyl_manuform/3x5_3/rules.mk, keyboards/keebio/bamfk1/keymaps/default/rules.mk, keyboards/keebio/bamfk1/rules.mk
=> Fix API errors

layouts/community/ortho_4x12/junonum/config.h, layouts/community/ortho_4x12/junonum/keymap.c, layouts/community/ortho_4x12/junonum/readme.md
- Apply homerow mods to my personal universal layout `ortho_4x12/junonum`.
- Remove some unnecessary dual function keys in the process.
- Update readme
*
=> [Keymap] Update personal keymap layouts/community/ortho_4x12/junonum

docs/flashing.md, docs/zh-cn/flashing.md
=> Fix small docs typo

keyboards/acheron/shark/alpha/config.h, keyboards/acheron/shark/alpha/rules.mk
Added rotary encoder support for `acheron/shark/alpha`. [Link to pin schematic](https://github.com/AcheronProject/SharkPCB/releases/tag/Alpha)
<details>
<summary>Schematic detail</summary>
</br>
</details>
=> Acheron shark alpha encoder support

keyboards/ploopyco/trackball_nano/keymaps/maddie/keymap.c
This keymap was using a user function that had been removed from QMK, so it was never being called.  The function that replaces it provides a slightly different interface, so the implementation in this keymap had to be updated as well as the
function signature.
=> Fix maddie layout for ploopy/trackball_nano

tests/tap_hold_configurations/default_mod_tap/test_tap_hold.cpp, tests/tap_hold_configurations/ignore_mod_tap_interrupt/test_tap_hold.cpp, tests/tap_hold_configurations/permissive_hold/test_one_shot_keys.cpp, tests/tap_hold_configurations/permissive_hold/test_tap_hold.cpp, tests/tap_hold_configurations/permissive_hold_ignore_mod_tap_interrupt/test_tap_hold.cpp, tests/tap_hold_configurations/retro_tapping/test_tap_hold.cpp, tests/tap_hold_configurations/retro_tapping/test_tapping.cpp, tests/tap_hold_configurations/tapping_force_hold/test_action_layer.cpp, tests/tap_hold_configurations/tapping_force_hold/test_tap_hold.cpp
...convenience macros to test cases that where missed during #17284. As the prior hotfix PR targeted `master` this targets `master` as well.
*
=> [Core] Apply EXPECT_REPORT and EXPECT_EMPTY_REPORT

keyboards/gmmk/pro/rev1/ansi/keymaps/trwnh/config.h, keyboards/gmmk/pro/rev1/ansi/keymaps/trwnh/keymap.c, keyboards/gmmk/pro/rev1/ansi/keymaps/trwnh/readme.md, keyboards/gmmk/pro/rev1/ansi/keymaps/trwnh/rules.mk
Finally upstreaming my personal keymap for the GMMK Pro after tweaking it over the course of the past few weeks.
Notable features include:
- No changes to Layer 0 compared to the default keymap (although I may be convinced to make changes)
- Layer 1 allows more sensible "zones" for certain functionality
- RGB controls can be increased/decreased more logically
- Arrow keys correspond to Home/End and PgUp/PgDn
- Media control are clustered in the lower-left corner
- Layer 2 allows mouse control
- RGB is a constant rainbow on the sides, while only the "best" (subjectively) effects are enabled. All else are disabled.
- When Caps Lock is enabled, the alphas turn red.
=> Add trwnh keymap for GMMK Pro

drivers/sensors/pimoroni_trackball.c, drivers/sensors/pimoroni_trackball.h
Pretty sure #16371 just forgot to remove this function, as it was moved to `quantum/pointing_device_drivers.c`
=> Fixup pimoroni trackball

keyboards/durgod/k3x0/readme.md
First of all, I'm a beginner when it comes to QMK, and just started using it this week. And glad to the development that went in this project in all fronts!
But when trying to flash my Durgod K320, I had some problems understanding the current docs, they are definitely not bad, but as a beginner, some of the terms or actions described on the original readme didn't really make sense at first glance, and I was only able to understand after searching on the discord server for previous questions like mine or researching on the internet.
So after flashing my keyboard for the first time, and getting more knowledgeable on the matter, I've writter a more descriptive readme for this keyboard, including requirements and a more descriptive behavior of the keyboard.
*
=> Improve the durgot k3x0 readme.md

keyboards/nacly/sodium62/keymaps/default/keymap.c, keyboards/nacly/sodium62/sodium62.c
Layer names weren't defined in `sodium62.c` file, causing build errors.
=> Fixup nacly/sodium62

keyboards/evyd13/wasdat/config.h, keyboards/evyd13/wasdat/info.json, keyboards/evyd13/wasdat/rules.mk
CLI complains about missing diode direction when I move matrix pins to data driven, even with custom matrix set :/
*
=> Wasdat: move some stuff to info.json

quantum/via.c
=> Fix via builds broken by brightness scaling

lib/python/qmk/cli/doctor/macos.py
At the moment, this will always report `Intel`, as the CLI must be installed under Rosetta 2 due to the lack of M1 bottles for the ARM and AVR toolchains - GHA has no M1 runners yet.
*
=> `qmk doctor`: show arch for macOS

.github/workflows/stale.yml
Apparently the labels need to be as a comma-separated list.
=> Fixup stale action.

docs/compatible_microcontrollers.md
After a user on Discord complained that things weren't compatible.
=> Inform people that things may not work.

keyboards/handwired/macroboard/keymaps/via/keymap.c
VIA keymap was missing a closing brace.
=> Fixup handwired/macroboard

.github/workflows/stale.yml
Seems I got the labels around the wrong way. Did some cleanup in the process.
Messages now match the applicable labels.
=> Fixup stale labels lists.

docs/feature_split_keyboard.md
Hi,
thanks for your work 💪 .
I asked a few days ago on reddit if it is possible to use two differents MCU on a split keyboard and [@drashna answered me that it is not possible to mix AVR and ARM](https://www.reddit.com/r/olkb/comments/vc7f2x/how_to_configure_a_split_keyboard_with_2/iceq8p9/?context=3). I think the doc is lacking this use case, so here is a modification for it.
=> Add a note about using differents MCU family

keyboards/xiudi/xd75/keymaps/markus/config.h, keyboards/xiudi/xd75/keymaps/markus/keymap.c
=> [Keymap] Update XD75 keymap by markus

docs/reference_info_json.md
i found the current wording quite confusing, as the example's inner array isn't a string, it's an array, and corresponds to multiple pins
=> [Docs] clarify inner array of direct pin matrix

keyboards/checkerboards/snop60/keymaps/default/keymap.c
=> Add missing snop60 default keymap

docs/feature_rgb_matrix.md, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3741.c
This PR, in relation with #17420, adds the `ISSI_GLOBALCURRENT` setting to all other ISSI drivers that support that current have it hardcoded.
*
=> ISSI Drivers Global Current Option

util/size_regression.sh
I wondered why I could never see 0 delta results.
*
=> Display 0 delta results in size regression

docs/ref_functions.md
Replaced deprecated `RESET` to `QK_RBT`/`QK_BOOT`.
=> Update ref_functions.md (replaced deprecated `RESET`)

lib/python/qmk/cli/generate/keyboard_h.py
=> Fix error message in generated code

quantum/mousekey.c
Cna cause a weird edge case where the pointer gets "stuck" and stops moving correctly. 
* Reported by ZSA
=> [Bug] Fix issue with mousekey movement getting stuck

keyboards/adm42/info.json
[title]
cc @lleonini (keyboard maintainer)
* ![image](https://user-images.githubusercontent.com/18669334/176754661-33cb28bc-2a38-4f9b-a266-d97931b144ea.png)
=> Add QMK Configurator layout data for ADM42 rev4

util/uf2conv.py
Adds `/run/media/<user>/` as a location to check, as `/media` does not exist on the machine im testing on.
=> Also check /run/media/ for uf2 drives

keyboards/cantor/info.json, keyboards/handwired/dygma/raise/rules.mk, keyboards/handwired/macroboard/f401/rules.mk, keyboards/handwired/macroboard/f411/rules.mk, keyboards/handwired/meck_tkl/blackpill_f401/rules.mk, keyboards/handwired/onekey/blackpill_f401/rules.mk, keyboards/handwired/onekey/blackpill_f411/rules.mk, keyboards/handwired/pill60/blackpill_f401/rules.mk, keyboards/handwired/pill60/blackpill_f411/rules.mk, keyboards/handwired/riblee_f401/rules.mk, keyboards/handwired/riblee_f411/rules.mk, keyboards/handwired/tractyl_manuform/5x6_right/f411/rules.mk, keyboards/handwired/uthol/rev3/rules.mk, keyboards/kin80/blackpill401/rules.mk, keyboards/kin80/blackpill411/rules.mk, keyboards/mechwild/obe/f401/eeprom/rules.mk, keyboards/mechwild/obe/f401/rules.mk, keyboards/mechwild/obe/f411/eeprom/rules.mk, keyboards/mechwild/obe/f411/rules.mk, keyboards/mechwild/waka60/f401/eeprom/rules.mk, keyboards/mechwild/waka60/f401/rules.mk, keyboards/mechwild/waka60/f411/eeprom/rules.mk, keyboards/mechwild/waka60/f411/rules.mk, keyboards/mlego/m60_split/rev2/rules.mk, keyboards/tkw/grandiceps/rules.mk, keyboards/tkw/stoutgat/v2/f411/rules.mk, keyboards/tronguylabs/m122_3270/blackpill/rules.mk, keyboards/yanghu/unicorne/f411/rules.mk, keyboards/zvecr/zv48/f401/rules.mk, keyboards/zvecr/zv48/f411/rules.mk
Prep for when the default changes away from blackpill files.
*
=> Specify blackpill board files where relevant

lib/python/qmk/keymap.py
```sh
$ qmk lint -kb idobao/id80/v1
☒ idobao/id80/v1: Can't find default keymap.
☒ Lint check failed for: idobao/id80/v1
$ qmk lint -kb idobao/id80/v1/ansi
Ψ Lint check passed!
```
=> Allow locate_keymap to handle DEFAULT_FOLDER

drivers/painter/ssd1351/qp_ssd1351.c
=> Fixup SSD1351 build after #17438

keyboards/preonic/keymaps/jpe230/config.h, keyboards/preonic/keymaps/jpe230/jpe230.h, keyboards/preonic/keymaps/jpe230/keymap.c, keyboards/preonic/keymaps/jpe230/rules.mk
Personal Keymap, used some hacks to dynamically change the keycodes of the 2u bars
*
=> Add Jpe230 Preonic Keymap

keyboards/bastardkb/charybdis/charybdis.c, keyboards/bastardkb/charybdis/post_config.h, keyboards/bastardkb/charybdis/readme.md, keyboards/handwired/tractyl_manuform/tractyl_manuform.c
Use the correct limits for the X-Y reports in charybdis code
=> [Keyboard] Update Charybdis code for Extended Mouse reports

keyboards/checkerboards/quark_squared/config.h, keyboards/checkerboards/quark_squared/quark_squared.c, keyboards/checkerboards/quark_squared/rules.mk
=> add rotary encoder support for Quark^2

users/stanrc85/config.h, users/stanrc85/rules.mk
Small changes to my userspace to support Nasu board.
* Define indicator pins to match existing code
* Use existing indicator code on Nasu board
*
=> [Userspace] Add Nasu to userspace code

keyboards/novelkeys/nk1/config.h
Just updating the config file to align with the animation defines of other boards :)
*
=> Update NK1 RGB animation defines

keyboards/ploopyco/trackball/trackball.c
Added a horizontal invert option
=> Added PLOOPY_DRAGSCROLL_H_INVERT

users/stanrc85/config.h, users/stanrc85/rules.mk
I just realized one of my Adelais PCB is a different version than my previous one so I'm adding the necessary changes to support it in my userspace.
*
=> [Userspace] Add support for additional Mechlovin Adelais PCB version to my userspace 

docs/newbs_getting_started.md
Lot of users who have little terminal experience seem to be choosing the manual install for whatever reason...
=> Attempt to discourage manual MSYS install for new users

platforms/chibios/boards/QMK_PM2040/configs/config.h
Minor correction to the I2C pins from #17514
=> Update PM2040 I2C pins

lib/python/qmk/cli/multibuild.py
Enabler for the incoming CI, makes sure there's something in the logfile that can be parsed to determine what was targeted.
=> Add line to multibuild output log showing the actual build target.

keyboards/merge/um80/um80.c
=> merge/um80 - Fix WPM issues in configurator builds

keyboards/checkerboards/quark_plus/quark_plus.c
=> Fix infinite recursion in checkerboards/quark_plus

platforms/avr/drivers/i2c_master.h
Without this directly included here, errors are likely to occur when making use of data-driven configuration and omitting config.h/other files.
=> Include stdint.h in avr/i2c_master.h

docs/_summary.md, docs/feature_secure.md, docs/reference_info_json.md
Somewhat to cover the XAP case where someone wants a longer `SECURE_UNLOCK_TIMEOUT`.
*
=> Add basic secure docs

docs/feature_converters.md
=> Grammar fixes for docs/feature_converters.md

keyboards/mode/m75h/readme.md
Readme content correction
* Fixes #17309
=> [Keyboard] Readme file correction

docs/feature_rgb_matrix.md, quantum/rgb_matrix/animations/solid_reactive_anim.h, quantum/rgb_matrix/animations/solid_reactive_cross.h, quantum/rgb_matrix/animations/solid_reactive_nexus.h, quantum/rgb_matrix/animations/solid_reactive_simple_anim.h, quantum/rgb_matrix/animations/solid_reactive_wide.h
Add gradient color mode to all 5 RGB matrix solid reactive effect. With this mode enabled, the reactive color hue will slowly change over time.
=> [Code] Add solid reactive gradient mode

.gitignore
While we shouldnt have to do this... :cry: 
* Ignore kb.c/kb.h
* Update Makefile ignores to be less verbose
Adding to ignore will then flag these files in the `qmk lint` CI workflow
=> Ignore kbfirmware exports

keyboards/coseyfannitutti/discipline/keymaps/briianpowell/keymap.c, keyboards/coseyfannitutti/discipline/keymaps/briianpowell/readme.md, keyboards/gentleman65/keymaps/briianpowell/keymap.c, keyboards/gentleman65/keymaps/briianpowell/readme.md
Added Layout Keymaps for BriianPowell:
- Discipline
- Gentleman65
* For those wondering if the Gentleman works well with QMK, there is full support I have not had any issues
=> Added Layout Keymaps for BriianPowell

keyboards/converter/m0110_usb/config.h, keyboards/handwired/minorca/config.h, keyboards/handwired/promethium/keymaps/default/config.h, keyboards/momoka_ergo/config.h
Removed from non user code as it no longer exists.
*
=> Remove full bootmagic config

.github/dependabot.yml
Bots are currently fighting with each other...
*
=> Add reviewer/labels to dependabot PRs

keyboards/mechlovin/kay60/config.h, keyboards/mechlovin/kay60/keymaps/default/keymap.c, keyboards/mechlovin/kay60/keymaps/via/keymap.c
Change capslock LED state, correct modify keycode in default and via keymap.
Thanks.
*
=> [Kay60] Change LED pin state and correct keycode.

docs/feature_macros.md, quantum/quantum.c, quantum/quantum.h
=> Add `tap_code16_delay`

docs/audio_driver.md
Noticed a while ago, that a couple of the tables were malformed.  Finally got around to fixing.
=> [Docs] Fix tables in Audio driver document

keyboards/charue/sunsetter_r2/sunsetter_r2.h
Fixed Sunsetter R2's Spacebar Position
*
=> Fixed spacebar position of Charue Design Sunsetter R2

keyboards/handwired/onekey/teensy_lc/readme.md
Updated the README to reflect the discussions on #17709. As noted in the issue the pins are working as intended. Just tested a Teensy LC with the pins in question. 
* fixes #17709
=> Update README.md to fix #17709

keyboards/cradio/config.h, keyboards/cradio/readme.md, keyboards/ferris/sweep/config.h, keyboards/ferris/sweep/readme.md
* `config.h` clean up
* Build instructions for RP2040 pro micro controllers.
=> [Keyboard] Add RP2040 config defaults

lib/python/qmk/submodules.py
The `echo` command `-n` parameter does not work as intended with `git submodule` on MacOS.
* Fixes #17806
=> CLI compatibility for MacOS

docs/feature_oled_driver.md
#17861 migrates the last problem keyboard over to split common.
=> Remove OLED driver Split Common warning

keyboards/uzu42/keymaps/default/keymap.c
Including a file that #17864 removed.
=> Fixup uzu42

keyboards/balloondogcaps/tr90/info.json, keyboards/balloondogcaps/tr90/keymaps/default/keymap.c, keyboards/balloondogcaps/tr90/keymaps/via/keymap.c, keyboards/balloondogcaps/tr90pm/info.json, keyboards/balloondogcaps/tr90pm/keymaps/default/keymap.c, keyboards/balloondogcaps/tr90pm/keymaps/via/keymap.c
[title]
cc @balloondogcaps (keyboard maintainer)
*
=> Balloondogcaps TR90 and TR90PM: rename LAYOUT to LAYOUT_ortho_3x3

docs/_summary.md, docs/newbs_building_firmware_workflow.md
Documentation on an alternative out-of-tree build environment. Users will only need to setup a personal repository with [Userspace](https://docs.qmk.fm/#/feature_userspace) code structure and keymaps in QMK Configurator JSON format.
GitHub action workflow will be use to merge the userspace content into `users/` path to build firmware in a container for download.
=> [Docs] Building with GitHub Userspace

data/mappings/info_config.json, data/mappings/info_rules.json, lib/python/qmk/info.py
Point people at the new way of doing stuff if needed.
*
=> Provide users with replacements for deprecated/invalid functionality where applicable

keyboards/takashicompany/minizone/keymaps/pimoroni_trackball/keymap.c
miniZone keyboard's "Pimoroni Trackball" keymap updated.
*
=> Update miniZone keymap

.github/workflows/develop_update.yml, .github/workflows/feature_branch_update.yml
Following on from #16176, the merge of `master` to `develop` failed.
*
=> Also disable line ending conversion for merge workflows
