tmk_core/protocol/lufa/lufa.c
tmk_core/protocol/lufa/outputselect.h

Simplifying the output selection logic.
*

Output selection: Remove "USB and BT" option

---

keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c

Change the g_led_config matrix to give each key an LED for RGB matrix reactive modes in my Mark65 keymap.
*

[Keymap] Assign each key an LED for reactive modes 

---

tmk_core/common/action.c
tmk_core/common/report.h

Refactor for code size & maintainability; save ~134 bytes on ATmega32.
```
commit 03ddd855d28dca2804e6b3e2a078b484e8fb1daa (origin/develop/action-mouse, develop/action-mouse)
Author: Liyang HU <git@liyang.hu>
Date:   Tue Feb 16 14:38:16 2021 +0000
tmk_core/common/action.c: collapse multiple `case KC_MS_BTN[1-8]:` into single `MOUSE_BTN_MASK(action.key.code - KC_MS_BTN1)`
This saves ~134 bytes on my ATmega32.
commit 1be62c75368575e09c8aa29a4252d02945167f83
Author: Liyang HU <git@liyang.hu>
Date:   Tue Feb 16 14:06:30 2021 +0000
tmk_core/common/report.h: define `enum mouse_buttons` in terms of `#define MOUSE_BTN_MASK()`
```
* ~~n/a~~

tmk_core/common/action.c: refactor for code size; merge multiple `case`s into one

---

keyboards/ergodox_ez/keymaps/dvorak_42_key/keymap.c

Changes to ergodox_ez dvorak_42_key layout.
*

ergodox_ez / dvorak_42_key layout: convert macros to new format

---

keyboards/handwired/pill60/info.json

Fix handwired/pill60 info.json so that it's working in configurator
changed LAYOUT_default to LAYOUT
*

pill60 fix info.json to be used in configurator

---

keyboards/massdrop/ctrl/config_led.c
quantum/quantum.c
tmk_core/common/keyboard.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.c
tmk_core/protocol/arm_atsam/md_rgb_matrix_programs.c

Massdrop boards weren't initialising correctly. This PR fixes things.

[BUG] Massdrop develop rgb fix

---

docs/getting_started_docker.md
util/docker_build.sh

* break out runtime into the RUNTIME variable
* allows RUNTIME to be set by the user
* decides on docker or podman if docker isn't avaible
* rewrote check for docker-machine to account only for docker runtime
* put --user arg into a variable only to be used with docker
this is not needed with podman as podman maps the containers root id
to the users id.

Add support for using podman to util/docker_build.sh

---

keyboards/ryloo_studio/m0110/m0110.h

Fixed LAYOUT_60_ansi for the ryloo_studio/m0110 keyboard - space key is correctly mapped now. 
I have this keyboard so I tested this manually and the space key works now 
*

fix: ryloo studio m0110 layout 60 ansi fixed

---

docs/feature_advanced_keycodes.md
docs/feature_macros.md

Added a new section to the documentation on modifiers on the topic of checking modifier states. I explain how to use mod masks to detect modifiers and give two code examples, including the very frequently asked for shift + backspace → del functionality.
Speaking of the del example, I have used an implementation that involves creating a new variable `uint8_t mod_state` and using it in `set_mods(mod_state)`. I know that it could be avoided by doing `add_mods(MOD_MASK_SHIFT)` or `add_mods(MOD_BIT(KC_LSFT))` instead but I chose against the latter options for multiple reasons; `add_mods(MOD_MASK_SHIFT)` would enable both shifts which can be problematic for people for whom pressing both shifts produces something special like toggling Caps Lock. `add_mods(MOD_BIT(KC_LSFT))` presupposes that the …

[Docs] New section to modifier docs: Checking Modifier State

---

keyboards/spiderisland/split78/config.h
keyboards/spiderisland/split78/matrix.c
keyboards/spiderisland/split78/readme.md
keyboards/spiderisland/split78/rules.mk

Updates to this keyboard:
- big debounce added, since I've been having bouncing problems with the `A` key
- `sym_eager_pr` because split, similar to ergodox
- added code to reset the MCP23018 when I2C ops fail, so reconnecting the right side doesn't require rebooting the keyboard anymore
- the ports are prone to interrupting the connection when moving the halves around, so this makes the keyboard much less annoying
- ping @walkerstop — might want to import these changes back into wheatfield/split75 :)
- update my github username while here

[Keyboard] Update spiderisland/split78

---

keyboards/ploopyco/trackball/trackball.c

The PloopyCo Trackball has a feature called "drag scroll" that lets the user press a button to enter a mode where scrolling is done with the trackball instead of the scroll wheel. The default behavior of the PloopyCo Trackball's drag scroll feature is for the vertical axis to scroll opposite to the direction the trackball is rolling (i.e. rolling the trackball up scrolls down and vice versa), while the horizontal axis scrolls in the same direction as the trackball. Personally, I find this a bit unintuitive, so I have added a configuration option called PLOOPY_DRAGSCROLL_INVERT that makes the vertical axis scroll in the same direction as the trackball's movement.
* None

Create an option for the PloopyCo Trackball that inverts the DRAG_SCROLL mode's vertical scroll direction.

---

quantum/split_common/split_util.c
tmk_core/common.mk
tmk_core/common/chibios/chibios_config.h
tmk_core/common/usb_util.c
tmk_core/common/usb_util.h
tmk_core/protocol/chibios.mk
tmk_core/protocol/chibios/usb_util.c
tmk_core/protocol/lufa.mk
tmk_core/protocol/lufa/usb_util.c
tmk_core/protocol/vusb.mk
tmk_core/protocol/vusb/usb_util.c

Refactor of USB code within split_common

---

tmk_core/rules.mk

Added `-fcommon` flag to avoid linking errors due to multiple variable definitions. Though this is neither a definitive nor good solution. Proper changes with use of `extern` keyword to avoid those multiple definitions must be made.
I recently bought a Drop CTRL and qmk_firmware couldn't compile it. Investigating the reason of that I found issue #9733, and PR #9485 fixing this issue. That PR has not yet been merged due to changes on non-default keymaps, problems with this mentioned in https://github.com/qmk/qmk_firmware/pull/9485#issuecomment-647044303. As @DelusionalLogic said, using -fcommon is also an option. Before gcc 10 this was the default but it isn't anymore, breaking a bunch of keyboards that need to be fixed.
I've tested make all:default with and without the change and it …

Modified tmk_core/rules.mk to avoid linking errors

---

keyboards/massdrop/ctrl/keymaps/default/keymap.c
keyboards/massdrop/ctrl/keymaps/default_md/keymap.c
keyboards/massdrop/ctrl/keymaps/mac/keymap.c
keyboards/massdrop/ctrl/keymaps/mac_md/keymap.c
keyboards/massdrop/ctrl/keymaps/responsive_pattern/keymap.c

General direction is to remove this when possible, and it also causes linking issues on gcc10.

Remove unused keymap_config from ctrl keymaps

---

keyboards/lily58/keymaps/default/keymap.c

Fixed triggering of the adjust layer in the lily58 keymap. This was broken during cleanup in pull #9979 which ended up orphaning the `update_tri_layer_RGB` function. I've updated this to use `update_tri_layer_state`, and removed an unused extern declaration.
FYI to @kata0510, maintainer of the lily58 keyboard
*

Fixing adjust layer issue with the lily58 default keymap

---

keyboards/ergodone/ergodone.h

The layout has one typo for ergodone keyboard in 80 key layout which makes one key duplicates the other.
*

Fix the typo in ergodone 80 layout

---

docs/feature_split_keyboard.md

I ran into some issues trying to suspend my computer when my tightyl was connected, and found that using `SPLIT_HAND_MATRIX_GRID` to identify the left side of the keyboard kept waking my computer back up. The solution was to define `MATRIX_MASKED` and supply a `matrix_mask` array, but it seemed useful to document this alongside `SPLIT_HAND_MATRIX_GRID`.
* #11958 is the bug that I filed for suspend issues on windows, and defining `MATRIX_MASKED` was the fix

MATRIX_MASKED docs for SPLIT_HAND_MATRIX_GRID

---

tmk_core/common/suspend.h

While I feel that this feature is a good change, and can benefit people, it seems that it does also cause issues. 
Have seen a couple of reports on discord of this causing problems, but ZSA has had a bunch of customers seeing issues with this change.

Set default for USB_SUSPEND_WAKEUP_DELAY to 0/disabled

---

keyboards/lily58/keymaps/default/config.h
keyboards/lily58/keymaps/default/keymap.c

This change removes some extraneous code leftover from PR #6260 which migrated the Lily58 config to use `split_common`. This code is a no-op at the moment, and likely confusing for new Lily58 users trying to customize their keymaps.
*

Remove more cruft from Lily58 default keymap

---

docs/feature_rgb_matrix.md
quantum/rgb_matrix.c
quantum/rgb_matrix_types.h
quantum/split_common/transport.c
tmk_core/common/avr/suspend.c
tmk_core/common/chibios/suspend.c
tmk_core/common/eeconfig.c
tmk_core/common/eeconfig.h

Final implementation of the Split RGB Matrix feature. This builds upon the previous features of #11046  and #10997 
*

Split RGB Matrix

---

docs/ws2812_driver.md
drivers/chibios/ws2812_pwm.c

Advanced-control timers (TIM1, TIM8, TIM20) on STM32 support complementary outputs (`TIMx_CHyN`) that actually have configurable polarity and can work exactly like normal outputs.  Add support for these outputs to the WS2812 PWM driver.
Using a complementary output requires adding
#define WS2812_PWM_COMPLEMENTARY_OUTPUT
to the usual set of PWM driver configuration options.  In addition, the `STM32_PWM_USE_ADVANCED` option in mcuconf.h must be set to `TRUE` (otherwise the flags to configure complementary outputs are silently ignored by the ChibiOS low-level PWM driver).
Note that complementary outputs of general-purpose timers (e.g., TIM15/TIM16/TIM17 on STM32F303) are still not supported, because the current version of the ChibiOS low-level PWM driver does not have the code to control …

Add support for complementary outputs to the WS2812 PWM driver

---

keyboards/crkbd/rev1/common/config.h
keyboards/crkbd/rev1/common/rules.mk
keyboards/crkbd/rev1/rev1.c

Since the RGB Matrix Split stuff has landed, add support for it in the corne keyboard.

[Keyboard] Enable RGB Matrix for Corne

---

docs/faq_debug.md
docs/feature_split_keyboard.md

- Clearify how (lack of) SPLIT_USB_DETECT affects Micro Pro vs Teensy/ARM.
- Add HID Listen udev rules tip.
*

Documentation changes SPLIT_USB_DETECT and hid_listen udev rules

---

quantum/quantum_keycodes.h

If the Swap Hands feature is disabled, it errors out on the keycodes for it, since they're no longer defined.   This adds placeholders for them (aliased to `KC_NO`), so that it doesn't error out when compiling.

Remove ifdefs for Swap Hands keycodes

---

keyboards/bastardkb/tbk/info.json

Change the layout name so it is displayed correctly in the online configurator
* 

Update correct layout name for online configurator

---

drivers/oled/oled_driver.h

Because the matrix scanning is slower for splits, in general,
the frequent updating of the OLEDs can slow down the matrix scanning.
To help prevent that, set the update interval for the OLEDs to not
update as frequently.

Set default OLED Update Interval for Split Keyboards

---

quantum/quantum_keycodes.h

This won't break VIA, so may as well get it in now.
*

Remove a few more ifdefs from quantum_keycodes

---

keyboards/ferris/keymaps/default/keymap.json
keyboards/ferris/keymaps/default/readme.md
keyboards/ferris/keymaps/pierrec83/keymap.json

The code was moved to the "ferris" directory.
Fixes the following commands:
```
qmk compile ~/qmk_firmware/keyboards/ferris/keymaps/default/keymap.json
qmk compile ~/qmk_firmware/keyboards/ferris/keymaps/pierrec83/keymap.json
```
* https://github.com/pierrechevalier83/ferris/issues/5
- [x My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)

Remove stale references to "handwired/ferris"

---

tmk_core/avr.mk

Technically, you can build QMK DFU without having `BOOTLOADER = qmk-dfu` set in rules.mk... but this should hopefully make it clearer that `:bootloader` and `:production` do not build whichever bootloader is defined; they are specific to QMK DFU. And who knows, perhaps the correct `BOOTLOADER` rule will be necessary at some point.
*

Require `BOOTLOADER = qmk-dfu` for `:bootloader` target

---

Makefile
bin/qmk
build_json.mk
build_keyboard.mk
lib/python/qmk/commands.py
lib/python/qmk/tests/test_cli_commands.py

This marks `bin/qmk` as deprecated in favor of the qmk cli. At this point I think most people have gotten on board with installing it globally. We will mark it deprecated during this develop cycle and remove it during the next.

Begin the process of deprecating bin/qmk in favor of the global cli

---

common_features.mk
quantum/led_matrix.c
quantum/led_matrix.h
quantum/process_keycode/process_backlight.c
quantum/quantum.c
quantum/quantum.h
tmk_core/common/eeconfig.h

This PR removes the dependency of LED Matrix on `BACKLIGHT_ENABLE`, and moves the EEPROM config to the same addresses as RGB Matrix. It still uses `process_backlight()` though, as `process_led_matrix(uint16_t, keyrecord_t*)` already exists (matching the RGB Matrix one, it does not only handle keycode events).
*

LED Matrix: decouple from Backlight

---

quantum/quantum_keycodes.h

As far as I can tell there are no more usages of this particular alias left (though there are still a lot of keymaps using fn_actions).
*

Remove `FUNC()`

---

quantum/quantum.h
tmk_core/common/arm_atsam/_wait.h
tmk_core/common/avr/_wait.h
tmk_core/common/chibios/_wait.h
tmk_core/common/chibios/wait.c
tmk_core/common/test/_wait.h
tmk_core/common/wait.h

Move gpio wait logic to platform locations

---

layouts/community/ergodox/coderkun_neo2/keymap.c
quantum/process_keycode/process_unicode_common.c
quantum/quantum.c
quantum/quantum.h
quantum/send_string.c
quantum/send_string.h

I think these technically belong here.
@coderkun just a heads up that this (lightly) touches your code, but there shouldn't be any functional change.
*

Remove hex_to_keycode and move tap_random_base64 to send_string.c

---

keyboards/boardsource/5x12/info.json

The layout name in info.json didn't match the name elsewhere in the code, so I couldn't load keymaps in properly

fix info.json layout name for boardsource/5x12

---

keyboards/clueboard/66_hotswap/gen1/gen1.c
keyboards/terrazzo/terrazzo.c
quantum/led_matrix.c
quantum/led_matrix.h
quantum/led_matrix_drivers.c

No more including the ISSI driver header in keyboard code.
*

LED Matrix: Clean up includes

---

data/schemas/keyboard.jsonschema
lib/python/qmk/constants.py
quantum/mcu_selection.mk
tmk_core/common/chibios/bootloader.c
tmk_core/common/chibios/chibios_config.h

This is in preparation for https://github.com/qmk/qmk_firmware/pull/10171
* https://github.com/qmk/qmk_firmware/pull/10171

core: add support for MK66F18 (Teensy 3.6) micro controller

---

keyboards/torn/bongocat.c

I was implementing a keymap for Torn and noticed that `process_record_user` was never called. 
After speaking to Torn's creator, @rtitmuss, this was identified as the fix.

Fixes an issue where custom keycodes were not possible in Torn

---

keyboards/bm68rgb/keymaps/default/keymap.c

fix bm68rgb default keymap

---

Makefile
bin/qmk
lib/python/qmk/commands.py

As reported in #12271 QMK_BIN was not correctly passed along to `build_keyboard.mk` in some situations.

Consistently use bin/qmk when that script is called

---

docs/ws2812_driver.md
drivers/chibios/ws2812_spi.c

Enable the divisor to be changed on different platforms due to different clock sources.
Also enable circular buffer so that SCK and MISO do not need to be defined (issue on STM32L433).
Edit: Tested and working on L433 and F072
* Enable the divisor to be changed on different platforms.
* Enable optional circular buffer configuration

ARM WS2812 SPI config (baudrate and circular buffer)

---

keyboards/boston/info.json

Fixes an issue with the QMK Configurator data for the Boston keyboard that was causing two layouts to be presented even though there is only one layout in the code.
- correct macro reference
- add missing encoder position
- correct maintainer value to reference keyboard maintainer's GitHub account
- remove trailing whitespace
cc @bluepylons

Boston: correct LAYOUT macro data

---

lib/python/qmk/info.py

Some info.json files use alias names instead of the real layout name. This change correctly integrates the layout data when this happens.

Use layout aliases when processing info.json

---

quantum/led_matrix.c
quantum/led_matrix_types.h

LED Matrix: Fix up eeconfig code

---

keyboards/ploopyco/mouse/mouse.c
keyboards/ploopyco/trackball/trackball.c

This is a bugfix for Ploopy devices (trackball and mouse).
Ploopy devices use an optical encoder to produce scroll information. The `opt_encoder_handler` returns a value of `1`, `-1` or `0` depending on direction of scroll. This was being coerced into a `uint8_t`, discarding the sign. The problem was masked by the coercion happening when the value is put into the mouse descriptor's `int8_t`.
It's not clear to me why `process_wheel_user` uses `int16_t` for its `h` and `v` parameters, when the `mouse_report` values are only `int8_t`, and `dir` only takes values of `1`, `-1` and `0`. Perhaps `int8_t` is more appropriate for the `dir` variable? Maybe even `opt_encoder_handler`? I matched the `dir` type to the function which produces it, and changed nothing that didn't strictly need to change.

Preserve signedness from opt_encoder_handler for scroll data on Ploopy devices

---

quantum/matrix.h
quantum/split_common/matrix.c

This adds a keyboard level weak function to compliment the user level weak function for the split/slave matrix scan functions. I needed both keyboard and user level matrix scan functions on the save side for some keyboard functionality I am implementing. Additionally this adds proper declarations of these functions into the base matrix definition file guarded by `#ifdef SPLIT_KEYBOARD` so that these functions can correctly be chained and called. 
*

Better slave scan functions

---

tmk_core/common/arm_atsam/_print.h
tmk_core/common/avr/_print.h

Looks like i broke the logic during the tidy up within #11863.
`uprint`s need to resolve upfront, so that the later undefs do not become too aggressive in what they then touch.

Fix USER_PRINT on avr/atsam

---

quantum/process_keycode/process_midi.c

This change makes it so that MIDI note on messages are sent every time a MIDI key is pressed, but the MIDI note off message is only sent once all instances of the same MIDI note have been released. This issue would make it so that if you have a keymap with several MIDI chords, where the chords had overlapping notes, the common notes would be turned off once one chord was released even if another chord containing the same note is still being held. This PR fixes that.
* #10199

Fix handling multiples of the same MIDI note (fixes bug brought up in issue #10199)

---

keyboards/helix/pico/keymaps/mtei/keymap.c

Stopped using the LAYOUT_kc macro. (this is response to #12160)
There is no change in the generated binary.

[Keymap] Update keyboards/helix/pico/keymaps/mtei/keymap.c

---

keyboards/choco60/rev2/config.h

As described in [this documentation](https://docs.qmk.fm/#/config_options?id=other-options), the size of MATRIX_ROW_PINS and MATRIX_ROW_PINS_RIGHT must be the same.
> Currently, the size of MATRIX_ROW_PINS must be the same as MATRIX_ROW_PINS_RIGHT and likewise for the definition of columns.
This PR will fix the problem.
Related PR: #12111

Make the size of MATRIX_ROW_PINS and MATRIX_ROW_PINS_RIGHT the same

---

quantum/rgblight.c
quantum/rgblight.h

There is no change in compilation result binary.
* Befor:
```
% find quantum tmk_core keyboards -name '*.[ch]' | xargs grep RGBLED_TIMER_TOP
quantum/rgblight.c:    // OCR3AH = (RGBLED_TIMER_TOP >> 8) & 0xff;
quantum/rgblight.c:    // OCR3AL = RGBLED_TIMER_TOP & 0xff;
quantum/rgblight.h:#    define RGBLED_TIMER_TOP F_CPU / (256 * 64)
quantum/rgblight.h:// #define RGBLED_TIMER_TOP 0xFF10
keyboards/mxss/rgblight.c:    // OCR3AH = (RGBLED_TIMER_TOP >> 8) & 0xff;
keyboards/mxss/rgblight.c:    // OCR3AL = RGBLED_TIMER_TOP & 0xff;
```
* After
```
% find quantum tmk_core keyboards -name '*.[ch]' | xargs grep RGBLED_TIMER_TOP
keyboards/mxss/rgblight.c:    // OCR3AH = (RGBLED_TIMER_TOP >> 8) & 0xff;
keyboards/mxss/rgblight.c:    // OCR3AL = RGBLED_TIMER_TOP & 0xff;
```

Removed unused RGBLED_TIMER_TOP and F_CPU macros from quantum/rgblight.[ch]

---

keyboards/ploopyco/adns5050.c
keyboards/ploopyco/adns5050.h
keyboards/ploopyco/trackball_mini/config.h
keyboards/ploopyco/trackball_mini/info.json
keyboards/ploopyco/trackball_mini/keymaps/default/keymap.c
keyboards/ploopyco/trackball_mini/keymaps/default/readme.md
keyboards/ploopyco/trackball_mini/keymaps/drag_scroll/keymap.c
keyboards/ploopyco/trackball_mini/keymaps/drag_scroll/readme.md
keyboards/ploopyco/trackball_mini/keymaps/via/config.h
keyboards/ploopyco/trackball_mini/keymaps/via/keymap.c
keyboards/ploopyco/trackball_mini/keymaps/via/rules.mk
keyboards/ploopyco/trackball_mini/readme.md
keyboards/ploopyco/trackball_mini/rev1_001/config.h
keyboards/ploopyco/trackball_mini/rev1_001/readme.md
keyboards/ploopyco/trackball_mini/rev1_001/rev1_001.h
keyboards/ploopyco/trackball_mini/rules.mk
keyboards/ploopyco/trackball_mini/trackball_mini.c
keyboards/ploopyco/trackball_mini/trackball_mini.h
keyboards/ploopyco/trackball_nano/config.h
keyboards/ploopyco/trackball_nano/info.json
keyboards/ploopyco/trackball_nano/keymaps/default/keymap.c
keyboards/ploopyco/trackball_nano/keymaps/default/readme.md
keyboards/ploopyco/trackball_nano/readme.md
keyboards/ploopyco/trackball_nano/rev1_001/config.h
keyboards/ploopyco/trackball_nano/rev1_001/readme.md
keyboards/ploopyco/trackball_nano/rev1_001/rev1_001.h
keyboards/ploopyco/trackball_nano/rules.mk
keyboards/ploopyco/trackball_nano/trackball_nano.c
keyboards/ploopyco/trackball_nano/trackball_nano.h

Added a driver for the ADNS-5050 optical mouse sensor.
Added implementations for the Ploopy Nano and Ploopy Mini trackball.
*

ADNS-5050 / Ploopy Nano / Ploopy Mini Trackballs

---

quantum/mousekey.c

In `#define MK_COMBINED`, this compile error is shown:
```c
quantum/mousekey.c: In function 'move_unit':
quantum/mousekey.c:135:35: error: 'mouse_timer' undeclared (first use in this function)
135 |     } else if (mousekey_repeat && mouse_timer) {
|                                   ^~~~~~~~~~~
quantum/mousekey.c:135:35: note: each undeclared identifier is reported only once for each function it appears in
quantum/mousekey.c: At top level:
quantum/mousekey.c:149:7: error: conflicting types for 'mk_wheel_interval'
149 | float mk_wheel_interval = 1000.0f / MOUSEKEY_WHEEL_INITIAL_MOVEMENTS;
|       ^~~~~~~~~~~~~~~~~
quantum/mousekey.c:68:9: note: previous definition of 'mk_wheel_interval' was here
68 | uint8_t mk_wheel_interval    = MOUSEKEY_WHEEL_INTERVAL;
|         ^~~~~~~~~~~~~~~~~ …
```

Fix Kinetic speed condition

---

tmk_core/common/action_tapping.c

The logic for TAPPING_TERM_PER_KEY and PERMISSIVE_HOLD_PER_KEY has been updated to reflect the behavior as described in the document.
Issue [#10587](https://github.com/qmk/qmk_firmware/issues/10587):  When TAPPING_TERM_PER_KEY is defined and TAPPING_TERM is less than 500, permissive hold would not work/be active, regardless of whether PERMISSIVE_HOLD or PERMISSIVE_HOLD_PER_KEY is defined.  When both _PER_KEY macros are defined, we currently have:
`if ( (get_tapping_term(...) >= 500) && !get_permissive_hold(...) && ... ) { ... }`
If get_tapping_term() returns anything smaller than 500, the if-clause condition would be false regardless of get_permissive_hold, or the rest of the conditions.  This needs to be changed to:
`if (( (get_tapping_term(...) >= 500) || get_permissive_hold(...) ) && …

Fix Permissive Hold when TAPPING_TERM_PER_KEY is defined

---

quantum/process_keycode/process_auto_shift.c

Specifically, when using the Auto-Shift feature, if you hold and roll shift, it would not actually shift the character that you hit after the shift.
* Reported from ZSA

Fix issues when manually shifting characters and Auto Shift

---

drivers/oled/oled_driver.c
tmk_core/common/keyboard.c

Now in split keyboards it is impossble to use I2C OLED display and I2C for communication beetween halves.
This described in #9335
PR disables calls to OLED display from slave half in case I2C used for OLED display and for communication beetwen halves. This restores normal communication between halves.
PR addresses the case when only one OLED display is used in split keyboard. When using two OLED displays on both halves of keyboard it is impossible to use I2C. Serial commmunication between halves should be used.
* Fixes #9335

Fix connection issue in split keyboards when slave and OLED display are connected via I2C, fix #9335

---

keyboards/redox/keymaps/finex/keymap.c

The Colemak base mod is named after swapping D and H from next to the base row.
N/A
N/A

Minor typo in comments Colemak DM-MK -> DH-MK

---

keyboards/handwired/rs60/keymaps/default/keymap.c
keyboards/handwired/rs60/rs60.h

This PR renames the macro LAYOUT to LAYOUT_ortho_5x12, and removes the alias.
cc: @rs (keyboard maintainer)

handwired/rs60: use LAYOUT_ortho_5x12 directly

---

quantum/quantum_keycodes.h

Hoo boy.
* Moved Swap Hands range to 0x5600, just to fill in that gap
* Pulled range aliases (MIDI velocity min/max etc.) out of the enum and into defines at the end of the file
* Annotated every keycode with its value in hex, up to the Sequencer keycodes - they still have yet to be made static, but at least they're at the end, for now
* Removed *all* the ifdefs! And via_ensure_keycode.h doesn't complain! This does mean that everything guarded by an ifdef had to be moved to the end of the enum, though
* Tweaked/added/improved some comments
As mentioned, this doesn't break VIA, but it does shuffle some values around, so perhaps this should go into develop instead?
*

Big quantum_keycodes cleanup

---

keyboards/keebio/levinson/keymaps/jyh/keymap.c

Converts kc macros to normal layout macros in the levinson:jyh keymap, as per deprecation of the KC macros in #12160.
* addresses #12160

remove kc layout from levinson jyh keymap

---

keyboards/kinesis/keymaps/default/keymap.c
keyboards/kinesis/keymaps/default_pretty/keymap.c
keyboards/kinesis/keymaps/dvorak/keymap.c

The right-most top-most key on the Kinesis Advantage keyboard is labeled
“Progrm” and was meant to enter the Teensy bootloader as per the comment.
However, the keycode was set to KC_1, which just produces a “1”.
It should be RESET instead.
This commit fixes KC_1 to RESET in all files where the fix is needed.
The other files have already been fixed independently.

keymaps: fix kinesis default keymap progrm/reset keycode

---

keyboards/kingly_keys/ave/config.h
keyboards/kingly_keys/ave/ortho/keymaps/default/config.h
keyboards/kingly_keys/ave/staggered/keymaps/default/config.h

QMK Configurator's API can't use the RGBLight configurator when it's defined at keymap level.
cc @The-Royal (keyboard maintainer)

Fix QMK Configurator compilation for Kingly Keys Ave

---

requirements-dev.txt

The PyPI `wave` package resolves to <https://pypi.org/project/Wave/>, but the places where it is imported make it clear that the standard library module <https://docs.python.org/3/library/wave.html> was intended instead.
Was originally added in #11820 and used in the following files:
* [`util/sample_parser.py`](https://github.com/qmk/qmk_firmware/blob/master/util/sample_parser.py#L19)
* [`util/wavetable_parser.py`](https://github.com/qmk/qmk_firmware/blob/master/util/wavetable_parser.py#L19)
* None

Remove `wave` from requirements-dev.txt

---

tmk_core/avr.mk

None of the other flashers currently spit out any WSL specific errors, so ive not kept that logic for avrdude.

Add WSL specific logic for avrdude device detection

---

keyboards/helix/rev2/keymaps/five_rows/config.h
keyboards/helix/rev2/keymaps/five_rows/keymap.c
keyboards/helix/rev2/keymaps/five_rows/rules.mk
keyboards/helix/rev3_5rows/keymaps/five_rows/config.h
keyboards/helix/rev3_5rows/keymaps/five_rows/keymap.c
keyboards/helix/rev3_5rows/keymaps/five_rows/oled_display.c

* Made the layout data easier to read.
* helix/rev2/keymaps/five_rows/keymap.c
* helix/rev3_5rows/keymaps/five_rows/keymap.c
* fix some comments
* The following two were made the same.
* keymaps/five_rows/config.h
* keymaps/five_rows/oled_display.c
The binary of the compilation result has not changed.

[Keymap] cleanup keyboards/helix/{rev2|rev3_5rows}/keymaps/five_rows

---

keyboards/kbdfans/bella/rgb/rules.mk
keyboards/kbdfans/bella/rgb_iso/rules.mk
keyboards/mt64rgb/rules.mk

Fixes up some builds on `develop` which became too big to build.

Fix up builds that are now too big for `develop` branch.

---

common_features.mk
quantum/led_matrix.c
quantum/led_matrix.h

Brightness changes are much nicer on the eyes now. Also tidying up a few other things in preparation for adding animations and updating the suspend- and split-related code.
*

LED Matrix: Implement CIE1931 curve

---

lib/python/qmk/cli/chibios/confmigrate.py

This command stacktraces without both of these.
*

`qmk chibios-confmigrate`: Make `-i` and `-r` required

---

keyboards/iron180/iron180.h
keyboards/iron180/mcuconf.h

Reverse K0E and K0G in Iron180: due to better tracing the switches were swapped. Matrix topology stays the same
*

Reverse K0E and K0G in Iron180

---

tmk_core/protocol/chibios/usb_driver.c

Before this commit, attaching an ARM-based (i.e. ChibiOS-based) keyboard that
uses CONSOLE_ENABLE = yes and produces debug messages would deadlock the
keyboard unless one was running hid_listen.
With this commit, dead-locking writes to the queue are detected and prevented.
fixes #5631
* #5631

ChibiOS USB driver: prevent deadlock with CONSOLE_ENABLE = yes

---

quantum/led_matrix.c
quantum/led_matrix.h
tmk_core/common/avr/suspend.c
tmk_core/common/chibios/suspend.c
tmk_core/common/keyboard.c

Still not doing a whole lot yet, but getting closer to actually adding some effects.
*

LED Matrix: suspend code

---

docs/feature_led_matrix.md
docs/ja/feature_led_matrix.md
keyboards/terrazzo/terrazzo.c
keyboards/terrazzo/terrazzo_effects/dino.h
keyboards/terrazzo/terrazzo_effects/dot.h
keyboards/terrazzo/terrazzo_effects/heart.h
keyboards/terrazzo/terrazzo_effects/outrun.h
keyboards/terrazzo/terrazzo_effects/pac_dude.h
keyboards/terrazzo/terrazzo_effects/wpm_chart.h

Didn't realise these were referenced elsewhere...
*

Terrazzo: Fix wrong LED Matrix function names

---

keyboards/cannonkeys/ortho75/info.json

`info.json` is referencing an incorrect layout macro name.
cc @awkannan (keyboard maintainer)
* https://github.com/qmk/qmk_configurator/issues/907

Correct layout macro name in Cannonkeys Ortho75 info.json

---

docs/_summary.md
docs/cli_tab_complete.md
lib/python/qmk/cli/__init__.py
lib/python/qmk/cli/c2json.py
lib/python/qmk/cli/cformat.py
lib/python/qmk/cli/compile.py
lib/python/qmk/cli/flash.py
lib/python/qmk/cli/generate/config_h.py
lib/python/qmk/cli/generate/dfu_header.py
lib/python/qmk/cli/generate/info_json.py
lib/python/qmk/cli/generate/layouts.py
lib/python/qmk/cli/generate/rules_mk.py
lib/python/qmk/cli/info.py
lib/python/qmk/cli/json2c.py
lib/python/qmk/cli/kle2json.py
lib/python/qmk/cli/lint.py
lib/python/qmk/cli/list/keymaps.py
lib/python/qmk/cli/new/keymap.py
lib/python/qmk/decorators.py
lib/python/qmk/keyboard.py
lib/python/qmk/keymap.py
requirements.txt
util/qmk_tab_complete.sh

First pass at support for tab completion. This supports completing the flags themselves and in many cases the arguments to the flags. Working at this time are keyboards, keymaps, and files.
To use this you need to source `util/qmk_tab_complete.sh`. Package maintainers can place this file into appropriate locations like `/etc/profile.d`.
**Note**: Bash users will need to be using version 4.2 or later.

Add support for tab completion

---

quantum/led_matrix.c
quantum/led_matrix.h
quantum/led_matrix_types.h

LED Matrix: Task system

---

keyboards/wilba_tech/wt60_xt/wt60_xt.c

`is_playing_notes()` was broken recently, now always returns true. Probably not needed anymore, so took it out here.
*

Fix audio on WT60-XT

---

docs/feature_rgblight.md
quantum/process_keycode/process_rgb.c
quantum/quantum_keycodes.h

When the Twinkle effect was implemented, keycodes were not created to select it.
This adds them.

Add missing RGB_MODE_TWINKLE / RGB_M_TW keycodes

---

keyboards/ergodox_ez/util/keymap_beautifier/KeymapBeautifier.py

The beautifier script did not handle cases like` LALT(LGUI(KC_D))` correctly, only parsing the first command, and thus rendering this case as `LALT()` in the beautified version. This is easily solved by recursively parsing the function call.
* 
- [-] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [-] My change requires a change to the documentation.
- [-] I have updated the documentation accordingly.
- [-] I have added tests to cover my changes.

Bug in beautifier script, compound modifiers not correctly parsed

---

keyboards/keyboardio/atreus/keymaps/ardumont/keymap.c
keyboards/keyboardio/atreus/keymaps/ardumont/readme.md

This adds a qwerty layout variant for the keyboardio atreus keyboard. Mostly for
symmetric use of hands.
This is a qwerty layout for the keyboardio/atreus. For the most part, it's a
straightforward layout. Only the modifiers key are not organized like the default
layout. Those modifier keys are mostly symmetrically configured.
The idea is that when using a modifier key, some users may expect to use both side of
the keyboard symmetrically (as in emacs, qutebrowser, terminal/tmux).
Exceptions to the rules are the `Escape` and the `Super` which only exists on the left
Side of the keyboard. Those are mostly unused.
Note that some keys are not present in the keyboard (e.g `Tab`, `Enter`, ...) since they
are available from the legacy terminal bindings:
- Ctrl-i: Tab
- Ctrl-m: Enter
- Ctrl-h: …

keyboardio/atreus: Add new keymap 'ardumont'

---

keyboards/amag23/amag23.c
keyboards/amag23/amag23.h
keyboards/amag23/config.h
keyboards/amag23/info.json
keyboards/amag23/keymaps/default/keymap.c
keyboards/amag23/keymaps/default/readme.md
keyboards/amag23/keymaps/qwert/keymap.c
keyboards/amag23/keymaps/qwert/readme.md
keyboards/amag23/readme.md
keyboards/amag23/rules.mk

Adds Koolertron AMAG23 - 23 Key market available macro pad, with RGB.
*

Add Koolertron AMAG23 Keyboard

---

keyboards/playkbtw/helen80/helen80.h
keyboards/playkbtw/helen80/rules.mk

old `keyboards/playkbtw/helen80/helen80.h` matrix have wrong column
for `Backspace`, causing the key to serve no function; it should have
same column as `Scroll Lock`, in standard ANSI layout terms.
- The original `helen80.h` missed a `KC_NO` in the macro function `LAYOUT_tkl_ansi`, which makes `Backspace` serve no function.
- This can be verified, if VIA enabled, that the keymap is blank on which should be `Backspace` on standard ANSI boards.
- By inspecting the board matrix, either by [PCB photos in the flickr album](https://www.flickr.com/photos/149475414@N03/albums/72157716825609963?fbclid=IwAR1Nct4xqLfo45-XUijTJGaijBjZXybpJuyntsISmfVRD4wPjSwnNvnEaXU/with/50586384146) of `Helen80`, by the `config.h`, or by `VIA`, we can see that, in standard ANSI layout terms, the keys `Backspace` and …

Helen80 matrix fixes

---

docs/feature_wpm.md
quantum/wpm.c
quantum/wpm.h

Enhancement of WPM feature

---

quantum/audio/driver_chibios_dac_basic.c

The `dac_basic` audio driver did not work properly with `#define AUDIO_PIN A4` (instead of configuring the **A4** pin, the driver actually was switching the **A5** pin to analog mode, breaking any other usage of that pin in addition to emitting a distorted signal on the improperly configured **A4** pin).  Fix the code to configure the **A4** pin as intended.
Tested on STM32F303CCT6. Without the fix an attempt to enable audio with `#define AUDIO_PIN A4` also broke the basic keyboard functionality with `#define MATRIX_COL_PINS { A5 }` (the column pin was always seen as active); after applying the fix the **A5** pin started working in the matrix again.
* No Github issue; the problem was reported by `@GKD#3464` in the QMK Discord.

Fix F303 audio output on A4 with the dac_basic driver

---

users/rverst/rverst.c

- keys were not unregistered properly

Fix handling of RV_LOCK and RV_SNAP for windows

---

keyboards/jkdlab/binary_monkey/binary_monkey.c
keyboards/jkdlab/binary_monkey/binary_monkey.h
keyboards/jkdlab/binary_monkey/config.h
keyboards/jkdlab/binary_monkey/info.json
keyboards/jkdlab/binary_monkey/keymaps/ascii/keymap.c
keyboards/jkdlab/binary_monkey/keymaps/default/keymap.c
keyboards/jkdlab/binary_monkey/readme.md
keyboards/jkdlab/binary_monkey/rules.mk

Hi! We made 3-Key macropad keyboard inspired by monkey!
It keyboard consists of 1, 0 and Enter Keys.
And We also made funny keymap called Ascii keymap. If press 0 and 1, it will record by binary and press enter it represent to ascii code.
This keyboard 3-Key (1x3 matrix) macropad.
*

Added keyboard jkdlab/binary_monkey

---

docs/feature_auto_shift.md
quantum/process_keycode/process_auto_shift.c
quantum/process_keycode/process_auto_shift.h

This adds a "per key" function for checking if a key should be auto-shifted or not. 
* Closes #11533

Add Per Key functionality for AutoShift

---

quantum/led_matrix.c
quantum/led_matrix.h

Last thing to do before I can actually add some effects! 😄
*

LED Matrix: Reactive effect buffers & advanced indicators

---

keyboards/millipad/config.h
keyboards/millipad/info.json
keyboards/millipad/keymaps/default/keymap.c
keyboards/millipad/keymaps/default/readme.md
keyboards/millipad/millipad.c
keyboards/millipad/millipad.h
keyboards/millipad/readme.md
keyboards/millipad/rules.mk

Added qmk support for my custom keypad "millipad". This keypad is open source and is available on my github. There is a private group buy going on between my friends and I, but it is still open source.
- [ x ] Keyboard (addition or update)
- [ x ] Keymap/layout/userspace (addition or update)
* 
- [ x ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ x ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ x ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).

Add millipad keypad and default keymap

---

keyboards/arch_36/config.h

Just a missing declaration as this keyboard was designed to use the 128x64 OLED displays.
*

Set OLED_DISPLAY_128X64 for Arch-36

---

keyboards/kinesis/kint36/rules.mk

This change shaves off ≈5ms of input latency by switching to eager debouncing.
Before:
```
% benchstat screenlog-kint36.0
name                 time/op
KeypressToLEDReport  7.61ms ± 8%
```
After:
```
% benchstat screenlog-kint36-eager.0
name                 time/op
KeypressToLEDReport  2.12ms ±16%
```

kint36: switch to sym_eager_pk debouncing

---

keyboards/kinesis/kint2pp/config.h
keyboards/kinesis/kint2pp/rules.mk

See the two individual commits and the added comments for details. In summary, increasing the USB polling interval from the overly-conservative 10ms USB 1.1 default to 1ms (USB 1.1 minimum) and switching to an eager debounce algorithm brings down the input latency significantly.
Before, I measured values above 10ms. With these changes, I measure an input latency of 3.27ms ±32%.
(Will publish more details on the test method in an upcoming blog post.)

kint2pp: reduce input latency by ≈10ms

---

keyboards/handwired/lagrange/transport.c

This PR contains two commits for the Lagrange handwired keyboard.
The first fixes the transport in view of the changes introduced by the `SPLIT_TRANSPORT_MIRROR` feature, which changed the arguments of the transport functions (and which went undetected due to an oversight on my part, in not including `"transport.h"`).
The second improves error checking during the transport, to avoid spurious keypresses, when disconnecting and reconnecting the transport cable (or, presumably, during transmission errors, although I haven't had any yet).

[Keyboard]  Fix and improve SPI transport in the Lagrange

---

keyboards/infinity60/config.h
keyboards/infinity60/led/config.h
keyboards/infinity60/led/readme.md
keyboards/infinity60/led/rules.mk
keyboards/infinity60/rev1/config.h
keyboards/infinity60/rev1/readme.md
keyboards/infinity60/rules.mk

Added support for the differently pinned no led version of infinity 60
The initial code for the infinity60 was a bit rough, and a nice refactor was done to make it all QMKy and easy to maintain.
This however also removed support for the older boards without LEDs which have a different column pinout, as these older boards were simply called "prototypes" in the old implementation.
They were in fact not prototypes, but the first drops on massdrop of the board.
I've broken the pin definitions out into revision sub-folders, and set the led folder to be the default :)

Added support for the older no_led revision infinity60

---

tmk_core/common/chibios/eeprom_teensy.c

```console
make clean handwired/onekey/teensy_lc:default
QMK Firmware 0.12.34
Making handwired/onekey/teensy_lc with keymap default
arm-none-eabi-gcc (Arch Repository) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
Compiling: keyboards/handwired/onekey/keymaps/default/keymap.c                                     Compiling: quantum/send_string.c                                                                   Compiling: keyboards/handwired/onekey/onekey.c                                                     Compiling: quantum/quantum.c …
```

Fix for gcc10 teensy_lc eeprom build warning

---

keyboards/anavi/macropad8/keymaps/git/config.h
keyboards/anavi/macropad8/keymaps/git/keymap.c

Git keymap for ANAVI Macro Pad 8 with the following shortcuts.
On the first row from left to right:
- git status
- git log
- git pull
- git push
On the second row from left to right:
- git diff
- git add
- git commit
- FN key to switch to the 2nd layout and control lights
Reduce the number of supported RGB animations and effects in
config.h to shrink the firmware size and fit it on the device.
Add new Git keymap for ANAVI Macro Pad 8 with the following shortcuts. On the first row from left to right:
- git status
- git log
- git pull
- git push
On the second row from left to right:
- git diff
- git add
- git commit
- FN key to switch to the 2nd layout and control lights
*

[Keymap] Add Git keymap for ANAVI Macro Pad 8

---

lib/python/qmk/keyboard.py

CLI's resolving of `config.h` and `rules.mk` files was following `DEFAULT_FOLDER` unconditionally, and in cases where a keyboard was not the default, parsed and generated data came from the default instead, even if fully qualified.
This fixes the logic to resolve the resulting keyboard based on `DEFAULT_FOLDER` first, then performing full parsing based off the final keyboard path.

Fix CLI incorrectly following `DEFAULT_FOLDER`

---

tmk_core/protocol/chibios/usb_driver.c
tmk_core/protocol/chibios/usb_main.c
tmk_core/protocol/lufa/lufa.c

This commit reverts PR https://github.com/qmk/qmk_firmware/pull/12472 (commit c823fe2d3f23ed090e36ce39beed4c448298bd2f),
and it implements the original intent of the commit in a better way.
The original intent of the above mentioned commit was to not deadlock the
keyboard when console is enabled, and hid_listen is not started.
The above mentioned commit had a few drawbacks:
1) When a lot of data was printed to the console, the queue would get full,
and drop data, even if hid_listen was running. (For example having matrix debug
enabled just didn't work right at all)
2) I believe the function in which this was implemented is used by all other
USB endpoints, so with the above change, overflow, and data loss could
happen in other important functions of QMK as well.
This commit implements …

Fix how USB queue overflow is handled in chibios.

---

bootloader.mk
data/schemas/keyboard.jsonschema
docs/flashing.md
keyboards/handwired/onekey/blackpill_f411_tinyuf2/chconf.h
keyboards/handwired/onekey/blackpill_f411_tinyuf2/config.h
keyboards/handwired/onekey/blackpill_f411_tinyuf2/halconf.h
keyboards/handwired/onekey/blackpill_f411_tinyuf2/mcuconf.h
keyboards/handwired/onekey/blackpill_f411_tinyuf2/readme.md
keyboards/handwired/onekey/blackpill_f411_tinyuf2/rules.mk
platforms/chibios/BLACKPILL_STM32_F411/ld/STM32F411xC_tinyuf2.ld
platforms/chibios/BLACKPILL_STM32_F411/ld/STM32F411xE_tinyuf2.ld
quantum/mcu_selection.mk
tmk_core/chibios.mk
tmk_core/common/chibios/bootloader.c

Building UF2-formatted binaries already exists in QMK, but there's no example project to point people towards, nor is there support for jumping to one of the more well-known bootloaders -- Adafruit's tinyuf2.
The tinyuf2 bootloader can be downloaded from the [tinyuf2 releases page](https://github.com/adafruit/tinyuf2/releases). The F401 blackpill binary works for both F401- and F411-based blackpill devices.
This PR subsequently adds support for F411 blackpills to target the tinyuf2 bootloader, by providing appropriate ldscript files as well as adding support for jumping to bootloader.

Add initial support for tinyuf2 bootloader (when hosted on F411 blackpill)

---

quantum/process_keycode/process_tap_dance.c

Tap dance callbacks may register weak mods; one case when it happens is when a tap dance registers a key with modifiers.  When the tap dance is interrupted by pressing another key, these weak mods could affect the interrupting key (normally any stale weak mods are cleared at the start of `action_exec()` when handling a keypress event, but the  tap dance interrupt check code is called later, and the weak mods left by that code were not cleared).  Add another `clear_weak_mods()` call to `preprocess_tap_dance()` to make sure that the interrupting keypress is not affected by unrelated weak mods from the previous tap dance.
One example of a tap dance which exhibits the problem and can be used with the US QWERTY layout (unlike the example from #12445, which assumes the US International layout): …

Do not leak weak mods from tap dance to the interrupting keypress

---

users/ninjonas/oled.c

changed is_master to is_keyboard_master()
Tried to compile+flash and didn't work, referenced default template to fix this on my board
*

Update checking board master function

---

data/schemas/keyboard.jsonschema
docs/compatible_microcontrollers.md
docs/ja/compatible_microcontrollers.md
lib/python/qmk/constants.py
platforms/chibios/GENERIC_STM32_F446XE/board/board.mk
platforms/chibios/GENERIC_STM32_F446XE/configs/board.h
platforms/chibios/GENERIC_STM32_F446XE/configs/config.h
platforms/chibios/GENERIC_STM32_F446XE/configs/mcuconf.h
quantum/mcu_selection.mk

By default it assumes an external crystal at 16MHz
I have tested this with with a controller board I'm working on, for Unicomp and 4th gen IBM Model M keyboards. (see here: https://imgur.com/a/ViLq301 )
A separate PR will be incoming with support for some specific keyboards, once some minor issues will be solved.

Add support for MCU = STM32F446

---

keyboards/gmmk/pro/config.h
keyboards/gmmk/pro/keymaps/via/keymap.c
keyboards/gmmk/pro/keymaps/via/rules.mk
keyboards/gmmk/pro/keymaps/wholesomeducky/keymap.c
keyboards/gmmk/pro/pro.h

Inside pro.h, the keys that are normally "RAlt" and "Fn" were swapped, causing confusion in making keymaps, since Fn needed to be left of RAlt in the keymap when the physical key is to the right.
My personal keymap is also included, which I adjusted alongside my fix for these two keys being swapped.
Default keymap is already correct and does not need to be changed for this (although RGUI is used instead of Fn. Maybe good use of Fn couldn't be made here?)
Added VIA support. JSON made by me is being submitted to VIA repo.
config.h has been changed to have bootmagic row/column defined for this board to use Esc instead of LShift for Bootmagic.
Firmwares in question have been compiled and flashed to my board with my keymap & tested.
First PR, always open to feedback on how to do things better. …

GMMK Pro: Fixed Bootmagic Lite support; added personal keymap and VIA support

---

keyboards/mechlovin/infinity87/rev1/rules.mk

Fix default folder of Mechlovin Infinity87 Rev1 to point to the standard otherwise it errors out and attempts to build the keyboard alone without any other #define's that are in standard/rogue/rouge versions.
https://github.com/Xelus22/QMK-VIA-Hex/runs/2443537176?check_suite_focus=true
* Fix default folder of Mechlovin Infinity87 Rev1 to point to the standard otherwise it errors out.

[Bug Fix] Mechlovin Infinity87 Rev1 - fix default folder

---

keyboards/m3n3van/keymaps/default/keymap.json

Build failures. @matthewdias confirm fix please?

Fix up bad keycode in #12405

---

docs/feature_rgb_matrix.md
keyboards/mt64rgb/keymaps/default/keymap.c
keyboards/mt84/keymaps/default/keymap.c
quantum/led_matrix.c
quantum/led_matrix.h
quantum/rgb_matrix.c
quantum/rgb_matrix.h
tmk_core/common/avr/suspend.c
tmk_core/common/chibios/suspend.c

Like the title says. 
But more specifically, instead of using a bool for the define, it changes it to be a simple define. If present, then enables the functionality, if not defined, then it stays running when USB suspends. 
Also makes the g_suspend_state variable static to not conflict between rgb matrix and led matrix.
And adds a check to make sure it's properly handled. 
Does not touch existing keyboards, just changes how the define works.

Change RGB/LED Matrix to use a simple define for USB suspend

---

keyboards/wilba_tech/wt75_b/config.h
keyboards/wilba_tech/wt75_c/config.h

The code for handling the RGB indicator on WT75-A was being enabled for WT75-B and WT75-C which doesn't have an RGB indicator, causing the F13 LED to always be lit.
*

Fix F13 LED issue for WT75-B, WT75-C

---

keyboards/meishi2/rules.mk

This fix enables flash command like `qmk flash -kb meishi2 -km default` .

[Keyboard] Fix bootloader rule for meishi2 keyboard

---

quantum/split_common/transport.c

https://github.com/qmk/qmk_firmware/pull/12697 Transport logic was never updated in the previous pr and was missed during review.
*

Fix transport suspend state

---

docs/cli_commands.md
lib/python/qmk/cli/new/__init__.py
lib/python/qmk/cli/new/keyboard.py

Short term, pulling out a small portion of the changes from #12031.
*

Shim cli to new keyboard script

---

keyboards/coseyfannitutti/discipline/keymaps/noroadsleft/keymap.c
keyboards/kbdfans/kbd75/keymaps/noroadsleft/keymap.c
keyboards/kc60/keymaps/noroadsleft/keymap.c
keyboards/kc60/keymaps/noroadsleft/readme.md
users/noroadsleft/readme.md

Have simplified my keymaps by deciding to run Dvorak as my Layer 0 on my boards, instead of having a mixed setup running Dvorak in the OS on my own systems and running it on the keyboard as Layer 1 everywhere else.

Update noroadsleft userspace and keymaps (2021-05-03)

---

tmk_core/avr.mk

When the USB device is connected, FreeBSD creates not one, but three
device nodes in /dev, e.g.: /dev/ttyU0, /dev/ttyU0.init, and
/dev/ttyU0.lock.
As a result, this leads to the USB variable containing 3 paths
(and therefore, whitespace) and messages like this one:
Device /dev/ttyU0
/dev/ttyU0.init
/dev/ttyU0.lock has appeared; assuming it is the controller.
This changes fixes the use of the -z flag of "[" (see test(1)). Also, it
removes undesired paths from the USB variable, (hopefully) leaving only
one path there (e.g., "/dev/ttyU0").

Fix qmk flash on FreeBSD

---

docs/feature_oled_driver.md
drivers/oled/oled_driver.c
drivers/oled/oled_driver.h

Instead of turning off instantly, the screen gradually fades to black.
See issue #11433.

Added OLED fade out support

---

build_keyboard.mk
keyboards/bm43a/keymaps/stevexyz/readme.md
message.mk

Fix some references to bin/qmk that slipped in

---

drivers/haptic/haptic.h

Title says it almost all.
Sum of size of bitfields was 34 before, which is larger than the raw value.
The last bitfield is reserved, so its size clearly wasn't updated only by accident.
**NOT TESTED**
* 
**NOT TESTED**

haptic: correct size of reserved field in the haptic structure. This saves 1 byte of wasted SRAM.

---

.github/workflows/cli.yml
bin/qmk
docs/cli_commands.md
lib/python/qmk/cli/__init__.py
lib/python/qmk/cli/console.py
requirements-dev.txt
requirements.txt
util/install/arch.sh
util/install/debian.sh
util/install/fedora.sh
util/install/gentoo.sh
util/install/msys2.sh
util/udev/50-qmk.rules

This adds a `qmk console` command. The initial work was done by @zvecr to connect to a single keyboard, I expanded it out to connect to all (or one) keyboard. It also shows the connected bootloaders, much in the same way QMK Toolbox does.

New command: qmk console

---

lib/python/qmk/cli/clean.py
lib/python/qmk/commands.py

Due to the way the path is available within WSL and MSYS2, there can be scenarios where `gmake` is incorrectly picked up.
The `MAKE` environment override works for compile/flash, but not for clean due to using its own implementation of the logic.

Allow MAKE environment override for 'qmk clean'

---

lib/python/qmk/cli/__init__.py
lib/python/qmk/cli/buildall.py
lib/python/qmk/cli/info.py
lib/python/qmk/cli/multibuild.py

Adds a helper script that performs all builds in a parallel fashion, instead of serially.

Add script to perform parallel builds.

---

lib/python/qmk/commands.py

It's possible that the `$SHELL` env var is not set in MSYS so instead of erroring out, fall back to BASH.
*

CLI: Use BASH if SHELL variable is not set (Windows)

---

tmk_core/avr.mk

Another reference to `bin/qmk` was hiding in the code for building `qmk-dfu`. With Nix shell updates from #12855 this reference was causing a build failure if a command like this was used:
```sh
qmk flash -kb preonic/rev2 -km default -bl production
```
(and commands like `make preonic/rev2:default:production` or `./bin/qmk flash -kb preonic/rev2 -km default -bl production` still worked, but printed a deprecation warning).

Fix another `bin/qmk` reference

---

quantum/dynamic_keymap.c

This correctly sets the EEPROM for the AT90USB128x MCUs, as well as adds support for the ATmega16u# MCU's, and ATtiny85.
* Sizes incorrectly set.

Add EEPROM defaults for Dynamic Keymaps

---

keyboards/crkbd/keymaps/soundmonster/keymap.c

crkbd soundmonster uses a timeout to turn off the OLED screen.
If the computer suspends, the microcontroller goes into power saving mode. This stops the timer (I think).
So the OLED never turns off when the computer is suspended.
Explicitly turning it off on suspend fixes this.
add `suspend_power_down_user` to turn off OLED on power down.

Turn OLED off on suspend in soundmonster keymap

---

lib/python/qmk/cli/__init__.py

Add setup, clone, and env to the list of commands we allow even when modules are broken.

Add setup, clone, and env to the list of commands we allow

---

quantum/led_matrix.c
quantum/led_matrix_types.h
quantum/rgb_matrix.c
quantum/rgb_matrix_types.h

Split out from #9657, this is needed to avoid conflicts with uGFX's own `point_t` type, while we still have it.
*

Rename `point_t` -> `led_point_t`

---

keyboards/coarse/cordillera/config.h

Sets the `LED_PIN_ON_STATE` config to `0` for `coarse/cordillera`
*

Fix Cordillera LED states config

---

keyboards/boardsource/the_mark/config.h
keyboards/boardsource/the_mark/the_mark.c

Minor updates to The Mark 65:
- Allow user override of the `RGB_DISABLE_WHEN_USB_SUSPENDED` setting, based on suggestion in #12290
- Update edge LED position for `g_led_config`

USB suspend option and LED position change for The Mark 65

---

tmk_core/common/avr/suspend.c
tmk_core/common/chibios/suspend.c

Realized that I never added the suspend function calls for LED Matrix.  Whoops.

Add missing LED Matrix suspend code to suspend.c

---

keyboards/redox/keymaps/jeherve/config.h
keyboards/redox/keymaps/jeherve/keymap.c
keyboards/redox/keymaps/jeherve/readme.md

This PR makes some changes to a personal keymap for the Redox keyboard. It doesn't bring any new features, but fixes a small bug and removes code that is now deprecated.
- Replace `UC_OSX` (deprecated) by `UC_MAC` -- [Reference](https://beta.docs.qmk.fm/using-qmk/software-features/feature_unicode)
- Set unicode for mac input mode in config -- [Reference](https://beta.docs.qmk.fm/using-qmk/software-features/feature_unicode#3-setting-the-input-mode-id-setting-the-input-mode)
- Update indentation (spaces instead of tabs everywhere)
- Switch to using unicode for non breaking spaces. I used the HTML code before, and it's not perfect for every use-case.
- Fix audio mode (I had started setting this up before but never completed it).
- Replace use of deprecated `send_unicode_hex_string()` (see …

Redox custom keymap (jeherve): updates to deprecated code and bugfixes

---

keyboards/anavi/macropad2/keymaps/msteams/keymap.c
keyboards/anavi/macropad2/keymaps/msteams/rules.mk

This keymap contains the following shortcuts for Microsoft Teams
on MS Windows and GNU/Linux distributions:
- Ctrl+Shift+M: Toggle mute
- Ctrl+Shift+O: Toggle video (doesn't work in a web browser)
NOTE: Mac users should replace Ctrl with Command in all shortcuts
This keymap contains the following shortcuts for Microsoft Teams
on MS Windows and GNU/Linux distributions:
- Ctrl+Shift+M: Toggle mute
- Ctrl+Shift+O: Toggle video (doesn't work in a web browser)
NOTE: Mac users should replace Ctrl with Command in all shortcuts
*

[Keymap] ANAVI Macro Pad 2 add MS Teams keymap

---

docs/feature_unicode.md
keyboards/1upkeyboards/sweet16/keymaps/ridingintraffic/keymap.c
keyboards/handwired/2x5keypad/keymaps/default_tapdance/keymap.c
keyboards/mechmini/v2/keymaps/wsturgiss/keymap.c
keyboards/spaceman/2_milk/keymaps/emoji/keymap.c
keyboards/yatara/drink_me/keymaps/queen/keymap.c
users/arkag/arkag.c
users/curry/process_records.c
users/d4mation/macros.c
users/kuchosauronad0/process_records.c
users/kuchosauronad0/unicode.h
users/ridingqwerty/process_records.c
users/yet-another-developer/process_records.c
users/yet-another-developer/unicode.h

There is not much use for this function anymore, now that you can pass Unicode strings directly to `send_unicode_string()`. I've gone ahead and migrated the existing usages.
@arkag
@Curry
~~@d4mation~~
~~@jeherve~~
@kuchosauronad0
@ridingintraffic
@ridingqwerty 
@wsturgiss
@yet-another-developer
~~@josjoha your Minivan keymap has not been migrated, as its usage is a bit more complex. Would it be possible to switch to `register_unicode()` instead?~~
*

Deprecate `send_unicode_hex_string()`

---

quantum/split_common/transport.c

A mistake (one missed 'e') in #12633 caused a compilation error in split_common/transport.c

Fix spelling mistake regarding LED Matrix in split_common.

---

keyboards/handwired/bolek/config.h

Bolek is a 36% keyboard. Basically unusable without those.

[handwired/bolek] Add PERMISSIVE_HOLD and IGNORE_MOD_TAP_INTERRUPT

---

keyboards/kinesis/kint36/keymaps/kzar/keymap.c

The kzar keymap for the Kinesis keyboard output's the keyboard's status when the STATUS key is pressed. Unfortunately there is a bug whereby the status output declares the current layout to be DVORAK instead of QWERTY. 
* https://github.com/kinx-project/kint/issues/28

[Keymap] Fix DVORAK/QWERTY status output for kzar keymap

---

docs/feature_rgblight.md
quantum/rgblight.c
quantum/rgblight.h

Added the functions `rgblight_blink_layer_repeat` and `rgblight_blink_layer_repeat_helper`. When `rgblight_blink_layer_repeat` is called, it stores the number of repeats in a counter which is decremented every time a layer is turned on again. `rgblight_blink_layer_repeat_helper` is called after `rgblight_unblink_layers` to check if a lighting layer needs to be enabled again. Both functions call `rgblight_blink_layer` to turn on a layer.

Add function to allow repeated blinking of one layer

---

.github/workflows/format.yaml
lib/python/qmk/cli/cformat.py

The 'cformat' subcommand should only run on "core" files when executed by the CI.
CI now should use the new `--core-only` argument.
*

Make sure 'cformat' only runs on core files

---

quantum/matrix.c
quantum/split_common/matrix.c

I noticed this discrepancy (last row of the matrix treated differently than the
others) when optimizing the input latency of my keyboard controller, see also
https://michael.stapelberg.ch/posts/2021-05-08-keyboard-input-latency-qmk-kinesis/
Before this commit, when tuning the delays I noticed ghost key presses when
pressing the F2 key, which is on the last row of the keyboard matrix: the
dead_grave key, which is on the first row of the keyboard matrix, would be
incorrectly detected as pressed.
After this commit, all keyboard matrix rows are interpreted correctly.
I suspect that my setup is more susceptible to this nuance than others because I
use GPIO_INPUT_PIN_DELAY=0 and hence don’t have another delay that might mask
the problem.

matrix: wait for row signal to go HIGH for every row

---

docs/feature_led_matrix.md
docs/feature_rgb_matrix.md
drivers/issi/is31fl3733.c
quantum/led_matrix_drivers.c
quantum/rgb_matrix_drivers.c

Add support for up to 4 IS31FL3733 drivers
This change allows configuring up to 4 IS31FL3733 rgb matrix drivers.
*

Add support for up to 4 IS31FL3733 drivers

---

keyboards/nullbitsco/scramble/keymaps/default/keymap.c
keyboards/nullbitsco/scramble/keymaps/oled/keymap.c

This fixes a silly copypasta error present in the default and OLED keymaps -- _BASE layer should be 0 and not 1. Tested and verified locally.
* N/A

Fix wrong _BASE layer for SCRAMBLE default/OLED keymaps

---

common_features.mk
platforms/chibios/QMK_PROTON_C/convert_to_proton_c.mk

This is needed or rules.mk changes get overriden.

Do not hard set config in CPTC files

---

keyboards/fleuron/rules.mk

Removed ortho_6x16 community layout support by commenting out the line.
This can be reversed if that layout ever gets added.
cc @ju0 (keyboard maintainer)

Fleuron: Remove LAYOUTS = ortho_6x16

---

keyboards/clawsome/sedan/config.h
keyboards/clawsome/sedan/keymaps/default/keymap.c

The matrix specified for Clawsome/Sedan (introduced in #9539) was erroneous.
I've provided updated pinouts from an Elite-C as expected here. 
The default keymap was also changed to change the Right Shift to the appropriate binding.
Thanks to @AlisGraveNil for your quick responses!
*

Fix Clawsome/Sedan matrix and default keymap

---

keyboards/ploopyco/trackball_nano/keymaps/maddie/keymap.c
keyboards/ploopyco/trackball_nano/keymaps/maddie/readme.md

This keymap adds a scrolling mode for the Ploopy Nano, accessed by toggling numlock twice within 25ms.

Add a keymap with a scrolling mode for the Ploopy Nano trackball

---

docs/feature_backlight.md
quantum/backlight/backlight.c
quantum/backlight/backlight.h
tmk_core/common/eeconfig.c
tmk_core/common/eeconfig.h

Similar to #11912 but for backlight. `#define BACKLIGHT_DEFAULT_LEVEL x` and `BACKLIGHT_DEFAULT_BREATHING` control the backlight level and breathing state to set upon clearing the EEPROM. Moved the backlight eeconfig functions into backlight.c to match the other lighting systems' APIs.
I should note that this PR doesn't actually do anything! `backlight_init()` never calls `eeconfig_update_backlight_default()` because at this point, no matter how the EEPROM was cleared, it has already been initialised. However, calling it manually in a custom keycode and replugging the board does as expected.
It works properly for RGBLight and LED/RGB Matrix due to an additional check on the mode (0 is invalid). This seems a little inefficient as their EEPROM sections will be written twice upon clear, so I …

Backlight: add defines for default level and breathing state

---

bootloader.mk

Instead of just having a comment for the LUFA mass storage bootloader in the makefile, this prints it out to the console, too.
Couldn't get it to print all pretty. So ...

Add dire message about lufa ms bootloader

---

lib/python/qmk/cli/c2json.py
lib/python/qmk/errors.py
lib/python/qmk/keymap.py

Print the "fatal errors" from `cpp` if the `-v` argument is passed to `c2json`.
*

CLI/c2json: Print 'cpp' error when executed in verbose mode

---

keyboards/handwired/amigopunk/keymaps/default/keymap.c
keyboards/keyprez/corgi/keymaps/default/keymap.c
keyboards/mechwild/mercutio/keymaps/jonavin/keymap.c
keyboards/mechwild/murphpad/keymaps/default/keymap.c
keyboards/mechwild/murphpad/keymaps/via/keymap.c
keyboards/minimacro5/keymaps/devdev/keymap.c
keyboards/planck/thk/keymaps/thk/keymap.c
keyboards/sofle/keymaps/devdev/keymap.c
keyboards/sofle/keymaps/rgb_default/keymap.c

Merge right before locking develop (or right after)

Fix keyboards/keymaps for boolean encoder callback changes

---

lib/python/qmk/cli/__init__.py
lib/python/qmk/cli/bux.py

World domination

---

keyboards/merge/um70/keymaps/via/keymap.c

The code using `sprintf()` did not fit into flash when `merge/um70:via` was compiled with avr-gcc 5.4.0:
* The firmware is too large! 29756/28672 (1084 bytes over)
Replacing `sprintf(wpm_str, " %03d", current_wpm);` with custom formatting code reduces the firmware size by 1504 bytes, which is enough to make the `merge/um70:via` firmware fit:
* The firmware size is approaching the maximum - 28252/28672 (98%, 420 bytes free)
(I also tried to use `itoa()`, but the resulting code was larger, and needed some not really nice looking code to add zero padding — keeping the output string length constant is needed to make the OLED updates work properly.)
Tested on Pro Micro with OLED.
Unlike #12908, this PR does not disable features like NKRO which could be useful for some people.

Reduce `merge/um70:via` firmware size to make it fit

---

docs/breaking_changes.md
docs/chibios_upgrade_instructions.md

Updates to ChibiOS 20.3.3, and the latest ChibiOS-Contrib matching the 20.3.x branch.
* Closes #12843

Update ChibiOS, ChibiOS-Contrib.

---

quantum/matrix.c
quantum/split_common/matrix.c

Allow for keyboards to override implementations full-port reads without messing with the rest of the scanning logic, and without requiring a full custom matrix.

Add weak refs on reading rows/cols.

---

drivers/avr/spi_master.c
drivers/avr/spi_master.h
drivers/chibios/spi_master.c
drivers/chibios/spi_master.h

A lot of things really do not need to include all of `quantum.h` now that the GPIO stuff has been refactored out. This change is needed for the ST7565 driver (adapted from the OLED driver) to work; some kind of circular dependency occurs otherwise, and it fails to compile:
There are a lot more places I think this should be done, though it'll be tricky to test.
*

Tidy up spi_master includes

---

lib/python/qmk/cli/multibuild.py

`Path` objects passed to `cli.run()` must be stringified first.
*

`qmk multibuild`: Fix bug with Path objects

---

layouts/community/split_3x6_3/bcat/config.h
layouts/community/split_3x6_3/bcat/rules.mk

Just updating my `split_3x6_3` community layout to account for the recent deletion of the legacy Crkbd revision and the universal use of Split Common for Crkbd.
None

Update bcat's split_3x6_3 for Crkbd legacy removal

---

keyboards/handwired/dactyl_manuform/5x6_right_trackball/pmw3360.c
keyboards/ploopyco/pmw3360.c

#13053 broke the includes for the pmw3360.c files.  This fixes them.

Fix includes for pmw3360 driver

---

docs/config_options.md
tmk_core/protocol/usb_descriptor.c

The Teensy 4.x comes with USB 2.0 support. This change is required to make the device advertise itself as USB 2.0 in the USB device descriptor.

core: bump USB spec version in device descriptor to 2.0

---

keyboards/id80/ansi/keymaps/msf/config.h
keyboards/id80/ansi/keymaps/msf/keymap.c
keyboards/id80/ansi/keymaps/msf/readme.md
keyboards/id80/ansi/keymaps/msf/rules.mk

This adds my personal keymap for the ansi variant of the id80 keyboard.
It's just a keymap submission :-)
I have it running on my own id80, compiles and flashes without issues.

add id80/ansi/keymaps/msf

---

keyboards/coseyfannitutti/mysterium/keymaps/ansi_7u/keymap.c
keyboards/coseyfannitutti/mysterium/keymaps/default/keymap.c
keyboards/coseyfannitutti/mysterium/keymaps/iso/keymap.c
keyboards/coseyfannitutti/mysterium/keymaps/via/keymap.c
keyboards/coseyfannitutti/mysterium/mysterium.h

Swapped the key mapping so the the left \ key is bound correctly and that some rows are no longer shifted. Also fixed a mistake when copying this fixed from local drive in earlier pull request.
* #11705

Fixed ISO keyboard layout for the Mysterium rev1.1 board

---

tmk_core/protocol/chibios/usb_main.c
tmk_core/protocol/lufa/lufa.c
tmk_core/protocol/vusb/vusb.c

Empty extra key reports where send (observed with Wireshark) form the keyboard when O3 optimizations with LTO where enabled on GCC 10.2 (RISC-V). The root cause should be the pointer to an stack allocated report object which is invalid by the time the report is send. The fix is simple enough, the reports are allocated with a static lifetime, so pointers to them are never invalid. Joystick reports got the same treatment as the pattern is exactly the same.
* ?

[Core] ChibiOS fix O3 and LTO breakage of extra keys and joystick

---

tmk_core/avr.mk
tmk_core/rules.mk

Debian bullseye (testing at the moment, but seems close to release) has avr-libc 1:2.0.0+Atmel3.6.2-1.1 with some changes taken from the Atmel-distributed toolchain.  In particular, the `<avr/io.h>` header for ATmega32A (`avr/iom32a.h`) now defines the `FLASHEND` constant as `0x7FFFU`, and that `U` suffix breaks the firmware size check code, because the shell arithmetic expansion that is used to calculate `MAX_SIZE` does not support those C-specific suffixes.
As a workaround, add `-D__ASSEMBLER__` to the C preprocessor invocation that is used to expand those macros; in this case `avr/iom32a.h` defines `FLASHEND` without the `U` suffix, and everything works as it did before with older avr-libc versions.
The exact same code is present in two places; they are both changed, even though the …

Fix firmware size check with avr-libc 1:2.0.0+Atmel3.6.2-1.1 (Debian bullseye)

---

tmk_core/common/avr/gpio.h
tmk_core/common/chibios/gpio.h

The following macros have been added to gpio.h.
* readPort(port)
* setPortBitInput(port, bit)
* setPortBitInputHigh(port, bit)
* setPortBitOutput(port, bit)
* writePortBitLow(port, bit)
* writePortBitHigh(port, bit)
<details>
<summary><strong>Effects of using `readPort()`.  (click)</strong></summary>
* Processing time for Row0: 75.2us
* Processing time for Row0: 12.8us
* Processing time for Row0: 14.2us
* Processing time for Row0: 9.2us
</details>

Add readPort() and some API to 'tmk_core/common/*/gpio.h'

---

drivers/chibios/spi_master.c
drivers/chibios/spi_master.h

@firetech
Hopefully this works, or is at least close. Haven't tried compiling it yet.
Prerequisite for #13089 to be applied to the Ergodox Infinity.
*

`spi_master` Kinetis support

---

quantum/led_matrix.c
quantum/rgb_matrix.c

The check actually errors out if not set to anything (just defined, per docs)

Fix Bug with (RGB|LED)_DISABLE_WHEN_USB_SUSPENDED define 

---

docs/config_options.md
docs/custom_quantum_functions.md
keyboards/anavi/macropad8/keymaps/default/config.h
keyboards/handwired/frankie_macropad/keymaps/default/config.h
keyboards/mt84/keymaps/default/config.h
quantum/matrix.c
quantum/split_common/matrix.c

Second followup to the matrix reads -- this does a single memcmp at the end of the row/col reads instead of checking every row/col for a change for every read.

Use single memcmp to determine if matrix changed.

---

build_test.mk
quantum/debounce.h
quantum/debounce/none.c
quantum/debounce/sym_defer_g.c
quantum/debounce/sym_defer_pk.c
quantum/debounce/sym_eager_pk.c
quantum/debounce/sym_eager_pr.c
quantum/debounce/tests/debounce_test_common.cpp
quantum/debounce/tests/debounce_test_common.h
quantum/debounce/tests/rules.mk
quantum/debounce/tests/sym_defer_g_tests.cpp
quantum/debounce/tests/sym_defer_pk_tests.cpp
quantum/debounce/tests/sym_eager_pk_tests.cpp
quantum/debounce/tests/sym_eager_pr_tests.cpp
quantum/debounce/tests/testlist.mk
testlist.mk
tmk_core/common/arm_atsam/_timer.h
tmk_core/common/avr/_timer.h
tmk_core/common/chibios/_timer.h
tmk_core/common/timer.h

A 16-bit timer will overflow sooner but be faster to compare on AVR.
Count down remaining elapsed time instead of trying to do 8-bit timer comparisons.
Add a "none" implementation that is automatically used if DEBOUNCE is 0 otherwise it will break the _pk/_pr count down.
The matrix only needs to be updated when a debounce timer expires.
The matrix only needs to be updated when a debounce timer expires.
The use of the "needed_update" variable is trying to do what "matrix_need_update" was added to fix but didn't work because it only applied when all keys finished debouncing.
DEBOUNCE=5 should process the key after 5ms, not 6ms
Unit tests for all the debounce algorithms. I've only done some basic tests but more advanced scenarios could be added.

Avoid 8-bit timer overflows in debounce algorithms

---

lib/python/qmk/cli/multibuild.py

Adds support for specifying keymap name for `qmk multibuild`. Intentionally does not use decorators, as we don't want to use the user-configured one by default -- intent of the command is to build everything in the repository.

Allow limiting the multibuild based on keymap name.

---

keyboards/sofle/keymaps/killmaster/keymap.c

Changed `void encoder_update_user(int8_t index, bool clockwise)` to `bool encoder_update_user(uint8_t index, bool clockwise)`.
Also swapped the `KC_GRV` and the `KC_MINS` around.
*

Updated encoder_update_user on my keymap to follow the new signature on quantum

---

bootloader.mk

Makes the lufa-ms bootloader warning a bit more prominent, as well as putting it at the end of the build.

Slightly more prominent LUFA Mass-storage bootloader warning.

---

common_features.mk
docs/_summary.md
docs/feature_st7565.md
drivers/lcd/st7565.c
drivers/lcd/st7565.h
quantum/quantum.h
tmk_core/common/keyboard.c

One more step towards eliminating uGFX. Adapted from the SSD1306/OLED driver. Tested on Proton-C but should work on AVR as well.
@firetech
* Resolves #5268

Add ST7565 LCD driver

---

docs/feature_debounce_type.md
quantum/debounce/asym_eager_defer_pk.c
quantum/debounce/tests/asym_eager_defer_pk_tests.cpp
quantum/debounce/tests/rules.mk
quantum/debounce/tests/testlist.mk

Add ```asym_eager_defer_pk``` debounce type.
This branch is based on https://github.com/qmk/qmk_firmware/pull/12240 which has not yet been merged.

Add asym_eager_defer_pk debounce type

---

quantum/rgb_matrix_animations/jellybean_raindrops_anim.h

The rand() function for HSV saturation of Jellybean Raindrops covers 0-255 range, resulting with mostly white effect. This change limit saturation above 0x7F (127) to ensure colors are always visible.

Limit saturation for RGB_MATRIX_JELLYBEAN_RAINDROPS

---

bootloader.mk
keyboards/gray_studio/cod67/rules.mk
keyboards/tada68/rules.mk

Increased the size of the Lufa-MS bootloader to 8k
Reason stated here:  
https://github.com/abcminiuser/lufa/commit/5ada54b43299564d5fa52d62abfa9648a4b6c207#diff-15ef1ada160ea767f8b2d21026d94de985fcc1641b8b83d69377053ccd6bfddf
The new version also fixed the issue of oversized firmware files overwriting parts of the bootloader and thus softbricking the MCU. 
Writing oversized files to the flashdrive still works to an extent (it will show an error if the file is vastly oversized) but it just results in the keyboard not starting up. It can still be put back into bootloader mode afterwards without problems.
Throwing random files into the flash drive (like the MacOS typical .DS_Store) also doesn't hurt the bootloader anymore.
I guess we could remove the warning for the Lufa-MS bootloader now …

Change Lufa-MS size

---

tmk_core/common/chibios/bootloader.c

This commit makes the Teensy 4.x use the same jump-to-bootloader logic as the Teensy 3.x.

core: make RESET key work with Teensy 4.x

---

keyboards/anavi/macropad2/keymaps/binary/keymap.c
keyboards/anavi/macropad2/keymaps/binary/rules.mk

This binary keymap for ANAVI Macro Pad 2 helps with 0 and 1:
left key: 0
right key: 1
Combo press both keys to control the backlit.
Suggested-by: Chris <christopher.walker@crowdsupply.com>
Add a new funny binary keymap for ANAVI Macro Pad 2 for quickly typing 0 and 1.
*

[Keymap] ANAVI Macro Pad 2 add binary keymap

---

keyboards/bm40hsrgb/config.h

Allow user override to the `RGB_DISABLE_WHEN_USB_SUSPENDED` setting, based on @tzarc's suggestion in #12290

Allow user override of RGB_DISABLE_WHEN_USB_SUSPENDED for BM40 keyboard

---

drivers/lcd/st7565.c

Takes the OLED fix from #13204 in `master` and applies it to ST7565 in `develop`, as requested in a comment on that PR.
I don't have the requisite hardware to test this, but at least I don't see any new build errors introduced in the `make all:default`.
* Related to #13203.

Fix overrun in st7565_write_raw when not at (0, 0)

---

drivers/oled/oled_driver.c

See #13203 for details on the bug itself. For simplicity, I updated `oled_write_raw` to follow the (non-buggy) pattern that `oled_write_raw_P` already uses for reads (incrementing the `data` pointer rather than indexing into it using array syntax).
Verified this fixes the display corruption bug for OLED on ARM. See [before](https://i.imgur.com/9uMvT0D.png) (with corruption) and [after](https://i.imgur.com/TyZUpkG.png) (without corruption) this fix.
* Fixes #13203.

Fix data buffer overrun and OLED corruption bug in oled_write_raw when cursor not at origin (0, 0)

---

keyboards/thevankeyboards/minivan/rules.mk

Config.h has support for RGB LEDs but enable line was missing in rules.mk
*

Minivan : add missing enable to support RGB LEDs

---

util/update_chibios_mirror.sh

Quick and dirty script for keeping qmk/ChibiOS in sync with upstream subversion.

ChibiOS SVN mirror script.

---

keyboards/handwired/split89/config.h

Added missing closing comment bit */
This seems to cause the QMK configurator to break when clicking the compile button:
Compiling: keyboards/handwired/split89/split89.c                                                   In file included from [K:
ent]
/* COL2ROW, ROW2COL */
[K

|
|
|
make: *** ine/keyboards/handwired/split89/split89.o] Error 1
*

Update config.h to add missing comment closing characters  */

---

keyboards/kyria/kyria.h
keyboards/kyria/rev1/rev1.h
keyboards/kyria/rules.mk

This is a hidden bug, as it doesn't show up, because somebody got clever. 
However, the keyboard header files will cause issues if the `LAYOUT` macro is changed, and the rev3.h file is not properly included, either. 
This fixes the issues and moves the layout macros into the rev1.h file. 
There is NO functional change here, and this should be invisible to users. 
*  Compiler issue

[Keyboard] Fix revision issues with Kyria

---

keyboards/pistachio/config.h
keyboards/pistachio/keymaps/rate/keymap.c
keyboards/pistachio/keymaps/via/keymap.c
keyboards/pistachio/keymaps/via/rules.mk

adding keymap for pistachio

---

docs/feature_st7565.md
drivers/lcd/st7565.c
drivers/lcd/st7565.h

Port of #13172 to the ST7565 driver, to keep them in sync.
*

ST7565 invert

---

Vagrantfile

Upgrades the Vagrant box used from Debian 9 to 10 since 9 is considered EOL by the Docker team and fails to build properly (see https://github.com/docker/docker-install/issues/222).
*

Upgrades Vagrant box to Debian 10 to fix Docker build error on Debian 9.

---

data/schemas/keyboard.jsonschema
lib/python/qmk/info.py

As discussed in https://github.com/qmk/qmk_firmware/issues/13052, we should use LINE_PINxx on Teensy 4.x. This PR makes that possible.
* fixes https://github.com/qmk/qmk_firmware/issues/13052

allow LINE_PINxx for Teensy 4.x pins

---

build_json.mk
build_keyboard.mk

Switching between building one keymap.json in a keyboard to another keymap.json doesn't actually regenerate a new keymap.c, and the old keymap.json/keymap.c is used in the build.
Repro:
Build a keymap based on a keymap.json:
$ make clean
$ make ferris/0_1:default
$ shasum $(find .build -name keymap.c)
9fd4e6fccca4fd2d224db7f583afb1dfd2bb54d8  .build/obj_ferris_0_1/src/keymap.c
Build another keymap.json for the same keyboard:
$ make ferris/0_1:pierrec83
$ shasum $(find .build -name keymap.c)
9fd4e6fccca4fd2d224db7f583afb1dfd2bb54d8  .build/obj_ferris_0_1/src/keymap.c
*Notice that the keymap.c has not been changed, and the new build uses the wrong keymap.*
Workaround: clean build
$ make clean
$ make ferris/0_1:pierrec83
$ shasum $(find .build -name keymap.c) …

Fixing incorrect keymap build when switching between multiple keymap jsons

---

quantum/led_matrix.c
quantum/rgb_matrix.c

Adds a limiter to updating the eeprom for rgb matrix to once every full rgb matrix loop. This helps reduce lagging / frequent writes due to rapid controlling of the rgb keycodes via encoders or such.
*

RGB Matrix eeprom write limiting

---

keyboards/telophase/config.h
keyboards/telophase/keymaps/default/keymap.c
keyboards/telophase/matrix.c
keyboards/telophase/readme.md
keyboards/telophase/rules.mk
keyboards/telophase/telophase.c
keyboards/telophase/telophase.h

Just clearing out my stashes. Could be converted to custom matrix lite - may try that at some point later.
*

Telophase cleanup

---

keyboards/kiwikey/wanderland/keymaps/stanrc85/config.h
keyboards/kiwikey/wanderland/keymaps/stanrc85/keymap.c
keyboards/kiwikey/wanderland/keymaps/stanrc85/rules.mk

Add stanrc85 Abasic keymap

---

docs/keycodes.md
docs/mod_tap.md
quantum/quantum_keycodes.h

Add macros for Option+Command (Alt + GUI) and Shift+Command (Shift + GUI) that are common shortcuts for OS X.

Add Mac centric Shift and Alt + GUI Macros

---

quantum/serial_link/system/serial_link.c
tmk_core/common/sync_timer.c
tmk_core/common/sync_timer.h

Add ability to sync the sync_timer over the serial_link system used by Ergodox Infinity.
More or less just a port from split_common/transport.c and some tweaked `#if`s in sync_timer.[ch].

Add support for sync_timer over serial_link (i.e. Ergodox Infinity).

---

keyboards/preonic/keymaps/default/keymap.c

The rev3 boards use RGBLIGHT_ENABLE now instead of BACKLIGHT_ENABLE.
This resolves the issue of flashing and losing functionality with the default keymap.

Fix Preonic rev3 default keymap

---

nix/poetry.lock
nix/pyproject.toml
nix/sources.json
shell.nix

Update Python dependencies for Nix to account for the recent changes:
- The `qmk console` command implementation now requires the `hid` and `pyusb` Python modules.
- The `Wave` Python dependency was a mistake; it was already removed from `requirements-dev.txt`, but still left in `nix/pyproject.toml`.
- The build scripts now complain that `bin/qmk` is deprecated, therefore the QMK CLI should be provided in the nix-shell environment.
The `hid` and `pyusb` Python modules required adding some overrides to `shell.nix` to make them actually work (without those overrides the packages seem to build, but break at runtime, because they cannot find the needed native libraries in Nix-specific directories). The override for `pyusb` was copied from …

Update Python dependencies for Nix

---

quantum/mcu_selection.mk

This can now be done by simply setting `BOOTLOADER = stm32-dfu`.
*

Remove dfu-util arguments from mcu_selection

---

keyboards/le_chiffre/le_chiffre.c

disabling RGB_MATRIX_ENABLE causes led_config to fail during compile. Setting this conditional allows you to turn off RGB
*

le_chiffre.c conditional led_config

---

docs/eeprom_driver.md
drivers/eeprom/eeprom_i2c.c

This is for boards that follow eeprom manufacturer recommendations,
to not hardcode the WP pin, but to deassert it only during writes,
to protect eeprom content during power-up/power-down/brown-out conditions.

eeprom_i2c driver: added EXTERNAL_EEPROM_WP_PIN configuration option.

---

lib/python/qmk/cli/doctor/__init__.py
lib/python/qmk/cli/doctor/check.py
lib/python/qmk/cli/doctor/linux.py
lib/python/qmk/cli/doctor/macos.py
lib/python/qmk/cli/doctor/main.py
lib/python/qmk/cli/doctor/windows.py

Doctor is getting pretty complex, it makes sense to split some of the code off into separate files. This moves those files into a common location so that our library is easier to understand.

Refactor doctor.py into a directory

---

lib/python/qmk/info.py

Now that jsonschema is validating the pin name ahead of time we should remove the extra validation in code.

Remove the redundant pin name validation

---

common_features.mk

```
| 
| /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_planck_light_drashna/color.o (symbol from plugin): in function `hsv_to_rgb_impl':
| (.text+0x0): multiple definition of `hsv_to_rgb_impl'; .build/obj_planck_light_drashna/quantum/color.o (symbol from plugin):(.text+0x0): first defined here
| /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_planck_light_drashna/color.o (symbol from plugin): in function `hsv_to_rgb_impl':
| (.text+0x0): multiple definition of `hsv_to_rgb'; .build/obj_planck_light_drashna/quantum/color.o (symbol from plugin):(.text+0x0): first defined here
| /usr/local/opt/avr-binutils/bin/avr-ld: .build/obj_planck_light_drashna/color.o (symbol from plugin): in function `hsv_to_rgb_impl':
| (.text+0x0): multiple definition of `hsv_to_rgb_nocie'; …
```

Fix linker error when rgblight and RGB Matrix are both enabled

---

quantum/rgb_matrix_runners/effect_runner_i.h
quantum/rgb_matrix_runners/effect_runner_reactive.h
quantum/rgb_matrix_runners/effect_runner_reactive_splash.h

If user keyboard's RGB speed setting (`rgb_matrix_config.speed`) is at zero, key press animation will remain static. Reactive runners will keep one key or entire keyboard lit.
This change avoid both conditions with a minimum value to the `tick` variable.

Fix zero condition of reactive runners that will suspend RGB animation

---

docs/feature_rgb_matrix.md
drivers/awinic/aw20216.c

Allow user to set SPI divisor for communicating to AW20216 RGB driver, default to 4.
Testing with a 480 fps video doesn't really show any tangible improvement, full matrix update still takes approx 15ms, I suspect the bottleneck is in the actual driver code.
*

Allow settable SPI divisor for AW20216 driver, set default to 4

---

keyboards/nullbitsco/nibble/keymaps/oled_bongocat/keymap.c

The original version of this keymap was missing layers 3 and 4, which messed with VIA support.
The "extra" macros from the default keymap were also added (Discord mute, super alt-tab, etc).
Tested locally on a NIBBLE keyboard with OLED display.
* None

Update oled_bongocat to match VIA keymap

---

keyboards/keyboardio/atreus/keymaps/ardumont/keymap.c

It so happens that when releasing the control key prior to the main key (C-h, C-i, C-n,
...), the substituted keycode was continuously sent in a loop after that (even when
releasing said key). The workaround so far was to type any other key to stop the loop.
This commit fixes such behavior by resetting the substitution keycode sent when the ctrl
released situation conditional is detected (and that the substitution keycode was on).
None

atreus/keymap/ardumont: Fix substitute keycode reset step

---

keyboards/studiokestra/nue/info.json

Corrected the info.json file to reference LAYOUT_all instead of LAYOUT.

Studio Kestra Nue: fix info.json layout macro reference

---

keyboards/ergodox_ez/util/keymap_beautifier/KeymapBeautifier.py

If one wishes to identify the different layers in a keymap using macro identifiers (`#define`), the `KeymapBeautifier` script for `ergodox_ez` will crash due to a missing integer, e.g.: 
```
#define L_BASE 0
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[L_BASE] = LAYOUT_ergodox_pretty(...
```
The script is unable to regenerate the pretty version of the layer, since it expects an integer, `[0] =  LAYOUT_..` rather than 
`[L_BASE] =  LAYOUT_..`
Solved by checking if the parsed data contains an integer value, or a name, and using the one that has been parsed.
*

Bug: only integers can be used to identify layers

---

lib/python/qmk/keyboard.py

If a keyboard is taller than 16 rows `qmk info -m` blows up. This expands that to allow up to 33 rows.

Expand the size of the textpad to allow for 33 row keyboards

---

lib/python/qmk/cli/__init__.py

Should address the problem reported in #13079.
* #12978 
* #13079

Add doctor to safe_commands

---

common_features.mk

I don't really understand the implications of QUANTUM_LIB_SRC vs SRC. 
I noticed removing the weak attribute on crc_init() threw up a undefined error in keyboard.c, so assumed it wasn't getting included correctly.
I've flashed this on a spare promicro and it seems to work correctly with the crkbd and kyria default keymaps. Might be good for someone else to confirm.
*

Fix CRC for AVR and enable again.

---

build_layout.mk

This commit fixes usage of keymap.json files in the layouts directory.
Support for this was added in #9553, but was recently broken by #12632.
Due to the changes introduced in #12632, it was now necessary to duplicate the json2c command in build_layout.mk. I'm not sure if there's a cleaner way to solve this, but I'm by no means a Makefile guru.

Fix building layouts from JSON

---

docs/feature_rgb_matrix.md
docs/feature_rgblight.md
quantum/color.h
quantum/rgblight/rgblight_list.h

Allows for rgblight_list.h to eventually be removed.
Both `rgb_matrix.h` and `rgblight.h` include `color.h`, and are included by `quantum.h`, so these defines should still be visible to keymaps.
*

Relocate RGB/HSV color defs to a more fitting place

---

keyboards/mb44/info.json
keyboards/mb44/keymaps/2u1u_space/keymap.c
keyboards/mb44/keymaps/2u_space/keymap.c
keyboards/mb44/keymaps/3u_space/keymap.c
keyboards/mb44/keymaps/default/keymap.c

Updated info.json to match mb44.h and rotary encoder callbacks in `keymap.c
* Due to having different layout names between `info.json` and  `mb44.h`, configurator was showing both the incorrect and correct named layouts. This PR revises the layout names in `info.json` to match `mb44.h`.
* Updated rotary encoder callback in keymap.c to conform to `bool`.
* See Description above.

kb: mb44 - Update info.json and encoder

---

keyboards/dztech/dz60rgb_ansi/keymaps/bingocaller/config.h
keyboards/dztech/dz60rgb_ansi/keymaps/bingocaller/keymap.c
keyboards/dztech/dz60rgb_ansi/keymaps/bingocaller/readme.md

Add my personal keymap for the DZ60RGB-ANSI board.
This is more or less a copy of [my existing DZ60 bingocaller keymap](https://github.com/qmk/qmk_firmware/tree/master/keyboards/dz60/keymaps/bingocaller) but with a few adjustments to the keymap itself, plus Mouse Key tweaks, and an updated README.

Create bingocaller keymap for DZ60RGB-ANSI

---

keyboards/kiwikey/wanderland/keymaps/stanrc85/keymap.c
users/stanrc85/rgb_timeout.c
users/stanrc85/rules.mk

I had RGB timeout code in a single keyboards keymap file, I've taken it out of there and moved it to my userspace in its own .c file so that multiple keyboards I use can have that feature.
*

RGB Timeout added to userspace

---

keyboards/kinesis/kint2pp/config.h
keyboards/kinesis/kint36/config.h

We have multiple user reports (https://github.com/kinx-project/kint/issues/39 and https://github.com/qmk/qmk_firmware/pull/12626) of ghost key press issues due to the short default debounce time of 5ms.
As the comment states, well-worn Cherry MX key switches as used in the Kinesis Advantage keyboards can produce noise for more than the 5ms specified in the Cherry data sheets.
* https://github.com/kinx-project/kint/issues/39

keyboards/kint*: update debounce time to 20ms to fix ghost key presses

---

keyboards/sanctified/dystopia/dystopia.h
keyboards/sanctified/dystopia/keymaps/default/keymap.c
keyboards/sanctified/dystopia/keymaps/via/keymap.c

Arranges the layout macro and keycodes to resemble the assembled keyboard.
Fixes
cc @Sanctified-git (keyboard maintainer)

Sanctified Dystopia: physically arrange layout macro

---

keyboards/illusion/rosa/info.json
keyboards/illusion/rosa/keymaps/default/keymap.c
keyboards/illusion/rosa/keymaps/oggi/keymap.c
keyboards/illusion/rosa/keymaps/split_bs_rshift/keymap.c
keyboards/illusion/rosa/keymaps/split_rshift/keymap.c
keyboards/illusion/rosa/keymaps/via/keymap.c
keyboards/illusion/rosa/rosa.h
keyboards/illusion/rosa/rules.mk

The Rosa PCB only supports Tsangan bottom row. This commit renames all the community layout macros to include the `tsangan` descriptor.
cc @bleeCS (keyboard maintainer)

Illusion Rosa: correct layout macro names

---

quantum/split_common/transactions.c

Now that the compilation bugs have been cleared out in #13253 switch the new transaction system implemented in #13353 to use the CRC functions added in #12641.
@XScorpion2 had issues with stripped `crc8` functions in their build. So I compiled both an AVR build of CRKBD and an ARM build of zvecr's split blackpill with and without LTO enabled. The functions are present under all configurations. This is the disassembly of the ELF files for the `crc8` functions:
**AVR GCC 5.4.0**
1. `make crkbd/rev1:default`
2. `avr-gdb -batch -ex "disassemble/rs 'crc8.constprop.13'" crkbd_rev1_default.elf`
<details>
<summary>ASM DUMP</summary>
```
Dump of assembler code for function crc8.constprop.13:
quantum/crc.c:
43      __attribute__((weak)) uint8_t crc8(const void *data, size_t data_len) {
0x0000390e …
```

[Core] Use CRC calculation subsystem for split_common

---

quantum/command.c
quantum/quantum.c
tmk_core/common/action_layer.c
tmk_core/common/action_layer.h

Add an explicit define for 32 bit layer mask, and set it as default. 
Also, set default bitmask based on Dynamic Keymap layer count define to automatically handle this.

Improve layer mask handling

---

quantum/matrix.c
quantum/split_common/matrix.c

Adds support for `NO_PIN` in the regular matrices

Add support for NO_PIN to all matrix types

---

quantum/mousekey.c
quantum/mousekey.h

This exposes the current mousekey report to the keymap code.
The keymap code can then make decisions based on that, for example to toggle buttons.
For other subsystems like the normal keyboard and pointing devices the report is exposed in a similar way.

mousekey: expose current report to users

---

show_options.mk

* Align the output to maximize readibility
* Add Bootloader to listed output

Improve 'show_build_options' target

---

drivers/awinic/aw20216.c

This PR updates `aw20216.c` to take advantage of register address auto increment similar to some of the ISSI drivers.
This effectively obsoletes #13173, which contains a similar implementation.
I've done some testing using @KarlK90's [debug trace prototype](https://hackmd.io/OY0oEy8LTQ6_zvZZy1Ws5w#Tracing-prototype) and this seems to be orders of magnitude faster than the existing code (pre and post update refers to before and after the commits in this PR):
*

AW20216 use register increment for framebuffer flushes

---

docs/feature_split_keyboard.md
quantum/split_common/split_util.c

Added a `#define` to allow split keyboards to use low is left, when using an input pin to set the keyboard half
Non

Allow invert of SPLIT_HAND_PIN logic

---

keyboards/latinpadble/info.json
keyboards/latinpadble/rules.mk

Removes an extra key object, and corrects the layout macro reference.
cc @haierwangwei2005 (keyboard maintainer)

LatinPadBLE: correct info.json data

---

tmk_core/common/chibios/bootloader.c

core: chibios: bootloader: use integer pointers as volatile
This prevents gcc from incorrectly trying to validate array bounds.
```
tmk_core/common/chibios/bootloader.c: error: '__builtin_memcpy' offset [0, 21] is out of the bounds [0, 0] [-Werror=array-bounds]
107 |     __builtin_memcpy((void *) VBAT, (const void *)sys_reset_to_loader_magic, sizeof(sys_reset_to_loader_magic));
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578#c16
* Fixes #12925 
Note: This is only compile tested, as I don't have such a device.

core: chibios: bootloader: use integer pointers as volatile

---

keyboards/crkbd/config.h
keyboards/crkbd/post_config.h
keyboards/crkbd/readme.md
keyboards/crkbd/rev1/config.h
keyboards/crkbd/rules.mk

Enables bootmagic lite and extra keys by default (because they should have been), as well as sets the keys for bootmagic lite. 
Also, auto-cformat pass due to commit hooks. 
* Reasonable defaults for configurator are not set.  They are now.

[Keyboard] Set reasonable defaults for Corne keyboard

---

docs/ja/config_options.md
docs/ja/faq_general.md
docs/ja/feature_swap_hands.md
docs/ja/feature_userspace.md
docs/ja/other_vscode.md
docs/ja/proton_c_conversion.md

* Check again that the following files are up to date.
- docs/proton_c_conversion.md
- docs/other_vscode.md
- docs/feature_swap_hands.md
- docs/faq_general.md
- docs/feature_userspace.md
- docs/config_options.md
*

[Update] Change Original TAGs of Japanese translations

---

lib/python/qmk/cli/doctor/main.py
lib/python/qmk/commands.py
lib/python/qmk/constants.py

Add `git`-related information such as branch, dirty-ness and deviation from master/develop to the output of `qmk doctor`.
Most of the checks are saved from zvecr's retired 'up/status' subcommand PR.
Although the end-goal for these checks to be used for the upcoming `update` subcommand, I think they are useful for assessing users' environment during debugging.
*

CLI: Add git and venv info to doctor's output

---

keyboards/helix/rev2/keymaps/fraanrosi/rules.mk

According to `helix/rev2/keymaps/fraanrosi/readme.md`, this keymap should be compiled with the following command:
```
make helix/rev2/under:fraanrosi
```
Therefore, when compiling all helix keymaps with the following command, an error occurs when compiling `fraanrosi`.
```
make helix:all
```
Therefore, add `LED_UNDERGLOW_ENABLE = yes` to `keymaps/fraanrosi/rules.mk` to suppress the error.

Fixed the Helix keymap 'fraanrosi' compile issues

---

keyboards/aeboards/constellation/rev2/config.h
keyboards/ai03/voyager60_alps/config.h
keyboards/boardsource/3x4/config.h
keyboards/boardsource/the_mark/config.h
keyboards/converter/ibm_5291/config.h
keyboards/converter/siemens_tastatur/config.h
keyboards/coseyfannitutti/mulletpad/config.h
keyboards/dc01/left/config.h
keyboards/ggkeyboards/genesis/hotswap/config.h
keyboards/ggkeyboards/genesis/solder/config.h
keyboards/handwired/promethium/config.h
keyboards/handwired/swiftrax/astro65/config.h
keyboards/kinesis/alvicstep/config.h
keyboards/kinesis/kint41/config.h
keyboards/kinesis/nguyenvietyen/config.h
keyboards/kmac/config.h
keyboards/lizard_trick/tenkey_plusplus/config.h
keyboards/mechlovin/tmkl/config.h
keyboards/meira/featherble/config.h
keyboards/meira/promicro/config.h
keyboards/orthodox/rev3/config.h
keyboards/orthodox/rev3_teensy/config.h

While working on #13470 I noticed a lot of keyboards have `MATRIX_ROWS` and `MATRIX_COLS` that are inconsistent with the pins actually configured to be used. This PR attempts to correct that in most cases.
TODO:

Matrix consistency improvements

---

lib/python/qmk/info.py

This ensures that the reported matrix matches the actual matrix.

Matrix consistency check

---

quantum/matrix.c

Two occurrences of `MATRIX_ROWS` weren't properly changed to `ROWS_PER_HAND` in #13330, causing a crash during boot on at least my Ergodox Infinity (including #13481).
(Only the `matrix_init_pins()` one, for `ROW2COL`, caused the crash on my Ergodox Infinity, but I found both these differences by comparing quantum/matrix.c after the change and quantum/split_common/matrix.c before the change, so both changes should be correct.)

Fix two out of bounds accesses from #13330.

---

docs/feature_rgb_matrix.md
drivers/issi/is31fl3737.c
keyboards/mt84/mt84.c
keyboards/planck/ez/ez.c
tmk_core/common/progmem.h

Moves the RGB Matrix g_is31_leds led config array to PROGMEM when using the issi/IS31FL3737 driver.
This array uses ~3bytes per rgb led and this change frees up considerable SRAM for the average rgb matrix keyboard.
Implementing this change to other issi drivers is trivial
This is a Break Change.
#13443
*

Enable g_is31_leds PROGMEM for RGB Matrix IS31FL3737 driver

---

keyboards/handwired/ortho5x14/info.json
keyboards/handwired/ortho5x14/readme.md

Fixes the visual position of the last key, and fixes a typo in the readme file.
cc @Antebios (keyboard maintainer)

Ortho 5x14 handwired info.json correction

---

lib/python/qmk/cli/__init__.py
requirements.txt

As reported in #12127 if you're using a non-unicode locale you may not be able to install dotty-dict. This switches to a package that does not have non-ASCII characters in the metadata.

Switch to the qmk-dotty-dict package

---

docs/feature_rgb_matrix.md
drivers/issi/is31fl3737.c
quantum/rgb_matrix/rgb_matrix_drivers.c

Enables Dual RGB Matrix IS31FL3737 driver support.  Is fully backward compatible and will not break existing keyboard configs.
* Fixes #13442

Dual RGB Matrix IS31FL3737 driver support to address #13442

---

keyboards/gmmk/pro/config.h

Adding a few configurations as defaults for the GMMK Pro which I think make sense either because they're either
1. The defaults on the stock firmware, or
2. Useful for a keyboard focused on enthusiasts and gamers, or
3. The same as the default value on QMK, but I tried to make them explicit here
Maybe it would be up to @glorious-qmk to check if these changes make sense for the GMMK Pro, but I think at least setting `USB_POLLING_INTERVAL_MS` to 1 does.
*

Set some default configurations for GMMK Pro

---

quantum/quantum.h

remove `#include "rgblight.h"` when `defined(RGB_MATRIX_ENABLE)` from quantum.h

Remove unnecessary `rgblight.h` include.

---

tmk_core/protocol/usb_descriptor.c
tmk_core/protocol/usb_descriptor_common.h
tmk_core/protocol/vusb/vusb.c

This is safe to do as literally 0 boards currently in the repo make use of `SERIAL_NUMBER`. This makes a good demo for doing the same to `MANUFACTURER` and `PRODUCT` so that things like:
https://github.com/qmk/qmk_firmware/blob/master/keyboards/exclusive/e6v2/le/config.h#L28
evaluate correctly (or rather, aren't evaluated at all).
*

Use string literals for `SERIAL_NUMBER`

---

quantum/led_matrix/led_matrix.c
quantum/rgb_matrix/rgb_matrix.c

* #12673
Failures when running `make all` don't seem to be related to my change. Note that I came across this bug while reading the source learning to implement a custom RGB matrix effect, so I might be mistaken and any input from maintainers more experienced is very welcome.

fix #12673

---

quantum/quantum.c
quantum/send_string.c

I forgot to do this when I moved all the sendstring stuff out of quantum.h. Also allowed for the bell song to be overridden.
*

Move `SENDSTRING_BELL` code to `send_string.h`

---

keyboards/tw40/keymaps/via/keymap.c
keyboards/tw40/keymaps/via/rules.mk

Adding via support for the TW40 keyboard
*

adding tw40 via support

---

keyboards/crkbd/post_config.h

Limits rgblight value or rgb matrix brightness if not defined.
Without a sensible limit the leds can draw over the 500mA fuse on a promicro, this results in the keyboard locking up or the secondary side not responding. This issue comes up fairly frequently in Discord.
120 may be a little conservative but should be safe when set to all white, it can vary between setups.

Limit RGB brightness for crkbd when not defined.

---

quantum/rgblight.h

Due to the change in #13555, `RGBLIGHT_H_DUMMY_DEFINE` in rgblight.h is already no longer needed, so delete it.

remove `RGBLIGHT_H_DUMMY_DEFINE` macro from rgblight.h

---

common_features.mk
quantum/rgb_matrix/rgb_matrix.h

Reverts qmk/qmk_firmware#13371
With #13555 and #13509, this should theoretically not be needed anymore.

Revert "Add rgblight to RGB Matrix VPATH"

---

keyboards/checkerboards/axon40/rules.mk

This PCB uses RGB underglow LEDs. If the user doesn't want them, they can turn them off with a keycode.
*

enable RGB underglow

---

keyboards/dztech/bocc/config.h

BOCC keyboard "config.h" had the incorrect amount of LEDs listed. Original code listed 16 rather than 20.
* 
Evidence from Discord about the issue:
Successful `make` output:
[bocc_success_make_output.txt](https://github.com/qmk/qmk_firmware/files/6634624/bocc_success_make_output.txt)

BOCC keyboard "config.h" had the incorrect amount of LEDs listed. Original code listed 16 rather than 20.

---

keyboards/massdrop/alt/keymaps/ewersp/README.md
keyboards/massdrop/alt/keymaps/ewersp/keymap.c

This PR contains small updates to my personal keymap for the Drop ALT keyboard. Primarily the changes are to enable EEPROM persistence for the RGB mode, to avoid having to reset the RGB pattern every time the board loses power.
It's worth noting that EEPROM is still disabled by default for the Drop ALT, so for this to actually work changes are also needed from https://github.com/qmk/qmk_firmware/pull/6068 which is unfortunately stuck in limbo.
I'd still like to get these keymap changes into mainline though, as they compile and run fine on their own.

[Keymap] Updates to personal Drop ALT keymap

---

keyboards/sekigon/grs_70ec/config.h
keyboards/sekigon/grs_70ec/ec_switch_matrix.c

@sekigon-gonnoc
https://github.com/qmk/qmk_firmware/runs/3126472278
```
ValueError: Invalid pin: S2
Error: Process completed with exit code 255.
```
`qmk generate-api` on develop is a little more forgiving (at least it catches the error):
```
☒ Invalid API data: sekigon/grs_70ec: matrix_pins.cols.0: 'S2' is not valid under any of the given schemas
```
*

Fix API generation failure caused by GRS-70EC

---

keyboards/ristretto/config.h
keyboards/ristretto/info.json
keyboards/ristretto/keymaps/default/keymap.c
keyboards/ristretto/readme.md
keyboards/ristretto/ristretto.c
keyboards/ristretto/ristretto.h
keyboards/ristretto/rules.mk

Add Ristretto Keyboard

---

docs/feature_rgblight.md
quantum/rgblight/rgblight.c

Add guard `RGBLIGHT_LAYERS_RETAIN_VAL` to retain the currently used val (as returned by `rgblight_get_val()`)
when applying lighting layers.

Retain brightness with lighting layers

---

common_features.mk

Random functions in lib8tion's `random8.h` requires the variable `rand16seed` that is externally initialised in `lib8tion.c`. Included that as part of source files to be built with `RGB_MATRIX_ENABLE`.

Include lib8tion.c into RGB matrix build list

---

keyboards/handwired/symmetric70_proto/matrix_debug/matrix.c
keyboards/handwired/symmetric70_proto/proton_c/proton_c.c
keyboards/kinesis/kint41/kint41.c
keyboards/rgbkb/mun/matrix.c
keyboards/rgbkb/mun/mun.c

Fir the function call for boards using `matrix_output_unselect_delay`.
* Compilation issues

Fix errors with `matrix_output_unselect_delay` function calls

---

keyboards/dc01/left/config.h
keyboards/dc01/left/matrix.c

Fixes this error:
☒ dc01/left: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 6 != 21

Fix dc01/left so that it doesn't throw a warning

---

keyboards/bastardkb/scylla/rules.mk

To reduce it's size so it will compile

[Keyboard] Enable LTO by default on BastardKB Scylla

---

.github/workflows/format.yaml
docs/cli_commands.md
docs/cli_development.md
docs/de/cli.md
docs/fr-fr/cli.md
docs/ja/cli_commands.md
docs/ja/cli_development.md
lib/python/qmk/cli/format/c.py
lib/python/qmk/tests/test_cli_commands.py

PR #13296 changed the name of the `cformat` and `pyformat` commands to
`format-c` and `format-py` respectively. This PR updates the documentation
and some parts of the CLI to use the new names.
Also add documentation for the new `format-text` subcommand, introduced
in the same PR.
*

CLI/Docs: Fix the format commands' name

---

keyboards/handwired/swiftrax/astro65/config.h

Fix column num, and add `NO_PIN` until it can be properly fixed.
* Fix CI compiler

[Keyboard] Quick hack to fix Astro65 board

---

keyboards/dztech/dz60rgb/v2_1/rules.mk
keyboards/ungodly/launch_pad/config.h

[Keyboard] Reduce compile size for dz60rgb v2.1

---

keyboards/lets_split/keymaps/via/config.h
keyboards/lets_split/sockets/config.h

Remove lock sync, and disable music mode to get it to compile under size.

[Keyboard] Fix compile size for the Lets Split Sockets via keymap

---

docs/cli_commands.md

Fairly certain it's `CONSOLE_ENABLE` everywhere else in the docs:
- https://github.com/qmk/qmk_firmware/blame/master/docs/faq_debug.md#L7
- https://github.com/qmk/qmk_firmware/blame/master/docs/faq_misc.md#L113
- https://github.com/qmk/qmk_firmware/blame/master/docs/config_options.md#L368
- https://github.com/qmk/qmk_firmware/blame/master/docs/getting_started_make_guide.md#L68

docs/cli_commands: fix typo

---

bootloader.mk
data/schemas/keyboard.jsonschema
docs/driver_installation_zadig.md
docs/flashing.md
tmk_core/avr.mk

Like the title says. 
Updates LUFA to the latest version, as well as adds support for generating the lufa HID bootloader, as well as flashing it.

Update LUFA to newest (18-07-2021) and add QMK-HID Bootloader support

---

build_test.mk
docs/faq_debug.md
docs/unit_testing.md
tests/test_common/main.cpp
tests/test_common/test_fixture.cpp

Can be run with `make test:all DEBUG=1`.
Should help slightly when trying to diagnose issues.

Allow output of logging when running unit tests

---

keyboards/ergodox_ez/ergodox_ez.c
keyboards/ergodox_ez/keymaps/default/keymap.c
keyboards/ergodox_ez/rules.mk
keyboards/moonlander/config.h
keyboards/moonlander/keymaps/default/config.h
keyboards/moonlander/keymaps/default/keymap.c
keyboards/moonlander/matrix.c
keyboards/moonlander/moonlander.c
keyboards/moonlander/moonlander.h
keyboards/moonlander/readme.md
keyboards/planck/ez/config.h
keyboards/planck/ez/ez.c
keyboards/planck/ez/ez.h
keyboards/planck/ez/glow/config.h
keyboards/planck/ez/glow/glow.c
keyboards/planck/ez/glow/glow.h
keyboards/planck/ez/readme.md
keyboards/planck/keymaps/oryx/config.h
keyboards/planck/keymaps/oryx/keymap.c
keyboards/planck/keymaps/oryx/rules.mk

[Keyboard] Update ZSA Keyboard Readmes and keymaps

---

keyboards/aeboards/constellation/rev2/rules.mk
keyboards/xelus/pachi/rgb/rules.mk

Prototypes were made using L433, however production has changed to L422. 
I can confirm there are no prototypes with L433 in the wild.
* Change to proper MCU

[Keyboard Update] Change to L422

---

keyboards/40percentclub/nein/info.json

Changes `LAYOUT` to `LAYOUT_ortho_3x3` in `info.json`.
Fixes:
https://github.com/qmk/qmk_firmware/blob/a73e0a7b1308825ffd2fff18ff385add09f31c03/keyboards/40percentclub/nein/nein.h#L28 vs. https://github.com/qmk/qmk_firmware/blob/a73e0a7b1308825ffd2fff18ff385add09f31c03/keyboards/40percentclub/nein/info.json#L8

40percentclub/nein: update info.json layout macro reference

---

keyboards/dztech/dz60rgb/v2_1/rules.mk
keyboards/dztech/dz65rgb/v3/rules.mk

Bootloader size needs to be 6144 to allow QMK to jump to the correct location with bootmagic
* https://github.com/qmk/qmk_firmware/issues/13283

Add bootloader size

---

keyboards/splitkb/kyria/rev1/config.h
keyboards/splitkb/kyria/rev1/rev1.c
keyboards/splitkb/kyria/rev1/rules.mk

This change adds `g_led_config` struct to Kyria, allowing LEDs to be addressed by `RGB_MATRIX_ENABLE` features if users enable support in their own configuration.

Add RGB matrix support for Kyria

---

drivers/awinic/aw20216.c
drivers/awinic/aw20216.h
quantum/rgb_matrix/rgb_matrix_drivers.c

Slight tidy up of a few things,
* Align api with existing ISSI drivers
* mostly handing the DRIVER_x stuff within `rgb_matrix_drivers.c`
* Reuse of some failure conditions
* Align some terminology
Saving a whole 236 bytes.... wooo... I guess.

Align AW20216 driver

---

keyboards/keebio/quefrency/rev3/rev3.c

Fix a short circuit evaluation issue in quefrency/rev3/rev3.c that causes the user function led_update_user() to never run when the right side of the board is connected. 
* 13750

fix short circuit in led_update_bk

---

tmk_core/protocol/arm_atsam/usb/udi_device_conf.h

Enables the `USB_POLLING_INTERVAL_MS` define to be respected for ATSAM boards.

Allow for higher USB Polling rate on ATSAM boards

---

docs/one_shot_keys.md

Simple typo clean up in documentation that threw me for a loop at first.
Changed "ON_TOGG" to "OS_TOGG" in the documentation to match what's present in the codebase. There is no "ON_TOGG" anywhere else. 
- [ x] Bugfix

fix: Fix typo in documentation for one shot keys. ON_TOGG -> OS_TOGG

---

Makefile

Hopefully this is a bit clearer.
```
$ make a:b       
make: *** No rule to make target 'a:b'. Stop.
|
| QMK's make format is:
|     make keyboard_folder:keymap_folder[:target]
|
| Where `keyboard_folder` is the path to the keyboard relative to
| `qmk_firmware/keyboards/`, and `keymap_folder` is the name of the
| keymap folder under that board's `keymaps/` directory.
|
| Examples:
|     keyboards/dz60, keyboards/dz60/keymaps/default
|       -> make dz60:default
|       -> qmk compile -kb dz60 -km default
|     keyboards/planck/rev6, keyboards/planck/keymaps/default
|       -> make planck/rev6:default:flash
|       -> qmk flash -kb planck/rev6 -km default
|
```
*

Update "make format" message

---

docs/cli_commands.md
lib/python/qmk/cli/docs.py

Last time I tried this in MSYS2 it didn't work, it seems to now 🤷
*

`qmk docs`: Add flag to open in browser

---

keyboards/ocean/sus/info.json
keyboards/ocean/sus/keymaps/default/keymap.c
keyboards/ocean/sus/keymaps/via/keymap.c
keyboards/ocean/sus/sus.h

- rename LAYOUT_ortho_3x4 to LAYOUT_ortho_4x3
- ... because ortho layouts in QMK are named by \<rows\>x\<columns\> instead of \<columns\>x\<rows\>
cc @alabahuy (keyboard maintainer)

Ocean Sus Board: rename layout macro

---

keyboards/stratos/info.json

- change LAYOUT_60_ansi_tsangan_hhkb to LAYOUT_60_tsangan_hhkb
https://github.com/qmk/qmk_firmware/blob/5a0985aa4a10ae15d3c3eb49a0394b10a62160ae/keyboards/stratos/stratos.h#L79 vs. https://github.com/qmk/qmk_firmware/blob/5a0985aa4a10ae15d3c3eb49a0394b10a62160ae/keyboards/stratos/info.json#L275
cc @kb-elmo (keyboard maintainer)

Stratos: fix layout macro reference in info.json

---

keyboards/txuu/info.json
keyboards/txuu/txuu.h

Renames the layout macro to be more conformant to the rest of QMK.
cc @matthewdias (keyboard maintainer)

txuu: rename LAYOUT to LAYOUT_65_ansi_blocker_split_bs

---

docs/cli_commands.md
docs/es/hardware_avr.md
docs/hardware_avr.md
docs/ja/hardware_avr.md
lib/python/qmk/cli/new/keyboard.py
lib/python/qmk/commands.py
util/new_keyboard.sh

For the most part this is pretty much just a straight port from the shell script, but with some notable improvements such as validation of keyboard name and type.
Currently there is a bug with MILC's `choice()` that causes a default selection of 0 to be interpreted as no default: https://github.com/clueboard/milc/pull/40
*

Port new_keyboard.sh to CLI

---

docs/pr_checklist.md

As per the title. Clarification.

Explicitly state that VIA should not be enabled in the default keymap.

---

lib/python/qmk/cli/doctor/check.py
lib/python/qmk/cli/doctor/linux.py

`qmk doctor` is a bit too strict on a couple of issues, which can lead to false-positive warnings:
1) To determine if the `qmk_firmware` home is a git repository, the `doctor` checks, if `${QMK_FIRMWARE}/.git` is a directory. However, if `qmk_firmware` is a git submodule, then `.git` will be a file instead of a directory. This PR relaxes the requirement, allowing `.git` to be a file.
2) When checking for the installed `udev` rules, the `doctor` searches only in `/etc/udev/rules.d/*.rules`. According to `man udev`, this isn't the only directory, where `udev` rules can be located:
```
RULES FILES
The udev rules are read from the files located in the system rules directories /usr/lib/udev/rules.d
and /usr/local/lib/udev/rules.d, the volatile runtime directory /run/udev/rules.d and the local …
```

Lenient doctor

---

keyboards/rgbkb/pan/pan.c
keyboards/rgbkb/pan/rev1/rules.mk

the RGB encoders for the Pan are wired up incorrectly (wrong channels), so needs custom handling for LEDs 0-1.
* issue reported on discord

[Keyboard] Fix RGBKB Pan Rev1 Encoder RGB handling

---

keyboards/nullbitsco/nibble/keymaps/oled_status/oled_display.c

Followed @drashna's advice for reducing size of wpm counter code -- this is the same optimization recommended in #13638.
Removed sprintf and stdio. Tested locally.
None

Reduce nibble oled_status keymap size

---

drivers/sensors/pimoroni_trackball.h

Changes the read address, I was unable to read trackball status without this change. Any queries would end up with `I2C_STATUS_ERROR`. 
Works fine with the change, tested on a promicro and pimoroni trackball.

[develop] Fix pimoroni trackball read address.

---

keyboards/massdrop/ctrl/keymaps/endgame/keymap.c
keyboards/massdrop/ctrl/keymaps/endgame/keymap.h

Updates the Massdrop CTRL keyboard endgame keymap to work after the changes to USB suspend in #12697
* Fixes #13782

Update endgame keymap to work with suspend changes

---

quantum/process_keycode/process_key_override.c
quantum/process_keycode/process_key_override.h

Include was wrong. Fixed. 
* Discord reported

[BUG] Fix Key Override includes

---

tmk_core/protocol/chibios/usb_main.c

Contents of HID_SET_REPORT requests which set status LEDs' state were not properly being copied.
It could be that this malfunction is only observed when using NUMICRO, Nuvoton NUC123, port of ChibiOS.
Adjusting the alignment restriction fix the issue. Naturally, it should do no harm for other builds.

[Core] [ChibiOS] Fix alignment of USB out report buffer 2 -> 4

---

tmk_core/common/chibios/flash_stm32.c

On stm32f4 after reboot from DFU it was observed that the flash is
already unlocked. In that case, attempting to unlock it again causes a
data abort.
*

flash_stm32: don't unlock flash if already unlocked

---

keyboards/0xcb/static/info.json
keyboards/0xcb/static/keymaps/default/keymap.c
keyboards/0xcb/static/keymaps/via/keymap.c
keyboards/0xcb/static/static.h

- `qmk info` can't retrieve the matrix data for the layout macro if there is white space before the `#define`.
- add macro for `LAYOUT_bigbar`
- rename `LAYOUT` to `LAYOUT_all` per QMK guidelines
cc @conor-burns (keyboard maintainer)

0xCB Static: fix `qmk info` and Configurator issues

---

keyboards/9key/keymaps/bcat/keymap.c
keyboards/eco/keymaps/bcat/keymap.c
keyboards/keebio/bdn9/keymaps/bcat/keymap.c
keyboards/keebio/quefrency/keymaps/bcat/config.h
keyboards/keebio/quefrency/keymaps/bcat/keymap.c
keyboards/lily58/keymaps/bcat/config.h
keyboards/lily58/keymaps/bcat/keymap.c
layouts/community/60_ansi_split_bs_rshift/bcat/keymap.c
layouts/community/60_tsangan_hhkb/bcat/keymap.c
layouts/community/65_ansi_blocker_split_bs/bcat/keymap.c
layouts/community/split_3x6_3/bcat/keymap.c
layouts/community/split_3x6_3/bcat/readme.md
users/bcat/bcat.c
users/bcat/bcat.h
users/bcat/readme.md

Added license headers to all my keymap/userspace sources still missing them, clang-formatted my source files, tweaked keymap code in insubstantial ways, and updates some of my keymap readme files. There shouldn't be any functional changes in this PR.
None

Minor cleanup of bcat keymaps and userspace

---

keyboards/ergodox_infinity/rules.mk
keyboards/k_type/rules.mk
keyboards/whitefox/rules.mk
platforms/chibios/IC_TEENSY_3_1/board/board.c
tmk_core/protocol/chibios/main.c
tmk_core/protocol/chibios/usb_main.c

On at least my Ergodox Infinity, the #10088 hotfix _causes_ the issue it intended to solve. That is, waking the keyboard from suspend after the keyboard has caused the host to wake works fine _without_ the #10088 hotfix, but _with_ it, the keyboard gets stuck sleeping.
This PR removes the #10088 hotfix for Ergodox Infinity, K-Type and Whitefox (all using the same MK20DX256 MCU).

Remove the #10088 hotfix for Teensy 3.1-like Input:Club keyboards

---

tmk_core/protocol/chibios/usb_main.c

I have my keyboard (Ergodox Infinity) connected to a powered USB hub/switch that can be connected to two computers allowing me switch between the computers with a button. Currently, switching between computers (or unplugging the cable from the "active" computer) causes `suspend_power_down()` to be called, but `suspend_wakeup_init()` never gets called afterwards. I suspect the same would happen with keyboards connected to at least some externally powered USB hubs when the hubs get disconnected from the host.
Some investigation showed that the device got a reset event when the USB switch was triggered, but retained power. Discussing this on Discord notified me about the fact that the USB specification (section 7.1.7.3) says that "Reset must wake a device from the Suspend state.", so a Reset …

Trigger a wakeup after USB Reset on ChibiOS

---

quantum/wpm.c

Fix two possible overflows in WPM calculations.
First, the "fresh" WPM calculation could end up being up to 12000 (with default `WPM_ESTIMATED_WORD_SIZE`) if keys were pressed more or less simultaneously. This value has now been clamped down to 255, in effect clamping WPM to its max value of 255. Before #11727, the intermediate value in question was limited by being stored in a uint8_t (causing slightly random values after overflows).
Second, with `WPM_ALLOW_COUNT_REGRESSION` enabled, it was possible to regress the WPM below 0 (i.e. to 255) by just repeatedly pressing backspace.

Fix overflows in WPM calculations

---

docs/other_vscode.md

This change fixes the warning caused by deprecated way of configuring terminal profiles.
The warning caused by old settings.json is the following:
```
This is deprecated, the new recommended way to configure your default shell is by creating a terminal profile in `#terminal.integrated.profiles.windows#` and setting its profile name as the default in `#terminal.integrated.defaultProfile.windows#`. This will currently take priority over the new profiles settings but that will change in the future.
```
Refer to the link below for more information:
https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration
* Warning caused by deprecated way of setting terminal profile.

Updated settings.json file to fit VSC's docs

---

keyboards/barracuda/info.json
keyboards/barracuda/rules.mk

- change LAYOUT to LAYOUT_ortho_3x11
https://github.com/qmk/qmk_firmware/blob/2b097d670a9fa458b8d059f824a0cbbd5b6c6659/keyboards/barracuda/barracuda.h#L30 vs. https://github.com/qmk/qmk_firmware/blob/2b097d670a9fa458b8d059f824a0cbbd5b6c6659/keyboards/barracuda/info.json#L8
cc @knaruo (keyboard maintainer)

barracuda: update info.json layout macro reference

---

keyboards/draculad/keymaps/default/keymap.c
keyboards/draculad/keymaps/pimoroni/keymap.c

It's compiling over size.  This removes the use of sprintf, and reduces the compiled size.
* CI

[Keyboard] Switch Draculad to using WPM char hack

---

docs/feature_ps2_mouse.md
tmk_core/protocol/ps2_mouse.c
tmk_core/protocol/ps2_mouse.h

This add the config parameter PS2_MOUSE_INVERT_BUTTONS that invert the left & right button on the PS2 mouse.
* https://github.com/qmk/qmk_firmware/issues/9204

[Feature] Swap buttons on PS2 Mouse/Trackball

---

docs/tap_hold.md
tmk_core/common/action_tapping.c

Implement an additional `HOLD_ON_OTHER_KEY_PRESS` option for dual-role keys which converts the dual-role key press into a hold action immediately when another key is pressed (this is different from the existing `PERMISSIVE_HOLD` option, which selects the hold action when another key is tapped (pressed and then released) while the dual-role key is pressed).  The Mod-Tap keys already behave in a similar way, unless the `IGNORE_MOD_TAP_INTERRUPT` option is enabled (but with some additional delays); the added option makes this behavior available for all other kinds of dual-role keys.
* #8971

Add HOLD_ON_OTHER_KEY_PRESS option for dual-role keys

---

quantum/command.c
quantum/command.h

I accidentally a huge refactor. (This is part 1 of n.) It improves the code size & {read,maintain}ability significantly.
This PR reduces the firmware size by ~1.5kB on my ATmega32, when built with `CONSOLE_ENABLE` and `COMMAND_ENABLE` set to `yes`.
If possible, could this PR be merged rather than squashed?
Because the last commit moves `mousekey_console()` to `mousekey.c` (verbatim, trust me :), I recommend reading the penultimate commit separately to see the changes to `mousekey_console()` itself.
```
commit 3ec12a579518e1dda45b3163d042d4d781a6850c
Author: Liyang HU <git@liyang.hu>
Date:   Sun Feb 7 16:19:52 2021 +0000
quantum/command.c: optimise `mousekey_console()` for size & legibility
Made various tweaks to the interface, but still functionally identical.
Assume `KC_1`…`KC_0` to be …
```

Refactor `quantum/command.{c,h}` for code size & {read,maintain}ability

---

keyboards/kbdfans/kbd67/rev2/config.h
keyboards/kbdfans/kbd67/rev2/rev2.c
keyboards/kbdfans/kbd67/rev2/rules.mk

Fixed the RGB LED count for the PCB (it only has 16 and not 20) and changed the capslock indicator function to the QMK default

Fixes for KBD67 rev2

---

keyboards/handwired/xealousbrown/matrix.c

Fix `matrix_output_unselect_delay` function call on develop
* CI

[Keyboard] Fix matrix_output_unselect_delay for handwired/xealousbrown

---

quantum/split_common/transactions.h

Fix compilation issue for bitbang serial on ChibiOS.

Fix compilation issue.

---

tmk_core/avr.mk

Without this padding, the LUFA-MS bootloader seems to place smaller firmware wherever it feels like, and apparently leaves previous data alone, which is an issue if it decides to start the new firmware somewhere other than `0x0000`. Adding the `--pad-to` flag to the avr-objcopy command in the `bin` target forces the final .bin file to be exactly the right size (assuming 32u4), giving the bootloader no choice but to fill up the entire available flash.
This should work for the older 6kB bootloader as well as the newer 8kB version.
*

Add padding to LUFA-MS .BIN files

---

lib/python/qmk/cli/lint.py

Uses `find_readme()` so that most keyboards now pass.

Improve the qmk lint readme check

---

keyboards/handwired/stream_cheap/2x4/config.h
keyboards/handwired/stream_cheap/2x4/keymaps/via/keymap.c
keyboards/handwired/stream_cheap/2x4/keymaps/via/rules.mk
keyboards/handwired/stream_cheap/2x4/keymaps/via/stream_cheap_2x4.json
keyboards/handwired/stream_cheap/2x4/rules.mk
keyboards/handwired/stream_cheap/readme.md

Signed-off-by: Luigi311 <luigi311.lg@gmail.com>
Add VIA support to handwired/stream_cheap/2x4
*

Handwired/Stream_Cheap/2x4: Add via support

---

util/qmk_install.sh

Previous code would fail if cd echoes the target directory to stdout,
which is pretty common.  Redirecting its output to /dev/null
solves the problem.
Sorry about the typo in the actual change comment, feel free to fix that.

Fix shell port bug in computation of QMK_FIRMWARE_DIR

---

keyboards/handwired/3dp660/config.h
keyboards/rpiguy9907/southpaw66/config.h
keyboards/yatara/drink_me/config.h

@sigprof found some keyboards in the VIA repo that use `0xFEED` for the Vendor ID, in violation of VIA's own policies.
A follow-up of sorts to #13961, this PR updates the other three keyboards sigprof flagged to use non-`0xFEED` Vendor IDs, two of which gain updated Product IDs as well.
CC:
* @gooberpsycho (maintainer of `handwired/3dp660` and `rpiguy9907/southpaw66`)
* @yatara-cc (maintainer of `yatara/drink_me`)

Update USB Device strings for VIA identification

---

keyboards/gmmk/pro/ansi/keymaps/andrebrait/config.h
keyboards/gmmk/pro/ansi/keymaps/andrebrait/keymap.c
keyboards/gmmk/pro/ansi/keymaps/andrebrait/readme.md
keyboards/gmmk/pro/ansi/keymaps/andrebrait/rules.mk
keyboards/gmmk/pro/ansi/keymaps/default/keymap.c
keyboards/gmmk/pro/ansi/keymaps/via/keymap.c
keyboards/gmmk/pro/iso/keymaps/default/keymap.c
keyboards/gmmk/pro/iso/keymaps/via/keymap.c
keyboards/gmmk/pro/pro.c

Just my own layout with an implementation for the CAPS LOCK indicator that works regardless of the actual status of the RGB Matrix.
*

[Keymap] Add andrebrait layout for GMMK Pro

---

keyboards/kbdfans/kbd67/mkiirgb/v3/config.h

QMK Configurator does not compile - needs a value on RGB_DISABLE_WHEN_USB_SUSPENDED
n/a

Update config.h to add a value to RGB_DISABLE_WHEN_USB_SUSPENDED

---

keyboards/ocean/gin_v2/keymaps/default/keymap.c
keyboards/ocean/gin_v2/keymaps/via/keymap.c

Has an extra `{` in the keymap array. Didn't catch. 
* Tzarc CI

[Keyboard] Fix keymaps for Ocean Gin v2

---

keyboards/gmmk/pro/iso/keymaps/default/keymap.c

Fix encoder define in default keymap

[Keyboard] Fix default keymap for GMMK Pro Iso

---

keyboards/moonlander/matrix.c

Right hand is scanned through i2c which incurs some delay,
we can use this delay instead of sleeping when scanning the
left hand.
When the right hand isn't present fallback to sleep.
And stop trying to re-init right hand multiple times per scan.
I've been able to hit 380 matrix scans seconds
on moonlander mark I and more than 2000 scans per seconds with
right hand detached, without the change I measure it to be at
320 scans seconds in both cases.
This work it inspired by:
https://michael.stapelberg.ch/posts/2021-05-08-keyboard-input-latency-qmk-kinesis/
*

Moonlander Interlace both hands during matrix scan for faster performance

---

keyboards/keyprez/corgi/keymaps/default/keymap.c

Adds colemak option to the default keymap.
*

[Keymap] Add optional colemak layout

---

drivers/sensors/pmw3360.c

Debugging is good, but should only be reported *when* requested.  This changes it so tha the pmw3360 sensor code only outputs debugging info if `debug_mouse` is set to true.

Fix pmw3360 code to only output debug info if mouse debugging is enabled

---

quantum/process_keycode/process_combo.c

Fixes a couple of issues with `combo_disable` function calls.
The key buffer was not emptied when disabling combos; I had removed the `dump_key_buffer()` call as it could lead to infinite loops. Removing the call it seems wasn't the right move.
Now recursive calls to `dump_key_buffer` start from the next key instead of the key that is "currently being dumped" from the buffer.
Another issues with disabling combos was that any currently active combo wasn't released on key releases.
Now combo key releases are always handled, even if combo processing is disabled.
Easy way to test the current issues:
- create a combo that resolves to `LT(_LAYER, KC_X)`
- When changing to `_LAYER`, call `disable_combo()`
Then just hold the combo for a while to activate the layer. On release the layer stays on. …

Fix `combo_disable`

---

keyboards/frooastboard/config.h
keyboards/pistachio_pro/config.h

These keyboards were added to `master` recently. This brings our error count back to 0.
```
⚠ frooastboard: DEBOUNCE in config.h is overwriting debounce in info.json
⚠ frooastboard: DEVICE_VER in config.h is overwriting usb.device_ver in info.json
⚠ frooastboard: DIODE_DIRECTION in config.h is overwriting diode_direction in info.json
⚠ frooastboard: PRODUCT_ID in config.h is overwriting usb.pid in info.json
⚠ frooastboard: VENDOR_ID in config.h is overwriting usb.vid in info.json
⚠ frooastboard: Matrix pins are specified in both info.json and config.h, the config.h values win.
☒ pistachio_pro: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 11 != 18
```

Fix errors that have cropped up in develop

---

docs/config_options.md
docs/feature_split_keyboard.md
quantum/split_common/transaction_id_define.h
quantum/split_common/transactions.c
quantum/split_common/transport.h

This allows the OLED/ST7565 display on/off state to be synced between the halves.
Requires a define to enable.

Enable sync of OLED/ST7565 display on/off state on Splits

---

keyboards/splitkb/kyria/rev1/config.h
quantum/split_common/transaction_id_define.h
quantum/split_common/transactions.c
quantum/split_common/transport.h

Was using the wrong defines ...
Plus side, verified that even if the timeouts are different, it still works, and doesn't cause flickering or other weird behavior.

Fix ifdefs for OLED split sync code

---

lib/python/qmk/info.py

We have a fallback that searches for layout macros in non-standard places. It used to run when layouts were not defined in any C file. This changes it to run only if there are no layouts in info.json as well.

Defer the expensive search for layout macros until info.json has been processed

---

docs/feature_audio.md
quantum/audio/audio.c
quantum/quantum.c

#11553 changed the location that the audio startup code was called (eg the code that plays the startup chime), due to issues with timing issues with the suspend code for the board and the audio. 
Unfortunately, this can cause the startup sound to simply not play at all, or to play a note or two, but nothing else.  	Reverting the change fixes the issue, but then potentially re-introduces the previous issue. 
This adds a define that allows for users to choose between which situation, until a better fix can be found.

Fixup Audio startup and add to documents

---

tmk_core/common/avr/_wait.h

`wait_ms`/`wait_us` on AVR cannot handle dynamic values like the ChibiOS abstraction can.
This leads to code that bleeds implementation details outside of tmk_core. For example;
```c
#if defined(__AVR__)
for (uint16_t i = delay; i > 0; i--) {
wait_ms(1);
}
#else
wait_ms(delay);
#endif
```
Hopefully the `__builtin_constant_p` magic should catch a lot of the existing cases, limited testing shows the same firmware sizes.

Unify behaviour of wait on AVR

---

keyboards/handwired/dactyl/matrix.c
keyboards/handwired/pterodactyl/matrix.c

Change `wait_us(1000000)` to `wait_ms(1000)` in dactyl and pterodactyl keyboards to prevent overflowing of uint16.
* Tzarc CI

Fix wait_us overflow in matrix for dactyl based boards

---

keyboards/neson_design/n6/n6.c
keyboards/neson_design/n6/rules.mk

Fix the include/src paths for the ISSI drivers for the keyboard, due to changes on develop. 
* Tzarc CI

[Keyboard] Fixup Neson Design N6 ISSI includes

---

lib/python/qmk/cli/console.py
lib/python/qmk/cli/doctor/linux.py
util/udev/50-qmk.rules

[CLI] Add qmk-hid bootloader detection support to `qmk console`

---

keyboards/massdrop/ctrl/config_led.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.h

The indicator LED code in `md_rgb_matrix.c` wasn't built to handle the iterative behavior associated with RGB_MATRIX_LED_PROCESS_LIMIT, causing indicator LED behavior to be buggy (scroll lock broken on Drop CTRL, for example). Modernized the code to use `rgb_matrix_indicators_advanced` instead.
*

Fix Indicator LED issues with md_rgb_matrix.c

---

docs/feature_stenography.md
quantum/keymap_extras/keymap_steno.h
quantum/process_keycode/process_steno.c
quantum/quantum_keycodes.h

Makes it possible to press one key instead of trying to hit multiple keys with one finger when inputting steno graphical chords on a keyboard. For example see the second row in the keymap below, combining the key on the keyboard row above and below into one key.
Example layer (for planck) using the combined consonant keys.
`[0] = LAYOUT_ortho_4x12(
STN_FN,  STN_S1,  STN_TL,  STN_PL,  STN_HL,  STN_ST1, STN_ST3, STN_FR,  STN_PR,  STN_LR,  STN_TR,  STN_DR ,
STN_FN,  STN_S3,  STN_TKL,  STN_PWL,  STN_HRL,  STN_ST1, STN_ST3, STN_FRR,  STN_PBR,  STN_LGR,  STN_TSR,  STN_DZR ,
XXXXXXX, STN_S2,  STN_KL,  STN_WL,  STN_RL,  STN_ST2, STN_ST4, STN_RR,  STN_BR,  STN_GR,  STN_SR,  STN_ZR ,
TG(10), ST_BOLT,  ST_GEM, STN_NA,   STN_A,  STN_O,   STN_E,    STN_U, STN_NB, STN_PWR, STN_RE1, STN_RE2),
};`
* 
I …

Steno combinedkeys

---

keyboards/cest73/tkm/rules.mk
keyboards/massdrop/alt/config_led.c

Bugfix for #12097 breaking massdrop/alt.
Bugfix for #13939 breaking due to bootmagic full.

Fixup `massdrop/alt`, `cest73/tkm`.

---

tmk_core/native.mk
tmk_core/rules.mk

On Mac, clang errors out on some flags when attempting to run tests.
On Mac, clang errors out on some flags when attempting to run tests:
`clang: error: the clang compiler does not support '-funsigned-bitfields' [-Werror]`
`clang: error: optimization flag '-fno-inline-small-functions' is not supported [-Werror,-Wignored-optimization-argument]`
`clang: error: unsupported argument '-adhlns=.build/test_obj/eeprom_stm32/tmk_core/common/test/flash_stm32_mock.lst' to option 'Wa,'`
Steps to reproduce:
* On a system using clang, run `make test:debounce_sym_defer_g`
This change skips including a few non-compatible compiler flags when using clang.
*

Fix clang unit tests

---

docs/cli_commands.md
lib/python/qmk/cli/compile.py
lib/python/qmk/cli/flash.py
lib/python/qmk/cli/multibuild.py
lib/python/qmk/commands.py
message.mk
platforms/arm_atsam/flash.mk
platforms/avr/flash.mk
platforms/chibios/flash.mk

This PR has 2 improvements for `--parallel` support with make
1) `parallel` values less than 1 will now mean "unlimited" (see `make --help | grep -- --jobs`). This is not a breaking change, because currently non-positive `parallel` values fail with `make: the '-j' option requires a positive integer argument`.
2) If more than 1 job is used, the `--output-sync` option is also added. The stdout/stderr of each job will be collected by make and displayed synchronously, after each target is finished processing. This will fix #13707.
* #13707
(Not sure, if this is a "Core PR", so submiting it against `master` for now)
(Not sure if `qmk --help` counts as documentation and I didn't find any references to `--parallel` in the online docs)
(I updated the `qmk --help` for subcommands that have …

`--parallel` improvements

---

docs/keycodes_magic.md
quantum/process_keycode/process_magic.c
quantum/quantum_keycodes.h

[Title]
Also, it's still july, right?

Add a toggle key for GUI On/Off in Magic feature

---

build_keyboard.mk
quantum/main.c
tmk_core/common.mk
tmk_core/common/arm_atsam/platform.c
tmk_core/common/avr/platform.c
tmk_core/common/chibios/platform.c
tmk_core/common/test/platform.c
tmk_core/protocol/chibios.mk
tmk_core/protocol/chibios/chibios.c
tmk_core/protocol/lufa/lufa.c
tmk_core/protocol/vusb.mk
tmk_core/protocol/vusb/protocol.c

Right now this just creates a single `main()` entrypoint, with some stub functions to allow the initial abstraction of the main loop.
Further iterations should:
* Begin to move out more common code such as call sites to `keyboard_*`
* Abstract the handling of suspend
* Roll up the existing host driver and usb util API
*

Begin to carve out platform/protocol API - Single main loop

---

docs/feature_encoders.md
quantum/encoder.c

Sometimes, controller skips encoder pulses and when it returns to default position, the encoder_pulses variable isn't equals 0. And when I turn encoder in opposite direciton, it skips first click becase of encoder_pulses crosses zero. To prevent this, I add the ENCODER_DEFAULT_POS constant, and reset encoder_pulses into 0 when the state variable equals ENCODER_DEFAULT_POS.
*

Allow for removal of hysteresis on 4x encoders

---

keyboards/handwired/stream_cheap/2x4/2x4.h
keyboards/handwired/stream_cheap/2x4/config.h
keyboards/handwired/stream_cheap/2x4/keymaps/via/keymap.c
keyboards/handwired/stream_cheap/2x4/keymaps/via/rules.mk
keyboards/handwired/stream_cheap/2x4/rules.mk

Added VIA support for the Stream Cheap 2x4.
While doing this, I noticed that the existing pin definition for the Stream Cheap 2x4 seemed entirely arbitrary. I have fixed the pins so that they are in a logical order.
I did not touch the Stream Cheap 2x3 and 2x5 configurations as I do not have them to test on.
Nil

Fix pins, add VIA support for Stream Cheap 2x4

---

keyboards/helix/rev2/keymaps/fraanrosi/config.h

I'm against using RGBLIGHT_ANIMATIONS because this happens.
See also #8688.

[Keymap] fix helix:fraanrosi compile error caused by #13677.

---

docs/feature_dip_switch.md
docs/ja/feature_dip_switch.md
quantum/dip_switch.c

Added right vs left support for dip switch pin configuration
*

Added right vs left specific pin assignments for dip switch

---

keyboards/keebzdotnet/fme/fme.h
keyboards/keebzdotnet/fme/info.json
keyboards/keebzdotnet/fme/keymaps/default/keymap.c
keyboards/keebzdotnet/fme/keymaps/via/config.h
keyboards/keebzdotnet/fme/keymaps/via/keymap.c

* renames `LAYOUT` to `LAYOUT_all`
* adds `info.json` file
* override layer count on `via` keymap
cc @keebzdotnet (keyboard maintainer)

keebzdotnet F-Me Configurator fixes and codebase touch-up

---

drivers/sensors/pimoroni_trackball.c
drivers/sensors/pimoroni_trackball.h

This should function almost the same as the old driver. I've avoided the costly floating point calculation in the main loop and implemented throttling. The major difference being the x, y directions are swapped vs the original. (I was following the python library). This can be corrected with a couple of defines.
I don't have prior experience with the trackball on the old driver so some feedback on how it compares would be great. The throttling can be adjusted using the `TRACKBALL_INTERVAL_MS` define, it defaults to 8 (125hz). So likely worth playing with lower values on faster usb polling rates.
The mouse control feels pretty similar to the old driver but with the speed increase being so large it may outweigh the slight difference in feel. I've included a little log of the scan rate while …

[develop] Speed up pimoroni driver.

---

tmk_core/chibios.mk
tmk_core/common/chibios/_wait.c
tmk_core/common/chibios/_wait.h
tmk_core/common/chibios/wait.c

There are spare GPT timers that can be used to get a more accurate wait_ms() time. This is required for the matrix scan unselect delay (30µs) to be shorter than the system tick rate of 100µs.
This is limited to the maximum GPT duration of 65535 so values above that will automatically use the previous implementation based on the system tick.
Using a specific timer means it can't be shared by another thread at the same time so when wait_us() is called from anything other than the main thread it will use the system tick implementation too.
* Fixes #12198 
Tested with a Durgod K320: https://github.com/nomis/qmk_firmware/compare/wait_us_timer...wait_us_timer_durgod_k320
* Original scan rate: 625Hz
* Improved scan rate: 1700-1800Hz
* Scan rate with LTO enabled: 2kHz

Support using a timer for wait_us() on ChibiOS-based boards

---

quantum/led_matrix/led_matrix.c
quantum/rgb_matrix/rgb_matrix.c

Since RGB Matrix's task was moved from `matrix_scan` to `keyboard_task`, the suspend functionally  was broken.  This is because the LED array is never flushed to the LEDs, since the keyboard task loops while suspended, and never hits the rgb matrix task. 
This fixes the suspend `set_suspend_state` function by forcing an update to the LEDs (using the "none" effect, which renders the LEDs off), and then forcibly flushes the data to the LEDs, so that they actually turn off. This happens as part of the suspend loop, and should only be called the first cycle.
* https://discord.com/channels/440868230475677696/867530715192885269/878113349957713960
* Contains the actual issue and a bit more technical detail

[Bug] Fix RGB/LED Matrix Suspend code

---

lib/python/qmk/info.py

The call to `_merge_layouts` was replaced at some point and is no longer called. The downside is this now allows bad `info.json` files to slip through.
Note the extra random keys on the right.
This restores the previous behaviour producing the following error:
```console
☒ cest73/tkm: cest73/tkm: LAYOUT_all: Number of elements in info.json does not match! info.json:105 != LAYOUT_all:110
```
If the new rendering behaviour is desired, then it might be worth still printing out the error. (And maybe a follow up PR to make the rendering put the extra matrix positions not miles to the right).
* <https://discord.com/channels/440868230475677696/440875445911683084/877671832529027182>

Restore layout count validation

---

quantum/bootmagic/bootmagic_lite.c
quantum/eeconfig.c
quantum/keyboard.c
quantum/quantum.c
quantum/via.c
quantum/via.h

VIA EEPROM checks and initialization isn't touched by `eeconfig_init`.  So, it's possible that it can be ignore.  This actively happens when the EEP_RST key is hit, as well as full bootmagic's eeprom reset.
* issue reported on discord

Fix issues with VIA EEPROM initialization and bring more in line with rest of eeconfig functionality

---

drivers/sensors/pmw3360.c
drivers/sensors/pmw3360.h
keyboards/handwired/tractyl_manuform/4x6_right/config.h
keyboards/handwired/tractyl_manuform/5x6_right/config.h
keyboards/ploopyco/mouse/config.h
keyboards/ploopyco/trackball/config.h

Title.
Allows it to be compiled for AVR or ARM.

Improve pmw3360 sensor and make it more hardware agnostic

---

drivers/sensors/pmw3360.h

Wrong define used for ARM config on pmw3360 sensor.  whoops. 
* Tzarc CI

[Core] Fix copypasta issue with pmw3360 sensor config

---

keyboards/handwired/tractyl_manuform/4x6_right/config.h
keyboards/handwired/tractyl_manuform/4x6_right/keymaps/drashna/keymap.c
keyboards/handwired/tractyl_manuform/5x6_right/config.h
keyboards/handwired/tractyl_manuform/config.h

Fix a couple of compile issues with keyboard. 
* wrong type in `process_record_mouse`
* Move config defines to root keyboard config
There is an issue with the pmw3360 code, but I figured that was better as a separate PR. 
* Tzarc CI

[Keyboard] Fix compile issues for Tractyl Manuform

---

keyboards/keebio/quefrency/keymaps/via/rules.mk
keyboards/keebio/quefrency/rev2/config.h
keyboards/keebio/quefrency/rev3/config.h

Console was enabled by default on VIA keymap. Not needed here, so lets disabled.
Also remove lock key syncing support because ... it saves a bit more. 
* Tzarc CI

[Keyboard] Disable Console on Keebio Quefrency

---

tmk_core/arm_atsam.mk

Add deprecation warning during build when building a board that uses arm_atsam.

Warn when building a board that uses arm_atsam

---

tmk_core/protocol/lufa/lufa.c

Noticed an issue compiling the joystick keymap for the onekey/promicro. Seems to be a typo from #12819.

[develop] Fix typo for joystick on avr. 

---

quantum/keymap_extras/keymap_us_extended.h
quantum/keymap_extras/keymap_us_international_linux.h

`US_RDQU` and `US_LDQU` were aliased to the same keycode. `US_RDQU` should use the right bracket.
*

Fix US_RDQU keycode

---

common_features.mk
tmk_core/common.mk

Specifically, if you enable the shared endpoint for mouse reports (or keyboard, which force enables it for mouse), and you don't have mousekeys enabled, it does not properly enable shared mouse EP for pointing device (which uses mouse reports).   This cause it to error out in compiling.  This fixes up some of the logic to ensure that all use cases are supported, and consolidates some of the code.
Honestly, I'm surprised that I didn't run into this before.  But ... wasn't running a blackpill before, so wasn't as much of a concern. 
* Compilation error when MOUSE_SHARED_EP or KEYBOARD_SHARED_EP are enabled, and POINTING_DEVICE_ENABLE is set, but mousekeys are not turned on.

Fix Mouse Shared EP functionality

---

keyboards/checkerboards/quark_squared/keymaps/default/keymap.c

[Keyboard] Fix default keymap for quark squared keyboard

---

keyboards/handwired/tractyl_manuform/5x6_right/config.h
keyboards/handwired/tractyl_manuform/5x6_right/f411/config.h
keyboards/handwired/tractyl_manuform/5x6_right/teensy2pp/config.h
layouts/community/ortho_4x12/drashna/keymap.c
users/drashna/drashna.c
users/drashna/drashna.h
users/drashna/transport_sync.c

[Keymap] Drashna keymap fixups

---

quantum/action.c
quantum/action.h
quantum/action_tapping.c
quantum/keymap_common.c
quantum/quantum.c
quantum/quantum.h

Align the locations of some quantum.c content

---

data/mappings/keyboard_aliases.json
docs/ChangeLog/20210828.md
docs/breaking_changes.md
docs/breaking_changes_history.md

* Adds changelog
* Adds keyboard aliases
* Bumps ChibiOS-Contrib

2021Q3 pre-merge `develop` changelog, keyboard aliases

---

lib/python/qmk/cli/lint.py

As part of what we discussed in #8422 this adds a check for keyboard level `rules.mk` files to ensure that only assignment rules are present. We can change the name to whatever we decide on in.

Add check for non-assignment code in rules.mk

---

lib/python/qmk/cli/lint.py

The recent improvements to `qmk lint` inadvertently broke the directory detection.

Fix automatic directory for qmk lint

---

keyboards/helix/rev2/local_features.mk

Some keymaps on the Helix keyboard have not yet been migrated to the standard OLED driver. Therefore, running `make helix/rev2/sc:all` will result in a compilation error on some keymaps.
The following changes are tentatively made to avoid compilation errors.
```diff
diff --git a/keyboards/helix/rev2/local_features.mk b/keyboards/helix/rev2/local_features.mk
index 47e8c6a83e..8c3ac9c3c1 100644
--- a/keyboards/helix/rev2/local_features.mk
+++ b/keyboards/helix/rev2/local_features.mk
@@ -164,6 +164,16 @@ ifeq ($(strip $(OLED_ENABLE)), yes)
OPT_DEFS += -DOLED_FONT_H=\"common/glcdfont.c\"
endif
else
+        ifeq ($(strip $(SPLIT_KEYBOARD)), yes)
+            $(info Helix/rev2: The following combinations are not supported.)
+            $(info - SPLIT_KEYBOARD = $(SPLIT_KEYBOARD)) # yes
+ …
```

[Keyboard] fix compile error `make helix/rev2/sc:all`

---

shell.nix
util/nix/poetry.lock
util/nix/pyproject.toml

Update the `nix-shell` environment:
- Update the `qmk` Python package to 1.0.0. Now this is actually required (after the recent develop merge the current master no longer builds with an obsolete QMK CLI version pulled by the old shell.nix).
- Apply the fix from https://github.com/qmk/qmk_firmware/pull/12855#issuecomment-853993792, so that `qmk doctor` and `qmk pytest` would work properly (actually `qmk doctor` works even without the fix, but only because it happens to ignore the failure).
Cc: @purcell
* #13226 (actually this should have been fixed by #12855, but with this PR even some more obscure commands like `qmk pytest` should be working too).

Update the nix-shell environment

---

.github/workflows/api.yml
.github/workflows/cli.yml
.github/workflows/develop_api.yml
.github/workflows/docs.yml
.github/workflows/format.yaml
.github/workflows/lint.yml
Dockerfile
Vagrantfile
docs/getting_started_vagrant.md
docs/ja/getting_started_vagrant.md
util/docker_build.sh
util/vagrant/Dockerfile
util/vagrant/readme.md

As part of deprecating `qmkfm/qmk_firmware` we want to move everything over to the `qmkfm/qmk_cli` container.

Move everything from qmkfm/base_container to qmkfm/qmk_cli

---

lib/python/qmk/cli/__init__.py

When the user is using `qmk` inside a virtualenv that has not been activated the directory that `sys.executable` is in (which usually contains other tools we need like `flake8` and `nose2`) may not be in the user's search path. This happens with our Debian/Ubuntu/Fedora packages, for example.
This PR ensures that the user's path will include the directory containing `sys.executable`.

Ensure that the directory for sys.executable is in the user's path

---

quantum/process_keycode/process_haptic.c

Without this build would fail, if a keyboard had haptic feedback enabled,
TAPPING_TOGGLE was not overridden in a config.h, and if NO_HAPTIC_MOD was
defined in config.h.
*

Fix build error when enabling NO_HAPTIC_MOD

---

quantum/quantum.c
tmk_core/common/avr/suspend.c
tmk_core/common/chibios/suspend.c
tmk_core/common/suspend.h

While looking to add OLED suspend support, noticed that a LOT of feature suspend code is duplicated in `tmk_core/common/(platform)/suspend.c`.  
Moves out that code into quantum.c to be a common location for easier management.
And added oled/st7565 suspend support, too. 
I'm not sure I like dumping it in quantum.c, but ...

Move feature suspend logic out of platform specific code

---

platforms/chibios/drivers/ws2812_spi.c

change the define name of WS2812_SPI_DIVISOR for chibios
* When customizing WS2812_SPI_DIVISOR, an error will be reported for redefined. Add a suffix to fix this bug to allow users to customize the spi frequency.

[Bug] Fix the bug that  chibios ws2812 spi divisor cannot be customized define

---

tmk_core/common/chibios/eeprom_stm32.c
tmk_core/common/chibios/flash_stm32.c
tmk_core/common/chibios/flash_stm32.h
tmk_core/common/test/flash_stm32_mock.c

Minor tidy up of STM EEPROM emulation

---

keyboards/helix/pico/keymaps/biacco/rules.mk
keyboards/helix/pico/keymaps/default/rules.mk
keyboards/helix/pico/keymaps/mtei/rules.mk
keyboards/helix/pico/post_rules.mk
keyboards/helix/pico/rules.mk
keyboards/helix/rev2/keymaps/default/rules.mk
keyboards/helix/rev2/keymaps/five_rows/rules.mk
keyboards/helix/rev2/keymaps/five_rows_jis/rules.mk
keyboards/helix/rev2/keymaps/fraanrosi/rules.mk
keyboards/helix/rev2/keymaps/froggy/rules.mk
keyboards/helix/rev2/keymaps/froggy_106/rules.mk
keyboards/helix/rev2/keymaps/led_test/rules.mk
keyboards/helix/rev2/keymaps/yshrsmz/rules.mk
keyboards/helix/rev2/post_rules.mk

Helix/pico and Helix/rev2 change to use `post_rules.mk`.

[Keyboard] Helix use `post_rules.mk`

---

keyboards/handwired/symmetric70_proto/post_rules.mk
keyboards/handwired/symmetric70_proto/promicro/fast/rules.mk
keyboards/handwired/symmetric70_proto/promicro/normal/rules.mk
keyboards/handwired/symmetric70_proto/proton_c/fast/rules.mk
keyboards/handwired/symmetric70_proto/proton_c/normal/rules.mk

handwired/symmetric70_proto change to use post_rules.mk.

[Keyboard] Symmetric70_proto use `post_rules.mk`

---

keyboards/keebio/iris/rev5/rules.mk

Disable the console, to make small enough to compile under size.
* Tzarc CI

[Keyboard] Disable console on Iris Rev5

---

docs/feature_velocikey.md

Added syntax highlighting for the required keycode to toggle the velocikey feature.
Added syntax highlighting for the required keycode.
This should make it consistent with other docs and hopefully will make less people miss this detail.

Docs: Velocikey: Highlight keycode

---

keyboards/bpiphany/pegasushoof/2015/matrix.c
keyboards/handwired/datahand/matrix.c
keyboards/keyboardio/model01/matrix.c
keyboards/matrix/noah/matrix.c
keyboards/ymdk/sp64/matrix.c

user functions were removed in #14312, but they weren't in the matrix.c for boards with full custom matrix.  So they are erroring out. 
* #14312 and tzarc CI

[Bug] Fix compile issues for boards with custom matrix

---

keyboards/3w6/rev2/matrix.c

Fix some casting for i2c commands. 
Reverts change to select_row, as

[Keyboard] Fix issues with 3w6 rev2 matrix

---

platforms/avr/drivers/analog.c
platforms/avr/drivers/analog.h

This was deprecated a few cycles ago, in favour of `analogReadPin()` which takes a QMK-style pin. There are no more usages in the repo.
*

Remove Arduino-style `analogRead()`

---

keyboards/reviung39/keymaps/via/keymap.c
keyboards/reviung39/keymaps/via/rules.mk

I based this upon the reviung41 via keymap that is in our code base but used `reviung39/keymaps/default` as the base instead.
Thanks.
*

[Keyboard] Add VIA keymap for the reviung39

---

common_features.mk
docs/feature_joystick.md
keyboards/handwired/onekey/keymaps/joystick/rules.mk

If `JOYSTICK_ENABLE = analog` is set at keyboard level, things like `qmk info` will complain about it:
```
☒ Invalid API data: handwired/onekey/promicro: features.joystick: 'analog' is not of type 'boolean'
```
So it has been split up into `_ENABLE` and `_DRIVER` settings, defaulting to `analog`. The documentation has been updated to reflect the new usage.
*

Bugfix for Joystick and JSON schema

---

quantum/keyboard.c

While implementing a custom timeout rule I stumbled upon the fact that `OLED_TIMEOUT 0` and `OLED_DISABLE_TIMEOUT` are not equivalent.
As far as I can tell this should be the case tho, at least [oled_driver.h#L150](https://github.com/qmk/qmk_firmware/blob/master/drivers/oled/oled_driver.h#L150) indicates so. Feel free to close this pr if I am misunderstanding something here.

`OLED_TIMEOUT 0` and `OLED_DISABLE_TIMEOUT` should behave the same

---

quantum/keyboard.c

Like in https://github.com/qmk/qmk_firmware/pull/14302, `ST7565_TIMEOUT 0` and `ST7565_DISABLE_TIMEOUT` are not equivalent.
I did not notice yesterday that the same problem exists for the ST7565 LCD driver.

`ST7565_TIMEOUT 0` and `ST7565_DISABLE_TIMEOUT` should behave the same

---

tmk_core/protocol/lufa/lufa.c

Adds support for boards running at 3.3V and crystal at 16 MHz (like the system76), or a [modded teensy](https://www.pjrc.com/teensy/3volt.html). 
There are a few boards that are doing this in the repo, doing this manually.

Backport F_CPU/F_USB hack from system76

---

keyboards/atreus62/rules.mk
keyboards/bantam44/rules.mk
keyboards/chimera_ergo/rules.mk
keyboards/chimera_ls/rules.mk
keyboards/chimera_ortho/rules.mk
keyboards/comet46/rules.mk
keyboards/dichotomy/rules.mk
keyboards/gh60/revc/rules.mk
keyboards/handwired/retro_refit/rules.mk
keyboards/hhkb/ansi/rules.mk
keyboards/hhkb/jp/rules.mk
keyboards/honeycomb/rules.mk
keyboards/jd40/rules.mk
keyboards/mitosis/rules.mk
keyboards/numatreus/rules.mk
keyboards/ok60/rules.mk
keyboards/redox_w/rules.mk

Starting cleanup of Bluetooth config system. `BLUETOOTH_ENABLE` will be removed from all keyboard `rules.mk`s and defaultish keymaps where it is `no`.
*

Remove commented out BLUETOOTH_ENABLE rules

---

quantum/action.c
quantum/action.h
quantum/process_keycode/process_tap_dance.c

This adds a wait before the `unregister_code16` in tap dances, so that it respects the tap code delay for media key compatibility. 
Also, this moves the tap code delay defines to action.h, so that they're picked up most everywhere, rather than just in action.c, in case they're not actually defined.
* Fixes #5262  and https://discord.com/channels/440868230475677696/869812721552601088/886583370795065354

Apply `TAP_CODE_DELAY` to Tap Dance key sequences

---

drivers/led/apa102.c
platforms/chibios/drivers/serial.c
platforms/chibios/drivers/ws2812.c
platforms/chibios/drivers/ws2812_pwm.c
tmk_core/common/chibios/_wait.h
tmk_core/common/chibios/chibios_config.h

Small steps to remove some of the STM specific notions within the ChibiOS part of the codebase.

Refactor use of STM32_SYSCLK

---

docs/audio_driver.md
docs/cli_development.md
docs/configurator_default_keymaps.md
docs/custom_matrix.md
docs/faq_debug.md
docs/feature_backlight.md
docs/feature_bluetooth.md
docs/feature_digitizer.md
docs/feature_joystick.md
docs/feature_layouts.md
docs/feature_midi.md
docs/feature_pointing_device.md
docs/feature_ps2_mouse.md
docs/feature_rawhid.md
docs/feature_rgb_matrix.md
docs/feature_stenography.md
docs/feature_swap_hands.md
docs/feature_userspace.md
docs/flashing_bootloadhid.md
docs/getting_started_docker.md
docs/getting_started_vagrant.md
docs/hardware_keyboard_guidelines.md
docs/how_keyboards_work.md
docs/newbs_git_resynchronize_a_branch.md
docs/unit_testing.md

In particular Docsify doesn't seem to like the capital C in the `feature_rawhid.md` code blocks.
*

[Docs] Clean up some code block languages

---

keyboards/sofle/keymaps/via/config.h

Added VIA support for the top facing RGB LEDs on top of the existing underglow.
*

VIA support with top facing LEDs and underglow

---

common_features.mk
keyboards/mxss/rgblight.c
quantum/eeconfig.c
quantum/keyboard.c
tmk_core/common/chibios/eeprom_stm32.c
tmk_core/common/test/rules.mk

Avoids `STM32_EEPROM_ENABLE` becoming a template when adding new MCU support, while also making the API a little more uniform.

Migrate STM32_EEPROM_ENABLE to use EEPROM_DRIVER

---

keyboards/kbdfans/boop65/rgb/config.h

`IS31FL3741` requires 2 addresses to be defined.

[Keyboard] Fix Boop65 rgb compile issues

---

common_features.mk
platforms/chibios/boards/common/ld/STM32F401xC.ld
platforms/chibios/boards/common/ld/STM32F411xE.ld
tmk_core/common/chibios/eeprom_stm32_defs.h
tmk_core/common/chibios/flash_stm32.c

Enable EEPROM emulation on  F401/F411

---

drivers/led/issi/is31fl3741.c
drivers/led/issi/is31fl3741.h
keyboards/kbdfans/boop65/rgb/config.h
quantum/rgb_matrix/rgb_matrix_drivers.c

This fixes the IS31fl3741 driver so that it will accept just a single address without failing to compile. 
Also reverts the change to the boop65 board to get it compiling. 
* Also closes #14443

[Bug] Fix IS31fl3741 driver to accept 1 or 2 addresses

---

tmk_core/protocol/lufa/lufa.c

core: fix compilation issues with USB programmable buttons

---

tmk_core/protocol/usb_descriptor.c

Use the correct value in the descriptor.
I think I only looked at the raw reports during testing and those are correct.
*

[Bug] Fix descriptor for USB Programmable Buttons

---

keyboards/helix/rev2/keymaps/five_rows/config.h
keyboards/helix/rev2/keymaps/five_rows/matrix_output_unselect_delay.c
keyboards/helix/rev2/keymaps/five_rows/oled_display.c
keyboards/helix/rev2/keymaps/five_rows/rules.mk
keyboards/helix/rev3_5rows/keymaps/five_rows/config.h
keyboards/helix/rev3_5rows/keymaps/five_rows/matrix_output_unselect_delay.c
keyboards/helix/rev3_5rows/keymaps/five_rows/oled_display.c
keyboards/helix/rev3_5rows/keymaps/five_rows/rules.mk

Update helix rev2 and rev3 keymap 'five_rows'.
*  Stop using snprintf() in keymaps/five_rows/oled_display.c.
The binary size becomes 1350 bytes smaller.
* add matrix scan rate display to OLED.
* add matrix_output_unselect_delay.c.

[Keymap] Update Helix:five_rows OLED code

---

platforms/chibios/boards/QMK_PROTON_C/configs/config.h

I2C config was updated for ChibiOS, and it breaks the CTPC compatibility.
This adds a default define that is override-able, but should work with the rest of the default config. 
I'm not sure this is the best way to handle this, though.

Add i2c defaults for Convert to Proton C

---

keyboards/mode/m65s/config.h
keyboards/mode/m65s/rules.mk

Enables extra keys, disables console, adds tap code delay allowing for media keys on Mode 65S.
*

Media keys on Mode 65S

---

keyboards/massdrop/ctrl/keymaps/r-pufky/config.h
keyboards/massdrop/ctrl/keymaps/r-pufky/keymap.c
keyboards/massdrop/ctrl/keymaps/r-pufky/readme.md

Update massdrop/ctrl:r-pufky with gaming layer, LED color change based on state.
* Added gaming layer
* Added `layer_state_set_user` to set backlight color based on current state
* Defined custom red, blue colors in `config.h`
* Update documentation with new image links and button mapping
* Corrected whitespace issues
* None.

Add gaming toggle layer & layer colors to r-pufky keymap.

---

keyboards/moonlander/halconf.h
keyboards/moonlander/mcuconf.h
keyboards/moonlander/rules.mk

The Moonlander does not use a Proton C, and shouldn't use the configuration from it. 
This removes the board type, and manually specifies the hardware config, properly.  No functionality change has occurred.

[Keyboard] Move Moonlander off 'Proton C' board

---

keyboards/planck/ez/halconf.h
keyboards/planck/ez/mcuconf.h
keyboards/planck/ez/rules.mk

Moves the Planck Z off of the Proton C board config, and onto the STM32F303 board definitions, since this doesn't actually use a proton C.
Functionality is not changed.

[Keyboard] Move Planck EZ off 'Proton C' board

---

keyboards/helix/rev3_5rows/keymaps/five_rows/oled_display.c

This is a tentative quick fix.
I was adding the same functions for both #14426 and #14427 and they were in conflict.

[Keymap] Fix link error for helix/rev3_5rows:five_rows

---

keyboards/sofle/keymaps/j4ckofalltrades/encoder.c
keyboards/sofle/keymaps/j4ckofalltrades/keymap.c
keyboards/sofle/keymaps/j4ckofalltrades/oled.c
keyboards/sofle/keymaps/j4ckofalltrades/readme.md
keyboards/sofle/keymaps/j4ckofalltrades/rules.mk

Modified version of default Via-compatible keymap with focus on adding a standard navigation cluster layer
plus some Vim-inspired features e.g. soft escape (Esc when held, Ctrl when tapped), using 'h', 'j', 'k', 'l' as arrow keys.
*

Add custom keymap 'j4ckofalltrades' for sofle/rev1

---

quantum/matrix.c

Continuing from #13523.
First, a slight cleanup of how the slave matrix is copied to the master matrix. Now using `memcmp`, `memcpy` and `memset`, as suggested by @KarlK90 in comments in the above mentioned PR.
Secondly, fixes an issue with `matrix_post_scan` signalling a matrix change on every scan cycle while disconnected, causing issues with (at least) OLED timeouts.

Improvements to handling of disconnected split keyboards.

---

keyboards/gmmk/pro/ansi/keymaps/benschaeff/keymap.c

Pretty simple keymap with a few handy tools on a 2nd layer and rotary encoder.
- Holding tab and scrolling encoder will allow scrolling through applications, as if using alt + tab
- Holding ctrl and scrolling encoder will allow scrolling through chrome tabs
- FN + Encoder scroll is media next/prev
- FN + Encoder press is media pause
- default encoder behavior is volume up/down
- FN + \ is used to put keyboard into bootloader mode
- FN + ESC is the same as alt F4, for closing applications
- FN + F1 is to close current browser tab
- FN + Q moves current application one monitor to the left
- FN + W maximizes current application
- FN + E moves current application one monitor to the right
- FN + S minimizes current application
- FN + F is used in junction with the "Popout tab" extension to …

GMMK Pro keymap

---

keyboards/planck/rev6_drop/halconf.h
keyboards/planck/rev6_drop/matrix.c
keyboards/planck/rev6_drop/mcuconf.h
keyboards/preonic/rev3_drop/halconf.h
keyboards/preonic/rev3_drop/matrix.c
keyboards/preonic/rev3_drop/mcuconf.h

Builds on #14510, adding the Chibios options to enable I2C (like the normal `rev*` boards), with the help of @Cipulot testing out the Preonic version on hardware.
* Reports by @Cipulot on Discord

Enables I2C for OLKB rev*_drop boards

---

keyboards/planck/rev6_drop/matrix.c
keyboards/preonic/rev3_drop/matrix.c

It was pointed out in discord that compiling these versions with `CONSOLE_ENABLE = no` it results in an error. I don't have hardware to test these changes but it does compile now.
I also noticed these don't use `BOARD = QMK_PROTON_C` like the previous ones, same person had problems using I2C on the drop version vs the original revs. Judging from recent PRs moving stuff away from the PROTON C as a base I didn't change it.

[Bugfix] Fix revX_drop compilation when console is disabled.

---

keyboards/ckeys/thedora/info.json
keyboards/ckeys/thedora/keymaps/default/config.h
keyboards/ckeys/thedora/keymaps/default/keymap.c
keyboards/ckeys/thedora/keymaps/default/readme.md
keyboards/ckeys/thedora/readme.md
keyboards/ckeys/thedora/rules.mk
keyboards/ckeys/thedora/thedora.c
keyboards/ckeys/thedora/thedora.h

* rearranges the layout macro to resemble the assembled board
* switches `thedora.h`/`info.json` to use QMK's 3-character notation for matrix position identifiers (`k<row><column>`)
* fixes a broken layout macro reference in `info.json`
* convert default keymap to use four-space indent
* remove `config.h` and `readme.md` from default keymap (they were effectively blank)
* add `encoder_update_kb()` to `thedora.c` (adds encoder functionality to firmware compiled through QMK Configurator)
* adds license headers
* minor touch-up on keyboard readme
* update `rules.mk` to conform to QMK's template
cc @brandenbyers (keyboard maintainer)

cKeys theDora Refactor

---

docs/custom_quantum_functions.md
keyboards/rgbkb/mun/keymaps/xulkal2/keymap.c
keyboards/rgbkb/mun/keymaps/xulkal2/rules.mk
keyboards/rgbkb/mun/matrix.c
keyboards/rgbkb/mun/rules.mk

Fixed documentation for `Low-level Matrix Overrides` as the function names were reversed from actual code usage.
Fixed Mun's custom fast matrix scanning.
*

Doc Fixes & Mun Custom Matrix Fix

---

lib/python/qmk/cli/generate/compilation_database.py

Modifies the logic of the compiledb generator to actually request from gcc the list of include directories it's going to use.
The original logic was injecting mingw32 directories for me -- this correctly handles the generation based on the toolchain in question.
Tested on both AVR and ARM.

compiledb: query include paths from gcc directly.

---

keyboards/bioi/ble.c
keyboards/bioi/main.c

Fixes an issue in develop due to the BIOI keyboards using a custom Bluetooth implementation - now that `outputselect.[ch]` have been moved to `drivers/bluetooth/` they are not visible to the compiler by default.
Nothing from `outputselect.h` is used anyway, so it is fine to remove.
```
bioi/g60:default
bioi/g60:via
bioi/morgan65:default
bioi/morgan65:via
```

Remove outputselect.h include from BIOI code

---

quantum/process_keycode/process_unicode_common.c

Adds an option `UNICODE_UC_WIN_USE_NUMPAD_IF_POSSIBLE` to use the numpad for entering digits 0-9 of a hexadecimal unicode codepoint for unicode mode `UC_WIN`, improving reliability of this unicode mode on Windows.
On Windows, if using the `UC_WIN` unicode mode, reliability of the alt entry succeeding is improved by using the numpad for entering the 0-9 digits of a hex code under numlock. This is because fewer apps hook alt+numpad digits for custom shortcuts. Of course this method of unicode entry still has issues if e.g. apps use menu mnemonics, though if they are disabled in for example VSCode the alt method becomes reliable if using the numpad instead of regular number keys.
The downside of this method is that numlock is required, thus entering a unicode character this way would make …

Add option to use numpad for digits entry for unicode mode UC_WIN

---

keyboards/kinesis/kint2pp/config.h
keyboards/kinesis/kint36/config.h
keyboards/kinesis/kint41/config.h

All generations of Teensy microcontrollers stay below (or at) the 100mA mark.
This makes the controllers work in tight power budgets, e.g. when connected to a
USB hub.

Set USB max power consumption of kint* controllers to 100mA

---

keyboards/smallkeyboard/smallkeyboard.c

Didn't catch the lack of `__flash` in the rgb matrix config for the `smallkeyboard`
* Tzarc CI

[Keyboard] smallkeyboard fix of rgb matrix config

---

keyboards/splitkb/kyria/keymaps/default/keymap.c

The OLED and rotary encoder code was moved from the contents of the `keyboards/splitkb/kyria/keymaps/default/keymap.c` file to `keyboards/splitkb/kyria/rev1/rev1.c` in order to keep the default functionality of these hardware features for online QMK configurator users but that move is confusing many Kyria users who can't find where is the code for the OLEDs and rotary encoders so that they can modify it.
Some find the source in `rev1/rev1.c` but they often end up editing this keyboard-level file instead of overriding the functions in their keymap. This is not the way it should be done. A keyboard user shouldn't feel compelled to change keyboard level files in order to fit with their newly made keymap.
My proposed solution is to copy the code from `rev1/rev1.c` without the `__weak__` …

Add a commented copy of OLED and rotary code in default Kyria

---

keyboards/boston/config.h

The original IDs (0xAC11 for Vendor ID and 0x4175 for Product ID) was identical to the Acheron (Driftmechanics) Austin, which was causing it to be mistakenly recognized as an Austin when VIA was open, even though Boston does not currently support VIA.
*

Changed VENDOR_ID and PRODUCT_ID to no longer be identical to the Acheron (Driftmechanics) Austin 

---

keyboards/jadookb/jkb65/config.h
keyboards/jadookb/jkb65/info.json
keyboards/jadookb/jkb65/jkb65.c
keyboards/jadookb/jkb65/keymaps/default/keymap.c
keyboards/jadookb/jkb65/keymaps/via/keymap.c

Keyboard is configured for RGB Matrix, but had RGB LIght code.  Didn't realize that until reviewing compilation issues.
Also, inconsistent layout macros. 
* Tzarc CI

[Keyboard] Fix jkb65 compile issues

---

keyboards/smallkeyboard/rules.mk

Is compiling over size, and forgot to check on avr gcc 5. 
* Tzarc CI

[Keyboard] Disable console on Smallkeyboard

---

keyboards/draytronics/elise_v2/keymaps/default/keymap.c

Fixed errant NUBS keycode, as well as some random characters at the end of the keymap array. 
* Tzarc CI

[Keyboard] Fix default keymap for Draytronics Elise V2 keyboard

---

keyboards/canary/canary60rgb/v1/rules.mk
keyboards/handwired/slash/rules.mk
keyboards/kiwikeebs/macro_v2/rules.mk
keyboards/kprepublic/bm43hsrgb/rules.mk
keyboards/mode/m65s/rules.mk
keyboards/mokey/mokey63/rules.mk
keyboards/nix_studio/oxalys80/rules.mk

Except where `BLUETOOTH_ENABLE` is `yes` or `BLUETOOTH` is set - those few will eventually (in develop) be changed to eg.
```makefile
BLUETOOTH_ENABLE = yes
BLUETOOTH_DRIVER = AdafruitBLE|RN42
```

Remove BLUETOOTH_ENABLE from keyboard-level rules.mk (2021-09-22)

---

keyboards/handwired/aek64/config.h
keyboards/handwired/aek64/keymaps/4sstylz/config.h
keyboards/handwired/aek64/keymaps/4sstylz/rules.mk
keyboards/handwired/aek64/rules.mk
keyboards/maxr1998/phoebe/rules.mk
keyboards/uranuma/rules.mk

Combos currently cannot be enabled at keyboard level, as it requires custom code that the Configurator doesn't generate.
@4sStylZ this lightly touches your AEK64 keymap.
*

Remove keyboard-level `COMBO_ENABLE` rules

---

keyboards/dyz/dyz40/config.h
keyboards/dyz/dyz40/dyz40.c
keyboards/dyz/dyz40/dyz40.h
keyboards/dyz/dyz40/info.json
keyboards/dyz/dyz40/keymaps/default/keymap.c
keyboards/dyz/dyz40/keymaps/via/keymap.c
keyboards/dyz/dyz40/keymaps/via/rules.mk
keyboards/dyz/dyz40/readme.md
keyboards/dyz/dyz40/rules.mk

40% 13u hotswap with multiple layouts for bottom row
* Keyboard Maintainer: [dayatz](https://github.com/dayatz)
* Hardware Supported: dyz40, ATMega32u4
* Hardware Availability: Local Indonesia GB.
Make example for this keyboard (after setting up your build environment):
make dyz/dyz40:default
Flashing example for this keyboard:
make dyz/dyz40:default:flash
See the [build environment setup](https://docs.qmk.fm/#/getting_started_build_tools) and the [make instructions](https://docs.qmk.fm/#/getting_started_make_guide) for more information. Brand new to QMK? Start with our [Complete Newbs Guide](https://docs.qmk.fm/#/newbs).

add keyboard dyz40

---

quantum/audio/song_list.h

This appears to not be an issue with avr-gcc 5.  May have been fixed with the binaries, not sure. 
But appears to be safe to remove.

Remove GCC version check from song list inclusion

---

keyboards/metamechs/timberwolf/config.h
keyboards/mint60/config.h
keyboards/miuni32/config.h
keyboards/snampad/config.h

gcc doesn't like double comment....
```
Compiling: quantum/action_macro.c                                                                  In file included from <command-line>:0:0:
./keyboards/metamechs/timberwolf/config.h:99:1: error: "/*" within comment [-Werror=comment]
/*
^
[ERRORS]
| 
| 
| 
gmake[1]: *** [tmk_core/rules.mk:443: .build/obj_metamechs_timberwolf_default/quantum/action_macro.o] Error 1
```
* Tzarc CI

[Keyboard] Fix double comment in config files

---

keyboards/zinc/keymaps/default/rules.mk
keyboards/zinc/keymaps/ginjake/rules.mk
keyboards/zinc/keymaps/monks/rules.mk
keyboards/zinc/keymaps/toshi0383/rules.mk

Removing the `Link_Time_Optimization` rule in favour of the core `LTO_ENABLE` rule.
@ginjake @monksoffunk @toshi0383
*

Zinc: Clean up LTO rules

---

keyboards/preonic/keymaps/arkag/keymap.c
users/arkag/arkag.c

Added a new leader sequence and modified my keymap slightly.
* N/A

arkag userspace/keymap -- new macro and minor preonic keymap change

---

tmk_core/common/arm_atsam/eeprom.c

Use SAMD51 virtual eeprom to store eeprom in nvm instead of ram buffer so it is persistent accross reboots.
In order to have this working it is required to set PSZ and SBLK values in the NVM user row, I believe that can be done with the mdloader, but not having the source code, I am not able to implement this, I would be happy to do so.
I've tested by manualy updating the NVM user row connecting a JLINK probe on my keyboard.
Signed-off-by: Alexandre d Alton <alex@alexdalton.org>

massdrop alt/ctrl: support saving into nvm

---

docs/feature_haptic_feedback.md
quantum/process_keycode/process_haptic.c

Add layer mod keys to the list of keys disabled by NO_HAPTIC_MOD

---

keyboards/mokey/mokey64/rules.mk

Doesn't appear to support RGB, at all? 
Disable RGBLIGHT by default. 
* Tzarc CI

[Keyboard] Disable RGBLIGHT on mokey64

---

docs/mod_tap.md

Intercepting Mod-Tap to workaround caveats is a frequently asked question in Discord. Documented here are code examples of doing so.
FAQ in QMK Discord

Document examples on intercepting Mod-Tap

---

docs/pr_checklist.md

Just some more clarification and rewording, also allowing for SPDX license identifier.

More PR checklist updates

---

tmk_core/rules.mk

Added semicolons to rules.mk to allow symlinks from /bin/sh to /bin/zsh to complete the filesize check without error.
*

Allow symlinks from /bin/sh to /bin/zsh

---

keyboards/massdrop/alt/config_led.h
keyboards/massdrop/alt/keymaps/default_md/keymap.c
keyboards/massdrop/alt/keymaps/mac_md/keymap.c
keyboards/massdrop/ctrl/config_led.h
keyboards/massdrop/ctrl/keymaps/default_md/keymap.c
keyboards/massdrop/ctrl/keymaps/mac_md/keymap.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.h

Forward-port of LED features from Massdrop QMK fork:
* Mode that turns off every other edge LED
* Ability to decrease brightness of only edge LEDs
* Ability to set the ratio of key to edge LED brightness (unused by keymap)
* Added up/down, radial inward/outward LED pattern directions
* Factory debug mode
Updates the following keymaps to add keys using the above feature set:
* massdrop/alt/default_md
* massdrop/alt/mac_md
* massdrop/ctrl/default_md
* massdrop/ctrl/mac_md
This is a stop-gap change while a larger rework of QMK support for the current generation of Drop keyboards is in progress.
*

Stop-gap forward-port Drop LED features for CTRL and ALT

---

keyboards/cradio/keymaps/default/config.h

Default keymap included home row mod taps and mouse keys. These `config.h` settings are good defaults for both features to be usable.

Improved settings for Cradio default keymap

---

lib/python/qmk/info.py

JSON generator is looking for newline characters inside labels in layouts and removes them
[#99 from qmk/qmk_cli](https://github.com/qmk/qmk_cli/issues/99)

Fix broken layout rendering in `qmk info` by '\n'

---

quantum/action.c
quantum/action_util.c
quantum/process_keycode/process_auto_shift.c

found an issue where when oneshots was disabled (at runtime via the keycodes, not by the define), it would cause incorrect cleanup of keys.  namely, noticed that it immediately released mousekeys, even when held down. 
Also, completely disables the oneshot behavior, so that tap toggling doesn't work.  OSM should work exactly as modifier keys, and OSL should work as MO, when disabled.
* found by me

Fix issues with Oneshot disabling

---

docs/feature_rgb_matrix.md
quantum/rgb_matrix/animations/fractal_anim.h
quantum/rgb_matrix/animations/rgb_matrix_effects.inc

Here is a Fractal RGB matrix effect that generates randomly lit keys on middle columns and pulse outwards, creating a horizontal fractal pattern. Animation speed is user adjustable.

Add Fractal RGB matrix effects

---

tmk_core/protocol/vusb/vusb.c

missing bracket in send_digitizer
*

Fix up issues shown by clang-format of vusb

---

tmk_core/common/chibios/eeprom_teensy.c

This commit updates QMK’s copy of the the teensy3 Arduino core code with the
necessary changes to make the Teensy 3.6 work.
Aside from different values for the partitioning, HSRUN mode must be left
temporarily while using the EEPROM.
fixes https://github.com/kinx-project/kint/issues/8
related to https://github.com/kinx-project/kint/issues/10

core: make the full 4096 bytes of EEPROM work on Teensy 3.6

---

quantum/process_keycode/process_auto_shift.c

simple define to disable auto shift at startup AUTO_SHIFT_DISABLED_AT_STARTUP
Simple define to change the auto shift initial state.
The current auto shift initial state is always on, with this #define we will be able to
make it disabled at startup.
#define AUTO_SHIFT_DISABLED_AT_STARTUP
*

simple define to disable auto shift at startupAUTO_SHIFT_DISABLED_AT_STARTUP

---

keyboards/massdrop/alt/config.h
keyboards/massdrop/alt/keymaps/default_md/keymap.c
keyboards/massdrop/ctrl/config.h
keyboards/massdrop/ctrl/keymaps/default_md/keymap.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.c
tmk_core/protocol/arm_atsam/md_rgb_matrix.h

This gets the ALT/CTRL feature compatible with the massdrop/qmk_firmware fork.
Future iterations will move away from the bespoke LED framework and to core RGB Matrix.

Add support to persist MD LED framework settings

---

keyboards/lefty/lefty.c

Somehow, I missed this? 
`oled_task_kb` doesn't return a value.

[Keyboard] Fix missing return for oled task on Lefty

---

keyboards/arabica37/keymaps/default/keymap.c

Arabica37's oled task function is a mess... Misplaced OLED return.

[Keyboard] Fix missing return for oled task on Arabica37

---

users/drashna/oled_stuff.c

Fix missing return time in oled task for drashna's oled stuff

[Keymap] Fix missing return for oled task in drashna userspace

---

keyboards/canary/canary60rgb/v1/rules.mk

Compiles over limit due to too many features.  Enables LTO.
* Tzarc CI

[Keyboard] Fix compilation size issues for Canary 60 RGB

---

docs/feature_haptic_feedback.md
drivers/haptic/solenoid.c
drivers/haptic/solenoid.h
quantum/haptic.c
quantum/haptic.h
quantum/process_keycode/process_haptic.c
tmk_core/protocol/usb_device_state.c

This also add support for specifying a LED pin to indicate haptic status,
and also adds support for a haptic-enable pin, which is useful to turn off
the boost converter on the solenoid driver.
This has been tested on chibios running on an STM32F446.
Also tested on atmega32u4, and also on atmega32u2.
The following pull-request was a pre-requisite: (it's now merged)
~https://github.com/qmk/qmk_firmware/pull/12691~
*

F haptic disable when usb not configured or suspended

---

tmk_core/common/chibios/eeprom_teensy.c

#12947 caused a whole host of problems with other boards. This fixes their build errors, and likely causes issues for boards that picked up new functionality from the previous PR, most likely around partitioning.
Ping @stapelberg -- you'll need to confirm the fixes, otherwise I'll end up having to revert the original changes entirely.

Fix build failures caused by #12947.

---

quantum/main.c
tmk_core/protocol/chibios/chibios.c
tmk_core/protocol/lufa/lufa.c
tmk_core/protocol/vusb/protocol.c

Partially reverts #14888 due to some form of condition between when keyboard_init is called and when the host driver is set. This was reproduced by spamming a key on startup, where it would then not recover and never output any keys.
This close to the code freeze, its not worth breaking a bunch of edge cases.

Revert to old init order for host driver

---

keyboards/melgeek/mach80/keymaps/via/rules.mk
keyboards/melgeek/mach80/rev1/rules.mk

Moves LTO from via keymap to keyboard config. 
Compiles fine on master, only has issues on develop. Yay feature creep.
* Tzarc CI

[Keyboard] Reduce compile size for melgeek mach80

---

keyboards/rocketboard_16/info.json
keyboards/rocketboard_16/keymaps/default/keymap.c
keyboards/rocketboard_16/keymaps/via/keymap.c
keyboards/rocketboard_16/rocketboard_16.h

`info.json` was referencing a layout macro that did not exist. Instead of fixing the reference, I renamed the layout macro in source per QMK guidelines because there's only one physical layout supported.
cc @fl3tching101 (keyboard maintainer)

Fix Rocketboard-16 QMK Configurator Implementation

---

keyboards/steal_this_keyboard/info.json

- change `LAYOUT` to `LAYOUT_split_3x5_2`
Source code uses `LAYOUT_split_3x5_2`
cc @obosob (keyboard maintainer)

steal_this_keyboard: fix info.json macro reference

---

keyboards/craftwalk/keymaps/default/keymap.c

[Keyboard] Fix keycode collision in craftwalk keymap

---

docs/cli_commands.md
lib/python/qmk/cli/docs.py

If `docsify-cli` is installed through NPM, `qmk docs` can run that instead, and you get live reload. Falls back to the current behaviour of starting a Python HTTPServer.
*

`qmk docs`: Run `docsify serve` if available

---

keyboards/massdrop/ctrl/keymaps/foxx1337/README.md
keyboards/massdrop/ctrl/keymaps/foxx1337/config.h
keyboards/massdrop/ctrl/keymaps/foxx1337/hid_protocol.c
keyboards/massdrop/ctrl/keymaps/foxx1337/hid_protocol.h
keyboards/massdrop/ctrl/keymaps/foxx1337/keymap.c
keyboards/massdrop/ctrl/keymaps/foxx1337/rgb_matrix_user.inc
keyboards/massdrop/ctrl/keymaps/foxx1337/rules.mk

This keymap is not too different from the default.
I introduced defaults according to my taste and stripped away some effects. The biggest change is the addition of a raw HID communication protocol, which opens the way for a configurator a la VIA or Logitech Gaming Software, etc.
* Added inactivity timeout for the rgb matrix; after 5 minutes of idleness the matrix turns off.
* Added a raw HID protocol based on 96bfce70009ac15 that exposes the rgbmatrix functionality to clients
[This YouTube video](https://www.youtube.com/watch?v=2SEVsAaa3tA) showcases the layout in action.
*

[Keymap] foxx1337 for Massdrop CTRL with raw HID

---

tmk_core/rules.mk

When compiling with LTO, the lto-wrapper of GCC will detect the presence
of parallelism via the environment, and either call $MAKE or simply
`make` (and the detection of a jobserver messes this up for FreeBSD).
On FreeBSD and other systems, you have to build with `gmake` and the
way to have lto-wrapper use the same make(1) is to pass it via the
environment.
This fixes the (parallel) linking when LTO is active under FreeBSD.
*

Fix parallel builds w/ LTO on systems where make is not GNU make.

---

keyboards/yanghu/unicorne/unicorne.c

This is broken on master too, not sure if worth fixing there, since part of the breakage is i2c_init related.
* Fixes issues with i2c compiling, due to changes with i2c setup.
* Fixes oled callbacks
* Tzarc CI

[Keyboard] Fix compilation issues for yanghu Unicorne

---

layouts/community/ergodox/french_hacker/keymap.c
layouts/community/ergodox/french_hacker/readme.md

Provides a revamp of my original ergodox french_hacker layout.
- Remove specific QubesOS shortcuts
- Remove clunky accented letters layers
- Add missing azerty symbols
- Add Meh key
All accented characters are now accessible either with dead accent keys or with
directly with on the traditional azerty top row
I have kept the media layer, even if I don't use it, as it may ease forking/hacking on the layout  for follow programmers.
*

Revamp the ergodox french_hacker layout

---

tmk_core/rules.mk

Resolves the long standing issue of,
```
Making lets_split/sockets with keymap default                                                          [WARNINGS]
| 
| lto-wrapper: warning: Options to Xassembler do not match: -adhlns=.build/obj_lets_split_sockets_default/keyboards/lets_split/lets_split.lst, -adhlns=.build/obj_lets_split_sockets_default/keyboards/lets_split/sockets/sockets.lst, dropping all -Xassembler and -Wa options.
|
````
447ec8f - Do the vast majority of users actually care about these files? Seems like it should be opt-in (which also removes an additional clang check).

gcc10 LTO - Only specify adhlns assembler options at link time

---

docs/pr_checklist.md

In regards to: https://github.com/qmk/qmk_firmware/pull/15114#discussion_r747888325

[Docs] Codify not using code from other keyboards in PRs

---

quantum/process_keycode/process_unicode_common.c

In order to use UC_WIN with remote sessions, a wait has to be inserted before sending KC_PPLS.
Fixes #15062

add wait to unicode for win

---

keyboards/kb_elmo/elmopad/info.json

Fixes
cc @kb-elmo (keyboard maintainer)

kb_elmo/elmopad: fix macro reference in info.json

---

.github/workflows/format.yaml
lib/python/qmk/cli/format/text.py

Puts back the dos2unix check, however keyboard PRs will need further work.
QOL improvement to flag which files are failing, rather than it be hidden in the log
(further iteration on the problem would be required to get accurate line numbers, error content, etc)

Partially reinstate CI formatting process

---

platforms/avr/drivers/uart.h

#14839 has mismatched types for the uart functions.  
* Travis CI

Fix uart function prototypes

---

docs/feature_wpm.md
quantum/wpm.c
quantum/wpm.h

Changes the WPM feature to provide a correct WPM value instead of only a rough estimate.
This change is similar to the one in [this PR](https://github.com/qmk/qmk_firmware/pull/13359), which I hadn't known about at the time I made this change locally.  It's worth checking that one out for comparison to this one!
The original WPM feature worked by measuring the time between two keypresses, estimating a WPM value from that delay between keypresses, and then interpolating a rolling average "WPM" value by 4.87% of the difference between the current average and the new calculation (which we're told is equivalent to averaging over 40 keypresses).  If no keys are pressed, then after one second the rolling average would be reduced by 4.87%.
There were some problems with this original calculation; …

Reimplements WPM feature to be smaller & precise

---

keyboards/bandominedoni/config.h

Add missing mode for via keymap. verified that via keymap compiles. (826 bytes free)
* Tzarc CI

Fix bandominedoni via keymap compilation

---

keyboards/ffkeebs/puca/puca.c

Update keyboard to use newer types for oled_task

[Keyboard] Fix oled_task_user for ffkeebs/puca

---

quantum/backlight/backlight_avr.c

This PR aims to make hardware PWM resolution configurable, allowing higher PWM frequencies at lower resolutions.
Currently, 16bit timers use the full 16bit resolution, resulting in a ~244Hz frequency for the backlight PWM. This would be noticeable in the peripheral vision if moving quickly / turning your head quickly. Additionally, with most keyboards having very few brightness levels, this resolution is wasted.
For now, making the top of the counter optionally configurable using `#define BACKLIGHT_CUSTOM_RESOLUTION = <custom resolution>` should offer configurability for users that find 244Hz too slow.
In order to achieve this, some things have been changed slightly. 
The cie_lightness function was hard-coded to assume the max value was 65535.
In order to avoid floating point arithmetic, …

Made AVR backlight pwm resolution configurable

---

docs/feature_stenography.md
docs/ja/feature_stenography.md

As mentioned in https://github.com/qmk/qmk_firmware/pull/15133#discussion_r749754206, `eeconfig_init_user()` is a better place than `matrix_init_user()` to call `steno_set_mode()`.

Update the documentation to call steno_set_mode inside eeconfig_init_user

---

quantum/backlight/backlight_avr.c

[Bug] Fix missing variable for Backlight Breathing

---

quantum/backlight/backlight_avr.c

Reverts the change to turn the pins on, as it's erroring out, and backlight_common properly handles it. 
* Tzarc CI

[Bug] Revert backlight pins on function call

---

docs/tap_hold.md

This is a minor addition to the docs that clarifies useful terminology that is already referenced. Hopefully it makes understanding dual-role key features a bit better, and makes them easier to talk about.

Clarify "nested" and "rolling" key sequences

---

tmk_core/protocol/usb_hid/override_wiring.c

[Bug] Fix timer include in override_wiring.c

---

.github/workflows/cli.yml
.github/workflows/unit_test.yml

Convert the core unit testing of QMK to GitHub Actions. (Originally #7361)

 CI: Create GitHub Actions unit test workflow

---

platforms/chibios/platform.mk
platforms/chibios/syscall-fallbacks.c
util/install/debian.sh

This PR contains multiple fixes for the upcoming develop to master merge. 
1. Debian and Distributions based on it ship the needed RISC-V toolchain beginning with Debian 11+ and Ubuntu 21.04+. Therefore the qmk install script checks if the needed dependencies are available.
2. QMK CLI setup: RISC-V toolchains are not widely available at the moment and the naming is not unified. The main userbase of QMK are AVR and ARM mcus therefore RISC-V should not be treated as a hard requirement. Therefore a missing toolchain produces no error but merely a warning.
3. picolibc usage with heap allocation: picolibc internally uses `__heap_start` and `__heap_end` instead of the defacto chibios linker script standard `__heap_base__` and `__heap_end__` therefore we introduce these symbols as an alias. …

[Core] RISC-V toolchain and picolibc fixes

---

quantum/split_common/transport.h

Should fixe the bugs introduced with https://github.com/qmk/qmk_firmware/pull/12090.
* Closes #15236

Fix encoder bug from #12090

---

data/mappings/info_config.json

With code freeze looming, virtually every keyboard is spitting out the following warning
```
make zvecr/zv48:default:flash
QMK Firmware 0.14.31
⚠ zvecr/zv48/f401: PRODUCT in config.h is overwriting keyboard_name in info.json
Making zvecr/zv48/f401 with keymap default and target flash
⚠ zvecr/zv48/f401: PRODUCT in config.h is overwriting keyboard_name in info.json
arm-none-eabi-gcc (Arch Repository) 11.2.0
```
While maybe a better experience while porting new keyboards, this is just going to cause issues for the majority. (Just look at how many questions get raised about the arm size warning)
*

Short term bodge for PRODUCT warning

---

util/udev/50-qmk.rules

The Keyboardio Atreus 2 Bootloader is a clone of the Caterina bootloader with different USB VID:PID values (`1209:2302`):
https://github.com/keyboardio/Atreus2-Bootloader
Add the appropriate udev rule for that bootloader.
Verified in Discord: https://discord.com/channels/440868230475677696/867530222407778344/911701982891360286
* Keyboardio Atreus 2 board not flashable from Linux

Add Keyboardio Atreus 2 Bootloader to udev rules

---

quantum/quantum.c
quantum/quantum.h

Adds functions to convert an unsigned int to a char array.  Useful for OLEDs and displays, especially on AVR, as things like sprintf take up ~1.5kB of firmware space. 
And instead of continually adding the same block of code, add a function into core to do this.

Add uint to char functions

---

.github/workflows/format.yaml

PR Formatting workflows are sometimes hitting the following error,
```
Run qmk format-c --core-only $(< ~/files.txt)
qmk format-c --core-only $(< ~/files.txt)
qmk format-python $(< ~/files.txt)
qmk format-text $(< ~/files.txt)
shell: bash {0}
No such file or directory
☒ Error formatting C code!
```
From https://github.com/trilom/file-changes-action,
> The names all new, updated, and removed files
This PR changes the workflow to only include added+changed files.

[CI] Ignore deleted files when formatting codebase

---

docs/feature_auto_shift.md
docs/tap_hold.md
quantum/action.c
quantum/action_tapping.c
quantum/process_keycode/process_auto_shift.c
quantum/process_keycode/process_auto_shift.h

This pull request will allow one to use Auto Shift (AS) on a key but also use it as a modifier - three keys in one, and it feels like they're completely separate! I've been using a very janky hardcoded version of this for months, it's great. It will also add support for custom AS keys, as things like `.` and `!` are clearly a better match than those they currently have.
This is a recode of https://github.com/qmk/qmk_firmware/pull/9889, as upon further testing it didn't work when `TAPPING_TERM` was not exceeded (and Auto Shift now supports keyrepeat).
https://github.com/p00ya/qmk_firmware/pull/2 has also been merged with this pull as there are quite a few conflicts between the two features. I also don't want to have to manage those conflicts once I've forgotten how AS works (I had a custom …

Add Retro Shift (Auto Shift for Tap Hold via Retro Tapping) and Custom Auto Shifts

---

docs/feature_rgblight.md
docs/ws2812_driver.md
platforms/chibios/drivers/ws2812.c

Due to the way that the PrimeKB Meridian PCB was assembled (LEDs not to spec), this change is needed in order to properly use the LEDs.
Note that this change alone does not fix the LEDs. A follow-up PR with changes to the keyboard firmware will fully solve the issue.
* https://github.com/qmk/qmk_firmware/issues/11755

Add ifndef to WS2812 timing constraints

---

keyboards/dztech/dz60rgb_ansi/v2_1/config.h

22 bytes over => 1252 bytes free.

More headroom for `dztech/dz60rgb_ansi/v2_1:via`.

---

util/size_regression.sh

Add script for performing compilation size regression investigations.

---

build_test.mk
quantum/encoder/tests/encoder_tests.cpp
quantum/encoder/tests/encoder_tests_split.cpp
quantum/encoder/tests/mock.c
quantum/encoder/tests/mock.h
quantum/encoder/tests/mock_split.c
quantum/encoder/tests/mock_split.h
quantum/encoder/tests/rules.mk
quantum/encoder/tests/testlist.mk

Re-add encoder tests

---

keyboards/ploopyco/trackball/trackball.c

`pointing_device_handle_buttons(…)` expects 3 arguments, the first one being an `uint8_t` corresponding to the `report_mouse_t.buttons` field to update.
Without this change, the `ploopyco/trackball` firmware fails to compile when `MOUSEKEY_ENABLE` is not defined.
*

Fix call to `pointing_device_handle_buttons`

---

quantum/action_tapping.c

#11059  broke compilation with keyboards that have `HOLD_ON_OTHER_KEY_PRESS` because of a typo: `KEYPRESS` should have been `KEY_PRESS`.
*

[Core] Hotfix for HOLD_ON_OTHER_KEY_PRESS after #11059

---

docs/ChangeLog/20211127.md
docs/ChangeLog/20211128.md
docs/_summary.md
docs/breaking_changes.md
docs/breaking_changes_history.md
docs/pr_checklist.md
lib/python/qmk/cli/generate/develop_pr_list.py

Adds the new changelog as well as updating some verbiage, scheduling.

Changelog 2021q4

---

keyboards/primekb/meridian/ktr1010/config.h
keyboards/primekb/meridian/ktr1010/rules.mk
keyboards/primekb/meridian/readme.md
keyboards/primekb/meridian/rules.mk
keyboards/primekb/meridian/ws2812/config.h
keyboards/primekb/meridian/ws2812/rules.mk

The Meridian PCB suffered a logistics/communication issue and some units were shipped with KTR1010 LEDs which are wildly out of timing when compared to the default WS2812 LEDs. In this regard, this firmware update makes use of the recent "ajustable timing parameters" recently merged into master from these PRs:
https://github.com/qmk/qmk_firmware/pull/14678
https://github.com/qmk/qmk_firmware/pull/15298
https://github.com/qmk/qmk_firmware/pull/15299
The updated firmware has two options, `ws2812` and `ktr1010` which compiling and flashing are explained in the readme.
Firmware-wise the difference between these options is that while the `ws2812` option uses the common SPI driver with default timings, the `ktr1010` options uses the bit-banged driver with the adjusted timing parameters. The PCB …

Meridian LED update

---

keyboards/0xcb/static/config.h
keyboards/0xcb/static/keymaps/bongocat/keymap.c
keyboards/0xcb/static/readme.md

Fixed an issue caused by [#13454](https://github.com/qmk/qmk_firmware/pull/13454) in the bongocat keymap and changed the encoder direction for use in prod parts - also updated readme

fixed oled in bongocat keymap and fixed encoder direction

---

docs/feature_key_lock.md
quantum/process_keycode/process_key_lock.c
quantum/process_keycode/process_key_lock.h

Added cancel_key_lock()
Add cancel key lock functionality to process_key_lock.c to cancel the key lock immediately. 
- [] New feature
n/a

Added cancel_key_lock function

---

quantum/backlight/backlight_avr.c

Bit loss during division breaks static backlight levels.
@Duckle29 since you authored the PR that made these changes can you confirm this doesn't break what you were trying to accomplish?
* Fixes #15331

Fix bit loss in cie_lightness() when doing division to resolve #15331

---

lib/python/qmk/cli/format/c.py

Found during the recent develop merge, <https://github.com/qmk/qmk_firmware/runs/4342852367?check_suite_focus=true>
Was incorrectly finding `drivers` within `keyboards/helix/local_drivers/i2c.h`

Fix 'format-c --core-only' matching keyboard level folders

---

tmk_core/protocol/usb_descriptor.c

Sets the default USB Polling rate to be 1ms/1kHz. 
This matches what VUSB is already doing.

Change default USB Polling rate to 1kHz

---

keyboards/keebio/iris/keymaps/mnil/keymap.c
keyboards/planck/keymaps/mnil/keymap.c
users/mnil/mnil.c

Commit 50d4dfd deprecated and removed a couple of Swedish character
defines that was still used in my keymap. This commit remedies that and
updates to the supported character names.
*

Remove deprecated defines from my keymaps

---

tmk_core/protocol/chibios/usb_main.c

If Steno/Virtser is enabled on a ChibiOS board, you get a linker error on `virtser_init()` as it is called in `keyboard.c` but only implemented in `lufa.c`.
*

Add missing virtser_init() to ChibiOS code

---

keyboards/ramonimbao/wete/readme.md
keyboards/ramonimbao/wete/rules.mk
keyboards/ramonimbao/wete/v2/readme.md

As it says on the tin. Causes issues with `qmk multibuild` due to wrong path.

Fixup paths for `ramonimbao/wete/v2`.

---

keyboards/handwired/tractyl_manuform/4x6_right/config.h

Made changes to the kb split sync code, but forgot to update the 4x6 variant. 
* Tzarc CI

[Keyboard] Add missng define for 4x6 Tractyl Manuform

---

keyboards/1upkeyboards/1up60hse/rules.mk
keyboards/alf/x11/rules.mk
keyboards/butterstick/rules.mk
keyboards/clueboard/66_hotswap/prototype/rules.mk
keyboards/converter/usb_usb/ble/rules.mk
keyboards/georgi/rules.mk
keyboards/hineybush/h87a/rules.mk
keyboards/idobo/rules.mk
keyboards/noxary/260/rules.mk
keyboards/percent/booster/rules.mk
keyboards/scarletbandana/rules.mk
keyboards/tetris/rules.mk
keyboards/tkc/candybar/lefty/rules.mk
keyboards/tkc/candybar/righty/rules.mk

Remove manual enable of LTO within keyboards

---

keyboards/matrix/m20add/m20add.c
keyboards/yanghu/unicorne/config.h
platforms/avr/drivers/i2c_master.c
platforms/chibios/drivers/i2c_master.c
platforms/chibios/drivers/i2c_master.h

Pulled out from #14337, as these changes can go in without the dependency of a single header file.

Tidy up existing i2c_master implementations

---

keyboards/moonlander/moonlander.c

Somebody (me) forgot to add `matrix_init_user` to the kb level function, causing it to not be called. 
Also, better handle process_record_*.

[Keyboard] Fix bug in Moonlander functions

---

keyboards/mnk1800s/rules.mk
keyboards/mnk50/rules.mk

Add APM chips suffix for the two MNK keyboards.
This is due to the chip shortage :)
*

Add DFU Suffix for APM chips

---

common_features.mk
quantum/quantum.c

Adds a define for unicode common, and removes the specific feature check for each unicode mode. 
This allows you to essentially have access to a "lite" unicode core, and build your own wrapper around it, dropping the keycode support for it.

Generalize Unicode defines

---

docs/flashing.md
platforms/chibios/bootloader.c

This is a fix for https://github.com/qmk/qmk_firmware/issues/6112. Keyboards with the Kiibohd bootloader would go into [secure DFU mode](https://github.com/kiibohd/controller/blob/master/Bootloader/Documentation/SecureDFU.md). In secure DFU mode the bootloader would do an extra key verification where it would look for a key in the first block of the new firmware. There is a way to disable this functionality, and after talking with @haata, I was able to implement this fix.
I have a K-type and this fixed the issue on my keyboard. If anyone that has a different keyboard, let me know if this fix also works on your board.
* Fixes #6112

Fix RESET not working for keyboards with Kiibohd bootloader

---

docs/feature_pointing_device.md
drivers/sensors/pmw3360.c

Data sheet mentions -30 to 30, but reading the register shows it supports a full 8 bit signed integer for the rotation. 
This updates th code to allow the full range of rotation.  Has been tested on hardware and can confirm that it works.

Expand rotational range for PMW3360 Optical Sensor

---

keyboards/ramonimbao/herringbone/pro/config.h
keyboards/ramonimbao/herringbone/pro/keymaps/via/keymap.c

1) Flips the encoder behavior so it behaves correctly.
2) Users were encountering a weird behavior where turning the encoder sometimes causes it to go to min or max volume, even if using high quality ALPS encoders.
The weird volume issue only happens with VIA keymap so it must be because of the encoder mapping code thing. I added code to override the behavior of `KC_VOLU` and `KC_VOLD`.

Flip encoder and fix weird volume behavior for Herringbone Pro

---

util/update_chibios_mirror.sh

Add support for 21.11.x, remove 21.6.x as ChibiOS "canceled" it (and QMK never used it).

ChibiOS SVN mirror script update

---

docs/compatible_microcontrollers.md

There is an errant space before `### WestberryTech` and it's messing up the formatting.
* https://discord.com/channels/440868230475677696/473506116718952450/918344148891861012

[Docs] Fix Header formatting in compatible mcu doc

---

docs/feature_pointing_device.md
drivers/sensors/pmw3360.c
drivers/sensors/pmw3360.h

Adds the ability to set the lift off distance between the sensor and the surface.
Currently the default is set to `0x02` (please refer to the datasheet). 
Using `#define PMW3360_LIFTOFF_DISTANCE xxx` will allow the user to set the wanted distance. 
e.g. `#define PMW3360_LIFTOFF_DISTANCE 0x27`
Tested and working
* Add lift off distance change

[Core] Add configuration of PMW3360 lift off distance

---

keyboards/ramonimbao/chevron/keymaps/via/keymap.c

Following https://github.com/qmk/qmk_firmware/pull/15423, adds `wait_ms` to another board of mine

Fix encoder issue with Chevron

---

quantum/audio/audio.c
quantum/process_keycode/process_audio.c
quantum/process_keycode/process_audio.h

This PR adds missing `audio_off_user()` callback. 
In order to react on audio being enabled/disabled the callbacks `audio_on_user()` and `audio_off_user()` are desirable. 
The latter mentioned callback is missing. 
- very minor enhancement
- did not find a place to document
* no issues found by the following filter: [is:open audio_off_user](https://github.com/qmk/qmk_firmware/issues?q=is%3Aissue+is%3Aopen+audio_off_user)

added missing audio_off_user() callback

---

quantum/action_util.c
tests/auto_shift/test_auto_shift.cpp
tests/basic/test_action_layer.cpp
tests/basic/test_keypress.cpp
tests/basic/test_one_shot_keys.cpp
tests/tap_hold_configurations/permissive_hold/test_tap_hold.cpp
tests/tap_hold_configurations/permissive_hold_ignore_mod_tap_interrupt/test_tap_hold.cpp
tests/tap_hold_configurations/tapping_force_hold/test_action_layer.cpp
tests/tap_hold_configurations/tapping_force_hold/test_tap_hold.cpp
tests/test_common/test_fixture.cpp

As the title suggest, with this change only keyboard reports that propagate changes to the host get send at all. This PR builds on to of #13789 so the change set is obviously a bit larger than necessary. Only ab2e2b2 and 5c9fb10 contain the necessary changes.
Note that the method used is a bit brute force as it doesn't fix the logic bugs under the hood.
* None

[Core] Don't send keyboard reports that propagate no changes to the host 

---

drivers/sensors/cirque_pinnacle_spi.c
drivers/sensors/pmw3360.c

Cirque Pinnacle trackpad SPI code doesn't compile due to mismatched names. whoops. 
Small bug with get cpi function for pmw3360
*

[Core] Fix Sensor driver code

---

quantum/keymap_extras/keymap_lithuanian_azerty.h
quantum/keymap_extras/keymap_slovak.h
quantum/keymap_extras/sendstring_lithuanian_azerty.h
quantum/keymap_extras/sendstring_slovak.h

Fix the issue that some undefined macros are used in `keymap_[locale].h` files and `sendstring_[locale].h` files. 
There are some undefined macros in `keymap_[locale].h` files and `sendstring_[locale].h` files. The compilation of the code set for each keyboard will be failed, if the code set includes these wrong header files.

Fix some wrong keycode macros in locale mapping files

---

quantum/keymap_extras/sendstring_canadian_multilingual.h

It seems to me `<` and `>` were inversed in the canadian multilingual mapping.

Fix inverted gt and lt send_string mapping in canadian multilingual

---

keyboards/ferris/sweep/config.h

Remove default to save firmware space because PCB has no support.

Remove locking support for Sweep

---

users/zigotica/rows.h

TAB in default layer, ESC in sym/fn layers
* none

zigotica userspace rows tweak: TAB in default layer, ESC in sym/fn layers

---

lib/python/qmk/cli/generate/develop_pr_list.py

Swaps to using the PR title instead of parsing the git output and using it instead. PR titles seem to be more relevant.
Example for #15435, which makes sense as an isolated git commit when looking at the actual change (it adds support for mirroring the newer branches from the ChibiOS repo's):
```
* Add support for 21.11.x, remove 21.6.x as ChibiOS "canceled" it. ([#15435](https://github.com/qmk/qmk_firmware/pull/15435))
```
becomes:
```
* ChibiOS SVN mirror script update ([#15435](https://github.com/qmk/qmk_firmware/pull/15435))
```

[cli] `develop` changelog generator: use the PR title instead

---

common_features.mk
drivers/bluetooth/rn42.c
drivers/bluetooth/rn42.h
tmk_core/protocol/lufa/lufa.c

For whatever reason there were some linking errors with simply migrating the existing function calls in lufa.c, so I had to refactor them into a separate file like the Adafruit BLE code. This is closer to the end goal anyway, so it kills approximately 1.5 birds with one stone.
*

Migrate RN42 to UART driver and refactor

---

docs/feature_haptic_feedback.md

Documentation Typo fix

---

docs/faq_debug.md

Add to the documentation that "qmk console" can also be used to print debug messages from the keyboard.

doc/faq_debug: qmk cli can also be used to print debug messages

---

quantum/joystick.h

While tracking down a bug in the joystick QMK implementation I noticed that the struct containing buttons allocates a byte more than needed.
Of course no big issue, but since I found it I better share it.
Allocate precisely enough memory (in bytes) to contain the number of buttons, instead of one byte too much.

Save a single byte of memory for joystick buttons

---

docs/feature_rgb_matrix.md

The correct keycode for the mapped swirl effect that can be used in the keymap directly is `RGB_MODE_SWIRL`, not `RGB_MATRIX_SWIRL`.
Fixed a typo in the documentation to reflect this.
* N/A

Fixed typo in keycode reference for swirl effect

---

docs/feature_pointing_device.md

Just some easy typo fixes while I'm digging into SPI stuff.
*

fix a typo

---

docs/feature_wpm.md
quantum/wpm.c
quantum/wpm.h

This commit does some further cleanup on the WPM feature as modified as part of pull request #13902 .
There are four main changes here:
1. Increased the size of sampling buffers from 8-bits to 16-bits, to dramatically reduce the chances of overflowing the integers.
2. Dropped the default number of WPM sampling buffers from 50 to 25, to compensate for the increased size of the sampling buffers.  This change includes editing the documentation file `feature_wpm.md` to bring it up to date with the changed default value.
3. Added some safety code to explicitly verify that no matter what, we won't overflow beyond either the high or low limits of the 16-bit signed integers.
4. Fixed a subtle (minor) bug which could happen if both `WPM_LAUNCH_CONTROL` and `WPM_ALLOW_COUNT_REGRESSION` were …

Fixes potential wpm sampling overflow, along with code comment fixes

---

builddefs/message.mk

Makes this a bit more foolproof.
* Fixes https://github.com/qmk/qmk_firmware/issues/15202

Add a clarification to an error message

---

quantum/action.c
quantum/quantum.c

This makes all of the register/unregister/tap functions weak, so that they can be replaced, if need be. This may be a better way to implement things like #12686 #9126 and #9125, since it doesn't require as drastic a change to the code, will work with features such as encoders, or custom macros.

Make (un)register code functions weak

---

platforms/avr/drivers/serial.c

Fixes `develop` build -- previous `#define` values matched gpio.h -- the changes introduced in the open-drain gpio changes made them differ (despite final preprocessor output matching). This just removes the re-definitions in `serial.c`.
Compilation seems fine, untested on boards at this stage.

Fix avr serial compile

---

data/schemas/keyboard.jsonschema
docs/feature_debounce_type.md
quantum/debounce/sym_defer_pr.c
quantum/debounce/tests/rules.mk
quantum/debounce/tests/sym_defer_pr_tests.cpp
quantum/debounce/tests/testlist.mk

Add a per-row debouncer that offers that some protection from electrical noise without
paying the full responsiveness hit of the default sym_defer_g debouncer.
*

Add sym_defer_pr debouncer type

---

quantum/rgb_matrix/rgb_matrix.c

Workaround for a bug which causes the slave side of a split keyboard (crkbd in my case) to randomly turn the rgb matrix on and off after every keypress when RGB_DISABLE_TIMEOUT is set. (had values like 300000 and 450000 for 5 or 7.5 minutes timeout)
I think the root of this bug has is in `sync_timer.c` where https://github.com/qmk/qmk_firmware/blob/6e8eb2cf542d38332ef460d4f88eed281aed9188/tmk_core/common/sync_timer.c#L36
can produce a negative value and the result in 
https://github.com/qmk/qmk_firmware/blob/6e8eb2cf542d38332ef460d4f88eed281aed9188/tmk_core/common/sync_timer.c#L46
can still be negative, which then results in a range underflow of the `uint32_t` result and therefore will be a very large number.
So as a result the code in `rgb_matrix.c` will eventually go into the if case in …

fix rgb_matrix flicker on split keyboards caused by RGB_DISABLE_TIMEOUT

---

keyboards/durgod/boards/DURGOD_STM32_F070/chconf.h
keyboards/durgod/boards/DURGOD_STM32_F070/mcuconf.h
keyboards/durgod/dgk6x/config.h
keyboards/durgod/dgk6x/halconf.h
keyboards/durgod/k3x0/config.h
keyboards/durgod/k3x0/halconf.h

Increase scan rate on Durgod keyboards by using the wait_us timer.
Lower the tick rate from 10kHz to 1kHz (otherwise all the extra interrupts reduce the achievable scan rate).
Enable the WAIT_US_TIMER using GPT timer 3.
Observed scan rate on the K320 is increased from 625Hz to 2090-2120Hz.
@J-Sully, @dkjer can you test this on the `dgk6x` keyboards? They use the same board definition so I had to enable it for those keyboards otherwise their scan rate would go down with the lower tick rate.

Durgod: Increase scan rate by using wait_us timer

---

keyboards/mechlovin/hex4b/keymaps/nazzer/keymap.c
keyboards/mechlovin/hex4b/keymaps/nazzer/reame.md
keyboards/mechlovin/hex4b/keymaps/nazzer/rules.mk

Hex 4b VIA Keymap to use scroll lock and num lock LED's to indicate active layer (0,1,2,3)
Repurposed the Scroll Lock and Num Lock LED's as Hex 4b does not have a NUM pad and default layout does not map Scroll Lock
- Top LED shows CAPS lock status
- Layer indicators:
- Layer 0: bottom LED off, middle LED off
- Layer 1: bottom LED on , middle LED off
- Layer 2: bottom LED off, middle LED on
- Layer 3: bottom LED on , middle LED on
*

Hex 4b LED Layer Indicater

---

keyboards/orthocode/info.json
keyboards/orthocode/keymaps/default/keymap.c
keyboards/orthocode/orthocode.c

Updating the default keymap to match the one shipped on the boards.
Moving the encoder function definition to orthocode.c so it works by default for those using the online qmk configurator
* 

Orthocode update default keymap, and fix encoder function for keymaps built in configurator

---

keyboards/wuque/ikki68_aurora/keymaps/ewersp/README.md
keyboards/wuque/ikki68_aurora/keymaps/ewersp/config.h
keyboards/wuque/ikki68_aurora/keymaps/ewersp/keymap.c
keyboards/wuque/ikki68_aurora/keymaps/ewersp/rules.mk

Added a personal keymap for the Wuque ikki68 Aurora (this keymap is based off of another of my personal keymaps for the Drop ALT).

[Keymap] Adding 'super alt' keymap for Wuque ikki68 Aurora

---

keyboards/gmmk/pro/iso/keymaps/vitoni/config.h
keyboards/gmmk/pro/iso/keymaps/vitoni/keymap.c
keyboards/gmmk/pro/iso/keymaps/vitoni/readme.adoc
users/vitoni/readme.adoc
users/vitoni/rgb_matrix_effects.c
users/vitoni/rgb_matrix_effects.h
users/vitoni/rules.mk
users/vitoni/utils.c
users/vitoni/utils.h
users/vitoni/vitoni.c
users/vitoni/vitoni.h

Add vitoni keymap and configuration for GMMK Pro (ISO).
Adds a layer to the keymap, similar to the FN layer of laptops.
Furthermore, the RGB functions are separated into their own layer.
RGB has been adapted to allow fade-in and fade-out for suspend and idle and the idle mode allows the use of a breathing effect.
These features can be used individually and are configured vie `#define` directives.
Feature parameters are checked at compile time.
No issue created.

[Keymap] Add vitoni keymap for GMMK Pro (ISO)

---

keyboards/iron180/config.h
keyboards/iron180/iron180.c
keyboards/iron180/readme.md

Some Iron180 users have shown interest in only having the caps lock LED soldered and for it to work as a caps lock indicator.
This PR adds a `CAPSLOCK_BACKLIGHT`  define in `config.h` which in turn enables a led state function in `iron180.c`  that toggles backlight and breathing according to caps lock. The PR also contains README instructions.

Add 'capslock backlight' feature to Iron180

---

drivers/sensors/pmw3360.c

Timing does not match Pixart documentation for this sensor (may have been carried forward from adns9800).
Not aware of any issues coming from this currently.
It should only cause issues when writing to multiple registers in succession which currently only happens during initialization for the PMW3360.
This should prevent future issues with write operations if other features of the sensor are added.
* No known issues caused by this at the moment but may cause issues in the future

Fix for SPI write timing in PMW3360 driver

---

drivers/sensors/adns9800.c
drivers/sensors/pmw3360.c
drivers/sensors/pmw3360.h
quantum/pointing_device_drivers.c

While working on the driver to add multi-device support, I noticed that it's very similar to adns9800 and to be able to better read them side-by-side I've renamed and shuffled things around a bit.
This removes unused defines, unused includes, unused return codes and renames a lot of things (sorry!).
It also removes some redundant calls to start/stop that are entirely duplicated.
*

pwm3360 driver cleanup and diff reduction to adns9800

---

keyboards/massdrop/thekey/keymaps/url-copy-paste-macos/keymap.c

The `url-copy-paste-macos` keymap is broken because it uses `LCTL` instead of the OSX-compatible `LGUI`
*

[massdrop/thekey] macos requires LGUI modifier instead of LCTL

---

keyboards/bandominedoni/keymaps/via/rules.mk

AVR + rgb + midi + mousekeys + via == bad times.  Too large.

[Keyboard] Fix over sized compiliation for Bandiominedoni via keymap

---

keyboards/yanghu/unicorne/keymaps/bcat/config.h
keyboards/yanghu/unicorne/keymaps/bcat/keymap.c
keyboards/yanghu/unicorne/keymaps/bcat/readme.md
keyboards/yanghu/unicorne/keymaps/bcat/rules.mk
users/bcat/compile.sh
users/bcat/readme.md
users/bcat/rules.mk

Just adding an initial layout for the Unicorne keyboard, a unibody Crkbd variant with rotary encoders, an OLED display and a speaker. Uses the same layout as my Crkbd, plus the encoders.
Also features a cute unicorn that trots on the OLED screen based on your typing speed. :)
None

Add initial Unicorne keyboard layout for bcat

---

keyboards/handwired/tractyl_manuform/4x6_right/rules.mk

Removed tm_sync.c, but forgot to update the 4x6 version...
* Tzarc CI

[Keyboard] fix compiler issue with Tractyl Manuform 4x6

---

lib/python/qmk/cli/generate/compilation_database.py

Currently produces the following error,
```
$ qmk generate-compilation-database
Ψ Making clean with make clean
QMK Firmware 0.15.11
Ψ Gathering build instructions from make -n --jobs=1 gmmk/pro/ansi:xxxxxx
<class 'ValueError'>
☒ stdin and input arguments may not both be used.
File "G:/QMK_MSYS/mingw64/lib/python3.9/site-packages/milc/milc.py", line 526, in __call__
File "G:/QMK_MSYS/mingw64/lib/python3.9/site-packages/milc/milc.py", line 531, in __call__
File "G:/qmk_firmware/lib/python/qmk/decorators.py", line 27, in wrapper
return func(*args, **kwargs)
File "G:/qmk_firmware/lib/python/qmk/decorators.py", line 47, in wrapper
return func(*args, **kwargs)
File …
```

Fix compilation-database command under MSYS

---

quantum/split_common/transactions.c

Adds a NULL check for get_cpi. It's only analog joystick left using NULL maybe a better option would be to share the speed regulator value for it.
*

Fix split pointing for analog joystick

---

drivers/sensors/pmw3360.c
keyboards/ploopyco/mouse/readme.md
keyboards/ploopyco/trackball/readme.md
keyboards/ploopyco/trackball/trackball.c

Update pmw3360 comments to match the datasheet better, fix delays.
We should de-assert NCS after waiting for tSCLK-NCS, so move spi_stop()
around a little. This was missed in PR#11519.
I'm less certain about adding the (quite long) tSRAD delay, but the
datasheet clearly indicates so. Not sure how this worked before, but we
don't actually use the read function, but read_burst instead. Only the
init phase and get_cpi() would be affected, and no one uses get_cpi,
only set_cpi, of course.
Also use the more natual spi_read() to discard the observation data,
this also saves 2 bytes in the firmware :)
Remove references to the no longer existing pmw_set_cpi, and use
pointing_device_set_cpi like in all other pointing devices
*

Update pmw3360 driver after reading the datasheet top to bottom. Fix some outdated refs.

---

docs/feature_encoders.md

Volume control is a more logical and frequently used function for encoders

Volume as default encoder documentation example

---

keyboards/keychron/q1/config.h

Currently the Q1 stays lit up when the PC is in suspend by default. This probably isn't what most people want.
N/A

[Keychron Q1] Turn off RGB during PC suspend

---

lib/python/qmk/cli/format/c.py
lib/python/qmk/cli/format/python.py

Noticed on 15555 that the formatters did not correctly kick in <https://github.com/qmk/qmk_firmware/runs/4608117091?check_suite_focus=true>.
Fixes the following issues:
1. core/ignore path comparison getting mixed up with absolute and relative paths
2. `cli.args.files` was being modified which caused the filtered filenames to later be printed as `None`
The behaviour can be tested locally with:
```console
qmk format-c --core-only quantum/quantum.c
```
A valid core file, yet formatting fails.

Fix "No C files in filelist: None"

---

keyboards/handwired/onekey/keymaps/oled/keymap.c

One of the returns doesn't return a value and causes a compilation error.  This fixes that.

[Keymap] Fix onekey oled keymap

---

.gitattributes

Had a few commits recently with `crlf` line endings, which causes havoc with merges and tooling and the like.
Hopefully this mitigates a bunch of that.
`*.bat`,`*.ini` explicitly set to `crlf`, and `*.cmd` added and set similarly.

Modify `.gitattributes`, set `eol=lf`, where appropriate

---

quantum/process_keycode/process_rgb.c

Not 100% sure why there has to be a difference, as it pushes unnecessary context to intercepting with something like `process_record_user`.
it seems rather strange to have such a distinction within the codebase, when it doesn't exist for any other keycodes.

Unify the key up/down behaviour of RGB keycodes

---

keyboards/checkerboards/quark_squared/info.json

[title]
Fixes:
cc @npspears (keyboard maintainer)

checkerboards/quark_squared: fix broken layout macro reference in info.json

---

keyboards/ploopyco/trackball/config.h

After the ploopy firmware was rewritten to use the new QMK pointing
device feature it got the unfortunate behaviour of inverting the
trackball in the Y-axis.
This commit inverts the Y-axis so that the ploopy firmware
behave like it used to do before the pointing device changes.

Fix inverted ploopy trackball

---

keyboards/ai03/andromeda/config.h

Adding caps and scroll lock indicator LED support to the Andromeda PCB firmware
*

Add caps and scroll indicator LEDs to andromeda PCB

---

drivers/led/issi/is31fl3733-simple.c
drivers/led/issi/is31fl3733-simple.h
quantum/led_matrix/led_matrix.h

After reading source code of LED matrix, I noticed that the [work for supporting IS31FL3733 has partially done](https://github.com/qmk/qmk_firmware/blob/master/quantum/led_matrix/led_matrix_drivers.c). But I've no idea why it wasn't finished since then.
I port an IS31FL3733 driver for LED matrix, almost the same way as how IS31FL3731 was ported. Simply add following lines in `rules.mk` to use it:
```
LED_MATRIX_ENABLE = yes
LED_MATRIX_DRIVER = IS31FL3733
```
The documentation needs to be updated accordingly, could be highly similar to IS31FL3731 section though.
*

IS31FL3733 driver for LED Matrix

---

quantum/keyboard.c

Cherry picked from 15722 to hopefully minimise changes.
Main aim is to reduce the size of `keyboard_task`, as its become fairly bloated by the matrix scanning logic. Functionality should hopefully be identical after the changes.

Slight tidy up of keyboard task loop

---

docs/feature_combo.md
quantum/process_keycode/process_combo.c

Here's a couple of new configuration features for combos.
`COMBO_MUST_PRESS_IN_ORDER` to force combos to only activate if the keys are pressed in the same order as they are defined in the combo's key array.
Per combo configuration can be modified by defining `COMBO_MUST_PRESS_IN_ORDER_PER_COMBO` and defining
`bool get_combo_must_press_in_order(uint16_t combo_index, combo_t *combo, uint16_t keycode, keyrecord_t *record)` function in which you choose which combos require the correct key order.
This feature even allows multiple combos from the same keys. For example on qwerty layout, `JK` can produce `/` and `KJ` can produce `\`. Just define two combos using the same keys but put the keycodes in reverse order for the other one.
`COMBO_SHOULD_TRIGGER` and its companying function `bool …

New combo configuration options

---

quantum/deferred_exec.c
quantum/deferred_exec.h

Reworks the deferred_exec code to allow for external tables to be specified, so as to not collide with any user-initiated deferred execution.
Core code can use `*_advanced` APIs instead, specifying their own tables -- for instance Quantum Painter has a configurable number of animations, and these new APIs allow the deferred execution limits to match the number of required animations.

Advanced deferred_exec for core-side code.

---

docs/feature_pointing_device.md
drivers/sensors/pmw3360.c

Let the SPI driver handle uploading the full firmware blob.  This procduces a faster init, especially as it was using waits. 
Retains old behavior in case there are issues. However, tested on both F411 blackpill and ploopy mouse (8MHz atmega32u4) without any issues.

Optimize initialization of PMW3360 Sensor

---

keyboards/kudox_full/rules.mk

Enable LTO on Kudox Full, as it's compiling too large on avr-gcc 5.x.  And clean up rules a bit. 
* Tzarc CI

[Keyboard] Fix compiled size for Kudox Full keyboard

---

tmk_core/protocol/chibios/usb_main.c

(Disclaimer: This is the rationale a came up after reading the USB spec, please feel free the chime in if this is wrong)
A SE0 state for longer then 2.5us signals a device disconnect from the USB bus - according to the USB specs. So the 1500ms are much longer than actually needed and had been copied from the ChibiOS demo code. That code does not state any reason for the long wait.
The new 50ms wait was chosen arbitrarily to be barely noticeable, but to be plenty of time for hosts/hubs that do not adhere to the specs. For split keyboards which rely on a fast enumeration for primary / secondary negotiation this shortens the boot up noticeably.
Also a soft reset for the USB connection should only be necessary for:
* MCUs with fixed pull-ups on the data lines that always signal readiness
to …

[Core] ChibiOS: shorten USB disconnect state on boot to 50ms

---

keyboards/ergodox_ez/matrix.c

Since read_cols() in ergodox_ez/matrix.c always returns numbers with two highest bits set,
and suspend_wakeup_condiiton() checks whether they are 0, ergodox_ez
wakes the system immediately after suspend. This very tiny PR fixes that.
Please note that while I have verified that the PR works and doesn't break anything to the extent of my knowledge, I do not know if it's the best place to put the bit mask. Well, at least it identifies the cause of the issue and fixes it *somehow*.
* possibly #15108

Fix suspend issues on ergodox_ez.

---

keyboards/macro1/macro1.c

This commit replaces `encoder_update_user()` with `encoder_update_kb()` in `<keyboard>.c` for the Macro-1 (see <https://docs.qmk.fm/#/feature_encoders>).  With this change, users are able to implement their own `encoder_update_user()` in user keymaps.
Also removes some odd whitespaces/indents.
*

Use correct callback in macro1 implementation

---

keyboards/kbdfans/kbd67/mkiirgb/v4/config.h

I'm seeing double:
https://github.com/qmk/qmk_firmware/blob/5f2b62528c7f94b098baf6ec691c3b6d50e88328/keyboards/kbdfans/kbd67/mkiirgb/v4/config.h#L60-L75

kbdfans/kbd67/mkiirgb/v4: remove duplicate definitions from config.h

---

keyboards/moonlander/moonlander.c

Correction to exclude declaration of LED_6 variable, that was added in #15644
Bug reported by user on Discord

[Bug] Fix compile error caused by variable exclusion

---

docs/feature_pointing_device.md
drivers/sensors/pmw3389.c

During testing the PMW3389 would fail to load the firmware when using spi_transmit for firmware load.  reverting to legacy version and added comment about this testing result.
* PMW3389 sensor would fail to respond unless enabling legacy firmware load

PMW3389 Revert Firmware load during Initilization

---

keyboards/a_dux/a_dux.h
keyboards/a_dux/info.json
keyboards/a_dux/keymaps/default/keymap.c
keyboards/cradio/cradio.h
keyboards/cradio/info.json
keyboards/cradio/keymaps/default/keymap.c
keyboards/ferris/0_1/0_1.h
keyboards/ferris/0_2/0_2.h
keyboards/ferris/info.json
keyboards/ferris/keymaps/default/keymap.json
keyboards/ferris/sweep/sweep.h

Update a_dux, cradio and ferris with the new split_3x5_2 community layout.

[Keyboard] Switch LAYOUT to split_3x5_2

---

docs/feature_macros.md

The docs mentioned `host_language` but in the code example `host_layout` was used.
See above.
* None

Fixed docs: host_layout to host_language

---

keyboards/clueboard/60/info.json
keyboards/clueboard/66/rev4/info.json
keyboards/clueboard/66_hotswap/gen1/info.json
keyboards/clueboard/california/info.json
keyboards/edi/hardlight/mk2/rules.mk
keyboards/ez_maker/directpins/proton_c/info.json
keyboards/forever65/info.json
keyboards/mechlovin/mechlovin9/rev1/rules.mk
keyboards/rgbkb/mun/rules.mk
platforms/chibios/bootloaders/none.c

Most are just missing a bootloader assignment as the change to info.py in #15638 seems to now require the bootloader to be set specifically in info.json.
This also adds a weak `enter_bootloader_mode_if_requested` so chibios builds with an unknown bootloader will compile successfully with an accompanying pragma message.
These keychron boards require the `BOOTLOADER` setting and `STM32_BOOTLOADER_ADDRESS` defining (which would go against the previous work if added to rules.mk). Maybe the MCU configuration should  be added to `builddefs/mcu_selection.mk` in a separate PR. (Compiles as a unknown bootloader with this PR)
```
keychron/q2/rev_0110:default
keychron/q2/rev_0110:via
keychron/q2/rev_0111:default
keychron/q2/rev_0111:via
keychron/q2/rev_0112:default
keychron/q2/rev_0112:via …
```

Fix broken bootloader builds in develop.

---

quantum/dynamic_keymap.c

Exposed by `karlb/kbic65:via`, if there is no config.h, because all the config is in the info.json, via and dynamic keymap will fail to compile.   
config.h should not need to be included, as it's included by the build/make system, automatically.

[Bug] Remove config.h include in dynamic_keymap.c

---

quantum/rgb_matrix/animations/pixel_fractal_anim.h

Add an init function the PIXEL_FRACTAL matrix effect to clear LEDs of previous effect colors on mode change.
RGB mode transition bug that was reported by @sigprof on Discord

[Core] Add init function to clear previous matrix effect

---

data/mappings/keyboard_aliases.json

Reverts qmk/qmk_firmware#15649
Wrongly targeted master instead of develop.

Revert "Update keyboard_aliases.json for KPrepublic, cleaning up after #15047"

---

keyboards/caffeinated/serpent65/info.json
keyboards/dumbpad/v0x/info.json
keyboards/dumbpad/v0x_dualencoder/info.json
keyboards/dumbpad/v0x_right/info.json
keyboards/dumbpad/v1x/info.json
keyboards/dumbpad/v1x_dualencoder/info.json
keyboards/dumbpad/v1x_right/info.json
keyboards/mlego/m48/info.json
keyboards/mlego/m60/info.json
keyboards/mlego/m65/info.json
keyboards/neopad/rev1/info.json
keyboards/spaceman/pancake/rev2/info.json

Recently learned that an incorrect `keyboard_folder` value can prevent QMK Configurator from compiling a keyboard. Most of these were correct, but clearing them out since they're not at all needed.
* @jrfhoutx (`caffeinated/serpent65`)
* @imchipwood (`dumbpad`)
* @alinelena (`mlego/` directory)
* @rookiebwoy (`neopad/rev1`)
* @Spaceman (`spaceman/pancake/rev2`)

Remove `keyboard_folder` instances from `info.json` files

---

quantum/keyboard.c
quantum/quantum.c

Dependency for #15722.
Having 2 files which collect the various `_task`s adds unnecessary complexity. While overall behaviour should be *mostly* the same, with this PR the order will have slightly changed.
Before:
1. scan matrix
2. master only tasks
3. ` matrix_scan_kb`/`matrix_scan_user`
4. other tasks
After:
1. scan matrix
3. ` matrix_scan_kb`/`matrix_scan_user`
2. master only tasks
4. other tasks
Given how the scan callbacks have little way in interaction with the other tasks, it should be fairly safe to change the order.
Also,
* `led_matrix_task` would previously be called twice on splits
* mid file `hd44780.h` include removed
*Note:* Future iterations are planned to further sort out the fragmentation shown by the tmk_core+quantum merge.

Relocate matrix_scan_quantum tasks

---

keyboards/gmmk/pro/ansi/keymaps/andrebrait/keymap.c
keyboards/gmmk/pro/ansi/keymaps/andrebrait/readme.md
keyboards/gmmk/pro/ansi/keymaps/andrebrait/rules.mk

Disable Mouse Keys on my keymap so it fixes my issues with my KVM switch.
*

Small code improvements, fix KVM switch issues with GMMK Pro on andrebrait's keymap

---

docs/feature_pointing_device.md

Hello!
I noticed a typo when reading the documentation, so I'm sending a fix.
Thank you for maintaining QMK!

[Docs] Fix typo in sensor name

---

docs/feature_grave_esc.md
docs/keycodes.md
docs/quantum_keycodes.md
quantum/process_keycode/process_grave_esc.c
quantum/quantum.c
quantum/quantum_keycodes.h
quantum/quantum_keycodes_legacy.h
quantum/via_ensure_keycode.h

Part of an effort to normalise keycode names.
Renamed keycodes:
|Old Keycode   |New Keycode      |
|--------------|-----------------|
|`RESET`       |`QK_BOOTLOADER`  |
|`DEBUG`       |`QK_DEBUG_TOGGLE`|
|`GRAVE_ESC`   |`QK_GRAVE_ESCAPE`|
|`EEPROM_RESET`|`QK_CLEAR_EEPROM`|
Added aliases:
|Alias    |Keycode          |
|---------|-----------------|
|`QK_BOOT`|`QK_BOOTLOADER`  |
|`DB_TOGG`|`QK_DEBUG_TOGGLE`|
|`EE_CLR` |`QK_CLEAR_EEPROM`|
|`QK_GESC`|`QK_GRAVE_ESCAPE`|
Removed aliases:
|Alias    |Replacement|
|---------|-----------|
|`EEP_RST`|`EE_CLR`   |
|`KC_GESC`|`QK_GESC`  |
*

Rename some Quantum keycodes

---

quantum/keymap.h

Fix hacky workaround being broken, by re-applying hack. Followup to #15968 
* Compilation issue

[Bug] Fix hack for chibiOS reset name

---

docs/feature_mouse_keys.md
quantum/mousekey.h

The accelerated mode defaults for mouse key are sluggish, while the kinetic mode ones are too jumpy. These changes will make both of them more usable.

Adjust mouse key defaults

---

keyboards/mschwingen/modelm/matrix.c

Fix build failures for `mschwingen/modelm`

---

quantum/led.c

Non backlight keyboards are currently spitting out the following error:
```
Compiling: quantum/led.c                                                                           quantum/led.c:24:13: note: '#pragma message: Cannot use BACKLIGHT_CAPS_LOCK without backlight being enabled'
24 | #    pragma message "Cannot use BACKLIGHT_CAPS_LOCK without backlight being enabled"
|             ^~~~~~~
[OK]
Compiling: 
```
Seems i let the some logic changes slip through when merging files.

Fix BACKLIGHT_CAPS_LOCK warning

---

quantum/led.c

It's erroring out on chibiOS on the gpio controls. 
Includes gpio.h, which should fix the issue.
* compilation error

[Bug] Fix compilation issues for led indicators

---

quantum/keyboard.c
quantum/matrix.c
quantum/matrix_common.c
quantum/quantum.c

Dependency for #15722.
Along the same lines as 15882, this moves the init pathway to a single file.

Relocate matrix_init_quantum content

---

keyboards/clueboard/66_hotswap/gen1/rules.mk

No such led.c exists for this board (but it does for the clueboard 60)
*

[Keyboard] Fix erroneous SRC for Clueboard 66 hotswap

---

common_features.mk
platforms/chibios/eeprom_teensy.c

Default implementation of EEPROM when unspecified was to use a transient-like implementation, implemented in `eeprom_teensy.c`. This moves the normal implementation to be the _actual_ transient EEPROM implementation, decoupling the implementations further.
All keyboards build, apart from the same two boards currently failing on `develop`.

EEPROM refactor: remove `eeprom_teensy.c` by default, use transient instead

---

keyboards/bpiphany/frosty_flake/20130602/20130602.c
keyboards/bpiphany/frosty_flake/20140521/20140521.c

4c080be seemed to swap the LED pins for the 20130602 and 20140521
variants. 20140521 is fine now, 20130602 untested but per the
schematics at https://deskthority.net/wiki/Costar_replacement_controllers
it seems correct.
This addresses the mixup of LED assignment for the frosty flake controller (20140521 vs 20130602) that happened in 4c080be
* regression introduced in https://github.com/qmk/qmk_firmware/pull/15365

[Keyboard] Fix frosty_flake LED pin assignment

---

platforms/arm_atsam/bootloaders/md_boot.c

I misread the code here and for some reason reworked it so that *all* CTRL boards used this "RAM method" instead of tripping the watchdog... which is not correct.
*

Fix bootloader_jump for certain CTRL boards

---

Makefile
build_keyboard.mk

Some perf. some tidy up.
* Remove more unused content
* Avoid as much as possible when running simple commands like `make clean`
* Be lazier when handling test discovery
* No point generating version.h
* Align location of phony targets
msys before
```
$ time make clean
QMK Firmware 0.15.11
real    0m5.124s
user    0m0.122s
sys     0m0.288s
```
msys after
```
$ time make clean
QMK Firmware 0.15.11
real    0m0.322s
user    0m0.075s
sys     0m0.166s
```

Various Makefile optimisations

---

util/docker_cmd.sh

Newer versions of `clang-format` produce different output compared to what's in the container.
Given that CI runs in the container, needed a simpler method of executing against the "blessed" version.
This adds a new command, `util/docker_cmd.sh`, which effectively just executes whatever arguments you pass to the script as another command, but inside the container.
Basically a dupe of `util/docker_build.sh`.

Add a script that simplifies running commands under docker.

---

Makefile

* Match with grep rather than recursive calls
* Use python to minimise any environment issues
* Try not to break things...
Some crude perf testing seems to suggest its roughly the same on msys, and maybe marginally faster under wsl.
* Fixes #13416

Workaround in Makefile for recursive rule matching

---

docs/feature_pointing_device.md
quantum/pointing_device.c
quantum/pointing_device.h
quantum/split_common/transactions.c

This doesn't appear to have any downsides and only improves split performance with the default of 1. AVR in particular struggles with this not being limited.
*

Enable a default task throttle for split pointing.

---

platforms/arm_atsam/suspend.c
platforms/avr/suspend.c
platforms/chibios/suspend.c
platforms/suspend.h

Unused, so no point in keeping (and implementing in RIOT port).

Remove unused suspend_idle

---

drivers/serial.h
platforms/avr/drivers/serial.c
platforms/chibios/drivers/serial.c
platforms/chibios/drivers/serial_usart.c
quantum/split_common/transactions.c
quantum/split_common/transactions.h
quantum/split_common/transport.c

It is a left over from previous serial implementations like the helix keyboard. The field is read and written to in split communications, but never evaluated as the current core implementation relies on the return value of `soft_serial_transaction` which is treated as a bool anyways. Therefore status is removed and `soft_serial_transaction` returns a bool now.
`soft_serial_get_and_clean_status` is removed as well as it is dead code.
**AVR: -202 Bytes**
```
./util/size_regression.sh -d maintenance/deprecate-transaction-status crkbd:default
Size:    27572, delta:   -202 -- 2582edb1da Deprecate split transactions status field
```
**ARM: +96 Bytes**
```
./util/size_regression.sh -d maintenance/deprecate-transaction-status zvecr/zv48/f411:default
Size:    34352, delta:    +96 -- 2582edb1da …
```

[Core] Deprecate Split Transaction status field

---

keyboards/kprepublic/bm65hsrgb_iso/bm65hsrgb_iso.c
keyboards/kprepublic/bm65hsrgb_iso/config.h

[Keyboard] Fixing missing led for keys, positioning and flags
When trying to implement more advanced lighting features for the kprepublic bm65hsrgb_iso keyboard. I found missing keys in the ledmap, positioning and flags. Flags are changed to be consistent with actual usage of keys.
Also adding wakeup and powerdown functions for future use.
NONE

[Keyboard] fixed led_config: missing key, missing/wrong flags

---

docs/feature_encoders.md

Add a description for multiple encoders feature in docs/feature_encoders.md cause the feature is only effective under limited conditions.
Here is a brief explanation.
#define ENCODERS_PAD_A { B1, B1 }
#define ENCODERS_PAD_B { B2, B3 }
ENCODER1
A ‾‾|__|‾‾|__|‾‾|__|‾‾|__|‾‾|__|
B ‾|__|‾‾|__|‾‾|__|‾‾|__|‾‾|__|‾
When the (stationary) encoder1's pad_A is low, B1 pin is shorted to GND, so no matter how much you turn the encoder2, the encoder2's pad_A cannot change from low, as shown below.
ENCODER2
A ______________________________ 
B ‾|__|‾‾|__|‾‾|__|‾‾|__|‾‾|__|‾
Encoder2 works properly when pad_A of encoder1 is High.
Luckily, some encoders always stop at a place where both pins are high.
However, there are encoders that stop at other places. Also, of course, all non-detent encoders don't have …

Update feature_encoders.md for multiple encoders

---

quantum/quantum.c

Unlike `tap_code`, `tap_code16` does not apply the caps lock delay (`TAP_HOLD_CAPS_DELAY`), when the key code is caps lock. As a result, in most operating systems, the caps lock key will not register since it's cycled too quickly. This change mirrors [the structure of `tap_code`](https://github.com/qmk/qmk_firmware/blob/c6ad3bf23d10d806c784c4cc3ceb7491a874de69/quantum/action.c#L970), but using the same function `wait_ms`, [as is currently in `tap_code16`](https://github.com/qmk/qmk_firmware/blob/c6ad3bf23d10d806c784c4cc3ceb7491a874de69/quantum/quantum.c#L102), to add this delay in, if the key code is caps lock.
This is consistent with existing documentation which says that the 16 version of the function behaves "similar" to the non 16 version.
> These functions work similar to their …

Adjust tap_code16 to account for TAP_HOLD_CAPS_DELAY

---

quantum/process_keycode/process_combo.c

`TAP_CODE_DELAY`: Some software (e.g. some games) don't like key press and release events too close to each other, so a delay is needed after dumping the key buffer in combo processing.
`clear_weak_mods`: Before, weak mods from combos could leak to the next key press if pressed too fast.

Combo `TAP_CODE_DELAY` and `clear_weak_mods`

---

keyboards/studiokestra/bourgeau/bourgeau.h
keyboards/studiokestra/bourgeau/info.json
keyboards/studiokestra/bourgeau/keymaps/default/keymap.c
keyboards/studiokestra/bourgeau/keymaps/via/keymap.c

`LAYOUT_75_ansi_rwkl` is the only supported layout.
cc @studiokestra (keyboard maintainer)

Studio Kestra Bourgeau: rename LAYOUT_all to LAYOUT_75_ansi_rwkl

---

keyboards/gmmk/pro/ansi/keymaps/hachetman/config.h
keyboards/gmmk/pro/ansi/keymaps/hachetman/keymap.c
keyboards/gmmk/pro/ansi/keymaps/hachetman/readme.md
keyboards/gmmk/pro/ansi/keymaps/hachetman/rules.mk

Keymap to GMMK Pro added based on andrebrait with additional overrides to UP and DOWN

[Keymap] Add hachetman layout for GMMK Pro

---

drivers/led/ckled2001.c

This PR adds a slight alteration of the Keychron CKLED2001 led driver initialisation code in core where in the Keychron Q-series keyboards require the initialization bit to be set to 0xA0 instead of 0xFF on certain tune lengths *(as implemented in the working copy of the Q-series hosted on the `keychron/qmk_firmware:playground` repo, and a follow up of PR #14872)*.

Add support for Q-series on the ckled2001 LED driver

---

docs/isp_flashing_guide.md

ISP programmers based on USBtinyISP (including SparkFun PocketAVR) do not support AVR chips with more than 64 KiB of flash (e.g., AT90USB1286/7).  Add a warning about that limitation to the ISP flashing guide (apparently the shop pages for those programmers do not emphasise this limitation enough).
The limitation is actually in the USB protocol between `avrdude` and the programmer firmware (the field for byte address in the flash has only 16 bits), so it cannot be fixed with “just” a minor firmware update (which would require a second ISP flasher anyway).
USBasp now has a separate section, because it does not have the 64 KiB flash size limit (in fact, the USBasp firmware seems to support even chips with more than 128 KiB of flash, which need an extra command to set high address bits).
I …

Add a warning about USBtinyISP limitations to the ISP flashing guide

---

keyboards/linworks/fave84h/keymaps/default/keymap.c
keyboards/linworks/fave87h/keymaps/default/keymap.c

```
Compiling: keyboards/linworks/fave84h/keymaps/default/keymap.c                                     keyboards/linworks/fave84h/keymaps/default/keymap.c:43:1: error: expected identifier or ‘(’ before ‘}’ token
```
*

Fave84H/87H: Fix stray closing brace in default keymap

---

docs/feature_rgb_matrix.md
docs/feature_rgblight.md

As titled, a frequently asked question on Discord for RGB indicators on split keyboards.

Add reference to split data sync options for RGB

---

build_keyboard.mk
lib/python/qmk/cli/multibuild.py

Moves the creation of `version.h` into a keyboard-specific location, so that parallel builds don't obliterate each other.
Also fixes up `qmk multibuild` to allow for `-e SKIP_VERSION=yes` and the like to be added, much like `qmk compile` already does.

Fixup multibuild filegen

---

lib/python/qmk/cli/doctor/main.py
lib/python/qmk/commands.py

Also handles the case where the repo has no tags (as I prefer it):
```
fauxpark@JUNE:qmk_firmware$ git tag 0.15.18
fauxpark@JUNE:qmk_firmware$ qmk doctor
Ψ CLI version: 1.0.0
Ψ QMK home: D:/Git/qmk_firmware
Ψ Detected Windows 10 (10.0.19043).
Ψ Git branch: master
Ψ Repo version: 0.15.18
⚠ Git has unstashed/uncommitted changes.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.4.0
Ψ Found avrdude version 6.3
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go, but minor problems were found
1 fauxpark@JUNE:qmk_firmware$ git tag -d 0.15.18
Deleted tag '0.15.18' (was 59f37bb710)
fauxpark@JUNE:qmk_firmware$ qmk doctor
Ψ QMK Doctor is …
```

`qmk doctor`: display qmk_firmware version tag

---

lib/python/qmk/cli/pytest.py
lib/python/qmk/tests/test_cli_commands.py

* Reformat python due to yapf changes
* Fix pytest keymap list test due to moved nui_mini

Fix issues with Python Tests

---

build_keyboard.mk
lib/python/qmk/cli/generate/version_h.py

Last attempt at moving version.h to a different location resulted in a one-time generation without a clean. This makes sure it's recreated each time.

Ensure `version.h` is recreated each build.

---

drivers/bluetooth/outputselect.c

Removes platform ifdefs, which in turn removes the need for some of the proposed changes in <https://github.com/qmk/qmk_firmware/pull/15947>
*

Update outputselect to use platform connected state API

---

platforms/chibios/timer.c

Fix several problems in the QMK timer API implementation for ChibiOS:
1.  The code uses a 32-bit tick counter internally, and that counter is overflowing and wrapping around faster than the 32-bit millisecond counter used by QMK:
* With `CH_CFG_ST_FREQUENCY` set to 10000 (typically used with the periodic tick mode, or with 16-bit hardware timers), the tick counter overflow happens after slightly less than 5 days of continuous runtime.
* With `CH_CFG_ST_FREQUENCY` set to 100000 (default for most chips with 32-bit hardware timers), the tick counter overflow happens after slightly less than 5 hours.
However, the existing timer code did not handle the tick counter overflow correctly — instead of continuing the millisecond counting further, the QMK timer value was reset back to 0; this broke …

ChibiOS timer fixes

---

docs/feature_rgb_matrix.md
docs/squeezing_avr.md
quantum/rgb_matrix/animations/pixel_flow_anim.h
quantum/rgb_matrix/animations/rgb_matrix_effects.inc

Add a PIXEL FLOW matrix effect, that was previously decoupled from #12670

[Core] Add Pixel Flow RGB matrix effect

---

lib/python/qmk/cli/generate/develop_pr_list.py

`develop` changelog generator: skip code formatting in listing

---

keyboards/amag23/keymaps/via/keymap.c
keyboards/amag23/keymaps/via/rules.mk

Add Via-compatible keymap for Koolertron AMAG23

Add Via-compatible keymap for Koolertron AMAG23

---

build_keyboard.mk
build_layout.mk
builddefs/bootloader.mk
builddefs/message.mk
common_features.mk

Build errors weren't always consistently printing `[ERRORS]` in the output. `qmk multibuild` expects this in the output, so this normalises all errors in the QMK-side makefiles to print out in the correct format.
For example:

Standardise error output.

---

platforms/avr/platform.mk
platforms/chibios/platform.mk
testlist.mk

More output I missed in #16220.

Followup to #16220, more test error output.
