qmk/qmk_firmware

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix/rgb_matrix.c
- quantum/rgb_matrix/rgb_matrix.h
This adds a  a trivial `rgb_matrix_reload_from_eeprom()` implementation drawing heavily from the equivalent `rgblight_reload_from_eeprom()`.
It is cherry-picked from https://github.com/qmk/qmk_firmware/pull/15922
> RGB Matrix: Reload from EEPROM

- common_features.mk
- docs/feature_pointing_device.md
- keyboards/3w6/rev2/keymaps/default_pimoroni/rules.mk
- keyboards/crkbd/keymaps/vlukash_trackpad_right/rules.mk
- keyboards/dichotomy/rules.mk
- keyboards/gergo/keymaps/abstractkb/rules.mk
- keyboards/gergo/keymaps/default/rules.mk
- keyboards/gergo/keymaps/germ/rules.mk
- keyboards/gergo/keymaps/gotham/rules.mk
- keyboards/gergo/keymaps/oled/rules.mk
- keyboards/honeycomb/rules.mk
- keyboards/molecule/rules.mk
- keyboards/splitkb/kyria/keymaps/gotham/rules.mk
A typo like `POINTING_DEIVCE_DRIVER = adns5050` now produces an error when compiling rather than using `POINTING_DEVICE_DRIVER = custom`.
I've included the required rules.mk changes, so keymaps/keyboards that were missing the rule still have the same behaviour as before this change.
*
> Remove default pointing device driver.

- quantum/process_keycode/process_dynamic_macro.c
By doing so, methods like 'layer_state_set_user' will be called, ensuring a correct behavior.
This is a fix for https://github.com/qmk/qmk_firmware/issues/16208. 
Restoring the layer state using `layer_state = saved_layer_state` doesn't call methods like `layer_state_set_user` leading to strange behavior (like shutting down the leds on the moonlander) 
* https://github.com/qmk/qmk_firmware/issues/16208
Note regarding tests: the original fix has been made on the zsa fork. A firmware has been build and tested `layer_state_set_user` is now called two times (from layer 0 then go back to actual layer)
To make this PR I've:
- checkout the master branch
- cherry picked the fix
- `make test:all` (everything is OK)
> [Bug] Fix `layer_state` restoration at end of dynamic macro feature #16208

- docs/data_driven_config.md
- docs/hardware_keyboard_guidelines.md
Added info_config.h added in #10817 to the include order description of config.h.
> add 'info_config.h' into docs/hardware_keyboard_guidelines.md

- keyboards/work_louder/work_board/work_board.c
- quantum/via.c
- quantum/via.h
Provides a way for keyboards to get the layout options, without having to constantly querying the eeprom.  what/how to implement that is left up to users.
> Add layout change callbacks to VIA

- util/size_regression.sh
- Sets environment variable SIZE_REGRESSION_EXECUTING during execution
so hook scripts like `post-checkout` may skip processing.
- Forces checkout of the target branch, including removal of all
temporary object files in the process.
- Prints out a warning on exit stating that the git repository is in an
indeterminate state, and the user needs to swap back to whatever
intended branch they were working with originally.
> Misc size regression script improvements.

- keyboards/melgeek/mach80/rev2/config.h
- keyboards/melgeek/mach80/rev2/rev2.c
- keyboards/melgeek/mach80/rev2/rules.mk
> [Keyboard] MelGeek Mach80 rev2

- drivers/gpio/pca9555.c
- drivers/gpio/pca9555.h
- keyboards/moon/matrix.c
- keyboards/switchplate/southpaw_65/matrix.c
- keyboards/xiudi/xd84/matrix.c
- keyboards/xiudi/xd96/matrix.c
Was originally part of #15944 but split out to separate the concerns slightly.
> Align existing pca9555 driver to better match mcp23018 API

- keyboards/capsunlocked/cu75/rules.mk
- keyboards/ergodox_ez/keymaps/default_glow/rules.mk
- keyboards/hhkb/ansi/post_rules.mk
- keyboards/hhkb/jp/post_rules.mk
- keyboards/rgbkb/mun/rules.mk
- keyboards/rgbkb/sol3/rules.mk
Cleanup, relative paths were being defined in a few keyboards, messing with the relative locations in `.build/` during build. 
In one case, CI was showing issues with intermediate files being removed due to multiple boards from the same manufacturer resulting in the same output file.
For example, rgbkb/sol3 and rgbkb/mun were both targeting:
```
.build/obj_rgbkb_sol3_rev1/../common/touch_encoder.o   =>   .build/common/touch_encoder.o
.build/obj_rgbkb_mun_rev1/../common/touch_encoder.o    =>   .build/common/touch_encoder.o
```
> Remove parent-relative paths from keyboards.

- tmk_core/rules.mk
There's been a few instances of people trying to flash the hex file listed during size checks, rather than the output firmware in the root directory. This is problematic for ARM builds, as they'll generally be in BIN format -- the output still lists the HEX path.
Old:
New:
> Size checks print out target firmware file instead

- keyboards/maxr1998/pulse4k/keymaps/default/keymap.c
- keyboards/maxr1998/pulse4k/keymaps/default/rules.mk
- keyboards/maxr1998/pulse4k/keymaps/maxr1998/keymap.c
- keyboards/maxr1998/pulse4k/keymaps/maxr1998/rules.mk
- keyboards/maxr1998/pulse4k/pulse4k.c
- keyboards/maxr1998/pulse4k/rules.mk
The Combo feature cannot be enabled at the keyboard level, as it requires code that will not exist when compiling a Configurator JSON or in the Configurator itself, producing a linker error:
```
Linking: .build/maxr1998_pulse4k_maxr1998_pulse4k_layout_mine.elf
[ERRORS]
|
| c:/msys64/mingw64/bin/../lib/gcc/avr/8.4.0/../../../../avr/bin/ld.exe: .build/obj_maxr1998_pulse4k_maxr1998_pulse4k_layout_mine/keyboards/maxr1998/pulse4k/pulse4k.o:D:\Git\qmk_firmware_develop/keyboards/maxr1998/pulse4k/pulse4k.c:27: undefined reference to `led_adjust_combo'
| collect2.exe: error: ld returned 1 exit status
|
make: *** [tmk_core/rules.mk:364: .build/maxr1998_pulse4k_maxr1998_pulse4k_layout_mine.elf] Error 1
```
This moves the Combo code into the keymaps, allowing users to customize it more freely, and …
> maxr1998/pulse4k: Move Combo code to keymap level

- builddefs/common_features.mk
This was missed in https://github.com/qmk/qmk_firmware/pull/14895.
Thanks to fauxpark for spotting this.
Fixes PS2 busywait compilation.
> ps2/avr: use the correct file name

- quantum/matrix.c
<https://github.com/qmk/qmk_firmware/pull/16287#discussion_r803194988>
The main issue, `matrix_init_pins` within `DIRECT_PINS` iterates double what it should on splits.
Remaining changes are to avoid using arrays double the required size.
> Various fixes for matrix _RIGHT handling

- quantum/action_tapping.c
- quantum/pointing_device_drivers.c
- quantum/process_keycode/process_tap_dance.c
[BUG FIX]
The second `keyrecord_t*` argument given to tap hold per key functions should refer to the same key as that given in the first `uint16_t keycode`  argument. All the per-key functions called in `bool process_tapping(keyrecord_t *keyp)` use the same pattern : `get_option(tapping_keycode, keyp)` but from what I've gathered, `keyp` is not necessarily the `tapping_key` so it should instead be `get_option(tapping_keycode, &tapping_key)`.
To illustrate my point:
Let the key on row=1, col=3 be MT(MOD_LSFT, KC_S) (hexadecimal keycode=0x6216 ) and the key on row=2, col=7 be KC_H.
Consider the following body for the `get_tapping_term` function.
```c
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
uprintf("0x%04X,%u,%u,%u,%u\n",
keycode,
record->event.key.row, …
```
> Pass in the keyrecord_t of the dual-role/tapping key when calling per-key tap hold functions

- quantum/rgb_matrix/rgb_matrix_drivers.c
I'm assuming this is a bug but I'm unsure if targeting master is the correct option as it may break users keymaps depending on which index they used to address the right side leds.
So the example below shows the issue, where index 12 and 30 currently refers to the same physical led on the right side.
```c
// config.h
RGB_MATRIX_SPLIT { 18, 18 }
// keymap.c
void rgb_matrix_indicators_user(void) {
rgb_matrix_set_color(30, 0, 0, 255); // blue
rgb_matrix_set_color(12, 255, 255, 255); // white
}
```
This currently results in the led being white but after applying this PR it's blue as you'd expect.
*
> Fix right side ws2812 leds having two indices

- keyboards/handwired/dactyl_manuform/5x6/keymaps/uqs/config.h
- keyboards/handwired/dactyl_manuform/5x6/keymaps/uqs/keymap.c
- keyboards/handwired/dactyl_manuform/5x6/keymaps/uqs/rules.mk
- keyboards/ploopyco/mouse/keymaps/uqs/keymap.c
- keyboards/ploopyco/mouse/keymaps/uqs/rules.mk
- keyboards/preonic/keymaps/uqs/keymap.c
- keyboards/preonic/keymaps/uqs/rules.mk
- keyboards/splitkb/kyria/keymaps/uqs/config.h
- keyboards/splitkb/kyria/keymaps/uqs/keymap.c
- keyboards/splitkb/kyria/keymaps/uqs/rules.mk
- users/uqs/config.h
- users/uqs/rules.mk
- users/uqs/uqs.c
- users/uqs/uqs.h
This contains a log of my 1 year journey to switch to ColemakDH. Some
other features are:
- nice Alt+Tab using the layer hold as Alt hold
- OSM that work (for me)
- ugly but significantly less verbose way to set combos
- some _Static_asserts to stop me from being silly
*
> Add uqs' keymaps for various boards and ploopy mouse

- .clang-format
*May* need some testing as the clang-format file seems not exactly stable across versions (specifically value types).
*
> Clang-format tweaks

- lib/python/qmk/cli/new/keyboard.py
- lib/python/qmk/constants.py
Make the output a little bit easier to read and provide more context to the user when the selected keyboard name is already used.
*
> CLI: Minor additions #12795

- keyboards/handwired/aball/aball.c
- keyboards/handwired/aball/aball.h
- keyboards/handwired/aball/keymaps/default/keymap.c
- keyboards/ploopyco/trackball_nano/keymaps/default/keymap.c
- keyboards/ploopyco/trackball_nano/keymaps/maddie/keymap.c
- keyboards/ploopyco/trackball_nano/trackball_nano.c
- keyboards/ploopyco/trackball_nano/trackball_nano.h
`handwired/aball` and `ploopyco/trackball_nano` both have `keymaps` at keyboard level. This was done because they have no actual keys, so there is not much point in having it at keymap level. However, this confuses the compiler when generating a keymap from JSON:
The simple fix is to move `keymaps` back to keymap level.
*
> Fix multiple definition errors for trackball "boards" with no keys

- data/templates/keyboard/config.h
- data/templates/keyboard/info.json
- lib/python/qmk/cli/new/keyboard.py
- lib/python/qmk/info.py
While working on #16357, I noticed a few issues
* `MANUFACTURER` was not being generated
* Formatting of some python code was a bit meh
* A default `config.h` for some of the unconverted options *could* be handy in the short term
*
> Various fixes for new-keyboard

- data/schemas/definitions.jsonschema
Mostly so that sparse `DIRECT_PINS` can be correctly configured without having to use a 1xN matrix.
Modifying `mcu_pin` does however allow other features to be incorrectly configured with `NO_PIN`. As an alternative solution, a new variant of `mcu_pin_array` could be introduced so that it limits the change to only matrix config.
*
> Allow NO_PIN within data driven configuration

- keyboards/helix/pico/split_util.h
- keyboards/helix/rev1/split_util.h
- keyboards/helix/rev2/split_util.h
With no reply on #16009 and code freeze looming, this at least returns the helix builds back to its previously fragmented state.
> Bodge for helix build failures

- quantum/quantum.c
In #14210, all previous calls to `suspend_power_down_kb()` were replaced with calls to `suspend_power_down_quantum()`, together with some much needed deduplication. However, the `_kb` function was never called from the `_quantum` one (unlike `suspend_wakeup_init_kb()`).
I followed the example of how it was implemented for AVR before #14210, i.e. called before the rest of the suspend functions, regardless of the `NO_SUSPEND_POWER_DOWN` setting.
* #16279
> Re-add call to `suspend_power_down_kb()`.

- keyboards/mlego/m60_split/info.json
- keyboards/splitkb/kyria/rev1/proton_c/rules.mk
These two boards fail to build in Configurator, because the ChibiOS submodules are not being pulled down.
`qmk info` misidentifies `mlego/m60_split/rev1` and `rev2` as AVR due to `keyboard_folder` pointing at the root, which has no rules.mk, causing `_extract_rules_mk()` to pull absolutely nothing and defaulting to 32u4/atmel-dfu.
For `splitkb/kyria/rev1/proton_c`, this has to do with the fact that `qmk info` doesn't understand `CONVERT_TO_PROTON_C`. Might be a bodge, but explicitly overriding the MCU and bootloader should do the job - CTPC can do the rest at compile time.
*
> Fix a couple of boards being wrongly identified as AVR

- keyboards/clueboard/card/info.json
- keyboards/clueboard/card/keymaps/default/rules.mk
- keyboards/clueboard/card/keymaps/rgb_effects/rules.mk
Command makes no sense with the form factor of this board, and is oversize by 732 bytes according to qmk_error_page.
*
> clueboard/card: disable Command to reduce size

- keyboards/splitkb/kyria/keymaps/default/config.h
- keyboards/splitkb/kyria/kyria.c
- keyboards/splitkb/kyria/readme.md
- keyboards/splitkb/kyria/rev2/config.h
- keyboards/splitkb/kyria/rev2/proton_c/chconf.h
- keyboards/splitkb/kyria/rev2/proton_c/halconf.h
- keyboards/splitkb/kyria/rev2/proton_c/mcuconf.h
- keyboards/splitkb/kyria/rev2/proton_c/proton_c.c
- keyboards/splitkb/kyria/rev2/proton_c/proton_c.h
- keyboards/splitkb/kyria/rev2/proton_c/rules.mk
- keyboards/splitkb/kyria/rev2/rev2.c
- keyboards/splitkb/kyria/rev2/rev2.h
- keyboards/splitkb/kyria/rev2/rules.mk
- keyboards/splitkb/kyria/rules.mk
This commit adds the code to support the newest revision of splitkb's Kyria.
Compared to the Kyria 1.x, the 2.x series features the following significant changes:
- Handedness by matrix pin
- Reworked matrix wiring
- Reworked WS2812B ordering
This means a new software revision is required as those make it backwards incompatible.
The code is pretty much a copy/paste from rev1, with minor changes where neccesary.
_**Note:** `make keyboard:all` returned firmware size errors, but those were already present before this commit._
_**Note:** Proton-C support has not been tested as we do not have a pair of controllers at hand._
> Add splitkb Kyria rev. 2

- keyboards/redox_w/keymaps/dvorak/keymap.c
- keyboards/redox_w/keymaps/dvorak/readme.md
- keyboards/redox_w/redox_w.c
- keyboards/redox_w/redox_w.h
add white led control,and remove useless led define,like "set_led_yellow"  @mattdibi 
add dvorak layout,and caps_lock,num_lock led Indicators
*
> [redox_w] add dvorak layout and white led support

- docs/flashing.md
Primarily for Linux users who can't use the Toolbox and already have a .hex or .bin file.
*
> Add commands to flashing docs

- keyboards/helix/rev2/keymaps/edvorakjp/oled.h
'helix/rev2/keymaps/edvorakjp' was no longer buildable due to changes made by #14864.
The reason is that the prototype of `oled_task_user()` was changed in keymaps/edvorakjp/oled.c, but keymaps/edvorakjp/oled.h was not changed.
Therefore, I modified the prototype in keymaps/edvorakjp/oled.h.
* #14864
> fix helix/rev2:edvorakjp build error

- data/schemas/keymap.jsonschema
- lib/python/qmk/cli/json2c.py
- lib/python/qmk/commands.py
- lib/python/qmk/json_schema.py
- lib/python/qmk/path.py
- lib/python/qmk/tests/test_cli_commands.py
The `flash`, `compile` and `json2c` subcommands accept user-provided JSON keymaps.
Instead of accepting them as is, use the already existing schema and its validator to check if the provided file is
1) a JSON file
2) a Configurator-compatible JSON keymap
I've also added test cases, but I'm not particularly happy with them. However a more "proper" testing would need additional refactoring and I wanted to keep the scope of this change limited.
*
> CLI: Validate JSON keymap input

- keyboards/projectcain/vault35/config.h
- keyboards/projectcain/vault35/keymaps/default/config.h
- keyboards/projectcain/vault35/keymaps/default/rules.mk
- keyboards/projectcain/vault35/rules.mk
- keyboards/projectcain/vault45/config.h
- keyboards/projectcain/vault45/keymaps/default/config.h
- keyboards/projectcain/vault45/keymaps/default/rules.mk
- keyboards/projectcain/vault45/rules.mk
From https://yanfali.github.io/qmk_error_page/
```
Ψ Compiling keymap with make -s --jobs=1 -r -R -f builddefs/build_keyboard.mk KEYBOARD=projectcain/vault35 KEYMAP=default_configurator KEYBOARD_FILESAFE=projectcain_vault35 TARGET=projectcain_vault35_default_configurator KEYBOARD_OUTPUT=.build/obj_projectcain_vault35 KEYMAP_OUTPUT=.build/obj_projectcain_vault35_default_configurator MAIN_KEYMAP_PATH_1=.build/obj_projectcain_vault35_default_configurator MAIN_KEYMAP_PATH_2=.build/obj_projectcain_vault35_default_configurator MAIN_KEYMAP_PATH_3=.build/obj_projectcain_vault35_default_configurator MAIN_KEYMAP_PATH_4=.build/obj_projectcain_vault35_default_configurator MAIN_KEYMAP_PATH_5=.build/obj_projectcain_vault35_default_configurator …
```
> Move projectcain encoder logic to keyboard level

- docs/newbs_getting_started.md
I changed the typo "reitroduced" to "reintroduced" in docs/newbs_getting_started.
> fixed typo in docs/newbs_getting_started.md

- quantum/action_util.c
fix v-usb  usb reporting by enabling empty reports for vusb
fixes vusb enumeration issues
> fix v-usb connection enumeration, ifdef workaround

- data/mappings/info_config.json
- data/mappings/info_rules.json
- docs/data_driven_config.md
- lib/python/qmk/cli/generate/config_h.py
- lib/python/qmk/cli/generate/rules_mk.py
- lib/python/qmk/info.py
In order for the USB manufacturer and product strings to be represented as string literals in future, the CLI mappings need to distinguish between values that are simply inserted into the generated files, and values that should be surrounded with quotes. Thus, I propose the default `value_type` be changed to `raw`, with `str` values treated as string literals and quotes added/removed as necessary.
I also fixed a slight issue I encountered in testing this where the generated config.h was not being written as UTF-8 (on Windows, at least).
*
> Change data driven "str" type to represent a quoted string literal

- data/schemas/definitions.jsonschema
- data/schemas/keyboard.jsonschema
Validation of `keymap.json` has shown that many more layout macros are considered invalid. `info.json` can currently contain values that cannot be keyed against with the corresponding `keymap.json` property.
Adding in the validation from #16142 along with a ton of exceptions will keep the 2 logical parts in step.
* Fixes #16515
> More validation of declared LAYOUT macro names

- data/mappings/info_config.json
- keyboards/sowbug/68keys/config.h
- keyboards/sowbug/ansi_tkl/config.h
- keyboards/unicomp/spacesaver_m_pre_2013/overnumpad_1xb/config.h
- keyboards/xelus/ninjin/config.h
- lib/python/qmk/tests/test_cli_commands.py
Somewhat follow up to #16516. 
*
> Map data driven `DESCRIPTION` as string literal

- data/templates/keyboard/info.json
`bootmagic_lite` is no longer a valid option, no validation of keys in this area allowed this to slip through on the recent rewwork.
*
> Fix new-keyboard bootmagic setting

- lib/python/qmk/keyboard.py
> `qmk info`: nicer rendering of ISO enter

- keyboards/helix/rev2/keymaps/five_rows/rules.mk
Change helix:five_rows keymap to use QMK standerd oled driver
> Change helix:five_rows keymap to use QMK standerd oled driver

- keyboards/merge/uma/uma.c
```
Compiling: keyboards/merge/uma/uma.c                                                               [K’:
plicit-function-declaration]
oled_write(get_u8_str(get_current_wpm(), '0'), false);
[K
```
*
> merge/uma - Resolve configurator issues

- keyboards/helix/rev2/keymaps/fraanrosi/rules.mk
Change helix:fraanrosi keymap to use split_common.
@fraanrosi, This PR needs to be tested and approved by you.
The Helix keyboard is currently in the process of changing from its original implementation of split_util to using split_common. (https://github.com/qmk/qmk_firmware/issues/16388)
As a first step, we are switching to split_common for each keymap one by one to make sure that each keymap is working properly.
*  #16388
> Change helix:fraanrosi keymap to use split_common

- keyboards/helix/rev2/keymaps/five_rows_jis/keymap.c
- keyboards/helix/rev2/keymaps/five_rows_jis/rules.mk
* Change helix:five_rows_jis keymap to use split_common
* Makes QMK standerd OLED driver used by the helix:five_rows_jis keymap switchable.
@marksard, This PR needs to be tested and approved by you.
The Helix keyboard is currently in the process of changing from its original implementation of split_util to using split_common. (#16388)
As a first step, we are switching to split_common for each keymap one by one to make sure that each keymap is working properly.
* #16388
> Change helix:five_rows_jis keymap to use split_common

- keyboards/qwertykeys/qk65/hotswap/hotswap.h
- keyboards/qwertykeys/qk65/solder/solder.h
Some files were missing newlines, causing 
```Compiling: keyboards/qwertykeys/qk65/hotswap/hotswap.c                                             In file included from keyboards/qwertykeys/qk65/hotswap/hotswap.c:17:
keyboards/qwertykeys/qk65/hotswap/hotswap.h:21:25: error: backslash-newline at end of file [-Werror]                                                                    
#define LAYOUT_hotswap( \
```
> Fix qwertykeys/qk65

- docs/flashing.md
- platforms/chibios/flash.mk
- util/uf2conv.py
Add :flash target for UF2 bootloaders using the `--deploy` cli flag of the uf2conv.py util, which automatically scans for valid mounted UF2 bootloaders and flashes the UF2 file. Depends on https://github.com/microsoft/uf2/pull/61 to filter out the error messages if the drive could not be found. 
* Part of #14877
> [Core] Add :flash target for UF2 bootloaders

- keyboards/lfkeyboards/lfk78/config.h
- keyboards/lfkeyboards/lfk78/keymaps/via/keymap.c
- keyboards/lfkeyboards/lfk78/keymaps/via/readme.md
- keyboards/lfkeyboards/lfk78/keymaps/via/rules.mk
- keyboards/lfkeyboards/lfk78/lfk78.c
- keyboards/lfkeyboards/lfk78/lfk78.h
Fixed LFK78 firmware to be able to compile in the latest version of QMK. Added VIA support to LFK78.
* Changed Vendor ID to 0x4C46 = LF
* Changed Product ID to 0x3738 = 78
* Added VIA keymap to LFK78
* Changed function name from click to clickingNotes (As click is a qmk variable and throws error when compiled)
> LFK78 VIA support and Updated to compile to the latest QMK

- keyboards/evyd13/wasdat/matrix.c
- keyboards/evyd13/wasdat_code/config.h
- keyboards/evyd13/wasdat_code/matrix.c
- keyboards/evyd13/wasdat_code/rules.mk
A followup to #16217.
This board is similar to the Wasdat, but the column setup is a little different. According to the schematic, D4 is connected to one of the 74HC138's enable pins, and all output pins are connected to a column (whereas on the Wasdat the IC is always enabled, and only 7 of the 8 outputs are connected, with address 0 being set when a non-demux column is selected).
@evyd13 if you still have one of these, would you mind testing it, or pointing someone else who has one here?
*
> Convert Wasdat Code custom matrix to SN74x138 driver

- keyboards/handwired/sick68/config.h
> [Keyboard] Change the default VENDOR_ID to allow VIA support for SICK68

- keyboards/handwired/dactyl_manuform/5x6/keymaps/nabos/config.h
- keyboards/handwired/dactyl_manuform/5x6/keymaps/nabos/keymap.c
Add nabos keymap
Personnal keymap with a gaming mode to have WASD placed ergonomically
> [Keymap] Add nabos keymap to dactyl_manuform (5x6)

- lib/python/qmk/keyboard.py
#16466 
`qmk info -kb gvalchca/spaccboard -l`
*
> `qmk info`: Nicer rendering of big-ass enter

- keyboards/machine_industries/m4_a/config.h
- keyboards/machine_industries/m4_a/info.json
- keyboards/machine_industries/m4_a/keymaps/default/keymap.c
- keyboards/machine_industries/m4_a/m4_a.c
- keyboards/machine_industries/m4_a/m4_a.h
- keyboards/machine_industries/m4_a/readme.md
- keyboards/machine_industries/m4_a/rules.mk
Adds support for Rama Works M4-A keyboard.
*
> [Keyboard] Add Rama Works M4-A

- quantum/dynamic_keymap.c
> Fix missing definition for non-encoder case.

- keyboards/gmmk/pro/iso/keymaps/chofstede/keymap.c
- keyboards/gmmk/pro/iso/keymaps/chofstede/readme.md
New Keymap for GMMK ISO
- Added Print-Screen to FN+POS1
- Added Insert to FN+#
- The LED bars on the left and right side of the keyboard blink red when CAPS Lock is enabled
- All mapped keys light up red when FN is being pressed
> Add new keymap for GMMK with some additional mappings and led indicator for caps lock

- docs/tap_hold.md
When reading the [Tap Hold Configuration Options](https://docs.qmk.fm/#/tap_hold?id=tap-hold-configuration-options), I find it hard to visualize the behaviour of each tap-hold modes.
To help future users better visualize, ASCII diagrams are included for each example sequences.
> [Docs] Include ASCII diagram to explain tap-hold modes

- lib/python/qmk/cli/cd.py
The `cd` subcommand was failing as the current shell's Windows path was
mangled while milc processed it.
Using `subprocess` directly avoids this issue and an extra layer of
subshell.
*
> CLI: Fix 'cd' subcommand on Windows

- quantum/action_util.c
The One Shot documentation says key `OS_ON` turns one-shot keys on and `OS_OFF` turns them off. The actual behavior is flipped: `OS_ON` turns them _**off**_ and `OS_OFF` turns them _**on**_.  This PR fixes this.
This bug was discovered by reddit user [u/Dutchnesss1](https://www.reddit.com/user/Dutchnesss1). I can reproduce it on my keyboards. We were troubleshooting a problem where one-shot keys weren't work on Dutchnesss1's keyboard, and confusingly, `OS_ON` disabled one-shot keys when we thought we were enabling them.
The underlying problem is the logic for functions `oneshot_set()`, `oneshot_enable()`, `oneshot_disabled()`, and `is_oneshot_enabled()` are similarly flipped. The bug is rather obvious once looking at their implementation ([code …
> [Core] Fix flipped logic bug with One Shot `OS_ON` / `OS_OFF` keys

- platforms/chibios/_pin_defs.h
- platforms/pin_defs.h
Wow this stuff is fragile.... 
Dislike the platform specific bodge, and will try and revisit this mess in the future to fix this include order mess.
*
> Redo workaround for pin_def errors on KINETIS

- docs/feature_pointing_device.md
This PR fixes a code sample in the docs for pointing devices.
There was a semicolon missing and I adopted the same style as in the code sample below (two assign statements instead of mangling them into one line).
- [] My change requires a change to the documentation.
> docs: fix code sample

- keyboards/helix/rev2/keymaps/edvorakjp/rules.mk
Changed helix:edvorakjp keymap to use split_common.
@epaew, This PR needs to be tested and approved by you.
The Helix keyboard is currently in the process of changing from its original implementation of split_util to using split_common. (#16388)
As a first step, we are switching to split_common for each keymap one by one to make sure that each keymap is working properly.
* #16388
> Change helix:edvorakjp keymap to use split_common

- docs/isp_flashing_guide.md
Based loosely on the [Cannonkeys docs](https://docs.cannonkeys.com/flashing/), but with a bit more information and "support" for Windows as previously MINGW64 st-flash did not work (some bug involving libusb IIRC).
*
> ISP flashing guide: add instructions for flashing STM32duino bootloader

- quantum/mousekey.c
- quantum/pointing_device.c
- quantum/pointing_device.h
- tmk_core/protocol/report.c
- tmk_core/protocol/report.h
Moves `has_mouse_report_changed` function to report.c, as both pointing device and mousekeys check for changes to the report to determine if to send or not.
> [Core] Move `has_mouse_report_changed` function to `report.c` 

- quantum/action.c
- quantum/action_util.c
- quantum/eeconfig.c
- quantum/eeconfig.h
- quantum/keycode_config.h
#16617  tried to fix the bug, but honestly made it more convoluted, and broke it further.  
This changes the variable name and simplifies the logic, so it's clear and concise. 
* Oneshot toggle and oneshot keys broken.
> Fix oneshot toggle logic

- quantum/keyboard.c
- quantum/keyboard.h
To prevent naming conflicts with external sources, especially needed for the RP2040 port which ran into this problem.
* Part of #14877
> [Core] Rename TICK to TICK_EVENT

- docs/feature_bootmagic.md
It is not immediately obvious how to set the `*_RIGHT` values for a split keyboard. Added an example that will help explain its values better.
> Add split keyboard example for Bootmagic Lite

- keyboards/westm/westm68/config.h
- keyboards/westm/westm68/rev1/config.h
- keyboards/westm/westm68/rev1/rules.mk
- keyboards/westm/westm68/rules.mk
From #16528 seems like `RGBLIGHT` should not be enabled at root keyboard level and is still a WIP...
It being enabled causes compilation errors.
> Fix westm/westm68

- .github/workflows/develop_update.yml
- .github/workflows/feature_branch_update.yml
Needs additional token permissions to trigger any dependent workflow.
*
> Ensure dependent CI workflows run after merge

- tmk_core/protocol/vusb/protocol.c
Noticed when implementing 13733.
Everything else uses `usbSetInterrupt4`, `USB_CFG_EP4_NUMBER`, etc.
> VUSB - Use correct endpoint poll for VIA

- lib/python/qmk/path.py
Fixes an issue where the mode string passed to `qmk.path.FileType` is mistakenly given to the `encoding` argument of the superclass if it is not explicitly named (eg. `qmk.path.FileType('r')`).
*
> qmk.path.FileType: fix argument handling

- lib/python/qmk/info.py
No real point in providing a chunk of the split config, on non split keyboards 
```
qmk info -f json -kb xd84 | grep -A2 split
"split": {
"transport": {
"protocol": "serial"
```
> Ignore transport defaults if SPLIT_KEYBOARD is unset

- keyboards/gmmk/pro/pro.c
Added a keyboard level encoder function as many users have complained about losing encoder functionality when using QMK Configurator.
> Add keyboard level encoder function

- layouts/community/ergodox/osx_whiskey_tango_foxtrot_capslock/keymap.c
- layouts/community/ergodox/osx_whiskey_tango_foxtrot_capslock/rules.mk
The osx_whiskey_tango_foxtrot_capslock layout for ergodox initially handled faking the caps lock keypress because of macOS's delay on caps key presses.  This functionality was previously implemented as an action_get_macro , and since that functionality seems to be deprecated / removed this functionality was lost in the shuffle.  This is an attempt to re-implement the same functionality with a process_record_user instead.  I have tested this on an original OG ergodox (massdrop kit) and seems to work pretty well. 
* Restore caps lock fakery
> updating osx_whiskey_tango_foxtrot_capslock to use process_record_user

- docs/feature_rgb_matrix.md
- drivers/led/issi/is31fl3737.c
I made the same changes to support changing the PWM frequency with the IS31FL3737B and no longer just the IS31FL3733B.
> add the ability to change the pwm frequency for the IS31FL3737B

- docs/cli_commands.md
- lib/python/qmk/c_parse.py
- lib/python/qmk/cli/__init__.py
- lib/python/qmk/cli/via2json.py
- lib/python/qmk/json_encoders.py
- lib/python/qmk/keymap.py
This subcommand can generate a keymap.json from a VIA keymap backup.
Both the layers and the macros are converted, enabling users to easily move away from a
VIA-enabled firmware without writing any code or reimplementing their
keymaps in QMK Configurator.
**Note**: Depends on  #16261
*
> CLI: Add 'via2json' subcommand

- docs/feature_joystick.md
- keyboards/handwired/battleship_gamepad/battleship_gamepad.c
- keyboards/handwired/misterdeck/keymaps/default/keymap.c
- keyboards/handwired/misterdeck/keymaps/nobuttons/keymap.c
- keyboards/handwired/onekey/keymaps/joystick/keymap.c
- keyboards/lime/keymaps/default/keymap.c
- quantum/joystick.c
- quantum/joystick.h
- quantum/process_keycode/process_joystick.c
- quantum/process_keycode/process_joystick.h
- quantum/quantum.h
- Refactored `process_joystick()`; extracted `register_joystick_button()`/`unregister_joystick_button()`
- Added `joystick.h` include in `quantum.h` so that it's implicitly visible at keyboard/keymap-level
*
> Joystick feature updates

- lib/python/qmk/info.py
Fix a bug that could happen for keyboards without any revision directory when the lookup for `info.json` files would go up until the root of the `qmk_firmware` directory.
This could cause issues if the user happen to have `info.json` here or in the `keyboards` directory as those would be included as well.
*
> Fix bug when 'info.json' lookup escapes keyboard dir

- lib/python/qmk/c_parse.py
- lib/python/qmk/cli/lint.py
Macros in `info.json` should either have the "matrix" key with the matrix
data or should should be also present in `<keyboard>.h`
*
> CLI: Lint non-data driven macros in info.json

- platforms/chibios/gpio.h
The ternary operator expects expressions as its arguments, this works for most gpio implementations but not for the RP2040 port as the gpio macros are implemented as statements. Using `writePin` would error on Macro expansion during compilation.  See https://github.com/qmk/qmk_firmware/pull/14877#issuecomment-1075645743
Therefore the ternary operator is replaced with a wrapped if-else statement which does accept simple statements.
* Part of #14877 which throws compilation errors when using `writePin`
> [Core] Refactor writePin to work with statements

- platforms/chibios/eeprom_stm32_defs.h
Added STM32F303xE to `FEE_PAGE_SIZE` and `FEE_MCU_FLASH_SIZE` defines in `platforms/ChibiOS/eeprom_stm32_defs.h`<br/>
QMK currently assumes mcus to be STM32F303xC for `MCU = STM32F303`. In order to compile for STM32F303xE, it was necessary to include a board.h as explained in https://github.com/qmk/qmk_firmware/pull/8179#issuecomment-819868686. However, that solution no longer works so this PR fixes it.
*
> Add emulated eeprom support for STM32F303xE

- lib/python/qmk/cli/generate/rgb_breathe_table.py
- lib/python/qmk/keyboard.py
- setup.cfg
> yapf: disable arithmetic precedence indication

- builddefs/converters.mk
Adds a build-time warning for CTCP/CONVERT_TO_PROTON_C -- stating the new syntax.
> Add warning for CTPC/CONVERT_TO_PROTON_C.

- data/mappings/defaults.json
- data/mappings/info_rules.json
- data/schemas/keyboard.jsonschema
Cherry picked whats ready to go from https://github.com/qmk/qmk_firmware/pull/16598.
This PR aims to help link `development_board` presets to converters.
In a future develop cycle, this will block invalid conversion attempts, such as make xd48pro CTPC=yes.
*
> Add mechanism to limit available converters

- lib/python/qmk/cli/new/keyboard.py
```
$ qmk new-keyboard -kb asdf -u zvecr -n asdf -l tkl_iso
Ψ Generating a new QMK keyboard directory
What Powers Your Project
For more infomation, see:
https://docs.qmk.fm/#/compatible_microcontrollers
MCU? 
1. elite_c
2. promicro
3. proton_c
4. at90usb1286
5. at90usb1287
6. at90usb162
7. at90usb646
...
```
*
> Allow new-keyboard to use development_board presets

- quantum/keyboard.c
The number of matrix scans per second should be counted using a 1000ms interval, not 1001ms which will result in a slightly higher number.
> Fix matrix scan reporting interval

- tmk_core/protocol/chibios/usb_main.c
The size variable was redeclared inside the do while in chibios usb main reading tasks. Therefore the outside variable, that was used in the while check was not assigned the new value. So it was always a do{} while(false) loop and the compiler removed it. I guess the original intention of the author was to read the data, until the size 0 was returned, and all data was read.
> Fixed usb read loops not reading until timeout

- keyboards/keebio/bdn9/keymaps/lickel/readme.md
- keyboards/keebio/sinc/keymaps/lickel/keymap.c
- keyboards/keebio/sinc/keymaps/lickel/readme.md
The intent was for these keys to behave like macOS. 
At the time, my board didn't have backlight LEDs, so I didn't realize my mistake.
When I went to update my readme, I realized I was using a bad date format, so I changed both of my keymaps in the repo to use ISO8601 format.
> Keymap: sinc/lickel: Use backlight keys in Fn Row

- keyboards/kbdfans/kbd67/rev1/config.h
This change properly aligns caps lock with its LED.
Current bug: When caps lock is set to off, the caps lock LED indicator is on. When caps lock is set to on, the caps lock LED indicator is off. This used to be handled by KBDFans who had their own QMK configurator at  http://qmkeyboard.cn/ but it now appears to be offline.
> KBD67 Rev1 Caps Lock LED Fix

- keyboards/crkbd/keymaps/snowe/config.h
- keyboards/crkbd/keymaps/snowe/keymap.c
- users/snowe/ocean_dream.h
- users/snowe/oled_setup.c
- users/snowe/snowe.h
- users/snowe/wrappers.h
* adjust is_master to is_keyboard_master()
* add gaming keymap
* turn on rgb
* turn on split wpm, but it doesn't seem to work...
n/a
> Fix snowe keymap after updates to QMK

- drivers/flash/flash_spi.c
- drivers/flash/flash_spi.h
Integers are 16-bit on AVR. 512*1024 does not fit in 16 bits, which caused a compile error. So let's make sure they are 32-bit.
I also threw in a spelling fix for good luck.
*
> Fix external flash on AVR

- quantum/rgblight/rgblight.c
Limit the maximum repeat times in `rgblight_blink_layer_repeat` because if `times` is too large it will overflow `_times_remaining` when doubled.
> rgblight: Limit maximum repeat times in rgblight_blink_layer_repeat

- docs/tap_hold.md
- quantum/action_tapping.c
- quantum/action_tapping.h
- quantum/pointing_device_drivers.c
- quantum/process_keycode/process_auto_shift.c
- quantum/process_keycode/process_space_cadet.c
- quantum/process_keycode/process_tap_dance.c
The macro gives the right tapping term depending on whether per-key
tapping terms and/or dynamic tapping terms are enabled. Unnecessary
function calls and variable resolution are avoided.
The time when `TAPPING_TERM` was _the_ tapping term is over. Per-key and dynamic tapping terms are possible now. This makes using the correct tapping term tricky and it requires some preprocessor-fu. Let's abstract all of that away in a `GET_TAPPING_TERM` macro modeled after the `get_tapping_term` function. Using this macro instead of `TAPPING_TERM` will produce the optimal and correct code for getting the tapping term.
* #16472
> Add GET_TAPPING_TERM macro to reduce duplicate code

- keyboards/cutie_club/keebcats/denis/config.h
- keyboards/cutie_club/keebcats/dougal/config.h
Hi folks,
We have discovered a bug with xorg where it will [segfault when a USB device with a % in the product name is connected](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1280). This PR removes the % from the KeebCats x Cutie Club PCBs that we have identified as affected.
*
> Fix Xorg segfault with KeebCats PCBs

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix/animations/typing_heatmap_anim.h
This is a simple override to limit heatmap effect to pressed keys. It is a stop gap workaround of incorrect columns and rows lighting for non-rectangle key matrix. (And reformatted both paragraphs in the heatmap section)
> Heatmap incorrect matrix effect workaround

- docs/feature_rgblight.md
- quantum/rgblight/rgblight.c
- quantum/rgblight/rgblight.h
Blinking RGB layers accumulate (as noted in #16824). Add functions to allow previously blinking layers to be stopped so that new layers can be made to blink instead.
> rgblight: Add functions to stop blinking one or all but one layer

- quantum/painter/qp_draw_image.c
Loading and drawing an image with 256 colors on a firmware with 16 colors maximum enabled, leads to memory corruption because the palette is loaded before checking if it this is even possible. This overwrites unrelated memory in https://github.com/qmk/qmk_firmware/blob/develop/quantum/painter/qp_draw_core.c#L124-L141. Without the change the firmware hard-faults at runtime.
*
> [QP] Check BPP capabilities before loading the palette

- docs/feature_led_indicators.md
* Remove incorrect link
* Use proper section headers instead of code function
* Improve description for various callback function
* Add code example for host LED state
> Refine LED indicator documentation

- keyboards/ploopyco/trackball_mini/trackball_mini.c
Only define `PLOOPY_DPI_*` if they are not already defined (ie. via a keymap).
Without this, customizing the DPI options in a `config.h` will cause
redefinition errors.
> Ploopy Trackball Mini: only define DPI options as needed

- quantum/action.c
- Fix state updates of one-shot locked modifiers
Activating additional one-shot locked modifiers removed previously enabled locked modifiers from the state.
`get_oneshot_locked_mods` returned zero when two or more one-shot locked modifiers were enabled and then one was disabled.
- Do not delete one-shot locked modifiers on a one-shot layer toggle
Non-locked one-shot modifiers are not removed so this behavior adds inconsistency.
Also the one-shot locked modifiers state was reset without unregistering any modifiers.
* Fixes #10921
> Fix one-shot locked modifiers

- docs/feature_pointing_device.md
- drivers/sensors/pmw3360.c
- drivers/sensors/pmw3360.h
- quantum/pointing_device_drivers.c
- remove unneeded start/stops during the init phase and do only what the
data sheet says (more or less). This saves about 50 bytes.
- tested on 2 random pmw3360 sensors and a Ploopy mouse
- reorder some functions so we don't need to expose them in the header
- add an index argument, so that the functions can work on different
pins
- this adds about 110 bytes again :/
- provide documentation updates on how to use and merge the reports
> Add support for multiple sensors to pmw3360

- keyboards/helix/rev2/keymaps/yshrsmz/keymap.c
- keyboards/helix/rev2/keymaps/yshrsmz/rules.mk
* Change helix:yshrsmz keymap to use split_common
* Makes QMK standerd OLED driver used by the helix:yshrsmz keymap switchable.
@yshrsmz, This PR needs to be tested and approved by you.
The Helix keyboard is currently in the process of changing from its original implementation of split_util to using split_common. (#16388)
As a first step, we are switching to split_common for each keymap one by one to make sure that each keymap is working properly.
* #16388
> Change helix:yshrsmz keymap to use split_common

- platforms/chibios/drivers/serial.c
- platforms/chibios/drivers/serial_usart.c
- platforms/chibios/platform.mk
- platforms/chibios/synchronization_util.c
- platforms/synchronization_util.h
- quantum/split_common/transactions.c
...on platforms that support it, which is only ChibiOS at this point. Further more the wrong usage of the API would result in lockups on the RP2040 QMK port. With these changes ChibiOS no longer halts with a critical system error when enabling the state check.
The shared memory on the ChibiOS platform can be accessed concurrently on the secondary device. This happens when the serial transaction thread reacts to transactions requests by the main side of the keyboard. This can lead to race conditions and corrupted transactions.
The access to the split shared memory is made exclusive at any given time by guarding it with a mutex.
The previous solution using a critical section didn't really work out because serial functions like send and receive would disable and enable interrupts on their …
> [Core] Use a mutex guard for split shared memory

- quantum/rgb_matrix/animations/digital_rain_anim.h
RGB matrix digital rain animation did not follow the current set hsv value.
Due to this, it also ignored `RGB_MATRIX_MAXIMUM_BRIGHTNESS`, which might cause too much current to be drawn .
This pull request changes the algorithm to adapt to the currently set hsv value by both
* scaling the brightness constants with the value
* adjusting the speed of decay to keep time from full brightness to 0 roughly constant
> Fixes #16705 : digital rain follows val

- keyboards/keebio/iris/readme.md
- keyboards/keebio/iris/rev6a/config.h
Add notes on Iris Rev. 6.x PCBs and firmware.
*
> Add notes on rev6a firmware

- docs/i2c_driver.md
The current documentation for the I2C driver wrongfully uses the word "SPI" to describe a function that clearly is meant to be use for I2C devices.
*
> Fix i2c driver documentation: Incorrect name

- quantum/rgblight/rgblight.c
The change to support repeated blinking (#12237) does not work correctly when there are multiple blinking layers active at the same time.
It is decrementing the number of times remaining for every active layer which will cause it to reach 0 prematurely and ignore some of the layers.
Decrement times remaining only once for each timer event.
> Fix rgblight_blink_layer when multiple layers are active

- quantum/backlight/backlight_avr.c
In attempting to do simple backlight breathing on Atmega32U4, I ran into two problems:
- The backlight was limited to a very low value during breathing. Adjusting brightness manually would briefly flash a higher brightness, then immediately resume the low brightness level. A demonstration of this behavior can be seen here: https://youtube.com/shorts/b1qZkLxvO1U?feature=share
- The backlight would gradually turn on, then off, and then gradually turn on again a little bit before restarting the cycle from off. The expected behavior was for it to not turn back on before restarting a breathing cycle
Investigating the first problem of low backlight limit, it appears that the data pulled from the breathing table was cast to `uint16_t` before being multiplied to `ICRx` (line 415 of …
> Fix AVR backlight breathing: low brightness limit & exceeding breathing table max index

- tmk_core/protocol/chibios/usb_main.c
Some Chibios chips like the SN32F260 have severe RAM limitations. This allows for a smaller footprint if overrided
*
> Chibios USB protocol: allow overriding RAW Capacity

- keyboards/bpiphany/pegasushoof/2013/2013.h
- keyboards/bpiphany/pegasushoof/2013/matrix.c
After a long long time I decided to update my Filco keyboard (w/ Pegasus Hoof 2013) and I found out many keys were not assigned properly or not working at all. I was surprised the "new" matrix, pin assignment and default layout was quite different from what it was supposed to be, compared to the [original bpiphany's files](https://github.com/BathroomEpiphanies/costar_keyboard/blob/master/models/common.h).
* Default layout 
* Matrix
* Pin assignments
> [Keyboard] Fix Pegasus Hoof (2013) layout, matrix and pin assignment

- keyboards/anavi/macropad8/keymaps/vscode/config.h
- keyboards/anavi/macropad8/keymaps/vscode/keymap.c
Creation of a new Keymap for the Anavi/macropad8 for Visual Studio Code development IDE.
This pull request pertains to the creation of a new Keymap for the Anavi/macropad8 for supporting shortcuts for the Visual Studio Code development IDE.
- [Χ] Keymap/layout/userspace (addition or update)
*
> Addition of new keymap for the anavi macropad8 keyboard

- docs/squeezing_avr.md
- platforms/avr/platform.mk
Introduce new AVR specific make variable `AVR_USE_MINIMAL_PRINTF`  which includes AVR's libc minimal printf implementation. It [has less features](https://www.nongnu.org/avr-libc/user-manual/group__avr__stdio.html#gaa3b98c0d17b35642c0f3e4649092b9f1) and thus can shave ~400 bytes. 
Usually we use the xprintf implementation but keyboards that use `s(n)printf` automatically pull in the normal AVR libc implementation, which is ~900 bytes heavy.
**Size impact: -390 Bytes**
```
./util/size_regression.sh -d feature/avr_minimal_printf crkbd/rev1:default
Size:    26564, delta:   -390 -- 03900d6e53 Enable for crkbd (not actually in PR)
Size:    26954, delta:     +0 -- 3eb1f765a1 [Core] Allow usage of AVR minimal printf library
```
*
> [Core] Allow usage of AVRs minimal printf library

- keyboards/idobao/id67/id67.c
- keyboards/idobao/id67/keymaps/vinorodrigues/keymap.c
`ID67_CAPS_LOCK_KEY_INDEX` is never defined anywhere. I assume its correct value is 23...
> Fix id67 RGB Matrix

- quantum/joystick.h
- tmk_core/protocol/usb_descriptor.c
The report descriptor can be simplified here by ~~replacing the individual `Usage` items with `Usage Minimum` and `Usage Maximum` and~~ limiting the number of axes/buttons able to be defined.
Windows refused to recognise the game controller interface, although it was labelled as such in Device Manager, and Wireshark also understood it...
*
> Joystick: Simplify report descriptor and clean up error messages

- keyboards/rgbkb/common/touch_encoder.c
Small fix for Sol 3 users that have a touch bar on their slave side only.
*
> Small fix for setups with only a slave touch bar.

- platforms/avr/platform.c
- quantum/keyboard.c
Removes more platform specific ifdef logic from core.
> Move disable_jtag to platforms

- quantum/rgblight/rgblight.c
Reproduced in deb10 + arm gcc 6.3.1. Error was
```
Compiling: quantum/rgblight/rgblight.c                                                             quantum/rgblight/rgblight.c: In function 'rgblight_sethsv_eeprom_helper':
quantum/rgblight/rgblight.c:563:17: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
uint8_t range = pgm_read_word(&RGBLED_GRADIENT_RANGES[delta / 2]);
^~~~~~~
```
This was due to the wrong progmem api being used, trying to read a u8 with th u16 version.
*
> Remove ARM pgm_read_word workaround in rgblight

- keyboards/wsk/pain27/keymaps/default/keymap.c
This is the same layout, just with keys aligned and separated by rows
for better readability.
> [Keymap] Improve Pain27 default keymap readability

- util/install/fedora.sh
When building qmk on Fedora it fails due to missing include usb.h
Added libusb1-devel package that contains the required header file.
- [x ] My code follows the code style of this project: [C](https://docs.qmk.fm/#/coding_conventions_c), Python
- [x ] I have read the PR Checklist document and have made the appropriate changes.
> Add missing dependency for qmk setup on Fedora

- keyboards/rgbkb/sol3/rev1/rev1.c
Sol3 RGB Keymap is off by one row
> Sol3 fix rgb map

- keyboards/nullbitsco/common/remote_kb.c
- keyboards/nullbitsco/common/remote_kb.h
The baudrate on the remote KB link is slightly too high for the SNAP. The ISR RX interrupt is not completing before kicking again in some cases, causing the data in the RX FIFO to be overwritten. This PR reduces the baudrate and cleans up some debug formatting.
Tested across all the nullbits boards (the only consumers of this feature, AFAIK).
*
> Update RMKB to support SNAP

- keyboards/ferris/keymaps/via/config.h
Add usable tap-hold defaults to some home row mod taps.
> [Keymap] Add usable tap-hold defaults

- shell.nix
This change allows Nix users to override the pinned Niv inputs.
Currently, `shell.nix` imports the Niv-provided inputs directly. However, if users are trying to interact with this repo's shell using some kind of hermetic system, like Flakes, then it would fail, because [Niv reads the `builtins.currentSystem` attribute](https://github.com/qmk/qmk_firmware/blob/caeb213400e7f612598af10354306fd4d3ee0adf/util/nix/sources.nix#L163). 
This refactor lifts pkgs into the inputs, so that the user can provide their own version of nixpkgs if they want. I've tested that nothing changes for normal use, and that the modified shell and the original shell are actually identical.
```
$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ nix-build --dry-run …
```
> Allow overriding Niv's sources in shell.nix

- layouts/default/65_iso_split_bs/default_65_iso_split_bs/keymap.c
Fix the layout macro reference in the `keymap.c` file, which caused this keymap to not be able to be compiled.
> 65_iso_split_bs Community Layout Keymap Bugfix

- quantum/mousekey.c
Kinetic mouse mode is currently broken, as described in https://github.com/qmk/qmk_firmware/issues/12082 and https://github.com/qmk/qmk_firmware/issues/13711.
The PR https://github.com/qmk/qmk_firmware/pull/11766 introduced a set of fixes in early 2021. This PR was closed in favour of ongoing refactoring of QMK's mouse code (see https://github.com/qmk/qmk_firmware/pull/11766#issuecomment-776931052 and https://github.com/qmk/qmk_firmware/issues/12082#issuecomment-790809864).
Since the mentioned comments, it appears nothing has been merged in order to fix kinetic mode, meaning kinetic mode is still broken. This commit adopts the changes from the pull request that was originally supposed to fix the problem, and updates the changes to handle recent changes to the mousekey.c file.
These …
> Fix kinetic mouse mode

- quantum/mousekey.c
This reverts commit 90eef4cd153cdc1b00d973e6abb029828f656294.
I should have tested more. 
Unfortunately, this seems to break at least the mouse scrolling.  It moves one tick, and then stops, meaning you have to repeatedly tap the scroll keys to get actual movement.
> Revert "Fix kinetic mouse mode (#16951)"

- quantum/process_keycode/process_secure.c
- quantum/quantum.c
- quantum/quantum_keycodes.h
- quantum/secure.c
- quantum/secure.h
- tests/secure/config.h
- tests/secure/test.mk
- tests/secure/test_secure.cpp
* Add hook for secure feature, for locking related events
* fix issue with stuck keys when unlocking request is sent
* Since the pending request blocks all keystrokes, this can/will cause keys to get stuck if they were being held when the request function was called.  To prevent this, clear all pressed keys and clear layers to ensure that no keys get stuck
* Better handle unlocking request keystrokes
* Can add a preprocessor for this instead, but found that !pressed causes problems, in general wit
* Issues found when testing out the feature
> Enhancement and fixes of "Secure" feature

- tmk_core/protocol/chibios/usb_driver.c
...when attempting to start a receiving USB transfer. Previously, we would check on the IN endpoint which is the transmitting part of the USB endpoint. This is wrong and lead to two USB transfers being started immediately after each other in case of e.g. RAW HID endpoints:
1. When finishing an OUT transfer the low level USB driver calls the `out_cb` callback, which in turn initiates another OUT transfer by calling `qmkusbDataReceived`.
2. When the raw hid receive channel runs empty inside the raw_hid task, another OUT transfer is started to potentially fill the channel again. This happens by calling `ibnotify`.
Both events occur directly after each other, thus triggering the bug.
* VIA(L) not enumeration on RP2040, part of #14877
> [Core] Check for ongoing transfers on the OUT endpoint

- builddefs/build_keyboard.mk
- data/schemas/keyboard.jsonschema
- lib/python/qmk/c_parse.py
- lib/python/qmk/cli/__init__.py
- lib/python/qmk/cli/generate/keyboard_c.py
- lib/python/qmk/info.py
- lib/python/qmk/json_encoders.py
Building blocks for #15631.
`info.json` providing context on LED location and key binding, will facilitate client UI presentation and `set led <index> to <colour>` style API.
It also allows better validation of the contents, and scope for future tooling.
* inconsistent config for splits
* fake padding for encoders
* config incorrect - not correctly defaulted to NO_LED but led 0?
```
qmk info -f json -kb splitkb/kyria/rev1
{
"manufacturer": "splitkb",
"keyboard_name": "Kyria rev1",
"maintainer": "splitkb.com",
"bootloader": "atmel-dfu",
...
"keyboard_folder": "splitkb/kyria/rev1",
"rgb_matrix": {
"layout": [
{ "flags": 255, "matrix": [2, 1], "x": 91, "y": 40 },
{ "flags": 255, "matrix": [3, 2], "x": 77, "y": 56 },
{ "flags": 255, "matrix": [3, 3], "x": 63, "y": 56 },
{ "flags": 255, …
```
> Data driven `g_led_config`

- platforms/avr/drivers/ws2812.c
`platforms/avr/drivers/ws2812.c` has been changed to use `DDRx_ADDRESS()` and `PORTx_ADDRESS()` instead of `_SFR_IO8()` in #8646.  To use them, `#include <pin_defs.h>` is required.
* create new keyboard
```shell
bash-3.2$ qmk new-keyboard
Ψ Generating a new QMK keyboard directory
Name Your Keyboard Project
For more infomation, see:
https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=naming-your-keyboardproject
Keyboard Name? ws2812_test
..................................
36. WB32F3G71
Please enter your choice:  [12]
Ψ Created a new keyboard called ws2812_test.
Ψ To start working on things, `cd` into keyboards/ws2812_test,
Ψ or open the directory in your preferred text editor.
Ψ And build with qmk compile -kb ws2812_test -km default.
```
* Enable RGBLIGHT.
```shell
bash-3.2$ echo …
```
> Fix platforms/avr/drivers/ws2812.c

- quantum/process_keycode/process_caps_word.c
- tests/caps_word/test_caps_word.cpp
This is a bug fix so that Caps Word is allowed to continue when AltGr symbols are typed, such as accented letters.
Currently, Caps Word (added in PR #16588) turns off whenever a non-shift mod becomes active. This is done to avoid interfering with hotkeys. What I overlooked is that outside the US, the AltGr key is used to type additional symbols. Depending on the language, these AltGr symbols may include symbols used within words like accented letters where it would be desirable to continue Caps Word. Examples for several languages [are described on Wikipedia](https://en.wikipedia.org/wiki/AltGr_key). 
This commit makes an exception to allow Caps Word to continue when AltGr (right Alt) is held.
Fortunately, the fix is simple. I hope it can be merged before 2022-05-26 to make it in the …
> [Core] Bug fix: Continue Caps Word when AltGr (right Alt) is held.

- docs/feature_rgb_matrix.md
> Small Markdown Patch for docs/feature_rgb_matrix.md

- keyboards/xelus/valor/rev2/keymaps/default/keymap.c
- keyboards/xelus/valor/rev2/keymaps/via/keymap.c
Fix TILDE to GRV in default and VIA keymaps
* Fix TILDE to GRV in default and VIA keymaps
> [Fix] Change default keymap tilde to grv

- keyboards/handwired/symmetric70_proto/matrix_debug/readme.md
- keyboards/handwired/symmetric70_proto/matrix_fast/readme.md
Added a little description to reademe.md under `handwired/symmetric70_proto/{matrix_debug|matrix_fast}`.
> [Keyboard] Small update to Symmetric70 keyboard readme

- docs/breaking_changes.md
As it says in the title. Makes sure we don't mess up versioning tags.
> Fixup command sequencing for master/develop.

- docs/feature_split_keyboard.md
- docs/flashing.md
- lib/python/qmk/cli/flash.py
- platforms/chibios/flash.mk
Thought this might be handy until there's a better solution.
*
> Add uf2-split-* make targets.

- shell.nix
- util/nix/poetry.lock
- util/nix/pyproject.toml
- util/nix/sources.json
Update the `nix-shell` environment to use QMK CLI 1.1.0 and newest versions of other required Python modules (including `pillow`).
The update is required to make the `master` branch buildable using `nix-shell` (with the existing version `qmk` fails to do anything due to the missing `pillow` module).
I tried my best to make this work on MacOS (using the `macos-11` environment provided by GitHub for testing, because I don't have an actual Mac available); this required adding a poetry2nix override for `pillow` (just updating `poetry2nix` was not sufficient, although that update was still required to build the `zipp` module).
Cc: @purcell @astridyu @andresilva
-----
This PR does not update the pinned `nixpkgs` version, so that it won't cause a rebuild of the `pkgsCross.avr.buildPackages.gcc8` …
> Nix shell updates

- drivers/led/aw20216.c
As observed in #17250, SPI Mode 0 currently causes issues on 0.17.0 and changing to SPI Mode 3 fixes the issue. This is considered a quick fix, and can be improved upon later by making a configurable mode.
Relevant discord discussion: https://discord.com/channels/440868230475677696/473506116718952450/981047895031705680
```
tzarc — Today at 11:14 PM
kinda smells like the SPI issues I had with the displays on the Djinn
I 'fixed" it my swapping to SPI mode 3
https://github.com/qmk/qmk_firmware/blob/master/drivers/led/aw20216.c#L66
try swapping the 0 to 3
triggerofsol — Today at 11:17 PM
oh, that worked!
tzarc — Today at 11:18 PM
bugger
that means ChibiOS bug
Drashna — Today at 11:19 PM
I'm probably using mode 3 already 😅
Yup
triggerofsol — Today at 11:21 PM
so do i send a pr to change the 0 …
```
> Change AW20216 SPI Mode from 0 to 3, to fix RGB LEDs on GMMK Pro

- docs/feature_rgb_matrix.md
- drivers/led/aw20216.c
Counterpart to #17262 but for `develop` branch instead of `master` branch
This PR makes the SPI Mode configurable for the AW20216. In  `master` branch, the bug was fixed by simply changing the mode from a hardcoded mode 0 to a hardcoded mode 3. Here in `develop` branch, we instead define a new variable `AW_SPI_MODE` which defaults to 3 but can more easily be changed/defined in `config.h` to be any value in 0, 1, 2, 3 without needing to touch the driver code at all.
Relevant Discord discussion: https://discord.com/channels/440868230475677696/473506116718952450/981056233152839690
```
Drashna — Yesterday at 11:47 PM
For making it configurable, look at the divider stuff.  Same idea.
triggerofsol — Today at 12:01 AM
Should I make the "configuration" PR against develop instead of master, then? …
```
> Make SPI Mode configurable for AW20216 and change default mode to 3

- quantum/action.c
```diff
diff --git a/quantum/action.c b/quantum/action.c
index 4e81a5466f..83f6e2a970 100644
--- a/quantum/action.c
+++ b/quantum/action.c
@@ -844,7 +844,7 @@ __attribute__((weak)) void register_code(uint8_t code) {
add_key(KC_CAPS_LOCK);
send_keyboard_report();
-        wait_ms(100);
+        wait_ms(TAP_HOLD_CAPS_DELAY);
del_key(KC_CAPS_LOCK);
send_keyboard_report();
}
```
*
> Use TAP_HOLD_CAPS_DELAY for KC_LOCKING_CAPS_LOCK

- drivers/ps2/ps2.h
- drivers/ps2/ps2_interrupt.c
- drivers/ps2/ps2_mouse.c
- platforms/avr/drivers/ps2/ps2_usart.c
Source PR: #5408
Credits to @tomykaira for doing the actual work!
This PR improves performance of PS/2 mouse in both **interrupt mode** and **USART mode**. On my keyboard, it reduces matrix scan delay from 11ms to 1ms. This makes it possible to use encoder AND trackpoint at the same time without any lags!
Additional changes introduced are:
- Compatibility with USART mode: [platforms/avr/drivers/ps2/ps2_usart.c:76](https://github.com/qmk/qmk_firmware/pull/17111/files#diff-16b236943697980f2e8cb8e73e308a87e3a061e663eda599bec8ee1776c2b087R76)
- Call `ps2_mouse_set_stream_mode` during initialization if stream mode is selected - not sure why that wasn't done already: [drivers/ps2/ps2_mouse.c:56](https://github.com/qmk/qmk_firmware/pull/17111/files#diff-a254e860ff8244ed2cd1622be056ef47b05d65b60d0 …
> Improve PS/2 mouse performance

- keyboards/dztech/dz64rgb/config.h
> fix dz64rgb usb suspend

- docs/feature_advanced_keycodes.md
- [x ] Documentation
* I'm new to QMK, but everywhere else `get_oneshot_mods` looks like it's a function, so I figured it was supposed to be a function in this example too.
> Add trailing parens to `get_oneshot_mods` in feature_advanced_keycodes.md

- quantum/split_common/split_util.c
I ran into this issue earlier on Discord. The current `SPLIT_USB_TIMEOUT_POLL` of `10` limits the maximum value of `SPLIT_USB_TIMEOUT`. Setting `SPLIT_USB_TIMEOUT` above the limit will cause the slave side to be non-responsive.
I guess the check alone would be enough but thought increasing the limit was a smoother experience.
*
> Allow larger SPLIT_USB_TIMEOUT with default SPLIT_USB_TIMEOUT_POLL

- keyboards/fallacy/config.h
- keyboards/handwired/brain/config.h
- keyboards/handwired/d48/config.h
- keyboards/kapcave/paladinpad/config.h
- keyboards/shiro/config.h
Flagged by #17063.
Fix a few legacy references within keyboards.
*
> Fix legacy config options within keyboards

- keyboards/keebio/iris/rev3/rev3.c
- keyboards/lime/lime.c
- keyboards/planck/planck.c
- keyboards/preonic/rev3/rev3.c
- keyboards/preonic/rev3_drop/rev3_drop.c
- keyboards/sofle/sofle.c
- keyboards/splitkb/kyria/rev1/rev1.c
- keyboards/splitkb/kyria/rev2/rev2.c
Adds missing configs for the boards that support both Encoders and Swap Hands features, so that encoder map will compile properly, if enabled.
> Add Encoder Map Swap Hands config for boards that support both features

- builddefs/common_rules.mk
- platforms/arm_atsam/platform.mk
- platforms/avr/platform.mk
- platforms/test/platform.mk
Pushes the used C standard for QMK to GNU11 and C++ standard to GNU17.
|      Platform       |                AVR GCC Version                |                  Embedded ARM GCC Version                  |                     AMD64 GCC Version                      |
| ------------------- | :-------------------------------------------: | :--------------------------------------------------------: | :--------------------------------------------------------: |
| Windows             |                 8.4.0 (MSYS2)                 |                        10.1 (MSYS2)                        |                       11.3.0 (MSYS2)                       |
| MacOS               |               8.4.0 (Homebrew)                |                      8.4.0 (Homebrew)                      | …
> [Core] Update C standard to GNU11, C++ to GNU++14

- keyboards/doppelganger/doppelganger.c
- quantum/split_common/split_util.c
Rather than setting the pin to input each check, it's done once during setup. This is to allow for a delay and ensure a correct reading is taken.
*
> Move SPLIT_HAND_PIN setup to split_pre_init

- docs/how_keyboards_work.md
Like much of our field, systemd has renamed their `master` branch to `main`
While reading through the documentation, I noticed the usage of the term `master` and found that odd. Upon investigation, it turns out that yes, systemd does in fact refer to this as `main` now, so I updated the documentation to reflect this change in the systemd project
Extraordinarily minor documentation change that I found while reading up on what's changed in QMK since last compiling it for my Let's Split that I built back in 2017
* Use of phased out term by SystemD
> docs: reflect systemd's change in language

- keyboards/redox_w/matrix.c
- This fixes the issue of keyboard deadlocking on the first matrix
scan with Redox Wireless keyboards
Resolves #16553. Closes #17071 
This brings back handling time-out in matrix scanning code. Versions `0.15.x` and before handled timeout implicitly, by using a non-blocking `UDR` register read.
The timeout variable is shared across each matrix scan — happy to change it to be individual to each UART byte read instead on a clear recommendation from someone more knowledgeable in UART comms.
The current `HEAD` uses a blocking read, disregarding the timeout code.
From my testing, it looks like it's only ever the first write/receive loop that fails. Debug messages never occured later in the short space I've tested this.
* #16553
> Handle timeout on UART for Redox Wireless receiver-to-keyboard communication.

- keyboards/handwired/onekey/evb_wb32f3g71/config.h
- keyboards/handwired/onekey/evb_wb32f3g71/readme.md
- keyboards/handwired/onekey/evb_wb32f3g71/rules.mk
- keyboards/handwired/onekey/evb_wb32fq95/config.h
- keyboards/handwired/onekey/evb_wb32fq95/readme.md
- keyboards/handwired/onekey/evb_wb32fq95/rules.mk
So Tz CI has something that exercises these boards.
> Add WB32 evaluation board onekey targets.

- keyboards/centromere/matrix.c
- keyboards/dichotomy/matrix.c
- keyboards/glenpickle/chimera_ergo/matrix.c
- keyboards/glenpickle/chimera_ls/matrix.c
- keyboards/glenpickle/chimera_ortho/matrix.c
- keyboards/glenpickle/chimera_ortho_plus/matrix.c
- keyboards/keyhive/honeycomb/matrix.c
- keyboards/mitosis/matrix.c
- keyboards/redox_w/matrix.c
- keyboards/satt/comet46/matrix.c
- keyboards/sirius/uni660/rev1/matrix.c
- keyboards/sirius/uni660/rev2/matrix.c
- keyboards/telophase/matrix.c
- this uses the approach used recently in Redox Wireless to fix the
blocking UART read issue
This follows-up on the fix implemented for `redox_w` keyboard (issue: #16553, PR: #17203), replicating the timeout mechanism to similarly working keyboards.
Includes tiny comment updates for consistency.
The following keyboards could be impacted:
For the last point, a test from owners of keyboards listed in Description section would be great.
> Move more UART-based keyboards to use timeout correctly.

- .github/workflows/lint.yml
- data/mappings/info_config.json
- data/mappings/info_rules.json
- lib/python/qmk/info.py
- lib/python/qmk/tests/test_cli_commands.py
```console
$ qmk lint -kb whale/sk/v3
⚠ whale/sk/v3: SPLIT_TRANSPORT in rules.mk is deprecated and will be removed at a later date
Ψ Lint check passed!
$ qmk lint -kb xiudi/xd84
⚠ xiudi/xd84: NO_ACTION_MACRO in config.h is deprecated and will be removed at a later date
☒ xiudi/xd84: NO_ACTION_FUNCTION in config.h has been removed and is no longer valid
☒ xiudi/xd84: Errors found when generating info.json.
☒ Lint check failed for: xiudi/xd84
````
*
> Add support for linting deprecated and removed functionality 

- keyboards/annepro2/annepro2.c
- keyboards/annepro2/ap2_led.c
- keyboards/annepro2/ap2_led.h
- keyboards/annepro2/protocol.h
- keyboards/annepro2/rgb_driver.c
This change utilizes new AnnePro2-Shine functionality and allows users to utilize the led_mask layer to set e.g. caps lock indicator while using the QMK rgb animations.
I have added functions that utilize new AnnePro2-Shine functionality (added [here](https://github.com/OpenAnnePro/AnnePro2-Shine/commit/a0878587e8220d6688e334332613503c246b911d)) to set led color directly rather than through mask. I have also made it so these functions are used for setting animation of the keyboard in `matrix_scan_kb`.
`ap2_led.c` now contains 2 led arrays, one for base layer and one for mask layer. The base layer is used to handle rgb animations, the mask layer can be used by users in their keymap for indicator lights.
*
> [keyboard] annepro2 Add and use functions to directly control led colors

- lib/python/qmk/cli/lint.py
- lib/python/qmk/info.py
This ensures errors propagate to things like `qmk_error_page`, as well as preventing users from trying to use them on configurator.
> Promote 'layouts require matrix data' to api error

- quantum/via.c
This fix is to scale the rgb_matrix brightness from and to VIA in case the max brightness set in firmware is not 255.
We have had confusion from users in an upcoming keyboard testing round about this.
VIA expects a value from 0 to 255. If the max brigthness in the firmware is set to below 255, any value send from VIA to the keyboard above the max firmware brightness will clip to the max firmware brightness. This results in the VIA slider to feel unresponsive.
As we are already doing something similar for Effect Speed I think this is appropriate.
EDIT:
This is also already done for backlight, so I cleaned it up a bit and did the same for rgblight
*
> Scale brigthness for VIA

- quantum/via.c
Needs defines from rgb engines to work.  Added default/placeholders. 
Ran multibuild to ensure all of the keymaps compile.
> Ensure that rgb+via compiles in all cases

- keyboards/mlego/m48/keymaps/via/keymap.c
Remove terminal keycodes from m48's via keymap since feature is scheduled for removal. 
* Tzarc CI
> [Keyboard] Remove terminal commands from m48

- keyboards/macro3/keymaps/default/keymap.c
- keyboards/macro3/keymaps/default/rules.mk
Add encoder map support to default keymap
> [Keyboard] Add encoder map

- keyboards/basketweave/config.h
Switches the 2 encoder pad pins. On the default keymap, even though the encoder is supposed to trigger volume up when turned clockwise, it turns the volume down when you turn the encoder clockwise. It seems that the pads for the encoder have been defined backwards.
*
> Flip encoder pads on basketweave

- lib/python/qmk/cli/compile.py
- lib/python/qmk/cli/flash.py
If you accidentally forget the `-km` arg, compile/flash currently barf out the following exception,
```
$ qmk compile -c -kb lets_split
☒ sequence item 1: expected str instance, NoneType found
File "/home/zvecr/qmk_firmware/.direnv/python-3.10.4/lib/python3.10/site-packages/milc/milc.py", line 528, in __call__
File "/home/zvecr/qmk_firmware/.direnv/python-3.10.4/lib/python3.10/site-packages/milc/milc.py", line 533, in __call__
File "/home/zvecr/qmk_firmware/lib/python/qmk/decorators.py", line 27, in wrapper
return func(*args, **kwargs)
File "/home/zvecr/qmk_firmware/lib/python/qmk/decorators.py", line 47, in wrapper
return func(*args, **kwargs)
File …
```
> Fix clean arg handling for compile/flash

- builddefs/build_keyboard.mk
Dumps out a set of the largest sized symbols during build, with `TOP_SYMBOLS=yes`.
Tested with AVR, ARM, and RISC-V builds.
Example:
> Dump out the largest symbols in flash and in RAM.

- lib/python/qmk/git.py
The lint check spews an error anytime it encounters a file that's listed in the output of `git_get_ignored_files`. However, the use of `--exclude-standard` in the git shell command ran by the aforementioned python function also ignores files in `.git/info/exclude` and the user's global `.gitignore`.
```
$ man git ls-files
[snip]
-X <file>, --exclude-from=<file>
Read exclude patterns from <file>; 1 per line.
--exclude-per-directory=<file>
Read additional exclude patterns that apply only to the directory and
its subdirectories in <file>.
--exclude-standard
Add the standard Git exclusions: .git/info/exclude, .gitignore in
each directory, and the user’s global exclusion file.
[snip]
```
This has the undesirable consequence of always failing the lint check if the user added some of his …
> Use --exclude-from=.gitignore in place of --exclude-standard

- drivers/led/aw20216.c
- util/update_chibios_mirror.sh
Also rolls back the Mode0=>Mode3 "hack" for the AW20216 driver caused by the SPI bug.
Refer #17262, #17263, @trwnh it would be great if you could verify this fix.
> SPI Bugfix for ChibiOS `21.11.1` => `21.11.2`

- keyboards/keebio/sinc/rev2/rev2.h
Each of the layouts for the keebio sinc include a 1u  space on the left.  This is also the spot on pcb which you use for a 3u spacebar.   In the header file, the key in the layout was left as KC_NO.  This failed to to compile and provide a working key despite the keymapping file matching the layout correctly.
I tested this change with LAYOUT_80_with_macro.
I cross referenced keyboards/keebio/sinc/info.json to ensure the key was there in all layouts, but did not test flashing my keyboard with those layouts.
Reach out if this is incomplete.
* Fixes #16900
> Fix 1U space in Keebio/sinc/rev2 layout macros

- docs/serial_driver.md
- platforms/chibios/drivers/serial_usart.c
- platforms/chibios/drivers/serial_usart.h
This PR build upon https://github.com/qmk/qmk_firmware/pull/16647 while this one is not merged please ignore the commit [Use a mutex for split shared memory synchronization](https://github.com/qmk/qmk_firmware/pull/15907/commits/0829b51c74fbd6839b28fec1c6c0c2027730bc2e) in this PR.
Allow usage of 21.11+ ChibiOS's SIO driver for split keyboards. The cool thing about the SERIAL and SIO driver is that both implement the [`BaseChannel`](https://chibiforge.org/doc/21.11/hal/group___i_o___c_h_a_n_n_e_l.html) interface that provides blocking reading and writing methods that resemble what we already use in the driver. Only some low level aspects like initialization have to be handled differently.
**Every STM32 MCU family that supports `USARTv2` or `USARTv3` like:**
* STM32F0xx (Patches needed to …
> [Core] Allow usage of ChibiOS's SIO driver for split keyboards

- builddefs/common_features.mk
- docs/serial_driver.md
- drivers/serial.h
- platforms/chibios/drivers/serial.c
- platforms/chibios/drivers/serial_protocol.c
- platforms/chibios/drivers/serial_protocol.h
- platforms/chibios/drivers/serial_usart.c
- platforms/chibios/drivers/serial_usart.h
This PR builds upon #15907 and #16647 for review please ignore the commits belonging to these.
Goal of this PR is to re-use the protocol logic of the existing ChibiOS usart driver for other means of transportation. Drivers implementing the protocol just need to provide the following methods to work:
```c
/**
* @brief Clears any intermediate sending or receiving state of the driver to a known good
* state. This happens after errors in the middle of transactions, to start with
* a clean slate.
*/
void serial_transport_driver_clear(void);
/**
* @brief Driver specific initialization on the slave half.
*/
void serial_transport_driver_slave_init(void);
/**
* @brief Driver specific specific initialization on the master half.
*/
void serial_transport_driver_master_init(void);
/**
* @brief …
```
> [Core] Split ChibiOS usart split driver in protocol and hardware driver part

- data/schemas/keyboard.jsonschema
Validating using nodejs AJV
- specify the schema draft
- min -> minimum
- max -> maximum
- minLength -> minItems
- maxLength -> maxItems
*
> Minor schema fixes

- data/schemas/definitions.jsonschema
- data/schemas/keyboard.jsonschema
- data/schemas/keymap.jsonschema
- lib/python/qmk/cli/generate/info_json.py
- lib/python/qmk/json_schema.py
Continues from 14200 (and somewhat 16635).
*
> Additional schema fixes

- docs/feature_mouse_keys.md
- quantum/mousekey.c
- quantum/mousekey.h
Iterating the mouse key kinetic mode fix from #16951 with functional mouse wheel and slightly faster and usable defaults.
* fixes #13711
> [Core] Mouse key kinetic mode fix

- docs/feature_rgb_matrix.md
- drivers/led/issi/is31fl3737.c
This tiny PR adds the ability to define a global current setting for the IS31FL3737 Driver which supports it. Currently it is hardcoded to 0xFF
*
> IS31FL3737 Global Current Setting

- quantum/split_common/split_util.c
I noticed while using transient EEPROM and EE_HANDS that flashing using uf2-split-left, the left side matrix behaved as the right but the LEDs behaved correctly. This appears to be due to the eeconfig handedness being read before it's initialised returning 0.
I've added a check to split_pre_init to ensure eeconfig is enabled and initialise if not.
*
> Ensure eeconfig initialised before reading EEPROM handedness.

- platforms/chibios/drivers/serial.c
- platforms/chibios/drivers/serial_protocol.c
- platforms/synchronization_util.h
This fixes a deadlock bug that sneaked in with #16669. It can only be triggered on a secondary half that is not connected to the main usb connected half, thus not receiving any handshake packets. Which should be a edge-case e.g. when updating one half but still...
**The problematic code that could trigger the deadlock**
```c
static THD_FUNCTION(SlaveThread, arg) {
(void)arg;
chRegSetThreadName("split_protocol_tx_rx");
while (true) {
split_shared_memory_lock(); // <-- (1.) Acquire Mutex in rx/tx thread which runs concurrent with main thread
if (unlikely(!react_to_transaction())) {
serial_transport_driver_clear();
}
split_shared_memory_unlock();
}
}
static inline bool react_to_transaction(void) {
uint8_t transaction_id = 0;
if (unlikely(!serial_transport_receive_blocking(&transaction_id, …
```
> [BUG] Fix deadlocks on disconnected secondary half

- platforms/synchronization_util.h
I forgot to add a `#ifdef` guard for the non-split keyboard case. That resulted in build errors on `develop`.
**AVR non-split**
```
make adelheid:default
QMK Firmware breakpoint_2022_05_28
Making adelheid with keymap default
avr-gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
Size before:
text    data     bss     dec     hex filename
0   16270       0   16270    3f8e adelheid_default.hex
Copying adelheid_default.hex to qmk_firmware folder                                                 [OK]
Checking file size of adelheid_default.hex                                                          [OK]
* The firmware size is fine - …
```
> [Fix] Fix compilation warning for non-split keebs after #17423

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix/animations/typing_heatmap_anim.h
- quantum/rgb_matrix/rgb_matrix.c
Tested on a split keyboard and board with a duplex matrix and it behaves much better, no more trigger incorrect locations. The effect is slightly different visually compared with the old one. I've not tested on AVR, hopefully not too much impact.
There's a define `RGB_MATRIX_TYPING_HEATMAP_SPREAD` that can be changed to increase the area of effect.
* Fixes https://github.com/qmk/qmk_firmware/issues/14041
> Fix RGB heatmap to use XY positions and use correct led limits.

- platforms/avr/drivers/i2c_master.c
`i2c_start()` produces a minimum `time_slice` of 1ms for use as timeout value.
The timer granularity is 1ms, it is entirely possible for `timer_count` to tick up immediately after the last timer read and falsely trigger timeout with a `>= 1` comparison.
*
> Fix AVR I2C master 1ms timeout

- keyboards/tzarc/djinn/djinn.c
- keyboards/tzarc/djinn/keymaps/default/config.h
The old BOM on the Djinn had fuses spec'ed wrongly -- this adds a preprocessor definition `DJINN_SUPPORTS_3A_FUSE` that can be added to config.h in order to enable the full 3A fuses on the newer BOM.
> Fix up Djinn fuse handling.

- keyboards/evyd13/atom47/keymaps/via/rules.mk
VIA firmware was too big for the 32u2 used in one of the Atom47 revisions, this fixes it.
*
> Fix firmware size for via keymap on Atom47

- platforms/avr/drivers/serial.c
If a serial pin isn't defined, and i2c isn't enabled, it gives some esoteric errors. 
This makes sure it errors out in a more obvious way.
* Troubleshooting on discord
- `qmk multibuild -f SPLIT_KEYBOARD=yes` came back with no errors
> [Split] Ensure SOFT_SERIAL_PIN is defined if USE_I2C isn't defined

- lib/python/qmk/keyboard.py
In `lib/python/qmk/keyboard.py`, we can see that `list-keyboards` omits any path containing the word "keymaps":
```py
def list_keyboards():
"""Returns a list of all keyboards.
"""
kb_wildcard = os.path.join(base_path, "**", "rules.mk")
paths = [path for path in glob(kb_wildcard, recursive=True) if 'keymaps' not in path]
```
However, the [keyboard naming guidelines](https://docs.qmk.fm/#/hardware_keyboard_guidelines?id=naming-your-keyboardproject) do not mention that "keymaps" is somehow a reserved keyword or something.
```sh
~/qmk_firmware/keyboards on develop *3 ⨤6                                                                                                                                                             
❯ mkdir agogo
mkdir: created directory 'agogo' …
```
> Don't omit keyboards whose name contains "keymaps" in `qmk list-keyboards`

- docs/feature_pointing_device.md
- drivers/sensors/cirque_pinnacle.c
- drivers/sensors/cirque_pinnacle.h
- drivers/sensors/cirque_pinnacle_i2c.c
- drivers/sensors/cirque_pinnacle_spi.c
- quantum/pointing_device_drivers.c
* read Software Data Ready bit before actually reading data to avoid useless work
* throttle data feed to 10ms by default, which is the fastest that Pinnacle supports
* set RESET for Pinnacle on QMK pointing device driver init
* first step towards relative mode (only data parsing for now)
* cleanup unused register values when in absolute mode
* added code comments and bit definitions for all registers and config options
> improvements for Cirque Pinnacle trackpads

- quantum/pointing_device.c
This PR reduces user confusion when using `POINTING_DEVICE_{LEFT,RIGHT,COMBINED}` while not having `SPLIT_POINTING_ENABLE` defined as well. Previously it would just silently fail and cause the other half to crash/not connect.
In the same spirit as #17466.
* 
- `qmk multibuild -f SPLIT_KEYBOARD=yes` came back with no errors
> [Split] pointing transport check

- quantum/mousekey.c
- quantum/mousekey.h
I missed the mousekeys 3 speed define, and didn't put the function where it could be properly referenced. 
Fixed, and placed prototype in header to simplify. 
Confirmed compilng on all modes (3 speed, kinetic, constant and combined
* Tzarc CI
> [Bug] Fix 3 speed mousekey mode

- quantum/rgb_matrix/animations/typing_heatmap_anim.h
As pointed out in PR #17184 I missed that a matrix position could be set to NO_LED. It now checks and skips any processing if the pressed or target position has NO_LED.
> RGB heatmap skip NO_LED

- docs/feature_split_keyboard.md
This sentence would've saved me about four hours of frustration with my hand-wired split!
Hopefully it helps someone else.
Described the requirements for defining split matrices in more detail, noted that left and right hands must have equal numbers of rows, and that unneeded spaces in the pin definitions must be padded with `NO_PIN`.
> Update feature_split_keyboard.md to add extra detail about left and right matrices.

- lib/python/qmk/cli/__init__.py
Currently if you run `make` when python modules are missing, it will block indefinitely. 
This is due the "install modules?" being piped to `/dev/null`,  ctrl+c produces the following:
```
^CTraceback (most recent call last):
File "/home/zvecr/qmk_firmware/.direnv/python-3.10.5/bin/qmk", line 8, in <module>
sys.exit(main())
File "/home/zvecr/qmk_firmware/.direnv/python-3.10.5/lib/python3.10/site-packages/qmk_cli/script_qmk.py", line 76, in main
import qmk.cli  # noqa
File "/home/zvecr/qmk_firmware/lib/python/qmk/cli/__init__.py", line 213, in <module>
if yesno('Would you like to install the required Python modules?'):
File "/home/zvecr/qmk_firmware/.direnv/python-3.10.5/lib/python3.10/site-packages/milc/questions.py", line 46, in yesno
answer = input(format_ansi(prompt % args)) …
```
> Allow module check to error out when piped to /dev/null

- keyboards/annepro2/c15/config.h
- keyboards/annepro2/c15/rules.mk
- keyboards/annepro2/c18/config.h
- keyboards/annepro2/c18/rules.mk
- keyboards/annepro2/halconf.h
- keyboards/annepro2/mcuconf.h
Enable WL EEPROM driver support for both variant of the AnnePro2(C15/C18) 
Tested only with the C18 variant but the C!5 uses the same NOR Flash with the exception of a different pin for the `EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN`
Nonetheless both variants compile:
C15 default keymap:
```
Ψ Compiling keymap with make --jobs=1 annepro2/c15:default
QMK Firmware 0.17.2
Making annepro2/c15 with keymap default
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
Size before:
text    data     bss     dec     hex filename
0   40476       0   40476    9e1c …
```
> (develop)AP2: Enable support for WL EEPROM Driver

- keyboards/keychron/q2/config.h
- keyboards/keychron/q2/rev_0110/rules.mk
- keyboards/keychron/q2/rev_0111/rules.mk
- keyboards/keychron/q2/rev_0112/rules.mk
- keyboards/keychron/q2/rev_0113/rules.mk
Enable WL EEPROM driver support for all the Keychron Q2 variants.
This PR removes the support for the (probably unused) I2c EEPROM but given that the _famous playground_ branch doesn't have support for I2C EEPROM, I can make a safe assumption that there's no user with a board with an I2C EEPROM
All variants compile successfully (Test builds using the VIA keymap):
rev_0110:
```
Ψ Compiling keymap with make --jobs=1 keychron/q2/rev_0110:via
QMK Firmware 0.17.2
Making keychron/q2/rev_0110 with keymap via
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
Size …
```
> (develop)Keychron Q2: Enable support for WL EEPROM Driver

- platforms/chibios/vendors/RP/stage2_bootloaders.c
> [style] rp2040 stage2 formatting

- quantum/painter/qp_draw_core.c
RP2040 was throwing exceptions when these buffers are placed at an odd-numbered memory address.
Forces 4-byte alignment.
> [QP] Explicit buffer alignment.

- keyboards/kb_elmo/sesame/config.h
This is a small workaround for https://github.com/qmk/qmk_firmware/issues/11389. While I don't love it (as this ultimately just works around the root cause), the original PR that caused this bug seems to be a fix for RGB (https://github.com/qmk/qmk_firmware/pull/10491), which this board does not have. ~~It also seems that some other keyboards (namely `massdrop/alt` and `massdrop/ctrl`) seem to have done similar, citing "matrix delay", which I can only assume is this same issue.~~
cc: @kb-elmo 
* I don't know if I'd call it "fixed", but https://github.com/qmk/qmk_firmware/issues/11389 is certainly relevant
> Add workaround to allow Sesame to work without atomic interactions

- quantum/led.c
- quantum/led.h
This PR is in part a question: would the proposed change make sense? It extends #11552 and  #11595.
This introduces two new functions that mimic
```c
uint32_t last_input_activity_time(void);    // Timestamp of the last matrix or encoder activity
uint32_t last_input_activity_elapsed(void); // Number of milliseconds since the last matrix or encoder activity
```
from `keyboard.h`.
Keyboard activity can come from inside (key and/or encoder activity), or from outside. Outside activity happens in the form of USB 'set' reports that can change the LED state.
* Some keyboards use a screen to show the LED state. If such keyboards have a need to implement custom screen timeout logic (e.g. when they show an animation that breaks the normal timeout logic), it would be real easy if they could just do: …
> Expose the time of the last change to the LED state

- docs/cli_tab_complete.md
[argcomplete](https://github.com/kislyuk/argcomplete) requires `bashcompinit` to be loaded. Without this, sourcing the tab completion script returns `(eval):46: command not found: complete` on shell startup and does not work.
> Add Zsh note for tab complete

- keyboards/ploopyco/trackball_nano/keymaps/lkbm/keymap.c
- keyboards/ploopyco/trackball_nano/keymaps/lkbm/readme.md
- keyboards/ploopyco/trackball_nano/keymaps/lkbm/rules.mk
- keyboards/ploopyco/trackball_nano/trackball_nano.c
- keyboards/ploopyco/trackball_nano/trackball_nano.h
The keymap that takes commands as LED-Key BitMasks.
Based on [maddie](https://github.com/qmk/qmk_firmware/tree/master/keyboards/ploopyco/trackball_nano/keymaps/maddie) (by @hexadecatrienoic), this keymap lets you send a 2-bit command by having a macro on your keyboard tap `KC_NUM_LOCK` and `KC_CAPS_LOCK` on and off within a very short window (25ms by default) to represent bits 1 and 2 respectively.  The keymap uses this to allow toggling between sending mouse-movement events and scrolling events; cycling DPI presets, and resetting to the bootloader, so you can reflash without having to unscrew your Ploopy Nano.
This required adding a function to the keyboard's `.c`/`.h` files to allow cycling the DPI presets, which were already defined there.
> Add lkbm keymap

- quantum/process_keycode/process_leader.c
Fix keys being discarded after using the leader key
Fixes a bug that causes the sixth keycode typed after activating the leader function to be discarded
N/A
> Fix keys being discarded after using the leader key

- docs/keycodes.md
- docs/keycodes_magic.md
- quantum/command.c
- quantum/keycode_config.c
- quantum/keycode_config.h
- quantum/process_keycode/process_magic.c
- quantum/quantum_keycodes.h
Add "Swap Escape and CapsLock" and "Unswap ..." capability dynamically via magic key.
This is just a proof-of-concept patch to swap Escape and Caps
* Adding flag in between existing bit field causes bug (BS \ swap)
* Adding quantum code in more proper comment requires to update comment.
It worked on my QMK keyboard (handwired 4x14 ortholinear compact.) When a host PC with GNOME tweak sets to swap Escape and Caps, I had to do this to obtain in sane key location on my QMK keyboard while keeping that note PC usable with vim.
If you like this idea, I will add needed things for general consumption.
* NEW FEATURE added to swap Escape and Caps.  (Different machine, different OS config, so it will be nice it is dynamically changed.
* GPL2+ /GPL3+
* Documentation is not updated yet
* Aesthetically …
> PoC: Swap Escape and Caps

- quantum/encoder.c
Modified encoder_update to be more permissive about lost pulses when returning to the ENCODER_DEFAULT_POS  to detect if a tick has happened. E.g. on resolution 4 rotary encoder all ticks with only 1, 2 or 3 detected pulses have been discarded in the original code, but when the rotary encoder returns ENCODER_DEFAULT_POS  and pulses are present, we can be sure, that a tick has happened. This modification catches all these lost ticks with only 1,2 or 3 pulses, which results in a more reliable performance of the rotary encoder.
Modified the encoder_update method to emit ticks even when not all pulses have been detected but direction is clear and the rotary encoder returned to its ENCODER_DEFAULT_POS.
*
> Improve ENCODER_DEFAULT_POS to recognize lost ticks

- docs/newbs_flashing.md
On Archlinux, the newbs flashing guide doesn't work as the required udev rules for non-root flashing are not applied. qmk doctor informs the user about this, so it should be mentioned for newbs.
*
> Add note about qmk doctor in newbs_flashing.md

- docs/feature_rgb_matrix.md
- quantum/process_keycode/process_rgb.c
Adds an `#ifdef` statement that slightly alters the `process_rgb()` function allowing for a more responsive feeling RGB subsystem
This adds an `#ifdef` statement that lets the user apply changes to the currect RGB effect on key press as opposed to key release
This is off by default so that the boards the feature was initially changed for don't break again
the change is enabled by `#define RGB_TRIGGER_ON_KEYDOWN` being placed in either user or keyboard level config.c
None that I'm aware of
> Allow for RGB actions to take place on Keydown instead of Keyup

- keyboards/ktec/ergodone/keymaps/vega/keymap.c
* Added the ability to abuse superscript and full width unicode characters to my keymap
> Yes, it's in my master. I know how to use git, but this change is small enough I just don't care.
> [keymap] Add tiny text, full width characters to Ergodone->Vega

- keyboards/annepro2/ap2_led.c
- keyboards/annepro2/ap2_led.h
- keyboards/annepro2/keymaps/default-full-caps/keymap.c
- keyboards/annepro2/keymaps/default-layer-indicators/keymap.c
- keyboards/annepro2/protocol.h
This change utilizes new AnnePro2-Shine functionality and allows users to set sticky keys, which shine even after led backlight is turned off, this is useful e.g. for caps lock indicator.
I have added functions that utilize new AnnePro2-Shine functionality (added [here](https://github.com/OpenAnnePro/AnnePro2-Shine/commit/058af8537df266d8c539fdb10ae320f74c195e01)) to set sticky keys that remain shining even after backlight is turned off.
I have also edited the default-layer-indicator keymap to utilize the sticky keys function. (I've also updated default-full-caps as I've forgotten to do so in the last merge request)
*
> [keyboard] annepro2 Add support for sticky keys

- docs/newbs_getting_started.md
- util/install/msys2.sh
- `python-qmk` package has been added to the MSYS2 repo; updated install script and docs to use it
- Removed requirements.txt line as those dependencies will now be handled by `python-qmk`. It might cause conflicts anyway as it still references qmk-dotty-dict which is no longer needed on MSYS2
- Removed `unzip` as I couldn't figure out where it was used - possibly left over from the precompiled AVR/ARM toolchains?
- Added hid-bootloader-cli, mdloader and wb32-dfu-updater for parity with Toolbox
*
> MSYS2 install: use MinGW python-qmk package

- builddefs/build_keyboard.mk
- quantum/keymap_introspection.c
- users/manna-harbour_miryoku/post_rules.mk
- users/manna-harbour_miryoku/rules.mk
Some weird keymap generation going on with the miryoku keymaps -- they weren't _actually_ part of the normal `keymap.c` file, but rather specified elsewhere.
This adds the ability to specify a different file to include into the introspection code.
> Allow for `keymaps` array to be implemented in a file other than `$(KEYMAP_C)`

- drivers/eeprom/eeprom_spi.c
- platforms/chibios/drivers/spi_master.c
Something weird going on with SPI in the sense that the first use would seemingly fail after init, but only on RP2040.
Under normal circumstances, the first read would be EEPROM when using SPI EEPROM, specifically the magic... which would then trigger an EEPROM reset as the data returned is zero'd out on SPI failure.
This PR changes the sequencing:
* On `spi_init` it stops the SPI peripheral as a final action, 
* SPI EEPROM now restarts the SPI peripheral each time the status register is read
* SPI EEPROM driver is now slightly more defensive w.r.t. executing `spi_stop()` on failure -- the previous assumption was that `spi_start()` failing did not necessitate a subsequent `spi_stop()` -- this now explicitly invokes the stop upon all failures.
> Fixup SPI init procedure, SPI EEPROM sequencing

- docs/custom_matrix.md
- docs/ja/custom_matrix.md
- quantum/debounce.h
- quantum/debounce/asym_eager_defer_pk.c
- quantum/debounce/none.c
- quantum/debounce/sym_defer_g.c
- quantum/debounce/sym_defer_pk.c
- quantum/debounce/sym_defer_pr.c
- quantum/debounce/sym_eager_pk.c
- quantum/debounce/sym_eager_pr.c
- quantum/debounce/tests/debounce_test_common.cpp
- quantum/matrix.c
- quantum/matrix_common.c
In preparation of optimizing the `matrix_task()` to not do the matrix comparison twice but instead use the already known matrix state.
* Continues work of #15292
> [Core] Make debounce algorithms signal matrix changes

- keyboards/cannonkeys/satisfaction75/satisfaction_oled.c
- keyboards/handwired/tractyl_manuform/tractyl_manuform.c
- keyboards/rocketboard_16/keymaps/default/keymap.c
- keyboards/rocketboard_16/keymaps/via/keymap.c
- keyboards/tzarc/djinn/graphics/theme_djinn_default.c
- quantum/command.c
- quantum/logging/print.h
* Add missing '(' to `print_bin_reverse32` declaration
* Fix insufficient character buffers on satisfaction75
* Remove `\0` character in format string and use corrected offset math
instead on rocketboard 16
* Replace `snprintf_` with `snprintf` for djinn
* Explicitly ignore format checks for tracktyl manuform that uses `%b`
specifier
* Print properly escaped version string in command.c, as `PRODUCT` or
other defines can contain constructs like 'Vendor keyboard 66%' which
will be interpreted as a format specifier
* Build errors after #16163
> [Fix] printf update aftermath

- lib/python/qmk/c_parse.py
- lib/python/qmk/cli/generate/config_h.py
* Ignore led config that contains preprocessor
* Generate `ENCODER_RESOLUTION` when all values are same value
* avoids generating `ENCODER_RESOLUTIONS` which _might_ not match `len(ENCODERS_PAD_A)`
* this is due to preprocessor use around encoders - last value wins
#17460 will continue efforts to gracefully handle preprocessor in `config.h` files 
*
> Fix rgbkb/sol/rev2 build issues

- lib/python/qmk/info.py
Noticed it wasn't displaying *_RIGHT pins when only one set was defined in config.h using `qmk info`. There doesn't seem to be a requirement for specifying both right cols and right rows in info.json either.
*
> Allow only col or row pins for *_right extraction.

- lib/python/qmk/cli/generate/config_h.py
- lib/python/qmk/info.py
Fixes for:
* case where resolution is not specified at all
* should allow where keymaps currently specify value without undef
Might get there eventually....:cry: 
*
> More DD encoder fixes

- platforms/chibios/drivers/vendor/RP/RP2040/serial_vendor.c
...by disabling USB IRQs during sending as those tend to occur during the timing critical sending phase. This hack notably reduces the amount of spurious failed transactions. Also the PIO IRQ now gets the highest priority over all other IRQs.
* Spurious failed transactions and disconnects
> [Core] Stabilize Half-duplex RP2040 PIO split comms

- keyboards/handwired/onekey/elite_c/config.h
- keyboards/handwired/onekey/keymaps/chibios_waiting_test/config.h
- keyboards/handwired/onekey/keymaps/chibios_waiting_test/keymap.c
- keyboards/handwired/onekey/promicro/config.h
- keyboards/handwired/onekey/rp2040/config.h
- keyboards/handwired/onekey/teensy_2/config.h
- keyboards/handwired/onekey/teensy_2pp/config.h
- keyboards/planck/rev6_drop/matrix.c
- keyboards/preonic/rev3_drop/matrix.c
- platforms/chibios/_wait.h
- platforms/chibios/bootloaders/rp2040.c
- platforms/chibios/chibios_config.h
- platforms/chibios/drivers/serial.c
- platforms/chibios/drivers/vendor/RP/RP2040/serial_vendor.c
Due to context switching overhead waiting a very short amount of time on a sleeping thread is often not accurate and in fact not usable for timing critical usage i.e. in a driver. Thus we use polled waiting for ranges in the us range on platforms that support it instead. The fallback is the thread sleeping mechanism.
This includes:
* ARM platforms with CYCCNT register (ARMv7, ARMv8) this is incremented at CPU clock frequency
* GD32VF103 RISC-V port with CSR_MCYCLE register this is incremented at CPU clock frequency
* RP2040 ARMv6 port which uses the integrated timer peripheral which is incremented with a fixed 1MHz frequency
Waiting values are 0, 1, 5, 10, 25, 50, 100, 150, 200, 500 and 1000 microseconds with 10us spacing. Pink is busy waiting, green is sleeping by yielding the thread. …
> [Core] Use polled waiting on ChibiOS platforms that support it

- quantum/dynamic_keymap.c
When playing back the VIA macro feature for UI manipulation, the UI may miss keystrokes because the keys are sent too fast.
This problem can be solved by adding a wait time for each key transmission.
Example.
```
config.h
#define VIA_MACRO_DELAY 10
```
to delay 10ms each key transmission in VIA macros.
*
> Added Delay time to sending each Keys for VIA Macros function feature

- keyboards/nightly_boards/paraluman/paraluman.h
```
keyboards/nightly_boards/paraluman/paraluman.h:55:9: error: excess elements in array initializer [-Werror]
55 |         { KC_NO,  KC_NO } \
|         ^
keyboards/nightly_boards/paraluman/keymaps/tsangan/keymap.c:20:11: note: in expansion of macro 'LAYOUT_60_ansi_split_bs_rshift_tsangan'
20 |     [0] = LAYOUT_60_ansi_split_bs_rshift_tsangan(
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keyboards/nightly_boards/paraluman/paraluman.h:55:9: note: (near initialization for 'keymaps[0]')
55 |         { KC_NO,  KC_NO } \
```
*
> Fix layout macro for nightly_boards/paraluman

- platforms/chibios/_wait.h
...by including `chibios_config.h` directly. Otherwise drivers that don't include `quantum.h` directly will error out on `REALTIME_COUNTER_CLOCK` beeing undefined.
* e.g. the cirque trackpad driver only includes `wait.h`
> [Fix] Make ChibiOS `_wait.h` independent of `quantum.h`

- builddefs/common_features.mk
- docs/feature_pointing_device.md
- drivers/sensors/cirque_pinnacle.c
- drivers/sensors/cirque_pinnacle.h
- drivers/sensors/cirque_pinnacle_gestures.c
- drivers/sensors/cirque_pinnacle_gestures.h
- drivers/sensors/cirque_pinnacle_regdefs.h
- quantum/pointing_device.h
- quantum/pointing_device_drivers.c
- quantum/pointing_device_gestures.c
- quantum/pointing_device_gestures.h
Adding gestures such as circular scroll and inertial cursor, along with some general QoL changes
- Circular scroll gesture - Disabled by default. Preloaded configuration detects touches originating in outer ring, after validation to differentiate between swipe from edge vs. scroll gesture, the trackpad turns into a scroll knob until finger lift.
- Inertial cursor - Disabled by default. If enabled, cursor will continue moving after a flick gesture and slows down by kinetic friction. Similar to trackball mode on Steam Controller.
- Add function to disable trackpad tap gesture.
- Recalibrate baseline after setting ADC attenuation.
- Set CPI according to trackpad diameter.
- Control cursor smoothing.
*
> Cirque trackpad features: circular scroll, inertial cursor

- quantum/led_matrix/led_matrix.c
- quantum/led_matrix/led_matrix.h
- quantum/rgb_matrix/rgb_matrix.c
- quantum/rgb_matrix/rgb_matrix.h
LED/RGB Matrix config was updated so all of it is in EEPROM, including flags.  However, the flag functions were not updated to properly write to eeprom. 
This ensures that it does, and that adds a "noeeprom" version, as well. 
Wasn't sure if to target develop or master here.  Based on master, targets develop. Should be able to be switched without issue, if needed.
> Update LED/RGB Matrix flag function behavior

- drivers/sensors/cirque_pinnacle_gestures.c
Compliation of cirque guestures errors out on wait_ms(x).  Adds include for wait.h to fix.
* reported on discord by freznel
> Fix compilation issue with Cirque Guestures file

- platforms/chibios/drivers/spi_master.c
- platforms/chibios/drivers/wear_leveling/wear_leveling_efl.c
EFL and SPI post-bootloader startup bugs, detected through assertions.
Under normal circumstances program code is mapped to `0x00000000` as well as `0x08000000`.
Post-bootloader, only the latter address is correct, so EFL is swapped to using the other location.
Also noted after bootloader is that the flash is already unlocked -- re-unlocking causes a fault and necessitates a restart.
Added explicit invocation of `backing_store_lock()` during `backing_store_init()` to force it to be in the correct state.
Invoking it even when locked is fine.
Also noted with debugging enabled that `spiUnselect()` requires the peripheral to be in the stopped state - with assertions disabled this is ignored, but is obviously "wrong" as far as ChibiOS is concerned. Have removed the call.
> Post-bootloader EFL/SPI fixes.

- quantum/rgb_matrix/animations/raindrops_anim.h
* Ensure `RGB_MATRIX_USE_LIMITS` is called on every iteration
* Use the smaller `random8()` function
* Fixes #17589
> [Core] Fix LED limit loop

- quantum/rgb_matrix/animations/pixel_rain_anim.h
Add `RGB_MATRIX_USE_LIMITS` to avoid breaking `rgb_matrix_indicators_advanced_*()`
* Fixes #17589
> Add LED limits call

- keyboards/doio/kb16/info.json
[title]
cc @HorrorTroll (keyboard maintainer)
> KB16-01: correct QMK Configurator key sequence

- keyboards/chocofly/chocofly.c
- keyboards/chocofly/chocofly.h
- keyboards/chocofly/config.h
- keyboards/chocofly/readme.md
- keyboards/chocofly/v1/config.h
- keyboards/chocofly/v1/keymaps/default/keymap.c
- keyboards/chocofly/v1/keymaps/winder/keymap.c
- keyboards/chocofly/v1/rules.mk
- keyboards/chocofly/v1/v1.c
- keyboards/chocofly/v1/v1.h
Add support for the open source chocofly keyboard.
> [Keyboard] Add Chocofly v1

- keyboards/keebio/iris/keymaps/emp/config.h
- keyboards/keebio/iris/keymaps/emp/keymap.c
My personal layout for the keebio/iris. Really simple, only two layers, have been using it for work for several years.
Added keymap.c and config.h to keyboards/keebio/iris/keymaps/emp
* 
- [nearly] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
> Added new keymap for keebio/iris

- docs/feature_pointing_device.md
- drivers/sensors/pmw33xx_common.c
- drivers/sensors/pmw33xx_common.h
...which is what the datasheet says.
*
> [Fix] Use correct angle tune range of +/-30 on PMW33XX

- .gitignore
Just a suggestion that we add this, since git merges seem to create these by default on my machine regardless of the mergetool I use. I figure we might as well just add this ignore line to master.
> Add .orig to .gitignore

- docs/feature_pointing_device.md
- drivers/sensors/pmw33xx_common.c
- drivers/sensors/pmw33xx_common.h
...partially reverts 580bcff4f65a3a9ee301de0fd036de7b610c7ee2 as the datasheet doesn't claim that the angle tuning as limited to +/- 30 degrees.
*
> [Core] Use correct angle tune range of +/-127 on PMW33XX

- shell.nix
The `poetry` package from the used Nixpkgs snapshot is no longer buildable when using the official binary releases of Nix >= 2.10.0 on `x86_64-darwin` due to a regex compatibility issue (https://github.com/NixOS/nix/issues/4758). The failure looks like:
```
error: invalid regular expression '^.*?(egg|tar|tar.bz2|tar.gz|tar.lz|tar.lzma|tar.xz|tbz|tgz|tlz|txz|whl|zip)'
at /nix/store/gm4rp1786ligd81v2qz420nkrwy0r50k-nixpkgs-src/pkgs/development/tools/poetry2nix/poetry2nix/mk-poetry-dep.nix:42:42:
41|           matchesVersion = fname: builtins.match ("^.*" + builtins.replaceStrings [ "." ] [ "\\." ] version + ".*$") fname != null;
42|           hasSupportedExtension = fname: builtins.match supportedRegex fname != null;
|                                          ^
43|           isCompatibleEgg …
```
> shell.nix: Fix compatibility with Nix >= 2.10.0 on `x86_64-darwin`

- lib/fnv/fnv.h
Fix AVR compilation of the FNV library.
> Fix AVR compilation of FNV by using standard integer typenames.

- builddefs/common_features.mk
- docs/feature_pointing_device.md
- drivers/sensors/paw3204.c
- drivers/sensors/paw3204.h
- quantum/pointing_device.h
- quantum/pointing_device_drivers.c
Adds support for the PAW3204 low powered optical sensor.
This is basic support, as the device supports multiple power modes and more, but aren't actually implemented here.
Uses bitbanged communication
> Add support for PAW3204 Optical Sensor

- docs/config_options.md
- docs/ja/config_options.md
This matches the value found in the [documentation](https://github.com/qmk/qmk_firmware/blob/74bec84740a2cc06e4409d28886fafb6afad1ef6/docs/config_options.md).
* #17316
> Fix docs regarding `USB_SUSPEND_WAKEUP_DELAY`

- platforms/chibios/boards/QMK_PM2040/configs/config.h
Refactor #17578 to use Pro Micro pinout instead. This will allow wider converter support for RP2040 boards such as Blok that uses different GPIO pins for SDA and SCL.
> Use Pro Micro SDA/SCL pinout for PM2040

- quantum/keymap_extras/keymap_turkish_f.h
quantum/keymap_extras/keymap_turkish_f.h won't compile without this fix.
the one character change is really self explanatory
* 
- [X ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ X] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
> fix syntax error in header file

- keyboards/mechlovin/zed60/config.h
- keyboards/mechlovin/zed60/readme.md
Change PID and name on readme.md to match with the actual name of the PCB, which is Zed60. Many apologies as I designated the incorrect name before. 
*
> change PID from 0x0601 (kay60) to 0x0602 (zed60)

- quantum/via.c
- quantum/via.h
As per https://github.com/the-via/app/issues/26 this change adds VIA support for the encoder map functionality that is already in QMK.
The current version of VIA (i.e. what is live now at https://usevia.app/#/) now supports this minor change to the protocol, to get and set the encoder map.
This change has no impact on existing firmware and VIA functionality. VIA works as usual for firmware built before this change, and these new commands will only be called by VIA if the keyboard definition includes the encoders and the firmware reports the correct protocol version. This allows keyboard maintainers to update at their discretion.
- Enable encoder maps as per QMK
- Add `ENCODER_ENABLE = yes` to rules.mk
- Add `ENCODER_MAP_ENABLE = yes` to keymaps/via/rules.mk
- Add an encoder map to …
> VIA Encoder Map Support

- data/mappings/defaults.json
- data/schemas/keyboard.jsonschema
- docs/feature_converters.md
- platforms/chibios/converters/promicro_to_blok/_pin_defs.h
- platforms/chibios/converters/promicro_to_blok/converter.mk
Add Promicro to [Blok](https://peg.software/docs/blok) RP2040 converter that uses QMK_PM2040 board.
> Add Blok RP2040 converter

- quantum/keyboard.c
If both pointing device and split is enabled, the pointing device init needs to be called after the split post init, otherwise the connection (serial/etc) isn't initialized yet, and any commands that need to send data over (such as calling the set cpi command) never get sent over.
Experienced this with the charybdis, confirmed that moving later fixes the issue.
* Experienced by myself and reported by others
> Move Pointing Device Initialization to after Split Post Initialization

- keyboards/adafruit/macropad/config.h
- keyboards/adafruit/macropad/readme.md
Made a small boo-boo in the original bring-up:
The key used for bootmagic lite (the encoder button) is already being used as "BOOT"/"BOOTSEL" so QMK can't clear the flash since essentially it never booted into the firmware.
The fix was simple: Just change the key used for bootmagic lite :D
*
> (develop) Update bootmagic for Adafruit Macropad

- lib/python/qmk/tests/test_cli_commands.py
Python will evaluate first the left and then the right side of the and operator.
The left side would previously return True based on the truthiness logic that treats any non-emptry string as true. It would not check if the desired keymap exists.
If the left side is true it will evaluate the right side which will check for the existance of a specific keymap.
With this change the check for existance of two keymaps is implemented.
*
> Fix test logic to check for both keymaps

- docs/keycodes.md
- docs/quantum_keycodes.md
- quantum/quantum.c
Puts keyboard in bootloader mode if shift & control are held. Omits the need for bootmagic and `QK_BOOT` keycode to compile and flash firmware.
> Add ability to enter bootloader mode from `QK_MAKE`

- quantum/quantum.c
Was checking for `MOD_MASK_CS` which will trigger on shift or control, not just control+shift, which is not intended behavior.
This fixes the check so that it properly triggers on control+shift.
> Fix QK_MAKE's reboot check

- docs/faq_debug.md
Because of the print library change, the `%b` no longer works in the example.  
This fixes it to be working code.  Additionally, updates the sample output to reflect the more advanced code.
> [Docs] Fix custom debug function and sample output

- keyboards/bastardkb/charybdis/charybdis.c
- keyboards/bastardkb/dilemma/dilemma.c
- keyboards/bastardkb/dilemma/rules.mk
* Print variables error in compilation, fixes. 
* Reduces amount of logging to just mouse related keycodes
> [Keyboard] Fix compilation issues for Charybdis/Dilemma

- drivers/sensors/cirque_pinnacle_gestures.c
- quantum/pointing_device/pointing_device.c
Adjust coordinates for circular scroll, handle `POINTING_DEVICE_ROTATION_*_RIGHT` appropriately.
Reuse `pointing_device_adjust_by_defines*()` instead of using an incomplete custom implementation of the same logic.
Fix `pointing_device_adjust_by_defines_right()` for 180 & 270 degrees.
*
> Cirque circular scroll: Support POINTING_DEVICE_COMBINED

- keyboards/bastardkb/scylla/info.json
- keyboards/bastardkb/skeletyl/info.json
- keyboards/bastardkb/tbk/info.json
- keyboards/bastardkb/tbkmini/info.json
Fix forward changes that were reverted during the last merge.
cc @drashna 
*
> bastardkb: fix info.json changes that got reverted during the last merge from `master` to `develop`

- lib/python/qmk/cli/doctor/main.py
- lib/python/qmk/git.py
- lib/python/qmk/submodules.py
Adds some extra `qmk doctor` logging output to show the latest commit for both `upstream/master` and `upstream/develop`.
Simplifies investigations on our side:
```
% qmk doctor
Ψ CLI version: 1.1.0
Ψ QMK home: /home/nickb/qmk_build/qmk_firmware
Ψ Detected Linux.
Ψ Git branch: doctor-last-log-entries
Ψ Repo version: 0.17.5
Ψ - Latest doctor-last-log-entries: 2022-07-20 13:46:58 +1000 (f8d6d1571d) -- Add submodules, common ancestor.
Ψ - Latest upstream/master: 2022-07-20 01:55:48 +0100 (00c8e24c6a) -- [Keymap] Michal Keymap for Sofle rev1 (#17610)
Ψ - Latest upstream/develop: 2022-07-20 00:56:25 +0000 (fa44f2b21e) -- Merge remote-tracking branch 'origin/master' into develop
Ψ - Common ancestor with upstream/master: 2022-07-18 19:20:19 +0700 …
```
> Make `qmk doctor` print out the last log entry for upstream/{master,develop}, including dates

- quantum/dynamic_keymap.c
Various via keymaps are currently configured with incorrect amounts of keymap layers (`45_ats:via`, `10bleoledhub:via`, etc).
Instead of a `_Static_assert` in keymap introspection to ensure `keymap layers == dynamic keymap layer count`....
- allow fewer keymap layers
- will allow a small amount to be shaved off total firmware size
- most layers are "empty" anyway
- why bother having to maintain 2+ layers full of `_______`
> Avoid OOB in dynamic_keymap_reset

- quantum/pointing_device/pointing_device_drivers.c
Static `x` & `y` should be the same type as `touchData.xValue` & `touchData.yValue`: `uint16_t`.
Their delta could be larger than `int8_t` and should be constrained to `mouse_xy_report_t`.
*
> Constrain Cirque Pinnacle coordinates

- platforms/chibios/drivers/i2c_master.c
To fix i2c errors on RP2040 we need to explicitly stop the i2c peripheral in case of errors / timeouts. Also the ChibiOS HAL I2C driver description states:
> After a timeout the driver must be **stopped and restarted** because the bus is in an uncertain state.
This commit does that stopping explicitly on any error that occurred, not only timeouts. As all the `i2c` functions restart the peripheral if necessary it is safe to do so. 
* Part of https://github.com/ChibiOS/ChibiOS-Contrib/pull/329
> [Core] Chibios: Stop I2C peripheral on transaction error

- docs/_summary.md
- docs/platformdev_blackpill_f411.md
Adds a page about the blackpill.
> [Docs] Add information about WeAct Blackpill F411

- keyboards/mechwild/murphpad/keymaps/default/keymap.c
- keyboards/mechwild/murphpad/keymaps/default/rules.mk
- keyboards/mechwild/murphpad/keymaps/jonavin/keymap.c
- keyboards/mechwild/murphpad/keymaps/via/keymap.c
- keyboards/mechwild/murphpad/keymaps/via/rules.mk
- keyboards/mechwild/murphpad/murphpad.c
(tl;dr: qmk#17767, but for MurphPad.)
- Updates two non-user keymaps (default, via) to utilize encoder mapping
- Migrates common OLED & encoder callbacks to keyboard level, so firmware generated by QMK Configurator will have these features
- Updates @jonavin's keymap so it is not impacted by the new keyboard-level implementations
-  :sparkles: **bonus** :sparkles: Extremely minor formatting improvements.
> add encoder mapping, keyboard-level OLED + encoder definitions for mechwild/murphpad

- platforms/chibios/drivers/i2c_master.c
`msg_t` is `MSG_OK` in the success case and either `MSG_RESET` or `MSG_TIMEOUT` in case of errors. So actually use them in the comparison.
*
> [Core] Fix ChibiOS `i2c_master` error codes

- docs/feature_stenography.md
- docs/ja/feature_stenography.md
- quantum/process_keycode/process_steno.c
Small refactor to bring the post processing steno callback function in line with every other post processing QMK function.
```zsh
❯ git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'upstream/develop'.
~/qmk_firmware on develop *3 ⨤4                                                                                                                                                                       
❯ which grepqmk
grepqmk: aliased to fd -t f -E docs -E keyboards -E layouts -E users -E lib -X grep -n --color
~/qmk_firmware on develop *3 ⨤4                                                                                                                                                                       
❯ grepqmk "post_\?process" …
```
> Refactor/rename postprocess_steno_user → post_process_steno_user

- platforms/chibios/drivers/vendor/RP/RP2040/serial_vendor.c
In case the sending or receiving timeout we don't want the IRQs to fire anymore as the waiting thread has already been woken.
*
> [Core] RP2040 disable PIO IRQs on serial timeout

- keyboards/rgbkb/sol3/rules.mk
Enable Mousekeys by default.
Many of our users have asked for this, they just want to use the configurator and easily map scrolling to encoders or touchbars.
> Enable mousekeys by default for RGBKB Sol3

- quantum/process_keycode/process_joystick.c
Analog read is not hidden behind a pre-processor, so will try to run even if analog isn't enabled/set as the driver.
* fixes #17825
> Fix check when compiling HID Joystick with digital driver

- docs/feature_pointing_device.md
- drivers/sensors/cirque_pinnacle.c
- drivers/sensors/cirque_pinnacle.h
- drivers/sensors/cirque_pinnacle_gestures.c
- drivers/sensors/cirque_pinnacle_gestures.h
- drivers/sensors/cirque_pinnacle_regdefs.h
- quantum/pointing_device/pointing_device_drivers.c
Implement relative mode for Cirque trackpad
Cirque can work in absolute or relative mode, they differ in features. Give user a choice to use one of them. Also relative mode saves a lot of space.
> Implement relative mode for Cirque trackpad

- docs/quantum_painter.md
- drivers/painter/st77xx/qp_st7735.c
- drivers/painter/st77xx/qp_st7735.h
- drivers/painter/st77xx/qp_st7735_opcodes.h
- quantum/painter/qp.h
- quantum/painter/rules.mk
Using ST7789 as a template, I've added an ST7735 driver to Quantum Painter
The ST7735 driver code is very similar to the existing ST7789 driver code, with a few exceptions:
- The list of ST7735-specific opcodes in ``qp_st7735_opcodes.h`` are different (albeit currently unused by QP)
- The automatic viewport offsets are different. Testing was done using a 80x160 ST7735 display, for which the automatic offsets were determined experimentally for each rotation option.
*
> Add ST7735 driver to Quantum Painter

- drivers/flash/flash_spi.c
- platforms/chibios/drivers/eeprom/eeprom_stm32.c
Compilation errors with `make annepro2/c18:default CONSOLE_ENABLE=yes`.
Fixes up relevant format specifiers to match the input type.
> Fixup compilation of printf-like functions with uint32_t args.

- platforms/chibios/drivers/eeprom/eeprom_stm32.c
> Fix issue with #17904.

- keyboards/linworks/dolice/config.h
This PR adds support for the indicator LED hardware present on the Dolice keyboard PCB. It also removes an outdated 1000 Hz USB polling rate define, since that is QMK default now.
* Indicator LEDs not working on Dolice keyboard
> Add missing indicator LED defines for Dolice

- data/mappings/info_config.json
- docs/config_options.md
- docs/feature_rgblight.md
- docs/ja/config_options.md
Adds a lint check for RGBLIGHT_ANIMATIONS, to start deprecating the define in favor of explicitly enabled animations
> Add deprecated check for RGBLIGHT_ANIMATIONS

- keyboards/bastardkb/dilemma/splinky/splinky.c
It's using the user function, when it should be using the kb function
> [Keyboard] use correct function in Dilemma splinky

- .github/workflows/api.yml
- .github/workflows/develop_api.yml
- lib/python/qmk/cli/generate/api.py
> Publish data as part of API generation

- quantum/split_common/transactions.c
- quantum/split_common/transport.h
In case the RPC info data was corrupted during transmission we prevent the execution of bogus data.
*
> [Core] guard RPC invocation by checking RPC info against crc checksum

- quantum/pointing_device/pointing_device.c
pointing device init kb/user functions aren't called if the master doesn't have the pointing device.  This leads to issues if you're trying to call code for it (like setting up acceleration, default dpi, etc).
> Always run pointing device init

- quantum/matrix_common.c
In the comment of matrix_common.c, there was a wide space character derived from JIS code, so I changed it to a normal space. (since #9603)
> Fix comment space code in quantum/matrix_common.c

- .github/workflows/format_push.yml
<https://github.com/qmk/qmk_firmware/runs/5039520207?check_suite_focus=true>
```
/usr/bin/git checkout --progress -B bugfix/format_master 8b723f43-9d66-470f-bb09-7e845ba49beb --
error: Your local changes to the following files would be overwritten by checkout:
keyboards/keyten/kt60_m/kt60_m.c
Please commit your changes or stash them before you switch branches.
```
A bit of a guess, but it looks like automatic conversion is kicking in....?
*
> Disable line ending conversion on format workflow

- keyboards/macrocat/info.json
- keyboards/macrocat/keymaps/default/keymap.c
- keyboards/macrocat/keymaps/oled/keymap.c
- keyboards/macrocat/keymaps/via/keymap.c
- keyboards/macrocat/readme.md
- renames `LAYOUT_numpad_4x4` to `LAYOUT_ortho_4x4` (keyboard layout is actually 4x4 ortholinear)
- refactor keymaps to use layout macro (previously assigned via raw matrix)
- adds starcatmeow as a listed maintainer
- switch Bootloader and Docs instructions in `readme.md`
Compilation results are unchanged; checksums verified:
```sh
$ shasum macrocat_*
5051097472b9a89dd3f9266488a02d7899761c20 *macrocat_default.hex
7388555d282f58d9f811475736bc51b4fa770c20 *macrocat_oled.hex
1addf5128c70c9964a069476afa38c907bde6154 *macrocat_via.hex
```
cc @catmunch, @starcatmeow (keyboard maintainers)
> MacroCat Refactor

- keyboards/yanghu/unicorne/info.json
`LAYOUT_unicorne` → `LAYOUT_split_3x6_4` in info.json. The keymaps already use either `LAYOUT_split_3x6_4` or just `LAYOUT`, which has been added as an alias.
> standardize yanghu/unicorne LAYOUT in info.json

- quantum/rgb_matrix/animations/pixel_fractal_anim.h
* Halved array size to reduce memory footprint
* Include `RGB_MATRIX_USE_LIMITS()` 
Fixes https://github.com/qmk/qmk_firmware/issues/17589
> Refactor Pixel Fractal effect

- docs/feature_pointing_device.md
- drivers/sensors/adns5050.h
- drivers/sensors/adns9800.h
- drivers/sensors/cirque_pinnacle.h
- drivers/sensors/paw3204.h
- drivers/sensors/pmw33xx_common.h
Create default defines for pin configs, so that switching between sensors is easier.
> Create generic Pointing Device Pin defines

- docs/feature_encoders.md
- docs/feature_rgb_matrix.md
- docs/newbs_learn_more_resources.md
* Use simple switch statement for encoder layer function
* Use layer numbers instead of names for RGB indicator
* Remove [sunsetting Atom](https://github.blog/2022-06-08-sunsetting-atom/) editor
> [Docs] Refactor code examples

- keyboards/mechlovin/adelais/keymaps/default/keymap.c
- keyboards/mechlovin/adelais/keymaps/via/keymap.c
Hide rgb keycodes behind preprocessors in adelais keymaps
> [Keyboard] Fix compilation issues for Mechlovin Adelais

- platforms/chibios/drivers/wear_leveling/wear_leveling_efl_config.h
> Added implementation of WB32 MCU wear_leveling_efl.

- quantum/keymap_extras/keymap_bepo.h
```diff
diff --git a/quantum/keymap_extras/keymap_bepo.h b/quantum/keymap_extras/keymap_bepo.h
index 72d5b81f32..036aa128e7 100644
--- a/quantum/keymap_extras/keymap_bepo.h
+++ b/quantum/keymap_extras/keymap_bepo.h
@@ -237,4 +237,4 @@
#define BP_DDAG S(ALGR(BP_H))    // ‡
#define BP_FORD S(ALGR(BP_F))    // ª
// Row 5
-#define BP_NNBS S(ALGR(BP_))     //   (narrow non-breaking space)
+#define BP_NNBS S(ALGR(KC_SPC))     //   (narrow non-breaking space)
```
`BP_` isn't a valid macro.
*
> Fix Bépo's BP_NNBS (narrow non-breaking space)

- quantum/keymap_extras/keymap_lithuanian_qwerty.h
The QWERTY Lithuanian '+' (`LT_PLUS`) is on `S(ALGR(KC_EQL))`, and yet `LT_PLUS` was used to compose the keycode aliases for other modded keycodes involving `KC_EQL`, when `LT_ZCAR` would have been more appropriate.
The file even contained a definition of `LT_PLUS` in terms of itself:
```c
#define LT_PLUS S(ALGR(LT_PLUS)) // +
```
*
> Use LT_ZCAR in place of LT_PLUS for modded kc definitions of keymap_lithuanian_qwerty.h

- quantum/keymap_extras/keymap_korean.h
KR_DQUO was incorrectly defined as shift + KR_COLN.
```diff
diff --git a/quantum/keymap_extras/keymap_korean.h b/quantum/keymap_extras/keymap_korean.h
index 74be122dad..3d41a98b88 100644
--- a/quantum/keymap_extras/keymap_korean.h
+++ b/quantum/keymap_extras/keymap_korean.h
@@ -121,7 +121,7 @@
#define KR_PIPE S(KR_WON)  // |
// Row 3
#define KR_COLN S(KR_SCLN) // :
-#define KR_DQUO S(KR_COLN) // "
+#define KR_DQUO S(KR_QUOT) // "
// Row 4
#define KR_LABK S(KR_COMM) // <
#define KR_RABK S(KR_DOT)  // >
```
For reference:
```cs
75:#define KR_QUOT KC_QUOT // '
```
*
> KR_DQUO S(KR_COLN) → KR_DQUO S(KR_QUOT) in keymap_korean.h

- builddefs/common_features.mk
Wrong variable, whoops.
Confirmed compiling on several board
* Me screwing up.
> [Bug] Fix wrong varaible in encoder block

- Makefile
- util/size_regression.sh
Fixes up submodules when calling `make git-submodule`, as well as when running size regression checks.
Also adds `make git-submodules` because I always type the wrong one.
> Remove old submodules if present

- docs/hand_wire.md
- lib/python/qmk/constants.py
- lib/python/qmk/importers.py
* Update importers to use new-keyboard template files
* Attempt to extract kbfirmware keymap
* Update handwire to suggest import over manual steps
> Improve importer workflow

- builddefs/build_keyboard.mk
Re-order inclusion of userspace `rules.mk` before `mcu_selection.mk` to support overriding micro controller settings, such as chibios `CONVERT_TO` converters or `MCU` selection.
Confirmed binary reproducibility with `planck/rev6` and `crkbd/rev1`.
> [Core] Re-order user space rules inclusion

- builddefs/build_keyboard.mk
This reverts commit 69fa2d83781104fafd3992c1cece2ee98e862a69.
PR #17459 has broken some community layouts that depend on userspace code, because it loads userspace `rules.mk` before community layout `rules.mk`, thereby removing the ability to turn settings on/off in the community layout, and then react to those settings in the build of the userspace code. For example, see `layouts/community/75_ansi/spidey3`.
This PR rolls back #17459 for now.
[see above]
> Revert "[Core] Re-order user space rules inclusion (#17459)"

- platforms/chibios/drivers/ws2812.c
- platforms/chibios/drivers/ws2812_spi.c
Supporting this update requires updating chibios-contrib.
*
> Added ws2812_spi support for WB32 MCU

- platforms/chibios/drivers/ws2812_pwm.c
Supporting this update requires updating chibios-contrib.
*
> Added ws2812_pwm support for WB32 MCU.

- quantum/action_code.h
- quantum/keymap_common.c
- quantum/quantum_keycodes.h
Alignment as part of the eventual DD migration of keycodes. Fewer special cases will help simplify parsing and validation.
> Align TO() max layers with other keycodes

- docs/feature_unicode.md
- quantum/process_keycode/process_unicode_common.c
- quantum/process_keycode/process_unicode_common.h
- quantum/quantum_keycodes.h
I added a new unicode input mode: emacs. 
While strictly not an operating system, inserting unicode characters in emacs has its own keybinding. The most usual way is `C-x-8 RET` followed by the unicode in hex. As a person who works across different OSes but with the constant being emacs, this was the most straightforward way forwards. 
Of course, the main credit goes to TrentinQuarantino in this [emacs stack exchange post](https://emacs.stackexchange.com/a/56027).
I added a new unicode input mode in `quantum/process_unicode_common.(c|h)`. Then I updated all the programmer friendly numbers of the enums, and added documentation too.
* 
I'm unfamiliar with the testing protocols of this project. If I could get some help that'd be great. I'm reasonably familiar with C. However, what I have …
> Added emacs as an "operating system" for input mode. 

- keyboards/massdrop/alt/keymaps/via/config.h
- keyboards/massdrop/alt/keymaps/via/keymap.c
- keyboards/massdrop/alt/keymaps/via/readme.md
- keyboards/massdrop/alt/keymaps/via/rules.mk
* Enable all RGB Matrix Effects
* Move keyboard-specific keycodes to the user keycodes space
* Add additional layer to prevent issues with VIA expecting 4 layers instead of 3
> Improve Drop Alt compatibility with VIA

- platforms/chibios/drivers/ws2812_pwm.c
- platforms/chibios/drivers/ws2812_spi.c
Didnt allow them on previous driver changes, so should this time either.
*
> Partially revert some WB32 specific changes

- quantum/keymap_extras/keymap_us_extended.h
This is another one of those PRs where you can't see any difference in the diff, sorry.
```py
[ins] In [29]: import unicodedata as uc
[ins] In [30]: before = "// ̛̛  (dead)"
[ins] In [31]: after = "// ̛  (dead)"
[ins] In [32]: list(map(uc.name, before))
Out[32]: 
['SOLIDUS',
'SOLIDUS',
'SPACE',
'COMBINING HORN',
'COMBINING HORN',
'SPACE',
'SPACE',
'LEFT PARENTHESIS',
'LATIN SMALL LETTER D',
'LATIN SMALL LETTER E',
'LATIN SMALL LETTER A',
'LATIN SMALL LETTER D',
'RIGHT PARENTHESIS']
[ins] In [33]: list(map(uc.name, after))
Out[33]: 
['SOLIDUS',
'SOLIDUS',
'SPACE',
'COMBINING HORN',
'SPACE',
'SPACE',
'LEFT PARENTHESIS',
'LATIN SMALL LETTER D',
'LATIN SMALL LETTER E',
'LATIN SMALL LETTER A',
'LATIN SMALL LETTER D',
'RIGHT PARENTHESIS']
[ins] In [34]: horn_comment_from_keymap_bepo = "// ̛ …
```
> Remove duplicate COMBINING HORN in keymap_us_extended.h

- keyboards/converter/adb_usb/readme.md
- keyboards/converter/adb_usb/rev1/rules.mk
- keyboards/converter/adb_usb/rev2/rules.mk
- keyboards/converter/adb_usb/rules.mk
Removed erroneous `USB_HID_ENABLE` rule. Split into rev1 and rev2 for Pro Micro and Hasu PCB versions.
https://geekhack.org/index.php?topic=14290.0
*
> ADB to USB converter: split into rev1 and rev2

- quantum/action.c
- quantum/action.h
- tests/tap_hold_configurations/default_mod_tap/test_tap_hold.cpp
...as it is called with tick events and this would generate out of bound access `(col: 255, row: 255)` in keymaps in `keymap_key_to_keycode` though #13619 [add a mitigation.](https://github.com/tzarc/qmk_firmware/blob/46862e196f8e8cfd40e3e60599595816a751001d/quantum/keymap_common.c#L150-L162). Unit-tests that previously failed are enabled again.
`is_tap_key` is removed as well because it is not used in the code base and subject to the same bug.
* Out of bounds access of keymaps when tapping keys are held longer then one iteration.
> [Bug] Add key event check to `is_tap_record` and remove `is_tap_key`

- quantum/keymap_extras/keymap_spanish_dvorak.h
Fix a small mix-up between KC_DOT and DV_DOT (idem for *_COMM)
```diff
commit 46e69851f8d699f95f13d9a9c32e234632527e7f (HEAD -> fix_dvorak_spanish_colon_keys, origin/fix_dvorak_spanish_colon_keys)
Author: precondition <57645186+precondition@users.noreply.github.com>
Date:   Sun Aug 14 21:02:41 2022 +0200
Fix DV_SCLN and DV_COLN in keymap_spanish_dvorak.h
diff --git a/quantum/keymap_extras/keymap_spanish_dvorak.h b/quantum/keymap_extras/keymap_spanish_dvorak.h
index 29c4f1c44a..ea0c93f86a 100644
--- a/quantum/keymap_extras/keymap_spanish_dvorak.h
+++ b/quantum/keymap_extras/keymap_spanish_dvorak.h
@@ -114,8 +114,8 @@
#define DV_QUES S(DV_QUOT) // ?
#define DV_IQUE S(DV_IEXL) // ¿
// Row 2
-#define DV_COLN S(KC_DOT)  // :
-#define DV_SCLN S(KC_COMM) // ;
+#define DV_COLN S(DV_DOT)  // : …
```
> Fix DV_SCLN and DV_COLN in keymap_spanish_dvorak.h

- docs/feature_combo.md
Names may not be recognised when `COMBO_ONLY_FROM_LAYER` is defined with layer macros in `config.h`. This changes the example to actual layer numbers.
> Use layer number as example for COMBO_ONLY_FROM_LAYER

- builddefs/mcu_selection.mk
Going forward this aligns the defaults with other STM32 variants. Blackpill users should take advantage of the DD info.json config:
```json
{
"development_board": "blackpill_f401"
}
```
or
```json
{
"development_board": "blackpill_f411"
}
```
Which will correctly set up the mcu / bootlaoder / board files.
```sh
rg -l "MCU = STM32F4.1" keyboards/ | xargs grep -L "^BOARD"
```
*
> Swap F4x1 default board files away from blackpill

- keyboards/handwired/hillside/46/keymaps/manna-harbour_miryoku/config.h
- keyboards/handwired/hillside/46/keymaps/manna-harbour_miryoku/keymap.c
- keyboards/handwired/hillside/52/keymaps/manna-harbour_miryoku/config.h
- keyboards/handwired/hillside/52/keymaps/manna-harbour_miryoku/keymap.c
This PR adds the Miryoku keymap for the Hillside familily.
I did not add a README since the other Miryoku mappings I checked have none. Is that OK?
> Add Miryoku keymap for Hillside family

- lib/python/qmk/constants.py
Apparently my suggestion in https://github.com/qmk/qmk_firmware/pull/16584#discussion_r945332867 contained a wrong PID value (copied from another entry nearby). 🤦‍♂️
Copy the correct PID for the Keyboardio Atreus 2 bootloader from [`util/udev/50-qmk.rules`](https://github.com/qmk/qmk_firmware/blob/d2accb48e784030637f5517dfec66b13f1eab609/util/udev/50-qmk.rules#L38).
* `⚠ Missing or outdated udev rules for 'caterina' boards. Run 'sudo cp …/util/udev/50-qmk.rules /etc/udev/rules.d/'.`
> Fix PID value for the Keyboardio Atreus 2 bootloader

- docs/feature_tap_dance.md
break statements are missing from the switch for both registering and unregistering key codes. Neither have a default: case either. The code as exists in the repository right now does not compile. It does with this changes.
*
> Example 4 code is broken. Fix proposed

- shell.nix
- util/nix/poetry.lock
- util/nix/pyproject.toml
- util/nix/sources.json
Update the nix-shell environment in the `develop` branch to use QMK CLI 1.1.1 and newest versions of other required Python modules (including `pyserial`, which is a recent addition to the Python dependencies).
The update is required to make the current state of the `develop` branch buildable using `nix-shell` (with the existing version `qmk` fails to do anything due to the missing `pyserial` module).
@astridyu: This somewhat interferes with your change from #16602, because any externally supplied `pkgs` must also contain at least version 0.8.0 of `python3.pkgs.tomlkit` (but I did not specifically test that version, just noticed that sdispater/tomlkit#148 should be fixed there). It could be possible to add a `nixpkgsSource` argument to override just `sources.nixpkgs` (then the `shell.nix` …
> Nix shell updates for `develop`

- data/mappings/keyboard_aliases.json
- docs/ChangeLog/20220827.md
- docs/_summary.md
- docs/breaking_changes.md
- docs/breaking_changes_history.md
- readme.md
> 2022q3 Changelog.

- keyboards/40percentclub/nori/keymaps/default/keymap.c
- keyboards/ergotravel/keymaps/default/keymap.c
- keyboards/handwired/atreus50/keymaps/default/keymap.c
- keyboards/handwired/ortho5x13/keymaps/default/keymap.c
- keyboards/keebio/levinson/keymaps/default/keymap.c
- keyboards/keebio/nyquist/keymaps/default/keymap.c
- keyboards/keebio/rorschach/keymaps/default/keymap.c
- keyboards/keebio/viterbi/keymaps/default/keymap.c
- keyboards/keebio/wavelet/keymaps/default/keymap.c
- keyboards/lets_split/keymaps/default/keymap.c
- keyboards/maple_computing/launchpad/keymaps/default/keymap.c
- keyboards/maple_computing/launchpad/keymaps/default_rgb/keymap.c
- keyboards/maple_computing/minidox/keymaps/default/keymap.c
- keyboards/miniaxe/keymaps/default/keymap.c
- keyboards/miniaxe/keymaps/underglow/keymap.c
- keyboards/omkbd/ergodash/mini/keymaps/default/keymap.c
- keyboards/omkbd/ergodash/rev1/keymaps/default/keymap.c
- keyboards/orthodox/keymaps/default/keymap.c
- keyboards/unikeyboard/divergetm2/keymaps/default/keymap.c
- keyboards/woodkeys/scarletbandana/keymaps/default/keymap.c
- quantum/keymap_introspection.c
Implements `enum layer_names` on default/reference keymaps that were using `#define _ADJUST 16`.
> Clean-up of `#define _ADJUST 16` instances

- keyboards/adpenrose/shisaku/info.json
- keyboards/karlb/kbic65/info.json
- keyboards/keebio/bamfk4/info.json
- lib/python/qmk/cli/generate/config_h.py
- lib/python/qmk/info.py
Second fix for #18183, double quotes need to be escaped and unescaped as necessary inside string literals:
```c
#define MANUFACTURER "Hello "World" 123"
// should be
#define MANUFACTURER "Hello \"World\" 123"
```
as well as backslashes:
```c
#define MANUFACTURER "Hello\ world 123\" // comment"
// should be
#define MANUFACTURER "Hello\\ world 123\\" // comment
```
Additionally, there were a couple of boards which did not have a `manufacturer` key in info.json.
```
adpenrose/shisaku:default
adpenrose/shisaku:via
handwired/baredev/rev1:default
handwired/baredev/rev1:via
hotdox:default
hotdox:via
karlb/kbic65:default
karlb/kbic65:via
keebio/bamfk4:default
keebio/bamfk4:via
```
*
> Handle escaping of manufacturer/product strings

- quantum/pointing_device/pointing_device.c
Reset report ID that gets changed when sending mouse report to host.
Properly reset the in-memory mouse report, so that it's not sent all the time. Current behavior prevents power saving on host.
> Fix mouse report comparison failing on shared EP (fixes KB preventing sleep)

- docs/feature_encoders.md
- quantum/encoder.c
Use `TAP_CODE_DELAY` for encoder mapping by default. Add docs for `ENCODER_MAP_KEY_DELAY` in case someone wants different values.
> Use `TAP_CODE_DELAY` for encoder mapping by default. Add docs.

- docs/feature_pointing_device.md
- drivers/sensors/cirque_pinnacle.c
- drivers/sensors/cirque_pinnacle.h
- drivers/sensors/cirque_pinnacle_i2c.c
- drivers/sensors/cirque_pinnacle_spi.c
- drivers/sensors/pimoroni_trackball.c
- drivers/sensors/pmw33xx_common.c
- quantum/pointing_device/pointing_device_drivers.c
- quantum/pointing_device_internal.h
Spun out of #17613
...as debug messages from the pointing device drivers can be come quite verbose. These can be enabled with `POINTING_DEVICE_DEBUG` define on a keyboard level.
*
> [Core] Introduce pointing device specific debug messages

- data/mappings/info_rules.json
- data/schemas/keyboard.jsonschema
Also removed `bluetooth.lto` as it doesn't appear to be wired up to anything (?)
*
> Fix incorrect `bluetooth.driver` rules.mk mapping

- tmk_core/protocol/midi/midi.c
It showed an error when tmk_core/protocol/midi/midi.c was included.
Error:
```
Compiling: tmk_core/protocol/midi/midi.c                                                           tmk_core/protocol/midi/midi.c:22: error: "MIN" redefined [-Werror]
#define MIN(x, y) (((x) < (y)) ? (x) : (y))
```
The same method applied to rgblight.c, audio.h, vilocikey.c, color.c and util.h is used to solve it.
*
> Redefinition of MIN is avoided in midi.c

- docs/feature_caps_word.md
Provide more information about the differences between the behaviour of Caps Lock and Caps Word when it comes to what keys get capitalized/shifted. This is especially addressed to users of international OS keyboard layouts.
Inspired by https://github.com/qmk/qmk_firmware/issues/18136 and #18137 
*
> Expand on the differences between Caps Word and Caps Lock

- lib/python/qmk/cli/lint.py
`git_get_ignored_files()` expects its `check_dir` argument to be a string, but `keymap_check()` is passing it a Path object.
*
> `qmk lint`: fix TypeError

- builddefs/build_keyboard.mk
- keyboards/handwired/pytest/basic/rules.mk
- keyboards/handwired/pytest/has_community/rules.mk
- keyboards/handwired/pytest/has_template/rules.mk
- keyboards/handwired/pytest/info.json
- keyboards/handwired/pytest/macro/rules.mk
- lib/python/qmk/info.py
- lib/python/qmk/keymap.py
- platforms/arm_atsam/bootloader.mk
- platforms/avr/bootloader.mk
- platforms/chibios/bootloader.mk
At this point every keyboard should have either a valid bootloader set, or `custom`. Anything else should generate an error.
This change splits up bootloader.mk into platform-specific makefiles, to further lock out anything that is invalid (eg. `md-boot` for `atmega32u4`). This would fail to compile anyway as there is no `md-boot.c` under the AVR bootloaders directory, but now it should spit out a more user friendly error.
*
> Move bootloader.mk to platforms

- keyboards/clueboard/17/info.json
- keyboards/clueboard/66/rev1/info.json
- keyboards/clueboard/66/rev2/info.json
- keyboards/clueboard/66/rev3/info.json
- keyboards/clueboard/66_hotswap/prototype/info.json
- keyboards/clueboard/card/info.json
- keyboards/handwired/3dortho14u/rev1/info.json
- keyboards/handwired/3dortho14u/rev2/info.json
- keyboards/handwired/dactyl_manuform/4x5_5/rules.mk
- keyboards/handwired/dactyl_manuform/dmote/62key/info.json
- keyboards/handwired/hillside/46/info.json
- keyboards/handwired/hillside/48/info.json
- keyboards/handwired/hillside/52/info.json
- keyboards/handwired/wakizashi40/info.json
- keyboards/lfkeyboards/lfk65_hs/rules.mk
As a result of #18228 removing the default bootloader assignment and adjusting the makefile logic to complain if no bootloader is set, or an invalid one for the given platform:
```
clueboard/17:default
clueboard/66/rev1:default
clueboard/66/rev1:via
clueboard/66/rev2:default
clueboard/66/rev2:via
clueboard/66/rev3:default
clueboard/66/rev3:via
clueboard/66_hotswap/prototype:default
clueboard/card:default
handwired/3dortho14u/rev1:default
handwired/3dortho14u/rev1:via
handwired/3dortho14u/rev2:default
handwired/3dortho14u/rev2:via
handwired/dactyl_manuform/4x5_5:default
handwired/dactyl_manuform/dmote/62key:default
handwired/hillside/46:default
handwired/hillside/46:via
handwired/hillside/48:default
handwired/hillside/48:via
handwired/hillside/52:default …
```
> Ensure all keyboards have a bootloader set

- keyboards/massdrop/thekey/keymaps/default-bepo/keymap.c
- keyboards/massdrop/thekey/keymaps/url-copy-paste-bepo/keymap.c
The [bépo layout](https://bepo.fr/wiki/Accueil) move most of the letters compared to qwerty or even azerty. This mean that the default keymap for The Key is basically useless for bépo user.
This PR provide a bepo variant for both the default and the url-copy-paste keymaps for massdrop/thekey.
*  N/A
> Add bepo variant to massdrop/thekey keymaps

- docs/feature_unicode.md
- quantum/process_keycode/process_unicode_common.c
- quantum/process_keycode/process_unicode_common.h
- users/spidey3/layer_rgb.c
- users/spidey3/spidey3.c
- users/spidey3/spidey3.h
This change adds the following callbacks, to make the implementation indicators for the current unicode input mode easier:
|Callback                                                                          |Description                                                                 |
|-------------------------------------------------------------------------|---------------------------------------------------------------------|
| `unicode_input_mode_set_kb(uint8_t input_mode)`     | Callback for unicode input mode set, for keyboard.  |
| `unicode_input_mode_set_user(uint8_t input_mode)`  | Callback for unicode input mode set, for users.        |
* _none_
> Add unicode mode change callbacks

- platforms/chibios/converters/promicro_to_bit_c_pro/_pin_defs.h
- platforms/chibios/converters/promicro_to_stemcell/_pin_defs.h
Seems these have incorrectly slipped through.
> Remove non promicro pins from converters

- quantum/quantum.c
Slight change to `QK_CLEAR_EEPROM`, so that it's more in line with other eeprom related code.  Specifically "disable" eeprom (set the eeprom disabled bit), so that on next init, eeprom is re-initialized.
> Better handle EEPROM reset keycode

- users/drashna/bootmagic_better.c
- users/drashna/drashna.c
- users/drashna/rules.mk
Fix issue with compilation where I don't have defines for bootmagic specified.
> [Keymap] Fix bootmagic compilation issue with Drashna keymaps

- keyboards/annepro2/annepro2_ble.c
- keyboards/bioi/ble.c
- keyboards/hhkb/rn42/rn42.c
- tests/test_common/test_driver.cpp
- tests/test_common/test_driver.hpp
- tmk_core/protocol/arm_atsam/main_arm_atsam.c
- tmk_core/protocol/chibios/chibios.c
- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/host.c
- tmk_core/protocol/host_driver.h
- tmk_core/protocol/lufa/lufa.c
- tmk_core/protocol/vusb/vusb.c
Should make it a bit easier to tack on the Telephony page to the extrakeys report descriptor, for its microphone mute usage.
*
> Simplify extrakeys sending at the host driver level

- tmk_core/protocol/arm_atsam/main_arm_atsam.c
- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/lufa/lufa.c
- tmk_core/protocol/vusb/vusb.c
They need to live inside the function body so it still exists when media keys are disabled.
*
> Adjust `EXTRAKEY_ENABLE` ifdefs for `send_extra()`

- docs/feature_encoders.md
- docs/pr_checklist.md
While lint currently isnt throwing errors, at least the docs can have some more words to prevent.
> Discourage use of ENCODER_MAP at keyboard level

- keyboards/kinesis/keymaps/stapelberg/keymap.c
This makes more keys function as printed on the actual keyboard:
…also add a WAKE key in an easy-to-remember spot now that we have a separate layer :)
> keymaps/stapelberg: keypad layer for multimedia keys, wake on escape

- builddefs/common_features.mk
- drivers/bluetooth/bluefruit_le.cpp
- drivers/bluetooth/bluefruit_le.h
- quantum/keyboard.c
- tmk_core/protocol/host.c
- tmk_core/protocol/lufa/lufa.c
* Removed some useless `MOUSE_ENABLE` ifdefs in Bluefruit LE code (which caused issues with the main change here anyway)
* Fixed Bluefruit LE device name being in quotes (due to recent USB string define changes)
* Extracted Bluetooth-related code out of lufa.c and into host.c/keyboard.c so it can be platform-agnostic
Tested on a Pro Micro and Proton-C with both RN42 and BluefruitLE drivers.
*
> Move Bluetooth-related function calls up to host/keyboard level

- keyboards/handwired/6key/6key.h
- keyboards/handwired/6key/config.h
- keyboards/handwired/6key/info.json
- keyboards/handwired/6key/keymaps/default/keymap.c
- keyboards/handwired/6key/keymaps/default/readme.md
- keyboards/handwired/6key/keymaps/via/keymap.c
- keyboards/handwired/6key/keymaps/via/readme.md
- keyboards/handwired/6key/keymaps/via/rules.mk
- keyboards/handwired/6key/rules.mk
Adds via support for the 6key macropad
Adds a new keymap to the 6key macropad, and moves the dip switch configuration from the default keymap to `6key.c`. As a part of adding VIA support the vendor id was changed to be unique.
Also appropriately updates all references from LAYOUT to LAYOUT_all.
*
> Add via support for 6key

- lib/python/qmk/info.py
With both DD and config.h config, the following error is thrown:
```
File "/home/zvecr/qmk_firmware/lib/python/qmk/info.py", line 535, in _extract_config_h
_extract_split_right_pins(info_data, config_c)
File "/home/zvecr/qmk_firmware/lib/python/qmk/info.py", line 373, in _extract_split_right_pins
if info_data.get('split', {}).get('matrix_pins', {}).get('right') in info_data:
TypeError: unhashable type: 'dict'
```
Can be seen on <https://github.com/qmk/qmk_firmware/runs/8274718381?check_suite_focus=true>
*
> Fix '_RIGHT' matrix pins lint error

- tmk_core/protocol/usb_descriptor.c
`p65/iso` / `p96/iso` currently produce:
```sh
$ lsusb
Bus 001 Device 115: ID 320f:504a Glorious GMMK V2 65 (( ISO_TypeDef *) ((((uint32_t)0x40000000UL) + 0x10000) + 0x6000))
```
Same garbage displays on windows.
This is due to the macro,
```sh
$ rg ISO_TypeDef
lib/chibios-contrib/os/common/ext/CMSIS/WB32/WB32F3G71xx/wb32f3g71xx.h
407:} ISO_TypeDef;
1074:#define ISO                       ((        ISO_TypeDef *)          ISO_BASE)
```
and PRODUCT code gen spitting out non quoted strings.
* super short term bodge while a better fix can target develop
* alternative could be to just lower case the iso part?
*
> GMMK2: Fix 'ISO' within product name

- docs/feature_pointing_device.md
With commit https://github.com/qmk/qmk_firmware/commit/5db705d054e54a901f8968e3380e13c791991ab3 the documentation for configuring the attenuation for the cirque pinnacle touchpad became out of date due to some code changes. This commit updates the docs accordingly to match the current code again.
Relevant code section: https://github.com/qmk/qmk_firmware/blob/f010af0c8efebaf46111f891f54d11a21c5f929e/drivers/sensors/cirque_pinnacle_regdefs.h#L384-L392
> Fix docs regarding cirque pinnacle attenuation

- keyboards/unicomp/classic_ultracl_post_2013/info.json
- keyboards/unicomp/classic_ultracl_pre_2013/info.json
Correct keyboard_name for Unicomp Classic/Ultra Classic keyboards.
Setting originally in config.h was wrong due to a copy-paste mistake, and then the wrong value was migrated to info.json sometime in August.
*
> Correct keyboard_name for Unicomp Classic/Ultra Classic keyboards

- layouts/community/ortho_5x12/riblee/keymap.c
Remove terminal related keycodes from my keymap.
> Remove TERM_ON/TERM_OFF from my keymap

- quantum/keymap.h
- quantum/quantum_keycodes_legacy.h
`_Static_assert` currently cannot be added as it throws errors where the previous `RESET` bodges were required.
However, limiting legacy keycodes to only files where `QMK_KEYBOARD_H` is used makes it slightly happy. Mocked up in 2cbf950c6ea1ce8ae6ff5efa68e8c2add367fba9.
*
> Remove deprecated RESET keycode alias

- keyboards/kagizaraya/chidori/config.h
Added USB-related definitions to config.h that were changed by consolidated usbconfig.h.
> Fix problem that Chidori is not recognized by host computer.

- drivers/sensors/cirque_pinnacle_gestures.c
- quantum/pointing_device/pointing_device_drivers.c
The use of `pointing_device_set_report(mouse_report);` and `pointing_device_send();` won't work when the cirque is on the slave side of a split keyboard.
This is the least invasive fix/change that should sort the issue.
*
> Fix cirque tap from secondary side of split keyboard

- quantum/eeconfig.c
- quantum/split_common/split_util.c
Moves and adds some logic so fake EE_HANDS no longer requires a EEPROM init. 
Triggering a EEPROM init can be a pain with split keyboards that make use of `_RIGHT` defines for the matrix. This also emulates AVR better when flashing with left/right bootloader targets.
*
> Move fake EE_HANDS from EEPROM init.

- data/mappings/info_config.json
- lib/python/qmk/cli/generate/layouts.py
- lib/python/qmk/info.py
The config.h mapping now points at `usb.device_version`, and the code to ensure both are populated is removed. The schema entry will remain until a version bump.
Also found an apparently unused dict in layouts.py for some reason.
*
> Disconnect `usb.device_ver`

- lib/python/qmk/cli/multibuild.py
This just means I can run things in RAM for the CI.
> [CLI] Allow temporary files to be deleted after each build during `qmk multibuild`

- quantum/keycode.h
The reason for this move is because ACTION LAYER reserves 0xE0-0xFF for internal usage.
Namely, for other layer functions.  This means that LT is limited to 0x00-0xDF keycodes,
and effectively blocks mousekeys from being used.
By moving the mousekeys, this allows them to be used as part of LT.
This leaves C0-CC usable, still.
> Move mousekey keycodes into newly freed up keycode block

- quantum/unicode/unicode.c
AtlasTheGarbage said:
> btw one of the biggest bugs involving unicode input (which QMK relies on) is still unpatched
> where anything U+Axxx or U+Exxx is not accessible due to the sequences for Ă/ă/Ĕ/ĕ
This works around that problem by prepending a 0 in `UC_WINC` if the code begins with A-F, as the problem does not occur if a leading zero is added (U+0Axxx or U+0Exxx).
* _none_
> Work around WinCompose issue for U+Axxx or U+Exxx

- data/schemas/keyboard.jsonschema
- docs/feature_converters.md
- keyboards/cozykeys/speedo/v3/rules.mk
- platforms/chibios/converters/elite_c_to_elite_pi/_pin_defs.h
- platforms/chibios/converters/elite_c_to_elite_pi/converter.mk
- platforms/chibios/converters/elite_c_to_stemcell/_pin_defs.h
- platforms/chibios/converters/elite_c_to_stemcell/converter.mk
#18239 broke conversions which incorrectly relied on Elite-C pinouts for Pro Micro converters.
Potentially reduce duplication by inferring `promicro` compatibility when targeting `elite_c`.
*
> Add Elite-C to converters

- docs/quantum_painter.md
- drivers/painter/generic/qp_rgb565_surface.c
- drivers/painter/generic/qp_rgb565_surface.h
- drivers/painter/tft_panel/qp_tft_panel.c
- quantum/painter/qp.h
- quantum/painter/qp_draw_image.c
- quantum/painter/qp_draw_text.c
- quantum/painter/qp_stream.c
- quantum/painter/qp_stream.h
- quantum/painter/rules.mk
Adds support for an RGB565 surface, aka framebuffer. Allows for drawing to RAM, then copying just the dirty region to another display.
Slight tweak to the image/font loader functions to allow for alternate methods of loading assets, with the filesystem stuff in the pipeline.
Also did documentation cleanup requested by Dasky.
> [QP] Add RGB565 surface. Docs clarification, cleanup, tabsification, and reordering.

- quantum/rgblight/rgblight.c
Remove busy waiting from rgblight functions these have presumably been added to guarantee ws2812 leds being reset properly, but this is already handled by the low level ws2812 drivers. Therefore we remove these waits to not block the main thread.
*
> [Core] remove busy waiting from rgblight functions

- tests/tap_hold_configurations/default_mod_tap/test_tap_hold.cpp
- tests/tap_hold_configurations/permissive_hold/test_tap_hold.cpp
- tests/tap_hold_configurations/retro_tapping/test_tap_hold.cpp
- tests/tap_hold_configurations/tapping_force_hold/test_tap_hold.cpp
Cherry-picked from 18429, but enough to throw in sooner than later. Continues on from the previous PRs to increase consistency across core.
*
> Remove legacy keycodes from unit tests

- platforms/chibios/drivers/vendor/RP/RP2040/serial_vendor.c
...by moving the actually timing critical `enter_rx_state()` and `leave_rx_state()` functions to RAM in order to not be affected by XIP cache spikes. This commit also reverts the hacky USB interrupt disabling that was done in 293c53d774
Tested successfully with RP2040 BastardKB half-duplex split.
*
> [Core] Stabilize RP2040 Half-duplex PIO split comms take 2

- lib/python/qmk/info.py
If neither LED Matrix nor RGB Matrix are enabled, but a `g_led_config` structure exists in the keyboard, this code will parse and re-generate it assuming RGB Matrix. With this change the `g_led_config` is not generated unless one of the two are enabled.
*
> Fix incorrect g_led_config generation

- lib/python/qmk/cli/generate/config_h.py
- lib/python/qmk/tests/test_cli_commands.py
Wrap the boilerplate ifndef...define...endif in its own reusable function.
Ran into this while looking at automating DD RGBLight & LED/RGB Matrix animations (as opposed to adding mappings for each effect in info_config.json).
*
> Normalise info_config.h define generation

- docs/pr_checklist.md
Features adding kb/user callbacks should be boolean, to allow users to override dehavior.
> Explicitly mention kb/user callbacks as boolean

- platforms/chibios/vendors/RP/RP2040.mk
~~Depends on https://github.com/ChibiOS/ChibiOS-Contrib/pull/336 being merged first.~~ merged, also to QMK develop.
...this reduces possible latency when invoking interrupt handlers by mitigating XIP cache misses which are not existent when running code from RAM.
*
> [Core] Copy RP2040 vector table to RAM on startup

- keyboards/wilba_tech/wt60_a/config.h
- keyboards/wilba_tech/wt65_a/config.h
- keyboards/wilba_tech/wt65_b/config.h
- keyboards/wilba_tech/wt75_b/config.h
- keyboards/wilba_tech/wt75_c/config.h
- keyboards/wilba_tech/wt80_a/config.h
- keyboards/wilba_tech/wt_mono_backlight.c
Some Wilba Tech PCBs which use a LED driver IC for mono through-hole LEDs only implemented a backlight function.
Some people really want just Caps Lock and Scroll Lock LEDs.
> Add Caps Lock and Scroll Lock indicators to some Wilba Tech PCBs

- docs/feature_pointing_device.md
- quantum/pointing_device/pointing_device.c
- quantum/pointing_device/pointing_device.h
Cirque touchpads 'data ready'-pin implements active-high logic in contrast to most other pointing devices which use an active-low logic. Therefore, this commit implements both a configurable inversion of the motion pin logic and sets the the default for the cirque touchpad driver accordingly.
This issue came up yesterday in the #help-firmware discord channel and was pointed out by @daskygit after Kuromitsu#5783 tried to use the motion pin.
> Invert pointing device motion pin for cirque touchpads

- docs/keymap.md
Removes an anchor link to the "custom functions" section of the keymap docs that was removed in #5281. (This style of custom functions were removed entirely in #16025.)
> Remove orphan link in keymap docs (old custom functions)

- keyboards/drop/sense75/config.h
- keyboards/drop/sense75/sense75.c
- keyboards/keychron/q0/rev_0130/config.h
- keyboards/keychron/q0/rev_0130/rev_0130.c
- keyboards/saevus/cor_tkl/config.h
> Remove lingering `DRIVER_LED_TOTAL` references 

- keyboards/handwired/jscotto/scotto9/info.json
- keyboards/handwired/jscotto/scotto9/keymaps/default/keymap.c
- keyboards/handwired/jscotto/scotto9/readme.md
- keyboards/handwired/jscotto/scotto9/rules.mk
Add Scotto9 Macropad and default keymap.
*
> Add Scotto9 Macropad

- keyboards/keyquest/enclave/info.json
- keyboards/keyquest/enclave/keymaps/default/keymap.c
- keyboards/keyquest/enclave/keymaps/via/keymap.c
Also corrects the `maintainer` field in `info.json` to reference the maintainer's GitHub username.
cc @keyquesttech (keyboard maintainer)
> Keyquest Enclave-1: rename LAYOUT to LAYOUT_ortho_3x3

- quantum/action.c
The main reason for this, is so that the callbacks can effect the mods after the fact. A good case for this is enabling caps word when shift is locked.
> Move Oneshot mod callbacks to after mods are set

- keyboards/bastardkb/charybdis/charybdis.c
- keyboards/handwired/tractyl_manuform/tractyl_manuform.c
- keyboards/ploopyco/mouse/mouse.c
- keyboards/ploopyco/trackball/trackball.c
- keyboards/ploopyco/trackball_mini/trackball_mini.c
- quantum/action.c
- quantum/pointing_device/pointing_device.c
- quantum/pointing_device/pointing_device.h
Removes custom keycode handling for pointing device keyboards, and allows for register_code to properly handle mouse buttons when mousekeys is off.
> Enabling Pointing Device support in register code functions

- quantum/rgblight/rgblight.c
If `RGBLIGHT_LAYERS_RETAIN_VAL` is defined while lighting layers are used, `rgblight_layers_write()` checks `rgblight_config.val` for the currently set brightness. However, `rgblight_sethsv_eeprom_helper()` updates `rgblight_config.val` with the new `val` _after_ it calls `rgblight_setrgb()`, which ultimately calls `rgblight_layers_write()`. This means that if the brightness is changed while a lighting layer is active, the LEDs won't change to the new brightness until the lighting layer changes, or the HSV is changed again.
Tested with Iris Rev. 3
*
> Fix retain brightness when val is changed while a layer is active

- docs/config_options.md
- docs/reference_info_json.md
When pointing people at the info.json file for configuration, I often get pushback in the form of apathy toward "something that is only used by QMK Configurator".
This quick band-aid PR is my first shot at changing this line of thought.
- Notes the existence of `info.json`, and points people who make keyboards in its direction.
(...Should USB PID/VID/device ver `#defines` even still be listed here?)
To facilitate review, most of the actual content has not been updated. This is something I hope to follow up on, provided this whole PR isn't entirely off base (and I don't end up Extremely Sidelined by upcoming medical events).
- As described earlier, points out that info.json is used during local compilation.
- Reorganizes keys slightly in order to align with the PR Checklist.
- Extremely …
> [docs] Improve documentation regarding info.json

- keyboards/keychron/q2/rev_0112/keymaps/default/keymap.c
- keyboards/keychron/q2/rev_0112/keymaps/via/keymap.c
- keyboards/keychron/q2/rev_0113/keymaps/default/keymap.c
- keyboards/keychron/q2/rev_0113/keymaps/via/keymap.c
This fixes the first row of the keychron q2 mac layer in iso default keymaps, where number keys (KC_3 + KC_4) were accidentally (?) F keys (KC_F3 + KC_F4). All the F keys are in a separate layer anyways.
This is correct in the ansi variants of the keyboard, see:
* https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/q2/rev_0110/keymaps/default/keymap.c#L40
* https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/q2/rev_0110/keymaps/via/keymap.c#L40
* https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/q2/rev_0111/keymaps/default/keymap.c#L40
* https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/q2/rev_0111/keymaps/via/keymap.c#L40
*
> Fix keychron q2 mac layer in iso default keymaps

- builddefs/build_full_test.mk
- builddefs/build_test.mk
- quantum/dynamic_keymap.c
- quantum/keyboard.c
- quantum/keymap.h
- quantum/keymap_common.c
- quantum/keymap_introspection.c
- quantum/keymap_introspection.h
Starts preparation for decoupling dynamic keymap from being so intertwined with EEPROM as its specific backend.
Adds overridable functions for retrieval of keymap and encodermap data.
Modified `dynamic_keymap.c` to implement those overrides, allowing normal use of `keymap_key_to_keycode`.
Combos, key overrides, etc. to come in followup PRs.
> Start moving towards introspection-based data retrieval

- quantum/action.c
- quantum/keymap_common.c
Pulls out all of the logic for handling mouse keycodes into a single function for more consistent behavior, and allows mouse keycodess to work, even if mousekeys is disabled.
> Handle mouse keys more consistently

- keyboards/plywrks/ahgase/ahgase.h
- keyboards/plywrks/ahgase/info.json
- keyboards/plywrks/ahgase/keymaps/default/keymap.c
- keyboards/plywrks/ahgase/keymaps/iso/keymap.c
Renames the two non-`LAYOUT_all` macros to be compatible with Community Layouts, and enables support for them.
cc @ramonimbao (keyboard maintainer)
> Plywrks Ahgase Community Layout Support

- keyboards/crkbd/keymaps/bermeo/keymap.c
- keyboards/kikoslab/ellora65/keymaps/default/keymap.c
- keyboards/kikoslab/ellora65/keymaps/via/keymap.c
- keyboards/sofle/keymaps/flare576/graphics.c
- keyboards/sofle/keymaps/helltm/keymap.c
- keyboards/sofle/keymaps/noqmk/keymap.c
The old keyboard pet code would cause the screen to flicker after timeout because the animation would keep on running and each new frame would turn the screen on, after which the timeout logic would turn it off (provided the screen was idle for `> OLED_TIMEOUT`). The same flicker would be triggered by other triggers that turn the screen on, for instance toggling Caps Lock.
The on/off bug is fixed by using the animation idle timer (`anim_sleep`) also to track whether the screen is off or not. If the screen turns on (for whatever reason), we restart the timer. Also, we only render the keyboard pet when the screen is on, to prevent causing it to turn on.
The keyboard pet OLED timeout logic duplicates the timeout logic in the OLED driver. There are two more thorough solutions I can think of …
> Luna keyboard pet OLED timeout fix

- quantum/action.c
- quantum/action_code.h
> Small un/register_code() cleanups

- quantum/keymap_extras/keymap_colemak.h
`#define CM_QUES S(CM_SLSH) // /` → `#define CM_QUES S(CM_SLSH) // ?`
* (Indirectly) incorrect label for the Colemak OS keyboard layout on the QMK configurator
> Fix comment of CM_QUES (Colemak question mark)

- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/chibios/usb_util.c
`usb_disconnect()` previously only stopped the USB driver but didn't disconnect the device from USB bus. This is a problem with split keyboards that fail to enumerate on bootup but are actually connected to a USB bus. This can happen in the case that a short `SPLIT_USB_TIMEOUT` is used but it takes longer to enumerate with the host system correctly. In this condition the host system would still try to enumerate with the keyboard, as it still recognizes it as a connected device, but never succeed as we already disabled the USB driver. This in turn prevents some systems to boot-up correctly or at least slow down the boot process until the device is finally rejected by the host USB stack.
A drive-by fix is the case for rebooting a keyboard without a physical reconnect and not stopping the …
> [Core] ChibiOS: Fix USB bus disconnect handling

- quantum/process_keycode/process_dynamic_macro.c
This pull request introduces the userspace function `dynamic_macro_valid_key_user` to allow the user to omit certain events from being stored in the dynamic macros. This is particularly important when `DYN_*` keycodes are mapped to tap-dance keys; prior to these changes, `DYN_*` keys (e.g. `DYN_REC_START*` and `DYN_REC_STOP` are triggered upon executing the macro (since `TD(DYN)` records are stored in the buffer), leading to the bug where recorded macros can only be executed once before they are wiped.
An example keymap implemented using this function is available [here](https://github.com/jasonkena/qmk_firmware/blob/288e318b8f0fe1bfe22e4decac686527df3910cd/keyboards/ferris/keymaps/jasonkena/custom.c#L4).
*
> Prevent tap dance from wiping dynamic macros

- quantum/process_keycode/process_tap_dance.c
- quantum/process_keycode/process_tap_dance.h
- quantum/quantum.c
- tests/tap_dance/tap_dance_layers/config.h
- tests/tap_dance/tap_dance_layers/tap_dance_defs.c
- tests/tap_dance/tap_dance_layers/tap_dance_defs.h
- tests/tap_dance/tap_dance_layers/test.mk
- tests/tap_dance/tap_dance_layers/test_tap_dance_layers.cpp
Switching layers from tap dances did not work properly if the tap dance was finished by interrupting it (pressing a different key before the tapping term had expired — this includes both taps and holds): the layer switch was not affecting the interrupting key, but *seemingly only in some cases*. It turned out that there is another bug which almost makes the layer switching from tap dances work, but only for builtin keycodes handled inside `process_action()` — `process_record_handler()` performs a keymap lookup for a keypress event in a way which overwrites the source layers cache, therefore builtin keycodes which are handled inside `process_action()` are looked up after the tap dance code had updated the layer state. However, if you also have some custom keycodes on the affected layers …
> Fix layer switching from tap dances by redoing the keymap lookup

- platforms/chibios/drivers/serial_protocol.c
...in order to flush out any spurious bytes or traffic that belongs to failed transactions send by the secondary half. This is save todo as the main half initiates every transaction and must never receive any data before sending a handshake.
Tested with RP2040 and GD32VF103 splits.
*
> [Core] Serial-protocol: always clear receive queue on main half of split keyboard

- quantum/split_common/transactions.c
The access to the split shared memory shall be as short as possible in order to not block any pending transaction initiated by the main half of the keyboard. Most transaction handlers are deterministic and short in runtime and therefore can simply take the lock for the whole duration of the handler. Other handlers execute code that might end up calling user code or invoke interactions with external peripherals. Those handlers need a specialized implementation that takes a lock for the shortest possible duration. This is done in the following commit.
*
> [Core] rewrite locking in split transaction handlers

- platforms/chibios/drivers/vendor/RP/RP2040/serial_vendor.c
Previously the Full-duplex implementation would have it TX FIFO cleared although it was still sending data, as sending data happens asynchronously and we don't wait for all data to be send out before continuing with the execution of the main keyboard loop. Here we would run into a race condition where we cleared all FIFOs before starting a new transaction, while the last one was still in progress. 
This condition can not happen with the RX FIFO as we wait for a reception to be fully completed before continuing the execution, therefore it is save to fully and unconditionally clear the RX FIFO.
* The problem in the driver first surfaced with re-enabling the clearing in #18419
> [Bug] RP2040: only clear RX FIFO for serial pio driver clear

- platforms/chibios/vendors/RP/RP2040.mk
The rp2040 cortex m0+ cores do not implement an integer divider itself, but instead the rp2040 provides two on-chip hardware dividers as an extra peripheral. To use those the GCC arm-v6 eabi integer division and modulo built-ins have to be replaced with implementations that utilize them. An optimized i64 multiplication implementation is provided as well.
**these functions are implemented directly and do not need the pico vtable mechanism as the float/double functions**
Reference metric is completed QMK keyboard tasks per second:
| board | baseline | with hardware divider | improvement |
| - | - | - | - |
| Onekey | 20000 | 23000 | 15% |
| 1up/pi40 | 5100 | 6000 | 17% |
* More processing power is always nice
> [Core] RP2040: use built-in integer hardware divider and optimized i64 multiplication

- tmk_core/protocol/chibios/chibios.c
- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/host.c
- tmk_core/protocol/host.h
- tmk_core/protocol/host_driver.h
- tmk_core/protocol/lufa/lufa.c
- tmk_core/protocol/vusb/vusb.c
Removing programmable button from `host_driver_t` (to match digitizer and joystick) and hoisting report assembly out of USB drivers.
Eventual goal is to replace the `host_driver_t`'s `send_keyboard`, `send_mouse` and `send_extra` with a single `send_report` which takes endpoint number, pointer to report, and size.
*
> Refactor more host code (programmable button & digitizer)

- drivers/ps2/ps2_interrupt.c
Fix the compilation error for `ps2_interrupt.c`
* Closes #18596
> fix: ps2_interrupt.c failed to compile

- quantum/split_common/transactions.c
Use manually locking for the ST7565 handler, otherwise we'll deadlock when acquiring the shared memory lock twice.
*
> [Bug] Fix ST7565 handler deadlock

- quantum/xap/xap_handlers.c
- tmk_core/protocol/chibios/usb_main.c
This PR fixes two problems:
* Fix unaligned memory access in config blob handler:
`data*` points in the middle of an `u8` array, casting this to an `u16*` and de-referencing it leads to an unaligned memory access - which hardfaults on Cortex M0 mcus e.g. RP2040s.
* Read all incoming data until there is no more data to be read
The while condition did exit after the first loop, regardless if there was more data ready to be read.
* RP2040 hard-faulting with the XAP client
> [Bug] XAP: Fix unaligned memory access in config blob handler and USB task loop condition

- keyboards/adafruit/macropad/config.h
- keyboards/adafruit/macropad/readme.md
Replace bellow with below and fix this typo.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
*
> [Keyboard] adafruit/macropad: Fix typo

- data/mappings/info_config.json
- data/schemas/keyboard.jsonschema
- docs/config_options.md
- docs/feature_split_keyboard.md
- quantum/keyboard.c
- quantum/split_common/split_util.c
- quantum/split_common/split_util.h
- quantum/split_common/transaction_id_define.h
- quantum/split_common/transactions.c
- quantum/split_common/transport.h
Only had minimal testing so far, but this will allow for some feedback.
*
> Implement split comms watchdog

- docs/feature_led_indicators.md
- quantum/led.c
- quantum/led.h
Allow implementors of led_update_user() to modify the current led_state
but still use the default functionality of led_update_kb().
This can be used to reuse one of the standard LEDs for a different
usecase without having to reimplement led_update_kb().
Fixes #13272
This is still missing updates to the docs and keymaps.
Will do those after a first round of feedback.
* #13272
> quantum: led: split out led_update_ports() for customization of led behaviour

- keyboards/annepro2/annepro2_ble.c
- keyboards/bioi/ble.c
- keyboards/hhkb/rn42/rn42.c
- tests/test_common/test_driver.cpp
- tests/test_common/test_driver.hpp
- tmk_core/protocol/arm_atsam/main_arm_atsam.c
- tmk_core/protocol/arm_atsam/usb/udi_device_conf.h
- tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c
- tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.h
- tmk_core/protocol/chibios/chibios.c
- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/host.c
- tmk_core/protocol/host.h
- tmk_core/protocol/host_driver.h
- tmk_core/protocol/lufa/lufa.c
- tmk_core/protocol/vusb/vusb.c
Changed the signature of `send_extra` to pass the `report_extra_t *` instead of report ID and usage as separate parameters, so that the common host code does the work of checking the last sent usage and assembling the report struct.
*
> Refactor `send_extra`

- keyboards/supersplit/config.h
- keyboards/supersplit/info.json
- keyboards/supersplit/keymaps/default/keymap.c
- keyboards/supersplit/readme.md
- keyboards/supersplit/rules.mk
I'd like to add my own [keyboard](https://github.com/tarneaux/supersplit) to the upstream so that I can configure it on config.qmk.fm.
> Add supersplit

- data/mappings/info_config.json
- data/mappings/info_rules.json
- data/schemas/keyboard.jsonschema
- `build.debounce_type` and `backlight.levels` are missing mappings
- enum for `build.debounce_type` doesn't align with files in `quantum/debounce`
> add/fix DD mappings for build.debounce_type and backlight.levels

- keyboards/gmmk/pro/rev1/ansi/keymaps/andrebrait/keymap.c
Updating my own keymap with the following changes:
- Change some time calculation things
- Fix a missing return value introduced with #18450 
- Makes CAPS LOCK LEDs more obvious.
*
> [Keymap] update andrebrait GMMK Pro keymap

- quantum/keymap_extras/keymap_us.h
- quantum/quantum_keycodes.h
- quantum/sequencer/tests/rules.mk
As part of DD keycodes, the US ANSI shifted keycode aliases can be generated from the same process.
This PR moves the block so that the parsing/generation can take place as well as making quantum keycodes easier to generate.
*
> Relocate US ANSI shifted keycode aliases

- keyboards/annepro2/annepro2.c
- keyboards/annepro2/ap2_led.c
- keyboards/annepro2/ap2_led.h
- keyboards/annepro2/rgb_driver.c
Move the flushing of the RGB Matrix from the matrix scan to the flush driver function.
From my tests:  the flickering is reduced, and the animations are more fluid.
*
> AnnePro2: Adjust RGB flushing

- keyboards/dailycraft/sandbox/sandbox.c
- keyboards/duck/jetfire/indicator_leds.h
- keyboards/duck/jetfire/jetfire.c
- keyboards/duck/octagon/v2/indicator_leds.c
- keyboards/duck/octagon/v2/indicator_leds.h
- keyboards/dyz/synthesis60/synthesis60.c
- keyboards/yandrstudio/nz64/nz64.c
Most of these stem from later gcc versions having increased checks for recursion/bounds checks.
> Various keyboard fixes

- tmk_core/protocol/lufa/lufa.c
Bug: cannot send MIDI messages to keyboard. The callback functions registered via midi_register_* are never invoked. This blocks implementing things like MIDI controller feedback where DAW software sends messages to the controller to turn indicator lights on/off etc.
Fix: update the endpoint direction to match the stream direction for MIDI output in lufa.c. The IN/OUT mismatch was introduced in f209f91c7ce073aa0381e79c10219616cb7db523, likely a copypaste error.
Note that I don't actually understand how this works :), the fix came from reviewing code and applying common sense. I did validate in a custom keyboard that this change unblocks sending MIDI notes to the keyboard and receiving them via midi_register_noteon_callback.
*
> Fix MIDI output endpoint to use the out direction

- quantum/send_string/send_string_keycodes.h
16076 updated IDs but missed send string stuff.
> Fix mouse use within send_string

- keyboards/anavi/macropad10/config.h
- keyboards/anavi/macropad10/info.json
- keyboards/anavi/macropad10/keymaps/default/keymap.c
- keyboards/anavi/macropad10/macropad10.c
- keyboards/anavi/macropad10/readme.md
- keyboards/anavi/macropad10/rules.mk
ANAVI Macro Pad 10 is a mini hot-swappable mechanical keyboard with a clickable rotary encoder, 9 Cherry MX compatible switches, translucent key caps, USB-C, RP2040 microcontroller, backlighting and under lighting.
This commits adds initial QMK support for ANAVI Macro Pad 10 with:
- Default keymap
- Rotary encoder for controlling the volume
- WS2812B RGB underlighting
Several hardware features of ANAVI Macro Pad 10 are not supported yet: backlighting, neopixel on the XIAO RP2040 module and the click of the encoder (aka to use the encoder as a key).
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Add a new keyboard: ANAVI Macro Pad 10 with Raspberry Pi RP2040 MCU, This is a mini hot-swappable mechanical keyboard with a clickable rotary encoder, 9 Cherry MX compatible switches, …
> keyboards/anavi: Add ANAVI Macro Pad 10

- tmk_core/protocol/chibios/usb_main.c
- tmk_core/protocol/chibios/usb_main.h
- tmk_core/protocol/usb_descriptor.h
This fixes an issue I was seeing where no joystick reports were being sent on my Blackpill testbed, but worked fine on other ARM boards (eg. Proton-C and Bluepill). Turns out the joystick endpoint setup (and likely digitizer too, but I cannot test it) was incorrect.
A bunch of empty IN notification callbacks were also removed.
*
> Fix joystick functionality for ChibiOS and OTG (Blackpill)

- keyboards/wilba_tech/wt_main.c
- keyboards/wilba_tech/wt_mono_backlight.c
- keyboards/wilba_tech/wt_mono_backlight.h
- keyboards/wilba_tech/wt_rgb_backlight.c
- keyboards/wilba_tech/wt_rgb_backlight.h
I got the LED address wrong on the last commit. Whoops.
Also did a minor refactor since caching the indicator state was redundant.
*
> Fix Caps Lock indicators on Wilba Tech PCBs

- drivers/gpio/mcp23018.c
- drivers/gpio/mcp23018.h
include a "is the device actually connected?" check into the init
function, that now returns a boolean, which can be handled by a
keyboard to - for example - decide not to query an unconnected
portexpander during each matrix scan; avoiding i2c
spam/errors/timeouts
Signed-off-by: Johannes Schneider <JohSchneider@googlemail.com>
*
> mcp23018: add return status to init

- drivers/painter/gc9a01/qp_gc9a01.c
- drivers/painter/ili9xxx/qp_ili9163.c
- drivers/painter/ili9xxx/qp_ili9341.c
- drivers/painter/ili9xxx/qp_ili9488.c
- drivers/painter/ssd1351/qp_ssd1351.c
- drivers/painter/st77xx/qp_st7735.c
- drivers/painter/st77xx/qp_st7789.c
Allows keyboards to override the init sequence for each driver, potentially opening up support for slightly different panels.
Will need to be on top of custom implementations to check that they don't get copypasta'd everywhere -- in that case we should formalise the process by punting the sequence into core.
> Make QP driver init functions weak.

- docs/feature_programmable_button.md
- quantum/action.c
- quantum/keyboard.c
- quantum/process_keycode/process_programmable_button.c
- quantum/programmable_button.c
- quantum/programmable_button.h
This feature is very spammy as the reports are sent in `keyboard_task()` regardless of whether there are any changes. I've removed this and added two new functions, `programmable_button_un/register()` which call `_add/remove()` and then `_flush()` to send the report. This way you can still leverage the API to programmatically modify multiple button states in a single report, but the keycodes will send a report immediately.
The documentation has also been cleaned up, and particularly I have added a note regarding support for this feature on Windows and macOS.
*
> Programmable Button API refactor and improve docs

- tmk_core/protocol/lufa/lufa.c
Noticed there was a fair bit of repetition here. Shaves off almost 100 bytes (tested with `gh60/satan:default`). Also looking into whether similar can be done for the other platforms.
*
> LUFA: Consolidate report sending code

- keyboards/dk60/dk60.c
- keyboards/dp60/keymaps/indicator/indicator.c
- keyboards/fallacy/fallacy.c
- keyboards/iron180/iron180.c
- keyboards/kc60/kc60.c
- keyboards/metamechs/timberwolf/timberwolf.c
- keyboards/moonlander/moonlander.c
- keyboards/novelkeys/nk65/nk65.c
- keyboards/nullbitsco/nibble/nibble.c
- keyboards/nullbitsco/tidbit/tidbit.c
- keyboards/viendi8l/viendi8l.c
- keyboards/weirdo/ls_60/ls_60.c
- keyboards/yiancardesigns/seigaiha/seigaiha.c
Following #14452, less boilerplate is needed to customize indicator led control.
I went through the keyboard .c files and updated those instances where the change was straightforward. I did not touch instances where the implementation consisted solely of `writePin` invocations, because I believe nearly all of those functions could go and be replaced by the desired LED pin `define`s.
> led_update_kb -> led_update_ports where appropriate

- keyboards/moonlander/moonlander.c
- keyboards/moonlander/moonlander.h
A music map where each row has the same length is a lot more intuitive. With a chromatic scale, having rows of twelve tones is especially nice.
> Allow changes to the moonlander default music map

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix/rgb_matrix_drivers.c
Trivial PR that brings 4 driver support (as opposed to only 2) for the IS31FL3737 LED driver
*
> 4 Driver support for IS31FL3737

- users/manna-harbour_miryoku/miryoku_babel/miryoku_alternatives.h
Change RESET to QK_BOOT in user/manna-harbour_miryoku
Clears way for CI on #18751. 
*
> [Keymap] manna-harbour_miryoku RESET to QK_BOOT

- users/snowe/ocean_dream.c
Fixes an issue in Ocean Dream that causes flashing after the oled screen
times out and turns off.
This occurs because writing to an OLED screen turns it on as well and we
are both writing then immediately turning the screen off, but only if
the timeout has occurred (no WPM, 30 seconds has passed).
*
> Adjust oled gen to fix flashing on timeout

- lib/python/qmk/commands.py
The following does not correctly build a via compatible keymap
```sh
qmk compile keyboards/thevankeyboards/minivan/keymaps/via/keymap.json
```
*
> Correctly build keymap.json containing additional config

- builddefs/build_keyboard.mk
- lib/python/qmk/cli/generate/config_h.py
- lib/python/qmk/cli/generate/rules_mk.py
Missed when implementing #18766.
*
> Correctly build out of tree keymap.json containing additional config

- keyboards/wolf/sabre/config.h
The caps lock and scroll lock LEDs were inverted
> Sabre Fix LEDs being inverted

- keyboards/readme.md
Clueboard keyboards are no longer commercially available and ZSA has expanded its offering.
The top-level project readme also suggests the Atreus keyboard as being 'official'. That keyboard is also no longer commercially available (in its original form; keyboardio sells a new variant). I wonder whether it would be good to either include Atreus in the list of official keyboards in the keyboards readme, or drop Clueboard from that list. The fate of both lines of keyboards appears to be similar.
@skullydazed @technomancy
> Update keyboards readme

- drivers/led/ckled2001.c
- keyboards/keychron/q3/config.h
This PR focuses on indirectly increasing the keyboard matrix scan frequency which is held back by sending the latest pwm buffers over to the 2 CKLED2001 LED drivers.
Prior to this PR the keeb is doing ~**640** matrix scans/sec with RGB enabled.
The increase in I2C speed to 1000 KHz (from the default of 400 KHz) gets this up to ~1100 matrix scans/sec with RGB enabled.
The increased g_twi_transfer_buffer gets the amount of transmissions from 12 per driver (24 total) to 3 per driver (6 total), getting it to ~**1150** matrix scans/sec with RGB enabled.
The 1000 KHz is within the spec of  the `STM32L432` and technically can be pushed even further (but CUBE-MX won't let me generate those :( ) .
I should note that the "official doc" for `CKLED2001` only advertises 400 KHz support (from my past …
> Keychron Q3 I2C & CKLED2001 transfer speedup

- data/schemas/keymap.jsonschema
- lib/python/qmk/cli/generate/config_h.py
- lib/python/qmk/cli/generate/rules_mk.py
Building on the recent bug fixes, its now possible to add in support for `CONVERT_TO`. Eventually this *could* power a drop down somewhere on configurator.
Potentially it could extend the existing `config` object, and reuse `mappings/info_rules.json`...? 
Key (and potentially any parents) up for grabs still.
*
> Add converter support to keymap.json

- keyboards/wilba_tech/wt_rgb_backlight.c
As the title says, this allows user keymaps to override backlight_effect_indicators() for keyboards which use Wilba Tech RGB.
I wanted to light things up in a custom way to show each key defined in each active non-base layer, plus extra lighting for modifier keys.  With this one-line change, now I can.
The Wilba Tech code doesn't have a _kb() / _user() abstraction for customizing this, and I don't want to break anyone's keymaps by changing the API, so I just made the function weak.
> wilba_tech: allow keymaps to override backlight_effect_indicators()

- tmk_core/protocol/chibios/usb_main.c
In #18631 some IN notification callbacks that were doing nothing were removed, which should be a valid thing to do (ChibiOS HAL checks the `in_cb` and `out_cb` pointers for being non-NULL before invoking those optional callbacks).  However, it turned out that some less popular USB LLDs (KINETIS and MIMXRT1062) have their own checks for those pointers, and (incorrectly) skip the ChibiOS callback handling when those pointers are NULL, which breaks the code for the `USB_USE_WAIT` configuration option (the waiting thread never gets resumed if the corresponding callback pointer is NULL).
Add those dummy callbacks again (but use a single function for all of them instead of individual ones for each endpoint); this restores the KINETIS and MIMXRT1062 boards to the working state while the LLDs are …
> ChibiOS USB: Add a dummy IN callback to work around LLD bugs

- builddefs/build_keyboard.mk
- builddefs/common_features.mk
- platforms/chibios/converters/promicro_to_proton_c/post_converter.mk
Remove CTPC specific changes, and allow other converters to specify other defaults
> Generalise CTPC logic from common_features

- data/mappings/info_config.json
- data/schemas/keyboard.jsonschema
- tests/tap_hold_configurations/hold_on_other_key_press/config.h
- tests/tap_hold_configurations/hold_on_other_key_press/test.mk
- tests/tap_hold_configurations/hold_on_other_key_press/test_tap_hold.cpp
Add HOLD_ON_OTHER_KEY_PRESS[_PER_KEY] to data-driven files and create a suite of unit tests to verify the behaviour of modtaps, layertaps and regular keys with HOLD_ON_OTHER_KEY_PRESS.
These commits were originally a part of #15741 but that's a breaking change that will take a long time to get merged. The unit tests for HOLD_ON_OTHER_KEY_PRESS aren't particularly tied to the scope and intent of the “make-ignore-mod-tap-interrupt-the-default” PR so they can be reviewed and merged separately.
*
> Add unit tests for HOLD_ON_OTHER_KEY_PRESS

- keyboards/macro3/info.json
- keyboards/macro3/keymaps/default/keymap.c
- keyboards/macro3/macro3.h
[title]
cc @filterpaper (keyboard maintainer, sort of)
> Macro3: rename LAYOUT to LAYOUT_ortho_2x4

- builddefs/build_test.mk
- tests/test_common/main.cpp
Currently some tests output as,
```
Testing secure
Running 10 tests from 1 test suite.
[==========] [----------] Global test environment set-up.
10 tests from Secure[----------] 
Secure.test_lock[ RUN      ] 
Secure.test_lock (0 ms)
[       OK ] Secure.test_unlock_timeout[ RUN      ] 
Secure.test_unlock_timeout (0 ms)
[       OK ] Secure.test_unlock_request[ RUN      ] 
Secure.test_unlock_request (0 ms)
[       OK ] Secure.test_unlock_request_fail[ RUN      ] 
Secure.test_unlock_request_fail (0 ms)
[       OK ] Secure.test_unlock_request_timeout[ RUN      ] 
Secure.test_unlock_request_timeout (0 ms)
[       OK ] Secure.test_unlock_request_fail_mid[ RUN      ] 
Secure.test_unlock_request_fail_mid (0 ms)
[       OK ] Secure.test_unlock_request_fail_out_of_order[ RUN      ] …
```
> Fix garbled test output

- docs/keycodes.md
- quantum/process_keycode/process_magic.c
- quantum/quantum_keycodes.h
Most of the magic swap keys have a toggle, but backspace/backslash didn't.  So I added one.
This lets me have one key to toggle that behavior, instead of needing to dedicate two keys.
> added BS_TOGG so BS_SWAP and BS_NORM can be on a single key

- keyboards/moonlander/moonlander.c
- keyboards/planck/ez/ez.c
- quantum/process_keycode/process_autocorrect.c
> Remove some assumptions on sequential keycode ranges

- keyboards/emptystring/nqg/config.h
- keyboards/emptystring/nqg/keymaps/default/keymap.c
- keyboards/emptystring/nqg/nqg.c
- keyboards/emptystring/nqg/nqg.h
Rename directory for consistency, keycode, & misc cleanup.
Can retarget to develop if that's preferred.
> Fixup emptystring/nqg

- keyboards/huytbt/h50/info.json
Missing manufacturer define for usb data
> Fixup huytbt/h50

- docs/feature_secure.md
- quantum/process_keycode/process_secure.c
- quantum/quantum_keycodes.h
- quantum/quantum_keycodes_legacy.h
Also adds short form aliases.
*
> Deprecate `SECURE_*` keycodes for `QK_SECURE_*`

- quantum/rgb_matrix/rgb_matrix.h
`rgb_matrix_get_flags_noeeprom`  doesnt exist :shrug: 
*
> Fix rgb_matrix_set_flags_noeeprom declaration

- keyboards/splitkb/aurora/sweep/keymaps/debug/rules.mk
- keyboards/splitkb/aurora/sweep/keymaps/default/keymap.json
- keyboards/splitkb/aurora/sweep/keymaps/default/readme.md
- keyboards/splitkb/aurora/sweep/rev1/info.json
- keyboards/splitkb/aurora/sweep/rev1/rev1.c
- Fixes compile error with `SWAP_HANDS_ENABLE = yes` due to missing header import
- Enables OLED, RGB Matrix, and encoder when using QMK Configurator
*
> [Keyboard] Minor Aurora Sweep fixes

- keyboards/keebio/sinc/rev3/config.h
- keyboards/keebio/sinc/rev3/info.json
- `DRIVER_LED_TOTAL` -> `RGB_MATRIX_LED_COUNT`
- avoid using `rgblight` config for `rgb_matrix`
> Fixup keebio/sinc/rev3

- keyboards/rart/rart4x4/config.h
- keyboards/rart/rart4x4/keymaps/via/keymap.c
- keyboards/rart/rart4x4/keymaps/via/rules.mk
- keyboards/rart/rart75/keymaps/via/keymap.c
- keyboards/rart/rart75/keymaps/via/rules.mk
- keyboards/rart/rart75hs/keymaps/via/keymap.c
- keyboards/rart/rart75hs/keymaps/via/rules.mk
- keyboards/rart/rart75hs/rart75hs.c
- keyboards/rart/rart75m/keymaps/via/keymap.c
- keyboards/rart/rart75m/keymaps/via/rules.mk
- keyboards/rart/rart75m/rart75m.c
- keyboards/rart/rart80/config.h
- keyboards/rart/rart80/rules.mk
- keyboards/rart/rartpad/config.h
- keyboards/rart/rartpad/keymaps/via/keymap.c
- keyboards/rart/rartpad/keymaps/via/rules.mk
- keyboards/rart/rartpad/rartpad.c
- Add encoder mapping for rart4x4, rart75, rart75hs, rart75m and rartpad
- Add encoder map enable to utilize encoder mapping
- Fix pin capslock and RGB fot rart80
*
> Add Encoder map support for rart

- keyboards/cannonkeys/hoodrowg/config.h
> Add indicator LEDs to hoodrow G PCB

- builddefs/common_rules.mk
When `CC` is clang, and compiler.txt does not exist, the following is printed to stderr:
```
error: write on a pipe with no reader
```
On macOS at least, this results in false `[WARNINGS]` when running the unit tests.
*
> compiler.txt: ensure file exists before comparison

- quantum/eeconfig.c
- quantum/eeconfig.h
`EECONFIG_MOUSEKEY_ACCEL` is not actually used anywhere in the repo, so since it's adjacent to `EECONFIG_KEYMAP`, remove it and appropriate it's block for the upper byte of keymap config, so it can use a full, contiguous block.
Also, shift default value to be still correct.
> Simplify Keymap Config EEPROM

- quantum/xap/xap.c
- quantum/xap/xap_handlers.c
This fixes two bugs:
1. An invalid `offset` could be specified which wasn't checked to be in the bounds of the config blob.
2. The `data_len` check was incorrect as it would allow reading one byte past the config blob lenght.
Before the changes the following operation wouldn't fail:
Assuming we have blob of 64 bytes size and attempt a read with an `offset` of 32 and `data_len` of 32, we actually try to read 32 bytes starting from the 33. byte in the config blob. This reads exactly one byte past array (33 + 32 > 64). Therefore we have to subtract one byte the get the correct length.
*
> [XAP] prevent OOB reads in config blob handler

- quantum/sequencer/sequencer.c
- quantum/sequencer/sequencer.h
Reduce includes for `sequencer.h`, and indirectly `quantum_keycode.h`.
*
> Reduce includes for sequencer header

- quantum/caps_word.c
- quantum/caps_word.h
Also includes minor formatting changes.
*
> Reduce includes for caps_word header

- quantum/wpm.c
`WPM_ALLOW_COUNT_REGRESSION` uses mods and keycodes, and the recent changes break the chain of includes.
> [Bug] Fix compilation issue with WPM

- quantum/keymap_common.c
- quantum/pointing_device/pointing_device_auto_mouse.c
- quantum/process_keycode/process_autocorrect.c
- quantum/process_keycode/process_caps_word.c
- quantum/process_keycode/process_leader.c
- quantum/process_keycode/process_unicode.c
- quantum/process_keycode/process_unicodemap.c
- quantum/quantum_keycodes.h
QMK has many keycodes with parameters, like `TO(layer)` or `MT(mod, kc)`. Add macros for extracting the values of those parameters from the keycode, so that the bit allocation for those parameters can be performed in a single place where those macros are defined; then change various code that was extracting the parameters manually to use those macros.
Macro names are based on the full `QK_xxx` range name; e.g., for `MO(layer)` it is `QK_MOMENTARY_GET_LAYER(kc)`. 
This change actually fixes several regressions introduced by DD keycode changes (mainly due to bit masks for layer-related keycodes no longer being correct).
Tested mostly by `make test:all` (which unfortunately does not cover much of the affected code); the `TT()` bug was verified on some actual hardware. And probably not all …
> Fix keycode parameter extraction to match the new DD keycodes

- keyboards/mechlovin/adelais/standard_led/avr/rev1/rev1.h
```
☒ mechlovin/adelais/standard_led/avr/rev1: Number of keys for LAYOUT_alice_full_rshift does not match! info.json specifies 64 keys, C macro specifies 65
```
Extra key in this layout macro which wasn't mapped anywhere.
*
> `mechlovin/adelais/standard_led/avr/rev1`: fix layout

- docs/quantum_painter.md
- lib/python/qmk/cli/painter/convert_graphics.py
- lib/python/qmk/cli/painter/make_font.py
Adds raw file generation for QGF/QFF files, rather than writing to C/H files.
> Add raw output option for QGF/QFF files.

- keyboards/gboards/gergoplex/config.h
- keyboards/gboards/gergoplex/matrix.c
```
☒ gboards/gergoplex: MATRIX_COLS is inconsistent with the size of MATRIX_COL_PINS: 5 != 4
☒ gboards/gergoplex: MATRIX_ROWS is inconsistent with the size of MATRIX_ROW_PINS: 4 != 10
```
Compiles, and shouldn't be any functional change, but I don't have hardware to test.
*
> `gboards/gergoplex`: fix matrix pins

- keyboards/keychron/q1/iso_encoder/config.h
- keyboards/keychron/q1/iso_encoder/iso_encoder.c
> Fixup keychron/q1/iso_encoder

- lib/python/qmk/c_parse.py
- lib/python/qmk/info.py
Helped me track down some of the recent `qmk info` complaints regarding `g_led_config`.
*
> Improve LED config parsing error messages

- keyboards/bolsa/bolsalice/bolsalice.h
```
./.build/obj_bolsa_bolsalice_generated/src/keymap.c:11:135: error: excess elements in array initializer [-Werror]
```
*
> `bolsa/bolsalice`: fix layout

- quantum/pointing_device/pointing_device_drivers.c
Avoid sending the report until the scale matches the x,y delta values. Otherwise when adjusting scale while touchpad is active causes a jump in report values due to the touchData and x,y values using different scales, causing the delta calculation to have an erroneous value
I'm happy to adjust the approach as needed. This just seemed the simplest way to ensure the report_x|y delta was using the same scale. 
* Fixes https://github.com/qmk/qmk_firmware/issues/18980
> Fix jump in mouse_report value when scale changes during cirque get report

- docs/ws2812_driver.md
- platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c
Allows setting of custom WS2812 timings using the defines found in `ws2812.h`, it also uses these timings as it's default now. Furthermore the reset timing is now applied correctly before starting a new transfer. Due to implementation details the waiting times are rounded to 50ns intervals.
| Period     | Time  |
| ---------- | ----- |
| WS2812_T1H | 900ns |
| WS2812_T1L | 350ns |
| WS2812_T0H | 350ns |
| WS2812_T0L | 900ns |
| RESET      | 280us |
| Period     | Time  |
| ---------- | ----- |
| WS2812_T1H | 500ns |
| WS2812_T1L | 450ns |
| WS2812_T0H | 400ns |
| WS2812_T0L | 750ns |
| RESET      | 80us  |
Deviation from 80us due to the driver choosing the longer `T0H + T0L` or `T1H + T1L` period which is irregular in this case.
*
> [Core] Allow custom timings for WS2812 PIO driver

- keyboards/handwired/onekey/bluepill_f103c6/rules.mk
- keyboards/handwired/onekey/info.json
```
⚠ handwired/onekey/bluepill_f103c6: Feature mousekey is specified in both info.json and rules.mk, the rules.mk value wins.
⚠ handwired/onekey/bluepill_f103c6: Feature nkro is specified in both info.json and rules.mk, the rules.mk value wins.
```
These features are hard to properly test with only a single key, and with CI in place checking that it at least compiles is already done.
*
> onekey: disable NKRO and mousekeys by default

- drivers/oled/ssd1306_sh1106.c
`oled_render` is meant to render all dirty changes to the device, but it only renders the first dirty block it finds. In practice this does not usually cause much of a problem because it is called periodically from `oled_task`, and eventually it works its way through all dirty blocks and they get rendered.
However, if you update the oled very fast, like in an animation, the first blocks are made  re-dirty before the `oled_task` loop can catch up w/ rendering the later blocks. This causes the later blocks to not get rendered.
This change fixes that problem by rendering all dirty blocks in `oled_render` which is what I believe users of that function would expect it to do.
* none
> Fix oled_render to render all dirty blocks.

- quantum/encoder.c
- quantum/encoder/tests/config_mock_split_role.h
- quantum/encoder/tests/encoder_tests_split_role.cpp
- quantum/encoder/tests/mock.c
- quantum/encoder/tests/mock_split.c
- quantum/encoder/tests/rules.mk
- quantum/encoder/tests/testlist.mk
Only call encoder behavior on primary/master side.  Delays can cause issues with split boards. 
* mentioned by mtei
> Only trigger encoder callbacks on primary side

- quantum/action_tapping.h
Adds the missing function prototype for `get_hold_on_other_key_press` in `/quantum/action_tapping.h`. The missing prototype doesn't cause errors most of the time, but does (at least) if both auto-shift and `HOLD_ON_OTHER_KEY_PRESS_PER_KEY` are enabled, due to use of `get_hold_on_other_key_press` in `quantum/process_keycode/process_auto_shift.c`.
* Closes #18855
> Add missing prototype for get_hold_on_other_key_press to resolve #18855

- drivers/oled/oled_driver.h
- drivers/oled/ssd1306_sh1106.c
In response to <https://github.com/qmk/qmk_firmware/pull/18887#issuecomment-1312812389>.
*
> Add default limit to OLED dirty processing

- keyboards/annepro2/annepro2.c
The keyboard BT LEDs are no longer hard coded into the keyboard but will move according to the corresponding mapping of BT Key
*
> BT LEDs are no longer hard coded

- quantum/eeconfig.c
- quantum/eeconfig.h
Following from #18874, my use case required changes to the introduced functionality to be usable:
* The ability to check version number
* exposed indirectly to avoid users manually implementing checks
* The ability to init to non zero values
* `eeconfig_init_kb` _could_ be used however it would write twice
*
> Extend eeconfig kb/user datablock API

- keyboards/bastardkb/charybdis/3x5/v2/splinky/rules.mk
- keyboards/bastardkb/charybdis/3x6/v2/splinky/rules.mk
- keyboards/bastardkb/charybdis/4x6/v2/splinky/rules.mk
- keyboards/bastardkb/scylla/v2/splinky/rules.mk
- keyboards/bastardkb/skeletyl/v2/splinky/rules.mk
- keyboards/bastardkb/tbkmini/v2/splinky/rules.mk
QMK's `list-keyboards` infer a keyboard directory by looking for a `rules.mk` file. Because `v2/splinky/v2` and `v2/splinky/v3` share some `rules.mk` definition in `v2/splinky/rules.mk`, `multibuild` attempts to build them, which fails because `POINTING_DEVICE_CS_PIN` is only defined for the leaf folders.
This commit allows us to default to `v3` by specifying `DEFAULT_FOLDER` in `v2/splinky/rules.mk`
*
> Specify `DEFAULT_FOLDER` for `v2/splinky`

- keyboards/bastardkb/dilemma/dilemma.c
Instead of  the `_user(void)` variant that should be used at the keymap level.
*
> Use `keyboard_pre_init_kb(void)` at keyboard level

- quantum/mousekey.c
MouseKey "inertia" mode wasn't working on AVR.  This one-word change fixes it.
The AVR compiler seems to need an explicit cast during fixed-point multiply, or it'll overflow and cause some strange behavior.
* MouseKey "inertia" mode didn't work correctly on AVR.
> fixed MOUSEKEY_INERTIA on AVR

- docs/feature_pointing_device.md
- keyboards/ploopyco/mouse/mouse.c
- keyboards/ploopyco/trackball/trackball.c
- keyboards/ploopyco/trackball_mini/trackball_mini.c
- keyboards/ploopyco/trackball_thumb/trackball_thumb.c
Noticed some references to an unexisting type on the docs and replaced them by the actual one. It should also fix a (probably unreachable) branch of the ploopy's code
*
> Fix references to `mouse_report_t` (which doesnt exist)

- keyboards/annepro2/annepro2_ble.c
This change fixes the bluetooth multi-pairing issue.
The bluetooth broadcasting and connection functions in the annepro2_ble.c are incorrect, they do not handle the multi-pairing correctly.
The exiting broadcasting command (12 bytes in total) is the combination of the 11 bytes length machine code (which is stated in the array "ble_mcu_start_broadcast[11]") and the 1 byte length value (which is stated in the variable "port" - also known as the Broadcast ID) :
```
[              ble_mcu_start_broadcast (11 bytes)                 ] + [Broadcast ID 0-3 (1 byte)]
0x7b, 0x12, 0x53, 0x00, 0x03, 0x00, 0x00, 0x7d, 0x40, 0x01, 0x00,            0x00-0x03
```
However, with above command, the annepro2 keyboard is always broadcasting the "ID 0" whatever we change the Broadcast ID to any value.
The …
> [Keyboard] annepro2: fix bluetooth multi-pairing issue

- keyboards/ducky/one2sf/keymaps/default/keymap.c
One of the features of the Ducky One 2 SF is that it makes heavy use of it's function layer to provide additional functionality and alternate key mappings. This PR modifies the default keymap to make the default QMK function layer key mapping closer to that of the original firmware.
The main differences between the QMK fn layer mapping and the original mappings are the backlight controls and macro recording bindings as they don't map 1 to 1 with the QMK available key codes.
cc: @f7urry
> Ducky One 2 SF: Adjust fn layer mappings

- keyboards/sofle/keymaps/default/keymap.c
As per [docs](https://github.com/qmk/qmk_firmware/blob/master/docs/ref_functions.md#update_tri_layer_statestate-x-y-z) handling it in `process_record_user` is no longer necessary.
I don't own OLED version, so I'd like to ask the dear reviewer to verify if `print_status_narrow` still works properly after that change.
> Use modern solution for tri-layer in sofle default layout

- lib/python/qmk/cli/generate/api.py
* generic search to try and cover future additions
* somewhat aligned to existing metadata files
*
> Publish constants metadata to API

- keyboards/bastardkb/tbk/tbk.h
- lib/python/qmk/info.py
`bastardkb/tbk` was missing a `quantum.h` include.
`jels/boaty` has nothing wrong with it. The MCU is specified in info.json instead of rules.mk but the CLI is only looking specifically at the latter when trying to determine the protocol, leading to it falling back to `LUFA`. Since info.json `processor` is guaranteed to be present in order to call the appropriate `*_processor_rules()`, let's look at that instead. 
*
> Fix build failures for `bastardkb/tbk` and `jels/boaty`

- docs/feature_led_matrix.md
- keyboards/input_club/ergodox_infinity/ergodox_infinity.c
- keyboards/input_club/whitefox/whitefox.c
- quantum/led_matrix/led_matrix.c
To more accurately describe their function.
*
> Change `LED_MATRIX_STARTUP_*` defines to `LED_MATRIX_DEFAULT_*`

- util/install/fedora.sh
Fedora 37 has libusb1, with libusb0-compat stuff.
This just pulls out the install script deps to try both cases.
> Fixup installation procedure for different Fedora versions.

- quantum/keyboard.c
From the [insight of sigprof](https://github.com/qmk/qmk_firmware/pull/19140#issuecomment-1326155380) it was discovered that `encoder_init` initializes `thisCount` which is used in `encoder_state_raw` `memcpy`. `quantum_init` was calling `encoder_state_raw` though the initialization of `bootmatgic` calling `matrix_scan`. This caused undefined behavior resulting in bad values being sent over transport. Adjusting
the call order of `encoder_init` allows for correct behavior of `encoder_state_raw`
* https://github.com/qmk/qmk_firmware/issues/19139
> Fix encoder_init call order in keyboard_init

- util/udev/50-qmk.rules
Added a udev rule to give proper access to the Glorious GMMK 2 compact ANSI in bootloader mode on Linux.
Tested and it works correctly, it avoids having to manually chown the device file when flashing.
The vendor id and product id were extracted from lsusb with the keyboard in bootloader mode, here's the relevant output line:
```
Bus 005 Device 008: ID 342d:dfa0 Westberry Tech. WB Device in DFU Mode
```
* N/A
> Add udev rule for the WB32 DFU bootloader

- quantum/action_tapping.c
- tests/basic/test_tapping.cpp
"Retain momentary layers until the end of tapping" is my solution for Bug17281.
"Make process_tapping more readable" helped me understand the code better as I was investigating this problem. I'm including it for consideration. It's purely for readability and should have no impact on functionality. It is not needed to fix the bug.
* https://github.com/qmk/qmk_firmware/issues/17281
> Bug17281 - Retain momentary layers until the end of tapping

- .github/workflows/format.yml
- .github/workflows/lint.yml
Seems the old action isnt being updated, and suffers from
* `node 12` warnings
* `set-output` deprecated warnings
Initial testing seems the action behaves similar enough
*
> Update files changed action

- keyboards/keebio/sinc/rev1/config.h
- keyboards/keebio/sinc/rev2/config.h
Enable `SPLIT_LED_STATE_ENABLE` for Sinc Revs 1 & 2
This should fix the caps-lock LED state when the keyboard is connected via the "right" half.
The keyboard pre-dates the existence of that macro; prior to that point, it apparently used to be the default.
> Keeb.io Sinc: Enable Split LED state

- docs/feature_oled_driver.md
Little update to OLED documentation
It's a commong thing having people ask why their compiler didn't work.
The answer is that they copied the logo-drawing function from the documentation but they aren't using it anywhere.
Thus, i've added a clarification about it.
*
> Update OLED doc

- lib/python/qmk/cli/__init__.py
- lib/python/qmk/cli/migrate.py
```bash
$ qmk migrate -kb zvecr/split_blackpill -f VENDOR_ID -f PRODUCT_ID
Ψ Migrating keyboard zvecr/split_blackpill.
Ψ   Migrating file keyboards/zvecr/split_blackpill/config.h
Ψ     Migrating PRODUCT_ID...
Ψ     Migrating VENDOR_ID...
Ψ   Migrating file keyboards/zvecr/split_blackpill/rules.mk
Ψ   Updating keyboards/zvecr/split_blackpill/info.json
Ψ Migration of keyboard zvecr/split_blackpill complete!
Ψ Verify build with qmk compile -kb zvecr/split_blackpill -km default
```
Might be of use for the current USB config -> DD efforts.
> Automate "Data Driven" migrations?

- keyboards/bastardkb/charybdis/config.h
Missing "config_common.h" Isn't a critical error, but ... sure AF broke my songs. 😅
> [Keyboard] Fix config error for Charybdis

- keyboards/gmmk/pro/rev1/ansi/keymaps/andrebrait/rules.mk
Just changing my debounce type on my keymap and adding my reasoning there.
*
> [GMMK Pro][Keymap] Change DEBOUNCE_TYPE to sym_eager_pk to reduce latency

- keyboards/splitkb/aurora/lily58/keymaps/default/keymap.json
- keyboards/splitkb/aurora/sweep/keymaps/default/keymap.json
> Fix build failures for aurora/lily58 and sweep

- tmk_core/protocol/chibios/usb_driver.c
- tmk_core/protocol/chibios/usb_main.c
NKRO is forced to turn on by mistake when receiving HID_SET_PROTOCOL.
*
> Fixed NKRO issue caused by HID_SET_PROTOCOL on Chibios platform

- data/mappings/info_config.hjson
- data/schemas/keyboard.jsonschema
- docs/porting_your_keyboard_to_qmk.md
- quantum/matrix.c
Some optical switch designs use inverted logic for pressed state.
To invert the keypress logic, configure `matrix_pins.input_pressed_state` in info.json:
```json
"matrix_pins": {
"input_pressed_state": 1,
},
```
or, define `MATRIX_INPUT_PRESSED_STATE 1`  in config.h
*
> Core: Support inverted scan logic for optical switches

- keyboards/bioi/f60/readme.md
- keyboards/bobpad/readme.md
- keyboards/creatkeebs/glacier/readme.md
- keyboards/creatkeebs/thera/readme.md
- keyboards/handwired/axon/readme.md
- keyboards/handwired/swiftrax/digicarp65/readme.md
- keyboards/late9/readme.md
- keyboards/linworks/fave65h/readme.md
- keyboards/linworks/fave84h/readme.md
- keyboards/linworks/fave87h/readme.md
- keyboards/mechanickeys/miniashen40/readme.md
- keyboards/neopad/readme.md
- keyboards/pearlboards/atlas/readme.md
- keyboards/pearlboards/pandora/readme.md
- keyboards/pearlboards/pearl/readme.md
- keyboards/pearlboards/zeus/readme.md
- keyboards/pearlboards/zeuspad/readme.md
- keyboards/polycarbdiet/s20/readme.md
- keyboards/ramonimbao/mona/v1_1/readme.md
- keyboards/ramonimbao/mona/v32a/readme.md
- keyboards/ryanskidmore/rskeys100/readme.md
- keyboards/ryloo_studio/m0110/readme.md
- keyboards/studiokestra/bourgeau/readme.md
- keyboards/studiokestra/cascade/readme.md
- keyboards/studiokestra/galatea/readme.md
- keyboards/studiokestra/nue/readme.md
- keyboards/ydkb/just60/readme.md
During the rename of RESET to QK_BOOT (#18110) some Read Me files were changed while describing labels or function rather than keycode. This PR reverts the changes where needed.
> Revert RESET-> QK_BOOT in Read Me files where applicable

- keyboards/ymdk/ymd75/rev3/config.h
Hi. I have same problem like @williamcll in issue: https://github.com/qmk/qmk_firmware/issues/18639.
My keyboards is Rev3 detected as:
```
idVendor           0x20a0 Clay Logic
idProduct          0x422d 
bcdDevice            3.00
iManufacturer           1 YMDK
iProduct                2 YMD75 / MT84
```
* https://github.com/qmk/qmk_firmware/issues/18639
> [Keyboard] Fix CapsLock pin for ymdk/ymd75/rev3

- platforms/chibios/boards/PJRC_TEENSY_3_6/board/board.mk
- platforms/chibios/boards/PJRC_TEENSY_3_6/board/extra.c
Without this change, the Teensy 3.6 kinT variant can wake a computer from Suspend-to-RAM, but the keyboard does not actually produce any keypresses until you un-plug and re-plug it.
related to https://github.com/kinx-project/kint/issues/59
related to https://github.com/qmk/qmk_firmware/issues/16934
* https://github.com/qmk/qmk_firmware/issues/16934
> kint36: do not restart USB stack after wakeup

- docs/porting_your_keyboard_to_qmk.md
- docs/reference_info_json.md
* avoid overwhelming users in porting guide
* bad header level
* not covered in info.json docs
*
> Rework input_pressed_state docs

- platforms/chibios/boards/PJRC_TEENSY_3_5/board/board.mk
- platforms/chibios/boards/PJRC_TEENSY_3_5/board/extra.c
> Teensy 3.5: do not restart USB stack after wakeup

- layouts/default/ortho_4x6/default_ortho_4x6/keymap.c
Fix keycode that wasn't updated correctly for the default Ortho4x6 layout
> Update KC_BKSP->KCBSPC for default Ortho4x6 layout

- drivers/sensors/pmw3389.c
Just removing the `extern constant pmw33xx_number_of_sensors` definition as it is not needed anymore as `pmw33xx_number_of_sensors`  is now a macro defined in `pmw33xx_common.h`  This was done for the PMW3360 sensor but the PMW3389 sensor was missed.
*  PMW3389 based pointing devices would fail to compile
> Fixing PMW3389.c so it can compile

- tests/caps_word/test_caps_word.cpp
Add tests that tapping or holding a OSL keeps caps word active and shifts keys on the layer that need to be shifted.
These tests address issue #18136.
*
> Tests that caps word stays active after use of OSL

- docs/feature_unicode.md
- quantum/process_keycode/process_ucis.c
- quantum/process_keycode/process_ucis.h
- users/uqs/uqs.c
Doesn't really match the general naming convention.
Also to do: leader key and... tap dance.
*
> UCIS: remove `qk_` prefix

- docs/feature_led_indicators.md
- docs/hardware_keyboard_guidelines.md
- docs/ja/feature_led_indicators.md
- docs/ja/hardware_keyboard_guidelines.md
- keyboards/bpiphany/kitten_paw/keymaps/ickerwx/keymap.c
- keyboards/converter/usb_usb/custom_matrix.cpp
- keyboards/duck/octagon/v1/v1.c
- keyboards/duck/octagon/v2/v2.c
- keyboards/duck/tcv3/tcv3.c
- keyboards/exclusive/e6v2/oe/oe.c
- keyboards/sirius/unigo66/custom_matrix.cpp
- layouts/community/ortho_4x12/wanleg/readme.md
- quantum/led.c
- quantum/led.h
Remove `led_set_kb` maintaining existing `led_set_user` behaviour.
Future passes will start to refactor `led_set_user` to `led_update_user`.
*
> Remove deprecated led_set_kb

- docs/feature_tap_dance.md
- docs/ja/feature_tap_dance.md
Just noticed a broken link while reading Tap Dance's documentation. Removed it
I don't speak japanese, so i may have do it wrong on that translation, chinese didn't have a Tap Dance file.
*
> [Docs] Remove broken link

- builddefs/mcu_selection.mk
Should hopefully alleviate Configurator until next cycle when we pick up the fixed ChibiOS.
* [qmk/qmk_configurator#1228](https://github.com/qmk/qmk_configurator/issues/1228)
> Revert to legacy wear-leveling driver by default for F401.

- .github/workflows/auto_tag.yml
> Add builddefs to the paths associated with tagging.

- quantum/rgblight/rgblight.c
Fix non-functional RGBLIGHT_EFFECT_TWINKLE on ARM (Issue #15345).
Also, a slight efficiency improvement.
* #15345
> Fix non-functional RGBLIGHT_EFFECT_TWINKLE on ARM

- docs/ChangeLog/20230226/PR17007.md
> Change log for Quick Tap Term

- quantum/action.c
- quantum/action_tapping.c
- quantum/keyboard.h
Just a small readability improvement.
*
> [Core] use `IS_EVENT` macro instead of `!IS_NOEVENT`

- tests/auto_shift/test_auto_shift.cpp
- tests/autocorrect/test_autocorrect.cpp
- tests/basic/test_action_layer.cpp
- tests/basic/test_keypress.cpp
- tests/basic/test_one_shot_keys.cpp
- tests/basic/test_tapping.cpp
- tests/caps_word/caps_word_autoshift/test_caps_word_autoshift.cpp
- tests/caps_word/caps_word_combo/test_caps_word_combo.cpp
- tests/caps_word/caps_word_unicodemap/test_caps_word_unicodemap.cpp
- tests/caps_word/test_caps_word.cpp
- tests/secure/test_secure.cpp
- tests/tap_hold_configurations/default_mod_tap/test_tap_hold.cpp
- tests/tap_hold_configurations/hold_on_other_key_press/test_tap_hold.cpp
- tests/tap_hold_configurations/permissive_hold/test_one_shot_keys.cpp
- tests/tap_hold_configurations/permissive_hold/test_tap_hold.cpp
- tests/tap_hold_configurations/quick_tap/test_action_layer.cpp
- tests/tap_hold_configurations/quick_tap/test_quick_tap.cpp
- tests/tap_hold_configurations/retro_tapping/test_tap_hold.cpp
- tests/tap_hold_configurations/retro_tapping/test_tapping.cpp
- tests/test_common/test_driver.hpp
- tests/test_common/test_fixture.cpp
Which is just a syntactic sugar for `testing::Mock::VerifyAndClearExpectations` to reduce the visual clutter in unit-tests.
*
> [Test] Introduce VERIFY_AND_CLEAR shorthand

- docs/feature_rgblight.md
[fix description for selectively disabling animations](https://docs.qmk.fm/#/feature_rgblight?id=example-usage-to-reduce-memory-footprint)
[fix description for selectively disabling animations](https://docs.qmk.fm/#/feature_rgblight?id=example-usage-to-reduce-memory-footprint)
> Fix description for selectively disabling animations

- lib/python/qmk/cli/generate/rgb_breathe_table.py
- quantum/rgblight/rgblight_breathe_table.h
* add "generated" header comments
* use generic write function
*
> Minor alignment of rgb_breathe_table generator

- lib/python/qmk/cli/new/keyboard.py
As title. Otherwise, the user will input various other info before an error is raised.
> Validate keyboard name before accepting further input

- keyboards/splitkb/aurora/lily58/lily58.c
Fix Aurora Lily58 default encoder behaviour.
The Aurora Lily58 has *one* encoder per half, not two. The previous behaviour made both left and right encoders act like volume control. This was unintended: the right half is supposed to be PgUp / PgDown.
N/A, mentioned on the splitkb.com Discord by casuanoob#0425
> Fix Aurora Lily58 default encoder behaviour

- quantum/rgb_matrix/animations/pixel_flow_anim.h
- quantum/rgb_matrix/animations/pixel_rain_anim.h
- quantum/rgb_matrix/animations/raindrops_anim.h
De-obfuscate random8 functions for
* Modulo of LED count
* Limiting saturation between 127 and 255.
> De-obfuscate random8 functions

- quantum/rgb_matrix/animations/solid_reactive_anim.h
- quantum/rgb_matrix/animations/solid_reactive_cross.h
- quantum/rgb_matrix/animations/solid_reactive_nexus.h
- quantum/rgb_matrix/animations/solid_reactive_simple_anim.h
- quantum/rgb_matrix/animations/solid_reactive_wide.h
* Gradient changes is more obvious with this timer scale at both ends of effect speed
* Use `qadd8` to cap speed upper limit
* Fix gradient implementation for reactive nexus effect
> Update RGB matrix reactive gradient timer scale

- keyboards/splitkb/aurora/corne/keymaps/x123/config.h
- keyboards/splitkb/aurora/corne/keymaps/x123/keymap.c
- keyboards/splitkb/aurora/corne/keymaps/x123/readme.md
- keyboards/splitkb/aurora/corne/keymaps/x123/rules.mk
add x123 keymap for splitkb/aurora/corne
This keymap is based on many concepts from Dreymar's big bag theory (see https://dreymar.colemak.org/index.html), tweaked a bit for my own preferences and adopted to the Aurora Corne. The readme provides further details and images of the layout.
> add x123 keymap for splitkb/aurora/corne

- keyboards/ploopyco/trackball_mini/trackball_mini.c
The encoder derives scroll direction based on the last known wheel position, as such it needs up-to-date wheel state at all times to compute the right direction.
When using `opt_encoder_simple.c` as the implementation, the default delay may cause the encoder to see "impossible" states (which requires recalibration) or states that imply an opposite direction to the actual scrolling direction. This is very evident when the wheel is free-spinning.
This commit reorders the code to make sure the optical encoder state is always updated, but only apply scrolling when specified conditions are met (ie. after debounce period, middle mouse released, etc.).
Tested with `opt_encoder_simple.c`, where a free-spinning wheel now generates very smooth scrolling with no apparent glitches. This has not been …
> ploopyco/trackball_mini: always update encoder

- docs/feature_encoders.md
Documentations do not mention that in order to modify encoder resolution, the half that has the encoder also needs to be reflashed, not only the master half.
In hindsight this is obvious and submitting this PR feels a bit like accepting my own stupidity, but... Well, it might save other dim fellows the couple hours of research and debugging I went through 🤦🏻‍♀️ 
*
> docs: add a note about reflashing both halves for encoder resolution

- keyboards/horrortroll/handwired_k552/config.h
- keyboards/horrortroll/handwired_k552/rules.mk
`STM32F103xC_stm32duino_bootloader.ld` doesn't exist. I presume the linker script in the keyboard directory is what's meant to be used.
cc @HorrorTroll
> Fixup horrortroll/handwired_k552

- docs/feature_unicode.md
If the previous example was used the incorrect codepoints are produced. 
Changes the order of arguments the declaration of the unicode_map
> Fixes unicode_map declaration example

- lib/python/qmk/flashers.py
```bash
qmk flash ~/Downloads/drop_sense75_default.bin 
Flashing binary firmware...
Please reset your keyboard into bootloader mode now!
Press Ctrl-C to exit.
dfu-util 0.11
Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
dfu-util: Could not open file drop_sense75_default.bin for reading: No such file or directory
```
*
> CLI flashers should allow files outside qmk_firmware folder

- keyboards/ploopyco/trackball_thumb/rev1_001/config.h
- keyboards/ploopyco/trackball_thumb/trackball_thumb.c
> Partially revert #18940 for Ploopy Thumb Trackball

- lib/python/qmk/cli/flash.py
- lib/python/qmk/flashers.py
Includes some minor updates to align `flash.py` with `compile.py`.
*
> Allow CLI to flash .uf2 files

- keyboards/beekeeb/piantor/info.json
- keyboards/beekeeb/piantor/rules.mk
Piantor is a split_3x6_3 as defined in info.json. Add the layout to community layouts so we can take advantage of layouts with a common implementation (e.g. manna-harbour_miryoku).
> Add common layout to Piantor

- lib/python/qmk/json_schema.py
- lib/python/qmk/keycodes.py
`keycodes_0.0.2_quantum.hjson` could contain the following to ignore any existing keycodes
```json
{
"keycodes": {
"!reset!":0,
"0x7C00": {
"group": "quantum",
"key": "QK_BOOTLOADER",
"aliases": [
"QK_BOOT"
]
},
}
}
```
Likewise `keycodes_0.0.2.hjson` could contain the following to ignore any existing ranges
```json
{
"ranges": {
"!reset!":0,
"0x0000/0x00FF": {
"define": "QK_BASIC"
},
}
}
```
*
> Implement XAP style merge semantics for DD keycodes

- quantum/action.c
- tests/tap_hold_configurations/default_mod_tap/test_one_shot_layer.cpp
This proposal allows mod-tap hold action on one shot layer. One shot layer is immediately disabled if `MT()` is pressed and therefore mod-tap hold is not possible.
Following example currently produce a lower case character `x`.
```
[L1] = LAYOUT(KC_X, OSL(L2))
[L2] = LAYOUT(KC_A, LSFT_T(...))
```
- on layer 1
- `OSL(L2)` down
- `OSL(L2)` up
- on layer 2
- `LSFT_T(...)` down
- `KC_A` down
- `KC_A` up
- `LSFT_T(...)` up
With the proposed change the result is a upper case `A` and it will behave same as `KC_LSFT`.
I'm not aware if this covers all possible situations, but I've tested it for several months with no problems.
> Allow mod-tap hold action on one shot layer

- lib/python/qmk/cli/doctor/check.py
- lib/python/qmk/cli/doctor/main.py
- lib/python/qmk/submodules.py
```
[zvecr@zvecr-zen qmk_firmware-master]$ qmk doctor
...
⚠ QMK home does not appear to be a Git repository! (no .git folder)
...
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ QMK is ready to go, but minor problems were found
```
Slightly misleading saying everything is ready...
Now the output is,
```
[zvecr@zvecr-zen qmk_firmware-master]$ qmk doctor
...
⚠ QMK home does not appear to be a Git repository! (no .git folder)
...
Ψ Submodule status:
☒ - lib/chibios: <<< missing or unknown >>>
☒ - lib/chibios-contrib: <<< missing or unknown >>>
☒ - lib/googletest: <<< missing or unknown >>>
☒ - lib/lufa: <<< missing or unknown >>>
☒ - lib/vusb: <<< missing or unknown >>>
☒ - lib/printf: <<< missing or unknown >>>
☒ - lib/pico-sdk: <<< missing or unknown >>>
Ψ Major problems detected, …
```
> Report submodule status when not valid work-tree

- Makefile
- builddefs/message.mk
- lib/python/qmk/cli/__init__.py
- lib/python/qmk/cli/git/submodule.py
Will remove the need for users to manually `cd` to the qmk_firmware folder, frequently a missed step.
`make` targets still exist to maintain existing compatibility.
> Migrate 'make git-submodule' to CLI command

- Makefile
- builddefs/message.mk
When trying to build via zip, the usual error is `⚠ "git describe --abbrev=6 --dirty --always --tags" returned error code 128` which isnt the most descriptive. This updates to produce the following:
```
$ make clean kprepublic/jj4x4:default
WARNING: Target folder is not a git repo.
Please consider following https://docs.qmk.fm/#/newbs_getting_started.
```
*
> Build warning when not valid work-tree

- Makefile
- lib/python/qmk/cli/list/keyboards.py
- lib/python/qmk/keyboard.py
- util/list_keyboards.sh
Short term, this maintains existing behaviour through a bleh flag.
*
> Replace list_keyboards.sh with CLI calls

- docs/chibios_upgrade_instructions.md
- lib/python/qmk/cli/__init__.py
- lib/python/qmk/cli/mass_compile.py
Adds `qmk mass-compile` -- an intended replacement for `qmk multibuild` that has support for data-driven filtering.
Needed to add multithreading support for processing all the info.json-like files, initial startup can be a bit slow.
Also adds support for `-km all` in order to try to cater for #15843.
Once this gets in, CI will be modified to use this instead, and `qmk multibuild` removed shortly thereafter.
Example:
```
% qmk mass-compile -j 41 -f features.rgblight=true -f features.rgb_matrix=true
Ψ Retrieving list of keyboards with keymap "default"...
Ψ Parsing data for all matching keyboard/keymap combinations...
Ψ Filtering on condition ("features.rgblight" == "true")...
Ψ Filtering on condition ("features.rgb_matrix" == "true")...
Build canary/canary60rgb/v1:default …
```
> Add `qmk mass-compile`.

- keyboards/peej/lumberjack/lumberjack.c
LED1 is activated by keypress and then deactivated by the layer change code. This causes LED1 to flash momentarily.
This PR removed the deactivation of LED1 on layer change so that it stays on and does not flash.
*
> [Keyboard] Stop LED1 from flashing on layer change

- lib/python/qmk/cli/generate/config_h.py
The code which generated the `MATRIX_COLS` and `MATRIX_ROWS` defines from the JSON information was checking the presence of the `matrix_pins` key, which may not exist if a custom matrix is used.  Check the presence of `matrix_size` instead.
> Fix MATRIX_COLS and MATRIX_ROWS generation for custom matrix

- Makefile
- lib/python/qmk/cli/git/submodule.py
Currently avoids using `submodule.update` as updating the code to work in existing cases and the submodule command is rather messy. Longer term, this will be resolved. 
*
> Migrate submodule dirty check to CLI

- keyboards/handwired/onekey/blackpill_f401_tinyuf2/info.json
- keyboards/handwired/onekey/blackpill_f411_tinyuf2/info.json
- lib/python/qmk/info.py
```json
{
"development_board": "blackpill_f401",
"bootloader": "tinyuf2"
}
```
Previously, this would have resulted in bootloader being overwritten to `stm-dfu`.
*
> Ignore defaults.hjson values if already set

- data/mappings/defaults.hjson
> Remove invalid pin_compatible config from defaults

- lib/python/qmk/cli/doctor/check.py
- lib/python/qmk/cli/doctor/main.py
* <https://discord.com/channels/440868230475677696/869749041074937936/1060561775604535397>
> `qmk doctor` - Handle timeouts while checking binaries

- quantum/via.c
VIA uses RGBLIGHT functions in the RGB Matrix section.  Normally, this is okay, but if you have both features enabled .... not so much.  So, naturally, I run into this.
> [Bug] Use correct functions for RGB Matrix support in VIA

- keyboards/keychron/s1/ansi/rgb/info.json
- keyboards/keychron/s1/ansi/rgb/keymaps/default/keymap.c
- keyboards/keychron/s1/ansi/rgb/keymaps/keychron/keymap.c
- keyboards/keychron/s1/ansi/rgb/keymaps/via/keymap.c
- keyboards/keychron/s1/ansi/white/info.json
- keyboards/keychron/s1/ansi/white/keymaps/default/keymap.c
- keyboards/keychron/s1/ansi/white/keymaps/keychron/keymap.c
- keyboards/keychron/s1/ansi/white/keymaps/via/keymap.c
Renames the layout macros for both versions to `LAYOUT_75_ansi` and enables Community Layout support. First in a series.
cc @lalalademaxiya1 (keyboard maintainer)
> Keychron S1 ANSI Layout Touch-Up

- lib/python/qmk/cli/generate/api.py
- lib/python/qmk/info.py
- lib/python/qmk/keymap.py
Short term fix with some lazy imports to avoid circular includes. Fixing this more correctly will require significant code reshuffles. Ignoring whitespace somewhat helps due to some indentation changes.
Fixes issues:
* only checking `LAYOUTS` in rule.mk and not also `community_layouts` in info.json
* only checking `layouts/community` and not also `layouts/default`
* Recent CLI test failures post merge of #19541
> Fix CLI community detection

- builddefs/build_keyboard.mk
- data/mappings/info_rules.hjson
- lib/python/qmk/info.py
- platforms/arm_atsam/bootloader.mk
- platforms/avr/bootloader.mk
- platforms/chibios/bootloader.mk
- platforms/chibios/platform.mk
Reverts qmk/qmk_firmware#19545 mainly due to converters now being broken
> Revert "De-duplicate platform detection"

- keyboards/ckeys/handwire_101/readme.md
- keyboards/keebio/bdn9/keymaps/codecoffeecode/rules.mk
- keyboards/kingly_keys/little_foot/keymaps/yanfali/rules.mk
- keyboards/montsinger/rebound/rev1/keymaps/curry/rules.mk
- keyboards/shapeshifter4060/keymaps/debug/readme.md
- keyboards/shapeshifter4060/readme.md
- layouts/community/split_3x6_3/drashna/rules.mk
- users/brandonschlack/process_records.c
- users/ericgebhart/rules.mk
Should make #19565 clean, and generally should be done anyway from the previous deprecation cycle.
*
> Tidy up use of CTPC

- builddefs/converters.mk
Previous cycle warn, this cycle error, next remove.
*
> Promote CTPC warning to error

- docs/platformdev_blackpill_f4x1.md
- keyboards/handwired/dactyl_manuform/6x6/readme.md
- keyboards/handwired/dygma/raise/readme.md
- keyboards/handwired/tractyl_manuform/5x6_right/f303/readme.md
- keyboards/handwired/tractyl_manuform/5x6_right/f411/readme.md
Amend blackpill docs to remove supposed security vulnerability link
*
> weact docs patch re "security vulnerability"

- docs/documentation_templates.md
- docs/porting_your_keyboard_to_qmk.md
* Fix a couple links
* Update suggested keyboard `readme`
> Touch up documentation templates & porting keyboards docs

- keyboards/handwired/acacia/acacia.c
- keyboards/handwired/acacia/acacia.h
- keyboards/handwired/acacia/config.h
- keyboards/handwired/acacia/info.json
- keyboards/handwired/acacia/keymaps/default/keymap.c
- keyboards/handwired/acacia/readme.md
- keyboards/handwired/acacia/rules.mk
New custom 42 key keyboard, with link to all source files to build it.
> Acacia keyboard

- keyboards/bluebell/swoop/rules.mk
People setting up their device on the web configurator are unable to use RGB if it's not enabled by default.
*
> [bluebell/Swoop] Enable RGB underlight by default

- docs/quantum_painter.md
- drivers/painter/gc9a01/qp_gc9a01.c
- drivers/painter/generic/qp_rgb565_surface.c
- drivers/painter/ili9xxx/qp_ili9163.c
- drivers/painter/ili9xxx/qp_ili9341.c
- drivers/painter/ili9xxx/qp_ili9488.c
- drivers/painter/ssd1351/qp_ssd1351.c
- drivers/painter/st77xx/qp_st7735.c
- drivers/painter/st77xx/qp_st7789.c
- drivers/painter/tft_panel/qp_tft_panel.c
- drivers/painter/tft_panel/qp_tft_panel.h
- lib/python/qmk/painter.py
- quantum/painter/qgf.c
- quantum/painter/qp.c
- quantum/painter/qp.h
- quantum/painter/qp_draw.h
- quantum/painter/qp_draw_codec.c
- quantum/painter/qp_draw_image.c
- quantum/painter/qp_draw_text.c
- quantum/painter/qp_internal_driver.h
- quantum/painter/qp_internal_formats.h
This pull request adds native color support (RGB565 and RGB888) to Quantum Painter.
Currently QP only provides support for images and animations with a palette of up to 256 colors. This addition provides for image generation and storage without using palettes, and instead uses the native file format of the display. For RGB565 displays, this makes images take up about 2x the memory compared to using a 256 color palette (since two bytes are used per pixel instead of one byte), and for RGB888 displays, it takes up 3x the memory (since three bytes are used per pixel instead of one byte).
An overriding goal of this implementation was to make handling of native color images no different than that of palette-based images. That is, the keyboard developer does not need to (for example) write …
> Add RGB565 and RGB888 color support to Quantum Painter

- keyboards/preonic/keymaps/brauner/keymap.c
* Ease stress on the thumbs by moving the lower/space and raise layer keys closer together. The layer/space keys are more important and way more frequently accessed than the compositor layer keys.
* Toggle the mouse layer via a leader sequence. This requires more intent and makes it less likely to accidently activate the mouse layer.
Signed-off-by: Christian Brauner (Microsoft) <brauner@kernel.org>
> [Keymap] Update brauner preonic layout

- tmk_core/protocol/chibios/usb_main.c
No longer needed as ChibiOS kernel version is 7 on both master and develop.
*
> usb_main.c: remove `CH_KERNEL_MAJOR` check

- tmk_core/protocol/chibios/usb_main.c
The code for the joystick feature failed to build on ChibiOS, because the old `joystick_report_t` type name was used instead of `report_joystick_t`.  Apparently the code in #14814 was written before #19052, but has been merged after that PR without updating.
The master branch is not affected — the offending code is only in develop.
> Fix joystick build for ChibiOS

- docs/feature_joystick.md
In #19052 the define was renamed from `JOYSTICK_AXES_COUNT` to `JOYSTICK_AXIS_COUNT`, but some usages of the old name in docs were missed.
> Fix `JOYSTICK_AXIS_COUNT` name in docs

- tmk_core/protocol/chibios/usb_main.c
Similar to #18629, refactoring report sending into a more generic, reusable function.
*
> ChibiOS: Consolidate report sending code

- quantum/rgb_matrix/animations/pixel_rain_anim.h
- Remove redundant "params" pointer
- Use descriptive "led_index" variable
- Place random on/off boolean within "if" statement
> Refactor rain pixel function

- quantum/quantum.c
This is a leftover from #17935. I kept the velocikey updates next to the wpm updates since they are similar in spirit.
Moving the tap dance preprocessing up ensures that WPM is calculated for the correct keycode, since the code can change as a result of tap dance preprocessing.
* WPM is now computed for the correct keycode, also in the case of an interrupted tap dance that altered the keycode using layers.
There is no serious bug here, this change is mainly for being 'correct'.
> Use the correct keycode when updating WPM

- docs/feature_leader_key.md
Explicitly mention the need for `LEADER_EXTERNS()` macro.
> Highlight extern macro usage

- lib/python/qmk/cli/mass_compile.py
Adds the ability to use filename-style wildcards to `qmk mass-compile`'s filter values.
e.g.
```sh
qmk mass-compile -j 4 -f 'processor=STM32F4*' # Builds F401, F405, F407, F411, F446, etc.
```
> Allow for wildcard filtering in `qmk mass-compile`

- builddefs/mcu_selection.mk
- docs/flashing.md
- platforms/chibios/boards/common/ld/STM32F303xC_tinyuf2.ld
> Add f303 to tinyuf2 bootloader support

- builddefs/converters.mk
- platforms/chibios/converters/promicro_to_bonsai_c3/pre_converter.mk
Longer term, #19533 will explore "better" and more complete solutions. For now this avoids things like symlinks, and is fairly trivial to unpick if/when we select a different solution.
*
> Add alias support for converters

- keyboards/tzarc/ghoul/rev1/rp2040/config.h
- keyboards/tzarc/ghoul/rev1/rp2040/halconf.h
- keyboards/tzarc/ghoul/rev1/rp2040/mcuconf.h
- keyboards/tzarc/ghoul/rev1/stm32/rules.mk
- keyboards/tzarc/ghoul/rules.mk
> Add support for current/voltage measurement on Ghoul.

- lib/python/qmk/cli/compile.py
- lib/python/qmk/cli/flash.py
Avoids,
```
$ qmk compile -kb keychron/q1/ansi_encoder -km ~/Downloads/zed.json 
Ψ Compiling keymap with make --jobs=1 keychron/q1/ansi_encoder:/home/zvecr/Downloads/zed.json
QMK Firmware 0.19.6
Making keychron/q1/ansi_encoder with keymap default and target /home/zvecr/Downloads/zed.json  [OK]
Making keychron/q1/ansi_encoder with keymap keychron and target /home/zvecr/Downloads/zed.json [OK]
Making keychron/q1/ansi_encoder with keymap via and target /home/zvecr/Downloads/zed.json      [OK]
```
* <https://discord.com/channels/440868230475677696/473506116718952450/1061331426286522399>
> `qmk compile`/`qmk flash` - Validate keymap argument

- builddefs/build_keyboard.mk
- builddefs/converters.mk
- data/mappings/info_rules.hjson
- lib/python/qmk/info.py
- platforms/arm_atsam/bootloader.mk
- platforms/avr/bootloader.mk
- platforms/chibios/bootloader.mk
- platforms/chibios/platform.mk
Attempt 2 after #19545 caused converters to fail.
Avoids logic being in 2 different places, and reducing issues when a new platform is introduced. 
`info.json` having "platform" already being used for another value, with a somewhat meaningless value, is a shame. That could be reworked at a later date. Ive added to 16598 to cover the case where `qmk info -f json -kb <keyboard> -km <keymap_with_convert_to>` shows pre-converted info (incorrect mcu/bootloader/protocol/etc)
*
> De-duplicate platform detection

- data/schemas/keyboard.jsonschema
- lib/python/qmk/info.py
19539 covers most of the failures. Remaining issues:
```
☒ dailycraft/stickey4: No LAYOUTs defined! Need at least one layout defined in info.json.
encoder meh
☒ mwstudio/alicekk: No LAYOUTs defined! Need at least one layout defined in info.json.
low quality image
```
*
> Fix 'Need at least one layout defined in info.json' check

- lib/python/qmk/cli/doctor/check.py
- lib/python/qmk/cli/doctor/linux.py
- lib/python/qmk/cli/doctor/windows.py
Linux
```
Ψ CLI version: 1.1.1
Ψ QMK home: /home/zvecr/qmk_firmware
Ψ Detected Linux (Manjaro Linux).
```
WSL
```
Ψ CLI version: 1.1.1
Ψ QMK home: /home/qmk/qmk_firmware
Ψ Detected Linux (WSL, Debian GNU/Linux 11 (bullseye)).
```
Msys
```
Ψ CLI version: 1.1.1
Ψ QMK home: C:/Users/zvecr/qmk_firmware
Ψ Detected Windows 10 (10.0.22000).
Ψ QMK MSYS version: 1.7.2
```
*
> Print distro in doctor output

- docs/platformdev_blackpill_f4x1.md
> Docs: typo fixes in platformdev_blackpill_f4x1.md

- builddefs/converters.mk
Was trying to handle the case where `PLATFORM_PATH` has parents, but for now its easier to handle folders not having trailing slashes? Most of this logic should go with the move to DD converters anyway.
*
> Fix converter alias after 19603

- lib/python/qmk/cli/generate/api.py
As `json` so that qmk_api_tasks can grab that file instead?
Also aligns file encoding, and indentation.
*
> Publish keymap.json to API

- docs/uart_driver.md
- platforms/chibios/drivers/uart.c
- platforms/chibios/drivers/uart.h
UART driver for ChibiOS was not working on ARM (testing using STM32F411), it looks like it just didn't follow along with changes in the serial driver as far as how to correctly assign pin modes with palSetLineMode. With these changes, it now works as expected.
I also took the opportunity to refactor some naming to make it more generic (SD instead of SD1) and updated documentation accordingly. A search of the repo showed that no one was actually using the original SD1 naming yet.
*
> Corrections to uart driver for Chibios platform

- platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c
- platforms/chibios/vendors/RP/RP2040.mk
The current implementation could be deadlocked if the last update was more then ~35min ago. This is due to the time resolution for the RP2040 on ChibiOS being 32bit and the counter running at 1MHz and `timer_expired32()` only handling timer intervals up to `(UINT32_MAX / 2)`. This can easily happen if the keyboard is put to sleep or the RGB being disabled for this time.
The solution is to use the full 64bit time resolution of the RP2040 which wraps after ~584942 years - let me know if you happen to witness this. Unfortunately we have fallback to the pico-sdk implementation as there is no 64bit timer resolution support in the ChibiOS implementation of the RP2040.
* #19600 (?)
* #18591 (?)
> [Bug] rp2040: fix timer wrap deadlock in ws2812 vendor driver

- keyboards/handwired/jscotto/scotto40/keymaps/default/keymap.c
Remove `qk_` tapdance prefixes.
> Fixup handwired/jscotto/scotto40

- keyboards/splitkb/kyria/keymaps/via/keymap.c
- keyboards/splitkb/kyria/keymaps/via/rules.mk
* Replace custom encoder code with encoder map (and remove `LAYOUT_via` as it doesn't play nicely with DD configuration as used in `splitkb/kyria/rev3/info.json`)
* Remove OLED code that already exists at keyboard level
* Disable rgblight, as `rev1/2` already enable it by default, and `rev3` uses RGB matrix.
> Fixup splitkb/kyria VIA keymap

- keyboards/annepro2/config_led.h
The current value `RGB_MATRIX_LED_FLUSH_LIMIT 16` causes noticeable input latency when animated RGB profiles are activated. The latency goes away as soon as the RGB is switched off.
This issue was introduced after refactoring in
https://github.com/qmk/qmk_firmware/pull/18640
There are multiple reports in OpenAnnePro 2 discord channel about this issue.
Maybe a proper fix will be refactoring the logic and adjusting the frequency of UART communication. This is a quick fix to make the keyboard usable with RGB enabled.
- [x ] Enhancement/optimization
* AnnePro2 input latency is improved when animated RGB profiles are enabled
> Decrease LED animation frequency to improve performance

- platforms/chibios/drivers/analog.c
The `adc_read()` code for STM32F0xx expects to get the 0-based channel number in `mux.input`, but the `pinToMux()` code for STM32F0xx was attempting to pass the CHSELR bit mask in that field, which resulted in selecting a wrong channel, therefore `analogReadPin()` did not work properly for the STM32F0xx chips.  Fix `pinToMux()` to put the channel number in that field (this matches the behavior for other supported chips and also allows selection of channels 16...18, which can be used to access the builtin temperature, reference voltage and VBAT sensors).
(It could be possible to fix this in a different way — by doing `adcConversionGroup.chselr = mux.input` in `adc_read()` and continuing to put the bit mask into `mux.input`; however, it would break things for people who may be working …
> analog.c: Fix `pinToMux()` for STM32F0xx

- keyboards/nullbitsco/scramble/rules.mk
- keyboards/nullbitsco/scramble/scramble.h
- keyboards/nullbitsco/scramble/v1/config.h
- keyboards/nullbitsco/scramble/v1/rules.mk
- keyboards/nullbitsco/scramble/v1/v1.c
- keyboards/nullbitsco/scramble/v1/v1.h
- keyboards/nullbitsco/scramble/v2/config.h
- keyboards/nullbitsco/scramble/v2/halconf.h
- keyboards/nullbitsco/scramble/v2/mcuconf.h
- keyboards/nullbitsco/scramble/v2/rules.mk
- keyboards/nullbitsco/scramble/v2/v2.c
- keyboards/nullbitsco/scramble/v2/v2.h
Add the new RP2040-based SCRAMBLE, along with HW PWM RGB LED control. No keymap changes or updates. Tested on final SCRAMBLE v2 hardware. 
*
> Add RP2040 SCRAMBLE v2

- keyboards/mode/m80v2/config.h
User in discord reported that CAPS lock Led state was inverted after soldering a LED to their board.
LED_PIN_ON_STATE defaults to 1, so just swap it 0 to invert the logic,
User has Flashed board and now CAPS LED reflects the actual state.
* 
> Fix Mode80V2 Caps Lock LED being inverted.

- docs/feature_split_keyboard.md
* Improve bootloader parameter clarity with a table
* Add explicit examples for `qmk flash` commands
> Additional handedness by EEPROM examples

- platforms/atomic_util.h
- platforms/chibios/atomic_util.h
- quantum/ring_buffer.h
While using ring_buffer for the RIOT port, noticed it was effectively AVR only. AVR only code should really not exist within the `quantum` folder.
The minimum change to get RIOT working would be the `#include <util/atomic.h>` to `#include "atomic_util.h"` part, but i've attempted to align the missing ChibiOS functionality. If there are concerns on the additional changes, I can stage them as a separate PR.
*
> Fix quantum ring_buffer for ChibiOS

- docs/feature_autocorrect.md
- lib/python/qmk/cli/generate/autocorrect_data.py
Aligns this CLI command more closely with other generators; using `dump_lines` and adding the standard headings.
Also fixed an issue where the input filename was not normalised to the CWD, resulting in the CLI searching for the file in the qmk_firmware root.
*
> Clean up `qmk generate-autocorrect-data`

- keyboards/baion_808/config.h
- keyboards/nullbitsco/scramble/v2/config.h
- quantum/config_common.h
- quantum/quantum.h
I've left the header for the time being, just so any keyboard PRs that skip through do not completely fail.
*
> Strip out more of config_common

- layouts/community/ergodox/zweihander-macos/keymap.c
- layouts/community/ergodox/zweihander-macos/readme.markdown
This updates the Zweihander layout for the Ergodox EZ:
- changes the power and scroll-lock keys' names to currently-supported versions
- replaces the `'` key on the left-hand thumb with a caps-lock key (intended to be used as an `fn` key)
* (none)
> zweihander-macos: Update keys, add capslock

- quantum/painter/lvgl/qp_lvgl.c
Small correction for the LVGL bindings when attaching a display.  
When setting up the LVGL display driver it took the original display width and height without taking in consideration the rotation and offsets
For example, if the display is 240x320 and the display was rotated using `qp_init(display, QP_ROTATION_90);` and applied a Y offset using `qp_set_viewport_offsets`, the LVGL driver will be set up with a resolution of 240x320 instead of a corrected resolution of 320x240 (minus the viewport offset).
Current implementation (170x320 display rotated 90 with 35px of Y-offset): LVGL is rendering only 240 wide (instead of 320) and the circle is being cut because of the offset.
With this PR: 0,0 is now at the top-left corner without any cut-off and it is rendering the whole screen.
*
> QP: Correct rotation and offset when using LVGL

- lib/python/qmk/cli/generate/version_h.py
- lib/python/qmk/git.py
Small changes to the CLI to add the current commit's hash into `version.h` aswell as a marker(`*`) to know if the repository contained any un-commited changes when firmware was compiled.
This way we can `print` stuff like: `firmware built with commit: e725d6b199*`.
I made this to show the hash on a corner of my Quantum Painter screen(s) but thought it could be useful to other people thus sharing it.
*
> Add commit info to `version.h`

- keyboards/leafcutterlabs/bigknob/keymaps/macos/keymap.c
- keyboards/leafcutterlabs/bigknob/keymaps/macos/readme.md
New Keymap for Leafcutter BigKnob to support MacOS
* Changed Volume up and down to mac scan codes
* MacOS doesnt support Stop, so changed default to spotlight search
* N/A
- [n/a] My change requires a change to the documentation.
- [n/a] I have updated the documentation accordingly.
- [n/a] I have added tests to cover my changes.
- [n/a] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
> Added MacOS Support for BigKnob

- docs/feature_split_keyboard.md
Add explicit description and use cases for master left and right.
> Update handedness by define examples

- docs/feature_midi.md
the compiler returns an undefined error when using the midi_send_cc() function, I think the docs meant to use the declared constant defined as MIDI_CC_OFF and MIDI_CC_ON which have a defined value that corresponds the one meant to be put as parameters.
```
./keyboards/ergodox_ez/keymaps/soggywhale/keymap.c:158:69: error: 'ON' undeclared (first use in this function); did you mean 'ONE'?
midi_send_cc(&midi_device, midi_config.channel, 80, ON);```
```
> changed the undefined ON and OFF parameters to the above defined constant

- docs/feature_combo.md
The documentation for combos is slightly confusing: it starts with the idea of replacing `ESC` with `A` and `S`, but then uses `A` and `B` in the code examples. This PR makes the page consistently use `A` and `B` (although I personally think `A` and `S` would make more sense)
> Combos example consistently uses A B keys

- keyboards/converter/usb_usb/custom_matrix.cpp
- keyboards/idobao/id75/keymaps/gkbd_orthon/keymap.c
- keyboards/sirius/unigo66/custom_matrix.cpp
- keyboards/xiudi/xd75/keymaps/xo/keymap.c
- lib/python/qmk/cli/generate/keycodes.py
- quantum/action.c
- quantum/action_tapping.c
- quantum/keycode.h
- quantum/keycodes.h
- quantum/process_keycode/process_combo.h
- quantum/process_keycode/process_key_override.c
- quantum/process_keycode/process_space_cadet.c
- quantum/quantum.c
- tests/test_common/keyboard_report_util.cpp
- users/twschum/xtonhasvim.c
- users/xtonhasvim/xtonhasvim.c
Small steps to being able to remove the `quantum/keycode.h` header.
*
> Tidy up use of keycode range helpers

- data/schemas/keymap.jsonschema
- lib/python/qmk/keymap.py
Adds `ENCODER_MAP` support to `qmk json2c`, benefiting `qmk compile` whenever used with a `keymap.json`, as well as opening the door for configurator to supply encoder mapping.
> Generate encodermap output from keymap.json.

- docs/newbs_git_resynchronize_a_branch.md
Consider Git submodules included on QMK superproject
Add ```--recurse-submodules``` clause in Git commands where applicable
* None
> [Docs] Resynchronizing Your Branch including submodules

- lib/python/qmk/info.py
> Reduce false positives in layout name validation

- quantum/led_matrix/led_matrix.c
- quantum/rgb_matrix/rgb_matrix.c
- quantum/split_common/split_util.c
Title. As many data driven keyboards omit a traditional `config.h` file.
tz ci
```
Compiling: quantum/split_common/split_util.c                                                       quantum/split_common/split_util.c:19:10: fatal error: config.h: No such file or directory                                                           
#include "config.h"                                                                                                                                                                                                                                   
^~~~~~~~~~
```
> Remove `config.h` include from quantum files

- quantum/action_layer.c
Forgot to check compilation if `NO_ACTION_LAYER` is defined.  Errors currently, due to multiple definitions.  This fixes it by wrapping the functions in preprocessors, properly.
* Tzarc CI
> [Bug] Fix tri layer compiler issue if NO_ACTION_LAYER is defined

- quantum/keyboard.c
- quantum/matrix.h
introducing flexibility on matrix tasks timing. matrix state can now be locked when we don't need a matrix scan
Followup on #18732 , specifically [this comment](https://github.com/qmk/qmk_firmware/pull/18732#pullrequestreview-1143212426). This takes care of matrix tasks running when they should not and also rectifies the matrix report rates on sn32. Might also be useful in the future for implementing timer controlled scans in other boards.
*
> core: allow locking the matrix state

- docs/config_options.md
- quantum/keycode_config.c
- quantum/keymap_common.c
Fixes up some of the quantum handlers to properly respect magic status.  
Specifically, there are a number of non-basic keycodes that don't respect the magic status currently, and this change aims to bring most of these keycodes in line, to respect the magic status.
For instance, LT doesn't respect the changes currently. So if you have Caps Lock for the keycode (eg `LT(2, KC_CAPS)`), and caps<->Escape enabled for magic, previously, it would still be caps lock.  
* [Chat on discord](https://discordapp.com/channels/440868230475677696/440868230475677698/711917597066526740)
> Make Magic handling more consistent in Action Keycode handling

- quantum/action.c
Current CI issue.
Don't get me started about the format. I'll sort out a followup PR once this is sorted.
> Fixup `develop` compiles.

- data/mappings/defaults.hjson
- data/schemas/keyboard.jsonschema
- docs/feature_converters.md
- docs/squeezing_avr.md
- platforms/chibios/converters/elite_c_to_elite_pi/pre_converter.mk
- platforms/chibios/converters/elite_c_to_helios/pre_converter.mk
- platforms/chibios/converters/elite_c_to_rp2040_ce/_pin_defs.h
- platforms/chibios/converters/elite_c_to_rp2040_ce/converter.mk
- platforms/chibios/converters/promicro_to_elite_pi/pre_converter.mk
- platforms/chibios/converters/promicro_to_helios/pre_converter.mk
- platforms/chibios/converters/promicro_to_rp2040_ce/_pin_defs.h
- platforms/chibios/converters/promicro_to_rp2040_ce/converter.mk
The rp2040_ce converter is added following the BastardKB standard pinout and adds elite-pi and helios as alias to rp2040_ce
Helios Info:
GitHub: https://github.com/0xCB-dev/0xCB-Helios
Shop: https://keeb.supply/products/0xcb-helios
Pinout reference: ![](https://raw.githubusercontent.com/0xCB-dev/0xCB-Helios/main/rev1.0/helios.webp)
*
> add rp2040_ce and add elite-pi and helios as alias

- keyboards/handwired/swiftrax/bumblebee/bumblebee.c
- keyboards/handwired/swiftrax/bumblebee/config.h
- keyboards/handwired/swiftrax/bumblebee/keymaps/via/rules.mk
> Fixup swiftrax/bumblebee (reduce firmware size)

- docs/feature_swap_hands.md
- quantum/action.c
- quantum/action.h
Add a simple user callback function for the status of swap hands that can be used by status indicators.
> Add swap hands status function

- quantum/keymap_common.c
- tests/basic/test_action_layer.cpp
Layer mod has a mixup between 5-bit vs. 8-bit mods representation, and this PR fixes that.
Layer mod `LM(layer, mod)` has a bug with right-handed mods. The keycode encodes the mods in a 5-bit format, it would seem intending the same 5-bit encoding as used in `LT` and `OSM` keys ([code link](https://github.com/qmk/qmk_firmware/blob/e922b46a866aec40f34d9e0dfcb15932adeb0563/quantum/quantum_keycodes.h#L101-L104)):
```c
// L-ayer M-od: Momentary switch layer with modifiers active - 16 layer max
#define LM(layer, mod) (QK_LAYER_MOD | (((layer)&0xF) << 5) | ((mod)&0x1F))
#define QK_LAYER_MOD_GET_MODS(kc) ((kc)&0x1F)
```
However the existing keymap_common code handles `LM` mods as if they were in 8-bit format. For instance, the key `LM(MOD_RALT)` incorrectly holds Left Alt + Right Ctrl, when it …
> Fix Layer Mod mishandling of right-handed mods, a mixup of 5-bit vs. 8-bit mods representation.

- quantum/process_keycode/process_key_override.c
`IS_KEY` is no longer present, but was an alias for `IS_BASIC_KEYCODE`.  So just corrected to that. 
* Compilation issue
> [Bug] Fix compilation issue for Key Overrides

- docs/feature_encoders.md
Add more thorough example of keyboard level encoder function, remove layer specific functionality example, as encoder map should be used, and some other cleanup.
> Elaborate on keyboard level encoder functionality

- keyboards/peej/lumberjack/keymaps/via/keymap.c
- keyboards/peej/lumberjack/lumberjack.c
When building the PCB, some people have issues knowing if the keyboard has power, so this PR adds a LED startup sequence to make the LEDs flash on powerup.
*
> [Keyboard] Add LED startup sequence to Lumberjack

- lib/python/qmk/cli/mass_compile.py
Allows `qmk mass-compile` to filter by key existence, i.e.:
```sh
qmk mass-compile -c -j 41 -f exists(matrix_pins.direct)
```
> Add `mass-compile` ability to filter by key existence.

- quantum/action_tapping.c
- tests/tap_hold_configurations/quick_tap/config.h
Defining only `QUICK_TAP_TERM_PER_KEY` creates the variable `tapping_keycode` but if that is the only option enabled, the `tapping_keycode` variable is unused and thus throws a compilation error.
```c
```
I removed the define from the `if` and added `#define QUICK_TAP_TERM_PER_KEY` in the config.h file of the unit test so that it catches the error.
Bug discovered by @XeroOl
Related discussion with @sigprof and @filterpaper  on Discord: https://discord.com/channels/440868230475677696/869812721552601088/1077140624643477534
PS: Should I add a comment to the PER_KEY define in the unit test config file linking to this PR? At face value, I can imagine some people in the future thinking it is totally useless.
*
> [Bug] Fix compilation error when defining QUICK_TAP_TERM_PER_KEY

- builddefs/common_rules.mk
```
Creating load file for flashing: .build/splitkb_kyria_rev3_wepo_promicro_rp2040.hex                 [OK]
Creating UF2 file for deployment: .build/splitkb_kyria_rev3_wepo_promicro_rp2040.uf2                [OK]
```
Seems users are trying to grab the hex file from the build directory and use it for flashing....
*
> Hide hex output when building uf2

- keyboards/ploopyco/trackball/readme.md
Fix the Ploopy trackball documentation so that the non-existant methods `process_mouse_user` and `process_wheel_user` are no longer referenced.  Instead, I added documentation for a similar method `pointing_device_task_user`.
> remove non-existent method from ploopy documentation

- keyboards/sofle/keymaps/michal/config.h
- keyboards/sofle/keymaps/michal/keymap.c
- keyboards/sofle/keymaps/michal/rules.mk
Revamped my existing QMK Keyboard config
* N/A
> sofle/keymaps/michal: rewrite

- drivers/led/aw20216.c
The unfashionable AW20216 takes a chance into anomaly when starting, so a soft reset is added to ensure it boots as expected.
Also there is a low power mode that automatically shutdown the chip when all LEDs are off, added that to.
*
> Improve robustness of AW20216 driver

- lib/python/qmk/c_parse.py
This area of the code naively assumes that a keyboard's `g_led_config.matrix_co` is the same shape as the switch matrix, as it gathers all the LED indexes and chunks them up by the row count. The result is that if one row is missing an element (not the same as having `NO_LED` set), it ends up parsing the matrix-to-LED-index mappings as follows:
```
...
{  3,  2,  1 },
{  7,  6,  5,  4 },
{ 11, 10,  9,  8 }
{ 15, 14, 13, 12 }
...
row 0: (3, 2, 1, 7)
row 1: (6, 5, 4, 11)
row 2: (10, 9, 8, 15)
row 3: (14, 13, 12)
```
Instead, we keep track of the current row using the same bracket-counting system and only add a row once it is "completed". Now we can validate the dimensions much better.
*
> Check all rows have the correct number of columns when parsing `g_led_config`

- docs/breaking_changes.md
- docs/chibios_upgrade_instructions.md
We're now using `qmk-master` for configurator branch name.
> Breaking changes - submodule branch name update

- keyboards/switchplate/southpaw_65/matrix.c
Apparently the changes done in #16277 swapped the values read from the PCA9555 expanders by mistake, which resulted in mixed up matrix columns. Fix the chip and register addresses to match the original code.
The broken change is [this](https://github.com/qmk/qmk_firmware/pull/16277/files#diff-921203cf4ee047ea3650fecd282a5709f92b83c88c0cbfbf3542f7f4fb60a63b); looks like the sequence of `pca9555_readPins()` calls was mistakenly copied from `xiudi/xd96`.
@elegantalchemist, are you able to compile the code locally to test these changes?  You can use the `switchplate-southpaw_65-fix-matrix` branch from `sigprof/qmk_firmware` directly.
* Fixes #20014
> Unbreak switchplate/southpaw_65 after #16277

- docs/feature_split_keyboard.md
- docs/porting_your_keyboard_to_qmk.md
There is no mention or visualization of how to create a layout macro in `info.json` for split keyboards.
@fauxpark helped me tremendously in Discord by creating and providing these visualizations to aid my understanding:
https://cdn.discordapp.com/attachments/440868230475677698/1073409438712610907/image.png
https://cdn.discordapp.com/attachments/440868230475677698/1073409562373259364/image.png
I strongly feel these should be in the docs.
I think it best to include a short discussion in the [split keyboard page](https://docs.qmk.fm/#/feature_split_keyboard), explaining that row pins are automatically doubled when setting `SPLIT_KEYBOARD = yes` and that QMK views the physical layouts according to those pictures.
These are the pages I used to search for answers to the question: …
> Discuss layout macro

- docs/feature_combo.md
* Added an explicit section title for mod-tap
* Removed superflous mention of PR
* Lowered heading levels for Advanced Configuration sub-section
> [Docs] Add mod-tap section header

- lib/python/qmk/info.py
Spits out a warning if there are no keys at x=0 or y=0.
*
> `qmk info`: add warning when layout is offset

- .github/workflows/ci_builds.yml
> Add CI builds for default and via keymaps

- data/mappings/defaults.hjson
- data/schemas/keyboard.jsonschema
- docs/feature_converters.md
- docs/squeezing_avr.md
- platforms/chibios/converters/elite_c_to_liatris/pre_converter.mk
- platforms/chibios/converters/promicro_to_liatris/pre_converter.mk
This pull request add a converter alias for the [Liatris](https://splitkb.com/products/liatris) microcontroller.
N/A
> Add RP2040 Community Edition alias for splitkb.com's Liatris controller

- keyboards/teleport/native/info.json
- keyboards/teleport/native/rules.mk
This PR is, as talked about on the QMK discord, a bugfix to keep this firmware from softbricking keyboards if compiled off the current master branch.
Apart from enabling mousekeys (people asked for it, figured I'd throw it in with the bugfix) this switches to the legacy eeprom wear levelling driver, as the new default one seems to brick F411CC based boards due to wrong flash size defines in configs.
New FW is tested on hardware and works as expected.
*
> Teleport native bugfix (changed F411CC wear levelling)

- keyboards/trashman/ketch/ketch.h
When soldering a Minivan layout to the Ketch (3 physical keys left of space bar).  The location of left ALT/GUI is transposed, and mapped to the location of the 4th key.  
*
> Ketch LGUI/LALT key transposed on Minivan layout

- .github/workflows/ci_builds.yml
Runner default stops after 6 hours -- current QMK default keymaps get to `t` at that point.
Extends to 23 hours for the moment until we work out how to drop the number of required builds.
> Allow for CI builds to run for 23 hours, instead of 6.

- .github/workflows/ci_builds.yml
Already includes the matrix param.
>  Allow for CI builds to run for 23 hours, instead of 6. (part deux)

- keyboards/annepro2/annepro2.c
- keyboards/annepro2/ap2_led.c
- keyboards/annepro2/ap2_led.h
- keyboards/annepro2/protocol.h
The current implementation enables LEDs and then sets mode
to manual. Because of this, [shine firmware](
https://github.com/OpenAnnePro/AnnePro2-Shine)
initially starts it own LED profiles and after processing next
message switches to manual mode where LEDs are controlled by QMK.
The effect of this is that for less than a second, keyboard
lights up all white and then switches to QMK profile.
The adjustment makes sure that no Shine profile logic is used at all.
Also, the second commit removes an unhandled command
`CMD_LED_GET_STATUS`. It does nothing on Shine side and should probably
be removed.
* LED flicker is removed during keyboard connect/boot
* Unnecessary call to an unhandled command `CMD_LED_GET_STATUS` is removed
> [keyboard] Prevent LED flicker when connecting AnnePro 2

- lib/python/qmk/c_parse.py
- lib/python/qmk/json_encoders.py
- lib/python/qmk/tests/test_cli_commands.py
* Removed `w: 1` from default key entry since it does not get filtered out of the `qmk info` output
* Improved sorting of layout keys: `label`, `x`, `y`, `w`, `h`, `flags` (LED/RGB Matrix), `matrix`
* Make rotary encoder config render on a single line too
*
> JSON encoder: improve sorting of layout dict keys

- .github/workflows/ci_builds.yml
- lib/python/qmk/cli/mass_compile.py
Super naive version of parallelism.
Splits up per-keyboard folder.
Uploads build artifacts.
Also fixes the wildcard filtering for `qmk mass-compile -f ...`.
> Let's use workflows to parallelise the builds.

- docs/custom_quantum_functions.md
- docs/feature_advanced_keycodes.md
- docs/feature_key_overrides.md
- keyboards/gray_studio/space65r3/readme.md
Main change:
- Add an example of using `void housekeeping_task_user(void)` to turn off RGB light as there is not a builtin way like `RGB_MATRIX_TIMEOUT`.
Minor changes:
- Add a link to key override into advanced keycode doc where `shift + backspeace = delete` is achieved by a macro.
- Fix the name for Space65 R3 in its README.
- Other minor format fixes in key override doc.
*
> [Doc] Add example to  keyboard housekeeping and some minor fixes

- keyboards/lily58/r2g/readme.md
Fix typos in readme for Lily58 R2G
* `lilly 58` -> `Lily 58`
* `crkbd/r2g:mb_via` -> `lily58/r2g:mb_via`
* some changes to keep the template like others...
> [Keyboard] Fix typos in readme for Lily58 R2G

- .github/workflows/ci_builds.yml
Parallelisation of full builds proved to be no real speed increase.
> De-parallelise CI

- docs/quantum_painter.md
- drivers/painter/gc9a01/qp_gc9a01.c
- drivers/painter/ili9xxx/qp_ili9163.c
- drivers/painter/ili9xxx/qp_ili9341.c
- drivers/painter/ili9xxx/qp_ili9488.c
- drivers/painter/ssd1351/qp_ssd1351.c
- drivers/painter/st77xx/qp_st7735.c
- drivers/painter/st77xx/qp_st7789.c
- quantum/painter/qp.h
- quantum/painter/qp_draw_image.c
- quantum/painter/qp_internal.c
- quantum/painter/qp_internal_driver.h
- quantum/painter/rules.mk
As per the title.
Split keyboard display auto-turnoff is not currently supported as it relies on the last input activity timestamps to be sync'ed. Separate PR will follow.
> Quantum Painter QoL enhancements -- auto-poweroff, auto-flush, buffer sizing

- drivers/lcd/hd44780.h
- quantum/digitizer.h
- quantum/joystick.h
- quantum/leader.h
- quantum/programmable_button.h
- quantum/secure.h
- quantum/send_string/send_string.h
Just some minor tweaks to make these docs prettier and easier to find in the HTML output (which is not currently enabled).
*
> Update Doxygen comments for some headers

- quantum/audio/audio.c
- quantum/audio/audio.h
- quantum/rgblight/rgblight.c
- quantum/rgblight/rgblight.h
Mainly to increase consistency between features.
*
> Add some helpers to tidy up XAP

- builddefs/build_keyboard.mk
Adds a new flag to the build -- `KEEP_INTERMEDIATES=yes` -- which instructs the compiler to keep the post-preprocessor output in `.build` as a sibling to the object file output that the compiler created.
This can then be diff'ed between builds in order to determine if preprocessor or include ordering etc. changes outputs.
Also factors in with the SHA1 verifications, so that code-wise differences can be determined, rather than looking at assembly.
> Optionally keep intermediate file listings in order to do comparisons between builds.

- keyboards/handwired/jotanck/config.h
- keyboards/handwired/jotanck/info.json
- keyboards/handwired/jotanck/jotanck.c
- keyboards/handwired/jotanck/jotanck.h
- keyboards/handwired/jotanck/keymaps/via/keymap.c
- keyboards/handwired/jotanck/keymaps/via/rules.mk
> add via firmware support

- platforms/arm_atsam/eeprom_samd.c
- platforms/avr/drivers/i2c_master.c
- quantum/audio/audio.c
- quantum/audio/audio.h
- quantum/color.c
- quantum/midi/midi.c
- quantum/rgblight/rgblight.c
- quantum/velocikey.c
Be it only small code chunks, we have common fallbacks so these shouldnt be duplicated everywhere.
*
> Tidy up duplication of MIN/MAX fallback implementations

- keyboards/jacky_studio/piggy60/readme.md
Unfortunately a couple of people have already "bricked" their `jacky_studio/piggy60` PCBs by flashing the firmware I reverse-engineered, not realizing they had a different PCB revision.
PRs to move the current version and add a `rev2` will ensue against `develop`, but I thought this warning would be better off in `master` so someone is likelier to see it before the end of May.
> [jacky_studio/piggy60] warn about incompatible PCB rev

- lib/python/qmk/c_parse.py
Currently info.json only allows a key to have a single matrix position. However, this is not the case for the C layout macros - the same key from the top section may be assigned to multiple matrix positions. Sometimes this is due to a typo, other times it is "intentional", in order to ensure eg. the two keys of a split backspace both perform the same action as a 2u backspace, if the wrong layout is used.
The layout parsing code, though, will only select the last seen matrix position for a given key as it simply overwrites any existing value. This might result in keys not working as expected when the layout is migrated to info.json.
Now, the matrix positions for each key are collected and an error given if the length of the list is not 1.
*
> Check for multiple matrix positions assigned to same key
