platforms/chibios/drivers/vendor/RP/RP2040/ps2_vendor.c
This PR contains PS/2 PIO Driver for RP2040. It supports both PS/2 Mouse Stream and Remote modes, and it **should** support PS/2 Keyboard too. 
Please, let me know if there are any changes needed in terms of code, comments or documentation. Thanks!
- https://github.com/qmk/qmk_firmware/pull/17892 needs to be merged before.
- Squash merge is recommended.
=> [Core] PS/2 PIO Driver for RP2040

quantum/rgblight/rgblight.h
PR #18338 introduced a change that deferred rgblight_set after a call to rgblight_set_layer_state to the next invocation of rgblight_task.
However, rgblight_task is a no-op unless RGBLIGHT_USE_TIMER is set, which only happens automatically if an RGB animation is enabled, or if RGBLIGHT_LAYER_BLINK is enabled.
If neither of these are enabled, rgblight_set is never called automatically after rgblight_set_layer_state, so the LED state is never actually set.
This commit fixes this issue by ensuring that RGBLIGHT_USER_TIMER is set if rgblight layers are enabled.
* #19520
=> Fix rgblight layers when animations aren't enabled

lib/python/qmk/cli/git/submodule.py
`qmk git-submodule -f` will remove any unknown directory within `lib/`, for instance when swapping from a riot based branch back to develop.
Can be the default behaviour with:  `qmk config git_submodule.force=True`.
*
=> Add force support to 'qmk git-submodule'

.github/workflows/ci_builds.yml, builddefs/build_keyboard.mk, util/ci/generate_failure_markdown.sh
Adds a step summary for each build during CI.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
=> Add step summary output to CI builds, with failure logs.

.github/workflows/ci_builds.yml, util/ci/generate_failure_markdown.sh
If everything succeeded, then the commands would fail due to file non-existence.
=> Fixup CI command failures.

lib/python/qmk/cli/mass_compile.py
Adds the ability to `qmk mass-compile` to specify `make` targets on the command line:
```sh
qmk mass-compile -c -t -j 8 planck/rev6:default planck/rev6_drop:default
```
Also modifies the `--no-temp` argument to keep final outputs as they're not temporary.
=> Add ability for `qmk mass-compile` to build specified targets

keyboards/kinesis/kint41/rules.mk
Fixes configurator spitting out the wrong firmware format.
* https://github.com/qmk/qmk_configurator/issues/1253
=> Revert to hex output for kint41

lib/python/qmk/painter_qgf.py
Geometry needs to be specified as pixel-inclusive -- delta frames forgot about that.
=> [QP] Fix up delta frame boundaries

docs/feature_pointing_device.md, keyboards/3w6/rev2/keymaps/default_pimoroni/pimoroni_trackball.c, keyboards/crkbd/keymaps/vlukash_trackpad_right/trackpad.c, keyboards/dichotomy/dichotomy.c, keyboards/keyhive/honeycomb/honeycomb.c, keyboards/molecule/adns.c, keyboards/splitkb/kyria/keymaps/gotham/thumbstick.c
Update callbacks for pointing devices in code
- [] I have updated the documentation accordingly.
=> Fixup Pointing device functions

keyboards/crkbd/keymaps/md40/config.h, keyboards/crkbd/keymaps/md40/keymap.c, keyboards/crkbd/keymaps/md40/readme.md, keyboards/crkbd/keymaps/md40/rules.mk
Adding a new keymap for crkbd. A minimally disruptive keymap for 40% keyboard.
=> Adding md40 a ckrbd compatible keymap

keyboards/ferris/keymaps/via/config.h
Generic cheap Promicros are often used to build the austere ferris/sweep board. Most of these controllers require `SPLIT_USB_DETECT` to function correctly and this change eliminates a frequent issue for first time builders testing their hardware.
=> Add split USB detection support

keyboards/preonic/keymaps/arkag/keymap.c, users/arkag/arkag.c, users/arkag/arkag.h
Just updating my user folder and preonic keymap
=> update keymap, add hitbox layout

docs/other_vscode.md
VS Code C/C++ extension is capable of understanding the standard compile_commands.json. This should be the default recommendation since it provides the most accurate information to the language server.
https://github.com/qmk/qmk_firmware/issues/19401
Just a documentation update. I checked that the document looks OK by running `qmk docs` locally.
* https://github.com/qmk/qmk_firmware/issues/19401
- [n/a] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [n/a] I have added tests to cover my changes.
=> Add recommendations for VSCode intellisense

quantum/painter/qp_draw_image.c
As already commented on [19994](https://github.com/qmk/qmk_firmware/pull/19994), there's an edge case
Scenario: Having a 16/24bpp QGF, and ofc, native color support enabled
Problem: On multi-device firmwares, you could also try and draw it on another display which doesn't use such format. 
\> Tested on ILI9163 and ILI9341 (RGB565) it indeed draws garbage with an RGB888 image
Thus i've added a small guard clause comparing the sizes before trying to draw. I guess the driver could store the ID of the data format (we can get bpp from it) for this kind of checks to be more useful.
Note: Im assuming the `<= 8` bpp formats are being converted to `hsv888` by the `qp_internal_decode_palette` function (didn't understand its code much), and then the `palette_convert` function on each driver can take …
=> [Bugfix] Check QGF's bpp against display's native_bits_per_pixel

keyboards/massdrop/alt/keymaps/urbanvanilla/keymap.c
Existing code used a uint32_t for the idle timer, but the comparisons were done with timer_read and timer_elapsed so actual comparison was on uint16_t.  This meant the idle timer could not be more than 65535 milliseconds, or just over 1 minute.
Switched the comparisons to timer_read32 and timer_elapsed32 so that the largest possible timeout is 4,294,967,295ms, or 136 years.  While that would be pretty ridiculous, at least this way more reasonable longer timeouts like 15 minutes or an hour will work.
*
=> Allow a larger int for the idle timeout for urbanvanilla keymap

builddefs/common_features.mk, docs/feature_pointing_device.md, drivers/sensors/pmw3320.c, drivers/sensors/pmw3320.h, quantum/pointing_device/pointing_device.h, quantum/pointing_device/pointing_device_drivers.c
Added support for Pixart PMW3320 optical sensor.
Since PMW3320 sensor's datasheets are not really descriptive in terms of programming and I don't really have experience in hardware reverse engineering, some parts of implementation are guesses.
I used ADNS5050 driver as a base for this driver, so some "hacks" are from here.
I'm pretty sure that some initial settings in pmw3320_init function are device-specific, but haven't found any similar settings for other sensor in other devices folders, so I'm not sure where to put them.
None
=> Added PMW3320 driver

docs/feature_dynamic_macros.md, docs/ja/feature_dynamic_macros.md, keyboards/40percentclub/mf68/keymaps/delivrance/keymap.c, keyboards/dztech/dz65rgb/keymaps/drootz/keymap.c, keyboards/ergodox_ez/ergodox_ez.c, keyboards/gmmk/pro/rev1/ansi/keymaps/mattgauf/keymap.c, keyboards/handwired/dactyl_manuform/3x5_3/keymaps/dlford/keymap.c, keyboards/kprepublic/bm40hsrgb/keymaps/coffee/keymap.c, keyboards/moonlander/moonlander.c, keyboards/mschwingen/modelm/modelm.c, keyboards/planck/keymaps/tk/keymap.c, quantum/process_keycode/process_dynamic_macro.c, quantum/process_keycode/process_dynamic_macro.h
This provides a means for user code to know which macro is being recorded, e.g., to display different indicators on an OLED.
Adds a `direction` argument to `dynamic_macro_record_start_user()`, just like the other `dynamic_macro_*_user()` functions.
Change `void dynamic_macro_record_start_user(void)` to `void dynamic_macro_record_start_user(int8_t direction)`.
`direction` is either `+1` or `-1` to indicate which dynamic macro is being recorded, making it similar to the other `dynamic_macro_*_user()` functions (which already take a `direction`).
Updated keyboard code with the new function signatures, as well as the documentation.
I did not touch the deprecated `quantum/dynamic_macro.h` which has a very different API.
None
=> Add direction to dynamic_macro_record_start_user

keyboards/handwired/onekey/keymaps/adc/keymap.c, keyboards/handwired/onekey/keymaps/hardware_id/keymap.c
Plain `printf()` does not work for console output on AVR (the `xprintf` code does not replace `printf()`, and QMK does not set up `stdout` for the avr-libc `printf` implementation).  Use `uprintf()` instead, which should work for all supported platforms.
Note that `uprintf()` requires the format string to be a constant (on AVR it uses `PSTR()` internally to put the format string into PROGMEM), therefore `uprintf(buffer)` cannot be used (and it would be wrong anyway if the buffer has some chance to contain any format characters).
* The `adc` and `hardware_id` keymaps for `handwired/onekey` boards did not output anything to the debug console on AVR-based boards (e.g., `handwired/onekey/promicro`).
=> onekey: Fix console output on AVR

lib/python/qmk/commands.py
Append user environment variables after the ones constructed from configurator json file. This will allow user defined variables (such as `TARGET`) to be used.
=> Append user variables to the end of make command

quantum/action.c, quantum/action_util.c, quantum/action_util.h, tests/basic/test_one_shot_keys.cpp
This PR fixes OSMs getting stuck with double tapping or holding another mod. The bug was caused by `oneshot_mods` being converted to regular mods with `registed_mods` and thus loosing possibility to unregister those mods, and also not clearing the mods.
The commits of this PR are: 
1. Remove handling of multiple taps: other than `ONESHOT_TAP_TOGGLE` functionality, single tap and double tap (or n-tap) should be treated equally
2. Leave OSMs intact on press-and-hold: holding an OSM should behave exactly like a regular mod, and should have no effect on OSMs
3. Remove redundant outer conditional block: this is mainly to improve readability and also to make it clearer that key-up of a tap has only effect with `ONESHOT_TAP_TOGGLE`
4. Add function `del_oneshot_locked_mods()`: improves …
=> Fix OSMs getting stuck

keyboards/keyboardio/model01/model01.h
This gives an alternate arrangement option that sees the thumb keys as a single row rather than 4.
=> Add an alternate layout definition for Keyboardio Model 01

docs/newbs_getting_started.md
Add `qmk list-keyboards` to the getting started guide.
As I was going through the install docs, I ran into an error. Since I didn't know any other options for the keyboard, it made it difficult to discern whether it was an issue with the keyboard name that I was using or whether it was due to something else.
=> Suggest `qmk list-keyboards` when testing build environment

docs/pr_checklist.md
Since keyboard maintainers updating their boards to data driven on `master` sometimes causes merge conflicts, if some or all of that work has already been completed on `develop`.
*
=> PR checklist: keyboard updates must go to `develop`

quantum/rgb_matrix/rgb_matrix.c, quantum/rgb_matrix/rgb_matrix.h
Changed `rgb_matrix_indicators_advanced` to restrict the RGB index range to the split keyboard's left or right range.
Added `RGB_MATRIX_USE_LIMITS_ITER` macro to reduce code duplication in handling split keyboard RGB index range.
* #20203
=> Fixed split keyboard issue where custom LED indicators could activate incorrect LEDs (#20203)

keyboards/blank_tehnologii/manibus/config.h, keyboards/blank_tehnologii/manibus/keymaps/samurai/keymap.c
Updated Manibus pinout for the PCB revision that will reach customers. 
Also cleaned up samurai keymap.
=> Manibus keyboard, update pinout

lib/python/qmk/info.py
```
⚠ botanicalkeyboards/fm2u: Layout "LAYOUT_isoenter" is offset on X axis by 0.25
⚠ illuminati/is0: Layout "LAYOUT" is offset on X axis by 0.25
⚠ kb_elmo/isolation: Layout "LAYOUT" is offset on X axis by 0.25
```
*
=> `qmk info`: account for ISO enter when calculating layout X offset

docs/feature_debounce_type.md
* Add documentation for setting `DEBOUNCE`
* Remove excess backtick formatting
=> Add debounce time description

lib/python/qmk/cli/mass_compile.py
Anything with a `DEFAULT_FOLDER` wasn't being correctly resolved.
Example issue:
```sh
qmk mass-compile -c durgod/dgk6x:default durgod/dgk6x/hades:default
```
=> Resolve keyboard names for `qmk mass-compile`.

quantum/basic_profiling.h
Adds basic profiling support in order to determine the percentage of time spent within a function or block of code.
```
/*
This API allows for basic profiling information to be printed out over console.
Usage example:
#include "basic_profiling.h"
// Original code:
matrix_task();
// Delete the original, replace with the following (variant 1, automatic naming):
PROFILE_CALL(1000, matrix_task());
// Delete the original, replace with the following (variant 2, explicit naming):
PROFILE_CALL_NAMED(1000, "matrix_task", {
matrix_task();
});
*/
```
=> Add basic profiler.

quantum/action.c
in some cases, when encoder map and swap hands are both enabled, it will generate errors because NUM_ENCODERS isn't included in action.c: 
```
Compiling: quantum/action.c                                                                        quantum/action.c:139:55: error: 'NUM_ENCODERS' undeclared here (not in a function)
extern const uint8_t PROGMEM encoder_hand_swap_config[NUM_ENCODERS];
^~~~~~~~~~~~
quantum/action.c: In function 'process_hand_swap':
quantum/action.c:188:24: error: unused variable 'encoder_swap_state' [-Werror=unused-variable]
static uint8_t encoder_swap_state[((NUM_ENCODERS) + (CHAR_BIT)-1) / (CHAR_BIT)];
^~~~~~~~~~~~~~~~~~
```
=> [Bug] Fix compilation issue with Swap Hands and Encoder Map

docs/zh-cn/mod_tap.md, keyboards/crkbd/keymaps/cameronjlarsen/config.h, keyboards/handwired/stef9998/split_5x7/keymaps/stef9998/keymap.c, keyboards/karn/keymaps/colemak/keymap.c, keyboards/splitkb/aurora/sweep/keymaps/default/keymap.json, keyboards/splitkb/kyria/keymaps/cameronjlarsen/config.h, quantum/action_tapping.h
Just some clean-up after #20211 has been merged.
*
=> [Chore] Remove stray mod tap interrupt defines and per key functions

keyboards/a_dux/a_dux.c, keyboards/a_dux/config.h, keyboards/a_dux/info.json, keyboards/a_dux/rules.mk
* Move build settings into info.json
* Remove unsupported switch type locking support
=> Move a_dux to data-driven

.github/workflows/ci_builds.yml, lib/python/qmk/cli/format/python.py, util/ci/discord-results.py, util/ci/requirements.txt
Closes the loop on Discord -- #webhooks_ci.
Have already set up the new repo secret accordingly.
Example:
=> Add Discord webhook at end of each CI run.

lib/python/qmk/cli/generate/config_h.py
`make clean bandominedoni:default` was generating to `.build/obj_bandominedoni/src/info_config.h`...
```c
#ifndef ENCODER_RESOLUTIONS
#endif // ENCODER_RESOLUTIONS
```
Which will not correctly init to the default value.
*
=> Avoid generating empty ENCODER_RESOLUTION

docs/feature_swap_hands.md, quantum/action.c, quantum/action.h
Additional user callback functions for toggling swap-hands.
=> Add swap hands toggle functions

lib/python/qmk/cli/generate/compilation_database.py
=> Add autocomplete to generate-compilation-database

keyboards/tada68/keymaps/tokyovigilante/keymap.c
Add a 0-9 numpad layer to my TADA68 layout.
Uses QWE/ASD/ZXC as 789/456/123 and R as Numlock when Mod 1 (Fn) is held. Also update keycodes for QMK 0.17.5. Successfully builds with `avr-gcc 12.2` and flashed using DFU.
=> [TADA68:DFU] Add numpad 0-9 to second layer

quantum/process_keycode/process_caps_word.c, tests/caps_word/test_caps_word.cpp
The newly introduced Tri-Layer keys do not behave like other layer tap/toggle keys when using the caps word feature.
This PR makes caps word continue on when one of those keys is pressed just like other layer keycodes.
Added the 2 new tri layer keys to the switch statement that ignores keycodes in the `process_caps_word` function.
=> Prevent Tri-Layer keys from stopping caps word

quantum/split_common/transport.h
I have a custom split keyboard with haptic (solenoid). One solenoid for each half.
I am not interested at the moment to have `SPLIT_HAPTIC_ENABLE` enabled because I want to fire only the solenoid located on the same half of the pressed key.
This PR only fixes a small preprocessor condition, introduced in #19203 (sending much love to @drashna)
Compiling a split keyboard with haptic (solenoid) and no `SPLIT_HAPTIC_ENABLE` I get:
```
Compiling: quantum/matrix_common.c                                                                 In file included from quantum/split_common/transactions.h:24,
from quantum/matrix_common.c:9:
quantum/split_common/transport.h:217:5: error: unknown type name 'split_slave_haptic_sync_t'
217 |     split_slave_haptic_sync_t haptic_sync;
| …
```
=> Fix preprocessor condition for SPLIT_HAPTIC_ENABLE

quantum/action_util.c
Since all bits of oneshot_layer_data are used for data encoding, the variable must not be signed. int8_t also breaks get_oneshot_layer() on newlib, because bit shifting on signed integers is implementation defined, so right-shift is filled up with 1s. The only reason this might work elsewhere are implementations filling up with 0.
Change of variable type.
* closes: #20418
=> quantum/action_util.c: Use uint8_t for oneshot_layer_data

builddefs/common_features.mk, drivers/ps2/ps2_interrupt.c, platforms/chibios/drivers/ps2/ps2_io.c
> ./keyboards/cantor/keymaps/test/config.h:10:23: error: 'A8' undeclared (first use in this function)
"gpio.h" fixes the issue. Not sure the exact cause, so not sure this is the right fix. 
Also, didn't properly enable the mouse endpoint. Was fine on AVR, but ChibiOS errors out on endpoint descriptors if mousekey or pointing device wasn't also enabled. 
* https://www.reddit.com/r/olkb/comments/12iyda4/help_qmk_ps2_mouse_and_arm_processor/
=> [Bug] Fix compilation issues with PS/2 driver on F4x1 controllers

docs/isp_flashing_guide.md
Current docs point to a specific `.hex` to flash to a Pro-Micro to sue it as an ISP. However, the default example ArduinoISP sketch emulates a stk500 ISP flasher. This is very accessible and should also be listed in the docs.
I confirmed this worked for my flashing `atmel-dfu` onto my Pro-Micro, via and Arduino Uno using the command (wiring as indicated):
```
avrdude -c stk500v1 -b 19200 -P /dev/ttyACM0 -p atmega32u4 -U flash:w:bootloader_atmega32u4_1.0.0.hex:i -U hfuse:w:0xD9:m -U efuse:w:0xC3:m -U lock:w:0x3F:m
```
Added corresponding wiring, description and `avrdude` parameters to guide. 
*
=> Adds Docs option for ArduinoIDE's example `ArduinoISP`

docs/feature_advanced_keycodes.md
The suggested way to check if `get_mods()` matches *only* a certain set of mod bits was wrong.
* Fixes #20361 
- [] I have updated the documentation accordingly.
=> [Docs] Fix suggested code pattern when a specific mod-mask is required.

keyboards/cannonkeys/ellipse_hs/keymaps/default/keymap.c, keyboards/cannonkeys/ellipse_hs/keymaps/via/keymap.c
Fixes an error introduced in #20560.
=> cannonkeys/ellipse_hs: correct layout macro references

keyboards/ez_maker/directpins/promicro/info.json
The configuration for the `ez_maker/directpins/promicro` board had `"bootloader": "atmel-dfu"` for some reason; this broke `qmk flash` for people who actually tried to use that code on a Pro Micro.  Set `"development_board": "promicro"` instead, so that the `caterina` bootloader and other settings appropriate for a Pro Micro would be used.
* `qmk flash -kb ez_maker/directpins/promicro -km default` did not work with a Pro Micro board due to the bootloader mismatch.
=> ez_maker/directpins/promicro: Fix bootloader mismatch

quantum/keyboard.c
When MATRIX_COL > 16 get_real_keys() does not work correctly because the `1 << col` shift overflows, since matrix_row_t is uint32_t. This causes key presses to be lost on keyboards with more than 16 columns.
=> Fix MATRIX_HAS_GHOST when MATRIX_COL > 16

docs/feature_rgb_matrix.md, quantum/rgb_matrix/animations/typing_heatmap_anim.h
There are a lot of configuration values for configuring the cooldown of the heatmap. However, for fast typers, the process of heating up might be too fast. Right now, manual changes to the codebase were necessary which in turn require to understand it first.
By defining a macro and allowing to override it, it's now easier to adjust this value as wanted.
=> typing_heatmap: Add macro to configure increase steps

docs/feature_pointing_device.md
I thought it was important to document different ways you can change drag scrolling to make it an even better feature.
Added some additional information to Drag scrolling
=> Add additional options for Drag Scroll config

docs/feature_rgb_matrix.md
Quick IS31FL3736 docs typos
* 3736 max 32 RGB leds
* 3736 copy paste error
=> [Docs] Develop cleanup IS31FL3736 docs

keyboards/vertex/angle65/config.h, keyboards/vertex/angle65/info.json
Follow up to #20514 — use `WS2812_DI_PIN` on develop branch.
=> Vertex/angle65 WS2812 pin fix

keyboards/1upkeyboards/pi50/config.h
1upkeyboards/pi50 update to WS2812_DI_PIN patch for develop
* as description
=> 1upkeyboards/pi50 WS2812_DI_PIN patch for develop

docs/feature_pointing_device.md, quantum/pointing_device/pointing_device_auto_mouse.c, quantum/pointing_device/pointing_device_auto_mouse.h
As the title says. 
Specifically make the layer timeout and debouncing configurable at runtime.
* Discord comments in bastardkb #firmware channel
=> Make Pointing Device Auto Layer more configurable

quantum/painter/qp_draw_text.c
Fixes font rendering when disabling ascii glyphs (`--no-ascii`), then specifying glyphs manually (`--unicode-glyphs "..."`).
No changes to font files required, just the rendering was a problem.
Tested and working on djinn.
* Closes #20624
=> Fixup QP font rendering when `--no-ascii` is specified.

keyboards/rart/rart45/info.json, keyboards/rart/rart45/keymaps/default/keymap.c, keyboards/rart/rart45/keymaps/via/keymap.c
- rename `LAYOUT_all` to `LAYOUT` (only one layout supported)
cc @alabahuy (keyboard maintainer)
=> Rart45: rename LAYOUT_all to LAYOUT

keyboards/durgod/k310/base/rules.mk
Will still work with STM32, but allows APM32 chips to be flashed as well
*
=> support boards with APM32 instead of the STM32

keyboards/salicylic_acid3/7skb/rev1/info.json
Is compiling ~100 bytes over, and LTO wasn't already enabled
* tzarc CI
=> [Keyboard] Enable LTO on salicylic acid 7skb to reduce size

keyboards/mode/m75s/rules.mk, keyboards/teleport/native/rules.mk, platforms/chibios/mcu_selection.mk
ChibiOS bump in this cycle allows us to remove the previously added workarounds.
*
=> Revert use of legacy wear leveling driver now ChibiOS is fixed

quantum/action.c, quantum/action_tapping.c, quantum/process_keycode/process_combo.c, tests/combo/config.h, tests/combo/test.mk, tests/combo/test_combo.cpp
Fixes #20668 by adding the keyevent back to the keyrecord.
* #20668
=> Fix Mod-Tap combo regression

quantum/action.c
is encoderevent check in #30669 introduced a warning/error: 
```
Compiling: quantum/action.c                                                                        quantum/action.c: In function 'process_hand_swap':
quantum/action.c:203:38: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]
203 |     else if (IS_ENCODEREVENT(*event) && pos.row == KEYLOC_ENCODER_CW || pos.row == KEYLOC_ENCODER_CCW) {
```
This fixes that, by wrapping the cw/ccw check in parentheses.
=> [Bug] Fix compilation error introduced by #20669

keyboards/winkeys/mini_winni/info.json, keyboards/winkeys/mini_winni/keymaps/default/keymap.c, keyboards/winkeys/mini_winni/keymaps/via/keymap.c
[title]
Also updates `info.json` to reference the maintainer's GitHub username.
cc @matthewdias (keyboard maintainer)
```
⚠ winkeys/mini_winni: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
=> WinKeys Mini Winni: rename LAYOUT_all to LAYOUT_ortho_2x4

keyboards/xiudi/xd004/info.json, keyboards/xiudi/xd004/keymaps/default/keymap.c, keyboards/xiudi/xd004/keymaps/narze/keymap.c, keyboards/xiudi/xd004/keymaps/system_and_media/keymap.c
[title]
cc @narze - This PR changes the layout macro reference in your keymap, but there aren't any logic changes here.
```
⚠ xiudi/xd004/v1: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
=> Xiudi XD004: rename LAYOUT_all to LAYOUT_ortho_1x4

keyboards/misterknife/knife66_iso/info.json, keyboards/misterknife/knife66_iso/keymaps/default/keymap.c, keyboards/misterknife/knife66_iso/keymaps/default_625u_space_split_bs/keymap.c
Even though it was documented in my previous PR, I failed to offer the choice of 2u or Split Backspace.
- rename `LAYOUT_all` to `LAYOUT_split_space_split_bs`
- rename `LAYOUT_625u_space` to `LAYOUT_625u_space_split_bs`
- adds new `LAYOUT_split_space` and `LAYOUT_625u_space` (both with 2u Backspace)
cc @afewyards (keyboard maintainer)
=> MisterKnife Knife66 ISO Layout Additions II

builddefs/build_keyboard.mk, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/generate/make_dependencies.py
This adds automated generation of a `make` dependency file, specifically tying the `generated-files` target to each of the "interesting" files that contribute to codegen (listed in `interesting_files`).
Upshot is, changes to `info.json` or any of the other metadata files should now properly trigger rebuilds.
=> Generate `make` dependency file during build for info.json's etc.

builddefs/common_features.mk
regression was introduced in commit bebfdad795add9fbc8c6c1393d1b817d542474ed
* 
- I tested only that it goes from not compiling to compiling.
=> Fix EEPROM_DRIVER=legacy_stm32_flash

keyboards/acheron/elongate/delta/info.json, keyboards/acheron/elongate/delta/keymaps/default/keymap.c, keyboards/acheron/elongate/delta/keymaps/via/keymap.c
[title]
Keyboard only supports one layout.
cc @Gondolindrim (keyboard maintainer)
```
⚠ acheron/elongate/delta: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
=> Acheron Elongate Delta: rename LAYOUT_all to LAYOUT

lib/python/qmk/cli/new/keymap.py, lib/python/qmk/importers.py, lib/python/qmk/keymap.py, lib/python/qmk/path.py, lib/python/qmk/tests/test_qmk_path.py
- Renamed `qmk.path.keymap()` to `keymaps()` and changed return value to a list of all found `keymaps/` directories for the given keyboard
- `keymap()` now takes a keyboard name and keymap name, and returns the path if it exists
This fixes an issue with `qmk new-keymap`: for example, attempting to create a new keymap for a board such as `crkbd/rev1` fails as there is no `default` keymap under rev1's `keymaps/` directory. Now it should grab the keymap folder from parent level and copy it down.
*
=> CLI: Improve keymap folder resolution

keyboards/nullbitsco/scramble/v2/config.h
XOSC delay needs to be set on SCRABMLE V2 for proper boot. Tested and working on all of our engineering/production units.
* N/A
=> nullbitsco/scramble: Add XOSC delay for startup

drivers/ps2/ps2_mouse.c
Support the 8-bit + sign-bit output from PS/2 using `MOUSE_EXTENDED_REPORT`.
Also gives user code more range to scale mouse movement.
*
=> Support PS/2 mouse 9-bit output with MOUSE_EXTENDED_REPORT

lib/python/qmk/cli/generate/autocorrect_data.py
The english_words package has breaking changes in v2.0 which results in the failure to load the English dictionary and an error indicating the english_words package should be installed for the functionality to work. This PR implements support for either v1 or v2 of the english_words package.
* #20914
=> Fix English word list retrieval in qmk generate-autocorrect-data

docs/cli_commands.md, lib/python/qmk/cli/find.py, lib/python/qmk/makefile.py, lib/python/qmk/search.py
- Force rules.mk files to be read as UTF-8 (default is CP1252 on Windows, causes issues with Unicode characters)
- `qmk find`: Add `--print` argument to print the value of the given key(s) for each matched target
- `qmk find`: Reworked the filtering a little to add support for `length(key, value)`, `contains(key, value)`, and `absent(key)`. Could probably be refactored further, maybe add `!=`?
*
=> `qmk find`: usability improvements

docs/cli_commands.md, lib/python/qmk/cli/c2json.py, lib/python/qmk/cli/format/json.py, lib/python/qmk/cli/generate/info_json.py, lib/python/qmk/cli/info.py, lib/python/qmk/cli/migrate.py, lib/python/qmk/cli/new/keyboard.py, lib/python/qmk/cli/via2json.py, lib/python/qmk/importers.py, lib/python/qmk/json_encoders.py
The info.json encoder now knows the full key path when encoding, instead of just the key name, in the form of an array. One possible application for this would be the ability to differentiate LED layouts from key layouts, possibly allowing further formatting of the latter to separate rows and gaps between keys. This is currently only done by hand and would be reverted by the encoder.
*
=> `qmk format-json`: Expose full key path and respect `sort_keys`

docs/understanding_qmk.md, quantum/quantum.c
Fix up #20584 to call `pre_process_record_kb()` (and therefore `pre_process_record_user()`) before `process_combo()`.
Adding the `pre_process_record_kb()` call after `process_combo()` is problematic — `pre_process_record_kb()` will miss any events which might be a part of some combo: https://github.com/qmk/qmk_firmware/pull/20584#issuecomment-1549138142.  Calling `pre_process_record_kb()` before the combo code would result in a much more logical behavior (`pre_process_record_kb()` receives all events for raw key or encoder actions before any other processing, including combos).
If we ever need a callback that runs after the combo processing, but before the tapping code, it would need to be called in more places (e.g., in two places where the combo code currently calls …
=> Move `pre_process_record_kb()` before `process_combo()`

keyboards/rart/rart80/keymaps/via/rules.mk
PR #20334 accidentally removed the `rules.mk` file from the `via` keymap for `rart/rart80`; restore that file.
(Another unrelated change in that PR is the addition of a final newline to `keyboards/rart/rart80/rules.mk`; this one is probably not worth to revert.)
* The `via` keymap for `rart/rart80` was broken (the VIA support was not actually enabled).
=> rart/rart80:via: restore rules.mk after #20334

tests/repeat_key/repeat_key_combo/test.mk, tests/repeat_key/repeat_key_combo/test_combos.c, tests/repeat_key/repeat_key_combo/test_repeat_key_combo.cpp
Repeat Key PR didn't have combo introspection changes, so once both were merged, unit tests starting failing.
This fixes that.
=> [Bug] Fix issue with Repeat Key-Combo test

lib/python/qmk/cli/json2c.py, lib/python/qmk/tests/test_cli_commands.py
Removes boilerplate / fixes inconsistencies.
Somehow missed when the other generate commands were updated.
*
=> Update json2c to use dump_lines

lib/python/qmk/cli/info.py
CLI currently always prints `Keyboard Folder: Unknown` when running "friendly" printing.
This is part of the stripped API content #20234, implemented this cycle.
As an alternative, we could move the `_strip_api_content` call to when we are only printing as `json` ( [like this?](https://github.com/qmk/qmk_firmware/compare/develop...21033_alt?expand=1) )?
*
=> `qmk info` - Remove printing of "Keyboard Folder"

keyboards/crkbd/crkbd.c
When merging/moving the oled code for the corne, I was not paying close enough attention.  r2g oled code didn't use progmem for the code to name array, but other code did.  Some mix and matching happened. 
Discovered when talking on discord (not directly about corne). 
Tested on hardware, to verify works correctly.
=> [Bug][Keyboard] Fix key display on Corne OLED

builddefs/common_rules.mk, util/uf2conv.py
Adds support for `0xc8a729 - device type identifier` - <https://github.com/microsoft/uf2#extension-tags>.
This functionality will be used with `adafruit/tinyuf2` to resolve some potential bricking scenarios with an upcoming product launch. The issue is that to reject "bad" self-update files, we also need to add the magic flags to QMK firmware files too.
The intention is to upstream compatibility in the long term, both to `microsoft/uf2` and `adafruit/tinyuf2`.
As discussed on Discord, in the short term we were okay accepting this change based on its changeset size, and the long term intentions.
=> Implement UF2 device type id extension tag

lib/python/qmk/painter.py
While updating to 20.0, and after [this Discord message](https://discord.com/channels/440868230475677696/568161140534935572/1080864486132555776) i've decided to try and draw a `rgb888` img on a `rgb565` display.
1) When trying to run the convert command, it error'ed out due to a typo on [here](https://github.com/qmk/qmk_firmware/blob/master/lib/python/qmk/painter.py#L184), the number in the check doesn't actually match the 888 colorspace size
2) QP indeed tries to draw the 24bpp image on the 16bpp which results in garbage, another PR for that coming soon (TM)
To avoid this, i've changed the code to perform a **dynamic** guard clause, i also took the chance to remove the obfuscated 2/4/8/12/256 check which used bitwise operations, and simply use the `in` operator.
NOTE: Using `_, fmt in …
=> [Bugfix + Refactor] `qmk painter-convert-graphics`

lib/python/qmk/cli/find.py, lib/python/qmk/search.py
When attempting to get `qmk find` to output the list of build targets for a specific keymap, exceptions were being thrown because the printable item list return value was not set during the search operation.
This PR fixes the exception but also provides a warning saying that it can't output the requested printable info if no filters are supplied -- mainly because the json's aren't parsed if not filters are present.
=> Fix up `qmk find` when not specifying filters.

docs/tap_hold.md
I forgot to remove certain remarks pertaining to the old hold-preferred default mode of mod-taps. They're now tap-preferred by default so these notes are misleading.
*
=> [Docs] Remove outdated remarks regarding the default MT behavior in tap_hold.md

lib/python/qmk/search.py
Functions in filters did not work properly except when used in the last (or only) filter.  The problem was caused by the peculiarity of the `lambda` behavior in Python — any variables from the outer scope are captured only by reference, therefore any subsequent reassignment of those variables is propagated to all lambdas created earlier in the same scope.  Together with the laziness of `filter()` (it returns an iterator which performs filtering on demand) this resulted in all function filters using the values of the `key` and `value` variables which correspond to the last filter in the sequence, therefore the result of filtering was wrong if some filter with a function was not the last one in the sequence.
Apparently the shortest way to make a Python lambda capture some variables by value …
=> `qmk find`: Fix handling of functions in filters

quantum/quantum.c, quantum/split_common/transactions.c
With split keyboards, when PC goes to sleep, only master side turns backlight off. 
This happens because `suspend_power_down_quantum` uses `backlight_set` which does not update in-memory config and just turns off pins. Backlight split sync uses the config to get current level value, so we must set it with `backlight_level_noeeprom`.
I also updated handling sync on the slave side to use same function, while technically it's not required for the fix, I think keeping the correct value in config makes sense.
Discussed in discord https://discord.com/channels/440868230475677696/440868230475677698/1112672499780571166
Reproduced and tested on my keyboard.
I put the PR to develop branch as per guidelines, however if you think it can be merged to master since it's a small bugfix, let me know and I …
=> Fix backlight sync on suspend_power_down for split keyboards

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, lib/python/qmk/info.py
Current hitting preprocessor isues:
```
⚠ acheron/apollo/87h/gamma: RGB_MATRIX_LED_COUNT->rgb_matrix.led_count: invalid literal for int() with base 10: 'DRIVER_1_LED_TOTAL'
⚠ aeboards/satellite/rev1: RGB_MATRIX_LED_COUNT->rgb_matrix.led_count: invalid literal for int() with base 10: 'ISSI_DRIVER_TOTAL'
```
Parsing is currently disabled due to the above issue. A 2nd pass will refactor keyboards, but this at least allows dd configuration in the short term.
*
=> Add *_MATRIX_LED_COUNT generation/validation

platforms/chibios/wait.c
By default, the initialization is NULL for callbacks and 0 for the rest of the fields. Additionally, not all chips share the same gpt_cfg
define only the fields needed
*
=> platfoms: chibios: wait: only define the frequency

quantum/process_keycode/process_dynamic_macro.c, quantum/process_keycode/process_dynamic_macro.h
This PR refactors the code used to stop recording a dynamic macro into it's own new function, void dynamic_macro_stop_recording(void), allowing users to programmatically end the recording of a dynamic macro.
An example of how this could be useful is that it would allow the user to, in their keymap, change the behavior of the QK_DYNAMIC_MACRO_PLAY_* keys to behave more like Emacs' key macros - where hitting the play 'key' while recording will stop recording and immediately play back the key macro, without requiring the user first perform a separate key stroke to explicitly end recording - by adding a case like this example to their process_record_user function:
```c
case QK_DYNAMIC_MACRO_PLAY_1:
case QK_DYNAMIC_MACRO_PLAY_2:
if (record->event.pressed)
dynamic_macro_stop_recording();
return …
```
=> [Core] Add a dynamic_macro_stop_recording(void) function.

quantum/process_keycode/process_autocorrect.c, quantum/process_keycode/process_autocorrect.h
Rigth now the weak function contains a lot of functionality that users may want to extend instead of completely override (eg: me 🙃), thus decoupling this into a function, to avoid duplications.
*
=> [Enhancement] Decouple autocorrect logic

docs/newbs_building_firmware_workflow.md
Incorrect GitHub account name in the JSON keymap field is a frequent user error. This change highlights that step.
=> Highlight keymap name entry

quantum/mousekey.c
The current kinetic mouse key function uses resource-intensive floating point to compute the quadratic curve speed. But the result is returned as an unsigned 8-bit integer value. The code line where fractional accuracy is important is at the division of `speed = (uint8_t)(speed / (1000.0f / mk_interval));`
This change uses 16-bit integers for the quadratic calculation variables, which are less resource-intensive. The output acceleration curve is almost unchanged with the default `MOUSEKEY_INTERVAL` value.
Truncation is used to round division output to an integer. With higher `MOUSEKEY_INTERVAL` values, rounding appears more accurate using 16-bit integer versus floating point. Example:
`mk_interval = 30`
| speed | (uint8_t)(speed / (1000.0f / mk_interval)) | (uint8_t)(speed / (1000U / …
=> Use unsigned integer for kinetic speed

quantum/painter/lvgl/qp_lvgl.c
QP-LVGL glue code has an bug. It computes panel size to be sent to LVGL as `width - offset_x` (and same for y), but that subtraction is not needed since the size is already the area in which we can draw, not size + offset (which doesnt even make much sense anyway).
* https://discord.com/channels/440868230475677696/440868230475677698/1115565012644274236
=> [Bugfix] LVGL bindings wrong offset math

quantum/debounce/asym_eager_defer_pk.c, quantum/debounce/sym_eager_pk.c, quantum/debounce/sym_eager_pr.c
doing this PR before it gets forgotten again. Fixes the significant performance drop when using one of the affected debounce algorithms.
example: `6400` matrix scan rates slow down to `5800` when a key is pressed and doesn't recover. Same test on another board, `1700`-> `1450`. With this patch the scan rate is consistent and stable.
The `matrix_need_update` variable needs to be reset to `false` in `transfer_matrix_values()`, otherwise that function continues to be invoked for every scanning loop (forever with `sym_eager_pk` and `sym_eager_pk`, or until some key gets released with `asym_eager_defer_pk`), and the scanning rate gets much lower because of all that useless work.
*
=> Reset `matrix_need_update` properly in eager debouncing algorithms

drivers/led/aw20216.c, drivers/led/ckled2001-simple.c, drivers/led/ckled2001.c, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3731-simple.c, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31flcommon.c
Actually uses the buffer/driver check to see if an i2c/spi flush is required to LED drivers.
Tested on STM32L4 + IS31FL3741 (pachi/rgb/rev2)
Effect Speed default (128)
For reference off is ~8171
<table>
<tr>
<td>Effect
<td>Old Scan Rate
<td>New Scan Rate
<tr>
<td>Solid Colour
<td>2926
<td>8127
<tr>
<td>Gradient Up/Down
<td>2858
<td>8062
<tr>
<td>Cycle All
<td>2840
<td>3594~3998
<tr>
<td>Cycle Spiral
<td>2719
<td>2708
</table>
* Prevent static animations to keep pushing i2c/spi commands slowing down overall scan rate
=> [Core] Optimisation - Add RGB LED colour set check in drivers

docs/newbs_getting_started.md
Not using MSYS terminal is a frequent user error. This change adds an additional statement to guide users to run the first command in MSYS itself. Edited the same statement for consistency for the other OSes.
=> Add an emphasis on QMK MSYS terminal

lib/python/qmk/c_parse.py
Make sure `led_config_t` is also present before `g_led_config`. Still not 100% accurate but should fix an edge case discovered on Discord:
```c
uint8_t led_index = g_led_config.matrix_co[row][col];
if (HAS_FLAGS(g_led_config.flags[led_index], LED_FLAG_INDICATOR))
```
Which causes `Unable to parse g_led_config matrix data`.
*
=> Slightly refine `g_led_config` parsing

quantum/rgb_matrix/rgb_matrix_drivers.c
Goes with https://github.com/qmk/qmk_firmware/pull/21134 . This change makes it so that the WS2812 doesn't update every cycle if no RGB LEDs have updated colour. (mainly for static and bitbang applications)
**Untested because I don't have any WS2812 only rgb matrix boards**
* WS2812 don't update every RGB Matrix cycle
=> [Core] RGB matrix ws2812 update

keyboards/handwired/dactyl_manuform/4x6/keymaps/scheikled/keymap.c, keyboards/handwired/dactyl_manuform/4x6/keymaps/scheikled/rules.mk
Amend named keymap to prevent compilation failure
* n/a
=> fix `scheikled` keymap for `dactyl_manuform/4x6`

quantum/dynamic_keymap.c
As discussed on Discord -- introspection already does the bounds checks so should decrease the resulting codegen size.
=> Rely on introspection to handle OOB access.

keyboards/lily58/keymaps/gaston/keymap.c, keyboards/lily58/keymaps/gaston/readme.md
Updates the custom Lily58 keymap to make the left CTRL key work with tap-hold. When tapped it's ESC and when held it's LCTRL.
=> Left Control is now ESC when tapped

quantum/rgblight/rgblight.c
=> Fix up operator precedence in RGBLIGHT

keyboards/gmmk/numpad/info.json
Fixes a key overlap issue in the Configurator rendering:
cc @GloriousThrall, @RustedAperture (keyboard maintainers)
=> GMMK Numpad: correct layout data

keyboards/handwired/onekey/nucleo_g431rb/info.json, keyboards/handwired/onekey/nucleo_g431rb/readme.md, keyboards/handwired/onekey/nucleo_g474re/info.json, keyboards/handwired/onekey/nucleo_g474re/readme.md, platforms/chibios/mcu_selection.mk
ChibiOS EFL driver is broken for STM32G431 -- it assumes it's a dual-bank part, which is incorrect.
This swaps the default G431 config to transient EEPROM -- a future ChibiOS update will result in the removal of this override.
Adds onekeys for G431 and G474.
=> Swap G431 to transient EEPROM. Add G431 and G474 onekeys.

keyboards/quarkeys/z40/info.json, keyboards/quarkeys/z40/keymaps/default/keymap.c, keyboards/quarkeys/z40/keymaps/via/keymap.c, keyboards/quarkeys/z40/readme.md
- enables `planck_mit` Community Layout support (only supported layout)
- style clean-ups on `info.json` and keymaps
- tidy-up keyboard metadata in `info.json` and `readme.md`
cc @tommyamoszhao (keyboard maintainer)
=> Quarkeys Z40 Community Layout Support and Touch-Up

keyboards/akko/top40/info.json
Corrects a key overlap issue in Configurator.
cc @jonylee1986 (keyboard maintainer)
=> Akko Top40: correct layout data

docs/feature_led_matrix.md, docs/feature_rgb_matrix.md, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733-simple.h, drivers/led/issi/is31flcommon.c, drivers/led/issi/is31flcommon.h
Shouldnt be here due to #15268.
Not sure how this has slipped through for so long, however this aligns everything to the other drivers.
* <https://discord.com/channels/440868230475677696/440911374571274240/1120653139322884118>
=> Remove use of __flash within LED drivers

.github/workflows/lint.yml
- Checks the before and after counts of the number of keyboards in the repository, ensuring that a maximum increase of 1 is present in the PR.
- Lists the added/removed keyboards in the CI run output.
=> Verify max one keyboard addition during CI.

docs/feature_hd44780.md, docs/feature_send_string.md, docs/i2c_driver.md, docs/spi_driver.md, docs/uart_driver.md
=> Fix anchor IDs for some API references

tmk_core/protocol/chibios/chibios.c
According to the USB 2.0 spec, remote wakeup should be disabled by
default, and should only be enabled if the host explicitly requests
it. The chibios driver code already takes care of storing this
information, and returning it on GET_STATUS requests. However our
application code has been ignoring it so far.
This is a USB compliance issue, but also a bug that causes trouble
in some cases: On RP2040 targets this has been causing problems if
a key is held down while the keyboard is plugged in. The keyboard
would fail to enumerate until all keys are released. With this
change that behavior is fixed.
Note that for LUFA targets this is already done correctly.
*
=> Chibios USB: Take into account if host wants remote wakeup or not

platforms/chibios/boards/GENERIC_PROMICRO_RP2040/configs/mcuconf.h, platforms/chibios/boards/GENERIC_RP_RP2040/configs/mcuconf.h, platforms/chibios/boards/GENERIC_WB32_F3G71XX/board/board.c, platforms/chibios/boards/GENERIC_WB32_FQ95XX/board/board.c, platforms/chibios/boards/IC_TEENSY_3_1/board/board.c, platforms/chibios/boards/PJRC_TEENSY_3_5/board/board.mk, platforms/chibios/boards/PJRC_TEENSY_3_5/board/extra.c, platforms/chibios/boards/PJRC_TEENSY_3_6/board/board.mk, platforms/chibios/boards/PJRC_TEENSY_3_6/board/extra.c, platforms/chibios/boards/QMK_PM2040/configs/mcuconf.h, platforms/chibios/suspend.c, tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/lufa/lufa.c
Waking a suspended host was previously broken for RP2040 and STM32 OTGv1 based keyboards on ChibiOS. Waking a host either didn't work at all or the host resumed operation but the keyboard was soft-bricked as it didn't recognized that the host was woken successfully.
The underlying cause was that the USB hal and low level USB drivers `USBv1` and `OTGv1` didn't recognized a resumed USB bus and therefore never signaled this to QMK's suspend/resume logic. Both drivers where fixed in `ChibiOS` and `ChibiOS-Contrib`. See:
* ChibiOS/ChibiOS@358678f9793ee11afd43ea467938be566140698d (STM32 OTGv1 LLD + HAL **already in `develop`**)
* ChibiOS/ChibiOS@e8413011051be737d33275b9cd443cdcf9044a1a (HAL **already in `develop`**)
* ChibiOS/ChibiOS-Contrib@e284aabd95ed57307dcf72dc94c163fbe23f4769 (RP2040 …
=> [Bug] Fix non-functional S3 wakeup / resume from suspense 

keyboards/40percentclub/gherkin/keymaps/default/keymap.c, keyboards/contra/keymaps/maxr1998/keymap.c, keyboards/crkbd/keymaps/rpbaptist/keymap.c, keyboards/dztech/dz60rgb/keymaps/matthewrobo/keymap.c, keyboards/dztech/dz60rgb/keymaps/mekanist/keymap.c, keyboards/dztech/dz65rgb/keymaps/matthewrobo/keymap.c, keyboards/handwired/arrow_pad/keymaps/default/keymap.c, keyboards/handwired/arrow_pad/keymaps/pad_21/keymap.c, keyboards/handwired/arrow_pad/keymaps/pad_24/keymap.c, keyboards/input_club/infinity60/led.c, keyboards/input_club/infinity60/led_controller.c, keyboards/kbdfans/niu_mini/keymaps/tobias/keymap.c, keyboards/kprepublic/jj40/keymaps/stevexyz/keymap.c, keyboards/massdrop/alt/keymaps/jdelkins_ss/keymap.c, keyboards/mt/mt980/keymaps/walker/keymap.c, keyboards/novelkeys/novelpad/keymaps/0xdec/keymap.c, keyboards/salicylic_acid3/setta21/keymaps/salicylic/keymap.c, keyboards/westfoxtrot/cypher/rev1/keymaps/kwer/keymap.c, keyboards/xiudi/xd75/keymaps/billypython/keymap.c, keyboards/xiudi/xd75/keymaps/boy_314/keymap.c, keyboards/yosino58/keymaps/default/keymap.c, keyboards/yosino58/keymaps/sakura/keymap.c, layouts/community/numpad_5x6/bjohnson/keymap.c, quantum/led.h, users/doogle999/doogle999.c
=> Get rid of `USB_LED_NUM_LOCK`

platforms/chibios/drivers/usbpd_stm32g4.c
The UCPD peripheral initially comes up in the “dead battery” mode, in which it supplies the Rd pull-downs on the CC1 and CC2 lines without any explicit configuration if the DBCC pins are wired appropriately.  The dead battery mode must be disabled to use the full functionality of UCPD; however, disabling the dead battery mode must be done only after the UCPD peripheral has been configured in the desired mode, so that the transition between modes happens without going through a state with no pull-down resistance on the CC lines.  Fix the code to respect the required initialization order.
The required init order is actually documented in the STM32G431 Reference Manual (46.4.6):
> After power arrives and the MCU boots, the desired behavior (for example source) must be programmed into ANAMODE …
=> usbpd_stm32g4: Configure UCPD before disabling the dead battery mode

drivers/painter/ili9xxx/qp_ili9xxx_opcodes.h
Found error with inversion cmds in ili9xxx opcode list when troubleshooting issue with ili9341 that needs inversion. 
Low impact since it's not actually used currently. Verified against datasheets for 9163, 9341, and 9488. 
* discord
=> Fix ili9xxx inversion opcode entry

keyboards/lily58/keymaps/gaston/config.h, keyboards/lily58/keymaps/gaston/keymap.c
Enable hold on other key press for better tap-hold experience.
=> Improve tap-hold configuration

keyboards/ryanbaekr/rb69/info.json, keyboards/ryanbaekr/rb86/info.json, keyboards/ryanbaekr/rb87/info.json
During creation of a now closed PR, noticed a section of ryanbaekr boards that define elite_c pins but have defined "promicro" as their controller. This PR aims to amend this configuration mismatch by changing processor, bootloader, and pin_compatibility to elite_c.
* n/a
=> Amend `ryanbaekr` boards by pin definitions

keyboards/planck/rev7/matrix.c
The watchdog code in `matrix.c` needs `#include <math.h>`; it broke with `AUDIO_ENABLE = no`, because `quantum.h` no longer included `<math.h>` implicitly.  Adding `#include <math.h>` fixes build of some user keymaps which have `AUDIO_ENABLE = no`.
* Build failures with `AUDIO_ENABLE = no`, e.g., CI build failure for #21344.
=> planck/rev7: Fix build without AUDIO_ENABLE

platforms/chibios/bootloaders/stm32_dfu.c
After #21352 other families weren't jumping to bootloader correctly.
Fixed version is confirmed functional on F303, H723, F072.
Unrelated verification:
G474 still functional, though it uses the different dual-bank implementation instead.
F401 with tinyuf2 still functional, too.
=> Fixup STM32-DFU

keyboards/rmkeebs/rm_fullsize/keymaps/default/keymap.c
The enter and delete keys were accidentally swapped on the numpad in the previous version of the keymap.  This update fixes that.
- [ X ] Keymap/layout/userspace (addition or update)
=> RM_Fullsize keymap fix: swap enter and delete keys

tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/arm_atsam/md_rgb_matrix.c, tmk_core/protocol/arm_atsam/md_rgb_matrix.h, tmk_core/protocol/arm_atsam/md_rgb_matrix_programs.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/usb_util.c, tmk_core/protocol/usb_util.h
=> tmk_core: remove direct `quantum.h` includes

docs/feature_auto_shift.md, quantum/process_keycode/process_auto_shift.c, quantum/process_keycode/process_auto_shift.h
The goal is to add a means of enabling all of the other special characters while disabling Auto Shift on tab. While I was at it, this adds documentation to the predefined character groups used to setup `get_auto_shifted_key` so that you don't have to go digging through .h files for them.
This also relates back to https://github.com/qmk/qmk_firmware/issues/13469 in that I added a flag to specifically enable enter .. though the need for it is arguable.
* Potentially https://github.com/qmk/qmk_firmware/issues/13469
=> Adds a way to separate tab from AUTO_SHIFT_SPECIAL.

lib/python/qmk/painter.py
=> [Refactor] Python-ify QP's converter code

docs/feature_key_overrides.md, docs/tap_hold.md, quantum/action.c, quantum/action_util.c, quantum/action_util.h, quantum/process_keycode/process_key_override.c, tests/tap_hold_configurations/retro_tapping/config.h, tests/tap_hold_configurations/retro_tapping/test_neutralization.cpp
Certain QMK features like Retro Tap and Key Overrides must unregister a previously registered modifier before sending a certain keycode but in doing so, the OS can sometimes misinterpret the intent of the user and trigger a keyboard shortcut when seeing the tap of modifier key. Notable examples are taps of the GUI key opening the start/applications menu in many desktop environments like Windows or Gnome or taps of the left Alt key focusing the menu bar in many GUI applications. This causes problems for the users of these features as described in issue #16795. 
This PR aims to solve this issue by the neutralization of those flashing modifiers achieved through the tap of a dummy, user-configurable, keycode.
To illustrate; the idea is to send a keycode like Right Control so that the OS sees …
=> [Feature] Send a dummy keycode to neutralize flashing modifiers in retro tap and key overrides

quantum/via.c, quantum/via.h
Adds led matrix functions for via's lighting system, base on #16086 
Tested on [mechlovin/zed65/mono_led](https://github.com/mechlovin/PCB/tree/master/Zed65/Mono-LED/Dolch65/Backlight-VIA-control) and mechlovin/olly/octagon.
Thanks.
*
=> add VIA support for LED Matrix

keyboards/handwired/dactyl_manuform/readme.md
Updated contents of dactyl_manuform readme.md to reflect current state of QMK
*
=> Revamp `dactyl_manuform` readme.md

docs/feature_mouse_keys.md, quantum/mousekey.c
* Use division by integer
Replace multiplication of fractional decimal numbers with division by integer to avoid floating point operations. This change will reduce compiled firmware size.
* Refactor if-else statements
Simplify duplicate `if` conditions and refactor ternary statements for consistency with the rest of the file.
* Revert kinetic wheel workaround
Revert mouse key wheel step size to `1` because stuck mouse wheel issue was fixed in #17493.
=> Refactor kinetic mouse key feature

keyboards/kprepublic/bm40hsrgb/keymaps/coffee/config.h, keyboards/kprepublic/bm40hsrgb/keymaps/coffee/keymap.c, keyboards/kprepublic/bm40hsrgb/keymaps/coffee/readme.md
I added a turbo function to my keymap that lets me pick a key and have it automatically spammed
I found there were some games I was playing that required me to use 1 key 
a lot and decided it would be easier to just write a turbo button feature 
To set the key that will be turbo-d, hold down the `TRBO_ST` key. It should now be light up solid white. To select a key, press any alpha, mod, or mouse key while the `TRBO_ST` key is lit up. To cancel selection, hold down the `TRBO_ST` key and the lighting should return to normal. To start or stop turbo, simply tap the `TRBO_ST` key
To adjust the speed of the turbo, I've created the `TRBO_TI` key. Simply tapping this key will adjust it in increments of 20ms with an upper limit of half a second and a lower limit of 60ms. If there's interest in …
=> Add a turbo feature to coffee keymap

quantum/rgb_matrix/animations/pixel_fractal_anim.h
Set a minimum middle column value of `1` to avoid integer rounding to zero on division when `MATRIX_COLS` is less than 2
Reported by @drashna on Discord when effect was tested with `MATRIX_COLS` = `1`
=> Set minimum middle column value

quantum/quantum.c
Move caps word handling before key override handling so if `KEY_OVERRIDE_INCLUDE_WEAK_MODS` is defined, key override will respect weak mods caused from caps word.
* #21258
=> Allow key override to respect weak mods caused by caps word

quantum/keycode_config.c
The `mod_config` function would swap modifiers as specified in the `keymap_config` object, but if the swapped modifiers were pressed at the same time (eg if you swapped ctrl and gui but pressed them both together) it would only apply one of the modifiers instead of both.
I refactored a bit to try and keep the simple bitwise operations that were there before.
I also added some comments to explain some of the code since some of it looks like copy-paste typos (comparing RALT to LALT for instance) but is actually intentional. 
- [ x] Core
- [x ] Bugfix
* 
- [ x] I have read the [**PR Checklist** …
=> bootmagic mods covering the case when swapped mods are pressed at the same time

quantum/mousekey.c
Diagonal mouse movement is calculated with equal x and y values times 1/sqrt(2). The current function uses bit shifting to divide and then truncates the fractional part to an integer, causing rounding errors.
Example, when x = -7 and y = 7, the current function will return a rounded-down value of `4` instead of `5`, when compared to a rounded floating point multiplication with 1/sqrt(2) (0.707106781):
| x | (x * 181) >> 8 | round(x * 0.707106781) |
|---|----------------|------------------------|
|-7 |     -5         |          -5            |
| 7 |      4         |           5            |
This change uses a simple sign checking ternary operator for the numerator. If negative, subtract half of the denominator before dividing. Otherwise add half of the denominator before dividing. The …
=> Refactor times inverse of sqrt 2 calculation

quantum/painter/lvgl/qp_lvgl.c, quantum/painter/qp.c, quantum/painter/qp_comms.c, quantum/painter/qp_draw_circle.c, quantum/painter/qp_draw_core.c, quantum/painter/qp_draw_ellipse.c, quantum/painter/qp_draw_image.c, quantum/painter/qp_draw_text.c
Haven't done an exhaustive review, seems like the codebase is correct in terms of "check before doing things", but the checks didn't account for users providing `NULL` pointers to the functions. Thus MCU would crash when checking `if (!pointer->valid)`, now we do `if (!pointer || !pointer->valid)`
Perhaps should have targeted `master`... 🤔 
Shall i add my name to headers after such a tiny change?
*
=> [Bugfix] Check `NULL` pointers on QP

quantum/keycode_config.c
This reverts commit ea87936b11a4396d607077d2ebb62e62c57c46a6.
Should not have gone to `master`.
=> Revert "bootmagic mods covering the case when swapped mods are pressed at the same time (#21320)"

drivers/led/apa102.c, drivers/sensors/pmw33xx_common.h, platforms/chibios/bootloaders/rp2040.c, platforms/chibios/drivers/i2c_master.c, platforms/chibios/drivers/serial.c, platforms/chibios/drivers/serial_protocol.c, platforms/chibios/drivers/serial_usart.c, platforms/chibios/drivers/serial_usart.h, platforms/chibios/drivers/uart.c, platforms/chibios/drivers/uart.h, platforms/chibios/drivers/vendor/RP/RP2040/ps2_vendor.c, platforms/chibios/drivers/vendor/RP/RP2040/serial_vendor.c, platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c, platforms/chibios/drivers/ws2812_bitbang.c, platforms/chibios/drivers/ws2812_pwm.c, platforms/chibios/drivers/ws2812_spi.c
=> drivers: remove direct `quantum.h` includes

keyboards/aleblazer/zodiark/keymaps/via/config.h
Remove two effects to bring firmware size under the limit
=> aleblazer/zodiark:via: Disable two RGB effects

docs/feature_mouse_keys.md, quantum/mousekey.h
* Add documentation for `MOUSEKEY_WHEEL_DELTA`
* Group `MOUSEKEY_WHEEL_DELTA` with the other wheel settings
=> Add MOUSEKEY_WHEEL_DELTA documentation

keyboards/xelus/rs60/rev1/info.json, keyboards/xelus/rs60/rev2_1/info.json
Fix RS60 indicators on_state to be 0 instead of default 1.
* Fix rs60 inverted led
=> [Keyboard][Update] Fix RS60 Indicators on_state

quantum/process_keycode/process_combo.c
Restore `wait.h` that was excluded by #21486. It is required for `wait_ms()`.
=> process_combo: restore wait.h header

quantum/split_common/split_util.c
#21507 removed quantum.h from split_util.c, but split watchdog needs bootloader.h for `mcu_reset(void)`.  Adds the bootloader.h only when split watchdog is enabled. 
* local testing
=> [Bug] Fix compilation error when Split Watchdog enabled

quantum/split_common/split_util.c
Reverts qmk/qmk_firmware#21543
Already done in #21551
=> Revert "[Bug] Fix compilation error when Split Watchdog enabled"

platforms/chibios/drivers/audio_dac_additive.c
Previously, if the user tried to build a firmware with audio enabled and `#define AUDIO_MAX_SIMULTANEOUS_TONES 1` to conserve CPU time, their firmware would fail to build with this error:
```
platforms/chibios/drivers/audio_dac_additive.c:91:73: error: excess elements in array initializer [-Werror]
91 | static float   active_tones_snapshot[AUDIO_MAX_SIMULTANEOUS_TONES] = {0, 0};
|                                                                          ^
```
This also affected the preset `#define AUDIO_DAC_QUALITY_VERY_HIGH`, which called up only one simultaneous tone at 88200 Hz.
This pull request changes the array initialization to allow for only one element if chosen.
=> Allow the user to select a single tone for the additive DAC

keyboards/era/era65/config.h, keyboards/era/era65/info.json
=> Update ERA65 PCB

keyboards/artemis/paragon/info.json
This PR fixes the paragon keyboard encoder step. Before this change, turning the encoder of two steps results in only one key press. After this change, one step = one key press.
=> Fix paragon keyboard encoder step

keyboards/keychron/s1/ansi/white/config.h, keyboards/keychron/s1/s1.c
Caps Lock indicator is already present for RGB backlight version, however, the white LED version currently doesn't have that. This PR adds the indicator light, bringing the white LED version on pair with RGB version.
*
=> Add Caps Lock indicator for Kyechron S1 white backlight version

keyboards/feker/ik75/keymaps/bkzshen/keymap.c, keyboards/feker/ik75/keymaps/default/keymap.c, keyboards/feker/ik75/keymaps/via/keymap.c
Status LEDs for Windows key lock and Scroll lock are messed up and should be swapped.
At the moment when you lock Windows key - LED with "S" lights up. The same when you Scroll lock lights up "W".
I was managed to fix it by swapping colors for indicators in keymap, now they are in line with the case markings.
* https://github.com/qmk/qmk_firmware/issues/19287
=> Fix scroll lock and windows lock status LEDs

platforms/chibios/drivers/audio_dac_additive.c
If `AUDIO_DAC_SAMPLE_WAVEFORM_SQUARE` is selected by the user, on the `dac_additive` driver, on a device where `AUDIO_DAC_OFF_VALUE` is not 0 or close to 0, `stop_note` did not work on the last concurrently active note, and the last note got stuck until a new one started, at which point that note got stuck instead.
One of the comments in `platforms/chibios/drivers/audio_dac_additive.c` explains why this happened:
```c
/* zero crossing (or approach, whereas zero == DAC_OFF_VALUE, which can be configured to anything from 0 to DAC_SAMPLE_MAX)
* ============================*=*========================== AUDIO_DAC_SAMPLE_MAX
*                          *       *
*                        *           *
* ---------------------------------------------------------
*                     * …
```
=> Fix stuck note with square wave in additive DAC

quantum/process_keycode/process_audio.c
The computations done in `float compute_freq_for_midi_note(uint8_t)`, to support the music mode feature, were invoking the `pow` function on double-precision inputs and immediately discarding any precision in excess of `float` from the `double`-precision output to make the return value. This is wasteful in both size and cycles, so I have made an edit to use `powf` and literals suffixed with `f` in that function.
As an example, on ARM MCUs having a single-precision FPU and the audio keycodes enabled, this saves around 4.5 KiB in firmware size.
=> Reduce needless precision in audio note frequency calculation

platforms/chibios/drivers/audio_dac_additive.c
In the additive DAC driver, calls to `fmod`, a `double`-precision function, got as inputs each element of `float dac_if[]` and their results were immediately assigned back to those `float` elements in the default implementation of `dac_value_generate`, and this was used to clamp the location within the bounds of the lookup table for the user-selected waveform. The added precision was thus immediately lost. Using `fmodf` instead saves cycles, especially important in the tight loop that repeatedly calls `dac_value_generate` in `dac_end`, and program space.
As an example, on my Moonlander (STM32F303, ARM with a single-precision FPU), switching `fmod` out for `fmodf` saves 436 bytes.
Boards whose MCUs have low clocks may crackle less from buffer underflows after this change, provided they use …
=> Remove needless precision in additive DAC sample generation

docs/feature_rgblight.md
Amend `RGBLIGHT_HUE_STEP` default value in `feature_rgblight.md` to match respective value in `quantum/rgblight/rgblight.c`
* n/a
=> Amend documented `RGBLIGHT_HUE_STEP` default value

keyboards/helix/rev3_4rows/config.h, keyboards/helix/rev3_4rows/keymaps/default/oled_display.c, keyboards/helix/rev3_4rows/keymaps/via/oled_display.c, keyboards/helix/rev3_5rows/config.h, keyboards/helix/rev3_5rows/keymaps/default/oled_display.c, keyboards/helix/rev3_5rows/keymaps/via/oled_display.c
The code for Helix rev3 boards could not be built with, e.g., `CONVERT_TO=rp2040_ce` due to invalid `#include <stdio.h>` in the keyboard level `config.h` (apparently the AVR version of that file contains guards against usage in assembly code, which was hiding the bug).  Move `#include <stdio.h>` to the C sources which need it.
* These commands were failing:
```sh
qmk compile -kb helix/rev3_4rows -km default -e CONVERT_TO=rp2040_ce
qmk compile -kb helix/rev3_4rows -km via -e CONVERT_TO=rp2040_ce
qmk compile -kb helix/rev3_5rows -km default -e CONVERT_TO=rp2040_ce
qmk compile -kb helix/rev3_5rows -km via -e CONVERT_TO=rp2040_ce
```
=> helix/rev3_4rows, helix/rev3_5rows: Fix build with converters

quantum/midi/qmk_midi.c
In #21496, I proposed a change to the note frequency calculation of the audio feature, and in a comment on that pull request, @sigprof pointed out that the MIDI code used a different calculation that was inaudibly imprecise, and distinct from the implementation used in the audio feature.
This pull request:
* unifies the calculation of the note frequency in the MIDI code to the existing code of the audio feature, calculating note pitches based on standard A at exactly 440 Hz;
* changes the calculation so that it's done on `float` rather than `double`, and using `powf` rather than `pow`, like #21496. Like that pull request, this one saves around 4.5 KB of firmware size on ARM with a float-precision FPU (like the STM32F303).
Tested on my Moonlander by playing a MIDI file with the current …
=> Unify MIDI note calculation with the audio feature (from #21496)

keyboards/handwired/onekey/stm32f3_disco/config.h, keyboards/handwired/onekey/stm32f3_disco/halconf.h, keyboards/handwired/onekey/stm32f3_disco/info.json, keyboards/handwired/onekey/stm32f3_disco/mcuconf.h, keyboards/handwired/onekey/stm32f3_disco/readme.md
This adds support for the [STM32F303 Discovery](https://www.st.com/en/evaluation-tools/stm32f3discovery.html) kit.
*
=> [Keyboard] Add STM32f3 Discovery onekey

tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/vusb/vusb.c
Running the "HID Tests" suite of the [USB 3 Command Verifier (USB3CV)](https://www.usb.org/document-library/usb3cvx64-tool) tool resulted in the following error:
```
(HID: 3.2.61) The report descriptor returned in response to a
GetDescriptor(Report) must be compliant with the HID specification.
Byte Number:   37h (  55d)
Data Field: 91 02
Mnemonic:  Output
Value: (Variable)
Errors: Error:   LOGICAL MAX MUST be bounded by Report 
```
The error stems from the fact that logical minimum and maximum are global items, which means that the next item in a report descriptor inherits the value from the previously set value. In this case the status leds item inherited the logical minimum (=0) and maximum (=255) from the keycodes item. As the status leds set a report size of 1 bit, wich can only hold …
=> [Fix] USB HID tests compliance

keyboards/crkbd/keymaps/colemad/config.h, keyboards/crkbd/keymaps/colemad/keycodes.h, keyboards/crkbd/keymaps/colemad/keymap.c, keyboards/crkbd/keymaps/colemad/readme.md
Add simple update to my personal keyboard layout: crkbd/colemad
=> update colemad keymap for the crkbd (corne) keyboard

keyboards/anavi/macropad12/config.h, keyboards/anavi/macropad12/halconf.h, keyboards/anavi/macropad12/info.json, keyboards/anavi/macropad12/keymaps/default/keymap.c, keyboards/anavi/macropad12/macropad12.c, keyboards/anavi/macropad12/mcuconf.h, keyboards/anavi/macropad12/readme.md, keyboards/anavi/macropad12/rules.mk
ANAVI Macro Pad 12 is a compact hot-swappable mechanical keyboard with 12 Cherry MX compatible switches, translucent key caps, USB-C, RP2040 microcontroller, backlighting and under lighting.
This commits adds initial QMK support for ANAVI Macro Pad 12 with:
- Default keymap
- Mini OLED I2C Display
- WS2812B RGB underlighting
- Backlighting (with PWMD5 and channel A as defined for GPIO 26 in the Raspberry Pi RP2040 datasheet)
The Neopixel on XIAO RP2040 is not supported as of the moment.
Add support for ANAVI Macro Pad 12 with Raspberry Pi RP2040 MCU and the following QMK features:
- Default keymap
- Mini OLED I2C Display
- WS2812B RGB underlighting
- Backlighting (with PWMD5 and channel A as defined for GPIO 26 in the [Raspberry Pi RP2040 datasheet page …
=> [Keyboard] Add ANAVI Macro Pad 12

docs/squeezing_avr.md
The documentation for LAYER_STATE_8BIT and LAYER_STATE_16BIT claim that 8BIT excludes 8 layers and 16BIT includes 16 layers. I'm told both are inclusive, so this corrects the documentation for 8BIT.
* I didn't file an Issue for this, as it seemed to me like the change stands on its own. If you prefer I file Issues in the future, please let me know!
(I don't know whether "I'm changing the documentation" counts for "My change requires a change to the documentation". If you have a preference, let me know, and I'll try to act accordingly in the future.)
I tested with `qmk docs`.
=> Correct "less than" to "up to" in squeezing_avr?id=layers

lib/python/qmk/cli/generate/keyboard_h.py
"Matrix data out of bounds" can be a little difficult to decipher particularly for new users. I've tweaked the wording and made it a bit more specific as to what the issue is. It also now flags row and col independently.
*
=> CLI: Improve error messages when layout key matrix row/col is OOB

quantum/process_keycode/process_dynamic_macro.c
This PR fixes an issue introduced in #21108 that prevents compilation in `avr-gcc` 5.4.0 on Linux when the Dynamic Macro feature is enabled.
```
$ qmk doctor
Ψ CLI version: 1.1.1
Ψ QMK home: /home/noroadsleft/Documents/GitHub/qmk_firmware
Ψ Detected Linux (Linux Mint 21.1).
Ψ Git branch: develop
Ψ Repo version: 0.21.6
Ψ - Latest develop: 2023-07-30 04:23:13 +0000 (fa4d51dab7) -- Merge remote-tracking branch 'origin/master' into develop
Ψ - Latest upstream/master: 2023-07-30 00:22:39 -0400 (14e14e9ab8) -- Correct "less than" to "up to" in squeezing_avr?id=layers (#21639)
Ψ - Latest upstream/develop: 2023-07-30 04:23:13 +0000 (fa4d51dab7) -- Merge remote-tracking branch 'origin/master' into develop
Ψ - Common ancestor with upstream/master: …
```
=> Fix Dynamic Macro Compilation for avr-gcc 5.4.0 + Linux

tmk_core/protocol/report.c
Problem:
`mousekey_task` spams empty hid reports with when a mouse key is pressed, causing resource exhaustion in the USB mouse endpoint.
Cause:
The check whether or not to send a new mouse report would always evaluate to true if a mouse key is pressed:
1. `mouse_report` has non-zero fields and `tmpmr` is a copy of this fields.
2. `mouse_report` is set to zero, `tmpmr` has now non-zero fields.
3. `has_mouse_report_changed` compares the two and evaluates to `true`.
4. an empty mouse report is sent.
Fix:
The check condition of `has_mouse_report_changed` will evaluate any empty record as unchanged, as mouse report data is relative and doesn't need to return to zero. An empty report will still be send by `register_mouse` on release of all mouse buttons.
* Choppy mouse keys with #21656
=> [Bug] Fix mouse-key spamming empty reports

quantum/audio/audio.c
`audio_play_melody`/`PLAY_SONG` may be called with a zero-note array if the user has enabled audio but disabled a particular melody with `SONG(NO_SOUND)`. Current code still calls `audio_play_note` in that case, which causes an out-of-bounds array access.
At least for the start-up melody, this access happens to work for most users, because during the DAC initialization, the RAM is close to full of `<00>` bytes, which means that `audio_play_note` is likely to be called with a frequency and a delay of 0, interpreted as silence.
However, this breaks down when either the address of the song array is at the very end of RAM or any of the bytes of what would be the first note, which are really the contents of the nearby variables, make up:
* NaN or infinity;
* a valid but bugged note frequency …
=> Audio: Don't play the first note of zero-note melodies

tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/chibios/usb_main.c
Changes to the suspend logic in #19780 removed the `USB_SUSPEND_WAKEUP_DELAY` waiting by accident. This PR restores it.
*
=> [Bug] Restore usb suspend wakeup delay

docs/pr_checklist.md
Custom keycodes don't make sense to #define (anymore?), so this removes the reference to that. It keeps the rule about beginning with SAFE_RANGE.
I also removed the leading space in ` = SAFE_RANGE`, because it looked weird to me, and there are zero other instances in the code of an inline code block beginning with a leading space and then an equals.
(none)
=> Clarify custom keycode enum requirement for PRs

keyboards/cxt_studio/info.json, keyboards/cxt_studio/keymaps/via/keymap.c, keyboards/cxt_studio/keymaps/via/rules.mk
Also changes the vendor and product to values from the manufacturer.
*
=> [Keymap] Add Via keymap for CXT Studio

keyboards/gmmk/pro/rev1/ansi/keymaps/andrebrait/config.h, keyboards/gmmk/pro/rev1/ansi/keymaps/andrebrait/keymap.c, keyboards/gmmk/pro/rev1/ansi/keymaps/andrebrait/rules.mk
* Small performance updates
* Use fast_timer_t
* Inline functions called during matrix scans and record processing
*
=> [Keymap] Update andrebrait keymap for GMMK Pro

keyboards/chouchou/config.h, keyboards/chouchou/info.json, keyboards/chouchou/keymaps/default/keymap.c, keyboards/chouchou/readme.md
Add [Chouchou](https://github.com/dlip/chouchou) keyboard and [Taipo](https://inkeys.wiki/en/keymaps/taipo) layout implementation
=> [Keyboard] Add Chouchou keyboard

keyboards/willoucom/keypad/info.json, keyboards/willoucom/keypad/keymaps/default/keymap.json, keyboards/willoucom/keypad/keymaps/via/keymap.json, keyboards/willoucom/keypad/readme.md, keyboards/willoucom/keypad/rules.mk
=> [Keyboard] add willoucom/keypad

drivers/led/apa102.c
Removing quantum.h from apa102.c removed chibios_config.h include, which breaks compilation as it depends on the CPU_CLOCK define. 
Can verify that it works on STM32F405 
* Testing locally with Sparkfun input and display micromod carrier board
=> [Bug] Fix compilation error for APA on ChibiOS

keyboards/drop/shift/v2/v2.c
Headers have changed on develop, which produces:
```
make clean drop/shift/v2:default
QMK Firmware 0.21.6
Making drop/shift/v2 with keymap default
Generating: .build/obj_drop_shift_v2_default/src/info_deps.d                                        [OK]
arm-none-eabi-gcc (Arch Repository) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
Generating: .build/obj_drop_shift_v2_default/src/info_config.h                                     Generating: .build/obj_drop_shift_v2_default/src/default_keyboard.c                                Generating: .build/obj_drop_shift_v2_default/src/default_keyboard.h …
```
=> Fix drop/shift/v2 compilation

quantum/rgb_matrix/animations/jellybean_raindrops_anim.h
After #21169, `rgb_matrix_indicators()` was limited to running on the final render iteration. Since the `jellybean_raindrops` animation immediately returns false after updating a single LED, `rgb_effect_params.iter` is never incremented enough for `rgb_matrix_indicators()` to run.
This change also brings `jellybean_raindrops` more in line with `raindrops`.
=> fix: restore rgb matrix indicators to jellybean_raindrops animation

keyboards/splitkb/aurora/sofle_v2/rev1/info.json
Followup to #21594, fixing boards that were missed/added since.
*
=> Fix keyboards with old RGB driver names

keyboards/keychron/c2_pro/config.h, keyboards/keychron/c2_pro/matrix.c
Although `keychron/c2_pro/ansi/rgb` and `keychron/c2_pro/ansi/white` use the same custom matrix code, the matrix layouts are slightly different; in particular, only the `keychron/c2_pro/ansi/white` board actually uses column 19.  However, the handling of column 19 in the custom matrix code was broken, therefore that column did not work.
Looks like the custom matrix code assumes that `SHIFT_COL_END` refers to the last column connected to the shift register, and not to the column past that; so the value of `SHIFT_COL_END` needs to be changed from 19 to 18 (columns 11...18 are connected to the shift register, and column 19 is connected to the C14 pin).
Also the code which was determining `SIZE_T` and `UNSELECT_ALL_COL` had an off-by-one bug when counting the required number of bits (again …
=> keychron/c2_pro/ansi/white: Fix column 19 in the custom matrix

platforms/avr/platform.mk
GCC 13 needs the same workaround as GCC 12.
To avoid having to maintain an ever-growing list of broken versions apply the workaround wherever it can be used.
If at some point a fixed version of GCC is released the workaround can be disabled for those fixed versions.
See #17064
=> Generalize AVR -Werror=array-bounds workaround

docs/feature_macros.md
* Updated the macro example using 'duration', which requires a number not a string.
=> Docs - corrected duration example, should be number not string

data/mappings/info_config.hjson, lib/python/qmk/cli/info.py, lib/python/qmk/info.py
~~Current hitting preprocessor isues:~~
```
⚠ acheron/apollo/87h/gamma: RGB_MATRIX_LED_COUNT->rgb_matrix.led_count: invalid literal for int() with base 10: 'DRIVER_1_LED_TOTAL'
⚠ aeboards/satellite/rev1: RGB_MATRIX_LED_COUNT->rgb_matrix.led_count: invalid literal for int() with base 10: 'ISSI_DRIVER_TOTAL'
```
~~Parsing is currently disabled due to the above issue. A 2nd pass will refactor keyboards, but this at least allows dd configuration in the short term.~~
Parsing is no longer important as the value is generated only from the length of the LED array.
*
=> Add *_MATRIX_LED_COUNT generation

keyboards/input_club/ergodox_infinity/keymaps/not-quite-neo/keymap.c, keyboards/planck/keymaps/rootiest/keymap.c, users/romus/romus.c, users/rupa/unicode.c, users/spidey3/spidey3.c
`register_unicode()` and `send_unicode_string()` being needlessly reimplemented.
*
=> Clean up Unicode API usage in user keymaps

keyboards/ferris/keymaps/test/keymap.c
Visually organize the `ferris:test` keymap for prettier source.
I have also changed the two thumb clusters to output printable numbers as described in the keymaps readme.
=> chore(ferris/test): visually format keymap

layouts/default/60_jis/default_60_jis/keymap.c
One key too many in `layouts/default/60_jis/default_60_jis/keymap.c` - erroneous key removed.
*
=> [Hotfix] fix 60_jis keymap.c

keyboards/idank/sweeq/config.h, keyboards/idank/sweeq/info.json, keyboards/idank/sweeq/keymaps/default/config.h, keyboards/idank/sweeq/keymaps/default/keymap.json, keyboards/idank/sweeq/keymaps/default/readme.md, keyboards/idank/sweeq/keymaps/via/config.h, keyboards/idank/sweeq/keymaps/via/keymap.c, keyboards/idank/sweeq/keymaps/via/rules.mk, keyboards/idank/sweeq/readme.md, keyboards/idank/sweeq/rules.mk
This version of the Ferris sweep uses diodes rather than directly soldering the switches to the MCU pins. The primary
goal is to free up the SDA/SCL pins so they can be used by auxiliary devices such as a trackball, trackpoint or an OLED
screen.
=> [keyboard] add sweeq, a ferris/sweep variant with diodes

keyboards/nullbitsco/snap/keymaps/bongo_reactive/keymap.c, keyboards/nullbitsco/snap/keymaps/oled/keymap.c, keyboards/nullbitsco/snap/keymaps/typehud/keymap.c
One of the breaking changes this cycle broke the SNAP OLED keymaps due to an invalid comparison:
```
./keyboards/nullbitsco/snap/keymaps/oled/keymap.c:122:30: error: invalid operands to binary != (have 'led_t' {aka 'union <anonymous>'} and 'led_t' {aka 'union <anonymous>'})
if (persistent_led_state != led_state) {
```
Comparing the raw LED state fixes it.
* N/A
=> nullbitsco/snap: fix broken keymaps

tmk_core/protocol/host.h
=> Remove old `IS_LED_ON/OFF()` macros

keyboards/redragon/k667/info.json
From the original PR,
> Because this keyboard is designed to support only Windows, it is set up with only two layers.
Not really a good reason to artificially limit the layer count, when the default eeprom provisioning allows more.
*
=> redragon/k667: Remove 2 layer VIA restriction

keyboards/bpiphany/kitten_paw/keymaps/ickerwx/keymap.c, keyboards/crkbd/keymaps/vlukash_trackpad_right/keymap.c, keyboards/dm9records/plaid/keymaps/gipsy-king/keymap.c, keyboards/ergodox_ez/keymaps/pvinis/keymap.c, keyboards/gboards/butterstick/sten.h, keyboards/gboards/georgi/sten.h, keyboards/handwired/traveller/keymaps/default/keymap.c, quantum/quantum.h, users/romus/romus.c
`mousekey.h` should be implicitly available to keymap code through `quantum.h` if it is enabled. See https://github.com/qmk/qmk_firmware/pull/19801#pullrequestreview-1513525678
*
=> Add `mousekey.h` include to `quantum.h`

keyboards/anavi/macropad12/info.json, keyboards/anavi/macropad12/keymaps/default/keymap.c
[title]
cc @leon-anavi (keyboard maintainer)
=> ANAVI Macro Pad 12: rename LAYOUT to LAYOUT_ortho_4x3

data/mappings/info_config.hjson, data/mappings/info_rules.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md
Supersedes #21604.
From some discussions, wear leveling has no intent to work with other subsystems. Having it as a top level key when its tightly coupled to eeprom just pollutes the json. Also added some defines for size, and updated docs.
*
=> Implement data driven wear leveling

platforms/chibios/boards/GENERIC_PROMICRO_RP2040/configs/mcuconf.h, platforms/chibios/boards/GENERIC_RP_RP2040/configs/mcuconf.h, platforms/chibios/boards/QMK_BLOK/configs/mcuconf.h, platforms/chibios/boards/QMK_PM2040/configs/mcuconf.h
An issue I noticed when playing with the rtc hardware stuff.
=> Add RTC IRQ Priority to RP2040 board files

drivers/led/apa102.c
Not sure if this is the best way to handle this... but I can confirm that it does work. (tested on micromod "input and display" carrier board, with RP2040 processor board)
* Compilation issue when testing
=> Enable RP2040 support for apa102 RGB LED driver

keyboards/binepad/pixie/config.h, keyboards/binepad/pixie/info.json, keyboards/binepad/pixie/keymaps/default/keymap.c, keyboards/binepad/pixie/keymaps/default/rules.mk, keyboards/binepad/pixie/keymaps/via/config.h, keyboards/binepad/pixie/keymaps/via/keymap.c, keyboards/binepad/pixie/keymaps/via/rules.mk, keyboards/binepad/pixie/readme.md, keyboards/binepad/pixie/rules.mk
Adding Binepad PIXIE keyboard, an RP2040 based 2x2 macro keypad featuring 2 rotary encoders and 2 macro buttons.
* (n/a)
=> [Keyboard] Add Binepad Pixie

platforms/chibios/boards/GENERIC_WB32_F3G71XX/board/board.c, platforms/chibios/boards/GENERIC_WB32_FQ95XX/board/board.c
There are some computers that need to add a wait implementation when remote wakeup
*
=> Fixed WB32 MCU remote wakeup issue

keyboards/cannonkeys/brutalv2_1800/rules.mk, keyboards/cannonkeys/caerdroia/rules.mk, keyboards/cannonkeys/ortho48v2/rules.mk, keyboards/cannonkeys/ortho60v2/rules.mk, keyboards/cannonkeys/typeb/rules.mk
Default `vendor` driver equates to wear leveling + rp2040_flash so specifying it at the keyboard level is redundant.
*
=> Remove duplication of RP2040 EEPROM defaults

lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/cli/generate/rules_mk.py
Changes keymap level generation from:
```c
#ifndef BOOTMAGIC_LITE_COLUMN
#endif // BOOTMAGIC_LITE_COLUMN
```
```make
BOOTLOADER ?= qmk-dfu
```
to
```c
#undef BOOTMAGIC_LITE_COLUMN
#define BOOTMAGIC_LITE_COLUMN 1
```
```make
BOOTLOADER = qmk-dfu
```
This should ensure that configuration gets correctly applied.
* Fixes #21958
=> Generate keymap.json config options more forcefully

keyboards/bastardkb/charybdis/3x5/blackpill/info.json, keyboards/bastardkb/charybdis/3x5/blackpill/rules.mk, keyboards/bastardkb/charybdis/3x6/blackpill/info.json, keyboards/bastardkb/charybdis/3x6/blackpill/rules.mk, keyboards/bastardkb/charybdis/4x6/blackpill/info.json, keyboards/bastardkb/charybdis/4x6/blackpill/rules.mk, keyboards/bastardkb/scylla/blackpill/info.json, keyboards/bastardkb/scylla/blackpill/rules.mk, keyboards/bastardkb/skeletyl/blackpill/info.json, keyboards/bastardkb/skeletyl/blackpill/rules.mk, keyboards/bastardkb/tbkmini/blackpill/info.json, keyboards/bastardkb/tbkmini/blackpill/rules.mk, keyboards/custommk/ergostrafer/info.json, keyboards/custommk/ergostrafer/rules.mk, keyboards/custommk/evo70_r2/info.json, keyboards/custommk/evo70_r2/rules.mk, keyboards/handwired/tractyl_manuform/5x6_right/f303/info.json, keyboards/handwired/tractyl_manuform/5x6_right/f303/rules.mk, keyboards/handwired/tractyl_manuform/5x6_right/f411/info.json, keyboards/handwired/tractyl_manuform/5x6_right/f411/rules.mk, keyboards/tzarc/djinn/info.json, keyboards/tzarc/djinn/rules.mk, keyboards/tzarc/ghoul/info.json, keyboards/tzarc/ghoul/rules.mk
=> Migrate spi EEPROM_DRIVER to info.json

keyboards/jaykeeb/sebelas/info.json, keyboards/jaykeeb/sebelas/keymaps/default/keymap.c, keyboards/jaykeeb/sebelas/keymaps/via/keymap.c
Existing implementation uses Community Layout names, but the board layout doesn't conform to the layouts implied.
- Rename `LAYOUT_65_ansi_blocker` to `LAYOUT_ansi_blocker`
- Rename `LAYOUT_65_ansi_blocker_split_bs` to `LAYOUT_ansi_blocker_split_bs`
- Rename `LAYOUT_65_ansi_blocker_tsangan` to `LAYOUT_ansi_blocker_tsangan`
- Rename `LAYOUT_65_ansi_blocker_tsangan_split_bs` to `LAYOUT_ansi_blocker_tsangan_split_bs`
cc @alabahuy (keyboard maintainer)
=> Jaykeeb Sebelas: Standardize Layout Names

keyboards/binepad/bnr1/v2/rules.mk, keyboards/doio/kb16/rev2/rules.mk, keyboards/gmmk/gmmk2/p65/ansi/rules.mk, keyboards/gmmk/gmmk2/p65/iso/rules.mk, keyboards/phage_studio/pila87/rules.mk, keyboards/xelus/kangaroo/rev2/rules.mk, keyboards/xelus/rs60/rev2_1/rules.mk
`wear leveling + efl` is the default for `STM32L412`. `STM32F103`, and `WB32F3G71`.
*
=> Remove duplication of EEPROM defaults

keyboards/monsgeek/m1/info.json
Apply vertical offset to the arrow keys.
cc @jonylee1986 (keyboard maintainer)
=> MonsGeek M1: Correct layout data

lib/python/qmk/cli/format/json.py
This adds an in-place mode to the format-json command.
It's off by default and requires the '-i' or '--inplace' flag to be set to run in-place
This will make it easier to format info.jsons without having to do an extra move operation
*
=> `qmk format-json`: Add an in-place mode to format json command

builddefs/common_rules.mk
Instead of taking all prerequisites and filtering out everything that is not an object just use the objects directly.
It is both easier to understand and also more robust in case other non-object files are added to the prerequisites in the future.
=> directly use object files when linking ELF

builddefs/common_features.mk, docs/reference_info_json.md, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3218.h, keyboards/wilba_tech/rama_works_m60_a/keymaps/zyber/config.h, keyboards/wilba_tech/rama_works_m6_b/config.h, keyboards/wilba_tech/wt_rgb_backlight.c, quantum/rgb_matrix/rgb_matrix.h, quantum/rgb_matrix/rgb_matrix_drivers.c
This driver was only used in a single WT board, so it was fairly rudimentary. I've updated it to align better with the other ISSI LED drivers, in case someone wants to make a <= 6 key board with RGB Matrix 🤷
*
=> Complete RGB Matrix support for IS31FL3218

platforms/chibios/drivers/uart.h
After [quantum.h was removed from several driver files](https://github.com/qmk/qmk_firmware/commit/b6d9409d2f8eaa9888fce1611bcb9a23d97be150), I was unable to compile by firmware, which is redox-w-esque, due to missing pin and chibios defs.
After working with @infinityis, [who reached out on discord](https://discord.com/channels/440868230475677696/867530715192885269/1151599331086970880), we decided to add the appropriate chibios header files to uart.h.
* No issue was created for this PR
=> add missing gpio and chibios defs to uart.h

keyboards/artemis/paragon/hotswap/info.json, keyboards/artemis/paragon/info.json, keyboards/artemis/paragon/soldered/info.json
For the paragon keyboard, the encoder pins are different on the hotswap and on the soldered PCB. It was not the case in the source code, although the binary files provided by the designer are fine.
Tested on both my official hotswap and soldered PCB, I can provide picture of the pcb trace leading to the PIN if necessary.
N/A
=> Fix paragon encoder pinout for soldered version

keyboards/geistmaschine/macropod/config.h, keyboards/geistmaschine/macropod/info.json
Users reported issues with the device not working after their Apple hardware (mainly Apple silicon) woke up from suspend/sleep. Adding USB_SUSPEND_WAKEUP_DELAY of 200ms fixed this issue for all users.
* Add 200ms USB_SUSPEND_WAKEUP_DELAY
* Enable mousekey since users requested the change
* Keyboard not responsive after Apple hardware wakes up from suspend/sleep
* Mousekeys support missing
=> geistmaschine/macropod: fix issues waking up after suspend on apple devices

platforms/chibios/drivers/vendor/RP/RP2040/ps2_vendor.c
=> Add missing gpio include to ps2 vendor

keyboards/riot_pad/config.h, keyboards/riot_pad/halconf.h, keyboards/riot_pad/info.json, keyboards/riot_pad/keymaps/default/keymap.c, keyboards/riot_pad/keymaps/via/keymap.c, keyboards/riot_pad/keymaps/via/rules.mk, keyboards/riot_pad/mcuconf.h, keyboards/riot_pad/readme.md, keyboards/riot_pad/rules.mk
Add the RiotPad to QMK. Additionally added both a default and VIA keymap.
=> Add riot pad

keyboards/sapuseven/macropad12/info.json, keyboards/sapuseven/macropad12/keymaps/default/keymap.c, keyboards/sapuseven/macropad12/keymaps/via/keymap.c
[title]
cc @SapuSeven (keyboard maintainer)
=> SapuSeven MacroPad12: rename LAYOUT to LAYOUT_ortho_3x4

keyboards/bastardkb/charybdis/3x5/v2/splinky_2/rules.mk, keyboards/bastardkb/charybdis/3x5/v2/splinky_3/rules.mk, keyboards/bastardkb/charybdis/3x6/v2/splinky_2/rules.mk, keyboards/bastardkb/charybdis/3x6/v2/splinky_3/rules.mk, keyboards/bastardkb/charybdis/4x6/v2/splinky_2/rules.mk, keyboards/bastardkb/charybdis/4x6/v2/splinky_3/rules.mk, keyboards/bastardkb/dilemma/3x5_2/assembled/rules.mk, keyboards/bastardkb/dilemma/3x5_2/splinky/rules.mk, keyboards/bastardkb/dilemma/3x5_3/rules.mk, keyboards/bastardkb/scylla/v2/splinky_2/rules.mk, keyboards/bastardkb/scylla/v2/splinky_3/rules.mk, keyboards/bastardkb/skeletyl/v2/splinky_2/rules.mk, keyboards/bastardkb/skeletyl/v2/splinky_3/rules.mk, keyboards/bastardkb/tbkmini/v2/splinky_2/rules.mk, keyboards/bastardkb/tbkmini/v2/splinky_3/rules.mk, keyboards/crowboard/rules.mk
Neither should be set, especially `ALLOW_WARNINGS` as that will mask non rp2040 specific issues.
*
=> Remove ALLOW_WARNINGS and PICO_INTRINSICS_ENABLED

data/schemas/definitions.jsonschema, data/schemas/keyboard.jsonschema
On 21894 and 21893, the following is not flagged by lint:
```json
"animations": {
"SOLID_COLOR": true,
"ALPHAS_MODS": true,
"GRADIENT_UP_DOWN": true,
"GRADIENT_LEFT_RIGHT": true,
"BREATHING": true,
"BAND_SAT  // white background ver. of _BAND_VAL": true,
```
Caps is one thing, but spaces and comments just would never work.
*
=> Restrict "feature" and "animation" keys

builddefs/common_features.mk, drivers/led/issi/is31flcommon.h, quantum/led_matrix/led_matrix.h, quantum/led_matrix/led_matrix_drivers.c, quantum/rgb_matrix/rgb_matrix.h, quantum/rgb_matrix/rgb_matrix_drivers.c
For consistency, the idea being to do this for all features with driver selection: `FEATURENAME_DRIVERNAME`.
Removed `STM32_I2C` defines as well since they don't seem to be referenced anywhere?
*
=> LED/RGB Matrix: prefix driver defines

docs/feature_oled_driver.md
I validated the SSD1306 128x64 OLED works as expected with an ARM processor (Pico) while building this board: https://github.com/JellyTitan/Sofle-Pico
* 
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
=> Added OLED SSD1306 128x64 to the verified working table

lib/python/qmk/cli/mass_compile.py
In a previous PR, Visual Studio Code _"helpfully"_ fixed up tabs by replacing with spaces.
CI didn't like that too much.
=> Fix up `qmk mass-compile` makefile indenting.

drivers/sensors/pmw3320.c, drivers/sensors/pmw3360.c, drivers/sensors/pmw3389.c
Move subtraction after `CONSTRAIN` to prevent unsigned int wrap on PMW3320, PMW3360, PMW3389
These sensors expect a value between `0` and `CPI_MAX/CPI_STEP - 1` Subtracting 1 from `cpi/CPI_STEP` within the `CONSTRAIN` macro causes a wrap to the maximum when attempting to set `cpi` less than `CPI_STEP`.
Setting the bounds for `CONSTRAIN` to be between `1` and `CPI_MAX/CPI_STEP` allows impossibly small `cpi` values to be set to the minumum CPI of the sensor, instead of the maximum.
Tested on Ploopy Classic Trackball (PMW3360)
* Fix incorrect handling of cpi when setting a cpi that is smaller than the minimum cpi on PMW3360, PMW3389, PMW3320
=> Fix lower cpi bound on PMW33XX

quantum/mousekey.c
Mouse movement will continue its acceleration in the new direction of an overlapping mouse key press. This behaviour can be especially jarring when the new overlapping key is for the opposite direction.
This change will restart the acceleration before processing the new overlapping direction for a smoother transition.
=> Improve directional transition of overlapping mouse keys

platforms/chibios/drivers/audio_dac_additive.c
In current code, the interrupt that fires when the DAC needs more samples could take so long to process that another interrupt is already waiting, as does another once that one is done, and so on. As a result, processing DAC interrupts may be the only thing the CPU can do. This prevents any code from working which would be able to request a note to be stopped:
* the matrix scan code, which would allow a note from the audio feature or Audio Clicky to be stopped if the user had released the key that started the note, had the CPU had the opportunity to get to the next matrix scan;
* the code for MIDI over USB, which would allow a NOTEOFF event to stop a note, had the CPU had the opportunity to get to the next USB interrupt, which has a lower priority than the DAC interrupt in the ChibiOS …
=> Optimize the additive DAC code, fixing performance-related hangs

tmk_core/protocol/arm_atsam/usb/udi_device_epsize.h, tmk_core/protocol/usb_descriptor.h
...to accommodate mouse reports with a size of 9 bytes, which happens
when the extended 16 bit movement range is activated by defining
`MOUSE_EXTENDED_REPORT` and `MOUSE_SHARED_EP` is NOT set.
* Miss match in mouse endpoint packetsize when `mouse_report_t` has `MOUSE_EXTENDED_REPORT` set
=> [Core] Bump mouse endpoint packet size to 16 bytes

quantum/process_keycode/process_combo.c
combo_ref_from_layer doesn't respect different default layer when the default layer is not layer 0.
#21780
*
=> Fix combo_ref_from_layer respect different default layer [#21780]

layouts/community/ortho_4x12/drashna/rules.mk
This is a very simple pull request that fixes a possible variable name misspelling in `layouts/community/ortho_4x12/drashna/rules.mk`: `LAYOUTS_HAS_RGB` is spelled without an `S` at `LAYOUTS`.
As most of the other `rules.mk` spell it with an `S`, I suppose this is a mistake. I am new to QMK and not sure how to properly test this keyboard layout.
=> Fix variable misspelling

platforms/test/timer.c, quantum/debounce/none.c, quantum/debounce/sym_defer_g.c, quantum/debounce/sym_eager_pr.c, quantum/debounce/tests/asym_eager_defer_pk_tests.cpp, quantum/debounce/tests/debounce_test_common.cpp, quantum/debounce/tests/debounce_test_common.h, quantum/debounce/tests/none_tests.cpp, quantum/debounce/tests/rules.mk, quantum/debounce/tests/sym_defer_pk_tests.cpp, quantum/debounce/tests/sym_defer_pr_tests.cpp, quantum/debounce/tests/sym_eager_pk_tests.cpp, quantum/debounce/tests/sym_eager_pr_tests.cpp, quantum/debounce/tests/testlist.mk
* Add tests for none
* Add check for consistency between cooked_changed and actual result
* Add check for ensuring debounce never reads the timer more than once
* Fix sym_eager_pr incorrectly returning cooked_changed as false
* Fix sym_defer_g reading the timer twice when debouncing
* Save some useless memory copies on none when there are no changes
* Restructure sym_defer_g so it is smaller on AVR
*
=> [Enhancement] Improvements for debounce test coverage + bug fixes for sym_defer_g and sym_eager_pr

drivers/ps2/ps2_mouse.c
Similar to drag scroll implementations elsewhere, accumulate the X & Y coordinates until enough for a wheel tick. Save and apply the remainder towards next wheel tick.
*
=> Take care of scroll divisor remainders for PS/2 drag scroll

quantum/action.c, tests/basic/test_one_shot_keys.cpp
This change follows #19214 by @kosorin, which allowed mod-tap hold action on one shot layers. The purpose of this change is to do the same for one shot mods and allow them on one shot layers.
I attempted adding `OSM(MOD_LSFT)` on one of my `OSL` activated layers in order to use it along with accented letters I have on that layer. I realized it didn't work and after looking into the code I noticed the condition that prevents deactivating one shot layers with mods, which wasn't considering one shot mods, but was considering mod-tap. So it seemed like a simple oversight, doesn't seem intended that OSM wasn't considered. At least I can't think of a reason why it would be supported with other mods but not with OSM.
*
=> Fix OSM on a OSL activated layer

docs/feature_ps2_mouse.md, platforms/chibios/drivers/vendor/RP/RP2040/ps2_vendor.c
Document the use of the PIO state machine code for RP2040 devices as an alternative implementation of a PS/2 interface.
I got help on Discord setting up the PS/2 feature with an RP2040. This is basically the info that I needed and the place where I would have expected it, so let's put this quick note here?!
*
=> Document the RP2040-specific PS/2 implementation

platforms/chibios/boards/GENERIC_STM32_F446XE/configs/config.h, platforms/chibios/boards/GENERIC_STM32_G431XB/configs/config.h
As per the title. The default wasn't present in 'G431. The rest are fine.
Also a slight bit of cleanup for irrelevant comments.
Tested on `handwired/onekey/nucleo_g431rb:reset`.
=> Fix entry into bootloader for STM32G431.

docs/feature_programmable_button.md
The usage of programmable buttons should 0x09, not 0x07 according to HID Usage Table v1.4. Also confirmed on MacOS that the key event report usage==0x09.
*
=> Fix doc for programmable buttons.

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md
Supersedes #21598.
Also adds support for limits and updates docs.
*
=> More data driven RGB/LED Matrix config

builddefs/common_features.mk, docs/reference_info_json.md, drivers/led/issi/is31fl3736-simple.c, drivers/led/issi/is31fl3736-simple.h, keyboards/wilba_tech/wt60_a/config.h, keyboards/wilba_tech/wt60_a/rules.mk, keyboards/wilba_tech/wt65_a/config.h, keyboards/wilba_tech/wt65_a/rules.mk, keyboards/wilba_tech/wt65_b/config.h, keyboards/wilba_tech/wt65_b/rules.mk, keyboards/wilba_tech/wt75_a/config.h, keyboards/wilba_tech/wt75_a/rules.mk, keyboards/wilba_tech/wt75_b/config.h, keyboards/wilba_tech/wt75_b/rules.mk, keyboards/wilba_tech/wt75_c/config.h, keyboards/wilba_tech/wt75_c/rules.mk, keyboards/wilba_tech/wt80_a/config.h, keyboards/wilba_tech/wt80_a/rules.mk, keyboards/wilba_tech/wt_mono_backlight.c, quantum/led_matrix/led_matrix.h, quantum/led_matrix/led_matrix_drivers.c
The 3736 driver had some specialised functions for the WT mono backlight code. For consistency, I've split this out into `is31fl3736-simple`, added LED Matrix support, and updated the affected boards.
*
=> is31fl3736: extract single-color API

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, lib/python/qmk/info.py
* incorrect jsonschema type for `react_on_keyup`
* just wrong... will look at adding something in CI to try and stop this slipping through in the future
* `"value_type": "bool"` currently does the wrong thing for parsing defines with no value
* existing issue
* `#define FORCE_NKRO` incorrectly becomes `"force_nkro" :false`
* `parse_config_h_file` correctly parses to `True` bool -> `_config_to_json` then only checks for string values
*
=> Fix parsing/validation for 21939

lib/python/qmk/cli/compile.py, lib/python/qmk/cli/generate/compilation_database.py
=> Allow inline generation of compile_commands.json while doing a `qmk compile`, using `--compiledb`

keyboards/teleport/native/ansi/keymaps/perfmode/config.h, keyboards/teleport/native/ansi/keymaps/perfmode/keymap.c, keyboards/teleport/native/ansi/keymaps/perfmode/rules.mk, keyboards/teleport/native/info.json, keyboards/teleport/native/iso/keymaps/perfmode/config.h, keyboards/teleport/native/iso/keymaps/perfmode/keymap.c, keyboards/teleport/native/iso/keymaps/perfmode/rules.mk, keyboards/teleport/native/native.c
This PR makes a few changes to the Native keyboard. First, it enables LTO for all keymaps, and replaces a `keyboard_post_init_user()` function with `keyboard_post_init_kb()` in native.c - as far as I am aware, _user functions should be used in keymaps, _kb functions in board-wide code files.
In addition, on the highly customized "perfmode" keymaps, it will replace the matrix delays with nops and add `OPT=2` to rules.mk. Both together lead to a significant speed-up of matrix scan rates, from about 3 kHz to 13.5 kHz (disabled LEDs, or static LEDs together with PR #21134).
The board was originally tested and working fine with `OPT=3`, but I was told `3` could lead to issues with custom keymaps enabling other features by other users eventually, so decided to play safe and stay at `2`. 13.5 …
=> teleport/native: switch from wrongly used user to kb function, boost matrix scan rate

docs/newbs_getting_started.md
Remove rosetta instructions for Apple Silicon
* fixes #22169
=> Remove rosetta instructions for Apple Silicon

quantum/painter/lvgl/qp_lvgl.c
In the qp_lvgl_attach function, when reallocating memory for the color_buffer, we were not properly handling the case when realloc fails, leading to potential memory leaks. This change ensures that memory is properly managed, and potential memory leaks are prevented in the qp_lvgl_attach function.
*
=> Fix memory leak in realloc failure handling

keyboards/monstargear/xo87/solderable/info.json
Correct key positions on the bottom row for `LAYOUT_tkl_ansi_tsangan`.
=> Monstargear XO87 Soldered: correct layout data

.github/workflows/lint.yml, data/mappings/keyboard_aliases.hjson, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/ci/validate_aliases.py, lib/python/qmk/commands.py, lib/python/qmk/keyboard.py
* Validates that all aliases exist in the repo.
* Recursively follows aliases
* Adds aliases check to CI lint
* Removes non-functional keyboard count lint check -- will fix it up later.
As of now, some don't:
```
% qmk ci-validate-aliases                               
☒ Keyboard alias angel64 has a target that doesn't exist: angel64/alpha
☒ Keyboard alias atom47/rev2 has a target that doesn't exist: maartenwut/atom47/rev2
☒ Keyboard alias atom47/rev3 has a target that doesn't exist: maartenwut/atom47/rev3
☒ Keyboard alias bm16a has a target that doesn't exist: kprepublic/bm16a
☒ Keyboard alias bm60poker has a target that doesn't exist: kprepublic/bm60poker
☒ Keyboard alias bm60rgb has a target that doesn't exist: kprepublic/bm60rgb
☒ Keyboard alias bm60rgb_iso has a target that doesn't …
```
=> Add `qmk ci-validate-aliases`

keyboards/handwired/dactyl_minidox/config.h, keyboards/handwired/dactyl_minidox/info.json, keyboards/handwired/dactyl_minidox/rules.mk
- migrate `rules.mk` to `info.json`
- condition RGB_MATRIX information in `config.h`
* n/a
=> partially modernize `dactyl_minidox`

quantum/pointing_device/pointing_device_auto_mouse.c
Building with POINTING_DEVICE_AUTO_MOUSE_ENABLE failes because the `string.h` header file is not included, resulting in an error when calling memset.
Add `<string.h>` to `pointing_device_auto_mouse.c` .
* Fixes #22228
=> Fix build error when Automatic Mouse Layer is enabled

platforms/avr/flash.mk
avrdude: Version 7.2 changes the text output from "could not find USB device with" to "cannot find USB device with".
This should fix issue #22234
*  Fixes #22234
=> avrdude: Version 7.2 changes the text output

docs/feature_unicode.md
=> Fix old usage of UNICODE_MODE_MAC

keyboards/blu/vimclutch/info.json, keyboards/blu/vimclutch/readme.md
Because the footswitch is on a long lead, the traditional QMK matrix scanning provides a lot of interference.  Hardware revision B  is able to fix this by making the foot pedal (and all other keys) direct keys.
This section is intentionally left blank.  The previous section provided enough description for a small change.
*  This section is intentionally left blank.
=> Keyboard change blu/vimclutch to hardware revision B.

docs/pr_checklist.md
Small change to remove a mention of personal keymaps still left after #21848.
=> Reword mention of personal keymaps from PR checklist

keyboards/annepro2/annepro2_ble.c, keyboards/bioi/bluetooth_custom.c, keyboards/sawnsprojects/okayu/stm32f072/config.h, keyboards/sawnsprojects/okayu/stm32f103/config.h, keyboards/sawnsprojects/okayu/stm32f303/config.h, platforms/chibios/drivers/eeprom/eeprom_kinetis_flexram.c, quantum/eeconfig.h, quantum/quantum.h, tmk_core/protocol/report.c, tmk_core/protocol/report.h, tmk_core/protocol/usb_descriptor.c, users/brandonschlack/brandonschlack.c
Pulled out all the less than relevant changes from #22267.
*
=> Prep work for NKRO report separation

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, lib/python/qmk/info.py
Implements:
```json
{
"split": {
"transport":{
"sync": {
"activity": true,
"detected_os": true,
"haptic": true,
"layer_state": true,
"indicators": true
"matrix_state": true,
"modifiers": true,
"oled": true,
"st7565": true,
"wpm": true
}
}
}
}
```
Moves:
`split.transport.sync_matrix_state` -> `split.transport.sync.matrix_state`
`split.transport.sync_modifiers` -> `split.transport.sync.modifiers`
*
=> Support additional split sync items for info.json

builddefs/build_keyboard.mk
Missed a few symbol types when doing `TOP_SYMBOLS=yes` -- explicitly list them rather than relying on case-insensitive checks as `C` has no lowercase equivalent.
=> Fixup symbol sizing listing.

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md
Title. Am open to this living under a different/existing key
=> Add DD mappings for locking switch

quantum/command.c, tmk_core/protocol/vusb/vusb.c
Out of curiosity I ran the Idle Test from the tool mentioned here: #22324.
It failed, and led me to discover a couple of small bugs. The switch block for HID Report descriptor requests was looking at the wrong byte, and the interface numbering was off by one.
*
=> V-USB: Fix `GET_IDLE/SET_IDLE`

data/mappings/info_config.hjson, data/mappings/info_rules.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/cli/generate/keyboard_c.py
Examples:
```json
"dip_switch": {
"pins": ["A14", "B13"]
},
"split": {
"dip_switch": {
"right": {
"pins": ["A14", "B0"]
}
},
},
```
```json
"dip_switch": {
"matrix_grid": [
[5, 4]
]
},
```
*
=> Implement data driven dip switches

quantum/painter/qp.c
Found this bug the hard way: recently updating to develop caused my QP/LVGL-driven OLED to stop working properly. The function I assign to LVGL's `set_px_cb()` requires the panel's width and height information. The code was swapping the panel's width and height regardless of display orientation, but is easily fixed by adding the missing breaks to the case statements.
*
=> QP getters correction

drivers/led/aw20216s.h, drivers/led/issi/is31fl3218-simple.h, drivers/led/issi/is31fl3218.h, drivers/led/issi/is31fl3731-simple.h, drivers/led/issi/is31fl3731.h, drivers/led/issi/is31fl3733-simple.h, drivers/led/issi/is31fl3733.h, drivers/led/issi/is31fl3736-simple.h, drivers/led/issi/is31fl3736.h, drivers/led/issi/is31fl3737-simple.h, drivers/led/issi/is31fl3737.h, drivers/led/issi/is31fl3741-simple.h, drivers/led/issi/is31fl3741.h, drivers/led/snled27351-simple.h, drivers/led/snled27351.h
Inferred from `LED_MATRIX_LED_COUNT`/`RGB_MATRIX_LED_COUNT` if the respective driver is configured. When using a custom driver this must obviously be defined manually.
*
=> Add `_LED_COUNT` defines to LED drivers

lib/python/qmk/cli/generate/config_h.py
`to_config` does not equal `to_c`.
*
=> Fix 'to_c' for config.h mappings

data/schemas/keyboard.jsonschema, keyboards/controllerworks/mini42/info.json, keyboards/hillside/48/0_1/info.json, keyboards/splitkb/aurora/corne/rev1/info.json, keyboards/splitkb/aurora/helix/rev1/info.json, keyboards/splitkb/aurora/lily58/rev1/info.json, keyboards/splitkb/aurora/sofle_v2/rev1/info.json, keyboards/splitkb/aurora/sweep/rev1/info.json, keyboards/splitkb/kyria/rev3/info.json, keyboards/tzarc/djinn/info.json, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/cli/info.py, lib/python/qmk/info.py
Nothing works in this area anyway - the plan is still to rework everything with something like #18254. Keyboard changes,
* `"main": "left"` - redundant as default behaviour anyway
* `"main": "matrix_grid"` - set on boards using SPLIT_HAND_PIN
* `"main": "pin"` - does nothing as dependent logic is still `config.h` 
Additional changes around 18254 incoming shortly after this PR. 
*
=> Remove use of broken split.main

tmk_core/protocol/report.h
Also renamed the enum entries for Mission Control and Launchpad to reflect their canonical names in the HID Usage Tables document - the keycode names remain the same.
This renders [my Apple Fn patch](https://gist.github.com/fauxpark/010dcf5d6377c3a71ac98ce37414c6c4) largely obsolete, although an Apple VID/PID is still required for it to be recognised as Fn.
*
=> Add "AC Next Keyboard Layout Select" consumer usage entry (macOS Globe key)

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/cli/generate/keyboard_c.py, lib/python/qmk/info.py
Adds mapping for:
* `SPLIT_HAND_MATRIX_GRID`
* `SPLIT_HAND_PIN`
Reworks some of 18254, where no further discussion was needed. Built in parsing/generation is used where possible. 
`SPLIT_HAND_MATRIX_GRID` still needs bespoke generation. Fixing this will take further develop cycles to implement the usual breaking changes process. For example, once migrated to `info.json`, we can rework the implementation to generate the following instead
```c
#define SPLIT_HAND_MATRIX_GRID {D4,D3}
```
As with dip switches, the automatic generation of `matrix_mask` is also triggered. The aim is to reduce keyboard level configuration, which in turn avoids errors such as 21655. However to simplify the logic, it has been changed to use the result of all layouts squashed on top of each other. This should mostly …
=> Add dd mapping for hardware based split handedness

drivers/led/issi/is31fl3218-simple.c, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3731-simple.c, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736-simple.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3737-simple.c, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3741-simple.c, drivers/led/issi/is31fl3741.c, drivers/led/snled27351-simple.c, drivers/led/snled27351.c, keyboards/input_club/k_type/is31fl3733-dual.c
=> LED drivers: add defines for PWM and LED control register counts

keyboards/boardsource/unicorne/unicorne.c
Modified the `unicorne.c` file fixing the switch case for each of the layers. They were all set to use `layer_zero`. I've tested the fix by flashing and verifying the OLED screen updates the layer being selected. i.e (1,2,3,4)
The following lines have been modified
https://github.com/qmk/qmk_firmware/blob/master/keyboards/boardsource/unicorne/unicorne.c#L19-L30
* Fixes #22388
=> [Bug] Fixed OLED layers being all set to zero

builddefs/generic_features.mk
Will allow sections like the following to instead use generic:
```makefile
ifeq ($(strip $(SEND_STRING_ENABLE)), yes)
OPT_DEFS += -DSEND_STRING_ENABLE
COMMON_VPATH += $(QUANTUM_DIR)/send_string
SRC += $(QUANTUM_DIR)/send_string/send_string.c
endif
```
Which refactors to the single line:
```diff
diff --git a/builddefs/generic_features.mk b/builddefs/generic_features.mk
index 261da564b2..1caf447923 100644
--- a/builddefs/generic_features.mk
+++ b/builddefs/generic_features.mk
@@ -34,6 +34,7 @@ GENERIC_FEATURES = \
PROGRAMMABLE_BUTTON \
REPEAT_KEY \
SECURE \
+    SEND_STRING \
SPACE_CADET \
SWAP_HANDS \
TAP_DANCE \
```
Or,
```
ifeq ($(strip $(SEQUENCER_ENABLE)), yes)
OPT_DEFS += -DSEQUENCER_ENABLE
MUSIC_ENABLE = yes
SRC += $(QUANTUM_DIR)/sequencer/sequencer.c
SRC += …
```
=> Allow generic_features to handle subdirectories

keyboards/crkbd/crkbd.c
This pull request contains changes to how keylog is rendered to the oled.
First there was a bug where some rows/columns would not get properly updated depending on what was mapped to the key (pretty annoying when testing if the keymatrix works on a new build).
Second was a tiny improvement that was suggested to me in a code review for a different keyboard, that I thought I'd carry over since it applies to the crkbd too.
*
=> Fix corne keylog

keyboards/lily58/lib/layer_state_reader.c
The layer state for Lily58 was `Default` instead of `Base` that is the standard term across qmk.
=> Update layer state of Lily58 from Default to Base

drivers/led/snled27351-simple.c, drivers/led/snled27351.c
Somehow missed this in #22365...I definitely did a pass to double check it.
* report of Q3 not working on Discord
=> snled27351: fix missing `i2c_init()`

keyboards/snes_macropad/snes_macropad.c
=> Fixup snes_macropad on develop

lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/license_check.py, lib/python/qmk/constants.py
As per the title. Initial RFC.
=> Add `qmk license-check` developer-level CLI command.

quantum/process_keycode/process_clicky.c
The delay that `AUDIO_CLICKY_DELAY_DURATION` leverages is not actually silent. This results in discordant notes when using clicky mode on certain configurations—e.g., [this keyboard](https://github.com/qmk/qmk_firmware/tree/master/keyboards/mechwild/waka60), but configured to use `pwm_hardware` for audio.
```config.h
#define AUDIO_PWM_DRIVER PWMD3
#define AUDIO_PWM_CHANNEL 2
#define AUDIO_PWM_PAL_MODE 2
```
⚠️ **Testing assistance from anyone with audio hardware is appreciated.**
I am only able to verify this works for STM32F401/F411 at this time, but it appears that [silence may no longer be broken in general](https://github.com/qmk/qmk_firmware/pull/11820).
=> fix: make clicky delay silent

tmk_core/protocol/report.h
Similar to the mouse X/Y typedef. Should probably live in joystick.h (and be used elsewhere), but for now just this.
*
=> Slight refactor of joystick axis type into typedef

builddefs/common_rules.mk, platforms/avr/platform.mk, platforms/chibios/platform.mk
The cc-option and try-run functions are GPL2 from the Linux kernel.
cc-option was adapted to also handle -Wl,foo linker arguments.
See discussion in #21986
Cc @tzarc @KarlK90
=> chibios: disable RWX segment warning on newer GNU lds

keyboards/converter/usb_usb/hasu/rules.mk, keyboards/converter/usb_usb/leonardo/info.json, keyboards/converter/usb_usb/leonardo/rules.mk, keyboards/converter/usb_usb/readme.md
There is no ready-to-use usb-usb converter build target for Leonardo based board with USB 2.0 host shield.
Leonardo is similar to the default hasu board but uses caterina as bootloader.
Added a 'leonardo' folder, which is based on the default hasu folder.
- [X ] Enhancement/optimization
- [] Keyboard (addition or update)
* 
- [X ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [ X] I have read the [**CONTRIBUTING** …
=> Add leonardo build target for leonardo + usb2.0 shield based projects

docs/feature_converters.md
* Minor rephrases
* Merge standalone sentences
* Rewrite ambiguous community edition links between sections
=> [Doc] Improve RP2040 references

lib/python/qmk/search.py
When multiple `-f FILTER` options were specified, `qmk find` did not return anything at all instead of printing the list of entries that matched all of the specified filters.
The problem was that the statement in `_filter_keymap_targets()` that filled `targets` had a wrong indent and therefore was executed for every filter instead of only once after applying all filters, and `valid_keymaps` was actually an iterator and therefore could be used only once.  Moving the statement outside of the loop fixes the problem.
* Commands like `qmk find -f "protocol=V-USB" -f features.rgblight=true` with more than one `-f FILTER` option did not give any output even when there were some keyboards which matched the specified filters.
=> `qmk find`: Fix failure with multiple filters

data/schemas/keyboard.jsonschema, docs/reference_info_json.md, keyboards/drop/sense75/info.json, lib/python/qmk/info.py, lib/python/qmk/keyboard.py
Will allow XAP client (or configurator) to know a given key should be rendered as circle, and index for addressing into encoder map.
Adds crude `qmk info` rendering where drawing circles is super fun.... but its at least something.
Also adds validation to ensure the values are somewhat correct.
* Additionally add something `"type": "switch|encoder|encoder_switch"`  instead of just inferring from index key?
* Could be done on api gen?
* Future, extend this to rotation only encoders? 
* Could strip keys with `encoder:x` when generating layout macros?
* Would break current assumption that all must have matrix
* Would need strategy on how to avoid user config errors?
<details>
<summary> Alternatives? </summary>
```json
{
"encoder": {
"rotary": [
{"pin_a": "B5", "pin_b": "B4"},
{"pin_a": "B3", …
```
=> Enable linking of encoders to switch within layout macros

lib/python/qmk/build_targets.py
There was an import cycle in the Python modules:
- `qmk.build_targets` imported `qmk.cli.generate.compilation_database`;
- importing `qmk.cli.generate.compilation_database` requires initializing `qmk.cli` first;
- the initialization of `qmk.cli` imported the modules for all CLI commands;
- `qmk.cli.compile` imported `qmk.build_targets`.
This cycle did not matter in most cases, because `qmk.cli` was imported first, and in that case importing `qmk.cli.generate.compilation_database` did not trigger the initialization of `qmk.cli` again.  However, there was one corner case when `qmk.bulld_targets` was getting imported first:
- The `qmk find` command uses the `multiprocessing` module.
- The `multiprocessing` module uses the `spawn` start method on macOS and Windows.
- When the `spawn` method …
=> Fix `qmk find` failure due to circular imports

lib/python/qmk/cli/ci/validate_aliases.py, lib/python/qmk/cli/generate/api.py, lib/python/qmk/commands.py, lib/python/qmk/keyboard.py, lib/python/qmk/search.py
As discussed on Discord.
```
master: qmk find -km all  363.64s user 4.69s system 1147% cpu 32.094 total
develop, before PR: qmk find -km all  566.75s user 5.11s system 284% cpu 3:21.15 total
develop, after PR: qmk find -km all  359.43s user 3.79s system 1713% cpu 21.201 total
```
=> CLI parallel search updates

lib/python/qmk/build_targets.py, lib/python/qmk/search.py
After #22221 duplicates started showing up in `qmk find` and `qmk mass-compile`. This removes them.
=> [CLI] Remove duplicates from search results

tmk_core/protocol/vusb/protocol.c, tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h
=> V-USB: Add generic `send_report()` function

keyboards/bastardkb/dilemma/4x6_4/keymaps/via/keymap.c, keyboards/miiiw/blackio83/blackio83.c
Fix a couple of keyboards's shutdown_* callbacks
* CI
=> Fix missed shutdown callbacks

lib/python/qmk/userspace.py
From configurator's logs, it seems `$ORIG_CWD` is not being set. Userspace searches it, and bombs out due to nonexistence.
=> Attempt to fix configurator.

docs/feature_combo.md, docs/feature_oled_driver.md, docs/feature_pointing_device.md, docs/feature_split_keyboard.md, docs/newbs_building_firmware_workflow.md
Correct Markdown syntax errors.
=> [Doc]: Correct Markdown syntax errors.

keyboards/nullbitsco/snap/keymaps/bongo_reactive/config.h
The SNAP bongo_reactive keymap is too large by a pitiful 6 bytes. Reduce the size so that it compiles. 142 bytes free after.
```
Checking file size of nullbitsco_snap_bongo_reactive.hex                                           
* The firmware is too large! 28678/28672 (6 bytes over)
```
*
=> nullbitsco/snap: reduce size of bongo_reactive

lib/python/qmk/info.py
This error message could be triggered for example if MATRIX_IO_DELAY is configured in config.h, but the matrix is a custom one. The custom matrix can still call back to existing delay functions that make use of the MATRIX_IO_DELAY macro. In this case 'matrix_pins' in info_data will be true, but there will be no 'direct' 'cols' or 'rows' in info_data['matrix_pins'], and without this commit it would trigger an invalid error.
*
=> Don't print error message when there are no row pins and no col pins

lib/python/qmk/userspace.py
Removes duplicate searched userspace paths.
Python `dict` insert order is guaranteed to be kept since Python 3.7.
=> Dedup the list of tested userspace paths.

lib/python/qmk/cli/__init__.py
Windows uses `;` as the path separator not `:`.  Splitting and appending to path with the incorrect delimiter causes the shutil.where calls to fail.
Downside is that on Windows, `python_dir` never matches due to being a different format. Calling `cygpath` to resolve the path caused issues on terminal startup. End result is the path is always appended (now correctly) however it doesnt really cause much issue as its generally the same as the first entry anyway.
* <https://discord.com/channels/440868230475677696/473506116718952450/1180201007607722146>
=> Fix `qmk doctor` not finding binaries on Windows

keyboards/splitkb/aurora/corne/corne.c, keyboards/splitkb/aurora/helix/helix.c, keyboards/splitkb/aurora/lily58/lily58.c, keyboards/splitkb/aurora/sofle_v2/sofle_v2.c, keyboards/splitkb/aurora/sweep/sweep.c
The OLED screen will display the wrong layer when the ADJUST layer is entered, it will still show the previous layer entered (either RAISE or LOWER) because the layer checking code returns `true` before even checking whether the ADJUST layer is entered or not. 
The code changes remove the more fragile ordering of if-else checks to case-statement, and changes the called function from `layer_state_is(` to `get_highest_layer(` to ensure we capture the right layer. 
I only verified the bug and the fix on my Aurora Corne board, but as the same code is used over all Aurora boards and the code change is minimal, I submit this PR for the full line. 
(copied from the Bug report)
Expected behaviour: when pressing the mod keys to enter both the LOWER and RAISE layer, the ADJUST layer is entered, and …
=> Changed order of layer-checking code to fix #22520

keyboards/fc660c/ad5258.c, keyboards/fc980c/ad5258.c
The i2c_master API requires shifting the address [one bit to the left](https://docs.qmk.fm/#/i2c_driver?id=note-on-i2c-addresses).
Originally, the Leopold code included a custom I2c driver which took the I2C device address as-is. During the refactoring in #21964, the code was migrated to the generic `i2c_master` API which has the quirk that I2C device address have to be shifted by one. That detail was missed in the refactor.
The changes here were originally included with #22260, but that is still waiting on reviews. With the [recent breaking changes update](https://github.com/qmk/qmk_firmware/pull/22553) the I2C address issue has migrated into master, and since I'm unsure when (or if) my original Leopold refactor PR gets reviewed/merged, I've decided to split this out into a separate PR. …
=> Fix AD5258 I2C address for Leopold keyboards

keyboards/anavi/arrows/arrows.c, keyboards/anavi/arrows/config.h, keyboards/anavi/arrows/halconf.h, keyboards/anavi/arrows/info.json, keyboards/anavi/arrows/keymaps/default/keymap.c, keyboards/anavi/arrows/keymaps/default/rules.mk, keyboards/anavi/arrows/mcuconf.h, keyboards/anavi/arrows/readme.md, keyboards/anavi/arrows/rules.mk
ANAVI Arrows is a compact inverted T hot-swappable mechanical keyboard with 4 Cherry MX compatible switches, translucent key caps, rotary encoder, USB-C, RP2040 microcontroller, backlighting and under lighting.
This commits adds initial QMK support for ANAVI Arrows with:
- Default keymap
- Mini OLED I2C Display
- WS2812B RGB underlighting
- Backlighting (with PWMD5 and channel A as defined for GPIO 26 in the Raspberry Pi RP2040 datasheet)
The Neopixel on XIAO RP2040 is not supported as of the moment.
*
=> [Keyboard] Add ANAVI Arrows

keyboards/helix/rev3_5rows/keymaps/default/keymap.c, keyboards/helix/rev3_5rows/keymaps/default/rules.mk, keyboards/helix/rev3_5rows/keymaps/via/keymap.c, keyboards/helix/rev3_5rows/keymaps/via/oled_display.c, keyboards/helix/rev3_5rows/keymaps/via/rules.mk, keyboards/helix/rev3_5rows/rules.mk
=> [Helix] enable encoder map

lib/python/qmk/cli/generate/keyboard_c.py
`generate_keyboard_h` spits out better errors so i figured its not worth duplicating. Ideally these would be caught earlier but having the generate code more defensive should only help.
*
=> Avoid exceptions when generating matrix mask from layouts containing OOB matrix values

keyboards/splitkb/aurora/helix/rev1/info.json
We accidentally flipped the A and B pins of one of the encoders, this fixes the issue.
Not filed
=> [Bug] Fix Aurora Helix encoder direction

drivers/led/issi/is31fl3218-simple.c, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3731-simple.c, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736-simple.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3737-simple.c, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3741-simple.c, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31flcommon.c, drivers/led/snled27351-simple.c, drivers/led/snled27351.c, keyboards/input_club/k_type/is31fl3733-dual.c
Just a small nit, as these are basically the only places left where I2C is referred to as TWI. The comment above also makes reference to a function that no longer exists since the adoption of `i2c_master`.
*
=> LED drivers: change "TWI" to "I2C"

lib/python/qmk/cli/generate/api.py
It seems that `list_keymaps()` now returns the absolute paths to each found keymap when `fullpath=True` - I suspect this was the intended behaviour all along.
However, this has broken api_tasks when it goes to download the default JSON keymap for compilation:
```
fetch_json(https://keyboards.qmk.fm/v1/keyboards/idank/sweeq/info.json)
fetch_json(https://raw.githubusercontent.com/qmk/qmk_firmware/master//__w/qmk_firmware/qmk_firmware/keyboards/idank/sweeq/keymaps/default/keymap.json)
ERROR: https://raw.githubusercontent.com/qmk/qmk_firmware/master//__w/qmk_firmware/qmk_firmware/keyboards/idank/sweeq/keymaps/default/keymap.json returned 404: 404: Not Found
```
*
=> Fix JSON keymap URLs generated by the API

lib/python/qmk/cli/generate/api.py
After #22222 `list_keymaps(fullpath=True)` returns absolute paths which might point to the userspace directory tree; however, the implementation of `qmk generate-api` expected to get paths relative to `qmk_firmware`. The problem was partially fixed in #22618 for the generated `url` value; however, the `path` value for keymaps was still incorrect (this also made the subsequent code overwrite the `keymap.json` files in the working copy instead of writing those files converted to plain JSON into the API output directory).
Fix the `path` value for keymaps to contain the keymap path relative to `qmk_firmware` as it was before the userspace changes, and skip any userspace keymaps which might have been found.
* The generated API files for keyboards had broken `path` values for JSON keymaps …
=> Fix more `qmk generate-api` fallout from userspace support

keyboards/splitkb/aurora/corne/rev1/info.json, keyboards/splitkb/aurora/lily58/rev1/info.json, keyboards/splitkb/aurora/sweep/rev1/info.json, keyboards/splitkb/kyria/rev3/info.json
We've received some reports from customers about keyboards having flickering LEDs and occasionally disconnecting. After some investigation, it turns out we mistakenly defined `max_brightness` for `rgblight` but _not_ for `rgb_matrix`. It should obviously be defined for both as they are the very same LEDs, and manually defining rgb_matrix max_brightness on the keyboard level resolved the issues.
This PR aims to fix the issue for the keyboards involved.
None filed
=> [Bug] Fix RGB Matrix max brightness for several splitkb.com keyboards

keyboards/aeboards/ext65/rev2/rev2.c, keyboards/dumbpad/v1x_oled/v1x_oled.c, keyboards/horrortroll/lemon40/lemon40.c, keyboards/lime/rev1/rev1.c, keyboards/mino_plus/mino_plus.c, keyboards/rura66/rev1/oled_display.c
Correct several instances of keyboard-level code incorrectly calling (or neglecting to call) user-level functions.
- `dumbpad/v1x_oled` and `rura66/rev1` call `oled_task_user()` for keyboard-level code.
- `dumbpad/v1x_oled` and `lime/rev1` call `encoder_update_user()` for keyboard-level code.
- `aeboards/ext65/rev2`, `mino_plus/*` and `horrortroll/lemon40` use the correct `oled_task_kb()`, but are missing the `if (!oled_task_user())` clause allowing user overrides.
- Since I was already modifying the file: `aeboards/ext65/rev2` calls `keyboard_pre_init_user()` only, instead of calling `keyboard_pre_init_user()` at the end of `keyboard_pre_init_kb()`.
The diff looks more extensive than this because I ran `qmk format-c` on all affected files before making changes. I'm leaving the commits …
=> fix: improper usage of keyboard/user-level functions

lib/python/qmk/cli/compile.py, lib/python/qmk/cli/flash.py
Noticed this while using my custom tool for automating the build process, as it logic broke a little :)
* `qmk` not raising `make`'s return code.
=> [Bugfix] `qmk {compile, flash}` return code

lib/python/qmk/cli/mass_compile.py
As discussed on Discord
Friendly ping @tzarc 
```
$ qmk mass-compile -n
Ψ Retrieving list of keyboards with keymap "default"...
Ψ Preparing target list...
Ψ Compilation targets:
☒ 'KeyboardKeymapBuildTarget' object is not subscriptable
File "/home/elpekenin/.local/lib/python3.13/site-packages/milc/milc.py", line 539, in __call__
^^^^^^^^^^^^^^^
File "/home/elpekenin/.local/lib/python3.13/site-packages/milc/milc.py", line 544, in __call__
^^^^^^^^^^^^^^^^^^^^^^
File "/home/elpekenin/dev_qmk/lib/python/qmk/cli/mass_compile.py", line 111, in mass_compile
return mass_compile_targets(targets, cli.args.clean, cli.args.dry_run, cli.args.no_temp, cli.config.mass_compile.parallel, …
```
=> [Bugfix] Broken `qmk mass-compile -n`

keyboards/lily58/keymaps/default/config.h, keyboards/lily58/keymaps/default/rules.mk
- Enables Link time Optimization which drops firmware size and improves matrix scan rate
- Fixes formatting in `rules.mk`
=> Enable Link Time Optimization for Lily58 Default Keymap

quantum/led_matrix/led_matrix.c, quantum/led_matrix/led_matrix.h, quantum/rgb_matrix/rgb_matrix.c
With the overall aim to remove all inits,  `magic()` is now called before `rgb_matrix_init`/`led_matrix_init` so the ones removed here are no longer required.
Also added `led_matrix_reload_from_eeprom` to align with `rgb_matrix_reload_from_eeprom`.
*
=> Remove redundant RGB/LED matrix eeconfig init

quantum/rgblight/rgblight.c
With the overall aim to remove all inits,  `magic()` is now called before `rgblight_init` so the one removed here are no longer required.
*
=> Remove redundant rgblight eeconfig init

quantum/backlight/backlight.c, quantum/backlight/backlight.h
With the overall aim to remove all inits,  `magic()` is now called before `backlight_init`. eeprom will always be valid by the time `backlight_init` is called. Because of this, the existing logic to default config is currently broken.
The spare bit in the eeprom config has been used to decide if the backlight eeprom init process has been completed.
*
=> Remove redundant backlight eeconfig init

keyboards/splitkb/aurora/corne/keymaps/debug/config.h, keyboards/splitkb/aurora/corne/keymaps/debug/keymap.c, keyboards/splitkb/aurora/corne/keymaps/debug/readme.md, keyboards/splitkb/aurora/corne/keymaps/debug/rules.mk, keyboards/splitkb/aurora/helix/keymaps/debug/config.h, keyboards/splitkb/aurora/helix/keymaps/debug/keymap.c, keyboards/splitkb/aurora/helix/keymaps/debug/readme.md, keyboards/splitkb/aurora/helix/keymaps/debug/rules.mk, keyboards/splitkb/aurora/lily58/keymaps/debug/config.h, keyboards/splitkb/aurora/lily58/keymaps/debug/keymap.c, keyboards/splitkb/aurora/lily58/keymaps/debug/readme.md, keyboards/splitkb/aurora/lily58/keymaps/debug/rules.mk, keyboards/splitkb/aurora/sofle_v2/keymaps/debug/config.h, keyboards/splitkb/aurora/sofle_v2/keymaps/debug/keymap.c, keyboards/splitkb/aurora/sofle_v2/keymaps/debug/readme.md, keyboards/splitkb/aurora/sofle_v2/keymaps/debug/rules.mk, keyboards/splitkb/aurora/sweep/keymaps/debug/config.h, keyboards/splitkb/aurora/sweep/keymaps/debug/keymap.c, keyboards/splitkb/aurora/sweep/keymaps/debug/readme.md, keyboards/splitkb/aurora/sweep/keymaps/debug/rules.mk, keyboards/splitkb/kyria/keymaps/debug/config.h, keyboards/splitkb/kyria/keymaps/debug/keymap.c, keyboards/splitkb/kyria/keymaps/debug/readme.md, keyboards/splitkb/kyria/keymaps/debug/rules.mk
22693 removed the splitkb debug keymaps, however we have the following request https://github.com/qmk/qmk_firmware/pull/22485#issuecomment-1820891011
*
=> [Keymap Removal] Restore splitkb 'debug' keymaps

quantum/deferred_exec.c
Bug raised in #22697 -- if a deferred executor callback clears its own token, then that slot may be reused and returning zero will re-clear a newly-created deferred executor.
This just ensures the entry is the same before clearing.
* Fixes #22697
=> [Bugfix] Manipulate deferred executor slot only if tokens match

docs/pr_checklist.md
=> [docs] - reword PR checklist for vendor keymaps/userspace changes

docs/feature_tap_dance.md, quantum/process_keycode/process_tap_dance.c, quantum/process_keycode/process_tap_dance.h, quantum/quantum_keycodes.h, tests/tap_dance/examples.c
Should be with all the other keycodes, in preparation for the generation of keycodes that have arguments.
Also aligns the method to unpack with the other keycodes.
*
=> Align location of tap dance keycode

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, quantum/audio/audio.c, quantum/audio/audio.h, quantum/eeconfig.c
With the overall aim to remove all inits,  `magic()` is now called before `audio_init`. eeprom will always be valid by the time `audio_init` is called.
A spare bit in the eeprom config has been used to decide if the eeprom init process has been completed. Defaulting of config options has been implemented per other features.
*
=> Remove redundant audio eeconfig init

keyboards/rookiebwoy/late9/rules.mk, keyboards/rookiebwoy/neopad/rules.mk
Add prefix for the default folder directive
=> Default folder correction for rookiebwoy

keyboards/keychron/q11/config.h
On Keychron Q11, the master side could switch to slave state, and become unresponsive, because of a long time between poweron and actually USB enumeration by the USB host,
This fixes the issue with SPLIT_WATCHDOG_ENABLE.
#22778
=> Keychron Q11 usb poweron fix

lib/python/qmk/info.py
Some of the dd conversions, 22806 22807 22808, are failing due to the led config not being parsed (or led count being added) when the lighting feature is disabled by default.
If we have _some_ dd config for a lighting feature, then we probably should still try and search for led config.
Likewise, if we already have position data, there is no point in trying to search for it.
*
=> Ensure LED config is extracted when feature is disabled

drivers/led/apa102.c, drivers/led/apa102.h
Preemptive diff minimisation for the APA102 and WS2812 drivers properly conforming to the RGB Matrix-esque `init`/`set_color`/`set_color_all`/`flush` API.
*
=> apa102: cleanups

drivers/led/aw20216s.h, drivers/led/issi/is31fl3218-mono.c, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3731-mono.c, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3733-mono.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736-mono.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3737-mono.c, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3741-mono.c, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31fl3742a-mono.c, drivers/led/issi/is31fl3742a.c, drivers/led/issi/is31fl3743a-mono.c, drivers/led/issi/is31fl3743a.c, drivers/led/issi/is31fl3745-mono.c, drivers/led/issi/is31fl3745.c, drivers/led/issi/is31fl3746a-mono.c, drivers/led/issi/is31fl3746a.c, drivers/led/snled27351-mono.c, drivers/led/snled27351.c
- Tightened up/normalised formatting
- Added missing license headers
- 3218: tweaked `set_value()`/`set_color()` to match the rest of the drivers - fixes potential out of bounds
- 3737: typo in `IS31FL3737_CS_PULLDOWN`
- snled27351: fixed wrong dirty flag being used in `update_pwm_buffers()`
- Moved some dirty flag assignments inside their checks (as there is no point setting them if it's the same value)
*
=> LED drivers: misc formatting and typos

drivers/led/issi/is31fl3733-mono.c, drivers/led/issi/is31fl3733-mono.h, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3733.h, keyboards/input_club/k_type/is31fl3733-dual.c, keyboards/input_club/k_type/is31fl3733-dual.h
Never used, and is the only ISSI driver which `write_register()` function does this.
*
=> is31fl3733: change `write_register()` return type to `void`

quantum/keymap_extras/sendstring_french.h
There are two circumflexes on the standard French keyboard layout: 
1) One AltGr-accessible one on key 9. Not a dead key, does not require an extra space afterwards to appear. 
2) One on the key right of P (US ANSI left bracket). Dead, does require an extra space afterwards to appear.
sendstring_french.h has defined the circumflex symbol as being dead *and* AltGr-accessible on key 9, resulting in all circumflexes being followed by a space. 
This commit marks the circumflex on the french sendstring keyboard layout as "alive" so that no extra space is sent afterwards.
- [ x] Bugfix
*
=> Raise Circumflex from the grave in sendstring_french.h

lib/python/qmk/cli/migrate.py, lib/python/qmk/info.py
When the DD mappings are set to `"to_json": false`, there is no replacement data for migration. The result right now is the original is removed, with nothing added to `info.json`.
This PR makes migrate ignore these problematic values for now. Ive also added some logic to reject `array.array.x` types due to the incorrect parsing.
*
=> Prevent `qmk migrate` processing unparsed info.json values

docs/feature_pointing_device.md, quantum/pointing_device/pointing_device_auto_mouse.c, quantum/pointing_device/pointing_device_auto_mouse.h
Add a threshold for a minimum amount of mouse movement before activating the auto mouse layer. Right now, any movement at all triggers the mouse layer. I have a BastardKB Charybdis and I've noticed that I often nudge the trackball when pressing other keys.
Adds a new configuration option for the auto mouse feature `AUTO_MOUSE_THRESHOLD`. If the mouse is bumped by a distance below this threshold, the auto mouse layer is not activated. The mouse distance is accumulated over multiple events in case a single mouse event does not move the mouse over this threshold (it would have to be a relatively quick movement).
* Fixes #21396
=> Add option for auto mouse movement threshold

quantum/process_keycode/process_dynamic_macro.c
The `dynamic_macro_record_key_user()` wasn't being called on every keypress when recording; this pull request fixes this.
The `dynamic_macro_record_key_user()` callback wasn't being called on every keypress, only when we ran out of space to record macro keys. Change this such that it calls on every keypress.
* none
=> Fix user hook call for dynamic_macro_record_key

quantum/process_keycode/process_midi.c
MIDI sustain effect fix on qmk 0.22.2.
I'd like to raise this issue again.
https://github.com/qmk/qmk_firmware/pull/11639#issuecomment-816761645
*
=> MIDI sustain effect fix on qmk 0.22.2

keyboards/annepro2/c15/info.json, keyboards/annepro2/c18/info.json, keyboards/annepro2/info.json
Fix of the AnnePro2's VID and PID
I have changed AnnePro2's VID and PID to the original firmware's values, so it can be used with VIA (0xFEED is invalid VendorId).
I got the original values from AnnePro2-Tools website - https://openannepro.github.io/ap2_revisions/
=> [Keyboard] Fix VID and PID for AnnePro2

tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/chibios/usb_main.h, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/usb_descriptor.h, tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h
ChibiOS changes a bit gross as QMK_USB_DRIVER_CONFIG and the various driver code assumes both endpoints and unpicking it is much more of a change. Instead the vusb implementation was cribbed.
Tested on:
* chibios - drop/alt/v2 + zvecr/zv48/f401
* lufa - drop/thekey/v2
* vusb - jj4x4
* arm_atsam - compiles but ignored due to pending removal.
* Fixes #8593
=> Remove console out endpoint

drivers/led/issi/is31fl3733-mono.c, drivers/led/issi/is31fl3733-mono.h, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3733.h, drivers/led/issi/is31fl3741-mono.c, drivers/led/issi/is31fl3741-mono.h, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31fl3741.h, drivers/led/snled27351-mono.c, drivers/led/snled27351-mono.h, drivers/led/snled27351.c, drivers/led/snled27351.h, keyboards/input_club/k_type/is31fl3733-dual.c, keyboards/input_club/k_type/is31fl3733-dual.h
=> LED drivers: change `write_pwm_buffer()` return type to `void`

drivers/led/issi/is31fl3218-mono.c, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3731-mono.c, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3733-mono.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736-mono.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3737-mono.c, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3741-mono.c, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31fl3742a-mono.c, drivers/led/issi/is31fl3742a.c, drivers/led/issi/is31fl3743a-mono.c, drivers/led/issi/is31fl3743a.c, drivers/led/issi/is31fl3745-mono.c, drivers/led/issi/is31fl3745.c, drivers/led/issi/is31fl3746a-mono.c, drivers/led/issi/is31fl3746a.c, drivers/led/snled27351-mono.c, drivers/led/snled27351.c, keyboards/input_club/k_type/is31fl3733-dual.c
It seems to me that this whole memcpy business to transmit the PWM buffers is a relic of the original ISSI driver(s) predating the i2c_master API.
Tested on 3731, appears to work just fine.
*
=> LED drivers: switch to i2c_writeReg()

quantum/pointing_device/pointing_device.c
the mutual exclusive POINTING_DEVICE_MOTION_PIN and SPLIT_POINTING_ENABLE influence if and how the `pointing_device_driver.get_report` is triggered. now the way the define is wrapping around an "unbraced" if leads clang-format to weirdly indent the first line in the 'SPLIT_POINTING_ENABLE' as the first command after the if.
this hints that any code addition in between the two - that possibly should run regardless, would break the if-def enabled code.
this can be solved by adding a pair of curly braces in the POINTING_DEVICE_MOTION_PIN part, to clearly denote which commands are to be skipped if the motion pin shows now activity.
*
=> pointing_device ifdef indentation fix

.gitignore
As per title. Helps prevent things like #22892 attempting to slide prebuilt library files into PRs instead of sources, as per licensing requirements.
=> Add more unwanted compilation output files to `.gitignore`.

keyboards/mode/m80v1/m80h/info.json, keyboards/mode/m80v2/m80v2h/info.json
sequence of keys in `layouts` doesn't conform to respectively declared Community Layout's sequence of keys, for keyboards:
- mode/m80v1/m80h
- mode/m80v2/m80v2h
Resulting keypresses, after F12 key, will not be as intended for compiled Community Layout keymaps.
later fix:
Backspace key is currently sequenced in Function row. To conform, move to Number row.
cc: @Gondolindrim 
* n/a
=> revoke `community_layouts` from mode/m80v*/m80*h

docs/feature_pointing_device.md, drivers/sensors/cirque_pinnacle.c
the physical reachable range for the x/y axis can be user defined with `CIRQUE_PINNACLE_X_LOWER` etc, 
to figure out these values the new `CIRQUE_PINNACLE_REACHABLE_CALIBRATION` can be used.
a user can enable the debug console, this feature, dandomly move over the sensor to cover the whole area and then read the last min/max value set printed to the console to set those defines
*
=> Cirque reachable calibration aide

lib/python/qmk/cli/generate/keyboard_c.py, lib/python/qmk/info.py
While it is true that LED and RGB Matrix are mutually exclusive (mainly due to sharing of `g_led_config`), I have encountered this issue as a bit of an edge case with my testbed folder - Features are simply enabled in the keymap-level rules.mk, with most of the actual config living in the top-level or "dev-board"-level info.jsons.
Since all of the LED/RGB Matrix config generated by the CLI is protected by feature ifdefs anyway, it should be safe to have both at once.
*
=> CLI: Allow generation of both LED and RGB Matrix config

lib/python/qmk/cli/format/json.py
=> `qmk format-json`: Force Unix line endings and ensure LF at EOF

keyboards/atreus62/info.json, keyboards/atreus62/keymaps/via/keymap.c, keyboards/atreus62/keymaps/via/rules.mk
Add VIA support for Atreus62. Changed vendorId to be unique so that VIA can be used.
*
=> Add VIA support for Atreus62

lib/python/qmk/cli/generate/keyboard_h.py, lib/python/qmk/info.py
Highlighted by #22609. Currently the OOB messages are only shown at build time. By moving them to the info.json loading/validation stage, this ensures they are not missed on PRs, and not lost within the walls of text that can output on build.
*
=> Move layout macro OOB checks to lint

drivers/sensors/cirque_pinnacle.c
I've not been able to test this myself yet but it has been tested by a Discord user that was experiencing the issue. https://discord.com/channels/440868230475677696/440868230475677698/1198671176902393947
*
=> Fix cirque connected check

drivers/led/issi/is31fl3218-mono.c, drivers/led/issi/is31fl3218.c, drivers/led/issi/is31fl3731-mono.c, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3733-mono.c, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3736-mono.c, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3737-mono.c, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3741-mono.c, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31fl3742a-mono.c, drivers/led/issi/is31fl3742a.c, drivers/led/issi/is31fl3743a-mono.c, drivers/led/issi/is31fl3743a.c, drivers/led/issi/is31fl3745-mono.c, drivers/led/issi/is31fl3745.c, drivers/led/issi/is31fl3746a-mono.c, drivers/led/issi/is31fl3746a.c, drivers/led/snled27351-mono.c, drivers/led/snled27351.c, keyboards/input_club/k_type/i2c_master.c, keyboards/input_club/k_type/i2c_master.h, keyboards/input_club/k_type/is31fl3733-dual.c
The final batch of `i2c_writeReg()` -> `i2c_write_register()` renames.
*
=> LED drivers: update I2C API usage

drivers/sensors/azoteq_iqs5xx.c
This change simply removes the call to `i2c_stop` from the azoteq iqs5xx driver since the function was removed in #21273.
Submitted at the behest of @KarlK90 
* Compliation-stopper introduced in #21273
=> Remove call to removed i2c function in azoteq driver

platforms/avr/_print.h, quantum/logging/debug.h, quantum/logging/print.h
Some minor tidy up before more invasive changes. Main aim is to avoid AVR specific implementations of print functions, limiting down to exposing just a `xprintf`.
*
=> Tidy up print/debug logging headers

drivers/sensors/analog_joystick.c
Pins for ADC on analog joystick sensor were never initialized.  Would work fine in many cases but causes issues on some controllers. 
* [Discord Link](https://discord.com/channels/440868230475677696/867530303261114398/1199605421300797501)
=> Init pins for Analog Joystick sensor

keyboards/0xcb/splaytoraid/info.json, keyboards/1upkeyboards/pi50/info.json, keyboards/alpaca/wfeclipse/info.json, keyboards/bastardkb/dilemma/3x5_3/info.json, keyboards/bastardkb/dilemma/4x6_4/info.json, keyboards/capsunlocked/cu80/v2/info.json, keyboards/chromatonemini/info.json, keyboards/controllerworks/city42/info.json, keyboards/darmoshark/k3/info.json, keyboards/dasky/reverb/info.json, keyboards/dekunukem/duckypad/info.json, keyboards/dp3000/rev1/info.json, keyboards/inland/v83p/info.json, keyboards/keychron/c1_pro/ansi/white/info.json, keyboards/keychron/c2_pro/ansi/white/info.json, keyboards/phentech/rpk_001/info.json, keyboards/qwertykeys/qk100/ansi/info.json, keyboards/redragon/k667/info.json, keyboards/sharkoon/skiller_sgk50_s3/info.json, keyboards/sofle_choc/info.json, keyboards/wolf/m6_c/info.json
Always enabled, so adding the config line is completely pointless.
*
=> Remove always enabled effects from lighting animation list

quantum/process_keycode/process_steno.c
With the overall aim to remove all inits,  `magic()` is now called before `steno_init` so the one removed here are no longer required.
*
=> Remove redundant steno eeconfig init

data/schemas/keyboard.jsonschema, keyboards/acheron/themis/87h/info.json, keyboards/acheron/themis/87htsc/info.json, keyboards/acheron/themis/88htsc/info.json, keyboards/clueboard/card/info.json, keyboards/crkbd/info.json, keyboards/dark/magnum_ergo_1/info.json, keyboards/fancytech/fancyalice66/info.json, keyboards/hotdox76v2/info.json, keyboards/kbdfans/kbdpad/mk3/info.json, keyboards/keychron/q1v1/info.json, keyboards/mode/m256wh/info.json, keyboards/mode/m256ws/info.json, keyboards/moondrop/dash75/info.json, keyboards/moondrop/dash75/keymaps/via/keymap.json, keyboards/pauperboards/brick/info.json, keyboards/quadrum/delta/info.json, keyboards/quokka/info.json, keyboards/smithrune/magnus/m75h/info.json, keyboards/smithrune/magnus/m75s/info.json, keyboards/teleport/native/info.json, keyboards/thevankeyboards/minivan/keymaps/via/keymap.json, lib/python/qmk/info.py
* Removes duplicates
* Migrates `feature.lto -> build.lto`
* Updates schema to reject keys
*
=> Ensure LTO is enabled as a `info.json` build config option

keyboards/aidansmithdotdev/sango/info.json
As the title states, the merge for the Sango was missing a definition for the RGB split in info.json. This caused the RGBs on the right side of the board to be uncontrollable. Fixed by adding the definition as explained by @fauxpark and @casuanoob in the QMK Discord.
* Fixed Sango LED definition such that the right side is properly lit
=> Fix Issue with RGB Matrix not understanding the split keyboard

keyboards/ferris/sweep/config.h, keyboards/ferris/sweep/readme.md
For some reason ferris/sweep was configured with EE_hands as its default handedness method. This provides no real benefit, and confuses new users (sweep is one of our most searched for boards according to analytics).
I've deleted the config.h with the ee_hands define meaning it should fall back to MASTER_LEFT by default, and deleted all the extra stuff in readme.md that related to it.
Just aiming to simplify new users experience with this very popular board.
*
=> Remove ee_hands config from ferris/sweep firmware

Makefile
Replaces #23034.
Fixes running unit tests located outside /tests folder. Aligns test names with keyboard compilation, `/` instead of `:`. 
-  Partial revert of #15889
- `Running make test:auto_shift will run all Auto Shift tests`
- 15889 reverted the previous "fix" that was included within #21659
- `Fixed a small bug with test matching due to how findstring works (eg. make test:unicode builds every test suite starting with unicode instead of just the one named unicode)`
- Partial matches will only be currently supported via future CLI changes
Adds `make list-tests` to make test name discovery a little eaiser.
*
=> Fix unit test execution

lib/python/qmk/cli/git/submodule.py
When config or environment variable point to an invalid location, `normpath` can return a directory that does not reflect the change of directory performed by the cli. We never want current directory paths, so the code has been updated to just use regular pathlib funcs. 
* <https://discord.com/channels/440868230475677696/473506116718952450/1206416039206719508>
=> Fix git-submodule running in wrong location

quantum/logging/debug.h
Should address the keyboard level issues seen in 23041.
```
Compiling: quantum/quantum.c                                                                       In file included from quantum/quantum.h:54,
from quantum/quantum.c:17:
quantum/logging/debug.h:58:9: error: expected identifier or ‘(’ before ‘do’
58 |         do {                                                      \
|         ^~
quantum/logging/debug.h:60:11: error: expected identifier or ‘(’ before ‘while’
60 |         } while (0)
|           ^~~~~
quantum/logging/debug.h:58:9: error: expected identifier or ‘(’ before ‘do’
58 |         do {                                                      \
|         ^~
quantum/logging/debug.h:60:11: error: expected identifier or ‘(’ before ‘while’
60 |         } while (0)
|           ^~~~~ …
```
=> Workaround for `make test:all DEBUG=1`

docs/custom_quantum_functions.md, docs/feature_led_indicators.md, docs/gpio_control.md, docs/i2c_driver.md, platforms/arm_atsam/gpio.h, platforms/avr/gpio.h, platforms/chibios/gpio.h, platforms/gpio.h, quantum/encoder/tests/mock.c, quantum/encoder/tests/mock.h, quantum/encoder/tests/mock_split.c, quantum/encoder/tests/mock_split.h
snake_case with `gpio_` prefix to align better with the rest of the codebase.
*
=> Update naming convention for GPIO control macros

quantum/action.c, quantum/send_string/send_string.c, quantum/send_string/send_string.h
When using `send_string_with_delay`, if the string contains capital letters, it gets sent to `send_char`, which does not insert the delay between pressing the modifier keys needed to type the shifted letter. This results in key codes being sent unshifted in some situations, such as ssh connections where the keyboard is too fast for the modifier taps to register.
This commit inesrts a delay between every modifier tap when they are detected.
=> Insert delay between shifted chars in send_string_with_delay

builddefs/common_features.mk, docs/feature_joystick.md, quantum/joystick.c, quantum/joystick.h, quantum/keyboard.c
Extracted from #22947 to make DD changes cleaner/clearer.
* output_pin/ground_pin removed
* Previously planned removal never happened
* users will now need to override weak init/sample functions
* Correctly inits `joystick_axes` to virtual when no config
* input_pin would equal zero which is a valid value on chibios platforms (eg rp2040)
* Correct handling of input_pin as 0xFF is not a valid value to use
* again could be a valid value on chibios platforms
* Fixes compilation when `JOYSTICK_AXIS_COUNT == 0`
*
=> Fix joystick initialization

docs/feature_os_detection.md, quantum/keyboard.c, quantum/os_detection.c, quantum/os_detection.h, quantum/os_detection/tests/os_detection.cpp, quantum/os_detection/tests/rules.mk, quantum/quantum.h, tmk_core/protocol/usb_device_state.c
This adds callbacks for OS detection, similar to other mechanisms we already have to allow the KB/user to run custom code on an event.
The main use is withholding taking action until the OS detection has run, so the user does not have to craft some sort of periodic checks for the current OS, etc. As an example (and my usage), to set the current default layer depending on whether the detected OS is Windows, macOS, etc. 
This also eliminates any questions on whether OS_UNSURE means the detection ran *and* it resulted in that, or if it just happened to be the default value.
Since the detection runs when the USB device descriptor is being assembled, I added the option to also automatically reboot the keyboard when the USB link goes back to a non-configured state, due to e.g. KVM switching …
=> [Core] Add OS detection callbacks

quantum/os_detection/tests/os_detection.cpp
While passing on CI, these fail locally...
```
[ RUN      ] OsDetectionTest.TestDoNotReportIfUsbUnstable
[       OK ] OsDetectionTest.TestDoNotReportIfUsbUnstable (0 ms)
[ RUN      ] OsDetectionTest.TestReportAfterDebounce
make: *** [Makefile:417: test:os_detection] Error 1
```
*
=> Fix make clean test:os_detection

drivers/sensors/pmw3360.c
Initially reported by Wimads and burkfers on the BastardKB discord.
> The bug with PMW3360 I was talking about a week ago or so, with DPI's of 100, 900, 1700, etc not working. We figured out it was caused by pointing_device_get_cpi() Calling that at those DPI settings, causes mouse reports to break (no reports coming in). Setting cpi right after getting it fixes the issue. So something is going wrong with the get_cpi call.
This sounds like a bug with the pmw3360 firmware itself. But for now, this is a quick fix to the issue that is confirmed to work. 
*  Issue reported on BastardKB discord
=> [Bug] Fix pmw33xx sensor corruption on get-cpi call

keyboards/inett_studio/sq80/hotswap_layout_i/info.json, keyboards/inett_studio/sq80/hotswap_layout_i/keymaps/via/keymap.json
* Disable unneeded features
* Remove invalid `lto` key from keymap level (not needed anyway)
=> Fixup inett_studio/sq80

lib/python/qmk/build_targets.py, lib/python/qmk/cli/generate/compilation_database.py
As per title. Bug reported on Discord.
=> Ensure `qmk generate-compilation-database` copies to userspace as well.

keyboards/cipulot/common/ec_switch_matrix.c
this fix allows PCBs with more than 2 AMUX to correctly index the matrix.
*
=> Fix for multiple AMUX usage

keyboards/viktus/osav2/keymaps/default/keymap.c, keyboards/viktus/osav2/keymaps/via/keymap.c, keyboards/viktus/osav2_topre/ec.c, keyboards/viktus/osav2_topre/keymaps/default/keymap.c, keyboards/viktus/osav2_topre/keymaps/via/keymap.c
Correcting tilde to grave, fixing a typo in ec.c, and removing some comments that were accidentally left in.
Corrected a keycode for both keyboards, fixed a typo in `ec.c`, and removed comments left in `ec.c` that shouldn't have been there.
*
=> Fixing typos for OSAv2 and OSAv2_Topre

platforms/avr/platform.mk
Building AVR targets with embedded bootloader had make environment contamination.
This PR fixes the intended build target when building the bootloader, as well as ensuring it's correctly sequenced in a parallel build.
=> Fix up AVR production build target.

lib/python/qmk/json_schema.py
We've been trying to work on this for a while:
* Loading JSON files can take a while, so we remember their post-load state
* Concerns were made that the resulting data could be modified, so we deepcopy and return that instead
* lru_cache of 0 was actually doing nothing but logging, so sizes were adapted to be nonzero.
Before:
```
qmk find -f 'exists(split.matrix_pins)'  571.96s user 6.05s system 1137% cpu 50.815 total
```
After:
```
qmk find -f 'exists(split.matrix_pins)'  349.67s user 3.47s system 1119% cpu 31.539 total
```
=> CLI Speed improvements.

keyboards/tzarc/djinn/djinn_portscan_matrix.c
Djinn uses `__WFI()` -- wait for interrupt -- during a period of input inactivity as it's not processing anything new.
Previously USB SOF interrupts were enough to wake up the main loop and let the board continue, but after #21656 this is no longer functioning.
This PR adds a new 100Hz Virtual Timer that ensures things are woken up at least once every 10ms.
=> Fix up scanning for Djinn, post-asyncUSB.

lib/python/qmk/cli/new/keyboard.py
Directory is relative to qmk_firmware folder. Seems to be tripping some users up when `new-keyboard` is run from whatever their terminal starts with like their home directory.
So its gone and replaced with what should be an absolute path, as well as the somewhat meaningless text replaced with a hint to those who think it can magically work out what pins are being used.
```
Ψ Created a new keyboard called asdf.
Ψ Build Command: qmk compile -kb asdf -km default.
Ψ Project Location: /home/zvecr/qmk_firmware_clean/keyboards/asdf,
Ψ Now update the config files to match the hardware!
```
*
=> Remove cd suggestion from new-keyboard

.editorconfig
* Disallows use of `.editorconfig` for `lib/**` apart from `lib/python/**`.
* Duplication between filetypes removed.
* Added YAML formatting to match GHA expected formatting.
=> Normalise .editorconfig.

.github/workflows/format.yml, .github/workflows/lint.yml
https://github.com/qmk/qmk_firmware/actions/runs/8125898899/job/22208993741
Seems to be picking up far too many files, and then flagging them when it should not. This previously did not happen so would suggest a change in the actions behaviour. As checking locally is something more recently introduced, and these issues seem to be with branches being out of date with upstream, force use of API in an attempt to restore the previous behaviour?
*
=> Attempt to fix changed files on CI workflow

.github/workflows/unit_test.yml, docs/cli_commands.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/test/c.py
Adds CLI subcommand that extends the available functionality of normal test execution.
Adds:
* basic test filtering
```bash
qmk test-c --list
qmk test-c
qmk test-c --clean --test basic
qmk test-c --test unicode*
qmk test-c --test *unicode*
qmk test-c -j=2 --test basic
qmk test-c --test basic -e DEBUG=1
```
*
=> Initial `qmk test-c` functionality

keyboards/momokai/aurora/info.json, keyboards/momokai/tap_duo/info.json, keyboards/momokai/tap_trio/info.json
Changes default RGB effect for momokai keypads to solid white
*
=> Change default RGB effect for momokai keypads to solid white

lib/python/qmk/info.py
Has been a PR requirement for a long time now, yet we still get many a PR with them specified in code. 
This still allows `qmk info -f json` to render the output, so it can be copy-pasted to the correct location.
*
=> Flag LAYOUT macros still defined in .h files

keyboards/work_louder/work_board/config.h, keyboards/work_louder/work_board/info.json, keyboards/work_louder/work_board/keymaps/default/keymap.c, keyboards/work_louder/work_board/keymaps/default/readme.md, keyboards/work_louder/work_board/keymaps/default/rules.mk, keyboards/work_louder/work_board/keymaps/via/config.h, keyboards/work_louder/work_board/keymaps/via/keymap.c, keyboards/work_louder/work_board/rules.mk
* Reduce VIA keymap firmware size (disable RGB Matrix animations)
* Move some things to data driven
* Tidy up misc code
=> Fixup work_board

quantum/action.c
`layer_on(action.layer_tap.val)` is also called from the following `set_oneshot_layer(action.layer_tap.val, ONESHOT_START)` call
*
=> Remove unuseful layer_on() call

quantum/main.c, tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/protocol.c, tmk_core/protocol/vusb/vusb.c
=> Refactor vusb to protocol use pre/post task

keyboards/cipulot/common/ec_switch_matrix.h, keyboards/cipulot/ec_23u/config.h, keyboards/cipulot/ec_60/config.h, keyboards/cipulot/ec_alveus/1_0_0/config.h, keyboards/cipulot/ec_alveus/1_2_0/config.h, keyboards/cipulot/ec_pro2/config.h, keyboards/cipulot/ec_prox/ansi_iso/config.h, keyboards/cipulot/ec_prox/jis/config.h, keyboards/cipulot/ec_theca/config.h, keyboards/cipulot/rf_r1_8_9xu/config.h
Noticed that these were all failing on `develop`, but `master` was okay, even without any changes.
See: https://github.com/qmk/qmk_firmware/actions/runs/8279382628
Turns out `util.h` wasn't included, so `PACKED` wasn't defined -- `typedef struct PACKED { ...` was treating `PACKED` as the struct name and continuing without struct packing actually occurring. This fixes things, and updates all the data sizes accordingly (subtract 1).
CC: @Cipulot
=> Fixup cipulot eeprom.

keyboards/alfredslab/swift65/solder/keyboard.json, keyboards/alfredslab/swift65/solder/keymaps/default/keymap.c, keyboards/alfredslab/swift65/solder/keymaps/via/keymap.c
- Renames the layout macros to have more standard names
- Refactors the keymaps
cc @spooknik (keyboard maintainer)
=>  Swift65 Solder Layout Name Standardization

keyboards/alfredslab/swift65/hotswap/keyboard.json, keyboards/alfredslab/swift65/hotswap/keymaps/default/keymap.c, keyboards/alfredslab/swift65/hotswap/keymaps/via/keymap.c
- Renames the layout macro to have a more standard name
- Refactors the keymaps
cc @spooknik (keyboard maintainer)
=> Swift65 Hotswap Layout Name Standardization

keyboards/bastardkb/charybdis/3x5/v2/stemcell/config.h, keyboards/bastardkb/charybdis/3x5/v2/stemcell/info.json, keyboards/bastardkb/charybdis/3x5/v2/stemcell/rules.mk, keyboards/bastardkb/charybdis/3x6/v2/stemcell/config.h, keyboards/bastardkb/charybdis/3x6/v2/stemcell/info.json, keyboards/bastardkb/charybdis/3x6/v2/stemcell/rules.mk, keyboards/bastardkb/charybdis/4x6/v2/stemcell/config.h, keyboards/bastardkb/charybdis/4x6/v2/stemcell/info.json, keyboards/bastardkb/charybdis/4x6/v2/stemcell/rules.mk, keyboards/bastardkb/scylla/v2/stemcell/info.json, keyboards/bastardkb/scylla/v2/stemcell/rules.mk, keyboards/bastardkb/skeletyl/v2/stemcell/info.json, keyboards/bastardkb/skeletyl/v2/stemcell/rules.mk, keyboards/bastardkb/tbkmini/v2/stemcell/info.json, keyboards/bastardkb/tbkmini/v2/stemcell/rules.mk
Fixes build issues in #23312
Conversion targets **must** adhere to to the given interface.
* Specifying a different MCU/Bootloader while using a converter is incorrect
* Adding in workarounds for missing `elite_c` pins when using a `promicro` a converter is incorrect
Either the keyboard must use conveters correctly, or the keyboard should just specify the native pin config upfront. As the `splinky_v2`/`splinky_v3` keyboard targets specify RP2040 pins directly and do not use a converter, the same has been applied to the `stemcell` targets.
*
=> Fix invalid use of stemcell converter

builddefs/converters.mk
Users should not be trying to target "blackpill" based boards with the current available converters.
The following is logically incorrect...
```
qmk compile -kb cantor -km default -e CONVERT_TO=promicro_rp2040
```
However the error should be a bit more human readable than what is produced.
Long term, #20330 will solve the issue but that involves many keyboard upates.
* https://discord.com/channels/440868230475677696/867530222407778344/1219772124542013543
=> Assume only 32u4 boards can run 'promicro' converters

keyboards/handwired/lovelive9/keymaps/default/keymap.c, keyboards/hineybush/hbcp/hbcp.c, keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c, keyboards/kingly_keys/ave/staggered/keymaps/default/keymap.c, keyboards/manyboard/macro/keymaps/default/keymap.c, keyboards/manyboard/macro/keymaps/via/keymap.c, keyboards/tetris/keymaps/default/keymap.c
Part of an effort to move responsibility for the pixel buffer to the LED drivers instead of the RGBLight feature itself. The next part will involve removing the `extern`ed LED array.
These were easy-ish, but there are more which actually read from the array instead of writing to it, and there is no real replacement for this. They may end up having to be removed altogether.
*
=> Remove RGBLight `led[]` references

data/constants/keycodes/extras/keycodes_spanish_latin_america_0.0.1.hjson, quantum/keymap_extras/keymap_spanish_latin_america.h
I forgot to add it in #22542
It is needed in order to merge https://github.com/qmk/qmk_configurator/pull/1324
=> Add ES_GRV to latam keymaps

quantum/rgblight/rgblight.c
Bug reported in [discord](https://discord.com/channels/440868230475677696/867530715192885269/1221200524163026987) by @lesshonor 
Fixes an issue introduced by #23076, rgblight_mode_noeeprom was trying to set_leds before init had happened.
*
=> Fix rgblight init

layouts/default/60_ansi_arrow/default_60_ansi_arrow/keymap.c
60_ansi_arrow Community Layout:
Re-arrange whitespace between keycodes to be uniform with, other, Community Layout keymaps
* n/a
=> tidy keymap of 60_ansi_arrow Community Layout

docs/flashing.md
Clearer text about double tapping reset only working for boot after already having QMK running in board.
Simple change that makes it clearer. It can prevent confusion with I had. As simple as it is, as it sounds like it has something to do with having the program compiled but does not make it clear that it should already be running on the board.
* 
- [] My change requires a change to the documentation.
=> Clearer text about double tapping reset only working for boot after already having QMK running in board

lib/python/qmk/info.py
With the many keyboard level migrations to use `keyboard.json`, there is currently nothing user facing to show that a keyboard is still using the legacy method of `rules.mk`.
This PR adds a lint/build warning when a keyboard has fallen back to backwards compatibility. Which after backwards compatibility is removed, can easily be promoted to a build error.
*
=> Produce warning if keyboard is not configured via `keyboard.json`

quantum/pointing_device/pointing_device.c
Corrected that when the USB cable was on the right side, the left side was changed when trying to change the CPI on the right side in POINTING_DEVICE_CONBINED.
* #19433
=> Fix pointing_device_set_cpi_on_side() changing CPI on correct side. relevant to #19433.

platforms/chibios/platform.mk
=> Update ChibiOS submodules.

docs/feature_split_keyboard.md, quantum/split_common/transactions.c, quantum/split_common/transport.h
Split transaction mods does not transfer one shot locked mods.
As noted in the title, split transactions one shot locked mods is not transferred to slave side for oled display, this pull request aims to change that.
=> Oneshot locked mods split transaction

docs/pr_checklist.md
=> PR Checklist: explain wireless requirements.

lib/python/qmk/cli/license_check.py
Running `qmk license-check` against any relative paths _outside_ `qmk_firmware` would result in an inability to actually find the files, as the CLI `cd`s to `qmk_firmware` before executing. This uses `$ORIG_CWD` to make the files absolute.
Had to reorder the file as `qmk pytest` was complaining about complexity.
=> Fix up license check path.

keyboards/kagizaraya/scythe/rules.mk
Setting `RGBLIGHT_SPLIT` within `rules.mk` does absolutely nothing.
Looking at the history, it was also specified in config.h and already migrated. 
*
=> Remove RGBLIGHT_SPLIT in rules.mk

quantum/encoder.c
The encoder support was broken in various ways when having 4 or more encoders on any keyboard side (or, more precisely, when `MAX_QUEUED_ENCODER_EVENTS` was not a power of 2, which happened when `NUM_ENCODERS_MAX_PER_SIDE` increased above 3, unless `MAX_QUEUED_ENCODER_EVENTS` was set directly).  In particular, with 4 encoders the encoder rotation did not have any effect.
The problem was caused by `encoder_queue_full_advanced()` always returning `true` even when the queue was not actually full, which caused all encoder events to be dropped.  The underlying reason was that `(events->tail - 1) % MAX_QUEUED_ENCODER_EVENTS` did not calculate what the rest of code expected when `events->tail` was 0, except when `MAX_QUEUED_ENCODER_EVENTS` happened to be a power of 2, so the code seemed to work …
=> Fix encoder breakage with 4 or more encoders

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/config_options.md, docs/feature_rgblight.md, docs/reference_info_json.md, docs/ws2812_driver.md, keyboards/ergodox_ez/config.h, keyboards/ergodox_ez/info.json, keyboards/ergodox_ez/shine/rgblight_custom.c, keyboards/handwired/tennie/config.h, keyboards/handwired/tennie/keyboard.json, keyboards/oddforge/vea/ws2812_custom.c, keyboards/rgbkb/pan/pan.c, keyboards/westfoxtrot/aanzee/config.h, keyboards/westfoxtrot/aanzee/keyboard.json, platforms/avr/drivers/ws2812_i2c.c, platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c, platforms/chibios/drivers/ws2812_bitbang.c, platforms/chibios/drivers/ws2812_pwm.c, platforms/chibios/drivers/ws2812_spi.c, quantum/color.c, quantum/color.h, quantum/rgb_matrix/rgb_matrix_drivers.c, quantum/rgblight/rgblight.c
This define really only affects the WS2812 driver:
- RGBLight only supports WS2812 and APA102 LEDs. As far as I can ascertain, there is no such thing as an RGBW APA102, and there is no support for RGBW in the current APA102 driver code.
- RGB Matrix supports WS2812 as well as a variety of ISSI LED drivers. These technically *could* do RGBW, as the drivers are simply mapping the RGB values to the PWM buffer indices specified in their LED config structs, but I would argue these should get their own defines (eg. `IS31FL3733_RGBW` etc.), if there exists a board with RGBW LEDs driven by one of these chips.
*
=> Rename `RGBW` define to `WS2812_RGBW`

lib/python/qmk/cli/lint.py, lib/python/qmk/keyboard.py
* removed `--all-kb` and `--all-km` to match `qmk compile`
* correctly handle `-kb` using aliases 
* Fixed handling of automagic_keyboard not using consistent `keyboard` value
*
=> Align 'qmk lint' argument handling

tests/basic/test_one_shot_keys.cpp
basic unit test refactoring
In tests/test_common/test_fixture.cpp there are
```
void TestFixture::run_one_scan_loop() {
this->idle_for(1);
} 
```
and
```
void TestFixture::tap_key(KeymapKey key, unsigned delay_ms) {
key.press();
idle_for(delay_ms);
key.release();
run_one_scan_loop();
}
```
So calls like :
```
key.press();
run_one_scan_loop();
key.release();
run_one_scan_loop();
```
Are the same as :
```
key.press();
idle_for(1);
key.release();
idle_for(1);
```
or 
`    tap_key(key);`
because 1 is the default value for delay_ms (`void tap_key(KeymapKey key, unsigned delay_ms = 1);` in tests/test_common/test_fixture.hpp)
*
=> Refactoring successive press() release() calls into tap_key() calls

data/constants/keycodes/extras/keycodes_czech_mac_ansi_0.0.1.hjson, data/constants/keycodes/extras/keycodes_czech_mac_iso_0.0.1.hjson, docs/reference_keymap_extras.md, quantum/keymap_extras/keymap_czech_mac_ansi.h, quantum/keymap_extras/keymap_czech_mac_iso.h, quantum/keymap_extras/sendstring_czech_mac_ansi.h, quantum/keymap_extras/sendstring_czech_mac_iso.h
This pull request introduces MacOS Czech input keymaps for both ANSI and ISO layouts.
The changes include:
- Declarations added in `keycodes_czech_mac_ansi_0.0.1.hjson` and `keycodes_czech_mac_iso_0.0.1.hjson` files.
- Generated keymap headers
- `SEND_STRING` lookup table.
- Documentation references updated accordingly.
Key names have been reused from `keycodes_czech_0.0.1.hjson` or other languages where necessary. 
All keycodes and the `SEND_STRING` macro, which sends the entire ASCII table, have been validated and tested.
* #23346
=> Add MacOS Czech ISO and ANSI keymaps #23346

keyboards/jlw/bruce_le_clavier/info.json, keyboards/jlw/bruce_le_clavier/keymaps/default/keymap.c, keyboards/jlw/bruce_le_clavier/keymaps/default/rules.mk, keyboards/jlw/bruce_le_clavier/readme.md, keyboards/jlw/bruce_le_clavier/rules.mk
This is a PR to add the keyboard "Bruce le Clavier" to QMK.  There is a PR for its brother, "Bruce the Keyboard"  (#23639). The two boards are very similar, but Bruce the Keyboard is a rectangular 4.25u tall by 10u wide column stagger board, whereas Bruce le Clavier is a unibody split version of Bruce the Keyboard with a center key/encoder option.
This keyboard has broken out pins for an addressable LED strip to be added if the end user so wishes. I defined the WS2812 pin in info.json for users to be able to add their own backlight code, but did not define the RGB Light feature in this PR since it is not a default functionality for the board.
Thank you for taking the time to review this submission (and/or its brother).
*
=> add Bruce le Clavier

.clangd, lib/python/qmk/cli/generate/compilation_database.py
Should hopefully assist with errors people are seeing.
- Adds new ignored arguments, which should fix up start-of-file errors complaining about `-mcpu=`, `-mfpu=` etc.
- Parses the removed `-mcpu=`, `-mfpu=` etc. args when building the compilation database, ensuring any `#define`s are correctly propagated depending on the MCU in use, as well as its settings.
Compilation flags in the resulting `compile_commands.json` end up appending things like:
```
-DAVR=1 -D__ACCUM_EPSILON__=0x1P-15K -D__ACCUM_FBIT__=15 -D__ACCUM_IBIT__=16 -D__ACCUM_MAX__=0X7FFFFFFFP-15K '-D__ACCUM_MIN__=(-0X1P15K-0X1P15K)' -D__ATOMIC_ACQUIRE=2 -D__ATOMIC_ACQ_REL=4 -D__ATOMIC_CONSUME=1 -D__ATOMIC_RELAXED=0 -D__ATOMIC_RELEASE=3 -D__ATOMIC_SEQ_CST=5 -D__AVR=1 -D__AVR_2_BYTE_PC__=1 -D__AVR_ARCH__=5 -D__AVR_ATmega32U4__=1 …
```
=> clangd enhancements.

keyboards/xiudi/xd75/keyboard.json
```
Compiling: platforms/avr/drivers/backlight_pwm.c                                                    [OK]
platforms/avr/drivers/backlight_pwm.c: In function 'enable_pwm':
platforms/avr/drivers/backlight_pwm.c:133:5: error: 'TCCRxA' undeclared (first use in this function); did you mean 'TCCR0A'?
133 |     TCCRxA |= _BV(COMxx1) | _BV(COMxx0);
|     ^~~~~~
|     TCCR0A
[OK]
platforms/avr/drivers/backlight_pwm.c:133:5: note: each undeclared identifier is reported only once for each function it appears in
In file included from /usr/avr/include/avr/io.h:99,
from platforms/avr/_pin_defs.h:18,
from platforms/pin_defs.h:22,
from platforms/gpio.h:18,
from platforms/avr/drivers/backlight_pwm.c:2:
platforms/avr/drivers/backlight_pwm.c:133:19: error: 'COMxx1' undeclared (first use in this …
```
=> xiudi/xd75 - Fix backlight compilation issues

quantum/split_common/split_util.c
This follows the style rules and better reflects the intent. Prep work for making `SPLIT_WATCHDOG_ENABLE` the new default.
*
=> split_util: rename `usbIsActive` to `usb_bus_detected`

docs/__capabilities.md, docs/flashing.md, docs/newbs.md
Collects the in-use capabilities in our docs site and puts them all on one page, so we can validate any technology changes.
Fixes up a couple of minor irritations.
=> Add page for capabilties used by docs site.

data/schemas/keyboard.jsonschema, docs/reference_info_json.md, keyboards/era/sirind/tomak/keyboard.json, keyboards/keychron/q11/info.json
Config option does not do anything.
It would have to be manually wired up to produce `SERIAL_DRIVER = usart`, however that scales poorly when we also have other serial drivers available.
*
=> Remove 'split.transport.protocol=serial_usart'

keyboards/binepad/bnk9/config.h, keyboards/binepad/bnk9/info.json
Binpad BNK9 rotary encoder does 2 "bumps" for every "key press" ... this should be 1:1.  This fix corrects that.
* No issue on GH.  This is a customer issue escalation.
=> [Bug][Keyboard] Fix encoder resolution issue with Binepad BNK9

lib/python/qmk/cli/userspace/compile.py
As per title. Failures were still exiting with RC=0.
* https://github.com/qmk/qmk_userspace/issues/5
=> [CLI] Fixup return code for `qmk userspace-compile`.

keyboards/keychron/q60/ansi/keymaps/default/keymap.c, keyboards/keychron/q60/ansi/keymaps/keychron/keymap.c, keyboards/keychron/q60/ansi/keymaps/via/keymap.c
Noticed that WIN/GUI and ALT/OPT keys are swapped in the Mac and Win layers.  This change correctly places the right GUI/OPT mappings in the right layers.
*
=> Fix mapping of GUI/ALT for Win/Mac layers

lib/python/qmk/userspace.py
Aligns resolution logic with global CLI <https://github.com/qmk/qmk_cli/blob/master/qmk_cli/helpers.py#L38-L45>.
Also swaps from dict to set, given only the dict keys are used.
* Fixes #23729
=> Resolve home directory in userspace config

quantum/split_common/transactions.c
This was a bad assumption on my part in thinking a true return meant the slave side had received the transaction.
Forcing an update using the timer ensures the CPI is set correctly if it fails without error albeit with a small delay.
I've targeted master as I think it's more a bug fix and causes no compatibility issues but I'm happy to switch to develop if required. 
*
=> Force CPI update using timer when using split pointing.

keyboards/shandoncodes/riot_pad/keyboard.json
Add the required config to enable media key usage on the Riot Pad.
Media key config added
*
=> Add media key support to Riot Pad

quantum/send_string/send_string.c
This was done for ARM in #19280, but there is another copy of these functions that needed to be fixed too.
See #19280
=> Insert delay between shifted chars in send_string_with_delay for AVR

docs/feature_combo.md
Mention support of advance keycodes that are not just limited to mod-tap.
=> [Doc] Reference advance keycodes in combos

keyboards/craftwalk/keyboard.json, keyboards/craftwalk/keymaps/via/keymap.c, keyboards/craftwalk/keymaps/via/rules.mk
Add via support for craftwalk.
=> Add via support for craftwalk 

drivers/ps2/ps2_mouse.c
Bug report #22265 and fix by d93921012, I'm just pushing the change. There is a longer description the bug report; shorter summary:
When the main loop calls `ps2_mouse_task()` for the first time after the button down event, it finds no new data in the PS/2 receive buffer. Here it should return, or it tries to detect a button state change anyway and updates the mouse state with the button released before it is actually released. When doing click and drag, it cycles between button down and up.
Tested on ARM ChibiOS (RP2040) with a Trackpoint from a Thinkpad T61. With this change it works perfectly. The keyboard itself is a home-made converter for the Thinkpad keyboard (only in my personal fork at this point).
* Fixes #22265
=> Fix PS/2 Trackpoint mouse clicks (#22265)

keyboards/ibm/model_m/modelh/config.h, keyboards/ibm/model_m/modelh/info.json
The Model M's matrix is 2-key rollover and can suffer from ghosting. This PR adds the constant `MATRIX_HAS_GHOST` to the Model H controller, so that the firmware addresses the issue.
*
=> Added MATRIX_HAS_GHOST definition for IBM Model H controller

data/mappings/keyboard_aliases.hjson, docs/ChangeLog/20240526/PR23309.md, docs/ChangeLog/20240526/PR23329.md, keyboards/kprepublic/jj40/rev1/readme.md
Minor touch-ups for the work I did for the 2024Q2 `develop` merge.
- updated PR23309 changelog
- added a direct link to its PR
- added PR23329 changelog
- updated the legacy `jj40`/`jj50` keyboard aliases to the new post-2024Q2 locations
- minor edit to the JJ40 rev1 readme because \*I\* am case-sensitive :upside_down_face:
=> noroadsleft's 0.25.0 Changelogs and Touch-Ups

drivers/eeprom/eeprom_custom.c-template, drivers/eeprom/eeprom_driver.c, drivers/eeprom/eeprom_driver.h, drivers/eeprom/eeprom_i2c.c, drivers/eeprom/eeprom_spi.c, drivers/eeprom/eeprom_transient.c, drivers/eeprom/eeprom_wear_leveling.c, platforms/chibios/drivers/eeprom/eeprom_legacy_emulated_flash.c, platforms/chibios/drivers/eeprom/eeprom_stm32_L0_L1.c, quantum/eeconfig.c
Make eeprom driver behaviour more uniform. Adding eeprom_driver_format abstraction.
Before this change, we used to call epprom_driver_erase(), if we detected that the eeprom
content did not have the necessary magic number, but only of it was implemented as an
"eeprom_driver". This is sometimes necessary, and sometimes not. We used to make the decision
based on whether the eeprom_driver_erase() function has been implemented or not, but that is
not really the best way to decide.
Erase in necessary for example when eeprom emulation/wear leveling is in use. This is because
the actual backing store also contains metadata that needs to start out in a clean state.
It is not necessary to erase I2C and SPI EEPROMs before use, however we used to do it.
The new eeprom_driver_format(erase=false) call …
=> EEPROM: Don't erase if we don't have to. Adding eeprom_driver_format abstraction.

docs/cli_commands.md, docs/cli_configuration.md, docs/cli_development.md, docs/cli_tab_complete.md, docs/feature_audio.md, docs/feature_auto_shift.md, docs/feature_layouts.md, docs/feature_macros.md, docs/flashing_bootloadhid.md, docs/hand_wire.md, docs/hardware_keyboard_guidelines.md, docs/how_a_matrix_works.md, docs/keymap.md, docs/newbs_building_firmware.md, docs/newbs_flashing.md, docs/newbs_getting_started.md
Especially bad on mobile.
Seems the 4 space indent code blocks dont play nice, but there is not much value in keeping them.
*
=> [docs] Fix code blocks overflowing page width

Makefile
Adds `make format-core`, `make pytest`, and `make format-and-pytest` targets to the base `Makefile`.
These launch the formatting and testing routines within docker using the same `qmk/qmk_cli` container as run on GHA. Should simplify ensuring the version of `clang-format` and the like is consistent.
Have used these in my userspace for several years at this point, figured it'd be a useful thing to upstream given comments on #23854.
=> Add helper `make` targets for formatting and pytest.

docs/features/swap_hands.md
Fix documentation for the Swap-Hands feature.
The previous instructions incorrectly stated to add the `SWAP_HANDS_ENABLE` define in the Makefile. This commit corrects it to specify adding `SWAP_HANDS_ENABLE = yes` in the rules.mk file instead.
- [x ] Documentation
- [x ] I have updated the documentation accordingly.
=> Fix documentation error

docs/pr_checklist.md
=> Fix broken link in PR checklist

platforms/eeprom.h
=> Re-implement `eeprom_write_qword` as define

keyboards/splitkb/kyria/info.json, keyboards/splitkb/kyria/rev1/base/keyboard.json, keyboards/splitkb/kyria/rev1/config.h, keyboards/splitkb/kyria/rev1/info.json, keyboards/splitkb/kyria/rev1/proton_c/config.h, keyboards/splitkb/kyria/rev1/proton_c/keyboard.json, keyboards/splitkb/kyria/rev1/proton_c/rules.mk, keyboards/splitkb/kyria/rev2/base/keyboard.json, keyboards/splitkb/kyria/rev2/config.h, keyboards/splitkb/kyria/rev2/info.json, keyboards/splitkb/kyria/rev2/proton_c/config.h, keyboards/splitkb/kyria/rev2/proton_c/keyboard.json, keyboards/splitkb/kyria/rev2/proton_c/rules.mk, keyboards/splitkb/kyria/rev3/config.h, keyboards/splitkb/kyria/rev3/keyboard.json
Configurator/`api_tasks` cannot handle converted boards, resulting in the following on the status page:
```
Ψ Compiling keymap with gmake -r -R -f builddefs/build_keyboard.mk -s KEYBOARD=splitkb/kyria/rev1/proton_c KEYMAP=default_configurator KEYBOARD_FILESAFE=splitkb_kyria_rev1_proton_c TARGET=splitkb_kyria_rev1_proton_c_default_configurator INTERMEDIATE_OUTPUT=.build/obj_splitkb_kyria_rev1_proton_c_default_configurator VERBOSE=false COLOR=true SILENT=false QMK_BIN="qmk" MAIN_KEYMAP_PATH_1=.build/obj_splitkb_kyria_rev1_proton_c_default_configurator MAIN_KEYMAP_PATH_2=.build/obj_splitkb_kyria_rev1_proton_c_default_configurator MAIN_KEYMAP_PATH_3=.build/obj_splitkb_kyria_rev1_proton_c_default_configurator MAIN_KEYMAP_PATH_4=.build/obj_splitkb_kyria_rev1_proton_c_default_configurator …
```
=> splitkb/kyria: remove `CONVERT_TO` at keyboard level

keyboards/4pplet/waffling60/rev_e/keyboard.json, keyboards/4pplet/waffling60/rev_e_ansi/keyboard.json, keyboards/4pplet/waffling60/rev_e_iso/keyboard.json
Bugfix: enable encoder in firmware and setting mousekey enable to ANSI and solder version
Not being able to change encoder settings in VIA or FW.
=> Bugfix: enable encoder in firmware and setting mousekey enable to ANSI and solder version

keyboards/keychron/q9_plus/ansi_encoder/keymaps/default/rules.mk, keyboards/mechlovin/zed65/no_backlight/wearhaus66/keymaps/default/rules.mk
As title, we seem to have missed these during review.
=> Remove VIA_ENABLE from default keymaps.

docs/ChangeLog/20240526.md
We forgot to add this to the changelog.
=> VIA keymap deprecation notice.

docs/ChangeLog/20240526.md, docs/_sidebar.json
=> Fixup docs.

.github/workflows/docs.yml, docs/public/CNAME
Will prevent publishing issues that would be found post PR merge.
*
=> Ensure documentation pull requests build

docs/features/led_matrix.md, docs/features/rgb_matrix.md
Replacing the rather awkward Functions section with a more fleshed out API reference.
*
=> Add API reference section for LED/RGB Matrix docs

keyboards/keebio/bamfk1/keyboard.json
Fixes non-working encoder due to missing enable.
*
=> Add missing encode enable for BAMFK-1

lib/python/qmk/cli/find.py, lib/python/qmk/cli/generate/autocorrect_data.py, lib/python/qmk/cli/mass_compile.py, lib/python/qmk/cli/userspace/compile.py, lib/python/qmk/cli/userspace/list.py, lib/python/qmk/cli/via2json.py, lib/python/qmk/commands.py, lib/python/qmk/info.py, lib/python/qmk/json_schema.py, lib/python/qmk/util.py
CLI code has been written under the assumption that it's run once from the terminal. In cases where it was originally deemed "annoying" to dump out an exception, a hard `exit()` was invoked instead.
This causes issue with CI, which temporarily loads/unloads the CLI modules. We get random unexplained failures as a result of the `exit()` calls. This introduces a `maybe_exit` which allows overriding by CI (later) and thus not killing the process invoking CI.
=> [CLI] Don't `exit()` when certain exceptions occur.

lib/python/qmk/commands.py
When running `./util/regen.sh` on Windows, every file generated (using `dump_lines()`) gets its newlines changed from LF to CRLF regardless of if there are any substantial changes to them. Since we enforce LF through Git anyway, this shouldn't really affect anything but we can turn off this noise by telling `write_text()` to use LF all the time.
*
=> [CLI] Force `dump_lines()` to always use Unix line endings

lib/python/qmk/importers.py
Incorrect filename used now the template keyboard directory uses `keyboard.json`.
* <https://discord.com/channels/440868230475677696/473506116718952450/1253091504138883165>
=> Update 'qmk import-kbfirmware' to use 'keyboard.json'

keyboards/gmmk/numpad/numpad.c
See issue https://github.com/qmk/qmk_firmware/issues/23973 for exact details on how the error has surfaced.
* fixes #23973
=> Fix leftover reference to previous AW20216S EN pin definition

docs/contributing.md, readme.md
#23977 reminded me that I had stashed, rather than PRed changes in the same area.
*
=> Update documentation suggestion in top level readme

docs/features/led_indicators.md, keyboards/converter/usb_usb/custom_matrix.cpp, keyboards/sirius/unigo66/custom_matrix.cpp, quantum/led.c, quantum/led.h
Deprecated for 1.5 years, so probably safe to now remove.
*
=> Remove deprecated `led_set_user`

keyboards/hs60/v2/hhkb/keyboard.json, keyboards/hs60/v2/hhkb/keymaps/default/keymap.c, keyboards/hs60/v2/hhkb/keymaps/via/keymap.c
Investigating this warning which confused me as `60_hhkb` is a valid community layout which should not be factored in:
`⚠ hs60/v2/hhkb: Layout "LAYOUT_60_hhkb" should not contain name of keyboard.`
As far as the `layouts/` directory is concerned this is *not* an HHKB layout, which explains the warning as it is not tagged in `community_layouts` (thus the keyboard name itself is also incorrect).
*
=> `hs60/v2/hhkb`: Adjust layout name

drivers/sensors/adns9800.c, drivers/sensors/pmw33xx_common.c
Tested 3360, 3389 and ADNS9800 are functional without SROM upload.
I did get some odd behaviour with the ADNS9800 but my sensor has always seemed a little iffy.
I chose not to document the defines as the idea is to have a larger test base running no SROM uploads. Ultimately they'll be reworked so the SROM can be included in the users keymap or uploaded by other means. 
*
=> Change ADNS9800 and PMW33XX SROM uploads to opt in.

keyboards/winry/winry315/keymaps/via/keymap.c, keyboards/winry/winry315/winry315.c, keyboards/winry/winry315/winry315.h
Preparations for <https://docs.qmk.fm/ChangeLog/20240526#migration-of-via-keymaps-to-via-team-control>.
*
=> Relocate winry315 VIA logic

keyboards/work_louder/rgb_functions.h, keyboards/work_louder/work_board/config.h, keyboards/work_louder/work_board/keymaps/via/config.h, keyboards/work_louder/work_board/keymaps/via/keymap.c, keyboards/work_louder/work_board/work_board.c
Preparations for <https://docs.qmk.fm/ChangeLog/20240526#migration-of-via-keymaps-to-via-team-control>.
*
=> Relocate work_louder VIA logic

data/templates/keyboard/keyboard.json, lib/python/qmk/cli/new/keyboard.py
Config would be created without the "board" config, which for blackpills fails to configure its HSE frequency correctly.
Instead of expanding `development_board` to its relevant config , just use the setting directly.
Also fixes the case of `qmk import-keyboard` where the json file is using `development_board`. Previously it would have processor/bootloader keys with unresolved tokens.
* https://discord.com/channels/440868230475677696/867530222407778344/1255208257463517205
=> Fix 'qmk new-keyboard' processing of development_board

builddefs/common_features.mk, drivers/flash/flash.h, drivers/flash/flash_spi.c, drivers/flash/flash_spi.h, drivers/wear_leveling/wear_leveling_flash_spi.c
=> SPI flash API cleanup, add async erase capability.

lib/python/qmk/cli/__init__.py
Just bumps minimum versions comment. No further changes.
=> Minimum python version listing.

tmk_core/protocol/chibios/chibios.c
Specifically, it seems on some systems that the sync doesn't happen correctly, and changing the order should address the issue by always calling `suspend_wakeup_condition`, which calls `matrix_scan`
I haven't experienced this issue, so I can't really test it.
* Closes #22269 
* Closes #22457
=> Change suspend condition check order on ChibiOS

keyboards/monsgeek/m5/m5.c
This PR makes the `led_update_kb` in the Monsgeek M5 keyboard call `led_update_ports`, actually synchronizing the numlock and capslock indicator LEDs to the numlock and capslock states.
*
=> monsgeek/m5: make numlock and capslock LEDs work

platforms/arm_atsam/hardware_id.c, platforms/avr/hardware_id.c, platforms/chibios/hardware_id.c
As per title. Makes it so we can use a separate chip identifier or preload a separate EEPROM or something with hardware identifiers during board bringup.
=> Allow overriding `get_hardware_id()`.

tmk_core/protocol/lufa/lufa.c
#24020 changed the order the remote wakeup check for ChibiOS.
The same logic behind the change would apply to LUFA and where possible, the 2 implementations should be kept in sync. While I cannot reproduce the same issue, testing doesnt seem like it has introduced any obvious problems.
*
=> Align LUFA suspend logic

docs/features/encoders.md, docs/features/rgblight.md, docs/keycodes.md
Keycode renames are already done (#23656), next up is #23765
*
=> [docs] Update RGBLight (Underglow) keycode names

keyboards/planck/rev7/keymaps/default/config.h, keyboards/planck/rev7/keymaps/default/keymap.c, keyboards/planck/rev7/matrix.c, keyboards/planck/rev7/readme.md
* Fix for encoders on Planck rev7
* Support `ENCODER_MAP_ENABLE` feature on Planck rev7
* Update readme.md on Planck rev7
* None
=> Fix for encoders and support ENCODER_MAP_ENABLE on Planck rev7

.github/workflows/ci_build_major_branch.yml
https://ci.qmk.fm/master/latest/index.html has a really long log entry -- I think because actions/checkout isn't actually getting anything other than a copy of the active revision. Testing locally doesn't trigger this, seemingly because of the full history being available.
This makes it so the whole repo is pulled down, including history.
=> [CI] Pull full history before generating index

.github/workflows/ci_build_major_branch_keymap.yml, util/ci/discord-results.py
As per title.
`#webhooks_ci` has builds which report success but zero (or less than normal) successfully built targets.
Seemingly this is when a CI run is cancelled due to a newer run being queued up.
Also fixes up the Discord notification so that it actually includes a link to the CI run with firmware downloads.
=> [CI] Disable Discord webhook when CI run is cancelled.

keyboards/bajjak/matrix.c, keyboards/gboards/georgi/matrix.c
Commit e9bd7d7a (PR #21273) refactors low-level calls to the i2c API into the current wrapper API calls. When translating for two keyboards (gboards/georgi, bajjak), said PR sadly missed two bitwise negation operators when receiving from i2c. This PR attempts to fix them.
The missed lines are:
- [here](https://github.com/qmk/qmk_firmware/commit/e9bd7d7ad308f9c72c86863bf9f19382c7e2d892#r144205894) for georgi
- [here](https://github.com/qmk/qmk_firmware/commit/e9bd7d7ad308f9c72c86863bf9f19382c7e2d892#r144205888) for bajjak
The other keyboards modified by the referenced PR (gboards/gergo, gboards/gergoplex, handwired/pterodactyl, ergodox_ez) were handled correctly. 
* fixes #24112
=> Fix i2c received value in georgi and bajjak

docs/ChangeLog/PR24120.md, docs/features/key_overrides.md, quantum/keymap_introspection.c, quantum/keymap_introspection.h, quantum/process_keycode/process_key_override.c, quantum/process_keycode/process_key_override.h
As per title. Some signature changes required to support it.
Also fixes up and standardises some of the other keymap introspection functions:
* some should've been weak but weren't
* standardised all functions to use bounds checks
* standardised all relevant `_raw` functions to use `ARRAY_SIZE(...)`
=> Add support for key override introspection.

platforms/chibios/drivers/spi_master.c
RFC on SPI threadsafety. Tested on Ghoul.
=> [WIP] Adds bus acquire/release semantics to SPI start/stop.

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, keyboards/zvecr/zv48/info.json, lib/python/qmk/info.py
Aligns structure to other features, and removes some driver terminology bleeding out.
*
=> Move split.soft_serial_pin to split.serial.pin

keyboards/pixelspace/capsule65i/keyboard.json
```
* The firmware size is approaching the maximum - 28294/28672 (98%, 378 bytes free)
```
*
=> `pixelspace/capsule65i`: reduce firmware size

keyboards/aidansmithdotdev/sango/keyboard.json, keyboards/takashicompany/heavy_left/keyboard.json
* Doesnt do anything
* `aidansmithdotdev/sango` also sets a logically conflicting value to its `config.h`
*
=> Remove incorrect use of split.main

keyboards/merge/um80/keyboard.json
```
* The firmware size is approaching the maximum - 28254/28672 (98%, 418 bytes free)
```
*
=> `merge/um80`: reduce firmware size

keyboards/meme/keyboard.json, keyboards/meme/keymaps/default/keymap.c
```
⚠ meme: Layout "LAYOUT_meme" should not contain name of keyboard.
```
Also worth noting this board is apparently [dead](https://geekhack.org/index.php?topic=94467.0), so perhaps it should instead be removed entirely.
*
=> `meme`: adjust layout names

lib/python/qmk/commands.py
Compilation tends to do everything each time -- we're constantly generating files as a precursor to a build, which updates `mtime`s and the like.
If regenerating the file doesn't change the content, then don't perform the write.
Doing rebuilds of the same board are significantly faster as a result.
=> [CLI] Only generate files if contents change.

keyboards/dasky/reverb/graphics/display.c
=> Fix Reverb lockup when using GCC14

keyboards/1upkeyboards/1upslider8/1upslider8.c, keyboards/boardsource/equals/equals.c, keyboards/hardwareabstraction/handwire/handwire.c, keyboards/neson_design/700e/700e.c, keyboards/neson_design/n6/n6.c, keyboards/pica40/rev1/rev1.c, keyboards/pica40/rev2/rev2.c, keyboards/stront/stront.c
Unlike other callbacks, `housekeeping_task_kb` should not itself call `housekeeping_task_user`. Doing so would cause it to be called twice as frequently as it should.
*
=> Remove duplicate calls to `housekeeping_task_user`

lib/python/qmk/cli/doctor/check.py
With the newer AVR GCC versions producing small binaries and the compilation issues surrounding them being addressed some time ago this warning is a little dated.
Changing the warning/check is another option but I feel like the severity should be reduced. The resultant minor problems detected just lead to confusion for some newer users.
*
=> Remove AVR GCC version warning

util/update_chibios_mirror.sh
We no longer use release tags for ChibiOS, so don't bother sync'ing them any further.
Same for ChibiOS 20.x, that's been removed.
Added some logic to ensure git revisions in the repo match up against what we're retrieving from SVN, mainly around dealing with re-cloning the repo. Does not change behaviour.
=> ChibiOS update script updates.

quantum/rgb_matrix/animations/starlight_anim.h, quantum/rgb_matrix/animations/starlight_dual_hue_anim.h, quantum/rgb_matrix/animations/starlight_dual_sat_anim.h
* Use unsigned integers
* Use lib8tion random8 function
* Test for valid LED flags
* Use rgb_matrix_hsv_to_rgb function
=> Refactor starlight RGB matrix effects

util/install/fedora.sh
As title. Install currently fails on Fedora 40 due to removal of dfu-programmer from the repo since 39...
*
=> Fix version check in Fedora install script to be >= 39

docs/features/mouse_keys.md, quantum/mousekey.c, quantum/mousekey.h
Enhance the overlapping mouse key press acceleration (introduced in #21494) with user preprocessor controls.
=> Enhance overlapping mouse keys control

.github/labeler.yml
Looks like the docs for actions/labeler@v5 do not line up with the actual behaviour.
When migrating, I copied the example `# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder` as it was what was previously used. But for keyboard PRs with keymaps, this does not add the label at all.
Bit of a stab... who knows.....
*
=> Attempt to fix auto 'keyboard' label

keyboards/zsa/moonlander/moonlander.c
In current `develop`, `zsa/moonlander` fails to build if `DEFERRED_EXEC_ENABLE` and `DYNAMIC_MACRO_ENABLE` are both defined:
```
keyboards/zsa/moonlander/moonlander.c: In function 'dynamic_macro_record_start_kb':
keyboards/zsa/moonlander/moonlander.c:48:1: error: expected ';' before '}' token
48 | }
| ^
keyboards/zsa/moonlander/moonlander.c: In function 'dynamic_macro_record_end_kb':
keyboards/zsa/moonlander/moonlander.c:59:1: error: expected ';' before '}' token
59 | }
| ^
```
Semicolons are actually missing from the preceding lines, which read
```c
return true
```
and
```c
return false
```
and this PR fixes the build.
*
=> Fix build failure on zsa/moonlander with DYNAMIC_MACRO_ENABLE

quantum/quantum.c
The previous implementation sends the same keycode variable to both pre_process_record_kb and process_combo. If changes are made to the record entry by pre_process_record_* functions that affect the keycode, it will not be reflected in the process_combo function.
This change ensures that the keycode variable in the process_combo function will be updated if modified.
=> Segregrate keycode at pre-process record quantum

lib/python/qmk/cli/lint.py
Shorter term change to follow #24322 and catch 'via' keymaps in keyboard PRs.
Rejecting arbitrary keymaps that have the via feature enabled in `rules.mk`/`keymap.json` will follow later,.
*
=> Reject via keymaps in lint

drivers/sensors/adns5050.c, drivers/sensors/adns5050.h, keyboards/ploopyco/trackball_nano/keymaps/default/keymap.c
This adds the ability to poweroff the ADNS5050 sensor and set this to happen on `suspend_power_down_user` for the ploopy nano.
As the LED on the trackball points up it can be a little annoying when the computer is suspended/off. 
I'm on the fence as to whether this should be the default for the ploopy as it would stop the trackball from being used to wake the computer.
=> Add ability to poweroff ADNS5050 sensor

docs/pr_checklist.md
Waiting on repo location before locking in changes.
*
=> Update PR Checklist for 'via' keymaps

docs/ChangeLog/20240825.md
As per title. As discussed on Discord.
=> Changelog update with actual `qmk_userspace_via` link.

keyboards/splitkb/aurora/corne/corne.c
There is a bug causing a visual glitch when multiple modifiers are pressed at the same time
Fix it
* None, I created the PR without issues first
Does not apply
=> fix: corne oled modifiers

quantum/rgb_matrix/rgb_matrix.c
Remove global k_rgb_matrix_split, all users have their own local definition.
=> Remove global k_rgb_matrix_split

util/uf2families.json
Sync with [current upstream revision](
https://github.com/microsoft/uf2/blob/5b9299df617c4610f4108aec774cf260271829ad/utils/uf2families.json).
*
=> [Core] util: uf2families: sync with upstream

docs/getting_started_docker.md
Little doc improvement for the docker getting started guide as result of a discussion on discord.
none
=> doc: "docker getting started" mentions `flash` limitations

builddefs/common_rules.mk, docs/other_vscode.md
Debug information is always generated while compiling a binary, but debugging is not the main use-case for the majority of users. Thus the new default is to explicitly require them with `DEBUG_ENABLE=yes`. The same is true for linker map files which are gated by the same flag.
As we target the gcc compiler and debug with the gdb debugger we can specify the ggdb3 flag in the most verbose to get macro expansion.
*
=> [Maintenance] builddefs: common_rules: overhaul debug information generation

docs/features/combo.md, quantum/process_keycode/process_combo.c, tests/combo/combo_repress/config.h, tests/combo/combo_repress/test.mk, tests/combo/combo_repress/test_combo.cpp, tests/combo/combo_repress/test_combos_repress.c
Allows for running code for combo key repressing after release
A copy-paste from new docs:
By defining `COMBO_PROCESS_KEY_REPRESS` and implementing `bool process_combo_key_repress(uint16_t combo_index, combo_t *combo, uint8_t key_index, uint16_t keycode)` you can run your custom code when you repress just released key of a combo. By combining it with custom `process_combo_event` we can for example make special handling for Alt+Tab to switch windows, which, on combo F+G activation, registers Alt and presses Tab - then we can switch windows forward by releasing G and pressing it again, or backwards with F key.
=> Add combo key repress feature

keyboards/4pplet/waffling80/rev_b_ansi/config.h, keyboards/4pplet/waffling80/rev_b_ansi/info.json, keyboards/4pplet/waffling80/rev_b_ansi/readme.md, keyboards/4pplet/waffling80/rev_b_ansi/rev_b_ansi.c, keyboards/4pplet/waffling80/rev_b_ansi/rev_b_ansi.h, keyboards/4pplet/waffling80/rev_b_ansi/rules.mk
Adding support for waffling80 hotswap, a open source h88/h87 TKL PCB: https://github.com/4pplet/waffling80 (hotswap version not yet added to readme)
=> Add waffling80 hotswap PCB

platforms/avr/drivers/spi_master.c, platforms/avr/drivers/spi_master.h, platforms/chibios/drivers/spi_master.c, platforms/chibios/drivers/spi_master.h
=> Allow for inverted SPI CS logic

keyboards/4pplet/waffling80/rev_b_ansi/keyboard.json
```
⚠ 4pplet/waffling80/rev_b_ansi: Build marker "keyboard.json" not found.
```
*
=> `4pplet/waffling80/rev_b_ansi`: fix missing `keyboard.json`

lib/python/qmk/search.py, lib/python/qmk/tests/test_cli_commands.py
Filters like `-f "exists(rgb_matrix.split_count)"` broke after #22887, because a plain dict was used instead of the `dotty` wrapper, therefore only keys with a single component worked.  Fix the implementation of filtering functions to use the `dotty` wrapper properly, so that keys with dots could be used in functions again.
Also add some tests for `qmk find` which get run by `qmk pytest` and should have caught the breakage introduced in #22887 if they existed at that time.
* Commands like `qmk find -f "exists(rgb_matrix.split_count)"` did not give the expected result if the specified key name contained multiple components separated with dots.  Other filtering functions (`absent`, `length`, `contains`) were also affected.
=> `qmk find`: Fix handling of keys with dots in filter functions

quantum/led_matrix/led_matrix.c, quantum/rgb_matrix/rgb_matrix.c
This reverts #24348, as it is actually needed for #24364. Instead, the local variable declarations have been removed. LED Matrix also updated for parity.
*
=> Reinstate global `k_rgb_matrix_split`

platforms/chibios/boards/GENERIC_STM32_L433XC/configs/mcuconf.h
Change STM32L433 LSI to False, this is to fix board startup issue, mcu config should be same to stm32L432 board.
* Fixes #24401
=> Workaround for broken STM32L433 startup

drivers/sensors/adns9800.c
Noticed reads were returning inconsistent data. Looking at the data sheet there should be a delay between the address write and subsequent data read.
This fixes the inconsistent read data.
*
=> Fix ADNS-9800 read

.editorconfig
On a recent PR (#23186) a section for YAML files was added, that included an inline comment (not starting on the first column), which used to be valid, but no longer¹. This produces an error at least with Emacs 29.4.
Also, normalize the name section expressing the file selection following a customary pattern. 
¹: https://spec.editorconfig.org/#no-inline-comments
* (change is so minor that I'll directly PR; hope that I’m not crossing a line here)
=> `.editorconfig`: fix inline comment, tidy name section for yaml

docs/reference_info_json.md
Using the [builtin `<Badge>` component in Vitepress](https://vitepress.dev/reference/default-theme-badge) to add some general type information for properties, and make the `(Required)`s look a bit nicer.
*
=> [docs] `reference_info_json`: add type hints

docs/feature_layers.md, docs/ref_functions.md, quantum/quantum.c, quantum/quantum.h
* Add `set_single_default_layer` to match `set_single_persistent_default_layer`
* Implements exactly the same behavior, except the write to EEPROM
* None that I know of
=> Add easier way to set default single layer

util/install/fedora.sh
As per title. Toolchain installation won't proceed if a package for `dfu-programmer` isn't found, but the install script still continues without flagging an error.
=> Install `dnf copr` plugin if not present (i.e. docker containers).

docs/features/os_detection.md, quantum/os_detection.c
* Default OS_DETECTION_DEBOUNCE bumped from 200ms to 250ms
* Add OS_DETECTION_SINGLE_REPORT to prevent undesired multiple reports
* Prevents random stability issues on ARM MacBooks after switching via KVM
* Works for every device I could test, including ARM MacBooks
* Disabled by default to keep current behavior
* Add Troubleshooting section on documentation
* Tweak reset logic to prevent a freeze with some KVMs
The USB stack on ARM MacBooks is more similar to that of iOS and,
for some reason, it seems to like sending packets that influence
the OS detection and results in a second OS_MACOS report being sent
at a random period of time after plugging the keyboard back. This
does not always happen and the consequences of this vary based on
what the user is doing in the callback, but since …
=> Tweak OS detect, add OS_DETECTION_SINGLE_REPORT

docs/features/pointing_device.md, quantum/pointing_device/pointing_device.c, quantum/pointing_device/pointing_device.h, quantum/pointing_device/pointing_device_drivers.c, tmk_core/protocol/report.h, tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/vusb/vusb.c
This PR contains the changes from my [previous PR](https://github.com/qmk/qmk_firmware/pull/24347) that are relevant to extended wheel reports. It can be merged independently.
An additional flag is added:
* `WHEEL_EXTENDED_REPORT`
In the event of a merge conflict with [PR 24423](https://github.com/qmk/qmk_firmware/pull/24423), refer back to my [previous PR](https://github.com/qmk/qmk_firmware/pull/24347) which contains the merged changes.
* https://github.com/qmk/qmk_firmware/issues/17585
=> Extended wheel reports

keyboards/thumbsup/keymaps/default/keymap.c, keyboards/thumbsup/keymaps/default/rules.mk
Fix invalid use of Tri-Layer keycodes.
`LT(TL_LOWR,KC_SPC), LT(TL_UPPR ,KC_SPC)` would not work. The use of `TL_LOWR` as a layer number, would effectively give `LT(12,KC_SPC)` and go out of bounds.
*
=> Fix `thumbsup:default` keymap

keyboards/noxary/valhalla_v2/valhalla_v2.c
Fixes Caps Lock indication on Valhalla V2 . The PCB suffers from the same problem than the Albatross PCB (see https://github.com/qmk/qmk_firmware/pull/22941) where the backlight feature, when paired with backlight as caps lock, gives a unwanted behavior.
=> Fix Caps Lock indication on Valhalla v2

quantum/keymap_introspection.c
Checks the count for tap dance to ensure it's not exceeding the max (0xFF), and to provide a more meaningful error when it is misconfigured.
The message is ... meh.  But have verified that it works.
based on master, so can retarget to that, if needed.
=> Expand count checks in keymap introspection

keyboards/akko/5108/5108.c, keyboards/monsgeek/m5/m5.c
Using host led callbacks to render will not correctly catch the cases where `keymap_config.no_gui` is mutated.
*
=> Fix rendering of `keymap_config.no_gui` within `led_update_kb`

data/mappings/defaults.hjson, data/schemas/keyboard.jsonschema, docs/feature_converters.md, platforms/chibios/converters/promicro_to_svlinky/_pin_defs.h, platforms/chibios/converters/promicro_to_svlinky/converter.mk
Add the svlinky RP2040 to the converters so that existing projects can be converted. The svlinky board is open source and available at:
https://github.com/sadekbaroudi/svlinky
This converter is for the v0.2. The v0.1 is already compatible with the `rp2040_ce` converter. I had to change the pinout to allow the controller to be fully compliant with the [vik specifications](https://github.com/sadekbaroudi/vik). The specification requires that the 2 extra gpio in the fpc connector are digital/analog. Given the RP2040 only has 4 analog capable pins, and all of them are used in the standard pinout on a pro micro controller, I had to take two of those out and swap them with different gpio, leading to this.
* N/A
=> Add svlinky converter

keyboards/zsa/moonlander/moonlander.c
`matrix_init_user` would get called twice, and `keyboard_post_init_user` not at all.
*
=> zsa/moonlander: Fix execution of user callback

quantum/bits.h, quantum/util.h
These helpers are handy and can prevent off-by-one errors when working
with registers and general low level bit manipulation tasks. The macros
themself are inspired by the bits.h macros from the linux kernel source
code.
*
=> [Core] quantum: util: add bit and bitmask helpers

tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/vusb/vusb.c
This value is a misunderstanding of the table found in the HID specification under §6.2.2.7 (possibly by me, but can also be found elsewhere on the internet I think), and should actually be `0x13`.
The least significant nibble here defines the measurement system (`0x3` = English Linear). The next nibble, however, always represents a unit of length, in this case being inches (for SI Linear it would be centimetres; for English Rotation, degrees). The key thing is that the Unit item is actually a multi-byte value, where the base units of length, mass, time, temperature, current and luminosity can be combined to describe more complex ones (some examples in the first link below).
So a value of `0x3` in the length nibble does not make sense as this specifies the *exponent* to apply to the unit. …
=> Digitizer: fix units tag in report descriptor

drivers/haptic/solenoid.c, keyboards/kikoslab/ellora65/keyboard.json, keyboards/rgbkb/pan/info.json, keyboards/takashicompany/minidivide/keyboard.json, keyboards/work_louder/loop/info.json, quantum/action_util.c, quantum/command.c, quantum/haptic.c, quantum/os_detection.c, quantum/os_detection.h, quantum/os_detection/tests/os_detection.cpp, quantum/process_keycode/process_haptic.c, tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/host.h, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/report.c, tmk_core/protocol/usb_device_state.c, tmk_core/protocol/usb_device_state.h, tmk_core/protocol/vusb/vusb.c
Previously all usb drivers and platform implementations (expect for our oddball atsam) tracked the same two global variables:
- `keyboard_protocol`: to indicate if we are in report or boot protocol
- `keyboard_idle`: for the idle_rate of the keyboard endpoint
And a local variable that was exposed trough some indirection:
- `keyboard_led_state`: for the currently set indicator leds (caps lock etc.)
These have all been moved into the `usb_device_state` struct wich is accessible by getters and setters.
This reduces code duplication and centralizes the state management across platforms and drivers.
This is then put into use for usb hid specification section 7.2.6:
> When initialized, all devices default to report protocol. However the
> host should not make any assumptions about the device’s …
=> [Core] `usb_device_state`: consolidate usb state handling across implementations

quantum/os_detection.c
It looks like a couple of instances of usb device state got missed. I missed them, too.
Addressed here, and I can confirm that it compiles and works
* Local compilation issues
=> [Bug] Fix compiliation issues with OS Detection

platforms/avr/timer.c, platforms/chibios/timer.c, platforms/timer.h
Needed to be able to set timer after exiting low power mode which requires clocks to be setup again. This allows things like timer_elapsed and deferred_exec to continue as normal.
*
=> Add timer_save and _restore functions.

quantum/rgb_matrix/animations/riverflow_anim.h
Simplify effect by reusing an existing runner
=> Refactor Riverflow matrix effect with runner

data/constants/keycodes/keycodes_0.0.1_midi.hjson, data/constants/keycodes/keycodes_0.0.2_kb.hjson, data/constants/keycodes/keycodes_0.0.2_midi.hjson, data/constants/keycodes/keycodes_0.0.2_user.hjson
Minor syntax changes (extra or missing commas) to improve consistency.
- [ n/a ] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [ n/a ] I have added tests to cover my changes.
=> Improve consistency of syntax within `data/constants/keycodes`

quantum/led_matrix/animations/breathing_anim.h
Simplify effect using an existing runner
=> Refactor LED Breathing effect with runner

lib/python/qmk/decorators.py
Handle both `<=1.8.0` and `1.9.0`, as we cant ensure a user has updated their environment.
```
/home/zvecr/qmk_firmware/lib/python/qmk/decorators.py:20: UserWarning: cli._subcommand has been deprecated, please use cli.subcommand_name to get the subcommand name instead.
if cli.config_source[cli._subcommand.__name__]['keyboard'] != 'argument':
```
*
=> Handle `cli._subcommand.__name__` deprecation warning

lib/python/qmk/search.py
Handle both `<=1.8.0` and `1.9.0`, as we cant ensure a user has updated their environment.
```
$ qmk find -f 'features.split=true'
Ψ Retrieving list of keyboards with keymap "default"...
<class 'AttributeError'>
☒ 'MILCInterface' object has no attribute 'log_level'
multiprocessing.pool.RemoteTraceback: 
"""
File "/usr/lib/python3.12/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
^^^^^^^^^^^^^^^^^^^
File "/home/zvecr/zv_firmware_clean/lib/python/qmk/search.py", line 148, in _keymap_exists
with ignore_logging():
File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
return next(self.gen)
^^^^^^^^^^^^^^
File "/home/zvecr/zv_firmware_clean/lib/python/qmk/search.py", line 132, in ignore_logging
old = …
```
=> Handle 'MILCInterface' object has no attribute 'log_level' error

keyboards/bastardkb/charybdis/charybdis.c, keyboards/bastardkb/dilemma/dilemma.c, keyboards/miiiw/blackio83/rev_0100/rev_0100.c, quantum/rgb_matrix/rgb_matrix.h
Exposing this API enables the examples in the keyboard shutdown/reboot documentation to compile instead of calling `rgb_matrix_driver.flush` directly.
* Fixes #24572
=> Expose rgb_matrix_update_pwm_buffers to be available in keymaps

docs/features/joystick.md, quantum/joystick.c, quantum/joystick.h, tmk_core/protocol/host.c, tmk_core/protocol/report.h, tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/vusb/vusb.c
Hat switches function a little differently to regular joystick axes, in that they have a "null" state rather than always having a value. Therefore it cannot simply be added by increasing the axis count.
Currently the report descriptor has been set up for an 8-way hat switch, but this could potentially be increased to anything that divides evenly into 360 and gives a maximum angle that is a whole number (so not 16-way as the pitch is 22.5 degrees and the max angle is 337.5). I've not checked whether the physical min/max tags are necessary so maybe this restriction is irrelevant.
Tested on Proton-C, V-USB not tested but should work too.
*
=> Joystick: add support for 8-way hat switch

docs/feature_macros.md, docs/reference_keymap_extras.md
- Document `host_language` in _Language-specific Keycodes_ instead of _Macros_.
- Removes the need for (outdated) table of supported languages.
- Mostly just shuffles existing text around.
Mention `host_language` in _Language-specific Keycodes_ so that those who use `keymap.json` instead of `keymap.c` also know how to include specific language headers. It's quite confusing to attempt including these language-specific headers without this information. E.g. trying to create `.h` files that includes them - but don't compile.
EDIT: as the _Macros_ page already had a description and example, I moved it into _Language-specific Keycodes_ and referenced it in _Macros_. I think it makes more sense to have it here, as the outdated list of supported languages can then also be removed, in favor of …
=> docs: move description of host_language from Macros to Language-specific Keycodes

docs/feature_advanced_keycodes.md
```md
|`LGUI(kc)`|`G(kc)`, `LCMD(kc)`, `LWIN(kc)`
```
Given the line above, this should probably be `RWIN`
*
=> docs: fix RWIN alias

lib/python/qmk/cli/new/keymap.py
Avoids slashes in the keymap name (eg. partial paths).
*
=> `qmk new-keymap`: validate keymap name

docs/porting_your_keyboard_to_qmk.md, lib/python/qmk/cli/new/keyboard.py
Instead of lumping everything into a giant list, we ask the user if their new keyboard project utilises a development board such as a Pro Micro, or has the microcontroller directly on the same PCB, then show the appropriate list. This has caused confusion for users in the past where they select eg. the bare RP2040 option when they are in fact using a particular RP2040-based devboard.
*
=> `qmk new-keyboard`: separate dev board and MCU selection

docs/cli_commands.md, lib/python/qmk/search.py, lib/python/qmk/tests/test_cli_commands.py
Replacing the singular `key = value` expression with support for the following operators:
- `key == value`: Match targets where `key` is equal to `value`. May include wildcards such as `*` and `?`.
- `key != value`: Match targets where `key` is not `value`. May include wildcards such as `*` and `?`.
- `key < value`: Match targets where `key` is a number less than `value`.
- `key > value`: Match targets where `key` is a number greater than `value`.
- `key <= value`: Match targets where `key` is a number less than or equal to `value`.
- `key >= value`: Match targets where `key` is a number greater than or equal to `value`.
*
=> `qmk find`: expand operator support

quantum/keyboard.c, quantum/layer_lock.c, quantum/layer_lock.h, quantum/process_keycode/process_layer_lock.c, quantum/process_keycode/process_layer_lock.h, quantum/quantum.c, quantum/quantum.h
Looks like i didnt actually hit the "submit review" button on #23430.
* Avoid `LAYER_LOCK_IDLE_TIMEOUT` implementation bleeding out
* Fix compilation with `NO_ACTION_LAYER`
* Remove incorrect comment content
*
=> Review fixes for layer lock feature

util/polling_rate.py
Since we often get users asking how to verify their board is actually running at 1000 Hz. Browser based testers may be "inaccurate" due to their measurement method; this script shows the requested polling rate from the device. Whether this is what the OS is truly polling at is out of QMK's control.
```
$ ./util/polling_rate.py
Evyd13 Wasdat (4705:C474:0001), 2.0 Full-speed
└─ HID Interface 0
├─ Subclass: Boot
├─ Protocol: Keyboard
└─ Endpoint 1 IN
├─ Endpoint Size: 8 bytes
└─ Polling Rate: 1 ms (1000 Hz)
└─ HID Interface 1
├─ Subclass: None
├─ Protocol: None
└─ Endpoint 2 IN
├─ Endpoint Size: 32 bytes
└─ Polling Rate: 1 ms (1000 Hz)
```
*
=> Simple Python script to show polling rate

builddefs/build_keyboard.mk
When both a `keymap.c` and `keymap.json` exist, a `rules.mk` is loaded multiple times.
Adding a `SRC += x.c` to a keymap level in this scenario, results in the compilation unit being appended twice, producing "multiple definition of" link issues.
*
=> Avoid loading keymap rules.mk twice

quantum/painter/qgf.c, quantum/painter/qp_draw_image.c
As title says.  When setting `OPT = 3` or similar heavy optimization, errors out with `-Werror=maybe-uninitialized` on a number of variables.  Initializing them should be harmlesss, as they're passed as pointers to other functions to be set, and fixes the errors without changing additional compiler options.
* issues locally
=> Fix Quantum Painter compiliation issues with heavy optimization

keyboards/murcielago/rev1/config.h, keyboards/murcielago/rev1/keymaps/default/keymap.c
Enable split watchdog for Murcielago for the keyboard to be detected on boot.
Tested on my own Murcielago running VIAL.
See: https://github.com/vial-kb/vial-qmk/pull/791
* n/a
=> [murcielago] Enable split watchdog

docs/hardware_keyboard_guidelines.md
Corrected a typo in the phrase "iOS device need lessthan 100" to "iOS devices need less than 100." 
This PR corrects a typographical error in the QMK documentation:
Original: "iOS device need lessthan 100."
Corrected: "iOS devices need less than 100."
This was to improve clarity and professionalism of the doc.
* This PR does not address any open issues since the change is minor and does not warrant a separate issue creation. The documentation's direct PR link was used for this fix.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the [**CONTRIBUTING** …
=> Update hardware_keyboard_guidelines.md to Fix Typos

keyboards/handwired/dactyl_manuform_pi_pico/config.h, keyboards/handwired/dactyl_manuform_pi_pico/keyboard.json, keyboards/handwired/dactyl_manuform_pi_pico/keymaps/default/keymap.c, keyboards/handwired/dactyl_manuform_pi_pico/readme.md
Adds new keyboard under handwired/dactyl_manuform_pi_pico
It is a mashup of alcor_datyl nad dactyl_manuform(5x6): a dactyl_manuform running on Pi Pico micro controller
Originally opened as  #21538 but I accidentally broke that repo when trying to re-base, thus a new one.
Started by cloning alcor_dactyl. Changed GPIOs to be Raspberry Pi Pico friendly.
Changed the layout to use dactyl_manuform 5x6. Added my default keymap.
*
=> Add dactyl_manuform_pi_pico

keyboards/skyloong/gk61/pro/config.h, keyboards/skyloong/gk61/pro/pro.c, keyboards/skyloong/gk61/pro_48/config.h, keyboards/skyloong/gk61/pro_48/pro_48.c
Keyboards should not override keycodes like `TO(x)` to behave like `PDF(x)`.
Also,
* Partially indicator logic as was dependent on overriding keycode behaviour
* Also made bad assumptions on configuration of keymap which user changes can invalidate
* Aligned implementations between the two pro revisions
* Remove some unused defines
*
=> skyloong/gk61: Remove overriding of core keycode behaviour

data/constants/keycodes/keycodes_0.0.1_basic.hjson
Fixes label for KC_MEDIA_PLAY_PAUSE 
New label was copied from https://github.com/qmk/qmk_firmware/blob/782f91a73a0f6d4128f9454509b4a207af269f8b/docs/keycodes_basic.md?plain=1#L209
Not sure if this should be fixed in the old version, or if a new one should be created. Did not find the key in any other versions.
Feel free to close if this update is not desired.
*
=> fix: KC_MEDIA_PLAY_PAUSE label

keyboards/lostdotfish/rp2040_orbweaver/keymaps/default/keymap.c
enhancement - power down indicator LEDs when host sleeps
*
=> [Keymap] Update rp2040_orbweaver

keyboards/vt40/keyboard.json, keyboards/vt40/keymaps/default/keymap.c, keyboards/vt40/keymaps/default/rules.mk, keyboards/vt40/readme.md
Added VT-40 keyboard
- [ x] Keyboard (addition or update)
=> Added VT-40 keyboard

lib/python/qmk/cli/doctor/main.py, lib/python/qmk/cli/import/kbfirmware.py, lib/python/qmk/cli/userspace/list.py, lib/python/qmk/git.py
`cli.log.warn` was deprecated in Python 3.3.
*
=> Resolve `cli.log.warn` warnings

tmk_core/protocol/chibios/usb_main.c
Depends on #24714 being merged
With the update of ChibiOS containing fixes for the OTGv1 LLD the workaround is not necessary anymore.
*
=> [Core] chibios: usb_main: remove OTG sof workaround

platforms/timer.h
A small refactoring of the defines `TIMER_DIFF_8`, `TIMER_DIFF_16`, `TIMER_DIFF_32` and `TIMER_DIFF_RAW`. Removing obsolete `TIMER_DIFF` helper definition. It makes the code more readable, understandable and maintainable.
Furthermore, it removes the "helper" `#define TIMER_DIFF`, which shouldn't be used directly by any code.
* https://github.com/qmk/qmk_firmware/issues/24652
=> small refactoring of TIMER_DIFF

docs/newbs_building_firmware.md
Add information regarding keyboards whose default keymaps are `.json` 
This documentation update will better guide users with keyboards containing default keymaps in the `keymap.json` format towards generating a `keymap.c` file.
*
=> Update newbs_building_firmware.md : Guide users whose keymaps are in `.json` format.

builddefs/common_features.mk
RGB Matrix has the following block <https://github.com/qmk/qmk_firmware/blob/master/builddefs/common_features.mk#L563-L569>, but the equivalent block is missing for LED Matrix.
* Fixes #24743
=> Set custom effect defines for LED Matrix

util/udev/50-qmk.rules
Noticed this when re-setting up system, at32 dfu bootloader was missed from the udev rules in #23445
* missing udev rule
- [] I have updated the documentation accordingly.
- [] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
=> Add ArteryTek AT32 dfu to udev rules

lib/python/qmk/info.py
Resurrecting #23941.
While its true this error should generally not happen to valid keyboards, users are constantly tripped up by the python stack trace that is otherwise spat out. This stack trace is output even if the board is not attempting to support RGB/LED matrix. 
This wall of text leads them down paths that are irrelevant to their issue. Worse is when reaching out for help, they then post the stack trace (usually as a screenshot...), and not the full output that shows the _actual_ error that triggered `matrix_size` to be undefined.
Before:
```
make clean  handwired/zeropad:default
QMK Firmware 0.27.1
☒ Not including data from file: keyboards/handwired/zeropad/keyboard.json
☒ 	matrix_pins: Additional properties are not allowed ('encoder' was unexpected)
☒ …
```
=> Skip parsing g_led_config when matrix_size is missing

keyboards/keychron/c1_pro/ansi/white/keyboard.json, keyboards/keychron/c2_pro/ansi/white/keyboard.json
`effect_max` is not a valid animation so should never be specified.
*
=> Remove invalid "effect_max" animation from keyboards

platforms/chibios/drivers/audio_pwm_hardware.c, quantum/audio/audio.c
The ARM audio PWM hardware implementation does not always return the audio pin to 0 when stopping the PWM. If the audio pin is held high while not playing audio, for magnetic speakers/buzzers, this will result in excessive current consumption while also producing undesirable audible noise.
This PR ensures that the audio pin is cleared whenever the PWM is stopped.
[Context (Discord)](https://discord.com/channels/440868230475677696/867530303261114398/1296753666723676183)
Only specific timers fully support disabling (clearing) the PWM output pin when the PWM is stopped. For timers that don't clear the output pin, this PR enforces stopping while the pin is low by ~(1) increasing the frequency as high as possible, (2) waiting for the pin to go low, and (3) only~ _edit:setting the PWM width to …
=> always return audio pin to 0 on ARM

quantum/rgb_matrix/animations/starlight_anim.h, quantum/rgb_matrix/animations/starlight_dual_hue_anim.h, quantum/rgb_matrix/animations/starlight_dual_sat_anim.h
* Improved effect to update LED index within led_min and led_max limits
* Check for LED flags
=> Update Starlight matrix effects

platforms/chibios/timer.c
[Context on Discord](https://discord.com/channels/440868230475677696/867530303261114398/1298603653413732363)
The ARM implementation of `timer_read()`/`timer_read32()` is not inherently safe to call from any context. Specifically, `chSysLock()`/`chSysUnlock()` are not safe to call from within interrupts. [An example](https://github.com/qmk/qmk_firmware/blob/32b6faaf353bf845a835bd7b71e53336fcb6416e/quantum/audio/audio.c#L443) of a system that calls `timer_read()` from an interrupt is `audio_update_state()` in `audio.c`.
This PR replaces the `chSysLock()`/`chSysUnlock()` function calls of `timer_read()` with `chSysGetStatusAndLockX()` and `chSysRestoreStatusX()` instead, which are safe to call from any context.
*
=> Ensure timer_read() is safe to call from interrupt handlers on ARM

quantum/rgb_matrix/animations/raindrops_anim.h
Improved effect with update to LED within `led_min` and `led_max` limits
=> Update Raindrops effect to respect LED range limits

docs/faq_debug.md
The link was broken (or more correctly put the information is not available at the wrong link). This PR points to the right section in the TMK docs.
*  N/A
=> Fix link to TMK magic commands

keyboards/durgod/k310/readme.md, keyboards/durgod/k320/readme.md, keyboards/durgod/k3x0/readme.md
As I was flashing my K320 I noticed that the links to the manufacture's websites were broken, and the flashing instructions were incorrect (`k310`/`k320` apparently used to reside below the `k3x0` folder, which is no longer the case).
* N/A
=> Fix durgod k3x0 docs

keyboards/rgbkb/sol3/rev1/keyboard.json
Due to power demands, the Sol 3 might get initially ignored or something by the attached device.
The solution is the enable watchdog, which would have the keyboard repoll the system to connect again.
I have been using watchdog for awhile, but given that the RGBKB developer never progressed #24279,
I made this to add in the essential feature.
* Should fix USB reconnect issues on power cycle for some users.
=> Add watchdog service to RGBKB Sol 3

util/install/macos.sh
All of these will conflict with the ARM toolchain that the `qmk` formula specifies as a dependency (`osx-cross/arm/arm-none-eabi-gcc@8`). This should help users who've accidentally installed the wrong one as they just need to rerun `qmk setup` or the install script directly instead of messing around with brew to manually uninstall the "bad" formulae.
*
=> macOS install: remove bad ARM toolchains

platforms/chibios/drivers/eeprom/eeprom_stm32_L0_L1.h
`EECONFIG_SIZE` is now dependent on datatypes in code, and thus isn't usable from preprocessor.
=> Remove preprocessor sanity check for STM32L0/L1 now that it relies on types in C.

docs/mod_tap.md
Title. Removes mention of `OSM()` as it seems irrelevant on mod tap page.
Fixes #24795
=> [Docs] Fix wording in Mod Tap documentation

quantum/process_keycode/process_underglow.c
If RGB Matrix is enabled and `RGB_MATRIX_DISABLE_SHARED_KEYCODES` is defined, `shifted` is set but never used, causing unused variable errors. 
* Fixes #24792
=> [Bug] Fix Underglow keycode processing

drivers/sensors/azoteq_iqs5xx.c, drivers/sensors/azoteq_iqs5xx.h
This aims to improve the behaviour when not using a motion pin. Using basic_profiling.h seems to have a fairly decent speed increase as less time is spent during I2C transactions.
```
Tweaked code
get_report -- Percentage time spent: 2% (idle)
get_report -- Percentage time spent: 2% (circle motion)
Old code
get_report -- Percentage time spent: 12% (idle)
get_report -- Percentage time spent: 63% (circle motion)
```
*
=> Azoteq - improve I2C behaviour while polling.

platforms/avr/timer.c, platforms/chibios/timer.c, platforms/test/timer.c, platforms/timer.c, quantum/debounce/tests/rules.mk, quantum/os_detection/tests/rules.mk, quantum/sequencer/tests/rules.mk
Saves a whole 20 bytes on AVR builds, and one less thing to implement on the RIOT port.
(Implementing as a define like timer_expired performs 22 bytes worse) 
*
=> Consolidate timer_elapsed implementations

platforms/avr/drivers/i2c_master.h, platforms/chibios/drivers/i2c_master.h
It's been a year, time to clean this up.
*
=> `i2c_master`: remove deprecated functions

data/mappings/info_rules.hjson
Been on the radar internally for a while, figured it was time we start the process of its removal.
Example output
```sh
$ qmk lint -kb ploopyco/trackball
⚠ ploopyco/trackball/rev1_005: DEFAULT_FOLDER in rules.mk is deprecated and will be removed at a later date
⚠ ploopyco/trackball/rev1_005: DEFAULT_FOLDER in rules.mk is deprecated and will be removed at a later date
Ψ Lint check passed!
```
*
=> Formally deprecate DEFAULT_FOLDER

builddefs/common_features.mk, quantum/dynamic_keymap.c, quantum/send_string/send_string.c, quantum/send_string/send_string.h
Consolidates handling of `send_string` et.al. such that the embedded commands using `SS_QMK_PREFIX` are consistently handled.
Tested on an AVR board, with string resident in RAM and PROGMEM. Tested with VIA and its use of `dynamic_keymap`.
=> Consolidate send_string implementations.

keyboards/ferris/0_1/matrix.c, keyboards/ferris/0_2/matrix.c, platforms/avr/drivers/i2c_master.h
These `I2C_READ` and `I2C_WRITE` defines don't need to exist.
The custom matrix code for `ferris/0_1` has been updated to align more closely with `0_2` by using `i2c_read/write_register()` instead. This was actually already done for `0_2` in #21273, but not `0_1` for some reason. They could possibly be completely identical but I mainly just wanted to clean up the `i2c_master` header.
*
=> `ferris/0_1`: update I2C API usage

quantum/dip_switch.c
While playing with test board, ran into "implicit definition of wait_ms" when dip switch map is enabled and `TAP_CODE_ENABLE` or `DIP_SWITCH_MAP_KEY_DELAY` is configured.
Considering it hasn't come up before now....
* compilation issue
=> Fix missing wait.h include in Dip Switch Map

quantum/action_tapping.c, tests/tap_hold_configurations/chordal_hold/hold_on_other_key_press/test_tap_hold.cpp, tests/tap_hold_configurations/chordal_hold/permissive_hold/test_tap_hold.cpp
I discovered an input sequence where Chordal Hold (https://github.com/qmk/qmk_firmware/pull/24560) leaves a mod in a stuck state.
**Repro example:** Suppose keys `LSFT_T(KC_A)` and `LCTL_T(KC_B)` are on the same hand, and the following input is made:
1. `LSFT_T(KC_A)` down
2. Wait unit the tapping term (Shift is now active)
3. `LCTL_T(KC_B)` down
4. `LSFT_T(KC_A)` up
5. `LSFT_T(KC_A)` down
6. `LCTL_T(KC_B)` up
7. `LSFT_T(KC_A)` up
where steps 3-5 are done quickly, within the tapping term. Then even after all keys are released, the Shift mod is stuck. The bug happens similarly with layer-tap keys or a mix of a mod-tap and a layer-tap key.
**Fix:** Handling goes wrong on step 5 of the example above, in the code `waiting_buffer_chordal_hold_taps_until()`. This function marks buffered events …
=> [Bug][Core] Fix for Chordal Hold: stuck mods when mod-taps are pressed in a stuttered sequence.

quantum/quantum.c
`process_record_via` completely takes over the functionality of `QK_MACRO`...`QK_MACRO_MAX`. As it's run before `process_record_kb`, there's no opportunity for keyboard- or user-level code to override.
This PR relocates the invocation of `process_record_via` after the equivalent `_kb` call, as VIA keymaps won't have these keycodes implemented in their keymap.
=> Invoke `process_record_via` after `_user`/`_kb` have a chance to handle it.

Makefile, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/resolve_alias.py
The aim is to minimise disruption to end users while we continue the deprecation process of `DEFAULT_FOLDER`.
Implementation is somewhat less than ideal, but hopefully its only temporary while `DEFAULT_FOLDER` handling still exists.
Enabled keyboard_aliases.hjson values to be used, for example
```
make 2_milk:default
```
While still allowing keyboards with `DEFAULT_FOLDER` to compile as before
```
make yosino58:default
```
*
=> Resolve keyboard_aliases when processing keyboard make targets

docs/cli_commands.md, docs/contributing.md, lib/python/qmk/cli/docs.py, lib/python/qmk/cli/generate/docs.py, lib/python/qmk/docs.py
These were removed during the move to Vitepress, however `vitepress dev` does have equivalent arguments.
Documentation for `qmk generate-docs` has been tweaked to emphasise it's only for emitting the production docs.
I've also adjusted `run_docs_command()` to make the dev server interactive, which provides a cleaner way to shut down than hitting Ctrl+C.
*
=> `qmk docs`: restore `--port` and `--browser` arguments

lib/python/qmk/cli/format/text.py
```python
qmk format-text /c/Users/treyw/qmk_firmware/keyboards/cloud_macro/readme.md
☒ expected string or bytes-like object, got 'WindowsPath'
File "C:/QMK_MSYS/mingw64/lib/python3.11/site-packages/milc/milc.py", line 604, in call
return self.call()
^^^^^^^^^^^^^^^
File "C:/QMK_MSYS/mingw64/lib/python3.11/site-packages/milc/milc.py", line 609, in call
^^^^^^^^^^^^^^^^^^^^^^
File "C:/Users/treyw/qmk_firmware/lib/python/qmk/cli/format/text.py", line 57, in format_text
return dos2unix_run(files)
^^^^^^^^^^^^^^^^^^^
File "C:/Users/treyw/qmk_firmware/lib/python/qmk/cli/format/text.py", line 22, in dos2unix_run
dos2unix = cli.run(['dos2unix', *chunk])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Avoid WindowsPath errors for 'qmk format-text'

util/install/gentoo.sh
I tried to install the dependencies using the `qmk setup` script and it failed on my machine. While digging into the install script, I noticed that there is an old name of the clang dependency, which recently changed, see here: https://github.com/gentoo/gentoo/commit/1f9f1999cdc8ccb94054dec2d2951c7e486aa996.
*
=> Fix installation of clang in gentoo install script

quantum/action.c, tests/tap_hold_configurations/retro_tapping/test_key_roll.cpp
The purpose of this PR is to fix the condition found with RETRO_TAPPING enabled when key rolling. The issue is that the dual function keys's retro tap keycode is not fired when a different key has been released between the dual function keys's down and up events. I am not sure if this is intended behavior or not, but does not seem to be given that retro tapping is supposed to apply if another key is not pressed. Also, none of the existing tests failed after the re-write.
I had to rewrite the logic, though the original idea is still intact. When considering key rolling from a dual function key to a dual function key, it was necessary to capture the previous modifier state and temporarily apply it to the tap code. There is a unit test for this.
This is still an early draft. I am brand new …
=> Retro Tapping Re-Write; Key Roll Fix

lib/python/qmk/cli/lint.py
Enforcing #24912, and flagging bad readmes in PRs.
*
=> Reject readme dummy content

keyboards/a_jazz/akc084/keyboard.json, keyboards/a_jazz/akc084/keymaps/default/keymap.c, keyboards/a_jazz/akc084/readme.md
Fix indicators, image, bootloader instructions and default keymap for 'A-JAZZ AKC084'
**Keyboard Indicators:**
By default, the new keyboard has indicators for CapsLock and ScrollLock. After flashing, these indicators changed to CapsLock and NumLock, even though there is no NumLock key on the keyboard.
**Layout Mismatch:**
The standard layout does not match the keys Pause, Del, End. This discrepancy is visible in the image in the Readme and on the product page in the store.
**BootLoader Entry Instructions:**
To enter BootLoader mode, you need to press Esc and reconnect the keyboard, instead of Enter as stated in the instructions.
* Fixes #24853
=> Update for 'A-JAZZ AKC084' ('A-JAZZ AKP846')

platforms/chibios/drivers/eeprom/eeprom_stm32_L0_L1.c
This fixes the STM32L0/1 driver for devices which only support writing null (all 0s) for full and double word writes.
Per [RM0038](https://www.st.com/resource/en/reference_manual/rm0038-stm32l100xx-stm32l151xx-stm32l152xx-and-stm32l162xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) section 3.4.3:
>  Data EEPROM Byte Write
This operation is used to write a NON NULL (This restriction applies only for Cat.1 devices) byte to the data EEPROM whatever the
previous value of the word to be written to. The time taken for this is 1 or 2 tprog, depending
on the FTDW bit (see Table 20 on page 77 for more details).
Required by https://github.com/qmk/qmk_firmware/pull/24916
=> fix EEPROM driver for STM32L0/1 cat.1 devices

docs/quantum_painter.md
[Docs] Fix example code in quantum_painter.md
Fixes #24896 
Fixes example code that would unintentionally display an image 1 pixel up-left of the intended bottom-right corner position. Additionally, fixes edge case causing uint16_t overflow for images the same size as the display.
See #24896 for more details. 
* #24896
=> [Docs] Fix example code in quantum_painter.md

data/schemas/keyboard.jsonschema
Spotted on 24994,
```json
{"matrix": [5, 4], "x": 44, "y": 32, "flags": 1},
{"flags": 1}
```
Note: `flags` has not been made mandatory as we have existing keyboards which do not specify the property.
*
=> Require 'x'/'y' properties for LED/RGB Matrix layout

lib/python/qmk/cli/generate/rules_mk.py, lib/python/qmk/path.py
Python was handing out Windows-style "posix" paths with drive letter but normal forward slashes. Generating the `rules.mk` caused issues with the output, so this fix adds a function similar to `cygpath` and swaps the drive letter to a unix-style rooted path.
Happy to entertain "better" suggestions as far as the conversion goes.
=> Fixup MSYS + unix-style paths in Community Modules.

docs/features/split_keyboard.md
Fixes typo in the split keyboard section of the docs ("theres's -> "there's").
* fixes #24983
=> Fix typo in docs: split_keyboard.md SPLIT_USB_DETECT ("theres's -> "there's")

modules/qmk/super_alt_tab/qmk_module.json, modules/qmk/super_alt_tab/super_alt_tab.c
Adds the Super Alt-Tab behavior from the [macros example](https://docs.qmk.fm/feature_macros#super-alt%E2%86%AFtab) as a module, with some configurable options
Blame tzarc
=> Add Super Alt-Tab macro example as module

keyboards/maxr1998/phoebe/keyboard.json, keyboards/maxr1998/phoebe/keymaps/default/config.h, keyboards/maxr1998/phoebe/keymaps/default/keymap.c, keyboards/maxr1998/phoebe/phoebe.c
Updating the default keymap of Phoebe to remove complex leader key support and include the more useful mouse key support instead. This is also to move towards a more pristine default keymap. Nonetheless, the default keymap of this board is still targeted towards German QWERTZ users, requiring various layers and macros to support all special characters.
=> Enable mouse key feature and disable leader key on Maxr1998/Phoebe

keyboards/ploopyco/trackball_thumb/rev1_001/config.h
PR #24880, has swapped encoder pins on ploopyco/trackball_thumb/rev1_001 
This seems to have been in error, reversing scroll direction.
Previous pin defs from old `keyboards/ploopyco/trackball_thumb/config.h` re-instated to current `keyboards/ploopyco/trackball_thumb/rev1_001/config.h` 
https://github.com/qmk/qmk_firmware/pull/24880/files
*
=> fix swapped encoder pins on ploopy thumb rev1_001 

lib/python/qmk/cli/generate/rules_mk.py
Modules may need access to the current path, in order to add relative paths to say, `COMMON_VPATH`.
Refer https://github.com/tzarc/qmk_modules/blob/main/experimental/filesystem/rules.mk#L11-L12
=> [Modules] Provide access to current path in `rules.mk`.

keyboards/annepro2/annepro2.c
Without this `mcu_reset()`, the QK_REBOOT key did nothing for the Anne Pro 2 keyboard.
*
=> Allow AnnePro2 to reboot

platforms/chibios/vendors/RP/RP2040.mk, quantum/bits.h
Fix path typo: `platfrom` → `platform` (RP2040-related).
*
=> Fix path typo related RP2040

keyboards/handwired/onekey/nucleo_f446re/config.h, keyboards/handwired/onekey/nucleo_f446re/keyboard.json, keyboards/handwired/onekey/nucleo_f446re/readme.md
The onekey example for the nucleo f446re board doesn't work: this PR updates the example. 
The onekey example for the nucleo f446re board doesn't work as it relies on pin A2, which by default isn't connected to a pin header but to USART (see the schematic available at [the ST website](https://www.st.com/en/evaluation-tools/nucleo-f446re.html#cad-resources)). This PR updates the pin assignments to use A0 and A1 which are both accessible on the standard board pin headers.
=> Update onekey example for nucleo f446re

modules/qmk/hello_world/hello_world.c
Lockups occur on AVR when using `printf` instead of `dprintf`.
=> Fix lockups on AVR with `qmk/hello_world` module

data/schemas/community_module.jsonschema, docs/features/community_modules.md, lib/python/qmk/json_encoders.py, modules/qmk/hello_world/qmk_module.json, modules/qmk/super_alt_tab/qmk_module.json
This PR adds an optional "`license`" field to indicate a license in the `qmk_module.json` file of a community module.
It is desirable that module authors indicate a license to clarify how the module may be used and shared, to foster collaboration and wider adoption.
* A simple string "`license`" field is added to the schema for `qmk_module.json`.
* In the documentation, I recommend that this field is a [SPDX license identifier](https://spdx.org/licenses/) like "`Apache-2.0`" or "`GPL-2.0-or-later`" if possible. Even so, the field allows an open-ended text description in case of more complex licensing situations.
* I updated the `qmk/hello_world` and `qmk/super_alt_tab` modules with `"license": "GPL-2.0-or-later"`, matching the license on their source files.
* While I was at it, I updated …
=> Add "license" field to Community Module JSON schema.

keyboards/coban/pad9a/keyboard.json
coban pad9a show wrong layout
Current:
https://config.qmk.fm/#/coban/pad9a/LAYOUT
Expect:
I change location of key_6 from [2, 3] to [2, 2]
*
=> Fix coban pad9a wrong layout in keyboard.json

builddefs/converters.mk, data/mappings/info_rules.hjson
Deprecated and marked as a build error for 2 years now.
*
=> Remove `CTPC`/`CONVERT_TO_PROTON_C` options

platforms/chibios/converters/promicro_to_promicro_rp2040/pre_converter.mk
https://docs.qmk.fm/ChangeLog/20240825#sparkfun-pro-micro-rp2040-converter-renamed-24192
Converter was marked as deprecated and removed from docs, but nothing is currently being shoved in users faces to tell them what they are doing is incorrect.
*
=> Add warning when deprecated 'promicro_rp2040' is used

keyboards/work_louder/rgb_functions.c
Allows disabling Underglow on Work Louder devices by using `RGBLIGHT_ENABLE = no` on rules.mk. Reduces firmware size to allow using other features. 
* fixes #25123
=> chore: Allow disabling underglow on Work Louder devices (#25123)

lib/python/qmk/cli/lint.py, lib/python/qmk/keymap.py
Updated `qmk lint` default behaviour of checking "default-ish" keymaps to ignore userspace.
There are a few things to consider,
* someone might want to actually lint userspace keymaps?
* not a ton of value right now, but with the recent `keymap.json` changes will become more important
* can still do `qmk lint -kb whatever -km my_important_keymap`
* `-km all` behaviour?
* currently still checks userspace
* would prefer not to have to add an additional `--userspace`/`--no-userspace` arg 
* Fixes #24676
=> Exclude external userspace from lint checking

keyboards/adm42/rev4/keyboard.json, keyboards/ashwing66/keyboard.json, keyboards/eek/info.json, keyboards/ein_60/keyboard.json, keyboards/fs_streampad/keyboard.json, keyboards/geekboards/macropad_v2/keyboard.json, keyboards/handwired/hnah40rgb/keyboard.json, keyboards/marcopad/keyboard.json, keyboards/mechboards/crkbd/pro/keyboard.json, keyboards/mechboards/lily58/pro/keyboard.json, keyboards/mechboards/sofle/pro/keyboard.json, keyboards/momokai/aurora/keyboard.json, keyboards/momokai/tap_duo/keyboard.json, keyboards/momokai/tap_trio/keyboard.json, keyboards/rot13labs/veilid_sao/keyboard.json, keyboards/splitkb/halcyon/kyria/rev4/keyboard.json, keyboards/system76/launch_1/keyboard.json
Removed config options where they are duplicating defaults while implementing 25149.
*
=> Remove duplication of RGB Matrix defaults

builddefs/common_features.mk, data/schemas/keyboard.jsonschema, quantum/dynamic_keymap.c, quantum/eeconfig.c, quantum/led_matrix/led_matrix.c, quantum/rgb_matrix/rgb_matrix.c, quantum/unicode/unicode.c, quantum/via.c
Allow for disabling the EEPROM subsystem entirely. NVM is now exposed to `eeconfig`, `via`, `dynamic_keymap` et.al. -- EEPROM is no longer necessary when NVM is implemented through other means.
Code diff is best viewed with whitespace disabled.
=> Allow for disabling EEPROM subsystem entirely.

lib/python/qmk/cli/doctor/check.py
When running `qmk setup` on msys, with missing submodules, the "Would you like to clone the submodules? [Y/n]" prompt refuses to accept any input.
Questions asked before the `check_binary_versions` call work, anything afterwards, broken.
From <https://github.com/clueboard/milc/blob/master/milc/milc.py#L170-L173>
```py
````
* <https://discord.com/channels/440868230475677696/473506116718952450/1344341968930476063>
=> Fix 'Would you like to clone the submodules?' prompt under msys

quantum/eeconfig.c
Lighting wasn't being reset correctly after an `EE_CLR`. The initial write of zero's to the lighting would effectively turn the subsystems off, and as such would disregard any attempts to update values within the configuration as all the APIs are guarded by an `if (!xxx_matrix.enabled) { return; }` or equivalent.
Basically, the example in the docs ([here, down the bottom](https://docs.qmk.fm/feature_eeprom#example-implementation)) was non-functional.
This change forces defaults to be written rather than zero's, but also in the case of rgb_matrix / led_matrix flushes the eeprom once the kb/user eeconfig hooks have been invoked. This ensures any changes those hooks made are actually saved.
Happy to rebase onto `master` if we think it's worth fixing there.
=> Fixup eeconfig lighting reset.

lib/python/qmk/cli/lint.py
Empty "url" fields serve no value for the repo.
This PR adds a lint warning so that we can begin to require this, without breaking anything. Next cycle we can then promote this to an error.
```
qmk lint -kb handwired/ziyoulang_k3_mod
⚠ handwired/ziyoulang_k3_mod: Invalid keyboard level config detected - Optional field "url" should not be empty.
Ψ Lint check passed!
```
*
=> Add lint warning for empty url

lib/python/qmk/cli/new/keymap.py
Converter discoverability is fairly low. [Part of the tutorial](https://docs.qmk.fm/newbs_building_firmware#create-a-new-keymap) suggests the user starts with `new-keymap`. 
Adding in a prompt to configure for compatible boards might avoid some confusion.
```
$ qmk new-keymap -kb sofle_choc -km asdf
Ψ Generating a new keymap
Configure Development Board
For more information, see:
https://docs.qmk.fm/feature_converters
Use converter? 
1. No (default)
2. bit_c_pro
3. blok
4. bonsai_c3
5. bonsai_c4
6. elite_pi
7. helios
8. imera
9. kb2040
10. liatris
11. michi
12. promicro_rp2040
13. proton_c
14. rp2040_ce
15. sparkfun_pm2040
16. stemcell
17. svlinky
Please enter your choice: [1]
```
*
=> Prompt for converter when creating new keymap

builddefs/build_keyboard.mk, lib/python/qmk/cli/generate/community_modules.py, lib/python/qmk/cli/generate/rules_mk.py, lib/python/qmk/info.py
Due to the way the content was previously generated, the moving of module config to slightly later does not change the effective order.
Also avoids the scenario where `keymap.json` "keyboard` field has a different value to the currently comping keyboard. This can happen when a keymap is shared across multiple revisions (or just set to a completely incorrect value).
```
keyboards/test/rev1/keyboard.json - include module A
keyboards/test/rev2/keyboard.json - include module B
keyboards/test/keymaps/default/keymap.json - include module C sets keyboard field to "test/rev1"
```
If you then compile `test/rev2:default` it will incorrectly pull in modules A, B and C
*
=> Avoid duplication in generated community modules `rules.mk`

data/mappings/info_defaults.hjson, lib/python/qmk/cli/lint.py
Example output:
```
qmk lint -kb all 2>&1 | grep "duplicates default value" | grep -v features.console | grep -v features.command
☒ cipulot/ec_980c: Option "rgb_matrix.max_brightness" duplicates default value of "255"
☒ custommk/evo70_r2: Option "backlight.breathing_period" duplicates default value of "6"
☒ darmoshark/k3: Option "indicators.on_state" duplicates default value of "1"
☒ dnworks/frltkl: Option "indicators.on_state" duplicates default value of "1"
☒ dnworks/sbl: Option "indicators.on_state" duplicates default value of "1"
☒ dnworks/tkl87: Option "indicators.on_state" duplicates default value of "1"
☒ ebastler/e80_1800: Option "backlight.on_state" duplicates default value of "1"
☒ handwired/daskeyboard/daskeyboard4: Option "indicators.on_state" duplicates default value of "1"
☒ …
```
=> Extend lint checks to reject duplication of defaults

quantum/action_tapping.c, tests/tap_hold_configurations/chordal_hold/permissive_hold_flow_tap/config.h, tests/tap_hold_configurations/chordal_hold/permissive_hold_flow_tap/test.mk, tests/tap_hold_configurations/chordal_hold/permissive_hold_flow_tap/test_keymap.c, tests/tap_hold_configurations/chordal_hold/permissive_hold_flow_tap/test_one_shot_keys.cpp, tests/tap_hold_configurations/chordal_hold/permissive_hold_flow_tap/test_tap_hold.cpp, tests/tap_hold_configurations/flow_tap/test_tap_hold.cpp
Make [Flow Tap](https://github.com/qmk/qmk_firmware/blob/develop/docs/tap_hold.md#flow-tap) better for rolls over multiple tap-hold keys: when `tapping_key` is settled as tapped, re-check whether Flow Tap applies to buffered events.
Currently, Flow Tap potentially intervenes only on the key down event. As pointed out by @amarz45 https://github.com/qmk/qmk_firmware/pull/25175#issuecomment-2822026962, it would be desirable, supposing <kbd>A</kbd> and <kbd>B</kbd> are both tap-hold keys, that the following quickly-typed input would apply Flow Tap to settle <kbd>B</kbd> as tapped:
1. <kbd>A</kbd>&nbsp;↓
2. <kbd>B</kbd>&nbsp;↓
3. <kbd>A</kbd>&nbsp;↑ (<kbd>A</kbd> settled as tapped)
However, Flow Tap currently only evaluates <kbd>B</kbd> on key down in step 2, but at that time, <kbd>A</kbd> is …
=> [Core] Enhance Flow Tap to work better for rolls over multiple tap-hold keys.

keyboards/spleeb/rules.mk, keyboards/spleeb/spleeb.c
spleeb.c relied on changing the glide setting at runtime and the `cirque_pinnacle_enable_cursor_glide` was no longer being included and was producing build errors. 
This change explicitly includes `drivers/sensors/cirque_pinnacle_gestures.h` to address this. 
If there is a "more correct" approach here I am happy to adjust the code as needed. 
*
=> Fix Spleeb compile when pointing device is enabled

builddefs/common_features.mk, builddefs/common_rules.mk, keyboards/stront/stront.h, platforms/chibios/bootloaders/uf2boot.c
When writing a module which included lua, naming collisions were occurring with `panic` and the like due to `POST_CONFIG_H` inclusions pulling in the pico-sdk for every compiled file, resulting in conflicting function signatures with the name of the one in lua itself.
This limits the `POST_CONFIG_H` inclusions to where they're required, setting up file-specific forced inclusions instead. Leverages the same plumbing as the ChibiOS init hook overrides for the board files, renaming the variable to something a bit more generic in the process.
=> [Bug] Minimise force-included files

lib/python/qmk/cli/new/keymap.py
From <https://github.com/qmk/qmk_userspace/issues/45>
> I also tried splitkb/kyria/rev2 which returns keyboard doesn't exist.
This would work if provided with the `--keyboard` argument, but any alias would not be resolved if specified via the keyboard prompts.
*
=> Resolve alias for `qmk new-keymap` keyboard prompts

keyboards/binepad/kn01/keyboard.json, keyboards/binepad/kn01/keymaps/default/keymap.json, keyboards/binepad/kn01/readme.md, keyboards/binepad/kn01/rules.mk
Addition of the Binepad NeoKnob KN01 rotary dial.
> This is an older model that was initially posted on Vial back in [March 2023](https://github.com/vial-kb/vial-qmk/commit/6c0ef5cbaedec62e0bd0e5936e0fbff8ea41ed80).
* (n/a)
=> [Keyboard] Add Binepad KN01

docs/drivers/battery.md, drivers/battery/battery.c, drivers/battery/battery.h
Avoids the following sort of code block:
```c
void housekeeping_task_kb(void) {
static uint16_t bat_timer = 0;
static uint8_t last_bat_level = UINT8_MAX;
if (timer_elapsed(bat_timer) > 5000) {
uint8_t level = battery_get_percent();
if (level != last_bat_level) {
// do something
last_bat_level = level;
}
}
}
```
Where the caching of value within `battery_get_percent` might not align with when the timer is checked.
This can now be reduced to:
```c
void battery_percent_changed_kb(uint8_t level) {
// do something
}
```
*
=> Add battery changed callbacks

lib/python/qmk/userspace.py
When `user.overlay_dir` is set, but current directory is inside a different `qmk_userspace` folder, the resolved order of the userspace directory resolves randomly. One compilation it can pick the "correct" directory, 30 seconds later the next invocation it can pick a different one.
This is due to the result of the `set -> list` not maintaining insertion order. Copied strat used by community modules to fix the issue.
*
=> Ensure `qmk_userspace_paths` maintains detected order

drivers/bluetooth/bluetooth.c, drivers/bluetooth/bluetooth.h, quantum/action_util.c, tmk_core/protocol.mk, tmk_core/protocol/host.c, tmk_core/protocol/host.h
Compiling Bluetooth enabled firmware currently produces the following:
> NKRO is not currently supported with Bluetooth, and has been disabled.
This is somewhat pointless, as the keyboard would still be perfectly capable of supporting NKRO over USB.
This PR removes USB only assumptions in `send_keyboard_report`, and adds a Bluetooth stub that maintains the existing behaviour. 
*
=> Remove force disable of NKRO when Bluetooth enabled

quantum/command.c
Enabling both LAYER_STATE_32BIT and CONSOLE_ENABLE currently causes QMK not to compile due to a mismatch in the types expected in a print statement in quantum/command.c.
I simply added a definition check around the print statement and handled both print statments independently.
* fixes #25026
=> Fixed print statement after enabling 32-bit layers

keyboards/splitkb/aurora/sweep/keymaps/default/keymap.json
Aurora sweep default keymap had some invalid configuration for the mouse keys and tapping. Duplicate items which were already set in the `keyboard.json` have also been removed.
*
=> Fix Aurora sweep default keymap configuration

keyboards/cxt_studio/12e3/keyboard.json, keyboards/cxt_studio/12e3/keymaps/default/keymap.c
Added resolutions to keyboard.json encoders so they apply properly.
Also took the opportunity to tweak the default keymap layout slightly.
*
=> CXT Studio 12E3: Fix encoder resolutions not applying

builddefs/common_features.mk, drivers/wear_leveling/wear_leveling_flash_spi.c, platforms/chibios/drivers/wear_leveling/wear_leveling_efl.c, platforms/chibios/drivers/wear_leveling/wear_leveling_legacy.c, platforms/chibios/drivers/wear_leveling/wear_leveling_rp2040_flash.c, platforms/eeprom.h, quantum/wear_leveling/wear_leveling.c, quantum/wear_leveling/wear_leveling_drivers.h
Fixes post #25194. Alternative solutions welcome.
The following builds cover the currently failing scenarios
```bash
make clean handwired/onekey/kb2040:default VIA_ENABLE=yes
make clean handwired/onekey/blackpill_f401:default VIA_ENABLE=yes
make clean monsgeek/m5:default VIA_ENABLE=yes
make clean smithrune/iron160/iron160_h:default VIA_ENABLE=yes
```
*
=> Fix Wear Leveling compilation

quantum/os_detection.c
In #24379 the OS_DETECTION_KEYBOARD_RESET logic got inadvertently changed to only reset if the keyboard ends up stuck in the INIT phase, which was apparently an issue with some KVMs, but this means that it no longer does what it originally was meant to do.
This PR leaves that functionality, but also resets the keyboard on USB device reinitilization again, as long as it had been stable for debounce duration before that. The debounce time used for reset is by default the same as for the detection, but it can be tuned with the undocumented `OS_DETECTION_RESET_DEBOUNCE` setting.
We set the debounce timer in the USB device change callback, because reacting to state changes in the main task loop feels racy. Actual reset still happens in `os_detection_task`, because some MCUs seem not to like it …
=> Fix OS_DETECTION_KEYBOARD_RESET

keyboards/magic_force/mf17/keyboard.json
* Magic Force MF17 numpad numlock indicator is not turning on.
=> Fixes the numlock indicator for Magic Force MF17 numpad

tmk_core/protocol/report.c
Only checking `usb_device_state_get_protocol` blocks other host drivers from correctly implementing NKRO.
*
=> Remove more USB only branches from NKRO handling

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/config_options.md, docs/features/stenography.md, docs/reference_info_json.md, quantum/eeconfig.c, quantum/keyboard.c
More work on unpicking the assumption that only USB can do NKRO. As well as removing the logic that NKRO should be "forced", when it doesnt actually force NKRO packets, but rather force the config to reset every boot. This is completely unnecessary when the setting persists.
As always, names are up for grabs before they are locked in.
*
=> Deprecate `usb.force_nkro`/`FORCE_NKRO`

quantum/rgb_matrix/animations/pixel_flow_anim.h, quantum/rgblight/rgblight.c
Some places are missing the correct overrideable weak functions.
*
=> [Chore] use {rgblight,rgb_matrix}_hsv_to_rgb overrides

builddefs/common_features.mk
These FastLED derived lib8tion functions have been fixed and enabled by default in FastLED. QMK just never set these defines, there is no reason to keep the buggy implementation. It is assumed that nobody relied on the buggy behavior.
*
=> [Fix] lib8tion: enable fixed scale8 and blend functions

keyboards/salicylic_acid3/getta25/keymaps/oled/config.h
[CI](https://github.com/qmk/qmk_firmware/pull/25293/checks?check_run_id=42806452897) produces the following error:
```
Compiling QMK Firmware for target: 'salicylic_acid3/getta25/rev1:oled'...
Generating: .build/obj_salicylic_acid3_getta25_rev1_oled/src/info_deps.d                            [OK]
Generating: .build/obj_salicylic_acid3_getta25_rev1_oled/src/community_modules.c                    [OK]
avr-gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
Generating: .build/obj_salicylic_acid3_getta25_rev1_oled/src/community_modules.h                    [OK]
Generating: …
```
=> salicylic_acid3/getta25 - Fix oled keymap

keyboards/1upkeyboards/pi50/pi50.c, keyboards/tzarc/djinn/graphics/theme_djinn_default.c
Bugfix; community module names were showing up as `Unknown`.
=> [tzarc/djinn] Include community modules in RGB naming.

Makefile, data/mappings/info_rules.hjson, docs/config_options.md, lib/python/qmk/cli/ci/validate_aliases.py, lib/python/qmk/cli/list/keyboards.py, lib/python/qmk/cli/migrate.py, lib/python/qmk/cli/resolve_alias.py, lib/python/qmk/info.py, lib/python/qmk/keyboard.py, lib/python/qmk/path.py
Currently `DEFAULT_FOLDER` serves 2 main purposes:
1. Maintaining backwards compatibility when new keyboard revision is added
* The existing `make <vendor>/<product>`  can be mapped to `make <vendor>/<product>/rev1`
2. Parent folders contain common configuration
* The presence of a `rules.mk` creates a build target that only has partial information and cannot be built 
Unfortunately an additional purpose has been adopted:
3. Providing a shorter form for users to specify in terminal commands
While the current solution "works", there are a fair few problems this functionality causes:
1. Many keyboards within the repo put config in incorrect locations and rely on `DEFAULT_FOLDER` to patch up the problems
2. Keyboard updates can change `DEFAULT_FOLDER` to a new revision and not maintain …
=> Remove `DEFAULT_FOLDER` handling

.clangd, lib/python/qmk/compilation_database.py, platforms/avr/_wait.h
The auto-detected compiler args were seemingly breaking clangd, overriding its own internal auto-detection routines:
* Updated `.clangd` to be multiline, so we can do proper diffs when the file changes in the future
* The executable is now changed to fully qualify the compiler path
* The executable was the one on vscode/clangd's `$PATH`, not the one actually used by the QMK CLI -- this would affect any instance which deals with the environment, so using `direnv` or the bootstrap distribution would usually result in the system-provided `avr-gcc` or `arm-none-eabi-gcc` being used by `clangd`
* The compiler's integer defines -- specifying things like type widths -- seemed to conflict with the auto-detection within clangd itself
* These are now stripped from the list of defines
* The …
=> More compiledb fixes.

docs/keycodes.md, docs/keycodes_basic.md, docs/mod_tap.md
A small terminology tweak based on a quick Google, it seems like Super is the more common name for the GUI key in Linux land (although it may possibly depend on your DE?).
*
=> [docs] Change GUI key references to "Meta" -> "Super"

keyboards/inland/kb83/keyboard.json, keyboards/inland/kb83/keymaps/default/keymap.c, keyboards/inland/kb83/keymaps/default/rules.mk
Inland KB83 had GPIOs backwards for encoder CCW and CW. Also enabled the encoder for default and fixed directions for the encoder keys. This keyboard ships with VIA and the same double-inversion encoder swap is done in the VIA user keymaps too, so a keymap fix will be needed in the-via/qmk_userspace_via as well.
*
=> Fix inverted encoder on Inland KB83

keyboards/handwired/franky36/keyboard.json
Changed VID and PID for handwired franky36 keyboard.
I think this values are available for open source projects.
This should resolve conflicts with keyboards that uses same `0x0001` pid and `0xFEED` vid
*
=> Update franky36 pid and vid

docs/feature_advanced_keycodes.md, docs/keycodes.md, docs/mod_tap.md, quantum/quantum_keycodes.h, quantum/quantum_keycodes_legacy.h
- Reorganised mod & mod-tap sections in quantum_keycodes
- Added missing combinations eg. `LCG()`, `RCA()` etc.
- Deprecated `C_S_T()` in favour of `LCS_T()`
- Hyper key blog post link kept but moved out of the keycode reference page, as a footnote to the keycode tables
- Adjusted keycode descriptions to always specify left/right for each modifier
Meh and Hyper could potentially become aliases of their "standard" representations, ie. `LCSA/_T()` and `LCSAG/_T()` (and have right-hand versions of each), but I'll leave those for now.
*
=> Clean up mod & mod-tap shortcuts

keyboards/ploopyco/ploopyco.c
Just a small QoL fix to follow QMK convention of calling `_user` *before* `_kb` level functions. Specifically moving the call to `pointing_device_task_user` to the top of `pointing_device_task_kb` rather than the bottom. This lets users have the first opportunity to modify the mouse_report *before* it is possibly mutated by drag scroll logic, etc.
N/A
=> Give mouse report to pointing_device_task_user first in ploopyco devices

keyboards/bastardkb/dilemma/3x5_2/assembled/mcuconf.h
Per this keyboard's SPI pins:
https://github.com/qmk/qmk_firmware/blob/c3773d9c350cef5c4323c209f85ffd076177f8f1/keyboards/bastardkb/dilemma/3x5_2/assembled/config.h#L29-L31
SPI1 is not the correct peripheral to be enabled:
This functioned correctly nonetheless because SPI0 is enabled by `GENERIC_PROMICRO_RP2040`.
=> Enable correct SPI peripheral `dilemma/3x5_2/assembled`

platforms/chibios/boards/STEMCELL/configs/config.h, platforms/chibios/boards/STEMCELL/configs/mcuconf.h
Configures the appropriate driver, pins for SPI in the `STEMCELL` `BOARD`, and enables `STM32_SPI_USE_SPI1` peripheral, per STM32F4x1 datasheet:
and the pins configured line up appropriately with Stemcell's pin mappings:
https://github.com/qmk/qmk_firmware/blob/c7a24a441f6b3e25b726089c3305ef2d92b46fd4/platforms/chibios/converters/promicro_to_stemcell/_pin_defs.h#L44-L46
Backwards compatibility should be no issue, as these values did not exist previously, and can still be overridden at the keyboard level.
This will allow for converters that use the `STEMCELL` board to have SPI automagically configured.
=> Configure SPI for `STEMCELL` board

platforms/chibios/boards/QMK_PM2040/configs/config.h
Configures the appropriate driver and pins for SPI in the `QMK_PM2040` `BOARD`. The necessary peripheral `RP_SPI_USE_SPI0` is already enabled in the board's `mcuconf.h`.
Backwards compatibility should be no issue, as these values did not exist previously, and can still be overridden at the keyboard level.
This will allow for converters that use the `QMK_PM2040` board to have SPI automagically configured.
=> Configure SPI for `QMK_PM2040` board

lib/python/qmk/keymap.py
Currently resolving keymap location incorrectly falls back to looking for aliases in qmk_firmware, when userspace is configured.
*
=> Only userspace should be searched for keyboard aliases when locating keymaps

lib/python/qmk/flashers.py
Missing from #23445 (and #25215). The following command currently does not function correctly,
```sh
qmk flash path/to/at32_keyboard.bin
```
While the CLI would find the bootloader, later code was not hooked up to actually perform the flashing.
*
=> Allow `qmk flash <filename>` to flash AT32 boards

docs/cli_commands.md, docs/hardware_keyboard_guidelines.md, docs/newbs_building_firmware.md, docs/newbs_flashing.md, docs/reference_info_json.md
Align use of the placeholder tokens we use within docs when referring to keyboards/keymaps so that a consistent set is used for all pages.
* Avoid using `keyboard_name` as it is also a `info.json` field
* Confusion can be seen in 25508
*
=> [docs] Align keyboard and keymap placeholders

keyboards/boardsource/unicorne/keyboard.json
The x coordinate of the three keys in the rightmost column were set to zero, so certain animations were acting funny. For example, any animation that sweeps from left to right, there'd be a pause before the rightmost column. Updating the x coord to a suitable value (so that it as seen as indeed being on the right, not the left) does fix these sweep animations.
* Fixes #23224
=> Update rgb x coordinate of rightmost column

util/qmk_install.sh
This PR is a one-liner changes to add `*cachyos*` pattern so that it's using arch installation script instead of being unrecognized.
CachyOS is an arch-based linux distribution, so it should be safe to use arch installation script for it. This PR adds a pattern so that cachyos is recognized by the dependency installation script.
As further info, the following is the output of `grep ID / etc/os-release` in my CachyOS machine:
```sh
$ grep ID /etc/os-release
ID=cachyos
BUILD_ID=rolling
```
* #25578
=> Add cachyos as pattern when installing dependencies

quantum/rgb_matrix/animations/raindrops_anim.h
The `deltaH` calculation in the raindrops animation was based on a 0-360 hue range. This commit simplifies the logic to correctly use 8-bit integer arithmetic, making the code more efficient and accurate for QMK's hue color range.
=> Simplify hue calculation in raindrops animation

docs/ChangeLog/20200229.md, docs/ChangeLog/20200530.md, docs/ChangeLog/20210529.md, docs/ChangeLog/20210828.md, docs/ChangeLog/20220226.md, docs/custom_quantum_functions.md, docs/drivers/serial.md, docs/feature_debounce_type.md, docs/feature_eeprom.md, docs/feature_layers.md, docs/feature_userspace.md, docs/features/audio.md, docs/features/bootmagic.md, docs/features/encoders.md, docs/features/haptic_feedback.md, docs/features/pointing_device.md, docs/features/repeat_key.md, docs/features/rgb_matrix.md, docs/features/space_cadet.md, docs/features/split_keyboard.md, docs/features/st7565.md, docs/features/stenography.md, docs/hand_wire.md, docs/hardware_drivers.md, docs/quantum_painter_lvgl.md, docs/squeezing_avr.md, docs/usb_nkro.txt, drivers/lcd/st7565.h, tmk_core/protocol/report.c
Fix misspellings into the docs. Trailing spaces are also removed, and line breaks are done with the HTML br tag.
=> docs: fix misspellings
