keyboards/salicylic_acid3/7skb/keymaps/default/keymap.c, keyboards/salicylic_acid3/7skb/keymaps/salicylic/keymap.c, keyboards/salicylic_acid3/7skb/keymaps/via/keymap.c, keyboards/salicylic_acid3/7skb/rules.mk
Change the number of LEDs and Enable Mouse Keys
*
=> (7skb)Change the number of LEDs and Enable Mouse Keys

keyboards/novelkeys/nk20/config.h, keyboards/novelkeys/nk20/halconf.h, keyboards/novelkeys/nk20/info.json, keyboards/novelkeys/nk20/keymaps/default/keymap.c, keyboards/novelkeys/nk20/keymaps/default/readme.md, keyboards/novelkeys/nk20/keymaps/via/keymap.c, keyboards/novelkeys/nk20/keymaps/via/readme.md, keyboards/novelkeys/nk20/keymaps/via/rules.mk, keyboards/novelkeys/nk20/mcuconf.h, keyboards/novelkeys/nk20/nk20.c, keyboards/novelkeys/nk20/nk20.h, keyboards/novelkeys/nk20/readme.md, keyboards/novelkeys/nk20/rules.mk
=> Initial commit for NK20

keyboards/dmqdesign/spin/keymaps/spidey3_pad/keymap.c
Adds a cursor key layer to DMQ Spin (personal layout)
=> Add cursor layer to DMQ Spin

quantum/command.h
=> Remove legacy keycode use from command

keyboards/linworks/fave104/keymaps/default/keymap.c, keyboards/linworks/fave104/keymaps/via/keymap.c
fixed keymaps.
Fix keymap matching error in file (keymap.c)
/keymaps/default/keymap.c --->  change KC_NUM_LOCK to KC_NUM.
/keymaps/via/keymap.c --->  change KC_NUM_LOCK to KC_NUM.
*
=> Uupdate Fave104 keymap

keyboards/viendi8l/config.h, keyboards/viendi8l/keymaps/default/keymap.c, keyboards/viendi8l/keymaps/via/keymap.c
Fixing bad includes, and removing random crap from via keymap
*
=> Fix viendi8l compilation

quantum/keymap_extras/keymap_czech.h
The  % percent symbol is situated on Shift + CZ_EQL, not on Shift + CZ_PLUS.
*
=> define CZ_PERC S(CZ_PLUS) → define CZ_PERC S(CZ_EQL)

keyboards/kinesis/kint41/kint41.c
Fixes #18014
@drashna @stapelberg 
I increased the matrix_output_unselect_delay time to resolve a ghosting problem I was having, described in #18014 
* #18014 
I have only tested the build of my keyboard's firmware. The change seems exceedingly unlikely to break other firmwares.
=> [Keyboard] Increase kinesis/kint41 unselect delay

data/mappings/defaults.json, data/schemas/keyboard.jsonschema, docs/feature_converters.md, platforms/chibios/converters/promicro_to_bit_c_pro/_pin_defs.h, platforms/chibios/converters/promicro_to_bit_c_pro/converter.mk
Add the nullbits Bit-C PRO RP2040 to the converters so that existing projects can be converted easily. Tested by converting a TIDBIT and crkbd and ensuring the resulting file flashed properly, booted with the Bit-C PRO flash, and worked as expected: no missing/swapped rows/columns, and underglow working.
*  N/A
=> Add Bit-C PRO converter

quantum/keymap_extras/keymap_latvian.h
```
/* AltGr symbols
* ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
* │ - │   │ « │ » │ € │   │ ’ │   │   │   │   │ – │   │       │
* ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
* │     │   │   │ Ē │ Ŗ │   │   │ Ū │ Ī │ Ō │   │   │   │     │
* ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
* │      │ Ā │ Š │   │   │ Ģ │   │   │ Ķ │ Ļ │   │ ´ │   │    │
* ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
* │    │   │ Ž │   │ Č │   │   │ Ņ │   │   │   │   │          │
* ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
* │    │    │    │                        │    │    │    │    │
* └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
*/
```
```diff
commit 445a35f251e056232002d0e461c39619ea04c366 (HEAD -> …
```
=> Fix LV_CCAR and LV_NCED in keymap_latvian.h

keyboards/ploopyco/mouse/mouse.c, keyboards/ploopyco/opt_encoder.c, keyboards/ploopyco/opt_encoder.h, keyboards/ploopyco/opt_encoder_simple.c, keyboards/ploopyco/trackball/trackball.c, keyboards/ploopyco/trackball_mini/trackball_mini.c
This implementation differs from the default implementation in that it
translates the phototransistor analog output into high/low states by
using a simple scheme inspired by a Schmit trigger.
The resulting code is half of the size of the default encoder
implementation and use less states, reducing memory usage.
For the Ploopy Mini Trackball, switching to this implementation
saves 856 bytes (~3% total flash space) in firmware size.
From my personal testing, it seems to be a lot more responsive than the
default implementation.
This has only been tested on a Ploopy Mini Trackball as I don't own
any other Ploopy hardware.
This implementation can be used by simply copying/symlinking the
file `opt_encoder_simple.c` to your keymap directory as `opt_encoder.c`,
then run `qmk clean && qmk …
=> RFC: add a simple implementation of the ploopy optical encoder

keyboards/keebio/bamfk4/bamfk4.c, keyboards/keebio/bamfk4/bamfk4.h, keyboards/keebio/bamfk4/config.h, keyboards/keebio/bamfk4/info.json, keyboards/keebio/bamfk4/keymaps/default/keymap.c, keyboards/keebio/bamfk4/keymaps/via/keymap.c, keyboards/keebio/bamfk4/keymaps/via/rules.mk, keyboards/keebio/bamfk4/rules.mk
=> add BAMFK-4

docs/pr_checklist.md
A small amendment to the PR checklist to document the imgur image size conventions.
* Inconsistent imgur image sizing in PRs (hopefully!)
=> [Docs] Suggest imgur images are edited to set size

keyboards/handwired/skakunm_dactyl/config.h, keyboards/handwired/skakunm_dactyl/info.json, keyboards/handwired/skakunm_dactyl/keymaps/default/config.h, keyboards/handwired/skakunm_dactyl/keymaps/default/keymap.c, keyboards/handwired/skakunm_dactyl/readme.md, keyboards/handwired/skakunm_dactyl/rules.mk, keyboards/handwired/skakunm_dactyl/skakunm_dactyl.c, keyboards/handwired/skakunm_dactyl/skakunm_dactyl.h
Added a new keyboard, it is similar to the Dactyl, but has 3x5 configuration with 5 thumb keys. Wiring is not compatible with the original dactyl since I used different wiring, so I had to make a different keyboard.
*
=> Added different wiring of dactyl

docs/breaking_changes.md
=> Add texts for Discord Events to be created post-merge.

keyboards/boardsource/microdox/v2/config.h
=> [Keyboard] Fix compilation issues for Boardsource Microdox

keyboards/4pplet/perk60_iso/rev_a/config.h, keyboards/4pplet/perk60_iso/rev_a/mcuconf.h, keyboards/4pplet/perk60_iso/rev_a/rules.mk, keyboards/acheron/apollo/87h/delta/config.h, keyboards/acheron/apollo/87h/delta/mcuconf.h, keyboards/acheron/apollo/87h/delta/rules.mk, keyboards/acheron/apollo/87htsc/config.h, keyboards/acheron/apollo/87htsc/mcuconf.h, keyboards/acheron/apollo/87htsc/rules.mk, keyboards/acheron/apollo/88htsc/config.h, keyboards/acheron/apollo/88htsc/mcuconf.h, keyboards/acheron/apollo/88htsc/rules.mk, keyboards/acheron/athena/alpha/config.h, keyboards/acheron/athena/alpha/mcuconf.h, keyboards/acheron/athena/alpha/rules.mk, keyboards/acheron/athena/beta/config.h, keyboards/acheron/athena/beta/mcuconf.h, keyboards/acheron/athena/beta/rules.mk, keyboards/mechwild/puckbuddy/rules.mk, keyboards/mlego/m48/rev1/rules.mk, keyboards/mlego/m60/rev1/rules.mk, keyboards/mlego/m65/rev3/rules.mk, keyboards/mlego/m65/rev4/rules.mk, keyboards/yandrstudio/nz64/rules.mk, keyboards/yandrstudio/zhou65/rules.mk
Final migrations before #17522.
*
=> Migrate more F4x1 board files

data/schemas/keyboard.jsonschema
=> Fix missing development_board schema entry

keyboards/gmmk/pro/rev2/ansi/info.json, keyboards/gmmk/pro/rev2/iso/info.json
As title. Seems like #17655 never defined vid/pid/device version. `diff rev1 rev2` seems to show that it's appropriate to use rev1 vid/pid.
=> Fixup gmmk/pro/rev2 USB Data

docs/pr_checklist.md
Trying to improve PR checklist again. This time with DD info.
I'm flexible on the wording of the first line of the info.json part- appreciate feedback.
*
=> [Docs] update pr_checklist.md with info about data-driven

keyboards/aurora65/config.h, keyboards/loki65/config.h
Made an upsie with those 2020 leds
*
=> Fix WS2812 order for aurora65 and loki65

docs/custom_quantum_functions.md
Thanks for your hard work :muscle: 
This PR adjust the level of the chapter `Deferred Execution`  to put it on a 2nd level as the other in this page
=> Adjust the hierarchy of chapter `Deferred Execution`

layouts/community/ortho_4x12/junonum/keymap.c, layouts/community/ortho_4x12/junonum/readme.md
- Minor update for my personal keymap.
* N/A
=> Replace CG_SWAP in junonum

keyboards/mokey/ibis80/keymaps/default/keymap.c, keyboards/mokey/ibis80/keymaps/via/keymap.c
As title. `via` keymap had an additional two keycodes defined.
=> Fixup mokey/ibis80 keymaps

lib/python/qmk/constants.py
Missing entry incorrectly sets "custom" which is less than ideal.
=> Fix new-keyboard default for RP2040 bootloader

lib/python/qmk/info.py
=> Remove legacy bootmagic cli parsing

docs/squeezing_avr.md
Added Boardsource's upcoming 'Blok' devboard to the reference-list of ARM-based ProMicro alternatives, within the "Firmware Squeezing" docs for users needing more firmware space. This being an especially helpful addition right now, while it's still in "Pre-Sale" at a discounted price for a short-time.
Updated the list of ARM-based development boards (listed at the bottom of the how-to Docs for 'Squeezing Firmware Space") with Pro-Micro PCB footprints to include a new option available for purchase (listed at the bottom of the QMK Docs for 'Squeezing Firmware Space").
=> Update list of "ARM-based ProMicro replacements"

keyboards/keycapsss/kimiko/kimiko.h
=> [Keyboard] Fix compilation issues for keycapsss kimiko

requirements.txt
=> Align CLI requirements

keyboards/nasu/keymaps/mariocs/config.h, keyboards/nasu/keymaps/mariocs/keymap.c, keyboards/nasu/keymaps/mariocs/readme.md, keyboards/nasu/keymaps/mariocs/rules.mk
Added a new keymap with a functionality to switch on the numlock indicator when activating the layer 1.
* N/A
=> [Keymap] Add new keymap to nasu

keyboards/cozykeys/speedo/v3/keymaps/pcewing/keymap.c, users/pcewing/README.md, users/pcewing/key_repeater.c, users/pcewing/key_repeater.h, users/pcewing/rules.mk
* Add my personal keymap for the CozyKeys Speedo v3 keyboard
* Add some code under `users/pcewing` for a key repeater
* Useful for repeatedly pressing mouse button 1 while a key is held
* Similar to "rapid fire" feature on some game controllers
* N/A
=> Add pcewing Speedo v3 keymap

keyboards/fungo/rev1/config.h
https://github.com/qmk/qmk_firmware/pull/17513
*
=> Remove USB IDs and strings from `fungo/rev1`

keyboards/cantor/info.json
=> Use correct board files for cantor

keyboards/mechwild/clunker/info.json, keyboards/mechwild/clunker/keymaps/default/rules.mk, keyboards/mechwild/clunker/keymaps/via/rules.mk
=> Fix use of encoder map in mechwild/clunker

lib/python/qmk/cli/__init__.py
=> Update invalid pip install flag

keyboards/mechlovin/foundation/keymaps/default/rules.mk, keyboards/mechlovin/foundation/rules.mk
=> Fix use of encoder map in mechlovin/foundation

data/mappings/info_rules.json
Setting `rgb_matrix.driver` in info.json has no effect.
*
=> Add missing DD mapping for RGB_MATRIX_DRIVER

lib/python/qmk/cli/generate/dfu_header.py
https://github.com/qmk/lufa/pull/16
*
=> Update LUFA submodule

quantum/send_string/send_string_keycodes.h
Docs mentions them but they didnt exist.
*
=> Add missing SS_LOPT and SS_ROPT defines

.vscode/settings.json
Exclude uf2 files in vscode settings.
=> Exclude uf2 files in vscode

data/schemas/api_keyboard.jsonschema, data/schemas/keyboard.jsonschema, data/schemas/keymap.jsonschema
Even though these are read as hjson, it's probably a good idea to keep them as close to valid JSON as possible.
*
=> Clean up schema syntax

keyboards/kegen/gboy/info.json
#18194
Not sure why this didn't show up before.
*
=> kegen/gboy: add manufacturer string

keyboards/handwired/hillside/48/keymaps/manna-harbour_miryoku/config.h, keyboards/handwired/hillside/48/keymaps/manna-harbour_miryoku/keymap.c
This PR adds the Miryoku keymap for the Hillside 48.
=> Add Miryoku keymap for Hillside 48

keyboards/chord/zero/config.h, keyboards/chord/zero/info.json, keyboards/chord/zero/keymaps/default/keymap.c, keyboards/chord/zero/keymaps/default/rules.mk, keyboards/chord/zero/readme.md, keyboards/chord/zero/rules.mk
=> [Keyboard] Add chord/zero

keyboards/boardsource/lulu/rules.mk
Don't try to compile plain `-kb boardsource/lulu`
tz ci 
```
quantum/keyboard.h:57:28: error: 'MATRIX_ROWS' undeclared (first use in this function)                                                               
return event.key.row < MATRIX_ROWS && event.key.col < MATRIX_COLS;                                                                              
^~~~~~~~~~~                                                                                                              
quantum/keyboard.h:57:28: note: each undeclared identifier is reported only once for each function it appears in                                     
quantum/keyboard.h:57:59: error: 'MATRIX_COLS' undeclared (first use in this function)                                                               
return event.key.row …
```
=> Fixup boardsource/lulu

util/install/fedora.sh
An alternative would be to patch bootloadHID source to link to `libusb-1.0.so` instead.
* Fixes #18242
=> Install correct package on Fedora

docs/understanding_qmk.md
Here an update of the documentation according to the code of `action_exec(keyevent_t event)` and childrens: 
- I have added missing function
- I have updated all the references to the code
*
=> [Docs] Update 'Process Record' according to the code

data/mappings/info_config.json, data/mappings/info_rules.json
=> Clean up data driven mappings syntax

keyboards/dyz/dyz60_hs/info.json, keyboards/handwired/reclined/info.json, keyboards/synthlabs/solo/info.json
=> Fix a couple of boards still using `usb.device_ver`

quantum/process_keycode/process_auto_shift.h
=> Remove use of legacy keycode

keyboards/kprepublic/bm40hsrgb/keymaps/dan/keymap.c
As I was more used to python syntax I had been getting errors doing 'if !(led_state.num_lock) {..' and got errors, so I got away with doing if else. But I found out 'if (!led_state.num_lock) {..' worked.
*
=> removed else in numlock led if statement

keyboards/massdrop/ctrl/keymaps/via/config.h, keyboards/massdrop/ctrl/keymaps/via/keymap.c
Enabled all RGB matrix effects.
Basically copied #18041's changes for the Drop ALT.
=> Enable RGB matrix effects for Drop CTRL with VIA

keyboards/mechlovin/zed65/wearhaus66/config.h
Correct matrix row pin (A10 -> A8).
Thank you!
*
=> [Keyboard] Wearhaus66 correct matrix

keyboards/keebio/iris/iris.h, keyboards/keebio/iris/rev6b/config.h, keyboards/keebio/iris/rev6b/info.json, keyboards/keebio/iris/rev6b/rev6b.c, keyboards/keebio/iris/rev6b/rev6b.h, keyboards/keebio/iris/rev6b/rules.mk
=> Add Iris Rev. 6b

keyboards/soda/cherish/rules.mk
Update 'soda/cherish' support apm32f072 dfu
*
=> 'soda/cherish' support apm32f072

drivers/bluetooth/rn42.c, drivers/bluetooth/rn42.h
Main thing is removing the `last_data` stuff in `rn42_send_consumer()` as this is now handled by `host_consumer_send()`.
*
=> RN42 driver: small cleanups

platforms/chibios/flash.mk
`-D` and `-R` at the same time doesnt seem to function, so run them back-to-back.
=> Reboot wb32 devices after flashing

keyboards/handwired/swiftrax/bumblebee/bumblebee.h
=> Fix handwired/swiftrax/bumblebee layout macro

quantum/eeconfig.c
=> Fix EECONFIG_KEYMAP_UPPER_BYTE init

keyboards/mechwild/murphpad/keymaps/jonavin/keymap.c, users/jonavin/jonavin.h
This minor update fixes the following:
- userspace jonavin jonavin.h definition of ARRAYSIZE conflicts with recent updates
- mechwild/murphpad keymap compile error due to search/replace on "RESET" to "QA_BOOT". String for display remains the same "RESET" but calls the new QK_BOOT code
*
=> Jonavin fix compile errors due to recent qmk master changes

keyboards/keyboardio/atreus/keymaps/dshields/keymap.c, keyboards/keyboardio/model01/keymaps/dshields/keymap.c, keyboards/planck/keymaps/dshields/keymap.c, users/dshields/dshields.h
=> Add home row modifiers to dshields keymaps.

keyboards/keebio/bdn9/rev2/config.h
Enable more BDN9 RGB effects because it needs more RGB.
*
=> Enable more BDN9 RGB effects

docs/pr_checklist.md
=> Checklist clarification.

keyboards/gmmk/pro/rev1/iso/keymaps/falkecarlsen/keymap.c, keyboards/gmmk/pro/rev1/iso/keymaps/falkecarlsen/readme.md
Adds personal GMMK PRO ISO keymap, which - unlike existing keymaps - adds layer 1 enhanced mouse emulation on WASD and Keychron keycap F-row functions on layer 1.
Includes a short readme detailing changes from default keymap.
Since default keymap contains copyright notice from Glorius and I inherit from this, my assumptions is that I cannot license this keymap under GPL2.0 - please correct me if I'm mistaken as I'd rather use GPL.
*
=> Add falkecarlsen GMMK PRO ISO keymap 

.github/workflows/stale.yml, keyboards/work_louder/work_board/keymaps/via/keymap.c
Like the title says.  Mostly, to stay consistent with shipped firmware.
=> [Keyboard] Update Work Louder VIA layouts

keyboards/tzarc/djinn/djinn.c
Mistakenly swapped width/height.
=> Fix `tzarc/djinn` screen geometry.

keyboards/cradio/info.json
As title
tz ci
```
Compiling QMK Firmware for target: 'cradio:default'...
* No bootloader specified. Please set an appropriate bootloader in your rules.mk or info.json.        [ERRORS]
platforms/avr/bootloader.mk:142: *** Invalid BOOTLOADER.  Stop.
```
=> Fixup cradio bootloader/processor

keyboards/kprepublic/bm40hsrgb/keymaps/dan/keymap.c
Updated keys mainly in RIGHTFN layer and started using variables for the rgb values in led lights
*
=> Switched keys around in RIGHFN layer and updated indicator lights to green

keyboards/w1_at/keymaps/zq/keymap.c, keyboards/w1_at/keymaps/zq/readme.md, keyboards/w1_at/keymaps/zq/rules.mk
Adding my personal keymap for W1-AT keyboard.
*
=> Adding my keymap

docs/feature_joystick.md, keyboards/handwired/onekey/keymaps/joystick/keymap.c, keyboards/synthlabs/solo/keymaps/gamepad/keymap.c, quantum/joystick.c, quantum/joystick.h, quantum/process_keycode/process_joystick.c, quantum/process_keycode/process_joystick.h, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/host.c, tmk_core/protocol/host_driver.h, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/report.h
Moving almost everything out of `process_keycode/`; `process_joystick.c` now solely handles the joystick buttons, though now it's able to be later expanded to add keycodes for axes too, as discussed in #13344. To this end I've chopped up `process_joystick_analogread_quantum()` into:
```
int16_t joystick_read_axis(uint8_t axis);
void joystick_read_axes(void);
void joystick_set_axis(uint8_t axis, int16_t value);
```
Docs have been updated to demonstrate use -- the existing example doesn't appear to actually do anything.
*
=> Further refactoring of joystick feature

keyboards/zicodia/tklfrlnrlmlao/config.h, keyboards/zicodia/tklfrlnrlmlao/info.json, keyboards/zicodia/tklfrlnrlmlao/keymaps/default/keymap.c, keyboards/zicodia/tklfrlnrlmlao/keymaps/via/keymap.c, keyboards/zicodia/tklfrlnrlmlao/keymaps/via/rules.mk, keyboards/zicodia/tklfrlnrlmlao/readme.md, keyboards/zicodia/tklfrlnrlmlao/rules.mk
Added firmware for a new keyboard, the "TKLFRLNRLMLAO" or "LMAO" for short.
*
=> TKLFRLNRLMLAO

keyboards/abatskeyboardclub/nayeon/info.json
Due to a conflict with another board's VIA VID/PID, the Abats Keyboard Club Nayeon will be changing its VID from `4B47` to `ABA7`. (see: https://github.com/the-via/keyboards/pull/1423)
*
=> Update VID and PID of Abats Keyboard Club Nayeon

util/install/gentoo.sh
As title. Without, the following linking error occurs:
```
Linking: .build/handwired_onekey_proton_c_default.elf                                               [ERRORS]
|
| /usr/libexec/gcc/arm-none-eabi/ld: cannot find -lg_nano: No such file or directory
| /usr/libexec/gcc/arm-none-eabi/ld: cannot find -lc_nano: No such file or directory
| collect2: error: ld returned 1 exit status
|
gmake[1]: *** [builddefs/common_rules.mk:267: .build/handwired_onekey_proton_c_default.elf] Error 1
gmake: *** [Makefile:414: handwired/onekey/proton_c:default] Error 1
```
=> Gentoo install script — build newlib with `nano` USE flag

keyboards/keychron/q0/config.h, keyboards/keychron/q0/q0.c, keyboards/keychron/q0/rev_0130/rev_0130.c
- Correct definition CONSTANT_CURRENT_STEP should be CKLED2001_CURRENT_TUNE
- Correct definition CAPS_LOCK_LED_INDEX should be NUM_LOCK_LED_INDEX
- Adjust the coordinates of RGB matrix slightly by reducing the size in half to enhance the color variations
*
=> Update q0 for keychron

builddefs/common_features.mk, drivers/bluetooth/bluefruit_le.cpp, drivers/bluetooth/bluefruit_le.h, drivers/bluetooth/bluetooth.c, drivers/bluetooth/bluetooth.h, quantum/keyboard.c, tmk_core/protocol/host.c
This is pretty barebones for the moment, and I'm not entirely sure whether this implementation or a more RGB Matrix-esque driver model is better. At the very least it abstracts away the existing driver-specific function calls in keyboard.c and host.c.
*
=> Start Bluetooth API

keyboards/ramonimbao/tkl_ff/info.json, keyboards/ramonimbao/tkl_ff/keymaps/default/keymap.c, keyboards/ramonimbao/tkl_ff/keymaps/iso/keymap.c, keyboards/ramonimbao/tkl_ff/tkl_ff.h
Enables Community Layout support for both V1 and V2 boards.
cc @ramonimbao (keyboard maintainer)
=> TKL-FF Community Layout Support

builddefs/common_features.mk
As per title, raised in #18529.
* #18529
=> Explicitly specify path to RP2040 wear_leveling config file.

docs/pr_checklist.md
"To read makes our speaking English good." - Xander Harris
=> Grammar Fix for PR Checklist

keyboards/handwired/onekey/blackpill_f401/halconf.h, keyboards/handwired/onekey/blackpill_f401/mcuconf.h, keyboards/handwired/onekey/blackpill_f411/halconf.h, keyboards/handwired/onekey/blackpill_f411/mcuconf.h, keyboards/handwired/onekey/blackpill_f411_tinyuf2/halconf.h, keyboards/handwired/onekey/blackpill_f411_tinyuf2/mcuconf.h, keyboards/handwired/onekey/bluepill/halconf.h, keyboards/handwired/onekey/bluepill/mcuconf.h, keyboards/handwired/onekey/bluepill_f103c6/halconf.h, keyboards/handwired/onekey/bluepill_f103c6/mcuconf.h
To fix `adc` and `joystick` keymaps (followup to #18502).
*
=> onekey: enable ADC for Bluepill and Blackpill

keyboards/handwired/onekey/keymaps/quine/keymap.c
=> onekey: fix quine keymap

keyboards/tzarc/djinn/djinn.c, keyboards/tzarc/djinn/graphics/theme_djinn_default.c
=> Djinn theme, allow force redraws.

keyboards/the_uni/pro_micro/readme.md, keyboards/the_uni/readme.md, keyboards/the_uni/rp_2040/config.h, keyboards/the_uni/rp_2040/info.json, keyboards/the_uni/rp_2040/readme.md, keyboards/the_uni/rp_2040/rp_2040.c, keyboards/the_uni/rp_2040/rp_2040.h, keyboards/the_uni/rp_2040/rules.mk, keyboards/the_uni/usb_c/info.json
Adding another keyboard version. [The Uni v4](https://stenokeyboards.com/products/the-uni-v4) uses the rp2040 chip.
*
=> Uni v4 keyboard add

platforms/arm_atsam/flash.mk, platforms/avr/flash.mk, platforms/chibios/flash.mk
A little thing to help diagnose "why isn't my board being detected" issues.
*
=> `:flash`: print bootloader

docs/feature_caps_word.md
Clarify docs that minus becomes underscore.
Fixes documentation issue related to:
* #18136
=> [Docs] CAPS_WORD '-' produces '_'

keyboards/linworks/fave84h/keymaps/default/keymap.c, keyboards/linworks/fave84h/keymaps/via/keymap.c
`LAYOUT` doesn't exist. Seems like #18450's branch did not catch #18496's changes.
=> Fixup linworks/fave84h

keyboards/terrazzo/terrazzo.c, keyboards/xbows/woody/woody.c
=> Remove lingering `DRIVER_LED_TOTAL` references

docs/faq_debug.md
Added undocumented content for print function.
*
=> [Docs] Add a note about the print function.

platforms/chibios/hardware_id.c
* fix missing stm32 bytes
* bodge RP2040 support
*
=> Fix/Update ChibiOS hardware ID

keyboards/momokai/tap_trio/rules.mk
=> Enable mouse keys for momokai tap_trio

platforms/chibios/hardware_id.c
=> Fix some rp2040 hardware ID errors

drivers/haptic/solenoid.h
=> fix typo in solenoid.h

keyboards/elephant42/keymaps/via/keymap.c
Pre-emptively handle naming conflicts with #18643.
=> Fix future naming collisions.

builddefs/converters.mk, quantum/quantum.c
Allow `QK_MAKE` to write the converter flag if enabled:
Eg: `qmk compile -kb crkbd/rev1 -km jpe230 -e CONVERT_TO=kb2040`
*
=> Allow QK_MAKE to work with converters

keyboards/handwired/twig/twig50/keymaps/default/keymap.c
=> Fixup twig50

keyboards/idobao/id61/config.h
=>  Remove lingering `DRIVER_LED_TOTAL` references

lib/python/qmk/constants.py
=> Remove unused LED_INDICATORS constant

keyboards/dumbpad/v3x/config.h, keyboards/dumbpad/v3x/keymaps/default/keymap.c, keyboards/dumbpad/v3x/keymaps/deveth0/keymap.c, keyboards/dumbpad/v3x/keymaps/via/keymap.c
=> Fixup dumbpad/v3x

docs/tap_hold.md
This PR solves some typos that I found in the `Tap-Hold Configuration Options` documentation
=> docs: fix typos

keyboards/bluebell/swoop/info.json
=> Fixup bluebell/swoop

keyboards/momoka_ergo/config.h, keyboards/momoka_ergo/keymaps/default/readme.md, keyboards/momoka_ergo/keymaps/via/keymap.c, keyboards/momoka_ergo/keymaps/via/readme.md
- Remove unnecessary defines
- Explicitly define RGB animations
- Keymap cleanup
=> Fixup momoka_ergo

keyboards/boardsource/holiday/spooky/info.json, keyboards/boardsource/microdox/v1/info.json, keyboards/boardsource/the_mark/info.json, keyboards/capsunlocked/cu80/v2_ansi/info.json, keyboards/capsunlocked/cu80/v2_iso/info.json, keyboards/clueboard/17/info.json, keyboards/clueboard/2x1800/2018/info.json, keyboards/clueboard/66/rev1/info.json, keyboards/clueboard/66/rev2/info.json, keyboards/clueboard/66/rev3/info.json, keyboards/clueboard/66/rev4/info.json, keyboards/clueboard/66_hotswap/prototype/info.json, keyboards/custommk/evo70/info.json, keyboards/dyz/dyz40/info.json, keyboards/dyz/dyz60/info.json, keyboards/dyz/dyz60_hs/info.json, keyboards/dyz/dyz_tkl/info.json, keyboards/dyz/selka40/info.json, keyboards/dyz/synthesis60/info.json, keyboards/jacky_studio/piggy60/info.json, keyboards/keebio/sinc/rev1/info.json, keyboards/keebio/sinc/rev2/info.json, keyboards/takashicompany/spreadwriter/info.json, keyboards/work_louder/micro/info.json
Replace the "all: true" setting with explicitly enabled animations in info.json files
=> Update info.json configs to explicitly list RGBLIGHT animations

keyboards/work_louder/micro/keymaps/via/config.h, keyboards/work_louder/micro/keymaps/via/rules.mk
Compiles too large. Removing some memory intensive effects seems like least intrusive fix. 
tz ci size check
=> Fixup work_louder/micro VIA keymap

keyboards/sofle/keymaps/keyhive_via/readme.md, keyboards/wavtype/p01_ultra/readme.md
=> Slipped through the cracks.

platforms/chibios/boards/GENERIC_STM32_F401XC/configs/mcuconf.h, platforms/chibios/boards/STEMCELL/configs/mcuconf.h, util/chibios_conf_updater.sh
As per the title. Fedora wasn't able to do any config updates. Updated in the process.
=> Allow Fedora to update ChibiOS configs.

lib/python/qmk/cli/compile.py, lib/python/qmk/cli/flash.py, lib/python/qmk/commands.py
* Converters by environment (`-e CONVERT_TO=kb2040`) did not clean
* `keymap.json` (in or out of tree) ignored clean flag
* also didnt incremental build either
Also minor alignment of flash code flow to make maintenance a little easier
*
=> [CLI] Ensure consistent clean behaviour

keyboards/cmm_studio/saka68/solder/solder.h
- bottom row misalignment behind space button sorted
*
=> Fix saka68 solder layout

docs/documentation_templates.md
Fix broken link to [Keyboard Layout Editor](http://keyboard-layout-editor.com) -- https://keyboard-layout-editor.com can't be reached.
*
=> [Docs] Fix broken keyboard layout editor link

keyboards/40percentclub/polyandry/info.json, keyboards/40percentclub/polyandry/keymaps/default/keymap.c, keyboards/40percentclub/polyandry/promicro/promicro.h, keyboards/40percentclub/polyandry/teensy2/teensy2.h
=> Polyandry: rename LAYOUT to LAYOUT_ortho_4x3

docs/serial_driver.md
=> spelling fix

keyboards/controllerworks/mini36/config.h
`DRIVER_LED_TOTAL` -> `RGB_MATRIX_LED_COUNT`
=> Fixup controllerwords/mini36

keyboards/splitkb/aurora/sweep/info.json, keyboards/splitkb/aurora/sweep/rev1/info.json
caused by:
```
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 74 column 9 (char 6074)
```
Technically `qmk_api_tasks` should be able to understand hjson, but until then...
cc @leah-splitkb
*
=> Fix splitkb/aurora/sweep

keyboards/elephant42/keymaps/default/keymap.c
These keycodes were not meant to be changed in #18864 as they are not Space Cadet related.
*
=> elephant42: fix default keymap

docs/feature_rgb_matrix.md
Fix a typo in the `feature_rgb_matrix.md`.
=> Docs: fix a typo

keyboards/keebio/sinc/rev1/config.h, keyboards/keebio/sinc/rev1/info.json, keyboards/keebio/sinc/rev2/config.h, keyboards/keebio/sinc/rev2/info.json
Migrate Sinc Rev. 1 and 2 to a different PID to allow for updated VIA .json to be used for encoder mapping support
*
=> Add Sinc Rev. 1-2 Encoder Map

keyboards/mechlovin/kay65/config.h, keyboards/mechlovin/kay65/keymaps/default/keymap.c, keyboards/mechlovin/kay65/keymaps/via/keymap.c
Reversed indicator LED and logo LED state.
*
=> Update Kay65 LED state

drivers/gpio/mcp23018.c, drivers/gpio/mcp23018.h
Reverts qmk/qmk_firmware#18178
=> Revert "mcp23018: add return status to init"

keyboards/novelkeys/nk65b/info.json
=> Remove duplicate key in novelkeys/nk65b

keyboards/elephant42/keymaps/default/keymap.c, keyboards/elephant42/keymaps/via/keymap.c
`KC_RSPC` still exists as a legacy keycode, for the time being.
*
=> Properly fix elephant42

platforms/avr/flash.mk
=> Refactor to avoid deprecated wmic execution

users/spidey3/spidey3.c
Fixes a syntax error introduced in #18800.
* _none_
=> Fix syntax error introduced in #18800

quantum/wpm.c, quantum/wpm.h
=> Reduce includes for wpm header

quantum/dip_switch.c, quantum/dip_switch.h
=> Reduce includes for dip_switch header

keyboards/cannonkeys/satisfaction75/satisfaction75.h, keyboards/nullbitsco/nibble/keymaps/via/keymap.c
Pulled out from 18643 so it remains a core only change.
*
=> Remove hardcoded VIA keycode range

quantum/send_string/send_string.c
=> Reduce includes for send_string header

keyboards/silverbullet44/keymaps/default/keymap.c
=> Fix use of shifted custom keycode

lib/python/qmk/cli/generate/api.py
To make api consumption easier post #18924.
*
=> Publish hjson files as json

keyboards/keychron/q1/config.h
These came in through #18829 despite being unrelated. Causes conflicts with other in-flight PRs.
=> Rollback unrelated changes from previous PR.

keyboards/binepad/bn006/config.h
=> Fixup bn006 on develop

platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c
`RGBLIGHT` specific macro used
=> Fixup WS2812 vendor driver

keyboards/laser_ninja/pumpkin_pad/config.h, keyboards/laser_ninja/pumpkin_pad/info.json, keyboards/laser_ninja/pumpkin_pad/keymaps/default/keymap.c, keyboards/laser_ninja/pumpkin_pad/keymaps/via/keymap.c, keyboards/laser_ninja/pumpkin_pad/keymaps/via/rules.mk, keyboards/laser_ninja/pumpkin_pad/readme.md, keyboards/laser_ninja/pumpkin_pad/rules.mk
- Added support for Laser Ninja's Pumpkin Pad
=> Support for pumpkin pad

data/schemas/keyboard.jsonschema
=> Fix duplicate key in keyboard.jsonschema

data/schemas/keyboard.jsonschema
=> Fixup `keyboard.jsonschema`.

keyboards/cannonkeys/serenity/info.json, keyboards/handwired/dactyl_manuform/5x6_6/info.json, keyboards/handwired/dactyl_manuform/5x6_6/keymaps/default/keymap.c
As title
& remove deprecated keycode.
=> Add missing `manufacturer` fields

keyboards/anavi/knob1/config.h, keyboards/anavi/knob1/info.json, keyboards/anavi/knob1/keymaps/default/keymap.c, keyboards/anavi/knob1/knob1.c, keyboards/anavi/knob1/knob1.h, keyboards/anavi/knob1/mcuconf.h, keyboards/anavi/knob1/readme.md, keyboards/anavi/knob1/rules.mk
ANAVI Knob 1 is a mini mechanical keyboard with a clickable rotary encoder, USB-C, RP2040 microcontroller and I2C slot for a display.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Add a new small mechanical keyboard with RP2040. ANAVI Knob 1 is a mini mechanical keyboard with a clickable rotary encoder, USB-C, RP2040 microcontroller and I2C slot for a display.
*
=> keyboards/anavi: Add ANAVI Knob 1

docs/config_options.md
=> [Docs] Document default value for TAP_CODE_DELAY

keyboards/handwired/jscotto/scottostarter/info.json, keyboards/handwired/jscotto/scottostarter/keymaps/default/config.h, keyboards/handwired/jscotto/scottostarter/keymaps/default/keymap.c, keyboards/handwired/jscotto/scottostarter/readme.md, keyboards/handwired/jscotto/scottostarter/rules.mk
Add ScottoStarter keyboard and its default keymap.
*
=> Add ScottoStarter Keyboard

keyboards/keyboardio/atreus/keymaps/dshields/keymap.c, keyboards/keyboardio/model01/keymaps/dshields/keymap.c, keyboards/planck/keymaps/dshields/keymap.c, users/dshields/config.h, users/dshields/dshields.h
=> [Keyboard] Add layer tap keys to dshields keymaps.

keyboards/jels/boaty/info.json, keyboards/jels/boaty/keymaps/default/keymap.c, keyboards/jels/boaty/keymaps/via/keymap.c
Fix typo & add missing VIA layers.
=> Fixup boaty

keyboards/meletrix/zoom87/config.h, keyboards/meletrix/zoom87/readme.md
change RGBLED_NUM to 20
https://github.com/qmk/qmk_firmware/pull/17831
=> [update] change RGBLED_NUM to 20 for zoom87

keyboards/kprepublic/bm40hsrgb/keymaps/coffee/keymap.c, keyboards/kprepublic/bm40hsrgb/keymaps/coffee/readme.md
Add home and end keys for convenience during programming 
*
=> Add home and end keys

Makefile, util/list_keyboards.sh
Was added for CI but that has been replaced, `make all` performs like a chocolate teapot so its unlikely anyone is using that scenario either.
*
=> Remove .noci functionality

keyboards/splitkb/aurora/corne/rev1/config.h
=> Fixup aurora/corne on develop

lib/usbhost/USB_Host_Shield_2.0/SPP.cpp, lib/usbhost/USB_Host_Shield_2.0/examples/Bluetooth/PS3Multi/PS3Multi.ino, lib/usbhost/USB_Host_Shield_2.0/examples/Bluetooth/WiiMulti/WiiMulti.ino, lib/usbhost/USB_Host_Shield_2.0/examples/HID/le3dp/le3dp_rptparser.h, lib/usbhost/USB_Host_Shield_2.0/examples/HID/scale/scale_rptparser.h
Some of the changes would break examples, and the rest should be upstream instead.
*
=> Revert lib/usbhost changes

keyboards/handwired/tractyl_manuform/5x6_right/arduinomicro/config.h, keyboards/handwired/tractyl_manuform/5x6_right/arduinomicro/info.json
=> Fix API errors in handwired/tractyl_manuform/5x6_right/arduinomicro

data/mappings/info_config.hjson, docs/ChangeLog/20221126.md, docs/api_docs.md, docs/breaking_changes.md, docs/pr_checklist.md, readme.md
=> 2022 Nov 26 changelog.

keyboards/beekeeb/piantor/config.h, keyboards/beekeeb/piantor/info.json, keyboards/beekeeb/piantor/keymaps/default/keymap.c, keyboards/beekeeb/piantor/readme.md, keyboards/beekeeb/piantor/rules.mk
=> Add piantor

quantum/keymap_extras/sendstring_czech.h
`CZ_LPRN` is a shifted keycode so this will not compile.
*
=> Fix Czech sendstring LUT

keyboards/work_louder/micro/info.json
Enable bootmagic as default for the macro pad.
=> Enable bootmagic

docs/reference_info_json.md
`USB` shouldnt be under `RGB Lighting`
*
=> Fix headers in info.json reference

lib/python/qmk/info.py
* Providing only `LAYOUT_all` is lazy
* Layouts containing keyboard name `LAYOUT_reviung33`/`LAYOUT_reviung53`/`LAYOUT_reviung39`
* Remove fallback search of every header file
Lint checks to become errors in the future
*
=> Extend layout lint checks

layouts/default/ortho_5x5/default_ortho_5x5/keymap.c
=> Add missing default_ortho_5x5 keymap

keyboards/40percentclub/25/rules.mk, keyboards/40percentclub/5x5/rules.mk
=> Add some community layouts to 40percentclub boards

lib/python/qmk/info.py
Seems #19200 might have been a tad aggressive for the current state of the codebase.
*
=> Ignore some layout macro names from lint

tmk_core/protocol/usb_descriptor.c
No longer required now product strings are quoted.
*
=> Revert WB32 ISO workaround

lib/python/qmk/submodules.py
=> Apply suggested workaround for #18371

docs/newbs_building_firmware.md, lib/python/qmk/cli/new/keymap.py
Minor tidy up so that the code (and output) is somewhat similar. Also fixes thrown exception when specifying only part of a keyboard name, eg `zvecr` instead of `zvecr/zv48`.
*
=> Align new-keymap with new-keyboard

keyboards/mechlovin/kay60/config.h
Change indicator LED state on Kay60.
Thanks.
*
=> [Keyboard] Change indicator LED state on Kay60

keyboards/cannonkeys/ortho60v2/config.h, keyboards/cannonkeys/ortho60v2/halconf.h, keyboards/cannonkeys/ortho60v2/info.json, keyboards/cannonkeys/ortho60v2/keymaps/default/keymap.c, keyboards/cannonkeys/ortho60v2/keymaps/via/keymap.c, keyboards/cannonkeys/ortho60v2/keymaps/via/rules.mk, keyboards/cannonkeys/ortho60v2/mcuconf.h, keyboards/cannonkeys/ortho60v2/ortho60v2.c, keyboards/cannonkeys/ortho60v2/ortho60v2.h, keyboards/cannonkeys/ortho60v2/readme.md, keyboards/cannonkeys/ortho60v2/rules.mk
Adding the Ortho60v2 keyboard to QMK.
I made it a new top-level keyboard because of the addition of an encoder.
MCU has also been swapped to RP2040
A revision of the existing top level Ortho60 didn't feel quite appropriate due to these changes - but if necessary, I can change organization to reflect this.
Targeting develop so we can use the PWM functionality @KarlK90 has added :)
*
=> Add the Ortho60 v2 Keyboard to QMK

keyboards/handwired/dqz11n1g/matrix.c, keyboards/handwired/dqz11n1g/readme.md
Documentation fixes for handwired/dqz11n1g keyboard (for which I appear to be the maintainer):
- more complete component list in "Hardware Availability" section of readme.md
- clarifications and orthography fixes
- fixed outdated code comment in dqz11n1g/matrix.c
none.
=> dqz11n1g: Documentation improvement.

data/schemas/keyboard.jsonschema
Covering what was initially pushed in 19234, which did not report any lint errors.
*
=> Ensure info.json layout macros are somewhat valid

keyboards/durgod/dgk6x/venus/keymaps/default/keymap.json, keyboards/durgod/dgk6x/venus/keymaps/via/keymap.json, keyboards/hillside/46/keymaps/default/keymap.json, keyboards/hillside/48/keymaps/default/keymap.json, keyboards/hillside/48/keymaps/via/keymap.json, keyboards/hillside/52/keymaps/default/keymap.json, keyboards/splitkb/aurora/corne/keymaps/default/keymap.json
I suspect this is what's causing the build failures for these boards
*
=> Fix `keyboard` for some JSON keymaps

lib/python/qmk/cli/lint.py
=> Add lint check for keyboard/keymap license header

keyboards/momokai/tap_duo/config.h, keyboards/momokai/tap_duo/info.json, keyboards/momokai/tap_duo/keymaps/default/keymap.c, keyboards/momokai/tap_duo/keymaps/via/keymap.c, keyboards/momokai/tap_duo/keymaps/via/rules.mk, keyboards/momokai/tap_duo/readme.md, keyboards/momokai/tap_duo/rules.mk, keyboards/momokai/tap_duo/tap_duo.c, keyboards/momokai/tap_duo/tap_duo.h
This is momokai tap duo, which is momokai tap trio but without one of the buttons. everything else down to the electrical connections are the same
*
=> [Keyboard] Add momokai tap duo

keyboards/linworks/fave84h/keymaps/default/keymap.c, keyboards/linworks/fave84h/keymaps/via/keymap.c
Develop merge broke a previous refactor.
=> Fix LinWorks FAve84H Keymaps

keyboards/converter/modelm101/modelm101.c, keyboards/duck/eagle_viper/v2/v2.c, keyboards/duck/jetfire/jetfire.c, keyboards/duck/lightsaver/lightsaver.c, keyboards/dumbpad/v1x/v1x.c, keyboards/dumbpad/v1x_dualencoder/v1x_dualencoder.c, keyboards/dumbpad/v1x_right/v1x_right.c, keyboards/handwired/daishi/keymaps/default/keymap.c, keyboards/handwired/promethium/promethium.h, keyboards/handwired/retro_refit/retro_refit.c, keyboards/kinesis/alvicstep/alvicstep.c, keyboards/lfkeyboards/lfk78/lfk78.c, keyboards/lfkeyboards/lfk87/lfk87.c, keyboards/lfkeyboards/mini1800/mini1800.c, keyboards/mechlovin/hannah910/hannah910.c, keyboards/org60/org60.c, keyboards/xiudi/xd60/xd60.c, keyboards/yiancardesigns/gingham/gingham.c
With the aim to help `led_set_kb` removal.
*
=> Refactor some led_set_kb instances

keyboards/handwired/prime_exl/config.h, keyboards/handwired/prime_exl/keymaps/default/keymap.c, keyboards/handwired/prime_exl/keymaps/via/keymap.c
=> Refactor use of led_set_user within `handwired/prime_exl`

keyboards/ydkb/ydpm40/config.h, keyboards/ydkb/ydpm40/info.json, keyboards/ydkb/ydpm40/keymaps/default/keymap.c, keyboards/ydkb/ydpm40/keymaps/ydm40/keymap.c, keyboards/ydkb/ydpm40/readme.md, keyboards/ydkb/ydpm40/rules.mk
This PR adds support for a atmega328p keyboard, whose original firmware was tmk.
*
=> add ydpm40 keyboard

keyboards/crypt_macro/config.h, keyboards/crypt_macro/crypt_macro.c, keyboards/crypt_macro/crypt_macro.h, keyboards/crypt_macro/halconf.h, keyboards/crypt_macro/info.json, keyboards/crypt_macro/keymaps/default/keymap.c, keyboards/crypt_macro/keymaps/default/readme.md, keyboards/crypt_macro/keymaps/via/keymap.c, keyboards/crypt_macro/keymaps/via/readme.md, keyboards/crypt_macro/keymaps/via/rules.mk, keyboards/crypt_macro/mcuconf.h, keyboards/crypt_macro/readme.md, keyboards/crypt_macro/rules.mk
=> [Keyboard] Crypt Macro

keyboards/ghs/xls/info.json, keyboards/ghs/xls/keymaps/default/keymap.c, keyboards/ghs/xls/keymaps/southpaw/keymap.c, keyboards/ghs/xls/keymaps/via/keymap.c, keyboards/ghs/xls/keymaps/via/rules.mk, keyboards/ghs/xls/readme.md, keyboards/ghs/xls/rules.mk
Adds the Gone Hacking Studio XLS. I had a previous PR I messed up so this is a redo: https://github.com/qmk/qmk_firmware/pull/18362 This does include all the latest changes requested though (missing license headers, encoder map support).
*
=> Add the Gone Hacking Studio XLS

keyboards/draculad/keymaps/manna-harbour_miryoku/config.h
Moved LAYER_STATE_8BIT from `draculad/config.h` to `draculad/keymaps/default/config.h`, now I can build both default (with `VIA_ENABLE=yes`) and manna-harbour_miryoku keymaps.
* Closes #19337
=> Fix #19337

docs/feature_joystick.md
Fix incorrect content of the joystick feature page
*
=> Fix wrong function name in joystick feature doc page

keyboards/tkc/portico75/keymaps/via/keymap.c, keyboards/tkc/portico75/keymaps/via/rules.mk
=> tkc/portico75 — Fix layers & move to encoder map

keyboards/converter/xmk/config.h, keyboards/converter/xmk/info.json, keyboards/converter/xmk/keymaps/default/keymap.c, keyboards/converter/xmk/post_rules.mk, keyboards/converter/xmk/readme.md, keyboards/converter/xmk/rules.mk, keyboards/converter/xmk/xmk.c, keyboards/converter/xmk/xmk_matrix.c, keyboards/converter/xmk/xmk_matrix.h, keyboards/converter/xmk/xmk_shell.c
This PR adds new keyboard `converter/xmk`. This is the QMK keyboard definition for [𝑥MK](https://github.com/manna-harbour/xmk). Also see https://github.com/manna-harbour/xmk/discussions/2.
Thanks!
*
=> [Keyboard] Add converter/xmk

.github/workflows/api.yml, .github/workflows/auto_approve.yml, .github/workflows/auto_tag.yml, .github/workflows/cli.yml, .github/workflows/develop_update.yml, .github/workflows/docs.yml, .github/workflows/feature_branch_update.yml, .github/workflows/format.yml, .github/workflows/format_push.yml, .github/workflows/labeler.yml, .github/workflows/lint.yml, .github/workflows/stale.yml, .github/workflows/unit_test.yml
As per the title. Most are "guesses" in the sense that they seem like they should be enough.
I've had a look at the imported actions and they _look_ like they should be correct. Will likely be something we need to iterate over time.
=> Lock down workflow permissions.

quantum/rgb_matrix/animations/jellybean_raindrops_anim.h
Refactor jellybean effect to the smaller and faster `random8()`
=> Use random8 for jellybean effect

lib/python/qmk/flashers.py
Should allow `qmk flash /path/to/firmware.ext` to work under `QMK WSL` or regular WSL where windows binaries are on the path?
Its also really really slow by comparison, but im yet to find an alternative method that is faster. However the code *could* be refactored somewhat so that the comparisons are done on a single invocation of the powershell mess.
*
=> WSL `qmk flash firmware.bin` workaround

docs/hardware_keyboard_guidelines.md, docs/pr_checklist.md
Words to cover the changes enforced in 19200
*
=> Add docs to cover recent LAYOUT_all lint checks

.github/workflows/regen_push.yml
Workflows are fighting over branches, which is the cause of the recent closed "regen" PRs.
*
=> Use unique name for regen PR branches

keyboards/atreyu/readme.md
Fix github URL for the atreyu maintainer.
*
=> Fix github URL for the atreyu maintainer.

Makefile
=> Remove unused Makefile paths

builddefs/build_keyboard.mk
=> Allow for specifying the number of symbols to output.

keyboards/sapuseven/macropad12/info.json, keyboards/sapuseven/macropad12/keymaps/default/keymap.c, keyboards/sapuseven/macropad12/keymaps/via/keymap.c, keyboards/sapuseven/macropad12/keymaps/via/rules.mk, keyboards/sapuseven/macropad12/readme.md, keyboards/sapuseven/macropad12/rules.mk
Add new keyboard - MacroPad12.
It will be released soon as I still need to finish some documentation.
This is my first contribution to QMK - please feel free to point out any mistakes.
*(none)*
=> Add SapuSeven MacroPad12

docs/feature_combo.md
Just in case someone (like me) copy paste this.
=> A comma was missing

docs/feature_led_matrix.md, docs/feature_rgb_matrix.md
Incorrectly documented.
See: `builddefs/common_features.mk`
Tested on RP2040 and it'll work to light up the matrix.
=> docs: Fix IS31FL3743A driver name

lib/python/qmk/cli/doctor/linux.py
=> `qmk doctor` - Handle permission issues while checking udev

data/schemas/keymap.jsonschema
Explicit validation does little to validate that some converters cannot be applied to all situations.
*
=> Relax converter validation within keymap schema

util/update_chibios_mirror.sh
Pending new tag creation in the ChibiOS repository.
=> New ChibiOS SVN URL, added new release.

keyboards/dailycraft/wings42/rev1/info.json, keyboards/janus/info.json, keyboards/obosob/steal_this_keyboard/info.json, keyboards/reviung/reviung34/info.json, keyboards/splitkb/aurora/sweep/rev1/info.json
Enable community layout support for some splits with missing entries in `info.json`.
*
=> [keyboard] Enable community layout support

docs/feature_layers.md, docs/feature_rgb_matrix.md
A typo and some rewording on a phrase that was ambiguous
*
=> Small doc changes

keyboards/keebio/iris/rev6b/rev6b.c
Adds a comment to the iris rev6b key matrix -> LED map.
* N/A
=> [Keyboard] keebio/iris document LED matrix

docs/feature_rgb_matrix.md
Minor format change for consistency in the RGB indicator section.
=> Format consistency edit

keyboards/nopunin10did/jabberwocky/v2/info.json
Just needed to change the productId so it would be unique to via, since v1 jabberwocky already exists.
*
=> update jabberwocky v2 productId

Makefile, builddefs/build_keyboard.mk, lib/python/qmk/cli/mass_compile.py, lib/python/qmk/cli/multibuild.py
Can now be done with `qmk mass-compile` filters.
*
=> Remove `make all-<platform>` build targets

docs/ChangeLog/20190830.md, docs/breaking_changes.md, docs/contributing.md, docs/pr_checklist.md
=> Minor cleanup to breaking/checklist docs.

keyboards/ferris/0_1/config.h, keyboards/ferris/0_2/config.h, keyboards/ingrained/config.h, keyboards/kopibeng/mnk65_stm32/config.h, keyboards/yushakobo/navpad/10/rev0/config.h, keyboards/yushakobo/navpad/10/rev1/config.h, keyboards/yushakobo/navpad/10_helix_r/config.h
=> Remove stray UNUSED_PINS

.github/workflows/lint.yml
Should help catch issues like #19615 slipping through.
*
=> Run format-text on keyboard PRs

keyboards/boardsource/lulu/avr/info.json
the encoder pins on the lulu avr were from an earlier PCB and I forgot to update the code when I pred this in. Encoders will now work with the pcb that is for sale.
*
=> [Keyboard] Fix boardsource/lulu/avr encoder pins

keyboards/keychron/v2/v2.c
* As title. 
* Also adds missing line containing `#if defined(RGB_MATRIX_ENABLE) && defined(CAPS_LOCK_LED_INDEX)` as the `#ifdef DIP_SWITCH_ENABLE` uses the `#endif // CAPS_LOCK_LED_INDEX` in [`v2.c`](https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/v2/v2.c). 
* N/A
=> Add missing `bool dip_switch_update_kb` function for Keychron V2

docs/understanding_qmk.md
Changed "...4 row by 5 column numpad" to "...5 row by 4 column numpad" on line 46.
*
=> Fix typo on line 46 of understanding_qmk.md

keyboards/preonic/keymaps/brauner/keymap.c
Signed-off-by: Christian Brauner (Microsoft) <brauner@kernel.org>
=> [Keymap] Update brauner preonic layout

keyboards/reviung/reviung34/keymaps/via/keymap.c, keyboards/reviung/reviung34/keymaps/via/rules.mk
VIA keymap for Reviung 34.
- [*] Keymap/layout/userspace (addition or update)
*
=> VIA keymap for Reviung 34.

quantum/config_common.h, quantum/matrix.h
One small step to killing off `config_common.h`
*
=> Relocate diode direction definitions

builddefs/build_keyboard.mk
=> Accumulate version.h generator flags.

tmk_core/protocol/lufa.mk
Seems to compile now, no idea if its the "best" fix.
Used to live in:
https://github.com/qmk/qmk_firmware/blob/e296d671463f38a78c75ee0727016939634ef985/tmk_core/protocol/midi.mk#L9
*
=> Fix midi after recent refactoring

.github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other_issues.yml
=> Politely ask people not to submit issues to add support for unknown keyboards.

util/regen.sh
`tests/test_common/keycode_table.cpp` was not correctly being flagged on #19720.
*
=> Regen keycode_table for unit tests

keyboards/mechlovin/adelais/adelais.c, keyboards/mechlovin/adelais/standard_led/arm/rules.mk
Fix the first LED stuck in green.
*
=> Fix the underglow RGB LED 

keyboards/crkbd/keymaps/colemak_luna/config.h, keyboards/crkbd/keymaps/colemak_luna/keymap.c, keyboards/crkbd/keymaps/colemak_luna/readme.md, keyboards/crkbd/keymaps/colemak_luna/rules.mk
Added a new keymap for the CRKBD keyboard - colemak_luna, it has an OLED animated pet, a wpm counter and game layers. I have been using it for a while so its tested.
*
=> Added a new keymap for the CRKBD keyboard - colemak_luna

keyboards/keychron/v10/ansi_encoder/info.json
Update the PID definition in info.json file of ansi version.
Please assist me in checking this PR kindly, Thank you!
- Replaced the PID definition with 0x03A1 instead of 0x01A1 in info.json file of ansi version.
*
=> Update info.json for Keychron V10

data/constants/keycodes/keycodes_0.0.2.hjson, quantum/keycodes.h, quantum/quantum_keycodes.h
=> Move more unicode ranges to DD

lib/python/qmk/cli/generate/keyboard_c.py, lib/python/qmk/cli/generate/keyboard_h.py
I was annoyed by `(x, y) = item['matrix']`, where `x` and `y` are reversed and also contextually ambiguous. I ended up fixing related code style, as well as the style of the generated code.
* Generation of layout macros now verifies whether all keys in a layout have matrix information assigned to them.
=> Fixes to source generation [mostly typographic]

keyboards/jacky_studio/bear_65/rules.mk
Wrong Bear65 default keyboard
* Compile issues
=> [Bug] fix bear65

keyboards/linworks/fave84h/info.json
=> [Keyboard] Fix merge error with fave84 board

docs/feature_layers.md
Right hand modifiers are now supported in `LM()`. This PR removes the obsolete limitation of left-modifiers only and adds a table to highlight common errors in the usage of the 5-bit mod-mask.
*
=> Update documentation for LM(layer, mod)

keyboards/synthlabs/060/config.h
=> Fixup synthlabs/060 (reduce firmware size)

keyboards/eniigmakeyboards/ek65/info.json
=> Fixup ek65 -- add processor & bootloader in `info.json`

keyboards/crbn/info.json, keyboards/kepler_33/proto/info.json
```
error: implicit declaration of function 'LAYOUT_1x2u'; did you mean 'LAYOUT_2x2u'?
```
```
error: implicit declaration of function 'LAYOUT_proto'; did you mean 'LAYOUT'?
```
*
=> Fix layout aliases for two boards

lib/python/qmk/cli/generate/keycodes.py, quantum/action.c, quantum/keycode.h, quantum/keycodes.h
=> Tidy up use of keycode range helpers

keyboards/fearherbs1/blue_team_pad/config.h, keyboards/nullbitsco/scramble/v2/config.h
=> Remove lingering `I2CD2` usages w/ RP2040

quantum/rgb_matrix/animations/pixel_fractal_anim.h
Comment update to reflect the original author's github name change.
=> Update fractal attribution comment

docs/ja/other_vscode.md, docs/other_vscode.md, docs/zh-cn/other_vscode.md
- Replace Plugins with Extensions in vscode guide for consistency.
~~- Replaced `KC_NLCK` and `KC_SLCK` with KC_NUM` and `KC_SCRL` in zh-CN and ja doc.~~
- Remove depracted extension links in vscode guide in zh-CN and ja doc following en doc changes.
*
=> [Doc]Remove depracted extension links in vscode guide

keyboards/durgod/dgk6x/info.json
=> Fixup durgod/dgk6x (scroll lock mis-defined as num lock)

keyboards/bpiphany/pegasushoof/2015/config.h, keyboards/bpiphany/pegasushoof/2015/info.json, keyboards/bpiphany/pegasushoof/info.json, keyboards/bpiphany/pegasushoof/keymaps/via/config.h, keyboards/bpiphany/pegasushoof/keymaps/via/keymap.c, keyboards/bpiphany/pegasushoof/keymaps/via/rules.mk
Added VIA keymap and changed info.json and config.h for 2015 to include device manufacturer, name and USB vid and pid. The changes to 2015 keyboard should cause no conflicts to existing users.
The VIA keymap matches the default keymap.
*
=> Added via keymap for bpiphany/pegasushoof

keyboards/bpiphany/pegasushoof/keymaps/via/keymap.c
Indicator functionality has been moved to info.json.
=> Fixup pegasushoof VIA keymap

keyboards/kprepublic/bm40hsrgb/keymaps/skewwhiffy/keymap.c, keyboards/kprepublic/bm40hsrgb/keymaps/skewwhiffy/readme.md
* New Colemak-based layout for BM40 keyboard
*
=> BM40 keymap for Skewwhiffy, revamp

keyboards/thepanduuh/degenpad/keymaps/default/keymap.c
per honorless#5941: "Configurator generates a JSON keymap based on what is assigned in the GUI. You can't assign encoders in that GUI (... yet...) so if there is no keyboard-level callback, the encoder won't do anything.
The default keymap is what gets compiled when someone runs qmk compile -kb keyboard -km default from the command line...and also what gets copied to a new keymap folder when somebody runs qmk new-keymap. So having encoder mapping on it is a good idea. "
*
=> [Keymap] Add encoder map to degenpad default keymap

keyboards/idobao/id61/keymaps/idobao/keymap.c, keyboards/idobao/id63/keymaps/idobao/keymap.c, keyboards/idobao/id67/keymaps/idobao/keymap.c, keyboards/idobao/id67/keymaps/vinorodrigues/keymap.c, keyboards/idobao/id80/v3/ansi/keymaps/idobao/keymap.c, keyboards/idobao/id87/v2/keymaps/idobao/keymap.c
=> Refactor more `KC_MISSION_CONTROL`/`KC_LAUNCHPAD` usages

keyboards/gmmk/gmmk2/p65/ansi/keymaps/achrovisual/keymap.c, keyboards/gmmk/gmmk2/p65/ansi/keymaps/achrovisual/readme.md, keyboards/gmmk/gmmk2/p65/ansi/keymaps/achrovisual/rgb_matrix_user.inc, keyboards/gmmk/gmmk2/p65/ansi/keymaps/achrovisual/rules.mk, keyboards/gmmk/gmmk2/p65/ansi/rules.mk
Just a personal Mac-centric keymap with indicators and custom side light RGB Matrix effects for GMMK2 Compact (P65, ANSI).
* None
=> New keymap for GMMK2 Compact

keyboards/cannonkeys/satisfaction75/info.json, keyboards/cannonkeys/satisfaction75/led.c
=> Fixup cannonkeys/satisfaction75 (readd `backlight.breathing_period`)

keyboards/keychron/q0/rev_0131/keymaps/keychron/keymap.c, keyboards/keychron/q0/rev_0131/keymaps/via/keymap.c, keyboards/keychron/v10/ansi_encoder/keymaps/keychron/keymap.c, keyboards/keychron/v10/ansi_encoder/keymaps/via/keymap.c, keyboards/keychron/v10/iso_encoder/keymaps/keychron/keymap.c, keyboards/keychron/v10/iso_encoder/keymaps/via/keymap.c
=> Remove VIA specific use of `MACRO0*`

keyboards/reviung/reviung34/info.json
0xFEED is not allowed within VIA.
- [* ] Enhancement/optimization
*
=> [Keyboard] Update Reviung Vendor ID

keyboards/keebio/kbo5000/keymaps/default/keymap.c, keyboards/keebio/kbo5000/keymaps/iso/keymap.c, keyboards/keebio/kbo5000/keymaps/via/keymap.c, keyboards/keebio/kbo5000/rev1/info.json
No need to make encoders symmetrical.
*
=> `keebio/kbo5000`: fix encoder config

docs/ChangeLog/20230226.md
=> Add changelog for Leader Key refactor

.github/labeler.yml
=> Flag "builddefs" as core changes

.github/workflows/cli.yml, .github/workflows/format.yml, .github/workflows/format_push.yml, .github/workflows/lint.yml, .github/workflows/regen.yml, .github/workflows/regen_push.yml
Should fix some of the recent CI failures
```
Ψ Wrote keymap_slovenian.h to /__w/qmk_firmware/qmk_firmware/quantum/keymap_extras/keymap_slovenian.h.
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
```
```
CompletedProcess(args=['git', 'submodule', '-q', 'foreach', 'git --no-pager log --no-show-signature --pretty=format:"$sm_path%x01%h%x01%ad%x01%s%x0A" --date=iso -n1'], returncode=128, stdout='', stderr="fatal: detected dubious ownership in repository at '/__w/qmk_firmware/qmk_firmware'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /__w/qmk_firmware/qmk_firmware\n")
```
*
=> Disable safe.directory check

docs/reference_info_json.md
Hasnt been accepted for a while, looks like it was missed.
*
=> Remove `all` from list of animations in `info.json`

lib/python/qmk/c_parse.py
Prints an error when the top half of the layout macro has more keys than the bottom half.
See: `qmk info -kb foxlab/time80 -m`
*
=> Check all keys have matrix positions when parsing C LAYOUT macros

platforms/chibios/flash.mk, util/uf2conv.py, util/uf2families.json
=> Merge upstream changes to uf2conv

docs/pr_checklist.md, docs/support_deprecation_policy.md
As per the title. Also clarifies some PR checklist stuff.
=> Deprecation policy documentation.

keyboards/preonic/keymaps/guillermoap/config.h, keyboards/preonic/keymaps/guillermoap/keymap.c, keyboards/preonic/keymaps/guillermoap/readme.md, keyboards/preonic/keymaps/guillermoap/rules.mk
Created new keymap for Preonic rev3 with encoder support. As mentioned in the README this is highly curated to my liking but is a good example to use the ENCODER_MAP_ENABLE from the docs that I haven't seen in other keymaps.
*
=> Add new keymap for Preonic rev3

data/schemas/keyboard.jsonschema
We block via json files from the repo, but what happens if someone puts that content in `info.json`....
(20008 isnt the first time this has happened)
*
=> Reject VIA keys within info.json

keyboards/anavi/knobs3/info.json, keyboards/anavi/knobs3/keymaps/default/keymap.c, keyboards/anavi/knobs3/knobs3.c, keyboards/anavi/knobs3/mcuconf.h, keyboards/anavi/knobs3/readme.md, keyboards/anavi/knobs3/rules.mk
ANAVI Knobs 3 is a mini mechanical keyboard with 3 clickable rotary encoders, USB-C, RP2040 microcontroller and I2C slot for a display.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Add a new small mechanical keyboard with RP2040. ANAVI Knobs 3 is a mini mechanical keyboard with 3 clickable rotary encoders, USB-C, RP2040 microcontroller and I2C slot for a display.
*
=> keyboards/anavi: Add ANAVI Knobs 3

docs/newbs_building_firmware_workflow.md
As titled, an additional step for workflow to function correctly.
=> Add step to disable git safe directory check

quantum/keymap_common.c
Looks like I missed something when refactoring `KC_MISSION_CONTROL` and `KC_LAUNCHPAD` keycodes.
*
=> Fix processing of recently added system keycodes

docs/pr_checklist.md
Add some more things that are now required in `info.json` and specify some other things that should *not* be included (let me know if I've missed any) and other misc clean up.
=> [Doc] Update PR checklist

keyboards/keebio/kbo5000/rev1/info.json
This pull corrects the Keebio KBO-5000 rev1's Info.json split encoder settings to reflect the correct pins, as addressed in the issues listed below. This was caused by PR #19923 incorrectly moving the pinouts directly rather than by the index, resulting in the rotary encoders no longer working on the right side.
The changes are based on the previous changes prior to PR 19923 to restore functionality.
Reference: https://github.com/qmk/qmk_firmware/commit/7e0299117b389b1c7fcdfa2f20891ba2287ea771#diff-6cb36f0bcd734c3006dece43f95c2536b9d96e55d6a257a6ee8d27bb8c6b5632
* #20073
=> Keebio/KBO-5000 Encoder Misconfiguration Fix for #20073

keyboards/ep/40/info.json
=> Restore matrix pins for ep/40

keyboards/lily58/r2g/config.h
Fix CI on `master`. Flash sizing, as usual.
=> Yet another adventure in trying to fit things into a 32U4

keyboards/pierce/info.json
Pierce split keyboard. To change vid from 0xFEED to 0x6431, to get proper support from VIA project.
To change vid from 0xFEED to 0x6431, to get proper support from VIA project.
*
=> [Keyboard] Change pierce vendor ID

keyboards/ferris/sweep/config.h, keyboards/ferris/sweep/info.json, keyboards/ferris/sweep/rules.mk, keyboards/ferris/sweep/sweep.c
Move build settings into info.json
=> Move Ferris Sweep to data-driven

docs/feature_autocorrect.md
Document additional user callback functions that can be used to manipulate Autocorrect.
=> Document Autocorrect callback functions

docs/newbs_getting_started.md
Add instructions for downloading Homebrew and qmk on an Apple Silicon Mac
=> Update newbs_getting_started to include instructions for apple silicon

keyboards/kbdfans/tiger80/info.json
=> kbdfans/tiger80: remove duplicate keys in info.json

.github/workflows/api.yml, .github/workflows/ci_builds.yml, .github/workflows/cli.yml, .github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/format_push.yml, .github/workflows/lint.yml, .github/workflows/regen.yml, .github/workflows/regen_push.yml, .github/workflows/unit_test.yml, Dockerfile, docs/newbs_building_firmware_workflow.md, util/docker_build.sh, util/docker_cmd.sh
Update to reflect upstream publishing changes.
*
=> Update qmk_cli container references

keyboards/melgeek/z70ultra/z70ultra.c
=> Fixup z70ultra — replace mis-removed file

keyboards/handwired/onekey/bluepill_f103c6/rules.mk
=> Fixup CI build for F103C6 onekey.

keyboards/lpad/info.json
Update incorrect row and col pins, now confirmed working via manual build in QMK MSYS
*
=> Update info.json to correct "rows" and "cols pins

lib/python/qmk/commands.py
Append verbose environment variable to match the verbosity of `compile_configurator_json` with `-v` argument.
=> Increase verbosity of make command

lib/python/qmk/cli/info.py
Should hopefully stop users copy-pasting "bad" content into PRs.
*
=> Strip API specific output from `qmk info`

keyboards/25keys/cassette42/common/oled_helper.h, keyboards/doio/kb16/lib/bongocat/bongocat.h, keyboards/doio/kb16/lib/layer_status/layer_status.h, keyboards/doio/kb16/lib/logo.h, keyboards/gboards/engine/keymap_engine.h, keyboards/gboards/g/config_default.h, keyboards/gboards/g/keymap_combo.h, keyboards/gboards/g/keymap_engine.h, keyboards/gopolar/gg86/lib/logo.h, keyboards/gopolar/gg86/lib/wave.h, keyboards/handwired/d48/taphold.h, keyboards/handwired/promethium/color.h, keyboards/handwired/promethium/rgbsps.h, keyboards/handwired/symmetric70_proto/matrix_fast/test_config.h, keyboards/handwired/symmetric70_proto/matrix_fast/test_config_74hc157.h, keyboards/handwired/symmetric70_proto/matrix_fast/test_config_direct.h, keyboards/hhkb/rn42/suart.h, keyboards/horrortroll/handwired_k552/lib/bongocat.h, keyboards/horrortroll/handwired_k552/lib/galaxy.h, keyboards/horrortroll/handwired_k552/lib/logo.h, keyboards/horrortroll/lemon40/lib/bongocat.h, keyboards/marksard/rhymestone/common/oled_helper.h, keyboards/marksard/treadstone48/common/oled_helper.h, keyboards/work_louder/rgb_functions.h, keyboards/yushakobo/quick17/quick17_prefs.h
=> Fix some more missing `#pragma once`s

keyboards/viktus/minne/info.json
=> [keyboard] Correcting info.JSON for Viktus Minne

lib/python/qmk/info.py
```
lib/python/qmk/info.py:53:1: C901 '_validate' is too complex (17)
```
*
=> Reduce _validate complexity

keyboards/viktus/osav2/info.json
Enabling extrakeys and mousekeys in info.JSON according to a recent comment on another PR pointing out they were disabled by accident.
*
=> [keyboard] Correcting info.JSON for OSAv2

keyboards/wuque/creek70/readme.md, keyboards/wuque/ikki68_aurora/readme.md, keyboards/wuque/mammoth75x/readme.md, keyboards/wuque/promise87/ansi/readme.md, keyboards/wuque/promise87/wkl/readme.md, keyboards/wuque/serneity65/readme.md
Removed some invalid characters between line breaks.
=> Remove invalid characters

.github/workflows/ci_builds.yml
Sometimes builds take too long to complete, especially with a lot of PRs being merged in a burst.
This limits the CI runs to twice-daily.
=> CI Builds: master/develop, default/via, twice daily.

keyboards/nack/nack.c
=> Fixup CI build for `nack`.

lib/python/qmk/cli/generate/api.py
`keyboards.json` is 38MB before, 22MB after, shaves a few seconds off loading the file.....
*
=> Minify content published to API

data/mappings/info_rules.hjson, data/schemas/keyboard.jsonschema
=> Allow EEPROM_DRIVER from info.json

keyboards/xiudi/xd75/keymaps/germanized/keymap.c, users/bcat/bcat.h, users/toinux/keymap_qwerty_fr.h
Time to tidy up yet another dumping ground header.
*
=> Remove some use of keymap.h

keyboards/handwired/dactyl_manuform/6x7/keymaps/iso-de/config.h, keyboards/handwired/dactyl_manuform/6x7/keymaps/iso-de/keymap.c, keyboards/handwired/dactyl_manuform/6x7/keymaps/iso-de/readme.md
Add ISO-DE keymap for Dactyl Manuform 6x7
* None
=> ISO-DE Keymap for Dactyl Manuform 6x7

keyboards/giabalanai/config.h, keyboards/giabalanai/info.json, keyboards/giabalanai/keymaps/2firmware/config.h, keyboards/giabalanai/keymaps/3araht/keymap.c, keyboards/giabalanai/keymaps/default_giabarinaix2/config.h, keyboards/giabalanai/keymaps/giabarinaix2led/config.h, keyboards/giabalanai/keymaps/party/keymap.c, keyboards/giabalanai/keymaps/via/config.h, keyboards/giabalanai/rules.mk
A new layer was added to two keymaps.
*
=> New layer added to giabalanai keyboard

docs/feature_debounce_type.md
* List algorithms in an easier to read table
* Remove superflous introduction section
* Move wordy `sym_eager_pr` recommendation
=> Use table for debounce algorithm description

.github/workflows/ci_builds.yml
=> Fixup CI build variables.

docs/feature_layers.md
Asking how to implement a keycode to perfom a cycle between some layers is a somewhat recurrent question on Discord, hence I added a code snippet for it on the layers' documentation page. Added a ton of comments so new people can *kinda* understand how the code works, but some of them may be useless and get removed instead.
*
=> Add layer-cycle example

docs/feature_converters.md
Supported Convertors sub section:
> | `promicro` | `elite_pi` | 
appeared twice, removed one
n/a
=> Convertors documentation: Removed duplicate table entry

keyboards/primekb/meridian/rules.mk
CI Build failure. As per the title.
From their site:
=> Set up DEFAULT_FOLDER for primekb/meridian

keyboards/custommk/genesis/rev2/keymaps/via/keymap.c
As per the title. Next time I'll actually commit the changeset, instead of just pushing the branch after a build.
=> Fix up via keymap builds.

keyboards/vertex/angle65/info.json
=> [Keyboard] Update angle65 VID/PID

.gitignore
Will catch cases like #20386 with bad configuration.
Now produces the follow lint error,
```
$ qmk lint -kb tweetydabird/lotus58/nanoboot
☒ tweetydabird/lotus58/nanoboot/default: The file "keyboards/tweetydabird/lotus58/nanoboot/keymaps/default/info.json" should not exist!
☒ Lint check failed for: tweetydabird/lotus58/nanoboot
```
*
=> Reject info.json at keymap level

keyboards/hineybush/h87_g2/info.json
Changes VID of the h87 g2 as it previously conflicted with another PCB.
* Duplicate VID/PID with another keyboard, causing conflicts with VIA
=> h87 g2 VID update

keyboards/ymdk/id75/config.h, keyboards/ymdk/id75/info.json
=> [Keyboard] Update ymdk/id75 config

keyboards/momokai/tap_duo/readme.md, keyboards/momokai/tap_trio/readme.md
Add missing hardware information to readme
=> Add hardware information momokai keyboards

docs/feature_wpm.md
=> Fix typo in `feature_wpm.md` title

keyboards/tweetydabird/lotus58/info.json
=> [Keyboard] Update lotus58 RGB config

keyboards/dotmod/dymium65/config.h, keyboards/dotmod/dymium65/info.json
=> Fixup dymium65 RGB Pin on develop

keyboards/mxss/keymaps/via/keymap.c
=> Fixup missing include in mxss `via` keymap

keyboards/amag23/info.json, keyboards/amag23/keymaps/default/keymap.c, keyboards/amag23/keymaps/qwert/keymap.c, keyboards/amag23/keymaps/via/keymap.c, keyboards/amag23/readme.md
- updates relevant product links (fixes the 404 errors I was getting while researching this board)
- renames `LAYOUT_all` to `LAYOUT` (only one layout is supported)
cc @ianmclinden (keyboard maintainer)
=> Koolertron AMAG23 Touch-Up

docs/feature_combo.md
Minor correction to the code example
=> Remove combo count from array

keyboards/novelkeys/nk_plus/info.json
rgblight -> ws2812 for pin config
=> [Keyboard] Fix nk plus ws2812 config

docs/feature_advanced_keycodes.md
Simplify code example to match changes in #20512.
=> Update code example to match description

drivers/led/issi/is31fl3218.h, drivers/led/issi/is31fl3731-simple.h, drivers/led/issi/is31fl3731.h, drivers/led/issi/is31fl3733-simple.h, drivers/led/issi/is31fl3736.h, drivers/led/issi/is31fl3737.h
`memcpy()` use from #20572 requires `string.h`.
=> Add required string header file

drivers/led/issi/is31fl3736.c
Fix multiple driver support
* Fix multiple drivers for 3736
=> [Bug] Add Develop is31fl3736 multi drivers

keyboards/karn/keymaps/colemak/config.h, keyboards/karn/keymaps/colemak/keymap.c
`make karn:colemak` was failing to build. This PR introduces a few small changes to fix it.
- Remove now deprecated `IGNORE_MOD_TAP_INTERRUPT_PER_KEY` from `keyboards/karn/keymaps/colemak/config.h`
- Update deprecated `qk_tap_dance_action_t` to `tap_dance_action_t` in `keyboards/karn/keymaps/colemak/keymap.c`
* See desrciption
=> Small changes to fix failing karn keyboard build (make karn:colemak)

keyboards/handwired/phantagom/baragon/info.json, keyboards/handwired/phantagom/varan/info.json
=> [Keyboard] Fix ws2812 pin for phantagom boards

keyboards/mxss/rgblight.c
=> [Keyboard] Fix mxss rgblight.c compilation issues

keyboards/akb/vero/info.json, keyboards/ebastler/e80_1800/info.json, keyboards/teleport/native/info.json
As it would just be set by mcu selection...
*
=> Specifying the default board file is redundant

keyboards/spaceholdings/nebula12b/info.json, keyboards/spaceholdings/nebula12b/keymaps/default/keymap.c, keyboards/spaceholdings/nebula12b/keymaps/via/keymap.c
- rename `LAYOUT_all` to `LAYOUT_ortho_4x3` (only one layout supported)
cc @yiancar (keyboard maintainer)
=> Space Holdings Nebula12B

keyboards/prototypist/oceanographer/keymaps/via/config.h
This one is fun...
It has rgblight, audio and oled enabled, on an atmega32u4... No wonder it's out of space.  Even with a bunch of stuff disabled. 
Simplest fix was also disabling music mode...
* Tzarc CI
=> [Keyboard] Reduce compiled size for prototypist oceanographer's via keymap

keyboards/1upkeyboards/pi50/keymaps/default/keymap.c, keyboards/1upkeyboards/pi50/keymaps/via/keymap.c, keyboards/adpenrose/obi/keymaps/default_625u_space/keymap.c, keyboards/dotmod/dymium65/keymaps/default/keymap.c, keyboards/dotmod/dymium65/keymaps/via/keymap.c, keyboards/gmmk/pro/rev1/ansi/keymaps/vnmm/keymap.c, keyboards/handwired/phantagom/baragon/keymaps/default/keymap.c, keyboards/handwired/phantagom/baragon/keymaps/via/keymap.c, keyboards/kalakos/bahrnob/keymaps/via/keymap.c, keyboards/keychron/v3/ansi_encoder/keymaps/vnmm/keymap.c, keyboards/mechwild/mercutio/keymaps/default_625u_space/keymap.c, keyboards/meletrix/zoom75/keymaps/default/keymap.c, keyboards/meletrix/zoom75/keymaps/via/keymap.c, keyboards/quadrum/delta/keymaps/ansi/keymap.c, keyboards/quadrum/delta/keymaps/default/keymap.c, keyboards/quadrum/delta/keymaps/iso/keymap.c, keyboards/quadrum/delta/keymaps/via/keymap.c, keyboards/sofle/keymaps/via/keymap.c, keyboards/stello65/beta/keymaps/default/keymap.c, keyboards/stello65/beta/keymaps/via/keymap.c, keyboards/tweetydabird/lotus58/keymaps/default/keymap.c
Tidy up new additions since #20454.
*
=> Tidy up encoder_map directions

users/dshields/config.h, users/dshields/rules.mk
=> [Keyboard] Add caps word enable to dshields keymaps.

keyboards/zwag/zwag75/info.json
=> Fixup zwag75

.clangd, .vscode/extensions.json, .vscode/settings.json, docs/other_vscode.md
`clangd` seems to be a lot better at dealing with detection of paths and the like automatically.
Draft PR for now while we work out dependencies -- macOS should be fine, Linux and Windows may need separate installations. Documentation to match, once figured out.
=> Far better VSCode intellisense support using clangd.

keyboards/tg4x/config.h
I changed the 6 by 7 at the line : "#define RGBLED_NUM 6". Because the TG4x has 7 RGB LEDs.
*
=> [Keyboard] Update tg4x RGB LED count

.github/workflows/auto_tag.yml
20964 didnt fix, will do further testing on my fork to isolate the issue. In the mean time, and for the pending develop merge, this should "fix" things.
*
=> Revert to last known working anothrNick/github-tag-action version

keyboards/ymdk/id75/rules.mk
- Correct `MCU_LDSCRIPT` per #20150
- Remove `WS2812_DRIVER` from keyboard-level `rules.mk` per #20350
=> [keyboard] update ymdk/id75/rules.mk for develop

lib/python/qmk/cli/generate/make_dependencies.py
=> `qmk generate-make-dependencies` improvements

docs/feature_space_cadet.md
I noticed that the site “stevelosh.com” is not available anymore.
So to keep the referenced article about "A Modern Space Cadet" accessible, I changed the link to the archive.org wayback machine.
=> Use wayback machine for unreachable site

data/mappings/defaults.hjson, platforms/chibios/boards/QMK_BLOK/board/board.mk, platforms/chibios/boards/QMK_BLOK/configs/board.h, platforms/chibios/boards/QMK_BLOK/configs/chconf.h, platforms/chibios/boards/QMK_BLOK/configs/config.h, platforms/chibios/boards/QMK_BLOK/configs/halconf.h, platforms/chibios/boards/QMK_BLOK/configs/mcuconf.h, platforms/chibios/converters/promicro_to_blok/converter.mk
An alternative solution was provided <https://github.com/qmk/qmk_firmware/pull/20626#discussion_r1181102890>, however that would have been somewhat incomplete if a user were to use `"development_board": "blok"`.
Downside, more board files incurs maintenance burdens.
*
=> Duplicate board files for blok converter

keyboards/fancytech/fancyalice66/keymaps/via/keymap.c, keyboards/jaykeeb/sriwedari70/keymaps/via/keymap.c, keyboards/keebio/foldkb/keymaps/via/keymap.c
I guess these slipped thru after the overall change.
=> Encoder map: NUM_DIRECTIONS

docs/_summary.md
=> Update "Most Recent ChangeLog" link

.github/workflows/auto_tag.yml
<https://github.com/anothrNick/github-tag-action/issues/269>
Looks like they might have addressed the issue we were having.
*
=> Bump anothrNick/github-tag-action from 1.62.0 to 1.66.0

keyboards/z12/keymaps/zigotica/keymap.c, keyboards/z12/keymaps/zigotica/oled.c
=> z12 zigotica keymap tweaks

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, lib/python/qmk/info.py
Reverts qmk/qmk_firmware#19515
=> Revert "Add *_MATRIX_LED_COUNT generation/validation"

keyboards/mechlovin/zed65/info.json, keyboards/mechlovin/zed65/rev1/info.json
Update diode direction. Thank to @keyboard-magpie 
*
=> [Keyboard] Zed65 Rev.1 - Update info.json

keyboards/handwired/scottokeebs/scottostarter/info.json, keyboards/handwired/scottokeebs/scottostarter/keymaps/default/config.h, keyboards/handwired/scottokeebs/scottostarter/keymaps/default/keymap.c, keyboards/handwired/scottokeebs/scottostarter/readme.md, keyboards/handwired/scottokeebs/scottostarter/rules.mk
Add ScottoStarter handwired keyboard along with `default` keymap.
*
=> Add ScottoStarter handwired keyboard

keyboards/handwired/scottokeebs/scotto40/info.json, keyboards/handwired/scottokeebs/scotto40/keymaps/default/config.h, keyboards/handwired/scottokeebs/scotto40/keymaps/default/keymap.c, keyboards/handwired/scottokeebs/scotto40/keymaps/scotto/config.h, keyboards/handwired/scottokeebs/scotto40/keymaps/scotto/keymap.c, keyboards/handwired/scottokeebs/scotto40/keymaps/scotto/rules.mk, keyboards/handwired/scottokeebs/scotto40/readme.md, keyboards/handwired/scottokeebs/scotto40/rules.mk
Add Scotto40 handwired keyboard along with `default` and `scotto` keymaps.
*
=> Add Scotto40 handwired keyboard

docs/feature_layers.md
=> [Documentation] Fix typo

keyboards/planck/rev7/readme.md
Corrected typo explaining encoder requirements.
=> Typo Correction readme.md

docs/newbs_building_firmware_configurator.md, docs/newbs_flashing.md
Add some details about rp2040 to the newbs flashing and configurator doc.
*
=> Update newbs docs with some rp2040 stuff

quantum/rgb_matrix/animations/pixel_rain_anim.h
Use a simple ternary operator to fill the HSV variable with zeros or randomised hue and saturation values. This change reduces output firmware size.
=> Refactor the rain light decision operator

keyboards/handwired/scottokeebs/scottonum/info.json, keyboards/handwired/scottokeebs/scottonum/keymaps/default/keymap.c, keyboards/handwired/scottokeebs/scottonum/readme.md, keyboards/handwired/scottokeebs/scottonum/rules.mk
Add ScottoNum macropad and default keymap.
*
=> Add ScottoNum macropad

keyboards/mokey/mokey12x2/info.json, keyboards/mokey/mokey12x2/keymaps/default/keymap.c, keyboards/mokey/mokey12x2/keymaps/via/keymap.c, keyboards/mokey/mokey12x2/keymaps/via/rules.mk, keyboards/mokey/mokey12x2/readme.md, keyboards/mokey/mokey12x2/rules.mk
=> [Keyboard] Add mokey12x2

keyboards/handwired/dactyl_manuform/6x7/info.json
Amended last row pin to pro_micro pin, previously was an elite_c pin
* n/a
=> `dactyl_manuform/6x7` correction

keyboards/viktus/osav2_numpad_topre/ec.c, keyboards/viktus/osav2_numpad_topre/ec.h, keyboards/viktus/osav2_numpad_topre/info.json, keyboards/viktus/osav2_numpad_topre/keymaps/default/keymap.c, keyboards/viktus/osav2_numpad_topre/keymaps/via/keymap.c, keyboards/viktus/osav2_numpad_topre/keymaps/via/rules.mk, keyboards/viktus/osav2_numpad_topre/osav2_numpad_topre.c, keyboards/viktus/osav2_numpad_topre/readme.md, keyboards/viktus/osav2_numpad_topre/rules.mk
Adding the OSAv2 Numpad Topre PCB
*
=> [Keyboard] Adding OSAv2 Numpad Topre support

docs/keycodes.md, docs/quantum_keycodes.md
Add note about having to enable QK_MAKE. 
* Discord
=> [Docs] Add note about `ENABLE_COMPILE_KEYCODE` to docs

docs/coding_conventions_c.md
Add code markdown for optional braces examples.
=> Code markdown amendment

keyboards/planck/keymaps/lindgrenj6/config.h, keyboards/planck/keymaps/lindgrenj6/keymap.c, keyboards/planck/keymaps/lindgrenj6/readme.md, keyboards/planck/keymaps/lindgrenj6/rules.mk
=> Add lindgrenj6 planck layout

keyboards/mechlovin/zed60/config.h
Update alternate function for correct underglow RGB on Zed60.
Thanks.
*
=> [Keyboard] Update alternate function for WS2812 SPI on Zed60 PCB

keyboards/kibou/winter/info.json, keyboards/kibou/winter/keymaps/default/keymap.c, keyboards/kibou/winter/keymaps/via/keymap.c
[title]
cc @FanXingStudio (keyboard maintainer)
=> Kibou Winter: rename LAYOUT to LAYOUT_tkl_ansi_wkl

keyboards/gmmk/pro/config.h
Turn off RGB on the GMMK Pro when suspended
* resolves #21336
=> Turn off RGB when suspended

.github/workflows/feature_branch_update.yml
=> Enable auto-merge of develop to riot

.github/workflows/feature_branch_update.yml
#21389 wasn't executed due to `develop` not being targeted by GH workflows.
=> Add riot auto-merge to `master` to trigger GH workflows.

keyboards/sofle/keymaps/via/config.h
=> Sofle: fix LED count

keyboards/keebio/bamfk1/rules.mk
=> Reduce `keebio/bamfk1:via` firmware size

keyboards/b_sides/rev41lp/info.json, keyboards/b_sides/rev41lp/keymaps/via/keymap.c, keyboards/b_sides/rev41lp/keymaps/via/rules.mk
=> keyboards/b_sides/rev41lp: add via keymap

keyboards/handwired/dactyl_maximus/info.json, keyboards/handwired/dactyl_maximus/keymaps/default/keymap.c, keyboards/handwired/dactyl_maximus/keymaps/via/keymap.c, keyboards/handwired/dactyl_maximus/keymaps/via/rules.mk, keyboards/handwired/dactyl_maximus/readme.md, keyboards/handwired/dactyl_maximus/rules.mk
The largest key count Dactyl variant available from a Dactyl generator, coming to QMK.
Thanks goes to [unit-5370](https://github.com/unit-5370) for providing images and testing.
* n/a
=> add `handwired/dactyl_maximus` keyboard

keyboards/1upkeyboards/pi60/info.json, keyboards/1upkeyboards/pi60/keymaps/default/keymap.c, keyboards/1upkeyboards/pi60/keymaps/via/keymap.c
Update info.json, default keymap, and via keymap
Discovered an error in the matrix (specifically left shift), and small changes to the default and via keymaps.
*
=> Update info.json, default keymap, and via keymap

drivers/ps2/ps2_mouse.c
`PS2_MOUSE_BTN_RIGHT` and `PS2_MOUSE_BTN_LEFT` are bit positions not bit masks.
Also keep `PS2_MOUSE_BTN_MIDDLE`
*
=> Fix PS2_MOUSE_INVERT_BUTTONS

docs/pr_checklist.md
documentation update to the PR checklist to try and make a "pristine keymap" clearer, in the vain hope someone will read this far
* overcomplicated default keymaps (we hope)
=> clarify what the heck pristine means for reasons

keyboards/handwired/dactyl_promicro/keymaps/default/keymap.c, keyboards/handwired/dactyl_promicro/readme.md
Modernize handwired/dactyl_promicro keyboard readme.md
* n/a
=> Update `dactyl_promicro` readme

users/bcat/bcat.h
added `quantum_keycodes.h` to [userspace].h file
* n/a
=> Minor amendment to `bcat` userspace to prevent build failure

keyboards/custommk/evo70_r2/config.h, keyboards/custommk/evo70_r2/halconf.h, keyboards/custommk/evo70_r2/info.json, keyboards/custommk/evo70_r2/keymaps/default/keymap.c, keyboards/custommk/evo70_r2/keymaps/via/config.h, keyboards/custommk/evo70_r2/keymaps/via/keymap.c, keyboards/custommk/evo70_r2/keymaps/via/rules.mk, keyboards/custommk/evo70_r2/matrix.c, keyboards/custommk/evo70_r2/mcuconf.h, keyboards/custommk/evo70_r2/readme.md, keyboards/custommk/evo70_r2/rules.mk
=> Add EVO70 R2 Keyboard

keyboards/k34/info.json, keyboards/k34/keymaps/default/config.h, keyboards/k34/keymaps/default/keymap.c, keyboards/k34/readme.md
- `info.json`
- changed LAYOUT to LAYOUT_split_3x5_2
- added community layout
- amended, and tidied, keymap(s) LAYOUT to match
* n/a
=> Update `k34` layout to `split_3x5_2`

quantum/keycode_config.c
=> bootmagic mods covering the case when swapped mods are pressed at the same time (#21320)

quantum/debounce.h, quantum/debounce/asym_eager_defer_pk.c, quantum/debounce/none.c, quantum/debounce/sym_defer_g.c, quantum/debounce/sym_defer_pk.c, quantum/debounce/sym_defer_pr.c, quantum/debounce/sym_eager_pk.c, quantum/debounce/sym_eager_pr.c, quantum/debounce/tests/debounce_test_common.cpp, quantum/debounce/tests/debounce_test_common.h
=> debounce: remove direct `quantum.h` includes

docs/squeezing_avr.md
Add an additional section on simplifying magic keycode config placeholder functions if that feature is unused.
=> [Docs] Squeeze AVR with simplified magic config functions

layouts/community/ergodox/zweihander-macos/keymap.c
=> Zweihander: swap volume direction, add Expand/Shrink Selection buttons

keyboards/jaykeeb/kamigakushi/info.json, keyboards/jaykeeb/sebelas/info.json
=> fix some indicator and pin jaykeeb board

keyboards/lily58/lib/rgb_state_reader.c
readded quantum.h to rgb_state_reader.c for the lily58
quantum.h was removed and not properly added back by #20167. This led to some keymaps being uncompilable. This commit fixes that issue.
=> re-add accidental removal of quantum.h

keyboards/holyswitch/lightweight65/info.json, keyboards/holyswitch/lightweight65/keymaps/default/keymap.c, keyboards/holyswitch/lightweight65/keymaps/via/keymap.c
- rename LAYOUT to LAYOUT_65_ansi_blocker
- enable Community Layout support
cc @DeskDaily (keyboard maintainer)
=> HolySwitch Lightweight65 Community Layout Support

docs/other_vscode.md
=> [Docs] Fix VS code live share extension link

docs/feature_rawhid.md, quantum/raw_hid.h
Added doc comments to raw_hid.h and reworked documentation, adding a simple example taken from my gist.
*
=> Raw HID: documentation improvements

quantum/unicode/unicode.h, quantum/unicode/unicode_keycodes.h
=> Unicode: move keycode aliases to a separate header

keyboards/keychron/c2_pro/info.json
As the title and request for a review, thanks!
- Updated info.json in c2_pro and added '"custom" = true'.
*
=> Updated info.json of keychron c2 pro

quantum/quantum.c, quantum/quantum.h
Only quantum.c really needs to know about the `process_*` functions, so for the headers that don't also declare stuff users might want to reference (eg. `register_ucis()` from `process_ucis`), move their header includes there.
Also fixed a small issue where the programmable button API was not visible due to quantum.h only including the `process_` header.
*
=> quantum.h: clean up process_keycode includes

builddefs/common_features.mk, docs/feature_led_matrix.md, drivers/led/ckled2001-simple.c, drivers/led/ckled2001-simple.h, drivers/led/issi/is31fl3731-simple.c, drivers/led/issi/is31fl3731-simple.h, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733-simple.h, keyboards/clueboard/66_hotswap/gen1/info.json, keyboards/fallacy/indicators.c, keyboards/input_club/ergodox_infinity/info.json, keyboards/input_club/whitefox/info.json, keyboards/keychron/c1_pro/ansi/white/info.json, keyboards/keychron/c2_pro/ansi/white/info.json, keyboards/keychron/s1/ansi/white/info.json, keyboards/mechlovin/olly/octagon/info.json, keyboards/mechlovin/zed65/mono_led/info.json, keyboards/terrazzo/info.json, quantum/led_matrix/led_matrix_drivers.c
Lowercased driver names and function prefixes.
*
=> LED Matrix: driver naming cleanups

lib/python/qmk/cli/generate/keycodes.py, quantum/keymap_extras/keymap_swiss_de.h, quantum/keymap_extras/keymap_swiss_fr.h
=> keycode aliases: work around ChibiOS ch.h include guard

data/mappings/keyboard_aliases.hjson, keyboards/coarse/vinta/info.json, keyboards/doro67/multi/info.json, keyboards/doro67/regular/info.json, keyboards/doro67/rgb/info.json, keyboards/jaykeeb/kamigakushi/info.json, keyboards/kbdfans/kbd67/mkiirgb/info.json, keyboards/noxary/268_2/info.json, lib/python/qmk/commands.py
Hasnt been kept up to date as they have generally been added to the keyboard level, within `info.json`.
Any existing entries have also been migrated.
=> Remove layout aliases from keyboard_aliases.hjson

keyboards/automata02/alisaie/info.json, keyboards/automata02/alisaie/keymaps/default/keymap.c, keyboards/automata02/alisaie/keymaps/via/keymap.c
Follow-up to #21552.
Physically arranges the keymaps to resemble the assembled board, and refactors the keymaps for style.
cc @Automata02 (keyboard maintainer)
=> Automata02 Alisaie Develop Touch-Up

keyboards/moondrop/dash75/keymaps/default/keymap.json, keyboards/moondrop/dash75/keymaps/via/keymap.json
`moondrop/dash75` is not a buildable keyboard as it contains no `rules.mk`.
*
=> moondrop/dash75: fix keymap

docs/contributing.md
=> Contributing docs: add note to make sure repo is up to date

keyboards/binepad/bn009/keymaps/default/keymap.json, keyboards/binepad/bn009/keymaps/via/keymap.json, keyboards/durgod/dgk6x/hades_ansi/keymaps/default/keymap.json, keyboards/durgod/dgk6x/hades_ansi/keymaps/via/keymap.json
Invalid `keyboard` values in JSON keymap.
*
=> Fix `binepad/bn009` and `durgod/dgk6x/hades_ansi` keymaps

keyboards/doio/kb38/info.json, keyboards/doio/kb38/keymaps/default/keymap.c
Encoder press keys were out of order.
*
=> doio/kb38: fix layout

keyboards/handwired/dactyl_lightcycle/info.json
change `usb.*` information to meet requirements for VIA
*
=> Update usb.* of `dactyl_lightcycle`

keyboards/wuque/nemui65/info.json
add two ','
https://github.com/qmk/qmk_firmware/pull/21304
=> json-like for nemui65

keyboards/handwired/dactyl_maximus/info.json
Update `usb` field to meet VIA requirements - related [PR](https://github.com/the-via/keyboards/pull/1936/files)
* n/a
=> Update `usb.`* for `dactyl_maximus`

keyboards/clueboard/2x1800/2021/keymaps/default/keymap.json, keyboards/durgod/k320/keymaps/default_mac/keymap.json, keyboards/handwired/pytest/macro/keymaps/default/keymap.json, keyboards/jacky_studio/piggy60/keymaps/via/keymap.json, keyboards/splitkb/aurora/sofle_v2/keymaps/default/keymap.json
These didn't error out in api_tasks because they're valid keyboards.
*
=> Fix `keyboard` field for some JSON keymaps

keyboards/kikoslab/kl90/config.h
`EMCODER_DIRECTION_FLIP` is not a thing though if the intention was to use `ENCODER_DIRECTION_FLIP`, then the A/B pins would need swapping. Assuming that it was tested with the spelling mistake so actually functions as expected?
cc @swiftrax as maintainer
*
=> Remove invalid config option

keyboards/handwired/dactyl_cc/info.json
Change `usb` information to meet VIA requirements
* n/a
=> Update `usb.`* for dactyl_cc

keyboards/coarse/cordillera/config.h
AF mode for timer 1, channel 1 on F072 pin A8 is 2 (the default).
Checked all the other boards too, this was the only wrong one.
*
=> coarse/cordillera: fix backlight config

keyboards/controllerworks/city42/info.json, keyboards/drop/alt/v2/info.json, keyboards/drop/ctrl/v2/info.json, keyboards/drop/shift/v2/info.json, keyboards/inland/mk47/info.json, keyboards/keebio/nyquistpad/info.json, keyboards/linworks/fave60a/info.json, keyboards/linworks/favepada/info.json, keyboards/monsgeek/m1/info.json, keyboards/pangorin/tan67/info.json, keyboards/projectd/65/projectd_65_ansi/info.json
Followup to #21594, fixing boards that were missed/added since.
*
=> Fix keyboards with old RGB driver names

docs/squeezing_avr.md
* Simplify description
* Add link to magic function section
=> [Doc] Improve magic keycode section

keyboards/lxxt/lxxt.c
```
keyboards/lxxt/lxxt.c: In function 'encoder_update_kb':
keyboards/lxxt/lxxt.c:22:6: error: infinite recursion detected [-Werror=infinite-recursion]
22 | bool encoder_update_kb(uint8_t index, bool clockwise) {
|      ^~~~~~~~~~~~~~~~~
keyboards/lxxt/lxxt.c:23:10: note: recursive call
23 |     if (!encoder_update_kb(index, clockwise)) {
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling: quantum/action.c
```
*
=> Fix infinite recursion in lxxt encoder logic

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema
Options do not exist for feature.
*
=> Remove `led_matrix.hue_steps` and `led_matrix.sat_steps` from schema

data/schemas/keyboard.jsonschema
Add "apm32-dfu" in "bootloader" lable to fix errors when use "apm32-dfu" as bootloader.
*
=> Add "apm32-dfu" in keyboard.jsonschema

docs/reference_info_json.md
I think I got pretty much everything.
*
=> Rework info.json reference

platforms/chibios/boards/GENERIC_WB32_F3G71XX/board/board.c, platforms/chibios/boards/GENERIC_WB32_FQ95XX/board/board.c, platforms/chibios/boards/IC_TEENSY_3_1/board/board.c, platforms/chibios/boards/PJRC_TEENSY_3_5/board/board.mk, platforms/chibios/boards/PJRC_TEENSY_3_5/board/extra.c, platforms/chibios/boards/PJRC_TEENSY_3_6/board/board.mk, platforms/chibios/boards/PJRC_TEENSY_3_6/board/extra.c, platforms/chibios/suspend.c, tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/chibios/usb_main.c
Current changes has some issues, reverting until we can get all this properly sorted
* #19780 
* #21676
* #21391
=> Revert  changes to ChibiOS Suspend Code

keyboards/chosfox/cf81/keymaps/default/keymap.c, keyboards/chosfox/cf81/keymaps/via/keymap.c
=> Fix invalid encoder_map declaration

util/install/macos.sh
Related to https://github.com/qmk/homebrew-qmk/pull/65
*
=> Update macOS install script

keyboards/ah/haven65/info.json, keyboards/ah/haven65/keymaps/default/keymap.c, keyboards/ah/haven65/keymaps/via/keymap.c
- rename LAYOUT to LAYOUT_65_ansi_blocker
- enable Community Layout support
cc @CMMS-Freather (keyboard maintainer)
=> AH Haven65 Community Layout support

drivers/led/issi/is31fl3218.c
Changed `ISSI_` define prefixes to `IS31FL3218_`.
*
=> is31fl3218: driver naming cleanups

keyboards/chosfox/cf81/info.json
[title]
cc @jonylee1986 (keyboard maintainer)
=> Chosfox CF81: correct layout data

.github/labeler.yml
=> Auto-label data-driven efforts

docs/qmk_custom_dark.css
Make the background of the tip more visible against the page's background, and make the text in the tip more visible against the tip's background. Also adjust code-within-tip background to be more visible against the new tip background.
Before:
After:
* [Mentioned on Discord](https://discord.com/channels/440868230475677696/867530715192885269/1148753893661089792)
=> [Docs] Improve contrast for tips in dark mode

keyboards/alpine65/readme.md, keyboards/pkb65/readme.md
* Allows the documentation user to click through on links.
=> docs: repair malformed links

builddefs/common_rules.mk
This stops a situation where a user could end up flashing oversize firmware soft bricking hardware.
*
=> Remove oversize binaries

builddefs/common_rules.mk, builddefs/message.mk, platforms/avr/platform.mk
1. Remove warning as it just confuses users that is some form of error
* Decided not to add it as a verbose message due to it then introducing duplication plus no one is really going to see it anyway
2. Relocate AVR checks to an AVR specific `.mk` file
* Removes a platform check in a generic file
*
=> Remove 'Firmware size check does not yet support' message

keyboards/inland/mk47/info.json, keyboards/inland/mk47/keymaps/default/keymap.c, keyboards/inland/mk47/keymaps/inland/keymap.c, keyboards/inland/mk47/keymaps/via/keymap.c
- Rename `LAYOUT` to `LAYOUT_planck_mit`
- Enable Community Layout support
- Touch-up keymaps
cc @jonylee1986 (keyboard maintainer)
=> Inland MK47 Community Layout Support

keyboards/input_club/k_type/post_rules.mk, keyboards/input_club/k_type/rules.mk
Fixes some errors that can be seen <https://github.com/qmk/qmk_firmware/pull/22009/checks?check_run_id=16777443187>.
*
=> Fix input_club/k_type when RGB Matrix disabled

quantum/color.h, quantum/led_matrix/led_matrix_types.h, quantum/rgb_matrix/rgb_matrix_types.h, quantum/util.h
A little bit of deduping. Also removed some MSVC-related? packing stuff.
*
=> Move `PACKED` define to util.h

keyboards/clueboard/66_hotswap/gen1/info.json, keyboards/handwired/3dp660/info.json, keyboards/hineybush/h660s/info.json
encompasses 66_* community layouts, where applicable:
- added community_layouts to keyboards
* n/a
=> amend 66_(ansi|iso) community_layouts in keyboards/

docs/pr_checklist.md
As per title.
could maybe also say "and paste the output into info.json", but this is more verbose
None
=> Add reminder about format-json to PR Checklist

keyboards/riot_pad/info.json
Added the `rgb_test` animation to support VIA requirements from QMK.
*
=> Added animation to riot_pad to support VIA

keyboards/dp3000/info.json, keyboards/dp3000/readme.md, keyboards/dp3000/rev1/info.json, keyboards/dp3000/rev1/rules.mk, keyboards/dp3000/rev2/info.json, keyboards/dp3000/rev2/rules.mk, keyboards/dp3000/rules.mk
- Moved the original files to rev1 folder, featuring `rgb_matrix`
- Adding rev2 with different pid, featuring `rgblight`
*
=> add dp3000 rev2 featuring rgblight

docs/feature_rgblight.md
Reverts qmk/qmk_firmware#21483
Superseded by #22106.
=> Revert "Update feature_rgblight.md"

keyboards/jacky_studio/piggy60/rev2/info.json, keyboards/ymdk/id75/info.json, platforms/chibios/bootloader.mk
Avoids the duplication at keyboard level. (Implements same behaviour as `stm32duino`),
*
=> Set default board files for uf2boot bootloader

keyboards/sofle_choc/info.json, keyboards/sofle_choc/keymaps/default/config.h, keyboards/sofle_choc/keymaps/default/keymap.c, keyboards/sofle_choc/keymaps/default/rules.mk, keyboards/sofle_choc/keymaps/via/config.h, keyboards/sofle_choc/keymaps/via/keymap.c, keyboards/sofle_choc/keymaps/via/rules.mk, keyboards/sofle_choc/readme.md, keyboards/sofle_choc/sofle_choc.c
* New hardware variant of the Sofle keyboard (`keyboards/sofle/choc`)
* New default keymap (`keyboards/sofle/keymaps/choc_default`)
* New Via keymap (`keyboards/sofle/keymaps/choc_via`)
=> Sofle Choc hardware variant

builddefs/common_features.mk, docs/reference_info_json.md, drivers/led/issi/is31fl3737-simple.c, drivers/led/issi/is31fl3737-simple.h, drivers/led/issi/is31fl3741-simple.c, drivers/led/issi/is31fl3741-simple.h, quantum/led_matrix/led_matrix.h, quantum/led_matrix/led_matrix_drivers.c
=> is31fl3737/3741: add LED Matrix support

keyboards/strech/soulstone/config.h, keyboards/strech/soulstone/info.json, keyboards/strech/soulstone/keymaps/default/keymap.c, keyboards/strech/soulstone/keymaps/via/keymap.c, keyboards/strech/soulstone/keymaps/via/rules.mk, keyboards/strech/soulstone/readme.md, keyboards/strech/soulstone/rules.mk, keyboards/strech/soulstone/soulstone.c
Add new keyboard `Soulstone`
None
=> Add Soulstone keyboard

docs/cli.md, docs/cli_development.md, docs/coding_conventions_python.md
=> Fix minimum python version references

keyboards/acheron/themis/87h/87h.c, keyboards/acheron/themis/87h/config.h, keyboards/acheron/themis/87h/halconf.h, keyboards/acheron/themis/87h/info.json, keyboards/acheron/themis/87h/keymaps/default/keymap.c, keyboards/acheron/themis/87h/keymaps/via/keymap.c, keyboards/acheron/themis/87h/keymaps/via/rules.mk, keyboards/acheron/themis/87h/mcuconf.h, keyboards/acheron/themis/87htsc/87htsc.c, keyboards/acheron/themis/87htsc/config.h, keyboards/acheron/themis/87htsc/halconf.h, keyboards/acheron/themis/87htsc/info.json, keyboards/acheron/themis/87htsc/keymaps/default/keymap.c, keyboards/acheron/themis/87htsc/keymaps/via/keymap.c, keyboards/acheron/themis/87htsc/keymaps/via/rules.mk, keyboards/acheron/themis/87htsc/mcuconf.h, keyboards/acheron/themis/88htsc/88htsc.c, keyboards/acheron/themis/88htsc/config.h, keyboards/acheron/themis/88htsc/halconf.h, keyboards/acheron/themis/88htsc/info.json, keyboards/acheron/themis/88htsc/keymaps/default/keymap.c, keyboards/acheron/themis/88htsc/keymaps/via/keymap.c, keyboards/acheron/themis/88htsc/keymaps/via/rules.mk, keyboards/acheron/themis/88htsc/mcuconf.h, keyboards/acheron/themis/info.json, keyboards/acheron/themis/readme.md
Adds support for Acheron Themis and its variants.
*
=> Add Acheron Themis and its variants

keyboards/coseyfannitutti/discipline/keymaps/briianpowell/keymap.c
=> Adding BriianPowell Discipline Keyboard Layout Updates

.gitignore, lib/python/qmk/cli/lint.py
Should catch what was included in #22226, and also somewhat prevent it being committed in the first place.
*
=> Flag vial keymaps in 'qmk lint'

docs/feature_tri_layer.md
=> Fix typo in `docs/feature_tri_layer.md`

keyboards/yampad/keymaps/default/keymap.c, keyboards/yampad/keymaps/via/keymap.c, keyboards/yampad/yampad.c
Needed for snprintf when compiling for elite-pi.
*
=> Yampad add missing includes for CONVERT_TO

data/mappings/keyboard_aliases.hjson
```
☒ Keyboard alias keychron/q1 has a target that doesn't exist: keychron/q1v1
☒ Keyboard alias keychron/q4 has a target that doesn't exist: keychron/q4/ansi
```
*
=> Resolve invalid keyboard alias targets

quantum/pointing_device/pointing_device.c
=> Add missing gpio include for pointing motion pin

keyboards/clickety_split/leeloo/leeloo.c, keyboards/clickety_split/leeloo/readme.md, keyboards/clickety_split/leeloo/rev3/config.h, keyboards/clickety_split/leeloo/rev3/info.json, keyboards/clickety_split/leeloo/rev3/rules.mk, keyboards/clickety_split/leeloo/rules.mk
* Added rev3 folder and updated associated configuration files to reflect Leeloo v2.1 PCB updates.
* Removed 8 RGB LEDs on each side, which served as backlighting.
* Added a solderable jumper to bypass unused circuitry.
* Simplified socketing of displays.
* N/A
=> Leeloo v2.1 revision 3 updates.

keyboards/yushakobo/navpad/10/keymaps/via/keymap.c, keyboards/yushakobo/navpad/10/keymaps/via/rules.mk
=> navpad1.0 - enable encoder map

quantum/split_common/split_util.c
Removes checks from within the main loop, locks left configuration to result on init.
Not fully tested yet but thought I'd share for some feedback.
*
=> Modify split config is_keyboard_master/left checks.

quantum/led_matrix/led_matrix.c
These are already being called here https://github.com/qmk/qmk_firmware/blob/d2773c6d67bce73dc3b8bc7922463184304651b1/quantum/led_matrix/led_matrix.c#L395-L397
and
https://github.com/qmk/qmk_firmware/blob/d2773c6d67bce73dc3b8bc7922463184304651b1/quantum/led_matrix/led_matrix.c#L421-L423
*
=> Remove extra led_matrix_indicators_user call

tmk_core/protocol/vusb/vusb.c
No idea how to test this, at least on Windows, since it doesn't seem to send these requests.
*
=> V-USB: Implement `GET_PROTOCOL` and `SET_PROTOCOL` handling

docs/serial_driver.md, docs/ws2812_driver.md
=> Clarify PIO define is optional in docs.

keyboards/eason/aeroboard/info.json
=> Modify bootloader

data/mappings/info_config.hjson
For example 22344 and 22316.
*
=> Flag more VIAL config options in lint

readme.md
=> Removed clueboard link as the website has been offline for some time

keyboards/cannonkeys/is0gr/info.json
PID and VID for the is0GR were swapped in the merged version. Under approval of the maintainer @awkannan I've swapped them to be correct.
*
=> Fix for swapped PID and VID

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, lib/python/qmk/cli/generate/config_h.py
Enable support for the following:
```json
{
"backlight": {
"default": {
"on": true,
"breathing": true,
"brightness": 7
}
},
"rgblight": {
"default": {
"on": true,
"animation": "static_gradient",
"hue": 100,
"sat": 100,
"val": 100,
"speed": 100
}
},
"rgb_matrix": {
"default": {
"on": true,
"animation": "cycle_pinwheel",
"hue": 100,
"sat": 100,
"val": 100,
"speed": 100
}
},
"led_matrix": {
"default": {
"on": true,
"animation": "band_pinwheel",
"val": 100,
"speed": 100
}
}
}
```
* Not a massive fan of the mixing of "brightness" vs "value"
*  already existing with val_steps and max_brightness, but it could be a chance to align to whatever ideal?
* "default" vs "defaults"
* not a fan of  just a "default_" prefix
* no parsing logic for _DEFAULT_MODE
* not really worth the effort?
* …
=> Implement data driven lighting defaults

lib/python/qmk/cli/c2json.py, lib/python/qmk/keymap.py, lib/python/qmk/path.py
* Allow arguments to be lazier 
* just path to keymap.c (only works in tree)
* just `--kb` and `--km`
* or `cd` to keymap folder
* Use established patterns for stdin and file writing
*
=> Improve argument handling of c2json

drivers/led/aw20216s.h, drivers/led/issi/is31fl3218-simple.h, drivers/led/issi/is31fl3218.h, drivers/led/issi/is31fl3731-simple.h, drivers/led/issi/is31fl3731.h, drivers/led/issi/is31fl3733-simple.h, drivers/led/issi/is31fl3733.h, drivers/led/issi/is31fl3736-simple.h, drivers/led/issi/is31fl3736.h, drivers/led/issi/is31fl3737-simple.h, drivers/led/issi/is31fl3737.h, drivers/led/issi/is31fl3741-simple.h, drivers/led/issi/is31fl3741.h, drivers/led/issi/is31flcommon.h, drivers/led/snled27351-simple.h, drivers/led/snled27351.h
=> LED drivers: use `PACKED` define from util.h

docs/feature_rgblight.md
Fix markdown typos in rgblight docs
=> docs(rgblight): fix typos

docs/feature_key_overrides.md
=> Fix typos: key-modifer→key-modifier and interacton→interaction

builddefs/common_rules.mk, platforms/avr/platform.mk, platforms/chibios/platform.mk
Reverts qmk/qmk_firmware#22007
=> Revert "chibios: disable RWX segment warning on newer GNU lds"

docs/feature_backlight.md
As mentioned <https://github.com/qmk/qmk_firmware/pull/21717#discussion_r1317987165>, default value is incorrect, and in updating that, it was noted to also be in the wrong section.
*
=> Move BACKLIGHT_PWM_PERIOD to correct docs section

tmk_core/protocol/vusb/vusb.c
Requires #22323 first. Tested and working on Plaid-Pad.
*
=> V-USB: implement NKRO

users/yanfali_wkl
Folder that was missed by #22544
=> Remove symbolic linked userspace folder

data/mappings/defaults.hjson, data/schemas/keyboard.jsonschema, docs/feature_converters.md, docs/squeezing_avr.md, platforms/chibios/converters/promicro_to_imera/_pin_defs.h, platforms/chibios/converters/promicro_to_imera/converter.mk
This PR adds support for a converter targeting the Imera, a soon-to-be-released microcontroller board using the Pro Micro form factor.
The Imera is quite similar to the [Liatris](https://splitkb.com/products/liatris) already supported by QMK but it includes a [VIK connector](https://github.com/sadekbaroudi/vik), which required pin changes on the Pro Micro interface to free up two analog pins. This unfortunately forced a break from the RP2040 Community Edition standard, requiring this new converter.
N/A
=> Add Imera converter

docs/quantum_painter.md
=> Small QP surface docs update

lib/python/qmk/cli/compile.py
As per title. It's currently documented as available and some manufacturers rely on it for their own CI.
* #22565
=> Fixup compilation with `qmk compile -kb zzz -km all`.

drivers/led/apa102.h
To match the rest of the LED drivers (particularly WS2812). No usages yet but will have in future; related to #22529.
*
=> Add `APA102_LED_COUNT` define

docs/contributing.md, docs/feature_userspace.md, docs/pr_checklist.md
As per [#22485 comment](https://github.com/qmk/qmk_firmware/pull/22485#issuecomment-1817784401). Please do comment if a notice should be added elsewhere.
=> Documentation regarding user code removal/acceptance

drivers/led/issi/is31fl3218-simple.h, drivers/led/issi/is31fl3218.h, drivers/led/issi/is31fl3731-simple.c, drivers/led/issi/is31fl3731-simple.h, drivers/led/issi/is31fl3731.c, drivers/led/issi/is31fl3731.h, drivers/led/issi/is31fl3733-simple.c, drivers/led/issi/is31fl3733-simple.h, drivers/led/issi/is31fl3733.c, drivers/led/issi/is31fl3733.h, drivers/led/issi/is31fl3736-simple.c, drivers/led/issi/is31fl3736-simple.h, drivers/led/issi/is31fl3736.c, drivers/led/issi/is31fl3736.h, drivers/led/issi/is31fl3737-simple.c, drivers/led/issi/is31fl3737-simple.h, drivers/led/issi/is31fl3737.c, drivers/led/issi/is31fl3737.h, drivers/led/issi/is31fl3741-simple.c, drivers/led/issi/is31fl3741-simple.h, drivers/led/issi/is31fl3741.c, drivers/led/issi/is31fl3741.h, drivers/led/snled27351-simple.c, drivers/led/snled27351-simple.h, drivers/led/snled27351.c, drivers/led/snled27351.h, keyboards/input_club/k_type/is31fl3733-dual.c, keyboards/input_club/k_type/is31fl3733-dual.h, keyboards/input_club/k_type/keymaps/andrew-fahmy/config.h
=> LED drivers: refactor page selection

keyboards/helix/rev3_5rows/info.json
As title — current firmware is too large. Will be opening a follow up PR that cleans up much of the legacy code in `helix` directory.
=> Fixup helix/rev3_5rows

quantum/led_matrix/led_matrix.h, quantum/led_matrix/led_matrix_drivers.c, quantum/led_matrix/led_matrix_drivers.h, quantum/rgb_matrix/rgb_matrix.h, quantum/rgb_matrix/rgb_matrix_drivers.c, quantum/rgb_matrix/rgb_matrix_drivers.h
Moving all the driver-related code out of the main `[led|rgb]_matrix.[ch]` files.
*
=> LED/RGB Matrix: add header for drivers

keyboards/anavi/macropad8/keymaps/vlc/keymap.c
Change OLED task function to be boolean and fixed minor inconsistency in formatting.
=> Fix compile error in VLC keymap for Anavi Macropad8

docs/cli_commands.md
I only learnt about this command recently- and to the best of my knowledge it doesn't seem to be documented on docs.qmk.fm
I am very happy to be corrected on the wording of the explanation. 
*  explain qmk migrate a bit
=> [documentation] QMK migrate docs patch

docs/cli.md
For users who are new to terminals/command line interfaces, I thought it would be beneficial to explain what CLI meant.
*
=> Give definition of 'CLI' for new users

keyboards/kikoslab/kl90/config.h, keyboards/kikoslab/kl90/keymaps/via/keymap.c, keyboards/kikoslab/kl90/keymaps/via/rules.mk
Updates the Kikoslab KL90 firmware to properly support encoders configured via "Via"
=> fix(kikoslab/kl90): Fix firmware to support encoder knobs properly

keyboards/cradio/keymaps/default/config.h, keyboards/cradio/keymaps/default/keymap.c
* Reduce copyright blurb
* Change home row mod placing
=> Cradio: update default keymap

keyboards/takashicompany/heavy_left/readme.md, keyboards/takashicompany/radialex/readme.md
=> takashicompany: readme link correction

data/mappings/info_config.hjson, docs/feature_led_matrix.md, keyboards/input_club/ergodox_infinity/config.h, keyboards/input_club/whitefox/config.h, keyboards/keychron/c1_pro/ansi/white/config.h, keyboards/keychron/c2_pro/ansi/white/config.h, keyboards/keychron/s1/ansi/white/config.h, keyboards/terrazzo/config.h, quantum/led_matrix/led_matrix.c
Counterpart for RGB Matrix coming in a separate PR, as it will be much larger.
*
=> Rename `LED_DISABLE_WHEN_USB_SUSPENDED` -> `LED_MATRIX_SLEEP`

keyboards/momokai/aurora/readme.md
=> Add Momokai Aurora Image

keyboards/kumaokobo/kudox/rules.mk, keyboards/kumaokobo/kudox_full/rules.mk, keyboards/kumaokobo/kudox_game/rules.mk, keyboards/kumaokobo/pico/rules.mk
Add prefix for the default folder directive
=> Default folder correction for kumaokobo

keyboards/bastardkb/skeletyl/readme.md
```
❯ qmk compile -kb bastardkb/skeletyl/v2/splinky/v3 -km default
usage: qmk compile [-h] [--compiledb] [-t TARGET] [-c] [-e ENV] [-j PARALLEL] [-n] [-km KEYMAP] [-kb KEYBOARD] [filename]
qmk compile: error: argument -kb/--keyboard: invalid keyboard_folder_or_all value: 'bastardkb/skeletyl/v2/splinky/v3
```
None
I really don't think all of this is necessary.
=> docs(skeletyl): fix readme instructions

keyboards/mechlovin/olly/octagon/config.h
LED config is invalid, so count is not currently generated. Partial revert from 22792.
*
=> Temporary fix for mechlovin/olly/octagon

data/mappings/info_config.hjson, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/info.py
Currently the codegen for the various `_DEFAULT_ON` values is broken.
To distinguish the 2 different output formats, a new type has been added to mapping.
* <https://discord.com/channels/440868230475677696/440868230475677698/1179632393070587925>
=> Generate true/false for _DEFAULT_ON options

drivers/led/issi/is31fl3733.h
=> is31fl3733: fix driver sync backwards compatibility defines

drivers/led/snled27351-mono.c, drivers/led/snled27351-mono.h, drivers/led/snled27351.c, drivers/led/snled27351.h
=> snled27351: change `write_register()` return type to `void`

drivers/led/aw20216s.c, drivers/led/issi/is31fl3741-mono.h, drivers/led/issi/is31fl3746a-mono.c, drivers/led/issi/is31fl3746a-mono.h, drivers/led/issi/is31fl3746a.h, keyboards/input_club/k_type/is31fl3733-dual.c, keyboards/input_club/k_type/is31fl3733-dual.h
=> LED drivers: more formatting

quantum/rgb_matrix/animations/solid_reactive_anim.h
Fading effect is smoother with scale8 function
=> Solid reactive: improve fading effect

docs/feature_rawhid.md
when I was trying to write a simple python script to send messages to the keyboard I had a lot of trouble getting the library linked in the docs to open the device. I eventually found a different python library, [pywinusb](https://pypi.org/project/pywinusb), that was able to handle this far easier. I have added a link to this library to the docs to help save others time if they have issues with the existing one and want to try a different library.
* N/A
=> add pywinusb lib to list of example libs for HID

keyboards/wilba_tech/wt20_h1/config.h, keyboards/wilba_tech/wt20_h1/info.json, keyboards/wilba_tech/wt20_h1/keymaps/default/keymap.c, keyboards/wilba_tech/wt20_h1/keymaps/via/keymap.c, keyboards/wilba_tech/wt20_h1/keymaps/via/rules.mk, keyboards/wilba_tech/wt20_h1/readme.md, keyboards/wilba_tech/wt20_h1/rules.mk
=> Added WT20-H1 (HIBI JUNIOR)

keyboards/redox/rev1/info.json
Fixes typo, whoops.
* https://discord.com/channels/440868230475677696/867530715192885269/1195848522482864261
=> [Keyboard] Fix typo in Redox config

lib/python/qmk/build_targets.py
=> Copy `compile_commands.json` to userspace.

util/install/fedora.sh
=> Workaround for dfu-programmer on Fedora 39

keyboards/40percentclub/ut47/matrix.c, keyboards/amjkeyboard/amj96/matrix.c, keyboards/bioi/bluetooth_custom.c, keyboards/converter/ibm_terminal/matrix.c, keyboards/converter/m0110_usb/m0110.c, keyboards/converter/palm_usb/matrix.c, keyboards/converter/sun_usb/matrix.c, keyboards/handwired/frenchdev/matrix.c, keyboards/ibm/model_m/mschwingen/matrix.c, keyboards/kinesis/alvicstep/matrix.c, keyboards/sirius/unigo66/main.c, quantum/led.c, quantum/logging/debug.h
Long time deprecated, and no point integrating into future logging changes.
*
=> Migrate and remove deprecated debug utils

docs/feature_encoders.md
Reduce copy-paste errors if users are not using specific label names
=> [Doc] Use number indexes for encoder code example

quantum/debounce/asym_eager_defer_pk.c
=> Update asymmetric debounce code comment

tmk_core/protocol/vusb/protocol.c
Partially restructures suspend (where possible) logic to LUFA/ChibiiOS while maintaining as much of the existing code as possible. 
With the logic more uniform, it will facilitate changes such as #14944. Future iterations will head towards the eventual unification of suspend behaviour.
*
=> Align VUSB suspend protocol logic

keyboards/handwired/scottokeebs/scottodeck/info.json, keyboards/handwired/scottokeebs/scottodeck/keymaps/default/keymap.c, keyboards/handwired/scottokeebs/scottodeck/readme.md, keyboards/handwired/scottokeebs/scottodeck/rules.mk
Add the ScottoDeck handwired macropad and default keymap.
*
=> Add ScottoDeck handwired macropad

keyboards/kk/65/info.json
Updated KK65 VID. (I was told creating PR to `master` should be fine since this is a very minor change)
* Prior KK65 VID/PID match that of another keyboard
=> KK65 VID Correction

lib/python/qmk/cli/lint.py
While submitters will continue to ignore the CI status, something is better than nothing.
[Alternative/addition](https://github.com/qmk/qmk_firmware/commit/9efbb2d024bf5e44bb1a8606caadd83f5c8ff45d) for failure at compile time.
*
=> Flag invalid keyboard features during lint

keyboards/boardsource/unicorne/info.json
Add a `LAYOUT` alias to support copying of keymaps from crkbd
=> [unicorne] Add a layout alias

docs/feature_combo.md
=> Fix double code indenting

drivers/led/issi/is31fl3729-mono.c, drivers/led/issi/is31fl3729-mono.h, drivers/led/issi/is31fl3729.c, drivers/led/issi/is31fl3729.h
Followup to #21850, bringing the driver up to par with the others.
* Adjusted spread spectrum define names
* Removed PWM register offset (#22897)
* Stored I2C addresses in an array (#22975)
* Added pullup/down resistor defines & config
* Added SDB pin support (#23058)
@HorrorTroll, would appreciate some testing :)
*
=> IS31FL3729 updates

data/schemas/keyboard.jsonschema, keyboards/moky/moky88/info.json
Just noticed these were missing. Also did some minor formatting and fixes so that it passes JSON lint.
*
=> Add LED/RGB Matrix drivers to info.json schema

util/uf2conv.py
Picking up https://github.com/microsoft/uf2/commit/a30269c4a54757c1103f05240c561405128ae91a
* Fixes #23160
=> Merge upstream uf2conv.py changes

docs/driver_installation_zadig.md, util/drivers.txt
https://github.com/qmk/qmk_toolbox/releases/tag/0.3.0
*
=> Update Atmel DFU driver assignments for dfu-programmer 1.x

keyboards/qwertykeys/qk100/ansi/info.json, keyboards/qwertykeys/qk100/ansi/keymaps/via/rules.mk, keyboards/qwertykeys/qk100/info.json
=> Fixup qk100 (firmware size)

keyboards/geistmaschine/geist/info.json, keyboards/geistmaschine/geist/keymaps/default/keymap.c, keyboards/geistmaschine/geist/keymaps/via/keymap.c
This PR adds mousekey support to geistmaschine geist, after customers asked for it. It also fixes an issue with wrong keymaps on non-split backspace on multilayout keymaps.
* geistmaschine/geist: Missing mousekeys support
* geistmaschine/geist: Keymap error
=> geistmaschine/geist: enable mousekey, fix issues in default/via keymap

platforms/chibios/chibios_config.h, platforms/chibios/drivers/uart_sio.c, platforms/chibios/platform.mk
For now the logic has been reverted to match the existing i2c logic.
On develop, this will be reworked further at a later date. Fixing the makefile logic, and refactoring existing items like i2c to follow the new define.
* <https://discord.com/channels/440868230475677696/867530715192885269/1212391432459915305>
=> Workaround for uart makefile issues

keyboards/custommk/cmk11/config.h, keyboards/custommk/cmk11/halconf.h, keyboards/custommk/cmk11/info.json, keyboards/custommk/cmk11/keymaps/default/keymap.c, keyboards/custommk/cmk11/keymaps/via/config.h, keyboards/custommk/cmk11/keymaps/via/keymap.c, keyboards/custommk/cmk11/keymaps/via/rules.mk, keyboards/custommk/cmk11/mcuconf.h, keyboards/custommk/cmk11/readme.md, keyboards/custommk/cmk11/rules.mk
=> Adding CMK11

keyboards/idobao/id61/keymaps/idobao/keymap.c, keyboards/idobao/id63/keymaps/idobao/keymap.c, keyboards/idobao/id87/v2/keymaps/idobao/keymap.c
=> Fixes for idobao vendor keymaps

docs/feature_tri_layer.md
=> Update feature_tri_layer.md - typo

lib/python/qmk/cli/new/keyboard.py
Might help somewhat for those PRs were the submitter has failed to rename the layout after adding/removing keys.
*
=> `qmk new-keyboard` - detach community layout when selecting "none of the above"

docs/getting_started_introduction.md
Modify a sentence of the document 'getting_started_introduction.md' : 
1. change 'keyboard' to 'keyboards'. 
2. add 'its subfolder' in front of 'handwired'.
*
=> Modify a sentence of document 'getting_started_introduction.md'

docs/pr_checklist.md
Some small changes to `pr_checklist.md` discouraging frequent branch updating for sake of CI, remove Imgur suffix requirement as they seem to be deprecated by Imgur, and some other things.
=> Updates to PR Checklist

keyboards/helix/rev3_4rows/keymaps/default/oled_display.c, keyboards/helix/rev3_4rows/keymaps/via/oled_display.c, keyboards/helix/rev3_5rows/keymaps/default/oled_display.c, keyboards/helix/rev3_5rows/keymaps/via/oled_display.c
Constantly failing with a few bytes either way of oversized.
Removing snprintf gives us about 1k extra to play with.
*
=> Reduce firmware size of helix/rev3

keyboards/bajjak/bajjak.c, keyboards/bajjak/matrix.c, keyboards/dc01/left/matrix.c, keyboards/ergodox_ez/ergodox_ez.c, keyboards/ergodox_ez/matrix.c, keyboards/ferris/0_2/matrix.c, keyboards/gboards/ergotaco/ergotaco.c, keyboards/gboards/ergotaco/matrix.c, keyboards/gboards/georgi/georgi.c, keyboards/gboards/georgi/matrix.c, keyboards/gboards/gergo/gergo.c, keyboards/gboards/gergo/matrix.c, keyboards/gboards/gergoplex/gergoplex.c, keyboards/gboards/gergoplex/matrix.c, keyboards/handwired/frenchdev/frenchdev.c, keyboards/handwired/frenchdev/matrix.c, keyboards/handwired/pterodactyl/matrix.c, keyboards/hotdox/left.c, keyboards/system76/launch_1/usb_mux.c, platforms/chibios/drivers/i2c_master.c
`i2c_writeReg` -> `i2c_write_register`
`i2c_readReg` -> `i2c_read_register`
*
=> Update I2C API usage in keyboard code

drivers/gpio/mcp23018.c, drivers/gpio/mcp23018.h, drivers/gpio/pca9505.c, drivers/gpio/pca9505.h, drivers/gpio/pca9555.c, drivers/gpio/pca9555.h, keyboards/geistmaschine/macropod/matrix.c, keyboards/ktec/ergodone/matrix.c, keyboards/mechwild/sugarglider/matrix.c, keyboards/moon/matrix.c, keyboards/switchplate/southpaw_65/matrix.c, keyboards/viktus/sp111/matrix.c, keyboards/xiudi/xd84/matrix.c, keyboards/xiudi/xd96/matrix.c
=> Update GPIO expander API naming

keyboards/merge/um80/keymaps/default/keymap.c
Building oversize in Configurator - keymap needs updating there too, this is to prevent it getting accidentally reverted.
*
=> merge/um80: remove pointless empty layers

keyboards/atreus/feather/keyboard.json, keyboards/cannonkeys/lib/satisfaction75/satisfaction_encoder.c, keyboards/cipulot/ec_typek/ec_typek.c, keyboards/handwired/symmetric70_proto/matrix_debug/matrix.c, keyboards/handwired/symmetric70_proto/matrix_fast/gpio_extr.h, keyboards/handwired/symmetric70_proto/matrix_fast/matrix.c, keyboards/handwired/symmetric70_proto/matrix_fast/matrix_extension_74hc15x.c
<https://github.com/qmk/qmk_firmware/pull/23405/checks?check_run_id=23385807776>
*
=> Fix failing keyboards on develop

keyboards/handwired/technicpad/keymaps/default/keymap.json, keyboards/handwired/technicpad/keymaps/via/keymap.json, keyboards/mechwild/bb40/keymaps/default/keymap.json
Status page has it failing with `Unknown keyboard`.
*
=> handwired/technicpad: fix `keyboard` in keymaps

keyboards/tweetydabird/lotus58/info.json
Updates to schema will follow separately, as its currently not producing a decent error.
*
=> "features.split" is not a valid key

builddefs/common_features.mk, quantum/process_keycode/process_backlight.c, quantum/process_keycode/process_led_matrix.c, quantum/process_keycode/process_led_matrix.h, quantum/quantum.c
The first puzzle piece. Keycodes are still shared; new ones for LED Matrix will come in the following PR.
*
=> Separate keycode handling for LED Matrix and Backlight

keyboards/cannonkeys/is0gr/info.json
The PID and VID on Is0gr are swapped in the QMK repo compared to the many units that already shipped.
In order to ensure the best user experience - we'd like to standardize on the de-facto units that are out there already.
This was my mistake in changing vid/pid.
*
=> Swap PID and VID on is0gr in QMK

keyboards/hs60/v1/rules.mk, keyboards/hs60/v2/ansi/rules.mk, keyboards/hs60/v2/hhkb/rules.mk, keyboards/hs60/v2/iso/rules.mk, keyboards/keebwerk/mega/ansi/rules.mk, keyboards/novelkeys/nk65/rules.mk, keyboards/novelkeys/nk87/rules.mk, keyboards/spaceholdings/nebula12/rules.mk, keyboards/spaceholdings/nebula68/rules.mk, keyboards/wilba_tech/rama_works_kara/rules.mk, keyboards/wilba_tech/rama_works_koyu/rules.mk, keyboards/wilba_tech/rama_works_m10_c/rules.mk, keyboards/wilba_tech/rama_works_m50_a/rules.mk, keyboards/wilba_tech/rama_works_m60_a/rules.mk, keyboards/wilba_tech/rama_works_m65_b/rules.mk, keyboards/wilba_tech/rama_works_m65_bx/rules.mk, keyboards/wilba_tech/rama_works_m6_a/rules.mk, keyboards/wilba_tech/rama_works_m6_b/rules.mk, keyboards/wilba_tech/wt60_b/rules.mk, keyboards/wilba_tech/wt60_bx/rules.mk, keyboards/wilba_tech/wt60_c/rules.mk, keyboards/wilba_tech/zeal60/rules.mk, keyboards/wilba_tech/zeal65/rules.mk, keyboards/xelus/dawn60/rev1/rules.mk, keyboards/xelus/dawn60/rev1_qmk/rules.mk
Manipulating `OPT_DEFS` is less than ideal, as it prevents the functionality from being disabled and would bypass any DD parsing logic.
*
=> Align NO_SUSPEND_POWER_DOWN keyboard config

keyboards/nullbitsco/snap/keymaps/bongo_reactive/config.h
New breaking changes, new size reduction PR to eek a bit more life out of AVR keymaps. This one is just a few bytes over on our CI build, and removing the snake mode frees up a few 100B.
* N/A
=> nullbitsco/snap: once again reduce size of bongo_reactive

keyboards/jlw/bruce_the_keyboard/info.json, keyboards/jlw/bruce_the_keyboard/keymaps/default/keymap.c, keyboards/jlw/bruce_the_keyboard/keymaps/default/rules.mk, keyboards/jlw/bruce_the_keyboard/readme.md, keyboards/jlw/bruce_the_keyboard/rules.mk
This is a PR to add the keyboard "Bruce the Keyboard" to QMK.  There is also a PR for its brother, "Bruce le Clavier" (#23640). The two boards are very similar, but Bruce the Keyboard is a rectangular 4.25u tall by 10u wide column stagger board, whereas Bruce le Clavier is a unibody split version of Bruce the Keyboard with a center key/encoder option.
Thank you for taking the time to review this submission (and/or its brother).
*
=> add Bruce the keyboard

.github/workflows/ci_build_major_branch.yml
This should fix up CI, as far as the repacking step is concerned.
=> [CI] Allow secrets to propagate from parent to child workflow.

.github/workflows/ci_build_major_branch.yml
More whack-a-mole with CI runs.
=> [CI] Use existing repo variables instead

.github/workflows/ci_build_major_branch.yml
Hopefully final change?
https://github.com/andstor/file-existence-action?tab=readme-ov-file#outputs
=> [CI] Fail workflow if there were build failures

lib/python/qmk/search.py
```
Ψ Filtering on condition: absent(rgblight...
Ψ Filtering on condition: absent(rgb_matrix...
```
*
=> `qmk find`: Fix typo in filter logging

docs/__capabilities.md, docs/__capabilities_inc.md
Adds to 23428 to cover additional usages from non master branches.
*
=> Add embed to docs capabilities

docs/squeezing_avr.md
* Note AVR's flash space
* Include guards for magic functions
* Remove mention of silicon shortage
* Demote an unavailable controller
=> [Doc] Revise squeezing AVR

quantum/led_matrix/led_matrix.c, quantum/rgb_matrix/rgb_matrix.c, quantum/rgb_matrix/rgb_matrix_drivers.c
=> Remove useless `LED/RGB_MATRIX_ENABLE` ifdefs

keyboards/handwired/dygma/raise/ansi/keyboard.json, keyboards/handwired/dygma/raise/info.json, keyboards/handwired/dygma/raise/iso/keyboard.json, keyboards/handwired/dygma/raise/rules.mk, keyboards/handwired/symmetric70_proto/promicro/info.json, keyboards/handwired/symmetric70_proto/promicro/rules.mk, keyboards/handwired/symmetric70_proto/proton_c/info.json, keyboards/handwired/symmetric70_proto/proton_c/rules.mk, keyboards/lazydesigners/dimple/ortho/rules.mk, keyboards/lazydesigners/dimple/staggered/rev2/rules.mk, keyboards/lazydesigners/dimple/staggered/rev3/rules.mk, keyboards/sirius/uni660/rev2/ansi/keyboard.json, keyboards/sirius/uni660/rev2/iso/keyboard.json, keyboards/sirius/uni660/rev2/rules.mk
Converts `rules.mk` entries to data-driven where applicable.
=> Miscellaneous Data-Driven Keyboard Conversions

util/install/macos.sh
The `--ignore-pinned` flag is no longer a thing; it was deprecated in https://github.com/Homebrew/brew/pull/16301 and completely disabled just a few days ago. Its behaviour is now the default.
*
=> macOS install script: remove `brew upgrade --ignore-pinned`

keyboards/vertex/t75/keyboard.json
KB name change to Part.1-75-HS
KB name change to Part.1-75-HS
*
=> KB name change to Part.1-75-HS

platforms/chibios/boards/GENERIC_STM32_G431XB/configs/mcuconf.h, platforms/chibios/boards/GENERIC_STM32_L432XC/configs/mcuconf.h
=> Workaround for broken ChibiOS startup

.github/workflows/ci_build_major_branch_keymap.yml
=> Decrease CPU count by one to try and stop GHA from killing runners.

docs/index.md
Previously required custom css. Updated to align better with current theme. 
*
=> [docs] Update "Get Started" blocks

docs/__capabilities.md, docs/feature_digitizer.md, docs/feature_unicode.md
Randomly clicked on the Digitizer page to see how the API sections hold up and noticed this.
*
=> [docs] Fix old anchor IDs

builddefs/docsgen/.vitepress/theme/custom.css, docs/cli_development.md, docs/driver_installation_zadig.md, docs/feature_sequencer.md, docs/isp_flashing_guide.md, docs/newbs.md, docs/newbs_building_firmware_workflow.md
Changes to...
* Use more screen width
* Slightly larger icon
* less rounded `<kbd>` on large font sizes
Also,
* misc md fixes spotted while testing
*
=> Docs theme updates

platforms/chibios/boards/common/ld/STM32F405xG_tinyuf2.ld
I've seen a couple other (besides myself) using tinyuf2 with the f405, so might as well add it.
=> Add STM32F405RG ld script for tinyuf2

keyboards/mt/mt84/config.h, keyboards/mt/mt84/keyboard.json, keyboards/mt/mt84/keymaps/default/keymap.c, keyboards/mt/mt84/keymaps/via/keymap.c, keyboards/mt/mt84/mt84.c
* Remove a default RGB matrix effect because #23881 will cause the via keymap to exceed flash size.
* Fix license headers.
=> Fixup mt/mt84

docs/features/tri_layer.md
Quote at the end of the description was most likely meant to be a period.
=> Fix Tri-Layer Keycode Descriptions

keyboards/keebio/iris/keymaps/default/keymap.json, keyboards/keebio/irispad/keymaps/default/keymap.json, keyboards/keebio/irispad/keymaps/via/keymap.json
Status page shows `Exception while compiling keebio/iris/rev1: KeyError` for all revisions of this board.
*
=> Fix Iris/Irispad keymaps

platforms/chibios/drivers/eeprom/eeprom_stm32_L0_L1.h
One more VIA reference removed from core.
*
=> Decouple VIA from STM32 L0/L1 EEPROM implementation

docs/features/led_matrix.md, docs/features/rgb_matrix.md
Followup to #23902, apparently I missed these.
Presumably #23908 will apply here and might pick up more stuff.
*
=> Fix nonunique anchors

docs/configurator_step_by_step.md
Aligns to the current process, detailed in the issue templates <https://github.com/qmk/qmk_firmware/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml>
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
Your best bet is to take the initiative, add support, then submit a PR yourself.
*
=> Remove suggestion of creating issues for unsupported keyboards.

keyboards/keychron/q4/info.json
As title. Was somehow missed during the process of https://github.com/qmk/qmk_firmware/pull/21996. 
This is coming from a user over in the Keychron Discord who noticed that the dip switch wasn't working properly when compiled from either `master` or `develop`.
* N/A
=> Add `enabled": true` rule for "dip_switch" for Keychron Q4

lib/python/qmk/util.py
Should help with CI runs. Was using python 3.11 functions, but CI is 3.9.
=> [CLI] Older python compat.

keyboards/ergodox_ez/base/keyboard.json
=> `ergodox_ez/base`: Add missing `features` object

data/mappings/info_rules.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md
* Additional settings will follow separately
*
=> Implement data driven serial driver

readme.md
Update docs system, since it's been switched over.
*
=> Update what's powering QMK docs

lib/python/qmk/importers.py
Was missed in the `rgblight.pin` to `ws2812.pin` and `rgblight.animations.all` changes.
*
=> Fix 'qmk import-kbfirmware' WS2812 config

lib/python/qmk/cli/userspace/path.py
=> Fix docker_cmd.sh when userspace is not configured

keyboards/custommk/elysian/config.h, keyboards/custommk/elysian/halconf.h, keyboards/custommk/elysian/keyboard.json, keyboards/custommk/elysian/keymaps/default/keymap.c, keyboards/custommk/elysian/keymaps/default/rules.mk, keyboards/custommk/elysian/keymaps/via/config.h, keyboards/custommk/elysian/keymaps/via/keymap.c, keyboards/custommk/elysian/keymaps/via/rules.mk, keyboards/custommk/elysian/mcuconf.h, keyboards/custommk/elysian/readme.md
=> Adding Elysian

keyboards/clueboard/card/keyboard.json
```
⚠ clueboard/card: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
*
=> `clueboard/card`: Swap layout and alias

keyboards/tzarc/djinn/info.json, keyboards/tzarc/djinn/keymaps/default/keymap.c, keyboards/tzarc/djinn/keymaps/via/keymap.c
```
⚠ tzarc/djinn/rev1: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ tzarc/djinn/rev2: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
From what I can tell this board has only one layout, which does not match any existing community layout.
*
=> `tzarc/djinn`: adjust layout name

keyboards/ez_maker/directpins/promicro/keyboard.json, keyboards/ez_maker/directpins/promicro/keymaps/default/keymap.json, keyboards/ez_maker/directpins/proton_c/keyboard.json, keyboards/ez_maker/directpins/proton_c/keymaps/default/keymap.json, keyboards/ez_maker/directpins/rp2040/keyboard.json, keyboards/ez_maker/directpins/rp2040/keymaps/default/keymap.json, keyboards/ez_maker/directpins/teensy_2/keyboard.json, keyboards/ez_maker/directpins/teensy_2/keymaps/default/keymap.json, keyboards/ez_maker/directpins/teensy_2pp/keyboard.json, keyboards/ez_maker/directpins/teensy_2pp/keymaps/default/keymap.json, keyboards/ez_maker/directpins/teensy_32/keyboard.json, keyboards/ez_maker/directpins/teensy_32/keymaps/default/keymap.json, keyboards/ez_maker/directpins/teensy_lc/keyboard.json, keyboards/ez_maker/directpins/teensy_lc/keymaps/default/keymap.json
```
⚠ ez_maker/directpins/promicro: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ ez_maker/directpins/proton_c: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ ez_maker/directpins/rp2040: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ ez_maker/directpins/teensy_2: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ ez_maker/directpins/teensy_2pp: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ ez_maker/directpins/teensy_32: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ ez_maker/directpins/teensy_lc: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
*
=> `ez_maker`: adjust layout names

keyboards/nullbitsco/snap/snap.c, keyboards/nullbitsco/snap/snap.h
* Not used by any in tree keymap
* Not implemented correctly
* VIA custom keycode require kb block
* KB level keycodes should not be using the user block
* Implement shutdown logic without re-implementing `QK_BOOT`
*
=> Remove custom keycodes from nullbitsco/snap

keyboards/ploopyco/readme.md
I noticed a broken link and fixed it.
*
=> Fix ploopy Adept/Madromys link

docs/features/encoders.md, docs/features/split_keyboard.md, drivers/encoder/encoder_quadrature.c, keyboards/dailycraft/wings42/rev2/keymaps/via/config.h, keyboards/handwired/sick68/keymaps/via/config.h, keyboards/kapcave/gskt00/keymaps/default-poly/config.h, keyboards/pica40/rev2/rev2.c, keyboards/ploopyco/mouse/config.h, keyboards/ploopyco/ploopyco.c, keyboards/ploopyco/trackball/config.h, keyboards/ploopyco/trackball_mini/config.h, keyboards/ploopyco/trackball_thumb/config.h, keyboards/rgbkb/sol/keymaps/default/keymap.c, keyboards/rgbkb/sol/rev2/config.h, keyboards/terrazzo/readme.md, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/info.py, quantum/encoder.h, quantum/encoder/tests/config_mock.h, quantum/encoder/tests/config_mock_split_left_eq_right.h, quantum/encoder/tests/config_mock_split_left_gt_right.h, quantum/encoder/tests/config_mock_split_left_lt_right.h, quantum/encoder/tests/config_mock_split_no_left.h, quantum/encoder/tests/config_mock_split_no_right.h, quantum/encoder/tests/config_mock_split_role.h
This is really the only place where pins are referred to as "pads". Since most of the encoder config has been moved to data driven at this point there is not much to update now.
*
=> Rename encoder pins defines

keyboards/dc01/arrow/keyboard.json, keyboards/dc01/arrow/keymaps/default/keymap.c, keyboards/dc01/arrow/keymaps/via/keymap.c
```
⚠ dc01/arrow: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
This is the nav (arrow) cluster module for the DC01. There are no other possible layouts.
*
=> `dc01/arrow`: fix layout name

keyboards/handwired/tkk/keyboard.json, keyboards/handwired/tkk/keymaps/default/keymap.c
```
⚠ handwired/tkk: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
This is a simple ten-key board, with only one layout.
*
=> `handwired/tkk`: fix layout name

keyboards/kbdfans/baguette66/rgb/keyboard.json, keyboards/kbdfans/baguette66/rgb/keymaps/default/keymap.c, keyboards/kbdfans/baguette66/rgb/keymaps/via/keymap.c, keyboards/kbdfans/baguette66/soldered/keyboard.json, keyboards/kbdfans/baguette66/soldered/keymaps/default/keymap.c, keyboards/kbdfans/baguette66/soldered/keymaps/via/keymap.c
```
⚠ kbdfans/baguette66/rgb: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
⚠ kbdfans/baguette66/soldered: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
From this GH groupbuy thread for the board:
https://geekhack.org/index.php?topic=114425.0
It appears to specify a "fixed layout" for both the hotswap and soldered versions. However this layout does not quite match the existing 66% community layouts or anything in the vicinity.
*
=> `kbdfans/baguette66`: fix layout name

quantum/keymap_introspection.c, quantum/keymap_introspection.h, quantum/process_keycode/process_tap_dance.c, quantum/process_keycode/process_tap_dance.h, tests/tap_dance/examples.c, tests/tap_dance/tap_dance_layers/test.mk, tests/tap_dance/test.mk
Adding introspection shims for tap dances.
=> Tap dance introspection

builddefs/docsgen/.vitepress/config.mts
=> [docs] Fixup home link.

keyboards/ano/keyboard.json, keyboards/ano/keymaps/default/keymap.c
```
⚠ ano: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
Can't find any information on this board. Looks like a one-off (possibly handwired), and readme seems to imply a fixed layout, so that's what I'm going with.
CC @sauvehoo
*
=> `ano`: fix layout name

keyboards/kakunpc/rabbit_capture_plan/keymaps/default/keymap.c
=> `kakunpc/rabbit_capture_plan`: update keymap layout name

keyboards/aeboards/ext65/rev3/rev3.c, keyboards/clueboard/2x1800/2021/2021.c, keyboards/enviousdesign/commissions/mini1800/mini1800.c, keyboards/exclusive/e6_rgb/e6_rgb.c, keyboards/handwired/selene/selene.c, keyboards/inett_studio/sqx/hotswap/hotswap.c, keyboards/inett_studio/sqx/universal/universal.c, keyboards/mechlovin/adelais/rgb_led/rev2/rev2.c, keyboards/mechlovin/hannah60rgb/rev2/rev2.c, keyboards/mechlovin/kay65/kay65.c, keyboards/mechlovin/zed65/no_backlight/wearhaus66/wearhaus66.c, keyboards/omnikeyish/omnikeyish.c, keyboards/projectd/75/ansi/ansi.c, keyboards/yandrstudio/nz64/nz64.c
Various fixes for keyboards not implementing callbacks correctly.
*
=> Various fixes for keyboards not implementing callbacks correctly

.github/workflows/ci_build_major_branch.yml, .gitignore, util/ci/firmware_list_generator.py, util/ci/templates/index.html.j2
`index.html` is great for humans, bad for downstream projects that want to consume the available firmware files.
*
=> Add json index of files to CI uploads

.github/workflows/ci_build_major_branch.yml
As per title. As discussed on Discord.
=> [CI] Remove `via` keymap builds.

keyboards/mechwild/bbpad/keymaps/default/keymap.json
Failing on status page.
```
☒ Invalid keyboard: mechwild/bbpad
```
*
=> `mechwild/bbpad`: fix build

keyboards/argyle/matrix.c, keyboards/gmmk/numpad/matrix.c, keyboards/halfcliff/matrix.c, keyboards/handwired/symmetric70_proto/matrix_debug/matrix.c, keyboards/keychron/c2_pro/matrix.c, keyboards/keychron/q10/matrix.c, keyboards/keychron/q12/matrix.c, keyboards/keychron/q1v2/matrix.c, keyboards/keychron/q3/matrix.c, keyboards/keychron/q5/matrix.c, keyboards/keychron/q6/matrix.c, keyboards/keychron/q65/matrix.c, keyboards/keychron/v1/matrix.c, keyboards/keychron/v10/matrix.c, keyboards/keychron/v3/matrix.c, keyboards/keychron/v5/matrix.c, keyboards/keychron/v6/matrix.c, keyboards/rate/pistachio_pro/matrix.c, keyboards/work_louder/micro/matrix.c, quantum/matrix.c
=> Update atomic GPIO macros in keyboard custom matrix

keyboards/checkerboards/axon40/keyboard.json, keyboards/checkerboards/axon40/keymaps/default/keymap.c, keyboards/checkerboards/axon40/keymaps/via/keymap.c
```
⚠ checkerboards/axon40: "LAYOUT_all" should be "LAYOUT" unless additional layouts are provided.
```
Cannot find anything at all on this board - it may possibly be vaporware. Assuming fixed layout for now. If @npspears has any input we can fix it up in a followup PR.
*
=> `checkerboards/axon40`: adjust layout name

lib/python/qmk/flashers.py
Updates code to ensure strings are used.
* https://discord.com/channels/440868230475677696/867530222407778344/1262798112792117400
=> Avoid path issues with `qmk flash` on Windows

keyboards/amjkeyboard/amj60/keyboard.json
```
* The firmware size is approaching the maximum - 28252/28672 (98%, 420 bytes free)
```
*
=> `amjkeyboard/amj60`: reduce firmware size

keyboards/vertex/angler2/keyboard.json
```
* The firmware size is approaching the maximum - 28372/28672 (98%, 300 bytes free)
```
*
=> `vertex/angler2`: reduce firmware size

keyboards/clueboard/66/rev3/keyboard.json
```
* The firmware size is approaching the maximum - 28142/28672 (98%, 530 bytes free)
```
*
=> `clueboard/66/rev3`: reduce firmware size

keyboards/handwired/tractyl_manuform/5x6_right/arduinomicro/keyboard.json
```
* The firmware size is approaching the maximum - 28334/28672 (98%, 338 bytes free)
```
*
=> `handwired/tractyl_manuform/5x6_right/arduinomicro`: reduce size

keyboards/mechlovin/delphine/rgb_led/keyboard.json
```
* The firmware size is approaching the maximum - 28240/28672 (98%, 432 bytes free)
```
*
=> `mechlovin/delphine/rgb_led`: reduce size

keyboards/dailycraft/claw44/keymaps/oled/config.h, keyboards/handwired/dactyl_minidox/keymaps/dlford/rules.mk, keyboards/jian/keymaps/left_hand/keymap.c, keyboards/sofle/keymaps/rgb_default/config.h
Unrelated to the PR but needs fixing nonetheless.
*
=> Fix build failures noticed in #24163 CI log.

keyboards/handwired/hnah108/keyboard.json
```
* The firmware size is approaching the maximum - 27720/28672 (96%, 952 bytes free)
```
*
=> `handwired/hnah108`: reduce firmware size

keyboards/doro67/rgb/keyboard.json
```
* The firmware size is approaching the maximum - 27786/28672 (96%, 886 bytes free)
```
*
=> `doro67/rgb`: reduce firmware size

keyboards/rubi/keyboard.json
```
* The firmware size is approaching the maximum - 27868/28672 (97%, 804 bytes free)
```
*
=> `rubi`: reduce firmware size

keyboards/melgeek/mojo68/rev1/keyboard.json
```
* The firmware size is approaching the maximum - 28230/28672 (98%, 442 bytes free)
```
*
=> `melgeek/mojo68/rev1`: reduce firmware size

docs/drivers/serial.md
=> [docs] update serial.md

keyboards/kingly_keys/ave/ortho/keyboard.json, keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c, keyboards/kingly_keys/ave/staggered/keyboard.json, keyboards/kingly_keys/ave/staggered/keymaps/default/keymap.c
```
⚠ kingly_keys/ave/staggered: Layout "LAYOUT_staggered_big_boy" should not contain name of keyboard.
⚠ kingly_keys/ave/staggered: Layout "LAYOUT_staggered" should not contain name of keyboard.
```
No warnings for the ortho layouts; IMO there probably ought to be some since they are not tagged as community layouts.
*
=> `kingly_keys/ave`: adjust layout names

quantum/rgb_matrix/animations/pixel_fractal_anim.h
Refactor effect to account for LED flags
* Fixes #23850
=> Check LED flags for Pixel Fractal effect

.github/workflows/auto_approve.yml
Fork updates to...
* use node20 to avoid errors in log
* implement "safe_files" as a better way to limit when PRs are auto approved to run workflows
The aim is to PR these changes but that could take time to land and actually be usable. 
*
=> Update to automatic-approve-action fork

keyboards/cipulot/ec_60x/keymaps/via/config.h
While doing some testing I realized that the amount of layout options needed to have 2 bytes instead of 1. This PR fixes it.
*
=> Fix for layout options not being applied

lib/python/qmk/keymap.py, lib/python/qmk/tests/test_cli_commands.py, lib/python/qmk/tests/test_qmk_keymap.py
Removed extraneous newline in keymap C template, and changed some tabs to spaces to avoid a lint warning.
*
=> Small tweaks to keymap generation

builddefs/build_keyboard.mk
As per title. Came from #22887.
=> Remove debugging prints.

quantum/rgb_matrix/animations/riverflow_anim.h
Check for LED flags at the start of loop to skip early
=> Refactor riverflow RGB matrix loop

.github/ISSUE_TEMPLATE/config.yml, docs/breaking_changes_instructions.md, docs/contributing.md, docs/custom_quantum_functions.md, docs/faq_general.md, docs/hand_wire.md, docs/index.md, docs/newbs_flashing.md, docs/pr_checklist.md, docs/support.md, lib/python/qmk/cli/doctor/main.py, readme.md
Update to consistently use vanity URL.
*
=> Update Discord URL

platforms/chibios/mcu_selection.mk
Change introduced in #21282 is no longer required.
*
=> Default STM32G431 back to wear_leveling EFL driver

docs/porting_your_keyboard_to_qmk.md
And no, i'm not trying to add `.md` to something....
*
=> Fix dead link in porting_your_keyboard_to_qmk.md

.gitignore
Aligns with logic currently used for `vial` keymaps.
*
=> Add via keymaps to gitignore

docs/features/tap_dance.md
=> fixed spelling errors in example 4

docs/breaking_changes.md
=> Update next breaking changes date

platforms/chibios/drivers/ws2812_spi.c
Discovered during testing for #24364. Thanks to @sigprof for pointing this out.
*
=> Fix RGBW for WS2812 SPI driver

platforms/chibios/boards/common/ld/STM32F401xC.ld, platforms/chibios/boards/common/ld/STM32F401xC_tinyuf2.ld, platforms/chibios/boards/common/ld/STM32F401xE.ld, platforms/chibios/boards/common/ld/STM32F401xE_tinyuf2.ld, platforms/chibios/boards/common/ld/STM32F411xC.ld, platforms/chibios/boards/common/ld/STM32F411xC_tinyuf2.ld, platforms/chibios/boards/common/ld/STM32F411xE.ld, platforms/chibios/boards/common/ld/STM32F411xE_tinyuf2.ld, platforms/chibios/boards/common/ld/stm32f4xx_common.ld, platforms/chibios/boards/common/ld/stm32f4xx_tinyuf2_common.ld
Unify all STM32F4XX linker files, so it will be easier to edit later.
Tested the changes in STeMCell.
*
=> Refactor F4 ld files to use common files

keyboards/cipulot/ec_60x/keyboard.json
No idea how this slipped through, but the PCB has 19 LEDs and not 22. This fixes it.
*
=> Update EC60X LED count

drivers/lcd/st7565.c
=> input_club/ergodox_infinity ST7565 call spi_stop

.github/workflows/docs.yml
Reverts qmk/qmk_firmware#24446
=> Revert "Bump JamesIves/github-pages-deploy-action from 4.6.4 to 4.6.6"

keyboards/pierce/config.h
Add necessary PS2 configuration settings for PS/2 mouse support in config.h
*
=> add USART configuration to config.h for PS/2 mouse support

keyboards/janus/config.h, keyboards/janus/readme.md
Update Janus keyboard firmware configuration to use `EE_HANDS` for split keyboard handedness detection.
Fixes an issue reported on the Janus keyboard repository: https://github.com/skarrmann/janus/issues/1
=> Update Janus keyboard firmware to use EE_HANDS

keyboards/novelkeys/nk_classic_tkl/keymaps/default/keymap.c, keyboards/novelkeys/nk_classic_tkl_iso/keymaps/default/keymap.c
=> Fix indicator code for NK classics

keyboards/mykeyclub/jris65/keymaps/default/keymap.json
```
Exception while compiling mykeyclub/jris65/hotswap: KeyError
```
CC @sizezero
*
=> `mykeyclub/jris65/hotswap`: fix keymap

keyboards/blackplum/keymaps/default/keymap.c
No value in duplication of core. Also quick tidy of layer IDs while touching the file.
*
=> Fix duplication of core `GU_TOGG` keycode

docs/features/combo.md, quantum/process_keycode/process_combo.c
* Use combo_index for consistency
* Update documentation examples
* Add header guards to examples
=> Update combo user function variable

keyboards/horrortroll/nyx/rev1/lib/startup_swirl_anim.h
=> horrortroll/nyx/rev1: Fix compilation of custom RGB effect

quantum/rgblight/rgblight.c
Just for fun. The animation now cycles through all combinations of RGB, instead of just each channel individually, and also respects `UG_VALU`/`UG_VALD` rather than simply using `RGBLIGHT_LIMIT_VAL`.
|Binary|Colour                |
|------|----------------------|
|001   |Red                   |
|010   |Green                 |
|011   |Yellow (Red+Green)    |
|100   |Blue                  |
|101   |Pink (Red+Blue)       |
|110   |Cyan (Blue+Green)     |
|111   |White (Red+Green+Blue)|
|000   |Off                   |
*
=> RGBLight: Improve RGB Test animation

quantum/rgb_matrix/animations/pixel_rain_anim.h
Improved effect with update to LED index within `led_min` and `led_max` limits
=> Update Pixel Rain to respect LED range limits

quantum/rgb_matrix/animations/breathing_anim.h
Simplify effect with an existing runner
=> Refactor Breathing effect with runner

requirements.txt
`milc 1.9.0` replaced `appdirs` with `platformdirs`. For users who update the global cli, they with see the following message
```
Could not find module appdirs!
Please run `/usr/bin/python3 -m pip install -r /__w/qmk_firmware/qmk_firmware/requirements.txt` to install required python dependencies.
```
As you cannot really install `qmk_cli` without having the dependencies fulfilled, users will always either have `appdirs`/`platformdirs` for whatever their environment requires. The exception is if they have done something to manually remove this package, but at that point any number of things could be broken and the automatic dependency install logic is unlikely to fix.
We should not just update this line to `platformdirs` as that will then block users who have not updated global cli. Though …
=> Remove `appdirs` from `requirements.txt`

lib/python/qmk/cli/__init__.py
Updates to reflect the `1.1.6` release of `qmk_cli`.
* Fixes #22190
=> Bump minimum required Python version

docs/newbs.md
=> [docs] Fix dead link to keyboard list in newbs.md

builddefs/docsgen/.vitepress/config.mts
Docs landing page (index.md) mentions clicking this link at the bottom as one of the ways to contribute, but it wasn't enabled. Also turned on the page timestamp.
*
=> [docs] Add "edit this page" link at the bottom

lib/python/qmk/cli/via2json.py
VIA recently(?) gained the ability to describe key down and key up events in macros. This seems to have broken the parsing in `via2json` as it doesn't know how to handle them:
```json
[
{
"action": "tap",
"keycodes": ["+RCTL}{+RSFT}{L}{-RCTL}{-RSFT"]
}
],
```
I've reworked this part to break the macro up into groups of curly-braced keycodes, and determining if they are a chord (`,` is present), keydown (`+` is the first character) or keyup (`-`).
The macro keycodes themselves were broken probably due to the addition of `QK_MACRO_*`. they should now be properly captured and renamed to `MC_*`.
Some problems, however:
- The `MC_` numbering will be incorrect (vs the keymap.json `macros` array) if the VIA JSON `macros` array contains empty string entries. I'm not sure how to correct for this. …
=> `qmk via2json`: Improve macro parsing

keyboards/satt/comet46/keymaps/default-rgbled/keymap.c, keyboards/satt/comet46/keymaps/default/keymap.c
Modified as part of #22933, these changes should instead be avoided as the code is unnecessary.
*
=> Remove keyboard use of eeconfig_read_default_layer

docs/configurator_default_keymaps.md, keyboards/era/sirind/tomak79h/keymaps/default/keymap.c, keyboards/keebfront/vanguard65/keymaps/default/keymap.c, keyboards/keebio/iris_lm/keymaps/default/keymap.c, keyboards/xdboards/recon/keymaps/default/keymap.c
These were missed due to being PRed and merged after the previous PRs to update the RGB keycodes. Also forgot to update the Configurator docs example.
*
=> Update leftover RGB keycodes

lib/python/qmk/info.py
When a feature flag or encoder config is specified in info.json and config.h, show the values extracted from both sources.
*
=> Improve "feature/encoder config both specified" warnings

platforms/chibios/boards/GENERIC_STM32_H723XG/configs/mcuconf.h, platforms/chibios/boards/QMK_PROTON_C/configs/chconf.h, platforms/chibios/boards/common/configs/chconf.h
=> Update ChibiOS to latest stable branch.

keyboards/sawnsprojects/bunnygirl65/keyboard.json
Fix name of Manufacture in sawnsprojects/bunnygirl65
*
=> Fix typo in name

keyboards/suikagiken/suika27melo/config.h, keyboards/suikagiken/suika27melo/keyboard.json, keyboards/suikagiken/suika27melo/keymaps/default/keymap.json, keyboards/suikagiken/suika27melo/keymaps/midi/keymap.json, keyboards/suikagiken/suika27melo/readme.md
Add keyboard suikagiken/suika27melo.
* n/a
=> add keyboard suika27melo

data/constants/keycodes/extras/keycodes_farsi_0.0.1.hjson, quantum/keymap_extras/keymap_farsi.h
Output for U+0656 is AltGr + V
* closes #24686
=> Subscript alef correction

docs/_sidebar.json, docs/license_violations.md
As per the title. #24085 was getting a bit long, and this clarifies a lot of our stance and the expectations.
We can update the list of offending vendors as required through PRs instead.
=> Add licensing violations page.

lib/python/qmk/cli/generate/keyboard_h.py
Adjusted layout macro generation - no mixed tabs & spaces, and added `XXX` define for better alignment.
Also moved the heading comments so that they only appear when necessary.
*
=> default_keyboard.h generation tweaks

keyboards/tzarc/djinn/graphics/theme_djinn_default.c
Issues when using user- or kb-level RGB effects.
=> [bug] Djinn theme fix.

lib/python/qmk/info.py
Re-fix #24739.
Indentation being incorrect makes it log out incorrectly, where it should only do so if there are generally worse issues beforehand.
*
=> Fix g_led_config parse warning

quantum/rgb_matrix/animations/hue_breathing_anim.h
Simplify effect with existing runner
=> Refactor Hue Breathing matrix effect with runner

keyboards/takashicompany/klec_02/config.h
Add EE_HANDS for KLEC-02. Please review.
*
=> Add EE_HANDS for KLEC-02

docs/feature_macros.md, docs/feature_userspace.md, docs/features/mouse_keys.md
Looks to be missed along the way with the docs migration. Aligned per the rest of the repo to:
*
=> Convert stray legacy warn/info docs panels

lib/python/qmk/cli/via2json.py
Now that `via` keymaps are not in the repo, searching for them will not find anything.
*
=> Update via2json layout macro searching

keyboards/aeboards/constellation/rules.mk, keyboards/bpiphany/pegasushoof/rules.mk, keyboards/dp3000/rules.mk, keyboards/eek/rules.mk, keyboards/exclusive/e85/rules.mk, keyboards/keebio/dsp40/rules.mk, keyboards/keycapsss/plaid_pad/rules.mk, keyboards/kprepublic/jj40/rules.mk, keyboards/kprepublic/jj50/rules.mk, keyboards/lfkeyboards/lfk78/rules.mk, keyboards/lfkeyboards/smk65/rules.mk, keyboards/mechlovin/adelais/rgb_led/rules.mk, keyboards/mechlovin/adelais/standard_led/rules.mk, keyboards/mechlovin/delphine/rules.mk, keyboards/mechlovin/hannah60rgb/rules.mk, keyboards/mechlovin/hannah910/rules.mk, keyboards/mechlovin/hex4b/rules.mk, keyboards/melgeek/z70ultra/rules.mk, keyboards/montsinger/rebound/rules.mk, keyboards/polilla/rules.mk, keyboards/primekb/prime_l/rules.mk, keyboards/projectkb/alice/rules.mk, keyboards/rgbkb/pan/rev1/rules.mk, keyboards/tkw/stoutgat/v2/rules.mk, keyboards/whale/sk/rules.mk, keyboards/ymdk/melody96/rules.mk
<details>
<summary>Script used</summary>
```sh
#!/bin/bash
for rule in $(find keyboards/ -name rules.mk | sort | grep -v keymaps); do
if [[ $(cat $rule | grep . | grep -Ev "^#.*" | grep -v DEFAULT_FOLDER | wc -l) == 0 ]]; then
default_folder=$(cat $rule | grep . | grep -Ev "^#.*" | sed 's^DEFAULT_FOLDER[= ]*^^')
kb_folder=$(echo $rule | sed 's?^keyboards/??' | sed 's^/rules.mk^^')
if [[ ! -d keyboards/$default_folder ]]; then
continue
fi
if grep -Pzq '\s"'$kb_folder'"\s*:\s{\n\s*"target"\s*:\s*"'$default_folder'"' data/mappings/keyboard_aliases.hjson; then
rm -f $rule
continue
fi
fi
done
```
</details>
Refactoring remaining use of `DEFAULT_FOLDER` will follow shortly after what can be automated.
*
=> Remove DEFAULT_FOLDER where keyboard aliases already exists

keyboards/rgbkb/pan/rules.mk
=> Fix up CI with `DEFAULT_FOLDER`.

docs/drivers/i2c.md
Various tweaks and corrections.
*
=> [Docs] Correct I2C API reference

lib/python/qmk/info.py
Adds lint checks to cover the less than ideal submission within 24880.
*
=> Reject keyboard.json next to info.json

keyboards/al1/readme.md, keyboards/alf/dc60/readme.md, keyboards/biacco42/meishi2/readme.md, keyboards/bpiphany/unloved_bastard/readme.md, keyboards/cool836a/readme.md, keyboards/deltapad/readme.md, keyboards/duck/jetfire/readme.md, keyboards/ericrlau/numdiscipline/readme.md, keyboards/handwired/fc200rt_qmk/readme.md, keyboards/handwired/novem/readme.md, keyboards/hineybush/h75_singa/readme.md, keyboards/kakunpc/business_card/readme.md, keyboards/keebio/ergodicity/readme.md, keyboards/kira/kira75/readme.md, keyboards/kprepublic/bm16a/v1/readme.md, keyboards/kprepublic/bm16s/readme.md, keyboards/marksard/treadstone32/readme.md, keyboards/marksard/treadstone48/readme.md, keyboards/masterworks/classy_tkl/readme.md, keyboards/mb44/readme.md, keyboards/mechlovin/delphine/readme.md, keyboards/mechwild/mokulua/readme.md, keyboards/meme/readme.md, keyboards/mint60/readme.md, keyboards/pegasus/readme.md, keyboards/tgr/tris/readme.md, keyboards/x16/readme.md
Remove content from keyboard readmes that should have been filled out when using the [template](https://github.com/qmk/qmk_firmware/blob/master/data/templates/keyboard/readme.md).
*
=> Remove readme dummy content

.github/workflows/stale.yml
These labels are waiting on a core-side wireless implementation.
=> Add more stale exemption labels.

docs/ChangeLog/20250223.md, docs/_sidebar.json, docs/breaking_changes.md, docs/breaking_changes_history.md, modules/qmk/hello_world/qmk_module.json
=> 2025q1 develop changelog

keyboards/jankycaps/janky9/keyboard.json, keyboards/jankycaps/janky9/keymaps/default/keymap.c, keyboards/jankycaps/janky9/readme.md
Add Janky No.9
Add support for Janky No.9
*
=> Add Janky No.9

keyboards/cipulot/ec_980c/keyboard.json, keyboards/gkeyboard/greatpad/keyboard.json, keyboards/splitkb/elora/rev1/keyboard.json, keyboards/splitkb/halcyon/kyria/rev4/keyboard.json
`solid_color` is always enabled and should never be specified in config.
*
=> Remove invalid RGB Matrix effects

keyboards/keychron/c1_pro_v2/config.h, keyboards/keychron/c1_pro_v2/info.json, keyboards/keychron/c2_pro_v2/config.h, keyboards/keychron/c2_pro_v2/info.json
=> keychron/c*_pro_v2: Migrate DIP_SWITCH_PINS

keyboards/keyten/kt60_mu/config.h
=> keyten/kt60_mu - Add missing header guard

.github/workflows/format.yml, .github/workflows/lint.yml
https://github.com/tj-actions/changed-files/issues/2464
<https://github.com/tj-actions/changed-files/releases/tag/v46.0.1>
*
=> Bump tj-actions/changed-files from 45 to 46

keyboards/uzu42/rev1/keyboard.json
As the current vendor code (0xFEED) for uzu42 is apparently a generic one blacklisted by a third party tool, I've changed it with the blessing of the original creator to the initials of their online handle.
*
=> Change generic vendor code for uzu42

docs/cli.md, docs/cli_development.md, docs/coding_conventions_python.md, lib/python/qmk/cli/__init__.py, requirements.txt
Updates to reflect the `1.1.6` release of `qmk_cli`.
Add back in `platformdirs`?
Most changes so far have been backwards compatible, so only worth merging once we get a decent amount of users upgraded.
*
=> Align to latest CLI dependencies

drivers/painter/ili9xxx/qp_ili9486.c, keyboards/zsa/moonlander/matrix.c
=> Fix outdated GPIO control function usage

.github/workflows/auto_tag.yml
Python is now as much of a dependency within the build system, we should tag it as we do with `.mk`, `Makefile`, `builddefs/` etc.
*
=> Create tags when `lib/python` changes

docs/features/community_modules.md
=> Module documentation typo correction

lib/python/qmk/cli/lint.py
Fixes the following scenarios,
1. `-kb` appends, so "all" might not be the first item in the list
```
qmk lint -kb zvecr/zv48/f401 -kb all
☒ unsupported operand type(s) for /: 'PosixPath' and 'AllKeyboards'
File "/home/zvecr/zv_firmware_clean/.direnv/python-3.12/lib/python3.12/site-packages/milc/milc.py", line 606, in __call__
^^^^^^^^^^^^^^^
File "/home/zvecr/zv_firmware_clean/.direnv/python-3.12/lib/python3.12/site-packages/milc/milc.py", line 611, in __call__
^^^^^^^^^^^^^^^^^^^^^^
File "/home/zvecr/zv_firmware_clean/lib/python/qmk/decorators.py", line 38, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix 'qmk lint -kb' argument handling

keyboards/coban/pad12a/config.h, keyboards/coban/pad12a/keyboard.json, keyboards/coban/pad12a/keymaps/default/keymap.c, keyboards/coban/pad12a/keymaps/default/rules.mk, keyboards/coban/pad12a/readme.md
Add Coban Pad 12A small macroboard
=> Add Coban Pad 12A

docs/hand_wire.md, docs/license_violations.md
=> Remove direct docs.qmk.fm links from docs

lib/python/qmk/build_targets.py, lib/python/qmk/cli/generate/make_dependencies.py, lib/python/qmk/commands.py
As per Discord. More Windows-style paths creeping into `Makefile` invocations.
=> More Windows->Unix style path fixes.

keyboards/preonic/config.h
Added `AUDIO_INIT_DELAY ` to config.h to resolve. Based on conversation for [Bug] #8825.
A similar fix was applied to Planck variant on #24893.
* fixes #25132
=> fix: Fix startup sound for Preonic (#25132)

drivers/sensors/pimoroni_trackball.c, quantum/pointing_device/pointing_device.c, quantum/pointing_device/pointing_device.h, tmk_core/protocol/report.h
Just a small clean-up to allow easier reuse in other code parts.
*
=> [chore]: move and rename mouse/scroll min/max defines

docs/features/led_matrix.md, docs/features/rgb_matrix.md, docs/features/rgblight.md, docs/reference_info_json.md
This attempts to resolve #24670 by clarifying the descriptions in the docs.
as titled.
#24670
=> unify lighting step descriptions across docs

data/schemas/community_module.jsonschema, data/schemas/keyboard.jsonschema, data/schemas/user_repo_v0.jsonschema, data/schemas/user_repo_v1.jsonschema, data/schemas/user_repo_v1_1.jsonschema
- before changes
- after changes
I discovered an issue where JSON schema could not be applied in IntelliJ IDEA and fixed it.
I resolved syntax errors by correcting missing or extra commas in the JSON schema file.
This fix ensures that JSON schemas can now be properly loaded in IntelliJ.
*
=> Fix missing and extra commas in JSON schema

docs/config_options.md
Add qmk-hid to the list of available bootloaders for completeness in https://docs.qmk.fm/config_options#avr-mcu-options
Found this list, there should be 8 options, not 7?
https://github.com/qmk/qmk_firmware/blob/edf34315affe4427f862ccd70ff2aa9143ee1966/platforms/avr/bootloader.mk#L22-L30
*
=> DOCS: `qmk-hid` missing in bootloaders list?

.clangd
Mainly discussed on #23968, includes suggested fix on that issue and was also confirmed separately be someone afflicted by the problem on Discord.
* Fixes #23968
=> Fix for `.clangd`.

keyboards/anavi/macropad8/keyboard.json
=> Decrease firmware size for `anavi/macropad8`.

tmk_core/protocol/chibios/chibios.c
Prep for future alignment of implementations.
*
=> Align ChibiOS `USB_WAIT_FOR_ENUMERATION` implementation

.github/workflows/format_push.yml, .github/workflows/regen_push.yml
Flagged by CodeQL, but not updated by dependabot?
*
=> Bump rlespinasse/github-slug-action from 3 to 5

lib/python/qmk/cli/generate/api.py
Avoid scenarios where `keymap.json` only contains build config and no layers, alongside a `keymap.c` which contains a typical keymap.
While maybe a better long term solution, updating `list_keymaps` was avoided to limit any snowballing of the change in behaviour.
*
=> Update 'qmk generate-api' to only publish pure DD keymaps

keyboards/cipulot/ec_980c/keyboard.json, keyboards/custommk/evo70_r2/keyboard.json, keyboards/darmoshark/k3/keyboard.json, keyboards/dnworks/frltkl/keyboard.json, keyboards/dnworks/sbl/keyboard.json, keyboards/dnworks/tkl87/keyboard.json, keyboards/ebastler/e80_1800/keyboard.json, keyboards/handwired/daskeyboard/daskeyboard4/keyboard.json, keyboards/kbdfans/odin75/keyboard.json, keyboards/kbdfans/tiger80/keyboard.json, keyboards/meetlab/kafkasplit/keyboard.json, keyboards/studiokestra/fairholme/keyboard.json, keyboards/studiokestra/line_friends_tkl/keyboard.json, keyboards/yandrstudio/transition80/keyboard.json, keyboards/zeix/eden/keyboard.json
Miscellaneous changes flagged from 25149.
*
=> Remove more duplication of defaults

data/templates/keyboard/keyboard.json
Aligning to current PR recommendations, and current/incoming refactoring.
*
=> Align `new-keyboard` template to current standards

keyboards/ibm/model_m/modelh/keyboard.json
To support via we need to use a different VID and also lower the number of dynamic_keymap layers.
=> modelh: add prerequisites for via support

keyboards/amptrics/0422/0422.c
`gpio_write_pin_high(pins[layer]);` for `layer >= 4` would go out of bounds.
Also fixed up a few types while updating the file.
*
=> amptrics/0422 - Prevent OOB in `update_leds_for_layer`

lib/python/qmk/decorators.py
Add Workaround for when a legacy keyboard value is set within the CLI config file.
Steps to reproduce:
1. `qmk config user.keyboard=lily58`
2.  `qmk config user.keymap=default`
3.  `qmk compile`
4. Note the following exception
```python
<class 'KeyError'>
☒ "Invalid keyboard: 'lily58'"
File "/home/zvecr/qmk_firmware/.direnv/python-3.13/lib/python3.13/site-packages/milc/milc.py", line 609, in __call__
~~~~~~~~~~~~~^^
File "/home/zvecr/qmk_firmware/.direnv/python-3.13/lib/python3.13/site-packages/milc/milc.py", line 614, in __call__
~~~~~~~~~~~~~~~~^^^^^^
File "/home/zvecr/qmk_firmware/lib/python/qmk/decorators.py", line 38, in wrapper
return func(*args, **kwargs)
File …
```
=> Workaround for resolving keyboard alias for config file values

builddefs/common_features.mk, drivers/bluetooth/bluetooth.c, drivers/bluetooth/bluetooth.h, drivers/bluetooth/bluetooth_drivers.c, quantum/connection/connection.c, tmk_core/protocol/host.c
Short-term changes while #24365 is in progress. The aim of this PR is to reduce overall complexity for the various wireless changes, while still maintaining backwards compatibility.
Also fixes `CONNECTION_HOST_NONE` still sending over USB.
> NKRO is not currently supported with Bluetooth, and has been disabled.
Existing NKRO assumptions will be fixed in subsequent PRs.
*
=> Bind Bluetooth driver to `host_driver_t`

docs/cli.md, docs/newbs_getting_started.md
Getting started with qmk. I work a lot with python, and wanted to contribute back some docs for managing the qmk tool installation with uv.
Dead simple and doesn't require a user to manually deal with virtual environments to get the benefits. Also allows qmk to be bulk updated with other uv managed tools via `uv tool upgrade --all`.
=> Docs update for installing qmk with uv

data/mappings/info_defaults.hjson, keyboards/mlego/m65/rev1/keyboard.json
Add check to flag `"debounce": 5` within keyboards.
*
=> Add debounce to duplicated defaults check

docs/features/community_modules.md
"hello world" vs "hello word".
* https://discord.com/channels/440868230475677696/867530715192885269/1369912377234952243
=> [Docs] Fix typos introduced by PR #25050

keyboards/hazel/bad_wings_v2/config.h, keyboards/hazel/bad_wings_v2/halconf.h, keyboards/hazel/bad_wings_v2/keyboard.json, keyboards/hazel/bad_wings_v2/keymaps/default/config.h, keyboards/hazel/bad_wings_v2/keymaps/default/keymap.json, keyboards/hazel/bad_wings_v2/mcuconf.h, keyboards/hazel/bad_wings_v2/readme.md, keyboards/hazel/bad_wings_v2/rules.mk
This PR adds support for the [Bad Wings v2](https://github.com/hazels-garage/bad-wings/tree/master/v2)
*
=> [Keyboard] Add Jason Hazel’s Bad Wings v2

builddefs/common_features.mk, drivers/bluetooth/bluetooth.c, drivers/bluetooth/bluetooth.h, quantum/raw_hid.c, tmk_core/protocol.mk, tmk_core/protocol/chibios/chibios.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/host.c, tmk_core/protocol/host.h, tmk_core/protocol/host_driver.h, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/vusb.c
Partially extracted from #24365. Avoids previous `md_raw.h` workarounds.
*
=> Add raw_hid support to host driver

keyboards/waveshare/rp2040_keyboard_3/keyboard.json, keyboards/waveshare/rp2040_keyboard_3/keymaps/default/keymap.c, keyboards/waveshare/rp2040_keyboard_3/readme.md
=> Add RP2040-Keyboard-3 support

docs/pr_checklist.md
=> Update PR checklist notes on custom matrix

keyboards/0_sixty/info.json, keyboards/0xcb/tutelpad/keyboard.json, keyboards/1upkeyboards/super16/keyboard.json, keyboards/1upkeyboards/sweet16/v1/keyboard.json, keyboards/25keys/cassette42/keyboard.json, keyboards/25keys/zinc/rev1/keyboard.json, keyboards/25keys/zinc/reva/keyboard.json, keyboards/30wer/keyboard.json, keyboards/40percentclub/25/keyboard.json, keyboards/40percentclub/4pack/keyboard.json, keyboards/40percentclub/6lit/keyboard.json, keyboards/40percentclub/foobar/keyboard.json, keyboards/40percentclub/half_n_half/keyboard.json, keyboards/40percentclub/i75/promicro/keyboard.json, keyboards/40percentclub/luddite/keyboard.json, keyboards/40percentclub/mf68/keyboard.json, keyboards/40percentclub/nano/keyboard.json, keyboards/40percentclub/nein/keyboard.json, keyboards/40percentclub/nori/keyboard.json, keyboards/40percentclub/polyandry/promicro/keyboard.json, keyboards/40percentclub/sixpack/keyboard.json, keyboards/40percentclub/tomato/keyboard.json, keyboards/4by3/keyboard.json, keyboards/8pack/info.json, keyboards/adkb96/rev1/keyboard.json
=> Configure boards to use development_board - 0-9

keyboards/ungodly/nines/keyboard.json, keyboards/unikeyboard/diverge3/keyboard.json, keyboards/unikeyboard/divergetm2/keyboard.json, keyboards/unikeyboard/felix/keyboard.json, keyboards/uzu42/rev1/keyboard.json, keyboards/vagrant_10/keyboard.json, keyboards/wsk/alpha9/keyboard.json, keyboards/wsk/g4m3ralpha/keyboard.json, keyboards/wsk/jerkin/keyboard.json, keyboards/wsk/kodachi50/keyboard.json, keyboards/wsk/pain27/keyboard.json, keyboards/xenon/keyboard.json, keyboards/yampad/keyboard.json, keyboards/yeehaw/keyboard.json, keyboards/yosino58/rev1/keyboard.json, keyboards/yushakobo/navpad/10/info.json, keyboards/yushakobo/navpad/10_helix_r/keyboard.json, keyboards/yushakobo/quick17/keyboard.json, keyboards/yushakobo/quick7/keyboard.json, keyboards/yynmt/dozen0/keyboard.json, keyboards/zigotica/z12/keyboard.json, keyboards/zigotica/z34/keyboard.json
=> Configure boards to use development_board - UVWXYZ

keyboards/takashicompany/center_enter/keyboard.json, keyboards/takashicompany/compacx/keyboard.json, keyboards/takashicompany/dogtag/keyboard.json, keyboards/takashicompany/endzone34/keyboard.json, keyboards/takashicompany/qoolee/keyboard.json, keyboards/takashicompany/radialex/keyboard.json, keyboards/takashicompany/spreadwriter/keyboard.json, keyboards/takashiski/hecomi/alpha/keyboard.json, keyboards/takashiski/namecard2x4/info.json, keyboards/tanuki/keyboard.json, keyboards/tender/macrowo_pad/keyboard.json, keyboards/tenki/keyboard.json, keyboards/tg4x/keyboard.json, keyboards/tominabox1/qaz/keyboard.json
=> Configure boards to use development_board - T

docs/drivers/battery.md
=> Fix typo in Battery Driver docs

keyboards/pabile/p18/keyboard.json, keyboards/pabile/p20/ver1/keyboard.json, keyboards/pabile/p20/ver2/keyboard.json, keyboards/pabile/p40/keyboard.json, keyboards/pabile/p40_ortho/keyboard.json, keyboards/pabile/p42/keyboard.json, keyboards/peej/tripel/info.json, keyboards/peranekofactory/tone/rev1/keyboard.json, keyboards/peranekofactory/tone/rev2/keyboard.json, keyboards/pica40/rev1/keyboard.json, keyboards/pimentoso/paddino02/rev1/keyboard.json, keyboards/pimentoso/paddino02/rev2/left/keyboard.json, keyboards/pimentoso/paddino02/rev2/right/keyboard.json, keyboards/pimentoso/touhoupad/keyboard.json, keyboards/pinky/3/keyboard.json, keyboards/pinky/4/keyboard.json, keyboards/plum47/keyboard.json, keyboards/psuieee/pluto12/keyboard.json, keyboards/pteron36/keyboard.json
=> Configure boards to use development_board - P

keyboards/rainkeebs/rainkeeb/keyboard.json, keyboards/rart/rart4x4/keyboard.json, keyboards/rart/rart67m/keyboard.json, keyboards/rart/rartlite/keyboard.json, keyboards/rart/rartpad/keyboard.json, keyboards/rate/pistachio_mp/keyboard.json, keyboards/recompile_keys/choco60/rev1/keyboard.json, keyboards/recompile_keys/cocoa40/keyboard.json, keyboards/recompile_keys/nomu30/rev1/keyboard.json, keyboards/rect44/keyboard.json, keyboards/redox_media/keyboard.json, keyboards/reviung/reviung34/keyboard.json, keyboards/reviung/reviung39/keyboard.json, keyboards/reviung/reviung41/keyboard.json, keyboards/reviung/reviung5/keyboard.json, keyboards/reviung/reviung53/keyboard.json, keyboards/rgbkb/zen/rev1/keyboard.json, keyboards/rgbkb/zen/rev2/keyboard.json, keyboards/rpiguy9907/southpaw66/keyboard.json, keyboards/rura66/rev1/keyboard.json, keyboards/ryanbaekr/rb1/keyboard.json
=> Configure boards to use development_board - R

keyboards/latincompass/latinpad/keyboard.json, keyboards/lets_split/info.json, keyboards/lily58/glow_enc/keyboard.json, keyboards/lily58/light/keyboard.json, keyboards/lily58/rev1/keyboard.json, keyboards/lime/rev1/keyboard.json, keyboards/machkeyboards/mach3/keyboard.json, keyboards/makrosu/keyboard.json, keyboards/manta60/keyboard.json, keyboards/maple_computing/6ball/keyboard.json, keyboards/maple_computing/christmas_tree/v2017/keyboard.json, keyboards/maple_computing/launchpad/rev1/keyboard.json, keyboards/maple_computing/minidox/rev1/keyboard.json, keyboards/marksard/leftover30/keyboard.json, keyboards/marksard/rhymestone/rev1/keyboard.json, keyboards/maxipad/promicro/keyboard.json, keyboards/mechwild/mokulua/mirrored/keyboard.json, keyboards/mechwild/mokulua/standard/keyboard.json, keyboards/mechwild/murphpad/keyboard.json, keyboards/meow48/keyboard.json, keyboards/merge/uc1/keyboard.json, keyboards/minimacro5/keyboard.json, keyboards/mint60/keyboard.json, keyboards/mixi/keyboard.json, keyboards/montsinger/rewind/keyboard.json, keyboards/morizon/keyboard.json, keyboards/mountainblocks/mb17/keyboard.json
=> Configure boards to use development_board - LM

lib/python/qmk/compilation_database.py
Fixes some more clangd issues.
=> Specify language standard when generating compilation database.

keyboards/ffkeebs/puca/keyboard.json, keyboards/flehrad/numbrero/keyboard.json, keyboards/flehrad/snagpad/keyboard.json, keyboards/flehrad/tradestation/keyboard.json, keyboards/for_science/keyboard.json, keyboards/fr4/southpaw75/keyboard.json, keyboards/fr4/unix60/keyboard.json, keyboards/fractal/keyboard.json, keyboards/free_willy/keyboard.json, keyboards/fungo/rev1/keyboard.json, keyboards/funky40/keyboard.json, keyboards/gl516/a52gl/keyboard.json, keyboards/gl516/j73gl/keyboard.json, keyboards/gl516/n51gl/keyboard.json, keyboards/gowla/keyboard.json, keyboards/halfcliff/keyboard.json, keyboards/hifumi/keyboard.json, keyboards/horizon/keyboard.json, keyboards/ibnuda/alicia_cook/keyboard.json, keyboards/ibnuda/gurindam/keyboard.json, keyboards/ibnuda/squiggle/rev1/keyboard.json, keyboards/ivndbt/late9/rev1/keyboard.json, keyboards/ivndbt/neopad/rev1/keyboard.json, keyboards/jiran/info.json, keyboards/jorne/rev1/keyboard.json
=> Configure boards to use development_board - FGHIJ

keyboards/ymdk/id75/keymaps/default/keymap.json
Both revisions failing in api_tasks due to the keyboard name `ymdk/id75` not existing.
*
=> ymdk/id75: fix keymap

docs/drivers/aw20216s.md
Was currently incorrectly linking to the unsupported I2C `AW20216` version.
*
=> Update link to AW20216S datasheet

data/mappings/info_config.hjson, data/schemas/keyboard.jsonschema, docs/reference_info_json.md, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/info.py
Adds:
```json
{
"matrix_pins": {
"masked": true
},
}
```
Also updates `dip_switch.matrix_grid` and `split.handedness.matrix_grid` defaulting logic to not conflict with configured value. 
*
=> Add MATRIX_MASKED DD config

docs/feature_userspace.md
=> Fix link - users folder now empty on default branch

keyboards/keebio/quefrency/rev1/keyboard.json
Currently produces the following error:
```
Compiling: quantum/keymap_introspection.c                                                          In file included from quantum/keymap_introspection.c:9:
./keyboards/keebio/quefrency/keymaps/default60/keymap.c:20:13: error: implicit declaration of function 'LAYOUT_60'; did you mean 'LAYOUT_65'? [-Werror=implicit-function-declaration]
[_BASE] = LAYOUT_60(
^~~~~~~~~
LAYOUT_65
./keyboards/keebio/quefrency/keymaps/default60/keymap.c:20:13: error: initializer element is not constant
./keyboards/keebio/quefrency/keymaps/default60/keymap.c:20:13: note: (near initialization for 'keymaps[0][0][0]')
In file included from quantum/keymap_introspection.c:9:
./keyboards/keebio/quefrency/keymaps/default60/keymap.c:28:12: error: initializer element is not …
```
=> Fix `keebio/quefrency/rev1:default60`

quantum/rgb_matrix/animations/starlight_smooth_anim.h
Use the smaller lib8tion random8() function.
=> Refactor Starlight Smooth matrix effect

drivers/sensors/adns5050.h, drivers/sensors/adns9800.h, drivers/sensors/analog_joystick.h, drivers/sensors/azoteq_iqs5xx.h, drivers/sensors/cirque_pinnacle.h, drivers/sensors/paw3204.h, drivers/sensors/pimoroni_trackball.h, drivers/sensors/pmw3320.h, drivers/sensors/pmw33xx_common.h, keyboards/bajjak/bajjak.c, keyboards/bajjak/bajjak.h, keyboards/hardwareabstraction/handwire/handwire.c, keyboards/sekigon/grs_70ec/matrix.c, keyboards/system76/launch_1/launch_1.c, keyboards/system76/launch_1/rgb_matrix_kb.inc, keyboards/system76/system76_ec.c, keyboards/work_louder/rgb_functions.c, quantum/audio/audio.c
Extracted from #25384.
No reason these changes cannot be merged first, as they only make the code more correct independent of `fcommon`/`fno-common`.
*
=> Compilation fixes for `-fno-common`

.gitignore
Zero reason for these to exist in the repo (gerbers code dumps), and adding this will also then flag the bad file in lint.
*
=> Add zip to .gitignore

quantum/rgb_matrix/animations/solid_reactive_anim.h, quantum/rgb_matrix/animations/solid_reactive_simple_anim.h
* Avoids underflow of the unsigned 8-bit
* Fix unintended wrap-around after #25272
=> Clamp reactive offset value

docs/_sidebar.json, docs/proprietary_libs.md
Probably long overdue considering how many times this has come up before.
=> Add proprietary libraries policy page.

lib/python/qmk/cli/new/keymap.py
Not that this should ever really happen.... default keymaps are a hard requirement.
However producing stack traces, as shown in 25534, tends to just confuse users.
```
$ rm -rf keyboards/drop/cstm65/keymaps/default
$ qmk new-keymap -kb drop/cstm65 -km asdf
Ψ Generating a new keymap
☒ Default keymap for drop/cstm65 does not exist!
```
```
$ rm -rf keyboards/drop/cstm65/keymaps
$ qmk new-keymap -kb drop/cstm65 -km asdf
Ψ Generating a new keymap
☒ Could not find the keymaps directory!
☒ Keymap folder for drop/cstm65 does not exist!
```
* fixes #25534
=> Improve `new-keymap` error handling when default keymap is missing

quantum/quantum.c
* Replaced for-loop with single wait_ms(delay) call
* Improve code consistency with tap_code_delay
* Loop is unnecessary after PR #14025
=> Simplify tap_code16_delay

docs/isp_flashing_guide.md
Changed the links to point directly at the proper repo branches, and added simple instructions on how to build.
Worth noting CFTKB appears to be [defunct or otherwise unresponsive](https://www.reddit.com/r/MechanicalKeyboards/comments/u0evvo/psa_dont_buy_from_cftkb/), so perhaps we should have our own fork of this?
*
=> Update USBaspLoader ISP instructions

quantum/rgb_matrix/animations/pixel_rain_anim.h
* Increase effect interval duration scale
* Scale interval timer with g_rgb_timer
=> Restructure Pixel Rain interval code

docs/features/led_matrix.md, docs/features/rgb_matrix.md, docs/keycodes.md
Looks docs were missing on #24649.
This should cover the added functionality, as well as cover those previously missing.
*
=> Add LED/RGB Matrix flags API docs

.github/workflows/ci_build_major_branch.yml
=> Add 'xap' branch to CI workflow and options

docs/quantum_painter.md, drivers/painter/comms/qp_comms_spi.c, drivers/painter/generic/qp_surface.h, drivers/painter/generic/qp_surface_internal.h, drivers/painter/generic/qp_surface_rgb565.c, drivers/painter/generic/qp_surface_rgb888.c, drivers/painter/ili9xxx/qp_ili9486.c, drivers/painter/tft_panel/qp_tft_panel.c, quantum/painter/qff.h, quantum/painter/qgf.c, quantum/painter/qgf.h, quantum/painter/qp_draw_core.c, quantum/painter/qp_draw_ellipse.c, quantum/painter/qp_internal.h, quantum/painter/qp_internal_formats.h, quantum/painter/rules.mk
As per title and commit messages
*
=> [QP] Minor cleanup and support for RGB888 surface

keyboards/stardustn0/keyboard.json, keyboards/stardustn0/keymaps/default/keymap.c, keyboards/stardustn0/readme.md
=> Add stardustn0
