- keyboards/converter/sun_usb/rules.mk
Type 5 is better polished, and probably more common as the last non-USB Sun
keyboard.
> Make type 5 the default sun keyboard.

- build_keyboard.mk
Prior to this, only the full keyboard path was defined.  Eg `KEYBOARD_planck_rev6`. But the docs mention `KEYBOAD_planck`, which never actually gets defined.
This addresses this, and creates a define for each level of the keyboard folder, so that stuff like `KEYBOARD_planck` actually exists.
> Fix LAYOUT define generation

- quantum/rgblight.c
rgblight_effect_alternating(void) calls rgblight_sethsv_at() RGBLED_NUM times. As a result, rgblight_set() is called RGBLED_NUM + 1 times. This is wasteful processing.
> optimize rgblight_effect_alternating(void)

- quantum/process_keycode/process_ucis.c
- quantum/process_keycode/process_unicode.c
- quantum/process_keycode/process_unicode_common.c
- quantum/process_keycode/process_unicode_common.h
- quantum/process_keycode/process_unicodemap.c
- users/drashna/drashna.h
Specifically, it wasn't being calling always, so you would have to run it every time.  Which means writing to EEPROM (and as you know, I hate unnecessary writing to EEPROM! :D).
Specifically, the `process_*` function for each unicode method now calls `get_unicode_input_mode()` during it.  The first time it's run after power on, it will read from EEPROM. 
Afterwards, it will read from the static uint, so minimize performance hits by reading EEPROM.
> Fix Unicode EEPROM handling so it is consistent.

- keyboards/dz60/keymaps/iso_de_andys8/README.md
- keyboards/dz60/keymaps/iso_de_andys8/keymap.c
- keyboards/dz60/keymaps/iso_de_andys8/rules.mk
I added another layout I'm using with ISO and german keyboard settings. Since this seems to be missing I propose to add it to the repository.
> Add dz60 iso-de layout

- keyboards/catch22/config.h
Set it to default. I have no idea what I was thinking. I think this was a left over from the big switch keyboard I copied over. It makes sense to have a high debounce value for the big switch because the switch is physically large and slow.
> Doesn't need a 50ms debounce

- docs/faq_build.md
- docs/getting_started_build_tools.md
- keyboards/planck/readme.md
I was helping a buddy with his just-arrived Planck rev6 on Friday, and I *could not* find out what upload tool we were supposed to use.  Eventually I saw someone referencing dfu-util, and figured it was worth a shot.  We hadn't installed it as part of the "getting started" instructions, but once we did it installed correctly.
So I'm adding two things: mention `brew install dfu-util` in the getting started docs, and then added `make planck/rev6:default:dfu-util` in a new "Install examples" in the Planck Readme.
> Updates docs - planck.6 and macos instructions

- docs/getting_started_build_tools.md
New PR for #4187 due to deletion of original branch, with [requested additional change](https://github.com/qmk/qmk_firmware/pull/4187#pullrequestreview-166774670)
> Minor updates to build tools docs revised

- docs/feature_backlight.md
I'm guessing someone deleted a row at some point in the past, but I didn't blame it.
> Fix incorrect doctoring in feature_backlight.md

- keyboards/ergodox_infinity/matrix.c
When comparing the pins in this file to the Ergodox Infinity schematic, it seems that the first section is describing the rows and the second section is describing the columns.
> Swapped Row and Column in comments

- keyboards/kbd19x/info.json
The info.json had a random backslash, which invalidated the JSON structure. This commit fixes that issue.
> Configurator info.json fix for KBD19x

- quantum/split_common/split_util.c
Added JTAG disable code to the split_common slave code since the slave never calls keyboard_init(). In the future the slave should likely be modified to call keyboard_init() in someway, but without calling any of the unneccesary USB initialization code.
> Added JTAG disable code to the split_common

- keyboards/levinson/keymaps/jyh/config.h
- keyboards/levinson/keymaps/jyh/keymap.c
- keyboards/levinson/keymaps/jyh/readme.md
- keyboards/levinson/keymaps/jyh/rules.mk
- keyboards/levinson/keymaps/jyh2/config.h
- keyboards/levinson/keymaps/jyh2/keymap.c
- keyboards/levinson/keymaps/jyh2/readme.md
- keyboards/levinson/keymaps/jyh2/rules.mk
My personal keymaps (2 alternatives) for the levinson/let's split keyboard
* remove tap dance number keys due to sluggish responses
* simplify I2C configuration
* reverse hyper and meh positions
* reduce tapping term to allow fast typing with mod tap space keys
* remove Alt hold on right space key. too many false touches.
* add vim-style arrows (hjkl) on asdf; semicolon/quote on raise
* correct documentation string for jyh levinson layout
* add alternative levinson layout for jyh
* more inspiration from atreus keyboard. keeps shift in the expected
places. reduces number of layers. puts numpad layout easily
accessible. places important keys on palms and meta keys on top
corners for xmonad.
* correct layer switching in jyh2 levinson layout
* I was getting stuck on the numpad layer because …
> Keymap: add jyh levinson keymaps

- quantum/split_common/matrix.c
- quantum/split_common/split_util.c
- tmk_core/common/keyboard.c
- tmk_core/common/keyboard.h
This way all split keyboards are using that code instead of just those using split_common with the fix
> Move disable JTAG code from `keyboard_init` to `keyboard_setup`

- tmk_core/common/arm_atsam/suspend.c
- tmk_core/protocol/arm_atsam/i2c_master.c
- tmk_core/protocol/arm_atsam/main_arm_atsam.c
- tmk_core/protocol/arm_atsam/usb/udc.h
- tmk_core/protocol/arm_atsam/usb/ui.c
- tmk_core/protocol/arm_atsam/usb/ui.h
Fix for Massdrop CTRL and ALT keyboards not waking computer from sleep.
Removed debug LED lighting when going to sleep since its original debugging purpose is obsolete.
> Fix CTRL/ALT keyboard does not wake computer from sleep

- docs/quantum_keycodes.md
- quantum/quantum.c
- quantum/quantum_keycodes.h
This allows users to reset the eeprom with a press of the button, rather than using bootmagic or other arcane methods.
> Add EEPROM_RESET keycode to core code

- docs/feature_combo.md
The example uses the same letter in two of the combos, which is explicitly not allowed, and even stated above. 
This changes the example to correctly reflect that behavior.
> Update Combo documentation example

- keyboards/qwertyydox/rules.mk
The rules.mk is using CRLF....  This fixes it.
Fixes #4280
> Fix line endings in Qwertyydox

- tmk_core/common.mk
Specifically, I missed a space, and Travis didn't flag it, because it causes a warning, not an error
> Fix Spacing issue in Terminal Config makefile that break compiling

- keyboards/massdrop/alt/keymaps/reywood/keymap.c
- keyboards/massdrop/alt/keymaps/reywood/rgb_matrix_user.c
- keyboards/massdrop/alt/keymaps/reywood/rgb_matrix_user.h
- keyboards/massdrop/alt/keymaps/reywood/rules.mk
- tmk_core/protocol/arm_atsam/led_matrix.c
- tmk_core/protocol/arm_atsam/led_matrix.h
Hi there. This pull request evolved from trying to implement some custom LED effects on the Massdrop ALT. The code here causes a flash to ripple out from a key's LED when pressed. I had to modify the arm_atsam code to make this possible, though I tried to make as few changes to it as possible, only enough to make more diverse types of effects possible. As such, I'd be interested in hearing from @patrickmt on these changes. [Here's a video](https://imgur.com/Ea6av2j) of the effect.
> Add localized LED flash effect on keypress to Massdrop ALT

- keyboards/helix/serial.c
- keyboards/helix/serial.h
The new simple API can be selected.
Previous version, can select two way.
* use old API (compatible with let's split serial.c)
* use new API (multi-type transaction)
This version, can select three way.
* use old API (compatible with let's split serial.c)
* use new API (single-type transaction)
* use new API (multi-type transaction)
There is no change in the code generated by this change.
> Helix-serial.c configuration improvement

- keyboards/crkbd/keymaps/default/keymap.c
undef SSD1306OLED should not kill entire process_record_user() function.
> Keyboard: fix ifdef for crkbd's default/keymap.c

- util/new_project.sh
- use git user.name if available to replace the boilerplate name in
files we generate
- fix shellshock warnings
> Improve new_project script

- util/linux_install.sh
The required packages are not provided by the official repository. The packages
need to be installed from slackbuilds.org either manually or with the help of
third party tools like sbotools.
> Add support for slackware distribution (linux_install.sh)

- util/linux_install.sh
Tested on openSUSE 15.0, but should also work on Tumbleweed.
> Add missing arm gcc compiler for openSUSE 15.0 and Tumbleweed.

- docs/faq_build.md
- docs/getting_started_build_tools.md
- util/macos_install.sh
I've seen a few posts recently with people having issues and manually having to link avr-gcc@7 into the path, since it is keg-only.
> Make sure that avr-gcc@7 gets linked into the path on MacOS.

- keyboards/helix/helix.c
- keyboards/helix/pico/pico.c
- keyboards/helix/rev1/rev1.c
- keyboards/helix/rev2/rev2.c
- keyboards/helix/ssd1306.c
- keyboards/helix/ssd1306.h
This patch fixes the following two problems related screen off timer on helix.
1. Never screen off because ScreenOffInterval exceeds uint16_t
2. Do not return from screen off until there is no change in the screen contents between screen off and on
This is the helix version of #4346 
I don't have Helix with OLED. so I have not verified this patch.
I hope someone verify this.
> [WIP]Fix up screen off timer of helix

- docs/features.md
Fixed incorrect link to feature_combo.md in features.md docs file. 
Was linked to feature_combos.md, but _sidebar.md, _summary.md, and config_options.md all link to feature_combo.md. 
Assuming that it should not be pluralized.
> Fixed incorrect link to feature_combo.md in features.md docs file.

- docs/keycodes.md
Previously, Unicode Support heading appeared as the last row in the Swap Hands table.
> Fixed Unicode Support heading

- docs/feature_backlight.md
- tmk_core/common/backlight.c
- tmk_core/common/backlight.h
Currently, the only way to set the backlight state is through `backlight_toggle()`, and there is no exposed way to get the current backlight state.
This PR adds `backlight_enable()`, `backlight_disable()`, and `backlight_enabled()` to cover this.
> Backlight status functions

- docs/_sidebar.md
- docs/_summary.md
- docs/reference_configurator_support.md
Wrote a doc covering how to properly support keyboards in the Configurator.
> Docs: Supporting a keyboard in the QMK Configurator

- keyboards/bpiphany/pegasushoof/keymaps/default_jis/keymap.c
- keyboards/bpiphany/pegasushoof/keymaps/default_jis/rules.mk
- keyboards/bpiphany/pegasushoof/pegasushoof.h
* Create a new layout for the 91-key JIS version of Majestouch + Pegasus Hoof
* Add standard mapping based on the current default layout
- in the default layout the `LGUI` was made `FN0`, this keyboard doesn't have `LGUI` so I chose to map the `MENU` key to `FN0`
> Default JIS TKL keymap for Pegasus Hoof

- keyboards/atom47/rev2/rev2.c
- keyboards/atom47/rev3/rev3.c
No idea how this happened, but it did.
> Fix permanently on capslock led on Atom47

- keyboards/ergodox_ez/matrix.c
Specifically, row 11 was wrong.
Thanks algernon, for catching that.
> Fix Ergodox EZ Matrix scan

- keyboards/ergodox_ez/config.h
- keyboards/ergodox_ez/matrix.c
I extended the current debounce logic with an adaptive by switch debouncing. This way a bad switch gets a higher debouncing as a good switch.
The debounce filtering reports a key/switch change directly as before, without any extra delay. The new thing is that the debounce logic will filter all further changes, until the key/switch reports the same state for the given count of scans. As long as the switch toggles the internal debounce counter of the switch will set to DEBOUNCE from config.h. The counter is decreased every scan where the switch didn't changed it's state.
So a perfect switch will get a short debounce period (min. DEBOUNCE) and a bad key will get a much longer debounce period. The result is an adaptive debouncing period for each switch.
In other words this gives an adaptive …
> Adaptive debounce logic

- keyboards/idobo/keymaps/default75/config.h
- keyboards/idobo/keymaps/default75/keymap.c
- keyboards/idobo/keymaps/default75/readme.md
- keyboards/idobo/keymaps/default75/rules.mk
This allows the default xd75 keyboard layout to be used with the idobo 75 key from Massdrop.
> Clone layout for Massdrop's xd75

- docs/keycodes.md
@drashna's addition of `EEPROM_RESET` in #4234 added the keycode to the [Quantum Keycodes doc](https://docs.qmk.fm/#/quantum_keycodes?id=qmk-keycodes), but not to [the doc that lists all the keycodes](https://docs.qmk.fm/#/quantum_keycodes?id=qmk-keycodes).
> Add EEPROM_RESET keycode to keycodes.md doc

- keyboards/40percentclub/foobar/keymaps/default/config.h
- keyboards/40percentclub/foobar/keymaps/default/keymap.c
Hi,
I'm submitting a flushed out keymap for the 40percentclub/foobar keyboard. This is basically the default Gherkin layout but it has a mod tap RGUI for the ESC key. I also omitted most of what comprises the FN5 layer (page up/ page down) since IMHO these are easy to accidentally type and can be a somewhat jarring experience when that happens. Completely open to adding those for completeness though.
@zvecr
> Adding keymap layers for 40precentclub/foobar

- docs/faq_keymap.md
These keys were previously in each other's positions.
According to the OADG 109A spec for JIS-layout keyboards, `KC_MHEN` is to the left of the spacebar, and `KC_HENK` to the right.
> Keymap FAQ: fix positions of KC_HENK and KC_MHEN for JIS layout

- keyboards/blockey/rules.mk
Specifically, remvove the SRC line addig the ws2812 file, as it's not needed, and disabled mousekeys for space.
> Fix Blockey compiler (and size) issues

- keyboards/idobo/rules.mk
This allows users of the Idobo board to use generic 5x15 layouts as well as custom Idobo layouts
> Keyboard: add generic ortho 5x15 layout support to Idobo

- keyboards/handwired/arrow_pad/arrow_pad.h
- keyboards/handwired/arrow_pad/info.json
- keyboards/handwired/arrow_pad/keymaps/default/keymap.c
- keyboards/handwired/arrow_pad/keymaps/pad_21/keymap.c
- keyboards/handwired/arrow_pad/keymaps/pad_24/keymap.c
- keyboards/handwired/arrow_pad/readme.md
- Layout macros moved from the keymaps to arrow_pad.h.
- LAYOUT_pad21 refactored to only accept keys that are physical present (no KC_NO entries required in keymap)
- Keymaps now use #include QMK_KEYBOARD_H
- Keymaps refactored to use process_record_user function (from action_get_macro)
Fixed the make commands and updated the layout macro.
> handwired/arrow_pad Refactor and Configurator support

- keyboards/helix/pico/rules.mk
- keyboards/helix/rev2/rules.mk
Remove `SRC += ws2812.c` from helix/rev2/rules.mk and helix/pico/rules.mk.
Because it will be added in common_features.mk.
> Fix Helix ws2812.c listed more than once warning.

- util/msys2_install.sh
This updates the MSYS install script to grab the newer  toolchain version AVR-GCC for Windows (version 5.4.0). 
Either way, I tested that it works (it does), and this version actually compiles a bit smaller in size, so it's a bit more efficient. And this should make sure that Travis shows the same size as MSYS systems.
> Update MSYS' AVR-GCC to use the 5.4.0 toolchain

- quantum/quantum.h
This is like #3784 for 16-bit keycodes.
At the moment we have `register_code`, `unregister_code`, `tap_code`; but only `register_code16` and `unregister_code16`. This completes the set by adding a `tap_code16` function.
> Add tap_code16 function

- tmk_core/protocol/chibios/usb_main.c
bug was causing lots of dropped events for me.
> fixed misplaced parenthesis in arm usb mouse send function

- tmk_core/protocol/lufa/lufa.c
If the keyboard has media keys or NKRO on, `SHARED_EP_ENABLE` is automatically enabled to merge them into a single endpoint (see #3951). The different interfaces are then identified by a unique report ID. However, the keyboard interface is by default not part of that shared endpoint unless `KEYBOARD_SHARED_EP = yes` in your rules.mk, and so it does not need a report ID.
The end result is that when LUFA tries to ask the host which LEDs to turn on, it expects there to be a report ID byte first, then the LED state. It will then set the report ID to the actual LED state, and no LEDs come on.
> Only try to read the report ID from SetReport when the keyboard is part of the shared EP

- keyboards/sixshooter/keymaps/default/keymap.c
- keyboards/sixshooter/sixshooter.c
- keyboards/sixshooter/sixshooter.h
Realized having them in the <keyboard>.c and <keyboard>.h file was problematic when setting up macros in keymaps.
> Updated sixshooter keyboard to move LED macros into the default keymap.

- keyboards/lets_split/keymaps/default/config.h
- keyboards/lets_split/keymaps/default/keymap.c
- keyboards/lets_split/keymaps/default/rules.mk
During the recent nori port, part of the review highlighted that the Lets split default keymap contained some legacy code.
Apply the review changes a92b03d1bbf4b0db647683953af4e785d3f36fe4 to the Lets split default keymap.
> Lets split default keymap - Fixes for superseded audio and default layer functionality

- keyboards/planck/keymaps/navi/config.h
- keyboards/planck/keymaps/navi/keymap.c
- keyboards/planck/keymaps/navi/rules.mk
Still something that needs to be worked with under keymap.c
Qwerty layer tap-toggle function seems to be a little laggy? Not instantaneous, need to look into this.
Was fixed through setting tapping_term to 0, but can't do that or else the Mod-Tap doesn't register the tapped key.
> Updated files to work with Planck Rev. 6

- keyboards/hs60/v1/keymaps/ansi/config.h
- keyboards/hs60/v1/readme.md
- keyboards/hs60/v1/rules.mk
WIth the caveat that the `60_ansi` layout needs a define to work properly.
@yiancar 
I'd like to be able to use the layout makefile stuff, but that's processed too late to be used by the keyboard's rules.mk.
> Allow HS60 to use Community Layouts

- tmk_core/protocol/arm_atsam/led_matrix.c
- tmk_core/protocol/arm_atsam/led_matrix.h
Wanted to experiment with a vertical animation on my keyboard, so I added a simple means of adjusting the orientation of an animation. This implementation should ensure that nobody's existing keyboards are affected while adding a simple means of toggling between horizontal and vertical animations; hopefully somebody else wants this and thinks it's worth merging?
Tagging this [WIP] for now because I can only make one direction of vertical animation work; anybody know why this would only work for defined bands scrolling downward and not upward?
> Vertical animation support for arm_atsam led_matrix

- keyboards/handwired/gamenum/gamenum.h
- keyboards/handwired/gamenum/info.json
- keyboards/handwired/gamenum/keymaps/default/keymap.c
- keyboards/handwired/gamenum/readme.md
- layout macro KEYMAP renamed to LAYOUT
- white space changes for alignment
- default keymap
- now uses #include QMK_KEYBOARD_H
- updated layout macro names
- white space changes (for readability)
- renamed file to lowercase
- updated to match current QMK template more closely
- edits to reflect the other changes in this PR
> handwired/gamenum Refactor, Configurator support and readme cleanup

- keyboards/alps64/alps64.h
- keyboards/alps64/keymaps/crd/keymap.c
- keyboards/dz60/keymaps/crd_ansi/keymap.c
In the process of updating my alps64 keymap to match conventions inspired by mechmerlin's dz60 keymap, I also attempted to use what I believe to be a more appropriate layout provided as `LAYOUT_aek_103`. However, I noticed that the layout provided uses an incorrect placement of a couple of keys on the bottom row. I have no sense for how many folks actually use this layout in the real world. I did a grep of the repository and the only other instance of it is an identical definition in the paladin64 tree. If I should rather add a new layout matching the AEK layout that I am using, I am happy to do so. FWIW, the key spacing of the `LAYOUT_aek_103` layout in the `info.json` file appears to match what I am using which is a bottom row of `1.5, 1.25, 1.5,    (space) 6.5,  1.5, 1.25, 1.5`.
Thanks …
> crd alps64 updates

- keyboards/helix/rev2/keymaps/froggy/keymap.c
Fixed a problem with underglow with froggy keymap
* Fixed a problem that keyboard stopped when underglow was used in helix's froggy keymap
> Fixed a problem with underglow with froggy keymap

- keyboards/handwired/nicekey/keymaps/default/keymap.c
- keyboards/handwired/nicekey/nicekey.h
- keyboards/handwired/nicekey/readme.md
Now uses a layout macro.
This keyboard will now be supported in the Configurator with this commit's changes.
- linked maintainer's GitHub account
- updated Docs links
> handwired/nicekey Refactor and readme cleanup

- keyboards/handwired/onekey/keymaps/default/keymap.c
- keyboards/handwired/onekey/onekey.h
- keyboards/handwired/onekey/readme.md
- keyboard now uses a layout macro (enables Configurator to compile for this keyboard)
- keymap now uses #include QMK_KEYBOARD_H
Updated Docs links.
> handwired/onekey Refactor and readme update 

- keyboards/lfkeyboards/lfk78/keymaps/ca178858/rules.mk
- keyboards/lfkeyboards/lfk78/keymaps/default/rules.mk
- keyboards/lfkeyboards/lfk78/keymaps/iso/rules.mk
- keyboards/lfkeyboards/lfk78/keymaps/split_bs_osx/rules.mk
- keyboards/lfkeyboards/lfk78/lfk78.c
- keyboards/lfkeyboards/lfk78/rules.mk
- keyboards/lfkeyboards/lfk87/keymaps/ca178858/rules.mk
- keyboards/lfkeyboards/lfk87/keymaps/default/rules.mk
- keyboards/lfkeyboards/lfk87/keymaps/gbchk/rules.mk
- keyboards/lfkeyboards/lfk87/keymaps/iso/rules.mk
- keyboards/lfkeyboards/lfk87/lfk87.c
- keyboards/lfkeyboards/lfk87/rules.mk
- keyboards/lfkeyboards/lfkpad/keymaps/default/rules.mk
- keyboards/lfkeyboards/lfkpad/rules.mk
- keyboards/lfkeyboards/mini1800/keymaps/ca178858/rules.mk
- keyboards/lfkeyboards/mini1800/keymaps/default/rules.mk
- keyboards/lfkeyboards/mini1800/mini1800.c
The keyboards need the `layer_info` const to be defined, but it was only defined in the keymap.  So when using the QMK Configurator, it would simply not work. 
Defining it weakly in the keyboard's c file fixes the compiler issue.
> Fix the LFKeyboards so they work with the QMK Configurator

- util/msys2_install.sh
On a laptop with god knows what mandatory security software (Cylance?), running up-to-date Windows 10 with msys2 mingw-64, attempting to install the AVR toolkit results in the following error:
```
1 [main] 7z (13316) C:\msys32\usr\lib\p7zip\7z.exe: *** fatal error - cygheap base mismatch detected - 0x612A5410/0x2375410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```
This appears to be related in some way, based on my research, to ASLR …
> adjust install_avr function to use unzip for broader compatibility

- keyboards/handwired/pilcrow/info.json
- keyboards/handwired/pilcrow/keymaps/default/config.h
- keyboards/handwired/pilcrow/keymaps/default/keymap.c
- keyboards/handwired/pilcrow/pilcrow.h
- keyboards/handwired/pilcrow/readme.md
- layout macro renamed from KEYMAP to LAYOUT
- keymap now uses #include QMK_KEYBOARD_H
- layers reformatted for readability
- removed unused and deprecated fn_actions and action_get_macro blocks
- keymap config.h
- updated to use #pragma once
- removed redundant config.h include
Updated readme.md file to use modern template formatting.
> handwired/pilcrow Refactor, Configurator support and readme update

- keyboards/zeal60/config.h
- keyboards/zeal65/config.h
Changing Zeal60/Zeal65 VID/PID to be unique, because 100+ other QMK keyboard implementations are using the same VENDOR_ID/PRODUCT_ID combination (0xFEED/0x6060). VIA Configurator uses VID/PID as the identifier of a device, so this avoids any confusion between Zeal60 PCBs and other QMK devices (with 0xFEED/0x6060) which may have enabled raw HID and/or have implemented VIA Configurator compatibility without changing VID/PID.
Obviously this change will break compatibility with VIA Configurator 0.2.6 and requires 0.2.7 and later, but since Zeal60/Zeal65 is still not officially supported yet, ¯\\\_(ツ)\_/¯
*
> Changing Zeal60/Zeal65 VID/PID to be unique

- keyboards/dichotomy/keymaps/alairock/keymap.c
Adding a keymap for the Dichotemy keyboard. It will now more closely resemble my keymap used on the minidox
*
> Dichotomy keymap by alairock

- docs/feature_advanced_keycodes.md
- docs/keycodes.md
- docs/keycodes_basic.md
- keyboards/handwired/reddot/keymaps/default/keymap.c
- keyboards/xd75/keymaps/germanized/config.h
- quantum/keymap_extras/keymap_belgian.h
- quantum/keymap_extras/keymap_bepo.h
- quantum/keymap_extras/keymap_canadian_multilingual.h
- quantum/keymap_extras/keymap_fr_ch.h
- quantum/keymap_extras/keymap_french.h
- quantum/keymap_extras/keymap_german.h
- quantum/keymap_extras/keymap_german_ch.h
- quantum/keymap_extras/keymap_hungarian.h
- quantum/keymap_extras/keymap_italian.h
- quantum/keymap_extras/keymap_nordic.h
- quantum/keymap_extras/keymap_slovenian.h
- quantum/keymap_extras/keymap_spanish.h
- quantum/keymap_extras/keymap_uk.h
- quantum/quantum.h
- quantum/quantum_keycodes.h
- tmk_core/common/keycode.h
At the moment, every language keymap that uses `ALGR` defines it separately. There's no need for this — `ALGR` should be a standard modifier definition in core code, and this PR makes it so. `ALGR_T` for mod tap already existed, so now a regular `ALGR` modifier exists too.
This PR also fixes inconsistencies in AltGr keycodes: some non-Nordic keymaps (namely: Belgian, French, Spanish, UK) used `NO_ALGR` instead of `BE_ALGR`, `FR_ALGR` etc.
Finally, this PR adds a standard alias `KC_ALGR` for `KC_RALT` that matches the aforementioned language-specific definitions. It also adds `SS_ALGR` for `SS_RALT`. This makes `ALGR` totally consistent with the `CMD` and `WIN` aliases for `GUI`.
> Add standard definitions for ALGR and KC_ALGR, fix inconsistencies

- docs/feature_rgblight.md
- keyboards/bigswitch/keymaps/333fred/config.h
- keyboards/bigswitch/keymaps/333fred/keymap.c
- keyboards/bigswitch/keymaps/333fred/rules.mk
- quantum/rgblight.c
- quantum/rgblight.h
The first commit adds a new versions of some of the common rgbled commands (increase/decrease_hue/sat/val, toggle, step(_reverse)) to not write to eeprom.
Commit 2 adds a keymap to bigswitch that consumes these new commands.
Note: Please rebase these and don't squash, they're intended to be separate as one's a feature and one's a keymap.
*
> Add noeeprom versions of rgbled functions and add a bigswitch map

- docs/config_options.md
- docs/feature_macros.md
- quantum/quantum.c
- quantum/quantum.h
- tmk_core/common/action.c
- tmk_core/common/action.h
* Moves `tap_code` to c files, since some compilers don't like the inline. 
* Adds a delay between registering and unregistering the keycodes (since some systems have issues)
* Adds documentation of this setting.
> Fix up tap_code functionality

- keyboards/tetris/config.h
- keyboards/tetris/keymaps/default/keymap.c
- keyboards/tetris/rules.mk
Reduce the file size and optimize the Tetris keyboard.
> Add some optimization to the Tetris keyboard

- docs/feature_audio.md
- docs/keycodes.md
> Docs: Clarify audio keycodes

- tmk_core/protocol/arm_atsam/usb/compiler.h
GNUC compilers greater than version 6 already have the macro __always_inline defined. This fix checks GNUC version before defining the macro itself.
* `tmk_core/protocol/arm_atsam/./usb/compiler.h:140: error: "__always_inline" redefined [-Werror]`
> Fix macro redefinition for GNUC compilers > 6

- keyboards/handwired/dactyl_manuform/readme.md
- keyboards/handwired/not_so_minidox/readme.md
- keyboards/handwired/xealous/readme.md
- keyboards/lets_split/readme.md
- keyboards/minidox/readme.md
- keyboards/orthodox/readme.md
This fixes incorrect paths to the split keyboard EEPROM files within the repo.
Other items for potential review:
- Should all references to eeprom files be updated to the full path `./quantum/split_common/eeprom-lefthand.eep` and `./quantum/split_common/eeprom-righthand.eep`?
- ~~Should this PR update the location within `./keyboards/lets_split/keymaps/bbaserdem/README.md`?~~ Not required
- ~~Should this PR remove the other eeprom files within `minidox` and `deltasplit75` so that the only eeprom files are within the common folder?~~ Not required
> Document the correct path to the split keyboard EEPROM files

- keyboards/fc980c/fc980c.h
Remove depreciated `#endif` from fc980c.h file, due to pragma once update.
> Fix fc980c.h update

- quantum/quantum.h
Cast output of `readPin()` to bool when using AVR, so that it matches the output for ChibiOS. This also fixes the issue of encoders not working probably with AVR, as `encoder.c` uses `readPin`.
* https://github.com/qmk/qmk_firmware/issues/4627
> Cast readPin output to bool for AVR to match ChibiOS

- keyboards/clueboard/60/keymaps/default/keymap.c
- keyboards/clueboard/60/keymaps/default_aek/keymap.c
- keyboards/clueboard/60/keymaps/yanfali/keymap.c
PROGMEM keyword was missing, prevented the firmware from running on my Clueboard 60% 1.0.1.
I read [some](https://www.nongnu.org/avr-libc/user-manual/group__avr__pgmspace.html#ga75acaba9e781937468d0911423bc0c35) [docs](https://www.arduino.cc/reference/en/language/variables/utilities/progmem/) docs but don't quite understand what the implications are here. Is the firmware bumping up against memory limits? Or did whatever is reading the keymap assume it was in program memory and hit an error at runtime?
* https://github.com/qmk/qmk_firmware/issues/4690
> Add PROGMEM keyword to Clueboard keymaps

- docs/config_options.md
- docs/feature_leader_key.md
- quantum/process_keycode/process_leader.c
- quantum/process_keycode/process_leader.h
Re-order the `process_leader` function so that it removes a redundant timer read, and make it a bit more orderly/optimized.
> Fix up process_leader to be a bit more optimized

- shell.nix
There was a bit of a cleanup recently in `nixpkgs`, causing most of the package names in `shell.nix` to be undefined. I've fixed that.
> shell.nix: Packages relocated in upstream cleanup

- util/linux_install.sh
The script currently uses a very convoluted, hacky and error-prone way of reading user input (y/n) when installing on Gentoo, which involves changing TTY settings. This changes it to a POSIX-compliant `read` call.
It also replaces the non-POSIX `echo -n` with `printf`, as well as fixing some inconsistent indentation.
> Read user input properly in linux_install.sh for Gentoo

- keyboards/s65_plus/info.json
Am I allowed to blame working on a 10" screen for the poorer quality of my pull requests since I went on vacation?
> S65-Plus: fix layout macro name in info.json

- tmk_core/common/action.c
- tmk_core/common/action.h
- tmk_core/common/action_layer.c
This allows pressed keys to stay pressed when a layer change occurs.
Say you're playing a game and you're holding W to run forward. You need to access a menu or skill that's bound to F4. You have that set on a momentary layer, so you try pressing Fn+4 — but as soon as you press Fn, QMK resets the W key and you stop moving forward, even though you're still holding the key.
For a visual explanation of the issue, see [this video](https://youtu.be/O4AKOX7F5SA?t=4h30m34s).
This fixes the problem by not resetting held keys when the layer state changes. It relies on the _prevent stuck modifiers_ implementation keeping track of which key was pressed on which layer and resetting them accordingly so that no keys end up stuck. As a consequence, it's disabled when `STRICT_LAYER_RELEASE` is defined, …
> Keep pressed keys on layer state change (fixes #2053, #2279)

- quantum/split_common/split_util.c
Travis CI is failing due to bug with split_common, that didn't appear to be caught initially (by Travis or myself). 
* Travis CI error
> Fix Split Common Split_util.c typo

- keyboards/whitefox/board_is31fl3731c.h
It seems the led_mask is set incorrectly on the WhiteFox meaning that the LED at C9-1 (the space bar) doesn't get lit.  I can't see any reason for this to be intentional so I am pretty sure it's a typo.  At the very least it fixes the space bar LED for me.
> Fix apparent typo in WhiteFox LED config

- quantum/process_keycode/process_leader.c
I think the rc of `process_leader` must be `true`, I recently added leader support in [my fork](https://github.com/grota/qmk_firmware/tree/grota/ergodoxez) but after flashing, the keyboard was unresponsive.  
* Fixes bug introduced in #4662
> Fix `process_leader` return code

- quantum/process_keycode/process_tap_dance.c
- quantum/process_keycode/process_tap_dance.h
This PR makes it so that the tap dance state struct also has the keycode responsible of the interruption.
I found it very useful to have that info in the finished/reset functions, see [here](https://github.com/grota/qmk_firmware/blob/c80eb9c1eaa89201c0f25dcd156281209a1f382f/layouts/community/ergodox/grota/tap_dance.c#L70) for an example.
Not sure if there's a saner way to do this.
> Register the interrupting keycode in the tap dance state struct

- keyboards/mxss/rgblight.c
- quantum/rgb_matrix.c
- quantum/rgb_matrix.h
- quantum/rgblight.c
- quantum/rgblight.h
`rgblight_get_mode()`'s return type right now is `uint32_t`, but upon inspection of its implementation, it's actually returning `rgblight_config_t.mode`, which is an `uint8_t`.  The return type should match `rgblight_config_t.mode`'s.  
I've grep'd through all the keymaps, there does seem to be a few places where `rgblight_get_mode`'s return value is being saved into another uint32_t variable.  These are probably be OK as they're just upcasting.
Also updating `rgb_matrix_get_mode` to return `uint8_t` for similar reason.
> Change rgblight_get_mode & rgb_matrix_get_mode's return type to uint8_t.

- keyboards/sol/rules.mk
The enables RGB, Mousekeys, and Extrakeys for
Sol owners using of config.qmk.fm
> Enable defaults for Sol

- quantum/split_common/matrix.c
- quantum/split_common/split_util.c
One tiny step towards refactoring split_common so it can be used by both AVR and ARM builds. This PR replaces the raw AVR gpio accesses with the generic QMK GPIO api calls. Functionality should be completely unchanged for existing users, but this needs verification.
This is just a starting point for discussion; as I see it to get split_common properly decoupled there are several significant issues that will require discussion/buy-in from other interested parties:
> Convert split_common to use generic GPIO api

- tmk_core/common/report.h
Change `BRIGHTNESSUP` to `BRIGHTNESS_UP` and `BRIGHTNESSDOWN` to `BRIGHTNESS_DOWN`.
This makes the constants' names consistent with their corresponding keycodes (`KC_BRIGHTNESS_UP`, `KC_BRIGHTNESS_DOWN`), as well as other constants defined in `report.h`. The changed constants are only used in this file, so this change shouldn't affect anything at all.
These constants were added in #4477.
> Add underscores to names of brightness control constants in report.h

- keyboards/fractal/fractal.h
- keyboards/fractal/readme.md
- keyboards/fractal/rules.mk
Removed KEYMAP alias for LAYOUT_preonic_mit. Alias was unused, and the terminology usage is deprecated.
Updated the line containing the documentation links in the readme.
> Fractal layout macro and readme cleanup

- docs/feature_unicode.md
- docs/getting_started_make_guide.md
- docs/keycodes.md
- docs/understanding_qmk.md
- quantum/process_keycode/process_unicode_common.c
- quantum/process_keycode/process_unicodemap.c
- quantum/process_keycode/process_unicodemap.h
- quantum/quantum_keycodes.h
Rename some constants and functions pertaining to UNICODEMAP so they're consistent with the rest of the system. Also update the documentation accordingly. See below for details.
These changes should be non-breaking. I've taken care to update all usages of the renamed symbols.
- Remove unused `UNICODE(n)` macro (alias for `UC(n)`, but no one was using it).
- Rename `QK_UNICODE_MAP` constant to `QK_UNICODEMAP` (only used internally).
- Rename `unicode_map_input_error` function to `unicodemap_input_error` (only used internally).
- Rename `process_unicode_map` function to `process_unicodemap` (only used internally).
**Reasoning:** `UNICODEMAP` is the name of the [keymap definition method](https://github.com/qmk/qmk_firmware/blob/1d200b607b4722e7f70af5668a8849a453fdb1a2/docs/feature_unicode.md# …
> Improve consistency in UNICODEMAP code and docs, update docs/understanding_qmk

- keyboards/ymd96/keymaps/epx/keymap.c
Add a keymap to YMD[K]96 keyboard. It is inspired on Model F, with arrow block activated by Num Lock. To be usable in Macs, Num Lock key toggles a layer instead of being sent to the computer. 
*
> Add Model F-inspired keymap to YMD[K]96 keyboard

- quantum/quantum_keycodes.h
- tmk_core/common/progmem.h
Add missing parentheses around arguments in macros like `LT`, `MO`, `TT`, `pgm_read_byte` etc.
This is done to prevent unintended grouping of operands due to operator precedence. Take the `MO` macro in its current state, for example:
```c
#define MO(layer) (QK_MOMENTARY | (layer & 0xFF))
```
Calling this macro with e.g. `MO(cond ? _RAISE : _LOWER)` would result in unexpected behavior. The macro would be expanded like so: `(QK_MOMENTARY | (cond ? _RAISE : _LOWER & 0xFF))`. Then, because of operator precedence, `_LOWER & 0xFF` would be grouped together, which likely isn't what was intended.
To fix this, we instead define `MO` as follows:
```c
#define MO(layer) (QK_MOMENTARY | ((layer) & 0xFF))
```
Same goes for
```c
#define pgm_read_dword(p) *((uint32_t*)p)
```
If we call that with …
> Add missing parentheses to some important macros

- docs/feature_advanced_keycodes.md
- docs/keycodes.md
- quantum/quantum_keycodes.h
- Reorganised the Mod-Tap shortcuts to all point to "base" definitions, eg. `CMD_T` → `LCMD_T` → `LGUI_T`.
- Renamed `ALL_T` to `HYPR_T` and added it as an alias (so that it doesn't break anything). In future `HYPR_T` should be preferred over `ALL_T`, and eventually the alias should be removed.
- Fixed a small typo in the alias list for `LGUI_T`.
None.
> Tidy up Mod-Tap shortcuts

- keyboards/kbd75/keymaps/edulpn/README.md
- keyboards/kbd75/keymaps/edulpn/keymap.c
75% Keymap for KBD75 with default ANSI layout + default layer switching for Windows and Mac "modes" (using `TG()`) + custom Fn layers for each mode
> Add KBD75 keymap

- keyboards/iris/keymaps/ave-63/config.h
- keyboards/iris/keymaps/ave-63/keymap.c
Added the folder keyboards/iris/keymaps/ave-63 and it's keymap.c and config.h files. The style is different than other iris keymaps, but more similar to chimera keymaps. I found it easier to read read and use this way. Features of this keymap:
--Lots of functionality on left hand for conjunction with mouse or pen in right hand
--_COMMAND layer ESDF arrow keys
--_MEH layer ESDF is super handy for switching tabs (SF) and apps (ED)
--_MEH layer other keys are linked with my AutoHotKey script
--macro for handling parentheses is very nice (credit: u/drashna)
Some things are very non-standard, like position of number keys, etc.
Will require heavy modification for most people.
* 
- [probably?] My code follows the code style of this project.
> Keymap: ave-63's iris layout

- keyboards/kbd67/readme.md
- keyboards/kbd67/rules.mk
QMK Configurator folk have no way to turn on the lighting feature. We can turn them on by default here and turn off the command enable to save space.
> Turn on KBD67 Lighting by default

- tmk_core/protocol/lufa/lufa.c
The status LEDs don't light up/light up incorrectly on Linux in certain circumstances. This is because, if NKRO is enabled it will send two LED states, one for the 6KRO interface, and one for the NKRO interface. QMK interprets the NKRO report ID as the LED state and turn on the num lock and scroll lock LEDs.
If we have two bytes, that probably means the first is a report ID. The 6KRO interface may or may not have one, but the NKRO interface always does, so we need to check this regardless of whether `KEYBOARD_SHARED_EP` is defined.
The status LEDs now function correctly on Windows 10, macOS 10.14 and Ubuntu 18.10 under the following conditions:
- `KEYBOARD_SHARED_EP=no`, `NKRO_ENABLE=no`
- `KEYBOARD_SHARED_EP=no`, `NKRO_ENABLE=yes`, NKRO off
- `KEYBOARD_SHARED_EP=no`, `NKRO_ENABLE=yes`, …
> Fix Caps Lock LEDs once and for all

- keyboards/gergo/info.json
Layout macro name in info.json was named LAYOUT instead of LAYOUT_GERGO as it is in gergo.h.
> Fix layout macro name for Gergo info.json

- keyboards/lets_split_eh/keymaps/resfury/config.h
- keyboards/lets_split_eh/keymaps/resfury/keymap.c
- keyboards/lets_split_eh/keymaps/resfury/readme.md
- keyboards/lets_split_eh/keymaps/resfury/rules.mk
This PR would add Colemak-based keymap with Dvorak/Qwerty support to the Let's Split, Eh.
This layout specializes the Let's Split, Eh for Colevrak users that occasionally let others play with their toys. Adjust layer allows swapping to Colemak/Dvorak/Qwerty alphas. Heavily influenced by the default planck layout, but with up/down switched, a left hand 10-key, remapped backspace, and a few convenience keys.
Master set by EE_HANDS method.
N/A
> Lets Split Eh - resfury keymap

- keyboards/ckeys/handwire_101/config.h
- keyboards/ckeys/handwire_101/handwire_101.c
- keyboards/ckeys/handwire_101/handwire_101.h
- keyboards/ckeys/handwire_101/info.json
- keyboards/ckeys/handwire_101/keymaps/default/config.h
- keyboards/ckeys/handwire_101/keymaps/default/keymap.c
- keyboards/ckeys/handwire_101/keymaps/default/readme.md
- keyboards/ckeys/handwire_101/readme.md
- keyboards/ckeys/handwire_101/rules.mk
- keyboards/ckeys/readme.md
Added the cKeys handwire keyboard that coincides with the cKeys Handwire 101 workshop. The default keymap is used as a teaching tool and introduction to QMK.
*  N/A
> Add cKeys Handwire 101 Keyboard

- keyboards/massdrop/ctrl/keymaps/responsive_pattern/keymap.c
[related issue](https://github.com/qmk/qmk_firmware/issues/4846)
[keymap.c](https://github.com/valen214/qmk_firmware/blob/master/keyboards/massdrop/ctrl/keymaps/responsive_pattern/keymap.c)
* 
Although only one file (`keymap.c`) is added, one core function (`tmk_core/protocol/arm_atsam/led_matrix.c (line 261): led_matrix_run()) is overridden. (`rgb_matrix_init_user()` also if you say)
> added custom led effect keymap.c for Massdrop/CTRL

- docs/keycodes.md
- tmk_core/common/keycode.h
Added aliases to tmk_core for OSX brightness controls (F13, F14)
closes https://github.com/qmk/qmk_firmware/issues/4750
> MacOS Brightness Alias

- quantum/process_keycode/process_terminal.c
This PR fixes issue described in  #4583
* Fixes #4583
> Allows Terminal to use ModTap/LayerTap keys

- keyboards/planck/rev1/config.h
- keyboards/planck/rev1/rules.mk
- keyboards/planck/rev2/config.h
- keyboards/planck/rev2/rules.mk
- keyboards/planck/rev3/config.h
- keyboards/planck/rev4/config.h
- keyboards/planck/rev5/config.h
Added Planck rev1 and rev2 hardware configs. They're both identical to the rev3 hardware, but will allow rev1 and rev2 owners to use e.g. `make planck/rev2:default` without needing to determine whether rev1 and rev2 are equivalent to rev3. An alias would probably be better, but I don't know how that would be implemented.
> Add Planck rev1 and rev2

- keyboards/duck/eagle_viper/v2/config.h
- keyboards/duck/jetfire/config.h
- keyboards/duck/lightsaver/config.h
- keyboards/duck/octagon/v1/config.h
- keyboards/duck/octagon/v2/config.h
Update IDs associated with Duck boards to uniquely identify them for future VIA support. Copy pasta all around has resulted in almost all QMK supported boards with the same vendor and product ids. 
*
> update VENDOR_ID, PRODUCT_ID, and DEVICE_VER for Duck boards

- docs/keycodes.md
- docs/keycodes_basic.md
Just a slight tweak to the changes in #4836:
- Added the new aliases to keycodes_basic.md as well
- Aligned the keycode tables again
- Removed the references to the new aliases in `KC_BRIU/D` - it makes them seem like they don't work on macOS. I'm pretty sure they work across the board.
And removed some extra newlines in keycodes.md.
None.
> Add new brightness aliases to keycodes_basic.md

- keyboards/handwired/ortho5x13/ortho5x13.h
Discovered the LAYOUT_compact macro didn't compile in QMK Configurator. Realized the reason for that was that it automatically prepends `KC_` to every keycode received.
Renamed the macro to LAYOUT_kc so Configurator will ignore it.
Also changed the file to use the #pragma once include guard because I was in here anyway.
> handwired/ortho5x13: layout macro refactor

- docs/internals_gpio_control.md
I found the Advanced Settings section to be poorly written.
> Grammatical fixes for GPIO Control doc

- keyboards/v60_type_r/rules.mk
Change `BOOTLOADER_SIZE` to 4096 so that the `RESET` keycode works.
> [Keyboard] Fix bootloader size for v60_type_r

- keyboards/helix/rev1/keymaps/OLED_sample/rules.mk
`keyboards/helix/rev1/keymaps/OLED_sample/rules.mk`  was removed by pull request #4462.
This is wrong.
> Fixed the build break of helix/rev1:OLED_sample caused by PR #4462.

- keyboards/snagpad/config.h
- keyboards/snagpad/keymaps/via/keymap.c
- keyboards/snagpad/keymaps/via/rules.mk
Added VIA Configurator support to Snagpad.
Approved by @flehrad 
Also demonstrates using a keymap directory called `via` to build a VIA compatible firmware, yet leaving the `default` and other keymap directories as-is, without the VIA magic (raw HID protocol, dynamic keymaps).
Tested on real hardware.
> Added VIA Configurator support to Snagpad

- docs/custom_quantum_functions.md
- tmk_core/common/host.h
I missed this while #4853 was open. Move the LED macros out of the function declarations to the top of the file, and make the macro arguments lowercase. Also use `#pragma once` instead of traditional include guards.
Remove unnecessary newlines from LED docs added by the aforementioned PR, fix some Markdown syntax issues, and tweak the wording a bit.
> Tidy up IS_{,HOST_}LED_{ON,OFF} macros

- keyboards/tada68/keymaps/rys/keymap.c
The ISO layout in my keymap wasn't actually ISO, so put KC_NUHS in the right place.
My ISO layout for the TADA68 had a key in the wrong place (KC_NUHS, next to KC_ENT on R3).
None.
> Fix for ISO layout in tada68:rys

- drivers/avr/i2c_slave.c
- drivers/avr/i2c_slave.h
- keyboards/dc01/arrow/matrix.c
- keyboards/dc01/numpad/matrix.c
- keyboards/dc01/right/matrix.c
The current i2c_master and i2c_slave driver have conflicting symbols. This commit renames the slave side so both can be linked in simultaneously. It also optimises RAM usage slightly (separate rx and tx buffers aren't needed), and fixes a couple of oddities (the variables were being instantiated in the header!?)
The only kbs that uses driver/avr/i2c_slave.c at present are dc01/arrow, dc01/numpad, dc01/right. I've updated them to build successfully against the updated API.
> Cleanup i2c_slave functions so it can coexist with i2c_master

- keyboards/tada68/keymaps/rys/keymap.c
- keyboards/tada68/keymaps/rys/readme.md
- keyboards/tada68/keymaps/rys/rules.mk
Emit a compile time provided `SEND_STRING()` macro on a new keycode, and assign it to `_FL`
Define a new keycode (`PSTOKEN`) and assign it to a key in the `_FL` layer. Assign `RESET` to `_FL` at the same time.
The associated `SEND_STRING()` macro emits a compile time defined string that we populate in `rules.mk`. This _only_ works on macOS, since it shells out to the macOS `security` utility, which securely fetches a string from the specified service name and account.
That avoids storing the string in the source code or in the clear anywhere on the filesystem. It also avoids changing any of QMK's makefiles, keeping the change local to my keymap. Since the keymap is macOS-specific due to left of spacebar key swaps, I figure the makefile changes being a bit macOS specific is OK.
I plan to …
> Add a compile-time provided macro and assign to _FL

- keyboards/handwired/datahand/config.h
- keyboards/handwired/datahand/datahand.h
- keyboards/handwired/datahand/keymaps/default/keymap.c
- keyboards/handwired/datahand/matrix.c
- keyboards/handwired/datahand/readme.md
- keyboards/handwired/datahand/rules.mk
- keyboards/readme.md
I have a DataHand keyboard in which I've replaced the stock processor with a [Teensy++ 2.0](https://www.pjrc.com/store/teensypp.html) in a similar manner to that described [here](https://geekhack.org/index.php?topic=12212.0). This PR adds a new `keyboard` to support this setup.
> Add support for Teensy-modified Datahand keyboard

- keyboards/bdn9/bdn9.c
- keyboards/bdn9/bdn9.h
- keyboards/bdn9/config.h
- keyboards/bdn9/keymaps/default/keymap.c
- keyboards/bdn9/readme.md
- keyboards/bdn9/rules.mk
> Add BDN9 Macropad

- keyboards/kbd67/hotswap/keymaps/default/keymap.c
- keyboards/kbd67/hotswap/rules.mk
- keyboards/kbd67/rev1/rules.mk
Users are not able to enter bootloader mode again to flash their boards after initial QMK flash. 
These boards actually have a hardware reset button on the back. Unfortunately the cases that these boards come in, do not have a hole to access said reset button. 
This change includes
- Setting `BOOTMAGIC_ENABLE` to `lite`
- Adding a second layer to the default keymap that has a `RESET` key under `R`.
> KBD67: enable bootmagic lite by default

- quantum/process_keycode/process_combo.c
- quantum/process_keycode/process_combo.h
Tested on Erogodx and Infinity Ergodox
> Fix process_combo which assign -1 to uint16_t

- tmk_core/common/keycode.h
Checks of the form `get_mods() & (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_RSHIFT))` are very common. This adds standard macros for mod masks so that they don't have to be specified manually, which makes user code shorter and clearer, and slightly reduces the chance for errors.
> Add MOD_MASK_* macros to core code

- quantum/quantum.c
- quantum/quantum.h
I think `quantum.h` should contain only API declarations that `quantum.c` provides externally. `rgb.h` contains function weak definitions. This should not be in `quantum.h`.
```
$ git checkout master
$ make lets_split:default:clean
$ make SILENT=true lets_split:default
$ grep -A1 rgblight_toggle .build/lets_split_rev2_default.map
.text.rgblight_toggle
0x0000000000000000  0x2 .build/obj_lets_split_rev2_default/keyboards/lets_split/lets_split.o
--
.text.rgblight_toggle
0x0000000000000000  0x2 .build/obj_lets_split_rev2_default/keyboards/lets_split/rev2/rev2.o
--
.text.rgblight_toggle
0x0000000000000000  0x2 .build/obj_lets_split_rev2_default/keyboards/lets_split/keymaps/default/keymap.o
--
.text.rgblight_toggle
0x0000000000000000  0x2 .build/obj_lets_split_rev2_default/quantum/quantum.o
-- …
```
> move `#include "rgb.h"` from quantum.h to quantum.c

- tmk_core/protocol/arm_atsam/led_matrix.c
- tmk_core/protocol/arm_atsam/led_matrix.h
It me, the animation person, here with a new animation PR! This time I'm adding another animation mode to the `arm_atsam` led matrix that animates the defined animation bands outward or inward in regard to the center of a keyboard.
Wanted to explore doing a circular animation out from a pressed key, but I don't know enough about support for animation triggers or getting their coordinates to do that so instead I decided to add a repeating circular animation (we could theoretically add variables to configure where the center is or modifier keys to adjust that if we wanted to). Advice on animation triggers and coordinates for key presses for a follow-up PR would be appreciated!
Forgive the potato quality, but here's a demo video:
> Circular animation

- tmk_core/common/avr/suspend.c
This is 100% my fault. 
Since I always want RGB Lights on (in a move that should surprise nobody here), I never botherer to check to see what would happen if the lights were not enabled first.  
As is, this means that if the sleep option is enabled, it will turn the lights on when waking, regardless of the previous setting.
This change should save the previous setting and only re-enable the lights if it was actually enabled previously. 
* Feedback from Ergodox EZ
> Fix RGBLIGHT_SLEEP function

- users/vosechu/config.h
- users/vosechu/readme.md
- users/vosechu/rules.mk
- users/vosechu/vosechu.c
- users/vosechu/vosechu.h
Add the vosechu.h/c userspace files. Nothing really interesting to see here, but it's the foundation of a bunch of other PRs I'm going to send in. 
**I would love help making sure this is the latest thinking!** Even though it works in my layouts, I am not well versed in the QMK way of thinking (yet!) so I would very much value feedback!
* None
> Add userspace files for vosechu

- keyboards/chimera_ergo/matrix.c
- keyboards/chimera_ls/matrix.c
- keyboards/chimera_ortho/matrix.c
- keyboards/comet46/matrix.c
- keyboards/dc01/arrow/matrix.c
- keyboards/dc01/left/matrix.c
- keyboards/dc01/numpad/matrix.c
- keyboards/dc01/right/matrix.c
- keyboards/dichotomy/matrix.c
- keyboards/handwired/promethium/matrix.c
- keyboards/kmac/matrix.c
- keyboards/kmini/matrix.c
- keyboards/mitosis/matrix.c
- keyboards/redox_w/matrix.c
- keyboards/sx60/matrix.c
- keyboards/telophase/matrix.c
- quantum/matrix.c
Wow, can't believe this wasn't spotted sooner!
* #2280
> Fix `1<col` instead of `1<<col` typo in matrix_is_on()

- keyboards/e6_rgb/keymaps/default/keymap.c
The E6_Rgb keyboard lacks a default keymap. 
Travis didn't error out on the board, so it didn't get noticed when merged. But causes errors globally, now. 
* Travis CI errors
> Add default layout for e6_rgb

- quantum/rgblight.c
In order to prolong the lifetime of eeprom, write of the same value is omitted.
> rgblight.c: Prevent wasteful writing to eeprom.

- docs/feature_backlight.md
- quantum/quantum.c
- tmk_core/common/avr/suspend.c
I've implemented this new option in backlight feature because my keyboard (S65-X) doesn't have LED indicators and the existing led_set_kb(usb_led) function try to use backlight as Caps Lock indicator but that creates an inconsistency with backlight_config state. Another bug, when suspending the power, the backlight stays on instead of turning off.
* define `BACKLIGHT_CAPS_LOCK` to enable Caps Lock indicator using backlight (for keyboards without dedicated LED). Default state : Not defined.
* Don't turn off LED indicators when suspend because backlight is already turned off. Else led_set(0) will turn back on backlight.
* Documentation has been updated
> Feature : Backlight - New option : BACKLIGHT_CAPS_LOCK

- keyboards/handwired/xealousbrown/config.h
It uses `keyboard_report->mods`, which is _\*Chyrosran voice\*_ unacceptableeee
The board was added in #4945
> Remove #define IS_COMMAND line in keyboards/handwired/xealousbrown/config.h

- keyboards/gray_studio/space65/readme.md
The current link is for Gray Studio's HB85 keyboard. As far as I can tell, the “Space65” spelling (no space) is used everywhere except for on this one line.
I also reworded the summary a bit to include some information from the GB page.
This board was added in #5001.
~~On another note, COD67 was also designed by Gray Studio; that board should probably be moved to the `gray_studio` directory as well.~~ Never mind, just saw #5002 😄
> Fix link and name spelling in Space65's readme

- keyboards/s65_x/config.h
- keyboards/s65_x/s65_x.c
* Replace buggy implementation of Caps Lock indicator using backlight with new backlight option `BACKLIGHT_CAPS_LOCK` (PR #4769)
* Adding `RGBLIGHT_SLEEP`
* Increasing `BACKLIGHT_LEVELS` from 3 to 5
Types of changes
* End of inconsistency between Caps Lock indicator and backlight state. There's was an inconsistency between backlight_config state and Caps Lock indicator so when toggling backlight sometime it doesn't turn off.
* Keyboard backlight turns off when Host is suspended.
> [Keyboard][S65-X] BACKLIGHT_CAPS_LOCK

- build_keyboard.mk
Cherry picked from #4947.
When performing parallel make, `make -jN` where N > 1, the size check `  * The firmware size is fine - 19458/28672 (9214 bytes free)` does not print out at the end. The change i have added to the make file adds a dependency to make sure it always happens after build.
Tested locally with:
- No -j
- -j2
- -j3
- -j4
> Fix file size check for parallel make

- quantum/keymap_extras/sendstring_german.h
German keyboards usually have, opposed to the standard keyboards, QWERTZ and not QWERTY. This was not reflected in the `sendstring_german.h` which caused the letters y and z to be exchanged when using sendstring. (E.g. if you wanted to send "pretty", "prettz" would come out)
This was very simple to fix by just exchanging KC_Y with DE_Y (=KC_Z) and KC_Z with DE_Z (=KC_Y)
* I didn't open an issue, since I had the fix on hand right away
> Fix QWERTZ <> QWERTY issue in sendstring_german.h

- keyboards/converter/adb_usb/rules.mk
- keyboards/converter/hp_46010a/rules.mk
- keyboards/converter/ibm_5291/rules.mk
- keyboards/converter/ibm_terminal/rules.mk
- keyboards/converter/m0110_usb/rules.mk
- keyboards/converter/palm_usb/rules.mk
- keyboards/converter/sun_usb/rules.mk
- keyboards/converter/usb_usb/rules.mk
- keyboards/converter/xt_usb/rules.mk
I noticed in #5035 that `rules.mk` files in `keyboards/converter/adb_usb`, `keyboards/converter/m0110_usb` etc. mix tabs and spaces heavily, and not in a good or meaningful way. This PR replaces all tabs in those files with spaces, since none of the tabs were semantic (i.e. part of a recipe), and we prefer to use spaces for visual indentation.
I also fixed typos in some of the build options, e.g. `LAYOUTS_HAS_RGB = NO` and `API_SYSEX_ENABLE = n`.
Finally, I improved the visual alignment and ordering of build options, made them consistent between file; and I added some newlines that were missing at EOF.
> Fix mixed tabs/spaces and typos in keyboards/converter makefiles

- Makefile
It didn't seem correct to me that `make clean` leaves the final firmware behind. Also useful when running `make all` for testing stuff.
* None.
> make clean should remove .bin and .hex too

- keyboards/tada68/keymaps/rys/keymap.c
- keyboards/tada68/keymaps/rys/rules.mk
Adds support for fetching another securely stored string from the macOS keychain, to emit in the firmware.
Fetch another secure string in `rules.mk` using the `security` binary on macOS, and emit that with a new keycode in the safe range.
Fixes a tiny alignment foible in the makefile rules too. OCD.
I also wrote about the basic process and the threat model on my blog, [here](https://rys.sommefeldt.com/post/securely-define-qmk-firmware-macros/)!
N/A
> Add another secure string emitter to the keymap

- keyboards/meishi/config.h
- keyboards/scarletbandana/config.h
- keyboards/sentraq/number_pad/config.h
- tmk_core/protocol/usb_hid/test/config.h
These made it past code review in #3397, #5047, #5054. Merlin also removed the definition in the Scarlet Bandana keyboard in #5058, but since the diffs are compatible there shouldn't be any conflicts between that PR and this one (I've double-checked and confirmed that this is the case, so this can be merged without any problems).
> Remove unnecessary IS_COMMAND definitions in recently added keyboards

- keyboards/preonic/keymaps/default/keymap.c
The function had the wrong name & arguments. This commit fixes this.
This in turn should also close issue #4997
* #4997
> Fixed default Preonic keymap's encoder handling

- quantum/keymap_common.c
This updates Layer Mod (`LM`) to properly respect the bootmagic configuration (`AG_SWAP`, and NO_GUI options), by properly processing them. 
Right now, both of these features lack the code to handle the bootmagic configuration, and as such, completely fail to respect the settings.  This simply adds the `mod_confg` function call to process this correctly. 
* Fixes #4263
> Fix Mod Handling for LM keycodes

- keyboards/quefrency/keymaps/default65macro/config.h
- keyboards/quefrency/keymaps/default65macro/keymap.c
- keyboards/quefrency/rev1/rev1.h
Adds support for new left half of Quefrency with 2x5 macro section. Backwards compatible with other Quefrency halves.
*
> Add support for Quefrency left half with 2x5 macro section

- keyboards/gray_studio/space65/config.h
- keyboards/gray_studio/space65/rules.mk
Turn off console/command in favor of the more commonly requested RGB Animation for default usage in QMK Configurator.
> Space65: RGB Animations on by default

- keyboards/plain60/config.h
- keyboards/plain60/keymaps/RGB/config.h
- keyboards/plain60/keymaps/RGB/keymap.c
- keyboards/plain60/keymaps/RGB/rules.mk
Fixes an error with the Plain60 PCB when compiling QMK without VIA support enabled and also adds a new RGB keymap as an example how to enable RGB for the board (if you have soldered a WS2812b strip to it)
* None
> Plain60 rgb

- keyboards/aeboards/aegis/aegis.c
- keyboards/aeboards/aegis/aegis.h
- keyboards/aeboards/aegis/config.h
- keyboards/aeboards/aegis/keymaps/default/keymap.c
- keyboards/aeboards/aegis/keymaps/default/readme.md
- keyboards/aeboards/aegis/keymaps/via/keymap.c
- keyboards/aeboards/aegis/keymaps/via/readme.md
- keyboards/aeboards/aegis/keymaps/via/rules.mk
- keyboards/aeboards/aegis/readme.md
- keyboards/aeboards/aegis/rules.mk
> Added aeboards/aegis

- util/travis_compiled_push.sh
Looks like Travis/Trusty doesn't like the `mv` command I used:
```
util/travis_compiled_push.sh: line 73: syntax error near unexpected token `('
```
I think this should work properly. Or, at least, it doesn't error out on my local branch.
> Fix travis_compiled_push.sh script issue

- keyboards/planck/keymaps/buhearns/config.h
- keyboards/planck/keymaps/buhearns/keymap.c
- keyboards/planck/keymaps/buhearns/readme.md
- keyboards/planck/keymaps/buhearns/rules.mk
Adding buhearns personal keymap.
*
> [Keymap] Adding buhearns keymap

- keyboards/kbdfans/kbd19x/kbd19x.c
- keyboards/kbdfans/kbd19x/kbd19x.h
- keyboards/kbdfans/kbd19x/readme.md
- keyboards/kbdfans/kbd19x/rules.mk
Responding to R_InvestCantReadGood on the #help channel of QMK Discord. KBD19x QMK port had the space+b disabled due to Bootmagic being set to `no`. 
Fixes implemented:
- bootmagic set to lite
- use pragma once in kbd19x h file
- found a compile issue when compiling default keymap. Realized led functions were not properly externed in the .c file. 
- lots of space left, might as well turn on mousekeys.
> KBD19x Bootmagic Enable (lite) and other fixes

- keyboards/kc60/keymaps/noroadsleft/keymap.c
- keyboards/kc60/keymaps/noroadsleft/readme.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch1.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch2.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch3.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch4.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch5.md
- keyboards/kc60/keymaps/noroadsleft/readme_git.md
Updates to my KC60 keymap.
Create a keycode that is normally Z, but KC_NUBS when tapped while Alt is being held.
This removes the possibility of using an Alt+Z shortcut.
Modify NUBS_Z macro to only use alternate operation if Right Alt is being held, rather than responding to either Alt key.
Also add QMK version keycode to System layer, Equals key.
- removed G_RST and G_C10R macros
- updated G_BRCH macro
- outputs `master` if used while Shift is held down; or my git alias for the current branch otherwise
- updated G_FTCH macro
- outputs `git pull upstream ` if used with Shift; `git fetch upstream ` otherwise
- swapped `modifiers` variable for `get_mods()` function directly for checking modifier state
- swapped keymap-level modifier mask macros for QMK-core mod mask macros (thanks …
> Updates to noroadsleft keymap for KC60

- keyboards/kbdfans/kbd75/rev1/rev1.c
- keyboards/kbdfans/kbd75/rev2/rev2.c
So that the LED indicator actually works
Specifically, the keyboard sets the pin high/low to set the LED, but never actually sets the output mode, so it doesn't work. 
* Fixes #5118
> Add pin initialization for KBD75's LED

- quantum/audio/audio_arm.c
- quantum/process_keycode/process_clicky.c
While investigating a bug with Audio Click on ARM... I ran into the fact that ARM Audio was never actually updated to persist in EEPROM storage!  The code was there, but commented out.
I've updated the audio code to support EEPROM if STM32 EEPROM support is enabled, as well as fixed the clicky issue on ARM. 
I've also updated the files that I've touched to conform to the QMK Coding conventions, but I can revert those changes if needed. 
I've also employed Drashna CI to ensure that these changes work. And from what I can tell, yes they do.
> Fix ARM Audio issues and its EEPROM persistence

- build_keyboard.mk
- build_layout.mk
- docs/feature_layouts.md
I use a nori as a 4x12 keyboard and 4x4 macro pad, and have community layouts for both. [Branch here](/zvecr/qmk_firmware/tree/feature/zvecr-keymap)
```bash
vagrant@vagrant:/vagrant$ ls layouts/community/*/zvecr
layouts/community/ortho_4x12/zvecr:
config.h  keymap.c  readme.md  rules.mk
layouts/community/ortho_4x4/zvecr:
config.h  keymap.c  readme.md  rules.mk
```
Currently there is no way to build both keymaps and `make 40percentclub/nori:zvecr` builds whatever it finds first, in this case ortho_4x12.
So far, i have added an additional flag that allows a particular keymap to be targeted
```
make 40percentclub/nori:zvecr FORCE_LAYOUT=ortho_4x4
make 40percentclub/nori:zvecr FORCE_LAYOUT=ortho_4x12
````
~~TBD~~
- ~~What docs would need updating?~~ done
- ~~Should the filename contain the …
> Add a mechanism for force building a particular community layout

- keyboards/converter/ibm_terminal/keymaps/default/rules.mk
- keyboards/converter/ibm_terminal/rules.mk
- keyboards/converter/palm_usb/rules.mk
- keyboards/converter/sun_usb/rules.mk
- quantum/process_keycode/process_unicodemap.c
- quantum/process_keycode/process_unicodemap.h
The weak `unicode_map` stub definition in `process_unicodemap.c` is unneeded and it causes errors when building with LTO enabled.
This definition is unneeded because `unicode_map` is supposed to be an external symbol that the user provides. Furthermore, you would want the build to fail if the user has `UNICODEMAP_ENABLE` on but hasn't defined `unicode_map`; having the stub definition prevents that and may lead to undefined behavior.
Essentially, much the same way you don't see `keymaps` defined anywhere in `quantum` or `tmk_core`, only declared with `extern`; so too should `unicode_map` only be declared in `process_unicodemap.h` and not defined anywhere in core code, only by the user.
This is the error that it causes when building with `-flto`:
<pre><details>
<summary>make …
> Remove problematic unicode_map stub definition in process_unicodemap.c

- keyboards/kbdfans/kbd75/rev1/rev1.c
- keyboards/kbdfans/kbd75/rev2/rev2.c
It appears that the Caps Lock LED on the KBD75 is wired in current sink configuration (see #5118). Therefore pulling the pin *low* when Caps Lock is on results in the LED lighting up.
* None.
> Swap KBD75 caps lock LED pin levels

- tmk_core/chibios.mk
For following directory structure:
```
ls ./qmk_firmware/lib/chibios/os/hal/ports/STM32/STM32L4xx/
platform.mk
platform_l432.mk
```
This pull request enable to custom the correct platform makefile by add
```PLATFORM_NAME = platform_l432``` into the rules.mk
> Enable custom chibios sub-platform

- quantum/rgblight.c
- quantum/rgblight.h
* Add out of bound checks for initialization, and eeprom writing.
* Add run guard (?) so rgblight_init only runs once.
* This should allow users to call it in matrix_scan_user and not overwrite the values.
* Can set `is_rgblight_initialized` to false to re-initialize, if needed.
> Improve RGB Light code

- docs/getting_started_build_tools.md
- util/docker_build.sh
Taken from #5063. Runs the container in interactive mode so the build can be interrupted with Ctrl+C. No downsides.
Also add a message to the script recommending QMK Toolbox for flashing on Mac and Windows. Tweak the Docker docs as well.
> docker_build.sh: Run container in interactive mode

- docs/feature_rgblight.md
- quantum/rgblight.c
- quantum/rgblight.h
This patch adds support for controlling continuous ranges of RGB LEDs.
Helper functions for split boards are also available.
New functions are also present in the documentation.
> Add support for using ranges for RGB

- docs/feature_advanced_keycodes.md
Based on conversation with Drashna on Discord, we know that if ONE_SHOT_TAP_TOGGLE is 5, then tapping a one shot mod key 5 times holds the one shot key permanently, but to come out of this, you need to press the same key only once.
*
> Fix documentation about one shot tap toggle

- keyboards/tada68/keymaps/mattgemmell/keymap.c
- keyboards/tada68/keymaps/mattgemmell/readme.md
- keyboards/tada68/keymaps/mattgemmell/rules.mk
- keyboards/tada68/keymaps/rys/keymap.c
Adds a new layout for the TADA68. It's similar to my `rys` layout where the main feature is `KC_LALT` and `KC_LGUI` swapped to work better on macOS, and it has tested fine on a brand new TADA68 build I'm giving away to someone. I'm starting the layout for him to work on and customise later!
> [keymap] Add new keymap for TADA68

- users/bbaserdem/bbaserdem.h
- users/bocaj/process_records.h
- users/gordon/gordon.h
- users/ishtob/ishtob.h
- users/losinggeneration/losinggeneration-common.h
- users/mtdjr/mtdjr.h
- users/not-quite-neo/nqn-common.h
- users/replicaJunction/replicaJunction.h
- users/romus/romus.h
- users/talljoe/talljoe.h
- users/zer09/zer09.h
A small diversion from the fn_actions stuff. I'm hoping the reason this hasn't been done yet is because no one's had the time 😄
* None.
> Remove redundant KC_TRNS and KC_NO fillers in userspace

- keyboards/wilba_tech/wt8_a/keymaps/rys/keymap.c
- keyboards/wilba_tech/wt8_a/keymaps/rys/rules.mk
New user keymap for the WT8-A using the same macOS-only `security`-based macro method from [my TADA68 layout](https://github.com/qmk/qmk_firmware/tree/master/keyboards/tada68/keymaps/rys). 
Adds a new keymap for the WT8-A with all 4 possible layers in place for future use, but only the base layer programmed with anything. 4 `security`-based `SEND_STRING` macros, macOS vol+-, and a macOS-specific screen lock define called `MACOSLK`.
Tested on a Singa Ocelot.
> [keymap] Add new keymap for wilba_tech WT8-A

- layouts/community/ergodox/adam/keymap.c
- layouts/community/ergodox/belak/keymap.c
- layouts/community/ergodox/familiar/keymap.c
- layouts/community/ergodox/haegin/keymap.c
- layouts/community/ergodox/meagerfindings/keymap.c
- layouts/community/ergodox/xyverz/keymap.c
- layouts/community/ortho_4x12/bakingpy/keymap.c
- layouts/community/ortho_4x12/colemak_mod_dh_wide/keymap.c
- layouts/community/ortho_4x12/crs/keymap.c
- layouts/community/ortho_4x12/ergodoxish/keymap.c
- layouts/community/ortho_4x12/grahampheath/keymap.c
- layouts/community/ortho_4x12/mindsound/keymap.c
- layouts/community/ortho_4x12/symbolic/keymap.c
- layouts/community/ortho_4x12/xyverz/keymap.c
- layouts/community/ortho_5x12/xyverz/keymap.c
- layouts/default/numpad_5x4/default_numpad_5x4/keymap.c
- layouts/default/ortho_5x4/default_ortho_5x4/keymap.c
> Remove redundant KC_TRNS and KC_NO fillers in layouts

- keyboards/planck/keymaps/oeywil/.gitignore
- keyboards/planck/keymaps/oeywil/config.h
- keyboards/planck/keymaps/oeywil/keymap.c
- keyboards/planck/keymaps/oeywil/readme.md
- keyboards/planck/keymaps/oeywil/rules.mk
> Planck Keymap for oeywil

- keyboards/crkbd/keymaps/omgvee/config.h
- keyboards/crkbd/keymaps/omgvee/keymap.c
- keyboards/crkbd/keymaps/omgvee/rules.mk
- flags for the linker
- added INSERT key as I kinda use it for work fairly often
- turned on more things in rules.mk since I recovered space via linker
flags and whatnot
Checking file size of crkbd_rev1_omgvee.hex                                                         [OK]                                                                                                                                                                         * The firmware size is fine - 27168/28672 (1504 bytes free)
--
*
> [omgvee:crkbd] minor keymap changes and fw size optimizations

- docs/newbs_testing_debugging.md
Now that #3113 has been merged, there is a nice programmatic way to toggle debug modes. This is useful when debugging matrix scan issues, where you cannot rely on keycodes/key presses.
**Note:** `keyboard_pre_init_user` still does not allow the same method, however i have [this commit](/zvecr/qmk_firmware/commit/ec051765b2b72617355d1c7877709e400ac4d2f0) that could fix it. The main issue is that `keyboard_pre_init_user` runs before `magic()` in `keyboard_init`
setting anything to do with the debug_x variables in matrix_init_user gets reset by whats in eeconfig_read_debug a little later. It looks like quite a common pattern in the keyboards folder, and these would all be broken... but i'm guessing they may have been from before the magic init code was introduced
> Add docs on using keyboard_post_init_user to enable debug modes

- quantum/keymap_extras/sendstring_uk.h
Implements the correct LUTs for `SEND_STRING()` to use with UK keymaps.
Implements the `ascii_to_shift_lut` table and the `ascii_to_keycode_lut` table for UK keymaps, which the `SEND_STRING()` macro eventually calls into when it gets to `send_char()`.
Tested on a Singa Ocelot using a string that contains the characters that are different between the US ASCII keymap and what a UK keymap would type (`@` and `"`).
There's no documentation for keymap_extras yet, but I'm happy to add this to it if needed, when it shows up.
> Add UK variant of the SEND_STRING() LUTs to keymap_extras

- docs/faq_build.md
Document ARM EEPROM issues in FAQ
Provide guidance for users of ARM based QMK boards
*
> [Docs] Add section about EEPROM on ARM

- quantum/process_keycode/process_clicky.c
When I was trying to fix some issues on ARM, I added a check to `clicky_play` to make sure that it only clicked when audio was enabled.  But I apparently missed the exclamation mark, and hard disabled it....
*
> Fix Audio Clicky

- quantum/audio/audio_arm.c
If there is no song and audio is disabled, do this to prevent continous tone from playing
> On ARM, run stop_all_notes on startup

- docs/feature_rgb_matrix.md
Fix compiling problems with the default settings in the documentation #3797.
Firmware does not compile with DRIVER_COUNT 1
The calculation for the matrix position is wrong
```
x = 224 / ( NUMBER_OF_ROWS - 1 ) * ROW_POSITION
y = 64 / (NUMBER_OF_COLS - 1 ) * COL_POSITION
```
NUMBER_OF_ROWS and NUMBER_OF_COLS should be switched
```
x = 224 / ( NUMBER_OF_COLS - 1 ) * ROW_POSITION
y = 64 / (NUMBER_OF_ROWS - 1 ) * COL_POSITION
```
In [qmk_firmware/keyboards/planck/light/light.c](https://github.com/qmk/qmk_firmware/blob/master/keyboards/planck/light/light.c#L86)
x         = 224 / ( NUMBER_OF_COLS - 1 )
20.36 = 224/ (12-1)
```
...
{{0|(0<<4)},   {20.36*0, 21.33*0}, 1},
...
```
*  #3797
> [Docs] Fix typo in RGB Matrix Driver configuration

- docs/config_options.md
Descriptions for B5_AUDIO, B6_AUDIO, and B7_AUDIO under Hardware Options were partially italicized when parsed by Docsify, though rendered as intended by GitHub.
> Markdown cleanup on Config Options doc

- keyboards/hs60/v2/config.h
This pull request fixes a bug where the keymap for the the top left key (usually escape) would be overwritten by the config for the rgb-backlight when it was written to the EEPROM. This would render the key unusable as the first byte of the keymap seems to be overwritten with the last byte of the backlight config. This is fixed by offsetting the keymap and everything there after by moving it by one byte
1. Flash the [current version](https://github.com/qmk/qmk_firmware/commit/b6e1e6aeeb2e2affce36a302ae0e14c07c8772c8)  of HS60 V2 ANSI to the board  `make hs60/v2:ansi:dfu-util`
2. The escape key should be working as expected
3. Change backlight effect/hue/brightness
4. The escape key will no longer be responsive, layer 2+ and the escape key still works fine.
5. Reset the EEPROM `Unplug -> …
> fix: Make escape work after changing the backlight settings on the HS60 V2

- keyboards/tetris/rules.mk
The `tetris:default` keymap rests just a few bytes below its maximum, such that even small overheads of new features (e.g `eeconfig` additions) push it over the limit.
Disabling default audio for this keyboard frees up a few thousand bytes while allowing those that want it to easily re-enable it.
The keyboard owner @YCF may also make additional size updates further on.
> Reduce tetris firmware size by disabling default audio

- docs/newbs_flashing.md
Fixed references to a "built" (sic) command, and an incorrect word.
> Grammar cleanup of Flashing Your Keyboard Newbs Guide

- docs/faq_keymap.md
- docs/feature_advanced_keycodes.md
- docs/feature_macros.md
- docs/hand_wire.md
- docs/keymap.md
- docs/porting_your_keyboard_to_qmk_(arm_and_other_chibios_cpus).md
- docs/understanding_qmk.md
Many instances in the QMK Docs referenced KEYMAP macros, which is outdated terminology.
Replaced most instances of KEYMAP with LAYOUT, to reflect the desired usage.
> Replace instances of KEYMAP with LAYOUT

- quantum/rgblight.c
Changed `RGBLED_RAINBOW_SWIRL_INTERVALS` in rgblight_effect_breathing () to `RGBLED_BREATHING_INTERVALS`.
@chrislewisdev
I think this is a simple careless mistake. Is this correct?
> fix rgblight_effect_breathing interval time

- keyboards/candybar/rules.mk
Binaries compiled at config.qmk.fm are oversized for the MCU. Adjusting
default options to compensate.
> Candybar: adjust rules.mk defaults

- keyboards/handwired/dactyl_manuform/5x6/keymaps/333fred/keymap.c
- users/333fred/333fred.c
- users/333fred/333fred.h
Small update to my keymap adding a tap-dance for copying and pasting in both terminal and non-terminal scenarios.
> Added a key to handle copy/paste in and out of a terminal

- quantum/quantum_keycodes.h
#4939 messed up some of the indentation in `quantum/quantum_keycodes.h`. This fixes that.
> Fix indentation in quantum_keycodes.h

- keyboards/atreus/keymaps/default/keymap.c
`lower` layer of the Atreus default keymap had a down arrow keycode where the layer comments describe a Page Down key.
*
> atreus default keymap `pagedown` didn't match comment instructions

- keyboards/hs60/v2/info.json
I noticed the keyboard name and maintainer were incorrect in the HS60v2 info.json file, they have been updated now.  Let me know if your standard for "versions" are different, HS60V2 or HS60v2, or something else. 
*
> Corrected HS60 v2 keyboard name in info.json

- keyboards/keebio/quefrency/rev1/config.h
Fix pinout for Quefrency left half with 2x5 macro.
*
> Fix pinout for Quefrency left half w/macros

- keyboards/hs60/v2/keymaps/iso_andys8/keymap.c
- keyboards/hs60/v2/keymaps/iso_andys8/readme.md
Adding an additional keymap, having a vim function layer on top of the default ISO keymap.
> HS60 v2 ISO layout andys8

- docs/contributing.md
- quantum/template/avr/config.h
- quantum/template/avr/readme.md
- quantum/template/avr/template.c
- quantum/template/base/keymaps/default/config.h
- quantum/template/base/keymaps/default/keymap.c
- quantum/template/base/template.h
- quantum/template/ps2avrgb/template.c
- util/new_project.sh
Currently the keyboard generator script decides what your name is for you. Now it will ask :^)
`REPLACE_WITH_YOUR_NAME` has been changed to `%YOUR_NAME%` and will be substituted in:
- config.h (Copyright header and `MANUFACTURER`)
- readme.md (Maintainer link text, but not GitHub username)
- *keyboard*.c (Copyright header)
- *keyboard*.h (Copyright header)
- keymaps/default/config.h (Copyright header)
- keymaps/default/keymap.c (Copyright header)
*
> Ask for your name when generating a new keyboard

- keyboards/preonic/keymaps/bucktooth/keymap.c
- keyboards/preonic/keymaps/bucktooth/readme.md
Updated layout slightly for better compatibility with sculpted
(row-specific) profile keysets.
Fix build error on rev 3 toolchain; click waits don't seem to be
necessary anymore.
Over time I found that it was hard to move to sculpted keysets with this layout. I moved a few keys to make this better.
Compiling for my rev3 failed because of lack for a prototype for a time wait function. I removed some calls to wait before creating bleeps since I didn't think they were necessary now anyway.
*
> Bucktooth 2.0 key layout for Preonic

- keyboards/planck/keymaps/juno/config.h
- keyboards/planck/keymaps/juno/keymap.c
- keyboards/planck/keymaps/juno/readme.md
- keyboards/planck/keymaps/juno/rules.mk
- keyboards/preonic/keymaps/juno/config.h
- keyboards/preonic/keymaps/juno/keymap.c
- keyboards/preonic/keymaps/juno/readme.md
- keyboards/vitamins_included/keymaps/juno/keymap.c
- keyboards/vitamins_included/keymaps/juno/rules.mk
My personal keymaps for Planck, Preonic and the Vitamins Included version of Let's Split.
- [ X] Keymap/layout/userspace (addition or update)
* 
- [X ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
> Added personal keymaps for Planck, Preonic, Vitamins Included by Juno

- docs/feature_unicode.md
Using Unicode Hex Input has a side effect of disabling the option arrow key combos in OSX. This took me a while to understand, so I thought I'd make a note of it here to save anyone else the headache.
The diff will explain better than more description here.
* 
- [n/a] I have added tests to cover my changes.
- [n/a] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
> Add note about using Unicode Hex Input

- keyboards/ergodox_ez/keymaps/steno/keymap.c
- keyboards/ergodox_ez/keymaps/steno/rules.mk
AFAIK this was the first layout to use a steno mode, and I think the keymap_steno was derived from it. But it was never changed to use keymap_steno.h.
* None
Currently these changes break the layout due to #4578. When changing to Gemini mode, it works. 
Since this might be used as a copy template, I think it is better to have it changed to use keymap_steno.h. 
You might consider waiting until #4578 is fixed before accepting this pull request, though.
> Use steno mode from base

- quantum/audio/song_list.h
I added two songs I use to song_list.h. 
First is FF_PRELUDE, which is the opening music to most Final Fantasy games.  
Second is TO_BOLDLY_GO, which from the main themes of Star Trek TNG and the original series.
It didn't seem like there was any sort of order to the list of songs, so I just added my two at the very end. Sorry if I missed something there.
*
> Added two songs to song_list.h

- users/mechmerlin/changelog.md
- users/mechmerlin/config.h
Looks like I broke some of the mechmerlin community layouts when it came to rgb lights. This should fix it by checking for RGBLIGHT_ENABLE before actually using `#define RGBLIGHT_ENABLE`.
> Fix rgblight_enable ifdefs in my userspace

- keyboards/converter/usb_usb/custom_matrix.cpp
This change adds the matrix_scan_kb and matrix_scan_user calls to the custom matrix_scan for usb-usb converters. I needed this to make the Leader key code work.
* Leader key and other things dependent on matrix_scan_user did not work.
> [Keyboard] Add support for matrix_scan_user to usb-usb converter

- keyboards/40percentclub/foobar/info.json
More clean-up tasks pertaining to the API and QMK Configurator.
Checking was prompted by a report from @i5ar in #4098.
For reference:
- https://github.com/qmk/qmk_firmware/issues/4098#issuecomment-469055391
- https://github.com/qmk/qmk_firmware/issues/4098#issuecomment-469081332
> Correct keyboard and layout dimensions for 40percent.club Foobar

- docs/custom_quantum_functions.md
The custom_quantum_functions docs currently read:
* Keyboard/Revision: `void uint32_t layer_state_set_kb(uint32_t state)`
`void uint32_t` is not a valid type, and I am inferring here that the correct type is uint32_t since that is what the _user function uses.
> Docs: fix a function signature

- quantum/audio/audio.c
- quantum/audio/audio_arm.c
- quantum/audio/audio_pwm.c
The `play_notes` function takes a `uint16` as the parameter for the length of the song, but the loop playing it uses a `uint8` as a counter, which will overflow on songs longer than 256 notes and loop even when `n_repeat` is `false` (and only play the first 256 notes of the song)
If anyone needs a long song to test this with (I've done this on my preonic rev3) this monstrosity exists https://github.com/inve1/qmk_firmware/blob/mrco/quantum/audio/song_list.h#L507
Anyway.. thanks for the cool firmware
> Fix playback of long songs

- keyboards/minidox/keymaps/dustypomerleau/keymap.c
Switch to using `register_code16()` and rename tapdance keys to match the `left` and `right` terminology preferred in QMK.
*
> Keymap update: Use `register_code16()` and its variants in lieu of separate mod registration

- users/stanrc85/stanrc85.c
- users/stanrc85/stanrc85.h
- Better reset_keyboard() code in KC_MAKE macro
- Removed duplicate MOD_MASK entries
*
> [Keymap] Smarter KC_MAKE code and removed duplicate MOD_MASK entries

- Makefile
There's no need to fetch the entire submodule history if we only need the latest revision.
Speeds up the download a fair bit.
> Shallow clone submodules.

- keyboards/crkbd/keymaps/thefrey/README.md
- keyboards/crkbd/keymaps/thefrey/config.h
- keyboards/crkbd/keymaps/thefrey/keymap.c
- keyboards/crkbd/keymaps/thefrey/rules.mk
Added my personal keymap for the CRKBD. It's a simple keymap with n-key rollover enabled, and a bunch of useful additions for programming (especially lisp, and especially in emacs). 
I've added a README for the layout with an image detailing it as well.
N/A
> Add personal keymap for crkbd

- keyboards/40percentclub/half_n_half/config.h
- keyboards/40percentclub/half_n_half/half_n_half.h
- keyboards/40percentclub/half_n_half/rules.mk
@Boy-314 raised on Discord,
> can someone check what's wrong with my half_n_half port?
>
> i flashed both halves pro-micro with the same hex file and only the left spacebar works
The issues are as follows
- Split keyboard not configured
- Also configured to force SERIAL as the board does not support I2C
- COL2ROW diode configuration required
> Fix diode and split keyboard configuration for 40percentclub/half_n_half

- tmk_core/avr.mk
Currently, running with :avrdude as a target will monitor /dev/tty* for the appearance of a new device, then sleep for one second, then launch avrdude to flash the keyboard.
For reasons that I haven't yet determined, that one-second sleep is insufficient on my system. `/dev/ttyACM0` appears with root:root ownership, and it takes udev a good 2.5 seconds or so to change its permissions to root:dialout, giving my normal user write access. This causes avrdude (and make) to exit with an error most of the time:
```
avrdude: ser_open(): can't open device "/dev/ttyACM0": Permission denied
avrdude done.  Thank you.
make[1]: *** [tmk_core/avr.mk:228: avrdude] Error 1
make: *** [Makefile:551: mitosis:datagrok:avrdude] Error 1
```
To account for this I have replaced the …
> Sleep until USB port becomes writable before running avrdude

- drivers/avr/i2c_master.c
XD84 has stopped successfully reading the matrix state from the port expanders. From discord:
>How are the reads succeeding if are only getting error codes back from the port expanders? I  tried turning on console and got immediately spammed
#4974 changed the behaviour of `i2c_readReg`. Instead of returning `I2C_STATUS_SUCCESS`, it now returns last result from i2c_read_nack, which is data. Anything doing a `!= I2C_STATUS_SUCCESS` check now fails.
This PR returns back the old behaviour of `i2c_readReg` and `i2c_receive`, returning `I2C_STATUS_SUCCESS` on success.
* xd84/xd96 not detecting matrix and spamming errors
> XD84 no longer detecting key presses / ARM I2C behaviour recently changed

- quantum/api.c
- quantum/rgblight.c
- quantum/rgblight.h
- quantum/split_common/transport.c
Currently split-common transfers the eeprom version of rgblight config to the slave side, meaning it is not possible to make any transient changes to configuration that also propagate to the slave side. (in my case, I turn off the rgb lights after a period of inactivity).
Add `rgblight_read_dword` function to retrieve the active config rather than directly reading the struct.
Make split i2c keyboards transfer this active rgblight config rather than eeprom saved version of rgblight config, enabling runtime changes that aren't persisted to eeprom.
Make `rgblight_update_dword` not update eeprom (we already have `eeconfig_update_rgblight` for that, so that the slave transport side doesn't persist changes to eeprom.
*
> rgblight split transfer non-eeprom config

- docs/config_options.md
- tmk_core/avr.mk
Adds ability to flash .eep files for setting hands with `:avrdude-split-<left/right>` commands
*
> Add avrdude split EE_HANDS flash commands

- Dockerfile
- Vagrantfile
Just noticed docker is using Debian, while vagrant is using Ubuntu. Its easy enough to change either way, but to quote a reply from my question on discord, "Debian is the de facto standard for containers"
While I've only just updated to the "bento/ubuntu-16.04" box, the main aim was to use a box that was updated more frequently and both seem to be updated monthly. Given it was previously broken, now seems a good time to make this change.
> Align docker and vagrant base images

- docs/feature_audio.md
This adds (needed) documentation to the "MUSIC MAP" feature, which allows you to remap the matrix layout for the music mode, so that it functions correctly for weirdly shaped matricis
* Discord
> [Docs] Add music_map to audio documentation

- keyboards/lily58/config.h
- keyboards/lily58/keymaps/default/keymap.c
- keyboards/lily58/rules.mk
This changes the layer values on the Lily58 keyboard, and disables macros and functions, since it's very close to the limit for the atmega32u4 chip. 
All other optimization has already been done, except LTO
*  Travis CI
> [Keyboard] Reduce compile size of the Lily58 Keyboard

- keyboards/zen/matrix.c
The `matrix_scan()` function for zen keyboards under `keyboards/zen` does not have a call to `matrix_scan_quantum()`, and similarly for the `matrix_init()` function. This prevents certain QMK features from functioning correctly (eg. Tap Dance).
> add quantum matrix calls to zen matrix calls

- quantum/split_common/transport.c
Silly bug in the transport code for i2c splits; was implicitly converting larger row variables to uint8_t. Fixed by using memcpy instead of manually assigning array elements.
* Discord
> Fix i2c splits with >8 columns

- keyboards/40percentclub/mf68/keymaps/default/keymap.c
Been sort of checking default/reference keymaps for issues, as I am wont to do.
> Refactor MF68 default keymap to use LAYOUT_68_ansi macro

- docs/feature_rgblight.md
- keyboards/helix/rev2/keymaps/five_rows/config.h
- quantum/rgblight.c
Added support for `RGBLIGHT_LED_MAP` macro to rgblight.c.
Example 1:
```c
// config.h
#define RGBLED_NUM 10
#define RGBLIGHT_LED_MAP { 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 }
```
Example 2:
```c
// config.h
#define RGBLED_NUM 30
/* RGB LED Conversion macro from physical array to electric array */
#define LED_LAYOUT( \
L00, L01, L02, L03, L04, L05,  \
L10, L11, L12, L13, L14, L15,  \
L20, L21, L22, L23, L24, L25,  \
L30, L31, L32, L33, L34, L35,  \
L40, L41, L42, L43, L44, L45 ) \
{ \
L05, L04, L03, L02, L01, L00,   \
L10, L11, L12, L13, L14, L15,   \
L25, L24, L23, L22, L21, L20,   \
L30, L31, L32, L33, L34, L35,   \
L46, L45, L44, L43, L42, L41    \
}
/* RGB LED logical order map */
/* Top->Bottom, Right->Left */
#define RGBLIGHT_LED_MAP LED_LAYOUT( \
25, 20, 15, 10,  5,  0,       \
26, 21, 16, …
```
> rgblight.c: add  remap feature

- keyboards/planck/keymaps/tom/config.h
- keyboards/planck/keymaps/tom/keymap.c
- keyboards/planck/keymaps/tom/readme.md
- keyboards/planck/keymaps/tom/rules.mk
This layout is data-driven: I installed [WhatPulse](https://whatpulse.org/) a few months ago and generated a heatmap of the most frequently used keys. I also optimized for my most-used programming languages, and muscle memory.
- swap escape and tab
- rearrange arrows in original layout
- swap rshift and Enter
- map / to original location of left arrow key
- move backslash to backspace
- map quote to original location from qwerty layer
- map brightness up / down to original location of left and up arrows
- map volume up / down to original location of down and right arrows
- move pipe to backspace
- map quote to original location from qwerty layer
- map brightness up / down to original location of left and up arrows
- map volume up / down to original location of down and right arrows
- …
> Add custom Planck Light keymap

- docs/feature_grave_esc.md
It appears Terminal doesn't respect the assigned Command+<code>&#96;</code> shortcut in Keyboard preferences:
There is apparently no way to change this within the Terminal preferences, so this should be noted in the Grave Escape Caveats section.
*
> Document an annoyance with Grave Escape and macOS Terminal

- docs/faq_build.md
Add udev rule details for input club keyboards to the build faq.
> Add udev rule for Input Club bootloaders

- message.mk
- tmk_core/rules.mk
Changed to display a warning when the free size of compilation result is less than 512 bytes. :-)
Example:
```
$ make crkbd:default
.....
Copying crkbd_rev1_default.hex to qmk_firmware folder                        [OK]
Checking file size of crkbd_rev1_default.hex                                 [WARNINGS]
* The firmware size is the limit soon - 28388/28672 (284 bytes free)
```
```
$ make crkbd:all
QMK Firmware 0.6.321
Making crkbd/rev1 with keymap default                                        [WARNINGS]
* The firmware size is the limit soon - 28388/28672 (284 bytes free)
Making crkbd/rev1 with keymap drashna                                        [OK]
Making crkbd/rev1 with keymap edvorakjp                                      [OK]
Making crkbd/rev1 with keymap jarred …
```
> build size-check enhancement

- keyboards/westfoxtrot/cypher/keymaps/kwer/config.h
- keyboards/westfoxtrot/cypher/keymaps/kwer/keymap.c
- keyboards/westfoxtrot/cypher/keymaps/kwer/readme.md
- keyboards/westfoxtrot/cypher/keymaps/kwer/rules.mk
Add new keymap and documentation on how to add/configure an RGB strip to the cypher keyboard PCB
*
> Add kwer keymap and RGB mod description to cypher

- keyboards/exclusive/e6v2/bmc/bmc.c
- keyboards/exclusive/e6v2/bmc/i2c.c
- keyboards/exclusive/e6v2/bmc/i2c.h
- keyboards/exclusive/e6v2/bmc/rules.mk
@drashna deceived me and I willingly obeyed his lies regarding the usage of i2c_master over the custom i2c code needed for ps2avrgb. I suspect it was all part of his ploy to discredit and undermine my BMC ambitions. 
In all seriousness, I'll have to take another look at i2c_master and see what exactly is causing it to mess up BMC boards making it not type ANYTHING. For the time being, reverting the change he requested.
> revert back to the old custom i2c code for bmc

- docs/custom_quantum_functions.md
- Fix typo in keyboard_post_init_user example
While changing the file, i have also:
- Added missing syntax highlighting
- remove EPRM from Persistent Configuration (EEPROM)
- `EEP_RST` keycode is now available
> Tidy up custom_quantum_functions documentation

- layouts/community/ergodox/bepo_alt/keymap.c
- layouts/community/ergodox/bepo_alt/readme.md
- layouts/community/ergodox/bepo_alt/rules.mk
Hello,
Please find my contribution to this repository as a new layout for the ergodox keyboard.
The other bépo layouts were a bit too complex/weird or without LED code
and hard to transition to for new users. This config is a good base for
bépo users. Also, it removes the AZERTY compatibility layers found in other keymaps, thus liberating some keys for the user.
I think it's best to have as much examples as possible, so I'm hoping my layout could be included in this repository so french bépo users can start from a good base.
You can see the [README.md here](https://github.com/NicolasCARPi/qmk_firmware/blob/pr/layouts/community/ergodox/bepo_alt/readme.md).
None.
> Add alternate bépo layout for Ergodox EZ

- docs/feature_debounce_type.md
- keyboards/ergodox_ez/matrix.c
- keyboards/ergodox_ez/rules.mk
- quantum/debounce/eager_pr.c
- quantum/debounce/readme.md
Added Eager_PR algorithm that should reduce ergodox debounce latency
Added a new algorithm and integrated ergodox into it.
Similar to #2675 but uses the shiny new Debounce API.
This requires TESTING - i have not got an ergodox EZ.
For whoever guinea-pigs into testing, i would like to know
1) scan rate with this algorithm (hopefully faster than official one, which has to update 60+ uint8_t's every scan)
2) scan rate with previous algorithm (updates 60+ uint8_t's every update, so will be a bit costly)
3) scan rate with debouncing turned off completely (simply use this branch and remove the call to debounce(). You won't get any keyboard input but it should still log the scan_rate.
*
> Ergodox EZ speedup

- quantum/encoder.c
- quantum/encoder.h
- quantum/split_common/matrix.c
- quantum/split_common/transport.c
Added encoder support to split common code. 
Added functionality to split common code to send encoder data from slave to master. Updated I2C communication in transport.c to be more robust for address shifting based on features turned on and off.
*
> Added encoder support to split common code

- docs/config_options.md
- docs/custom_quantum_functions.md
- quantum/quantum.c
- quantum/quantum.h
- tmk_core/common/action_tapping.c
- tmk_core/common/action_tapping.h
Allow a user customizable tapping term, that is configurable, per key.  In theory. 
However, it doesn't work correctly.  The default value works, but I can't seem to get it to properly work using the `keycode`, but does work if you specify the Row and Column of the key. 
This is not ideal, at all.   But I'm not sure sure how to fix this issue.   So, I'm opening the pull request to get some input on this, and see if somebody can help me get this working "properly". 
This isn't originally my code, but is fredizzimo and @danielo515
* #2477
> Custom Tapping Term per key

- quantum/rgb_matrix.c
- quantum/rgb_matrix_animations/breathing_anim.h
AI found a couple of compile failures while running with various RGB Matrix animations disabled.
`#define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT`
Causes explosion due to incorrect check at https://github.com/qmk/qmk_firmware/blob/cb33643f0209202e5d195613ad685e3cdae4ef2d/quantum/rgb_matrix.c#L104
Enabling breathing but disabling most others, causes explosion due to lack of extern declaration for `g_rgb_counters` at:
https://github.com/qmk/qmk_firmware/blob/cb33643f0209202e5d195613ad685e3cdae4ef2d/quantum/rgb_matrix_animations/breathing_anim.h#L9
> Fix compile failures when enabling only some matrix animations.

- drivers/avr/i2c_master.c
Bootmapper Client (BMC) boards have to use custom i2c instead of the QMK i2c_master driver. I would like to get rid of that dependency and modify i2c_master to support atmega32a boards. The difference actually lies in the `i2c_init` routine. 
In `i2c_init`, enable
1. Pull up resistors
2. Two Wire Interface
3. TWI Interrupts
4. Slave Address Ack
Tested working on 
1. Gray Studio HB85
2. Panc60
3. Donut Cables Budget96
I don't have any other non BMC boards that make use of i2c currently in my possession that I can think of, so I could use some help testing this =).
> i2c_init update to work with atmega32a boards

- keyboards/kc60/keymaps/noroadsleft/keymap.c
- keyboards/kc60/keymaps/noroadsleft/readme.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch3.md
- keyboards/kc60/keymaps/noroadsleft/readme_ch5.md
- Update NUBS_Z macro so it repeats when held down
- Number row now uses numpad keycodes if Right Alt is being held
- coding conventions and formatting update
- switched to four-space indent
- reformatted a block comment
> Updates to noroadsleft keymap for KC60 (2019-04-07)

- keyboards/treadstone48/rev1/config.h
Found another one of these. See #4301 #5065 #5269 for more details.
> Remove unnecessary IS_COMMAND definition in treadstone48

- tmk_core/protocol/lufa/adafruit_ble.cpp
As I mentioned in https://github.com/qmk/qmk_firmware/pull/4967#discussion_r252911811, Adafruit BLE keyboards include the keyboard description from `config.h` in the device name. I think this is not really the right place for it, especially since some descriptions can be quite long.
* None.
> Remove keyboard description from Adafruit BLE device name

- quantum/dynamic_keymap.c
- quantum/quantum.c
- quantum/quantum.h
Fixed tap/down/up handling in dynamic keymap macros
> Fixed tap/down/up handling in dynamic keymap macros

- keyboards/satan/keymaps/default/keymap.c
No need for this custom keycode.
*
> Change SFT_ESC keycode in default Satan keymap to KC_GESC

- keyboards/ergodox_ez/matrix.c
Ergodox_ez now calculates whether the matrix changed during scanning.
Ergodox_ez previously did not calculate if the matrix changed while scanning it.
This is required to make sym_g debounce work correctly.
* 
I have only compiled it - @drashna (lol) to test.
> ergodox_ez: Matrix changes now used for debounce()

- Dockerfile
- docs/getting_started_build_tools.md
- util/docker_build.sh
Reverts qmk/qmk_firmware#2724
The changes that PR made to the dockerfile and build script are not correct. `make clean` and `make git-submodule` should not be executed every time the container is run, as this can slow down keymap build times significantly. Submodules should already be present in the directory when the image is built. CI enforces this for [official images](https://hub.docker.com/r/qmkfm/qmk_firmware), and you're supposed to have the submodules cloned ahead of time if you're building a custom image locally.
Furthermore, the change to the docs is unnecessary as well, since the guide instructs the user to use `git clone --recurse-submodules` to clone the repo (as can be seen [here](https://github.com/qmk/qmk_firmware/blob/master/docs/newbs_getting_started.md#set-up-qmk) and …
> Revert "Update build instructions and docker file to download submodules"

- docs/feature_combo.md
Combos with shared keys are supported as of https://github.com/qmk/qmk_firmware/pull/2561. Therefore, this caveat no longer applies and should be removed.
> Remove caveat about combos with shared keys

- quantum/template/ps2avrgb/readme.md
- fix markdown formatting on macOS instructions (close code block)
- update package install commands
- set python3
- use pip3 to install pyusb
- fix typo (extra backtick on bootloadhid package install line)
- update Keyboard Maintainer line (now unified with AVR template)
Based on @mechmerlin's work of refactoring BMC boards to use QMK core functionality, though I'd guess he hopes to never again actually need this file.
> Update ps2avrgb readme template

- util/travis_build.sh
Fix build detection of keymap and board changes
#5127 contains changes that are only keymap, travis decided to skip building the keymap. This is the build output:
```bash
0.02s$ bash util/travis_build.sh
keyboards/kc60/keymaps/noroadsleft/keymap.c
keyboards/kc60/keymaps/noroadsleft/readme.md
keyboards/kc60/keymaps/noroadsleft/readme_ch1.md
keyboards/kc60/keymaps/noroadsleft/readme_ch2.md
keyboards/kc60/keymaps/noroadsleft/readme_ch3.md
keyboards/kc60/keymaps/noroadsleft/readme_ch4.md
keyboards/kc60/keymaps/noroadsleft/readme_ch5.md
keyboards/kc60/keymaps/noroadsleft/readme_git.md
The command "bash util/travis_build.sh" exited with 0.
```
Introduced with this [commit](/qmk/qmk_firmware/commit/800ec55dfca06b4630acf62cbb5f130c4031e4f1). The combination of the continue logic, and the more …
> Fix build detection of keymap and board changes

- util/atmega32a_program.py
To allow something like #5206, where a board which uses `atmega32a_program.py` wants to use a unique VENDOR_ID and PRODUCT_ID. The programming script has hard coded values, which will cause problems if the target board is not in the bootloader. This PR allows the values to be passed, for example:
```
./utils/atmega32a_program.py --vendor=0x4B52 --product=0x422D kprepublic_jj40_default.hex
```
Defaults maintain the previous behaviour.
While changing the script, i also got rid of a few pylint warnings.
> Add vendor and product arguments to atmega32a_program.py

- quantum/quantum.c
- quantum/quantum.h
This should allow for AltGr based codes (eg Right Alt) to be used for send string mappings. 
Also, this cleans up the code a bit.
Though, I'm not sure how useful this actually is?  But hey, it was an idea, and I felt like doing it. :D
> Add AltGr/RALT support to Send String

- quantum/process_keycode/process_combo.c
I botched the merge conflict resolution in #2561 , inverting the logic for when combos should be re-enabled. This PR fixes #5595 that came as a result; on master with combos I can reproduce stuck keys and swallowed keypresses when using `SEND_KEYS()` but with these changes I cannot. It'd be great if @noahfrederick could confirm!
* #5595
> fix combo enabling logic

- keyboards/alpha/keymaps/default/keymap.c
Set custom key codes  for alpha to start at SAFE_RANGE
Set the custom keycode to start at SAFE_RANGE.
This will change Layer 3 KC_NO to not behave like the custom key code.
@PyrooL If all keys on layer 3 should behave like your custom key code, I can change all KC_NO to MACRO1.
*
> Fix macro keycode for alpha keyboard

- keyboards/tada68/keymaps/kbp-v60/keymap.c
- keyboards/tada68/keymaps/kbp-v60/readme.md
- keyboards/tada68/keymaps/kbp-v60/rules.mk
Added a custom keymap for TADA68 with a function layer that resembles KBParadise V60
None
> [keymap] TADA68 KBP-V60-like keymap

- tmk_core/common/arm_atsam/suspend.c
When waking from suspend, only enable the LED drivers if they were not previously set to disabled by the user. This functionality was removed by the recent updates to adapt Massdrop keyboards to QMK RGB Matrix. Affects Massdrop CTRL and ALT keyboards compiled using Massdrop Configurator mode.
*
> Fix wake from suspend LED functionality for Massdrop CTRL and ALT

- keyboards/crkbd/keymaps/default/keymap.c
- keyboards/crkbd/keymaps/omgvee/keymap.c
- keyboards/crkbd/keymaps/thefrey/keymap.c
- keyboards/crkbd/lib/layer_state_reader.c
Change the layer values to be sequential.   This will reduce the firmware size, at it was using 16 layers, but now uses 4. 
Unfortunately, the requires changing both the default keymaps, but other keymaps using the `layer_state_reader` code. 
So this necesitate the changes of other keymaps.
> Reduce CRKBD firmware size by reducing layer numbers

- quantum/debounce/eager_pr.c
Added extra transfer_matrix_values() call whenever counters don't need updating
My theory is that due to shared counter usage, we also need to `transfer_matrix_values()` whenever the we change from a state of `counters_need_update` to `!counters_need_update`. 
* #5643
> [core] Fix for eager_pr #5643

- .clang-format
- .editorconfig
- docs/contributing.md
Update our style guide to reflect a couple recent things that have been coming up.
* Officially move to 4 space indent
* Document our stance on `#ifdef` vs `#if defined()`
*
> Update our style guide

- docs/feature_mouse_keys.md
- tmk_core/common/mousekey.c
- tmk_core/common/mousekey.h
* Make default speed settings more consistent across modes:
* In accelerated and constant+momentary mode, one setting is faster than unmodified speed and two settings are slower
* In constant+tap-to-select mode, there is no unmodified speed
* Improve documentation
* Add an unmodified speed that is used in momentary mode when no `KC_ACLx` key is pressed
* This gives users another speed setting without introducing new key codes
* Previously, one key code (`KC_ACL1`) had no effect because its speed was identical to the unmodified speed, which could confuse users and made one key code useless
* The speeds are named `0`, `1`, `2`, thus corresponding to their respective key codes `KC_ACL0`, `KC_ACL1`, `KC_ACL2`
* Easier to configure as one no longer needs to translate between speed descriptions …
> Improve mouse keys docs and constant speed mode

- keyboards/planck/rules.mk
- keyboards/preonic/rules.mk
Doing this to remove the chance of the wrong firmware being built/flashed, since rev 6/3 firmwares are incompatible with past versions.
I've apparently forgotten how this system works - looks like it'll require some additional changes.
> Remove default folders for the Planck & Preonic

- .travis.yml
- util/travis_test.sh
Currently unit tests take 35s, which if you have only changed docs is a waste of cpu cycles. Given the limit of 5 concurrent builds, any time saved helps to keep the build job backlog free.
This PR follows the ideas configured within `travis_build.sh` and sets up Travis to skip tests on non master branches with only docs changes.
This could safely be extended to keyboard and community layout folders if required.
> Travis CI - skip unit tests for documentation changes

- tmk_core/common/avr/bootloader.c
Patch from https://github.com/qmk/qmk_firmware/issues/3657#issuecomment-415147411
Tested on avr-gcc 8.3 on Mac.
Still needs testing on Windows and Linux to confirm.
* https://github.com/qmk/qmk_firmware/issues/3657
> Make sure NOBITS is set on reset_key to fix avr-gcc 8.2+ builds

- util/linux_install.sh
I'm assuming that because `DEBIAN_FRONTEND=noninteractive` is set, we actually want this to be non interactive. However when I run this on my system, it actually is interactive. Adding the -yq flag will fix this.
> Add -yq flags to actually make debian installs noninteractive

- docs/feature_rgb_matrix.md
- tmk_core/common/eeconfig.c
If you define `EECONFIG_RGB_MATRIX` in your config.h file, it's not actually initialized.  This leads to a number of issues with the feature (namely that it just won't work). 
This will allow it to be initialized, properly, if it's defined.  
Also, this updates the doc to point to an unused address in EEPROM. 
* Drashna CI failure, trying to get rgb matrix and light working.
> Fix RGB Matrix issue with EEPROM 

- keyboards/zen/rev2/rev2.c
Forgot to update Zen Rev2 keyboard when 90 degree rotation was moved to a runtime switch.
Forgot to update Zen Rev2 keyboard when 90 degree rotation was moved to a runtime switch.
*
> Forgot to update the oled define usage for Zen rev2

- docs/feature_rgb_matrix.md
- docs/feature_rgblight.md
- quantum/rgb_matrix.h
- quantum/rgblight_list.h
Define RGB colors and pass them to the rgblight functions, instead of
defining multiple macros.
Instead of having multiple macros for each color, the PR defines the color twice (RGB/HSV) that can be passed to the appropriate functions.
*
> Define RGB colors

- tmk_core/arm_atsam.mk
- tmk_core/avr.mk
- tmk_core/chibios.mk
- tmk_core/rules.mk
On ARM targets, the LIB_SRC and QUANTUM_LIB_SRC macros have been corrected as they do not function properly.
* #5617
> fix LIB_SRC and QUANTUM_LIB_SRC for ARM(chibios)

- users/mechmerlin/changelog.md
- users/mechmerlin/config.h
Turns out I was enabling RGBLIGHT_ENABLE on my boards regardless if there was a pin defined or not.
> Fix my userspace RGB bug

- keyboards/exclusive/e6v2/bmc/bmc.h
> Forgot to omit k05 from the electrical matrix in hhkb layout

- keyboards/zen/rev1/rules.mk
Project Zen rev 1 uses pro micros, which use the caterina bootloader. I've added the bootloader declaration to the rev1's rules file so that you can use the reset keycode to flash the keyboard.
*
> fix project zen rev1 bootloader declaration

- quantum/rgblight.c
Fixed that sync information was not notified to slave when `rgblight_update_dword()` and `eeconfig_update_rgblight_default()` were executed.
*
> FIX rgblight.c split sync bug

- keyboards/emptystring/NQG/info.json
- keyboards/emptystring/NQG/readme.md
Adds QMK Configurator support for the NQG by emptystring studio.
Spotted this while looking into something else.
The layout visually in Configurator won't match the way the layout macro is in the source files, but I chose to do it this way because it doesn't require changing any of @culturalsnow's source code.
> QMK Configurator support for the emptystring studio NQG

- tmk_core/common/chibios/suspend.c
Somebody was a very, very bad boy, and did a poor job of copy-pasting
Added the wrong function when adding suspend functions.  
This fixes it, and allows proper wake trigger handling for ChibiOS boards. 
*  Mine
> Fix wakeup function on ChibiOS

- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c
- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/readme.md
This is pretty much a stock 65% split keyboard layout, with an HHKB-style (split) backspace and media keys in the function layer centered around the WASD cluster.
Basically the same as [my Quefrency keymap](https://github.com/qmk/qmk_firmware/tree/master/keyboards/keebio/quefrency/keymaps/bcat), just without mouse keys, since I don't have a use for those on this keeb, and without RGB keys since this keeb has no underglow. :)
None
> New keymap for KBD67 hotswap

- quantum/keymap_extras/sendstring_uk.h
Using the # character in a `SEND_STRING` erroneously produces £ = Shift+`KC_3`. Both of these are wrong and it should simply be sending unshifted `KC_NUHS`.
Credit to @pelrun for figuring this out 👍 
* Fixes #5722
> Fix sendstring "#" producing "£" instead

- keyboards/handwired/promethium/keymaps/default/keymap.c
- keyboards/handwired/promethium/keymaps/priyadi/keymap.c
- keyboards/planck/keymaps/priyadi/config.h
- keyboards/planck/keymaps/priyadi/rules.mk
Added compatibility for Planck rev6
none
> Added compatibility for Planck rev6

- keyboards/kbdfans/kbd4x/kbd4x.h
- keyboards/kbdfans/kbd4x/rules.mk
Enabling ortho_4x12 & planck_mit layouts for KBD4X.
> Adding ortho_4x12 & planck_mit layouts for KBD4X.

- lib/lib8tion/lib8tion.h
Reduces firmware size at a slight cost for performance.
Using the SOL keyboard, atmega32u4 mcu and lto enabled
Firmware size:
`make sol:xulkal`
Before: 2948 bytes free
After: 3118 bytes free
Savings: 170 bytes
Performance:
rgb_matrix_multisplash max 8 presses
Before Worse Case: 10ms
After Worse Case: 10ms
Sub MS performance change, cannot measure.
*
> Removed forced in lining for lib8tion functions

- keyboards/signum/3_0/elitec/keymaps/default/generate_km.py
- keyboards/signum/3_0/elitec/keymaps/default/layout.py
- keyboards/signum/3_0/elitec/keymaps/default/readme.md
* Remove dependency on sortedcontainers
> Signum3.0 remove sortedcontainers

- keyboards/sol/sol.c
- quantum/rgb_matrix.c
This PR adds a kb level weak function for for keyboard owners to implement special handling for rgb matrix key to led lookup code. This allows keyboards, such as the Sol in this example, handle 2 keys triggering 1 led which is not possible today. This makes Reactive mode work correctly for all possible key presses.
*
> Implement kb function for rgb matrix to led lookup

- keyboards/planck/keymaps/motform/config.h
- keyboards/planck/keymaps/motform/keymap.c
- keyboards/planck/keymaps/motform/readme.md
- keyboards/planck/keymaps/motform/rules.mk
My keymap for the Planck keyboard.
*
> [Keymap] Add motform planck keymap (swedish colemak)

- .gitignore
VSCode has started to store precompiled headers in `/.vscode/ipch/`, so lets add this folder to gitignore, so we no longer see these from people's PRs.
> Ignore VSCode's Precompiled Headers folder

- drivers/avr/ws2812.c
- quantum/rgb_matrix_drivers.c
There were two usages of RGBLED_NUM in the ws2812 driver that would cause an issue if it was used only in the RGB Matrix feature where it was not defined. Switched it to correctly calculate it using sizeof or the RGB Matrix specific DRIVER_LED_TOTAL define where necessary.
*
> Fixing incorrect usage of RGBLED_NUM in ws2812 driver when used with RGB Matrix

- common_features.mk
- docs/feature_rgblight.md
- keyboards/jc65/v32u4/keymaps/dead_encryption/keymap.c
- quantum/rgblight.c
- quantum/rgblight.h
- quantum/rgblight_list.h
Converted rgblight to use 255 hue identical to rgb matrix
Converted some rgblight code to use math8
*
> rgblight 255 hue

- quantum/rgb_matrix_animations/solid_reactive_anim.h
- quantum/rgb_matrix_animations/solid_reactive_simple_anim.h
Changed the simple reactive effects to grab the most recent keypress for a given key instead of the oldest. 
Here's a rough image of the effect of this change. The before change behavior (actual) vs the after change behavior (expected)
*
> Simple fix for selecting which tracked key press to work off of for simple reactive effects

- keyboards/plaid/plaid.h
- keyboards/plaid/rules.mk
Spotted within the output of http://compile.qmk.fm/v1/keyboards/error_log.
Plaid defines `LAYOUTS = planck_mit planck_grid` however the LAYOUT macros are defined as `plaid_mit` and `plaid_grid`.
This PR allows the default community layout ` make plaid:default_planck_mit` to be built and also removes planck_grid as ortho_4x12 supersedes it. I have kept the existing macro and defined an alias, just incase any keymaps already exist. If required i can change the logic so the layouts are planck and the alias is plaid.
> Plaid - Add compatibility for LAYOUTS = planck_mit planck_grid

- keyboards/mint60/config.h
- keyboards/mint60/keymaps/default/config.h
- keyboards/mint60/keymaps/eucalyn/config.h
add '#define USE_SERIAL' to keyboards/mint60/config.h.
If there is no '#define USE_SERIAL', qmk configurator will give an error, so add '#define USE_SERIAL' to `mint60/config.h`。
> fix mint60 with qmk_configurator 

- build_keyboard.mk
Specifically, to fix some edge cases, and keep the handling consistent, the userspace folder should not actually be added at the end.  Ideally, it should be added after the keymap paths, but before the keyboard's path.
This issue was discovered in #5484, and the fix created by mtei.
*
> Change VPATH path addition order

- build_keyboard.mk
The insertion point for `$(patsubst %.c,%.clib,$(LIB_SRC))` must be after all normal `SRC += ..` . I modified it to be so.
Because LIB_SRC and SRC are assumed to be used in pairs. Similarly, QUANTUM_LIB_SRC and QUANTUM_SRC are also assumed to be used in pairs.
> Fix build_keyboard.mk: LIB_SRC insert position

- .travis.yml
- keyboards/candybar/rules.mk
- keyboards/clueboard/60/rules.mk
- keyboards/clueboard/66/rev4/rules.mk
- keyboards/clueboard/66_hotswap/gen1/rules.mk
- keyboards/dztech/dz40rgb/rules.mk
- keyboards/dztech/dz60rgb/rules.mk
- keyboards/ergodox_infinity/rules.mk
- keyboards/hs60/v2/keymaps/ansi_via/rules.mk
- keyboards/hs60/v2/keymaps/default_via/rules.mk
- keyboards/hs60/v2/keymaps/goatmaster/rules.mk
- keyboards/hs60/v2/keymaps/hhkb_via/rules.mk
- keyboards/hs60/v2/keymaps/iso_andys8/rules.mk
- keyboards/hs60/v2/keymaps/stanrc85/rules.mk
- keyboards/hs60/v2/keymaps/win_osx_dual/rules.mk
- keyboards/hs60/v2/rules.mk
- keyboards/infinity60/rules.mk
- keyboards/k_type/rules.mk
- keyboards/vinta/rules.mk
- keyboards/whitefox/rules.mk
- quantum/mcu_selection.mk
- quantum/stm32/proton_c.mk
- tmk_core/chibios.mk
This adds support for adding the DFU Signature to to the BIN files for ChibiOS based boards.   This gets rid of the "invalid signature" warning when flashing the boards. 
* "invalid signature" warning in dfu-util
> Add DFU Suffix for ARM boards

- docs/newbs_testing_debugging.md
Partially stolen from @drashna on discord and #5498, I have added some useful examples on how to debug after enabling debug, as well as mentioning hid_listen as an alternative to QMK Toolbox.
> Add examples to debugging docs

- util/docker_build.sh
Docker requires access to hosts `/dev` in order to find the correct serial devices. It's possible that this fix is only required on Linux as I am unable to test this on a Windows machine.
If somebody has access to a Windows machine with Docker I would appreciate help in testing this.
This also runs the container interactively which allows the user to
interupt the build with Ctrl-C. This smaller change is not a separate pull request mostly because it affects the same line and would cause a merge conflict.
> docker_build.sh: Docker requires access to hosts devices

- docs/feature_macros.md
The code as originally listed didn't work for me, but replacing `unregister_code16(LALT(KC_TAB));` with `unregister_code(KC_LALT);` fixes the problem and causes the macro to work as intended.
Thanks to folks on Discord for helping me figure this out.
> Update Super ALT↯TAB to remove use of unregister_code16

- keyboards/westfoxtrot/aanzee/aanzee.h
This PR fixes an issue for the ISO layout keymap on aanzee PCBs where the Backspace key has the wrong matrix assignment and is therefore not usable
* Backspace not usable when using LAYOUT_ISO on aanzee
> Fix wrong key assigning in keymap for ISO layout

- docs/feature_space_cadet.md
- quantum/process_keycode/process_space_cadet.c
- quantum/process_keycode/process_space_cadet.h
- users/xulkal/config.h
and minor docs / variable name changes
Added a check to remove unnecessary keypresses in the event that the hold mod is the same as the tap mod.
* https://github.com/qmk/qmk_firmware/issues/5780
* https://github.com/qmk/qmk_firmware/issues/5793
> Space Cadet: Reducing unnecessary reported keypresses

- tmk_core/common/mousekey.c
After the new movement model was instroduced, it broke diagonal momement, again.  Reapplying fix from #3147 to both old and new acceleration method.
* Issue reported by Ergodox EZ users
> Re-fix Mousekey Movements

- keyboards/zen/rev2/config.h
- keyboards/zen/rev2/rev2.c
I forgot to enable this by default and lots of sad users told me I was bad and I should feel bad.
*
> Enable RGBLIGHT_ANIMATIONS by default on the Zen rev2

- keyboards/keebio/bdn9/keymaps/vosechu-browser/keymap.c
- keyboards/keebio/bdn9/keymaps/vosechu-ksp/keymap.c
Add several examples for use in our company keyboard building activity!
This adds a simple layout which has examples of different encoder options, slack reactions, default lights, and some macro definitions
Also adds a much more complex gaming example for use with KSP which demonstrates per-layer colors, multiple layers, and debugging examples
> Adding bdn9 keymap examples for company event

- keyboards/singa/singa.c
The refactor in #5579 partially works, but:
- RGB underglow does not render to the LEDs on startup (so firmware thinks RGB is on and if static color is set, displaying the selected color, but it is not)
- Animations do not work
This deficiency potentially also affects:
- HB85
- Budget96
- E6V2
If it makes sense, I can expand this PR to address those three boards.
cc: @mechmerlin
> Add remaining RGB underglow logic to Singa.

- quantum/split_common/transport.c
slave side matrix scanning copied the matrix *twice* to the i2c slave
buffer... - though, for i2c one copy was put in the wrong offset.
The wrong i2c copy (offset 1) overwrote the unused RGBLIGHT part of the
buffer... and when using more than 5 columns per half also the original
matrix buffer.
removed code that does the unnecessary second copy.
> fix: split_common i2c slave backlight not disabled

- docs/features.md
In the Features list in the docs, the link to the Space Cadet feature is broken (404).
> Fix broken Space Cadet link in Features list

- users/konstantin/rules.mk
Fixes a bug introduced by #5774 
The `ifneq ($(strip $(RGB_MATRIX_ENABLE)), no)` check didn't work on its own because `RGB_MATRIX_ENABLE` is undefined rather than `no` when the userspace makefile is processed. This is because `common_features.mk` hasn't yet been included at that point, and so this line (which is supposed to set the default value to `no`) hasn't been executed:
https://github.com/qmk/qmk_firmware/blob/2ea7c597f8d66db332ab569d4e67df46e1af7cbe/common_features.mk#L139
See [here](https://github.com/qmk/qmk_firmware/pull/5774#discussion_r281043110) for some related discussion.
> Fix RGB_MATRIX_ENABLE check in users/konstantin/rules.mk

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix_animations/cycle_out_in_anim.h
- quantum/rgb_matrix_animations/cycle_out_in_dual_anim.h
- quantum/rgb_matrix_animations/rgb_matrix_effects.inc
New rgb matrix effects: Cycle Out to In & Cycle Out to In Dual
Effect Video: https://photos.app.goo.gl/5TdFdV3CyZFQ9XV37
Built on top of PR https://github.com/qmk/qmk_firmware/pull/5811 so merge that PR first.
*
> Cycle out to in rgb matrix effect

- docs/feature_space_cadet.md
- docs/keycodes.md
- docs/quantum_keycodes.md
- quantum/process_keycode/process_space_cadet.c
Small usability bugfix. When typing fast, you could press down A, then press LSPO, releasing A, then releasing LSPO. The releasing of A would cause space cadet to be cleared and not trigger when in reality it should still trigger in this case. 
*
> Added check for event pressed to clear space cadet

- keyboards/dz60/dz60.h
- keyboards/dz60/keymaps/olligranlund_iso/keymap.c
```json
{
"message": "Error: dz60: LAYOUT_60_iso_split_space_bs_rshift: Number of elements in info.json does not match! info.json:66 != LAYOUT_60_iso_split_space_bs_rshift:67",
}
``` 
Fixed up the layout macro to match the `info.json` and code comments (however it could go the other way with a 5x1u bottom corner). Flagging @OlliGranlund as the keymap owner.
> Fix dz60 LAYOUT_60_iso_split_space_bs_rshift api errors

- util/linux_install.sh
The old url <https://archive.archlinux.org/packages/a/avr-gcc/avr-gcc-8.1.0-1-x86_64.pkg.tar.xz> returns 404, only the following files are now available:
```
avr-gcc-8.2.0-1-x86_64.pkg.tar.xz                  26-Jul-2018 22:26     21M
avr-gcc-8.2.0-1-x86_64.pkg.tar.xz.sig              26-Jul-2018 22:26     566
avr-gcc-8.3.0-1-x86_64.pkg.tar.xz                  26-Feb-2019 01:40     21M
avr-gcc-8.3.0-1-x86_64.pkg.tar.xz.sig              26-Feb-2019 01:40     566
avr-gcc-9.1.0-1-x86_64.pkg.tar.xz                  04-May-2019 07:31     22M
avr-gcc-9.1.0-1-x86_64.pkg.tar.xz.sig              04-May-2019 07:31     566
```
#5456 has been merged so it should be safe to use 8.3. I have flashed a hex produced from this PR and it functions as expected.
> Fix arch installs as avr-gcc 8.1 is now unavailable

- docs/config_options.md
- tmk_core/common/action.c
Increases the delay to 200ms, since it seems to have issues registering on MacOS.
Also, made the delay configurable, for those that want to change this. 
* On Discord
> Make delay for Capslock in Hold-Tap functions configurable 

- keyboards/claw44/ssd1306.c
- keyboards/comet46/ssd1306.c
- keyboards/crkbd/ssd1306.c
- keyboards/lily58/ssd1306.c
- keyboards/yosino58/ssd1306.c
I changed the font variable's modifier from **static** to **extern** in ssd1306.c of claw44, comet46, crkbd, lily58 and yosino58.
These modifiers had caused build error on my environment (avr-gcc 9.1.0).
> Fix the modifier in ssd1306.c of some keyboards

- keyboards/converter/modelm101/keymaps/default/keymap.c
In the default keymap for the Model M converter keyboard, keypad enter is remapped to Left GUI. While this is probably useful to many, this shoud not be the default behavior. Changed keymap such that keypad enter is mapped to KC_PENT.
*
> keypad enter should not be remapped in default keymap (Model M converter)

- tmk_core/common/action_layer.c
Fix for bug introduced in https://github.com/qmk/qmk_firmware/pull/3637
sizeof returns size of the data structure in bytes, and this logic needs size in bits.
*
> Fix bit count calculation for iterating layers

- quantum/color.c
hsv to rgb was ignoring the linear lookup table when saturation was 0. This causes visibly larger brightness if your value was also less than maxed compared when saturation was > 0.
*
> Fixing hsv_to_rgb where s = 0 and v < 255

- docs/feature_rgb_matrix.md
- quantum/rgb_matrix.c
- quantum/rgb_matrix_animations/cycle_out_in_anim.h
- quantum/rgb_matrix_animations/cycle_out_in_dual_anim.h
- quantum/rgb_matrix_animations/dual_beacon_anim.h
- quantum/rgb_matrix_animations/rainbow_beacon_anim.h
- quantum/rgb_matrix_animations/rainbow_pinwheels_anim.h
Added a define for overriding rgb matrix effect's keyboard center point from the 112, 32 of today.  This allows users or keyboard makers to put the center point in the center of the qwerty keys instead of the center of the board. Or even more accurately provide x and y positions for leds on longer or narrower boards and still keeping those effects looking good!
As an example, the Massdrop CTRL should have range of 224, 84 to keep the physical x and y in proper ration to real world scale. So the center point should be 112, 42 instead. Minor change but updating the y point of the leds and defining the new center point makes effects look even better.
:exclamation: :exclamation: :exclamation: Should be merged after https://github.com/qmk/qmk_firmware/pull/5867 and …
> Added custom center point to rgb matrix

- quantum/quantum.c
I just thought it was slightly annoying that the `DEBUG` keycode only enables debugging. It should be able to turn it off too.
*
> Make DEBUG keycode disable as well as enable

- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c
- keyboards/keebio/bdn9/keymaps/bcat/keymap.c
- keyboards/keebio/quefrency/keymaps/bcat/keymap.c
Suggested in https://github.com/qmk/qmk_firmware/pull/5924#discussion_r285401499.
None
> Remove spurious backslashes from my keymaps

- keyboards/keebio/levinson/rev1/config.h
Update pinout for Levinson Rev 1.
*
> Fix pinout of Levinson Rev 1 scrap sale boards to use non-jumpered pinout

- keyboards/9key/keymaps/default/keymap.c
- keyboards/9key/keymaps/tap_dance/keymap.c
- keyboards/9key/keymaps/tap_dance/rules.mk
- keyboards/9key/rules.mk
Fails to compile on the configurator because tapdance is enabled for the entire keyboard
* Configurator
> Fix 9key macropad keymap

- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c
- keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/readme.md
- keyboards/keebio/quefrency/keymaps/bcat/config.h
- keyboards/keebio/quefrency/keymaps/bcat/keymap.c
- keyboards/keebio/quefrency/keymaps/bcat/readme.md
- keyboards/keebio/quefrency/keymaps/bcat/rules.mk
- users/bcat/config.h
- users/bcat/rules.mk
I've been having lots of trouble with I2C for my Quefrency. Thought it was a bad cable, but I've tried several and still get dropped/reordered characters. It could still be a hardware problem on my end, but from a quick glance at Reddit and the Keebio Discord, it seems several other folks have had the same issue. My Quefrency is my daily driver at work, so I don't have a ton of cycles to debug it right now. Therefore, I'm switching back to serial in the meantime. (Seems more than fast enough for me in practice, given my typing speed.)
I'm also factoring some common stuff into a userspace since I just found out that was a thing.
None
> Switch Quefrency keymap from I2C back to serial; factor common configs into userspace

- keyboards/tada68/keymaps/iso-nor/keymap.c
Swap the "Cmd" and "Alt" keys in the comment to reflect the actual layout.
Also change "Cmd" to "Win" for consistency with the default keymap.
> Fix layout comment

- quantum/template/avr/config.h
- quantum/template/ps2avrgb/config.h
`DEBOUNCING_DELAY ` no longer exists, and instead, `DEBOUNCE` is what is used. 
This changes the template to properly reflect this.
> Fix up Debouncing in AVR Templates

- keyboards/spacetime/config.h
- keyboards/spacetime/info.json
- keyboards/spacetime/keymaps/default/config.h
- keyboards/spacetime/keymaps/default/keymap.c
- keyboards/spacetime/keymaps/default/readme.md
- keyboards/spacetime/keymaps/kyleterry/keymap.c
- keyboards/spacetime/keymaps/kyleterry/rules.mk
- keyboards/spacetime/readme.md
- keyboards/spacetime/rev1/rev1.c
- keyboards/spacetime/rev1/rev1.h
- keyboards/spacetime/rev1/rules.mk
- keyboards/spacetime/rev2/rev2.c
- keyboards/spacetime/rev2/rev2.h
- keyboards/spacetime/rev2/rules.mk
- keyboards/spacetime/rules.mk
- keyboards/spacetime/spacetime.c
- keyboards/spacetime/spacetime.h
Adds a split design keyboard called the Spacetime Keyboard
Includes matrix, rev1, rev2 and 2 layouts.
> adds spacetime keyboard

- keyboards/waldo/waldo.h
LAYOUT_60_hhkb keymaps for the Waldo don't compile due to a typo in `waldo.h`.
Reported by @Sushiimi at https://github.com/qmk/qmk_configurator/issues/376
> Waldo LAYOUT_60_hhkb bugfix

- quantum/matrix.c
Fixing matrix_scan so it properly returns changed status, this allows the oled driver to detect if there is activity and timeout properly.
* #5982
> Fixing matrix_scan so it properly returns changed status

- tmk_core/common/action.c
When using `TO()` and `DF()`, `layer_state_set_user()` was observed to be called twice. This was not a keydown/keyup thing - the code first does an `AND`, then an `OR`, which both call `layer_state_set()`, which in turn calls `layer_state_set_kb()`... Instead of doing that, we can directly set the layer state here.
*
> Fix TO() and DF() calling layer_state_set_[kb,user] twice

- quantum/keymap_extras/sendstring_belgian.h
Note that you have to send the dead keys twice: tilda, circ.
Tested with the following : 
```c
SEND_STRING(" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^^``_abcdefghijklmnopqrstuvwxyz{|}~~");
```
And what the keyboard typed when triggered:
```
!"#$%&'()*+,-.+0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}
```
Note that the deadkey backtick (grave accent) isn't displayed for some reason
> belgian layout had no sendstring definition

- tmk_core/chibios.mk
Teensy 3.x and LC both use teensy_loader_cli for flashing and expect a `.hex` file.
The change has been stolen from avr.mk, im not sure if there is a more centralised location to avoid duplication? (MCU logic will need to be slightly different between ARM and AVR due to ARM teensy requiring `MCU  = cortex-m0plus` and that not being what `-mmcu` expects).
> Add ARM Teensy flashing support

- keyboards/jc65/v32a/v32a.c
When building a firmware with RGB and Backlight disabled there were compile errors
because the headers are not imported but the code which calls its methods are still
called.
This change adds additional #ifdefs to remove the problematic pieces.
> Pti jc65 v32 a fix rgb backlight disable

- .travis.yml
- Dockerfile
- util/travis_build.sh
- util/travis_test.sh
In order to locally reproduce build issues, it is essential to minimise differences. Getting an environment to mimic travis is rather troublesome and involves far too many steps. Using the current docker image for both local builds and CI builds allows contributors to get the same results locally with minimal changes. While it potentially adds the optional docker dependency on the development environment, this still cuts out an entire section of the currently supported platform/compiler matrix.
This PR switches travis to use docker with the following changes:
- Added docker support to the travis configuration
- Removed install of compile dependencies
- Build current qmk_firmware docker image
- This could pull the one from docker hub if its reliably up to date
- Alternatively the build …
> Use qmk docker image for travis CI builds

- keyboards/dc01/arrow/rules.mk
- keyboards/dc01/left/rules.mk
- keyboards/dc01/numpad/rules.mk
- keyboards/dc01/right/rules.mk
#6038 has seen some permission errors pop out of the build.
I'm sure its due to the build system writing to a folder outside itself.
- when docker was running as root, it could write outside the mounted folder. 
- when running outside container, it could write to a folder outside of the qmk_firmware folder
Tagging @yiancar as maintainer.
> Fix DC01 recent build issues due to sourcing of i2c dependencies

- util/travis_build.sh
- util/travis_test.sh
Recent builds contain the following failures, after the recent "travis use docker" PR:
```
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
To github.com:qmk/qmk_firmware.git
* [new tag]             0.6.393 -> 0.6.393
/bin/sh: 1: cannot create .//quantum/version.h: Permission denied
/bin/sh: 1: cannot create .//quantum/version.h: Permission denied
Cloning into 'qmk.fm'...
All identities removed.
Agent pid 1147
Identity added: id_rsa_qmk.fm (id_rsa_qmk.fm)
Removing deprecated binary: ./compiled/adkb96_rev1_default.hex
rm: remove write-protected regular file ‘./compiled/adkb96_rev1_default.hex’? 
```
This is due to running as root within the container. This PR makes it so the travis user is used, it should mimic the old behaviour …
> TravisCI - Fix docker permission issues when pushing firmware files to qmk/qmk.fm

- docs/i2c_driver.md
- drivers/arm/i2c_master.c
- drivers/arm/i2c_master.h
I2C timing parameters were seemingly set up for an STM32F303 target MCU, at a specific clock speed. This commit allows specifying the timing parameters via config.h, allowing other STM32 MCUs to be targeted, potentially at different clock frequencies.
Alternate function modes for the I2C pins are now also configurable, allowing for remapping to other pins.
* none
> Parameterise STM32 I2C pin modes and timing parameters.

- keyboards/keebio/iris/rev3/config.h
- keyboards/keebio/iris/rules.mk
Update Iris Rev 3 QMK-DFU settings with correct pinout
*
> Update Iris Rev 3 QMK-DFU settings

- keyboards/keebio/iris/keymaps/hexwire/config.h
- quantum/split_common/transport.c
Fixes I2C split keyboard encoder usage.
* Closes #6058
> Fix i2c split encoder

- keyboards/lazydesigners/dimple/dimple.c
The LED was always-on if the custom keymap did not call dimple_led_off()
at least once.
*
> Dimple: fix unintended LED behaviour

- tmk_core/protocol/arm_atsam/md_bootloader.h
The latest version of arm-none-eabi-gcc fails to compile firmware for massdrop keyboards. This is the fixes suggested in #5958.
* #5958
> Fixes compile errors for massdrop keyboards

- Dockerfile
Instant60 is currently having runtime issues with firmware built from both the configurator, and travis (the default firmware published to <https://qmk.fm/keyboards>) .
From Discord, the error was sumarised as:
> Binary doesn't seem to work
> Keyboard doesn't respond to input
> Flashing 6.3.1 built on did
This PR updates the Docker container to use gcc-arm-none-eabi from the default 5.4.1 to 6.3.1, which in turn will be used for travis builds.
> Upgrade gcc-arm-none-eabi from the default 5.4.1 to 6.3.1 due to ARM runtime issues

- docs/feature_combo.md
Fix indentation and whitespace in code examples for the Combo features page.
> Docs: Make Code Examples Consistent On Combo Page

- docs/faq_build.md
- docs/getting_started_build_tools.md
- docs/zh-cn/faq_build.md
- util/macos_install.sh
Change default install of avr-gcc from 7.x to 8.x (8.3.0) for Mac installs.
*
> Change from avr-gcc@7 to @8 for Mac

- keyboards/handwired/dactyl_manuform/4x5/config.h
- keyboards/handwired/dactyl_manuform/4x6/config.h
- keyboards/handwired/dactyl_manuform/5x6/config.h
- keyboards/handwired/dactyl_manuform/5x7/config.h
- keyboards/handwired/dactyl_manuform/6x6/config.h
- keyboards/handwired/dactyl_manuform/config.h
- keyboards/handwired/dactyl_manuform/dactyl_manuform.h
- keyboards/handwired/dactyl_manuform/dmote/62key/62key.c
- keyboards/handwired/dactyl_manuform/dmote/62key/62key.h
- keyboards/handwired/dactyl_manuform/dmote/62key/config.h
- keyboards/handwired/dactyl_manuform/dmote/62key/keymaps/default/config.h
- keyboards/handwired/dactyl_manuform/dmote/62key/keymaps/default/keymap.c
- keyboards/handwired/dactyl_manuform/dmote/62key/rules.mk
- keyboards/handwired/dactyl_manuform/dmote/config.h
- keyboards/handwired/dactyl_manuform/dmote/readme.md
Added [the DMOTE](https://github.com/veikman/dactyl-keyboard) as a variant of the hand-wired Dactyl-ManuForm, with slight changes to prior code organization to reflect differences.
Tom Short, the creator of the original Dactyl-ManuForm, has approved my publishing DMOTE firmware in this manner.
I hope my pushing straight from `master` is all right; I can branch out if it helps.
None.
> New keyboard variant (DMOTE)

- users/bcat/config.h
A delay of 10ms seems sufficient. Otherwise, media keys tapped from the
encoder of my BDN9 macropad only seem to get picked up by the OS
(Windows 10) some of the time.
None
> Set a short TAP_CODE_DELAY so media keys work

- docs/feature_oled_driver.md
- drivers/oled/oled_driver.c
- drivers/oled/oled_driver.h
Fixes the COM PINS and BLOCK TYPE for 128x64 displays so users can use the full display without issues.
*
> Fixing OLED Driver for 128x64 displays

- keyboards/niu_mini/readme.md
- keyboards/niu_mini/rules.mk
modified: readme.md
Small change to the readme. The afrdude bootloader doesn't work for the niu_mini. The dfu bootloader does work for the niu_mini.
*  Fixes #5835
> niu_mini uses dfu bootloader rather than the afrdude bootloader

- .clang-format
Fix indent size of .clang-format.
This fix is related to #5500.
> Fix indent size .clang-format (related to #5500)

- keyboards/lily58/lib/layer_state_reader.c
- display adjust when the bits are set correctly
The current definitions just make the UI display undefined 8 and undefined 14, instead of Adjust.
None
> Fix the layer state messages for actual values

- keyboards/plaid/keymaps/default/keymap.c
- keyboards/plaid/keymaps/default/readme.md
- keyboards/plaid/plaid.h
The plaid keyboard has two LEDs installed, but there was no functionality in the code to activate them.  I've added some, hopefully, interesting and fun modes for these little guys.
plaid/plaid.h - Added two constants for the LED pins to ease any keymap dev to add functionality
plaid/keymaps/default/readme.md - Added documentation on how to set various LED modes
plaid/keymaps/default/keymap.c -
* Altered keymap to include 10 led mode keys on the adjust layer
* Added code to handle new led mode keys, save to eeprom
* Added handler for changing state of LEDs as appropriate for each mode
- [X ] Keyboard (addition or update)
* None
- [X ] My code follows the code style of this project.
- [X ] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
> Adding LED support to the plaid default keycap

- docs/feature_oled_driver.md
- drivers/oled/oled_driver.c
- drivers/oled/oled_driver.h
This patch adds rudimentary support for the SH1106 OLED driver IC, and some minor enhancements to better support my particular OLED module.
The SH1106 chip is quite similar to but not the same as the SSD1306 that `drivers/oled/oled_driver.c` was written to support. In particular:
- Its internal ram for the display is 132x64 bits, compared to 128x64 for the SSD1306.
- It supports only Page Addressing Mode, while the SSD1306 also supports Horizontal Addressing and Vertical Addressing. (`oled_driver.c` assumes Horizontal Addressing.)
- It does not support hardware scrolling.
Regarding my particular OLED module:
I purchased a cheap 128x64 I2C OLED module claiming to use SSD1306, but it turned out to have an SH1106 instead. Recall that the SH1106 at 132x64 has a wider buffer than the physical …
> Add SH1106 OLED support

- util/linux_install.sh
avrdude is require package but not installed by script when arch linux.
Here is steps to reproduce.
```shell
% pacman --remove avrdude
% ./util/qmk_install.sh
% sudo make meishi:default:avrdude
QMK Firmware 0.6.400
WARNING:
Some git sub-modules are out of date or modified, please consider running:
make git-submodule
You can ignore this warning if you are not compiling any ChibiOS keyboards,
or if you have modified the ChibiOS libraries yourself.
Making meishi with keymap default and target avrdude
avr-gcc (GCC) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
Size before:
text    data     bss     dec     hex filename
0   22116 …
```
> Install avrdude in Arch or Manjaro Linux

- docs/config_options.md
- docs/feature_backlight.md
- quantum/quantum.c
When the backlight pin is C6, QMK uses timer 3 as the PWM source. However, some things were still hardcoded to timer 1, in particular the overflow vector for the breathing ISR and the interrupt mask register. I added these to the big block of `#define`s, and now breathing works across the board (except pure software PWM, of course).
*
> Fix backlight breathing on C6

- keyboards/40percentclub/gherkin/keymaps/midi/config.h
- keyboards/40percentclub/gherkin/keymaps/midi/keymap.c
- keyboards/40percentclub/gherkin/keymaps/midi/readme.md
- keyboards/40percentclub/gherkin/keymaps/midi/rules.mk
Added a midi layout for gherkin, assuming vertical layout with USB port at the top.
Mod layer used to set and persist Modal change, includes keys for octave and transposition changes on base layer off of which modal note layers inherit.
I would mention here that I'm very open to help setting a default layer other than 0 (ideally all layers could fallback to 0 but default would start on 1 / Ionian), but also generally open to any suggestions on how to make this better.
Similarly, while I based my layout on code I've read on other keyboard layouts, I'm not entirely certain whether I'm strictly adhering to the code style of this project.
Necessary glamour shot:
> 40percent/gherkin Midi Layout

- keyboards/kbdfans/kbd67/rev2/config.h
KBD67 Rev 2 has 20 LEDs, not 18. This was causing 2 of the underglow LEDs to remain off. This fix updates that.
* N/A
> Fix incorrect RGBLED_NUM value

- docs/config_options.md
- quantum/split_common/post_config.h
Restores default I2C clock speed to 100kHz, after it was switched to 400kHz during refactor to use core I2C driver instead of split_common specific one.
* https://github.com/qmk/qmk_firmware/issues/5569
> Set default I2C clock speed to 100kHz for split_common

- keyboards/1upkeyboards/1up60hse/config.h
LEDs would stay on when computer was shut down. This option turns the LEDs off.
> 1up60hse: Add RGBLIGHT_SLEEP To Default Config

- docs/config_options.md
- docs/feature_backlight.md
- quantum/quantum.c
For backlight systems that don't use a hardware PWM-capable pin, `breathing_task()` is always running! This is because for hardware PWM, `breathing_interrupt_enable()` and `_disable()` modify the `TIMSK` register to control the ISR, whereas the software PWM versions of these macros (they're not functions) set the static bool `breathing`... which is never checked anywhere!
So, before we run `breathing_task()`, we get the green light from `is_breathing()`. I can now control software PWM backlight properly with my test setup - though it is quite flickery at low brightness levels, but I think that is a separate issue.
This *may* (partially) resolve some of the recent issues people have been having with soft backlighting doing weird things. Eg:
#5425, #5953
*
> Fix breathing always on for soft PWM

- docs/keycodes.md
Current docs suggest that a key which is mapped to `TO(n+1)` where `n` is the current layer, except on layer 4 where the key is mapped to `TO(0)`, will result in the following sequence as it is pressed:
```
1
1+2
1+2+3
1+2+3+4
1+2+3+4
1+2+3+4
...
```
This is not actually what `TO(layer)` does, so this pull request makes it clearer on the summary page.
> Reword confusing description of `TO(layer)`

- keyboards/katana60/keymaps/josefadamcik/config.h
- keyboards/katana60/keymaps/josefadamcik/keymap.c
- keyboards/katana60/keymaps/josefadamcik/readme.md
Add a custom layout for Katana60 keyboard. 
The layout have alternative base layers with MacOS/Linux+Qwerty/Colemak support.
> Katana60 custom layout by josefadamcik 

- keyboards/ergodox_ez/ergodox_ez.c
Adds the function calls for the idle/wakeup functionality, so that the board will "sleep" the LEDs  when enabled.
> Add idle/wakeup function calls to Ergodox EZ

- keyboards/cannonkeys/instant60/instant60.h
- keyboards/cannonkeys/instant60/keymaps/default/keymap.c
- keyboards/cannonkeys/instant60/keymaps/tsangan/keymap.c
- keyboards/cannonkeys/instant60/rules.mk
Provides QMK Configurator support for both ANSI and Tsangan variants of the Instant60.
- Instant60 layouts are currently blocks of 1u keys in QMK Configurator.
- flagged by @yanfali 
- `LAYOUT_all` macro is unchanged, per @awkannan's request. There are some ideas to deal with this moving forward.
- Also, as @awkannan is the keyboard maintainer, I'd like to have his "OK" on the record before these changes are merged.
- @skullydazed would probably call this a `breaking change` because of the layout macro renaming, which could break unmerged user keymaps. I'm willing to alias the layout macros to maintain backwards compatibility, but I would prefer not to do so.
> Cannonkeys Instant60 Configurator updates

- keyboards/planck/keymaps/callum/keymap.c
Sorry for another PR so soon after the last one, not sure why this worked for my v6 but it doesn't work for my v5... 😬
The lowercase `send_string` seems to do the trick though.
> [keymap] use lowercase send_string for non-literals

- keyboards/crkbd/keymaps/manna-harbour_miryoku/keymap.c
- layouts/community/ergodox/manna-harbour_miryoku/keymap.c
- layouts/community/ortho_4x12/manna-harbour_miryoku/keymap.c
- users/manna-harbour_miryoku/README.org
- users/manna-harbour_miryoku/config.h
- users/manna-harbour_miryoku/manna-harbour_miryoku.c
- users/manna-harbour_miryoku/miryoku.org
- users/manna-harbour_miryoku/rules.mk
The miryoku layout is an ergonomic, minimal, orthogonal layout for ergo or ortho keyboards.  The layout is maintained in emacs org-mode tables and converted to QMK keymap data structures using embedded python scripts. The layout is mapped onto keyboards with different physical layouts as a subset without code duplication using the QMK userland feature and C macros.
> [keymap] miryoku layout

- keyboards/dz60/keymaps/kifinnsson/keymap.c
- keyboards/dz60/keymaps/kifinnsson/readme.md
- keyboards/dz60/keymaps/kifinnsson/rules.mk
Keymap for my non-standard DZ60 layout. It is an ansi layout on the right and iso on the left (ie 1.25x left shift). This is to implement the angle mod on for Colemak which is the base layer. A side effect of this is that I have an extra key on row 4, which sits between the "b" and "k" keys in Colemak. I use this key as a switch to layer 2 which is my macro layer.
*
> kifinnsson's Colemak angle mod ansi-ish layout for the dz60

- keyboards/mitosis/keymaps/datagrok/config.h
- quantum/audio/song_list.h
Tiny changes in config.h for my keymap to refer to only the available (non-copyright-restricted) songs.
Adds a new variant of the layout-types mini-songs to `quantum/audio/song_list.h`, that I use for workman.
*
> [keyboard] mitosis:datagrok: use non-copyrighted songs, add workman ditty

- keyboards/tanuki/config.h
- keyboards/tanuki/keymaps/default/keymap.c
- keyboards/tanuki/tanuki.h
The Tanuki keyboard uses different wiring layout from how it appears physically. It has 11 wired columns but 12 physical columns, the leftmost column keys are stacked in the following ones on the bottom row. See here to understand what I mean: 
This PR fixes that by modifying the default layout in tanuki.h and the default keymap to follow the physical appearance and don't confuse people. Since nobody else submitted their keymaps, it shouldn't break anything.
Also added support for RGB sleep.
*
> Corrected Tanuki keymap to match physical appearance

- keyboards/keebio/iris/rules.mk
- keyboards/keebio/nyquist/rules.mk
Revise method used to detect revision number so that the correct bootloader is used. This should fix issues with the RESET command not jumping to bootloader for Iris Rev. 3 and Nyquist Rev. 3.
*
> Fix detection of rev number used to set bootloader

- keyboards/crkbd/rev1/rev1.c
Because the default `led_set_kb()` simply calls `led_set_user()`, this actually prevents the use of lock LED processing in keymap-level code (eg. RGB indicators) when the OLED feature is enabled.
*
> Remove empty led_set_kb() from crkbd/rev1

- quantum/matrix.c
unselect_row() uses setPinInputHigh(), but unselect_rows() uses setPinInput().
This is not correct. unselect_rows() should also use setPinInputHigh().
> fix unselect_rows() in quantum/matrix.c

- keyboards/wasdat/matrix.c
Porting #6243 (and #5984) to the Wasdat. The diode direction on this board is actually `ROW2COL` so it will not end up in the compiled firmware - this is just to keep the custom matrix aligned with the default implementation :)
*
> Fix unselect_rows() for Wasdat custom matrix

- util/linux_install.sh
linux_install.sh checked openSUSE for v 15.0 (exactly), and doesn't work for the recently released v 15.1.
Change is pretty trivial.
*
> linux_install.sh fix for openSUSE Leap 15.1

- docs/feature_space_cadet.md
- quantum/process_keycode/process_space_cadet.c
This is an option for those fast typing folks that carry over the mods from when you pressed the space cadet key to the release. For example: Press Shift > Press KC_LSPO > Release Shift > Release KC_LSPO. In this example, since KC_LSPO tap triggers on release, it will not contain the Shift modifier from when it was pressed. This define will carry over the modifiers from when it was pressed and use them on tap trigger release. This is super useful when using a setup like this and fast typing to get both { & [ based on if the other shift is held down or not.
```
#define LSPO_KEYS KC_LSFT, KC_TRNS, KC_LBRC
#define RSPC_KEYS KC_RSFT, KC_TRNS, KC_RBRC
```
*
> Added Space Cadet modifer carry over

- tmk_core/chibios.mk
- tmk_core/rules.mk
If you build your firmware and then run the same make command with `:dfu-util` appended you will get an error message because we attempt to add a dfu-suffix when one already exists. This changes that process to only add the suffix at bin creation time.
Thanks to @fauxpark for helping to identify and fix this issue.
*
> Fix chibios so the dfu-suffix is only applied once.

- common_features.mk
- drivers/qwiic/qwiic.mk
- keyboards/ergodox_ez/rules.mk
- keyboards/model01/rules.mk
Using QUANTUM_LIB_SRC prevents the warning when multiple sources add the i2c_master.c file. Boards such as the Ergodox EZ Glow see this warning every time they compile because the board uses the file in general, and because the RGB LED Matrix requires it, as well.
> Use QUANTUM_LIB_SRC for i2c_master.c inclusion

- keyboards/handwired/promethium/rules.mk
Mostly, this just enables LTO on the board, since there isn't a lot left that we can actually disable to save space 
* Travis CI pitching a fit
> Reduce compiled size of handwired Promethium keyboard

- util/linux_install.sh
- util/macos_install.sh
- util/msys2_install.sh
- util/travis_compiled_push.sh
Run clang-format on any checked-in files in core.
*
> Enforce clang-format

- util/linux_install.sh
This is a very small PR to correct a typo in the Gentoo warning, which says use changes go to /etc/portage/package.use/qmk_firmware instead of qmkfirmware, the file created by the script. 
* None that I know of
> Fix typo in util/linux_install.sh Gentoo docstring.

- quantum/rgb_matrix_animations/colorband_pinwheel_sat_anim.h
- quantum/rgb_matrix_animations/colorband_pinwheel_val_anim.h
- quantum/rgb_matrix_animations/colorband_sat_anim.h
- quantum/rgb_matrix_animations/colorband_spiral_sat_anim.h
- quantum/rgb_matrix_animations/colorband_spiral_val_anim.h
- quantum/rgb_matrix_animations/colorband_val_anim.h
Fixes color band rgb matrix effects that were not respecting the current saturation and value levels from the config.
*
> Fixing effects to respect user sat and val levels

- tmk_core/common/avr/bootloader_size.c
The code in bootloader_size.c is a hack to determine the available firmware size limits. Clang format breaks it.
*
> Have clang ignore the code in bootloader_size.c

- .travis.yml
- Dockerfile
- util/docker_build.sh
- util/travis_build.sh
- util/travis_test.sh
Now that <https://github.com/qmk/qmk_base_container> exists, we can update the travis build to use the new "slim" image, that does not bundle the qmk_firmware repo, and not build the image for every build. Should save a small amount of time (~100 seconds), and more importantly, increase the repeatability between builds.
> Update docker util script and travis to use new base container

- drivers/avr/i2c_master.c
- drivers/avr/i2c_master.h
- drivers/avr/i2c_slave.c
- drivers/avr/i2c_slave.h
The files have officially been updated to GPL3.   So updating that in our repo.
> Add GPL3 header to avr i2c files

- build_json.mk
- lib/python/qmk/cli/json/keymap.py
- lib/python/qmk/keymap.py
Somehow I didn't notice these were broke before merging #6176. This is my PR of shame.
*
> Fix compiling json files.

- build_keyboard.mk
- tmk_core/rules.mk
Display the size of the created object files.
It is convenient to use as follows.
```
$ make crkbd:all
QMK Firmware 0.6.321
Making crkbd/rev1 with keymap default             [OK]
Making crkbd/rev1 with keymap drashna             [OK]
Making crkbd/rev1 with keymap edvorakjp           [OK]
Making crkbd/rev1 with keymap jarred              [OK]
Making crkbd/rev1 with keymap like_jis            [OK]
Making crkbd/rev1 with keymap omgvee              [OK]
Making crkbd/rev1 with keymap thefrey             [OK]
$ make crkbd:all:objs-size | grep keymap.o
2558	      0	      0	   2558	    9fe	.build/obj_crkbd_rev1_default/keyboards/crkbd/keymaps/default/keymap.o
0	      0	      0	      0	      0	.build/obj_crkbd_rev1_drashna/keyboards/crkbd/keymaps/drashna/keymap.o
438	      0	      0	    438 …
```
> add 'objs-size' target into tmk_core/rules.mk

- quantum/process_keycode/process_ucis.c
Add a callback style function qk_ucis_cancel to quantum/process_keycode/process_ucis.c, similar to qk_ucis_start_user and qk_ucis_success, that will be called in case the user cancels by sending KC_ESC during UCIS input.
Useful for cleaning up changes set up in qk_ucis_start_user, since neither qk_ucis_symbol_fallback nor qk_ucis_success will get called when input is cancelled.
Personally I use it for a workaround to UCIS not interpreting LT(_LAYER, KC_SPC) as KC_SPACE and thus not being able to finish UCIS input from my default layer. I layer_on() a UCIS specific layer in qk_ucis_start_user that then needs to be turned off after UCIS is finished.
> Add user-overridable callback for cancelling UCIS input

- docs/_summary.md
- docs/feature_split_keyboard.md
- docs/features.md
> [Docs] Add dedicated page for Split Keyboard information

- quantum/process_keycode/process_leader.c
- quantum/process_keycode/process_leader.h
Leader keys is limited to 5 keypresses, even the array for is sets it to 5, but at no time does it check to make sure that it's hit the end of the array before adding more key sequences.... which appears to crash the controller. 
This adds a sanity check to make sure that once you've hit 5 keys, it doesn't add more.  However, it forcibly ends the lead sequence, and may not process it correctly. 
* Fixes #5762
> Add out of bound check for Leader Key sequence array

- shell.nix
Temporary fix for https://github.com/qmk/qmk_firmware/issues/5868
Tried gcc versions `7.4` as well as `8.3`(the versions in the channels corresponding to the latest NixOS release - 19.03), both compile firmware, which does not work on Planck rev6. See issue for more details.
Fix the issue by pinning the "known-good" gcc ARM version from `18.09` channel.
Once the firmware is fixed to work on versions `7.4` and `8.3`, this change should be reverted.
* Temporary fix for #5868 (does not close the issue, but merely is a workaround on systems using `nix` package manager)
> Downgrade gcc-arm-embedded in shell.nix

- Vagrantfile
- docs/getting_started_vagrant.md
- util/vagrant/Dockerfile
- util/vagrant/readme.md
To help with environment predictability, this PR configures Vagrant to use qmk_base_container.
The process is as follows:
vagrant up
```
if using docker directly
build a slightly modified qmk_base_container with ssh
run container
else
build Debian vm
install docker
pull qmk_base_container
run container
patch so that we jump directly to container instead of to vm
```
vagrant ssh
```
Running inside qmk_base_container with the predicable toolchain
```
To an new/existing vagrant user, the change is transparent, and should not change the workflow.
> Configure Vagrant to use qmk_base_container

- docs/config_options.md
- tmk_core/common/action.c
This reduces the default timeout back to what was the hardcoded default was, but keeps the customizational options.
> Make Caps Lock delay more reasonable

- lib/lufa/Bootloaders/DFU/makefile
- tmk_core/avr.mk
This expands the `:bootloader` target, so that it should work with any non-V-USB AVR device.  Primarily, the ATMega32U4 and the AT90USB1286 boards.
This is accomplished by soft setting the settings in the makefile for LUFA's DFU firmware, and passing along the needed values to make.  
* closes #6244
big thanks to @yanfali for helping me figure out the mess of make commands to get this working.
> Expand bootloader target to support most AVR boards

- docs/i2c_driver.md
- drivers/arm/i2c_master.c
- drivers/arm/i2c_master.h
Currently the i2c_master driver assumes I2Cv2, which is fine for STM32 f3 boards but not f1. The changes required are quite minimal, and revolve around the config object and port init.
This allows the oled driver to work on bluepill boards, as can be seen https://github.com/zvecr/qmk_firmware/commit/f509a19fd06d1f84bba146de72d9da895d26345f
For the version configuration option, should we attempt to detect the MCU family and use the correct I2CvX automatically? (note, that is what is currently implemented here)
> Add ARM I2Cv1 support to i2c_master

- keyboards/clueboard/2x1800/2019/2019.c
Call led_set_user at the end of led_set_kb so that customizations can be made in keymaps.
> Call led_set_user at the end of led_set_kb for Clueboard 2x1800 2019

- drivers/arm/i2c_master.c
- drivers/arm/i2c_master.h
- keyboards/cannonkeys/satisfaction75/i2c_master.c
When compiling some generic I2C code, I was getting some compile issues on ARM due to the differences in API.  `i2c_readReg` is fine to take a non pointer regaddr, as its only ever going to be an [in] as its the address to read. This change also matches what the docs describe the API as.
I have checked all instances of `i2c_readReg` and none should cause an issue.
> Align ARM i2c_readReg with AVR

- docs/feature_combo.md
- quantum/process_keycode/process_combo.c
- quantum/process_keycode/process_combo.h
- quantum/quantum_keycodes.h
This adds the ability to enable, disable and toggle the state of the Combo feature without having to recompile if want to disable the feature.
This makes it useful, if you have modes where combos are actually in the way (such as when gaming).
* thread on reddit
> Allow Combo feature to be enabled/disabled live

- keyboards/xd004/keymaps/system_and_media/keymap.c
- keyboards/xd004/keymaps/system_and_media/readme.md
Guys I am sorry, there was useless code left over in my previous PR, plus `tap_code16` was spelled wrong. The thing was not compiling! Weird that Travis didn't warn us. Anyway, here's the fix.
> Fix advanced keymap readme and macro function

- docs/feature_encoders.md
- keyboards/abstract/ellipse/rev1/config.h
- keyboards/boston_meetup/2019/config.h
- keyboards/cannonkeys/ortho75/config.h
- keyboards/cannonkeys/satisfaction75/config.h
- keyboards/hadron/ver3/config.h
- keyboards/handwired/daishi/config.h
- keyboards/keebio/bdn9/config.h
- keyboards/keebio/iris/rev3/config.h
- keyboards/maxr1998/pulse4k/config.h
- keyboards/planck/ez/config.h
- keyboards/planck/rev6/config.h
- keyboards/preonic/rev3/config.h
- keyboards/rgbkb/sol/config.h
- keyboards/rgbkb/zen/rev2/config.h
- keyboards/rgbkb/zygomorph/rev1/config.h
- keyboards/ropro/config.h
- keyboards/tetris/config.h
- quantum/encoder.c
- quantum/split_common/transport.c
Instead, this calculates the number from the array of pins used. 
Thanks mtei for this, on the dip switch PR.
> Remove the need to specify NUM_OF_ENCODERS for the Encoder feature

- keyboards/melody96/melody96.c
The Melody96 keyboard file should define `led_set_kb()` rather than `led_set_user()`, as the latter makes it impossible to mix in a user-defined implementation of `led_set_user()` (it fails at link time). This PR fixes that.
Tested on my Melody96.
> Use led_set_kb instead of led_set_user in melody96.c

- keyboards/abstract/ellipse/rev1/config.h
- keyboards/halberd/config.h
- keyboards/kagamidget/config.h
- keyboards/nek_type_a/config.h
- keyboards/scythe/config.h
Another few outdated `IS_COMMAND` definitions that made it past code review. See #4301 #5065 #5269 for more information.
> Remove unnecessary IS_COMMAND definitions from a couple of boards

- docs/feature_backlight.md
- tmk_core/common/backlight.h
Turns out 15 levels wasn't enough for some people 😁 so it's increased to 5 bits.
Also, nudged the level bits over again and added a reserved bit, which could be eventually merged into the breathing bit, for a tiny (4) mode selector.
Once again there will be a further dimming of the backlight after flashing, which is solved by just hitting `BL_INC` until it's back where you want it.
* Supersedes #6343
> Extend maximum number of backlight levels to 31

- keyboards/cannonkeys/stm32f072/keyboard.c
The process_record_kb() function for cannonkeys/stm32f072 doesn't call process_record_user(), so any userspace keycode handling is ignored by boards using the stm32f072 support.  The fix is trivial - call process_record_user() at the end of process_record_kb() in the usual way.
*
> stm32f072: make sure userspace has chance to handle keycodes

- docs/feature_backlight.md
Arghhh... This section is all kinds of wrong - my bad. I confirmed with some test circuits that PNP transistors are in fact the ones which are active low.
But, this presents another problem: `BACKLIGHT_ON_STATE` is only respected for software PWM, *and* it defaults to 0, which is at odds with hardware PWM; it currently assumes an NPN. ~So this paragraph is still confusing as it appears to imply the default is `1`, since it's more common and is inherently true for hardware PWM~ **Reworded to reduce the confusion**.
I'm still experimenting to get this define working for hardware PWM, and I seem to be on the right track as the addition and usage of `COMxx0` in #2661 is pretty much what I came up with. `COMxx1` == clear on compare match, `COMxx1 | COMxx0` == set on compare match.
*
> Correct backlight on state docs

- quantum/rgblight.c
Some of the debug prints in `rgblight.c` use `xprintf()`, even though I think that function is primarily meant for printing errors. This means that the messages are printed regardless of whether debug mode is on, and they fill up the console rather quickly. This PR changes them to use `dprintf()` like the rest of the debug prints in the file.
P.S. This is the first PR I've ever submitted from my phone, since my laptop died. Hurray, but also I may have missed something because of that.
> Change xprintf() calls in rgblight.c to dprintf()

- quantum/split_common/split_util.c
Just like `is_keyboard_left`, this allows a board to use a alternative logic (maybe pin high/low), rather AVR vusb pad, to determine slave/master. This allows something like handwired AVR Teensy 2.0 to also have a way to force slave/master without hacking the split_common code.
<details>
<summary>Passing notes....</summary>
The current default for ARM is `true`, which causes issues if you want a ARM slave.
When using `SPLIT_TRANSPORT` within split common to tinker with available options, slave/master identification gets in the way.
I do not intend for this to be a long term solution, but it does align a few things for implementers.
</details>
> Allow board to override split keyboard master check

- keyboards/handwired/splittest/config.h
- keyboards/handwired/splittest/promicro/config.h
- keyboards/handwired/splittest/promicro/readme.md
- keyboards/handwired/splittest/promicro/rules.mk
- keyboards/handwired/splittest/readme.md
- keyboards/handwired/splittest/rules.mk
- keyboards/handwired/splittest/teensy_2/config.h
- keyboards/handwired/splittest/teensy_2/readme.md
- keyboards/handwired/splittest/teensy_2/rules.mk
- keyboards/handwired/splittest/teensy_2/teensy_2.c
Add a collection of boards to enable split testing, as preparation for future ARM split work.
The idea is to have something that testers can easily breadboard to verify the various stages of split development. One area being master/slave detection, which the teensy2 also suffers from. The advantage of solving this issue on teensy, is that is removes the dependency on having a working ARM split transport.
> Refactor handwired/splittest to support multiple boards

- tmk_core/common/action.c
This adds support for the `TAP_CODE_DELAY` to the tapping code for LT/MT and for SWAP Hand's Hold-Tap key.   And convert retro tap's register-unregister code to just tap_code for simplicity. 
*  Discord
> Add support for TAP_CODE_DELAY to Hold-Tap keys

- quantum/split_common/matrix.c
Storing `MATRIX_ROW_PINS_RIGHT` in a uint8_t array fails due to uint32_t being involved in the pin defs, and instead `pin_t` should be used to match the rest of the file. It currently produces the following error
```console
./lib/chibios/os/hal/ports/STM32/LLD/GPIOv1/hal_pal_lld.h:81:3: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
((ioline_t)((uint32_t)(port)) | ((uint32_t)(pad)))
```
<details>
<summary>Click for full log</summary>
```console
quantum/split_common/matrix.c: In function 'matrix_init':
./lib/chibios/os/hal/ports/STM32/LLD/GPIOv1/hal_pal_lld.h:81:3: error: large integer implicitly truncated to unsigned type [-Werror=overflow]
((ioline_t)((uint32_t)(port)) | ((uint32_t)(pad)))
^
quantum/config_common.h:202:17: note: in expansion of macro …
```
> Fix MATRIX_ROW_PINS_RIGHT and MATRIX_COL_PINS_RIGHT compilation on ARM

- keyboards/crkbd/keymaps/default/keymap.c
- keyboards/crkbd/keymaps/foostan/config.h
- keyboards/crkbd/keymaps/foostan/keymap.c
- keyboards/crkbd/keymaps/foostan/rules.mk
- Remove `LAYOUT_kc` s from the default keymap(Use `LAYOUT`).
- Fix some keys(remove tap dance, add arrow keys).
- Remove self defined keys(e.g. `KC_CTLTB`, `KC_RST ` and more).
- Disable keylogs.
*
> Refactor the default keymap for crkbd and add a new keymap for me

- docs/feature_tap_dance.md
Changes:
1. Added sub-section headings to the portion before the examples.
2. Edited text around sub-headings to better fit with sub-headings.
3. Added a new Example 6, that allows MO(layer) and TG(layer) functionality to be embedded within tap dance functions.
* The FIXME comment at the top of docs/feature_tap_dance.md is addressed, and therefore deleted.
My change is a documentation change. I have tested the code from my Example 6 using a MiniVan keyboard (see qmk_firmware/keyboards/thevankeyboards/minivan), and it works as it should. I believe my example code follows the code style of this project, but this is my first commit so I might have missed something.
> Add Sections and MO(layer)/TG(layer) Example

- keyboards/rgbkb/sol/keymaps/default/keymap.c
Small fix to display the correct default layer.
*
> [Keyboard] Sol r2: Fix default layer oled display

- keyboards/ares/config.h
- keyboards/bfake/config.h
- keyboards/canoe/config.h
- keyboards/donutcables/budget96/config.h
- keyboards/facew/config.h
- keyboards/ft/mars80/config.h
- keyboards/jc65/v32a/config.h
- keyboards/panc60/config.h
- keyboards/singa/config.h
- keyboards/unikorn/config.h
- quantum/template/ps2avrgb/config.h
The code that used this define was refactored a loooong time ago (#2187), and so it does absolutely nothing now.
> Remove NO_BACKLIGHT_CLOCK

- quantum/rgb_matrix.c
One-line fix for a typo that could break build if DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT was defined but not DISABLE_RGB_MATRIX_CYCLE_ALL
Ran into this when customizing keymaps. Given the code structure + comment, I assume this was what the code was originally supposed to be, and current version was an oversight
*
> One-line build fix

- drivers/oled/oled_driver.c
Currently OLED Dirver only supports LF (\n) character in a string to clear out the rest of the current line and advance to the next line for writing. This PR adds support for CR (\r) character as well to advance to the next line, however not clear out the rest of the current line. This is extremely useful when you want to display a multi-line logo using a single array without wiping out exiting lines and flagging the OLED as dirty unnecessarily. 
```
LF (\n):
"EX BUFFER L1"
"EX BUFFER L2"
oled_write("E1\nE2");
Result:
"E1          "
"E2 BUFFER L2"
CR (\r):
"EX BUFFER L1"
"EX BUFFER L2"
oled_write("E1\rE2");
Result:
"E1 BUFFER L1"
"E2 BUFFER L2"
```
*
> [OLED] Added support for CR

- keyboards/crkbd/readme.md
As the title says.  Adds documentation and default settings, so that people know where to start when converting over.
> [Keyboard] Add RGB Matrix config info to Corne Keyboard's readme

- keyboards/hs60/v1/rules.mk
- keyboards/hs60/v2/rules.mk
```json
{
"severity":"error",
"message":"Error: hs60/v1: Missing layout pp macro for ['60_ansi_split_bs_rshift']"
}
```
`60_ansi_split_bs_rshift` support does not exist in the header files, but `60_ansi` and `60_iso` do. I have left off `60_hhkb` from v2 as the current macro is incompatible.  
Tagging @yiancar as maintainer.
> Fix community support for hs60

- keyboards/keebio/rorschach/keymaps/insertsnideremarks/readme.md
- keyboards/keebio/rorschach/keymaps/tuesdayjohn/config.h
- keyboards/keebio/rorschach/keymaps/tuesdayjohn/keymap.c
- keyboards/keebio/rorschach/keymaps/tuesdayjohn/rules.mk
> Added keymap folder matching username to rorschach; added readme to old keympa

- docs/newbs_flashing.md
Fixed a minor typo where ergodox is misspelled. It made me scratch my head for a while, because I couldn't build my keyboard.
> Fix typo for building Ergodox EZ keyboards

- docs/faq_build.md
Currently the suggestion for caterina flashing is to disable ModemManager, however Udev can be told to filter out these devices. The only potential stumbling block is that filtering only works when not in strict mode, so I have added a note about this with a scripted workaround.
While in the area, I have also added some dfu-util Udev rules to cover the scenarios that I currently have access to.
> Add dfu-util and caterina udev examples

- keyboards/rgbkb/sol/keymaps/default/keymap.c
Fixed the default oled rotation to match the expected bottom facing oled connector instead of my prototype with the top facing connector.
*
> Fixing Sol Rev2 Default keymap OLED rotation.

- keyboards/melody96/keymaps/zunger/keymap.c
Adding some new commonly-needed keys (as discovered with use) to the melody96:zunger keymap: currency symbols, the degree sign, Spanish punctuation marks, and combining accents.
* 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qmk/qmk_firmware/6478)
> Add some more commonly used symbols to melody96/zunger.

- docs/config_options.md
- docs/feature_split_keyboard.md
- quantum/split_common/matrix.c
Adds support for different direct pin mappings on the halves of a split keyboard.
* N/A
> Add config option for DIRECT_PINS_RIGHT

- keyboards/alice/config.h
- keyboards/ergo42/rev1/config.h
- keyboards/ergo42/rules.mk
- keyboards/helix/rev1/config.h
- keyboards/helix/rules.mk
- keyboards/jj50/config.h
- keyboards/jj50/rules.mk
- keyboards/lets_split/keymaps/zer09/config.h
- keyboards/lets_split/rules.mk
- keyboards/lily58/rev1/config.h
- keyboards/lily58/rules.mk
- keyboards/meira/featherble/config.h
- keyboards/meira/promicro/config.h
- keyboards/meira/rules.mk
- keyboards/orthodox/rev3/config.h
- keyboards/skog/config.h
- keyboards/winkeyless/bface/config.h
- keyboards/winkeyless/bface/rules.mk
- keyboards/ymd75/config.h
- keyboards/ymd96/config.h
Another round of dead code removal. `CATERINA_BOOTLOADER` and `BOOTLOADHID_BOOTLOADER` are never used anywhere, and they duplicate the `BOOTLOADER_*` defines set in bootloader.mk.
Also made sure `BOOTLOADER` was correctly set for all of the touched boards.
*
> Remove unused _BOOTLOADER defines

- util/win_shared_install.sh
When running qmk_install.sh on a fresh Windows install, the script gets as far as prompting to run qmk_driver_installer.exe, and then sits at a command prompt until you type `exit` - it continues on its way but the driver installer never gets run.
Turns out on Msys2, you need to pass `//c` (double slashes) to cmd.exe, otherwise it will think you mean the C:\ drive.
I don't know if this is an issue on WSL too, and if not, whether this extra character will break it in turn. Please test :)
*
> Fix qmk_install.sh on Windows dropping to command prompt

- quantum/process_keycode/process_midi.c
MIDI noteon events accept velocity from 0-127. Basic MIDI mode was sending 128 velocity, which does not work. This fix allows midi to work.
If you `#define MIDI_BASIC` and then press your `MI_ON` key, then it will actually send proper MIDI note ons.
> * MIDI: Fix basic noteon: send correct velocity

- quantum/quantum_keycodes.h
A purely cosmetic change (and a typo fix). Nothing else references these enum values.
I think the current name for this range is not entirely apt, as they are not "TMK" keycodes; they are defined in the HID spec. Given how often the "basic" keycodes are mentioned in the docs and elsewhere, this might clear up some confusion for anyone digging into the code.
But, maybe there is sentimental/historical value in it?
*
> Rename QK_TMK(_MAX) to BASIC

- tmk_core/common/action.c
- tmk_core/common/action_code.h
This should allow you to do things like `LCTL_T(KC_LGUI)` for a Control/GUI Mod-Tap.
*
> Extend allowed range of tappable keycodes to include modifiers

- quantum/mcu_selection.mk
- quantum/template/avr/rules.mk
- quantum/template/ps2avrgb/rules.mk
For about 80% of the boards in QMK right now, we actually only need specify `MCU`, `BOOTLOADER` and the feature options.
Should I remove this stuff from the templates too?
*
> Add some defaults for ATmega32A to mcu_selection.mk

- quantum/process_keycode/process_tap_dance.h
The Tap Dance index should be `|`ed with `QK_TAP_DANCE` and masked to its proper range of 0 to 255.
*
> Mask off TD() parameter properly

- tmk_core/common/wait.h
Using LT() causes some ARM keyboards to apparently crash.
Issue was tracked down to commit https://github.com/qmk/qmk_firmware/commit/3261c408e454dbc3cc2a1591ba62575036af19ad.
The code change is innocent looking, but the `TAP_CODE_DELAY` macro defaults to 0 and in theory, would not optimise out the sleep call. The ChibiOS docs have the following:
>#define chThdSleepMilliseconds    (         msec    )       chThdSleep(TIME_MS2I(msec))
Delays the invoking thread for the specified number of milliseconds.
>Note
The specified time is rounded up to a value allowed by the real system tick clock.
The maximum specifiable value is implementation dependent.
Use of this macro for large values is not secure because integer overflows, make sure your value can be correctly converted.
Parameters
[in] …
> Fix LT() crashing some ARM keyboards

- Makefile
- util/docker_build.sh
Discussed within #6065.
The main take-away is that windows vagrant and macos docker can have poor filesystem performance. This PR attempts to work around that issue by providing a method of keyboard discovery that seems to be faster, up to a factor of 3x.
> Add an alternative method for keyboard discovery to speed up build

- docs/feature_encoders.md
- docs/feature_split_keyboard.md
- quantum/encoder.c
Adds option to define `ENCODERS_PAD_A_RIGHT` and `ENCODERS_PAD_B_RIGHT` to allow right half of split keyboard to have a different encoder pinout than the left half. Needed for upcoming Iris Rev. 4.
*
> Add support for different encoder pinout for right half of split keyboard

- docs/feature_rgb_matrix.md
Adds an entry to the docs for the default mode for RGB Matrix when starting up for the first time.
> [Docs] Add RGB Matrix default mode define info

- keyboards/ergodox_infinity/keymaps/halfkeyboard/rules.mk
- keyboards/ergodox_infinity/rules.mk
- keyboards/infinity60/rules.mk
- keyboards/k_type/rules.mk
- keyboards/whitefox/rules.mk
- message.mk
- tmk_core/arm_atsam.mk
- tmk_core/avr.mk
- tmk_core/chibios.mk
- tmk_core/rules.mk
This adds a `:flash` target that detects the board and bootloader type, and runs the correct flashing command, based on that information.
This supports AVR, and ChibiOS based ARM boards, as ATSAM has no flash command in QMK, currently.
This also cleans up the `:dfu` target to make it more modular, the way the `:avrdude` target is.
> Add a universal flash command for cli

- docs/custom_quantum_functions.md
- docs/feature_oled_driver.md
- docs/feature_userspace.md
- docs/ref_functions.md
- quantum/quantum.c
- quantum/quantum.h
- quantum/visualizer/visualizer.c
- quantum/visualizer/visualizer.h
- tmk_core/common/action_layer.h
- tmk_core/common/eeconfig.c
This updates the documents, and the tri-layer functions to use the correct code. 
Additionally, it adds `get_highest_layer(state)` (subject to renaming) to replace the `biton32` function with the correct version of the function.
> Additional changes for Layer State typedef compatibility

- keyboards/massdrop/ctrl/keymaps/mac/keymap.c
This includes the modifier keys in "keys only" mode of the RGB matrix, bringing the keymap
closer to how the off-the-shelf firmware behaves.
* None
> Fix RGB_TOG cycle for Massdrop CTRL default keymap

- docs/flashing.md
- tmk_core/chibios.mk
As an end user, I want to have a consistent behaviour when flashing firmware from the commandline. Having to remember that bootloader type X, requires slightly different process Y is a pain.
Align flashing retry logic of dfu-util with dfu and avr dude, where it will search/retry multiple times rather than only try once. Also added an alias for `dfu-util-wait` as its not longer required but might be used by end users. 
**Note**: grepping in english should be fine for now, as dfu-util contains untranslated output.
> Align flashing behaviour of dfu-util

- docs/_summary.md
- docs/driver_installation_zadig.md
- docs/faq_build.md
A brief primer on how to use Zadig, how not to use it, and how to get yourself out of the "installed driver on wrong device" pickle.
*
> Add Zadig 101 to docs

- layouts/community/60_tsangan_hhkb/bcat/keymap.c
- layouts/community/60_tsangan_hhkb/bcat/readme.md
Basically a straightforward port of my existing `60_ansi_split_bs_rshift` layout to a Tsangan bottom row (for use with CanonKeys Instant60 PCB, right now).
None
> Add new 60% Tsangan HHKB layout

- keyboards/ft/mars80/mars80.h
Fixed a bug in which k2c, while used in the physical matrix was set to KC_NO in the electrical matrix.
> Mars80 Bug: Physical/Electrical Matrix Mismatch

- drivers/oled/oled_driver.c
`OLED_TIMEOUT` is defined in `oled_driver.c` and `oled_driver.h`, but not in the same way.   This is redundant and can cause compiler errors if the timeout is disabled or set. 
This removes the define from `oled_driver.c`, fixing the issue.
> Fix Redefinition of OLED_TIMEOUT

- keyboards/cannonkeys/instant60/rules.mk
Support flashing Instant60 from the command line (via :flash or :dfu-util).
Before this change, flashing from the command line errors out with "More than one DFU capable USB device found! Try `--list' and specify the serial number or disconnect all but one device". (QMK toolbox works fine to flash, but it's annoying to have to use it for just this one board.) After this change, flashing finds the correct DFU device and works fine.
> Support flashing Instant60 from command line

- keyboards/dz60/rules.mk
Support flashing DZ60 with :flash command, instead of requiring :dfu to be manually specified. 
Before this change, :flash gives an error that it doesn't know what bootloader to use. Since all DZ60's come with atmel-dfu bootloader by default, may as well configure that so :flash works.
> Support flashing DZ60 with :flash command

- docs/i2c_driver.md
- drivers/avr/i2c_master.c
Looking at moving a keyboard of mine to the generic i2c driver, I noticed [the docs](https://beta.docs.qmk.fm/for-makers-and-modders/i2c_driver#configuration) mentioned that you could tune the frequency using the Prescaler for i2c, something I considered fairly niche, but it got me curious and I looked at the [implementation](https://github.com/qmk/qmk_firmware/blob/master/drivers/avr/i2c_master.c#L30-L34) 
As it turns out, this define isn't guarded by an ifndef, and isn't even used to set the prescaler, just to calculate the TWBR value.
discussing it with @zvecr in the discord it seemed not really useful, and I decided to open this PR removing it. This means it's still fixed at 1 as before, but docs don't mention it.
> Removed prescaler define from avr i2c, as it was impossible to use

- keyboards/atreus/keymaps/workman/README.md
- keyboards/atreus/keymaps/workman/config.h
- keyboards/atreus/keymaps/workman/keymap.c
This adds an implementation of the Workman layout for Atreus keyboards.
> [Keymap] Workman layout for Atreus keyboard

- .travis.yml
Specifically, the `util/travis_compiled_push.sh` runs a number of cleanup and deployment routines. This includes `dos2unix` that fixes the line endings for sanity's sake.   However, it only runs on successful builds.  That would be fine, except some builds WILL fail (community layouts, yay), which is a problem. 
This should change the behavior to always run the post compile checks. 
However, in the long run, we should break up this script into more parts.
* https://docs.travis-ci.com/user/job-lifecycle/
* https://docs.travis-ci.com/user/uploading-artifacts/
> Always run `util/travis_compiled_push.sh`

- util/msys2_install.sh
`pacman -S msys/clang` returns `error: target not found: clang`. This happens both in the MSYS2 terminal, and the MinGW terminal, because [there is no msys2 clang package](https://github.com/msys2/MSYS2-packages/issues/380).
Apparently, this makes pacman lose its train of thought during `msys2_install.sh`, and no packages are installed at all...
*
> Fix msys2 not installing any packages because it can't find clang

- keyboards/atreus/atreus.h
I was wondering why the PCBDOWN=yes option had no effect on the two middle keys of my Atreus. As @technomancy, the maker of the keyboard [said](https://github.com/qmk/qmk_firmware/commit/79ae59c155c76394b09fb4286951a6ed5b71d82d#commitcomment-34836401):
> this is because these two keys are distinguished by row, not by column, and PCBDOWN only flips the columns.
This is basically his commit ab80f2fa79c1abdd9eda6e115ebeb724e302f105.
* My question in 79ae59c155c76394b09fb4286951a6ed5b71d82d
> [Keyboard] Flip the middle two keys when PCBDOWN is set.

- keyboards/lfkeyboards/lfk78/rules.mk
- keyboards/lfkeyboards/lfk87/rules.mk
- keyboards/lfkeyboards/mini1800/rules.mk
- keyboards/lfkeyboards/smk65/rules.mk
- keyboards/naked48/rules.mk
- keyboards/sixkeyboard/rules.mk
- keyboards/xd004/v1/rules.mk
- quantum/mcu_selection.mk
This is pretty much the last of the MCUs currently in the repo, apart from the 328P, and since there's only a handful of them I removed the relevant stuff in their `rules.mk`s too. No 16U4s at all actually, but I threw it in there just in case.
*
> Add 16U2, 16U4 and USB646 to mcu_selection.mk

- keyboards/planck/keymaps/default/keymap.c
The default keymap for Planck keyboard has missing legend for music mode MU_MOD)
*
> fix missing "music mode" legend

- util/docker_build.sh
Two minor changes to the Docker build script: replace stray space indentation with tab, and add `errcho` function to replace repeated `echo >&2` output redirections.
> Update docker_build.sh: indentation fix, error echo function

- tmk_core/common/avr/bootloader.c
- tmk_core/common/avr/timer.c
Of note here is that `~(FUSE_BOOTSZ0 & FUSE_BOOTSZ1)` in particular for some reason adds an extra 4 bytes to the final binary. I don't see it as too much of an issue though, as that block of code is only compiled in if `BOOTLOADER_SIZE` is not defined, and pretty much every keyboard does either directly or through `BOOTLOADER`, in rules.mk.
*
> Banish some more magic numbers

- tmk_core/protocol/lufa/adafruit_ble.cpp
Requested by dohmain#0566 on Discord (who reports that this works). Apparently, you can get the [BLE modules](https://www.adafruit.com/product/2633) used in the Feather by themselves. This should allow them to be used by things like Teensys and 5V Pro Micros which have 16MHz crystals.
*
> Adafruit BLE: Set SPI2X bit only when F_CPU is 8MHz

- message.mk
- tmk_core/avr.mk
- tmk_core/chibios.mk
We have the same "bootloader not found" message in at least 3 spots.  This replaces them with a variable/thing, so that they can be more easily managed, in the future.
> Move Bootloader not found message to global variable

- keyboards/waldo/config.h
- keyboards/waldo/rules.mk
Nebulant reported that he could not control RGB animations on his Waldo PCB. 
Turns out RGB is defined but animations aren't enabled. I also took the opportunity to clean up the rules.mk file.
> Waldo RGB Enable

- keyboards/maartenwut/atom47/rules.mk
When travis decides to make all keyboards, the output currently contains the following:
```console
Making default keymaps for all keyboards
QMK Firmware 0.7.13
Makefile:542: keyboards/adkb96/rev1/rules.mk: No such file or directory
Makefile:542: keyboards/atom47/rev3/rules.mk: No such file or directory
```
This PR allows the boards to be built so that we get the expected coverage.
> Fix boards being skipped during make all

- keyboards/georgi/sten.c
It was sending a comma keypress, while I believe that the targeted 
stenography software (at least on systems that generally use
US-International keyboard layout) expects a single-quote/apostrophe key.
@germ, the main author of this part of the code, has previously taken a brief
look at this patch in pull request [germ/qmk_firmware#8](https://github.com/germ/qmk_firmware/pull/8#issuecomment-529151901).
> Fix Georgi's RZ key in NKRO fake-steno mode

- common_features.mk
If you enabled bothe DRV2605 and SOLENOID, it would only enable one of these, not both. 
This fixes the check so that you can enable both options.
> Fix enables for Haptic Feedback

- keyboards/planck/keymaps/default/keymap.c
- keyboards/preonic/keymaps/default/keymap.c
The dip_switch_update callback was overriding the default startup sound.  This should prevent that from happening, and still allow it to play sounds, or stop them, when appropriate.
Specifically, this was caused because the dip switch was only being called on change, but not on initialization.   The recent dip switch feature changes this so that it's always called, to properly set the initial state.  However, this was effectively disabling the startup sound.
> Fix default keymaps for OLKB boards to play Startup Sound

- keyboards/preonic/keymaps/default/keymap.c
Removes accidental text in default preonic keymap.
- [ x] Bugfix
* #6747
> remove accidental characters in default preonic keymap

- keyboards/percent/booster/info.json
Fixing something I missed in a PR review a while back.
(info.json/keyboard.h macro name mismatch)
> Percent Studio Booster: Configurator fix

- keyboards/xd87/xd87.c
Add capslock LED support for xd87.
*
> xd87: add capslock led support

- keyboards/planck/keymaps/default/keymap.c
This should fix the compile issues that I introduced by not properly testing out the boards. 
This time, they've been more thoroughly tested to ensure that they don't break anything. 
* Travis, and flagged issue.
> [Keyboard] Fix compile issues for OLKB Default keymaps

- quantum/encoder.c
Updated split encoders so indexes are based on left hand encoders first.
This ensures when swapping master sides that code logic based on encoder index doesn't change.
*
> Updated split encoders so indexes are based on left hand encoders first.

- keyboards/1upkeyboards/1up60hte/1up60hte.c
- keyboards/1upkeyboards/1up60hte/keymaps/default/keymap.c
- keyboards/1upkeyboards/1up60hte/keymaps/hhkb/keymap.c
- keyboards/1upkeyboards/1up60hte/readme.md
- keyboards/1upkeyboards/1up60hte/rules.mk
It was reported to me that using QMK Configurator for the 1up60hte would result in the caps lock LED failing to illuminate. Turns out the functionality was only available on the default and hhkb keymaps. I've moved said code to keyboard level to accomodate this. 
In addition, I set the bootloader to atmel-dfu.
> 1up60hte cleanup + bugfix

- .vscode/settings.json
- docs/feature_tap_dance.md
- quantum/process_keycode/process_tap_dance.c
- quantum/process_keycode/process_tap_dance.h
This generalizes the tap dance function so that other layer functions are possible, without a significant amount of work. 
This is based in #1993, but adds documentation, and fixes a potential bug in the dance that was missed. 
* Closes #1993
> Generalize Tap Dance Layer functions

- keyboards/planck/light/light.h
- keyboards/planck/rev1/rev1.h
- keyboards/planck/rev2/rev2.h
- keyboards/planck/rev3/rev3.h
- keyboards/planck/rev4/rev4.h
- keyboards/planck/rev5/rev5.h
- keyboards/planck/rev6/rev6.h
- keyboards/preonic/preonic.h
Apparently QMK API can't parse layout macro aliases if you use more than one space character between the alias name and the macro name, which messes up their discoverability in QMK Configurator.
```
{
"message": "Error: planck/light: Missing layout pp macro for ['planck_mit']",
},
{
"message": "Error: planck/rev1: Missing layout pp macro for ['planck_mit']",
},
{
"message": "Error: planck/rev2: Missing layout pp macro for ['planck_mit']",
},
{
"message": "Error: planck/rev3: Missing layout pp macro for ['planck_mit']",
},
{
"message": "Error: planck/rev4: Missing layout pp macro for ['planck_mit']",
},
{
"message": "Error: planck/rev5: Missing layout pp macro for ['planck_mit']", …
```
> Fix OLKB layout macro aliases

- .gitignore
In the .gitignore file DS_Store was listed as DS_STORE and DS_Store files weren't being ignored on macos.
> Correct casing for DS_Store in .gitignore

- tmk_core/common/timer.h
I did not cast the result back to unsigned for the timer_expired functions to properly handle wrapping. So this bugfix fixes that issue by adding the correct cast. The timer will now properly handle checking against wrapped values easily and correctly.
```
uint16_t whenToTrigger = timer_read() + SOME_FUTURE_TIME;
If (timer_expired(timer_read(), whenToTrigger))
// Future time has been reached, no worrying about time wrapping!
```
*
> Fixing wrapping math logic for timer_expired functions

- keyboards/copenhagen_click/click_pad_v1/config.h
Changed the pinouts in the copenhagen clickpad, since the firmware was still using the ones from the prototype
*
> Fix pinout on the copenhagen clickpad

- keyboards/model01/keymaps/dshields/keymap.c
- keyboards/planck/keymaps/dshields/keymap.c
- users/dshields/config.h
- users/dshields/dshields.c
- users/dshields/dshields.h
- users/dshields/rules.mk
- Add oneshot mod/layer unlocking
- Fix Planck rev 3 backlight breathing
- Fix Planck rev 6 build with arm gcc 9.2.0
- General code clean up
> Various enhancements for dshields user space and keymaps.

- keyboards/niu_mini/keymaps/tobias/config.h
- keyboards/niu_mini/keymaps/tobias/keymap.c
- keyboards/niu_mini/keymaps/tobias/readme.md
- keyboards/niu_mini/keymaps/tobias/rules.mk
- keyboards/preonic/keymaps/senseored/config.h
- keyboards/preonic/keymaps/senseored/keymap.c
- keyboards/preonic/keymaps/senseored/readme.md
- keyboards/preonic/keymaps/senseored/rules.mk
Just new layouts for 2x different keyboards.
*
> Added two different Swedish layouts for the Niu Mini 40% and Preonic 50%.

- keyboards/clueboard/readme.md
Small change to fix the README link to go to the actual 66_hotswap instead of just the 66%.
The markdown link in the clueboard readme used to go to the 66 even if you clicked on the hotswap board, this is a small change and it has been corrected here.
> Minor link fix in Clueboard README

- layouts/community/75_ansi/yanfali/keymap.c
- layouts/community/75_ansi/yanfali/rules.mk
- users/yanfali/config.h
- work around flash issues by disabling most of the animations
- I use a 2 * 1.5u on right side of space bar, so ignore center 1.25 position right of space.
*
> Use 75_ansi and community layout for xd84

- docs/config_options.md
- docs/feature_split_keyboard.md
- docs/flashing.md
- docs/newbs_flashing.md
- tmk_core/chibios.mk
- tmk_core/common/eeconfig.c
No method to set eeprom handedness
Existing AVR implementations rely on flashing another file to set a particular eeprom byte.
ARM currently looks like it has no way to configure EECONFIG_HANDEDNESS within the emulated eeprom via dfu-util or another tool.
Until a solution is found, this PR emulates the behaviour with the limitation that produces different binaries for the left and right sides.
> ARM split - Add support for dfu-util EE_HANDS flashing

- util/drivers.txt
This ports the changes from https://github.com/qmk/qmk_toolbox/pull/122 to the drivers.txt used during qmk_install.sh. Mostly just removing the unsupported ATxmega MCUs, and adding an entry for USBaspLoader.
*
> Port drivers.txt changes from the Toolbox

- lib/python/qmk/cli/doctor.py
This fixes the following issue related to encoding on linux systems. The
solution is to use bytes formated new line character regardless of the
encoding.
☒ a bytes-like object is required, not 'str'
File "/usr/local/lib/python3.7/site-packages/milc.py", line 564, in __call__
File "/usr/local/lib/python3.7/site-packages/milc.py", line 569, in __call__
return self._entrypoint(self)
File "$HOME/qmk_firmware/lib/python/qmk/cli/doctor.py", line 56, in doctor
for line in mm_check.stdout.split('\n'):
TypeError: a bytes-like object is required, not 'str'
No opened issue.
> Fix qmk doctor 'bytes-like object is required' on linux

- tmk_core/common/util.h
`bitrev16()` in particular is [called](https://github.com/qmk/qmk_firmware/blob/37c29961379f39dd60f173b4b82df41a4f80b078/keyboards/converter/usb_usb/custom_matrix.cpp#L248) from the Hasu USB-USB converter's custom matrix, a C++ file. So, it needs this in order to compile with Console enabled.
*
> Wrap util.h functions in `extern "C"`

- keyboards/reviung34/config.h
- keyboards/reviung34/keymaps/default/config.h
- keyboards/reviung34/keymaps/default/keymap.c
- keyboards/reviung34/keymaps/default/readme.md
- keyboards/reviung34/readme.md
- keyboards/reviung34/reviung34.c
- keyboards/reviung34/reviung34.h
- keyboards/reviung34/rules.mk
Add Reviung34 keyboard.
The REVIUNG34 SPLIT is 34-key split ortholinear keyboard.
Use a LAN cable to connect the left and right keyboards.
*
> [Keyboard] Add keyboard Reviung34

- lib/python/qmk/cli/new/keymap.py
The command `gmk new_keymap` is not working due to an undefined variable:
```
$ ./bin/qmk new_keymap
Keyboard Name: ergodox_ez
Keymap Name: testing-123
<class 'NameError'>
☒ name 'username' is not defined
File "/tmp/qmk_firmware/lib/python/milc.py", line 564, in __call__
File "/tmp/qmk_firmware/lib/python/milc.py", line 569, in __call__
return self._entrypoint(self)
File "/tmp/qmk_firmware/lib/python/qmk/cli/new/keymap.py", line 22, in new_keymap
keymap_path = os.path.join(kb_path, "keymaps/%s" % username)
NameError: name 'username' is not defined
```
This feature was added and working in #6066 but appears to have broken during the refactoring in #6708.  See https://github.com/qmk/qmk_firmware/pull/6708/files#diff-d5208bcbc79aa42855 …
> Use `keymap` instead of `username` variable for `qmk new_keymap`

- keyboards/40percentclub/mf68/keymaps/emdarcher/keymap.c
Fixing the LED code in my keymap to use both LEDs on the Pro Micro. Before, it was incorrectly using pin B5 instead of D5.
Edited the LED driving code to accurately use the LEDs on pins B0 and D5 instead of B0 and B5 as my previous code was doing.
Fixing use of incorrect pins for LEDs in my keymap.
*
> Mf68 keymap LED pins fixed

- keyboards/cannonkeys/satisfaction75/satisfaction_oled.c
Some `sprintf` calls in the `satisfaction75` driver were being used to fill buffers with an exact number of characters for date and time, but the buffers didn't account for the `NULL` terminator `sprintf` always adds, thus writing beyond the provided buffer.
So this simply increases the size of those buffers by 1.
> Fix buffer sizes for sprintf overflows.

- keyboards/katana60/keymaps/default/keymap.c
The top-right key should be = and not the shifted pseudo-key +. This matches the sample keyboard from the [picture in the readme][0].
[0]: https://i.imgur.com/xVkODOu.jpg
cc @rominronin
> katana60: Fix = key in default keymap

- docs/feature_tap_dance.md
Cleaned up and updated Tap Dance code examples in the documentation.
Under Example 6 in the Tap Dance Documentation, the code created a variable called `active_layer` to track which layer was active using a switch statement in `layer_state_set_user()`.  This is no longer needed as one can use the built in `layer_state_is( layer )` function to check whether a layer is active. This function also works better in this case as it will not only work for the current top active layer, but will also check for other active layers that aren't currently on top.
In addition, the code was not formatted according to the coding conventions of the other examples in the document, so I changed it to match.
Edited the markdown so it will format the C code with syntax highlighting.
*
> Update and cleanup of Tap Dance Documentation

- docs/cli.md
- lib/python/qmk/cli/__init__.py
- lib/python/qmk/cli/docs.py
Added a command that runs the builtin HTTP server provided by Python, to serve the docs from the comfort of your own PC.
*
> CLI command to serve docs locally

- tmk_core/protocol/usb_descriptor.c
- tmk_core/protocol/usb_descriptor.h
The raw HID interface is given a number of 1:
https://github.com/qmk/qmk_firmware/blob/efb7f3cc3a5844a8da40ce78c64f7da88e39766c/tmk_core/protocol/usb_descriptor.h#L138-L143
However, it is usually not at *index* 1 in the configuration descriptor, because it is placed after the mousekeys, NKRO and shared (extrakeys) interfaces, and Google's libusb wrapper apparently wants them to be the same, citing the USB spec:
https://github.com/google/gousb/blob/18f4c1d8a750878c4f86ac3d7319b8aa462a79f9/libusb.go#L295-L297
```go
if ifNum != i.Number {
return nil, fmt.Errorf("config %d interface at index %d has number %d, USB standard states they should be identical", c.Number, ifNum, i.Number)
}
```
And this does seem to be the case. The description for `bInterfaceNumber` in the USB 2.0 spec …
> Reorder Raw HID interface to match what the USB spec expects

- docs/feature_tap_dance.md
Just noticed that I forgot to remove in my previous Pull Request the line that declares the `active_layer` variable that is not needed any more. 
Removed the line declaring the unneeded variable `active_layer`. I should have caught this on the first PR which rendered this unneeded, but missed it.
*
> unneeded line of code removed in Tap Dance documentation

- quantum/config_common.h
When using `CTPC=yes`, and `#define CONVERT_TO_PROTON_C_RXLED`, the wrong pin is used for the TX led. When code runs to flash the RX led, the TX led will incorrectly light up.
> Fix CONVERT_TO_PROTON_C_RXLED pins

- docs/config_options.md
- docs/feature_split_keyboard.md
- quantum/split_common/matrix.c
- quantum/split_common/split_util.c
- quantum/split_common/split_util.h
Master/slave detection is hard coded to always assume master
This PR changes the startup behavior to detect an active USB connection when delegating master/slave. If this operation times out, then the half is assume to be a slave. This is the default behavior for ARM, and required for AVR Teensy boards (due to hardware limitations).
<details><summary>CLICK ME FOR INVESTIGATION INFO</summary>
Split code currently expects to run different routines on slave and master. The assumption is that devices cannot run both a requester and responder concurrently. The current process is that the master pulls the matrix and encoder data from the slave, and pushes rgb and backlight settings to the slave.
Current AVR init order:
```
lufa/lufa.c::main
keyboard.c::keyboard_setup
split_util.c::matrix_setup …
```
> ARM split - detect USB to select master/slave

- drivers/arm/i2c_master.c
- keyboards/ergodox_stm32/config.h
Introduced in #5398, duplicate I2CV1 configuration has been removed, and migrated via existing config values.
> Remove i2c logic for STM32F103xB in favour of USE_I2CV1 

- tmk_core/common/chibios/printf.c
When debugging debounced matrix keypresses on ARM, you get the following blank output:
```
r/c 01234567
00: 
01: 
02: 
03: 
04: 
05: 
06: 
07: 
```
Printing is done via `xprintf("%08b", i)`, digging into the tinyprintf lib that is used, it lacks binary support. This PR enables support and produces the expected output:
```
r/c 01234567
00: 00000000
01: 00001000
02: 00000000
03: 00000000
04: 00000000
05: 00000000
06: 00000000
07: 00000000
```
> ARM - Fix missing debug_matrix output

- quantum/rgblight.c
There's an occasional 'lag' frame of animation or two when using the 'snake' RGB animation when the 'snake' reaches the last LEDs. This small fix just corrects that issue (it will no longer try to set LEDs that don't exist).
*
> Fix small hiccup in snake animation

- docs/fr-FR/newbs_testing_debugging.md
- docs/newbs_testing_debugging.md
- docs/zh-cn/newbs_testing_debugging.md
Since the switch hitter site is no longer up, and has shown no signs of returning, lets replace the links with the Wayback machines indexed version. 
This way, the files can be accessed and downloaded by users.
> [Docs] Replace Switch Hitter link with Wayback Machine link

- quantum/quantum.c
- tmk_core/common/action.c
- tmk_core/common/action.h
This bug prevents you from calling the `_code16()` functions with a right modifier. Example:
```c
tap_code16(ALGR(KC_O));
```
On Windows, the above will emit `KC_O`, Left Alt and every right modifier. This is because the `QK_L/RCTL` etc. enum entries are *not* bitmasks; four of the bits represent the type of mod, and the fifth bit is the "left/right" flag. Thus, the mod checking `if`s will AND the keycode with `QK_R*`, and evaluate to true every time!
Instead, we should collect the mods we find in a variable, and look for the right flag separately. Then finally, we call `f()` with our mod bitmask.
*
> Fix bug in `do_code16()`

- keyboards/handwired/splittest/teensy_2/config.h
- keyboards/vitamins_included/rev1/config.h
- quantum/split_common/split_util.c
Disable USB after we become slave, as checks seem to partially enable it somehow.
Now when using `#define SPLIT_USB_DETECT` on avr, you no longer need to also use `#define NO_USB_STARTUP_CHECK` to avoid slave "locks up" during startup.
Tagging @Duckle29 as I have also refactored vit inc rev 1.
> SPLIT - Remove NO_USB_STARTUP_CHECK requirement for usb detection

- keyboards/maartenwut/plain60/keymaps/via/keymap.c
- keyboards/maartenwut/plain60/keymaps/via/rules.mk
- keyboards/maartenwut/plain60/rules.mk
Adds a VIA keymap target to plain60. Tested on plain60-c with VIA 0.5.4 macOS
*
> Add a via compatible keymap

- docs/coding_conventions_c.md
> Fix incorrect spacing in example on Coding Conventions page

- util/linux_install.sh
Due to "pip3 install" failed in script linux_install.sh. python-pip has been added as package dependency for archlinux.
#7040
*
> Add python-pip as package dependency for archlinux

- keyboards/preonic/keymaps/cranium/config.h
- keyboards/preonic/keymaps/cranium/keymap.c
- keyboards/preonic/keymaps/cranium/readme.md
- keyboards/preonic/keymaps/cranium/rules.mk
Add the keymap I use daily. There are more info about this mapping in the README.
> [keymap] Romain's Preonic layout

- keyboards/v60_type_r/v60_type_r.c
When Backlight and the custom RGB are both enabled on this board, they both try to use timer 1. The latter should be using timer 3 instead, to avoid this conflict.
* Fixes #7094
> Change V60 Polestar RGB timer to 3

- keyboards/maartenwut/wonderland/keymaps/rys/keymap.c
Just a personal layout for my Lubrigante with Wonderland PCB.
> Personal layout for the Wonderland

- keyboards/lets_split/keymaps/halvves/config.h
- keyboards/lets_split/keymaps/halvves/keymap.c
- keyboards/lets_split/keymaps/halvves/rules.mk
Hey! Just finally taking the time to toss my keymap up in the repo. Thanks!
> [keymap] add halvves let's split keymap

- docs/hardware_avr.md
- docs/hardware_drivers.md
- docs/reference_glossary.md
- docs/understanding_qmk.md
While this was historically a valid possibility, nowadays, it reads
kinda weird, and the [Oxford Dictionaries Online suggests to avoid it](https://english.stackexchange.com/a/56010).
Thus, I removed it everywhere I found it.
> Remove apostrophe from various abbreviations' plural forms

- docs/cli.md
- lib/python/milc.py
- lib/python/qmk/tests/test_cli_commands.py
The subcommand functions' name follows the Python convention of using
snake case, but looks odd on the command line.
Fix it by converting underscores to dashes, eg.: list_keyboards ->
list-keyboards.
* https://github.com/qmk/qmk_cli/blob/master/qmk_cli/script_qmk.py#L6
> MILC: Use dashes instead of underscores for subcommands

- quantum/process_keycode/process_tap_dance.h
Tap Dance name is wrong.   Docs and function don't actually match.  
This corrects the name in the code to match what the documentation lists, and to be more consistent with the naming.
> Fix Tap Dance name for consistency and to match docs

- keyboards/primekb/prime_e/keymaps/jetpacktuxedo/keymap.c
Some formatting changes in `layer_state_set_user`, as well as switching the way that I am detecting layers to the (much more readable) `layer_state_cmp`. Also added example code to blink the indicator LED when capslock is on.
> Fix some formatting, add blink on lock example

- keyboards/maartenwut/wonderland/keymaps/rys/keymap.c
Align the two layers in my Wonderland layout to make it easier to see what the lower layer maps to. 
Align the two layers so I can see what the heck is going on, remap one key I make mistakes on all the time, and also remove the spurious `\` line enders I had in from when I forked the layout originally. That was caught in review of my original PR but kindly merged anyway.
> Align top and bottom layers to make it easier to map between them

- docs/hand_wire.md
Some of the links were not playing nice on docs.qmk.fm, I think this fixes it.
* Some internal links did not work on the docs.qmk.fm site
> Fixed internal links

- docs/feature_split_keyboard.md
Small update to the Split keyboard feature documentation. The pull-ups not being present has shown up a few times in the help channel of the discord, and this would provide a reference for the issue.
> Update split i2c docs for example of when pull-ups are required

- quantum/keymap_extras/sendstring_belgian.h
- quantum/keymap_extras/sendstring_bepo.h
- quantum/keymap_extras/sendstring_colemak.h
- quantum/keymap_extras/sendstring_dvorak.h
- quantum/keymap_extras/sendstring_french.h
- quantum/keymap_extras/sendstring_german.h
- quantum/keymap_extras/sendstring_jis.h
- quantum/keymap_extras/sendstring_norman.h
- quantum/keymap_extras/sendstring_spanish.h
- quantum/keymap_extras/sendstring_uk.h
- quantum/keymap_extras/sendstring_workman.h
Setting `clang-format off` and un-clang-formatting the `sendstring_*.h` files to make them align again.
*
> Fix formatting for sendstring LUTs

- keyboards/cannonkeys/an_c/an_c.h
- 1st mod after space bar was wrong position
The key configured for Tsangan was a dead key that was switch to the left of the correct position for this layout.
*
> Fix matrix for Tsangan

- drivers/avr/ws2812.c
- drivers/avr/ws2812.h
- quantum/rgb_matrix_drivers.c
When producing a ARM ws2812 driver (#7173), it has been noted that the rgb matrix specific code ends up duplicated. This worsens when we pursue adding pwm, spi, and attiny85 based i2c implementations to core. 
As the required shim is quite small, Ive chosen to add it to `rgb_matrix_drivers.c`, quick checks show no overall impact to compiled firmware.
> Reduce duplication for ARM/AVR ws2812 RGB Matrix driver

- keyboards/lily58/config.h
Currently the Lily58 keyboard doesn't build with `LINK_TIME_OPTIMIZATON_ENABLE = yes` due to multiple definition of a couple macros. This PR fixes that.
Before this PR,
$ LINK_TIME_OPTIMIZATION_ENABLE=yes make lily58:default
fails with this error:
Compiling: keyboards/lily58/i2c.c                                                                  In file included from 
<command-line>:0:0:
./keyboards/lily58/config.h:27:0: error: "NO_ACTION_MACRO" redefined [-Werror]
#define NO_ACTION_MACRO
^
<command-line>:0:0: note: this is the location of the previous definition
In file included from <command-line>:0:0:
./keyboards/lily58/config.h:28:0: error: "NO_ACTION_FUNCTION" redefined [-Werror]
#define NO_ACTION_FUNCTION
^
<command-line>:0:0: note: this is the location of the previous definition …
> Fix Lily58 build with link-time optimization

- docs/faq_keymap.md
- docs/keycodes.md
- docs/keycodes_basic.md
KC_MNXT and KC_MPRV work fine on MacOS, so this note is obsolete.
> Remove obsolete note about media keys in MacOS

- docs/getting_started_vagrant.md
Fixes a typo in the `vagrant destroy` line.
> Fix typo in getting_started_vagrant.md

- docs/coding_conventions_python.md
The Python coding conventions docs have the `__names__` ban part accidentally seen as a bold directive by Markdown. I escaped it.
> Fix dunder names being accidentally bolded

- keyboards/kbdfans/kbd75/config.h
Set "RGBLIGHT_SLEEP" as default value (RGB lighting will be switched off when the host goes to sleep)
> KBDfans/KBD75: Set "RGBLIGHT_SLEEP" as default value

- keyboards/handwired/sticc14/info.json
Completes the `info.json` data, which was previously blank.
Tagging @erkhal (keyboard maintainer).
http://api.qmk.fm/v1/keyboards/error_log:
```json
{
"message": "Error: Could not parse qmk_firmware/keyboards/handwired/sticc14/info.json as JSON: Expecting value: line 1 column 1 (char 0)",
},
```
> Complete info.json for Sticc14 handwired

- drivers/arm/i2c_master.h
It was beleaved that this setting result in a 400Khz I2C bus.
This was incorrect, actual frequency measure with a logic analyzer was around 150Khz.
This is derived from the excel sheet linked in the .h file.
Also confirmed with the ST IDE.
*
> Correct ARM STM32 I2C frequency.

- docs/proton_c_conversion.md
- quantum/stm32/proton_c.mk
Requires #6709.
As an attempt at a "works everywhere" CTPC upgrade, in the short term ARM backlight can use the task driven software PWM.
* Add hardware PWM auto configuration
> Use task driven PWM for CTPC until ARM can provide automatic configuration

- docs/feature_oled_driver.md
- drivers/oled/oled_driver.c
- drivers/oled/oled_driver.h
The current way to write images to OLED displays is by making use of the font functionality. This has several limitations:
- The way to serialize images into the font format isn't obvious;
- The font format limits the image size to a maximum of 128x32, while 128x64 OLED displays are too supported by QMK.
This pull request, code written by @XScorpion2, intends to introduce an easier way to write custom images to OLED displays within QMK.
> Added oled_write_raw and oled_write_raw_P functions to the OLED driver

- keyboards/v60_type_r/config.h
- keyboards/v60_type_r/rules.mk
- keyboards/v60_type_r/v60_type_r.c
- keyboards/v60_type_r/v60_type_r.h
```console
Making v60_type_r with keymap default                                                                  [ERRORS]
quantum/backlight/backlight_avr.c:116:25: note: #pragma message: Using hardware timer 1 with software PWM
^
| 
| .build/obj_v60_type_r_default/quantum/rgblight.o: In function `rgblight_effect_alternating':
| /qmk_firmware/quantum/rgblight.c:709: undefined reference to `rgblight_set'
| .build/obj_v60_type_r_default/quantum/rgblight.o: In function `rgblight_effect_christmas':
| /qmk_firmware/quantum/rgblight.c:709: undefined reference to `rgblight_set'
| .build/obj_v60_type_r_default/quantum/rgblight.o: In function `rgblight_effect_knight':
| /qmk_firmware/quantum/rgblight.c:709: undefined reference to `rgblight_set'
| .build/obj_v60_type_r_default/quantum/rgblight.o: …
```
> Fix v60_type_r compile failures

- docs/config_options.md
- tmk_core/common.mk
This adds a shorter option for adding LTO, because it's awesome typing out `LINK_TIME_OPTIMIZATION_ENABLE=yes`....
Now, we can use `LTO_ENABLE=yes`
* Drashna's sanity
> Add short form LTO_ENABLE

- tmk_core/protocol/usb_descriptor.c
I think there was a typo introduced when `lib/lufa` was made a submodule and `usb_descriptor.c` was adapted to latest. This change makes my Planck EZ work as a MIDI device again.
- [x ] Bugfix
#7256 
*
> Fixes #7256: USB descriptor to identify correctly as MIDI device.

- keyboards/keebio/quefrency/keymaps/bcat/config.h
Turns out the right half of my Quefrency doesn't work independently with I2C, but it does with serial. I think this is because there are only pull-up resistors for the I2C lines on the left PCB, not the right PCB, and so the lines float when only the right half is connected.
I could add pull ups to the right side too, but meh. There's no PCB footprints for them, and honestly serial seems to work perfectly fine. :)
None.
> Switch my Quefrency (back) to serial so halves work independently

- common_features.mk
- docs/feature_dynamic_macros.md
- docs/keycodes.md
- quantum/dynamic_macro.h
- quantum/process_keycode/process_dynamic_macro.c
- quantum/process_keycode/process_dynamic_macro.h
- quantum/quantum.c
- quantum/quantum.h
- quantum/quantum_keycodes.h
This imports the code from Dynamic Macro into the core code, and handles it, as such.
This deprecates the old method but does not remove it, for legacy support. This way, no existing user files need to be touched.
Additionally, this reorganizes the documentation to better reflect the changes.
Also, it adds user hooks to the feature so users can customize the existing functionality.
Based heavily on and closes #2976
> Convert Dynamic Macro to a Core Feature

- keyboards/maartenwut/wasdat/wasdat.c
With the following code in my keymap to repurpose the Scroll Lock LED as a layer indicator:
```c
bool led_update_user(led_t led_state) {
writePin(B0, !led_state.caps_lock);
return false;
}
layer_state_t layer_state_set_user(layer_state_t state) {
writePin(B1, IS_LAYER_ON(_FN));
return state;
}
```
The LED turns on upon reset. Because the pins are in current sink configuration (VCC -> LED -> pin), output low lights up the LEDs. So we need to explicitly initially set them to output high.
As a side note this also basically fixes the brief flickering on powerup, due to the reliance on the first call to `led_update_kb()` to turn them back off, which obviously has to wait for USB enumeration.
*
> Fix `led_init_ports()` for Wasdat

- keyboards/planck/rev6/config.h
- keyboards/planck/rev6/rules.mk
- keyboards/preonic/rev3/config.h
- keyboards/preonic/rev3/rules.mk
This enables the bitbang WS2812 support for the ARM OLKB keyboards (Planck Rev6, and Preonic Rev3).
Defaulted to "enabled", since size really isn't a consideration, and you won't see if the LEDs are not soldered on.
> [Keyboard] Enable RGB Light on ARM OLKB Keyboards

- tmk_core/common/chibios/suspend.c
I know ARM boards don't have a general WS2812 implementation yet, but some specific boards do, like the CannonKeys ARM boards. For these boards, it'd be nice if `RGBLIGHT_SLEEP` just worked. I copied over the implementation from `tmk_core/common/avr/suspend.c` and it seems to work fine with ChibiOS.
I verified on my Instant60 that with `RGBLIGHT_SLEEP` the RGB now turns off when the host PC goes to sleep and turns back on (including animations) when the host PC wakes. Normal keyboard stuff seems fine after wake as well.
**Open question:** Should I guard this code behind `NO_SUSPEND_POWER_DOWN` like the equivalent AVR code? It's honestly not clear to me what that define is for, exactly....
* ARM boards keeping their RGB underglow on at all times, even if `RGBLIGHT_SLEEP` was defined.
> Support RGBLIGHT_SLEEP when ChibiOS boards suspend

- tmk_core/common/action_layer.c
- tmk_core/common/action_layer.h
- tmk_core/common/eeconfig.c
When on a mission to cut down firmware size, the following settings were added
```
#define LAYER_STATE_8BIT
#define NO_ACTION_LAYER
```
Which produces the following error:
```
tmk_core/common/action_layer.h:26:38: error: implicit declaration of function ‘biton8’ [-Werror=implicit-function-declaration]
```
This PR fixes a few scenarios where a u32 is still being used.
> Fix LAYER_STATE_8BIT compile issues

- tmk_core/protocol/chibios/usb_main.c
When disabling basically all the features on `handwired/onekey/proton_c:default`, including mouse and nkro, the following error is produced:
```console
Compiling: tmk_core/protocol/chibios/usb_main.c                                                    In file included from ./lib/chibios/os/hal/include/hal.h:141:0,
from tmk_core/protocol/chibios/usb_main.c:19:
tmk_core/protocol/chibios/usb_main.c: In function 'usb_request_hook_cb':
tmk_core/protocol/chibios/usb_main.c:451:60: error: 'set_report_buf' undeclared (first use in this function); did you mean 'has_report_id'?
usbSetupTransfer(usbp, set_report_buf, sizeof(set_report_buf), set_led_transfer_cb);
^
./lib/chibios/os/hal/include/hal_usb.h:477:23: note: in definition of macro 'usbSetupTransfer'
(usbp)->ep0next  = (buf); …
```
> Fix ChibiOS compile error when mouse and nkro disabled

- quantum/rgblight.c
Reports have started slowly filtering in about the recent RGB changes on ChibiOS, mostly within the context of the Planck v6.
I have reproduced locally, with the default keymap. However if i run hid_listen, then the board works.
Disabling console and the board responds fine. A guess at the core issue, is its like it tries to log, and blocks waiting for someone host side to read. When you disable console, those log functions are compiled out.
Tracking down the logging theme, resulting in chopping out code till the board worked again, resulting in the following line being the culprit:
```diff
diff --git a/quantum/rgblight.c b/quantum/rgblight.c
index a4cbe513e..ea54a349f 100644
--- a/quantum/rgblight.c
+++ b/quantum/rgblight.c
@@ -189,7 +189,7 @@ void rgblight_init(void) {
return;
}
- …
```
> Remove force of debug on within rgblight - causes lockups waiting for hid_listen

- quantum/template/avr/config.h
- quantum/template/ps2avrgb/config.h
Set config templates to disable `action_get_macros` and `fn_actions` by default for [#3947](https://github.com/qmk/qmk_firmware/issues/3947)
* #3947 
- not sure, it may be worth mentioning the default under 'features that can be disabled'
> disable deprecated actions

- lib/python/qmk/cli/doctor.py
On older versions of `dfu-programmer` it exits with a returncode of 1 when run with `--help`. Newer versions exit with a returncode of 0. For the time being our test infrastructure is stuck on the older version, so for the purpose of this check we treat both 0 and 1 as working.
*
> QMK Doctor: When checking program returncodes treat both 0 and 1 as installed

- build_json.mk
- lib/python/qmk/cli/json/keymap.py
When compiling `keymap.json` we used to generate the `keymap.c` in a kludgy way. This makes the `keymap.c` a proper make target, so it can be generated in a straightforward way.
*
> Make generating keymap.c from JSON more reliable

- keyboards/converter/xt_usb/config.h
- keyboards/converter/xt_usb/matrix.c
The XT converter didn't have `#include "config_common.h"` which is necessary for defining `RGB_DI_PIN`, among other things. Since the custom matrix already defines `E0` as one of the states (even though this is not an actual pin on the 32U4), they had to be prefixed to avoid this collision.
Thanks to @acid2000 for reporting.
* Fixes #7324
> XT converter: add config_common.h include and fix E0 collision

- shell.nix
I tried to use `shell.nix`, but I ran into a build issue. To fix it, I found a commit in `nixpkgs` from around the time the file was made, and modified `shell.nix` to always use the version of `nixpkgs` at that commit. That way even as `nixpkgs` changes, this `shell.nix` file should always work.
I also tweaked the way we get around the fact that `dfu-programmer` and `teensy-loader-cli` are erroneously marked as unsupported on darwin, so that it only affects those two packages. I'm not sure what the status of theses packages is for the current version of `nixpkgs`, but maybe someone should submit a PR to nixpkgs to fix this upstream?
> Fix shell.nix by pinning nixpkgs

- quantum/rgb_matrix_animations/rainbow_pinwheels_anim.h
The internal naming was `PINWHEELS` instead of `RAINBOW_PINWHEELS` causing a mismatch between animation definition and the function.
> Fix the RGB_MATRIX_RAINBOW_PINWHEELS animation

- docs/feature_haptic_feedback.md
- drivers/haptic/solenoid.h
* Removes `SOLENOID_ACTIVE` since this is stored in eeprom. No need for it
* Remove default pin define to prevent unexpected/unwanted behavior. Instead, explicitly require a define for it. 
* Actually add solenoid settings to documentation. 
* if solenoid is enabled, but pin not defined, can cause keys to not work.
> Improvements to Solenoid feature 

- keyboards/crkbd/rev1/matrix.c
- keyboards/crkbd/rev1/split_util.c
While there are plans to move to split_common, that has complications as that currently has behaviour changes.
This PR adds `SPLIT_USB_DETECT` support for those users having issues with Elite-C V3s.
Tagging @foostan as maintainer.
> Port SPLIT_USB_DETECT to crkbd

- lib/python/milc.py
* Remove the shadow argparser
* Make it easier to reason about arguments and how they're translated into the config tree
* Populate self.config during init to support setting user.qmk_home for the global CLI
* Remove the short argument -c so that we can unambiguously determine the config file location without doing full argument processing
* Remove the --save-config option as it's a little confusing anyway
* Use Pathlib for path manipulation
*
> Improve a number of things about how MILC operates

- quantum/template/ps2avrgb/config.h
Small fix for a small mistake.
This fixes the behaviour of `util/new_keyboard.sh` and https://github.com/qmk/qmk_firmware/pull/6886 when a ps2avrgb keyboard is created.
*
> Fix ps2avrgb template

- layouts/community/ergodox/qwerty_code_friendly/keymap.c
- layouts/community/ergodox/qwerty_code_friendly/readme.md
This is an update to a keymap I wrote/maintain.
- Move space to thumb cluster.
- Make L1 & L2 symmetrical.
- Hold L1 & L2 to activate L3.
- Correct layer names.
> Update to qwerty_code_friendly

- docs/feature_advanced_keycodes.md
docs/feature_advanced_keycodes.md has:
```
[Tap Dance](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_tap_dance.md#example-5-using-tap-dance-for-advanced-mod-tap-and-layer-tap-keys)
```
change to:
```
[Tap Dance](feature_tap_dance.md#example-5-using-tap-dance-for-advanced-mod-tap-and-layer-tap-keys)
```
> fix feature_advanced_keycodes.md's link

- .github/stale.yml
This adds the configuration for probot-stale, so that PRs and Issues can be automatically pruned without intervention by collaborators.
This marks PRs with `awaiting changes` label after 45 days, and then closes any PR with "Awaiting changes" after 30 days.  Unless they have `awaiting review`, `breaking_changes`, `in progress` or `on hold` labels.
This marks issues as `solved` after 90 days, and then closes them 30 days afterwards. Unless they have `bug`, `discussion`, `to do`, `in progress` or `on hold` labels.
This does require the installation of the ProBot Stale bot.
https://github.com/probot/stale
~~Alternatively, there is: 
https://github.com/actions/stale~~
> Add auto-handling of stale PRs/Issues

- keyboards/exclusive/e65/e65.c
Caps lock LED indicator is reverse.  Light comes on if Caps Lock is not on and turns off when it is on.
Fixed the lines to reverse the Caps Lock LED indicator to turn on when Caps Lock is pressed.
Swapped writePinLow/writePinHigh
* Fixed Caps Lock LED
> Update e65.c to fix Caps Lock indicator

- Makefile
Currently if you run something like `make all:zvecr` it produces the following output...
```console
$ make all:zvecr
QMK Firmware 0.7.79
Making 1upkeyboards/1up60hse with keymap default and target zvecr                              [ERRORS]
make[1]: *** No rule to make target 'zvecr'. Stop.
Making 1upkeyboards/1up60hse with keymap default_60_ansi and target zvecr                      [ERRORS]
make[1]: *** No rule to make target 'zvecr'. Stop.
Making 1upkeyboards/1up60hse with keymap mechmerlin-ansi and target zvecr                      [ERRORS]
make[1]: *** No rule to make target 'zvecr'. Stop.
Making 1upkeyboards/1up60hse with keymap stanrc85-ansi and target zvecr                        [ERRORS]
make[1]: *** No rule to make target 'zvecr'. Stop.
Making 1upkeyboards/1up60hse with keymap …
```
> Allow 'make all:<user>' to not build EVERYTHING

- users/manna-harbour_miryoku/manna-harbour_miryoku.c
- users/manna-harbour_miryoku/miryoku.org
> [Keymap][miryoku] Add ALGR and kle image, expand and correct documentation

- docs/newbs_best_practices.md
`docs/newbs_best_practices.md` has broken link:
```diff
-2. You've [set up your build environment](newbs_getting_started.md?id=environment-setup).
+2. You've [set up your build environment](newbs_getting_started.md#set-up-your-environment).
```
> fix broken link in docs/newbs_best_practices.md

- keyboards/clueboard/2x1800/2019/2019.h
- keyboards/clueboard/2x1800/2019/keymaps/default_2u_ansi/config.h
- keyboards/clueboard/2x1800/2019/keymaps/default_2u_ansi/keymap.c
- keyboards/clueboard/2x1800/2019/keymaps/default_2u_ansi/readme.md
- keyboards/clueboard/2x1800/2019/keymaps/default_2u_iso/config.h
- keyboards/clueboard/2x1800/2019/keymaps/default_2u_iso/keymap.c
- keyboards/clueboard/2x1800/2019/keymaps/default_2u_iso/readme.md
Add default ANSI and ISO layouts for 2u spacebar option. @skullydazed may want to review.
> Add default layouts for 2u spacebar to Clueboard 2x1800 2019

- lib/python/milc.py
Subcommands with 'hidden=True' will not show up in the help output, but
will work as any other subcommands.
* https://github.com/qmk/qmk_cli/blob/master/qmk_cli/script_qmk.py#L7
> MILC: Add support for hidden subcommands

- util/msys2_install.sh
* Update AVR GCC and ARM GCC to 8.3.x (and don't prompt unless it exists)
* Install packages via pacman without prompting user
* Remove prompts for installing stuff unless it already exists
This doesn't touch the win_shared_install.sh  stuff, since that prompts only if utils have already been installed already, and for drivers (since that's long and requires a UAC prompt .... lets not change that).
> Improve and streamline MSYS2 installation

- util/travis_compiled_push.sh
Issues:
1. grep needs `-z` to correctly handle the null instead of newlines from previous `git diff -z` output
2. clang-format needs `-i` otherwise it prints all the newly formatted code to stdout
3. changed files can be outside of the original format pass
* this leads to clang-format targeting makefiles and markdown
> Fix clang-format logic within CI

- docs/custom_quantum_functions.md
- keyboards/maartenwut/wonderland/keymaps/default/keymap.c
- keyboards/maartenwut/wonderland/wonderland.c
- layouts/community/60_hhkb/yanfali/keymap.c
- needed for custom LED functions in keymap.c
- adds an example in code on how to override the LEDs and use them as layer indicators
Allow end-user to override functions again in keymap.c
If you want to use the LEDs for custom stuff, it's good to allow users to override these functions defined in wonderland.c
*
> Allow overriding of all functions in wonderland.c

- docs/custom_quantum_functions.md
Provide a more succinct and less verbose example for a custom LED function.
*
> Update led_update_kb example

- tmk_core/avr.mk
- tmk_core/rules.mk
In cygwin, calculation of BOOTLOADER_SIZE fails because of CR character passed-out by avr-gcc.
Here, avr-gcc originates to the binary package distributed by Microchip.
I'm using cygwin as my default working terminal and fixing this little issue clears the way.
> Remove CR when computing BOOTLOADER_SIZE.

- docs/_summary.md
- docs/contributing.md
- docs/index.html
- docs/translating.md
- readme.md
Without this `fallbackLanguages` array, pages that don't exist in the selected language will 404. All links must also be prefixed with the language code, or it will revert back to English.
Additionally, pointed users towards using the `qmk docs` CLI command, and used fenced code blocks in translating.md, for syntax highlighting.
Also I think the country flags should be the actual emoji characters, instead of eg. `:ja:`, as some of them appear to be unsupported currently.
*
> Set up language fallback for docs, and update translation guidelines

- drivers/issi/is31fl3733.c
- drivers/issi/is31fl3733.h
Function IS31FL3733_update_led_control_registers was never setting update register to false. As a result the led on/off page was being written every transaction even when it was not modified. This is ineficient and causes lots of bandwidth use.
-> Fix the IS31FL3733_update_led_control_registers.
-> After testing it was evident that failed I2C transactions could corrupt the Led on/off register.
-> Update IS31FL3733_write_pwm_buffer and IS31FL3733_write_register functions to return 0 upon succesful tranmission and 1 if any of the transmitions within the function fail.
-> Modify IS31FL3733_update_pwm_buffers function so if any of the IS31FL3733_write_pwm_buffer transuction fails, the g_led_control_registers_update_required register is set to true forcing a rewrite of the led on/off register …
> IS31FL3733 Dirty page fix

- quantum/mcu_selection.mk
This script doesn't exist as of #7456.
*
> Remove PROGRAM_CMD in mcu_selection.mk for 32A

- keyboards/gh60/satan/keymaps/smt/keymap.c
User keymap change:
- Swap RGUI and FN keys for comfort
- Adjust layout to accommodate HHKB-style arrow cluster on the right-hand side
*
> Adjust Fn key and right arrow cluster of GH60/Satan keymap

- docs/faq_build.md
- docs/flashing_bootloadhid.md
- util/activate_msys2.sh
- util/activate_wsl.sh
- util/linux_install.sh
- util/macos_install.sh
- util/win_shared_install.sh
Many previous PRs have started to flesh out the bootloadHID integration.
This PR installs on a bunch of platforms to make `:flash` work as much as possible.
- kinda a messy install for *all* supported distros
- errors out "gracefully" if dependencies are not available
> Install bootloadHid as part of qmk_install

- keyboards/crkbd/rev1/split_util.c
Currently `is_keyboard_master` has a default implementation of `return true`, where keycodes are processed on the slave half by
https://github.com/qmk/qmk_firmware/blob/46d0fe44f357f0435d3335cbe5e361324d4236f6/tmk_core/common/keyboard.c#L288-L316
Porting over usb detection added an implementation to this function, which with its effective false on the slave half, stops keycode processing.
For now, this behaviour will need to fixed, as its the only method that currently works across rgb light and matrix.
Symptoms also found within #7385.
* RGB matrix issue raised on Discord by @tominabox1 
* fixes 7492
> Fix processing of RGB keycodes on crkbd slave half

- quantum/keymap_common.c
- quantum/quantum.c
This PR attempts to save some bytes (and potentially bringing #7484 back under size). Mimicking travis by running `./util/docker_build.sh helix/pico/back:default`:
before
`* The firmware size is approaching the maximum - 28320/28672 (98%, 352 bytes free)`
after
`* The firmware size is approaching the maximum - 28120/28672 (98%, 552 bytes free)`
> Compile out some keycode processing when features are disabled

- docs/index.html
- docs/translating.md
Without this, clicking on the sidebar heading while browsing in another language takes you back to the English landing page.
*
> Add yet another dictionary for the QMK Firmware docs sidebar heading

- util/docker_build.sh
Docker build output files were owned by root. This PR modifies the docker invocation to specify the user/group of the host user such that the output files are owned by the caller.
> Fix output file permissions when using docker build.

- lib/python/qmk/cli/docs.py
I tried to be clever here, but `directory` isn't a thing below 3.7...
*
> Use os.chdir for `qmk docs` instead of a custom HTTP request handler

- keyboards/crkbd/keymaps/manna-harbour_miryoku/config.h
- keyboards/crkbd/keymaps/manna-harbour_miryoku/rules.mk
- users/manna-harbour_miryoku/manna-harbour_miryoku.c
- users/manna-harbour_miryoku/miryoku.org
> [keymap] miryoku: Add RGB keycodes, enable RGB_MATRIX on crkbd

- keyboards/handwired/jotanck/jotanck.c
The C file for this keyboard was calling `keyboard_pre_init_user`.  Which is wrong.
This fixes that behavior. 
Discovered when running `make all:drashna`
> [Keyboard] Fix calls in handwired/jotanck

- keyboards/lets_split/sockets/config.h
- keyboards/lets_split/sockets/rules.mk
This removes the `NO_ACTION_*` and `EXTRAFLAGS+=-flto` in favor of just `LTO_ENABLE = yes`, which accomplishes both.
Discovered when running `make all:drashna`
> [Keyboard] Update Lets Split Sockets to use LTO_ENABLE

- util/linux_install.sh
A minor misconfiguration in the install when using Linux Ubuntu.
This consisted of 2 issues:
First being sh not having [
Second being that pip is independent from python3 on Debian-based systems.
*
> Fix install for Linux Ubuntu

- keyboards/ai03/orbit/split_util.c
- keyboards/ai03/orbit/transport.c
- quantum/split_common/post_config.h
- quantum/split_common/split_util.c
- quantum/split_common/transport.c
`#define EH` and its checks were a temporary solution in the early days of `split_common`. Its use in lets_split_eh was factored out in https://github.com/qmk/qmk_firmware/pull/6411, so the checks are no longer needed.
*
> Remove check for EH define

- drivers/gpio/pca9555.c
- drivers/gpio/pca9555.h
- keyboards/xd84/matrix.c
Trying to get to a point where ` #define USB_POLLING_INTERVAL_MS 1` is actually worthwhile, where scanrate needs to be > 1000.
before:
`matrix scan frequency: 351`
after:
`matrix scan frequency: 657`
Potentially with running the i2c devices faster than we should.... with `#define F_SCL 800000UL`:
`matrix scan frequency: 1072`
> Increase matrix scanning speed on xd84

- common_features.mk
- quantum/process_keycode/process_magic.c
- quantum/process_keycode/process_magic.h
- quantum/quantum.c
- quantum/quantum.h
This PR relocates a block of keycode handling to its own file for readability. I've ditched a few redundant checks to save a few bytes in firmware size, the net saving is about 10 bytes, so basically the same as before.
The main functional change, is the removal of:
```c
if (!eeconfig_is_enabled()) {
eeconfig_init();
}
```
Which seems to be handled within `magic.c` and `bootmagic.c` on keyboard startup, so should be initialised by first magic keypress.
> Relocate magic keycode processing

- quantum/quantum.c
`BL_BRTG` keycode handling was hidden within the rgb keycodes, and compiled out if you did not have rgblight or rgbmatrix enabled. Moved block to the other single state keycode handling,
> Fix breathing toggle when rgb is disabled

- keyboards/keebio/ergodicity/ergodicity.h
Fixes missing KC_NO in last line of macro of the Ergodicity layout macro.
* 
> Fix missing item in Ergodicity macro

- keyboards/helix/rev2/matrix.c
- keyboards/helix/rev2/split_util.c
This PR adds SPLIT_USB_DETECT support for those users having issues with Elite-C V3s.
Copied from PR https://github.com/qmk/qmk_firmware/pull/7195
> Port SPLIT_USB_DETECT to helix/rev2

- docs/feature_advanced_keycodes.md
Current syntax in the document is not correct, since `set_oneshot_layer()` has two parameters, and doesn't do what we want.  Based on experimentation, `clear_oneshot_layer_state()` seems to be the correct function to call on key release.
*
> fix instructions for oneshot layer handling on key release

- keyboards/helix/pico/rules.mk
- keyboards/helix/rev2/rules.mk
helix-serial.c is sensitive to execution timing and will not work as expected when compiled with the -flto option. As a result, if Helix is compiled with LTO_ENABLE = yes, the key input on the slave side will not be performed correctly.
In particular, `helix:xulkal` is always set to LTO_ENABLE = yes, so key input on the slave side is not possible.
To solve this problem, #7089 suggests a general way to specify the `-fno-lto` option, but it still doesn't merge after a month and a half.
This PR adds a temporary workaround to helix/rev2 and helix/pico until #7089 is merged.
What happens with this PR:
* When LTO_ENABLE = no. 
All helix/rev2 and helix/pico keymap compilation results will not change. Therefore, there is no adverse effect.
* When LTO_ENABLE = yes. 
This PR ensures that all …
> Added workaround for serial.c issue when LTO_ENABLE=yes for the Helix.

- keyboards/cannonkeys/instant60/rules.mk
Add bootmagic lite to instant60 to make resetting eeprom easier
User was not able to reset their eeprom easily. Enable bootmagic lite to facilitate that.
@awkannan this seems to be a harmless and helpful change.
*
> instant60: Enable bootmagic lite to make eeprom reset easier

- build_json.mk
Without this change, you have to remove the generated C keymap if you want your updated JSON keymap to take effect. I'd consider that a bug, since the whole point of `make` is to do that work for you.
I tested this on my personal lily58 keymap and it worked---the keymap.c file was regenerated when my keymap.json file changed, and it left keymap.c alone when keymap.json wasn't changed. I also watched `make all` run for a few minutes and didn't see any errors that would have been caused by this change.
(I'm not sure what kind of change this is. Sorry if I filled this out wrong.)
> Automatically rebuild C keymap when JSON keymap is changed

- lib/python/qmk/cli/compile.py
- lib/python/qmk/cli/flash.py
- lib/python/qmk/commands.py
Compiling JSON files by passing them into `qmk compile` was broken. This fixes it.
> Fix compiling json files

- keyboards/hineybush/h87a/keymaps/default/keymap.c
Changes where the MO(1) layer switching key is to allow FN-layer switching if a user builds a 7u-based, blocked WKL keyboard with the default keymap's 6.25u-based bottom row.
Previous base keymap would prevent access to the FN layer as the default MO(1) key is the blocked one on this physical layout.
* Previous base keymap would prevent access to the FN layer as the default MO(1) key is the blocked one on this physical layout.
> update default h87a keymap for fn functionality

- keyboards/gray_studio/space65/keymaps/default/keymap.c
- keyboards/gray_studio/space65/space65.h
When building firmware for the GrayStudio Space65 keyboard using the `LAYOUT_65_ansi_blocker` layout, in both the online configurator, as well as building the firmware locally, the key in the backspace position does not work.
Swap the location of the blank layout position.
> Fix 2U backspace key in ansi_blocker layout for GrayStudio Space65 keyboard

- keyboards/gray_studio/think65/hotswap/keymaps/default/keymap.c
- keyboards/gray_studio/think65/solder/keymaps/default/keymap.c
This commit cleans up the default think6.5 keymaps and also adds GESC along with F-row keys to the keymaps
*edited for context – noroadsleft*
Default hotswap keymaps do not have function keys nor access to tilde/backtick
* N/A
> Think6.5 Default Keymap Cleanup

- quantum/process_keycode/process_magic.c
- tmk_core/common/keyboard.c
Fixed Issues:
1. Fix force nkro overwriting on matrix scan
* Introduced with #7512
* `eeconfig_read_keymap()` is called on every keycode process, the previous nkro value in memory is lost.
* could be fixed with just number 2 below
* reverted code closer to what it was before #7512 to avoid any other behaviour changes from uncaptured logic
2. Fix first magic keycode overwriting force nkro
* existing issue
* when NKRO_FORCE, `tmk_core/common/keyboard.c` sets nkro value, which when the first magic keycode triggers `eeconfig_read_keymap()`, the previous nkro value in memory is lost.
* changed to persist nkro config
* this should be safe as eeprom will only write if value is different?
> Fix FORCE_NKRO handling

- keyboards/gami_studio/lex60/config.h
- keyboards/gami_studio/lex60/keymaps/default/keymap.c
- keyboards/gami_studio/lex60/lex60.c
- keyboards/gami_studio/lex60/lex60.h
- keyboards/gami_studio/lex60/readme.md
- keyboards/gami_studio/lex60/rules.mk
Add AustinPCB support
This PR adds support for the Lex60 PCB revision Alpha.
This firmware was tested on Alpha revision PCBs.
> [Keyboard] Added Lex60 keyboard

- drivers/arm/i2c_master.c
- drivers/arm/i2c_master.h
stm32f4 uses I2Cv1 and GPIOv2 drivers, so the current definitions on i2c_master.h should be modified.
* Fixes #7524
> fixed I2C driver support for stm32f4

- keyboards/handwired/aek64/config.h
- keyboards/handwired/aek64/keymaps/4sstylz/keycodes.h
- keyboards/handwired/aek64/keymaps/4sstylz/keymap.c
- keyboards/handwired/aek64/rules.mk
* Rework of my personal keymap for the AEK64 handwired keyboard.
* Adding backlight effects on the keyboard.
> Adding Backlight on the handwired AEK64 keyboard

- tmk_core/protocol/chibios/usb_main.c
As per #4783 USBv1 devices have `ep_buffers` and OTGv1 have `in_multiplier`.
This PR aligns usb endpoint config as per rest of file, using explicit order instead of struct member name.
* Fixes #4783
> Fix ChibiOS USB config for chips which support OTGv1

- tmk_core/protocol/serial_soft.c
SERIAL_SOFT_DEBUG can be defined in the `config.h`
Backported from tmk/tmk_keyboard@c74eee6327c5995456ba004d70b9663cf485d9f8
> remove SERIAL_SOFT_DEBUG macro

- quantum/keymap_common.c
tmk backport from tmk/tmk_keyboard@325a99acd9c81f60519b6e594b2bf5d1e478ac56
> core: Fix variable init in keymap_common.c

- keyboards/hineybush/h88/keymaps/default/keymap.c
Updates h88 default keymap to allow WKL bottom row builds to access the MO(1) keycode
*
> update default h88 keymap

- keyboards/maartenwut/plain60/keymaps/default/keymap.c
- keyboards/maartenwut/plain60/rules.mk
Discord user typischt requested access to bootmagic and a reset coed on default keymap.
- enable bootmagic lite to make resetting easier
- add a RESET keycode to default keymap on a layer
- override KC_UP and KC_APP to be MO(1)
- remove obsolete comments about sizes from rules.mk
This seem ok @Maartenwut ?
*
> [keyboard] Plain60 cleanups

- keyboards/cannonkeys/satisfaction75/keymaps/boy_314/config.h
- keyboards/cannonkeys/satisfaction75/keymaps/boy_314/keymap.c
- keyboards/cannonkeys/satisfaction75/keymaps/boy_314/readme.md
- keyboards/cannonkeys/satisfaction75/keymaps/boy_314/rules.mk
Added my custom satisfaction75 layout. Includes a default QWERTY keymap along with missing TKL keys on a second layer. also changes the encoder resolution from 4 (default) to 2 so that turning the knob once activates the knob instead of twice. See readme for some more details.
* N/A
> [keymap] boy_314's satisfaction75 layout

- tmk_core/common/keyboard.c
Backport of tmk/tmk_keyboard@ad6059adc7039a54d1db75da783068654906a679
> [Core] Optimize matrix processing

- quantum/split_common/split_util.c
When using serial transport, the slave side still runs the ISR and sends the previous data, but from an end user perspective the slave doesnt respond.
Similar to the elite-c v3/teensy2/vit_inc issue, the slave side gets stuck in the sleep loop. However on ARM, its less consistent and happens at random.
A bit of a "when you only have a hammer everything looks like a nail." solution, but for now I just want things to work.....and can try to tackle *better* once things are working.
> ARM split - Disable USB on slave half to resolve random 'lockup'

- common_features.mk
- docs/feature_backlight.md
- quantum/stm32/proton_c.mk
Kind of an oversight on my part, but `BACKLIGHT_ENABLE = software` or `BACKLIGHT_ENABLE = custom` makes life a little difficult. Having a clear option for what method to use, and then a master on/off, provides users with just a toggle and removes overhead of them finding context on stuff like pwm/timer/software emulation for a particular keyboard. Another example with issues is, userspace where a board has backlight off by default to save space.
> Convert backlight to follow driver rules pattern

- keyboards/7skb/rev1/config.h
- keyboards/fortitude60/rev1/config.h
- keyboards/keebio/iris/rev1/config.h
- keyboards/keebio/iris/rev1_led/config.h
- keyboards/keebio/iris/rev2/config.h
- keyboards/keebio/iris/rev3/config.h
- keyboards/keebio/levinson/rev1/config.h
- keyboards/keebio/levinson/rev2/config.h
- keyboards/keebio/quefrency/rev1/config.h
- keyboards/keebio/rorschach/rev1/config.h
- keyboards/naked48/rev1/config.h
Causes issues when building with CTPC:
```console
zvecr@zvecr-XPS-L322X:~/Desktop/qmk_firmware$ ./util/docker_build.sh keebio/levinson/rev2:default:flash
...
Compiling: tmk_core/protocol/chibios/main.c                                                         [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: tmk_core/protocol/chibios/usb_driver.c                                                   [OK]
Compiling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt1.c                               In file included from <command-line>:
./keyboards/keebio/levinson/rev2/config.h:22:10: error: #include expects "FILENAME" or <FILENAME>
#include QMK_KEYBOARD_CONFIG_H
^~~~~~~~~~~~~~~~~~~~~
[ERRORS]
| 
| 
| …
```
> Remove QMK_KEYBOARD_CONFIG_H from boards

- common_features.mk
- keyboards/mxss/rules.mk
- quantum/process_keycode/process_rgb.c
- quantum/process_keycode/process_rgb.h
- quantum/quantum.c
- quantum/quantum.h
- quantum/rgb_matrix.h
This PR relocates a block of keycode handling to its own file for readability and also attempts to save some firmware bytes. Mimicking travis by running ./util/docker_build.sh helix/pico/back:default:
before
` * The firmware size is approaching the maximum - 28482/28672 (99%, 190 bytes free)`
after
` * The firmware size is approaching the maximum - 28158/28672 (98%, 514 bytes free)`
> Relocate RGB keycode processing

- keyboards/atreus62/keymaps/d4mation/keymap.c
- keyboards/atreus62/keymaps/d4mation/readme.md
- keyboards/atreus62/keymaps/d4mation/rules.mk
- users/d4mation/config.h
- users/d4mation/d4mation.c
- users/d4mation/d4mation.h
- users/d4mation/macros.c
- users/d4mation/macros.h
- users/d4mation/rules.mk
- users/d4mation/tap-dance.c
- users/d4mation/tap-dance.h
- users/d4mation/tap-hold.c
- users/d4mation/tap-hold.h
- users/d4mation/zalgo.c
- users/d4mation/zalgo.h
Adds the `d4mation` userspace, as well as my keymap for the Atreus62 keyboard
> Added userspace for d4mation. Included their keymap for the Atreus62

- keyboards/clueboard/60/config.h
- layouts/community/60_ansi_split_bs_rshift/yanfali/keymap.c
Swaps columns 12 and 11 so they are in the correct positions for the matrix
This is a bug fix, this has been broken for quite a while.
*
> clueboard 60 fix col 11 12 mixup

- drivers/arm/i2c_master.c
- drivers/arm/i2c_master.h
- quantum/backlight/backlight_arm.c
- quantum/quantum.h
- tmk_core/common/chibios/chibios_config.h
Given the ChibiOS HAL doesnt have a unified API, we end up in a HAL of HAL's situation where various code areas have to sniff config options and compile in different blocks of code. Unfortunately it doesn't look like there are internal "this board is using gpiov2" defines we can leverage.
Rather than have these defines duplicated, this PR aims to add a central location to manage the mcu logic.
> Add central location for ChibiOS defines

- keyboards/rgbkb/sol/keymaps/default/keymap.c
Adding code that was lost at some point to the Sol Rev2 Encoder keymaps.
*
> Readded lost pgm_read_word code to encoder array lookups

- drivers/arm/i2c_master.c
- drivers/arm/i2c_master.h
- drivers/haptic/DRV2605L.c
This function is listed in the ARM header file, but doesn't actually exist.
> Completely remove i2c_transmit_receive function

- quantum/rgb_matrix.c
Currently, when suspend/sleep is enabled for the rgb matrix, it sets a boolean toggle, which prevents the animation from being updated.  This was fine when the entire animation was done each cycle, but because the animation is sliced up (and has been for a while), it can lead to a state where some of the LEDs are on, but the rest are not, as it's mid animation.  
This forcibly turns off (well, sets to black/blank) all of the LEDs when the keyboard goes to sleep (and only then), so that all the lights are off.
> Turn off RGB Matrix LEDs when keyboard sleeps

- keyboards/handwired/k_numpad17/config.h
- keyboards/handwired/k_numpad17/k_numpad17.c
- keyboards/handwired/k_numpad17/k_numpad17.h
- keyboards/handwired/k_numpad17/keymaps/default/keymap.c
- keyboards/handwired/k_numpad17/keymaps/default/rules.mk
- keyboards/handwired/k_numpad17/keymaps/karlssn/keymap.c
- keyboards/handwired/k_numpad17/keymaps/karlssn/rules.mk
- keyboards/handwired/k_numpad17/readme.md
- keyboards/handwired/k_numpad17/rules.mk
I created a new handwired keyboard and added it under keyboards/handwired/ 
So I recently created a numpad and handwired it on my own but found that qmk didnt have a numpad with 17 keys under the handwired tab. Therefore I created my own based of Tritium Numpad which is a 21 key numpad.
*
> K-Nunmpad17 

- docs/newbs_git_resynchronize_a_branch.md
In first paragraph
`GitHub will tell you that your commit is a number of commits ahead of qmk:master`
change to
`GitHub will tell you that your branch is a number of commits ahead of qmk:master`
Because, GitHub displays as follows.
> Fix minor differences in docs/newbs_git_resynchronize_a_branch.md

- quantum/mcu_selection.mk
As an attempt to resurrect parts of #5669, this PR aims to add defaults for a few of the more popular STM32 chips.
2nd pass will be to refactor boards to use these new defaults where possible
> Add rules.mk defaults for f103,f072,f042

- bootloader.mk
- keyboards/gray_studio/cod67/rules.mk
- keyboards/tada68/rules.mk
Tested with a Pro Micro and the MassStorage bootloader from current submodule LUFA. Mainly interested in the behaviour of the `RESET` keycode as it was reportedly not working (possibly `BOOTLOADER_SIZE` was wrong, since `atmel-dfu` specifies 4kB instead of 6). It seems to work fine.
I purposely did not document this, nor add it to the list in the templates. I will not be QMK-ifying the bootloader in our fork a la QMK-DFU. For anyone stumbling across this wanting to have a mass storage bootloader: I _strongly_ advise against it 😄
*
> Add LUFA mass storage `BOOTLOADER` "support"

- keyboards/ckeys/washington/rules.mk
The cKeys workshop will be using Elite-Cs, not Pro Micros like I originally thought. This changes the bootloader option in rules.mk to `atmel-dfu` so the reset keycode will work.
None
> Change cKeys Washington keyboard to use atmel-dfu bootloader

- keyboards/ergodox_ez/matrix.c
When reconnecting the left half of the Ergodox EZ Glow, the RGB matrix doesn't work until it's re-init'ed.   And since the matrix code already handles this detection, we can use that to re-initialize the driver, so that the per key RGB will work immediately. 
I would prefer to use `rgb_matrix_driver.init();`, but in testing, this would error out, even though, it looks to be externed and included properly. 
However, this does work, and should be fine. 
* Left half Ergdox EZ Glow doesn't re-init driver on reconnect.
> [Keyboard] Ergodox EZ - Re-init ISSI driver on reconnect

- keyboards/foxlab/leaf60/hotswap/keymaps/crd/keymap.c
This is just my usual keymap for the leaf60 hotswap pcb.
Simple keymap with a single HHKB-like function layer and a backlight control layer
*
> [Keymap] crd's personal keymap for hotswap leaf60

- docs/getting_started_build_tools.md
Fix installation commands for macos.
Related to #7744 .
> [Docs] fix installation commands for macos

- common_features.mk
- keyboards/kinesis/alvicstep/rules.mk
- keyboards/kinesis/rules.mk
- keyboards/xd84/custom_matrix_helper.c
- keyboards/xd84/rules.mk
- keyboards/xd96/custom_matrix_helper.c
- keyboards/xd96/rules.mk
- quantum/matrix.c
- quantum/matrix_common.c
- quantum/split_common/matrix.c
- quantum/split_common/matrix.h
- tmk_core/common/matrix.h
It started with the xd84/xd96 ports, where implementing custom matrix felt like reimplementing a bunch of boiler plate over and over again. And again when trying to unify behaviour between split and non split keyboards.
As part of this i have touched a few things in `quantum/split_common/matrix.c` so that it diffs better with `quantum/matrix.c`.
This PR aims to add a common location to remove duplication, as well as this new location to be optionally leveraged when implementing custom matrix.
* For `CUSTOM_MATRIX=no` boards, the aim is to have zero impact. 
* Round 2 will migrate `keyboards/xd84/custom_matrix_helper.c` to core as 'lite' mode, and in the process remove more duplication from the other matrix implementations.
* Personally I would be keen to add docs once this extra phase is …
> Move some common matrix code to a common location

- keyboards/efreet/config.h
- keyboards/efreet/keymaps/via/keymap.c
- keyboards/efreet/keymaps/via/rules.mk
- keyboards/efreet/rules.mk
Added VIA support to Efreet, a keyboard designed by Soran.
> Added VIA support to Efreet

- keyboards/cannonkeys/satisfaction75/keymaps/default/keymap.c
- keyboards/cannonkeys/satisfaction75/keymaps/tester/keymap.c
- keyboards/cannonkeys/satisfaction75/keymaps/via/keymap.c
- keyboards/converter/usb_usb/keymaps/ble/keymap.c
- keyboards/converter/usb_usb/keymaps/default/keymap.c
- keyboards/handwired/bluepill/keymaps/default/keymap.c
- keyboards/handwired/bluepill/keymaps/iso/keymap.c
- keyboards/handwired/ck4x4/keymaps/default/keymap.c
- keyboards/infinity60/keymaps/default/keymap.c
- keyboards/k_type/keymaps/default/keymap.c
- keyboards/sirius/unigo66/keymaps/default/keymap.c
- keyboards/whitefox/keymaps/default/keymap.c
Omitting this results in some rather interesting behaviour on AVR. These are all ARM boards so the macro resolves to nothing (except for the Unigo66 and USB-USB converter, which just have them in the wrong spot), but we should keep it for consistency.
*
> Ensure `PROGMEM` is present on default keymaps

- keyboards/cannonkeys/stm32f072/keyboard.c
Fix matrix_scan_user is not called at stm32 env(projectkb/alice etc.) which using cannonkeys/stm32f072
just added matrix_scan_user() into cannonkeys/stm32f072/keyboard.c : matrix_scan_kb()
*
> Fix matrix_scan_user is not called at stm32 env(projectkb/alice etc.)

- docs/ChangeLog/20200229/PR6825.md
This updates the LUFA submodule to the latest version, which includes a number of changes, including setting LTO for the bootloader generation. 
~~There are two outstanding PRs for LUFA right now qmk/lufa#5 and qmk/lufa#6 that should be merged into this, as well (and will be updated when they are)~~
This shouldn't wait on these PRs. 
This should also have fewer/no issues with updating, since LUFA is already a submodule.
> Update LUFA submodule

- docs/getting_started_build_tools.md
- util/docker_build.sh
Fixed error when keyboard parameter is omitted in interactive mode.
```
util/docker_build.sh
keyboard=
make: *** empty string invalid as file name.  Stop.
```
> Fix docker script and document

- docs/config_options.md
- docs/custom_quantum_functions.md
- docs/ja/config_options.md
- tmk_core/common/action.c
This PR adds the `IGNORE_MOD_TAP_INTERRUPT_PER_KEY` feature, as like `TAPPING_TERM_PER_KEY`.
The feature may be quite useful for keyboards with few keys (say, 30% or so).
I have confirmed as follows that this patch does not break anything to existing keymaps:
```
git checkout qmk/master
make ergo42/rev1:default # IGNORE_MOD_TAP_INTERRUPT IS NOT enabled
make treadstone32:default # IGNORE_MOD_TAP_INTERRUPT IS enabled
mv ergo42_rev1_default.hex ergo42_rev1_default_MASTER.hex
mv treadstone32_default.hex treadstone32_default_MASTER.hex
git checkout pr_ignore_mod_tap_interrupt_per_key
make ergo42/rev1:default
make treadstone32:default
diff ergo42_rev1_default.hex ergo42_rev1_default_MASTER.hex # shows nothing
diff treadstone32_default.hex treadstone32_default_MASTER.hex # shows nothing
```
> Add per-key IGNORE_MOD_TAP_INTERRUPT feature

- lib/python/qmk/cli/doctor.py
Check the udev rules on the system for the recommended rules. Print warning if not found.
If the udev rules for catalina bootloader are not present, check if ModemManager is running, because that could cause troubles with flashing. In this scenario the `doctor` strongly advices fixing the problem.
**Note**: I tested it the best I could, but most likely need some work before merging. I'm opening this PR in order to get early feedback and help with testing.
*
> CLI: Rework ModemManager check and add udev check

- keyboards/lily58/rules.mk
This is the same workaround as #7558 applied for the Helix.
This code is timing sensitive and seems to break with LTO enabled (at
least on avr-gcc 8.3.0... it worked on older gcc versions). Without this PR applied, Lily58 slave side is totally nonfunctional (no keystrokes register) when using LTO.
* I believe this addresses #7857, though it's possible they're having an unrelated issue.
> Added workaround for serial.c issue when LTO_ENABLE=yes for the Lily58

- tmk_core/protocol/chibios/usb_main.c
Currently produces the error:
```console
Compiling: tmk_core/protocol/chibios/usb_main.c                                                    tmk_core/protocol/chibios/usb_main.c:386:16: error: 'set_led_transfer_cb' defined but not used [-Werror=unused-function]
static void    set_led_transfer_cb(USBDriver *usbp) {
^~~~~~~~~~~~~~~~~~~
[ERRORS]
```
This PR aligns checks to callsite:
https://github.com/qmk/qmk_firmware/blob/2d051d8de3787de889ff0f0301153dbb4e2e1272/tmk_core/protocol/chibios/usb_main.c#L448-L453
> Fix KEYBOARD_SHARED_EP on ChibiOS

- common_features.mk
- quantum/backlight/backlight.c
- quantum/backlight/backlight.h
- quantum/backlight/backlight_arm.c
- quantum/backlight/backlight_avr.c
- quantum/quantum.h
Part 1 of N: 
* Remove duplication of breathing config
* Had to use weak as a bunch of boards are doing custom backlight without setting the rules.mk flag
* ~~Remove duplication of cie_lightness~~
* ~~there might be a better location for this as it kind of fits in with the led_tables functionality~~
* removed for now to avoid conflict with #7521
* Relocate backlight function definitions from quantum to backlight
> Relocate some common backlight functionally

- keyboards/duck/orion/v3/matrix.c
Broken with #7273, empty function without the correct custom driver stuff now produces:
```console
Linking: .build/duck_orion_v3_default.elf                                                           [ERRORS]
| 
| .build/obj_duck_orion_v3_default/quantum/backlight/backlight_avr.o: In function `backlight_init_ports':
| /home/zvecr/Desktop/qmk_firmware/quantum/backlight/backlight_avr.c:449: multiple definition of `backlight_init_ports'
| .build/obj_duck_orion_v3_default/matrix.o:matrix.c:(.text.backlight_init_ports+0x0): first defined here
| collect2: error: ld returned 1 exit status
```
> Remove backlight_init_ports from duck/orion/v3

- tmk_core/protocol/chibios/usb_main.c
Fixes #5585 (attempt 2)
USB status might change from USB_ACTIVE while the thread is sleeping in `osalThreadSuspendS`. If the status is not USB_ACTIVE, we don't have any endpoints and attempting to send on them crashes. Discard these sends. Also fix a race condition in the same function. 
* #5585
> chibios/usb_main: re-check USB status in send_keyboard after sleeping the thread

- docs/he-il/quantum_keycodes.md
- docs/keycodes.md
- docs/quantum_keycodes.md
Also removed documentation of `F()`, `M()`, and `MACROTAP()` to avoid confusion, and encourage users towards `process_record_user()`.
*
> Move Space Cadet keycodes to their own section in keycode reference
