keyboards/business_card/alpha/info.json, keyboards/business_card/beta/info.json
API error log contains:
```
{
"severity": "error",
"message": "Error: Could not parse qmk_firmware/keyboards/business_card/info.json as JSON: Expecting value: line 1 column 1 (char 0)"
},
{
"severity": "error",
"message": "Error: Could not parse qmk_firmware/keyboards/business_card/alpha/../info.json as JSON: Expecting value: line 1 column 1 (char 0)"
},
{
"severity": "error",
"message": "Error: Could not parse qmk_firmware/keyboards/business_card/beta/../info.json as JSON: Expecting value: line 1 column 1 (char 0)"
},
```
Added an `info.json` file for each revision of business_card, and deleted the keyboard-level `info.json` which was made redundant.
Tagging @kakunpc as keyboard maintainer.
=> Provide QMK Configurator API data for business_card

keyboards/choco60/choco60.c, keyboards/choco60/choco60.h, keyboards/choco60/config.h, keyboards/choco60/info.json, keyboards/choco60/keymaps/default/config.h, keyboards/choco60/keymaps/default/keymap.c, keyboards/choco60/keymaps/default/readme.md, keyboards/choco60/readme.md, keyboards/choco60/rules.mk
=> Add support for Choco60

docs/newbs_building_firmware_configurator.md
The QMK Configurator Tutorial link was an outdated one, it has been updated
I just changed a link to the appropriate one, according to the description in MechMerlin's video. It was linked to https://www.youtube.com/watch?v=7RH-1pAbjvw
The correct link appears to be https://www.youtube.com/watch?v=tx54jkRC9ZY which is shortened as in the file change.
* None
=> Update QMK Configurator Tutorial YouTube URL

keyboards/snampad/info.json
```json
{
"severity":"error",
"message":"Error: Could not parse qmk_firmware/keyboards/snampad/info.json as JSON: Expecting value: line 1 column 1 (char 0)"
}
```
Tagging @ptillemans as maintainer.
=> Add Configurator support for snampad

keyboards/meishi2/info.json
```json
{
"severity":"error",
"message":"Error: Could not parse qmk_firmware/keyboards/meishi2/info.json as JSON: Expecting value: line 1 column 1 (char 0)"
}
```
Tagging @biacco42 as maintainer.
=> Add meishi2 Configurator support

keyboards/ergodox_ez/keymaps/colemak_es_osx/config.h, keyboards/ergodox_ez/keymaps/colemak_es_osx/keymap.c, keyboards/ergodox_ez/keymaps/colemak_es_osx/readme.md
Spanish Colemak keymap for ErgoDox EZ
*
=> ErgoDox EZ Spanish Colemak

keyboards/xd75/keymaps/msiu/readme.md
=> Update msiu's xd75 keymap README to be accurate

keyboards/1upkeyboards/1up60hse/keymaps/vosechu/config.h, keyboards/1upkeyboards/1up60hse/keymaps/vosechu/keymap.c, keyboards/1upkeyboards/1up60hse/keymaps/vosechu/readme.md
Basic personal layout that adds spacefn and some other things
=> Add personal 1up60HSE layout

quantum/split_common/matrix.c, tmk_core/protocol/xt_interrupt.c
=> Removed print call to resolve  #6364

keyboards/tanuki/keymaps/default/keymap.c
The default keymap so far used very inefficient and kinda unreadable code to handle per-layer RGB switching. Hooking into matrix scan, overlaying layers, etc. Moreover, it actually writes to EEPROM constantly - originally we thought with every layer change, but it turns out it actually writes on every keypress.
This completely reworks the RGB code, which is now based mostly on what's provided in QMK docs as an example. Functionality stays the same, but it should be much less of a resource hog and not kill Pro Micros after a short while. As an added benefit the toggle for per-layer RGB switching now persists after restart or disconnection of keyboard.
I'd like to thank @haptick#1749 from 40% Discord for testing this with me and making sure everything works as it should.
*
=> Fixed Tanuki RGB lighting

keyboards/projectkb/alice/keymaps/madhatter/keymap.c, keyboards/projectkb/alice/keymaps/madhatter/rules.mk, keyboards/projectkb/alice/readme.md, keyboards/projectkb/alice/rules.mk
A new keymap for the projectkb Alice 
Keymap optimized for my Mac. Changes or mods are:
* vim key bindings for arrows
* left and right command options
* reset moved from right to left
* added DFU_ARGS to rules.mk
=> new keymap for projectkb alice

keyboards/keebio/levinson/keymaps/treadwell/keymap.c
Just some minor edits for my personal layout.
=> Updates personal layout

bin/qmk
=> Use the older `universal_newlines` name instead of `text`

docs/feature_combo.md
=> Change "yu" to "you" in combo docs

docs/config_options.md, docs/feature_backlight.md, docs/getting_started_make_guide.md, docs/hardware_avr.md, docs/porting_your_keyboard_to_qmk_(arm_and_other_chibios_cpus).md, quantum/quantum.c
I've reorganised the big block of defines that help set up the backlight PWM timers and registers. It's now easier to understand what pins are supported on what MCU, and I even threw in a few ones that were missing.
The table now looks like this:
|Backlight Pin|AT90USB64/128|ATmega16/32U4|ATmega16/32U2|ATmega32A|
|-------------|-------------|-------------|-------------|---------|
|`B5`         |Timer 1      |Timer 1      |             |         |
|`B6`         |Timer 1      |Timer 1      |             |         |
|`B7`         |Timer 1      |Timer 1      |Timer 1      |         |
|`C4`         |Timer 3      |             |             |         |
|`C5`         |Timer 3      |             |Timer 1      |         |
|`C6`         |Timer 3      |Timer 3      |Timer 1      |         |
|`D4` …
=> Improve backlight PWM pin support

keyboards/kudox/keymaps/default/keymap.c, keyboards/kudox/keymaps/jis/config.h, keyboards/kudox/keymaps/jis/keymap.c, keyboards/kudox/keymaps/jis/readme.md, keyboards/kudox/keymaps/x1/keymap.c
Adds JIS keymap for Kudox Keyboard.
* Adds JIS keymap for Kudox Keyboard.
* Removed unnecessary codes of Kudox.
=> [keymap] Add kudox japanese keymap

keyboards/planck/keymaps/sascha/keymap.c
A simple keymap update for my rev5 planck.
* None
=> Update my keymap to contain the latest changes

keyboards/kudox/keymaps/jis/keymap.c
Modified imcomplete keymap for Kudox JIS by including `keymap_jp.h` .
* Kudox JIS keymap is imcomplete.
=> [keymap] Modified imcomplete keymap for Kudox jis.

keyboards/romac/keymaps/jarred/keymap.c
* 
- [ x] My code follows the code style of this project.
- [ x] I have updated the documentation accordingly.
=> Add my romac keymap

keyboards/40percentclub/gherkin/keymaps/default/keymap.c
Reported on Discord by mikethetiger. `make 40percentclub/gherkin:default CTPC=yes` fails due to AVR specific code in the default keymap.
=> Gherkin CTPC compatibility - Update to use gpio

users/talljoe/talljoe.c
The Wilba refactor broke my keymap with a header file move.
*
=> Fix include following Wilba refactor

quantum/template/base/keymaps/default/keymap.c
=> Remove backslashes from template keymap

docs/hardware_avr.md
Small bit of wordsmithing, `DESCRIPTION` is not actually displayed as part of the USB device's properties (and never was).
*
=> Reword a note about the MANUFACTURER and PRODUCT defines in hardware_avr.md

quantum/mcu_selection.mk
All of the 32U2 boards currently in the repo use these values, so they seem like good defaults 👍
*
=> Add ATmega32U2 to mcu_selection.mk

keyboards/xd96/xd96.c
=> Implement NUMLOCK indicator light for XD96

keyboards/projectkb/alice/keymaps/madhatter/keymap.c, keyboards/projectkb/alice/keymaps/madhatter/rules.mk
* Enabled Velocikey
* Moved reset, so I don't press this accidentally
* Added Grave and GESC, cause Escape is too damn far away on an Alice
*
=> Personal Keymap - Add velocikey, move reset and align layout

quantum/keycode_config.c, quantum/quantum.c
* Provide better documentation in files for what the check functions do.
* Adds better handling for quantum keycodes that toggle both right and left mods. 
* Addresses comments from #6110 by @yanfali
=> Fix up Bootmagic code

keyboards/clueboard/card/rules.mk, keyboards/preonic/rev1/rules.mk, keyboards/preonic/rev2/rules.mk, keyboards/xd004/v1/rules.mk
=> Reduce compile size to fix various Travis CI errors

docs/flashing.md, docs/flashing_bootloadhid.md, docs/getting_started_make_guide.md, docs/newbs_flashing.md, quantum/template/ps2avrgb/readme.md, tmk_core/avr.mk
Currently there are over 20 readme files that have various states of documentation on how to flash BMC/bootloadHID/ATmega32A based boards. Some include faq style help, some include bootloadHID installation instructions, while others just state the flashing requirement.
In order to clean up the fragmented bootloadHID docs within various readme files:
And at some point:
* Tidy up existing readme files (however this could be better if done one by one as its a potential moving target).
=> Add 'bootloadHID' flash target

keyboards/tada68/keymaps/onelivesleft/config.h, keyboards/tada68/keymaps/onelivesleft/keymap.c, keyboards/tada68/keymaps/onelivesleft/readme.md, keyboards/tada68/keymaps/onelivesleft/rules.mk
Bare:
* Delete
* Capslock
* Home
* End
With FN:
* Insert
* Break
* Page Up
* Page Down
* Fn + cursors to move
* Fn + Right Ctrl for left click
* Fn + Right Shift for right click
* Capslock key used as a second Fn key (for easy one-handed alt+F4 etc.)
* Fn + ': `
* Fn + P: Printscreen
=> ISO keymap for TADA68 with programming in mind

keyboards/redox_w/keymaps/default/keymap.c
This switches from updating the LED state on every `matrix_scan_user` to `layer_state_set_user` which as I understand it is preferable.
FAO @mattdibi
=> Redox_w Use layer_state_set_user instead of matrix_scan_user

bin/qmk
=> Make the CLI Ψ capital

keyboards/hhkb/keymaps/tobiasvl_iso/keymap.c, keyboards/hhkb/keymaps/tobiasvl_iso/readme.md
Adds my personal keymap for HHKB (Hasu), with some adjustments to make it a bit more ISO-like.
* N/A
=> Personal ISO-ish keymap for HHKB

keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c, keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/readme.md, keyboards/keebio/quefrency/keymaps/bcat/config.h, keyboards/keebio/quefrency/keymaps/bcat/keymap.c, keyboards/keebio/quefrency/keymaps/bcat/readme.md, layouts/community/60_ansi_split_bs_rshift/bcat/keymap.c, layouts/community/60_ansi_split_bs_rshift/bcat/readme.md, layouts/community/60_tsangan_hhkb/bcat/keymap.c, layouts/community/60_tsangan_hhkb/bcat/readme.md
* Switch Quefrency back from serial to I2C since this works now.
* Add (EEPROM) reset keybindings everywhere, since Bootmagic Lite combines reset and EEPROM reset, which isn't always desired.
* Move Caps Lock from Fn+Ctrl to Fn+Tab everywhere.
* Move Menu key to a layer tap on Fn key for KBD67.
None
=> Assorted personal keymap/layout updates

docs/cli.md, lib/python/qmk/cli/cformat.py
=> CLI command for formatting C code

keyboards/dztech/dz60rgb/keymaps/perseid/keymap.c, keyboards/dztech/dz60rgb/keymaps/perseid/readme.md, keyboards/planck/keymaps/skank/keymap.c
* One new keymap for my dz60rgb
* Update to my existing keymap for the planck
=> Combo keymap update - For planck and dz60rgb

keyboards/foxlab/leaf60/universal/keymaps/jarred/keymap.c, keyboards/foxlab/leaf60/universal/keymaps/jarred/readme.md, keyboards/tada68/keymaps/jarred/keymap.c, keyboards/tada68/keymaps/jarred/readme.md, keyboards/tada68/keymaps/jarred/rules.mk, users/jarred/readme.md
Add my leaf60 and tada68 keymaps
*
=> Add leaf60 and tada68 keymaps

docs/index.html
=> Fix typo in Open Graph description for docs

keyboards/projectkb/alice/config.h, keyboards/projectkb/alice/keymaps/madhatter/keymap.c, keyboards/projectkb/alice/rules.mk
Fix for the Ctrl and OS key swap for this specific board
* Adds suggested fix for (unofficial) VIA board
* Updates keymap and adds an EEP_RST too
=> Update keymap for alice and fix for ctrl and os swap

Makefile
As LUFA is now a submodule, we should be checking it.
=> Update submodule check to include LUFA

keyboards/keebio/tukey/config.h, keyboards/keebio/tukey/info.json, keyboards/keebio/tukey/keymaps/default/config.h, keyboards/keebio/tukey/keymaps/default/keymap.c, keyboards/keebio/tukey/keymaps/default/readme.md, keyboards/keebio/tukey/readme.md, keyboards/keebio/tukey/rules.mk, keyboards/keebio/tukey/tukey.c, keyboards/keebio/tukey/tukey.h
=> Add Tukey board

keyboards/ergodone/keymaps/vega/keymap.c
=> added ability to change unicode input method to ergodone:vega

keyboards/atomic/atomic.c
Seems I missed one in #6445 ...
*
=> Missed a JTAG disable

keyboards/vitamins_included/config.h
Changed to 1209 VID as I was granted the BEE5 PID :) https://github.com/qmk/qmk_firmware/pull/6677
=> Changed to 1209 PID

docs/config_options.md, tmk_core/protocol/usb_descriptor.c
This one may need some testing. There have already been a few people who have changed this value manually and reported back with no issues, but it wouldn't hurt. I'm interested to know whether setting it to 1ms makes much difference at all, given how much QMK can be doing in its loop.
*
=> Make USB polling rate configurable with a define

keyboards/atomic/atomic.c, keyboards/playkbtw/ca66/ca66.c, keyboards/playkbtw/ca66/ca66.h, keyboards/playkbtw/ca66/config.h, keyboards/playkbtw/ca66/keymaps/default/keymap.c, keyboards/playkbtw/ca66/readme.md, keyboards/playkbtw/ca66/rules.mk
Was porting CA66 R2 into QMK only to realize that it is exactly the same in terms of switch matrix and LEDs as the R1. The only difference is physical. Just cleaned up the repo to more align with QMK standards. 
*
=> CA66 R1/R2 Cleanup

bin/qmk, keyboards/handwired/onekey/pytest/config.h, keyboards/handwired/onekey/pytest/readme.md, keyboards/handwired/onekey/pytest/rules.mk, keyboards/handwired/onekey/pytest/templates/keymap.c, lib/python/milc.py, lib/python/qmk/cli/doctor.py, lib/python/qmk/cli/nose2.py, lib/python/qmk/cli/pyformat.py, lib/python/qmk/tests/attrdict.py, lib/python/qmk/tests/onekey_export.json, lib/python/qmk/tests/test_qmk_errors.py, lib/python/qmk/tests/test_qmk_keymap.py, lib/python/qmk/tests/test_qmk_path.py, nose2.cfg, util/travis_build.sh
Unit tests for python and a `qmk doctor` that also tries to run some programs. Run the unit tests with `bin/qmk nose2`.
This PR requires https://github.com/qmk/qmk_base_container/pull/4 before it can be merged.
*
=> Basic python test framework

keyboards/gingham/rules.mk, keyboards/handwired/hnah40/rules.mk, keyboards/plaid/rules.mk, quantum/mcu_selection.mk
Now all that's left to do is remove these defaults from every board in the repo 😁
*
=> Add 328P to mcu_selection.mk

tmk_core/avr.mk, tmk_core/chibios.mk
Whoops, wrong message string!!
=> Actually use correct bootloader not found message

keyboards/copenhagen_click/click_pad_v1/click_pad_v1.c, keyboards/copenhagen_click/click_pad_v1/click_pad_v1.h, keyboards/copenhagen_click/click_pad_v1/config.h, keyboards/copenhagen_click/click_pad_v1/info.json, keyboards/copenhagen_click/click_pad_v1/keymaps/default/config.h, keyboards/copenhagen_click/click_pad_v1/keymaps/default/keymap.c, keyboards/copenhagen_click/click_pad_v1/keymaps/default/readme.md, keyboards/copenhagen_click/click_pad_v1/readme.md, keyboards/copenhagen_click/click_pad_v1/rules.mk
Add Copenhagen Click Pad
Added a keyboard and keymap for the Copenhagen Click Pad V1
*
=> Add Copenhagen Click Pad

keyboards/chimera_ergo/chimera_ergo.h, keyboards/chimera_ls/chimera_ls.h, keyboards/chimera_ortho/chimera_ortho.h, keyboards/comet46/comet46.h, keyboards/dichotomy/dichotomy.h, keyboards/honeycomb/honeycomb.h, keyboards/mitosis/mitosis.h, keyboards/redox_w/redox_w.h, keyboards/telophase/telophase.h
Cherry picked from #6710 
While working on unifying backlight, various keyboards have been found to include extra headers instead of just `quantum.h`.
This PR aligns includes for a few of the boards `<keyboard>.h`.
=> Tidy up backlight header use to avoid build issues

.vscode/extensions.json
This includes a number of recommended extensions from the VS Code doc page that should make coding things a lot easier for QMK Firmware.
The `xaver.clang-format` will actually properly apply the clang formatting options to files when you format them in VS Code (the built in C/C++ extension fails to do so properly).   This way, we can help keep things consistent. 
The other extensions are ones that we have in the "How to use VSCode" doc, and ... well, would fit in well here.
=> Add to VSCode's recommended extensions

keyboards/2key2crawl/2key2crawl.c, keyboards/2key2crawl/2key2crawl.h, keyboards/2key2crawl/config.h, keyboards/2key2crawl/keymaps/default/keymap.c, keyboards/2key2crawl/keymaps/tabs/keymap.c, keyboards/2key2crawl/keymaps/vol/keymap.c, keyboards/2key2crawl/readme.md, keyboards/2key2crawl/rules.mk
Adds support for the 2key2crawl macro pad
changes made in accordance with requests in original commit #4532
*
=> Add 2key2crawl

keyboards/ergodash/rev1/keymaps/greenshadowmaker/keymap.c
Updated Keymap, corrected style as advised on different keymap update
*
=> style cleanup, no keys changed

docs/feature_backlight.md
Add a bit more detail to the doc. Otherwise, it's a bit trial and error. 
*
=> Clarify the backlight_level API doc slightly

keyboards/cannonkeys/satisfaction75/config.h, keyboards/cannonkeys/satisfaction75/satisfaction75.c, keyboards/cannonkeys/satisfaction75/satisfaction75.h, keyboards/cannonkeys/satisfaction75/satisfaction_encoder.c
Bump EEPROM addresses for S75 to avoid collisions.
Add custom encoder configuration through VIA support.
*
=> 201909 s75 custom encoder

keyboards/clueboard/2x1800/rules.mk, keyboards/converter/modelm101/rules.mk, keyboards/donutcables/scrabblepad/rules.mk, keyboards/handwired/108key_trackpoint/rules.mk, keyboards/handwired/aek64/rules.mk, keyboards/handwired/daishi/rules.mk, keyboards/handwired/datahand/rules.mk, keyboards/handwired/downbubble/rules.mk, keyboards/handwired/hacked_motospeed/rules.mk, keyboards/handwired/ibm122m/rules.mk, keyboards/handwired/magicforce61/rules.mk, keyboards/handwired/ms_sculpt_mobile/rules.mk, keyboards/handwired/onekey/teensy_2pp/rules.mk, keyboards/kinesis/rules.mk, keyboards/lfkeyboards/lfk78/rules.mk, keyboards/lfkeyboards/lfk87/rules.mk, keyboards/lfkeyboards/mini1800/rules.mk, keyboards/lfkeyboards/smk65/rules.mk, keyboards/m0lly/rules.mk, keyboards/omnikey_blackheart/rules.mk, keyboards/omnikeyish/rules.mk, keyboards/planck/light/rules.mk, keyboards/subatomic/rules.mk, keyboards/tkc1800/rules.mk, keyboards/uk78/rules.mk, keyboards/vision_division/rules.mk, keyboards/z150_blackheart/rules.mk
#6768, part 3. This is it for everything that isn't 32U4, I think I'll be breaking that up into several batches.
*
=> Cleanup rules.mk for USB64 and USB128 keyboards

keyboards/2key2crawl/rules.mk, keyboards/alps64/rules.mk, keyboards/bigseries/rules.mk, keyboards/bpiphany/frosty_flake/rules.mk, keyboards/bpiphany/kitten_paw/rules.mk, keyboards/bpiphany/pegasushoof/rules.mk, keyboards/bpiphany/tiger_lily/rules.mk, keyboards/bpiphany/unloved_bastard/rules.mk, keyboards/handwired/6macro/rules.mk, keyboards/idb_60/rules.mk, keyboards/illuminati/is0/rules.mk, keyboards/kbdfans/kbdpad_mk2/rules.mk, keyboards/meme/rules.mk, keyboards/novelpad/rules.mk, keyboards/primekb/prime_m/rules.mk, keyboards/primekb/prime_o/rules.mk, keyboards/sixkeyboard/rules.mk, keyboards/staryu/rules.mk, keyboards/ut472/rules.mk, keyboards/xd004/v1/rules.mk
=> Cleanup rules.mk for 16U2 and 32U2 keyboards

docs/feature_backlight.md, quantum/quantum.c
I forgot all about the 328P, it has a 16-bit timer too :D
*
=> Add support for 328P hardware backlight on B1/B2

docs/breaking_changes.md
=> Update the breaking changes process so we always have a future branch

shell.nix
1. The makefile told me that python3 was needed soon.
2. I wasn't able to run `make planck/rev4:default` without that modification (using `nix-shell`).
*
=> add python3 to shell.nix

keyboards/dztech/dz65rgb/keymaps/chocol8/config.h, keyboards/dztech/dz65rgb/keymaps/chocol8/keymap.c, keyboards/dztech/dz65rgb/keymaps/chocol8/rules.mk
New Keymap for the dz65rgb:
* adds a layer for mac vs linux keymaps
* puts a reset on the FNM layer
=> New keymap for the DZ65RGB

keyboards/kbdfans/kbd75/keymaps/broswen/README.md, keyboards/kbdfans/kbd75/keymaps/broswen/keymap.c
Modified the default kbd75 keymap for more personal use.
*
=> add keymap broswen for kbd75

keyboards/vitamins_included/rev2/config.h
I realized I at some point managed to get rid of the QMK-DFU defines in my rev2 config. This PR re-introduces them
=> Vita inc rev2 bootloader fix

keyboards/maartenwut/wonderland/keymaps/default/keymap.c
=> correct default keymap for wonderland

keyboards/hecomi/keymaps/kakunpc/keymap.c
=> [keymap]update hecomi/kakunpc keymap

keyboards/donutcables/budget96/budget96.c
Adding code to make the RGB switching work. Taken from the singa (singa.c).
Just adding missing lines to the budget96.c. Please let me know if there would be changes needed.
=> [featurefix] budget96 RGB light-switches

keyboards/signum/3_0/elitec/config.h, keyboards/signum/3_0/elitec/keymaps/default/keymap.c, keyboards/signum/3_0/elitec/keymaps/default/layout.py
Enable kinetic speed and update keymap.
=> Signum 3 0 enable kinetic speed

docs/arm_debugging.md, docs/cli.md, docs/hardware_keyboard_guidelines.md, docs/newbs_flashing.md
Fixed typos in the following files:
- newbs_flashing.md
- arm_debugging.md
- cli.md
- hardware_keyboard_guidelines.md
=> Fixed typos in documentation

keyboards/massdrop/alt/keymaps/favorable-mutation/README.md, keyboards/massdrop/alt/keymaps/favorable-mutation/config.h, keyboards/massdrop/alt/keymaps/favorable-mutation/keymap.c
=> :world_map: Adds massdrop/alt/favorable-mutation keymap

keyboards/alpha/keymaps/hvp/keymap.c
Added a functional, sort of mod heavy layout that fits my usage. 
* NA
=> Added my version of the alpha28 layout. Usable.

keyboards/donutcables/budget96/budget96.h, keyboards/donutcables/budget96/readme.md
Turns out the production version of the budget96 is different from the prototype. 
The difference is that the production has the top 2 right most keys swapped. 
Since there are only 6 prototypes and 1 of them is with me, and 5 are with @DonutCables , I am just going to make this change here without specifying that its a different PCB.
=> Budget96 Production PCB Fix

.travis.yml
Refer to https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.
> In the next phase of the migration, all builds will run on virtual-machine-based infrastructure – regardless of the configuration for `sudo` in the `.travis.yml`.
> Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.
*
=> removed deprecated option for Travis

keyboards/keebio/iris/keymaps/mattly/keymap.c, users/mattly/mattly.h
Just updating my keymap & underglow colors
*
=> finally committing my updates

keyboards/westfoxtrot/cyclops/keymaps/peippo/config.h, keyboards/westfoxtrot/cyclops/keymaps/peippo/keymap.c, keyboards/westfoxtrot/cyclops/keymaps/peippo/readme.md
Add a new keymap for Cyclops, nordic layout with faster access to cursor movement keys and brackets among other features.
*
=> Add new Cyclops keymap

docs/feature_ps2_mouse.md
Removed an old link and fixed a typo
=> Removed dead link

keyboards/lazydesigners/dimple/config.h, keyboards/lazydesigners/dimple/dimple.c, keyboards/lazydesigners/dimple/keymaps/default/keymap.c
Fix one of my small mess-ups. The Caps Lock indicator should be On when the CL is on and Off when CL is off, not the other way around. :)
*
=> Dimple: Fix Caps Lock LED behaviour

docs/cli.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/list/__init__.py, lib/python/qmk/cli/list/keyboards.py, lib/python/qmk/tests/test_cli_commands.py
`list_keyboards` replicates the `make list-keyboards` by globbing for all paths
that include `rules.mk` and then removing the paths that include `keymaps`.
This basis of this cli command could be reused in the future as a util, but is
not done so here since this would be the only place that would use it currently
Resolves #6911
* #6911
=> Add `qmk list_keyboards`

keyboards/40percentclub/gherkin/keymaps/talljoe-gherkin/keymap.c
talljoe-gherkin keymap was missing the number 8 but had 7 twice. This patch replaces the second seven by 8.
*
=> Talljoe gherkin typo

keyboards/lets_split/keymaps/khord/keymap.c
Removed unneeded lines and change right side mouse buttons on raise layer back to media control
*
=> Clean up / adjust khord let's split keymap

docs/contributing.md
This wasn't really documented anywhere. Might need some wordsmithing?
Also just a couple of typos.
*
=> Add an important note about modifying user code

docs/faq_general.md
=> Remove unanswered/unnecessary FAQ item

docs/internals_gpio_control.md
Add examples for reference for people not as well versed in microcontroller coding, such as myself.
* My frequent annoyance, since I have issues remembering this stuff
=> [Docs] Add AVR and ARM examples to GPIO Commands

users/yanfali/rules.mk
Only build audio for specific boards that match this community layout. Apologies to @awkannan for breaking the instant60 build
*
=> Overly greedy community keymap build userspace

docs/newbs_flashing.md
Brings flashing docs in line with change #6930.
=> [Docs] Clean up docs/newbs_flashing.md

readme.md
I Fixed missing link in readme.
Close #5240
=> Fix missing link in readme

docs/fr-FR/ChangeLog/20190830.md, docs/fr-FR/_summary.md, docs/fr-FR/breaking_changes.md
This PR adds the French translation for the Breaking change section, with the breaking changes of the 2019 08 30. 
* #6924
=> French translation - breaking changes section

lib/python/qmk/cli/docs.py
To avoid the stack trace when you get bored of looking at docs :^)
*
=> `qmk docs` graceful shutdown on Ctrl+C

quantum/template/ps2avrgb/readme.md
Reported by rempired. Link leads to 404 error.
=> fix broken link to ps2avrgb flashing instructions

docs/feature_key_lock.md
=> docs: update one shot keys link

util/travis_build.sh, util/travis_test.sh
=> Move running CLI tests to travis_test

keyboards/converter/usb_usb/README.md
Minor updates to make the README a little more readable.
None
=> Update formatting of README for usb_usb

keyboards/crkbd/keymaps/hvp/config.h, keyboards/crkbd/keymaps/hvp/keymap.c, keyboards/crkbd/keymaps/hvp/readme.md, keyboards/crkbd/keymaps/hvp/rules.mk, users/hvp/hvp.c, users/hvp/hvp.h, users/hvp/readme.md, users/hvp/rules.mk, users/hvp/tap_dances.c, users/hvp/tap_dances.h
Keymap to be used with Eurkey for easy access to Swedish characters on the #first layer.
Links:
- https://eurkey.steffen.bruentjen.eu/
*
=> Adding profile for Corne with tap dance Swedish support.

keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md
Tweaks a bunch of things on the keymap based on day-to-day use. Also adds KLE images and a readme explaining some choices that went into the keymap.
None
=> Various improvements to my Lily58 keymap

keyboards/dztech/dz65rgb/dz65rgb.c, keyboards/dztech/dz65rgb/keymaps/default/keymap.c
- to keyboard so it works in configurator
* fixes issue raised by Malincak#7372 and tested by Mailnchak
=> DZ65RGB Caps lock moved from keymap

keyboards/redox/keymaps/KL1RL/config.h, keyboards/redox/keymaps/KL1RL/keymap.c, keyboards/redox/keymaps/KL1RL/readme.md, keyboards/redox/keymaps/KL1RL/rules.mk
Just a quick upload of the keymap i've had in use on my redox for about 4 months now.  Since it's been long enough without any changes I figure it's likely stable.  For me at least.
None
=> Inital commit of KL1RL keyboard layout

lib/python/qmk/cli/doctor.py
Fixed detection of ModemManager on Linux when running ```qmk doctor``` from the repository local CLI.
* #7074
=> Fix detection of ModemManager on Linux

keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c, keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/readme.md, keyboards/keebio/quefrency/keymaps/bcat/keymap.c, keyboards/keebio/quefrency/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md, layouts/community/60_ansi_split_bs_rshift/bcat/keymap.c, layouts/community/60_ansi_split_bs_rshift/bcat/readme.md, layouts/community/60_tsangan_hhkb/bcat/keymap.c, layouts/community/60_tsangan_hhkb/bcat/readme.md, users/bcat/config.h
* Tweaks tapping settings a bit.
* Further modifies Lily58 keymap.
* Updates the rest of my keymaps/userspace to use standard formatting and have correct KLE images/links in readmes.
None
=> Assorted personal keymap and layout updates

keyboards/projectkb/alice/keymaps/madhatter/keymap.c, keyboards/projectkb/alice/keymaps/madhatter/readme.md
- A layer for all functions and mouse keys
- A layer for arrows and media
- Arrows on IJKL
- Caps and control on caps lock - wonderful
- Things to reduce my finger travel just about everywhere
=> [keymap] updates to madhatter keymap - project keyboard alice pcb

keyboards/planck/keymaps/default/keymap.c, keyboards/planck/planck.c, keyboards/preonic/keymaps/default/keymap.c, keyboards/preonic/rev1/rev1.c, keyboards/preonic/rev2/rev2.c
=> Use GPIO macros for E6 LED in Planck and Preonic default keymaps

docs/driver_installation_zadig.md
While translating I noticed that the troubleshooting section could use a
little bit more explanation. @Yanfali was so kind to chime in on this on
discord and explained that this was ment for people who accidently
forget to put their board in bootloader mode, so I tried to be more
clear about this.
Also I don't think Zadig installs anything `onto` the keyboard but rather
changes what driver is responsible for interacting with the WCID, so I
changed the wording to reflect this.
Let me know what you think about this please. 
Also fixed the spelling of Msys2 to MSYS2 and Halfkay to HalfKay as
these are the official spellings they use themselves.
Cheers
=> Add a short explanation to Zadig the troubleshooting section

keyboards/keebio/bdn9/keymaps/eosti/config.h, keyboards/keebio/bdn9/keymaps/eosti/keymap.c, keyboards/keebio/bdn9/keymaps/eosti/readme.md, keyboards/keebio/bdn9/keymaps/eosti/rules.mk
Adds EosTi's BDN9 keymap.
* None
=> add bdn9/eosti keymap

keyboards/hineybush/h87a/config.h
Update PID and VID and vendor of h87a
*
=> update VID and PID for h87a

keyboards/clueboard/california/california.c, keyboards/clueboard/california/california.h, keyboards/clueboard/california/config.h, keyboards/clueboard/california/info.json, keyboards/clueboard/california/keymaps/default/keymap.json, keyboards/clueboard/california/readme.md, keyboards/clueboard/california/rules.mk
Support for the Clueboard California, a 10 key macropad that will be sold at the NorCal meetup.
=> Support for the Clueboard California macropad

keyboards/reviung34/info.json
Tagging @gtips (keyboard maintainer).
http://api.qmk.fm/v1/keyboards/error_log:
```json
{
"message": "Error: Could not parse qmk_firmware/keyboards/reviung34/info.json as JSON: Expecting value: line 1 column 1 (char 0)",
},
```
=> reviung34: Configurator layout fix

keyboards/atreus/astar_mirrored/astar_mirrored.c, keyboards/atreus/astar_mirrored/astar_mirrored.h, keyboards/atreus/astar_mirrored/config.h, keyboards/atreus/astar_mirrored/rules.mk, keyboards/atreus/atreus.h
* Fixes #5952
* Fixes qmk/qmk_configurator#537
=> copied atreus astar to mirrored, set PCBDOWN flag

.github/labeler.yml, .github/workflows/labeler.yml
A stab at adding some labels automagically, as some first steps at some process automation.
Automatic keyboard label requires <https://github.com/actions/labeler/issues/9> otherwise something like `keyboards/**/*` would also be triggered by keymap changes.
=> Initial actions/labeler config

keyboards/wilba_tech/rama_works_m6_a/keymaps/rys/keymap.c
Personal layout for the M6-A, to turn it in to an arrow cluster with some other useful keys when I'm using smaller boards.
=> Personal layout for the RAMA M6-A

docs/keycodes.md, docs/keycodes_basic.md, docs/keycodes_us_ansi_shifted.md
This seems to render properly on GitHub and Docsify now. Not caring about Gitbook.
*
=> Backslash-escape pipe character in keycode lists

docs/how_keyboards_work.md
Changes the invalid given URL for `60-keyboard.hwdb at Master` to the fixed one.
* Invalid URL in `how_keyboards_work.md`
=> Update URL for `60-keyboard.hwdb`

keyboards/namecard2x4/rules.mk
Example error output [here](https://travis-ci.org/qmk/qmk_firmware/builds/603704223?utm_source=github_status&utm_medium=notification).
```console
Making namecard2x4 with keymap default                                                                 [ERRORS]
In file included from quantum/quantum.h:29:0,
from keyboards/namecard2x4/namecard2x4.h:19,
from keyboards/namecard2x4/namecard2x4.c:16:
quantum/keymap.h:52:33: error: 'MATRIX_ROWS' undeclared here (not in a function)
extern const uint16_t keymaps[][MATRIX_ROWS][MATRIX_COLS];
^
quantum/keymap.h:52:46: error: 'MATRIX_COLS' undeclared here (not in a function)
extern const uint16_t keymaps[][MATRIX_ROWS][MATRIX_COLS];
^
| 
| 
| 
tmk_core/rules.mk:377: recipe for target '.build/obj_namecard2x4_default/keyboards/namecard2x4/namecard2x4.o' …
```
=> Fix travis build failures for namecard2x4

util/macos_install.sh
* Fixes potential issue with [word splitting](https://github.com/koalaman/shellcheck/wiki/SC2086). 
* Proper [shell redirection](https://github.com/koalaman/shellcheck/wiki/SC2069)
* Potential word splitting issue with directories with spaces in them.
* `if ! brew --version 2>&1 > /dev/null; then` doesn't hide error messages as stderr is redirected to stdout and not `/dev/null`
=> Clean macOS install script

keyboards/ergodox_ez/keymaps/skug/keymap.c
Added `KC_ESC` to "standard" position in main layer and moved `SE_HALF` to ARRW layer
Added `<` `>` as standalone keys in SYMB layer
*
=> Layout update for my ergodox

docs/cli.md, lib/python/qmk/cli/json/keymap.py
- Sort the commands alphabetically
- Add missing `json_keymap`
- Correct underscore to dash
=> Fix some bugs in CLI docs

docs/feature_userspace.md, docs/flashing.md, docs/fr-FR/flashing.md, docs/fr-FR/newbs_flashing.md, docs/getting_started_build_tools.md, docs/getting_started_make_guide.md, docs/newbs_flashing.md
And some cleanup. 
Additionally, attempted machine translation of french docs. 
May attempt chinese later?
=> [Docs] Update flashing information to include :flash target

docs/de/cli.md
- I followed the guide lines set by kuchosauronad0 in their start of the German translation
> * Weise den User an, die Umgebungs-Variable `QMK_HOME` zu setzen, um die Firmware-Quelle anders einzustellen als `~/qmk_firmware`.
- I wasn't quite sure with this translation, as I didn't understand the context in the original English docs.
- The link to the CLI Configuration page is currently not working, due to it being missing in German.
*
=> Translated "CLI" documentation to German

keyboards/c39/keymaps/kuchosauronad0/config.h, keyboards/c39/keymaps/kuchosauronad0/keymap.c, keyboards/c39/keymaps/kuchosauronad0/readme.md, keyboards/c39/keymaps/kuchosauronad0/rules.mk
Update to my c39 keymap in conjunction with #6899 
* Add RGB
* Add Plover layer
*
=> Update keymap for c39 / kuchosauronad0

tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/main.c
Noticed during #7173 and #7183.
=> rgblight_task logic fixes

bin/qmk
Noticed this in the Travis log for #7218.
*
=> Fix "could not find module" error message formatting

docs/feature_haptic_feedback.md
A description of keycode is not correct, so corrected it.
=> update uncorrect description of haptic_feedback doc

common_features.mk, docs/feature_backlight.md, quantum/backlight/backlight_avr.c, quantum/backlight/backlight_soft.c, quantum/quantum.c, quantum/quantum.h
* Default CTPC to pure software PWM
* Add software breathing
* Unpick existing AVR implementation?
* Convert existing boards?
=> Initial migration of software PWM backlight

docs/feature_auto_shift.md, quantum/process_keycode/process_auto_shift.c, quantum/process_keycode/process_auto_shift.h
* Fix edge case when using One Shot Layer with Auto Shift, and it not triggering the cleanup
* Remove junk code (no longer used)
* Replace `(un)register_code` calls with `tap_code` where appropriate
* Fixed up Switch check to be more readable (less verbose)
* Simplified modifier check (if it comes back non-zero, there are mods)
* Add additional function calls for autoshift settings
* Made all variables static, since there are function calls to get their status
* Fixed up documentation
* Fixes #4629
=> Smallish overhaul of Auto-Shift feature

keyboards/model01/keymaps/dshields/keymap.c, keyboards/planck/keymaps/dshields/keymap.c, users/dshields/dshields.h
=> [Keymap] Add new LED/RGB key codes.

keyboards/kyria/keymaps/default/keymap.c
Some errors slipped through.  Whoops! Sorry!
=> [Keyboard] Fix Kyria default keymap

.travis.yml, util/travis_build.sh, util/travis_compiled_push.sh, util/travis_docs.sh, util/travis_push.sh, util/travis_test.sh, util/travis_utils.sh
At the moment there are a few issues which cause confusion during the PR process:
<details><summary>1. Merge of master causes the build to target the wrong files</summary>
TODO
</details>
<details><summary>2. Keymap detection sometimes builds too much/skips build completely</summary>
<https://travis-ci.org/qmk/qmk_firmware/builds/593344280?utm_source=github_status&utm_medium=notification>
```bash
The command "bash util/travis_test.sh" exited with 0.
0.99s$ bash util/travis_build.sh
keyboards/massdrop/alt/keymaps/favorable-mutation/README.md
keyboards/massdrop/alt/keymaps/favorable-mutation/config.h
keyboards/massdrop/alt/keymaps/favorable-mutation/keymap.c
Making all keymaps for massdrop/alt/keymaps
QMK Firmware 0.7.30
make: *** No rule to make target 'massdrop/alt/keymaps:all'. Stop.
|
| …
```
=> CI - Fix change detection

drivers/arm/i2c_master.h
=> Fix typo in ARM I2C copyright header

Makefile
Per https://superuser.com/a/1286550, the depth being set to 1 seems to be what's causing some of the submodule headaches - at least for LUFA. 50 is the value that Travis uses to clone, so let's go with that.
*
=> Set `git submodule update` depth to 50

keyboards/crkbd/rev1/rules.mk
The need for this was dropped in 947e61eaebf168c0c60be34914141cff9a69e599
*
=> Remove RGB_MATRIX_SPLIT_RIGHT from crkbd

keyboards/model01/keymaps/dshields/keymap.c, keyboards/planck/keymaps/dshields/keymap.c, users/dshields/config.h, users/dshields/dshields.c, users/dshields/dshields.h, users/dshields/rules.mk
=> [keymap] Remove dynamic macro customization now it's a core feature.

docs/_summary.md, docs/compatible_microcontrollers.md
Made this page a little more comprehensive, and actually added it to the nav.
*
=> Tidy up compatible MCUs docs

.github/ISSUE_TEMPLATE/blank.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other_issues.md
Add Labels to Issue templates?
=> Update issue templates

keyboards/kingly_keys/romac/readme.md, keyboards/kingly_keys/romac_plus/readme.md, keyboards/kingly_keys/ropro/readme.md
These were apparently missed in the move to the vendor directory.
* Fixes #7307
=> Fix readme make examples for some Kingly Keys boards

docs/config_options.md, drivers/arm/ws2812.c, drivers/arm/ws2812.h, drivers/avr/ws2812.c, drivers/avr/ws2812.h, drivers/avr/ws2812_i2c.c, quantum/rgb_matrix_drivers.c, quantum/rgblight.c
* Unified RGB and RGBW API using `LED_TYPE`
* `rgblight.c` now clears W on RGBW LEDs
* Closes #2350
=> Unify RGB and RGBW commands

keyboards/atreus62/keymaps/xyverz/keymap.c
Added MACLOCK macro, which sends CMD+CTRL+Q to perform a screen
lock on macs running Mojave or newer.
=> Added macro

keyboards/hs60/v2/keymaps/stanrc85/config.h
Small RGB config changes to my layout
*
=> minor user config changes

lib/python/qmk/cli/cformat.py
Some distributions, like Debian, ship old versions of clang-format by default. This will select the newest version of clang-format installed and use that.
*
=> Add support for newer versions of clang-format, if installed

lib/python/qmk/cli/config.py, lib/python/qmk/cli/list/keyboards.py, lib/python/qmk/errors.py, lib/python/qmk/tests/attrdict.py, lib/python/qmk/tests/test_cli_commands.py, lib/python/qmk/tests/test_qmk_path.py
* yapf changes
* Fix the cformat test
* Make the normpath test work when run from /
* `qmk config`: Mark `--read-only` as arg_only
*
=> Small CLI cleanups

keyboards/massdrop/alt/keymaps/xulkal/config.h, keyboards/massdrop/alt/keymaps/xulkal/keymap.c, keyboards/massdrop/alt/keymaps/xulkal/rules.mk, users/xulkal/custom_rgb.h
=> Added Xulkal ALT Keymap

keyboards/dz60/keymaps/calbatr0ss/keymap.c
- Set default layer to macOS
- Updated comment graphic to match longer spacebar on the left side
- Add RGB toggle as a FN key
- Set Windows and macOS layers to the W and M keys, respectively
=> update calbatr0ss layout to enhance layer functionality, change default layout to macOS, and add RGB toggle

util/travis_utils.sh
Introduced in #7038, it seems we now have issues with:
1. PRs from a master branch build everything all the time 
While @noroadsleft is looking into better solutions, (and im currently exploring alternative CI solutions and porting over the build logic to GitHub Actions), I figured it best to put back some of the old behaviour.
=> CI - Revert to previous logic for branch name and changes

util/macos_install.sh
Also switching to the same tap as avr-gcc.
*
=> Update ARM GCC in macOS install script to 8.3

keyboards/helix/readme.md
=> add lkb as a seller of helix pcbs outside of japan

docs/feature_debounce_type.md
=> Update debounce docs

layouts/community/ortho_4x12/jotix/keymap.c
=> capslock_led

keyboards/nafuda/config.h, keyboards/nafuda/info.json, keyboards/nafuda/keymaps/default/config.h, keyboards/nafuda/keymaps/default/keymap.c, keyboards/nafuda/keymaps/default/readme.md, keyboards/nafuda/nafuda.c, keyboards/nafuda/nafuda.h, keyboards/nafuda/readme.md, keyboards/nafuda/rules.mk
Add Nafuda keyboard.
A 7 keys keyboard.
Salicylic-acid3
*
=> [Keyboard] Add keyboard Nafuda

docs/feature_tap_dance.md
A bit of tap dance explanations 😊
=> #5346 Explain Tap Dance interruption

docs/documentation_templates.md
=> Doc fix to conform with #7221

drivers/haptic/DRV2605L.c, drivers/haptic/haptic.c, drivers/haptic/haptic.h, quantum/backlight/backlight_avr.c, quantum/config_common.h, quantum/dip_switch.c, quantum/encoder.c, quantum/keymap_extras/keymap_italian.h, quantum/keymap_extras/keymap_italian_osx_ansi.h, quantum/keymap_extras/keymap_italian_osx_iso.h, quantum/process_keycode/process_tap_dance.h, quantum/quantum.c, quantum/quantum.h, quantum/quantum_keycodes.h, quantum/rgblight.c, quantum/stm32/chconf.h, tmk_core/common/arm_atsam/suspend.c, tmk_core/common/eeconfig.c, tmk_core/common/host.c, tmk_core/common/led.h, tmk_core/protocol/arm_atsam/usb/usb_protocol_hid.h, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/iwrap/iwrap.c, tmk_core/protocol/lufa/adafruit_ble.cpp
Following on from #7386, this PR fixed up core files missed by clang-format.
=> Run clang-format manually to fix recently changed files

docs/faq_debug.md
=> Modified the description about setting debug_enable in `docs/faq_debug.md`.

docs/feature_rgblight.md
=> Fix typo and code indentation

keyboards/dztech/dz60rgb_wkl/dz60rgb_wkl.h, keyboards/dztech/dz60rgb_wkl/keymaps/default/keymap.c
fix malposition combile in config.qmk.fm
=> dz60rgb_wkl malposition fix

bin/qmk, docs/cli_development.md, lib/python/kle2xy.py, lib/python/qmk/cli/compile.py, lib/python/qmk/cli/config.py, lib/python/qmk/cli/doctor.py, lib/python/qmk/cli/flash.py, lib/python/qmk/cli/json/keymap.py, lib/python/qmk/cli/kle2json.py, lib/python/qmk/cli/list/keyboards.py, lib/python/qmk/cli/pytest.py, lib/python/qmk/keymap.py, lib/python/qmk/path.py, requirements.txt, setup.cfg
This will mark CI as bad if it doesn't pass flake8 in addition to the tests we run currently.
=> Add flake8 to our test suite and fix all errors

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other_issues.md, .github/stale.yml
So we can mark stuff as solved without bot being stupid.
=> Change label for stale bot

keyboards/kyria/readme.md
I've configured a new portal for my documentation, and as such the Kyria build guide now has a new location. I wasn't able to put a permanent redirect in place, so I've changed the link in the readme.
*
=> Updated Kyria readme.md with relocated build guide

keyboards/planck/keymaps/dsanchezseco/keymap.c
=> added rgblight controls to planck keymap

keyboards/keebio/bdn9/keymaps/hbbisenieks/keymap.c, keyboards/keebio/iris/keymaps/hbbisenieks/config.h, keyboards/keebio/iris/keymaps/hbbisenieks/keymap.c, keyboards/keebio/iris/keymaps/hbbisenieks/readme.md, keyboards/keebio/iris/keymaps/hbbisenieks/rules.mk
=> Adding hbbisenieks keymap for keebio/iris

docs/translating.md
Fix simple mistake in docs/translating.md
=> Fix link in docs/translating.md

docs/feature_leader_key.md, docs/feature_macros.md, docs/feature_userspace.md, keyboards/kmac/keymaps/default/keymap.c, keyboards/kmac/keymaps/default_tkl_ansi/keymap.c, keyboards/kmac/keymaps/default_tkl_ansi_wkl/keymap.c, quantum/process_keycode/process_terminal.c, quantum/quantum.h, quantum/send_string_keycodes.h, quantum/template/base/keymaps/default/keymap.c
* Moved all the sendstring modifier macros to send_string_keycodes.h and added missing right side versions
* Added `SEND_STRING_DELAY(string, interval)` to match `SEND_STRING(string)`
* Added `SS_LCTL()` to match the other macros and deprecated `SS_LCTRL()`
*
=> Send string keycode tweaks

.github/stale.yml
=> Fix typos in stale.yml

quantum/quantum.c
functional equivalence, less code. I've tested this on an AN-C. Need to test it on a split with RGB.
Remove common boilerplate, migrate code into a different functionally equivalent switch while maintaining backwards compatibility
- hoist the keypress detection
- remove nesting
- commonality among ifdefs
*
=> clean up quantum.c

quantum/encoder.c
Revert encoder fix until I can resolve the phantom presses
*
=> Revert split encoder fixes until able to repro a better fix

users/stanrc85/stanrc85.c
Convert "compile and flash" macro to use new QMK CLI 
Removed some unused code and cleaned up send_string commands
*
=> Userspace updates

keyboards/planck/keymaps/callum/keymap.c, keyboards/planck/keymaps/callum/readme.md
Rearranged symbol layer based on a more robust model than last time.
=> [keymap] personal keymap tweaks

util/macos_install.sh
osx-cross updated their `arm-gcc-bin` formula to GCC 9. Now 8.3.1 is available as `arm-gcc-bin@8`.
*
=> Specify Arm GCC 8 in macOS install script

keyboards/ut472/keymaps/hvp/config.h, keyboards/ut472/keymaps/hvp/keymap.c, keyboards/ut472/keymaps/hvp/readme.md, keyboards/ut472/keymaps/hvp/rules.mk
Keymap to be used with Eurkey for easy access to Swedish characters on the #first layer.
Links:
- https://eurkey.steffen.bruentjen.eu/
* NA
=> Added my UT47.2 Swedish layout with tap dance function.

keyboards/keebio/iris/keymaps/jhelvy/README.md, keyboards/keebio/iris/keymaps/jhelvy/config.h, keyboards/keebio/iris/keymaps/jhelvy/keymap.c, keyboards/keebio/iris/keymaps/jhelvy/rules.mk, keyboards/lily58/keymaps/jhelvy/README.md, keyboards/lily58/keymaps/jhelvy/config.h, keyboards/lily58/keymaps/jhelvy/keymap.c, keyboards/lily58/keymaps/jhelvy/rules.mk
Added jhelvy folder and related keymap files to keebio/iris and lily58 folders
*
=> Added jhelvy keymaps for keebio/iris and lily58

bin/qmk, lib/python/qmk/cli/doctor.py, lib/python/qmk/tests/test_qmk_errors.py, requirements.txt
This will help new developers follow the proper naming conventions.
=> Add pep8-naming to our python linting

keyboards/preonic/keymaps/kjwon15/keymap.c
Recently, WS2812B support added for ARM chipset. So why not support on keymaps
* LED keys are now available
=> [preonic/kjwon15] Support led key

docs/coding_conventions_c.md, docs/coding_conventions_python.md, docs/feature_haptic_feedback.md, docs/feature_rgb_matrix.md
Grammar in coding_conventions_c.md and coding_conventions_python.md
`rule.mk` to `rules.mk` in feature_haptic_feedback.md and feature_rgb_matrix.md
* Grammar and misc. typos (filename)
=> Minor grammar and filename fixes in docs

tmk_core/protocol/iwrap/main.c
This fixes #1931, I guess.
* Fixes #1931
=> Set proper ASCII character for KC_NUHS in iWRAP code

keyboards/crkbd/keymaps/manna-harbour_miryoku/config.h, keyboards/crkbd/keymaps/manna-harbour_miryoku/keymap.c, keyboards/crkbd/keymaps/manna-harbour_miryoku/rules.mk, layouts/community/ergodox/manna-harbour_miryoku/keymap.c, layouts/community/ortho_4x12/manna-harbour_miryoku/keymap.c, users/manna-harbour_miryoku/config.h, users/manna-harbour_miryoku/manna-harbour_miryoku.c, users/manna-harbour_miryoku/miryoku.org, users/manna-harbour_miryoku/rules.mk
=> [keymap] Display logo for caps lock indication on crkbd using old OLED driver

drivers/arm/ws2812.c
Tested on f407 and f411, arm-none-eabi-gcc 6.3.1, 7.3.1 and 8.3.1.
As mentioned in #7526 and implemented in #7542, I have also aligned the use of ChibiOS defines to only uppercase.
=> Enable bitbang ws2812 for f4

keyboards/ergotravel/keymaps/yanfali/config.h, keyboards/ergotravel/keymaps/yanfali/rules.mk
Adjust rules.mk so it fits inside a pro micro sized flash.
*
=> [keymap] ergotravel updates

docs/index.html
Sidebar links 404 without this.
*
=> Fix docs fallback for pt-br

docs/proton_c_conversion.md
Added a couple of entries for some features not currently supported on Proton C.
* #7580
=> Update feature support for Proton C

docs/faq_build.md, docs/faq_debug.md, docs/faq_keymap.md, docs/fr-fr/faq_build.md, docs/fr-fr/faq_debug.md, docs/fr-fr/faq_keymap.md, docs/zh-cn/faq_build.md, docs/zh-cn/faq_debug.md, docs/zh-cn/faq_keymap.md
TBQH I think most of the stuff in these pages could be ripped out, or wordsmithed into some other existing page.
*
=> Remove some outdated FAQ items

keyboards/maxr1998/phoebe/keymaps/default/keymap.c
Sorry for the PR spam, the more I use my new board, the more issues with my keymap I discover ^^
=> [Keyboard/Phoebe] Send backslash on AltGr + ?

docs/getting_started_github.md, docs/getting_started_introduction.md
update git command and directory name of documents
docs/
getting_started_github.md
getting_started_introduction.md
*
=> update git command and directory name of documents

keyboards/exclusive/e65/keymaps/madhatter/keymap.c
A new personal keymap for E6.5
*
=> Personal keymap for the E6.5

tmk_core/protocol.mk
Backports a fix from tmk_keyboard
Fixes #7611
=> core: Fix build config in protocol.mk

docs/newbs.md
docs/newbs_best_practices.md no longer exists, so point to the new docs/newbs_git_best_practices.md.
=> Change newbs.md to link to the new newbs_git_best_practices.md instead of newbs_best_practices.md.

quantum/backlight/backlight_soft.c
Current issues:
* flicker on startup
* level 0 does not always turn off
* levels > 5 fail
* level does not seem to scale well
* Performance
* Becomes an issue when scan rate < 1000
*  `ARM split + software backlight + ws2812 bitbang = flicker`
This PR address the non performance issues, but does slightly improve flicker of some backlight levels at low scan rates.
(ignore the branch name, I'm going to stage those changes differently)
=> Software backlight improvements

keyboards/dztech/dz60rgb/v1/rules.mk, keyboards/dztech/dz60rgb/v2/rules.mk, keyboards/dztech/dz60rgb_ansi/v1/rules.mk, keyboards/dztech/dz60rgb_ansi/v2/rules.mk, keyboards/dztech/dz60rgb_wkl/v1/rules.mk, keyboards/dztech/dz60rgb_wkl/v2/rules.mk, keyboards/dztech/dz65rgb/v1/rules.mk, keyboards/dztech/dz65rgb/v2/rules.mk
=> Tidy up dztech rules.mk

docs/contributing.md, docs/index.html, readme.md
Changed the URL slightly so it goes directly to the edit page on GitHub.
*
=> Improve docs "Edit Document" footer

keyboards/fluorite/readme.md
=> I corrected my name.

docs/arm_debugging.md, docs/fr-fr/getting_started_github.md, docs/fr-fr/getting_started_introduction.md, docs/getting_started_github.md, docs/he-il/getting_started_github.md, docs/he-il/getting_started_introduction.md, docs/ja/arm_debugging.md, docs/ja/getting_started_github.md, docs/ru-ru/getting_started_github.md, docs/ru-ru/getting_started_introduction.md, docs/zh-cn/getting_started_github.md, docs/zh-cn/getting_started_introduction.md
Fix some of documentation problems.
=> [Docs] fix docs

keyboards/reviung39/keymaps/toshi0383/keymap.c, keyboards/zinc/keymaps/toshi0383/keymap.c
Minor update for my keymaps for zinc and reviung39.
=> Update toshi0383 keymap

drivers/oled/oled_driver.h
```console
zvecr@zvecr-XPS-L322X:~/Desktop/qmk_firmware$ make kyria/rev1:default:flash CTPC=yes
QMK Firmware 0.7.103
Making kyria/rev1 with keymap default and target flash
arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
Copyright (C) 2017 Free Software Foundation, Inc.
Compiling: keyboards/kyria/kyria.c                                                                  [OK]
Compiling: keyboards/kyria/rev1/rev1.c                                                              [OK]
Compiling: keyboards/kyria/keymaps/default/keymap.c …
```
=> Add backwards compatibility for oled_write_raw_P on ARM

quantum/quantum.c
https://en.wikipedia.org/wiki/Bell_character
Just a fun little detail :)
`TERMINAL_SOUND` is a single C5 note.
*
=> Make the keyboard beep when Audio is enabled and `\a` is encountered in a sendstring

keyboards/crkbd/keymaps/bcat/config.h, keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/crkbd/keymaps/bcat/rules.mk, users/bcat/config.h
Basically just my Lily58 layout with the number row chopped off. (Also, man, those SMD RGB LEDs are a PITA. But they seem to work, so yay!)
None
=> Initial Crkbd layout for bcat

docs/zh-cn/custom_quantum_functions.md
```
$ enca -g -L chinese zh-cn/custom_quantum_functions.md
Simplified Chinese National Standard; GB2312
$ enconv -L chinese -x UTF8 zh-cn/custom_quantum_functions.md
$ enca -g -L chinese zh-cn/custom_quantum_functions.md
Universal transformation format 8 bits; UTF-8
```
*
=> Fix file encoding for zh-cn/custom_quantum_functions.md

docs/ja/contributing.md
=> [Docs] Update Japanese translation

keyboards/kbdfans/kbd67/mkiirgb/keymaps/codecoffeecode/keymap.c, keyboards/kbdfans/kbd67/mkiirgb/keymaps/codecoffeecode/rules.mk
Adding a keymap for the KBDFans Kbd67 MKII RGB
*
=> Adding keymap for KBDFans Kbd67 MKII RGB

drivers/issi/is31fl3218.h, drivers/issi/is31fl3731-simple.c, drivers/issi/is31fl3731-simple.h, drivers/issi/is31fl3731.c, drivers/issi/is31fl3731.h, drivers/issi/is31fl3733.c, drivers/issi/is31fl3733.h, drivers/issi/is31fl3736.c, drivers/issi/is31fl3737.c, drivers/issi/is31fl3737.h
Only need to include the header, i2c_master and wait.h, AFAICT.
*
=> Clean up ISSI driver includes

keyboards/handwired/dactyl_manuform/5x6/keymaps/swedish/config.h, keyboards/handwired/dactyl_manuform/5x6/keymaps/swedish/keymap.c
A Dactyl Manuform layout optimized for Swedish and XMonad.
=> Dactyl manuform layout optimized for Swedish

docs/faq_build.md
Update FAQ docs for MacOS stuff
=> [Docs] Update macOS related issues in docs

keyboards/ergodox_ez/led_i2c.c, quantum/color.c, quantum/color.h, quantum/rgb_matrix_drivers.c, quantum/rgblight.c
Updates the RGBW code to actually set the white channel to something other than 0. 
* Closes #4385, supersedes that PR
=> Use White channel on RGBW LEDs

docs/ws2812_driver.md, drivers/arm/ws2812_spi.c
Taking over from #4670, with permission from @awkannan, this PR aims to implement ws2812 SPI support within the new ws2812 framework.
| | SPI1 | SPI2 | SPI3 |
|-|-|-|-|
| f072 | ? | B15 :heavy_check_mark: | ? |
| f103 | A7 :heavy_check_mark: (B5?) | B15 :heavy_check_mark: | n/a |
| f303 | A7 :heavy_check_mark: B5 :heavy_check_mark:  | B15 :heavy_check_mark: | B5 :heavy_check_mark:  (C12?) |
| f407/f411 | :x: <sub>2</sub> | :x: <sub>2</sub> | ? |
| teensy 3.2 | :man_shrugging: <sub>3</sub> | | |
1. F072 seems to have issues with SPI1
* *Could* be fixed with pending ChibiOS update
* Maybe add docs to cover scenario?
2. F4xx seems to just fails, lsusb shows no device
3. Teensy spi config is different, it compiles if you change a bunch of stuff but doesnt boot....
=> SPI DMA based RGB Underglow for STM32

tmk_core/common/action.c
Fixes wrong preprocessor syntax in action.c
*
=> Fix typo in action.c

keyboards/percent/skog/rules.mk
I missed this in https://github.com/qmk/qmk_firmware/pull/7396. It should build now.
*
=> Remove remnants of custom matrix from Skog rules.mk

docs/newbs_building_firmware.md
There is a very small typo in the docs. I'm just getting started right now and just wanted to fix it when i found it. :) 
I haven't read your CONTRIBUTING - Sorry - but if I don't create the PR now, then it wont ever happen :P
=> Fixed a small typo

docs/config_options.md
Added description of LIB_SRC to 'Build Options' section.
And LINK_TIME_OPTIMIZATION_ENABLE move to 'Build Options' section.
=> Added description of LIB_SRC to docs/config_options.md

users/rossman360/readme.md, users/rossman360/rossman360.c, users/rossman360/rossman360.h, users/rossman360/rules.mk
hopefully the beginnings of a userspace. Haven't changed any keymaps, yet.
*
=> Userspace add

keyboards/hineybush/h75_singa/h75_singa.c, keyboards/hineybush/h75_singa/rules.mk
- enable bootmagic lite
- change default RGB underglow animation
*
=> h75_singa changes

docs/ja/README.md, docs/ja/arm_debugging.md, docs/ja/cli.md, docs/ja/cli_configuration.md, docs/ja/contributing.md, docs/ja/driver_installation_zadig.md, docs/ja/faq.md, docs/ja/faq_debug.md, docs/ja/faq_general.md, docs/ja/faq_keymap.md, docs/ja/getting_started_getting_help.md, docs/ja/getting_started_github.md, docs/ja/getting_started_introduction.md, docs/ja/newbs.md, docs/ja/newbs_building_firmware_configurator.md, docs/ja/newbs_flashing.md, docs/ja/newbs_getting_started.md, docs/ja/newbs_git_best_practices.md, docs/ja/newbs_git_resolving_merge_conflicts.md, docs/ja/newbs_git_resynchronize_a_branch.md, docs/ja/newbs_git_using_your_master_branch.md, docs/ja/newbs_learn_more_resources.md, docs/ja/newbs_testing_debugging.md
The Japanese documents included a sample command to check the original document changes. But there was something wrong, so I fixed it.
=> Update check commands in Japanese documents

keyboards/nk65/config.h, keyboards/tada68/rules.mk, keyboards/tada68/tada68.h, layouts/community/65_ansi/yanfali/keymap.c
- fix quoting because of comma in config.h
- make it work with tada68 which uses an older layout macro
*
=> Add an 65_ansi community layout

keyboards/maartenwut/wasdat/config.h, keyboards/maartenwut/wasdat/readme.md, keyboards/maartenwut/wasdat/rules.mk, keyboards/maartenwut/wasdat/wasdat.h
Changed PID to first four chars of SHA1 of `PRODUCT`. Aligned config, rules and readme to match current template.
*
=> Update Wasdat config

docs/breaking_changes.md
=> Update Breaking Changes doc timeline

keyboards/kbdfans/kbd67/mkii_soldered/readme.md, keyboards/kbdfans/kbd67/mkiirgb/readme.md, keyboards/kbdfans/kbd67/mkiirgb/v1/readme.md, keyboards/kbdfans/kbd67/mkiirgb/v2/readme.md, keyboards/kbdfans/kbd67/readme.md
This PR has no logic change. Though my sentences may have questionable logic. 
We've had quite a few people not sure which firmware to use for what board. Hopefully these notes will help guide people to flashing .bin files and .hex files on the appropriate boards.
=> KBD67 MKII Notes Update

keyboards/handwired/promethium/config.h, keyboards/uk78/config.h
These two aren't parsed quite correctly in https://api.qmk.fm/v1/usb.
* 
- x ] My code follows the code style of this project.
=> Fix a couple of USB VIDs for the API

keyboards/keebio/iris/keymaps/sethBarberee/config.h, keyboards/keebio/iris/keymaps/sethBarberee/rules.mk
Enable LTO and guard RGBLED_SPLIT
Should be merged before #7754 as it'll fix my keymap issues
*
=> Update my iris keymap for LTO and rgbled split

keyboards/model01/keymaps/dshields/keymap.c, keyboards/planck/keymaps/dshields/keymap.c
=> [Keymap] Add additional dynamic macro key to dshields keymaps.

keyboards/jj50/keymaps/abstractkb/config.h, keyboards/jj50/keymaps/abstractkb_gergomatch/config.h, keyboards/jj50/keymaps/abstractkb_gergomatch/keymap.c, keyboards/jj50/keymaps/abstractkb_gergomatch/readme.md
Changed jj50 keymaps for myself
These changes were made 8 months ago so not sure what has changed since then.  May need to make more changes to fit in with current rules.
*
=> Updated keymaps

keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md, layouts/community/60_ansi_split_bs_rshift/bcat/keymap.c, layouts/community/60_ansi_split_bs_rshift/bcat/readme.md, layouts/community/60_tsangan_hhkb/bcat/keymap.c, layouts/community/60_tsangan_hhkb/bcat/readme.md
Just some rehab of my split ergo keymaps, and some minor tweaking of secondary layers in my 60% keymaps to stay roughly consistent.
None
=> Personal keymap updates for the new year

keyboards/keebio/levinson/readme.md
Updates the example make commands in the Levinson readme to
`keebio/levinson/...`  instead of `levinson/...`
Also updated the example to rev3 (the current version of the board)
=> Update Levinson Readme to reflect changes to directory structure

keyboards/xelus/dawn60/config.h
Place in `VIA_EEPROM_CUSTOM_CONFIG_SIZE` and clean up defines.
**URGENT since the bug breaks the functionality of the board**
* Dawn60 VIA EEPROM clobbering keymap EEPROM
=> Dawn60 bug fix [URGENT]

layouts/community/65_ansi/mechmerlin/keymap.c, layouts/community/65_ansi/mechmerlin/readme.md, layouts/community/65_ansi/mechmerlin/rules.mk
Just putting in my community keymap
=> Merlin's LAYOUT_65_ansi keymap

keyboards/nk65/config.h, keyboards/nk65/rules.mk
Enable bootmagic as default!
*
=> NK65 Bootmagic lite for default

docs/coding_conventions_python.md
=> Add a section on python tests to the python coding conventions

keyboards/hhkb/keymaps/xyverz/keymap.c, layouts/community/60_hhkb/xyverz/keymap.c
=> Hhkb keymap

docs/_summary.md, docs/custom_matrix.md, docs/getting_started_make_guide.md
There were no real docs on CUSTOM_MATRIX, so this PR aims to cover #7863 and the existing functionality.
Might need some wordsmithing...
=> Add docs for 'CUSTOM_MATRIX = lite'

keyboards/maartenwut/wasdat/matrix.c, keyboards/maartenwut/wasdat/rules.mk
Taking advantage of the new custom matrix lite to dedupe some of this matrix code.
*
=> Wasdat matrix cleanup

docs/feature_oled_driver.md
Improving code examples, aligning tables, and a spot of wordsmithing.
*
=> Misc cleanups for OLED documentation

keyboards/getta25/rev1/config.h
This keyboard was submitted before, and merged after, my `DIODE_DIRECTION` PR went in. So Travis didn't pick up on it.
*
=> Add DIODE_DIRECTION to Getta25

keyboards/montsinger/rebound/keymaps/rossman360/keymap.c, users/rossman360/rossman360.h
=> adding personal rebound keymap

keyboards/nk65/config.h
Same here as: https://github.com/qmk/qmk_firmware/pull/7968
*
=> NK65 EEPROM size fix

keyboards/maxr1998/phoebe/config.h, keyboards/maxr1998/phoebe/keymaps/default/keymap.c, keyboards/maxr1998/phoebe/phoebe.c
=> [Keymap] Phoebe keymap improvements

keyboards/crkbd/keymaps/curry/keymap.c, users/curry/process_records.h, users/curry/wrappers.h
Small formatting changes to my userspac, key swap based on preference.
=> Minor Userspace Changes

keyboards/tmo50/config.h, keyboards/tmo50/keymaps/via/keymap.c, keyboards/tmo50/keymaps/via/readme.md, keyboards/tmo50/keymaps/via/rules.mk, keyboards/tmo50/rules.mk, keyboards/tmo50/tmo50.h
Add VIA keymap and clean up rules.mk a little.
With permission from @emiilsd 
*  VIA support added
=> Add VIA support to TMO50

docs/cli.md, lib/python/qmk/cli/doctor.py, lib/python/qmk/questions.py, lib/python/qmk/submodules.py
* Move OS specific checks to the top
* Prompt to install packages if dependencies aren't found
* Check the status of submodules, prompt if they're not there
* Add new `--yes` and `--no` arguments
* Two new additions to the QMK python library-
* `qmk.submodule` - Get the status of and update the submodules
* `qmk.questions` - Functions for getting information from users
=> Beef up how `qmk doctor` works.

docs/_summary.md, docs/breaking_changes_instructions.md
Wrote a doc for instructing users on what to expect for Breaking Change PRs.
=> Add Breaking Change PR Instructions doc

keyboards/clueboard/66/rev4/config.h, keyboards/clueboard/66/rev4/rev4.c, keyboards/clueboard/66/rev4/rules.mk
Reverts qmk/qmk_firmware#7942
Something about this PR breaks the V4.5 PCB, I don't know what yet. Confirmed with a .bin I downloaded from configurator. This should be reverted until we figure out what caused it to break.
=> Revert "Clueboard Rev4 Updates aka Volcano 660"

keyboards/maxr1998/pulse4k/info.json, keyboards/maxr1998/pulse4k/keymaps/default/keymap.c, keyboards/maxr1998/pulse4k/pulse4k.c
This should fix the configurator support for this macro pad, I think.
=> Fix Pulse4k info.json LAYOUT name

keyboards/hs60/v2/ansi/keymaps/stanrc85/keymap.c, keyboards/kingly_keys/romac/keymaps/stanrc85/rules.mk, layouts/community/60_ansi/stanrc85-ansi/keymap.c, users/stanrc85/rules.mk
Added PGUP and PGDN to keymaps
Enable VIA in userspace for 1up60hse, DZ60, and Romac
*
=> Userspace and keymap updates

keyboards/ogre/ergo_single/config.h, keyboards/ogre/ergo_single/ergo_single.c, keyboards/ogre/ergo_single/ergo_single.h, keyboards/ogre/ergo_single/keymaps/default/keymap.c, keyboards/ogre/ergo_single/keymaps/default/readme.md, keyboards/ogre/ergo_single/readme.md, keyboards/ogre/ergo_single/rules.mk, keyboards/ogre/ergo_split/config.h
=> Adds ogre ergo single

keyboards/ckeys/thedora/readme.md
Updates cKeys/theDora README.md with explicit flashing instructions -- how to enter bootloader mode, and resetting controller.
* N/A
=> Updates cKeys/theDora README with explicit flashing instructions

keyboards/ergoslab/rev1/rules.mk, keyboards/getta25/rev1/rules.mk, keyboards/treadstone48/rev1/rules.mk
Travis is currently spitting out
```console
1598.04s$ bash util/travis_build.sh
Making default keymaps for all keyboards
Makefile:560: keyboards/ergoslab/rev1/rules.mk: No such file or directory
Makefile:560: keyboards/getta25/rev1/rules.mk: No such file or directory
Makefile:560: keyboards/treadstone48/rev1/rules.mk: No such file or directory
Making 1upkeyboards/1up60hse with keymap default                                                       [OK]
```
Longer term, there may be a better solution addressing the root cause. (Note: this was not visible on <http://compile.qmk.fm/v1/keyboards/error_log>)
=> Patch up 'Makefile:560: <kb>/rev1/rules.mk: No such file or directory'

keyboards/kbdfans/kbd75/readme.md, keyboards/winkeyless/bmini/readme.md, keyboards/winkeyless/readme.md
I was sent a KBD75 Round 1 PCB for porting from Bootmapper Client to QMK. Backstory is that the user had tried to no avail, the rev1 and rev2 firmwares. After consultation with me, we discovered that the board was not supported in QMK. 
In the middle of matrix tracing, I recognized the switch matrix. It's the same one as the Winkeyless.kr B.mini. 
This PR has no code change and is just an update of the documentation pointing other potential users who own Round 1 or Round 2 of the KBD75 PCB to the correct sources.
=> Documentation: KBD75

message.mk
Since LUFA is now a submodule, this message does not just apply to ChibiOS.
*
=> Update dirty submodule make message

lib/python/qmk/cli/hello.py, lib/python/qmk/questions.py
This adds new functionality to the `qmk.questions` module:
* Adds a validate argument to `question()` so that developers can validate answers
* Adds a new `choice()` function for selecting options from a list
=> Improve the functionality of qmk.questions

keyboards/lfkeyboards/lfkpad/config.h, keyboards/lfkeyboards/lfkpad/info.json, keyboards/lfkeyboards/lfkpad/keymaps/default/config.h, keyboards/lfkeyboards/lfkpad/keymaps/default/keymap.c, keyboards/lfkeyboards/lfkpad/keymaps/default/readme.md, keyboards/lfkeyboards/lfkpad/lfkpad.c, keyboards/lfkeyboards/lfkpad/lfkpad.h, keyboards/lfkeyboards/lfkpad/readme.md, keyboards/lfkeyboards/lfkpad/rules.mk
Not touching the custom RGB code right now... but it's got a 3731 so should be easy to migrate.
*
=> LFKPad refactor

docs/config_options.md, docs/feature_split_keyboard.md, keyboards/crkbd/rev1/split_util.c, keyboards/helix/rev2/split_util.c, quantum/split_common/split_util.c
The first of a few rounds of "speeding up" slave detection.
Hopefully over time this value will hone in to a less reserved value, rather than the overly pessimistic initial value that was chosen.
I have also reduced the poll time, and made it configurable, to further help with detection speed.
=> Reduce SPLIT_USB_TIMEOUT by 500ms

keyboards/kbdfans/kbd67/mkiirgb/keymaps/via/keymap.c, keyboards/kbdfans/kbd67/mkiirgb/keymaps/via/rules.mk, keyboards/kbdfans/kbd67/mkiirgb/v1/config.h, keyboards/kbdfans/kbd67/mkiirgb/v2/config.h
Add the VIA keymap and change vendor id to something thats not hopefully been used yet. I picked "KB".
=> VIA Support: KBD67 mkii v1/v2

docs/keycodes.md, docs/quantum_keycodes.md
Also reworded the descriptions for `RESET` and `EEP_RST`, to hopefully clarify their function.
*
=> Move Grave Escape, Lock and Leader keycodes into their own sections

keyboards/lily58/keymaps/yshrsmz/config.h, keyboards/lily58/keymaps/yshrsmz/keymap.c, keyboards/lily58/keymaps/yshrsmz/rules.mk
=> add lily58 yshrsmz keymap

.github/workflows/cli.yml, lib/python/qmk/tests/test_cli_commands.py, util/travis_test.sh
Convert the testing of CLI to GitHub Actions.
=> CI: Add workflow for CLI testing

lib/python/qmk/cli/flash.py
I've noticed that the `qmk flash` command was not updated and ignores the user's config.
This simple PR fixes it.
*
=> Update the flash cli command to use the user config

message.mk
In anticipation of size check support for Arm.
*
=> Use FIRMWARE_FORMAT for "Checking file size" message

docs/config_options.md, docs/ja/config_options.md, docs/porting_your_keyboard_to_qmk_(arm_and_other_chibios_cpus).md
=> Align max backlight level in docs

quantum/split_common/matrix.c
While scoping some future work, migrating more common logic from the two core `matrix.c` to `matrix_common.c`, a few differences were noticed.
The differences are mostly minor, but i figured it better to keep the files in step where possible.
=> Align split_common/matrix.c with matrix.c

keyboards/coseyfannitutti/mysterium/rules.mk
Adds support for tkl_ansi community layout to Mysterium keyboard by @coseyfannitutti. Tested with default keymaps and layouts/community/tkl_ansi keymaps.
*
=> Add community layout support to Mysterium

drivers/boards/GENERIC_STM32_F072XB/board.c, drivers/boards/GENERIC_STM32_F072XB/board.h, drivers/boards/GENERIC_STM32_F072XB/board.mk, drivers/boards/GENERIC_STM32_F072XB/cfg/board.chcfg, drivers/boards/GENERIC_STM32_F072XB/cfg/board.fmpp
ChibiOS upgrade means these board files need a little update here and there. These are still the default board files, with the name and `enter_bootloader_mode_if_requested` patch applied.
=> Update generic f072 board files in line with ChibiOS v19.1.3

docs/feature_backlight.md, quantum/backlight/backlight_arm.c
Needed for #8176.
Testing has shown that backlight has started working somewhere along the way from when support was initially added. A few Discord users have also reported success, but figured it worth transitioning from error to message (and at a later date, remove the message altogether).
=> Convert f072 backlight build error to message

keyboards/dztech/dz60rgb_ansi/keymaps/via/keymap.c, keyboards/dztech/dz60rgb_ansi/keymaps/via/rules.mk, keyboards/dztech/dz60rgb_ansi/v1/config.h, keyboards/dztech/dz60rgb_ansi/v2/config.h
Adding VIA support for DZ60RGB ANSI V1 and V2. 
One annoying thing is that I had to change the V2 PID to be 1221, which is already taken by another dztech board. When I get to the others I'll start changing them.
=> VIA Support: DZ60RGB ANSI V1/V2

docs/ja/cli.md
Update Japanese translation of cli.md
=> [Docs] Update Japanese translation of cli.md

keyboards/mxss/mxss_frontled.c, keyboards/mxss/rgblight.c, keyboards/mxss/rgblight.h
Slight tweak to some of the front LED keycode handlers to improve operation
=> MxSS RGB Handler Touchup

keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md
Just getting a last few key locations dialed in for my Crkbd and Lily58. :)
None.
=> Move Grave/Tilde and some lesser used keys on my ergo boards

quantum/keymap_extras/keymap_danish.h, quantum/keymap_extras/sendstring_danish.h
=> Add Danish keymap and sendstring LUT

quantum/send_string_keycodes.h
Allows something like `SEND_STRING("QMK is the best thing ever!" SS_TAP(X_MS_BTN1));`
* Mouse keycode range exist within the 0xFF range used by register_code
* SEND_STRING backing code uses register_code
* register_code has magic handling for mouse keycodes
=> Add mouse support to SEND_STRING

keyboards/gingham/config.h, keyboards/gingham/matrix.c, keyboards/gingham/rules.mk
In light of fixing vusb's timer. A small update on Gingham to use:
- Bootmagic light.
- Custom matrix light.
- Unused define in config.h
*
=> Gingham Update

keyboards/hub16/keymaps/default/keymap.c, keyboards/hub16/keymaps/no_mod/keymap.c
Removing of some bugs found during keyboard use, along with cleaning up code and adding better documentation and examples in keymap.
*
=> Hub16 - Bug removal + clean up code

lib/python/qmk/cli/doctor.py
My last "fix" was a bit too effective at detecting macOS
=> Fixed OS detection such that OSX doesn't take over the world

keyboards/acheron/austin/chconf.h, keyboards/acheron/austin/halconf.h
Updates the `acheron/austin` files to new ChibiOS config format, as it got added after the upgrade branch got merged.
*
=> Upgrade acheron/austin to ChibiOS 19.1.3.

keyboards/wete/chconf.h, keyboards/wete/halconf.h
Update wete to support ChibiOS 19.1.3.
*
=> Upgrade wete to ChibiOS 19.1.3.

tmk_core/chibios.mk
Saves a little extra space (about 1~2k with the limited testing I've done so far) to avoid the impact of #8269.
=> Switch to nano specs on ChibiOS builds

.gitmodules
=> Track master branches for lib/chibios, lib/chibios-contrib, lib/ugfx.

quantum/quantum.c
This was meant to be removed as part of #7008... not sure why it didn't survive the future rebases.
*
=> Remove duplicate BRTG case

keyboards/cannonkeys/savage65/keymaps/via/rules.mk, keyboards/cannonkeys/tmov2/keymaps/via/rules.mk
Rules.mk fixes for VIA support in Savage65 and TMOv2
*
=> Make a fix to savage65 and tmov2 for via

keyboards/cannonkeys/satisfaction75/config.h
Between the last time I flipped these pins and now, it seems like encoder behavior might have changed again.
This fixes the pins to make clockwise recognized as clockwise in the code.
*
=> Get the direction right on the S75 encoder

keyboards/keebio/iris/keymaps/via/keymap.c, keyboards/keebio/iris/rev4/rev4.h
Adds encoder functionality to encoder on right half of VIA keymap.
*
=> Update encoder functions for Iris VIA keymap

quantum/keymap_extras/keymap_hungarian.h, quantum/keymap_extras/sendstring_hungarian.h
=> Update Hungarian keymap and add sendstring LUT

keyboards/ai03/equinox/keymaps/crd/keymap.c, keyboards/ai03/equinox/keymaps/crd/readme.md
just add a simple keymap for the equinox
*
=> [keymaps] Add crd's equinox keymap

keyboards/atreus/keymaps/ibnuda/config.h, keyboards/atreus/keymaps/ibnuda/rules.mk, keyboards/handwired/dactyl_manuform/4x5/keymaps/ibnuda/config.h, keyboards/handwired/dactyl_manuform/4x5/keymaps/ibnuda/keymap.c, users/ibnuda/combo.c, users/ibnuda/combo.h, users/ibnuda/config.h, users/ibnuda/ibnuda.c, users/ibnuda/ibnuda.h, users/ibnuda/readme.md, users/ibnuda/rules.mk, users/ibnuda/tapdance.c, users/ibnuda/tapdance.h, users/ibnuda/wrapper.h
created a user space to ease maintenance for some boards that i use.
- created user space for ibnuda.
- changed ibnuda's atreus keymap.
- added ibnuda's dactyl manuform 4x5 keymap.
*
=> new userspace for @ibnuda

keyboards/1upkeyboards/super16/super16.c
=> [Keyboard] Forget to ifdef Super16 led config

keyboards/donutcables/budget96/config.h
There are 18 LEDs, not 16
When QMK is applied only 16 LEDs light up. The bottom left and left middle do not light up.
=> Update config.h - Fixed number of RGB LEDs

keyboards/dichotomy/config.h, keyboards/dichotomy/dichotomy.c, keyboards/dichotomy/dichotomy.h, keyboards/dichotomy/keymaps/beat/config.h, keyboards/dichotomy/keymaps/beat/keymap.c, keyboards/dichotomy/matrix.c
Adding a keymap for the Dichotemy keyboard.
=> Dichotomy keymap by beat

docs/tap_hold.md
Correct typo: "reasonal" to "reasonable"
=> Correct typo in tap_hold.md

keyboards/m10a/config.h, keyboards/m10a/keymaps/default/keymap.c, keyboards/m10a/keymaps/via/config.h, keyboards/m10a/keymaps/via/keymap.c, keyboards/m10a/keymaps/via/rules.mk
Added VIA keymap for Ramaworks M10-A
This intentionally leaves the original code unchanged.
=> Added VIA keymap for Ramaworks M10-A

keyboards/matrix/noah/boards/noah_bd/board.mk, keyboards/matrix/noah/config.h, keyboards/matrix/noah/halconf.h, keyboards/matrix/noah/matrix.c, keyboards/matrix/noah/mcuconf.h, keyboards/matrix/noah/noah.c, keyboards/matrix/noah/rules.mk
upgrade board configurations to the latest chibios and fixed  #8259
*  fixes #8259
=> fixed #8259

quantum/keymap_extras/keymap_norwegian.h, quantum/keymap_extras/sendstring_norwegian.h
=> Update Norwegian keymap and add sendstring LUT

tmk_core/common/action_layer.c
`biton32` isn't necessarily the correct call here.
=> Fix layer debug calls

keyboards/illuminati/is0/keymaps/default/keymap.c
Replaced tab indentation with space in `keyboards/illuminati/is0/keymaps/default/keymap.c` to conform to style guide.
*
=> Replace tab indentation with spaces in is0 default keymap.

docs/index.html, docs/qmk_custom_dark.css
=> Fix up dark mode rendering.

quantum/keymap_extras/keymap_spanish.h, quantum/keymap_extras/sendstring_spanish.h
=> Update Spanish keymap and sendstring LUT

quantum/keymap_extras/keymap_swedish.h, quantum/keymap_extras/sendstring_swedish.h
=> Update Swedish keymap and add sendstring LUT

keyboards/keyhive/maypad/rules.mk
This board uses a Pro Micro, so it should have Caterina set as default.
*
=> Fix bootloader for Maypad

docs/feature_stenography.md
Link to new Learn Plover google site in the Stenography docs.
* the old `ploverdoc` link for Learn Plover led to a google site where every page only contained a link to `learnplover` - better to link to the new site directly. 
- tested the updated link with `qmk docs`
=> Update link for Learn Plover google site

docs/other_eclipse.md
fix typo in docs/other_eclipse.md
*  #7408
=> fix two links on docs/other_eclipse.md

util/msys2_install.sh
When the path (usually containing the username) contains a space, this fails.
*
=> msys2_install.sh: wrap requirements.txt in quotes

quantum/keymap_extras/keymap_plover.h
=> Update Plover keymap

quantum/keymap_extras/keymap_norman.h, quantum/keymap_extras/sendstring_norman.h
=> Update Norman keymap and sendstring LUT

quantum/keymap_extras/keymap_slovenian.h, quantum/keymap_extras/sendstring_slovenian.h
=> Update Slovenian keymap and add sendstring LUT

quantum/keymap_extras/keymap_belgian.h, quantum/keymap_extras/sendstring_belgian.h
=> Update Belgian keymap and sendstring LUT

keyboards/converter/sun_usb/type5/keymaps/sigma/rules.mk, users/sigma/sigma.c
handle unicode input properly.
*
=> fix sigma keymaps build

quantum/keymap_extras/keymap_french.h, quantum/keymap_extras/sendstring_french.h
=> Update French keymap and sendstring LUT

quantum/keymap_extras/keymap_german.h, quantum/keymap_extras/sendstring_german.h
=> Update German keymap and sendstring LUT

docs/adc_driver.md, drivers/arm/analog.c, drivers/arm/analog.h, keyboards/handwired/onekey/keymaps/adc/config.h, keyboards/handwired/onekey/keymaps/adc/keymap.c, keyboards/handwired/onekey/keymaps/adc/rules.mk
Working through a few things while ironing out the scope of what needs to be updated
Tested on
* F072
* F103
* F303
* F401
=> ARM - ADC cleanup

keyboards/lazydesigners/dimple/keymaps/via/keymap.c
In #8447 I did not noticed that the new function @fauxpark recommended changed, the returned value is `bool` instead of `void`.
*
=> Fix Dimple VIA keymap

tmk_core/avr.mk, tmk_core/chibios.mk
Legacy behaviour. We can re-implement in cli in a more generic way if the dependency is required again.
=> Remove qmk archive generation

quantum/keymap_extras/keymap_uk.h, quantum/keymap_extras/sendstring_uk.h
=> Update UK keymap and sendstring LUT

users/alfrdmalr/alfrdmalr.h
Swap position of `@` and `#` characters in SYMBOL layer.
*
=> swap # and @ symbols

quantum/keymap_extras/keymap_dvp.h, quantum/keymap_extras/sendstring_dvp.h
=> Update Programmer Dvorak keymap and add sendstring LUT

keyboards/handwired/onekey/keymaps/i2c_scanner/config.h, keyboards/handwired/onekey/keymaps/i2c_scanner/keymap.c, keyboards/handwired/onekey/keymaps/i2c_scanner/readme.md, keyboards/handwired/onekey/keymaps/i2c_scanner/rules.mk
Aiming to provide a more qmk friendly version of https://playground.arduino.cc/Main/I2cScanner/
Thrown in onekey to take advantage of its hardware folder structure (I can move if strong feelings against this).
=> [Keymap] I2C scanner

keyboards/ergodox_stm32/rules.mk, keyboards/handwired/bluepill/bluepill70/rules.mk, keyboards/jm60/rules.mk
=> Set MCU for some F103 boards

quantum/keymap_extras/keymap_swedish.h
=> Fix missing deprecated keycodes for keymap_swedish

quantum/keymap_extras/keymap_jp.h, quantum/keymap_extras/sendstring_jis.h
=> Update JIS keymap and sendstring LUT

tmk_core/common/action.c, tmk_core/common/action_code.h
Literally nothing using this, and... it does nothing, too.
*
=> Remove ACT_COMMAND

tmk_core/common/report.h
Turning some defines into enums so they look a little nicer, and also added some comments for the desktop/consumer usages. No behaviour changes.
*
=> Tidy up report.h

docs/newbs_getting_started.md
It seems to be important to make sure `pacman` has no updates available before attempting to set up QMK. Also made it a bit clearer that the terminal to be using is the MingW64 one, not the MSYS one.
Another note: `python3-pip` will install the msys Python 3.7, when we really want `mingw-w64-x86_64-python3-pip` - except that `pip install qmk` fails when trying to install `coverage`. `qmk_install.sh` works fine last I checked, so it probably has something to do with the fact that `base-devel` or `mingw-w64-x86_64-toolchain` is installed first.
*
=> Update newbs installation procedure for MSYS2

tmk_core/common/report.h
Looks like I put the comment on the wrong line...
*
=> Fix formatting for report.h

docs/feature_rgblight.md
Fixes an issue with the Lighting Layers documentation example, [reported](https://github.com/qmk/qmk_firmware/pull/7768#pullrequestreview-378899437) by @mkylama.
Also some file linting.
=> [Docs] Fixes for feature_rgblight.md

common_features.mk
The randomness within this file has been bugging me for ages. While there might be a better long term solution, I figure it could use some sort of ordering. Some driver stuff near other drivers, some keycode stuff near other keycode logic.
=> Reorder logic within common_features.mk

quantum/keymap_extras/keymap_finnish.h, quantum/keymap_extras/sendstring_finnish.h
=> Add Finnish keymap and sendstring LUT

quantum/keymap_extras/keymap_icelandic.h, quantum/keymap_extras/sendstring_icelandic.h
=> Add Icelandic keymap and sendstring LUT

quantum/keymap_extras/keymap_czech.h, quantum/keymap_extras/sendstring_czech.h
=> Add Czech keymap

quantum/keymap_extras/keymap_irish.h
🇮🇪
Pretty much identical to the UK keymap, but with the addition of a dead acute accent on AltGr+`'`.
*
=> Add Irish keymap

docs/ja/contributing.md
Update Japanese translation of contributing.md
=> [Docs] Update Japanese translation of contributing.md

docs/ja/keymap.md
Update Japanese translation of keymap.md
=> [Docs] Update Japanese translation of keymap.md

docs/ja/flashing.md
Update Japanese translation of flashing.md
=> [Docs] Update Japanese translation of flashing.md

docs/ja/custom_quantum_functions.md
Update Japanese translation of custom_quantum_functions.md
=> [Docs] Update Japanese translation of custom_quantum_functions.md

docs/feature_rgb_matrix.md
Like the title says. This explicitly lists the available functions for the RGB matrix feature, in the documentation page, because if it's not documented, it doesn't exit.
=> [Docs] Update RGB Matrix docs with function refs

docs/hardware_keyboard_guidelines.md
I couldn't find the description of loading order of config.h files in the documents, so I added it.
=> added the description of the reading order of the config.h files.

quantum/keymap_extras/keymap_croatian.h, quantum/keymap_extras/sendstring_croatian.h
=> Add Croatian keymap

quantum/keymap_extras/keymap_estonian.h, quantum/keymap_extras/sendstring_estonian.h
=> Add Estonian keymap

keyboards/projectkb/alice/keymaps/stanrc85/keymap.c, users/stanrc85/rules.mk
Added Alice keymap and rules to userspace files
*
=> [keymap] Add Alice keymap and to userspace files

drivers/oled/oled_driver.c, quantum/rgblight.c, tmk_core/common/progmem.h
So i am well aware that my solution probably isn't up to standards - neither code nor modularity nor DRY principles - i don't normally work with C, but had a bug that made the layers stuff useless. I fixed this for my working version and would just, as a friendly gesture, provide you guys with the solution. I hope you can possibly guide me to a better way of fixing the bug (maybe by importing the correct header, or something else)
I also want to say that this introduces a warning, which i had to ignore, but it works fine. 
I hope you can help me help you, and hopefully i can learn something in the go.
* Fixes #8381
=> fixed problem with implicit declaration in quantum/rgblight.c

bin/qmk, lib/python/qmk/cli/doctor.py, lib/python/qmk/commands.py, lib/python/qmk/tests/test_cli_commands.py
Now I can fully setup and work with qmk_firmware on an MSYS2
installation without any errors or exceptions.
*
=> CLI: More MSYS2 fixes

docs/hardware_keyboard_guidelines.md
As with #8545, add an explanation of the loading order of `rules.mk` to the documentation.
=> added the description of the reading order of the rules.mk files.

quantum/audio/song_list.h
Added "**State Anthem of the Soviet Union**" to [quantum/audio/song_list.h](https://github.com/qmk/qmk_firmware/blob/master/quantum/audio/song_list.h)
*
=> Added USSR anthem.

keyboards/converter/usb_usb/hasu/rules.mk
Verified by duoshock on #8611.
* Fixes #8611
=> Fix hasu usb converter bootloader

docs/ja/config_options.md
Update Japanese translation of config_options.md
=> [Docs] Update Japanese translation of config_options.md

docs/ja/cli_commands.md
Add Japanese translation of cli_commands.md
=> [Docs] Add Japanese translation of cli_commands.md

docs/newbs_getting_started.md
`qmk` is not available in the official Arch repositories. It is in the AUR, this install command will work if user has `yay` installed.
=> Change Arch qmk install command in newbs_getting_started.md

quantum/keymap_extras/keymap_slovak.h, quantum/keymap_extras/sendstring_slovak.h
=> Add Slovak keymap and sendstring LUT

keyboards/coseyfannitutti/romeo/config.h, quantum/config_common.h, quantum/quantum.c, tmk_core/protocol/lufa/lufa.h, util/activate_msys2.sh, util/activate_wsl.sh
Just some stuff that doesn't really warrant individual PRs.
*
=> Miscellaneous cleanups

quantum/config_common.h, quantum/mcu_selection.mk, tmk_core/common/avr/bootloader.c, tmk_core/common/avr/timer.c
Prerequisite for #8598. I've intentionally left out bootloader stuff as that will be in a 2nd pass.
=> Initial support for ATtiny85

keyboards/wilba_tech/wt60_d/wt60_d.c, keyboards/wilba_tech/wt69_a/wt69_a.c
Added Caps Lock LED handler to wilba.tech PCBs
*
=> Added Caps Lock LED handler to wilba.tech PCBs

layouts/community/ortho_4x12/jotix/keymap.c, layouts/community/ortho_4x4/jotix/keymap.c, layouts/community/ortho_4x4/jotix/readme.md
=> jotix layouts

users/stanrc85/config.h, users/stanrc85/rgblight_layers.c, users/stanrc85/rules.mk
Update to use some of the new RGB Layer code on Alice PCB.
*
=> [Keymap] Userspace update Rgb layers code

keyboards/2_milk/2_milk.c, keyboards/2_milk/2_milk.h, keyboards/2_milk/config.h, keyboards/2_milk/info.json, keyboards/2_milk/keymaps/copypasta/keymap.c, keyboards/2_milk/readme.md, keyboards/pancake/config.h, keyboards/pancake/feather/config.h, keyboards/pancake/info.json, keyboards/pancake/pancake.c, keyboards/pancake/pancake.h, keyboards/pancake/promicro/config.h, keyboards/pancake/readme.md
=> Fix spaceman naming

keyboards/cannonkeys/devastatingtkl/rules.mk
Messed up a suggestion on #8209... now stuff does not compile. Well done me.
=>  Fix compile issues with devastatingtkl

keyboards/kbdfans/kbd8x_mk2/readme.md
Previous link led to a 404, this one links to the product page.
=> Fix broken KBD8X MKII Hardware link

keyboards/yushakobo/quick7/readme.md
=> Fix quick7 build command

users/stanrc85/rules.mk
Small update to userspace rules to match new alice/rev1 naming.
*
=> Update userspace rules for alice/rev1

build_json.mk
Load keymap-level rules.mk when compiling keymap.json
*
=> Load keymap-level rules.mk when compiling keymap.json

docs/proton_c_conversion.md
=> Document the Proton C pins for manual Pro Micro conversion

bin/qmk, docs/cli.md, docs/cli_development.md, docs/coding_conventions_python.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/cformat.py, lib/python/qmk/cli/doctor.py, lib/python/qmk/cli/json2c.py, lib/python/qmk/cli/kle2json.py, lib/python/qmk/cli/new/keymap.py, lib/python/qmk/keymap.py
We used to support Python 3.5 or later. This bumps us to supporting Python 3.6 or later.
*
=> Move everything to Python 3.6

quantum/keymap_extras/keymap_italian_osx_ansi.h, quantum/keymap_extras/keymap_italian_osx_iso.h, quantum/keymap_extras/sendstring_italian_osx_ansi.h, quantum/keymap_extras/sendstring_italian_osx_iso.h
=> Update Italian macOS keymaps and add sendstring LUTs

.github/workflows/cli.yml
Seems they fixed the submodule issues, initial results seem to be 50% faster checkouts (17% faster overall).
=> Update cli CI checkout to v2

docs/_summary.md, docs/syllabus.md
Inspired by a conversation on discord I put together a syllabus for QMK. This can be used by people who want to learn QMK but aren't sure about what the right path to follow is.
=> Add a syllabus to guide people who are learning QMK

keyboards/kbdfans/kbd67/mkii_soldered/config.h, keyboards/kbdfans/kbd67/mkii_soldered/keymaps/via/keymap.c, keyboards/kbdfans/kbd67/mkii_soldered/keymaps/via/rules.mk
Add VIA keymap to the soldered version of the KBD67mkii. 
Tested by Bogwitch Brie on the KBDFans discord.
=> [Keyboard] VIA Support: KBD67mkii SOLDERED

keyboards/preonic/keymaps/elisiano/keymap.c
The enter key works as shift when held down
* None
=> Updated personal preonic keymap

docs/syllabus.md, docs/tap_hold.md, tmk_core/common/action.c
Fixing some minor typos I came across while working through my own personal keymap. The docs are really great overall!
* N/A
=> [Docs] Fixed minor typos

keyboards/reversestudio/decadepad/decadepad.c
=> Fixing DecadePad Numlock LED Bug

docs/ja/feature_encoders.md
Add a Japanese translation of docs/feature_encoders.md.
*
=> [Docs] Japanese translation of docs/feature_encoders.md

docs/feature_encoders.md, docs/ja/feature_encoders.md
Change the sample code in feature_encoders.md a little.
=> fix sample code indent in feature_encoders.md

util/linux_install.sh
Without these, `qmk setup` will continuously prompt to run qmk_install.sh.
*
=> Add missing packages to Linux install scripts

keyboards/maartenwut/wasdat_code/config.h, keyboards/maartenwut/wasdat_code/keymaps/via/keymap.c, keyboards/maartenwut/wasdat_code/keymaps/via/rules.mk, keyboards/maartenwut/wasdat_code/wasdat_code.h
Also adds more backlight levels to the Wasdat Code.
*
=> Add VIA support for Wasdat Code

keyboards/cospad/config.h
Changed it for myself, but just seems logical to me that this should be the default for everyone 🤷‍♂️
=> Changed default RGBLIGHT_SLEEP for cospad

keyboards/7skb/keymaps/salicylic/keymap.c, keyboards/7skb/rev1/config.h
The number of LED is changed from 5 to 6 on one side.
DEVICE_VER was changed to a number with no duplicates.
*
=> Correction of the number of LEDs and DEVICE_VER

docs/unit_testing.md
Update wording of sentence in Tracing Variables
Removed the second "for" in the sentence "This works for both for
variables ..."
*
=> Edit Unit Testing Documentation

docs/internals_gpio_control.md, quantum/quantum.h
for AVR and chibios
sometimes all one needs to debug a (timing) issue is a well placed 'togglePin' :-)
=> add 'togglePin' convenience function

keyboards/xd75/keymaps/buzzlighter1/readme.md
=> Improve buzzlighter1 readme formatting

docs/index.html
* Fixes #8983
* Fixes link within keyboard readme
=> Add redirect for old getting started links

keyboards/ergodox_stm32/keymaps/default/keymap.c, keyboards/infinity60/keymaps/jpetermans/keymap.c, keyboards/keebio/nyquist/keymaps/danielhklein/keymap.c, keyboards/planck/keymaps/ishtob/keymap.c, keyboards/sentraq/s60_x/keymaps/ansi_qwertz/keymap.c, layouts/community/ergodox/kastyle/keymap.c
Some assorted things that didn't warrant their own migration PRs.
*
=> Migrate miscellaneous `fn_actions` entries

keyboards/tgr/910/config.h
To fix the vendor ID and product ID fo VIA support https://github.com/qmk/qmk_firmware/pull/8985
*
=> Update TGR 910 config.h

.gitmodules
Fork all our submodules to protect against upstream repos disappearing.
*
=> Switch to qmk forks for everything

keyboards/atreus/keymaps/xyverz/config.h, keyboards/kinesis/keymaps/xyverz/keymap.c, keyboards/kinesis/keymaps/xyverz/readme.md
Minor changes to Dvorak layout with readme.md updates to match.
*
=> Kinesis update

keyboards/helix/pico/config.h, keyboards/helix/rev1/config.h, keyboards/helix/rev2/config.h
Change the vendor ID and product ID.
*
=> Changed the VID/PID for Helix keyboards

keyboards/tgr/910/keymaps/via/keymap.c, keyboards/tgr/910/keymaps/via/rules.mk, keyboards/tgr/910/readme.md
VIA pull request: https://github.com/the-via/keyboards/pull/118
*
=> Add TGR-910 VIA support

docs/feature_hd44780.md
The referenced site was moved.
=> Docs: fix links in feature_hd44780.md

keyboards/eniigmakeyboards/ek87/rules.mk
=> Updated rules.mk to allow for audio control in VIA for ek87

quantum/keymap_extras/keymap_canadian_multilingual.h, quantum/keymap_extras/sendstring_canadian_multilingual.h
=> Update Canadian Multilingual keymap and add sendstring LUT

quantum/keymap_extras/keymap_neo2.h
Not much point adding more than just the unshifted keycode aliases or a sendstring LUT, as some of the necessary characters are only reachable through holding `KC_CAPS`/`KC_NUHS` which are not chainable.
*
=> Update Neo2 keymap

keyboards/crkbd/ssd1306.c
optimize crkbd/ssd1306.c for size. reduce compiled binary size 292 bytes
optimize crkbd/ssd1306.c for size. reduce compiled binary size 292 bytes
*
=> optimize source code for size. reduce compiled binary size 292 bytes

layouts/community/ergodox/j3rn/keymap.c, layouts/community/ergodox/j3rn/readme.md
Just an update to my custom keymap
- Add top-left sleep key
- Change top-left `Tab` to `Esc` to force muscle memory retraining
- Add home-row hold-modifiers
* None
=> Update j3rn keymap

docs/keymap.md
Revised the layer transparency paragraph based on feedback from this [issue](https://github.com/qmk/qmk_firmware/issues/9048)
Resolves #9048
*
=> Clarify layer transparency keymap.md

keyboards/maxr1998/pulse4k/config.h, keyboards/maxr1998/pulse4k/keymaps/default/keymap.c, keyboards/maxr1998/pulse4k/keymaps/maxr1998/keymap.c, keyboards/maxr1998/pulse4k/pulse4k.c, keyboards/maxr1998/pulse4k/pulse4k.h
Some small tweaks to my Pulse4k macro pad code. Should be more customizable now, cleaned up the code while I was at it, also added my new personal keymap.
I'd appreciate if you could merge this as rebase, and not squash the commits, as they're kinda independent.
=> [Pulse4k] Keyboard tweaks, personal keymap

keyboards/gergo/keymaps/abstractkb/config.h, keyboards/gergo/keymaps/abstractkb/keymap.c, keyboards/gergo/keymaps/abstractkb/readme.md, keyboards/gergo/keymaps/abstractkb/rules.mk, keyboards/keebio/bfo9000/keymaps/abstractkb/keymap.c
Added my personal gergo keymap
*
=> added my gergo keymap

docs/ja/feature_thermal_printer.md
Add a Japanese translation of docs/feature_thermal_printer.md.
*
=> [Docs] Japanese translation of docs/feature_thermal_printer.md

util/msys2_install.sh
This makes me sad, but it has to be done :(
*
=> MSYS2 install: bodge out avrdude package installation for USBaspLoader

keyboards/ymdk/ymd09/config.h, keyboards/ymdk/ymd09/keymaps/via/keymap.c, keyboards/ymdk/ymd09/keymaps/via/rules.mk, keyboards/ymdk/ymd09/rules.mk
Update to the YMD09 to add Via support to the keyboard as well the additional keymap needed for Via.
* Update to have VIA support
=> Add Via support to the YMD09

docs/_summary.md, docs/getting_started_docker.md
Looks like in the recent-ish docs reorg, the docker docs were lost. This PR adds them back, slightly reworked to fit in alongside some of the other alternative build environments.
* Fixes #9076
=> Reintegrate previous docker docs

lib/python/qmk/cli/doctor.py
Fix this conflicting and erroneous output:
```
Submodule %s is not up to date!
Ψ Submodules are up to date.
```
*
=> Fix submodule check

docs/newbs_flashing.md
Moved the "Put Your Keyboard into DFU (Bootloader) Mode" section up so it is not skipped over. Also updated the example Toolbox output and did a little wordsmithing.
* Fixes #9074
=> newbs_flashing.md: place bootloader instructions before Toolbox intro

quantum/split_common/split_util.c
While in the area, i have also cleaned up the logic so that non LUFA avr boards can just implement `is_keyboard_master`.
(cb4a64e6c5013091c8864366320874f9114625c5 was added just to check compile issues, it can be removed if required)
* Partially fixes #8592
=> Use LUFA funcs for split_util

Makefile, Vagrantfile
* The current Makefile examples include `make planck:default`.  Since the planck no longer has a top-level rules.mk, and they are instead squirreled away in the respective revision, we should amend this example to prevent misleading people into using this example.
=> Remove broken example from Makefile

keyboards/kyria/keymaps/asapjockey/config.h, keyboards/kyria/keymaps/asapjockey/keymap.c, keyboards/kyria/keymaps/asapjockey/rules.mk, keyboards/kyria/keymaps/default/rules.mk
These change add a keymap for a customer, and make some changes to my own keymap. These are purely keymap changes and do not contain any other additions.
*
=> Kyria: Updated personal keymap, added asapjockey's keymap

lib/python/qmk/cli/doctor.py
If any of the submodules are missing or out-of-date, report the error
and present the user the oppurtunity to fix it.
*
=> CLI: Rework submodule checking

docs/feature_split_keyboard.md, docs/proton_c_conversion.md, docs/serial_driver.md
Now that #7072 and #7987, i've given a pass over the docs to hopefully help clarify the current situation.
=> Update ARM split keyboard docs

quantum/split_common/split_util.c
=> Fix ChibiOS split build.

keyboards/handwired/k8split/README.md, keyboards/handwired/k8split/config.h, keyboards/handwired/k8split/k8split.c, keyboards/handwired/k8split/k8split.h, keyboards/handwired/k8split/keymaps/default/keymap.c, keyboards/handwired/k8split/keymaps/left/config.h, keyboards/handwired/k8split/keymaps/left/keymap.c, keyboards/handwired/k8split/keymaps/right/config.h, keyboards/handwired/k8split/keymaps/right/keymap.c, keyboards/handwired/k8split/rules.mk
Adding my personal split keyboard for easy maintiaining and reflashing with new qmk firmware, I added under `handwired/` as its a non production thing without any drops or sales (besides ordering the pcb manually).
=> New Keyboard: k8split

layouts/community/60_tsangan_hhkb/dohmain/keymap.c, layouts/community/60_tsangan_hhkb/dohmain/readme.md
=> dohmain 60_tsangan_hhkb layout

drivers/eeprom/eeprom_spi.c
=> Fix SPI EEPROM compile issue when Console is enabled

keyboards/kbdfans/kbd67/rev1/config.h, keyboards/kbdfans/kbd67/rev1/keymaps/via/keymap.c, keyboards/kbdfans/kbd67/rev1/keymaps/via/readme.md, keyboards/kbdfans/kbd67/rev1/keymaps/via/rules.mk
Add VIA support for kbdfans/kbd67/rev1
*
=> Add VIA support for kbd67rev1

keyboards/helix/rev2/keymaps/yshrsmz/config.h, keyboards/helix/rev2/keymaps/yshrsmz/keymap.c, keyboards/helix/rev2/keymaps/yshrsmz/rules.mk
I've updated my keymap file for helix.
Basically I've copied & pasted from default keymap and then changed some keymap
*
=> update helix/rev2:yshrsmz keymap

keyboards/handwired/onekey/keymaps/default_json/keymap.json, keyboards/handwired/onekey/pytest/templates/keymap.c, lib/python/qmk/cli/json2c.py, lib/python/qmk/tests/test_cli_commands.py, lib/python/qmk/tests/test_qmk_keymap.py
This went under the radar for too long (since the Python 3.6 move) due to not having any test cases.
So now we have for this subcommand.
*
=> CLI: fix `json2c` subcommand and add/fix tests

lib/python/qmk/cli/compile.py, lib/python/qmk/keymap.py
Looks like the last fix wasn't quite right and only worked in limited circumstances.
*
=> Fix the path for generated keymaps

docs/_summary.md, docs/reference_keymap_extras.md
=> Documentation for keymap_extras

keyboards/projectkb/alice/alice.c
Keyboard pre initialization code for LED pins.
*
=> Fix projectkb/alice LED indicator

quantum/keymap_extras/keymap_belgian.h
BE_J was defined as KC_K instead of KC_J.
cf.
```
* ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
* │ ² │ & │ é │ " │ ' │ ( │ § │ è │ ! │ ç │ à │ ) │ - │       │
* ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
* │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ $ │     │
* ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
* │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ ù │ µ │    │
* ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
* │    │ < │ W │ X │ C │ V │ B │ N │ , │ ; │ : │ = │          │
* ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
* │    │    │    │                        │    │    │    │    │
* └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
```
=> BE_J should map to KC_J

docs/reference_keymap_extras.md
> This is because Belgium is predominantly bilingual
cf. https://en.wikipedia.org/wiki/AZERTY#Differences_between_the_Belgian_and_French_layouts_of_the_AZERTY_keyboard
*
=> `French (Belgium)` was missing

keyboards/primekb/prime_e/config.h, keyboards/primekb/prime_e/keymaps/via/keymap.c
Mentioned by `@Sterenke#4838 ` on Discord. As its quite a small board, we can squeeze a few extra layers in here.
=> Prime_E - Increase number of via layers

keyboards/kyria/keymaps/plattfot/README.md, keyboards/kyria/keymaps/plattfot/config.h, keyboards/kyria/keymaps/plattfot/keymap.c, keyboards/kyria/keymaps/plattfot/rules.mk
Keymap for the [Kyria keyboard](https://splitkb.com/) with programming, writing in both English and Swedish and easy navigate a tiling window manager in mind.
See README.md for more info.
=> [Keymap] plattfot - Kyria layout

keyboards/mechlovin/infinityce/rules.mk
Actice NKRO function
Actice NKRO function
Thanks!
*
=> Infinity CE PCB: Update rules.mk

keyboards/the_royal/liminal/config.h
=> Fixing the PRODUCT_ID to match the liminal.json on VIA repo

keyboards/mechlovin/adelais/adelais.c, keyboards/mechlovin/adelais/rules.mk
Fix indicator LED pinout, active some function
Num lock LED Pinout C12 -> C15.
Enable NKRO, Console and command.
Thanks!
*
=> Adelais: Fix indicator LED pinout

util/linux_install.sh
#5526 was just a month too early: https://github.com/void-linux/void-packages/commit/0c4fa0b92a6a4ac0dece3b2b94874cc6de862bc3
Thanks to @Liebach
Tested this in a VM, `planck/rev6:default` compiles. 
*
=> Void Linux: Switch to cross-arm-none-eabi toolchain

layouts/community/ortho_4x12/jotix/keymap.c
=> jotix ortho_4x12 layout

keyboards/percent/canoe/keymaps/dhertz/keymap.c, keyboards/percent/canoe/readme.md
Use the new function for user init!
=> Update canoe:dhertz to use new post-init functions

quantum/quantum.c, quantum/split_common/matrix.c, tmk_core/common/keyboard.c
Removes another small portion of the fragmentation within split_common.
=> Move encoder_read to common location

keyboards/tada68/keymaps/abishalom/keymap.c, keyboards/tada68/keymaps/abishalom/readme.md, keyboards/tada68/keymaps/abishalom/rules.mk
=> Changes to abishalom Tada68 keymap

docs/ja/newbs_git_best_practices.md, docs/ja/newbs_git_resolving_merge_conflicts.md, docs/ja/newbs_git_resynchronize_a_branch.md, docs/ja/newbs_git_using_your_master_branch.md
* Checked again that docs/ja/newbs_git_*.md is up to date.
* The original document reference has been changed to 0.9.0.
=> [Update] Japanese translation of docs/newbs_git_*.md

keyboards/maartenwut/eon40/keymaps/via/keymap.c, keyboards/maartenwut/eon40/keymaps/via/rules.mk
Adds VIA support for the Eon40 PCB.
*
=> Add VIA support for Eon40

docs/ja/newbs_testing_debugging.md
Updated the Japanese translation of newbs_testing_debugging.md to 0.9.0.
```shell
git diff ed0575fc8 0.9.0 -- docs/newbs_testing_debugging.md
```
=> [Update] Japanese translation of docs/newbs_testing_debugging.md.

docs/ja/newbs_learn_more_resources.md
Updated the Japanese translation of newbs_learn_more_resources.md to 0.9.0.
=> [Update] Japanese translation of newbs_learn_more_resources.md

keyboards/projectkb/alice/alice.c
Update code to fix projectkb alice indicators
*
=> Fix project alice indicators

keyboards/planck/keymaps/callum/keymap.c, keyboards/planck/keymaps/callum/readme.md
=> [keymap] upstreaming a minor keymap update

keyboards/hub16/config.h, keyboards/hub16/keymaps/default/keymap.c, keyboards/hub16/readme.md
- Fix bug where modifier was not sent with key due to tap dance implementation
- Fix typos
*
=> Hub16 keymap bugfix

keyboards/alu84/rules.mk, keyboards/amj40/rules.mk, keyboards/ckeys/nakey/rules.mk, keyboards/fc660c/rules.mk, keyboards/gh80_3000/rules.mk, keyboards/handwired/magicforce61/rules.mk, keyboards/handwired/not_so_minidox/rules.mk, keyboards/handwired/onekey/blackpill_f401/rules.mk, keyboards/handwired/onekey/blackpill_f411/rules.mk, keyboards/handwired/woodpad/rules.mk, keyboards/katana60/rules.mk, keyboards/knops/mini/rules.mk, keyboards/kona_classic/rules.mk, keyboards/mt40/rules.mk, keyboards/noxary/268/rules.mk, keyboards/omnikey_bh/rules.mk, keyboards/paladin64/rules.mk, keyboards/primekb/prime_r/rules.mk, keyboards/sx60/rules.mk, keyboards/toad/rules.mk, keyboards/uk78/rules.mk, keyboards/wilba_tech/zeal60/rules.mk, keyboards/xmmx/rules.mk
=> Change ?= to = in keyboard rules.mk

keyboards/planck/keymaps/dcompact/keymap.c, keyboards/planck/keymaps/dcompact/readme.md
Adding a Game mode layer to my keymap on the Planck
*
=> Implement game mode layer for dcompact on planck

keyboards/hotdox/config.h, keyboards/hotdox/keymaps/via/config.h, keyboards/hotdox/keymaps/via/keymap.c, keyboards/hotdox/keymaps/via/rules.mk
I adjusted the VENDOR_ID and PRODUCT_ID in the config.h file of the keyboard's base directory such that they are unique. Further, the config.h in the /via subdirectory contains instructions of the maximum layer count VIA requires. Lastly, the keymap.c in the /via subdirectory is an adjusted copy of the default keymap.c with the three additional layers specifically assigned KC_TRANS codes so as to avoid them being populated randomly when not used. I did not delete any of the additional code or inline documentation present in the default keymap, so that once mouse layers and media keys are supported by VIA, those can easily be found and re-added to this keymap. Rules.mk enable VIA as well as disable currently unsupported features, mitigating errors due to those yet unsupported features. …
=> added VIA support for HotDox

keyboards/keebio/iris/keymaps/dcompact/config.h, keyboards/keebio/iris/keymaps/dcompact/keymap.c, keyboards/keebio/iris/keymaps/dcompact/readme.md
Adding a new implementation of my keymap (dcompact) for the Iris keyboard.
*
=> Dcompact for iris

keyboards/clawsome/gamebuddy/config.h, keyboards/clawsome/gamebuddy/gamebuddy.c, keyboards/clawsome/gamebuddy/gamebuddy.h, keyboards/clawsome/gamebuddy/info.json, keyboards/clawsome/gamebuddy/keymaps/default/keymap.c, keyboards/clawsome/gamebuddy/readme.md, keyboards/clawsome/gamebuddy/rules.mk
A 26-key macropad with a focus on gaming
*
=> GameBuddy macropad

keyboards/keebio/quefrency/rev1/rules.mk
https://github.com/qmk/qmk_configurator/issues/751
=> Enable Mousekeys for Keebio Quefrency rev1

docs/ja/faq_debug.md, docs/ja/flashing.md, docs/ja/getting_started_vagrant.md
The TAGs pointing to the original text has been updated to facilitate future verification.
* docs/ja/flashing.md
* docs/ja/faq_debug.md
* docs/ja/getting_started_vagrant.md
=> [Update] Files with Japanese translations related to #8822

docs/feature_encoders.md
There was no description of what ENCODER_RESOLUTION, just an explanation of how to define it. I'm adding a rough description of what ENCODER_RESOLUTION does.
*
=> Adding information to feature_encoders.md

docs/newbs_getting_started.md
Adding `--needed --noconfirm` flags to prevent pacman redownloading any already installed packages, and showing the prompt for package selection (`There are 17 members in group mingw-w64-x86_64-toolchain`). Plus `--disable-download-timeout` just in case.
*
=> Update newbs MSYS2 pacman instructions

docs/ja/cli_configuration.md, docs/ja/driver_installation_zadig.md, docs/ja/feature_audio.md, docs/ja/feature_auto_shift.md, docs/ja/feature_bluetooth.md, docs/ja/feature_tap_dance.md, docs/ja/getting_started_make_guide.md, docs/ja/hardware_avr.md, docs/ja/hardware_drivers.md
* Check again that the following files are up to date.
* docs/ja/cli_configuration.md
* docs/ja/driver_installation_zadig.md
* docs/ja/feature_audio.md
* docs/ja/feature_auto_shift.md
* docs/ja/feature_bluetooth.md
* docs/ja/feature_tap_dance.md
* docs/ja/hardware_avr.md
* docs/ja/hardware_drivers.md
* docs/ja/getting_started_make_guide.md
* The original document reference has been changed to 0.9.0.
=> [Update] Change Original TAGs of Japanese translations 

docs/ja/hardware_keyboard_guidelines.md
Changes in #8545 and #8566 have been reflected in the Japanese translation.
=> [Update] Japanese Translation of docs/hardware_keyboard_guidelines.md

docs/ja/feature_pointing_device.md
=> [Docs] fix indentation

keyboards/mixi/config.h, keyboards/mixi/keymaps/default/keymap.c, keyboards/mixi/keymaps/default/readme.md, keyboards/mixi/keymaps/via/keymap.c, keyboards/mixi/mixi.c, keyboards/mixi/readme.md
Updates on Mixi default keymaps and fixes on configuration
- fixed wrong pins for rotary encoder
- added pins for second rotary encoder
- fixed RGB not turned on at initialization
- changed default keymap on second layer to improve functionality
- changed via keymap (follows the default keymap)
- updated front page image and default keymap image
*
=> Updates on Mixi default keymaps and fixes on configuration

drivers/issi/is31fl3741.c, drivers/ws2812.h, quantum/process_keycode/process_ucis.c, quantum/process_keycode/process_unicode_common.c, quantum/process_keycode/process_unicodemap.c, quantum/rgb_matrix_drivers.c
=> `qmk cformat`

docs/ja/faq_build.md
Updated the Japanese translation of faq_build.md to 0.9.0.
=> [Update] Japanese Translation of  docs/faq_build.md

layouts/community/ortho_4x12/jotix/keymap.c
=> add_adjust_layer

docs/documentation_best_practices.md
=> [Docs] fix file path

layouts/community/ortho_4x12/jotix/config.h, layouts/community/ortho_4x12/jotix/keymap.c
=> tap toggle to lower layer

keyboards/jisplit89/readme.md, keyboards/jisplit89/rev1/config.h
1.Update the URL and photos in the build guide.
2.Changed the number of LEDs.
*
=> [Update]JISplite89 Readme and LED nums

docs/ja/documentation_templates.md
Add a Japanese translation of docs/documentation_templates.md.
*
=> [Docs] Japanese translation of docs/documentation_templates.md

keyboards/xd004/readme.md
I can find no documentation on The Internet _specifically_ for this board, particularly around how to get it into DFU mode. There is some fairly shoddy generic XD-series documentation in Google Drive, but it's not a lot of help. In the end, I took an educated guess and lucked out, so I thought it'd be worthwhile documenting the DFU process to save others a lot of stress in the future.
I'm not sure if the ASCII-art is acceptable, but it does help describe the text a bit better.
No formal Github issues, but there's always been a lack of documentation for this board.
=> Added DFU instructions for XD004 board

docs/ja/compatible_microcontrollers.md
Add a Japanese translation of docs/compatible_microcontrollers.md.
*
=> [Docs] Japanese translation of docs/compatible_microcontrollers.md

keyboards/xd87/info.json, keyboards/xd87/keymaps/mac_underglow/keymap.c, keyboards/xd87/xd87.h
XD87 failed to pass qmk info check. I've fixed it and updated info.json for this keyboard.
*
=> XD87 qmk info fixes

keyboards/botanicalkeyboards/fm2u/fm2u.h, keyboards/botanicalkeyboards/fm2u/info.json, keyboards/botanicalkeyboards/fm2u/keymaps/default/keymap.c, keyboards/botanicalkeyboards/fm2u/keymaps/via/keymap.c
@noroadsleft 
Configurator (and actually, `qmk info`) didn't like the extra layouts being defined as simple aliases. The silly sizes work now :)
I also tweaked the naming a little.
*
=> Fix layouts for FM2U

docs/feature_ps2_mouse.md, tmk_core/protocol/ps2_mouse.c, tmk_core/protocol/ps2_mouse.h
Process mouse movement in the keymap before it is sent to the host.  Example uses include filtering noise, adding acceleration, and automatically activating a layer.  To use, define the following function in your keymap: 
void ps2_mouse_moved_user(report_mouse_t *mouse_report);
*
=> Add movement hook to ps2_mouse

docs/feature_backlight.md
- Aligned tables
- Deduped a bunch of info (eg. config defines)
- Reorganised headings and added IDs for translation
- Added example schematic
Could probably do with a nice picture of a board with backlight like the underglow docs have, but I'm using blank black PBT caps so it doesn't look that great on camera. And I'd need to clean the dust out of it...
*
=> Backlight docs wordsmithing

keyboards/rotr/info.json, keyboards/rotr/keymaps/default/keymap.c, keyboards/rotr/readme.md
Updated README and default keymap
*
=> Rotr - Updated README and default keymap

docs/reference_glossary.md
* 
- [x ] I have updated the documentation accordingly.
=> fixed link to Eclipse instructions

users/stanrc85/rules.mk
Add Alice rev2 to my userspace rules.mk
*
=> Add Alice rev2 to my userspace

keyboards/jian/keymaps/via/keymap.c, keyboards/jian/keymaps/via/rules.mk, keyboards/jian/nsrev2/config.h, keyboards/jian/rev2/config.h, keyboards/jian/rules.mk
=> Add jian qmk_via layout and LTO_ENABLE to all jian revs

docs/faq_build.md
Instead of modifying the service file provided by the distro,
use drop-in functionaly to explicitly specify the policy.
*
=> Docs: update ModemManager recommendation

keyboards/aos/tkl/config.h
One line `config.h` change to limit the maximum LED brightness value to 50, to better suit the LED setup on the board. Tested on a pre-production PCB.
N/A
=> Reduce peak LED brightness for AoS TKL

keyboards/planck/keymaps/abishalom/config.h, keyboards/planck/keymaps/abishalom/keymap.c, keyboards/planck/keymaps/abishalom/readme.md, keyboards/planck/keymaps/abishalom/rules.mk
=> Created abishalom keymap

users/pcoves/.gitignore, users/pcoves/combo.c, users/pcoves/config.h, users/pcoves/pcoves.c, users/pcoves/pcoves.h, users/pcoves/rainbowUnicorn.c, users/pcoves/rainbowUnicorn.h, users/pcoves/readme.md, users/pcoves/rules.mk, users/pcoves/tapDance.c, users/pcoves/tapDance.h, users/pcoves/unicode.c, users/pcoves/unicode.h
Add the userspace I've been using for month.
=> Add pcoves's userspace

keyboards/planck/keymaps/callum/keymap.c, keyboards/planck/keymaps/callum/readme.md, keyboards/planck/keymaps/callum/rules.mk
Just upstreaming some keymap changes. :)
=> [keymap] curly quotes

keyboards/4pplet/steezy60/rev_a/config.h
Similar to #8115  #8150 #9022
MATRIX_COLS is wrongly defined larger than it should be.
=> [Keyboard] Fix inconsistent MATRIX_COLS: 4pplet/steezy60

keyboards/rart/rartpad/keymaps/default/keymap.c, keyboards/rart/rartpad/keymaps/numpad/keymap.c, keyboards/rart/rartpad/keymaps/via/keymap.c, keyboards/rart/rartpad/keymaps/via/rules.mk
add via support and add reset for default and numpad keymaps
*
=> RARTPAD : add support via

quantum/rgb_matrix_drivers.c
This should be a pointer, as that is what the function expects.
* Self Testing. Found this when testing ... another bug with the RGBW strip that I have.  Simple fix.
=> Fix RGB Matrix using RGBW WS2812 LEDs

keyboards/preonic/keymaps/kjwon15/keymap.c
Make it possible to ctrl+click on mouse layer
* Fix doesn't responding from booting/wake up from sleeping
=> [Keyboard] Update preonic/Kjwon15 layout

quantum/keymap_extras/keymap_canadian_multilingual.h
I justed fixed a keycode that I needed that used the wrong modifier. :)
*
=> Fixed CA_DOTA key code

docs/isp_flashing_guide.md
Correct the fuses for Caterina, and make the `:production` command more obvious.
* Discord
=> [Docs] Update ISP Guide

keyboards/hhkb/ansi/matrix.c, keyboards/hhkb/jp/matrix.c
ensure hhkb runs matrix_init_quantum
eeprom wasn't being restored on init, this fixes that
=> ensure hhkb runs matrix_init_quantum

docs/feature_mouse_keys.md, tmk_core/common/mousekey.c
The mousekey feature of QMK has always left out documentation regarding the function of the `KC_ACL0`, `KC_ACL1`, and `KC_ACL2` keys when using **Accelerated** mode. I have left their function intact, and elaborated on their function with a new mode. The **Combined** mode lets the user control all of the same aspects as **Accelerated** in addition to documenting some (slightly changed) acceleration keys.
I often found myself unsuccessfully trying to grab the edge of a window for resizing. Every now and then, an application like this comes along where the **Accelerated** mode does not allow for small enough movements. I have programmed the `KC_ACL0` key, while held, to slow the cursor (or scroll) down to a single unit step. This is the smallest allowed value, and it allows for very …
=> Implemented New MK_COMBINED Functionality

docs/ja/getting_started_github.md
Japanese documentation fix.
tag: @mtei
=> [Docs] fixed alt text for images.

keyboards/rart/rartpad/keymaps/via/keymap.c
add rotary encoder code for via keymaps
*
=> Update rartpad via keymap

keyboards/handwired/onekey/teensy_2pp/readme.md
In commit 297aad6ebd85 pins for `handwired/onekey/teensy_2pp` were changed from `B2`/`B1` to `F4`/`F5`; update `readme.md` to match that change.
=> Update handwired/onekey/teensy_2pp readme

docs/ja/config_options.md
=> [Docs] Update Japanese translation of config_options.md.

docs/ja/driver_installation_zadig.md
=> [Docs] Update Japanese translation of driver_installation_zadig.md.

docs/ja/feature_dynamic_macros.md
=> [Docs] Update Japanese translation of feature_dynamic_macros.md.

docs/ja/feature_encoders.md
=> [Docs] Update Japanese translation of feature_encoders.md.

docs/ja/_summary.md
=> [Docs] Update Japanese translation of _summary.md.

keyboards/cu80/readme.md
This is an 80% keyboard, not 60%.
*
=> Update readme.md for cu80

docs/ja/faq_build.md
=> [Docs] Update Japanese translation of faq_build.md.

docs/ja/feature_hd44780.md
=> [Docs] Update Japanese translation of feature_hd44780.md.

docs/ja/feature_userspace.md
=> [Docs] Update Japanese translation of feature_userspace.md.

docs/ja/flashing_bootloadhid.md
Add a Japanese translation of docs/flashing_bootloadhid.md.
*
=> [Docs] Japanese translation of docs/flashing_bootloadhid.md

docs/ja/custom_quantum_functions.md
=> [Docs] Update Japanese translation of custom_quantum_functions.md.

keyboards/tkc/osav2/keymaps/stanrc85/keymap.c, users/stanrc85/config.h, users/stanrc85/rgblight_layers_osa.c, users/stanrc85/rules.mk
Added keymap and configs for OSAv2 to userspace
*
=> Keymap for OSAv2

keyboards/handwired/dactyl_manuform/4x5/config.h, keyboards/handwired/dactyl_manuform/4x6/config.h, keyboards/handwired/dactyl_manuform/5x6/config.h, keyboards/handwired/dactyl_manuform/5x7/5x7.h, keyboards/handwired/dactyl_manuform/5x7/config.h, keyboards/handwired/dactyl_manuform/5x7/keymaps/via/config.h, keyboards/handwired/dactyl_manuform/5x7/keymaps/via/keymap.c, keyboards/handwired/dactyl_manuform/5x7/keymaps/via/rules.mk, keyboards/handwired/dactyl_manuform/6x6/config.h, keyboards/handwired/dactyl_manuform/config.h, keyboards/handwired/dactyl_manuform/dmote/62key/config.h
Added VIA support for the Dactyl Manuform 5x7 and fixed a capitalization issue with the avr/io & interrupt imports
* fixed a capitalization issue with the avr/io & interrupt imports for the dactyl manuform 5x7
=> Adding VIA support for Dactyl Manuform 5x7

keyboards/7skb/keymaps/via/keymap.c, keyboards/7skb/keymaps/via/readme.md, keyboards/7skb/keymaps/via/rules.mk, keyboards/7skb/rev1/config.h
-Changing the VID
-Add a keymap via
*
=> Added via support for 7sKB

keyboards/choc_taro/config.h
Change the vendor ID and product ID.
*
=> Changed the VID/PID for choc_taro keyboards.

keyboards/kbdfans/kbdpad_mk2/keymaps/via/keymap.c, keyboards/kbdfans/kbdpad_mk2/keymaps/via/rules.mk
Added new keymap for VIA support to kbdfans/kbdpad_mk2, based on default keymap.
* None
=> Add via keymap for kbdfans/kbdpad_mk2.

keyboards/gingham/keymaps/codecoffeecode/keymap.c, keyboards/gingham/keymaps/codecoffeecode/readme.md
Adding a new keymap for the Gingham through-hole keyboard.
* N/A
=> [keymap] Adding personal keymap for Gingham

docs/ja/feature_stenography.md
Add a Japanese translation of docs/feature_stenography.md.
*
=> [Docs] Japanese translation of docs/feature_stenography.md

keyboards/hineybush/physix/keymaps/via/keymap.c, keyboards/hineybush/physix/keymaps/via/readme.md, keyboards/hineybush/physix/keymaps/via/rules.mk
Added a Via-enabled keymap for LZ Physix
Via PR: https://github.com/the-via/keyboards/pull/229
*
=> Added Via-enabled keymap for Physix

docs/ja/internals_gpio_control.md
Add a Japanese translation of docs/internals_gpio_control.md.
*
=> [Docs] Japanese translation of docs/internals_gpio_control.md

docs/ja/feature_ps2_mouse.md
=> [Docs] Update Japanese translation of feature_ps2_mouse.md.

docs/ja/feature_tap_dance.md
=> [Docs] Update Japanese translation of feature_tap_dance.md.

docs/ja/internals_input_callback_reg.md
Add a Japanese translation of docs/internals_input_callback_reg.md.
*
=> [Docs] Japanese translation of docs/internals_input_callback_reg.md

docs/ja/newbs_getting_started.md
=> [Docs] Update Japanese translation of newbs_getting_started.md.

docs/other_vscode.md
fix double opening `<kbd>` tags for correct formatting
expand two points for better understanding
none
=> small text and formatting fixes in vscode manual

keyboards/bm60rgb/config.h, keyboards/bm60rgb/keymaps/via/keymap.c, keyboards/bm60rgb/keymaps/via/readme.md, keyboards/bm60rgb/keymaps/via/rules.mk
- Add VIA support for bm60rgb
- Changes Vendor ID from 0xFEED to 0x4B50 (to follow VIA's guidelines)
* N/A
=> Add VIA support for bm60rgb

keyboards/coseyfannitutti/discipline/keymaps/osx/keymap.c
Adds a new layout for discipline that is more OSX friendly
*
=> Adds OSX layout with additional media keys

keyboards/craftwalk/keymaps/default/keymap.c
=> [keymap] Update default layout for craftwalk

keyboards/wheatfield/blocked65/config.h, keyboards/wheatfield/blocked65/keymaps/via/keymap.c, keyboards/wheatfield/blocked65/keymaps/via/rules.mk
Changed VID and PID, added VIA keymap.
*
=> Blocked65: add support for VIA Configurator

bootloader.mk, keyboards/ergodox_infinity/bootloader_defs.h, keyboards/ergodox_infinity/rules.mk, keyboards/infinity60/bootloader_defs.h, keyboards/infinity60/rules.mk, keyboards/k_type/bootloader_defs.h, keyboards/k_type/rules.mk, keyboards/whitefox/bootloader_defs.h, keyboards/whitefox/rules.mk, tmk_core/chibios.mk, tmk_core/common/chibios/bootloader.c
A small tidyup for the I:C boards.
*
=> Add Kiibohd bootloader type to bootloader.mk

keyboards/jian/keymaps/via/config.h, keyboards/jian/rev2/config.h
=> Add jian/keymaps/via/config.h

keyboards/handwired/swiftrax/cowfish/config.h
Change Vendor ID and Product ID 
*
=> fix handwired/swiftrax/cowfish PID and VID

util/activate_msys2.sh, util/activate_wsl.sh, util/msys2_install.sh, util/win_shared_install.sh
MSYS2 now has packages for dfu-programmer, dfu-util and teensy-loader-cli.
Next up: AVR toolchain 👍
*
=> MSYS2: install packages for dfu-programmer, dfu-util, teensy-loader-cli

keyboards/ghs/rar/rar.c
This adds caps lock and scroll lock indicator LEDs for GHS.RAR.
*
=> Add indicator LEDs for GHS.RAR

keyboards/hhkb/ansi/keymaps/shela/keymap.c
=> [keymap] Fixed an issue that long pressed alt key does not work on PSN_FN layer.

keyboards/lily58/keymaps/mikefightsbears/config.h, keyboards/lily58/keymaps/mikefightsbears/keymap.c, keyboards/lily58/keymaps/mikefightsbears/rules.mk
On May 30th breaking changes were introduced to master (#9215), this PR updates my user keymap which had been failing to compile due to that update.
No open issue
=> Update after the breaking 30 may 2020 changes

keyboards/1upkeyboards/super16/config.h, keyboards/1upkeyboards/super16/keymaps/via/keymap.c, keyboards/1upkeyboards/super16/keymaps/via/rules.mk
Added VIA support for 1upkeyboards Super16
Added the VIA keymap following the documentation. Tested with the VIA design tab.
*
=> Super16 VIA support

keyboards/mechlovin/adelais/standard_led/rules.mk
Enable RGBLIGHT for standard pcb rev2&3
*
=> Refactor Adelais PCB

keyboards/thevankeyboards/minivan/keymaps/king/keymap.c
Small changes to my minivan layout
* 
- [x ] I have added tests to cover my changes.
=> Changes to minivan layout

keyboards/cannonkeys/ortho60/config.h, keyboards/cannonkeys/ortho60/keymaps/via/keymap.c, keyboards/cannonkeys/ortho60/keymaps/via/rules.mk
Added the VIA keymap for Ortho60 
Updated the Vendor ID to match the other CannonKeys boards in config.h 
Added a VIA keymap 
*
=> Ortho60 VIA keymap

docs/feature_dynamic_macros.md
=> Fix typo in docs/feature_dynamic_macros

keyboards/atreus/keymaps/dvorak_42_key/keymap.c, keyboards/ergodox_ez/keymaps/dvorak_42_key/keymap.c
=> [keymap] dvorak_42_key layouts for atreus and ergodox_ez: add VSCode shortcuts

keyboards/cannonkeys/ortho60/keymaps/via/keymap.c
Added the license header and made the layers generic
*
=> Ortho60 via

keyboards/hineybush/h10/h10.c
add num lock indicator LED functionality to h10 PCB
*
=> add num lock indicator functionality to h10

keyboards/miuni32/keymaps/cassdelacruzmunoz/config.h, keyboards/miuni32/keymaps/cassdelacruzmunoz/keymap.c, keyboards/miuni32/keymaps/cassdelacruzmunoz/readme.md
Created a custom keymap for the Miuni32 keyboard.
* none
=> created keymap for miuni32:cassdelacruzmunoz

util/activate_msys2.sh, util/msys2_install.sh
avr-binutils, avr-gcc and avr-libc are now in MSYS2.
Marked as draft until avr-libc hits the Pacman repo - shouldn't be more than a couple days.
*
=> MSYS2: install packages for AVR toolchain

keyboards/kbdfans/kbd67/mkiirgb/mkiirgb.c
wrap rgb matrix funcs in defines
*
=> kbd67/mkiirgb - allow disabling rgb matrix

lib/python/qmk/commands.py
Came in handy when trying to figure out what the CLI was doing in https://github.com/qmk/qmk_firmware/issues/9950.
*
=> Add debug logging to `run()`

layouts/community/ortho_4x12/ddeklerk/keymap.c
Merges my 4x12 layout used on the Planck and Plaid into QMK. Originally lived on my own GitHub page.
I did not feel the need for a readme.md, as it's a fairly simple keymap.
*
=> Add ddeklerk ortho_4x12 layout

keyboards/dz60/keymaps/mrsendyyk/keymap.c, keyboards/dz60/keymaps/mrsendyyk/readme.md
Update DZ60 `readme.md` and `keymap.c`
* None
=> Update DZ60 Personal readme.md and keymap.c

keyboards/bm60rgb/keymaps/jbradforddillon/keymap.c, keyboards/bm60rgb/keymaps/jbradforddillon/readme.md
Just contributing my bm60 layout
*
=> Added bm60rgb jbd layout

keyboards/ai03/soyuz/keymaps/mrsendyyk/keymap.c, keyboards/ai03/soyuz/keymaps/mrsendyyk/readme.md
Update @ai03-2725 Soyuz `readme.md` and `keymap.c`
*
=> Update ai03 Soyuz readme.md and keymap.c

keyboards/keebio/bdn9/keymaps/ghostseven/config.h, keyboards/keebio/bdn9/keymaps/ghostseven/keymap.c
Added new keymap for Keeb.io BDN9 macro pad, including reversed direction encoders as my most recent build they were reversed. 
*
=> Keebio BDN9 Additional Keymap - Rev Encoders

keyboards/sixkeyboard/keymaps/via/keymap.c, keyboards/sixkeyboard/keymaps/via/rules.mk
Adding support for the sixkeyboard by techkeys.us
Added a new folder called via to hold the new keymap for via.
None
* 
=> Adding VIA support for sixkeyboard

keyboards/dz60/config.h, keyboards/dz60/readme.md, keyboards/readme.md
=> Update DZ60 Information

.github/workflows/info.yml
Should solve the PR lint failures eg. https://github.com/qmk/qmk_firmware/pull/7949
According to https://github.com/trilom/file-changes-action/issues/104
*
=> Update file changes action

docs/pr_checklist.md
* Reordered the list so the more common/casual stuff is up front.
* Fixed/unified some letter cases.
* Added a few items, I thought are necessary or nice to have.
*
=> Docs/PR_checklist: Reorder, unify and pet-peeves

users/stanrc85/rgblight_layers.c, users/stanrc85/rules.mk, users/stanrc85/stanrc85.c, users/stanrc85/startup_fanfare.c
Short bootup fanfare with the LED indicator lights.
*
=> [Keymap] Add indicator light bootup fanfare

keyboards/jj40/config.h
Updating both IDs, in order to attempt to add via support for the keyboard.
=> Update JJ40 VID and PID

keyboards/boardsource/4x12/keymaps/via/keymap.c, keyboards/boardsource/4x12/keymaps/via/readme.md, keyboards/boardsource/4x12/keymaps/via/rules.mk
added in keymap and rules.mk for to support via use for boardsource's 4x12 ortholinear keyboard
*
=> add via support for boardsource/4x12

keyboards/lazydesigners/bolt/via/keymap.c, keyboards/lazydesigners/bolt/via/rules.mk
Add VIA support for lazydesigners\bolt
*
=> Add VIA support for lazydesigners\bolt

keyboards/kingly_keys/romac/keymaps/boss566y/config.h, keyboards/kingly_keys/romac/keymaps/boss566y/keymap.c, keyboards/kingly_keys/romac/keymaps/boss566y/rules.mk
=> Romac Keymap with VIA and OLED Support

docs/ja/feature_split_keyboard.md
Apply #10242 changes to ja/feature_split_keyboard.md
=> [Docs] Update Japanese translation of feature_split_keyboard.md

tmk_core/avr.mk
Fixes <https://github.com/qmk/qmk_firmware/issues/10286>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qmk/qmk_firmware/10292)
=> [fix] dfu-programmer <0.7 doesn't support --force flag

docs/other_vscode.md
.vscode/c_cpp_properies.json -> .vscode/c_cpp_properties.json
fixed a small typo of the file name in the guide
*
=> Fixed "properies" typo on line 51

docs/feature_rgb_matrix.md
Update the code snippet for the led_conf_t to remove `const`. Fixes compile error for previous declaration.
*
=> Update led_conf_t example in RGB Matrix feature page

keyboards/handwired/onekey/blackpill_f401/rules.mk, keyboards/handwired/onekey/blackpill_f411/rules.mk, keyboards/handwired/riblee_f401/rules.mk, keyboards/matrix/m20add/rules.mk, keyboards/matrix/noah/rules.mk, keyboards/phoenix/rules.mk, keyboards/tkw/stoutgat/v2/f411/rules.mk, keyboards/zvecr/zv48/f401/rules.mk, keyboards/zvecr/zv48/f411/rules.mk, quantum/mcu_selection.mk
=> Add STM32F401/F411 to mcu_selection.mk

lib/python/qmk/constants.py
=> Add STM32F401/F411 to ARM_PROCESSORS

layouts/community/ortho_5x12/xyverz/keymap.c
Minor fixes.
Minor fixes including the addition of the RAISE and LOWER macros, as well as the MACLOCK macro.
*
=> Fixing my 5x12 Ortho layout

keyboards/kingly_keys/romac_plus/config.h
adding vendor and product info so VIA will recognize it.
*
=> Align RoMac+ vendor and product info

keyboards/wsk/sl40/readme.md
updating image for V2 options
* 
=> adding V2 support

quantum/via.c
=> Fix typo in via.c

docs/ref_functions.md
- Add documentation to clarify if layer z is not a higher layer than both x and y, the layer change code does not function correctly.
- Remove random blank space at the end of a line.
*
=> Add information to docs

layouts/community/60_ansi_arrow/mrsendyyk/keymap.c, layouts/community/60_ansi_arrow/mrsendyyk/readme.md, layouts/community/60_ansi_arrow/readme.md, layouts/default/60_ansi_arrow/default_60_ansi_arrow/keymap.c, layouts/default/60_ansi_arrow/info.json, layouts/default/60_ansi_arrow/readme.md
Minor updates `60_ansi_arrow`
*
=> Minor updates 60_ansi_arrow

keyboards/dz60/keymaps/mrsendyyk/keymap.c, keyboards/dz60/keymaps/mrsendyyk/readme.md
Minor updates `dz60:mrsendyyk`
*
=> Minor updates dz60:mrsendyyk

keyboards/40percentclub/mf68/keymaps/delivrance/config.h, keyboards/40percentclub/mf68/keymaps/delivrance/keymap.c, keyboards/40percentclub/mf68/keymaps/delivrance/readme.md, keyboards/40percentclub/mf68/keymaps/delivrance/rules.mk
=> Add delivrance's keymap for 40percentclub/mf68

keyboards/basekeys/slice/config.h, keyboards/basekeys/slice/keymaps/default/config.h, keyboards/basekeys/slice/keymaps/default/keymap.c, keyboards/basekeys/slice/keymaps/default_split_left_space/config.h, keyboards/basekeys/slice/keymaps/default_split_left_space/keymap.c, keyboards/basekeys/slice/rev1/config.h, keyboards/basekeys/slice/rev1/keymaps/2moons/config.h, keyboards/basekeys/slice/rev1/keymaps/2moons/keymap.c, keyboards/basekeys/slice/rev1/keymaps/default_all/config.h, keyboards/basekeys/slice/rev1/keymaps/default_all/keymap.c, keyboards/basekeys/slice/rev1/keymaps/default_split_backspace/config.h, keyboards/basekeys/slice/rev1/keymaps/default_split_backspace/keymap.c, keyboards/basekeys/slice/rev1/rev1.c, keyboards/basekeys/slice/rev1/rev1.h, keyboards/basekeys/slice/rev1_rgb/config.h, keyboards/basekeys/slice/rev1_rgb/keymaps/2moons_rgb/config.h, keyboards/basekeys/slice/rev1_rgb/keymaps/2moons_rgb/keymap.c, keyboards/basekeys/slice/rev1_rgb/rev1_rgb.c, keyboards/basekeys/slice/rev1_rgb/rev1_rgb.h, keyboards/basekeys/slice/slice.c, keyboards/basekeys/slice/slice.h, keyboards/basekeys/slice/slice_font.c
valid license headers on all *.c and *.h source files
Updated all .c and .h files with copyright information. This is per the PR Checklist but was not completed. 
Copyrights up to date per PR Checklist
=> Copyright Updates

keyboards/boardsource/4x12/config.h
in PR  #10236 and PR #10043 we updated vendor ID for boardsource 3x4 and 5x12 to 0x4273 ("Bs"). We missed this change for the 4x12. This updates the vendor ID to match. 
* https://github.com/qmk/qmk_firmware/pull/10236#discussion_r484672360
=> update vendor id of 4x12 to match 3x4 and 5x12 for boardsource

keyboards/minimacro5/config.h, keyboards/minimacro5/info.json, keyboards/minimacro5/keymaps/default/keymap.c, keyboards/minimacro5/keymaps/media/keymap.c, keyboards/minimacro5/minimacro5.c, keyboards/minimacro5/minimacro5.h, keyboards/minimacro5/readme.md, keyboards/minimacro5/rules.mk
Adds the miniMACRO5 Macropad to QMK. This hardware is by @leafcutterlabs, and I have completed the work for this pull request.
=> Add miniMACRO5 Macropad

keyboards/ai03/soyuz/keymaps/mrsendyyk/keymap.c, keyboards/ai03/soyuz/keymaps/mrsendyyk/readme.md
Minor updates `ai03/soyuz:mrsendyyk`
*
=> Minor updates ai03/soyuz:mrsendyyk

lib/python/qmk/cli/doctor.py
Helpful if you don't know/remember where you/`qmk setup` cloned to.
*
=> CLI/Doctor: Print QMK_HOME

docs/faq_build.md, docs/faq_debug.md, lib/python/qmk/cli/doctor.py
Merged the udev rules files into a single file, and tweaked it a bit to include all USB devices under the known Caterina VIDs, and add some missing rules (USBAspLoader, SAM-BA).
Also, while I was here, I removed some outdated FAQ items.
*
=> Consolidate udev rules into a single file

keyboards/basekeys/trifecta/keymaps/via/keymap.c
Minor Trifecta keymap revision. RGB_TOG left over from testing. 
*
=> Trifecta Keymap Revision

keyboards/tgr/910ce/910ce.h
Moved keys around. Apparently I got them reversed.
=> Swapparoo of bottom row keys

keyboards/ergodox_ez/config.h, keyboards/ergodox_ez/ergodox_ez.c, keyboards/ergodox_ez/ergodox_ez.h, keyboards/ergodox_ez/matrix.c, keyboards/ergodox_ez/rules.mk
Like the title says.
Also added some config settings from the dactyl board, in prep to convert it.
=> Convert ErgoDox EZ to Matrix Lite

docs/hardware_keyboard_guidelines.md
Fixes small typo in the docs
*
=> Fixes small typo in docs

docs/faq_build.md
Apparently, udev does not like inline comments.
Rules with them are ignored, oops.
*
=> Docs: fix udev rules

quantum/process_keycode/process_rgb.c
PR #10404 (https://github.com/qmk/qmk_firmware/pull/10404/commits/ef7c79b781318faaef4e6fe318fffade1b1ed299) is causing build failure for following keyboards.
- inett_studio/sqx/hotswap
- inett_studio/sqx/universal
- mechlovin/hannah60rgb/rev2
- mechlovin/adelais/rgb_led/rev2
=> Fix issue introduced by PR#10404

docs/ja/breaking_changes.md
=> Update breaking_changes.md of Japanese document.

docs/ja/faq_debug.md
=> Update faq_debug.md of Japanese document.

docs/ja/feature_auto_shift.md
=> Update feature_auto_shift.md of Japanese document.

docs/ja/i2c_driver.md
=> Update i2c_driver.md of Japanese document

docs/ja/faq_build.md
=> Update faq_build.md of Japanese document.

docs/ja/flashing.md
=> Update flashing.md of Japanese document

docs/ja/ref_functions.md
=> Update ref_functions.md of Japanese document

keyboards/aeboards/ext65/rev2/bootloader_defs.h, keyboards/ai03/vega/bootloader_defs.h, keyboards/cannonkeys/an_c/bootloader_defs.h, keyboards/cannonkeys/chimera65/bootloader_defs.h, keyboards/cannonkeys/instant60/bootloader_defs.h, keyboards/cannonkeys/iron165/bootloader_defs.h, keyboards/cannonkeys/savage65/bootloader_defs.h, keyboards/cannonkeys/tmov2/bootloader_defs.h, keyboards/tkc/candybar/bootloader_defs.h, keyboards/xelus/trinityxttkl/bootloader_defs.h
Already present in `platforms/chibios`.
Remaining, some or all of these might also be deletable after #10418:
```
at_at/660m/bootloader_defs.h
cannonkeys/satisfaction75/bootloader_defs.h
chavdai40/bootloader_defs.h
handwired/bluepill/bluepill70/bootloader_defs.h
matrix/m20add/bootloader_defs.h
matrix/noah/bootloader_defs.h
nebula12/bootloader_defs.h
```
*
=> Remove bootloader_defs.h for some F072 boards

docs/ja/other_vscode.md, docs/other_vscode.md
=> Update other_vscode.md of Japanese document

keyboards/exclusive/e85/soldered/soldered.c
On behalf of VashtaNerada, committing his code
=> Get Caps Lock LED working 

keyboards/planck/keymaps/eosti/config.h, keyboards/planck/keymaps/eosti/keymap.c, keyboards/planck/keymaps/eosti/readme.md, keyboards/planck/keymaps/eosti/rules.mk
Adds the eosti/planck keymap. This keymap has a number of features, such as HJKL navigation, MacOS navigation shortcuts, and tmux navigation macros.
This is a re-PR of #10565 since I had my changes on the master branch, and then pulled to the master branch, causing mass chaos in the PR. Oops. Anyway, now it's on its own branch and everything is good. 
*
=> adds eosti/planck keymaps

keyboards/keyhive/maypad/info.json, keyboards/keyhive/maypad/maypad.h, keyboards/keyhive/maypad/readme.md, keyboards/keyhive/maypad/rules.mk
Adds a splitPlus layout option to the Maypad keyboard. Good option if you want those nice large Enter and 0 keys but really can't see yourself using the plus key too much. 
* N/A
=> Maypad improvements

keyboards/redox_w/config.h, keyboards/redox_w/keymaps/via/keymap.c, keyboards/redox_w/keymaps/via/readme.md, keyboards/redox_w/keymaps/via/rules.mk
Added via configuration for redox_w keyboard
*
=> Make via config for redox_w

docs/ja/feature_combo.md
=> Update feature_combo.md of Japanese document

lib/python/qmk/info.py
https://github.com/qmk/qmk_compiler/pull/76
*
=> [CLI] Remove check for Input Club boards

keyboards/minimacro5/keymaps/kabraxcis/keymap.c, keyboards/minimacro5/keymaps/voaraq/keymap.c
Add user keymaps for the miniMACRO5. These were programmed by me, but are designed by and requested by people who joined my recent group-buy for this macropad.
=> Add miniMACRO5 User Keymaps

docs/_summary.md, docs/ja/_summary.md
The file was added, but never actually linked. Whoops.
=> Add last breaking changes log to sidebar

keyboards/bm40hsrgb/config.h, keyboards/bm40hsrgb/keymaps/via/keymap.c, keyboards/bm40hsrgb/keymaps/via/readme.md, keyboards/bm40hsrgb/keymaps/via/rules.mk
Enabled the use of VIA for KPRepublic BM40
Enabled the use of VIA for KPRepublic BM40
=> Enabled the use of VIA for KPRepublic BM40

.github/labeler.yml, .github/workflows/labeler.yml
Along the same lines as #7091, however using a cron based action to work round permission issues.
=> Initial auto PR labeler config

.github/labeler.yml, .github/workflows/labeler.yml
* Update to official github action that doesn't rely on cron
* See actions/labeler#90 for more context
* The magic `pull_request_target` that was recently introduced allows CI to run in the context of the parent repo, avoiding the previous token rights issue
* Updates will have to land in master before they can be seen, but thats no worse than some of the current "try and see what happens" practice
* <https://github.community/t/running-code-from-forks-with-pull-request-target/126688>, We will need to be careful in its use (as mentioned within that link), but is fine with the current scope of this PR
* Add additional labels
* keyboard
* Limitation that it still adds `keymap` label right now to new ported keyboard PRs
* translation
* CI
=> Update PR labeler to use pull_request_target

lib/python/qmk/commands.py
```
...
File "D:/Git/qmk_firmware/lib/python/qmk/keymap.py", line 237, in _c_preprocess
pre_processed_keymap = qmk.commands.run(['cpp', path], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
File "D:/Git/qmk_firmware/lib/python/qmk/commands.py", line 85, in run
safecmd = ' '.join(safecmd)
File "C:/msys64/mingw64/lib/python3.8/shlex.py", line 325, in quote
if _find_unsafe(s) is None:
TypeError: expected string or bytes-like object
```
*
=> c2json: Fix TypeError on MSYS2

keyboards/cospad/config.h, keyboards/cospad/keymaps/via/keymap.c, keyboards/cospad/keymaps/via/rules.mk
Add VIA keymap for Cospad PCB
*
=> Add Cospad VIA support

drivers/issi/is31fl3731.c, drivers/issi/is31fl3736.c, drivers/issi/is31fl3737.c
Correctly change the LED updates to false to not have to transmit data every cycle.
* FIX IS31FL3731 update required
=> [Core] IS31FL3731/36/37 bug fix

keyboards/anavi/macropad8/keymaps/zoom/keymap.c
Zoom keymap for ANAVI Macro Pad 8 with the following shortcuts:
* Alt+V: Start/stop video
* Alt+A: Mute/unmute my audio
* Alt+M: Mute/unmute audio for everyone except the host
* Alt+S: Start/stop screen sharing
* Alt+R: Start/stop local recording
* Alt+P: Pause/resume recording
* Alt+C: Start/stop cloud recording
* Switch to 2nd layout to control backlighting and underlighting
Add Zoom keymap for ANAVI Macro Pad 8 with the following shortcuts:
* Alt+V: Start/stop video
* Alt+A: Mute/unmute my audio
* Alt+M: Mute/unmute audio for everyone except the host
* Alt+S: Start/stop screen sharing
* Alt+R: Start/stop local recording
* Alt+P: Pause/resume recording
* Alt+C: Start/stop cloud recording
* Switch to 2nd layout to control backlighting and …
=> [Keymap] Add Zoom keymap for ANAVI Macro Pad 8

keyboards/dm9records/plaid/keymaps/gipsy-king/keymap.c, keyboards/dm9records/plaid/keymaps/gipsy-king/readme.md
My keymap for the plaid keyboard, with custom LED animation
=> [Keymap] plaid keymap with custom LED animation

layouts/community/alice/stanrc85-alice/keymap.c, layouts/community/alice/stanrc85-alice/rules.mk
Add my community layout for Alice PCBs
*
=> Alice community layout

.github/labeler.yml
* Add `via` label
* Add 'dependencies' to stuff in `lib` (but not python stuff)
* Makefiles are core changes
=> Add additional auto labeler rules

.github/workflows/api.yml
This fixes the api update action that's currently broken: https://github.com/qmk/qmk_firmware/runs/1311925907?check_suite_focus=true
=> Add rsync to the api update process

keyboards/percent/booster/keymaps/via/keymap.c, keyboards/percent/booster/keymaps/via/rules.mk
Add via keymap for percent booster.
* None
=> Add via keymap for percent booster.

keyboards/anavi/macropad8/keymaps/obs/keymap.c
OBS keymap for ANAVI Macro Pad 8 with the following shortcuts:
- Shortcuts useful for switching scenes on the 1st row:
Hold Left Control, Shift, Alt and GUI and press F9
Hold Left Control, Shift, Alt and GUI and press F10
Hold Left Control, Shift, Alt and GUI and press F11
Hold Left Control, Shift, Alt and GUI and press F12
- Center to screen: Ctrl+D
- Fit to screen: Ctrl+F
- Move source to top of sources list: Ctrl+Home
Add OBS keymap for ANAVI Macro Pad 8 with the following shortcuts:
- Shortcuts useful for switching scenes on the 1st row:
Hold Left Control, Shift, Alt and GUI and press F9
Hold Left Control, Shift, Alt and GUI and press F10
Hold Left Control, Shift, Alt and GUI and press F11
Hold Left Control, Shift, Alt and GUI and press F12
- …
=> [Keymap] Add OBS keymap for ANAVI Macro Pad 8

keyboards/dm9records/plaid/keymaps/gipsy-king/keymap.c, keyboards/dm9records/plaid/keymaps/gipsy-king/readme.md
=> [Keymap] add an autoclicker to my plaid keymap

keyboards/anavi/macropad8/keymaps/kicad/keymap.c
KiCad is a cross platform, free and open source electronics design
automation (EDA) suite. It was used to create ANAVI Macro Pad 8.
This keymap contains 2 layers for KiCad hotkeys and a 3rd layer
for controlling the backlighting and the underlighting.
- Layer for KiCad Schematic hotkeys:
m - to move selected component
r - to rotate selected component
w - to wire components
v - to edit component value
F1 - zoom in
F2 - zoom out
F4 - zoom center
- Layer for KiCad PCB layout hotkets:
m - to move selected component
r - to rotate selected component
x - to route a new track
v - to add a via
F1 - zoom in
F2 - zoom out
F4 - zoom center
[KiCad](https://kicad-pcb.org/) is a cross platform, free and open source electronics design automation (EDA) suite. It …
=> [Keymap] Add KiCad keymap for ANAVI Macro Pad 8

keyboards/handwired/hnah108/keymaps/default/keymap.c
I keep forgetting the name of this function...
*
=> Hnah108: Fix `implicit declaration of function 'get_host_led_state'`

keyboards/kinesis/keymaps/dvorak/keymap.c
Updated the dvorak layout to match the official dvorak layout by Kinesis.
The dvorak layout introduced by f74ff86f9c5f3dfe1ee2b6e2b6d82edd4935ba1f is **mostly** correct. But some of the keys don't match the official layout by Kinesis.
Official images for reference (Kinesis Advantage - Dvorak Layout):
*
=> Corrected the dvorak layout for kinesis advantage keyboards

keyboards/percent/canoe/keymaps/via/rules.mk
Enable media keys support to Canoe VIA keymap. This works now thanks to https://github.com/qmk/qmk_firmware/issues/9650
*
=> Enable media keys support for Canoe VIA keymap

quantum/config_common.h
In _quantum/config_common.h_, the logic for 32U2/16U2 is exactly the same with 328p/328, but are written separately. Combine repeated lines.
*
=> [quantum] combine repeated lines of code

.github/workflows/lint.yml
=> Add qmk info -l to show the layouts too

keyboards/kingly_keys/little_foot/config.h, keyboards/kingly_keys/little_foot/keymaps/yanfali/config.h, keyboards/kingly_keys/little_foot/keymaps/yanfali/keymap.c, keyboards/kingly_keys/little_foot/keymaps/yanfali/rules.mk
- use a proton c instead of a pro micro
- configure audio clicky
- set up obnoxious startup song for bay area meetup
- Start of keymap for littlefoot
- quote the description text to avoid compilation errors
- fix personal userspace disabling audio for all other keyboards
Turn on fauxclicky and an obnoxious startup song for the bay area meetup
*
=> [Keymap] little foot

docs/index.html, docs/newbs.md
Changed the name to be less scary / off-putting to complete-beginners that have to learn CLI and C to use more of QMK
=> Docredirect

docs/feature_rgblight.md
I've converted the 360 color wheel to the 255 color wheel for QMK HSV values.
*
=> Added color wheel that have QMK HSV values.

.github/workflows/lint.yml
This is meant to fail when qmk lint fails.
=> Improve the QMK Lint workflow

keyboards/foxlab/key65/hotswap/readme.md, keyboards/foxlab/time80/config.h, keyboards/foxlab/time80/keymaps/default/keymap.c, keyboards/foxlab/time80/keymaps/default/readme.md, keyboards/foxlab/time80/readme.md, keyboards/foxlab/time80/rules.mk, keyboards/foxlab/time80/time80.c, keyboards/foxlab/time80/time80.h
=> Porting Time 80 TKL

keyboards/lily58/keymaps/via/config.h, keyboards/lily58/keymaps/via/keymap.c, keyboards/lily58/keymaps/via/rules.mk
Added Lily58 via keymap (keymap is based on yuchi)
This keymap has been tested with the VIA configrator.
*
=> Add Lily58 via keymap

keyboards/uno/config.h, keyboards/uno/info.json, keyboards/uno/keymaps/default/keymap.c, keyboards/uno/keymaps/default/readme.md, keyboards/uno/readme.md, keyboards/uno/rules.mk, keyboards/uno/uno.c, keyboards/uno/uno.h
Adding a new key"board" - "uno", one key.
Added all the new files for "Uno," I think I even did it right.  Maybe.
- [x ] Keyboard (addition or update)
*
=> [Keyboard] Add "Uno"

docs/pr_checklist.md, quantum/template/avr/config.h, quantum/template/ps2avrgb/config.h
Add notes to PR checklist and update templates with examples.
=> Recommend use of LED Indicator config

keyboards/keebio/bdn9/rev1/config.h
- Adds 3rd encoder support that was added in Rev. 1.3
- Fixes encoder orientation
*
=> BDN9: Fix encoder direction, add 3rd encoder for Rev. 1.3 support

keyboards/exclusive/e6v2/le_bmc/config.h, keyboards/exclusive/e6v2/le_bmc/keymaps/via/keymap.c, keyboards/exclusive/e6v2/le_bmc/keymaps/via/rules.mk, keyboards/exclusive/e6v2/le_bmc/readme.md, keyboards/exclusive/e6v2/oe_bmc/config.h, keyboards/exclusive/e6v2/oe_bmc/keymaps/via/keymap.c, keyboards/exclusive/e6v2/oe_bmc/keymaps/via/rules.mk, keyboards/exclusive/e6v2/oe_bmc/readme.md
Add VIA keymaps to the 2 BMC edition PCBs present in R1 and R2. 
*
=> VIA Support: E6V2 BMC editions 

keyboards/ploopyco/mouse/mouse.c, keyboards/ploopyco/mouse/readme.md, keyboards/ploopyco/pmw3360.c, keyboards/ploopyco/trackball/readme.md, keyboards/ploopyco/trackball/rev1/readme.md, keyboards/ploopyco/trackball/rev1/rules.mk, keyboards/ploopyco/trackball/rev1_005/readme.md, keyboards/ploopyco/trackball/rev1_005/rules.mk, keyboards/ploopyco/trackball/rules.mk, keyboards/ploopyco/trackball/trackball.c
This is based on feedback talking with crop_octagon about the device.  Future trackballs will ship with ATMEL DFU for simplicity.  
This also includes some fixes and optimizations based on code review and tinkering on my own devices.
=> [Keyboard] PloopyCo update and fixes

.github/workflows/develop_rebase.yml, .github/workflows/develop_update.yml
Should keep develop more up to date with master and reduce maintenance burden.
=> Rebase develop after a master push

.github/workflows/develop_api.yml
We currently push updates for this data for master, we should do so for develop as well.
=> Push the API data for develop as well

.github/workflows/develop_update.yml
Develop is not locked, yet the following was spotted <https://github.com/qmk/qmk_firmware/runs/1436458204?check_suite_focus=true>.
The check could be `&& exit 1` though i think skipping the merge is slightly nicer as it wont hide real failures
=> Fix failed develop updates within CI

.github/workflows/develop_update.yml
Apparently the git config is not automatically set.
=> Fix the master->develop merge

layouts/community/split_3x6_3/ddeklerk/rules.mk
Fixes a bug in my layout.
In order for the media controls to work, a rules.mk file was necessary.
I added a rules.mk file to my layout.
*
=> Add rules.mk

keyboards/lazydesigners/dimpleplus/keymaps/via/keymap.c, keyboards/lazydesigners/dimpleplus/keymaps/via/rules.mk
Add VIA Support for Dimple Plus
*
=> Add VIA Support for Dimple Plus

keyboards/lucid/phantom_hs/readme.md
Updated README name for Phantom by Lucid. No other changes.
Updated README name for Phantom by Lucid. No other changes.
*
=> Changed README name for Phantom by Lucid

shell.nix
Nix shell definition was missing a required dependency.
*
=> nix-shell: add milc dependency

keyboards/handwired/swiftrax/bebol/keymaps/default/keymap.c, keyboards/handwired/swiftrax/bebol/keymaps/via/keymap.c
=> fix handwired/swiftrax/bebol keymaps

keyboards/handwired/swiftrax/beegboy/keymaps/default/keymap.c, keyboards/handwired/swiftrax/beegboy/keymaps/via/keymap.c
=> fix handwired/swiftrax/beegboy keymaps

.github/workflows/auto_tag.yaml, util/travis_compiled_push.sh
Further migration of workflow away from travis.
=> CI: Add workflow for tagging essential modified files

.github/workflows/auto_tag.yaml
=> Use patch bump for auto tagging workflow

keyboards/e88/keymaps/via/keymap.c, keyboards/e88/keymaps/via/readme.md, keyboards/e88/keymaps/via/rules.mk
This is to add VIA support to the E88 PCB. I have tested this on my own board and it works.
*
=> Add VIA support for E88

keyboards/planck/readme.md
Add missing information needed to mirror the supported hardware in the previous line
=> Add missing hardware availability for Plank EZ

keyboards/claw44/lib/glcdfont.c
Loks like this was accidentally reintroduced after #7745.
*
=> Use progmem.h for claw44 glcdfont

keyboards/beatervan/keymaps/via/keymap.c, keyboards/beatervan/keymaps/via/readme.md, keyboards/beatervan/keymaps/via/rules.mk
added a via compatible keymap for the beatervan
=> add Via keymap for beatervan

keyboards/xd75/readme.md
The readme.md of the XD75 stated that only the XD75Re is supported, however the XD75Am is supported as well.
Since I could not find any information on whether the XD75Am is supported prior to flashing the XD75Re firmware on my XD75Am. I have added it to the list of supported hardware in the readme.md in case someone is not sure about the XD75Am support like I was.
*
=> Add XD75am as supported in XD75 readme

.github/workflows/format.yaml, lib/python/qmk/cli/fileformat.py
* Format all C files for now, till diff logic works within CI
* Fix recursion of dos2unix
=> CI automated format fixes

.github/workflows/format.yaml
Getting slightly further than before, however now committing seems to rejected. The log shows the following:
```console
[master eb628aa03] Format code according to conventions for ${GITHUB_SHA}
Author: zvecr <zvecr@users.noreply.github.com>
```
Hard code author to avoid this behaviour.
=> Another attempt to fix formatting workflow

keyboards/gh60/satan/config.h
This should be caps lock, not num lock.
*
=> gh60/satan: fix indicator LED define

.github/workflows/format.yaml
Why not attempt one more try at this workflow.... maybe this time ay?
=> Yet another stab at trying to get GitHub actions to push

keyboards/massdrop/ctrl/keymaps/r-pufky/config.h, keyboards/massdrop/ctrl/keymaps/r-pufky/keymap.c, keyboards/massdrop/ctrl/keymaps/r-pufky/readme.md
* Added personal keymap per: https://docs.qmk.fm/#/contributing?id=keymaps
Update personal keymap based on massdrop core changes, new RGB defines.
* None.
=> Update keymap based on massdrop/ctrl core changes.

Makefile, util/list_keyboards.sh, util/travis_build.sh
To reduce build times and make more travis builds pass we want to start excluding keyboards from the build.
=> Add the ability to exclude keyboards from travis builds

docs/cli_commands.md
The docs for the usage of the `qmk c2json` were wrong and notably didn't feature the mandatory `-kb` and `-km` flags/options.
*
=> Updated usage of qmk c2json

lib/python/qmk/cli/doctor.py
Moves the OS checks to a separate function.
=> Simplify qmk doctor to make room for #11208

lib/python/qmk/cli/generate/api.py, lib/python/qmk/info.py
Brings the keyboard JSON generation for keyboards.qmk.fm in-line with what the current API spits out. Also fixes a bug that prevented generation when a keyboard had invalid JSON.
=> Change keyboard json format to bring it inline with the current api

lib/python/qmk/cli/doctor.py
Just a simple check for `.git`. Emits a warning if absent, but maybe it should be an error, since we need the submodules to build?
*
=> Doctor: add check for .git folder

keyboards/boston_meetup/2019/rules.mk, keyboards/ckeys/thedora/rules.mk, keyboards/clueboard/66_hotswap/gen1/rules.mk, keyboards/hadron/ver3/rules.mk, keyboards/infinity60/rules.mk, keyboards/jm60/rules.mk, keyboards/planck/ez/rules.mk, keyboards/planck/keymaps/ishtob/rule.mk, keyboards/planck/rev6/rules.mk, keyboards/preonic/rev3/rules.mk, keyboards/tkc/candybar/lefty/rules.mk, keyboards/tkc/candybar/righty/rules.mk, quantum/mcu_selection.mk
None of these boards actually use a Teensy LC, and the EEPROM emulation code this is related to runs on a lot more than the LC. AFAICT it does not *require* a custom ldscript, however if you wanted to make sure there was no overlap you could create one, and this information should be placed in a singular location in the docs, if it is not already.
*
=> Remove comments about custom ldscript for Teensy LC

docs/newbs_getting_started.md
Add command to run on gentoo to setup qmk.
*
=> docs: add Gentoo to newbs_getting_started.md

keyboards/handwired/dactyl_manuform/5x6_right_trackball/info.json
Wrong name for the layout macro. Whoops.
=> [Keyboard] Fix Dactyl Manuform with Trackball info.json

keyboards/lizard_trick/tenkey_plusplus/config.h, keyboards/lizard_trick/tenkey_plusplus/info.json, keyboards/lizard_trick/tenkey_plusplus/keymaps/default/keymap.c, keyboards/lizard_trick/tenkey_plusplus/keymaps/macro/keymap.c, keyboards/lizard_trick/tenkey_plusplus/readme.md, keyboards/lizard_trick/tenkey_plusplus/rules.mk, keyboards/lizard_trick/tenkey_plusplus/tenkey_plusplus.c, keyboards/lizard_trick/tenkey_plusplus/tenkey_plusplus.h
Adding a new keyboard: Tenkey++ (tenkey_plusplus)
I will be merging in another keyboard soon, so I nested this one inside the /lizard_trick directory to keep my keyboards in the same place in the future.
*
=> Adding new keyboard: Tenkey++ (tenkey_plusplus)

docs/index.html, docs/newbs_getting_started.md, docs/qmk_custom_dark.css, docs/qmk_custom_light.css
Add tabs to getting started page, this should avoid users trying to use commands for the wrong platform due to them skimming the wrong section.
=> Simplify the visual flow of the getting started page

docs/feature_macros.md
=> Typo fix: Useful function -> Useful Functions

lib/python/qmk/cli/c2json.py, lib/python/qmk/cli/json2c.py, lib/python/qmk/keymap.py, lib/python/qmk/tests/test_cli_commands.py
Now you can pipe json config to json2c command.
=> [CLI] Add stdin support for json2c command

Makefile
This stuff isn't valuable anymore.
=> Remove some old and unused code from Makefile

docs/driver_installation_zadig.md
Just need to know what the APM32 bootloader device name is. @awkannan ?
*
=> Update Zadig docs with list of bootloader device names and IDs

docs/keycodes.md, docs/keycodes_basic.md
Fixing some...misalignments.
*
=> Update keycode docs

keyboards/handwired/6key/6key.c, keyboards/handwired/6key/6key.h, keyboards/handwired/6key/config.h, keyboards/handwired/6key/info.json, keyboards/handwired/6key/keymaps/default/keymap.c, keyboards/handwired/6key/readme.md, keyboards/handwired/6key/rules.mk
Add my custom macropad "6key" to the handwired keyboard subdirectory.
=> Add 6key to keyboards/handwired

tmk_core/common/avr/suspend.c
No other references to `BOOTLOADER_TEENSY` in the repo. Seems to be dead code.
*
=> Remove useless wait in AVR suspend code

docs/newbs_getting_started.md
Add Arch / Manjaro section for Linux setup instructions
* #10492
=> Add Arch / Manjaro section for Linux setup instructions

tests/test_common/test_matrix.h, tmk_core/make_dfu_header.sh
=> Missed a couple more `#pragma once`s

docs/driver_installation_zadig.md
=> Zadig docs: add APM32 device name

keyboards/ploopyco/mouse/readme.md, keyboards/ploopyco/trackball/readme.md
censor -> sensor
Fixing a typo
*
=> Fixed typo in readme.md

keyboards/rart/rart4x4/info.json
```
☒ rart/rart4x4: Invalid JSON in file keyboards/rart/rart4x4/info.json: JSONDecodeError: Expecting value: line 29 column 13 (char 1008)
```
*
=> Fix rart4x4 info.json

keyboards/montsinger/rebound/rev4/config.h, keyboards/montsinger/rebound/rev4/keymaps/via/keymap.c, keyboards/montsinger/rebound/rev4/keymaps/via/rules.mk
=> Rebound, adding files for VIA compat

keyboards/pos78/config.h
Added LED hardware pins and corrected ROW and COL hardware pins
As above.
*
=> Pos78 update

keyboards/quark/config.h
D6 and B1 were swapped by mistake
*
=> Update quark pin config

lib/python/qmk/cli/compile.py, lib/python/qmk/cli/flash.py
This will allow things like CI to rely on `qmk compile`.
=> Return the make exit code for qmk compile and flash

lib/python/qmk/cli/generate/config_h.py
A merging error led to uncompilable keyboards.
=> Fix compiling on develop

tmk_core/arm_atsam.mk
`arm_atsam` architecture does not support the `:flash` target, but we can at least make use of PROGRAM_CMD if it is set.
*
=> arm_atsam: Use PROGRAM_CMD for :flash target if set

docs/ja/_summary.md, docs/ja/custom_quantum_functions.md, docs/ja/feature_led_indicators.md
Add Japanese translation of docs/feature_led_indicators.md.
*
=> [Docs] Japanese translation of feature_led_indicators.md

keyboards/leafcutterlabs/bigknob/bigknob.c, keyboards/leafcutterlabs/bigknob/bigknob.h, keyboards/leafcutterlabs/bigknob/config.h, keyboards/leafcutterlabs/bigknob/info.json, keyboards/leafcutterlabs/bigknob/keymaps/default/keymap.c, keyboards/leafcutterlabs/bigknob/readme.md, keyboards/leafcutterlabs/bigknob/rules.mk
Add support for bigknob macropad
* 
- [ X] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [X ] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ X] I have added tests to cover my changes.
- [ X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> add support for bigknob

keyboards/butterstick/butterstick.c, keyboards/ergotaco/readme.md, keyboards/georgi/readme.md, keyboards/gergo/readme.md
Changing these docs to be correct
=> name change

keyboards/massdrop/alt/matrix.c, keyboards/massdrop/ctrl/matrix.c
* Duplicate matrix.c within #11365
=> Implement matrix_io_delay abstraction for Drop boards

docs/newbs_getting_started.md
[QMK MSYS](https://msys.qmk.fm/) seems stable enough now to start thinking about it becoming the default suggestion for new Windows users.
Hopefully this bundle should avoid a lot of the initial issues we see:
* Using wrong terminal
* Single shortcut to avoid confusion
* `pacman` download timeouts
* Failing to install dependencies/Failing to install the CLI/Running commands for another OS
* All dependencies to run `qmk setup` should ready to go out the box
=> Suggest 'QMK MSYS' as the default windows platform

keyboards/bakeneko60/readme.md
Update description and link URL on readme
*
=> Update Bakeneko60 readme

keyboards/bakeneko65/readme.md
Update description and link URL on readme
*
=> Update Bakeneko65 readme

keyboards/planck/keymaps/atreus/config.h, keyboards/planck/keymaps/atreus/keymap.c, keyboards/planck/keymaps/atreus/readme.md, keyboards/planck/keymaps/atreus/rules.mk
Add new atreus keymap to planck keyboard
*
=> Add new atreus keymap to planck keyboard

keyboards/zinc/keymaps/via/readme_en.md, tmk_core/common/action_tapping.h
=> Manually run formatting job

keyboards/melody96/keymaps/zunger/keymap.c
The previous implementation generated accents in NFKD -- e.g., i
followed by fn+e would generate í, which is actually an ordinary i
followed by U+0301 COMBINING ACUTE ACCENT. Unfortunately, it turns
out that a bunch of websites and apps (especially European ones
written in languages that use these a lot) were very poorly written,
and will misparse and/or crash if presented with Unicode NFKD. They
require and expect NFKC, with characters like í (U+00ED LATIN SMALL
I WITH ACUTE) that look visually identical -- and are in fact
normalization-equivalent -- but have to be encoded differently.
The new accent implementation handles this in a very flexible way.
Many new comments added as well, as it's also clear that this is going
to need a bit more expansion before it becomes a true polyglot …
=> Redo the accent implementation in melody96:zunger.

keyboards/kbdfans/kbd19x/config.h
Looks like I got the logic backwards in #10906.
Verified by `@Boto#3505` on discord
=> Fix inverted indicator leds on kbdfans/kbd19x

util/list_keyboards.sh
In an attempt to make the travis-ci check useful again and to make running the check locally yourself more feasible I'm adding more keyboards to be excluded. These are keyboards that have 0 or 1 features enabled, meaning there is nothing unique about them.
This also changes `list_keyboards.sh` to exclude all of handwired and remove the individual `.noci` files therein.
=> Exclude more keyboards from CI

keyboards/leafcutterlabs/bigknob/bigknob.c, keyboards/leafcutterlabs/bigknob/bigknob.h, keyboards/leafcutterlabs/bigknob/config.h, keyboards/leafcutterlabs/bigknob/keymaps/default/keymap.c, keyboards/leafcutterlabs/bigknob/keymaps/default/rules.mk, keyboards/leafcutterlabs/bigknob/rules.mk
The same idea as that behind 11464, but without the messy git history.
=> Fix leafcutterlabs/bigknob compiles in configurator

docs/feature_unicode.md
=> Fix documentation so UCIS example compiles.

keyboards/primekb/prime_e/keymaps/gwillad/keymap.c, keyboards/primekb/prime_e/keymaps/gwillad/readme.md, keyboards/primekb/prime_e/keymaps/gwillad/rules.mk
Besides using a tweaked version of my prefered layout, this also includes:
* code to use the prime e LEDs for layers (instead of caps lock or num lock or anything else), which I thought made more sense on a 40%
* via enabled so people can still adjust their code without having to recompile
*
=> add gwillad's keymap for prime_e

keyboards/playkbtw/ca66/config.h, keyboards/playkbtw/ca66/keymaps/via/keymap.c, keyboards/playkbtw/ca66/keymaps/via/readme.md, keyboards/playkbtw/ca66/keymaps/via/rules.mk, keyboards/playkbtw/ca66/rules.mk
Added necessary files and changes for VIA support
Added vendorID and checked to make sure it wasn't currently a used vendorID
Added VIA keymap.c based off the KeLorean keymap and rules.mk
All changes have been tested with VIA.
*
=> Add VIA support for CA66

tmk_core/protocol/arm_atsam/usb/udi_device_epsize.h
This is the odd one out, although in the long term they should probably all be upped to 64 bytes.
*
=> arm_atsam: temporarily lower raw HID endpoint/report size

tmk_core/protocol/lufa/adafruit_ble.cpp, tmk_core/protocol/lufa/adafruit_ble.h, tmk_core/protocol/lufa/lufa.c
Just getting this out of the way to make the final bluetooth refactoring diff smaller.
*
=> Adafruit BLE cleanups

lib/python/qmk/commands.py
Some features depend on `version.h`, which was not being generated for JSON compiles.
=> Generate version.h when compiling json files
