qmk/qmk_firmware

keyboards/wilba_tech/wt_rgb_backlight.c
This is done to fix https://github.com/qmk/qmk_firmware/issues/7899
The `backlight_set_color_all` function was using the `IS31FL3733_set_color_all` function which sets **ALL** the leds of the drivers. As the indicators are driven by the drivers this means they were getting overwritten.
Before the NK65 refactoring, after `backlight_set_color_all` was called, `backlight_effect_indicators` was called fixing the wrong state of the indicators.
Now as the indicator code is not synchronous with the backlight effects we need to avoid putting "dirty" values in the indicator registers.
*
=> Fix NK65 indicator code after refactoring

common_features.mk
Bitbang ws2812 currently causes issues on ARM split with both "serial" and potential uart transport code, mainly due to the need to chSysLock to get accurate timings.
In order to add build errors/warnings for `if(ARM && ws2812_driver == bitbang, && RGBLIGHT_SPLIT)`, this PR adds the `WS2812_DRIVER_BITBANG/WS2812_DRIVER_SPI/WS2812_DRIVER_I2C/WS2812_DRIVER_PWM` defines.
=> Add ws2812 driver type define

quantum/matrix_common.c
When converting another board to use `CUSTOM_MATRIX = lite`, the board was always reporting change, causing the OLED to not timeout. Slight oversight when porting over the xd84 code to core.
=> Fix CUSTOM_MATRIX lite matrix_scan return code

keyboards/hhkb/keymaps/xyverz/keymap.c
Usability changes: added `KC_GRV` and `KC_GESC` to keymap as well as `FN_TAB` for `LT(_FL, KC_TAB)`.
*
=> Further changes to HHKB keymap

tmk_core/common/action_tapping.c
Extra, unneeded check
* Should have zero impact. Is just cleanup
=> Cleanup check for PERMISSIVE_HOLD

docs/config_options.md, docs/feature_advanced_keycodes.md, tmk_core/common/action_tapping.c
Inspired by @zk-phi 
Implements a per-key `TAPPING_FORCE_HOLD`
Special thanks to @Curry for helping me suck less at git.
=> Implement and document TAPPING_FORCE_HOLD_PER_KEY

common_features.mk, quantum/process_keycode/process_steno.c, quantum/process_keycode/process_steno.h
The general purpose chording engine that my boards use leverages the steno hooks. However some of them (Ginny, ButterStick, FaunchPad) don't use the serial interface typically used by a steno writer. This PR sticks in a option to stub out those serial calls in a way that only effects the steno subsystem. 
This saves about 1K of space that could be used for additional dictionary entries/words.
=> Virtser disable

keyboards/ergodash/rev1/config.h
On the v1.2 PCB the slave half leds go in reverse order compared to the master half.
With this change, the leds are all in order from left to right, so animations like
Knight Rider look like you'd expect.
=> Fix the order of underglow LEDs on ergodash/rev1

quantum/quantum.c, tmk_core/common/keyboard.c, tmk_core/protocol/chibios/main.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/main.c
Backlight with CTPC wasnt happy on arm_split, where it would only function on the master slide. While moving backlight_task, rgblight_task also looked out of place at the protocol level so that was moved too.
=> Relocate rgblight and backlight task

.travis.yml, util/travis_compiled_push.sh
clang-format is not currently being run on core files. From <https://travis-ci.org/qmk/qmk_firmware/builds/622207692?utm_source=github_status&utm_medium=notification>,
```console
0.21s$ bash util/travis_compiled_push.sh
id_rsa_qmk_firmware
id_rsa_qmk.fm
Agent pid 16033
Identity added: id_rsa_qmk_firmware (id_rsa_qmk_firmware)
Using git hash 201c5bf
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
dos2unix: converting file quantum/encoder.c to Unix format ...
YAML:15:21: error: unknown key 'IndentPPDirectives'
IndentPPDirectives: AfterHash
^~~~~~~~~
Error reading /home/travis/build/qmk/qmk_firmware/.clang-format: Invalid argument
```
=> Fix unknown key 'IndentPPDirectives' on CI

lib/python/milc.py
If an undefined attribute of a submodule is accessed, fall back to
same attribute of the submodule's parent.
Example:
QMK CLI submodules try to access their respective configs, for example: `qmk compile` will read from `cli.config.compile.*`.
If we try to access an attribute that's not defined on the submodule level, fall back to the submodules' parent level (`cli.config.user.*`) before erroring out.
This was the intended behaviour before, but it was kind of broken.
*
=> MILC: Fix/complete attribute heritance

keyboards/ymdk_np21/ymdk_np21.c
#7775 appears to have inverted the Num Lock LED on the YMDK NP21, causing it to light up when Num Lock is off, and not light up when Num Lock is on. I removed a negation so that the LED properly reflects the state of Num Lock on the computer.
*
=> Correct the Num Lock LED state on YMDK NP21

tmk_core/protocol/chibios/usb_main.c
Following on from #7860, porting my fix from #4824. Now we always use `set_led_transfer_cb`, so the ifdef surrounding it has been removed altogether.
*
=> Fix lock LEDs for ChibiOS when using shared endpoints

keyboards/gray_studio/think65/solder/readme.md, keyboards/gray_studio/think65/solder/solder.c, keyboards/gray_studio/think65/solder/solder.h
It was reported to me by mwb that on the soldered PCB, both the backspace and left shift keys were not correct on the LAYOUT_65_ansi LAYOUT. 
Also took the opportunity to do some minor clean ups.
=> Think 6.5 Soldered Matrix Fix

lib/python/qmk/cli/cformat.py
Noticed while fixing #7934, `quantum/template/*` gets included in clang-format, which breaks the tokens `#define MANUFACTURER % YOUR_NAME %`.
=> Align cformat rules with current CI implementation

tmk_core/common/chibios/printf.c
When implementing matrix printing on ChibiOS, binary support was added to the printf lib. This was only tested on a "small" board, however recent investigation within #7946 has shown that the original buffer used is not large enough... :man_facepalming: 
Credit goes to @wiml for the awesome investigation work!
* Fixes #7946
=> Fix printf buffer overflow when cols>16

tmk_core/protocol/chibios/usb_main.c
Force 4 byte alignment on USB buffers. Chibios casts these buffers to `size_t*` before dereferencing them (`os/hal/src/hal_buffers.c:633`, among other locations); in some cases this can result in an unaligned access if LTO decides to shift things around. Ideally the chibios API would express this alignment precondition, but this will ensure that all accesses to these buffers are aligned.
There are several more APIs in which chibios performs an unsafe cast, but as far as I can tell this is the only one that might result in an unaligned access to QMK data. 
I've been able to reliably reproduce this crash in the following configuration:
- docker build on `tzarc/qmk_firmware:chibios-upgrade`
- target `onekey/stm32f0_disco:rgb` 
- disable NKRO
- enable RGBLIGHT
- enable UNICODE
- enable LTO …
=> Fix unaligned access with LTO

keyboards/40percentclub/mf68/keymaps/emdarcher/keymap.c, keyboards/atreus62/keymaps/xyverz/keymap.c, keyboards/atreus62/keymaps/xyverz/readme.md, keyboards/eco/keymaps/xyverz/keymap.c, keyboards/gh60/revc/revc.h, keyboards/gingham/matrix.c, keyboards/handwired/owlet60/matrix.c, keyboards/hineybush/h87a/keymaps/wkl/keymap.c, keyboards/hineybush/h88/h88.c, keyboards/kbdfans/kbd75/keymaps/tucznak/keymap.c, keyboards/kmac/matrix.c, keyboards/minidox/keymaps/xyverz/keymap.c, keyboards/noxary/268_2/268_2.c, keyboards/orthodox/keymaps/xyverz/keymap.c, keyboards/yd60mq/yd60mq.c, layouts/community/ortho_4x12/xyverz/keymap.c, layouts/community/ortho_5x12/xyverz/keymap.c, quantum/config_common.h, quantum/quantum.h
* 
[The documentation](https://github.com/qmk/qmk_firmware/blob/master/docs/internals_gpio_control.md) here says that setPinInput() sets the pin to a high-z input. This is true only if the PORTx register is 0, meaning you have to use writePinLow() to go from setPinInputHigh to input high-z again. This fixes that.
=> Ensure setPinInput actually sets input high-Z

common_features.mk
Another little common slice from #7072 and #7987.
As #6494 is still on the back burner, this removes the need to have stub files, and i2c enabled in the chibios conf files, for it to just be thrown away....
=> Remove compilation of i2c for arm split

lib/python/qmk/cli/doctor.py
I noticed in a fresh MSYS2 installation on a fresh W10 (home and pro) installation didn't work with qmk doctor anymore, as the platform string has changed to indicate that it's msys
=> Qmk doctor os check to support newer msys2/w10 installations

tmk_core/protocol/lufa/lufa.c
Improve performance of virtser. Currently it consumes 1 byte at a time, which took for me over 30ms when sending 49 bytes. With a simple change, it can send 10x that in 30ms.
*
=> Improve VIRTSER performance

keyboards/noxary/280/280.c
Dead Encryption reached out to me stating that the led was backwards. He provided the following code which I have since updated to the new standards
void led_set_kb(uint8_t usb_led) {
if (IS_LED_ON(usb_led, USB_LED_CAPS_LOCK)) {
writePinHigh(D5);
} else {
writePinLow(D5);
}
if (IS_LED_ON(usb_led, USB_LED_SCROLL_LOCK)) {
writePinHigh(D0);
} else {
writePinLow(D0);
}
led_set_user(usb_led);
}
=> Noxary 280 Backwards LED Fix

drivers/arm/i2c_master.c
Adds thread safety when `I2C_USE_MUTUAL_EXCLUSION=TRUE`.
Small amount of cleanup as well, saves a whole byte of RAM!
=> ChibiOS/ARM i2c_master mutex

quantum/process_keycode/process_space_cadet.c, tmk_core/common/chibios/timer.c
Space Cadet does not work on STM32F103 (BluePill). Specifically it works a couple of times, then it stops. There may be a deeper problem in timeout computation that I'm not able to fix (being a Java programmer). Basically after a couple of any key presses the timer_elapsed() starts returning large increments (the overflow variable in chibios/timer.c) gets stuck at 65535.
Adding TIMER_DIFF_16() to the comparison in perform_space_cadet() fixed the problem. I'm aware that it is probably not the "right" solution but it works for this case.
It is a simple change but I'm a little worried that I was not able to test the fix on any other architecture.
*
=> Fix timer_elapsed() overflow issue for STM32F103 and other ChibiOS boards

tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c
Should be no behaviour changes. I fixed the raw HID descriptor to have the correct usage page and usages, but since there is no raw HID implementation for ATSAM yet anyway, we don't need to worry about it breaking anything.
*
=> Align ATSAM HID descriptors with LUFA/ChibiOS

lib/python/qmk/cli/cformat.py
Running `bin/qmk cformat` locally, I get changes made to ignore folders. This PR fixes the logic that removes path walking but still processed files at that level.
=> CLI: Fix cformat processing files within ignore folders

tmk_core/common/report.h, tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/chibios/usb_main.h, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/lufa/lufa.h, tmk_core/protocol/vusb/vusb.c
The changes here are twofold: the report struct for the extrakeys (media keys) interface was defined in multiple places, so I pulled them up into report.h, where the rest of the report structs are.
Also, the system and consumer send functions have a good amount of common code that can be refactored into a single `send_extra()` function that takes the report ID and the usage.
```
make gh60/satan:default
before: 18618/28672 (64%, 10054 bytes free)
after: 18542/28672 (64%, 10130 bytes free)
make jj4x4:default
before: 19106/28672 (66%, 9566 bytes free)
after: 19060/28672 (66%, 9612 bytes free)
```
So on avr-gcc 8.3.0/avr-binutils 2.33.1, that's about a 76 byte decrease in filesize for LUFA with extrakeys on, and around 46 bytes for V-USB 👍
*
=> Dedupe extrakey report struct, and send functions in V-USB & LUFA

tmk_core/protocol/chibios/main.c, tmk_core/protocol/chibios/usb_main.c
Add `midi_ep_task` so that the MIDI endpoint on ChibiOS is actually functional. 
Before, the feature would be enabled, but wouldn't actually do anything, since there was no actual communication.
I'm not 100% certain that this works, but alexfry#4975 on Discord has confirmed that it works (as well, as identified that it wasn't working)
*  [Discord] MIDI wasn't working on ChibiOS
=> Add Midi Endpoint task to ChibiOS main

.gitignore
No longer necessary due to #7924.
=> Remove entries for Minidox eep files from gitignore

keyboards/atreus/atreus.h, keyboards/atreus/keymaps/ibnuda/config.h, keyboards/atreus/keymaps/ibnuda/keymap.c, keyboards/atreus/keymaps/ibnuda/rules.mk, keyboards/atreus/promicro/config.h, keyboards/atreus/promicro/promicro.c, keyboards/atreus/promicro/promicro.h, keyboards/atreus/promicro/rules.mk, keyboards/atreus/readme.md
- Added cheap promicro clone as one of the alternative controllers, intended to be used with [this fork](https://github.com/ibnuda/atreus/tree/promicro).
- Added my personal keymap.
*
=> Added Atreus Pro Micro variant

keyboards/ergosaurus/info.json
Corrected the layout macro name in `info.json`.
@cfbender kindly opened a PR to add a default keymap for this board in QMK Configurator, and when I went to check it I discovered the layout rendering wasn't working. Cause was the `info.json` file referencing a layout macro that doesn't exist.
=> Ergosaurus Configurator support bugfix

tmk_core/common/report.h
Convert the KEYCODE2SYSTEM and KEYCODE2CONSUMER macros to functions,
defaulting to using the macros.  The function form allows the compiler
to optimize the switch statement itself, over the macro nested
ternaries.
~~To enable this feature, #define USE_KEYCODE2_FUNCTION.~~
Testing against a random selection of avr-based keyboards, this
increased available flash by ~500 bytes. For arm-based keyboards,
the available flash increased by ~400 bytes.
=> Use function for KEYCODE2 routines instead of macro.

docs/cli.md, lib/python/qmk/cli/compile.py
Adds context sensitivity to `qmk compile`. Allows the command to be run within a keyboard directory, given no other CLI arguments, and will compile the default keymap for the given keyboard.
* Closes #6824
=> Add QMK Compile Context Sensitivity

keyboards/ergodox_ez/matrix.c
Since the IO expander is sequential mode (IOCON.SEQOP = 0),  the address pointer is set to GPIOB (columns to be read) register after the row selection write operation on GPIOA so this write-restart to set address to GPIOB is unnecessary.
I also looked into special byte mode (IOCON.SEQOP = 1, IOCON.BANK = 0) that should cause the address pointer to toggle between GPIOA and GPIOB, but it doesn't look like you should write without sending the register address from the MCP23018 datasheet Figure 1-1 so  there were no other savings.
This improves scan rate from 590 to 790.
@seebs
=> Remove i2c write command when reading columns on Ergodox EZ

keyboards/maxr1998/phoebe/keymaps/default/config.h, keyboards/maxr1998/phoebe/keymaps/default/keymap.c
As stated in the title ;)
I wondered, could I also just put the defines directly into the `keymap.c`?
=> Phoebe/Maxr1998 keymap: enable space cadet with curly braces

tmk_core/common/action.c
When ONESHOT_TIMEOUT and NO_ACTION_ONESHOT are both defined, this code
fails to compile.
Wrap the one usage of ONESHOT_TIMEOUT that is inconsistent with the
rest so all usages are properly wrapped by a check of NO_ACTION_ONESHOT.
=> Compile error if ONESHOT_TIMEOUT defined but oneshot disabled

keyboards/bpiphany/sixshooter/config.h, keyboards/bpiphany/sixshooter/sixshooter.h
In the config.h of sixshooter, it has been defined as following.
#define MATRIX_ROWS 1
#define MATRIX_ROW_PINS {  }
This is a potential bug because by definition row_pins will get assigned undefined value.
In this case use of DIRECT_PINS is appropriate. 
Similar to https://github.com/qmk/qmk_firmware/pull/8115, I need this consistency for my next PR.
=> [Keyboard] Use DIRECT_PINS instead of empty MATRIX_ROW_PINS: sixshooter

keyboards/crkbd/keymaps/bcat/config.h, keyboards/keebio/quefrency/keymaps/bcat/config.h, users/bcat/config.h
I'm reducing my `TAPPING_TERM` back to the default (200 ms) to try and combat spurious Esc keypresses on an Esc (tap)/Ctrl (hold) key. It turns out my real issue before was the Lily58 keyboard sets it to _super short_ (100 ms) by default. :) I'm also explicitly `#undef`ing some symbols I redefine in keymap configs so I don't cause problems if the keyboards start defining those things in the future (e.g., #7754).
None
=> Tweak my TAPPING_TERM and be more futureproof

lib/python/milc.py
`os.rename()` doesn't support cross-platform overwriting of files (windows, yay) `os.replace()` does
https://docs.python.org/3.5/library/os.html#os.rename
> If you want cross-platform overwriting of the destination, use replace().
=> use replace() over rename() to have cross-platform overwriting

keyboards/wsk/gothic50/config.h
Similar to https://github.com/qmk/qmk_firmware/pull/8115
MATRIX_ROWS and MATRIX_COLS are wrongly defined larger than it should be.
=> [Keyboard] Fix inconsistent MATRIX_ROWS and MATRIX_COLS: wsk/gothic50

keyboards/ai03/polaris/info.json, keyboards/ai03/polaris/keymaps/default_ansi_tsangan/keymap.c, keyboards/ai03/polaris/polaris.h, keyboards/ai03/polaris/rules.mk
The Polaris PCB has a Tsangan layout macro that matches the existing [`60_tsangan_hhkb`](https://github.com/qmk/qmk_firmware/tree/master/layouts/default/60_tsangan_hhkb) layout. I'm just renaming the layout macro to use that name so existing community layouts work. AFAIK these boards haven't shipped to anyone yet, so I don't think this is a breaking change since there is no hardware in the wild to break.
I ran `make ai03/polaris` and everything seems happy, except that yanfali's community layout firmware is too big (unrelated to this change).
@ai03-2725, are you okay with this change?
None.
=> Rename Polaris Tsangan layout to 60_tsangan_hhkb and enable community layout support

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
The default font is 1344 bytes, or a total of 224 glyphs (each 6-bytes wide).
OLED_FONT_END defaults to 224, which if used will then index off the end of
the font array. So either the documentation or code is wrong.
Instead of figuring out the rewording of the documentation, just change
the OLED_FONT_END default value to 223, to match the documentation and code.
=> Fix out of bound OLED font access

keyboards/keebio/quefrency/rev2/config.h
Per @nooges' comment in #8041. I would have also added `led_update_kb()` for B6 as the caps lock LED, but that pin seems to already be included in `MATRIX_ROW_PINS_RIGHT`, and I'm not quite sure whether we should be checking which half we're on (or if the split code even understands what to do with lock LEDs).
*
=> Define backlight pin for Quefrency Rev2

layouts/community/ergodox/osx_neo2/config.h, layouts/community/ergodox/osx_neo2/keymap.c
A few small tweaks and bugfixes for the osx_neo2 Ergodox keymap.
* Use TAPPING_TERM constant (and redefine value to 200ms)
* change TAPPING_TOGGLE to 2 to require two taps to lock in layer 4
* add support for Shift-Command 3/4/5 key combinations that are used in
macOS Catalina
* avoid false positive tap detecion for RMOD3 when the whole sequence of
pressing RMOD3, tapping another key and releasing RMOD3 took less than
TAPPING_TERM milliseconds.
* None that are reported as issues on the repository.
=> [osx_neo2] Bugfixes and improvements to Ergodox macOS Neo2 keymap

keyboards/handwired/daishi/keymaps/default/keymap.c, keyboards/handwired/daishi/rules.mk, keyboards/handwired/space_oddity/keymaps/default/keymap.c, keyboards/handwired/space_oddity/rules.mk
When travis is building all default keymaps, it flags these two as using the old Dynamic Macro code. This updates them to the new feature.
*
=> Convert two handwired default keymaps to Dynamic Macro feature

docs/ChangeLog/20200229/PR8078.md, tmk_core/common/chibios/timer.c, tmk_core/common/timer.h
When running a high SysTick frequency on 16-bit devices, the "simplified" timer implementation on the original PR #7597 was not tested thoroughly enough and was incorrectly ignoring overflows.
This PR support for overflow when running on 16-bit devices.
It also updates `timer_expired` and `timer_expired32` to be defines, as when compiling for debug mode, the linker has already stripped out the inline functions.
=> Fix ChibiOS timer overflow for 16-bit system clock devices.

keyboards/40percentclub/gherkin/keymaps/default/keymap.c
Updates the default QMK keymap for Gherkin to [the same one](http://www.keyboard-layout-editor.com/#/gists/7eac308ec268b36b0621bfca7500d20c) that's in [the original TMK repository](https://git.40percent.club/di0ib/tmk_keyboard/src/branch/master/keyboard/gherkin/actionmap_gherkin.c). This will let new Gherkin builders flash the default QMK firmware and get the same experience that they would if they built and flashed from di0ib's TMK repository.
=> Conform Gherkin defaults to original TMK keymap

quantum/dynamic_keymap.c
Checks dynamic keymap EEPROM usage is within available EEPROM
As an aid to adding VIA support to new keyboards, this checks the amount of EEPROM to be used for dynamic keymaps doesn't exceed the amount of EEPROM available, thus potentially avoiding one's Sunday afternoon being wasted trying to debug why firmware isn't working due to four layers of a huge switch matrix not fitting into 1K of EEPROM.
It additionally allows for keyboard-level override of how much EEPROM is allocated.
*
=> Dynamic keymap sanity check

util/win_shared_install.sh
This is to allow CI to run `qmk setup -y` on windows runners. Without it it'll loop in "invalid answer" when it reaches [the driver installation step](https://github.com/Duckle29/qmk_cli/runs/451126266?check_suite_focus=true#step:7:906)
=> Made windows driver installation accept y as All to allow CI

docs/config_options.md, quantum/matrix.c, quantum/matrix_common.c, quantum/split_common/matrix.c, tmk_core/common/matrix.h
Hitting some limits when testing the arm uart serial code, this allows the delay while waiting for IO to settle to be configurable.
Ive tested as low as 5us with success.
=> Allow 30us matrix delay to be keyboard/user overridable 

keyboards/cannonkeys/satisfaction75/config.h
Change some settings in config.h to make the S75 encoder behave as desired
*
=> S75 Encoder Fixes

tmk_core/common/uart.c
Backport from tmk/tmk_keyboard@c41e48a0ab0712d2667feb6b5dd8a4d5491cfcc5
=> uart.c fix from TMK

keyboards/preonic/keymaps/elisiano/config.h, keyboards/preonic/keymaps/elisiano/keymap.c, keyboards/preonic/keymaps/elisiano/readme.md, keyboards/preonic/keymaps/elisiano/rules.mk
=> Added custom keymap for preonic

tmk_core/protocol/vusb/main.c
As discussed here: https://github.com/qmk/qmk_firmware/issues/8193
In vusb main, the interrupt enable was after `keyboard_init();`. As a result, the debouncing was not working correctly to capture the first press of the bootmagic lite key.
Now the USB stack is initialized, then the usb connection is initialized, interrupt is enabled and finally `keyboard_init();`.
Thanks to @fauxpark for his help.
Tested on gingham with 328p
* https://github.com/qmk/qmk_firmware/issues/8193
=> V-USB interrupt enable fix

docs/cli.md, lib/python/qmk/cli/cformat.py, lib/python/qmk/path.py, lib/python/qmk/tests/test_cli_commands.py
`qmk cformat <file1> <file2> <...> <fileN>` functionality remains unchanged
`qmk cformat -a` formats all core files, same as old `qmk cformat` behavior
`qmk cformat` now only formats files that have changed between local and default `origin/master`. Branch can be changed via the `-b` flag.
* Fixes #7884 
* #7872
=> New flags and functionality for cformat

docs/feature_macros.md
Help people find additional features they can activate within a macro.
I was looking for how to reset the keyboard from a macro, which is documented in "Useful functions" but if you don't know to look there it's not easy to find. I've added a link to that page from the "Macros" documentation to make it a little easier to discover.
=> Add link to "Useful functions" in macro docs

drivers/arm/i2c_master.c
~`i2c_start` and `i2c_stop` were actually only really useful for people who want to explicitly invoke ChibiOS i2c functions. With mutual exclusion enabled, there were instances of `i2c_start`->`i2c_transmit` which would deadlock as the mutexes are non-recursive.~
~This PR turns `i2c_start` and `i2c_stop` into no-ops in order to maintain the previous interface, and folds the `i2c_stop` functionality into the other transmission functions -- they were already effectively doing `i2c_start` anyway.~
Modified this PR to rollback #7967, specifically to fix the Qwiic OLED issue. Will do a new followup PR to fix all I2C usage across the platform to correctly invoke start/stop, and only perform lock acquisition in those functions.
=> Rollback #7967, ChibiOS thread safety

docs/feature_unicode.md, quantum/process_keycode/process_unicode_common.c, quantum/process_keycode/process_unicode_common.h
This essentially supersedes (but does not deprecate or remove) `send_unicode_hex_string()`. Now you can use UTF-8 string literals in a `send_string()`y way, although it currently skips over surrogate pairs and code points higher than U+FFFF, as `register_hex()` is used instead of `register_hex32()` which is in unicodemap.c.
*
=> A proper `send_string()` for the Unicode feature

keyboards/hineybush/h87a/h87a.c, keyboards/hineybush/h87a/keymaps/default/keymap.c, keyboards/hineybush/h87a/keymaps/via/keymap.c, keyboards/hineybush/h87a/keymaps/wkl/keymap.c
Reported to me by wholesomeducky on discord. When using the VIA enabled firmware, his locking indicators were not working as expected. Tagging @hineybush for visibility. 
To fix this I updated the led code used in the VIA keymap and moved it to h87a.c so that all keymaps can make use of this. Wholesomeducky has confirmed that my changes work. 
I also had to speak with both default and wkl about changing their user keymaps. They weren't too happy, but after a few beers and some arm wrestling matches, they conceded.
=> Hineybush h87a lock indicators

tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/arm_atsam/usb/udi_device_conf.h, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/vusb/vusb.c
As mentioned in #963, these descriptors are declared as Array, so the logical value sent over the wire is the 1-based index of the usage between Usage Minimum and Usage Maximum. Only one value can be asserted at a time, and a value of 0 means nothing pressed.
I've reverted the range of the System usages from just the three power keycodes to the entire thing so that one can send arbitrary usages with `host_system_send()`. Now we don't need to do the whole `data - SYSTEM_POWER_DOWN + 1` first, as usage 1 == index 1.
Similarly I increased the range of the Consumer usages slightly, to allow for some of the newer additions to the page such as the macOS Launchpad and Mission Control usages (#4762). They still don't have their own keycodes yet, but you can now at least DIY.
I couldn't reproduce …
=> Improvements to extrakey HID descriptors

docs/feature_unicode.md, quantum/process_keycode/process_unicode_common.c, quantum/process_keycode/process_unicode_common.h, quantum/process_keycode/process_unicodemap.c, quantum/process_keycode/process_unicodemap.h
Following on from #8155. Now it does emoji!
*
=> `send_unicode_string()`: Add support for code points > 0xFFFF

quantum/split_common/matrix.c, quantum/split_common/split_util.c, quantum/split_common/split_util.h
Made much worse by the `SPLIT_USB_DETECT` mode, there is a window where the slave side has is interrupt handler registered before its init process has finished. Given this interrupt can jump in at any point, it breaks some single threaded assumptions within the codebase.
Order of events:
1. master powers on - begin init
2. slave powers on - begin init
3. master detects USB quickly - finish init
* as part of init finish, RGB is set to eeprom values
4. master runs `post_init` which triggers RGB sync
5. slave receives sync and sets RGB
6. slave times out on USB detect - finishes init
* as part of init finish, RGB is set to eeprom values
What you expect is that both halves share the same RGB config, however what actually happens is the slave side has the eeprom values set till the next …
=> Split - Avoid race condition during matrix_init_quantum

docs/config_options.md, docs/feature_advanced_keycodes.md, tmk_core/common/action_tapping.c
Expands on the per-key tap-hold configuration options, allowing for fine-tuned control of exactly which keys are affected by `PERMISSIVE_HOLD`.
=> New feature: PERMISSIVE_HOLD_PER_KEY

keyboards/kbdfans/kbd67/mkiirgb/v2/rules.mk
Adds support for 65_ansi_blocker community layout to KBDFans KBD67 MKIIRGB v2 maintained by @moyi4681. Tested with default keymaps and layouts/community/65_ansi_blocker keymaps.
N/A
=> Add community layout support to KBD67 MKIIRGB v2

docs/feature_macros.md, quantum/quantum.c, quantum/send_string_keycodes.h
Adds support for delays in `send_string`. Tested on an iris rev4.
Due to the lack of available codes for QMK-specific functionality, I've turned the tap/up/down (and now delay) commands into a prefix+command; for example, SS_UP was previously `\3`, it's now `\1\3`. Delay has been added as `\1\4`, as originally `\4` alone was X_A.
=> Add support for delays in send_string.

keyboards/wete/rules.mk
Including the `xB` suffix prevents qmk_compiler (and thus QMK Configurator) from compiling firmware for the Wete.
Rolling this change back until we work out a long-term solution for the suffixes.
@ramonimbao This is why Configurator can't compile your board.
=> Fix MCU rule for Wete

tmk_core/chibios.mk, tmk_core/common.mk
As ChibiOS syscalls is already used within in a few scenarios, this enables by default so that we avoid some of the issues within #7059.
Been using this for a while now and not seen issues :man_shrugging:, but then we only alloc in limited circumstances ( otherwise a lot more builds would be failing).
* Fixes #7059
* Fixes `make 1upkeyboards/sweet16/v2/proton_c:switchtester`
=> Unconditionally enable ChibiOS syscalls

docs/ws2812_driver.md, drivers/arm/ws2812_pwm.c
Based off <https://github.com/joewa/WS2812-LED-Driver_ChibiOS>, this PR aims to implement ws2812 PWM support within the new ws2812 framework.
| | Status |
|-|-|
| f072 | ? |
| f103 | :heavy_check_mark: |
| f303 | :heavy_check_mark: |
| f401/f411 | :heavy_check_mark: |
1. I have added a non documented `WS2812_PWM_TARGET_PERIOD` option
* the original code seems to use a 10x larger value, but does not work with the testing i've done so far
* if required, board maintainers can use whatever value works for them
=> PWM DMA based RGB Underglow for STM32

quantum/quantum.c
* doesnt happen with clang-format-8
* not easy to get into the environment
* doesnt happen on 7 if i remove a comment...
* fragile so something to keep an eye on
* maybe need to change the process to catch this sort of error in the future
=> Fix recent clang-format breaking quantum.c

tmk_core/common/chibios/printf.c, tmk_core/common/chibios/printf.h
When adding encoders to a board, while console is enabled, the following error is thrown
```console
Compiling: quantum/encoder.c                                                                       In file included from tmk_core/common/print.h:76:0,
from tmk_core/common/debug.h:22,
from quantum/keymap.h:35,
from quantum/quantum.h:30,
from quantum/encoder.h:20,
from quantum/encoder.c:18:
tmk_core/common/chibios/printf.h:107:16: error: conflicting types for 'tfp_printf'
#define printf tfp_printf
^
tmk_core/common/chibios/printf.h:102:6: note: previous declaration of 'tfp_printf' was here
void tfp_printf(char* fmt, ...);
^~~~~~~~~~
tmk_core/common/chibios/printf.h:108:17: error: conflicting types for 'tfp_sprintf'
#define sprintf tfp_sprintf
^
tmk_core/common/chibios/printf.h:103:6: note: …
```
=> Short term fix for conflicting types for 'tfp_printf'

quantum/backlight/backlight_avr.c
**Would advise diff ignore whitespace due to the clang-format stuff on all the ifdefs.**
=> Refactor AVR backlight

keyboards/handwired/onekey/keymaps/reset/keymap.c
Adds a simple keymap for `handwired/onekey` to be able to perform resets to bootloader.
Tested on Proton C.
=> Add onekey keymap for testing reset to bootloader

keyboards/bpiphany/frosty_flake/config.h, keyboards/bpiphany/frosty_flake/frosty_flake.c, keyboards/bpiphany/frosty_flake/frosty_flake.h, keyboards/bpiphany/frosty_flake/matrix.c, keyboards/bpiphany/frosty_flake/rules.mk
This pull request comprises three individual commits with their own descriptions, copied below.
This commit replaces frosty_flake's custom matrix and debounce logic
with a "lite" custom matrix. In addition to being somewhat clearer, this
allows a consumer of the flake board to choose their own debouncing
algorithm. The one closest to the implementation originally in use is
sym_g, but this opens us up to supporting eager_pk and eager_pr.
The original matrix code was 18 columns for 8 rows, but using a single
row read and unpacking the bits into individual columns. To simplify,
I've changed the key layout to be 8C 18R instead of 18C 8R: this lets us
use a single read directly into the matrix _and_ drop down to a uint8_t
instead of a uint32_t for matrix_row_t.
Since we're no longer …
=> Rewrite the Bathroom Epiphanies Frosty Flake matrix and LED handling

docs/isp_flashing_guide.md
Hopefully, clarify a lot of the process, and add additional, useful information to the guide.
=> [Docs] Update ISP Flashing guide

keyboards/at_at/660m/config.h, keyboards/cannonkeys/an_c/config.h, keyboards/cannonkeys/chimera65/config.h, keyboards/cannonkeys/instant60/config.h, keyboards/cannonkeys/iron165/config.h, keyboards/cannonkeys/ortho48/config.h, keyboards/cannonkeys/ortho60/config.h, keyboards/cannonkeys/ortho75/config.h, keyboards/cannonkeys/practice60/config.h, keyboards/cannonkeys/practice65/config.h, keyboards/cannonkeys/satisfaction75/config.h, keyboards/cannonkeys/savage65/config.h, keyboards/cannonkeys/tmov2/config.h, keyboards/handwired/bluepill/bluepill70/config.h, keyboards/handwired/ck4x4/config.h, keyboards/hid_liber/config.h, keyboards/jm60/config.h, keyboards/k_type/config.h, keyboards/projectkb/alice/config.h, keyboards/wete/config.h, keyboards/xiaomi/mk02/config.h
Since ChibiOS now shares its descriptors with LUFA in usb_descriptor.c, this hack no longer exists, and these comments serve no purpose.
https://github.com/tmk/tmk_core/blob/437115bf1f623d19986f8375fe6c6aae52e1d406/protocol/chibios/usb_main.c#L562
*
=> Remove "ugly hack in usb_main.c" comments

keyboards/namecard2x4/rules.mk
BOOTLOADER needs to be defined as `caterina` because namecard2x4 keyboard uses avrdude for flasher.
tag: @takashiski
=> Fix bootloader definition for namecard2x4 keyboard

keyboards/1upkeyboards/super16/config.h, keyboards/1upkeyboards/super16/rules.mk, keyboards/1upkeyboards/super16/super16.c
The Super16 keyboard from 1upkeyboards appears to have per key RGB via "helix style mounted" WS2812 LEDs.  So it makes more sense to use the RGB matrix, as this allows for better animations on the macropad. 
Tested by sirknighting on discord.
=> [Keyboard] Switch to RGB Matrix for Super16

keyboards/wete/config.h, keyboards/wete/rules.mk
Add RGB lighting support through one of the free pins on the board.
*
=> [Wete] Add RGB lighting through one of the free pins

drivers/boards/BLACKPILL_STM32_F401/board.c, drivers/boards/BLACKPILL_STM32_F401/board.h, drivers/boards/BLACKPILL_STM32_F401/board.mk, drivers/boards/BLACKPILL_STM32_F401/bootloader_defs.h, drivers/boards/BLACKPILL_STM32_F401/cfg/board.chcfg, drivers/boards/BLACKPILL_STM32_F401/cfg/board.fmpp, drivers/boards/BLACKPILL_STM32_F411/board.c, drivers/boards/BLACKPILL_STM32_F411/board.h, drivers/boards/BLACKPILL_STM32_F411/board.mk, drivers/boards/BLACKPILL_STM32_F411/bootloader_defs.h, drivers/boards/BLACKPILL_STM32_F411/cfg/board.chcfg, drivers/boards/BLACKPILL_STM32_F411/cfg/board.fmpp, keyboards/handwired/onekey/blackpill_f401/chconf.h, keyboards/handwired/onekey/blackpill_f401/config.h, keyboards/handwired/onekey/blackpill_f401/halconf.h, keyboards/handwired/onekey/blackpill_f401/mcuconf.h, keyboards/handwired/onekey/blackpill_f401/readme.md, keyboards/handwired/onekey/blackpill_f401/rules.mk, keyboards/handwired/onekey/blackpill_f411/chconf.h, keyboards/handwired/onekey/blackpill_f411/config.h, keyboards/handwired/onekey/blackpill_f411/halconf.h, keyboards/handwired/onekey/blackpill_f411/mcuconf.h, keyboards/handwired/onekey/blackpill_f411/readme.md, keyboards/handwired/onekey/blackpill_f411/rules.mk
<https://www.cnx-software.com/2019/12/24/stm32-black-pill-board-features-stm32f4-cortex-m4-mcu-optional-spi-flash/>
* Cheap
* USB C
* Lots of flash
=> Add f401 and f411 blackpill examples

keyboards/clueboard/66/rev4/rev4.c, keyboards/clueboard/66/rev4/rules.mk
Issue found within #7959 and #8292.
Another instance of backlight code existing without custom driver being used. Given the functions are just comments, I figured it best to just remove.
Tagging @skullydazed.
=> Remove stub backlight functions from clueboard/66/rev4

quantum/backlight/backlight.c, quantum/backlight/backlight.h, quantum/backlight/backlight_arm.c, quantum/backlight/backlight_avr.c, quantum/backlight/backlight_soft.c
To make something like #8291 not introduce a 3rd duplicate copy of some backlight functionality, this PR aims to move more backlight logic to a common location.
=> Refactor more backlight to a common location

tmk_core/common/uart.c
Slight correction to #7628 (`UCSRB` -> `UCSRnB` and `UDR0` -> `UDRn`), and adding the 32A to the defines (untested) The 32A is a bit odd as the high byte of the baud rate register `UBRR` shares the same memory location as the control/status register C (`UCSRC`). The MSB `URSEL` is used to choose between them. I'm doubtful those top three bits are really used so I just switched the define to use the low byte.
*
=> Fix typo in uart.c backport and add 32A "support"

shell.nix, tmk_core/avr.mk
AVR `CFLAGS`/`ASFLAGS` were unconditionally used for all targets, even if they were targeting Arm. This limits the scope to those variables to AVR-specific, as the normal Arm compiler included in Nix actually has these set correctly.
* #8241
=> Fix up Arm builds with nix-shell.

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
A duet of functions to facilitate sophisticated graphical displays such as time series graphing using the OLED library.
A function to pan the contents of an OLED display left or right by manipulating the buffer. This is distinct from the scrolling features provided by the driver in that the program can control speed by panning the display column by column.
A function to write a byte at an arbitrary index of the OLED display buffer to allow for modifying discreet areas of the display.
=> Buffer based OLED panning, write byte to buffer at arbitrary index

lib/python/qmk/cli/doctor.py
Per title, basic version detection so we can warn users with gcc 9. Also outputs the version number of both to aid troubleshooting.
=> Add gcc version detection to qmk doctor

quantum/keymap_extras/keymap_colemak.h, quantum/keymap_extras/keymap_dvorak.h, quantum/keymap_extras/keymap_workman.h, quantum/keymap_extras/sendstring_colemak.h, quantum/keymap_extras/sendstring_workman.h
Now on to some more keymap_extras stuff. The `KC_` prefixed aliases have been deprecated as they are an artifact of the old macro system and `_kc` layouts.
*
=> Update Dvorak, Colemak and Workman keycode aliases

keyboards/cu80/rules.mk
This pull request will enable bootmagic lite for the CU80.
This is helpfull, because the reset switch is located inside the case which needs to be opened.
*
=> Enable bootmagic lite for CU80

docs/config_options.md, docs/feature_rgblight.md, quantum/rgblight.c, quantum/rgblight.h
This PR introduces a new feature I'm calling lighting layers. This feature allows users to define multiple independent layers of lighting that can be toggled on and off individually, making it easy to use your RGB lighting to indicate things like active keyboard layer & modifier state. (This is valuable to many of us who have RGB lights but no status LEDs.)
Here's a video demo:
https://youtu.be/uLGE1epbmdY
I'm aware that there are existing solutions to the "change colors when you change layers" problem, but having tried them out I can say that this is really much nicer. Each lighting layer can be toggled independently, so the user doesn't need to track a bunch of state. Multiple lighting layers can be active at the same time. Lighting layers don't interfere with lighting animations, so …
=> Feature: RGBLight layers

build_json.mk, docs/cli.md, docs/ja/cli.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/json/keymap.py, lib/python/qmk/cli/json2c.py
Per title, rename for consistency with other and future commands. Should also make this functionality easier to find for people who want to use configurator to generate `keymap.c` files.
=> Rename qmk json-keymap to qmk json2c

docs/adc_driver.md, drivers/arm/analog.c, drivers/arm/analog.h
Adds some spartan ADC support for STM32F0 and STM32F3 devices.
N/A
If someone could point me in the right direction for adding ADC tests, I'd be happy to. Not sure how an ADC test would work though.
=> Add ADC support for STM32F3 and STM32F0 devices

keyboards/mxss/rgblight.h
PR #7773 caused a build error for `mxss:default`, I made similar changes to 'keyboards/mxss/rgblight.h' as #7773 did to 'quantum/rgblight.h'.
**This commit does not change the build result.**
Testing script
```shell
git checkout 0.8.24
echo master > /tmp/master_md5.txt
make mxss:default:clean
make mxss:default
md5 mxss_default.hex >> /tmp/master_md5.txt
git checkout fix-keyboards-mxss-rgblight.h
echo fix-keyboards-mxss-rgblight.h > /tmp/branch_md5.txt
make mxss:default:clean
make mxss:default
md5 mxss_default.hex >> /tmp/branch_md5.txt
diff -u /tmp/master_md5.txt /tmp/branch_md5.txt
```
Test result:
```
--- /tmp/master_md5.txt 2020-03-12 05:51:39.000000000 +0900
+++ /tmp/branch_md5.txt 2020-03-12 05:51:49.000000000 +0900
@@ -1,2 +1,2 @@
-master
+fix-keyboards-mxss-rgblight.h
MD5 …
```
=> fix keyboards/mxss/rgblight.h

common_features.mk, docs/eeprom_driver.md, drivers/eeprom/eeprom_stm32_L0_L1.c, drivers/eeprom/eeprom_stm32_L0_L1.h
Adds support for chip-based EEPROM for STM32L0 and L1, using the default "vendor" driver.
Tested with STM Nucleo boards, both L0xx and L1xx function as intended.
=> Add support for STM32L0/L1 onboard EEPROM.

keyboards/kmac/rules.mk
Looks like I was a little bit overreaching during #8044 (double checked the others and they seem fine).
Verified by `@ramnes#6786` on Discord.
=> Enable custom backlight driver for kmac

lib/python/qmk/cli/json2c.py
Currently the `qmk json2c -o <file>` command outputs relative to `qmk_firmware`. It should output relative to the current directory instead.
=> Use qmk.path.normpath to locate the output file for json2c

docs/feature_mouse_keys.md, tmk_core/common/mousekey.c, tmk_core/common/mousekey.h
In accelerated mode, MOUSEKEY_INTERVAL is used for both the cursor and the wheel. Since the step for the wheel is way higher than the step for the cursor, this results in the wheel being almost unusable. See issue #3370 for example.
In this change, I decoupled the cursor and the wheel behaviors (using the decoupling pattern in the constant mode). I also introduced 2 settings:
- MOUSEKEY_WHEEL_DELAY
- MOUSEKEY_WHEEL_INTERVAL
which are the equivalent of MOUSEKEY_DELAY and MOUSEKEY_INTERVAL. Users can therefore choose different values for the cursor and the wheel (typically you would want MOUSEKEY_WHEEL_INTERVAL to be a lot greater than MOUSEKEY_INTERVAL to have a not-too-fast wheel mouvement. The default values work fine for me).
* fixes #1434
* fixes #3370
=> Decouple mouse cursor and mouse wheel in accelerated mode

lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/compile.py, lib/python/qmk/cli/flash.py, lib/python/qmk/cli/json/keymap.py, lib/python/qmk/cli/list/keymaps.py, lib/python/qmk/cli/new/keymap.py, lib/python/qmk/commands.py, lib/python/qmk/decorators.py, lib/python/qmk/path.py
Based on @Erovia's brilliant POC I've created two decorators that can be used to determine keyboard or keymap names from the user's current working directory.
=> Add decorators for determining keyboard and keymap based on current directory

quantum/dynamic_keymap.c
#8244 broke VIA macro handling by changing the protocol of `send_string()`
This PR fixes it by maintaining the original protocol and translating to the new protocol, so we can defer VIA and existing firmware getting out of sync until a major version upgrade of VIA and VIA protocol.
*
=> Realign dynamic macros with recent SEND_STRING changes

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
Added two functions to set scroll speed and region for hardware scrolling. These two functions set three bytes in memory which are used in the command sent to start scrolling in: 
`oled_scroll_left()` and `oled_scroll_right()`
=> Adding OLED scroll setup functions

tmk_core/protocol/chibios/main.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/main.c
Remove `#Include "rgblight.h"` from the following files. Because the #7733 removed the call to `rgblight_task()`.
* tmk_core/protocol/chibios/main.c
* tmk_core/protocol/lufa/lufa.c
*  tmk_core/protocol/vusb/main.c
~see #8380 for tmk_core/protocol/vusb/main.c.~
=> Remove unnecessary import of rgblight.h in tmk_core/protocol/*/*.c

docs/cli_commands.md, docs/feature_userspace.md
Introduced in #7402, but unless documented it doesnt exist...
=> Document 'make all:<name>'

quantum/keymap_extras/keymap_br_abnt2.h, quantum/keymap_extras/sendstring_br_abnt2.h
=> Update Brazilian keymap and add sendstring LUT

quantum/keymap_extras/keymap_italian.h, quantum/keymap_extras/sendstring_italian.h
🇮🇹
Amazingly, there is no way to input <code>&#96;</code> or `~` with this layout, at least on Windows. Thus they have been marked as `KC_NO` in the LUT.
https://superuser.com/questions/667622/italian-keyboard-entering-the-tilde-and-backtick-characters-without-cha
*
=> Update Italian keymap and add sendstring LUT

keyboards/massdrop/alt/keymaps/emptyflask/README.md, keyboards/massdrop/alt/keymaps/emptyflask/config.h, keyboards/massdrop/alt/keymaps/emptyflask/keymap.c
Customized Drop ALT config:
* Tap caps lock for ESC, hold for CTRL
* Prefer grave/tilde to dedicated ESC key
* Swap home and delete. It's more compatible with my keycaps, and closer to a traditional layout.
* Numpad layer (FN-\ to enable)
* Method for clearing all stuck-down mods (taken from favorable-mutation, for tapped modifiers)
* Switch between QWERTY, Colemak, Dvorak, Workman layouts using FN-/ plus one of [Q,C,D,W]
=> [Keymap] New Massdrop ALT keymap for emptyflask

docs/feature_rgblight.md
Update feature_rgblight.md to note that for split dual-mcu boards, 
both sides must be flash to get the new value of the rgblight_layers.
https://github.com/qmk/qmk_firmware/pull/7768#issuecomment-600237611
=> [docs] Note the need to flash both sides for rgb layers.

lib/python/qmk/cli/json/keymap.py
The `json-keymap` subcommand was deprecated in #8372.
The new command `json2c` is right under it with the same description.
In order to avoid confusion, this one should be hidden until we remove it.
*
=> CLI: Hide json-keymap subcommand, as it's been deprecated.

keyboards/choco60/keymaps/default/keymap.c
Several Choco60 owners have reported that the RESET assignment conflicts with some key combinations. This change is to reduce their confusion.
This PR is related to #8448
=> Update default keymap for Choco60

.vscode/settings.json
This makes highlighting work in Visual Studio Code when adding custom RGB matrix effects by following these instructions: https://beta.docs.qmk.fm/using-qmk/hardware-features/lighting/feature_rgb_matrix#custom-rgb-matrix-effects-id-custom-rgb-matrix-effects
=> Highlight .inc files as .c files

keyboards/palette1202/config.h, keyboards/palette1202/keymaps/default/keymap.c, keyboards/palette1202/readme.md
fixed keymap to fix encoder rotate direction.
Palette1202's encoder rotate direction was not correct (due to QMK Firmware's change of encoders support)
So that, fixed keymap to follow QMK's change.
(and changed readme in URL of hardware availability)
=> Palette1202 fix encoder rotate direction

docs/_summary.md, docs/feature_advanced_keycodes.md, docs/feature_layers.md, docs/feature_leader_key.md, docs/feature_rgblight.md, docs/keycodes.md
Expands the documentation to include a bunch of the layer functions, and callbacks.  
Note:  I don't like that "mods" is still on this page, and feel it should be moved. However, I'm not sure where, or if it should. 
Additionally, I feel that it may be a good idea to move the entire layer change code section into this document, instead. 
And ... it may be best to move the layer stuff to `function_layer.md` and just be done with it.
=> [Docs] Update layer documentation

docs/feature_bootmagic.md, quantum/quantum.c, quantum/quantum.h, quantum/via.c, tmk_core/common.mk, tmk_core/common/bootmagic_lite.c
Pulled the bootmagic logic into its own file. And to avoid implementing the logic in 2 places, I have merged the via override logic in.
=> Add support for Bootmagic lite when using SPLIT_HAND_PIN

quantum/template/avr/rules.mk
It's rarely needed - apart from the LFK65 HS (which seems like it could be QMK-DFU?), there isn't a single AVR board in the repo that has an unknown/unsupported bootloader.
*
=> Remove BOOTLOADER_SIZE stuff from template

docs/feature_macros.md, docs/understanding_qmk.md, quantum/quantum.c, quantum/quantum.h, tmk_core/common/action.c, tmk_core/common/action.h
This adds `post_process_record_*` in addition to `process_record_*`, so that you can run cleanup/handling AFTER a keystroke has been sent. 
This code was developed by @colinta, and pursued by myself after conversations on Discord.
This also moves the "report to keycode" code to a separate function, that can be called elsewhere, since it is being used by both `process_record_quantum()` and `post_process_record_quantum()` now. (`get_record_keycode` and `get_event_keycode`)
Also, I updated the formatting of the touched files to follow the Contributing documentation. 
* fixes #2098
=> Add Post Processing to process_record

keyboards/minidox/keymaps/bepo/config.h, keyboards/minidox/keymaps/bepo/keymap.c, keyboards/minidox/keymaps/bepo/readme.md
Add bepo (french) layout to keyboard Minidox
*
=> [Keymap] Minidox Bepo layout

keyboards/handwired/onekey/blackpill_f401/config.h, keyboards/handwired/onekey/blackpill_f411/config.h, keyboards/handwired/onekey/bluepill/config.h, keyboards/handwired/onekey/elite_c/config.h, keyboards/handwired/onekey/keymaps/adc/config.h, keyboards/handwired/onekey/keymaps/adc/keymap.c, keyboards/handwired/onekey/promicro/config.h, keyboards/handwired/onekey/proton_c/config.h, keyboards/handwired/onekey/stm32f0_disco/config.h, keyboards/handwired/onekey/teensy_2/config.h, keyboards/handwired/onekey/teensy_2pp/config.h
And corrected the matrix pinout for the Proton C onekey. A3 is one of the midboard pads.
*
=> Set backlight and RGB pins for AVR onekeys

tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/arm_atsam/usb/conf_usb.h, tmk_core/protocol/arm_atsam/usb/main_usb.c, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.h, tmk_core/protocol/arm_atsam/usb/usb_main.h
* Added 300 ms timeout for the led indicators for Massdrop CTRL
* Added raw HID support together with a very stupid test program linked in the readme. My plan is to write a proper configurator a la VIA, but this is a good starting point as CTRL (and ALT) lacked this arm_atsam functionality.
The code is originally authored by @helluvamatt and I saw that @ash0x0 also has interest in these things.
=> Add RawHID support to ATSAM (Massdrop boards)

docs/newbs_getting_started.md
`python3-pip` drags in the MSYS Python 3.7, and the CLI gets installed to the wrong place. After `qmk_install.sh` completes, MinGW64 Python 3.8 and its pip (`mingw-w64-x86_64-python3-pip`) will be the default.
However it seems to be not enough to only install the latter package instead; `mingw-w64-x86_64-toolchain` is also necessary, otherwise pip will fail trying to install `coverage`. This is because it contains some C extensions that must be compiled.
*
=> Fix wrong python-pip package for MSYS setup instructions

tmk_core/common/avr/sleep_led.c, tmk_core/protocol/vusb/main.c
Stole some logic from backlight code, compiles :man_shrugging:.
* this allows for fixing potential timer conflicts on platforms with more than 1 timer
=> Enable SLEEP_LED on ATmega32A 

quantum/keymap_extras/keymap_italian.h
Found by ZSA.
This is defined on line 48 (as `KC_MINS`), and again, lower down. If this file is included, it will fail to compile.
=> Fix IT_APOS backward compatibility define in keymap_italian.h

keyboards/xd60/rev2/config.h, keyboards/xd60/rev3/config.h
The XD60's backlight is on a non-hardware PWM pin, so the recent breaking change to the default value of `BACKLIGHT_ON_STATE`... has broken it.
* Fixes #8573
=> Fix inverted backlight for XD60

keyboards/hhkb/keymaps/dbroqua/keymap.c, keyboards/hhkb/keymaps/dbroqua/readme.md
Removed _ADJUST layout and integrate move directly on _FN layout.
=> Cleaning dbroqua's HHKB layout

keyboards/xd87/config.h
The XD87's backlight is on a non-hardware PWM pin, therefore the change to the default value of `BACKLIGHT_ON_STATE` has broken it.
=> Fix inverted backlight for XD87

tmk_core/protocol/vusb/main.c, tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h
Add hid_raw feature to keyboard with USB. 
Currently,  I had tested on atmega328p.   
Would anyone test on other VUSB MCU?
Test method is here.  https://github.com/qmk/qmk_firmware/issues/8320#issuecomment-597762268
This feature is not available with  mousekey / extrakey.
~I will remove draft flag after #8321 merged.~
* #8320
=> add hid_raw feature to VUSB

quantum/keymap_extras/keymap_latvian.h, quantum/keymap_extras/sendstring_latvian.h
=> Add Latvian keymap and sendstring LUT

tmk_core/avr.mk, tmk_core/chibios.mk
Facilitates a tighter integration of custom bootloader flash utils, eg within #8598.
There were no use cases left in the repo, or docs for `:program` so I also removed that handling as its superseded by the more consistent `:flash`.
=> Migrate :program logic to :flash

tmk_core/protocol/vusb/usbconfig.h, tmk_core/protocol/vusb/vusb.c
Currently the general template has `usbFunctionWriteOut()` disabled which is necessary for raw_hid. It looks like one cannot easily overwrite usbconfig.h. I suggest enabling it in general as it does no harm. If raw_hid is not defined it is an empty function.
Also while I am here, `usbFunctionWriteOut()` has a delay and a usbPoll which are unnecessary. there is no need to Poll after you have set a usb interrupt.
*
=> Updated V-USB template to allow usbFunctionWriteOut

quantum/keymap_common.c, quantum/quantum.c, tmk_core/common/action.c, tmk_core/common/action_layer.h, tmk_core/common/util.c, tmk_core/protocol/vusb/vusb.c
=> Strip out features to allow minimum firmware sizes

tmk_core/common/progmem.h
Since we read a `void *` at `address_short`, and are dereferencing it, it must be a *pointer* to the void pointer.
Thanks to @sigprof for correcting my original attempt.
* RGB layer lighting reported not compiling by @stanrc85 on Discord - this appears to fix their problem
=> Fix `pgm_read_ptr()` define for ARM

drivers/avr/ws2812.c, drivers/avr/ws2812.h, keyboards/ergodox_ez/led_i2c.c
Prerequisite for #8598.
Aligned calls with logic within `config_common.h`.
Should also allow 32a support too (though I have not tested this).
=> Fix AVR ws2812 when ADDRESS_BASE is non zero

keyboards/dz60/rules.mk
Simply adds the 60_tsangan_hhkb layout to the dz60 rules file. The actual layout implementation was already there.
=> Add 60_tsangan_hhkb layout to dz60

keyboards/gh60/revc/revc.h, keyboards/gh60/revc/rules.mk
This adds the 60_tsangan_hhkb layout to the rules file and implements it in the keyboard's header file.
=> Add 60_tsangan_hhkb layout to gh60

keyboards/1upkeyboards/sweet16/config.h, keyboards/1upkeyboards/sweet16/keymaps/via/keymap.c, keyboards/1upkeyboards/sweet16/keymaps/via/rules.mk, keyboards/1upkeyboards/sweet16/v1/config.h, keyboards/1upkeyboards/sweet16/v2/promicro/config.h, keyboards/1upkeyboards/sweet16/v2/proton_c/config.h
VIA support for v1 and v2 editions of the sweet16. Tested on a elite C v1.
=> VIA Support: 1upkeyboards Sweet16

keyboards/hhkb/hhkb.h, keyboards/hhkb/rules.mk
This updates the hhkb keyboard such that it satisfies the `60_hhkb` layout. I implemented this in the most minimal way possible with a simple `#define LAYOUT_60_hhkb LAYOUT`, though if this is frowned on, I can update all instances of `LAYOUT` to be `LAYOUT_60_hhkb` instead.
=> [Keyboard] Add 60_hhkb layout to hhkb

tmk_core/protocol/vusb/main.c, tmk_core/protocol/vusb/vusb.c
Backport from tmk/tmk_keyboard@391c979be751eaf113c8f53c36644a6bb6ff12f6
I don't have any vusb boards to test this one, so it may need somebody like @mechmerlin to test it.
=> V-USB remote wakeup

lib/python/qmk/cli/doctor.py
```
255 fauxpark@marissa:qmk_firmware$ bin/qmk doctor           
Ψ Detected macOS.
Ψ All dependencies are installed.
Ψ Found avrdude version 6.3
Ψ Found dfu-util version 0.9
Ψ Found dfu-programmer version 0.7.2
Ψ Found arm-none-eabi-gcc version 8.3.1
Ψ Found avr-gcc version 8.4.0
Ψ Submodules are up to date.
Ψ QMK is ready to go
```
* Fixes #8684
=> Doctor: Add avrdude/dfu-util/dfu-programmer version printing

keyboards/acheron/austin/chconf.h, keyboards/acheron/keebspcb/chconf.h, keyboards/at_at/660m/chconf.h, keyboards/candybar/chconf.h, keyboards/cannonkeys/an_c/chconf.h, keyboards/cannonkeys/chimera65/chconf.h, keyboards/cannonkeys/instant60/chconf.h, keyboards/cannonkeys/iron165/chconf.h, keyboards/cannonkeys/satisfaction75/chconf.h, keyboards/cannonkeys/savage65/chconf.h, keyboards/cannonkeys/tmov2/chconf.h, keyboards/cheshire/curiosity/chconf.h, keyboards/handwired/ck4x4/chconf.h, keyboards/handwired/onekey/stm32f0_disco/chconf.h, keyboards/projectkb/alice/chconf.h, keyboards/retro_75/chconf.h, keyboards/wete/chconf.h, keyboards/xiaomi/mk02/chconf.h
Using malloc/rand on these boards crashes. This is due to the default stub syscall implementation always returning 0. This is just a short term alignment of files, and a longer term solution will follow.
=> Enable memcore to fix malloc/rand crashes

tmk_core/protocol/vusb/usbconfig.h, tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h
…able
As with the LUFA/ChibiOS descriptors, the device/interface class/subclass/protocol does not need to be configurable, so we can safely hardcode it in the descriptors. V-USB is also aware of `F_CPU` and so `USB_CFG_CLOCK_KHZ` is not necessary either.
*
=> V-USB: Remove some stuff from usbconfig.h that should not be configurable

keyboards/fortitude60/keymaps/default/config.h, keyboards/fortitude60/rev1/config.h
When "split_common" was introduced in Fortitude 60, it did not work perfectly because it did not have the option to detect USB connections.
=> Fixed a bug caused by "split_common" in Fortitude 60.

quantum/via.c, quantum/via.h
Allow override of the layout options default value. This requires advanced knowledge of how VIA stores layout options and is only really useful for setting a boolean layout option state to true by default.
*
=> Configurable VIA layout options default value

docs/coding_conventions_c.md
In #6316 we agreed that, in the long term, preprocessor directives should be indented using the `BeforeHash` style. However, we are using `AfterHash` for the time being until versions of clang-format that support the former option are more widely available.
As mentioned in #8664, there is a discrepancy between the coding conventions doc and the current `.clang-format` configuration, which is causing some confusion. This updates the conventions to match that configuration for the time being.
* resolves #8664
=> Update C coding conventions to match .clang-format config for indenting PP directives

docs/_summary.md, docs/de/_summary.md, docs/es/_summary.md, docs/fr-fr/_summary.md, docs/he-il/_summary.md, docs/ja/_summary.md, docs/pt-br/_summary.md, docs/ru-ru/_summary.md, docs/spi_driver.md, docs/zh-cn/_summary.md, drivers/avr/spi_master.c, drivers/avr/spi_master.h, tmk_core/protocol/lufa.mk, tmk_core/protocol/lufa/adafruit_ble.cpp
Pulling the SPI code up out of the BLE stuff so we can reuse it. Also replaced as much of the AVR-specific code as I could see, to facilitate Arm support by simply dropping in an appropriate spi_master.
Feel free to point out any dumb mistakes.
* fixes #3187
=> spi_master for AVR

keyboards/tkc1800/keymaps/yanfali/rules.mk, layouts/community/60_tsangan_hhkb/yanfali_wkl/keymap.c, users/yanfali/rules.mk, users/yanfali_wkl
Personal keymap updates for WKL and upcoming TKC1800 changes
*
=> Updates to personal keymaps

docs/feature_ps2_mouse.md, tmk_core/protocol/ps2_mouse.c
=> Add PS2_MOUSE_ROTATE to compensate for device orientation

keyboards/massdrop/ctrl/keymaps/default/keymap.c
This is just an "aesthetic" change, to use more modern code for detecting the states of the main modifiers.
Makes use of the `MOD_MASK_` macros instead of the expanded expressions when dealing with the modifier keys.
Others should be able to see this and incorporate it in their own Massdrop layouts. The old model was:
```c
#define MODS_SHIFT  (get_mods() & MOD_BIT(KC_LSHIFT) || get_mods() & MOD_BIT(KC_RSHIFT))
#define MODS_CTRL  (get_mods() & MOD_BIT(KC_LCTL) || get_mods() & MOD_BIT(KC_RCTRL))
#define MODS_ALT  (get_mods() & MOD_BIT(KC_LALT) || get_mods() & MOD_BIT(KC_RALT))
```
vs 
```c
#define MODS_SHIFT  (get_mods() & MOD_MASK_SHIFT)
#define MODS_CTRL   (get_mods() & MOD_MASK_CTRL)
#define MODS_ALT    (get_mods() & MOD_MASK_ALT)
```
* 
Suggested by @ash0x0 at #8692.
=> Simplify ctrl, shift, alt mods detection for Massdrop CTRL

quantum/debounce/eager_pk.c, quantum/debounce/eager_pr.c, tmk_core/common/timer.h
This PR makes 3 main changes
1) The TIMER_DIFF* macros calculated wrong values after timer overflow (1 less)
2) Improves code generation efficiency for TIMER_DIFF* macros (smaller, faster code)
3) The eager_pr, and eager_pk debounce algorithms had a serious problem with how they tracked time.
For details please see each commit message in turn.
* 
NOTE: I have tested the changes using a atmega32u4 devboard, with some synthetic tests. I have not tested with an actual keyboard.
=> Various fixes to how timer differences are calculated

keyboards/helix/rev2/keymaps/default/keymap.c, keyboards/helix/rev2/keymaps/five_rows/keymap.c
Since #7773, the mode number of RGBlight is no longer displayed on the Helix OLEDs. I fixed this.
=> [Keymap] fix OLED display on Helix keyboard keymaps default and five_rows

docs/feature_debounce_type.md, quantum/debounce/eager_pk.c, quantum/debounce/sym_pk.c
Added sym_pk debounce algorithm
sym_pk is debouncing per key. On any state change, a per-key timer is set. When DEBOUNCE milliseconds of no changes have occured on that key, the key status change is pushed.
* 
NOTE: I have only tested this on a pro micro devboard, by touching some exposed pins, and having it pick up noise. I have not tested this on a real keyboard.
=> quantum/debounce: Added sym_pk debounce algorithm

util/linux_install.sh
GCC 4.9.4 is no longer available on Gentoo (or Sabayon), which causes
problems when attempting to install on either of these platforms. Since
QMK is not particularly sensitive to its GCC version, modify the version
restriction to <9 so newer versions of GCC may be installed.
Additionally, drop the Python installation as part of the Gentoo
installation process. Python is a core system package on Gentoo and can
therefore be assumed to be present; in addition, the slot restriction of
3.5 which was present is also no longer available in Gentoo.
Finally, separate the gcc rebuild invocation of `emerge` from the new
packages that may need to be installed, and apply the `--noreplace` flag
to new packages so that they are not rebuilt if already present.
None
=> Upgrade gcc version/tweak package installs in Gentoo installation

docs/ref_functions.md
I was reading [Useful Functions - (OLKB) Tri Layers](https://docs.qmk.fm/#/ref_functions?id=olkb-tri-layers) and was having a hard time understanding `update_tri_layer(x, y, z)` until I actually went and read the code implementing the function.
This change just fixes a couple of typos that I think will help folks to understand this more readily.
=> Fix a couple of confusion-inducing documentation typos

keyboards/handwired/bdn9_ble/bdn9_ble.c, keyboards/handwired/bdn9_ble/bdn9_ble.h, keyboards/handwired/bdn9_ble/config.h, keyboards/handwired/bdn9_ble/info.json, keyboards/handwired/bdn9_ble/keymaps/default/keymap.c, keyboards/handwired/bdn9_ble/readme.md, keyboards/handwired/bdn9_ble/rules.mk
Add BDN9-BLE, a handwired BDN9 macropad modified to add Bluetooth.
=> [Keyboard] Add handwired BDN9-BLE

docs/_summary.md, docs/platformdev_chibios_earlyinit.md, tmk_core/protocol/chibios/init_hooks.h, tmk_core/protocol/chibios/main.c, tmk_core/rules.mk
ChibiOS board files aren't normally able to be overridden without making duplicates of the definitions, and modding them.
This PR introduces some new API methods and provides a way to override the initialisation files such that hooking the early bootup sequence can be achieved whilst retaining the original ChibiOS board definitions.
Effective changes, replacing modifications for each board definition's `board.c`:
- `__early_init` has been overridden, and now has qmk api equivalents `early_hardware_init_pre` and `early_hardware_init_post`
- `boardInit` has been overridden, and now has qmk api equivalent `board_init`
See documentation for notes on the constraints for usage -- any board developer that has previously overridden these will likely know the constraints already.
=> Add support for hardware and board initialisation overrides.

.vscode/settings.json
Some of the docs pages require two trailing spaces on lines to ensure a line break occurs, but does not result in a new paragraph or new list item.
=> Allow trailing whitespace in markdown docs, for formatting purposes.

docs/spi_driver.md, drivers/avr/spi_master.c, drivers/avr/spi_master.h, tmk_core/protocol/lufa/adafruit_ble.cpp
There were a few issues with the SPI configuration on AVR, with wrong registers being written.
This fixes those, but also removes the external timeout parameters as it's a synchronous protocol.
=> Fix AVR SPI parameter configuration, remove timeouts

lib/python/qmk/commands.py
Current makefiles aren't portable, so we should invoke gmake on FreeBSD. Arguable, this is likely the same scenario in other BSD variants, but I don't see any install scripts for this in `util/` so it seems safe to only check for FreeBSD here.
* Running `qmk compile` on FreeBSD currently fails, lots of errors from "standard make" failing to load the non-portal makefiles.
=> CLI: Invoke gmake on FreeBSD when using `qmk compile`.

keyboards/mint60/config.h
define RGBLIGHT_SPLIT for Mint60.
* LED isn't synced on Mint60.
=> define RGBLIGHT_SPLIT for Mint60

docs/newbs_getting_started.md
Using just qmk setup <github_username> would fail w/ "Could not find repo github.com/<username>, whereas the repo is actually after another slash after the user name. Can consider changing code to add the default forked repo name if slash is not detected in the arg.
=> Add missing repository name to qmk setup w/ github

lib/python/qmk/cli/doctor.py
Running `qmk setup` on a fresh FreeBSD system results in an error trying to log one of the error messages to the console after failing to run `bin/qmk --version`. It looks like it is attempting to pass a tuple for the arguments, instead of individual arguments to the `error` method for logging.
Stacktrace:
```
--- Logging error ---                                                      
Traceback (most recent call last):                                         
File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit  
msg = self.format(record)                                              
File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format                                                                            
return fmt.format(record) …
```
=> CLI: Fix doctor error when can't run `bin/qmk --version`.

lib/python/milc.py
Fixes the following bugs:
* Using `action='store_true'` and `action='store_false'` did not populate the config
* Setting `args_only=True` for one subcommand would set it for all subcommands that used the same flag.
=> MILC: Fix setting config values for store_true and store_false

keyboards/keebwerk/nano_slider/keymaps/default/keymap.c
As mentioned in https://github.com/qmk/qmk_configurator/pull/675 I wanted to update the default layout in qmk_firmware, such that the default layout had a bit more functionality. 
The change adds some media controls and high F-codes to the renamed media layer. 
The custom keycodes are retained, as I think they serve as a nice jumping off point for people to make their own custom keycodes
- [] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> Improved default layout to match improved layout from configurator PR

docs/faq_debug.md, docs/flashing.md, docs/fr-fr/faq_debug.md, docs/fr-fr/flashing.md, docs/getting_started_vagrant.md, docs/ja/faq_debug.md, docs/ja/flashing.md, docs/ja/getting_started_vagrant.md, docs/reference_glossary.md, docs/zh-cn/faq_debug.md, docs/zh-cn/reference_glossary.md, tmk_core/avr.mk, tmk_core/rules.mk, util/activate_msys2.sh, util/activate_wsl.sh, util/msys2_install.sh, util/win_shared_install.sh, util/wsl_install.sh
Since it's barely used, we already have the Toolbox, and Microchip are probably unlikely to maintain FLIP.
*
=> Remove Atmel FLIP from install scripts and documentation

quantum/keymap_extras/keymap_fr_ch.h, quantum/keymap_extras/keymap_german_ch.h, quantum/keymap_extras/sendstring_fr_ch.h, quantum/keymap_extras/sendstring_german_ch.h
=> Update Swiss French/German keymaps and add sendstring LUTs

quantum/keymap_extras/keymap_french_osx.h, quantum/keymap_extras/keymap_german_osx.h, quantum/keymap_extras/sendstring_french_osx.h, quantum/keymap_extras/sendstring_german_osx.h
=> Update French and German macOS keymaps and add sendstring LUTs

quantum/keymap_extras/keymap_bepo.h, quantum/keymap_extras/sendstring_bepo.h
🇫🇷
The layout shown on https://bepo.fr differs somewhat from the layout that actually seems to be used. I used https://gitlab.com/bepo/pilotes/-/blob/master/windows/bepo.klc as a reference, it is a much more close match to what was already defined in this file (if not identical).
*
=> Update BÉPO keymap and sendstring LUT

keyboards/hineybush/hbcp/config.h, keyboards/hineybush/hbcp/matrix.c, keyboards/hineybush/hbcp/rules.mk
So my PCB manufacturer messed up. Instead of common cathode diodes like I specced (MMBD4148CC) they used dual-direction (MMBD4148SE). This posed an issue as my original COL2ROW-only firmware would not work, understandably. @nooges from Keeb.io suggested that I look at PR #8160 and try these adjustments out. I built based on that PR and the PCB with the wrong diodes worked perfectly. I added the changes to an hbcp-specific matrix.c and adjusted the configs with @drashna's help. 
I'm adding the changes here because 1. it won't affect the "correct" HBCP PCBs with common cathode diode packages and 2. anyone building their own firmware from here, or updated VIA builds, won't be done by me - so the changes should be here for anyone to access. Once #8160 is merged, I will adjust the code within …
=> [Keyboard] add dual-direction diode capability for hbcp

layouts/community/60_tsangan_hhkb/bcat/keymap.c, layouts/community/60_tsangan_hhkb/bcat/readme.md, users/bcat/rules.mk
Reworks my Tsangan layout's two function layers to make more sense for gaming (including F1-F6 keys accessible with the left hand alone).
Also turns off mouse keys for all my keyboards since I don't actually use them in any keymaps, and they interfere with sleep on Windows.
None.
=> [Keymap] Rework my Tsangan layout; turn off mousekeys

quantum/keymap_extras/keymap_belgian.h, quantum/keymap_extras/keymap_greek.h, quantum/keymap_extras/keymap_serbian.h, quantum/keymap_extras/keymap_serbian_latin.h, quantum/keymap_extras/keymap_slovenian.h, quantum/keymap_extras/keymap_swedish.h
Small corrections to Belgian (#8349), Serbian (#8560) and Slovenian (#8350) keymaps.
Namely, the Belgian keymap calls the non-dead-key degree sign `RNGA` instead of `DEG`, the Slovenian keymap does the opposite for the ring accent dead key, and the Serbian keymaps have a couple of wrong names altogether (one of them causes a multiple definition error).
/request_review @fauxpark
=> Small corrections to Belgian, Serbian and Slovenian keymaps

keyboards/maartenwut/plain60/plain60.h
Fixes the LAYOUT_60_ansi_split_bs_rshift where the key next to right shift didn't work.
Changed the plain60.h file to actually use the key next to the right shift on the LAYOUT_60_ansi_split_bs_rshift layout.
*
=> Fix Plain60 layout

docs/ja/feature_command.md
Add a Japanese translation of docs/feature_command.md.
*
=> [Docs] Japanese translation of docs/feature_command.md

tmk_core/protocol/arm_atsam/usb/conf_usb.h, tmk_core/protocol/arm_atsam/usb/main_usb.c, tmk_core/protocol/arm_atsam/usb/udi_cdc.c, tmk_core/protocol/arm_atsam/usb/udi_cdc.h, tmk_core/protocol/arm_atsam/usb/udi_device_conf.h, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.h, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd_desc.c, tmk_core/protocol/arm_atsam/usb/usb_main.h, tmk_core/protocol/arm_atsam/usb/usb_protocol_cdc.h
For some reason the ATSAM code uses these three-letter defines for NKRO/mousekeys/extrakeys/console/raw/virtser/etc, when it really doesn't need to. I also reformatted the descriptors to be more readable.
*
=> Clean up ATSAM ifdefs

keyboards/wheatfield/blocked65/config.h
Evidently there is a polycarb variant with underglow LEDs. This change should support that without negatively impacting aluminum case variant which only has 2 RGB LEDs on top.
*
=> Wheatfield Blocked65: Update RGBLED num

keyboards/vitamins_included/keymaps/default/keymap.c, keyboards/vitamins_included/rev2/config.h, keyboards/vitamins_included/rules.mk
When I initially made the keymaps for vitamins_included, I was barely familiar with qmk and the conventions. On top of that, things have also changed a bit, and features like RGBSPLIT are available (Or I entirely missed them when first making the keymap, also very posible :) )
I've:
- Enabled NKRO and added NKRO toggle keycodes to either half for legacy bios support
- Removed `AG_SWAP` and AG_NORM as the board doesn't use bootmagic
- Moved the layout keys to imo easier to remember locations
- Switched layer names to use an enum
- Enabled RBGLED_SPLIT for the rev2
=> Update vitamins included default keymap, enable NKRO, rev2 rgbsplit

keyboards/crkbd/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/config.h, keyboards/lily58/keymaps/bcat/readme.md, users/bcat/bcat.c, users/bcat/config.h, users/bcat/readme.md, users/bcat/rules.mk
* Turned on `SPLIT_USB_DETECT` in my Lily58 keymap since I'm rebuilding it with buggy Elite-C v3 controllers.
* Turned off a few more unused features in my userspace's `rules.mk` file.
* Ran `clang-format` on my userspace.
* Updated my Crkbd and Lily58 keymap readme files to make the Crkbd the "canonical" layout, as that's my daily driver. Now the Crkbd readme lists a bunch of reasons why things are laid out the way they are, and the Lily58 readme just lists the delta from the canonical Crkbd keymap.
* Added a readme to my userspace pointing at my "canonical" keymaps.
None
=> Clean up my ergo keymaps and userspace

keyboards/maartenwut/plain60/keymaps/via/keymap.c
Updates the VIA keymap for the plain60 to have four layers instead, as should be for every VIA keymap.
*
=> Update Plain60 VIA keymap

keyboards/maartenwut/ta65/config.h, keyboards/maartenwut/ta65/keymaps/default/keymap.c, keyboards/maartenwut/ta65/rules.mk
Adds support for a rotary encoder to the ta-65 and gives an example of how to use it in the default keymap. Also updated rules.mk to match the latest template.
*
=> Add encoder support to ta-65

keyboards/keebio/bdn9/bdn9.c, keyboards/keebio/chocopad/chocopad.c, keyboards/keebio/dilly/dilly.c, keyboards/keebio/ergodicity/ergodicity.c, keyboards/keebio/iris/rev2/rev2.c, keyboards/keebio/iris/rev3/rev3.c, keyboards/keebio/iris/rev4/rev4.c, keyboards/keebio/levinson/rev2/rev2.c, keyboards/keebio/levinson/rev3/rev3.c, keyboards/keebio/nyquist/rev2/rev2.c, keyboards/keebio/nyquist/rev3/rev3.c, keyboards/keebio/quefrency/rev1/rev1.c, keyboards/keebio/viterbi/rev2/rev2.c
Adds lighting defaults for Keebio boards, so users aren't confused that their lighting isn't working.
*
=> Add Keebio lighting defaults

keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/keymap.c, keyboards/kbdfans/kbd67/hotswap/keymaps/bcat/readme.md, keyboards/keebio/quefrency/keymaps/bcat/keymap.c, keyboards/keebio/quefrency/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md, layouts/community/60_ansi_split_bs_rshift/bcat/keymap.c, layouts/community/60_ansi_split_bs_rshift/bcat/readme.md, layouts/community/60_tsangan_hhkb/bcat/keymap.c, layouts/community/60_tsangan_hhkb/bcat/readme.md
Just tidying up some inconsistencies across my less-frequently-used keyboard layouts after #8836 and #8857 reworked my preferred (Crkbd, Tsangan) layouts to reflect current preferences.
* Put Menu key binding in a uniform location across keyboards.
* Move backlight controls to a conflict-free location across keyboards.
* Standardize labeling of layers on row-staggered keyboards.
* Tweak non-Tsangan bottom rows so they make a little more sense to me.
None
=> Make personal keymaps a bit more consistent

lib/python/kle2xy.py, lib/python/qmk/cli/kle2json.py
Two tweaks to the code that converts from keyboard layout editor json to qmk info json files:
- Remove error on command line execution
- Round x and y output
Remove an error thrown in python 3.7.7 (more recent than the targeted 3.6):
```
./bin/qmk kle2json -f file.json
[...]
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```
```diff
[...]
"layouts": {
"LAYOUT": {  
-             "layout": [{"label":"Esc", "x":0.66, "y":1.45}, {"label":"!", "x":1.6600000000000001, "y":1.45},
+             "layout": [{"label":"Esc", "x":0.66, "y":1.45}, {"label":"!", "x":1.66, "y":1.45},
```
Starting small as I'm starting to understand python and qmk in general.
=> [kle2json] fix rounding in output

docs/newbs_getting_started.md
Tested on
- Fedora 31
- Ubuntu 16.04
- Ubuntu 18.04
- Manjaro
- Debian 10
- Debian 9
*
=> Update and try to clarify the CLI installation on Linux

keyboards/funky40/info.json
adding info.json for funky40 and fixing some technical difficulties. Thanks noroadsleft!
*
=> adding info.json for funky40

tmk_core/protocol/vusb/usbconfig.h
Currently there is no way to override options within `usbconfig.h`, which is fine till you need to use different pins for the usb port.
If you add an override file at the keyboard level(as a short term workaround), it produces the following sort of errors:
```console
Compiling: tmk_core/protocol/vusb/vusb.c                                                           In file included from tmk_core/protocol/vusb/vusb.c:22:0:
tmk_core/protocol/vusb/usbconfig.h:27:0: error: "USB_CFG_IOPORTNAME" redefined [-Werror]
#define USB_CFG_IOPORTNAME      D
^
In file included from tmk_core/protocol/vusb/usbdrv/usbdrv.h:13:0,
from tmk_core/protocol/vusb/vusb.c:21:
keyboards/xd002/usbconfig.h:26:0: note: this is the location of the previous definition
#define USB_CFG_IOPORTNAME      B
^
In file included …
```
=> Allow some usbconfig.h overrides at the keyboard level

keyboards/ergodox_ez/led_i2c.c, keyboards/ergodox_ez/rules.mk, quantum/rgblight.c, quantum/rgblight.h
This allows these variables to be called by keyboard code that uses the custom rgb driver.
Right now, any keyboard using a custom rgblight driver cannot access these settings, so any benefit from using them is lost for those boards.  Such as the Ergodox EZ.  This allows them to be externed, so they can be used by those boards.
=> Convert clipping variables in rgblight.c to a structure

keyboards/gh60/satan/keymaps/denolfe/keymap.c, keyboards/infinity60/keymaps/jpetermans/keymap.c, keyboards/jd45/keymaps/justin/keymap.c, keyboards/planck/keymaps/matrixman/keymap.c, keyboards/xd60/keymaps/cheese/keymap.c, readme.md
=> Migrate `ACTION_LAYER_MODS` to `LM()`

keyboards/amjkeyboard/amj66/config.h, keyboards/duck/orion/v3/config.h, keyboards/gray_studio/cod67/config.h, keyboards/gray_studio/cod67/readme.md, keyboards/handwired/aek64/config.h, keyboards/handwired/bdn9_ble/config.h, keyboards/staryu/config.h, keyboards/tokyo60/config.h, keyboards/xd68/config.h, keyboards/xd75/config.h
Removing instances of `BACKLIGHT_ON_STATE 1` since it is now the default for both hardware and software PWM, and added some `BACKLIGHT_ON_STATE 0`s for some other boards. The only one I'm not sure of is the COD67 -- @rys you appear to have one; could you confirm whether the inswitch backlight LEDs function properly with this change?
*
=> BACKLIGHT_ON_STATE config.h fixes

quantum/template/avr/rules.mk, readme.md
quantum/audio/audio_avr.c does not implicitly enable any default pins used as output - unless the correct define is set
the comment automatically generated from quantum/template/avr/rules.mk is hence misleading
if a user enables audio and forgets to define a pin on AVR based projext, they'll end up with the audio-feature not working, wasting space/bytes in the firmware and - worst case - breaking the build because the firmware size exceeds the maximum
these patches address this by correcting the comment in the avr template, 
- #8904 updates the comments on all already existing keyboards 
- and #8903 fixes the few mis-configured keyboards = the ones which have AUDIO_ENBALE=yes but no XX_AUDIO define on any level
*
=> Audio_Enable, AVR template update

tmk_core/common/keyboard.c
Specifically this allows keyboards like lily58 in the short term, and #5998, to override core behaviour without having to clutter tmk_core with split specific defines.
=> Provide a mechanism for split keyboards to process key press on both halves

tmk_core/common/report.h
This adds two Consumer Page usages that are used often in ChromeOS.
- `AL_CONTROL_PANEL` (`0x19F`) - On ChromeOS this opens the settings tray.
- `AL_ASSISTANT` (`0x1CB`) - On ChromeOS this starts the Google Assistant. 
Many Chromebooks have dedicated keys for these; this will allow them in QMK.
Note, owing the the shortage of available KC_ keycodes, there is no mapping to these now. To use them, you will need to implement your own custom keycode, and can call this to send the code:
```c
if (record->event.pressed) {
host_consumer_send(AL_ASSISTANT);
} else {
host_consumer_send(0);
}
```
=> Add some usages needed for ChromeOS hosts

tmk_core/common.mk, tmk_core/common/sendchar_null.c, tmk_core/protocol/ibm4704.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb.mk, tmk_core/protocol/vusb/main.c, tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h, tmk_core/ring_buffer.h
In a similar effort to #8380, this enables console support for vusb. Given the endpoint limitations, this also has to have mouse/extra disabled for it to work.
* Tested on windows && linux with and without hid_listen running
=> Initial vusb console support

docs/feature_rgb_matrix.md, quantum/rgb_matrix.c, quantum/rgb_matrix.h, quantum/rgb_matrix_animations/breathing_anim.h, quantum/rgb_matrix_animations/digital_rain_anim.h, quantum/rgb_matrix_animations/jellybean_raindrops_anim.h, quantum/rgb_matrix_animations/raindrops_anim.h, quantum/rgb_matrix_animations/typing_heatmap_anim.h, quantum/rgb_matrix_runners/effect_runner_dx_dy.h, quantum/rgb_matrix_runners/effect_runner_dx_dy_dist.h, quantum/rgb_matrix_runners/effect_runner_i.h, quantum/rgb_matrix_runners/effect_runner_sin_cos_i.h, quantum/rgb_matrix_types.h, tmk_core/protocol/arm_atsam/led_matrix.c, users/xulkal/config.h
This PR changes RGB_DISABLE_AFTER_TIMEOUT to be based on seconds, instead of some odd previous 1.2s per unit from before all the rgb matrix work. In addition this did a bit of code cleanup saving another 100 bytes depending on features used. Also fixed issues with timeouts / suspending at the wrong time not turning off all LEDs in some cases.
*
=> Fixed RGB_DISABLE_AFTER_TIMEOUT to be seconds based & small internals cleanup

layouts/community/ortho_4x12/junonum/keymap.c, layouts/community/ortho_4x12/junonum/readme.md
Extremely minor update to an existing keymap.
Replace `Tab` on the primary layer with `CtrlTab` on `layouts/community/ortho_4x12/junonum/`, my personal layout.
*
=> [Keymap] Minor keymap update to layouts/community/ortho_4x12/junonum/

docs/ChangeLog/20200530/PR8484.md, docs/custom_quantum_functions.md, docs/ja/custom_quantum_functions.md, docs/zh-cn/custom_quantum_functions.md, keyboards/cu75/cu75.c, keyboards/jd45/keymaps/mjt6u/keymap.c, keyboards/keebio/viterbi/keymaps/bakingpy/keymap.c, keyboards/keebio/viterbi/keymaps/dwallace/keymap.c, keyboards/keebio/viterbi/keymaps/mike808/keymap.c, keyboards/lets_split/keymaps/mjt/keymap.c, keyboards/meira/keymaps/default/keymap.c, keyboards/meira/keymaps/grahampheath/keymap.c, keyboards/meira/keymaps/takmiya/keymap.c, keyboards/planck/keymaps/emilyh/keymap.c, keyboards/planck/keymaps/ishtob/keymap.c, keyboards/planck/keymaps/that_canadian/keymap.c, keyboards/preonic/keymaps/that_canadian/keymap.c, keyboards/rgbkb/zen/rev1/keymaps/default/keymap.c, keyboards/rgbkb/zen/rev1/keymaps/jwlawrence/keymap.c, keyboards/thevankeyboards/minivan/keymaps/mjt/keymap.c, keyboards/thevankeyboards/roadkit/keymaps/mjt/keymap.c, quantum/audio/audio.h
remove the deprecated PLAY_NOTE_ARRAY macro throughout the code, and replace it with PLAY_SONG
code cleanup :-)
*
=> audio refactor: replace deprecated PLAY_NOTE_ARRAY

keyboards/kbdfans/kbd67/hotswap/hotswap.h, keyboards/kbdfans/kbd67/hotswap/rules.mk, keyboards/kbdfans/kbd67/rev1/rules.mk, keyboards/kbdfans/kbd67/rev2/rev2.h, keyboards/kbdfans/kbd67/rev2/rules.mk, layouts/community/65_ansi_blocker_split_bs/bcat/keymap.c, layouts/community/65_ansi_blocker_split_bs/bcat/readme.md
Adding support for the new `65_ansi_blocker_split_bs` layout from #8793 to the old (pre-MKII) KBD67 PCBs, as well as a couple other layouts where appropriate:
* `rev1`: Adding `65_ansi` layout. (I'm pretty sure this PCB also supports at least `65_iso`, and probably `65_ansi_blocker` & `65_ansi_blocker_split_bs` too; however, I can't find a picture of the original KBD65 PCB to verify that.)
* `rev2`: Adding `65_ansi_blocker_split_bs`. (The layout is already here, just under a different name. Added an alias for backwards compatibility.)
* `hotswap`: Adding `65_ansi_blocker_split_bs`. (This is a fixed-layout hotswap keyboard, so `65_ansi_blocker_split_bs` is in fact the _only_ layout this particular PCB supports.)
I also moved my personal `kbd67/hotswap` keymap into the …
=> More community layout support for legacy KBD67 PCBs

keyboards/basekeys/slice/rev1/config.h, keyboards/basekeys/slice/rev1_rgb/config.h
Similar to #8115  #8150
MATRIX_COLS is wrongly defined larger than it should be.
*
=> [Keyboard] Fix inconsistent MATRIX_COLS: basekeys/slice

tmk_core/chibios.mk
Reverts qmk/qmk_firmware#8270
Fixes #8809
`syscalls_cpp.cpp` contains some of the required stub functions, however on this arch environment it produces:
* ```multiple definition of `__dso_handle'```
* +2k firmware size over nosys
For the most part, ARM users are not strapped for space. So I put the case that it is better to have working builds across the board in the short term, while a potential longer term solution is worked on.
=> Revert "Switch to nano specs on ChibiOS builds"

quantum/process_keycode/process_rgb.c, quantum/process_keycode/process_unicode_common.c, quantum/process_keycode/process_unicode_common.h, quantum/process_keycode/process_unicodemap.c
1. There is a bug in `cycle_unicode_input_mode()` that prevents cycling in reverse. The bug is due to unsigned arithmetic. As a consequence, the `UC_RMOD` keycode does not currently work. This PR changes the `uint8_t offset` parameter to `int8_t` and fixes the bug.
2. This PR further allows Shift to be used for inverting the direction of the `UC_MOD`, `UC_RMOD` keycodes, similar to how `RGB_MOD`, `RGB_RMOD` work.
I've tested `UC_RMOD` and cycling with Shift after these changes and can confirm that they work as intended.
3. Currently, audio feedback for changing input modes currently only plays for specific `UC_M_*` keycodes. This PR allows it to play when changing input modes with `UC_MOD`, `UC_RMOD` as well.
=> Fix bug in UC_RMOD, add shift and audio support for UC_MOD/UC_RMOD

tmk_core/avr.mk
Using predictable names for temp files is not a good idea. While it's unlikely someone will write an exploit for this we should still be safe.
As a side benefit, in the unlikely situation that 2 users use QMK on the same machine they'll still be able to flash avrdude boards. This could be beneficial in a lab environment.
=> Improve security by eliminating the use of well-known names.

drivers/oled/oled_driver.c
`oled_write_raw_P` has an off by one error where it omits the first byte, and prints out of bounds data at the very end.
I created an image that was a 1px outline around the entire 128x32 image, but this is how `oled_write_raw_P` displayed it on screen before the bugfix.
=> fixes off by one error with oled_write_raw_P

keyboards/keebio/viterbi/keymaps/vosechu/config.h, keyboards/keebio/viterbi/keymaps/vosechu/keymap.c, keyboards/keebio/viterbi/keymaps/vosechu/rules.mk, users/vosechu/vosechu.h
Adds a layout for my one-handed viterbi that I use for playing EVE and other games. 
Any and all feedback would be greatly appreciated!!
- Adds gaming layout
- Adds half-sized macro
=> Add one-handed Viterbi layout for gaming

tmk_core/common/action_layer.c, tmk_core/common/action_layer.h
This is a quick cleanup of layer_state_t that allows users to input their maximum layer number.
Generally, most users have 2-4 layers. Scanning from 31 down to 0 and checking KC_NO /KC_TRANS 32 times before hitting layer one takes quite a bit of time.
This speeds it up by scanning from NUM_LAYERS, which is automatically defined if you've used `#define LAYER_STATE_8BIT`, or you can define it in your config.h.
* Added auto define for NUM_LAYERS
* Changed scanning code from highest_layer (32) to NUM_LAYERS
I've tested with LAYER_STATE_8BIT + NUM_LAYERS = 2, on my 2 layer keyboard.
One caveat is you have to put in your maximum layer number + 1 (e.g. [0] and [1] will need NUM_LAYERS = 2.  [0] [1] [4] will require NUM_LAYERS = 5)
=> Optimization for scanning less layers.

layouts/community/ortho_4x12/xyverz/keymap.c
I like being able to use layers. This fixes my screw-up from my last
code overhaul.
Added defines for RAISE and LOWER, and removed RAISE  LOWER from the keycode enum. (Thanks @ridingqwerty!)
*
=> Added defines for RAISE and LOWER

docs/feature_hd44780.md, docs/ja/feature_hd44780.md
brought to attention by RichardMiruGeorge and fauxpark in #9085
* fixes #9085
=> fixed typo for clear lcd screen function in hd44780 docs

docs/config_options.md, docs/feature_rgblight.md, quantum/rgblight.c, quantum/rgblight.h
This pull request increases the maximum number of RGB Lighting Layers from 8 to 16, if `RGBLIGHT_LAYERS_16` is defined. The default remains 8, since this impacts split transport. When enabled, the packing of the state transport is changed, so when enabling, it is necessary to flash both halves.
The reason for this change is to enable enough lighting layers to:
- use a different lighting layer for each keymap layer
- use a different lighting layer for each locking modifier (caps lock, scroll lock, num lock, compose, kana)
- use lighting layers to acknowledge events (yes/no/fail)
=> Allow expanding from 8 to 32 RGB Lighting Layers

tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h
This might seem irrelevant now as we only got 2 endpoints, but with a 3rd endpoint (https://github.com/qmk/qmk_firmware/pull/9020) it is needed.
I have PRed in master as this is NOT breaking change.
- Reordered usb_interface enumeration.
- VIA expects RAW_HID endpoint to be at interface 1.
- This does not break anything with only 2 endpoints. Keyboard is always at interface 0 and the extra feature is at interface 1.
*
=> V-USB Interface reorder

docs/ChangeLog/20200530/PR8974.md, quantum/audio/audio_avr.c
throw a compile error on mis-/un-configured AVR audio pins
quantum/audio/audio_avr.c does not implicitly enable/use any pins, the proper defines have to be set for audio to actually work
-> this PR adds a compile error to alert the user to a wrong/missing configuration 
Note: this PR will break the build; build-fixes are in #8903
*
=> Audio enable corrections (Part 4)

Makefile
Recent arch install produces:
```console
$ make handwired/onekey:all LTO_ENABLE=yes
QMK Firmware 0.8.144
Making handwired/onekey/promicro with keymap adc                                                       [WARNINGS]
make[1]: Entering directory '/home/zvecr/qmk_firmware'
make[1]: Leaving directory '/home/zvecr/qmk_firmware'
Making handwired/onekey/promicro with keymap backlight                                                 [WARNINGS]
make[1]: Entering directory '/home/zvecr/qmk_firmware'
make[1]: Leaving directory '/home/zvecr/qmk_firmware'
Making handwired/onekey/promicro with keymap default                                                   [WARNINGS]
make[1]: Entering directory '/home/zvecr/qmk_firmware'
make[1]: Leaving directory '/home/zvecr/qmk_firmware'
Making …
```
=> Avoid 'Entering|Leaving directory' messages

lib/python/kle2xy.py
This is not aimed to change functionality. Just trimming the code a little to hopefully be more understandable
2 commits:
- use min, max
- remove `current_x`, `current_y` 
the `label_style` can be between 0 and 9.
If a value is too high, it is set to 9.
The old code would put the correct value in `current_key`, but would put the incorrect value in `skel` (i.e. default values for the current key).
Simplifying the bounds checking to a single expression allowes both `skel` and `current_key` to be set with the correct value.
Same goes for `font_size`.
`row` and `column` are the location of a key in `u` units. `u` being the size of a key.
`x` and `y` are the location of the center of the key in `mm`.
`y = current_row * key_size + key_height * key_size /2`
you can have this value either by …
=> [kle2info] Trim the code in `kle2xy`

lib/python/qmk/cli/doctor.py, tmk_core/avr.mk
Tune doctor's udev rule checking to match #8750.
It will detect the old rules and suggests updating them.
* https://github.com/qmk/qmk_firmware/issues/8655
=> CLI: Tune doctor's udev rule checking to match #8750

docs/feature_rgb_matrix.md, docs/feature_rgblight.md, quantum/rgb_matrix.c, quantum/rgb_matrix.h, quantum/rgblight.c, quantum/rgblight.h
Adds additional `rgblight_get_*` and `rgb_matrix_get_*` functions for querying RGB status, rather than referencing the rgblight or rgb matrix config directly.
=> Add query functions for RGB Light and RGB Matrix

common_features.mk, docs/eeprom_driver.md, drivers/eeprom/eeprom_driver.c, drivers/eeprom/eeprom_i2c.c, drivers/eeprom/eeprom_spi.c, drivers/eeprom/eeprom_spi.h, keyboards/handwired/onekey/keymaps/eep_rst/keymap.c
Adds support for SPI-based 25xx EEPROM, using spi_master.
With #8779 applied, has been verified working against Pro Micro (32u4), Proton-C (F303), Blue Pill (F103), Black Pill (F401), and custom L082 board, all communicating with an M95256 SPI EEPROM.
Note that there is a 64kB size restriction for AVR, due to the fact that EEPROM function signatures use pointers for the address.
Raised #8742 for the AVR size issue.
=> Add support for SPI EEPROM

docs/cli.md, docs/faq_build.md, docs/newbs_getting_started.md, util/macos_install.sh
The Homebrew formula was recently changed to included all the dependencies needed for QMK. This PR makes a few tweaks to streamline the installation process on macOS based on that change.
After this is merged there is only one step needed to setup a fully functional build environment: `brew install qmk/qmk/qmk`
=> Streamline the macos install process

tmk_core/common/command.c
This is kind of a brute force fix, but in "Constant Speed" mode, these values don't really change, for the ones that still exist.  
This disables the mousekey console/command code if this mode is deactivated, fixing the compiler errors that are generated. 
* Fixes #6974
=> Disable Mousekey Command interface when Constant speed is enabled

keyboards/40percentclub/gherkin/keymaps/stevexyz/keymap.c, keyboards/40percentclub/gherkin/keymaps/stevexyz/readme.md
This update of the Gherkin keymap make the original 28 keys design compatible to a 26 "pure alpha" one, as well as 27 (alpha+space) and 30 keys (all the Gherkin switches installed).
No issues detected to close
=> Gherkin 26, 27, 28, 30 keys compatibility

docs/newbs_getting_started.md, util/freebsd_install.sh
* Install the `avrdude` package as well.
* Switch to installing python packages w/ `--user` flag.
* Basic getting started sections for FreeBSD.
* Update `util/freebsd_install.sh` for root/non-root branches.
* Currently, after installing QMK with pip, running `qmk setup` does not work properly as a normal user. This MR aims to address most of that pain, while adhering to best practices for FreeBSD, such as using `pip install` with the `--user` flag.
* Install avrdude as well from the FreeBSD install script.
* Missing docs on basic setup w/ FreeBSD.
=> CLI: Improve experience when running `qmk setup` on FreeBSD.

tmk_core/chibios.mk, tmk_core/rules.mk
Currently the fpu logic sets float-abi to yes/no, from <https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html>,
> -mfloat-abi=name
> Specifies which floating-point ABI to use. Permissible values are: ‘soft’, ‘softfp’ and ‘hard’.
Change the OPT logic to CFLAGS and it starts spitting out errors,
```console
note: valid arguments to '-mfloat-abi=' are: hard soft softfp
```
Now the OPT variable is not reused, I have also made it overridable so we can test scenarios like `make <kb>:<km> OPT=2`.
=> Fix ChibiOS FPU build logic

keyboards/tada68/config.h
The factory TMK firmware for the TADA68 supports backlight breathing,
so I was surprised when the BL_BRTG key I set up in the online QMK
configurator didn't work.
As far as I can tell, this was just a simple omission.
=> Enable backlight breathing support for the TADA68

quantum/matrix.c, quantum/split_common/matrix.c
While a big limit is the 30us delay within matrix scanning, that figure can be configured now along with overall optimisation. These changes can net up to 10% increases depending on matrix size and scanning method. In DIRECT_PINS cases its maybe in the region of 1% but I figured it was worth keeping the code consistent.
=> Slight speed increases for matrix scanning

docs/_summary.md, docs/serial_driver.md, drivers/chibios/serial.h, drivers/chibios/serial_usart.c
Transport does not exist
This PR adds a hardware backed transport mechanism which *might* work on I2C based boards.
Provides a method of transport that does not require a patch or upgrade to ChibiOS. Hardware backed, this avoids some of the locking conflicts from within #7072. The downside is that it requires pullups on the TX line, and using pins which share I2C/USART, rather than the bitbang serial which can run on whatever. A good proportion of pro micro splits can run I2C, so this is potentially already covered for CTPC.
Scan rate goes over 2k with higher speed options so more than enough to keep up with current AVR boards.
TODO
| Chip        | Status                        | Notes |
|--------------|-----------------------------|-|
| f072         | ?                                | …
=> ARM split - Add uart half duplex transport support

drivers/chibios/serial.c, quantum/stm32/halconf.h
Transport does not exist
This PR partially ports some of the old lets_split serial code, with slightly different timings.
<details><summary>CLICK ME FOR INVESTIGATION INFO</summary>
Current issues include
* drivers/arm/i2c_serial.[ch] not implemented
* ChibiOS patch has at least been verified against current QMK fork
* needs verification against latest release
* self contained master/slave example might help testing
* split_common/serial.[ch] does not compile for ARM
Requirements
* 1 wire protocol
* Serial
* complete implementation required
* 2 wire protocol
* I2C
* boards may have wired the I2C bus to both a split slave and device like OLED
Upgrading ChibiOS, maintain patch - could break
Potential to lock in to current version if patch cannot be applied going forward
> Think of the …
=> ARM split - Add serial transport support

Makefile
Was about to put these suggestions on #9159 but it got merged 😄
This more fully demonstrates the syntax, by using the `:flash` target and showing an example of a LUFA board and a ChibiOS board, and an example of a board with no revision and one with.
*
=> Improve the Makefile message a bit more

drivers/eeprom/eeprom_i2c.c
If console is enabled, the i2c EEPROM support fails to compile. 
This adds the correct includes to ensure that everything compiles properly
*  Mine
=> Fix i2c EEPROM compile issue when Console is enabled

keyboards/atreus/astar_mirrored/config.h
This fixes a bug which would cause the two center keys to be swapped
when building the firmware for atreus_mirrored.
"PCBDOWN" was spelled incorrectly in the atreus_mirrored version of the atreus firmware. I fixed
the typo, and now the two center keys are swapped like they are supposed to be.
This makes the firmware work the way that it is documented in the code, but it will change the keymaps of anyone currently using the atreus_mirrored variant.
- [X ] Bugfix
* 
- [X ] My code follows the code style of this project.
- [X ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
=> PDBDOWN should be PCBDOWN for atreus_mirrored.

tmk_core/common/command.c
Currently the COMMAND+B(reboot the keyboard) missed the shutdown_user() hook.
It should be same as the reset_keyboard() function called while click the RESET key. 
- [x ] Core
- [x ] Enhancement/optimization
* 
- [ x] My code follows the code style of this project.
=> Added missing shutdown_user() hook

drivers/issi/is31fl3731.c
Fix compile error for when `DRIVER_COUNT` is 1 (it is usually 2 or more).
*
=> ISSI driver compile error fix

lib/python/qmk/cli/info.py, lib/python/qmk/path.py
Currently `qmk info` will crash if run without --keyboard. This fixes that.
=> Fix running qmk info without any arguments

keyboards/crkbd/rev1/split_scomm.c
The crkbd prints slave matrix debug info with CONSOLE_ENABLE.  This change only prints with debug_matrix.
*
=> Fix crkbd slave matrix print to require debug_matrix

tmk_core/common/action.c
Fixes the build when using `IGNORE_MOD_TAP_INTERRUPT_PER_KEY`.
=> Fix build when using IGNORE_MOD_TAP_INTERRUPT_PER_KEY.

docs/config_options.md, docs/feature_rgblight.md, quantum/rgblight.c
At present, if RGB Lighting is disabled (e.g. using `RGB_TOG` keycode) then enabling the lighting layer has no effect. 
With this change, if RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF is defined, then lighting layers will work even when RGB Lighting is otherwise turned off.
=> Option to allow lighting layers when RGB Lighting is off

quantum/rgblight.c
The blinked layer mask had the wrong size if RGBLIGHT_MAX_LAYERS > 8, potentially leading to incorrect behavior.
=> Fix layer mask size for RGBLIGHT_LAYER_BLINK

quantum/quantum.c, tmk_core/common/keyboard.c
Init's too early to be able to set a number of settings. 
This moves it to the very end (well, almost), so that everything else is inited
* discord chat
=> Move dip switch init to back of the init process

keyboards/ergodox_stm32/readme.md, keyboards/handwired/myskeeb/readme.md
Spotted within the output of http://compile.qmk.fm/v1/keyboards/error_log.
```json
{
"severity": "warning",
"message": "Warning: ergodox_stm32 does not have a readme.md."
}, {
"severity": "warning",
"message": "Warning: handwired/myskeeb does not have a readme.md."
}
```
=> Fix 'does not have a readme.md' warnings

tmk_core/common/report.h, tmk_core/protocol/lufa/bluetooth.h, tmk_core/protocol/lufa/lufa.c
A la #8101.
`AL Keyboard Layout` apparently toggles the virtual keyboard on iOS, and *only* iOS. Nothing seems to happen on Windows, Android or macOS, though I didn't have a touch-capable Windows device nor an iPhone/iPad to test.
*
=> Convert `CONSUMER2BLUEFRUIT()` and `CONSUMER2RN42()` macros to static inline functions

docs/faq_build.md
* udev for several years now has supported "dynamic" permissions
for device access for the logged in user, that avoids needing
custom groups, or making devices world writable.
* Update the docs for udev rules to use the "newer" `uaccess`
approach.
* N/A
=> [Docs] Update udev rules to use TAG+="uaccess".

.travis.yml
Actually fetch the branch we're attempting to compare against.
=> Attempt to fix CI for non-master branches.

keyboards/handwired/onekey/keymaps/adc/keymap.c, keyboards/handwired/onekey/keymaps/backlight/keymap.c, keyboards/handwired/onekey/keymaps/default/keymap.c, keyboards/handwired/onekey/keymaps/default_json/keymap.json, keyboards/handwired/onekey/keymaps/eep_rst/keymap.c, keyboards/handwired/onekey/keymaps/i2c_scanner/keymap.c, keyboards/handwired/onekey/keymaps/reset/keymap.c, keyboards/handwired/onekey/keymaps/rgb/keymap.c, keyboards/handwired/onekey/onekey.h, layouts/community/ortho_1x1/test/keymap.c
```
Error: handwired/onekey: Missing layout pp macro for ['ortho_1x1']
```
*
=> Fix error_log complaint about handwired/onekey layout macro

docs/keycodes.md
Documenting which keycodes work on the big three, which don't, and which have weird/nonstandard behaviour (mostly on macOS). Would appreciate confirmation/testing of the unknown ones :)
*
=> Add OS compatibility matrix for basic keycodes

docs/newbs_getting_started.md
The `echo` command in the note doesn't work on Ubuntu/Debian WSL. An `export` command is simpler and does work on WSL systems.
*
=> Fix Ubuntu/Debian setup when $PATH contains spaces

docs/newbs_getting_started.md
PR #9307 fixed the immediately visible problem (the command that was added to `$HOME/.bashrc` was incorrect because of missing quotes around paths with spaces).  However, the modified command is still wrong — it captures the value of `$PATH` at the setup time, and the resulting command written out to `$HOME/.bashrc` will overwrite `$PATH` with that captured value, ignoring any changes in the environment.  This may be especially important for WSL, where the initial value of `$PATH` in Linux includes everything which has been added to `%PATH%` on the Windows side; after adding that command to `$HOME/.bashrc` the WSL environment will no longer pick up any changes made by newly installed Windows software.
Instead of that, use single quotes around the command, so that the environment variables …
=> Really fix Ubuntu/Debian setup when $PATH contains spaces

keyboards/murcielago/rev1/keymaps/default/keymap.c, keyboards/murcielago/rev1/keymaps/via/keymap.c
Improved default keymap for Murciélago.
This layout is more useful for US and US international users, while it was previously more focused on US international layout only.
Additionally, all hold/tap dual functionality was removed in the default keymap for avoiding issues when using the keyboard with remote machines or VMs.
=> Murcielago: improve default keymap

docs/one_shot_keys.md
Link to mod_tap.md was accidentally pointing to #mod-tap section of one_shot_keys.md. This fix corrects the link to point to mod_tap.md.
* #9321
=> Correcting the link to mod_tap.md in the one_shot_keys.md file (Fixes 9321)

drivers/avr/ssd1306.c, keyboards/claw44/ssd1306.c, keyboards/comet46/ssd1306.c, keyboards/crkbd/ssd1306.c, keyboards/helix/local_drivers/ssd1306.c, keyboards/yosino58/ssd1306.c
Nothing declared in this header is used by the SSD1306 code - not even the Comet46 which is a wireless split that uses the same BLE module but not the Adafruit firmware.
*
=> Remove inclusion of adafruit_ble.h from ssd1306.c

quantum/quantum.c, tmk_core/protocol/lufa.mk, tmk_core/protocol/lufa/lufa.c
If Bluetooth is disabled we should always output over USB, so the `where_to_send()` call and early return can safely be placed behind the `BLUETOOTH_ENABLE` ifdef.
Saves about 90 bytes on avr-gcc 8.4.0 with `gh60/satan:default`, should be no change for boards with Bluetooth enabled.
*
=> Don't compile outputselect.c if Bluetooth is disabled

lib/python/qmk/constants.py
Support for ATmega328 was added in #9043.
*
=> CLI: Add ATmega328 and ATtiny85 to supported CPUs

docs/feature_tap_dance.md
Mostly fixing code style, removing references to the deprecated `ACTION_FUNCTION_TAP` and trying to clarify the simple example (in particular, where to put the `TD()` keycode).
*
=> Clean up Tap Dance docs

tmk_core/common/action.c
This provides a fix for two cases of One Shot Layers not being cleaned up after the next key has been pressed:
1. KC_MUTE does not trigger cleanup action for One Shot Layers (Issue #7599)
2. QMK functions (implemented in `process_record_quantum()` or its constituents) will never reach [this code](https://github.com/qmk/qmk_firmware/blob/58a9c84d6bb22c7544231f60acace4a85d6f8dd2/tmk_core/common/action.c#L227), leaving the OSL active.
To solve these problems I have:
-  added a check for `ACT_USAGE` to prevent that case from allowing the action to erroneously be interpreted as a modifier (@fauxpark suggested).  
- added code to `process_record()` so that when an QMK function is processed, the OSL is still cleaned up even though `process_action()` is never called in that case.
Note: 
This code …
=> Fix for One Shot Layer not being cleaned up after some actions

keyboards/ymd75/rev1/rules.mk, keyboards/ymd75/rev2/rules.mk, keyboards/ymd75/rules.mk
Work-around for an issue with QMK Configurator's API that prevents it from compiling firmware for this board.
=> YMD75: move MCU/Bootloader rules to revision level

lib/python/qmk/cli/doctor.py, lib/python/qmk/tests/test_cli_commands.py, requirements.txt
To avoid the case where the `version_number.split('.', 2)` fails due to:
> -dumpversion
> Print the compiler version (for example, 3.0, 6.3.0 or 7)—and don’t do anything else. This is the compiler version used in filesystem paths and specs. **Depending on how the compiler has been configured it can be just a single number (major version), two numbers separated by a dot (major and minor version) or three numbers separated by dots (major, minor and patchlevel version).**
>
> -dumpfullversion
> Print the full compiler version—and don’t do anything else. The output is always three numbers separated by dots, major, minor and patchlevel version.
*
=> Parse version better in `qmk doctor` GCC version checks

keyboards/gboards/engine/rules.mk, keyboards/gboards/g/rules.mk
These folders don't contain actual keyboard definitions, so they should not have a rules.mk as that is one of the criteria, and is causing these lines in the API error_log:
```
"Warning: gboards/engine: Falling back to searching for KEYMAP/LAYOUT macros."
"Warning: gboards/g: Falling back to searching for KEYMAP/LAYOUT macros."
```
Otherwise @germ if you still need these would it be possible to use a different name so it doesn't get picked up? I don't see any references to it in your current boards or open PRs.
*
=> Remove rules.mk for gboards/engine and gboards/g

users/spidey3/spidey3.c
Fixes a bug that caused cursor keys and some other keys to be sent as LGUI(key) when GUI F-key lock mode was on.
=> spidey3 userspace: GUI F-Key lock was affecting some non-F-keys

quantum/rgb_matrix_drivers.c
Is a minor change that only affects the driver file. 
However, this will allow somebody to run rgblight along side rgb matrix
using the ws2812 driver, as well.  Specifically, so you can use the
custom driver for rgblight to set a different pin (barring a change to
the `ws2812_setleds` function).  
Courtesy of discord conversion:
https://discordapp.com/channels/440868230475677696/568161140534935572/721555623191248906
Specifically, the issue is that both rgblight and rgb matrix use an array named `led` to hold the LED array before sending it to the hardware. This creates a conflict.  Renaming the led array in rgb matrix allows for coexistence.
=> Change `led` to `led_matrix` in rgb_matrix_drivers

docs/ja/feature_bootmagic.md
Updated the Japanese translation of feature_bootmagic.md to 0.9.0.
=> [Update] Japanese Translation of docs/feature_bootmagic.md

keyboards/1upkeyboards/1up60hse/rules.mk, keyboards/1upkeyboards/1up60rgb/rules.mk
1up has asked me to make sure NKRO is enabled on their boards, while I was at it, I decided to make sure Bootmagic was consistently set to lite.
=> Enable NKRO on 1up's boards

drivers/ws2812.h, quantum/process_keycode/process_ucis.c, quantum/process_keycode/process_unicode_common.c, quantum/process_keycode/process_unicodemap.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/lufa/lufa.c
=> `qmk cformat` on `develop`

tmk_core/protocol/midi/qmk_midi.h
MIDI does not work for ARM without NKRO enabled, because it includes this header file. By adding this, the correct header is included regardless of NKRO, while allowing AVR to continue to work.
Adding header file.
* fixes #9439
=> Fixing MIDI for ARM without NKRO enabled

docs/feature_rgb_matrix.md, docs/feature_rgblight.md, quantum/process_keycode/process_rgb.c
Specifically, this adds explicit calls for the rgb matrix code to the `process_record_rgb` function. 
Right now, if you have both RGB Light and RGB Matrix enabled, it will only let you control the RGB Light functions, with no way to control the RGB Matrix features.
=> Improve keycode handling for RGB 

keyboards/atreus/keymaps/dvorak_42_key/keymap.c, keyboards/ergodox_ez/keymaps/dvorak_42_key/keymap.c
user keymap changes for ergodox_ez/dvorak_42_key / atreus/dvorak_42_key
add windows 10 workspace shortcuts, add vscode shortcuts, remove Cloud9 shortucts.
=> user keymaps for ergodox_ez/dvorak_42_key / atreus/dvorak_42_key

keyboards/coseyfannitutti/discipline/discipline.h, keyboards/coseyfannitutti/discipline/rules.mk
Adds support for 65_ansi_blocker community layouts to Discipline maintained by @coseyfannitutti. LAYOUT_65_ansi_blocker is aliased as the already implemented LAYOUT_65_ansi_2_right_mods. Although there is no physical blocker, it is the same layout with the same number of arguments, but with the 2 right mods being 1.5u keys and not 1.25u. Tested with layouts/default and layouts/community keymaps.
* N/A
=> Add more community layout support to Discipline

keyboards/keebzdotnet/wazowski/info.json
- online configurator keys were in the wrong location and needed to be fixed
- fixed a key being to high on the y position
When I used the online configuration my keys were wrong. So I had to map out what was wrong and where they went. I think I fixed it. I think its because I put the switches in weird places on the board. 
*
=> Wazowski fixed keymap placement

docs/reference_keymap_extras.md, quantum/keymap_extras/keymap_dvorak_fr.h, quantum/keymap_extras/sendstring_dvorak_fr.h
Add the dvorak-fr as extra keymap
Dvorak adaptation for the French language (Version 2)
The layout is designed by Francis Leboutte <dvorak-fr@algo.be>
Source: https://algo.be/ergo/dvorak-fr.html
=> [Keymap Extra] Add dvorak-fr

keyboards/atreus62/keymaps/xyverz/keymap.c
Changed bottom-right keys in WOW and DESTINY layers from KC_ENT
to KC_RCTL.
*
=> Minor keymap fix

keyboards/jd40/keymaps/myoung34/keymap.c
Add JD40 keymap for my layout
*
=> Add JD40 keymap for myoung34

layouts/community/ortho_4x12/xyverz/keymap.c
My MACLOCK macro doesn't work in its present location. Moving it to
another key location that actually works. VERY minor fix.
*
=> Fixed MACLOCK key

keyboards/fc660c/config.h, keyboards/fc660c/fc660c.h, keyboards/fc660c/keymaps/via/README.md, keyboards/fc660c/keymaps/via/keymap.c, keyboards/fc660c/keymaps/via/rules.mk
Add VIA support for Hasu FC660C controller.
I had to reduce the matrix rows to 5 so that it would fit. The last three rows were not being used.
https://github.com/the-via/keyboards/pull/184
*
=> Add Via support for Hasu FC660C controller

keyboards/ramonimbao/herringbone/keymaps/default/keymap.c, keyboards/ramonimbao/herringbone/keymaps/iso/keymap.c, keyboards/ramonimbao/herringbone/keymaps/via/keymap.c
Mistakenly put KC_TILD instead of KC_GRV for the default keymaps.
*
=> Fix Herringbone keymap typo

keyboards/keebio/quefrency/rev1/config.h
Apparently VIA allocates bits in the layout options field from the lowest bit, but starting from the **last** option defined in the JSON file.  So the default value `0x06` was actually trying to set the value `3` (`0b11`) for the second-to-last option ("Right Shift"), which had only 3 values defined, and the attempt to set an undefined option value caused the VIA app to hang with a black window.
Fix the default layout options so that it works as intended (the "Macropad" and "65% Column" options are set).
=> Quefrency rev1: Fix default VIA layout options

keyboards/planck/keymaps/xjtian/config.h, keyboards/planck/keymaps/xjtian/keymap.c, keyboards/planck/keymaps/xjtian/readme.md
New layout for 4x12 grid Planck keyboards.
=> Add xjtian keymap for Planck

tmk_core/common/action.c
Fix sharing of mouse button state from mousekeys to ps2_mouse.
#1327 shares mousekeys button state with ps2_mouse but prevents clicks when using only mousekeys.
#1344 fixes this but produces clicks from both mousekeys and ps2_mouse.
https://github.com/qmk/qmk_firmware/issues/1339#issuecomment-304580379 would fix the missing and duplicate cilcks but break mousekeys dragging.
With this change, when ps2_mouse is disabled, mousekeys works as usual.  With ps2_mouse enabled, mousekeys button state is shared with ps2_mouse for clicking, dragging, and scrolling, mousekeys clicks are produced by ps2_mouse only, and mousekeys button state is transferred to mousekeys without generating clicks to enable mousekeys dragging. 
Resolves #1339.
*
=> Fix sharing of mouse button state from mousekeys to ps2_mouse

quantum/quantum.c
For consistency, `SEND_STRING()` et al. should use `tap_code()` instead of register/unregister in the `SS_TAP_CODE` case, so that the `TAP_CODE_DELAY` is added, if defined.
*
=> Make sendstring respect `TAP_CODE_DELAY`

util/linux_install.sh
For Void Linux the `libusb-compat-devel` package is needed to have the `libusb-config` command and the `usb.h` header. Without this package the `linux-install.sh` script fails.
=> Add missing dependency for Void Linux to util/linux-install.sh

quantum/keymap_extras/keymap_neo2.h
Fix duplicated “NE_H” definition to use “NE_G” in Neo2 keymap, introduced with commit 44ff14f (see PR #9063).
Looping in @fauxpark.
=> Fix “G” in Neo2 keymap

keyboards/xd87/xd87.c
Slight refactor of XD87 Caps Lock LED toggling.
*
=> XD87 Caps Lock LED refactor

drivers/issi/is31fl3741.c
=> [Driver] bugfix reset the scaling register flag to FALSE

build_layout.mk
Add ability to build keymaps from keymap.json in the layouts directory as well.
Currently, keymaps can be built from JSON format when placed in keyboards/.../keymaps/.../, but only keymap.c is supported when placed in layouts/. This small change adds support for keymap.json files placed in the layouts directory.
=> Add ability to use keymap.json files in layouts/

tmk_core/common/action.c
Adds TAP_CODE_DELAY to the Mod-Tap function and fixes #9418.
This is my first contribution to QMK, so please check that I didn't do any obvious mistakes here 👼 I tested this on my ErgoDox and it works well, but I'm unsure if this could have any side effects.
Note: There were compilation errors and "firmware too large" messages when running `make all`, but I think these may be related to my build environment or outdated layouts and are not caused by my change, but I'm not 100% sure about this.
Copied the `else` branch as suggested by @fauxpark in #9418 from Layer-Tap.
* #9418
=> Add TAP_CODE_DELAY to Mod-Tap

docs/tap_hold.md
The `TAPPING_TERM_PER_KEY` code sample is missing a closing bracket.
This adds it.
*
=> Add missing bracket for Tap-Hold code sample

docs/reference_keymap_extras.md, quantum/keymap_extras/keymap_french_afnor.h, quantum/keymap_extras/sendstring_french_afnor.h
Add the French AZERTY (AFNOR - NF Z71-300) as extra keymap
The project was launched at the end of 2015 on the proposal of the General Delegation for the French language and the languages ​​of France (Ministry of Culture), starting from the observation that the current "azerty"  keyboards constrain the writing of French, languages regional and European languages ​​with Latin alphabet.
For the first time, a standard (NF Z71-300) defines the placement of characters on the French keyboard. It offers two layouts, one of which closely follows the QWERTY keyboard used by most people who write in French.
However, it is in many ways superior to the old keyboard:
- it contains all the characters required to enter text in French (for example É, œ and ")
- it is designed to be more ergonomic and …
=> [Keymap Extra] Add French AZERTY (AFNOR - NF Z71-300)

quantum/keymap_extras/keymap_us_international.h
This pull request contains a simple fix to a simple bug: the US International keyboard layout erroneously assigns both left and right square bracket to left square bracket.
The fix consists of letting US_RBRC reference KC_RBRC instead of KC_LBRC.
=> Changed US_RBRC to KC_RBRC instead of KC_LBRC

shell.nix
Improvements to shell.nix were made in #8910 by @thorstenweber83, but the result was that the nix shell no longer worked on Darwin.
I have tidied up and improved some of the Nix expression, fixing this issue along the way. If someone would be kind enough to test this on Linux too, that would be appreciated, though I don't expect issues.
- Removed unnecessary overrides
- Provided a more complete Python environment, adequate for actually running/developing `bin/qmk`
- Unset NIX_TARGET_CFLAGS_COMPILE in the Nix shell, to avoid incompatible host CC flags getting picked up by avr-gcc.
* None
=> shell.nix improvements, and fix problems on Darwin

keyboards/centromere/centromere.h, keyboards/centromere/rules.mk, keyboards/crkbd/rev1/rev1.h, keyboards/crkbd/rev1/rules.mk
This pull request adds support for the split_3x6_3 layout to keyboards that are compatible.
Add support for the split_3x6_3 layout to the following keyboards:
- Centromere, maintained by @spe2 
- Crkbd, maintained by @foostan 
*
=> split_3x6_3 layout support

quantum/backlight/backlight_chibios.c
Currently this PR aims to:
* Add `BACKLIGHT_ON_STATE` support
* Resolve `BACKLIGHT_BREATHING` always required to avoid compilation errors
* Short term 'fix' for breathing_pulse
* existing solution only works when breathing is disabled
* a pulse during breathing will just leave breathing disabled
* allows the ChibiOS PWM config and breathing task logic to be greatly simplified
* allows pulse when when and without breathing
* generic pulse method will be PRed separately
=> Refactor ARM backlight

keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/config.h, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md, users/bcat/bcat.c, users/bcat/bcat.h, users/bcat/rules.mk
I started out by splitting my Crkbd's Ctrl/Esc mod-tap key into two separate keys and just, well, spiraled from there.
Incidentally, I also removed `SPLIT_USB_DETECT` from my Lily58 since I've switched it to controllers with working VUSB detection, and I re-enabled `MOUSEKEY_ENABLE` because otherwise media keys don't work on Chrome OS. (I'm still not sure if this is a Chrome OS bug or a QMK one.)
None
=> Rework my Crkbd and Lily58 modifier keys

keyboards/kyria/keymaps/plattfot/README.md, keyboards/kyria/keymaps/plattfot/keymap.c
- Fix typo in the default layout.
- Move esc and del to the navi layer.
- Fix issue with oneshot layer and double tap aka DBL_TAP.
- Add caps lock to the raise layer.
Was relying on a broken behavior for the double tap to work with
oneshot keys, i.e. the oneshot layer not being cleared after a key
press in `process_record_user`, which allowed me to first press an
oneshot key, then double tap and then a key. With the behavior fixed,
this no longer works. As the oneshot layer will be cleared when double
tap is pressed.
To make double tap useful again. I changed that any of the layer keys
does not clear the double tap. Which allows me for example to first
press double tap, then an oneshot key and then a key. So now I'm able
to type my double symbols again.
* #9521 - Will no longer be an …
=> [Keymap] plattfot - Update and fix issue with DBL_TAP

keyboards/planck/rev6/chconf.h, keyboards/planck/rev6/config.h, keyboards/planck/rev6/mcuconf.h, keyboards/planck/rev6/rev6.c, keyboards/planck/rev6/rules.mk
This patch enables pwm drivers for the rev6 planck by default, and includes the necessary configuration for it to work out of the box.
- The default WS2812 driver has been changed from bitbang to pwm.
- RGB_MATRIX_ENABLE has been set to WS2812 by default in the rev6 rules.mk.
- In rev6.c, I've added a led_config_t define to allow the matrix indexing to work properly (taken from https://github.com/qmk/qmk_firmware/pull/6675).
- DRIVER_LED_TOTAL is set in the rev6 config.h, as well as some WS2812 config options.
- Lastly, overrides for chconf.h and mcuconf.h have been created to fix some board-specific issues with the default driver configuration.
I built the new version with all keymaps for the planck, and the only ones that have issues related to this pull request are those that define …
=> planck/rev6: Enable WS2812 LED matrix with pwm drivers

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
Add a function to set individual pixels to oled driver.
Add a function to turn an individual pixel on or off, based on x and y coordinates. Coordinates start from top-left and positive values of x and y move right and down respectively.
Allows for things like [a starfield](https://imgur.com/gallery/HeFWeKJ) ([example code](https://github.com/GauthamYerroju/qmk_firmware/blob/oled_starfield/keyboards/kyria/keymaps/gotham/oled_animations/starfield.c)), or [bitmap rendering at exact pixel positions](https://imgur.com/gallery/yk9k0XP)  ([example code](https://github.com/GauthamYerroju/qmk_firmware/blob/oled_starfield/keyboards/kyria/keymaps/gotham/oled_animations/dvd_logo.c)).
The bitmap rendering example code has an implementation for ```oled_write_bitmap(bitmap, x, y, width, height, …
```
=> OLED driver function to set pixels

docs/ws2812_driver.md, drivers/chibios/ws2812_pwm.c
Newer STM32 MCUs have a DMAMUX peripheral, which allows mapping of DMAs to different DMA streams, rather than hard-defining the target streams in silicon.
Affects STM32L4+ devices, as well as the soon-to-be-supported-by-QMK STM32G4/H7 families.
Tested on F303/Proton-C (ChibiOS v19, non-DMAMUX), G474 (ChibiOS v20, with DMAMUX).
=> Allow for WS2812 PWM to work on DMAMUX-capable devices

.gitignore, quantum/audio/song_list.h
Allows for user song lists to be added, but keeps them out of the repo (for legal reasons). 
Additionally, defines the removed songs weakly, so people can use them without issue.
=> Allow for user song lists

tmk_core/common/mousekey.c
Mousekey scrolling should have a separate repeat variable
to keep track of scrolling acceleration, instead of being
tied to mouse movement scolling in mousekeys. The send function
should record when the last movement was made since this is
when movement is actually sent. Doing this fixes the bug where
the initial press of a mousekey scroll button causes a double scroll.
* https://github.com/qmk/qmk_firmware/issues/5690
=> Fix the mousekey scrolling

docs/platformdev_chibios_earlyinit.md, tmk_core/common/chibios/bootloader.c, tmk_core/protocol/chibios/main.c
Adds support for STM32 dual-bank flash bootloaders, by toggling a GPIO during early init in order to charge an RC circuit attached to `BOOT0`.
The main rationale behind this is that dual-bank STM32 devices unconditionally execute user-mode code, regardless of whether or not the user-mode code jumps to the bootloader. If either flash bank is valid (and `BOOT0` is low), then the built-in bootloader will skip any sort of DFU.
This PR allows for the initialisation sequencing to charge the RC circuit based on the example circuit posted on Discord, effectively pulling `BOOT0` high before issuing the system reset. As the RC circuit takes a while to discharge, the system reset executes the ROM bootloader which subsequently sees `BOOT0` high, and starts executing the DFU routines.
Tested with …
=> Add dual-bank STM32 bootloader support

docs/ChangeLog/20200829/PR9318.md, keyboards/ashpil/modelm_usbc/keymaps/ashpil/keymap.c, keyboards/converter/usb_usb/keymaps/chriskopher/combo.c, keyboards/converter/usb_usb/keymaps/narze/keymap.c, keyboards/ergodox_infinity/keymaps/narze/keymap.c, keyboards/gboards/g/keymap_combo.h, keyboards/maxr1998/pulse4k/pulse4k.c, keyboards/minidox/keymaps/rsthd_combos/keymap.c, keyboards/planck/keymaps/narze/keymap.c, keyboards/xd75/keymaps/4sstylz/keymap.c, quantum/process_keycode/process_combo.c, quantum/process_keycode/process_combo.h, users/issmirnov/issmirnov.c, users/kuchosauronad0/combo.c, users/ninjonas/combos.c, users/yet-another-developer/combo.c
Changes `uint8_t` to `uin16_t` when looping over combos. With 16 bits we can have much more than 256 combos.
*
=> Bigger combo index

docs/driver_installation_zadig.md, util/activate_msys2.sh, util/activate_wsl.sh, util/drivers.txt, util/msys2_install.sh, util/win_shared_install.sh
MSYS2 now has a bootloadHID package, so let's use it instead of downloading the zip from obdev.
Also, the "bug" in the avrdude package is not really a bug - USBAspLoader just requires the libusbK driver to be installed on it. So I've updated the drivers.txt and put back the avrdude package.
*
=> MSYS2: Switch to bootloadHID package and bring back avrdude package

tmk_core/common/chibios/bootloader.c
Apparently I hadn't actually updated to the latest copy when I merged. Serves me right for assuming it was unchanged.
Anyways, this swaps things out to jump to bootloader directly when using dual-bank flash -- there's no need to go through the process of resetting the MCU, then charging the capacitor, and resetting the MCU a second time.
This change makes it so that we skip the first reset -- i.e. we only charge the capacitor then issue a system reset.
=> Re-fix the STM32 dual-bank bootloader stuff.

keyboards/dztech/dz60rgb/dz60rgb.c, keyboards/dztech/dz60rgb_ansi/dz60rgb_ansi.c, keyboards/dztech/dz60rgb_wkl/dz60rgb_wkl.c, keyboards/dztech/dz65rgb/dz65rgb.c
Simple fix. Previously if `RGB_MATRIX_ENABLE=no` was set, a compilation warning would be produced preventing build completion. Moving the `#endif` on a `#ifdef RGB_MATRIX_ENABLE` solves this issue.
=> Fix compilation warning for the DZ60RGB/DZ65RGB when RGB matrix is disabled

tmk_core/common.mk
NKRO isn't available on on V-USB.  Instead of erroring out and failing to compile, just forcibly disable NKRO on V-USB controllers.
=> Disable NKRO on V-USB controllers

keyboards/lets_split_eh/keymaps/doxish_dvorak/keymap.c
The doxish_dvorak layout originally committed by @ROMUSKING did not change the diagram in comments to match the changes to the layout. This PR makes that diagram change. This is for the lets_split_eh keyboard.
This PR solely changes comments.
=> Updating comment diagram to match code in lets_split_eh/doxish_dvorak

docs/ja/feature_dip_switch.md
=> [Docs] Update Japanese translation of feature_dip_switch.md.

keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/keebio/quefrency/keymaps/bcat/keymap.c, keyboards/keebio/quefrency/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md, layouts/community/60_ansi_split_bs_rshift/bcat/keymap.c, layouts/community/60_ansi_split_bs_rshift/bcat/readme.md, layouts/community/60_tsangan_hhkb/bcat/keymap.c, layouts/community/60_tsangan_hhkb/bcat/readme.md, layouts/community/65_ansi_blocker_split_bs/bcat/keymap.c, layouts/community/65_ansi_blocker_split_bs/bcat/readme.md, users/bcat/rules.mk
On further investigation, it seems that Chrome OS isn't processing media keys unless the USB endpoint with the consumer and system control devices also contains a keyboard or mouse device. Mouse keys aren't useful to me, and they actually seem to cause a Windows bug instead (#8323), so I'm switching to NKRO. This functions as an equivalent workaround for Chrome OS, and is also at least theoretically useful to me.
None
=> Switch my Chrome OS media keys workaround from mouse keys to NKRO

keyboards/do60/config.h, keyboards/do60/do60.c, keyboards/do60/do60.h, keyboards/do60/keymaps/default/keymap.c, keyboards/do60/keymaps/via/keymap.c, keyboards/do60/keymaps/via/readme.md, keyboards/do60/keymaps/via/rules.mk
Added VIA enabled keymap along with a few refactors
=> VIA Support: DO60

docs/ja/config_options.md, docs/ja/driver_installation_zadig.md, docs/ja/faq_build.md, docs/ja/feature_dip_switch.md, docs/ja/feature_dynamic_macros.md, docs/ja/feature_encoders.md, docs/ja/feature_hd44780.md, docs/ja/feature_layers.md, docs/ja/feature_split_keyboard.md, docs/ja/feature_userspace.md, docs/ja/getting_started_github.md
I fixed the comment indicating the original document.
tagging: @shelaf
=> [Docs] Fix Japanese documents 'original document' comment 

docs/feature_tap_dance.md, keyboards/converter/usb_usb/keymaps/narze/keymap.c, keyboards/ergodox_infinity/keymaps/narze/keymap.c, keyboards/planck/keymaps/narze/keymap.c, quantum/process_keycode/process_space_cadet.c, quantum/process_keycode/process_space_cadet.h, quantum/process_keycode/process_tap_dance.c
This updates both the Space Cadet feature, and Tap Dances to use the Custom Tapping Term functionality, so that you can check them as well.
For the Tap Dance feature, this completely removes the need for the `ACTION_TAP_DANCE_FN_ADVANCED_TIME` dance, but I didn't want to remove it, as a few keymaps do rely on this function.
=> Update features to use Custom Tapping Term when appropriate

keyboards/massdrop/ctrl/keymaps/responsive_pattern/README.md, keyboards/massdrop/ctrl/keymaps/responsive_pattern/keymap.c
`"responsive pattern"` add splash led effect to massdrop CTRL keyboard
last rgb matrix update (#5328) broke the old code,
this update utilizes the newly added `led_instructions` for led rgb effect
background led are also affected now!
* 
for now only traveling splash is implemented, other effects provided in the past (single key twinkle, pattern indicators on the number row, background-off-key-on) might be added in the not-so-near future, same applies to documentation (README).
=> Keymap update - massdrop/ctrl/responsive_pattern

common_features.mk
It wants a number, but a number of files have it set to "no", even
though it's commented out.  This means that if you set it to no, it
will cause a compiler error.  This sets the default to "no", and
checks to make sure it's not set to "no" before processing it, and
striping the value from it.
* Found on discord
=> Fix Variable Trace handling

keyboards/cannonkeys/atlas/config.h, keyboards/cannonkeys/atlas/keymaps/default/keymap.c, keyboards/cannonkeys/atlas/keymaps/via/keymap.c
=> Atlas Updates

tmk_core/common/action_layer.h, tmk_core/common/bootmagic.c, tmk_core/common/magic.c
Right now, on startup, the default layer state gets called and set, triggering the callback functions for the default layer state. However, the normal layer state never actually gets initialized.  It's set to 0 directly, by default, but the callback functions are never actually called.  This creates some inconsistency in the behavior for end users.  This adds a simple "clear" that triggers the callback on startup.  This should produce more consistent behavior between the two functions and layer masks.
=> Initialize Layer State on startup

docs/ja/other_eclipse.md
Add a Japanese translation of docs/other_eclipse.md.
*
=> [Docs] Japanese translation of docs/other_eclipse.md

docs/ja/feature_macros.md
=> [Docs] Update Japanese translation of feature_macros.md.

keyboards/metamechs/timberwolf/config.h, keyboards/metamechs/timberwolf/keymaps/via/keymap.c, keyboards/metamechs/timberwolf/rules.mk, keyboards/metamechs/timberwolf/timberwolf.c
- changed the via.c keymap to be more useful as a stock keymap and require less adjustment
- made a few other small adjustments to match up with via recommended settings
- modified custom caps lock code to eat less eeprom
sorry for spamming PRs, keyboards are shipping so I want all the firmware to be as good as possible before the first package arrives.
=> Timber Wolf - updated via keymap, reduced eeprom writing from backlight code

docs/custom_quantum_functions.md, docs/ja/custom_quantum_functions.md, docs/ref_functions.md, docs/zh-cn/custom_quantum_functions.md
just remove unnecessary break after return from documentation
=> remove break after return

keyboards/handwired/dactyl_manuform/5x6_5/config.h
Seems we were (read: I was) a bit overzealous in merging #9659 – the USB Device descriptors weren't fully set up, so it didn't actually compile:
```shell
noroadsleft ~/qmk_firmware/keyboards/handwired/dactyl_manuform/5x6_5 (master)
$ qmk compile -km all
Ψ Compiling keymap with make handwired/dactyl_manuform/5x6_5:all
QMK Firmware 0.9.46
Making handwired/dactyl_manuform/5x6_5 with keymap default
avr-gcc.exe (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
Compiling: keyboards/handwired/dactyl_manuform/dactyl_manuform.c                                    [OK]
Compiling: keyboards/handwired/dactyl_manuform/5x6_5/5x6_5.c …
```
=> fix Dactyl-Manuform 5x6_5 compilation

keyboards/daisy/config.h, keyboards/daisy/keymaps/via/keymap.c, keyboards/daisy/keymaps/via/readme.md, keyboards/daisy/keymaps/via/rules.mk, keyboards/daisy/rules.mk
Adds compatibility for VIA on Daisy 40, for both split and full size spacebar
https://github.com/the-via/keyboards/pull/226
* N/A
=> [Keyboard] Add via compatibility to Daisy 40 [1/2]

quantum/rgb_matrix.c
Forces long integer math in the expansion of `RGB_DISABLE_TIMEOUT` when a config file uses the deprecated define `RGB_DISABLE_AFTER_TIMEOUT` to prevent overflow with values greater than 27.
```C
```
* Fixes #9866
=> Fix RGB_DISABLE_TIMEOUT overflow warning (#9866)

keyboards/anavi/macropad8/rules.mk, quantum/color.c, quantum/color.h
As preparation for the new drawing APIs, I need to add support for HSV -> RGB conversions but disregard the CIE curve when doing so.
=> Add support for hsv->rgb conversion without using CIE curve.

docs/feature_rgb_matrix.md, quantum/rgb_matrix_types.h
This adds a new flag for the RGB Matrix feature that lets you specify if the LED is an indicator LED, to be used to indicate the system state of the keyboard (eg caps/num/etc lock status, layer indication, modifer status, etc).
=> Add Indicator flag for RGB Matrix

.github/PULL_REQUEST_TEMPLATE.md, docs/_summary.md, docs/pr_checklist.md
Adds a new PR checklist document to simplify ambiguities when asking for changes, as well as providing some consistency.
=> Add PR checklist document.

keyboards/squiggle/keymaps/rick-complicated/config.h, keyboards/squiggle/keymaps/rick-complicated/keymap.c, keyboards/squiggle/keymaps/rick-complicated/readme.md, keyboards/squiggle/keymaps/rick-complicated/rules.mk
Added a keymap example for squiggle, goldberg version.
currently, there is no example for `LAYOUT_complicated` for squiggle keyboard. this PR fixes that.
*
=> keymap for squiggle goldberg.

keyboards/handwired/dactyl_manuform/5x6_5/keymaps/default/keymap.json
Fix keymap reference to the dactyl_manuform_5x6_5
=> fix: broken keyboard and keymap reference

keyboards/centromere/keymaps/mini_bom/config.h, keyboards/centromere/keymaps/mini_bom/keymap.c, keyboards/centromere/keymaps/mini_bom/readme.md, keyboards/centromere/keymaps/mini_bom/rules.mk
* add a keymap with chording, inspired by gboards gergoplex default, to the centromere mini keyboard.
=> add mini_bom chorded keymap

keyboards/lily58/keymaps/yshrsmz/config.h, keyboards/lily58/keymaps/yshrsmz/keymap.c, keyboards/lily58/keymaps/yshrsmz/rules.mk
- update my keymap for lily58
- apply breaking changes introduced [here](https://github.com/qmk/qmk_firmware/pull/6260/files)
*
=> update yshrsmz lily58 keymap

keyboards/handwired/onekey/keymaps/joystick/config.h, keyboards/handwired/onekey/keymaps/joystick/keymap.c, tmk_core/protocol/lufa/lufa.c
Addressing some of the points brought up by @sigprof in #4226 after merge. Not sure what to do about the ARM pin state save/restore, but if anyone has any ideas I can add them here.
*
=> Fix joystick compile issues

tmk_core/common/action_util.c
Fixes the handling for the oneshot cleanup, so it only cleans up if it is active.  It should not cleanup of SHO is off (eg using a normal oneshot key), nor if it's actively pressed or used.  
Previous behavior BROKE swap hand keys completely.
* Fixes #9967 
I've tested this out with a few of the keys to ensure that both OneShot Swap works, as well as some of the other Swap Hand keys work. 
Based on the code, the "cleanup" should only occur on timeout, and this is the simplest way to do this.
=> [Bugfix] Fix Swap Hands bug introduced by OSH

keyboards/keebio/bfo9000/config.h, keyboards/keebio/fourier/config.h, keyboards/keebio/iris/rev2/config.h, keyboards/keebio/levinson/rev1/config.h, keyboards/keebio/levinson/rev2/config.h, keyboards/keebio/nyquist/rev1/config.h, keyboards/keebio/nyquist/rev2/config.h, keyboards/keebio/quefrency/keymaps/drashna_ms/config.h, keyboards/keebio/quefrency/rev1/config.h, keyboards/keebio/viterbi/rev1/config.h, keyboards/keebio/viterbi/rev2/config.h
Change configuration for Keebio split boards to use the same RGB strip wiring for each half, which provides the following improvements:
1. Easier wiring due to one fewer wire needed (the wire between left DOut to extra data pin) and the fact that wiring is the same for both halves.
2. RGB LEDs can be controlled by each half now instead of just master half.
3. Extra data line is freed up to allow for I2C usage instead of serial.
Keebio docs have also been updated already to reflect new wiring setup.
*
=> Keebio RGB wiring update

docs/flashing.md, lib/python/qmk/cli/flash.py, tmk_core/chibios.mk
Add support for flashing the firmware via the `st-flash` utility from the STLink Tools package (https://github.com/stlink-org/stlink).
The ST-LINK CLI utility used by the `st-link-cli` target is proprietary and Windows-only; the `st-flash` utility is open source (BSD 3-clause), and the STLink Tools package (called `stlink`, or sometimes `stlink-tools`) is available in many Linux distributions and in Homebrew for Mac OS.
I tested this with some STM32 development boards:
* STM32F103C8T6 “Bluepill” with the [STM32duino user bootloader](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/) (the bootloader remains intact after flashing the `handwired/onekey/bluepill` firmware over ST-LINK)
* STM32F401CCU6 “Blackpill”
* STM32F411CEU6 “Blackpill”
The main reason for this PR is that some …
=> Add `st-flash` flash target

keyboards/planck/rev6/rev6.c, keyboards/planck/rev6/rules.mk
Specifically, don't want to have both RGBLight and RGB Matrix (with WS2812) enabled at the same time.  This will cause issues in usage, but apparently not when compiling.  Additionally, the led matrix was not encapsulated with preprocessor code.
=> [Keyboard] Fix Planck/Rev6 compiler issue

tmk_core/rules.mk
Adds a new subtarget to builds, `dump_vars`, which allows for printing out all the variables that make knows about, after all substitutions occur.
Example: `make handwired/onekey/proton_c:default:dump_vars`
=> Add ability to dump all makefile variables for the specified target.

docs/feature_auto_shift.md, quantum/process_keycode/process_auto_shift.c, quantum/quantum_keycodes.h
I added a config option called AUTO_SHIFT_SETUP for `autoshift_timer_report` `autoshift_enable` `autoshift_disable` funtions and  `KC_ASRP` `KC_ASUP` `KC_ASDN` keycodes
*
=> #define AUTO_SHIFT_SETUP

common_features.mk, platforms/chibios/GENERIC_STM32_F303XC/configs/mcuconf.h, quantum/backlight/backlight_timer.c
Now that ChibiOS has been updated, we can use GPT timers to emulate `Using hardware timer 1 with software PWM` without using the TIM1-4 PWM timers. Binding backlight to an out the way timer avoids conflicts with other features such as PWM ws2812 and allows for a more performant default behaviour for CTPC.
Next phase could be to migrate `BACKLIGHT_PWM_TIMER` from the avr backlight code.
=> ARM backlight - timer implementation

docs/feature_backlight.md, quantum/backlight/backlight.c
We have had the warning in place now for a while, with zero issues reported.
=> Remove f072 backlight warning

keyboards/handwired/onekey/keymaps/adc/keymap.c
Just a tiny bugfix. `SEND_STRING(str)` is shorthand for `send_string_P(PSTR(str))` which doesn't make sense for `buffer` here, as it has to be stored in RAM, not program memory.
*
=> Fix sendstring call in onekey ADC keymap

users/stanrc85/rgblight_layers.c, users/stanrc85/rgblight_layers_osa.c
Making better use of num lock and scroll lock indicators lights by using them for layer indicators instead. 
*
=> [Keymap] layer indicator lights

docs/keycodes.md, quantum/quantum_keycodes.h
Add codes to quantum_keycodes for LSA, RSA, RCS, and their corresponding _T macros
Per feature request 9942, added macro defines for common modifier combos.
1. LSA(kc) & LSA_T(kc) - Left Shift + Left Alt
2. RSA(kc) & RSA_T(kc) - Right Shift + Right Alt (Alt Gr)
3. RCS(kc) & RCS_T(kc) - Right Ctrl + Right Shift 
* Fixes #9942
=> Issue 9942: Add LSA, RSA, RCS, LSA_T, RSA_T, and RCS_T

.github/workflows/info.yml
At the moment, PRs can sometime fail due to the current method of detecting changes. The scenario as I currently understand is as follows:
1. Additional commits are added to master
2. Additional commits are added to PR
3. CI runs `git diff ....` which now reports the changes to master
=> Swap git diff logic to github action when running qmk info

keyboards/planck/keymaps/callum/keymap.c
I haven't yet established when this was fixed, but the workaround for #4072 no longer seems to be necessary! 🎉
=> [keymap] Removing #4072 workaround!

keyboards/redox/rev1/config.h
Enable left right RGB sync with #define RGBLIGHT_SPLIT macro
*
=> redox: sync RGB on left and right sides

tmk_core/protocol/vusb/usbconfig.h, tmk_core/protocol/vusb/vusb.c
- With the addition of https://github.com/qmk/v-usb/pull/1 a 3rd endpoint (endpoint4) becomes available.
- We can assign mouse/extrakeys to that endpoint as its a desirable feature and leave rawhid and console to compete for the 2nd endpoint.
NOTE: The version of vusb.c in future branch is older than master. Just remember that it will need a #error if both raw_hid and console are enabled at the same time.
*
=> Update vusb to match 3rd endpoint.

tmk_core/common/progmem.h, tmk_core/protocol/lufa/adafruit_ble.h, tmk_core/protocol/lufa/outputselect.c, tmk_core/protocol/lufa/outputselect.h, tmk_core/protocol/serial.h
Just some more prep work for Bluetooth API.
- Added `PGM_P` equivalent for ARM
- Include guards to `#pragma once` for some files I've touched (to make later diffs easier to read)
- Added `is_usb_configured()` for output selection, only LUFA implemented so far
More stuff ~~I may add to this PR~~ for the next PR:
- Rename `adafruit_ble.[cpp|h]` to `bluefruit_le`
- Remove `bluefruit_keyboard_print_report()` and change `bluefruit_serial_send()` usages to `serial_send()`
- Drop support for Adafruit EZ-Key (product discontinued)
*
=> More Bluetooth refactoring

keyboards/kbdfans/kbd6x/keymaps/dbroqua/keymap.c
Add dbroqua layout for kbd6x with HHKB style and RGB.
=> [kbdfans] Added dbroqua layout for kbd6x

keyboards/tada68/keymaps/rupa/config.h, keyboards/tada68/keymaps/rupa/keymap.c, keyboards/tada68/keymaps/rupa/readme.md, keyboards/tada68/keymaps/rupa/rules.mk, users/rupa/config.h, users/rupa/process_records.c, users/rupa/process_records.h, users/rupa/rules.mk, users/rupa/rupa.c, users/rupa/rupa.h, users/rupa/unicode.c, users/rupa/unicode.h
=> userspace and keymap for rupa

bootloader.mk, keyboards/ergodox_infinity/bootloader_defs.h, keyboards/ergodox_infinity/rules.mk, keyboards/infinity60/bootloader_defs.h, keyboards/infinity60/rules.mk, keyboards/k_type/bootloader_defs.h, keyboards/k_type/rules.mk, keyboards/whitefox/bootloader_defs.h, keyboards/whitefox/rules.mk, quantum/mcu_selection.mk, tmk_core/chibios.mk, tmk_core/common/chibios/bootloader.c
#9908 #10067 #10126
The ldscript selection in bootloader.mk was not happening because mcu_selection.mk overwrites the value of `MCU`. To solve this, we store the original value first before running through MCU selection, and use *that* in bootloader.mk.
*
=> Kiibohd bootloader, take 2

common_features.mk, keyboards/zvecr/split_blackpill/rules.mk, keyboards/zvecr/zv48/rules.mk
The PWM-based WS2812 driver on ChibiOS/STM32 requires DMA. For some reason, one of the definitions isn't set up correctly by ChibiOS, and requires manual intervention to get it to cooperate.
This PR ensures that the definition `STM32_DMA_REQUIRED` is correctly set when using the PWM driver.
=> Define STM32_DMA_REQUIRED when using DMA-based WS2812 driver on STM32.

drivers/chibios/ws2812_pwm.c
Some STM32 chips have `STM32_DMA1_STREAM1` as the first DMA stream, others (F4xx, F7xx, H7xx) have `STM32_DMA1_STREAM0`.  Instead of those names, use `STM32_DMA_STREAM(0)`, which should always give the first `stm32_dma_stream_t` structure in the DMA streams array, so that the stream ID would be calculated correctly.
I don't actually have the hardware to test the change at the moment (I found the problem when trying to adapt the DMA streams code from ws2812_pwm for a different purpose and running it on the F401 Blackpill board — the DMA completion callback was not invoked, because `dmaStreamAlloc()` was called for a wrong stream ID).
=> Fix DMA stream ID calculation in ws2812_pwm

quantum/rgb_matrix_drivers.c
Specifically, when rgb matrix is enabled and using the ws2812 driver, and rgb light is enabled at the same time, print a message about coexistence because it can cause issues, since you cannot change pins/config for the WS2812 driver.
=> Compiler warning when using WS2812 

docs/feature_rgblight.md, quantum/rgblight.c, quantum/rgblight.h
Add the no-eeprom versions of the speed functions for the RGB Light feature
* Closes #9504
=> Add noeeprom speed function for RGBLIGHT

tmk_core/common/chibios/suspend.c
This is present in the AVR suspend code, but missing here.
*
=> Fix ChibiOS backlight not turning off on suspend

tmk_core/common/matrix.h
The `matrix_col_t` type was added in commit 0284431ad9 (part of #3449), but then the code which used that type was removed in #6140, and no other users were added since that time.  The presence of that type, however, limits `MATRIX_ROWS` to 32, which probably does not matter for a real keyboard, but prevents doing things like making a firmware to test all existing pins on a board like Teensy++ 2.0 (which has 46 GPIOs).
=> Remove matrix_col_t to allow MATRIX_ROWS > 32

quantum/keymap_extras/keymap_spanish.h
`ES_DIAE` should be `S(ES_ACUT)` not `S(ES_GRV)`
*
=> Fixed Spanish keymap extra ES_DIAE symbol

keyboards/dmqdesign/spin/keymaps/gorbachev/config.h, keyboards/dmqdesign/spin/keymaps/gorbachev/keymap.c, keyboards/dmqdesign/spin/keymaps/gorbachev/readme.md, keyboards/dmqdesign/spin/keymaps/gorbachev/rules.mk
Add a new keymap for Spin macropad with OLED support.
=> Add keymap for DQM Design Spin macropad

keyboards/tmo50/tmo50.c, keyboards/tmo50/tmo50.h
The keyboard should implement `_kb` methods, not `_user`. This was causing conflict with the routines I defined in my user keymap.
*
=> Change TMO to use layer_state_set_kb as is customary at the keyboard level.

keyboards/1upkeyboards/1up60rgb/1up60rgb.h
The recent change to unnest macros put the enter on the wrong matrix key. On the 1uprgb, the ANSI and ISO enters share the same cell as does the ANSI and ISO backslash.
*
=> Fix broken enter on 1uprgb.

keyboards/keebio/viterbi/rev2/config.h
Replaced product id to distinguish rev2 from rev1.
replaced the product_ID from 0x1157 to 0x2157. Was given permission by bakingpy through discord chat.
* Same product ID of rev1 and rev2
=> replaced PRODUCT_ID 0x1157 with PRODUCT_ID 0x2157

keyboards/hineybush/h88/h88.c
change default RGB pattern for h88 and modernize the indicator LED functions
*
=> update h88 LED stuff

keyboards/centromere/keymaps/mattly/keymap.c, keyboards/centromere/keymaps/mattly/rules.mk
I added a layout for my centromere, and I believe this is the first user layout for this keyboard.
Since there wasn't a build guide, I soldered the switches in upside-down, so the layout is mirrored. If someone knows a better way to handle swapping the keycodes, I'd appreciate it.
For some reason it's also powering-on into the second layer (`OVER_WIN`) instead of the first layer. It's annoying but if anyone knows why I'd appreciate it.
*
=> mattly's mirrored centromere layout

common_features.mk, drivers/avr/serial.c, quantum/mcu_selection.mk
serial.c now support ATmega32U4 only. However, ATmega32U2 has a similar feature, and it's not difficult to add ATmega32U2. This change adds soft serial support to the ATmega32U2.
Thanks to @mtei for his help in sending this pull request. The most of the code came from his ideas.
=> Add support for soft serial to ATmega32U2

docs/ja/serial_driver.md
Add Japanese translation of docs/serial_drive.md.
*
=> [Docs] Japanese translation of docs/serial_driver.md

quantum/keymap_extras/keymap_canadian_multilingual.h
In commit 741c7d5eec7deb89a0043852ad711917137a5e61  CSA_LESS and CSA_GRTR were flipped when switched to using the CA_LABK and CA_RABK macros. This CL unflips them. 
- [ x] Bugfix
* 
=> Unflip < and > for canadian mutlilingual

keyboards/ergodox_ez/keymaps/nathanvercaemert/config.h, keyboards/ergodox_ez/keymaps/nathanvercaemert/keymap.c, keyboards/ergodox_ez/keymaps/nathanvercaemert/readme.md, keyboards/ergodox_ez/keymaps/nathanvercaemert/rules.mk
Updated personal keymap to include changes in mouse key acceleration. Also fixed minor bugs in tap dance functionality.
*
=> Personal Keymap (nathanvercaemert) Update

keyboards/converter/adb_usb/adb_usb.h
Make adb_usb/aek layout keypad equal key work.
=> [Keyboard] Fix adb_usb/aek layout keypad equal key

docs/feature_split_keyboard.md
Replace figures in docs/feature_split_keyboard.md
=> Replace figures in docs/feature_split_keyboard.md

tmk_core/avr.mk
Theoretically, this should get dfu-programmer to stop whinging about "Not blank at 0x1". Testers appreciated 👍
* Fixes #7624
=> Use the force when flashing with dfu-programmer

keyboards/lily58/readme.md
I don't think it is advisable to use sudo when using make. This changed the ownership of a lot of files within qmk.
=> Remove use of sudo in make docs

quantum/dynamic_keymap.c
Due to the return type of `uint16_t` it would be a temporary control to add in a check for the size
Previously it would compile with a number greater than 65535, e.g.  65536. 
However as shown in the issue below, the compiler only tells us when the #define is much larger than the `uint16_t` max size.
https://github.com/qmk/qmk_firmware/issues/8742 - see  more here
* Max EEPROM size check for dynamic keymaps
=> [Core] DYNAMIC_KEYMAP_EEPROM_MAX_ADDR check

drivers/avr/ssd1306.c, drivers/avr/ssd1306.h, keyboards/claw44/ssd1306.c, keyboards/claw44/ssd1306.h, keyboards/comet46/ssd1306.c, keyboards/comet46/ssd1306.h, keyboards/crkbd/ssd1306.c, keyboards/crkbd/ssd1306.h, keyboards/helix/local_drivers/ssd1306.c, keyboards/helix/local_drivers/ssd1306.h, keyboards/yosino58/ssd1306.c, keyboards/yosino58/ssd1306.h
From #9147,
```console
Linking: .build/crkbd_rev1_default.elf                                                              [ERRORS]
| 
| /usr/bin/avr-ld: .build/obj_crkbd_rev1_default/./lib/layer_state_reader.o:/home/nihilazo/projects/qmk_firmware/keyboards/crkbd/ssd1306.h:68: multiple definition of `display'; .build/obj_crkbd_rev1_default/ssd1306.o:/home/nihilazo/projects/qmk_firmware/keyboards/crkbd/ssd1306.h:68: first defined here
| /usr/bin/avr-ld: .build/obj_crkbd_rev1_default/./lib/logo_reader.o:/home/nihilazo/projects/qmk_firmware/keyboards/crkbd/ssd1306.h:68: multiple definition of `display'; .build/obj_crkbd_rev1_default/ssd1306.o:/home/nihilazo/projects/qmk_firmware/keyboards/crkbd/ssd1306.h:68: first defined here
| /usr/bin/avr-ld: …
```
=> Fix ssd1306 compilation on avr-gcc 10

keyboards/lfkeyboards/TWIlib.c, keyboards/lfkeyboards/TWIlib.h, keyboards/meira/TWIlib.c, keyboards/meira/TWIlib.h
```console
Making meira/featherble with keymap default                                                            [ERRORS]
| 
| /usr/bin/avr-ld: .build/obj_meira_featherble_default/keyboards/meira/meira.o:/home/zvecr/qmk_firmware/keyboards/meira/TWIlib.h:45: multiple definition of `TWIInfo'; .build/obj_meira_featherble_default/TWIlib.o:/home/zvecr/qmk_firmware/keyboards/meira/TWIlib.h:45: first defined here
| /usr/bin/avr-ld: .build/obj_meira_featherble_default/keyboards/meira/meira.o:/home/zvecr/qmk_firmware/keyboards/meira/TWIlib.h:28: multiple definition of `RXBuffLen'; .build/obj_meira_featherble_default/TWIlib.o:/home/zvecr/qmk_firmware/keyboards/meira/TWIlib.h:28: first defined here
| /usr/bin/avr-ld: .build/obj_meira_featherble_default/keyboards/meira/meira.o:/home/zvecr/qmk_firmwar …
```
=> Fix TWIlib compilation on avr-gcc 10

tmk_core/common.mk
Commit 92385b3fb617326b129609726020453c8949c7f8 renamed the `LINK_TIME_OPTIMIZATION_ENABLE` flag to `LTO_ENABLE`. Unfortunately, any configurations that were using the old flag but not caught under this merge (e.g. checked out on forks or other branches) have the side effect of having the optimizations silently disabled.
A few hours of debugging time was spent trying to figure out why a test keymap was suddenly throwing firmware too large errors at the final link step for an Iris keyboard after a `git pull`.
This change fails the build with an explicit error message **if and only if** the user has set `LINK_TIME_OPTIMIZATION_ENABLE` (the old name) but not `LTO_ENABLE`, in an effort to stave off questions to Discord about helping to debug this fun little issue.
*
=> Output an error message if LINK_TIME_OPTIMIZATION_ENABLE is set but LTO_ENABLE is not

keyboards/ergodox_infinity/ergodox_infinity.c
Make Ergodox Infinity sync calculated Words Per Minute between keyboard halves.
The Words Per Minute calculation feature from PR #8054 that was merged back in March included code to sync the WPM value between keyboard halves using the split_common framework. This PR adds code to Ergodox Infinity to sync the WPM value between its keyboard halves, since it's using a different transport mechanism (serial_link).
=> Make WPM able to sync between keyboard halves on Ergodox Infinity.

quantum/process_keycode/process_midi.c, quantum/process_keycode/process_midi.h, quantum/quantum_keycodes.h
I've been trying to make a MIDI keyboard based on QMK, and one of the challenges of using mechanical keyboard switches for this is the lack of velocity sensitivity. To compensate, I was trying to add velocity control with an analog input, like a potentiometer. To my disappointment, I wasn't able to use my potentiometer to change velocity freely between 0-127, as the current implementation forces velocity down to a range of 1-10 which is far too low resolution for my wants and needs. These changes are an attempt at fixing this without breaking the current velocity keycodes, to allow the old method to work, and open up for setting velocity directly with something as simple as
`midi_config.velocity = analogReadPin(POT_PIN) >> 3`
My changes are at a relatively low level so I wanted to make …
=> Change MIDI velocity implementation to allow direct control of velocity value

keyboards/handwired/onekey/rules.mk
There is no way to invoke the command feature while having just a single physical key, and disabling that feature fixes build for keymaps like `handwired/onekey/promicro:rgb` without resorting to LTO (the command feature consumes more than 4900 bytes with avr-gcc 8.4.0).
=> Disable the command feature for onekeys

keyboards/massdrop/alt/keymaps/default/keymap.c, keyboards/massdrop/alt/keymaps/default_md/keymap.c, keyboards/massdrop/alt/keymaps/mac/keymap.c, keyboards/massdrop/alt/keymaps/mac_md/keymap.c
The default keymaps don't make use of the global `keymap_config`
variable nor the `matrix_*_user()` functions.  Therefore, remove them to
avoid confusion for future keymap authors.
=> massdrop/alt: Remove unused user functions and config in default keymaps

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h
Split out from https://github.com/qmk/qmk_firmware/pull/10272. This adds a function to determine if the OLED is currently on, for usage in update code to make sure that you don't necessarily turn on the OLED again when it's currently off.
=> Add function to determine if the OLED is on

keyboards/crkbd/keymaps/bcat/keymap.c, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md
Just swapping out some shortcut keys I don't use for Chrome zoom keys (which I find myself perpetually mistyping on my ergo boards).
None
=> Swap ergo lower layer shortcuts for zoom keys in my personal keymaps

keyboards/metamechs/timberwolf/keymaps/a_ansi/keymap.c, keyboards/metamechs/timberwolf/keymaps/a_iso/keymap.c, keyboards/metamechs/timberwolf/keymaps/b_ansi/keymap.c, keyboards/metamechs/timberwolf/keymaps/b_iso/keymap.c, keyboards/metamechs/timberwolf/keymaps/default/keymap.c, keyboards/metamechs/timberwolf/keymaps/prime_ansi/keymap.c, keyboards/metamechs/timberwolf/keymaps/prime_iso/keymap.c, keyboards/metamechs/timberwolf/keymaps/via/keymap.c, keyboards/metamechs/timberwolf/timberwolf.c
Found that having encoder code in keymap files made it so that when you flashed firmware from qmk configurator, the encoder stopped working. moved the code to keyboard.c in order to fix that issue
*
=> moved encoder code to timberwolf.c

docs/feature_bluetooth.md, tmk_core/common.mk
Expand documentation in Bluetooth rules.mk options for requiring 
As seen in #10314, the Bluetooth documentation is missing some information about support for NKRO, and how enabling it can be problematic.
This change expands slightly on the Bluetooth feature documentation, and while not nearly comprehensive or sufficient for covering managing Bluetooth in qmk, could likely save some time and troubleshooting.
None
=> Add description in Bluetooth docs for requiring NKRO to be disabled

keyboards/flehrad/bigswitch/keymaps/via/keymap.c, keyboards/flehrad/bigswitch/keymaps/via/rules.mk
Add a VIA keymap for the big switch from flehrad
=> Bigswitch VIA Support

quantum/keymap_extras/sendstring_belgian.h
Specifically, the `BE_CIRC` is an alt-ed keycode, which means it 
doesn't fit into the 8 bit keycode range...  It should be `BE_SECT`,
as it is already alt-ed by the alt lut.
Confirmed that this change fixes compilation warnings and works 
correctly, on reddit. 
https://www.reddit.com/r/olkb/comments/iywin1/unsigned_conversion_from_int_to_unsigned_char/g6jvfgl/
* won't compile ... reporting in 2 reddit threads
=> Fix Belgian sendstring file

keyboards/lazydesigners/the30/keymaps/via/keymap.c, keyboards/lazydesigners/the30/keymaps/via/rules.mk
Add VIA support for lazydesigners\the30
*
=> Add VIA support for lazydesigners\THE30

quantum/keymap_extras/sendstring_belgian.h
`[` is on AltGr+`^` (dead circumflex, `BE_DCIR`), not the non-dead one (`BE_CIRC`).
#10443
*
=> Fix Belgian sendstring properly

keyboards/mxss/rgblight.c, quantum/rgblight.c
Just a really tiny style fix. `foo->bar` is equivalent to `(*foo).bar`, and these are the only places this notation is used. It most likely compiles to the exact same thing.
@MxBlu
*
=> `setrgb()`: Use arrow operator

docs/tap_hold.md
I corrected the incorrect "this repeats the tapped key **rather to** hold a modifier key." and used the opportunity to reword that paragraph in the Tapping Force Hold section a bit to make it clearer what is the *default* behaviour, and contrasted it with the `TAPPING_FORCE_HOLD` behaviour and let it know that it applies to all dual-role keys, not just mod-taps.
Additionally, I also formatted the example by putting the pressed keys between backticks as done everywhere else in the Tap Hold configuration settings documentation page.
Then, I also replaced the "tapping" in "One Shot Tapping Toggle" by simply "tap" because that's what the One-Shot documentation page uses exclusively.
Finally, I removed the quotes around the word "tapping" in `the "tapping" function` because they're …
=> [Docs] Wording & formatting changes in the Tapping Force Hold section of the Tap Hold page + removed trailing whitespaces

tmk_core/common/chibios/bootloader.c
Certain boards have their own implementation of `bootloader_jump()`, without setting `STM32_BOOTLOADER_ADDRESS`.
However, using the include files in `platforms/chibios/...` will generally end up defining the bootloader address -- either through `bootloader_defs.h` or adding to `rules.mk`.
This allows the existing platform definitions to coexist with boards which require their own bootloader jump logic.
=> ChibiOS upgrade: weak bootloader_jump

bootloader.mk, lib/python/qmk/constants.py, quantum/config_common.h, quantum/keymap.h, quantum/mcu_selection.mk
Setting `MCU = at90usb647` or `1287` would fail to compile, because there were no checks in mcu_selection.mk, bootloader.mk, and a few other places, that would catch it.
The xx7 parts seem to be essentially identical to the xx6, however they [also have the ability to act as a USB host](http://www.fourwalledcubicle.com/files/LUFA/Doc/170418/html/_page__a_v_r8_support.html). I don't think you can be in both modes at the same time though, but QMK doesn't have any host-mode capability anyway.
* https://old.reddit.com/r/olkb/comments/ii66i5/does_qmk_support_at90usb1287/
=> Add logic for AT90USBxx7 where needed

util/activate_msys2.sh, util/msys2_install.sh
Only thing left to do after this is to rework the driver installation step to use a temp dir, then we can eliminate ~/qmk_utils.
*
=> MSYS2: Switch to arm-none-eabi-gcc package

quantum/split_common/split_util.c
in split_util.c a code block `#ifdef`'d for AVR deals with specific USB features that only ATMega*U4 support, compilation on U2 fails like this:
```
quantum/split_common/split_util.c:77:5: error: implicit declaration of function 'USB_OTGPAD_On'; did you mean 'USB_REG_On'? [-Werror=implicit-function-declaration]
77 |     USB_OTGPAD_On();  // enables VBUS pad
|     ^~~~~~~~~~~~~
|     USB_REG_On
quantum/split_common/split_util.c:80:12: error: implicit declaration of function 'USB_VBUS_GetStatus' [-Werror=implicit-function-declaration]
80 |     return USB_VBUS_GetStatus();  // checks state of VBUS
|            ^~~~~~~~~~~~~~~~~~
```
This PR adjusts the ifdef to not attempt to use these facilities on ATmega16U2 and ATMega32U2 targets.
=> Fix SPLIT_KEYBOARD compilation for ATMega*U2, which doesn't have VBUS/OTG control

keyboards/crkbd/rev1/legacy/matrix.c, keyboards/crkbd/rev1/legacy/split_util.h
The OLED screen on the keyboard never turns off with the timeout as it supposed to.
With debugging output, it appears `keyboard_task()` in tmk_core/common/keyboard.c is constantly calling `oled_on()`. This only happens when `OLED_DRIVER_ENABLE` is defined and `OLED_DISABLE_TIMEOUT` is not defined.
It appears that the return value of `matrix_scam()` is interpreted as a boolean of whether there are updates. And the custom implementation of that function in crkbd returns a constant 1.
Thus I imitate the way quantum/matrix.c implement this return value and applied it to the crkbd implementation.
Despite a required change of the return type for `matrix_slave_scan()` from `void` to `uint8_t`, this function is never meant to and never does be called anywhere else. This change should not affect …
=> Crkbd implementing return value for matrix_scan()

layouts/community/ortho_4x12/junonum/keymap.c, layouts/community/ortho_4x12/junonum/rules.mk
Update `make` `rules.mk` for `community/ortho_4x12/junonum`
Update more specific `rules` for `community/ortho_4x12/junonum/`, specifically, for the Planck series and Let's Split Vitamins Included, which I personally own and use.
Also, an extremely minor indentation in the keymap file.
*
=> Update make rules for community/ortho_4x12/junonum

layouts/community/split_3x6_3/ddeklerk/keymap.c
Merges my split_3x6_3 layout into QMK. Very similar to my 4x12 layout from #10109.
Again, I did not feel the need for a readme.md, as it's a fairly simple keymap.
*
=> Add ddeklerk split_3x6_3 layout

keyboards/bm60rgb_iso/bm60rgb_iso.h, keyboards/bm60rgb_iso/keymaps/default/keymap.c
- correctly assigns the Non-US Backslash and Hash keys
- adds Function and Navigation keys
- use KC_GESC instead of KC_ESC to make Grave accent available
The layout is the ISO equivalent of QMK's `LAYOUT_60_ansi_arrow`, so I updated the layout macro, with an alias for backwards compatibility.
=> BM60RGB ISO: update default keymap and layout macro

keyboards/clawsome/fightpad/config.h, keyboards/clawsome/fightpad/fightpad.c, keyboards/clawsome/fightpad/fightpad.h, keyboards/clawsome/fightpad/info.json, keyboards/clawsome/fightpad/keymaps/default/keymap.c, keyboards/clawsome/fightpad/readme.md, keyboards/clawsome/fightpad/rules.mk
This is a 12-key macropad for fighting games
*
=> FightPad! macropad

keyboards/keebio/quefrency/keymaps/joestrong/README.md, keyboards/keebio/quefrency/keymaps/joestrong/config.h, keyboards/keebio/quefrency/keymaps/joestrong/keymap.c
Adds a UK ISO keymap for the 60% version of quefrency rev 2
*
=> Add joestrong keymap for quefrency rev 2

drivers/issi/is31fl3741.c, drivers/issi/is31fl3741.h
Fix up a few things about IS31FL3741 driver.
- Fix issue with data transfer of CS1_SW7 to CS18_SW7. https://github.com/qmk/qmk_firmware/pull/10519/commits/0e40e9e7097401ca01d682e0714af43178a3e838
- Fix issue with handling of scaling register buffer's dirty flag. https://github.com/qmk/qmk_firmware/pull/10519/commits/05731f157a33a0cc86ee9012b4fa312de016486c
- Remove unused extern declaration. https://github.com/qmk/qmk_firmware/pull/10519/commits/f792491a848b6ea2d0380f26071a9f023fe2ab87
- Compaction of struct is31_led utilizing bit fields. https://github.com/qmk/qmk_firmware/commit/46538d9cd153afd356bc45ab22137b7b88644b5e
* #9961
* https://github.com/qmk/qmk_firmware/issues/10423
=> IS31FL3741 driver fixup

drivers/oled/oled_driver.c
Fix several problems in the OLED driver:
1. `oled_write_pixel()` was unconditionally setting the dirty bit for the touched block, even if the pixel value was not actually changed. This made `oled_write_pixel()` unusable inside `oled_task_user()` if the implementation of `oled_task_user()` was redrawing the whole image unconditionally.
2. `oled_write_pixel()` did not handle the 90° or 270° rotation properly.
3. Attempting to override `OLED_BLOCK_COUNT` with a custom value in config.h resulted in a compile error, even though the documentation listed `OLED_BLOCK_COUNT` as one of the configurable values.
4. Using a custom `OLED_BLOCK_COUNT` could result in out-of-range accesses inside `oled_render()`, because in this case some bits in `oled_dirty` may not correspond to existing blocks, but …
=> OLED driver fixes

docs/feature_encoders.md, quantum/encoder.c
Allows you to define the resolution per-encoder, in case you are using mismatched encoders.
*
=> Per-encoder resolutions

docs/feature_mouse_keys.md, readme.md, tmk_core/common/action.c
If you enable mousekey (mouse keys) with pointing_device (pointing device) and add button keycodes to your keymap, you'll get a click from mousekey but drags with pointing_device movement won't work as button state needs to be sent with the move. If you handle the mousekey button keycodes yourself in process_record_user() to update pointing_device button state you'll break drags using mousekey movement. If you handle mousekey movement keycodes too then you've just re-implemented mousekey.
This change shares button state from mousekey to pointing_device to support simultaneous use of mousekey and pointing_device, including mouse drags with mousekey buttons and mousekey or pointing_device movement.
To use, enable mousekey and pointing_device and add button keycodes to keymap.  No extra code …
=> Share button state from mousekey to pointing_device

tmk_core/protocol/chibios/main.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/chibios/usb_main.h
Reconnect the USB if users wake up a computer from the keyboard to restore the USB state.
Keyboards using STM32 controllers with Chibios are suffering from keyboards that are frozen due to the USB state detection problem when waking up the computer from that keyboard.  The hotfix forces the keyboard to reconnect to the computer.
* #9962
=> Add hotfix for chibios keyboards not wake

docs/feature_rgb_matrix.md, quantum/rgb_matrix.c, quantum/rgb_matrix.h
The RGB Matrix indicators is currently getting called on every task cycle, regardless of the type of cycle. 
Additionally, it calls the entire code, which could be every LED in the matrix, which may be costly.  
This adds an "advanced" function that passes the min and max LEDs, and adds a function (a C macro), that will check to see if a specific LED is in the specified range and only set it if it is.  
This should reduce the number of LEDs set each cycle and make the indicators less costly/more efficient. 
* This is RGB we're talking about, you know I tested it :D
=> Add advanced/efficient RGB Matrix Indicators

keyboards/rominronin/katana60/rev2/keymaps/via/keymap.c, keyboards/rominronin/katana60/rev2/keymaps/via/rules.mk
This change adds VIA support to the katana60 rev2 board. I spoke to @rominronin to make sure that
we were not duplicating work and that was not the case. He approved of me adding this so here it is.
The layout was copied from the default with the 1a bottom row and split backspace since that's what
i have on my personal board.
N/A
=> Adding VIA support to katana60 rev2

quantum/process_keycode/process_rgb.c, quantum/rgb_matrix_drivers.c
Core fixes required for OpenDeck32.
Requested split from https://github.com/qmk/qmk_firmware/pull/10305#pullrequestreview-492256442 
* Allows the use of only one IS31FL3731 LED driver (instead of two)
* Removes unused variables when `RGB_MATRIX_DISABLE_KEYCODES` is set, preventing a clean compile with `-Werror`.
* (let me know if you want me to create issues for this, I'm refraining from doing it to avoid a race with some one fixing it before this is merged).
=> Allow the use of only one IS31FL3731 LED driver

quantum/process_keycode/process_midi.c
When duplicate notes are pressed, the duplicate notes keep ringing or make the sustain effect until you unplug the USB cable.
For example, "duplicate notes" here means **C**, **E** and **G**  when C chord (**C, E, and G**) and C7 chord (**C, E, G**, and A#) are pressed at the same time.  
This issue can be replicated with GarageBand, Logic Pro, Piano 10 (Windows), etc.
(Ableton Live 10 didn't have this problem.)
A quick fix was found as the modification shown in the process_midi.c code.
Assuming QMK Firmware is mainly based on the "common sense" that there are no duplicate keys on the single keyboard.
Number keys on the upper row and num-pad keys are individual keys.
Probably handling duplicate keys are not well-developed because of such reason.
I guess something irregular happens when …
=> Fix MIDI sustain effect issue

Makefile, build_keyboard.mk, message.mk
Adds support for building all keyboards, filtered by platform key.
Examples:
```
make all:default             # as before
make all-avr:default         # only build AVR-based keyboards
make all-chibios:default     # only build ChibiOS keyboards
make all-arm_atsam:default   # only build arm_atsam-based keyboards
```
=> ChibiOS upgrade: Filter 'all' builds by platform

lib/python/qmk/cli/doctor.py, lib/python/qmk/cli/info.py, lib/python/qmk/cli/json/keymap.py, lib/python/qmk/cli/json2c.py, lib/python/qmk/cli/kle2json.py, lib/python/qmk/cli/list/keymaps.py, lib/python/qmk/cli/new/keymap.py, lib/python/qmk/tests/.gitignore, lib/python/qmk/tests/test_cli_commands.py
With https://github.com/qmk/qmk_cli/pull/27 merged, subcommands can now produce exit codes when CLI is installed.
Any instances where `exit(1)` has been changed to `return False` would be broken until a new release of CLI is published (and the user updates it), but depending on whether anything currently relies on the exit codes this may not be an issue. I think this should also remove the need to [grep here](https://github.com/qmk/qmk_firmware/blob/master/.github/workflows/info.yml#L50), too.
*
=> CLI: update subcommands to use return instead of exit()

lib/python/qmk/info.py
Trying to fix the issue I discovered in https://github.com/qmk/qmk_firmware/pull/9528#issuecomment-648536062, where the presence of `DEFAULT_FOLDER` causes `qmk info` to check there first, even if we are as or more specific.
ie:
`qmk info -kb helix -l` should search `helix.h`, then `rev2/rev2.h`. But if we want `helix/rev1` instead, we should search there first, *then* fall back on `DEFAULT_FOLDER`, *then* search everywhere else.
*
=> Improve LAYOUT macro searching

keyboards/kbdfans/maja/maja.c
=> add  maja capslock indicator

lib/python/qmk/constants.py, lib/python/qmk/info.py
Aligns this logic more closely with that in qmk_compiler, and also fixes:
```
⚠ xd002: Unknown MCU: attiny85
```
*
=> CLI: Fix MCU lists for `qmk info`

lib/python/qmk/keymap.py
=> CLI: Fix stripping of `ANY` from Configurator exports

keyboards/ergodox_infinity/matrix.c, keyboards/ergodox_infinity/readme.md
Add EE_HANDS support to Ergodox Infinity.
Ergodox Infinity doesn't use the split_common framework, but either half (or both) can be connected to the computer (with the second half optionally connected to that half, to make them behave as a single keyboard). Currently, the two halves must be flashed with separate firmwares to be able to work "in both directions", which requires QMK to be rebuilt with MASTER=right.
This PR adds the ability to use the EE_HANDS feature on Ergodox Infinity, making it possible to flash both halves with the same firmware and still have them behave properly, regardless of how the two halves are connected to the computer. I also added a guide to set the required EEPROM values (in ergodox_infinity/readme.md), as it's currently a bit awkward on devices using …
=> Ergodox Infinity: Add EE_HANDS support.

docs/feature_combo.md
in tutorial for combos feature, changed type of compo_index argument of process_combo_event form uint8_t to uint16_t
Signature of process_combo_event in tutorial did not mach with the signature in process_combo.h
=> changed type of process_combo_event argument in tutorial

docs/ja/feature_bluetooth.md
=> Update feature_bluetooth.md of Japanese document.

docs/ja/feature_tap_dance.md
=> Update feature_tap_dance.md of Japanese document.

quantum/keymap_extras/sendstring_french.h
This is the sendstring part of #9611. There is still the matter of the dead/non-dead circumflex keycodes in `keymap_french.h`, but let's at least get this in first as it's not a potential breaking change.
* Fixes #9610
=> Partial fix for sendstring_french.h

docs/ja/config_options.md, docs/ja/custom_quantum_functions.md, docs/ja/documentation_best_practices.md, docs/ja/feature_dynamic_macros.md, docs/ja/feature_leader_key.md, docs/ja/feature_stenography.md, docs/ja/getting_started_make_guide.md, docs/ja/hardware_avr.md, docs/ja/hardware_keyboard_guidelines.md, docs/ja/reference_info_json.md
=> Update tags in japanese document to check for document updates

keyboards/eve/meteor/readme.md
Document boot-mode method for EVE Meteor. Some Meteor PCBs do not have the mentioned FW_JP contacts exposed. Instead, the +/= key is wired to the 32a controller pins responsible for triggering boot mode.
* Fixes #10452
=> Add documentation for additional boot-mode method for EVE Meteor.

keyboards/preonic/keymaps/dudeofawesome/keymap.c, users/dudeofawesome/dudeofawesome.h
I've wanted to help @NeoScaler with his bug. He couldn't compile Preonic (rev3) with dudeofawesome keymap as it wasn't prepared for STM and it had some issues described in [#10386](https://github.com/qmk/qmk_firmware/issues/10386).
* [#10386](https://github.com/qmk/qmk_firmware/issues/10386)
=> Fix for issue #10386 - Can't compile preonic:dudeofawesome

bootloader.mk, keyboards/wolfmarkclub/wm1/rules.mk
`MCU_LDSCRIPT` in bootloader.mk must use `=`, not `?=`, otherwise it will not set the correct value due to there already being one set from mcu_selection.mk. As a result, `wolfmark/wm1` cannot have this bootloader set because rules.mk is processed first, but it seems to actually have a custom mass storage bootloader anyway.
* Fixes #10645
=> Fix STM32duino bootloader

docs/mod_tap.md
This PR adds a link to the tap-hold config options page from mod-tap. Specifically, this will help users that are unaware of the available settings that affect mod-tap (like TAPPING_FORCE_HOLD).
=> Add documentation link to Tap-Hold Configuration Options from Mod-Tap

docs/_summary.md, docs/configurator_default_keymaps.md
=> [Docs] add "Adding Default Keymaps to QMK Configurator" doc

docs/faq_build.md, util/udev/50-qmk.rules
This makes it overall easier to package for downstream distributions
instead of keeping tabs with inline documentation.
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> 50-qmk.rules: Move udev rules from documentation into a file

lib/python/milc.py, lib/python/qmk/cli/doctor.py, lib/python/qmk/questions.py
This changes `cli.echo()` so that it strips ANSI when `--no-color` is used, the same way `cli.log.*` works. It also adds support for emoji log symbols when `--no-color` is used.
=> Improve ANSI support and --no-color

docs/feature_oled_driver.md, drivers/oled/oled_driver.c
This PR adds support for OLED_UPDATE_INTERVAL_MS to oled_driver.c.
Use of the OLED driver has degraded matrix scan performance.
The matrix scan rate can be improved by changing the update interval of the OLED display to the length specified by OLED_UPDATE_INTERVAL.
Example.
* OLED_DRIVER_ENABLE = no
```
*** yushakobo - Helix rev3 5rows connected -- 0x3265:0x3
> matrix scan frequency: 929
> matrix scan frequency: 1071
> matrix scan frequency: 1073
> matrix scan frequency: 1074
```
* OLED_DRIVER_ENABLE = yes
```
*** yushakobo - Helix rev3 5rows connected -- 0x3265:0x3
> matrix scan frequency: 220
> matrix scan frequency: 301
> matrix scan frequency: 299
> matrix scan frequency: 299
```
* #define OLED_UPDATE_INTERVAL 30
```
*** yushakobo - Helix rev3 5rows connected -- 0x3265:0x3
> matrix …
```
=> OLED display update interval support

lib/python/qmk/cli/doctor.py
```
⚠ Missing udev rules for 'massdrop' boards. See https://docs.qmk.fm/#/faq_build?id=linux-udev-rules for more details.
```
* Fixes #10692
=> Fix CLI warning for Massdrop udev rule

keyboards/gh60/v1p3/keymaps/default/keymap.c
The vendor contacted nMaib0 (who provided me with the initial files I used to generate this source) with an inquiry as to whether the default keymap could be posted on QMK Configurator. I've converted their JSON keymap to C here.
=> GH60 v1.3: update default keymap

common_features.mk
Adds a `#define` based on the currently selected serial driver, so that preprocessor can be used to modify functionality in code.
Djinn has a serial driver based off the normal `serial_usart.c`, but adds arbitrary data transfer from master to slave and back.
Would be useful if I could determine which serial driver was in use from `users/` and modify my user area's functionality accordingly.
=> Add definition based on currently-selected serial driver.

common_features.mk
These MCUs do not have a hardware multiplier, for some odd reason. Thus lib8tion needs to treat it like an ATtiny device, and multiply in software instead.
```
Compiling: quantum/rgb_matrix.c                                                                    /tmp/cc8GITYA.s: Assembler messages:
/tmp/cc8GITYA.s:33: Error: illegal opcode or for mcu avr35
```
See also https://github.com/FastLED/FastLED/issues/24#issuecomment-35154603
*
=> Fix RGB matrix for ATmegaxxU2

docs/config_options.md, docs/tap_hold.md, tmk_core/common/action.c
This is the last tap-hold config option that was lacking a per-key configuration.  It should behave as the others, where enabling `RETRO_TAPPING_PER_KEY` with no `get_retro_tapping` sieve defined will behave is if the feature weren't enabled at all.
*
=> New feature: Retro Tapping per key

quantum/rgb_matrix.c, quantum/rgb_matrix_animations/alpha_mods_anim.h, quantum/rgb_matrix_animations/breathing_anim.h, quantum/rgb_matrix_animations/gradient_left_right_anim.h, quantum/rgb_matrix_animations/gradient_up_down_anim.h, quantum/rgb_matrix_animations/jellybean_raindrops_anim.h, quantum/rgb_matrix_animations/raindrops_anim.h, quantum/rgb_matrix_animations/solid_color_anim.h, quantum/rgb_matrix_animations/typing_heatmap_anim.h, quantum/rgb_matrix_runners/effect_runner_dx_dy.h, quantum/rgb_matrix_runners/effect_runner_dx_dy_dist.h, quantum/rgb_matrix_runners/effect_runner_i.h, quantum/rgb_matrix_runners/effect_runner_reactive.h, quantum/rgb_matrix_runners/effect_runner_reactive_splash.h, quantum/rgb_matrix_runners/effect_runner_sin_cos_i.h, quantum/rgblight.c
The Djinn has the ability to dynamically change the current limit of the RGB LEDs on the PCB.
When they pull too much current, they brownout and stop working, unsurprisingly at higher brightness values.
This PR introduces a hook that can be overridden by keyboards in order to dynamically modify the output RGB values with code, for example scaling the max brightness depending on the USBPD negotiation state:
```c
RGB rgblight_hsv_to_rgb(HSV hsv) {
float scale = 0.2f;
if (current_3000mA) {
scale = 0.55f;
} else if (current_1500mA) {
scale = 0.32f
}
hsv.v = (uint8_t)(hsv.v * scale);
return hsv_to_rgb(hsv);
}
```
Unsure if we need documentation for this -- it's pretty low-level and unlikely to be used terribly frequently.
=> RGB output hooks

docs/custom_quantum_functions.md, tmk_core/common/keyboard.c, tmk_core/common/keyboard.h, tmk_core/protocol/arm_atsam/main_arm_atsam.c, tmk_core/protocol/chibios/main.c, tmk_core/protocol/lufa/lufa.c, tmk_core/protocol/vusb/main.c
When developing some lower-power modes, there was a need to be able to execute `__WFI()` (wait for interrupt) at the end of each loop iteration in order to get the MCU to go into sleep mode, after all QMK-related processing had occurred.
This PR is an extension of that requirement, alowing for keyboards/keymaps to arbitrarily execute some "housekeeping" code at each iteration of the main loop.
Example:
```c
void housekeeping_task_kb() {
__WFI();
}
```
=> Allow keyboards/keymaps to execute code at each main loop iteration

docs/feature_backlight.md, quantum/backlight/backlight_avr.c, quantum/backlight/backlight_chibios.c
Needed to be able to apply a limit to the backlighting duty cycle -- breadboard testing of using QMK's backlight code to control an LCD backlight showed it was pulling 80mA, but in circuit with SMT components it showed it was capable of pulling 400mA per LCD.
Artificially limiting the duty cycle allows controlling max brightness instead of messing about with current limiting circuits, much like the RGB limit constants we already have.
=> Allow backlight duty cycle limit

keyboards/moonlander/matrix.c
Fixes issue with the indicator LEDs flashing during sleep.
This is because it re-inits the expander during `matrix_power_up`, which triggers this behavior.  This moves things around a bit, so that it matches the actual initialization better, and stores the state for leds, peventing it from constantly flashing them.
=> [Keyboard] Fix Moonlander indicator LEDs during sleep

keyboards/percent/canoe_gen2/rgb_matrix_kb.inc
Made the static color preset for the indicator RGB LEDs on Canoe Gen2 configurable instead of static white.
=> make Canoe Gen2 static indicator rgb color configurable

.github/workflows/api.yml, .gitignore, api_data/_config.yml, api_data/readme.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/c2json.py, lib/python/qmk/cli/generate/__init__.py, lib/python/qmk/cli/generate/api.py, lib/python/qmk/cli/info.py, lib/python/qmk/cli/json2c.py, lib/python/qmk/cli/list/keyboards.py, lib/python/qmk/constants.py, lib/python/qmk/datetime.py, lib/python/qmk/decorators.py, lib/python/qmk/info.py, lib/python/qmk/keyboard.py, lib/python/qmk/keymap.py, lib/python/qmk/tests/test_qmk_keymap.py
Generate keyboard API data and push it to the qmk_keyboards repo.
=> Generate api data on each push

drivers/oled/oled_driver.c
This is a minor change to the previous PR: https://github.com/qmk/qmk_firmware/pull/10388
Per discussion in that PR, the main cause of the scanning performance hit was the oled_task frequency, not the display updates as they were guarded by a dirty flag. This change allows the oled to be flushed if there is still dirty data in between oled_task ticks. The benifit of this approach is that the oled display remains, in all appearances, still performant while retaining the high matrix scan rates as achieved by not running oled_task so frequently.
*
=> Oled task update timer change

drivers/haptic/haptic.c, quantum/backlight/backlight_avr.c, tmk_core/common/action.c, tmk_core/common/report.h
=> qmk cformat

quantum/process_keycode/process_unicode_common.c
Especially useful if you have your OS layout set to something non-US ANSI, where the number row is flipped (such as French AZERTY).
For example, you could add the following to your keymap.c:
```c
uint16_t hex_to_keycode(uint8_t hex) {
switch (hex) {
case 0:
return FR_0;
case 1 ... 9:
return FR_1 + (hex - 1);
case 0xA:
return FR_A;
case 0xB:
return FR_B;
case 0xC:
return FR_C;
case 0xD:
return FR_D;
case 0xE:
return FR_E;
case 0xF:
return FR_F;
default:
return KC_NO;
}
}
```
*
=> Allow modified keycodes in Unicode input

tmk_core/protocol/usb_descriptor.h
The `KEYBOARD_SHARED_EP=yes` option was breaking the VIA support, because the raw HID interface number in this case was 0 instead of 1, and the VIA app depends on the exact interface number for raw HID. Change the interface ordering to put the shared interface before the raw HID interface if `KEYBOARD_SHARED_EP` is enabled, so that the raw HID interface can keep its number.
I verified this on XD87 HS (atmega32u4, no official VIA JSON yet), bare Pro Micro flashed with `make contra:via:flash KEYBOARD_SHARED_EP=yes`, and bare Bluepill (STM32F103) flashed with `make cannonkeys/practice60:via:flash KEYBOARD_SHARED_EP=yes` (VIA JSON in a pending and buggy PR). In all those cases just adding `KEYBOARD_SHARED_EP=yes` prevented the board from being detected in the Linux VIA app; applying the patch …
=> Fix KEYBOARD_SHARED_EP incompatibility with VIA

keyboards/projectkb/alice/alice.h, keyboards/projectkb/alice/info.json, keyboards/projectkb/alice/keymaps/default/keymap.c, keyboards/projectkb/alice/keymaps/via/keymap.c, keyboards/projectkb/alice/rev2/rules.mk, layouts/community/alice/stanrc85-alice/keymap.c, layouts/community/alice/stanrc85-alice/rules.mk, layouts/default/alice/default_alice/keymap.c
Added support for LAYOUT_alice to projectkb/alice/rev2 keyboard.  
Updated layout macros for Default and VIA keymaps.  I confirmed the following compile and flash successfully:
-km default
-km via
-km stanrc85-alice (https://github.com/qmk/qmk_firmware/pull/10696)
-km default-alice
~~The following users will need to update their keymaps (LAYOUT_default to LAYOUT_alice)
-devinceble
-keithlo
-madhatter~~
I also had to update the LAYOUT_alice default keymap to add an additional BSPC to match the typical Alice PCB layout to have split backspace as option.
*
=> Add Projectkb/alice/rev2 LAYOUT_alice support

keyboards/massdrop/alt/readme.md, keyboards/massdrop/ctrl/readme.md
Update the link to the Massdrop Loader releases page to point to the releases index rather than release 0.0.1 (current version is 1.0.5). This will reduce the chance that someone will get stuck using an old version of `mdloader`
=> docs(massdrop alt/ctrl): update link to loader releases

docs/feature_oled_driver.md, drivers/oled/oled_driver.c, drivers/oled/oled_driver.h, keyboards/handwired/onekey/keymaps/oled/keymap.c
🔅 🔆
The SSD1306 datasheet calls this "contrast", probably a holdover from LCDs, but since OLEDs emit light, it is actually brightness.
The VCOM deselect level was changed from 0x40 to 0x20 in order to get what seems (to me) to be a larger brightness range - at 0x40 the OLED is quite bright but at brightness level 0, the display only dims a little bit. Likewise, when set to 0x00, the maximum brightness is noticeably dimmer, but the minimum is *much* dimmer. 0x20 appears to be the sweet spot from my 5 seconds of experimentation (I also note that this is the value upon reset). Maybe there is some way to dynamically change the VCOM deselect along with the brightness level...
*
=> Add brightness level API to OLED driver

keyboards/idb/idb_60/idb_60.c, keyboards/idb/idb_60/idb_60.h
=> [Keyboard] Fix function references IDB 60

.github/workflows/api.yml
When testing some other actions on my master branch, i noticed it tried to run the process to push API data. It didnt manage as it doesnt have a `API_TOKEN_GITHUB` secret, but this change makes it skip and not fail at the end of the process.
=> Protect API actions against those who develop with their fork on master

keyboards/aeboards/ext65/rev2/rev2.c, keyboards/xelus/trinityxttkl/trinityxttkl.c
Change matrix io delay to use nops. They have been tested working.
* Fix 500 scan rate
=> Fix keyboard matrix scan rate with F072

lib/python/qmk/cli/info.py, lib/python/qmk/keyboard.py, lib/python/qmk/tests/test_cli_commands.py
Replaced #10734 with something more useful.
MinGW Python on MSYS2 has trouble rendering the box drawing characters (because it's a native binary and thus thinks the character set is cp1252). As a hacky workaround, we can use ASCII characters instead.
It's not as pretty, but it's something.
*
=> `qmk info`: Add `--ascii` flag

keyboards/nk65/config.h, keyboards/nk65/nk65.c
Due to some manufacturing constrains, a large number of NK65s have been made (but not sold) with a F303CB chip.
After contacting ST the Application Engineer has informed me that CB and CC share the same die, but CB is validated to have working Flash up to 128KB. This means that in both versions of the chip, 256KB are addressable but not necessarily functioning. 
This workaround asks for the size of the flash memory from the internal register. This means that it will auto adjust to 128KB or 256KB.
This saves adding a whole new chip class "F303xB" that chibios doesn't have, probably because the only difference is the flash size. Downside is that the every time there is an eeprom access an extra cycle is used to read that register. This is the reason I opted to not add it in core.
*
=> NK65 eeprom compatibility with 128KB and 256KB

keyboards/handwired/riblee_f411/config.h, keyboards/handwired/riblee_f411/halconf.h, keyboards/handwired/riblee_f411/mcuconf.h, keyboards/handwired/riblee_f411/rules.mk, layouts/community/ortho_5x12/riblee/keymap.c, users/riblee/riblee.c, users/riblee/riblee.h
This PR adds OLED support for my F411 based keyboard.
The KB can receive strings via the RAW HID interface and can display them after the current layer. This can be useful for displaying system information such as CPU utilization and temperature.
=> Add OLED support for Riblee F411

keyboards/ploopyco/mouse/mouse.c, keyboards/ploopyco/mouse/readme.md, keyboards/ploopyco/mouse/rules.mk, keyboards/ploopyco/trackball/readme.md
* Fix inverted Y access. 
* Remote ISP flashing info (not needed on the mouse)
* Minor tweaks
=> [Keyboard] Fixes for PloopyCo mouse and readme

docs/cli_commands.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/clean.py, lib/python/qmk/tests/test_cli_commands.py
Currently the CLI can compile firmware, but it can't clean them up.
*
=> CLI: Add `qmk clean`

quantum/rgb_matrix_drivers.c
This is a simple change.Support for IS31FL3731 has been changed from 2 to 4.
*
=> Add support for 4 IS31FL3731 devices

keyboards/exclusive/e85/config.h, keyboards/exclusive/e85/hotswap/hotswap.c, keyboards/exclusive/e85/hotswap/keymaps/via/rules.mk, keyboards/exclusive/e85/soldered/keymaps/via/rules.mk, keyboards/exclusive/e85/soldered/soldered.c
Both the e85 soldered and hotswap PCBs support in-switch backlighting. This PR enables it for the VIA keymaps.
Also update the LED indicator code for both soldered and hotswap PCBs to handle both caps and scroll lock LEDs.
cc: @mechmerlin 
* None
=> E85 backlight & LED indicator updates

keyboards/crkbd/keymaps/bcat/config.h, keyboards/crkbd/keymaps/bcat/readme.md, keyboards/crkbd/keymaps/bcat/rules.mk, keyboards/eco/keymaps/bcat/config.h, keyboards/eco/keymaps/bcat/keymap.c, keyboards/eco/keymaps/bcat/readme.md, keyboards/eco/keymaps/bcat/rules.mk, keyboards/lily58/keymaps/bcat/keymap.c, keyboards/lily58/keymaps/bcat/readme.md, layouts/community/split_3x6_3/bcat/config.h, layouts/community/split_3x6_3/bcat/keymap.c, layouts/community/split_3x6_3/bcat/readme.md, layouts/community/split_3x6_3/bcat/rules.mk, users/bcat/config.h, users/bcat/readme.md
* Adds a keymap for my Eco.
* Refactors my Crkbd keymap to use the new split 3x6 + 3 thumb keys community layout and to work with Split Common.
* Tweaks my Lily58's bottom row slightly to match the new Eco keymap.
* Updates documentation on my personal keymaps and userspace.
* Adds copyright notices to .c and .h files changed in this PR. (I'll add them to other files in the future.)
None
=> Add Eco keymap, factor Crkbd keymap to community layout, other minor tweaks

.github/workflows/lint.yml, docs/cli_commands.md, docs/hardware_keyboard_guidelines.md, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/lint.py, lib/python/qmk/info.py, lib/python/qmk/path.py
Adds a command for checking over a keyboard/keymap.
=> New command: qmk lint

keyboards/underscore33/rev1/keymaps/default/config.h, keyboards/underscore33/rev1/keymaps/default/keymap.c, keyboards/underscore33/rev1/keymaps/default_big_space/config.h, keyboards/underscore33/rev1/keymaps/default_big_space/keymap.c, keyboards/underscore33/rev1/keymaps/default_big_space/readme.md, keyboards/underscore33/rev1/keymaps/default_big_space/rules.mk, keyboards/underscore33/rev2/keymaps/default/config.h, keyboards/underscore33/rev2/keymaps/default/keymap.c, keyboards/underscore33/rev2/keymaps/default_big_space/config.h, keyboards/underscore33/rev2/keymaps/default_big_space/keymap.c, keyboards/underscore33/rev2/keymaps/default_big_space/readme.md, keyboards/underscore33/rev2/keymaps/default_big_space/rules.mk
Accidentally left off big spacebar default keycaps
*
=> Add big spacebar defaults to Underscore33 

keyboards/mschwingen/modelm/modelm.c
Specifically, the lgreen variable isn't used, and avr-gcc 8.x complains about this. To prevent it from being an issue, just set all of these led variables to be unused.
* Another case of avr-gcc 8+ not liking how things are done
=> [Keyboard] Fix unused variables in mschwingen modelm

common_features.mk, tmk_core/common/keyboard.c
Add a Make variable to easily enable DEBUG_MATRIX_SCAN_RATE on the command line.
eg.
```
make DEBUG_MATRIX_SCAN_RATE_ENABLE=yes  KEYBOARD:KEYMAP
```
=> add DEBUG_MATRIX_SCAN_RATE_ENABLE to common_features.mk

tmk_core/common/action_util.c, tmk_core/common/action_util.h
To be consistent with all the other mod functions in `action_util` that all had a `add...mods(mods)` and `del...mods(mods)` function, I added similar functions for one shot mods.
`add_oneshot_mods` takes a modmask as an argument and adds the modifier passed in argument to the one shot mod state by ORing the two together. The one shot timer gets also updated.
`del_oneshot_mods` disables the passed modifier(s) in the current one shot mod state in the same fashion as all other del...mods functions in the file. The one shot timer gets reset to 0 if no shot mod is left after the deletion but gets restarted if there still remains a one shot modifier. Please let me know if you find any pitfalls in changing the one shot timer this way.
Aside from adding two new functions, I also:
Deleted …
=> [Core] Added `add_oneshot_mods` & `del_oneshot_mods`

keyboards/handwired/onekey/blackpill_f401/blackpill_f401.c
By default the `i2c_master` driver for ChibiOS uses the B6 pin for `I2C1_SCL` and the B7 pin for `I2C1_SDA`.  However, the ChibiOS board file used for the F401 Blackpill board (`ST_STM32F401C_DISCOVERY`) configures B6 as `I2C1_SCL` and B9 as `I2C1_SDA`, and if that configuration is left unchanged, enabling the `i2c_master` driver results in having two pins (B7 and B9) configured as `I2C1_SDA` at the same time, which does not work properly (experimental results show that the B9 pin still works as `I2C1_SDA` in that case, and the B7 pin does not work).
Configure the B9 pin as an input with pull-up in `board_init()`, so that the B7 pin can be configured as `I2C1_SDA` by the I2C driver.
Tested on a Blackpill board marked “WeAct V3.0” with STM32F401CCU6 and several OLED displays (with a keymap …
=> handwired/onekey/blackpill_f401: Fix I2C pin config mismatch

drivers/oled/oled_driver.c
The documentation for these APIs say that they write to the buffer from the current cursor position, but they would always write from the start of the buffer irrespective of the current cursor.
Use the current cursor position as the start location to write the raw data to the oled buffer.
Docs: https://github.com/qmk/qmk_firmware/blob/master/docs/feature_oled_driver.md#L283-L290
*
=> Use cursor position as start index for oled_write_raw and oled_write_raw_P

lib/python/qmk/cli/doctor.py, lib/python/qmk/tests/test_cli_commands.py, util/udev/50-qmk.rules
- Only check ModemManager if Caterina udev rule is not found.
- Not all udev implementations support 'RUN{builtin}+="uaccess"', so we only check it on systemd systems where `systemd-udevd` is likely used.
@sigprof could you test it with `eudev`?
*
=> CLI: Udev related fixes and improvements

keyboards/ymdk_np21/ymdk_np21.h
I noticed that my KC_PPLS and KC_PENT keys weren't actually doing
anything. By looking at the ortho_6x4 layout, I guessed that maybe the
pins were incorrect and guessed the proper ones. Now, my numpad is fully
functional.
It's quite possible that this is only the case for my specific board (maybe a mistake during soldering?), however.
=> [Keyboard] YMDK NP21: correct numpad layout matrix

keyboards/helix/rev2/keymaps/five_rows/keymap.c, keyboards/helix/rev2/keymaps/five_rows/layer_number.h, keyboards/helix/rev2/keymaps/five_rows/oled_display.c, keyboards/helix/rev2/keymaps/five_rows/rules.mk, keyboards/helix/rev3_5rows/keymaps/five_rows/config.h, keyboards/helix/rev3_5rows/keymaps/five_rows/keyboard_post_init_user_scan.c, keyboards/helix/rev3_5rows/keymaps/five_rows/keymap.c, keyboards/helix/rev3_5rows/keymaps/five_rows/layer_number.h, keyboards/helix/rev3_5rows/keymaps/five_rows/oled_display.c, keyboards/helix/rev3_5rows/keymaps/five_rows/rules.mk
Clean up my keymap 'helix:five_rows'
* Makes the OLED driver used by the helix:five_rows keymap switchable.
* Separated the OLED related code from keymap.c and moved it to oled_display.c.
* Removing unused audio-related code.
* Stopped using `LAYOUT_kc()`.
* Ported the keymap from helix/rev2:five_rows to helix/rev3_5rows:five_rows.
ssd1306.c v.s. oled_driver.c (helix/rev2:five_rows)
|text size | data size | bss size | OLED          |scan rate | configure      |
|----------|-----------|----------|---------------|----------|----------------|
| 18880    | 58        | 235      | none          | 1590     | Helix old code |
| 18554    | 40        | 231      | none          | 1202     | split_common   |
| 24048    | 196       | 342      | ssd1306.c     | 739      | Helix old code |
| 23750    | …
=> [Keymap] clean up helix:five_rows keymap

quantum/keymap_extras/keymap_french_osx.h
I encountered an error while compiling my french osx based keymap.
I noticed `FR_LSAQ` was defined twice and `FR_RSAQ` was missing, probably a miss copy/paste on #8700.
So... here is my one char contribution :)
* #8700
=> Fix typo causing `redefined error` in keymap_french_osx 

keyboards/planck/keymaps/bghull/keymap.c, keyboards/planck/keymaps/bghull/rules.mk, keyboards/preonic/keymaps/bghull/keymap.c, keyboards/preonic/keymaps/bghull/rules.mk
First PR! Finally trying to get my user keymaps up in the main repo so I can stop losing my keymaps as I learn how to use git on the command line...
*
=> Add user keymaps to qmk master

keyboards/anavi/macropad8/keymaps/default/keymap.c, keyboards/anavi/macropad8/keymaps/kodi/keymap.c
Improvements and bug fixes for the keymaps kodi and default for
ANAVI Macro Pad 8:
- Add space to the end of string "Active layer: " for better
visibility on the mini I2C OLED display for both keymaps
- Replace "Main" with "Kodi" for the Kodi keymap
- Add comment with reference to Kodi documentation for the
available shortcuts in this keymap
Improvements and bug fixes for the keymaps kodi and default for ANAVI Macro Pad 8 as explained in the git commit message.
*
=> [Keymap] ANAVI Macro Pad 8 fix kodi and default

Makefile
`quantum/version.h` was not being updated when builds with `SKIP_VERSION=yes` occur, breaking sha1sum validation.
This PR ensures `quantum/version.h` is written even with values of "NA".
=> Fixup version.h

Makefile
Certain locations in the codebase rely on the length of the `QMK_BUILDDATE` string. 
This PR hard-codes a known value in the expected format.
=> version.h BUILD_DATE fix

keyboards/melody96/keymaps/zunger/keymap.c
Move the combining accents to fn + (keys used by Mac OS for that purpose),
and move the fn key to be the one adjacent to the space bar, since one needs
to type combinations of that a lot more than one needs to type Greek letters
in normal use. (As determined by experiment)
Also clean up the comments.
=> Update the melody96/zunger layout to make typing Romance languages easier

drivers/avr/serial.c
Adds support for the AT90USB chips in the serial driver for AVR.
=> Add AT90USB support for serial.c

tmk_core/common/bootmagic_lite.c, tmk_core/common/keyboard.c, tmk_core/common/keyboard.h
This function is used a couple of places for split keyboards, but never actually set in the core (outside of split code), so there is no direct way to reference it. 
This adds it to `keyboard.[ch]` so that it can be used everywhere. 
* DMs on discord
=> Add references for is_keyboard_left()

keyboards/yoichiro/lunakey_mini/keymaps/via/keymap.c, keyboards/yoichiro/lunakey_mini/keymaps/via/rules.mk
This pull request adds a new keymap to support VIA for Lunakey Mini keyboard.
=> VIA support for Lunakey Mini keyboard.

docs/feature_auto_shift.md, quantum/process_keycode/process_auto_shift.c, quantum/process_keycode/process_auto_shift.h, quantum/quantum.c
Instead of waiting for the next record to tap the autoshiftable key, register a matrix_scan function that will check the timeout and register the key immediately if the timeout period has elapsed.  This means the user gets immediate feedback about their press and doesn't have to guess whether it's been long enough.
Additionally, don't unregister the keypress immediately.  This means that auto-shifted keys can be held down.
* #7048 
I've tested with `AUTO_SHIFT_ENABLE`, `NO_AUTO_SHIFT_ALPHA` on an Ergodox EZ, with taps, holds, and tap-then-holds, and rollovers to autoshiftable and non-autoshiftable keys.  There are a lot of edge cases.
=> Auto shift: support repeats and early registration

docs/feature_split_keyboard.md
Adds section on how to add VBUS support to Teensy 2.0 and Teensy++ 2.0, so that Split USB Detect isn't needed. 
*
=> [Docs] Add VBUS hack for teensys

docs/serial_driver.md, drivers/chibios/serial_usart.c
Added an option to allow overriding the serial usart timeout. Reducing this on a STM32F303CC Split has shown a noticeable improvement on keyboard startup speed as well as a very small improvement on matrix scan speed. Going from 100ms to 10ms made it startup significantly faster (sadly didn't time it), and the scan speed improved by ~50 scans per second.
Recreation of PR: https://github.com/qmk/qmk_firmware/pull/11013
*
=> Configurable serial usart timeout

tmk_core/common/timer.h
Small change to the timer_expired macros to fix cases on ARM where the int wrapping did not happen as expected, making the macros always return true. Additionally, switched from using a hex value for the half mark to the int max macros instead for clarity.
*
=> Fix int wrapping for timer_expired macros 

lib/python/qmk/tests/test_cli_commands.py, util/travis_build.sh, util/travis_test.sh, util/travis_utils.sh
Currently a lot of things trigger full builds that shouldn't. This changes our core code identification strategy from "all directories we haven't excluded" to "all directories we have explicitly included."
=> Reduce travis load by replacing an exclusive grep with an inclusive grep

quantum/quantum.h, quantum/rgb_matrix.c, quantum/rgblight.c, quantum/split_common/transport.c, tmk_core/common.mk, tmk_core/common/keyboard.c, tmk_core/common/sync_timer.c, tmk_core/common/sync_timer.h
Added a sync_timer set of apis that will keep their value in sync across split common keyboards. This helps keeps led animation effects in sync when run in split modes (RGBLIGHT_SPLIT or the upcoming RGB_MATRIX_SPLIT). This PR is targeting the development branch as this is a change to the Transport code which will require users to flash both master and slave halves.
~~Spent quite a bit of time poking at RGBLIGHT fixing the hitching of the previous attempts at a sync timer. Solved all the hitching, but it still does not stay in sync as well as I would like (when RGBLIGHT_SPLIT_NO_ANIMATION_SYNC  is defined) due to how animation ticks are handled in RGBLIGHT. So while it's using the sync timer, it's not any better than what it was before. Additionally an option to disable the sync timer and …
=> Sync Timer feature

keyboards/handwired/6macro/config.h, keyboards/handwired/6macro/rules.mk
RGB Matrix wasn't enabled previously, but was enabled in develop.  This is causing the keyboard to fail on build
* Travis CI
=> [Keyboard] Fix compiler issues for handwired/6macro

keyboards/xelus/valor/rev1/rules.mk
Turn the default rgb underglow on as it should be.
* Turn on RGB underglow by default
=> Fix Valor default underglow

keyboards/kyria/keymaps/default/config.h
Add recommendation to default firmware https://docs.splitkb.com/hc/en-us/articles/360017633199-The-keyboard-behaves-erratically-after-changing-the-RGB-settings
*
=> Fix issue where leds can pull too much power and crash the keyboard

keyboards/facew/config.h
The fix compiles OK. But I don't have the corresponding hardware so I cannot actually test it.
TBH, I have a feeling that this code has no user at all.
I need consistency of MATRIX_ROWS and MATRIX_COLS against MATRIX_ROW_PINS and MATRIX_COL_PINS respectively for all keyboards to shape my next PR complete.
Could you help? @mechmerlin
* https://github.com/qmk/qmk_firmware/issues/8106
=> Fixed: inconsistent MATRIX_COLS and MATRIX_COL_PINS in facew.

keyboards/cannonkeys/an_c/rules.mk, keyboards/cannonkeys/db60/rules.mk, keyboards/cannonkeys/devastatingtkl/rules.mk, keyboards/cannonkeys/instant60/rules.mk, keyboards/cannonkeys/instant65/rules.mk, keyboards/cannonkeys/obliterated75/rules.mk, keyboards/cannonkeys/rekt1800/rules.mk, keyboards/cannonkeys/satisfaction75/rules.mk, keyboards/cannonkeys/savage65/rules.mk, keyboards/cannonkeys/tmov2/rules.mk
Allow APM32 MCUs on certain CannonKeys PCBs
We'll do this by removing the DFU suffix which locks in the firmware to just STM32 device ids.
*
=> Allow APM32 MCUs on certain CannonKeys PCBs

platforms/chibios/GENERIC_STM32_F042X6/configs/config.h, platforms/chibios/GENERIC_STM32_F072XB/configs/config.h
F042/F072 aren't entering bootloader by default because the define for bootloader during early init isn't set.
This also affects bootmagic, as it can't reset to bootloader.
This PR cherry-picks running the early init code from the develop branch.
=> Fix: Add default early-init bootloader to F042/F072.

tmk_core/protocol/usb_descriptor.c, tmk_core/protocol/vusb/vusb.c
Saves a handful of bytes. There don't seem to be any boards in the repo which override the default value of "0".
*
=> Omit serial number if not defined

drivers/avr/spi_master.c
This PR fixes two issues with the AVR SPI master driver, specifically in the error handling in `spi_receive`.  As it is, errors are only detected in the last byte and, more importantly, received zero bytes are ignored.  The fix follows the simplest path of returning immediately in case of error, operating under the assumption that partial reads would be useless anyway.
I have currently no easy way to test this as my keyboard doesn't use the `spi_master` driver, or any of the QMK functionality that currently depends on it, so I have only verified that it compiles properly and that it looks like a reasonable fix.  Sorry for that.
Let me know if you like me to make any changes.
=> Fix error handling in SPI master driver.

drivers/oled/oled_driver.c
Added checks before transmits to see if the oled was properly initialized. If not, these checks will early out before the i2c transmit calls reducing wait timeouts from lagging the keyboard.
*
=> Added OLED Initialized checks

quantum/rgblight_list.h
Added "black" to RGB color definitions, including a synonym "off".
Code using pre-defined color definitions switches back and forth between defines and static values. This enables standardization.
e.g.
```
rgb_matrix_set_color_all(0, 0, 0);
rgb_matrix_set_color(41, RGB_WHITE);
```
becomes
```
rgb_matrix_set_color_all(RGB_OFF);
rgb_matrix_set_color(41, RGB_WHITE);
```
etc.
Deprecated functions have intentionally not been modified.
=> Add defines for RGB/HSV black(off).

docs/ws2812_driver.md, drivers/chibios/ws2812.c, drivers/chibios/ws2812_pwm.c, drivers/chibios/ws2812_spi.c, quantum/color.h
While flashing and repairing some hbcp PCBs, I realized that the LEDs were not showing the correct color - specifically that the red and green channels were reversed. The LEDs on the board are WS2812B-2020 from WorldSemi. I replaced one LED with a WS2812C-2020, and it was the correct colors, according to the VIA output (and QMK). After examining the datasheets for each LED, I found that even though the software is the same (G, R then B, 1 byte each) the hardware is not - the red and green LEDs are reversed physically! 
https://i.imgur.com/kB3mPyI.jpg
https://i.imgur.com/dmB1aY1.png
I created a definition, `WS2812_BYTE_ORDER` in color.h to define the byte order for the LED. The RGB definition swaps the R and G bytes and corrects the color issue.
https://i.imgur.com/sLcRLYU.jpg
If …
=> add definition WS2812_BYTE_ORDER to fix RGB LED issues

keyboards/massdrop/alt/keymaps/abishalom/keymap.c, keyboards/massdrop/alt/keymaps/bonta/keymap.c, keyboards/massdrop/alt/keymaps/default/keymap.c, keyboards/massdrop/alt/keymaps/default_md/keymap.c, keyboards/massdrop/alt/keymaps/favorable-mutation/keymap.c, keyboards/massdrop/alt/keymaps/mac/keymap.c, keyboards/massdrop/alt/keymaps/mac_md/keymap.c, keyboards/massdrop/alt/keymaps/reywood/keymap.c, tmk_core/protocol/arm_atsam/i2c_master.c, tmk_core/protocol/arm_atsam/i2c_master.h
According to the official documentation[1] gcc 10 is more strict about
correct extern usage.
I've had to split the definition and declaration of dmac_desc and dmac_desc_wb
from i2c_master.{c,h}. This could be an issue if anyone includes the
i2c_master.h file without liking with the object file.
I've also had to remove the keymap_config definition from all the massdrop alt
keymaps, since it's defined in magic.c as well. The same would have to be done
for other keymaps. It doesn't seem like any of the in-tree keymaps use the
variable anyway. Anyone using it would have to declare it extern in their
keymap.
With these changes all the in-tree keymaps for the massdrop alt now compiles in
gcc 10
* #9268 (This issue tracks multiple problems, this fixes part of it)
=> gcc 10 compatibility for Drop alt

keyboards/duck/tcv3/matrix.c
Apparently our matrix changes to accomodate debounce were flawed and didn't work with Duck TC-V3, this commit reverts back to what it was before. 
*
=> Revert back to the old matrix (Take the blue pill)

keyboards/custommk/genesis/config.h, keyboards/custommk/genesis/genesis.c, keyboards/custommk/genesis/genesis.h, keyboards/custommk/genesis/info.json, keyboards/custommk/genesis/keymaps/default/keymap.c, keyboards/custommk/genesis/keymaps/default/readme.md, keyboards/custommk/genesis/keymaps/numpad/keymap.c, keyboards/custommk/genesis/keymaps/numpad/readme.md, keyboards/custommk/genesis/keymaps/via/keymap.c, keyboards/custommk/genesis/keymaps/via/readme.md, keyboards/custommk/genesis/keymaps/via/rules.mk, keyboards/custommk/genesis/readme.md, keyboards/custommk/genesis/rules.mk
Adding keyboard and keymap files for customMK Genesis, a 5x4 macro pad.
N/A
=> Add customMK Genesis Macro Pad

keyboards/kb_elmo/aek2_usb/config.h, keyboards/kb_elmo/aek2_usb/keymaps/via/keymap.c, keyboards/kb_elmo/aek2_usb/keymaps/via/rules.mk
Added a VIA keymap for my AEK2 USB PCB.
The Keymap only has two dynamic layers because the 32A doesn't support more for a matrix of that size.
=> add via layout for aek2 usb pcb

platforms/chibios/keyboard-config-templates/board.h, platforms/chibios/keyboard-config-templates/chconf.h, platforms/chibios/keyboard-config-templates/halconf.h, platforms/chibios/keyboard-config-templates/mcuconf.h
Just a include search path fix for the ChibiOS config templates to match the automated conversion command.
=> Fixup config template to match <> instead of "" for includes.

.github/workflows/format.yaml, .travis.yml, lib/python/qmk/cli/__init__.py, lib/python/qmk/cli/fileformat.py, util/travis_compiled_push.sh
Migrate formatting logic from travis to CLI, hock up to GitHub Actions.
=> CI: Add workflow for codebase formatting

lib/python/qmk/cli/cformat.py
Was producing the following error:
```
qmk cformat -a
☒ sequence item 0: expected str instance, PosixPath found
File "/home/zvecr/.local/lib/python3.8/site-packages/milc/milc.py", line 415, in __call__
File "/home/zvecr/.local/lib/python3.8/site-packages/milc/milc.py", line 420, in __call__
return self._entrypoint(self)
File "/home/zvecr/qmk_firmware/lib/python/qmk/cli/cformat.py", line 65, in cformat
cformat_run(files, cli.args.all_files)
File "/home/zvecr/qmk_firmware/lib/python/qmk/cli/cformat.py", line 27, in cformat_run
cli.log.warning('Filenames passed with -a, only formatting: %s', ','.join(files))
```
However on further inspection the condition for when the warning should be displayed was also in the …
=> Fix warning logic when running 'qmk format -a'

quantum/rgblight.c
When `rgblight.c` includes `rgblight_breathe_table.h`, the search order should be as follows.
* `keyboards/KEYBOARD/keymaps/USER/rgblight_breathe_table.h`
* `users/USER/rgblight_breathe_table.h`
* `quantum/rgblight_breathe_table.h`
However, the current implementation was wrong, so I fixed it.
Currently, there are only two custom rgblight_breathe_table.h
* `users/drashna/rgblight_breathe_table.h`
* `users/curry/rgblight_breathe_table.h`
At first glance, `curry` does not seem to be alive at present. The following command will result in an error regardless of this PR.
```
make all:curry
```
Therefore, only `users/drashna` is affected by this PR.  (Tag @drashna)
This PR will be merged into `master`, since the affected area is clear.
=> Fix incorrect search order for `rgblight_breathe_table.h` that `rgblight.c` includes.

quantum/split_common/transport.c
And moved the sync timer define to match its placement in the struct.
*
=> Fix duplicate I2C_KEYMAP_START define

keyboards/helix/rev2/keymaps/default/oled_display.c
In the `helix:default` keymap, the OLED display on the right side was showing garbage, which has been fixed.
`helix:default`の右側のOLEDディスプレイにゴミが表示されていたのを修正しました。
@MakotoKurauchi, could you please review this?
=> [Keymap] fix keyboards/helix/rev2/keymaps/default/oled_display.c

util/list_keyboards.sh
The recent change to getting the list of keyboards broke instances where they get injected via symlink.
=> Follow symlinks when listing keyboards.

tmk_core/protocol/vusb/vusb.c
There is only one Raw HID report descriptor.
*
=> Fix small typo in V-USB configuration descriptor

quantum/process_keycode/process_unicode_common.h, quantum/process_keycode/process_unicodemap.c
As @sigprof mentions in #9533, this was broken in #8770. Now that `unicodemap_index()` is called before the unicode input functions, it must use the current modifier state, not the saved state.
* Issue #9533 
* Issue #9405 (partially)
=> Fix Issue #9533 - Delayed shift state handling 

keyboards/ymd75/config.h, keyboards/ymd75/rev1/config.h, keyboards/ymd75/rev2/config.h, keyboards/ymd75/rev3/config.h
Since the change from the Atmega32a to Atmega32u4. The pin for the per-key LED backlight has changed. As a result, the pin that worked on the older versions does not work on this model anymore.
Hope this change could help some troubled users who are trying to flash the default YMD75 rev 3 firmware.
Source (where I found the correct pin): `http://mtkeyboard.vip`
- add new BACKLIGHT_PIN in the default layout for YMD75/rev 3
*
=> YMD75 rev 3:  fix BACKLIGHT_PIN

tmk_core/protocol/vusb/main.c
The ordering of these function calls now match that of the LUFA code. Bootmagic Lite appears to still function, and the board sends the first key event again.
* Fixes #11251
=> V-USB: Fix initial dropped keypress

docs/feature_rawhid.md, tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c
The issue stems from the documentation mentioning the following:
```
`raw_hid_receive` can receive variable size packets from host with maximum length `RAW_EPSIZE`.
```
However, the current implementation of the `udi_hid_raw_report_rcvd` is that the incoming report needs to be `UDI_HID_RAW_REPORT_SIZE` otherwise it is ignored and thrown away. @fauxpark pointed out this out as I was having difficulties having my keyboard respond to the data I was sending it.
N/A
=> Updated Raw HID docs to clarify packet/report length

tmk_core/chibios.mk
PLATFORMASM is currently not added to ChibiOS build, potentially breaking builds with platforms that need it.
=> chibios: honor PLATFORMASM in chibios build

keyboards/helix/rev3_5rows/keymaps/five_rows/config.h, keyboards/helix/rev3_5rows/keymaps/five_rows/keyboard_post_init_user_scan.c, keyboards/helix/rev3_5rows/keymaps/five_rows/rules.mk
fix and update helix/rev3_5rows:five_rows
* fix rgblight animation selection
* use `DEBUG_MATRIX_SCAN_RATE_ENABLE` insted of keyboard_post_init_user_scan.c
* Change the initial value of the ENCODER_ENABLE to 'no' in 'rev3_5rows/keymaps/five_rows/rules.mk'
* Add '#define OLED_UPDATE_INTERVAL 100'  into 'rev3_5rows/keymaps/five_rows/config.h'
=> [Keymap] fix and update helix/rev3_5rows:five_rows

docs/feature_rgb_matrix.md
Added more clarification on how to use a newly created rgb effect as it was unclear that the prefix 'RGB_MATRIX_CUSTOM_' had to be added.
Also included an example consistent with the documentation example.
=> Add clarification on use of custom RGB Matrix effect

keyboards/helix/rev2/keymaps/five_rows/config.h, keyboards/helix/rev2/keymaps/five_rows/oled_display.c, keyboards/helix/rev2/keymaps/five_rows/rules.mk
Update rules.mk and config.h of `helix/rev2:five_rows`
* align rgblight animation selection method to `rev3_5rows/keymap/five_rows`.
* align OLED driver selection method to `rev2/keymap/default`.
=> [Keymap] update rules.mk and config.h of `helix/rev2:five_rows`

keyboards/tunks/ergo33/keymaps/default/keymap.c, keyboards/tunks/ergo33/keymaps/prpro/keymap.c
`HSV_OFF` was added to core, but not removed from this keymap, causing compile errors. 
* CI
=> [Keyboard] Fix default keymap for tunks/ergo33

quantum/rgb_matrix.c
Before, when disabling RGB, the indicators would still show up, and not be cleaned up properly.  This uses the `effect` value to both check the suspended state and the enabled status (effect is 0 if suspended or rgb is disabled, otherwise it has a value equal to the mode).  
Tested and verified that this works correctly (no "after image" so to speak). 
* Me, testing stuff
=> [Bug] Fix RGB Matrix Indicators

keyboards/nullbitsco/nibble/big_led.c, keyboards/nullbitsco/nibble/big_led.h
I wrote a simple convenience method for the Nibble's big LED to make setting custom RGB combos easier, and figured I'd upstream it.
Currently the Nibble provides three methods in `big_led.h`: `set_big_LED_r`, `set_big_LED_g` and `set_big_LED_b`. If you want to turn on two of these, it's a bit annoying that you have to call two methods, so I wrote `set_big_LED_rgb` as a convenience method to delegate this out.
N/A
=> Add convenience method for setting NIbble's big LED RGB

util/install/debian.sh
To successfully compile bootloadHID, we must have the libusb-config tool, which comes from the libusb-dev package. This package is available in both Ubuntu Groovy and Debian Buster
=> Add missing Debian/Ubuntu dependency to the install script

keyboards/kyria/kyria.h
This adds a macro to support the 2 x 2u layout which facilitates
a cleaner looking layout configuration for the people using it.
I did check with Thomas beforehand and he seemed fine with this addition.
N/A
=> Add support to Kyria for the 2 x 2u layout

util/install/fedora.sh
On a clean fedora 33 install, building BootloadHID fails because libusb-devel is not installed as a dependency
=> Add libusb-devel dependency for fedora

keyboards/keebio/bdn9/rev2/config.h
Wrong pin used for the left encoder, should be A4
This resulted in the left encoder not working correctly on a newly built BDN9v2
*
=> Correct encoder pins on BDN9v2

build_keyboard.mk, tmk_core/common/command.c, tmk_core/rules.mk
The `check-md5` target provides an easy way to check the md5 checksum of the generated binary.  This target will generate the binary and then display its md5 checksum.
~The `build-for-compare` target provides an easy way to check the md5 checksum of the generated binary. This target generates a binary without embedding the git version and qmk version, and then displays the md5 checksum for that binary.~
You can easily see if there is any change in the generated binaries between the two versions, as in the example below.
```
$ git checkout 0.11.0
M	build_keyboard.mk
M	tmk_core/rules.mk
Note: checking out '0.11.0'.
HEAD is now at c66df1664 2020 November 28 Breaking Changes Update (#11053)
$ make clean
$ make helix:all:check-md5 | grep ^MD5
MD5 (.build/helix_rev2_default.hex) = …
```
=> Add target 'check-md5' to `build_keyboard.mk`

keyboards/mode/eighty/config.h, keyboards/mode/eighty/m80h/config.h, keyboards/mode/eighty/m80s/config.h
Make M80S and M80H have different PRODUCT_ID descriptors for VIA reasons. This PR substitutes #11370  because I'm dumb and my mom probably cries in the shower because of it.
Since M80S and M80H have different layout topologies -- M80S supporting more alternate layouts like split backspace and split right shift -- both need different VIA json files and hence they need different PRODUCT_ID descriptors so VIA can detect them uniquely. This PR makes M80S with 0x0080 and M80H with 0x0081.
*
=> Change PRODUCT_ID descriptors for M80S and M80H

util/list_keyboards.sh
This PR makes utils/list_keyboards.sh speed up.
`utils/list_keyboards.sh` invokes `sed` for each keyboards/*/rules.mk lines, it takes long time.
but it could be replaced by only one `sed` invoke.
This PR does it.
It improves on especially Windows, x12 faster on my environment.
```console
$ time ./util/list_keyboards.before.sh | md5sum
4875b109258156499fbc26095e8c1f53 *-
real    1m3.038s
user    0m14.086s
sys     0m44.983s
```
```console
$ time ./util/list_keyboards.sh | md5sum
4875b109258156499fbc26095e8c1f53 *-
real    0m4.908s
user    0m0.482s
sys     0m4.496s
```
nothings.
=> make list_keyboards.sh faster

quantum/rgblight.c
This fixes a bug that occurred if there were more than 16 lighting layers in use. Layers 16 and above could not be enabled due to an error in the bitwise arithmetic used to update `rgblight_status.enabled_layer_mask`.
=> Fix broken Lighting Layers when RGBLIGHT_MAX_LAYERS > 16 (layer>=16 not operable)

drivers/chibios/spi_master.c
In the AVR SPI driver, `spi_write()` performs a simultaneous write and read due to how the SPI protocol works. Thus you can transmit a byte and get a "response" back with the same function call.
The Bluefruit LE code does just this - it sends the first byte of a packet and reads the simultaneous response back from the module to check if it is ready to accept data. If not, we back off and try again later:
(example from Pro Micro; the top three lines are MISO, bottom three are MOSI)
Except when I tested this on a Proton-C, it looked like this "not ready" signal was being ignored...
So, I ~~rewrote the `spi_transmit()` and `spi_receive()` functions to match the AVR driver, and~~ called `spiExchange()` in `spi_write()` instead.
I can now type over Bluetooth on a Proton-C :)
*
=> Align ChibiOS spi_master behaviour with AVR

util/install/macos.sh
If a user has pinned formulae in Homebrew, `brew upgrade` will return nonzero:
```
Already up-to-date.
Error: Not upgrading 1 pinned package:
mysql 8.0.22_1
==> No packages to upgrade
```
As this is the last thing that is run during `_qmk_install_prepare()`, it provides the return code of the function, which is then checked in `qmk_install.sh` - if nonzero, the script does not proceed with `_qmk_install()`. So we must add the `--ignore-pinned` flag:
```
--ignore-pinned              Set a successful exit status even if pinned
formulae are not upgraded.
```
* https://old.reddit.com/r/olkb/comments/koww09/qmk_setup_troubles_cant_find_in_path_during_qmk/
=> Homebrew install: ignore pinned formulae in `brew upgrade`

keyboards/clueboard/2x1800/2019/info.json, keyboards/clueboard/66_hotswap/gen1/rules.mk, keyboards/lizard_trick/tenkey_plusplus/info.json, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/info.py
A few keyboards were broken by my info.json work.
*
=> Fix broken keyboards on develop

build_keyboard.mk, tmk_core/rules.mk
Fixes up build dependencies so that the generated files are correctly made available previous to compiling any object files.
=> Fix up build dependencies.

keyboards/handwired/tennie/keymaps/default/config.h, keyboards/handwired/tennie/keymaps/default/keymap.c, keyboards/marksard/leftover30/keymaps/default/keymap.c, quantum/process_keycode/process_space_cadet.c, quantum/process_keycode/process_space_cadet.h, quantum/process_keycode/process_tap_dance.c, quantum/quantum.h, tmk_core/common/action_tapping.h
Makes sure that `action_tapping.h` is always included, by adding it to `quantum.h`
Includes the proper prototypes for all of the tap-hold per key functions. 
This makes sure that TAPPING_TERM is picked up consistently, and will error out if it's defined incorrectly.  And same for the per key functions.
=> Fix Tap-Hold Configs

keyboards/kingly_keys/ave/ortho/keymaps/default/keymap.c, keyboards/kingly_keys/ave/staggered/keymaps/default/keymap.c
Tapping term was referenced, but not defined by default.  
* Travis CI
=> [Keyboard] Fix compiler errors for Kingly Key boards

tmk_core/common/avr/bootloader.c
Allows for a custom implementation of bootloader_jump() for non-standard bootloaders on AVR.
This allows for a cleaner override compared to catching RESET in process_record_* and implementing bootmagic_lite().
=> AVR weak bootloader_jump

keyboards/nightly_boards/octopad/config.h
Is compiling too large right now, due to audio and rgblight being "fully enabled". 
Disabling music mode is a simple way to reduce the size, especially on a macropad that is unlikely to use it, due to the lack of keys available. 
* Travis CI faiilures
=> [Keyboard] Disable music mode on OctoPad to reduce size

keyboards/nightly_boards/octopad/rules.mk
This make the compiled `nightly_boards/octopad` firmware small enough to flash. I have not tested this on an actual octopad but the via keymap already has this enabled so it should be safe enough.
Before this PR:
```
Checking file size of nightly_boards_octopad_default.hex
* The firmware is too large! 29582/28672 (910 bytes over)
```
After this PR:
```
Checking file size of nightly_boards_octopad_default.hex
* The firmware size is fine - 26210/28672 (91%, 2462 bytes free)
```
=> Enable LTO to bring nightlyboards/octopad size down

tmk_core/rules.mk
The following variables have been added to `tmk_core/rules.mk` for build debugging.
* DUMP_C_MACROS
* VERBOSE_LD_CMD
* VERBOSE_AS_CMD
* VERBOSE_C_CMD
* VERBOSE_C_INCLUDE
If you specify the source file name in this `DUMP_C_MACROS` Makefile variable, you can observe the definition of the C macro that is finalized at compile time.
Usage:
```
% make lets_split/rev2:mjt:clean
% make DUMP_C_MACROS=keymap.c lets_split/rev2:mjt > /tmp/macrolog
% grep RGBLIGHT /tmp/macrolog
```
<details>
<summary><strong>The result is as follows:(click)</strong></summary>
```
| #define RGBLIGHT_EFFECT_KNIGHT 
| #define RGBLIGHT_SAT_STEP 17
| #define RGBLIGHT_EFFECT_SNAKE_LENGTH 4
| #define RGBLIGHT_EFFECT_ALTERNATING 
| #define RGBLIGHT_EFFECT_CHRISTMAS_STEP 2
| #define RGBLIGHT_EFFECT_TWINKLE_PROBABILITY 1 / 127 …
```
=> Add build debug option to tmk_core/rules.mk

keyboards/lily58/keymaps/barabas/config.h, keyboards/lily58/keymaps/barabas/keymap.c, keyboards/lily58/keymaps/barabas/readme.md, keyboards/lily58/keymaps/barabas/rules.mk
=> Added my lily58 keymap

keyboards/nullbitsco/nibble/keymaps/iso/keymap.c, keyboards/nullbitsco/nibble/nibble.h
Enter and backslash keys were accidentally flipped on the ISO keymap, this PR corrects that. Tested and confirmed with an ISO build. Replaced Tilde with Home in the ISO keymap to make it better match the documentation.
* None
=> Update NIBBLE ISO keymap to fix flipped enter and backslash key.

data/schemas/keyboard.jsonschema, keyboards/hineybush/hbcp/config.h, keyboards/nek_type_a/config.h, keyboards/nek_type_a/matrix.c, lib/python/qmk/c_parse.py, lib/python/qmk/cli/generate/config_h.py, lib/python/qmk/info.py
Somehow these things broke even though my last PR was compiling clean.
=> Another round of develop fixing

docs/newbs_getting_started.md
On Arch, `qmk` is now in the official repos, whereas only `qmk-git` is in AUR.
=> Fix AUR package name

docs/feature_rgblight.md
The documentation of the following functions incorrectly indicated that they wrap around at minimum and maximum:
- `rgblight_increase_sat()`
- `rgblight_increase_sat_noeeprom()`
- `rgblight_decrease_sat()`
- `rgblight_decrease_sat_noeeprom()`
- `rgblight_increase_val()`
- `rgblight_increase_val_noeeprom()`
- `rgblight_decrease_val()`
- `rgblight_decrease_val_noeeprom()`
The documentation has been updated to indicate that they stop at the minimum or maximum value, as appropriate for each.
=> Correct documentation of rgblight_{increase,decrease}_{sat,val}() 

data/schemas/keyboard.jsonschema, keyboards/clueboard/60/info.json, keyboards/clueboard/60/rules.mk, keyboards/clueboard/66/rev4/info.json, keyboards/clueboard/66/rev4/rules.mk, keyboards/clueboard/66_hotswap/gen1/info.json, keyboards/clueboard/66_hotswap/gen1/rules.mk, keyboards/clueboard/california/info.json, keyboards/clueboard/california/rules.mk, keyboards/cmm_studio/saka68/info.json, lib/python/qmk/cli/generate/rules_mk.py, lib/python/qmk/info.py
`BOARD` was added while I was working on my data driven qmk  project. This adds support for specifying it in info.json like everything else.
=> Add support for specifying BOARD in info.json

keyboards/handwired/freoduo/config.h
Configurator compiles fail without the number of LEDs defined here. Included the rest to match the default keymap's settings.
cc @FilipParyz
=> handwired/freoduo: define RGBLight config at keyboard level

docs/hardware_avr.md
The documentation did not accurately reflect the behaviour of `lsusb` , which might result in minor confusion.
On Fedora 32 (and I assume most other distributions), `lsusb` will display the configured `MANUFACTURER` and `PRODUCT` if the database does not contain entries for the `VENDOR_ID` and `PRODUCT_ID` used. Considering the DB does not contain any entries for the vendor `0xFEED`, it should just display the values as advertised by the device.
Similarly, doing a `lsusb -v` will not show those values, as it seems that a regular user does not have the required permissions to read them. It will just leave the field empty. Doing a `sudo lsusb -v` fixes this.
Most don't apply because it's just a two-line documentation fix.
=> Fix documentation of `lsusb` behaviour

keyboards/keebio/quefrency/keymaps/rogthefrog/config.h, keyboards/keebio/quefrency/keymaps/rogthefrog/keymap.c
Quefrency 65-key layout with space on the right side and enter on the left.
None.
=> Quefrency layout for rogthefrog

keyboards/wheatfield/split75/keymaps/default/keymap.c, keyboards/wheatfield/split75/keymaps/iso/keymap.c, keyboards/wheatfield/split75/split75.h
The pcb used for wheatfield/split75 supports ANSI and ISO layout. This
commit adds the ISO variant.
=> wheatfield/split75 with ISO layout

quantum/rgblight.c, quantum/rgblight.h, tmk_core/common/avr/suspend.c, tmk_core/common/chibios/suspend.c
The current implementation of RGBLIGHT_SLEEP does not disable lighting layers on suspend if RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF is defined. This was an oversight when it was originally implemented, resolved in this pull request.
I have also refactored RGBLIGHT_SLEEP somewhat to eliminate some duplicate code, and to improve encapsulation.
This change does not incur any significant change in compiled firmware size.
=> Lighting Layers should be disabled when suspended

tmk_core/common/report.h, tmk_core/protocol/vusb/vusb.c, tmk_core/protocol/vusb/vusb.h
Basically just a rename of the mouse/extra interface to shared, and implementing `KEYBOARD_SHARED_EP`.
Tested on Plaid-Pad, but a more thorough typing test might be useful.
*
=> Add support for shared EP on V-USB boards

shell.nix
For me, on macOS 10.15.7 running `make` would fail with errors about -iframework. This change fixes it. I assume that the name of the flag has been changed.
I haven't checked this change on a linux platform. Would appreciate if somebody did.
*
=> Fix Nix macOS build

quantum/split_common/matrix.c, tmk_core/common/keyboard.c, tmk_core/common/keyboard.h
This PR adds support for recording the last time matrix activity was detected.
Two new APIs have been added:
```c
uint32_t last_matrix_activity_time(void);     // Timestamp of the last matrix activity
uint32_t last_matrix_activity_elapsed(void);  // Number of milliseconds since the last matrix activity
```
These values are compatible with normal matrix scanning, as well as split_common.
=> Keep track of last matrix activity

keyboards/moonlander/matrix.c
`printf` in the moonlander's matrix errors out if you disable the console. Fixed.
=> [Keyboard] Fix printf calls in Moonlander matrix

quantum/matrix.c, quantum/matrix_common.c, quantum/quantum.h, quantum/split_common/matrix.c, tmk_core/common/matrix.h, tmk_core/common/wait.h
~~The timing of the call to matrix_io_delay() has been changed to the appropriate time.  With this change, we can reduce the number of times we call matrix_io_delay() by one.~~
**Separated `matrix_io_delay()` into the following two functions so that you can set the appropriate delay value for each.**
* `matrix_output_select_delay()` -  after `select_row()/select_col()`
The delay is a small number of clocks specific to the MCU.  
The default implementation is as follows:
```c
__attribute__((weak)) void matrix_output_select_delay(void) { waitInputPinDelay(); }
```
See below for more information on `waitInputPinDelay()`.
* `matrix_output_unselect_delay()` - after `unselect_row()/unselect_col()`
The delay is in the range of a few microseconds, depending on the capacitance and resistance of …
=> fix matrix_io_delay() timing in quantum/matrix.c

quantum/keymap_extras/keymap_fr_ch.h
Thanks to @ra-astons for reporting.
* Fixes #11530
=> keymap_fr_ch: undef `CH_H`

build_keyboard.mk
Fixes the import order so that keyboard-level vars don't overwrite userspace.
=> Process info.json rules ahead of userspace rules

keyboards/boardrun/bizarre/info.json, keyboards/boardrun/classic/info.json, keyboards/ergodox_ez/info.json, keyboards/ergotravel/info.json, keyboards/handwired/evk/info.json, keyboards/handwired/freoduo/info.json, keyboards/kiwikey/kawii9/info.json, keyboards/moonlander/info.json, keyboards/nopunin10did/railroad/rev0/info.json, keyboards/nullbitsco/info.json, keyboards/phoenix/info.json, keyboards/ploopyco/mouse/info.json, keyboards/ploopyco/trackball/info.json, keyboards/qwertyydox/info.json, keyboards/tkw/stoutgat/v2/info.json, keyboards/xd87/info.json
Now that the integration between info.json and config.h is tighter we should define these variables in only one place. I chose to leave this in `config.h` under the principle of least surprise.
=> Remove duplicate manufacturer definitions

keyboards/ymdk/ymd09/keymaps/andys8/keymap.c
Custom layout for macropad. It shows the usage of macros with unicode, and other layouts (ISO-DE) with unicode, emojis, and git commands.
=> [Keymap] Adds ymdk/ymd09 andys8 layout

docs/ws2812_driver.md, drivers/chibios/ws2812.c, drivers/chibios/ws2812_pwm.c, drivers/chibios/ws2812_spi.c, quantum/color.h
Some custom keyboard PCBs (the MatrixLabs ones for example) have RGB strip modules that use standard RGB LEDs with a WS2812 compatible controller (TM1812 in most cases).
Unfortunately some of these PCBs have the LEDs wired up in reverse which requires the byte order to be in reverse as well for the colors to be correct.
In normal QMK it's not really noticable but when setting the color in a GUI tool like VIA it can be confusing because the wrong colors light up on the board.
I added a new byte order for this to the WS2812 drivers with reversed byte order (BGR).
=> Add BGR byte order for WS2812 drivers

docs/cli_commands.md, lib/python/qmk/cli/chibios/confmigrate.py, lib/python/qmk/cli/compile.py, lib/python/qmk/cli/flash.py, lib/python/qmk/commands.py, lib/python/qmk/constants.py
This adds two new features to `qmk compile` and `qmk flash`, as well as enhancing JSON keymaps so they don't pollute the tree:
* `--clean` flag: remove the build directory for a keyboard before compiling
* `--env` flag: pass environment variables down to make
* JSON keymaps no longer write to the keymaps directory, but instead write into the `$(KEYMAP_OUTPUT)/src` directory.
* Make flake8 happy with unrelated files
=> Improve the compile and flash subcommands

quantum/quantum.c, quantum/quantum.h, quantum/rgblight.c, quantum/split_common/matrix.c, quantum/split_common/transport.c, tmk_core/common/avr/bootloader.c, tmk_core/common/mousekey.c, tmk_core/common/mousekey.h, tmk_core/common/wait.h
Execution of `qmk cformat` against `develop`.
=> `qmk cformat`

keyboards/ebastler/isometria_75/rev1/chconf.h, keyboards/ebastler/isometria_75/rev1/halconf.h, keyboards/hp69/rules.mk
Fixes failing builds on develop after the change to the default set of enabled ChibiOS peripherals.
=> Fixup builds on develop branch.

layouts/community/ortho_4x12/peej/keymap.c, layouts/community/ortho_5x12/peej/keymap.c, layouts/community/ortho_5x14/peej/keymap.c, users/peej/layout.h, users/peej/peej.c, users/peej/peej.h, users/peej/rules.mk
Add personal userspace functions and keymaps for boardwalk, lets split, plaid, and planck keyboards.
=> [Keymap] Add peej userspace and keymaps

keyboards/ploopyco/opt_encoder.c, keyboards/ploopyco/opt_encoder.h
Mark the variables used by the optical encoder as extern, resolving the errors of 'multiple definition of `x`'
```/usr/bin/avr-ld: .build/obj_ploopyco_trackball_rev1_005_drag_scroll/keyboards/ploopyco/trackball/keymaps/drag_scroll/keymap.o:/qmk_firmware/keyboards/ploopyco/opt_encoder.h:31: multiple definition of `state'; .build/obj_ploopyco_trackball_rev1_005_drag_scroll/opt_encoder.o:/qmk_firmware/keyboards/ploopyco/opt_encoder.h:31: first defined here```
* Similar to #9268 - Default keymap for Ploopy does not compile with GCC10
=> GCC 10 compatibility for Ploopy optical encoder

keyboards/chavdai40/rev1/config.h, keyboards/chavdai40/rev2/config.h, keyboards/ergodox_stm32/boards/ERGODOX_STM32_BOARD/board.c, keyboards/ergodox_stm32/ergodox_stm32.c, keyboards/jm60/boards/JM60_BOARD/board.c, keyboards/jm60/jm60.c, keyboards/matrix/m20add/boards/m20add_bd/board.c, keyboards/matrix/m20add/config.h, keyboards/matrix/noah/boards/noah_bd/board.c, keyboards/matrix/noah/config.h, keyboards/polilla/rev1/config.h, keyboards/xiaomi/mk02/config.h, platforms/chibios/GENERIC_STM32_F042X6/board/board.c
This brings the last batch of stragglers over to use the early initialisation code.
=> Leftover early initialisation conversions

platforms/chibios/QMK_PROTON_C/configs/chconf.h, platforms/chibios/QMK_PROTON_C/configs/halconf.h, platforms/chibios/common/configs/chconf.h, platforms/chibios/common/configs/halconf.h
The long-awaited upgrade to ChibiOS 20.3.2.
```
-------------------------------
Successful builds: 121
Warning builds: 21
Failing builds: 0
-------------------------------
```
=> ChibiOS 20.3.2

tmk_core/common/chibios/syscall-fallbacks.c
Just some "proper" handling of `errno`, as well as adding a few more syscalls that were originally missed.
Rationale for all the `errno` handling is that these are the base functions invoked by newlib -- user-code never invokes these directly and it's likely we need to act "proper" in order for the assumptions newlib have made in the C library to correctly function.
=> Fixup declaration for _kill, add other missing syscalls, populate errno.

tmk_core/chibios.mk
With #11573, this could be worth another try... maybe (#9044 for the previous iteration).
=> Switch to nano specs on ChibiOS builds - Round 2

quantum/process_keycode/process_music.c
When "Music Map" is used with MAJOR_MODE, key(music) rolls back 5th lower at each position of multiple of 12 in music_map.
When positions are set in music_map as below :
```
0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14 ...
```
Expected keys :
```
C0, D0, E0, F0, G0, A0, B0, C1, D1, E1, F1, G1, A1, B1, C2 ...
```
Actual keys (BUG):
```
C0, D0, E0, F0, G0, A0, B0, C1, D1, E1, F1, G1, C1, D1, E1 ...
```
At position 12, key rolls back 5th lower, A1 --> C1.  
This happens at each position of multiple of 12. (12, 24, 36 ...)
With MAJOR_MODE (= major scale), keys in one octave is not 12 but 7.  
So, change divisor number from 12 to 7 at %(Modulo) and /(Division) to solve this issue.
- [ x ] Core
- [ x ] Bugfix
* none
- [ x ] My code follows the code style of this project: …
=> Fix wrong key(music), when "Music Map" is used with MAJOR_MODE.

docs/feature_rgblight.md
Improves the Lighting Layers example in the RGB Lighting documentation to address a commonly asked question using lighting layers to indicate default layer selection.
=> Improve the Lighting Layers example in the RGB Lighting documentation

bootloader.mk, docs/flashing.md
Part 1, adding the options. Parts 2-?? will be to set `BOOTLOADER` for all applicable STM32 boards, and remove the dfu-util args from mcu_selection.mk.
*
=> Add stm32-dfu and apm32-dfu to bootloader.mk

docs/README.md, docs/_summary.md, docs/faq_debug.md, docs/faq_misc.md, docs/newbs.md, docs/newbs_building_firmware_configurator.md, docs/newbs_flashing.md, docs/newbs_getting_started.md, docs/newbs_learn_more_resources.md, docs/newbs_testing_debugging.md, docs/qmk_custom_dark.css, docs/qmk_custom_light.css
Summary of the changes,
* Split out newbs testing_debugging to faq pages
* Reason being generally new starters are not going to start with hid_listen type stuff
*  Strip down the wording of some setup sections
* Mostly round the "download software" section so users can see the good stuff a little easier
* Call out various sections with a pop of colour to draw users to the key parts of the page
*
=> Small tweaks to docs to make them more user friendly

quantum/encoder.c, quantum/encoder.h, tmk_core/common/keyboard.c, tmk_core/common/keyboard.h
Addition to the "last matrix activity" PR, this time around it keeps track of encoder activity too.
Adds four new APIs:
```c
uint32_t last_input_activity_time(void);     // Timestamp of the last matrix or encoder activity
uint32_t last_input_activity_elapsed(void);  // Number of milliseconds since the last matrix or encoder activity
uint32_t last_encoder_activity_time(void);     // Timestamp of the last encoder activity
uint32_t last_encoder_activity_elapsed(void);  // Number of milliseconds since the last encoder activity
```
Tested on the Djinn rev1.
=> Keep track of encoder activity

keyboards/leafcutterlabs/bigknob/keymaps/default/rules.mk
Removes an unneeded compile rule from the leafcutterlabs/bigknob:default keymap. The tap dance function was enabled biut never used or set up in the keymap, causing builds to fail
*
=> Fix unused rule in leafcutterlabs/bigknob:default causing builds to fail

tmk_core/protocol/arm_atsam/main_arm_atsam.c
Patch for https://github.com/qmk/qmk_firmware/pull/10530#discussion_r549612205
None
=> Remove duplicated housekeeping call from `arm_atsam`

keyboards/crkbd/config.h, keyboards/crkbd/rev1/common/config.h, keyboards/crkbd/rev1/legacy/config.h
By simplifing the PRODUCT string of the CRKBD, I've fixed issues I had with MIDI on this keyboard. I can't really explain why as I'm not an expert. If anyone have an explanation, I would love to have it, but for now, I want to share with you my fix if anyone needs it. If you want to test it, use the keycode `MI_C_1` in one of your keys and test with MIDI-OX or any DAW that your keyboard is correctly recognized as a MIDI input.
*
=> Fix midi for CRKBD

keyboards/torn/rules.mk
Fixes the torn keyboard to allow using layouts.
=> Add community layout support to torn keyboard

keyboards/boardsource/the_mark/config.h, keyboards/boardsource/the_mark/rules.mk, keyboards/boardsource/the_mark/the_mark.c
Add physical under glow LED light mapping to support RGB matrix features.
*
=> Add RGB Matrix support for The Mark:65 keyboard

keyboards/program_yoink/ortho/keymaps/ortho_split/keymap.c
Revise ortho split bar default keymap to swap `slash` and  `up`
*
=> [Keymap] Update Program Yoink Ortho Split Layout

keyboards/evyd13/pockettype/pockettype.c
The LED anodes of the pockettype are connected to the bus voltage when a pro micro is used, but other controllers like the Elite-C connect this pin to GPIO B0. This means that LEDs do not work by default for those controllers.
After consulting with the maintainer @evyd13, a fix was implemented that simply writes the B0 pin high.
=> Fix for LEDs on PocketType

data/schemas/keyboard.jsonschema
Mirroring checked values between python and jsonschema.
=> Update list of MCUs in keyboard.jsonschema to mirror qmk.constants.py

quantum/audio/audio_chibios.c, quantum/audio/musical_notes.h
Should disable the pins for audio when not in use (playing notes).  Added due to issues found with the Planck EZ.  
* Issues found on planck ez.
=> Backport ChibiOS Audio changes from ZSA

common_features.mk, tmk_core/common/keyboard.c, tmk_core/common/keyboard.h
Added `get_matrix_scan_rate ()` to make it easier for keymap level code to get the matrix scan rate.
Example:
```diff
diff --git a/keyboards/helix/rev2/keymaps/five_rows/oled_display.c b/keyboards/helix/rev2/keymaps/five_rows/oled_display.c
index 689efe4c8..ff2f05e29 100644
--- a/keyboards/helix/rev2/keymaps/five_rows/oled_display.c
+++ b/keyboards/helix/rev2/keymaps/five_rows/oled_display.c
@@ -142,6 +142,11 @@ void render_status(void) {
int name_num;
uint32_t lstate;
oled_write_P(layer_names[current_default_layer], false);
+#ifdef DEBUG_MATRIX_SCAN_RATE
+    char num[10];
+    snprintf(num, sizeof(num), " %ld ", get_matrix_scan_rate());
+    oled_write(num, false);
+#endif
oled_write_P(PSTR("\n"), false);
for (lstate = layer_state, name_num = 0;
lstate && name_num < …
```
=> add get_matrix_scan_rate() to tmk_core/common/keyboard.c

docs/feature_rgblight.md, quantum/rgblight.c, quantum/rgblight.h
Add `rgblight_reload_from_eeprom()` to allow a way to atomically reset the rgblight settings back to those which are currently stored in EEPROM. This is helpful when coding startup and acknowledgement animations, to restore the user's desired effects settings after the animation has completed. 
While it is possible at present to do this by storing local copies of the state before the animation started, there is no way to restore that state without ugly flashes of light, because there is no way to atomically set enabled/enabled, hsv, and effect mode. Note that `rgblight_mode_noeeprom()` and `rgblight_sethsv_noeeprom()` are both no-ops when rgblight is not enabled.
=> Add rgblight_reload_from_eeprom()

build_keyboard.mk
Allow `post_config.h` to be defined in userspace directories.
At present, we pay attention to it in keyboard and keymap directories, but not in the userspace.
=> Allow post_config.h to be implemented in userspace

quantum/debounce/sym_defer_pk.c, quantum/debounce/sym_eager_pk.c, quantum/debounce/sym_eager_pr.c
Using one of the alternate debounce algorithms requires a memory allocator.
ChibiOS allows you to disable said memory allocator.
This puts some compile-time checks to enforce that the allocator has been enabled -- during testing with it set to FALSE, the keyboard would run and function correctly from a visible standpoint, but no keypresses would register. The fun part was, if the slave side had a firmware that had an allocator enabled, the master would still report keypresses on the slave, but not itself!
=> Enforce memory allocator for ChibiOS builds with allocating debounce algorithms

drivers/avr/uart.h
Include stdbool.h in uart.h to fix compiler errors. 
* Travis CI errors
=> Include stdbool.h in uart.h

keyboards/aos/tkl/keymaps/default/keymap.c, keyboards/aos/tkl/keymaps/via/keymap.c
While working on another board I noticed the `default` and `via` maps for the AoS TKL had a missing F2 in the top row where I'd typo'd F1 by mistake.
Very minor typo fix in two keymaps for the Ace of Spades TKL.
=> Fix missing F2 in top row in AoS TKL maps

tmk_core/protocol/chibios/main.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/chibios/usb_main.h
Struck a bit of an issue when using backlight and an external EEPROM -- the backlight handler issues a read which can eventually trigger a thread suspension.... the problem is, this is done from within an interrupt handler:
Attempting a thread suspension triggers an unhandled exception and the MCU subsequently locks up.
This PR pushes the event handling to the main keyboard loop.
=> ChibiOS: Decouple USB events from the USB interrupt handler

quantum/audio/audio.h, quantum/audio/audio_avr.c, quantum/audio/audio_chibios.c, quantum/audio/audio_pwm.c, quantum/quantum.c, tmk_core/common/avr/suspend.c, tmk_core/common/chibios/suspend.c
The code to stop sounds when suspending was commented out long ago, because it interfered with the startup sound working correctly. The problem was that at the time of `audio_init()` the USB device status might still be in flux, passing through the Suspended state, which would call `stop_all_notes()`.
The solution is to move the playing of the startup song into a routine that is run 300ms after startup, giving enough time for the USB state to settle.
Note: This has been tested thoroughly on AVR. I have provided code for ARM, but it is not as well tested. I understand that the state of audio on ARM is limited to Proton-C; I'd appreciate if someone with that architecture could test this before it is merged.
Fixes #8167
=> Stop sounds when suspended

common_features.mk, keyboards/handwired/dactyl_manuform/5x6_right_trackball/rules.mk
LTO can cause issues for the transport, and cause sync issues, especially if there is a lot of data.  
* Issues with LTO being enabled and sync issues on split.
=> Move transport.c to QUANTUM_LIB_SRC

keyboards/ergosaurus/config.h
The correct breakout pin used for RGB underglow is B6, not E2 (which seems to have been overlooked when generating the firmware).
* N/A
=> Fix Ergosaurus default RGB_DI_PIN

docs/config_options.md, tmk_core/common/avr/suspend.c, tmk_core/common/suspend.h, tmk_core/protocol/chibios/main.c, tmk_core/protocol/chibios/usb_main.c, tmk_core/protocol/lufa/lufa.c
My work-from-home setup is a complicated mess of KVM switches, USB hubs, etc. Sleep / wake works fine when the keyboard is plugged directly into the computer, but through the switches / hubs it becomes unreliable, with the keyboard hanging sometimes on wake, or lighting being wrong after wakeup. Other people have reported similar experiences, especially when using KVM switches or when using pass-through USB on a USB-C or HDMI connected monitor.
Debugging showed that when a key is tapped to wake the board / host, if it goes through the switch, instead of USB device state going smoothly from Suspended to Configured, it goes back and forth a few times before settling on Configured.  When that happens, sometimes, the keyboard hangs. Other times the host just doesn't stay awake.
After spending …
=> Address wake from sleep instability

tmk_core/common/keyboard.c
Fixes compiler issues when enabling this on chibiOS boards. 
```
Compiling: tmk_core/common/keyboard.c                                                              In file included from quantum/keymap.h:34,
from tmk_core/common/keyboard.c:21:
tmk_core/common/keyboard.c: In function 'matrix_scan_perf_task':
tmk_core/common/keyboard.c:118:17: error: format '%d' expects argument of type 'int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
dprintf("matrix scan frequency: %d\n", matrix_scan_count);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~
tmk_core/common/debug.h:68:39: note: in definition of macro 'dprintf'
if (debug_enable) xprintf(fmt, ##__VA_ARGS__); \
```
=> Fix DEBUG_MATRIX_SCAN_RATE on chibiOS when console is enabled

keyboards/afternoonlabs/breeze/keymaps/default/keymap.c
To match the default keymap in configurator, and to fix a bug where the layer keys would conflict, reordering layer modifiers.
*
=> Fixing layer order for Breeze default keymap

keyboards/kbdfans/kbdpad_mk2/config.h
The LED indicator on the KBDfans KBDPAD MKII is incorrectly tied to the caps lock state instead of num lock. This change fixes that.
* Fixes #11780
=> Use num lock instead of caps lock for KBDPAD MKII LED

docs/feature_pointing_device.md, quantum/pointing_device.c, quantum/pointing_device.h
Expands the `pointing_device_send()` function to be more robust. 
Specifically, it's not a good idea to always send the mouse report to the host system, as this is considered activity, and may/will keep the system awake.  So reports should only be sent when there is an update.  
Additionally, after #10179, it became apparent that any changes that happened and weren't immediately sent and you manually checked for activity (such as with the ploopyco code), the reports could get "stuck".  As such, this moves the logic to the send function, so that it's better able to check.
=> Improve Pointing Device report sending

data/schemas/keyboard.jsonschema, docs/compatible_microcontrollers.md, docs/ja/compatible_microcontrollers.md, lib/python/qmk/constants.py, platforms/chibios/GENERIC_STM32_G431XB/board/board.mk, platforms/chibios/GENERIC_STM32_G431XB/configs/config.h, platforms/chibios/GENERIC_STM32_G431XB/configs/mcuconf.h, platforms/chibios/GENERIC_STM32_G474XE/board/board.mk, platforms/chibios/GENERIC_STM32_G474XE/configs/config.h, platforms/chibios/GENERIC_STM32_G474XE/configs/mcuconf.h, quantum/mcu_selection.mk
Adds default board configurations for:
* `MCU = STM32G431`
* `MCU = STM32G474`
Added documentation changes to state that F401, F411, G431, G474 are also supported.
=> Add STM32G431 and STM32G474 board definitions.

tmk_core/common/action.c
[Bug] Pressing media key on a momentarily activated layer may leads to missing key up events.
* fixes #11161
=> [Bug] Fix media key missing upstroke event

keyboards/earth_rover/config.h, keyboards/earth_rover/earth_rover.c, keyboards/earth_rover/earth_rover.h, keyboards/earth_rover/info.json, keyboards/earth_rover/keymaps/default/keymap.c, keyboards/earth_rover/keymaps/default/readme.md, keyboards/earth_rover/readme.md, keyboards/earth_rover/rules.mk
Add new keyboard [earth_rover](https://github.com/bigwheel/earth_rover).
=> [Keyboard] Add earth_rover keyboard

lib/python/qmk/cli/compile.py, lib/python/qmk/cli/flash.py, lib/python/qmk/cli/json2c.py, lib/python/qmk/path.py
Common issue that gets reported in the Discord, where the initial `cd qmk_firmware` within cli changes the assumption of where the relative path is to.
=> Allow flash/compile to accept relative json paths

keyboards/xelus/trinityxttkl/rules.mk
Allows for usage of APM32. Since there are two variants, one with STM32 and one with APM32.
* Allow APM32 MCU
=> [Update] Allow APM32 on TrinityXTtkl

drivers/avr/ws2812.c
When trying to calculate the number of nops for AVR running at 8 MHz, the value of `w3` is expected to be negative; however, because `F_CPU` is defined in tmk_core/avr.mk with the `UL` suffix, the preprocessor performs its calculations using `unsigned long`, getting a very large positive number instead of the expected negative number; this then results in generating code with a huge number of nops.  Fix the broken calculations by performing a comparison before subtraction, so that the unsigned number wraparound does not occur.
The keyboard which triggers the problem is `handwired/promethium`; the buggy code silently compiles, but the resulting timings would be wrong (but apparently not wrong enough to be noticed, because for most WS8212-like LEDs a low level pulse of 6 us is not enough to …
=> ws2812: Fix number of nops for AVR at 8 MHz

keyboards/playkbtw/helen80/helen80.h
Fix matrix macro mapping in Helen 80.
Fix macro expand of `LAYOUT_tkl_ansi` in Helen 80
*
=> fix Helen 80 matrix mapping

keyboards/boardsource/the_mark/keymaps/stanrc85/keymap.c, keyboards/boardsource/the_mark/keymaps/stanrc85/rules.mk, layouts/community/60_ansi/stanrc85-ansi/readme.md, layouts/community/alice/stanrc85-alice/readme.md, users/stanrc85/config.h, users/stanrc85/readme.md, users/stanrc85/rules.mk, users/stanrc85/stanrc85.c
Overdue userspace updates
* Userspace Readme updated
* Community layout readme update
* Layout images updated
* Enable NKRO, VIA, LTO by default
* Add -j to compile/flash commands for faster compiling 
*
=> Userspace updates

keyboards/hidtech/bastyl/keymaps/german_gaming/keymap.c, keyboards/hidtech/bastyl/keymaps/german_gaming/readme.md, keyboards/hidtech/bastyl/keymaps/german_gaming/rules.mk
Added a german gaming keymap for @HID-Technologies' Bastyl. 
`MOUSEKEY_ENABLE` was set to `no` for this keymap, since I'm not using it, and IIRC the size of the firmware ended up being too large.
=> Added german_gaming keymap for hidtech/bastyl

keyboards/quark/keymaps/pezhore/config.h, keyboards/quark/keymaps/pezhore/keymap.c
Similar to my keymap for the Preonic, this brings a custom keymap to the Quark board. Of note, I've made the `Fn` layer's bottom row the number row - while waiting for more keycaps I salvaged what I could from a Filco keyboard and liked being able to see which keys were the numbers/special character keys (bonus points for the angle of the normally top row keys fitting nicely with my thumbs).
=> Adding custom keymap for Quark keyboard

docs/ref_functions.md
I added a link to the EEP_RST keycode in the "Wiping the EEPROM" section. I wanted to link to this section while helping a customer but it didn't have the information I wanted to convey to them.
* N/A
=> Add EEP_RST keycode to "Wiping the EEPROM" section

quantum/via.c
Entry to bootloader through the rawhid endpoint is a potential attack vector. This PR disables those commands by default, turning them into no-ops, but allows reinstating them through the use of `#define VIA_YES_I_UNDERSTAND_THIS_IS_AN_ATTACK_VECTOR`.
=> Disable VIA protocol's EEPROM reset and bootloader jump commands

keyboards/durgod/k320/k320.h, keyboards/durgod/k320/keymaps/default/keymap.c, keyboards/durgod/k320/keymaps/default_toggle_mac_windows/keymap.c, keyboards/durgod/k320/keymaps/kuenhlee/keymap.c
As noted in Issue #11883 and in the comments on PR #11778, the Durgod k320 `LAYOUT_tkl_ansi` macro does not match the physical keyboard layout, or the layout recorded in info.json, resulting in garbled unusable key mappings when using the QMK configurator. The unusually organized layout macro also makes it very hard to write a manual keyboard layout since the keys in the layout macro are not in an order that one can make sense of.
This PR updates the layout to be aligned with the physical keyboard and with the info.json.
Kudos to @baruch for noticing the problem and raising the issue, including a proposed updated `LAYOUT_tkl_ansi` macro. 
Notes:
* I have verified that this compiles, but I do not have a Durgod k320 with which to test the code. I would appreciate if someone who has that …
=> unscramble Durgod k320 keymap / fix Issue #11883

keyboards/ploopyco/mouse/keymaps/drag_scroll/keymap.c, keyboards/ploopyco/mouse/keymaps/via/keymap.c, keyboards/ploopyco/mouse/mouse.c, keyboards/ploopyco/mouse/mouse.h, keyboards/ploopyco/mouse/rules.mk, keyboards/ploopyco/trackball/keymaps/drag_scroll/keymap.c, keyboards/ploopyco/trackball/rev1/readme.md, keyboards/ploopyco/trackball/rules.mk, keyboards/ploopyco/trackball/trackball.c, keyboards/ploopyco/trackball/trackball.h
- Updates the devices to use the completely undocumented User keycodes for VIA. 
- Additionally, moves the drag scoll keycode into the keyboard code. 
- Enables mousekeys, so that LT/MT will work with mouse buttons.
=> [Keyboard] PloopyCo VIA updates

docs/feature_split_keyboard.md, docs/ja/understanding_qmk.md, docs/understanding_qmk.md, quantum/quantum.c, quantum/rgb_matrix.c, quantum/rgb_matrix.h, quantum/rgb_matrix_animations/typing_heatmap_anim.h, quantum/split_common/matrix.c, quantum/split_common/transport.c, quantum/split_common/transport.h, tmk_core/common/eeconfig.h, tmk_core/common/keyboard.c
Added a define option for split keyboards to transport the master matrix to the slave side. This allows systems (such as rgb matrix's key reactive animations) to be processed on the slave side instead of the master side, or mirrored in the case of the up coming split rgb matrix split support.
*
=> Split transport mirror

docs/tap_hold.md
Current wording of IGNORE_MOD_TAP_INTERRUPT is incorrect, and very confusing when attempting to correct a somewhat common issue for quick typists that have Mod-Tap on a commonly used key.  Research indicates this wording has been incorrect for some time, and has tripped up others attempting to solve the issue of Mod + Key being sent, when Tap + Key is expected after quickly pressing keys.
Update IGNORE_MOD_TAP_INTERRUPT documentation for clarity and correctness.
*
=> Update IGNORE_MOD_TAP_INTERRUPT documentation

docs/feature_rgblight.md, quantum/rgblight.c
=> RGBLight: Allow configurable default settings

lib/python/qmk/cli/doctor.py
The initialization of the submodules would succeed, but the result of the subsequent
check_submodules() run wasn't checked correctly.
When bootstrapping a `qmk_firmware` repository, according to the documentation, there is an issue when calling `qmk setup`. That is, `qmk` is being installed via `pip`, not the one under `bin/qmk`. According to the docs.
Anyhow, the setup process asks to initialize the git submodules for the user, which it does on confirmation, but the check fails with a `Not an iteratable`-Error. I deem the problem fixed by this PR, but 1. I don't code python usually, 2. I only invested the minimum time.
I'm still confused why there is a `bin/qmk` but it doesn't have `setup`, yet the one installed via `pip install` still uses the local libraries in `lib/python`. Well. I …
=> Fix submodule check for qmk setup

docs/feature_macros.md, tmk_core/common/action.c, tmk_core/common/action.h
Could be useful for encoders, if you don't want to define `TAP_CODE_DELAY` across the board.
*
=> Add `tap_code_delay(code, delay)`

tmk_core/common/action.c
#11913
On AVR, the parameter to `_delay_ms()` must be a compile-time constant, so we cannot directly pass in the `delay` argument here.
*
=> Fix compilation error for `tap_code_delay()`

keyboards/durgod/k320/readme.md
Fix for typos in durgod/k320 readme
*
=> Fixing typos in durgod/k320 readme

keyboards/handwired/xealousbrown/info.json, keyboards/handwired/xealousbrown/keymaps/default/keymap.c, keyboards/handwired/xealousbrown/readme.md, keyboards/handwired/xealousbrown/rules.mk, keyboards/handwired/xealousbrown/xealousbrown.c, keyboards/handwired/xealousbrown/xealousbrown.h
A long-overdue refactor of @alex-ong's handwired 60%.
Reference: https://github.com/qmk/qmk_firmware/pull/8215#issuecomment-617011359
@alex-ong, please note that the layout macro name changes from `LAYOUT` to `LAYOUT_60_ansi` with this pull request.
=> Xealous Brown handwired Refactor

keyboards/4pplet/aekiso60/keymaps/via/rules.mk, keyboards/4pplet/steezy60/keymaps/via/rules.mk
Setting rgb underglow enabled by default for VIA firmware
Setting rgb underglow enabled by default for VIA firmware
No rgb underglow function in precompiled via hex.
=> enable rgb underglow for VIA-firmware
